# Antiarrhythmic Pharmacology (Scully) — Version 2, 18 items (4 with images): class III, class IV, adenosine, digoxin, atropine, the hockey case
Q = [
dict(img='Aaamiocxr', cap='Chest x-ray',
stem="A 71-year-old man has taken an oral antiarrhythmic for 3 years to prevent recurrent ventricular tachycardia. Over 4 months he has developed a progressive dry cough and dyspnea on exertion. He also burns easily in the sun. Bibasilar crackles are heard, and his chest x-ray is shown.{FIG}Which of the following drugs is most likely responsible?",
choices=["Amiodarone","Sotalol","Dofetilide","Flecainide","Procainamide"], key=0,
exp="The x-ray shows bilateral reticular (interstitial) opacities, i.e. <b>pulmonary fibrosis</b> after long-term antiarrhythmic use, plus <b>photosensitivity</b>. That's <b>amiodarone</b>. \"Very likely you will see amiodarone.\" Organ toxicities (slide 31):<br>• Lung: pneumonitis → fibrosis (baseline + annual PFTs)<br>• Thyroid: hypo- or hyperthyroidism (TFTs)<br>• Liver: elevated enzymes (LFTs)<br>• Eye: corneal microdeposits<br>• Skin: photosensitivity, blue-gray discoloration<br>• Nerves: peripheral neuropathy, tremor, ataxia<br>• Heart: bradycardia, AV block, hypotension<br>The cardiac effects can follow a single dose. The organ toxicities come with long-term use.<br><br><b>Educational objective:</b> Long-term amiodarone causes pulmonary fibrosis (plus thyroid, liver, eye and skin toxicity), so it needs baseline and annual monitoring.",
wrong={1:"Sotalol's adverse effects are β-blocker effects plus torsades, not lung fibrosis.",
2:"Dofetilide's main risk is QT prolongation and torsades.",
3:"Flecainide causes pro-arrhythmia, blurred vision and ataxia.",
4:"Procainamide causes drug-induced lupus, which can give pleuritis but not progressive fibrosis or photosensitivity."},
eli5="Amiodarone builds up in the body over years and can scar the lungs, which shows up as a dry cough and a cloudy, net-like chest x-ray."),

dict(img='Aacornea', cap='Slit-lamp photograph at a routine eye examination',
stem="A 64-year-old woman has taken a drug for 2 years to prevent recurrent paroxysmal atrial fibrillation. A routine eye examination finds the deposits shown; her visual acuity is normal and she has no symptoms.{FIG}In addition to regular eye examinations, which of the following should be checked at baseline and yearly?",
choices=["Thyroid and pulmonary function tests","Serum digoxin and magnesium levels","Creatine kinase and urine myoglobin","Antinuclear and antihistone antibodies","Fasting glucose and hemoglobin A1c"], key=0,
exp="Whorl-like <b>corneal microdeposits</b> are typical of <b>amiodarone</b>. They are usually harmless and often found at a routine eye exam, as here. The lecture's monitoring plan for long-term amiodarone: <b>baseline and annual pulmonary function tests</b> (fibrosis), <b>baseline and annual thyroid function tests</b> (hypo- or hyperthyroidism), liver enzymes, regular eye exams, and an ECG for nodal effects. History: amiodarone was once used for everything and then dropped as toxicities emerged. It is back \"on every algorithm\" now that monitoring is understood. Its off-label uses include preventing recurrent paroxysmal AF/flutter.<br><br><b>Educational objective:</b> Amiodarone needs baseline and annual thyroid and pulmonary function tests, plus liver enzymes and eye exams.",
wrong={1:"Digoxin levels matter for digoxin, not as routine amiodarone monitoring (though amiodarone does raise digoxin levels).",
2:"Creatine kinase monitoring is for statin myopathy.",
3:"Antihistone antibodies relate to procainamide (and hydralazine) lupus.",
4:"Glucose monitoring isn't part of amiodarone surveillance."},
eli5="This drug leaves harmless swirls in the eye, but it can also damage the thyroid and lungs, so those get checked every year."),

dict(img=None,
stem="A 66-year-old man with heart failure with reduced ejection fraction (ejection fraction 30%) has persistent atrial fibrillation. His cardiologist wants an oral drug that can both convert him to sinus rhythm and keep him there, without depressing contractility. His creatinine clearance is 55 mL/min.{FIG}Which of the following is the most appropriate drug?",
choices=["Dofetilide","Ibutilide","Flecainide","Verapamil","Disopyramide"], key=0,
exp="<b>Dofetilide</b> (class III, oral) blocks the rapid delayed-rectifier K⁺ current (I<sub>Kr</sub>). Indications: <b>conversion of AF/flutter and maintenance of sinus rhythm afterward</b>. That second part is what sets it apart from ibutilide. It has <b>no negative inotropy</b>, so it's acceptable with a depressed ejection fraction. It is <b>renally excreted, so the dose is set by creatinine clearance</b>. Torsades risk is 1–3%, so it is started in hospital.<br><br><b>Educational objective:</b> Dofetilide converts and maintains sinus rhythm, is safe with a low ejection fraction, and is dosed by creatinine clearance.",
wrong={1:"Ibutilide is IV and only <b>terminates</b> AF/flutter. It doesn't maintain sinus rhythm.",
2:"Flecainide (IC) is pro-arrhythmic with structural heart disease. It's only for a normal heart.",
3:"Verapamil is a rate drug, and its negative inotropy worsens HFrEF.",
4:"Disopyramide is negatively inotropic and can worsen heart failure."},
eli5="Dofetilide can reset the rhythm and then keep it steady, and it doesn't weaken the heart's squeeze. Because the kidneys clear it, the dose is matched to kidney function."),

dict(img=None,
stem="A 78-year-old woman is admitted to start dofetilide for atrial fibrillation. Her serum potassium and magnesium are normal. Her creatinine has risen since her last visit, but the full standard dose is ordered. On day 2 she has polymorphic ventricular tachycardia with a QTc of 560 ms.{FIG}Which of the following most likely contributed?",
choices=["Dose not reduced for low creatinine clearance","Its negative inotropic effect on the ventricle","Induction of its hepatic metabolism","Blockade of L-type Ca²⁺ channels","Hyperkalemia from potassium supplements"], key=0,
exp="<b>Class III</b> drugs block repolarizing K⁺ currents → longer plateau → longer QT → <b>torsades</b>. Ibutilide ≈2%, dofetilide 1–3%: \"that's 2 in 100 people\", which is why these drugs are <b>started in hospital with ECG monitoring</b>. Dofetilide is <b>renally excreted and dosed by creatinine clearance</b>. A full dose in worsening kidney function raises its level, lengthens the QT and causes torsades. Contraindications: other QT-prolonging drugs, congenital long QT, and class I or III drugs together. Treatment of torsades: IV magnesium (board add-on).<br><br><b>Educational objective:</b> Dofetilide is renally cleared and causes torsades in a dose-dependent way. Dose by creatinine clearance and start in hospital with QT monitoring.",
wrong={1:"Dofetilide has <b>no</b> negative inotropic effect.",
2:"Dofetilide is mainly renally cleared, and hepatic induction would <b>lower</b> its level.",
3:"Dofetilide blocks I<sub>Kr</sub> (K⁺), not Ca²⁺ channels.",
4:"Her potassium is normal, and hyperkalemia doesn't prolong the QT."},
eli5="Her kidneys were clearing the drug more slowly, so it built up and stretched the heart's reset time too far, which set off torsades."),

dict(img=None,
stem="A 59-year-old man takes an antiarrhythmic ending in \"-olol\" to prevent recurrent ventricular tachycardia because he couldn't tolerate amiodarone. His heart rate is 48/min, and his corrected QT is 510 ms.{FIG}Which classes of activity does this drug have?",
choices=["Class II and class III","Class I and class III","Class II and class IV","Class IA and class IB","Class III and class IV"], key=0,
exp="<b>Sotalol</b> is a <b>mixed class II + III</b> drug: a β-blocker (\"-olol\") that also blocks K⁺ channels. Indications: severe ventricular arrhythmias, especially when amiodarone isn't tolerated, and preventing recurrent AF/flutter. Not usually first-line. Its adverse effects follow both classes: <b>class II</b> (fatigue, <b>bradycardia</b>) and <b>class III</b> (<b>QT prolongation, torsades</b>). Can you draw it? A flatter phase 4 in the node (β-block) plus a longer plateau in the myocyte (K⁺ block).<br><br><b>Educational objective:</b> Sotalol combines β-blockade (class II, bradycardia) with K⁺-channel block (class III, QT prolongation and torsades).",
wrong={1:"Sotalol has no Na⁺-channel (class I) activity.",
2:"Sotalol doesn't block Ca²⁺ channels.",
3:"IA and IB are Na⁺-channel subclasses, unrelated to sotalol.",
4:"Sotalol has no class IV (Ca²⁺-channel) activity. Amiodarone is the one with activity in all four classes."},
eli5="Sotalol is two drugs in one: a β-blocker that slows the heart and a potassium blocker that stretches the QT."),

dict(img=None,
stem="A 70-year-old man who takes metoprolol develops supraventricular tachycardia at 180/min. Intravenous verapamil is given. Minutes later his blood pressure is unobtainable; the monitor still shows organized electrical activity at 40/min, but there is no palpable pulse.{FIG}Which of the following best explains this?",
choices=["Combined loss of nodal conduction and contractility","Verapamil-induced torsades de pointes from a long QT","Anaphylaxis to the intravenous preparation","Profound reflex vasodilation from dihydropyridine-like action","Acute hyperkalemia from β-blockade"], key=0,
exp="<b>IV verapamil plus a β-blocker is contraindicated</b>. Both depress the AV node and the myocardium (negative chronotropy, dromotropy and inotropy). Together they can cause irreversible <b>electromechanical dissociation</b> (pulseless electrical activity): drug-induced heart failure with electrical activity but no effective contraction. Non-dihydropyridine adverse effects are exaggerations of their action: bradycardia, AV block, heart failure, hypotension, plus constipation (verapamil) and edema (diltiazem).<br><br><b>Educational objective:</b> IV verapamil with a β-blocker can cause electromechanical dissociation and is contraindicated.",
wrong={1:"Verapamil doesn't prolong the QT, and the monitor shows an organized slow rhythm.",
2:"There's no urticaria, wheeze or angioedema, and the timing fits additive cardiodepression.",
3:"Verapamil is a non-dihydropyridine that acts mainly on the heart. Reflex vasodilation wouldn't cause pulselessness with a slow organized rhythm.",
4:"β-blockade causes only a minor K⁺ shift, not acute pulselessness."},
eli5="Both drugs slow and weaken the heart. Together they slowed and weakened it so much that the electrical signal kept going but the muscle stopped pumping."),

dict(img=None,
stem="A 77-year-old man on digoxin for atrial fibrillation has verapamil added for better rate control. Ten days later he has nausea and blurred vision, and his digoxin level has nearly doubled. His serum potassium and creatinine are unchanged.{FIG}Which of the following best explains the rise in digoxin?",
choices=["Competition for renal excretion of digoxin","Killing of gut flora that metabolize digoxin","Displacement of digoxin from plasma proteins","Hypokalemia increasing digoxin binding","Induction of hepatic CYP3A4 metabolism"], key=0,
exp="Digoxin interactions are \"a board favourite\". The lecture's table:<br>• <b>Verapamil, diltiazem:</b> compete for digoxin's <b>renal excretion</b> (pharmacokinetic) and add AV-node slowing (pharmacodynamic).<br>• Quinidine: displaces it from plasma proteins and reduces renal clearance.<br>• Erythromycin (oral antibiotics): kills gut bacteria that metabolize digoxin, so more is absorbed.<br>• Loop and thiazide diuretics: hypokalemia → more digoxin binding → toxicity.<br>• β-blockers, calcium channel blockers: additive slowing of the node or the muscle.<br>Normal K⁺ and the verapamil timing point to renal competition.<br><br><b>Educational objective:</b> Verapamil and diltiazem raise digoxin levels by competing for its renal excretion.",
wrong={1:"Killing gut flora is the <b>erythromycin</b> mechanism.",
2:"Plasma-protein displacement is the <b>quinidine</b> mechanism.",
3:"His potassium is unchanged. Hypokalemia is the diuretic mechanism.",
4:"Enzyme induction would <b>lower</b> drug levels, and verapamil inhibits CYP3A4 rather than inducing it."},
eli5="Verapamil and digoxin queue for the same exit in the kidneys. With verapamil in line, digoxin can't leave as fast and builds up."),

dict(img='Aadigaf', cap='12-lead ECG',
stem="An 81-year-old woman takes a once-daily drug for rate control of atrial fibrillation; her ECG is shown. Two weeks after furosemide was added for ankle swelling, she has anorexia, nausea and yellow-green halos around lights.{FIG}Which of the following laboratory values should be checked first?",
choices=["Serum potassium","Serum calcium","Serum sodium","Thyroid-stimulating hormone","Troponin I"], key=0,
exp="The ECG shows atrial fibrillation with <b>scooped (down-sloping) ST depression</b>, the digitalis effect (\"swoosh\" or \"reverse check\"). With yellow-green halos (xanthopsia) and anorexia, she has <b>digoxin toxicity</b>. \"Here's the EKG — what drug are they on?\" is a common question. <b>K⁺ competes with digoxin at the Na⁺/K⁺-ATPase</b>. The loop diuretic caused <b>hypokalemia</b>, which raises digoxin's binding and toxicity. Dr. Scully: <b>check the potassium first</b>. \"We don't have to give an antidote if all we have to do is fix their potassium.\" Severe toxicity → digoxin immune Fab.<br><br><b>Educational objective:</b> In suspected digoxin toxicity, check serum K⁺ first, because hypokalemia (often from diuretics) increases digoxin binding.",
wrong={1:"Calcium matters less. Potassium is the key modifier of digoxin's effect.",
2:"Sodium isn't the main regulator of digoxin binding.",
3:"Thyroid status affects digoxin sensitivity, but it isn't the first, most likely culprit after a diuretic.",
4:"There's no chest pain, and the ST scooping is a drug effect, not ischemia."},
eli5="Digoxin and potassium fight for the same parking spot on the heart's pump. The water pill lowered her potassium, so more digoxin parked and she got toxic. Check potassium first."),

dict(img=None,
stem="Digoxin is prescribed for a patient with heart failure and atrial fibrillation. A student is asked to explain how it increases contractility.{FIG}Which sequence best describes digoxin's inotropic mechanism?",
choices=["Na⁺/K⁺-ATPase block → less Ca²⁺ extruded by the exchanger","β1 stimulation → ↑ cAMP → phosphorylation of L-type channels","Phosphodiesterase-3 inhibition → ↑ cAMP in myocytes","Ca²⁺ sensitization of troponin C without ↑ Ca²⁺","Opening of K⁺ channels → hyperpolarized myocytes"], key=0,
exp="Digoxin <b>blocks the Na⁺/K⁺-ATPase</b> → ↑ intracellular Na⁺ → the <b>Na⁺/Ca²⁺ exchanger (NCX)</b> loses the gradient it needs to push Ca²⁺ out (it can even reverse) → more Ca²⁺ stored in the sarcoplasmic reticulum → bigger Ca²⁺-induced Ca²⁺ release → <b>↑ contractility</b>. Its antiarrhythmic (rate) effect is separate: ↓ AV-node automaticity, longer nodal refractory period, ↓ sympathetic outflow and ↑ vagal tone.<br><br><b>Educational objective:</b> Digoxin inhibits the Na⁺/K⁺-ATPase, raising intracellular Na⁺ so less Ca²⁺ leaves through the Na⁺/Ca²⁺ exchanger. More stored Ca²⁺ means stronger contraction.",
wrong={1:"β1 stimulation is dobutamine's mechanism.",
2:"PDE-3 inhibition is milrinone's mechanism.",
3:"Ca²⁺ sensitization is levosimendan's mechanism.",
4:"Opening K⁺ channels is adenosine's action in nodal tissue, and it would reduce excitability."},
eli5="Digoxin jams the sodium pump, so sodium builds up inside. The cell then can't push calcium out as well, and the extra calcium makes each squeeze stronger."),

dict(img=None,
stem="A 28-year-old woman has a regular narrow-complex tachycardia at 210/min. Vagal maneuvers fail. Adenosine 6 mg is pushed rapidly with a saline flush, and the rhythm converts after a 3-second pause.{FIG}Which of the following describes adenosine's mechanism?",
choices=["Opening of K⁺ channels that hyperpolarize nodal cells","Blockade of L-type Ca²⁺ channels in the AV node","Blockade of fast Na⁺ channels in the ventricle","Inhibition of the Na⁺/K⁺-ATPase in nodal tissue","Stimulation of M2 muscarinic receptors on the SA node"], key=0,
exp="Adenosine → <b>P1 purinergic receptor</b> (a G-protein–coupled receptor) → <b>Gi/o</b>, whose βγ subunit <b>opens K⁺ channels</b> (I<sub>KACh</sub>) → <b>hyperpolarizes SA-node, atrial and AV-node cells</b> → a big pause (brief asystole, AV block or severe bradycardia) → the underlying sinus rhythm takes back over. The lecture calls this the \"IT approach\": switch the conduction system off and on again. Its half-life is seconds, hence the rapid push and flush (\"like a hand grenade\"). It fixes re-entry, not sinus tachycardia.<br><br><b>Educational objective:</b> Adenosine acts on P1 receptors → Gi/o → opens K⁺ channels → hyperpolarizes nodal tissue → transient AV block that breaks re-entrant PSVT.",
wrong={1:"Blocking L-type Ca²⁺ channels in the node is verapamil or diltiazem.",
2:"Fast Na⁺-channel block is class I, acting on myocytes.",
3:"Na⁺/K⁺-ATPase inhibition is digoxin.",
4:"Adenosine acts on P1 receptors, not muscarinic ones, though both pathways open the same K⁺ channel."},
eli5="Adenosine opens potassium doors in the heart's electrical gatekeeper, so it goes quiet for a second. That breaks the looping short-circuit, and the normal pacemaker takes back over."),

dict(img=None,
stem="A 24-year-old hockey player leaves the ice with a racing heartbeat, chest tightness and dizziness, then loses consciousness. His 12-lead ECG shows a regular narrow-complex rhythm at 192/min with no visible P waves. A drug is pushed intravenously; the monitor shows a brief pause and then sinus rhythm at 88/min. For several minutes afterward, the paramedic notices it is much harder to squeeze the bag-valve mask.{FIG}Which drug was most likely given?",
choices=["Adenosine","Propranolol","Amiodarone","Atropine","Lidocaine"], key=0,
exp="This is the lecture's case. <b>Narrow + regular + no P + 192 → PSVT</b> (re-entry). Would propranolol \"take us down from 192, unresponsive\"? Not fast or hard enough. The choices are <b>adenosine</b> or electricity. Expected ECG after adenosine: a brief asystole, severe bradycardia or AV block, then sinus. The confirming clue is <b>transient bronchoconstriction</b> (more resistance on the bag), which can last <b>up to 30 minutes in asthma</b>. Warn patients about a sense of impending doom, flushing and chest pain.<br><br><b>Educational objective:</b> Adenosine converts narrow-complex PSVT with a brief pause and can cause transient bronchoconstriction.",
wrong={1:"Propranolol could cause bronchospasm, but it doesn't convert PSVT in seconds with a pause.",
2:"Amiodarone is for unstable VT and VF and doesn't cause acute bronchospasm.",
3:"Atropine speeds the heart. It's for bradycardia.",
4:"Lidocaine is for ventricular arrhythmias, not a narrow-complex re-entrant tachycardia."},
eli5="Adenosine briefly switched his heart's wiring off and on, which stopped the racing rhythm. It also tightened his airways for a few minutes, which is why the bag got hard to squeeze."),

dict(img=None,
stem="A 30-year-old man with recurrent paroxysmal supraventricular tachycardia drinks six energy drinks a day. In the emergency department the standard adenosine dose, given by rapid push with a flush, has no effect on the rhythm.{FIG}Which of the following best explains the poor response?",
choices=["Methylxanthines block adenosine receptors","Caffeine speeds the hepatic breakdown of adenosine","The drug needs a central line to reach the heart","Caffeine raises sympathetic tone via β1 agonism","Energy drinks lower the density of cardiac P1 receptors"], key=0,
exp="Board add-on, building on the lecture's mechanism: <b>methylxanthines (caffeine, theophylline) are competitive antagonists at adenosine receptors</b>, so a larger dose may be needed. If adenosine fails, the lecture says <b>repeat it or move to cardioversion</b>. Other cautions: avoid adenosine in asthma (bronchospasm) and in pre-excitation. Dipyridamole and carbamazepine strengthen its effect.<br><br><b>Educational objective:</b> Caffeine and theophylline block adenosine receptors and blunt adenosine's effect. Repeat at a higher dose or cardiovert.",
wrong={1:"Adenosine is cleared within seconds by cellular uptake and adenosine deaminase, not the liver.",
2:"A rapid push into a good proximal IV with a flush works. A central line isn't required.",
3:"Caffeine's main action is receptor antagonism, not β1 agonism.",
4:"Energy drinks don't reduce cardiac P1 receptor numbers."},
eli5="Caffeine sits in the same receptor slot adenosine needs. With lots of caffeine on board, a normal dose of adenosine can't get in."),

dict(img=None,
stem="A 26-year-old woman with recurrent supraventricular tachycardia is about to receive adenosine in the emergency department. The physician explains what she may feel during the push.{FIG}Which of the following effects is she most likely to experience?",
choices=["A brief feeling of impending doom","Yellow-green halos around lights","Ringing in the ears and blurred vision","Blue-gray skin with sun exposure","Vivid nightmares for several nights"], key=0,
exp="Adenosine adverse effects are <b>brief</b> because it washes out in seconds. The lecture's list: a <b>sense of impending doom</b> (\"I'm going to die\"), a feeling of being kicked in the chest, <b>flushing</b>, chest pain and headache. In the ED video the patient groaned: \"they feel it\". The ECG pause (asystole, AV block, bradycardia) is expected. Bronchoconstriction can last up to 30 minutes in asthma. Each distractor is another drug's signature effect.<br><br><b>Educational objective:</b> Warn patients that adenosine causes a brief sense of impending doom, chest discomfort and flushing.",
wrong={1:"Yellow-green halos (xanthopsia) are digoxin toxicity.",
2:"Tinnitus and blurred vision (cinchonism) come from quinidine.",
3:"Blue-gray skin and photosensitivity come from long-term amiodarone.",
4:"Vivid nightmares come from lipophilic β-blockers."},
eli5="For a few seconds the heart pauses, and many people feel a wave of 'something terrible is happening'. It passes almost as soon as it starts."),

dict(img='Aasbrady', cap='Lead II rhythm strip',
stem="A 67-year-old man is brought in after feeling faint while gardening. He is confused, his blood pressure is 82/50 mm Hg, and his skin is cool. His rhythm strip is shown.{FIG}Which of the following is the most appropriate first drug?",
choices=["Atropine","Epinephrine infusion","Adenosine","Metoprolol","Digoxin"], key=0,
exp="The strip shows <b>sinus bradycardia at 37/min</b> with hypotension and confusion: <b>symptomatic bradycardia</b>. Dr. Scully's one \"indication → drug\" question: <b>atropine first, then the catecholamines</b> (sympathetic amines such as epinephrine or dopamine). Atropine is a <b>non-selective muscarinic antagonist</b>. It blocks vagal M2 input to the SA and AV nodes → ↑ rate and AV conduction. ACLS bradycardia rhythms: sinus bradycardia, 1st-degree, 2nd-degree types I and II, and 3rd-degree block (pacing is often needed for high-grade block).<br><br><b>Educational objective:</b> Symptomatic bradycardia is treated first with atropine (muscarinic antagonist), then catecholamines.",
wrong={1:"Catecholamine infusions are <b>second-line</b>, after atropine.",
2:"Adenosine causes a pause. It would worsen bradycardia.",
3:"Metoprolol would slow him further.",
4:"Digoxin increases vagal tone and slows the node."},
eli5="His vagus nerve is pressing the heart's brake too hard. Atropine blocks that brake so the heart speeds back up."),

dict(img=None,
stem="A resident gives a small dose of atropine (0.1 mg) to a patient with symptomatic sinus bradycardia at 46/min. Instead of rising, the heart rate briefly falls to 40/min before increasing after a full dose.{FIG}According to the lecture slide, which of the following best explains the initial slowing?",
choices=["Blockade of M1 receptors before M2 receptors","Direct stimulation of cardiac M2 receptors","Reflex bradycardia from atropine-induced hypertension","Atropine-induced AV block from Ca²⁺-channel blockade","Inhibition of acetylcholinesterase at the SA node"], key=0,
exp="The lecture flags a <b>paradoxical slowing</b>: at low doses atropine can slow the heart before the expected tachycardia. The slide explains this as <b>M1 receptor blockade showing before M2 blockade</b>. Board add-on: one proposed mechanism is blockade of presynaptic M1 autoreceptors on vagal nerve endings, which normally limit acetylcholine release. More acetylcholine then reaches the still-unblocked M2 receptors. An adequate dose blocks M2 and the rate rises.<br><br><b>Educational objective:</b> Low-dose atropine can paradoxically slow the heart (M1 blockade before M2 blockade). Give an adequate dose.",
wrong={1:"Atropine is an antagonist. It doesn't stimulate M2 receptors.",
2:"Atropine doesn't cause hypertension at this dose.",
3:"Atropine doesn't block Ca²⁺ channels.",
4:"Inhibiting acetylcholinesterase is physostigmine's action, the antidote, not atropine's."},
eli5="At a tiny dose, atropine first blocks a nerve 'off switch' that limits the brake signal, so the brake briefly gets stronger. A full dose then blocks the brake itself."),

dict(img=None,
stem="After repeated atropine doses for bradycardia, a 70-year-old woman becomes agitated and disoriented. Her temperature is 39.0°C (102.2°F); her skin is flushed, hot and dry, her pupils are dilated and her bowel sounds are absent.{FIG}Which of the following is the most appropriate antidote?",
choices=["Physostigmine","Pyridostigmine","Pralidoxime","Neostigmine","Naloxone"], key=0,
exp="This is the <b>anticholinergic toxidrome</b>: <b>mad</b> as a hatter (delirium), <b>dry</b> as a bone, <b>blind</b> as a bat (mydriasis, cycloplegia), <b>red</b> as a beet (flushing), <b>hot</b> as a hare (hyperthermia). Atropine <b>crosses the blood–brain barrier</b>, so the antidote must too. <b>Physostigmine</b> is an acetylcholinesterase inhibitor. Acetylcholine builds up and competes atropine off muscarinic receptors, and because it enters the CNS it reverses the delirium. Pyridostigmine and neostigmine don't cross the BBB. Pralidoxime regenerates acetylcholinesterase in organophosphate poisoning.<br><br><b>Educational objective:</b> Atropine toxicity is reversed with physostigmine, an acetylcholinesterase inhibitor that crosses the blood–brain barrier.",
wrong={1:"Pyridostigmine doesn't cross the BBB, so it misses the delirium.",
2:"Pralidoxime is for <b>organophosphate</b> (cholinergic excess) poisoning.",
3:"Neostigmine is a quaternary amine that doesn't enter the CNS.",
4:"Naloxone reverses opioids."},
eli5="Too much atropine blocks the body's 'rest and digest' signals everywhere, including the brain. Physostigmine boosts those signals back up, and it can get into the brain to fix the confusion."),

dict(img=None,
stem="A cardiology team is reviewing which patients on their ward can safely receive amiodarone.{FIG}In which of the following patients is amiodarone contraindicated?",
choices=["Third-degree heart block without a pacemaker","Ventricular fibrillation recurring after defibrillation","Stable monomorphic ventricular tachycardia","Heart failure with an ejection fraction of 25%","Paroxysmal atrial fibrillation with recurrences"], key=0,
exp="Amiodarone has class I, II, III and IV activity (\"it does all the things\"). It slows the SA and AV nodes, so the lecture's contraindications are <b>second- and third-degree heart block</b>, symptomatic bradycardia, <b>cardiogenic shock</b>, and polymorphic VT with a prolonged QT. Indications: unstable VT, <b>recurrent VF</b>, supraventricular arrhythmias, and off-label prevention of recurrent paroxysmal AF/flutter. Board add-on: it has almost no negative inotropy, so it is <b>safe in HFrEF</b>, and despite the long QT its torsades risk is low.<br><br><b>Educational objective:</b> Amiodarone is contraindicated in second- or third-degree heart block (without a pacemaker), symptomatic bradycardia and cardiogenic shock.",
wrong={1:"Recurrent VF is an indication for amiodarone.",
2:"Ventricular tachycardia is a core indication.",
3:"Amiodarone is safe in HFrEF because it has little negative inotropy.",
4:"Preventing recurrent paroxysmal AF is an (off-label) indication."},
eli5="Amiodarone slows the heart's wiring. If the wiring is already blocked and there's no pacemaker backup, slowing it more could stop the heartbeat."),

dict(img=None,
stem="A 45-year-old woman has recurrent atrioventricular nodal re-entrant tachycardia. Intravenous verapamil terminates her episodes. Her cousin has recurrent monomorphic ventricular tachycardia from a scar, which verapamil does not help.{FIG}Which of the following best explains the difference?",
choices=["AV nodal upstroke depends on L-type Ca²⁺ channels","Verapamil opens K⁺ channels only in nodal cells","Ventricular myocytes lack β1-adrenergic receptors","Verapamil is cleared before it reaches the ventricles","Ventricular tachycardia depends on the funny current"], key=0,
exp="The <b>AV node depolarizes with Ca²⁺</b> (L-type channels, phase 0). Verapamil and diltiazem block those channels → slower upstroke and conduction in the AV node → <b>longer nodal refractory period</b>. That breaks re-entrant circuits that run through the node (AVNRT, AVRT) and slows the ventricular rate in AF/flutter. <b>Ventricular myocytes depolarize with Na⁺</b>, so a scar-related VT circuit is out of reach. Verapamil is best at nodal tissue, dihydropyridines at the vasculature, and diltiazem \"does both\".<br><br><b>Educational objective:</b> Class IV drugs block nodal L-type Ca²⁺ channels, so they break re-entry that uses the AV node but don't treat myocyte-based VT.",
wrong={1:"Verapamil blocks Ca²⁺ channels. It doesn't open K⁺ channels (that's adenosine).",
2:"Ventricular myocytes do have β1 receptors, and verapamil isn't a β-blocker anyway.",
3:"Verapamil reaches the whole heart through the circulation.",
4:"The funny current is a nodal pacemaker current. Scar VT is re-entry in myocytes."},
eli5="The AV node fires with calcium, so a calcium blocker can stop a loop that runs through it. The ventricle's loop runs on sodium, so a calcium blocker can't touch it."),
]
