# Antiarrhythmic Pharmacology (Scully) — Version 1, 18 items (3 with images): action potentials, rate vs rhythm, class I, class II
Q = [
dict(img=None,
stem="An investigator records action potentials from isolated sinoatrial (SA) node cells and from ventricular myocytes. A toxin abolishes the upstroke (phase 0) of the SA node action potential but leaves the ventricular upstroke intact.{FIG}Which of the following channels does the toxin most likely block?",
choices=["L-type Ca²⁺ channels","Fast voltage-gated Na⁺ channels","HCN (funny-current) channels","Delayed-rectifier K⁺ channels","Inward-rectifier K⁺ channels"], key=0,
exp="Dr. Scully's first skill is to <b>attribute an ion to every phase</b>.<br>• <b>SA/AV node (pacemaker):</b> phase 4 = funny current (I<sub>f</sub>, Na⁺, opened by hyperpolarization) · <b>phase 0 = Ca²⁺ through L-type channels</b> · phase 3 = K⁺ out.<br>• <b>Ventricular myocyte:</b> phase 0 = Na⁺ through fast channels · phase 1 = I<sub>to</sub> · phase 2 = Ca²⁺ in vs K⁺ out (plateau) · phase 3 = K⁺ out · phase 4 = I<sub>K1</sub> holds rest.<br>A toxin that removes the nodal upstroke but spares the ventricular one blocks <b>L-type Ca²⁺ channels</b>. That's why class IV drugs (verapamil, diltiazem) act on the node and class I drugs act on muscle.<br><br><b>Educational objective:</b> Nodal phase 0 is carried by Ca²⁺ (L-type channels). Myocyte phase 0 is carried by Na⁺ (fast channels).",
wrong={1:"Fast Na⁺ channels carry the <b>ventricular</b> upstroke, which was spared.",
2:"HCN channels carry the funny current of phase 4, the slow diastolic drift, not the upstroke.",
3:"Delayed-rectifier K⁺ channels repolarize the cell (phase 3).",
4:"The inward rectifier holds the resting potential of myocytes (phase 4)."},
eli5="Pacemaker cells use calcium to fire their spike, while regular heart muscle uses sodium. Block calcium and only the pacemaker spike disappears."),

dict(img=None,
stem="Isoproterenol raises the firing rate of isolated sinoatrial node cells, and acetylcholine slows it. The β1-adrenergic receptor couples to a stimulatory G protein (Gs) and the M2 muscarinic receptor to an inhibitory G protein (Gi).{FIG}Both receptors change the firing rate mainly by acting on which of the following enzymes?",
choices=["Adenylyl cyclase","Phospholipase C","Guanylyl cyclase","Phosphodiesterase-5","Na⁺/K⁺-ATPase"], key=0,
exp="\"S and I work on the same effector.\" <b>β1 → Gs → ↑ adenylyl cyclase → ↑ cAMP → protein kinase A</b>, which phosphorylates Ca²⁺ channels, phospholamban (↑ SERCA) and phospholemman. The result is a steeper phase 4, faster conduction and stronger contraction. <b>M2 → Gi → ↓ adenylyl cyclase → ↓ cAMP</b>, a more hyperpolarized cell and a flatter phase 4, so the rate slows. Phosphorylating the Ca²⁺-handling proteins is how autonomic tone changes rate, conduction velocity and contractility.<br><br><b>Educational objective:</b> Sympathetic (β1/Gs) and parasympathetic (M2/Gi) tone both set nodal rate through adenylyl cyclase and cAMP.",
wrong={1:"Phospholipase C is the Gq pathway (α1, M3), not the β1/M2 pathway in the node.",
2:"Guanylyl cyclase makes cGMP (nitric oxide, natriuretic peptides), mainly in vascular smooth muscle.",
3:"Phosphodiesterase-5 breaks down cGMP in smooth muscle (the target of sildenafil).",
4:"The Na⁺/K⁺-ATPase is digoxin's target, not the G-protein effector."},
eli5="The gas pedal (β1) and the brake (M2) both act on the same machine, adenylyl cyclase. One turns it up, the other turns it down, and that sets how fast the heart beats."),

dict(img=None,
stem="In an experiment, a drug shifts the threshold potential of sinoatrial node cells to a less negative value. The slope of phase 4 depolarization and the maximum diastolic potential are unchanged.{FIG}Which of the following best describes the effect on heart rate?",
choices=["Falls, because phase 4 takes longer to reach threshold","Rises, because phase 4 reaches threshold sooner","Rises, because the cells repolarize more quickly","Falls, because the upstroke can no longer occur","Is unchanged, because phase 4 slope alone sets the rate"], key=0,
exp="Slide 15 lists four levers on the action potential: maximum diastolic potential, <b>phase 4 slope</b>, <b>threshold potential</b> and action potential duration. In the lecture's worked example the threshold is raised without changing the funny-current drift. <b>Same slope, higher line to cross → longer to reach threshold → slower rate.</b> The reverse also holds: a steeper phase 4, a more negative threshold or a less negative resting potential all speed firing. The fastest pacemaker sets the heart rate (board add-on: SA node 60–100/min, AV node 40–60/min, Purkinje 20–40/min).<br><br><b>Educational objective:</b> A more positive threshold, a flatter phase 4 or a more negative maximum diastolic potential all lengthen the cycle and slow the rate.",
wrong={1:"A higher threshold is reached <b>later</b>, not sooner.",
2:"Repolarization speed wasn't changed in this experiment.",
3:"The upstroke still fires once threshold is reached. It just takes longer.",
4:"Rate depends on slope, threshold and starting potential together, not slope alone."},
eli5="Imagine filling a cup at the same speed but making the cup taller. It takes longer to overflow, so the 'beats' come less often."),

dict(img='Lafrvr', cap='12-lead ECG',
stem="A 68-year-old man has had palpitations for 2 days. His blood pressure is 128/76 mm Hg and he is alert. His electrocardiogram (ECG) is shown. The team chooses a rate-control strategy rather than restoring sinus rhythm.{FIG}Which of the following drugs fits this strategy?",
choices=["Diltiazem","Flecainide","Ibutilide","Dofetilide","Procainamide"], key=0,
exp="The ECG shows <b>atrial fibrillation with a rapid ventricular response</b>: irregularly irregular narrow complexes, no organized P waves. The lecture's organizing idea:<br>• <b>Rate control → nodal tissue</b> (the AV node gates how many atrial impulses reach the ventricles) → <b>class II (β-blockers) and class IV (verapamil, diltiazem)</b>, plus digoxin.<br>• <b>Rhythm control → myocytes</b> → <b>class I</b> (Na⁺-channel blockers) and <b>class III</b> (K⁺-channel blockers).<br>\"When you hear 'we're going to try a rate approach for this AF'\" → a β-blocker or calcium channel blocker. Slide notes: atrial fibrillation also needs anticoagulation and risk-factor reduction.<br><br><b>Educational objective:</b> Rate control targets the AV node with class II or IV drugs (or digoxin). Rhythm control uses class I or III drugs.",
wrong={1:"Flecainide (class IC) is a <b>rhythm</b> drug for AF in a structurally normal heart.",
2:"Ibutilide (class III) <b>converts</b> AF or flutter to sinus rhythm, a rhythm strategy.",
3:"Dofetilide (class III) converts and maintains sinus rhythm, also a rhythm strategy.",
4:"Procainamide (class IA) is a rhythm drug acting on myocytes."},
eli5="To control the rate, you slow the gatekeeper (the AV node) so fewer of the chaotic atrial signals get through. Diltiazem does that by blocking calcium in the node."),

dict(img=None,
stem="A 74-year-old woman with atrial fibrillation has been stable on digoxin for a year. Quinidine is added to restore sinus rhythm. A week later she has nausea, anorexia and yellow-tinted vision. Her serum potassium is 4.3 mEq/L.{FIG}Which of the following best explains her symptoms?",
choices=["Protein-binding displacement and ↓ renal clearance","Induction of hepatic enzymes that activate digoxin","Hyperkalemia that raises digoxin binding to its pump","Killing of gut bacteria that metabolize digoxin","Competition with digoxin for the Na⁺/K⁺-ATPase site"], key=0,
exp="This is <b>digoxin toxicity</b> (GI upset, xanthopsia) caused by <b>quinidine</b>. Dr. Scully: \"Drug–drug interactions with digoxin are a board favourite.\" Quinidine <b>displaces digoxin from plasma proteins</b> (free drug ↑, and free drug is what acts) and <b>reduces its renal clearance</b>. Her K⁺ is normal, so this isn't the hypokalemia mechanism. <b>Procainamide does not change digoxin levels</b>, which is the IA alternative if this matters.<br><br><b>Educational objective:</b> Quinidine raises digoxin levels by displacing it from plasma proteins and reducing its renal clearance. Procainamide does not.",
wrong={1:"Digoxin isn't activated by liver enzymes, and quinidine doesn't work this way.",
2:"<b>Hypo</b>kalemia raises digoxin binding. Hyperkalemia <b>reduces</b> its effect, and her K⁺ is normal anyway.",
3:"Killing gut flora is how <b>erythromycin</b> (oral antibiotics) raises digoxin.",
4:"Quinidine doesn't act at the Na⁺/K⁺-ATPase. K⁺ is what competes with digoxin there."},
eli5="Quinidine kicks digoxin off its carrier proteins and slows its exit through the kidneys. Free digoxin builds up and she gets toxic."),

dict(img='Xlupus', cap='Illustration of the facial rash',
stem="A 58-year-old man has taken an oral antiarrhythmic for 10 months for recurrent ventricular tachycardia. He now has fever, joint pain in both hands, pleuritic chest pain, and the facial rash illustrated. Antihistone antibodies are positive; anti–double-stranded DNA antibodies are negative.{FIG}Which of the following drugs is most likely responsible?",
choices=["Procainamide","Quinidine","Lidocaine","Flecainide","Amiodarone"], key=0,
exp="A malar (butterfly) rash, arthralgias, serositis and <b>antihistone antibodies</b> with negative anti-dsDNA mean <b>drug-induced lupus</b>. The lecture names <b>procainamide</b> (class IA): \"same AEs as quinidine, <b>plus drug-induced lupus with chronic use</b>.\" Procainamide is given IV or orally for supraventricular and ventricular arrhythmias. It is acetylated in the liver to N-acetylprocainamide (NAPA, active) and cleared by the kidneys. Board add-on: lupus is more likely in slow acetylators and usually resolves after the drug is stopped.<br><br><b>Educational objective:</b> Chronic procainamide causes drug-induced lupus (antihistone antibodies).",
wrong={1:"Quinidine's signature adverse effects are cinchonism, diarrhea and torsades.",
2:"Lidocaine is IV-only and causes CNS effects (confusion, seizures), not lupus.",
3:"Flecainide's problems are pro-arrhythmia, ataxia and blurred vision.",
4:"Amiodarone causes blue-gray skin and photosensitivity, not a lupus syndrome."},
eli5="Some drugs trick the immune system into a lupus-like illness. Procainamide is the classic one, and it usually clears up once the drug is stopped."),

dict(img=None,
stem="A 62-year-old man in the coronary care unit after a myocardial infarction has frequent runs of premature ventricular contractions. A lidocaine infusion suppresses them while barely affecting conduction in healthy myocardium.{FIG}Which property of lidocaine best explains this selectivity?",
choices=["It binds open and inactivated Na⁺ channels and unbinds fast","It blocks L-type Ca²⁺ channels in the ischemic border zone","It prolongs repolarization by blocking K⁺ channels","It binds resting Na⁺ channels with high affinity","It hyperpolarizes cells by opening K⁺ channels"], key=0,
exp="Class I drugs bind Na⁺ channels in the <b>open and inactivated</b> states (use-dependent block). <b>Class IB (lidocaine, mexiletine)</b> also <b>dissociates rapidly</b>, so in healthy tissue it washes off between beats and the block is mild. <b>Ischemic, depolarized myocardium</b> can't hold its membrane potential and fires more often, so its channels spend more time in the bindable states and the block builds up there. The effect is almost preferential for damaged tissue. Indication: ventricular arrhythmias (second-line, emergency use). Board add-on: \"class IB is Best after MI.\"<br><br><b>Educational objective:</b> Lidocaine targets ischemic tissue because it binds open and inactivated Na⁺ channels and dissociates rapidly from healthy tissue.",
wrong={1:"Lidocaine is a Na⁺-channel blocker. Ca²⁺-channel block is class IV.",
2:"Class IB <b>shortens</b> repolarization (Goldilocks: \"too short\"). K⁺ block is class III and IA.",
3:"Resting channels are the state class I drugs bind <b>least</b>. That's why normal tissue is spared.",
4:"Opening K⁺ channels is adenosine's nodal mechanism."},
eli5="Lidocaine grabs sodium channels only while they're busy, and lets go quickly. Damaged heart muscle keeps its channels busy, so lidocaine sticks there and leaves healthy muscle alone."),

dict(img=None,
stem="A 70-year-old woman with cirrhosis is given a lidocaine infusion for recurrent ventricular tachycardia. The next day she has perioral numbness, slurred speech and confusion, and then a generalized seizure.{FIG}Which of the following best explains her neurologic findings?",
choices=["Na⁺-channel blockade in central neurons","Accumulation of an active acetylated metabolite","Hypocalcemia from chelation by the drug","Torsades de pointes from QT prolongation","Anticholinergic excess crossing the blood–brain barrier"], key=0,
exp="Lidocaine is also a local anesthetic (\"-caine\"), and at high levels it <b>blocks Na⁺ channels in the central nervous system</b>. The lecture's adverse effects: <b>confusion, dizziness, seizures</b>, tremor and <b>methemoglobinemia</b>. Its interactions are pharmacokinetic (CYP), and the <b>dose must be adjusted for liver function</b>. Her cirrhosis let the drug accumulate.<br><br><b>Educational objective:</b> Lidocaine toxicity is mainly neurologic (confusion, seizures) from CNS Na⁺-channel block. It is hepatically cleared, so reduce the dose in liver disease.",
wrong={1:"An active acetylated metabolite (N-acetylprocainamide) belongs to <b>procainamide</b>.",
2:"Lidocaine doesn't chelate calcium.",
3:"Class IB drugs <b>shorten</b> repolarization, and torsades wouldn't explain prodromal perioral numbness.",
4:"Anticholinergic CNS effects belong to quinidine, disopyramide and atropine, not lidocaine."},
eli5="Lidocaine numbs nerves by blocking sodium channels. With too much on board (her liver can't clear it), it starts blocking brain sodium channels too, causing confusion and seizures."),

dict(img=None,
stem="A 35-year-old woman with paroxysmal atrial fibrillation and a structurally normal heart takes flecainide. Her resting QRS duration is 100 ms. During a treadmill stress test at a heart rate of 150/min, it widens to 140 ms.{FIG}Which of the following best explains the exercise-related widening?",
choices=["Use-dependent Na⁺-channel block at faster rates","Exercise-induced hyperkalemia blocking K⁺ channels","Ischemia of the bundle branches during exertion","Catecholamines increasing the drug's absorption","Prolonged repolarization from K⁺-channel block"], key=0,
exp="<b>Class IC (flecainide, propafenone)</b> causes the <b>most marked slowing of phase 0</b> (\"salty CAB driver\": C > A > B) and leaves repolarization unchanged (Goldilocks: \"just right\"). The QRS is ventricular depolarization, so a flatter upstroke widens it. Because class I drugs bind open and inactivated channels and IC drugs dissociate slowly, <b>more beats per minute means more block</b>. The QRS widens more with exertion. Flecainide is for sustained VT and AF prevention in a <b>structurally normal heart</b>. It is pro-arrhythmic with ischemia or scar.<br><br><b>Educational objective:</b> Class IC drugs show use-dependent Na⁺-channel block, so QRS widening increases at faster heart rates.",
wrong={1:"Exercise hyperkalemia is minor and isn't the mechanism of drug-related QRS widening.",
2:"She has a normal heart. The widening tracks rate, which points to the drug.",
3:"Absorption doesn't change acutely on a treadmill.",
4:"Class IC drugs don't change repolarization. K⁺-channel block lengthens the <b>QT</b>, not the QRS."},
eli5="Flecainide jams sodium channels each time they open. The faster the heart beats, the more channels get jammed, so each beat spreads more slowly and the QRS gets wider."),

dict(img=None,
stem="A 70-year-old man in the intensive care unit after abdominal surgery develops atrial fibrillation at 150/min. His blood pressure is 102/64 mm Hg, and the team wants a β-blocker whose effect will wear off within minutes if his blood pressure drops.{FIG}Which of the following is the most appropriate choice?",
choices=["Esmolol","Atenolol","Nadolol","Propranolol","Carvedilol"], key=0,
exp="<b>Esmolol</b> is a second-generation (β1-selective) blocker with a <b>very short half-life</b>: it \"washes in and washes out\", so it suits <b>hemodynamically unstable</b> patients. In practice it is limited by the volume of fluid that must be infused with it. β-blockers are class II, rate drugs: they flatten phase 4 and prolong AV-node repolarization. Generations: 1st non-selective (propranolol, nadolol); 2nd β1-selective (atenolol, metoprolol, esmolol); 3rd vasodilating (carvedilol and labetalol block α1; nebivolol releases nitric oxide).<br><br><b>Educational objective:</b> Esmolol's ultra-short half-life makes it the β-blocker for unstable patients, because its effect can be stopped quickly.",
wrong={1:"Atenolol is long-acting and renally cleared, so it can't be turned off quickly.",
2:"Nadolol is a long-acting non-selective blocker.",
3:"Propranolol is non-selective and lasts hours.",
4:"Carvedilol's α1 blockade adds vasodilation, which is risky at borderline blood pressure, and it lasts hours."},
eli5="Esmolol works like a light switch. If his blood pressure dips, you stop the drip and it's gone within minutes."),

dict(img=None,
stem="A 31-year-old woman at 28 weeks' gestation has chronic hypertension (154/100 mm Hg). Her obstetrician prescribes labetalol rather than metoprolol.{FIG}Which property of labetalol best explains this choice?",
choices=["Its α1 blockade prevents reflex placental vasoconstriction","It does not cross the placenta to reach the fetus","It is β1-selective and spares uterine β2 receptors","It raises renal blood flow by stimulating dopamine receptors","It stimulates endothelial nitric oxide release"], key=0,
exp="Pregnancy is the setting where a β-blocker is first-line for hypertension. Lowering cardiac output alone triggers the <b>baroreceptor reflex</b>: sympathetic outflow clamps down the peripheral vessels, <b>including those that perfuse the placenta</b>. <b>Labetalol also blocks α1 receptors</b>, preventing that compensatory vasoconstriction and protecting placental perfusion. Labetalol and carvedilol are third-generation (α1-blocking) agents. Nebivolol releases nitric oxide.<br><br><b>Educational objective:</b> Labetalol's added α1 blockade prevents baroreflex vasoconstriction, preserving placental perfusion. That makes it the β-blocker for hypertension in pregnancy.",
wrong={1:"Labetalol does cross the placenta. Safety comes from its hemodynamic profile.",
2:"Labetalol is <b>non-selective</b> (β1 + β2) plus α1. Metoprolol is the β1-selective one.",
3:"Dopamine-receptor agonism describes fenoldopam, not labetalol.",
4:"Nitric oxide release is <b>nebivolol</b>'s third-generation feature."},
eli5="When you slow the heart, the body squeezes its blood vessels to keep pressure up, including the ones feeding the baby. Labetalol also blocks that squeeze, so the placenta keeps getting blood."),

dict(img=None,
stem="A 16-year-old girl with congenital long QT syndrome has palpitations during exercise. Her cardiologist adds propranolol.{FIG}Which property makes propranolol acceptable in this patient?",
choices=["It doesn't prolong repolarization","It selectively blocks β1 receptors","It has intrinsic sympathomimetic activity","It blocks α1 receptors to lower afterload","It opens K⁺ channels to shorten the QT interval"], key=0,
exp="Dr. Scully's \"fun fact\" for the nitty-gritty question: <b>propranolol does not prolong repolarization</b>, so it can be used in patients with a <b>prolonged QT</b>. (Class III and IA drugs prolong repolarization and are contraindicated with long QT.) In congenital long QT, β-blockade also blunts the adrenergic triggers of torsades (exercise, startle).<br><br><b>Educational objective:</b> Propranolol doesn't prolong repolarization, so it is acceptable in long QT syndrome.",
wrong={1:"Propranolol is <b>non-selective</b> (β1 + β2), a first-generation drug.",
2:"Intrinsic sympathomimetic activity belongs to pindolol and acebutolol, not propranolol.",
3:"Propranolol has no α1 blockade. That's carvedilol and labetalol.",
4:"Propranolol doesn't open K⁺ channels. That's adenosine's nodal action."},
eli5="Drugs that stretch the heart's reset time are dangerous when it's already too long. Propranolol doesn't stretch it, and it calms the adrenaline that can trigger the bad rhythm."),

dict(img=None,
stem="A 19-year-old violin student has a racing heart and palpitations before every recital. She takes propranolol 30 minutes before a performance. She has mild intermittent asthma, and 1 hour after the dose she develops chest tightness and wheezing.{FIG}Which of the following best explains her wheezing?",
choices=["Blockade of β2 receptors on bronchial smooth muscle","Blockade of β1 receptors in the airway epithelium","Release of histamine from mast cells","Direct stimulation of muscarinic receptors in the airway","Blockade of α1 receptors on bronchial vessels"], key=0,
exp="Sympathetically triggered palpitations (exams, public speaking, \"palpitations that get in the way of daily life\") are a classic β-blocker indication. But <b>first-generation (non-selective) drugs block β2 as well as β1</b>. Bronchial smooth muscle relaxes through β2 (the receptor albuterol acts on), so blocking it causes <b>bronchospasm</b>. Non-selective β-blockers are \"not for asthmatics\". Other β2-antagonism effects: vasospasm, cold extremities, impotence. A β1-selective (second-generation) drug carries less risk.<br><br><b>Educational objective:</b> Non-selective β-blockers block β2 receptors on bronchial smooth muscle and can trigger bronchospasm in asthma.",
wrong={1:"β1 receptors are cardiac. Airway relaxation is β2-mediated.",
2:"Propranolol doesn't degranulate mast cells.",
3:"Propranolol doesn't stimulate muscarinic receptors. Unopposed vagal tone is a consequence of β2 loss, not a direct action.",
4:"Propranolol has no α1 activity, and α1 receptors don't control airway caliber."},
eli5="Her airways stay open thanks to β2 receptors, the same ones her inhaler activates. Propranolol blocks β2 too, so her airways tighten."),

dict(img=None,
stem="A 52-year-old man started on a β-blocker for palpitations reports vivid nightmares that \"feel like being awake\", along with insomnia. His heart rate and blood pressure are well controlled.{FIG}Which property of the drug most likely explains these effects?",
choices=["High lipid solubility","β1 selectivity","Intrinsic sympathomimetic activity","α1-receptor blockade","Renal elimination"], key=0,
exp="CNS effects of β-blockers (<b>insomnia, depression, vivid nightmares</b>) are typical of <b>lipophilic</b> drugs that cross the blood–brain barrier. The lecture table marks <b>propranolol, betaxolol and metoprolol</b>. Dr. Scully's counseling tip: you don't have to plant the idea. Say the drug \"may cause some issues around sleep — let me know if anything occurs\". Board add-on: a hydrophilic drug such as atenolol is less likely to do this.<br><br><b>Educational objective:</b> Lipophilic β-blockers (propranolol, metoprolol) cross into the CNS and cause vivid nightmares, insomnia and depression.",
wrong={1:"β1 selectivity reduces bronchospasm risk. It doesn't predict CNS effects (metoprolol is both β1-selective and lipophilic).",
2:"Intrinsic sympathomimetic activity limits bradycardia. It doesn't cause nightmares.",
3:"α1 blockade causes orthostatic hypotension, not nightmares.",
4:"Renally eliminated β-blockers (atenolol, nadolol) tend to be <b>hydrophilic</b> and cause fewer CNS effects."},
eli5="Fat-soluble β-blockers slip into the brain and can scramble sleep and dreams. Water-soluble ones mostly stay out."),

dict(img='Ltdp', cap='Rhythm strip recorded on telemetry',
stem="A 66-year-old woman is started on quinidine for atrial fibrillation. On day 3 her serum potassium is 3.1 mEq/L, and she has a brief syncopal episode while on telemetry (strip shown).{FIG}Which mechanism best explains this arrhythmia?",
choices=["Early afterdepolarizations during a long plateau","Delayed afterdepolarizations from Ca²⁺ overload","Re-entry through an accessory atrioventricular pathway","Enhanced automaticity of the sinoatrial node","Complete conduction block in the atrioventricular node"], key=0,
exp="The strip shows <b>torsades de pointes</b>: polymorphic VT that twists around the baseline after a long pause. <b>Class IA (quinidine, procainamide, disopyramide)</b> blocks K⁺ as well as Na⁺ channels, so repolarization is prolonged (Goldilocks: IA is \"too big\"). The lecture's mechanism: when repolarization is too slow, Na⁺ channels recover from inactivation <b>before the membrane falls below threshold</b>. They fire again and the membrane oscillates. These are <b>early afterdepolarizations</b>, triggered activity that becomes torsades. <b>Hypokalemia</b> worsens QT prolongation and reduces quinidine's efficacy, so K⁺ must be monitored. Contraindications: long QT, myasthenia gravis.<br><br><b>Educational objective:</b> Quinidine (class IA) prolongs repolarization, and early afterdepolarizations trigger torsades de pointes, worse with hypokalemia.",
wrong={1:"Delayed afterdepolarizations come from Ca²⁺ overload (digoxin), after repolarization.",
2:"Accessory-pathway re-entry causes WPW tachycardias, not drug-induced polymorphic VT.",
3:"SA node automaticity causes sinus tachycardia, not polymorphic VT.",
4:"AV block causes dropped beats or bradycardia, not a twisting ventricular tachycardia."},
eli5="Quinidine makes each heart cell take too long to reset. While it's still resetting, it can fire again by accident, and those misfires spiral into this twisting rhythm. Low potassium makes it worse."),

dict(img=None,
stem="A 60-year-old man is being considered for an oral class I antiarrhythmic for chronic ventricular ectopy. In isolated myocytes, the candidate drug slows the phase 0 upstroke only slightly and shortens action potential duration. It is described as the oral relative of a drug used intravenously in emergencies.{FIG}Which of the following is this drug?",
choices=["Mexiletine","Quinidine","Flecainide","Disopyramide","Dofetilide"], key=0,
exp="Use the two class I mnemonics:<br>• <b>Phase 0 slowing</b>, \"salty CAB driver\": C > A > B. Slight slowing is <b>IB</b>.<br>• <b>Repolarization</b> (Goldilocks): IA too big (prolongs) · <b>IB too short (shortens)</b> · IC just right (no change).<br>Slight phase 0 slowing with a <b>shortened</b> action potential is class IB: lidocaine (IV) and <b>mexiletine, its oral relative</b>. Board add-on: mexiletine is used for chronic ventricular arrhythmias, and phenytoin also has class IB activity.<br><br><b>Educational objective:</b> Class IB drugs (lidocaine IV, mexiletine oral) slightly slow phase 0 and shorten repolarization.",
wrong={1:"Quinidine (IA) moderately slows phase 0 and <b>prolongs</b> repolarization.",
2:"Flecainide (IC) <b>markedly</b> slows phase 0 with no change in repolarization.",
3:"Disopyramide (IA) prolongs repolarization and is strongly anticholinergic.",
4:"Dofetilide is class III. It blocks K⁺ channels and prolongs the action potential."},
eli5="Class IB drugs barely touch the upstroke and actually make the beat's reset shorter. Lidocaine is the IV version and mexiletine is the pill version."),

dict(img=None,
stem="A 72-year-old man with chronic kidney disease (creatinine clearance 22 mL/min) has taken procainamide for recurrent ventricular tachycardia. He develops marked QT prolongation and a run of torsades de pointes, although his procainamide level is within the target range.{FIG}Which of the following best explains this?",
choices=["Accumulation of its active acetylated metabolite","Displacement of procainamide from albumin binding sites","Inhibition of procainamide's hepatic metabolism","Drug-induced lupus involving the conduction system","Hyperkalemia from reduced renal K⁺ excretion"], key=0,
exp="Procainamide pharmacokinetics (lecture): bioavailability 75–95%, only 15–20% protein bound, <b>acetylated in the liver to N-acetylprocainamide (NAPA), which is active</b>, and <b>renally cleared</b> (dialyzable). In kidney failure NAPA accumulates even when the parent drug level looks fine. Board add-on: NAPA has <b>class III (K⁺-blocking) activity</b>, so it prolongs the QT and can cause torsades. Measure both procainamide and NAPA levels.<br><br><b>Educational objective:</b> Procainamide's active metabolite, N-acetylprocainamide, is renally cleared and accumulates in kidney failure, prolonging the QT.",
wrong={1:"Procainamide is only 15–20% protein bound, so displacement matters little.",
2:"Slower hepatic acetylation would <b>reduce</b> NAPA formation and raise the parent level, which is in range here.",
3:"Drug-induced lupus causes rash, arthritis and serositis, not QT prolongation.",
4:"Hyperkalemia tends to <b>shorten</b> repolarization. It doesn't cause torsades."},
eli5="The liver turns procainamide into a second active drug, and only the kidneys can clear that one. His kidneys are weak, so it piled up and stretched out his QT."),

dict(img=None,
stem="A 60-year-old man has taken quinidine for 3 weeks. He reports ringing in his ears, decreased hearing, blurred vision, frequent loose stools and two episodes of confusion. His salicylate level is undetectable.{FIG}Which of the following best describes this syndrome?",
choices=["Cinchonism","Anticholinergic toxidrome","Serotonin syndrome","Digitalis toxicity","Salicylism"], key=0,
exp="<b>Cinchonism</b> (named for the cinchona bark that quinidine and quinine come from) is <b>decreased hearing, tinnitus, blurred vision and delirium</b>, often with headache. Quinidine (class IA prototype) adverse effects in the lecture: torsades, cinchonism, <b>anticholinergic effects</b>, and nausea, diarrhea, headache. Contraindications: QT prolongation and <b>myasthenia gravis</b> (anticholinergic effects). It also raises digoxin levels.<br><br><b>Educational objective:</b> Quinidine causes cinchonism: tinnitus, hearing loss, blurred vision, delirium and GI upset.",
wrong={1:"Quinidine is mildly anticholinergic, but tinnitus and diarrhea point to cinchonism. An anticholinergic toxidrome causes constipation, not diarrhea.",
2:"Serotonin syndrome brings clonus, hyperthermia and agitation, typically after serotonergic drugs.",
3:"Digoxin toxicity causes yellow-green vision and GI upset, but not tinnitus or hearing loss.",
4:"Salicylism causes tinnitus too, but the salicylate level is undetectable."},
eli5="Quinidine comes from the same tree bark as quinine, and too much causes ringing ears, blurry vision and confusion. That set has its own name: cinchonism."),
]
