# ECG II: Clinical ECG Reading & Arrhythmias — Version 2, 18 items, every item has an ECG (read it yourself)
Q = [
dict(img='Rnormal', cap='12-lead ECG',
stem="A 28-year-old woman at 28 weeks' gestation is seen in the office because of occasional palpitations for 2 weeks. She feels well now. Her pulse is 84/min and blood pressure is 112/68 mm Hg. Her ECG is shown.{FIG}Which of the following is the most appropriate interpretation of this ECG?",
choices=["Atrial flutter with 4:1 conduction","First-degree AV block","Left bundle branch block","Normal sinus rhythm","Wolff–Parkinson–White pattern"], key=3,
exp="Run the checklist: rate normal, P before every QRS, PR normal, QRS narrow, QT normal, no pre-excitation, no ST changes → a <b>normal ECG</b>. The lecturer: \"<b>the hardest ECG you'll ever see is the normal one</b>.\" On an exam you'll wonder why they're showing you a healthy young woman, and sometimes the answer really is normal. Context matters: this is a routine office visit in pregnancy, not the trauma bay. Normal ECGs come as a family, including juvenile T waves, early repolarization and athlete's changes.<br><br><b>Educational objective:</b> Always run the checklist (rate, rhythm, P for every QRS, intervals, axis) and be willing to call a normal ECG normal, especially in a low-risk clinical setting.",
wrong={0:"Flutter would show regular sawtooth atrial waves, and there are none here.",
1:"First-degree block needs a PR over 200 ms. Hers is normal.",
2:"LBBB needs a QRS of 120 ms or more with a broad R laterally. Her QRS is narrow.",
4:"WPW needs a short PR and a delta wave. Neither is present."},
eli5="Sometimes the trick is that there's no trick. Her heart rhythm, timing and shape are all normal. Being able to say 'this is normal' is a real skill."),

dict(img='Rartifact', cap='12-lead ECG',
stem="A 45-year-old man is found unresponsive on a medical ward. A nurse reaches him within a minute and feels a strong carotid pulse; his blood pressure is 128/76 mm Hg. He has a coarse tremor of all four limbs. An ECG is obtained immediately and is shown. The machine interpretation prints \"ventricular fibrillation?\"{FIG}Which of the following is the most appropriate next step?",
choices=["Begin chest compressions","Check lead placement and repeat the ECG","Deliver an unsynchronized defibrillation","Give intravenous amiodarone","Give intravenous magnesium sulfate"], key=1,
exp="High-frequency chaotic deflections in some leads, with other leads looking relatively ordered and a patient who has a <b>strong pulse and normal blood pressure</b>: this is <b>artifact</b>, not ventricular fibrillation. The lecture's rule is \"<b>garbage in, garbage out</b>.\" Causes are loose leads, shivering, or a tremor from a neurologic condition. The most important move is to <b>fix the leads and repeat the ECG</b>. The computer may still print a diagnosis, so don't trust it. Treat the patient, not the printout.<br><br><b>Educational objective:</b> Chaotic deflections in a patient with a pulse and a normal blood pressure are artifact. Check the leads and repeat the ECG rather than treating the printout.",
wrong={0:"Chest compressions are for a pulseless patient. He has a strong pulse.",
2:"Defibrillating a perfusing rhythm could <b>cause</b> VF. His pulse and BP rule out VF.",
3:"Amiodarone treats a real ventricular arrhythmia, and there isn't one here.",
4:"Magnesium is for torsades de pointes. This is artifact."},
eli5="Real ventricular fibrillation means no pulse. This man has a strong pulse, so the messy squiggles are noise from his tremor or loose stickers. Fix the leads and take a new ECG."),

dict(img='Rsvt', cap='12-lead ECG',
stem="A 65-year-old man with cough and fever comes to urgent care because his palpitations, which he has had on and off since age 18, are worse. He has smoked 50 pack-years and has not seen a doctor in years. His pulse is 182/min and blood pressure is 128/78 mm Hg; he is alert. His ECG is shown. Carotid sinus massage (both carotids have been auscultated, with no bruits) does not change the rhythm.{FIG}Which of the following is the most appropriate next step?",
choices=["Adenosine 6 mg by rapid IV push","Immediate synchronized cardioversion","Intravenous amiodarone infusion","Intravenous procainamide infusion","Oral flecainide"], key=0,
exp="A <b>regular, narrow-complex tachycardia</b> at about 180 with <b>no visible P waves</b> (maybe a hint in lead III): fast + narrow + no visible P → it's coming from above the ventricles, an <b>SVT</b>, most likely typical <b>AVNRT</b> (P buried in the QRS). The acute algorithm for regular SVT:<br>1. Vagal maneuvers (carotid sinus massage) if stable.<br>2. <b>Adenosine 6 mg rapid IV push + flush</b>, then 12 mg if needed. It acts at the AV node, with a half-life under 5 seconds.<br>3. If stable and still in SVT, give an IV β-blocker, diltiazem or verapamil.<br>4. If unstable or refractory, synchronized cardioversion.<br><br><b>Educational objective:</b> For a stable regular narrow-complex SVT after failed vagal maneuvers, give adenosine 6 mg by rapid IV push with a flush (12 mg if needed).",
wrong={1:"Cardioversion is for the <b>unstable</b> patient or failure of drugs. He is alert with a good BP.",
2:"Amiodarone isn't in the acute regular-SVT algorithm taught here.",
3:"Procainamide is the drug for pre-excited AF (WPW), not a narrow regular SVT.",
4:"Oral flecainide is long-term rhythm control (only without structural disease), not acute termination."},
eli5="His heart is racing with a narrow, regular rhythm starting above the ventricles. Rubbing the carotid didn't work, so the next step is adenosine, which briefly blocks the AV node and usually snaps the rhythm back to normal."),

dict(img='Raf', cap='12-lead ECG with lead II rhythm strip',
stem="A 45-year-old man comes to the emergency department because of palpitations that began the morning after a weekend of heavy drinking. He has no other medical history. His blood pressure is 132/84 mm Hg. His ECG is shown.{FIG}Which of the following is the most likely rhythm?",
choices=["Atrial fibrillation","Atrial flutter with variable block","Multifocal atrial tachycardia","Sinus arrhythmia","Sinus rhythm with premature atrial beats"], key=0,
exp="<b>Irregularly irregular</b> R–R intervals, <b>narrow</b> QRS complexes and <b>no consistent P waves</b> (no two \"P waves\" look the same, and there is no isoelectric baseline) = <b>atrial fibrillation</b>. After a binge this is called \"holiday heart\" (a board add-on). Alcohol is a direct myocardial toxin with autonomic effects, and the lecture ranks it the #3 risk factor. AF is the most common arrhythmia in the world, and on exams it's usually a straightforward tracing. Next: assess duration, anticoagulation (CHA₂DS₂-VASc) and rate versus rhythm control, and treat the cause.<br><br><b>Educational objective:</b> An irregularly irregular narrow-complex rhythm without consistent P waves is atrial fibrillation. Heavy drinking is a classic trigger.",
wrong={1:"Flutter with variable block is irregular, but it shows uniform <b>sawtooth</b> flutter waves.",
2:"MAT has <b>distinct</b> P waves of at least three shapes before each QRS.",
3:"Sinus arrhythmia has an identical sinus P before every QRS, with rate varying with breathing.",
4:"Premature atrial beats interrupt an otherwise regular sinus rhythm with a visible P before each normal beat."},
eli5="After a heavy weekend of drinking, his upper heart chambers started quivering. The heartbeat is totally irregular and there are no proper P waves. That's atrial fibrillation, sometimes called 'holiday heart'."),

dict(img='Rflutter', cap='12-lead ECG',
stem="A 56-year-old man is brought to the emergency department with sudden left-sided weakness. CT of the head shows no hemorrhage. He has hypertension and diabetes mellitus. His ECG is shown.{FIG}Which of the following statements about managing his stroke risk from this rhythm is most accurate?",
choices=["Anticoagulate by the same risk profile as atrial fibrillation","Anticoagulation is not needed because flutter is organized","Aspirin alone is sufficient for this rhythm","Catheter ablation removes the need for any anticoagulation","Stroke risk is lower than in AF, so use half-dose anticoagulation"], key=0,
exp="The inferior leads show a <b>sawtooth</b> pattern: identical flutter waves in II, III and aVF → <b>typical atrial flutter</b>. The lecture's test trap is \"<b>it's only flutter</b>.\" Flutter gets the <b>same anticoagulation as AF</b>, using the same CHA₂DS₂-VASc risk profile (a guideline class 1 recommendation). Here, hypertension + diabetes + a stroke already mean anticoagulation. Flutter and AF are \"a family\": about half of typical-flutter patients go on to AF within ~2 years, and CTI ablation doesn't prevent that.<br><br><b>Educational objective:</b> Atrial flutter carries a thromboembolic risk and is anticoagulated using the same CHA₂DS₂-VASc criteria as atrial fibrillation.",
wrong={1:"An organized atrial rhythm still leaves the atria with poor mechanical function, and stroke risk is real.",
2:"Aspirin isn't adequate stroke prevention in AF or flutter with risk factors.",
3:"Ablation stops the flutter circuit but <b>doesn't prevent AF</b>, and anticoagulation still follows the risk profile.",
4:"Flutter isn't managed with \"half-dose\" anticoagulation. It uses the same criteria as AF."},
eli5="His upper chambers are looping around a circuit, the sawtooth pattern of atrial flutter. It can cause clots and strokes just like atrial fibrillation. Blood thinners are decided exactly the same way."),

dict(img='Rfl1to1', cap='12-lead ECG with lead II rhythm strip',
stem="A 42-year-old athlete with known atrial flutter takes flecainide as his only medication. He comes to the emergency department sweating and lightheaded after a hard training run. His pulse is 250/min and blood pressure is 96/64 mm Hg. The machine reads \"ventricular tachycardia, rate 250.\" His ECG is shown. After cardioversion, the arrhythmia is attributed to his medication regimen.{FIG}Addition of which of the following would most likely have prevented this episode?",
choices=["An AV-nodal blocking agent","A second class IC drug","A loop diuretic such as furosemide","A potassium supplement","Daily low-dose aspirin"], key=0,
exp="A regular wide-complex tachycardia at 250 in a patient with <b>flutter on flecainide</b>: this is <b>1:1 atrial flutter</b> with a <b>drug-widened QRS</b>, not VT. The QRS deflects rapidly at its onset, and the history is the clue. <b>Class IC drugs</b> (flecainide, propafenone) block Na⁺ channels and slow phase 0 → a wide QRS. They are <b>use-dependent</b> (more block at faster rates), so the QRS widens further in tachycardia. They also <b>slow the flutter circuit</b>, so the AV node, which normally handles only 2:1 at ~300/min, can now conduct <b>1:1</b>. The lecture's rule: <b>always give an AV-nodal blocker (β-blocker or CCB) with a class IC drug</b>.<br><br><b>Educational objective:</b> Class IC drugs can slow atrial flutter enough to allow 1:1 AV conduction with use-dependent QRS widening. Always pair them with an AV-nodal blocker.",
wrong={1:"Adding another Na⁺ channel blocker would worsen QRS widening and slowing.",
2:"A diuretic has no role in preventing 1:1 conduction.",
3:"Potassium matters for irritability, but it wouldn't stop the AV node conducting every flutter wave.",
4:"Aspirin doesn't affect conduction. Stroke prevention is a separate question."},
eli5="Flecainide slowed his flutter circuit just enough that the AV node could let every single flutter wave through, so the heart raced at 250. The drug also widened the beats. A pill that slows the AV node, like a beta-blocker, would have kept the gate partly closed."),

dict(img='Rvtcap', cap='12-lead ECG',
stem="A 64-year-old man comes to the emergency department because of presyncope. Echocardiography later shows a structurally normal heart. His pulse is 176/min and blood pressure is 104/70 mm Hg. His ECG is shown.{FIG}Which feature of this ECG most strongly supports the diagnosis?",
choices=["A single narrow beat among wide ones","Left axis deviation","QRS complexes with a sharp initial deflection","The regularity of the R–R intervals","The rate of about 176/min"], key=0,
exp="A <b>wide, ugly, regular tachycardia</b> with R-to-S of about 110–120 ms and some dissociated P waves, plus <b>one narrow complex</b> in the middle. That narrow beat is a <b>capture beat</b>: a sinus impulse (~70/min) sneaks through the AV node between VT beats (~160–176/min) and briefly captures the normal conduction system. It proves <b>AV dissociation</b> and is almost diagnostic of <b>VT</b> (seen in ~5%). The lecture says focus on <b>capture/fusion beats and AV dissociation</b> first. VT can occur in a structurally normal heart.<br><br><b>Educational objective:</b> A capture (or fusion) beat during a wide-complex tachycardia shows AV dissociation and strongly indicates ventricular tachycardia.",
wrong={1:"Axis can help (a northwest axis favors VT), but left axis alone isn't specific.",
2:"A <b>sharp</b> initial deflection favors SVT with aberrancy. VT is slurred from the first millisecond.",
3:"Regularity doesn't separate VT from SVT, and VT is often regular after the first ~20 beats.",
4:"Rate can't separate VT from SVT with aberrancy."},
eli5="Most beats here are wide and ugly, coming from the ventricles. But one normal narrow beat sneaks in because the top chamber's signal got through for a moment. That proves the ventricles are running on their own, so it's VT."),

dict(img='Rvtcad', cap='12-lead ECG with lead II rhythm strip',
stem="A 59-year-old man with coronary artery disease and a prior myocardial infarction is brought to the emergency department because of shortness of breath. He is diaphoretic and confused. His pulse is 168/min and blood pressure is 74/44 mm Hg. His ECG is shown.{FIG}Which of the following is the most appropriate immediate management?",
choices=["Adenosine 6 mg rapid IV push","Carotid sinus massage on one side","Intravenous diltiazem bolus","Oral metoprolol with observation","Sedation, then synchronized shock"], key=4,
exp="Very wide, ugly complexes (R-to-S about 140 ms) in a patient with <b>coronary disease and old infarct scar</b> → <b>VT</b>. The rule \"constantly on the test\" is: <b>wide and you can't tell → assume VT, treat as VT</b>. He is <b>unstable</b> (hypotension, confusion), so ACLS says <b>sedate and cardiovert</b> (synchronized, since there is a pulse). After cardioversion in the lecture case: sinus rhythm with a mildly wide QRS.<br><br><b>Educational objective:</b> An unstable patient with a wide-complex tachycardia, especially with structural heart disease, should be treated as VT with sedation and synchronized cardioversion.",
wrong={0:"Adenosine is for stable regular narrow SVT. It won't treat VT and delays definitive therapy in an unstable patient.",
1:"Vagal maneuvers target the AV node in SVT. They're inappropriate in unstable VT (and history of VT is a contraindication).",
2:"IV diltiazem in VT can cause hemodynamic collapse, since negative inotropy and vasodilation worsen shock.",
3:"Oral therapy is far too slow for an unstable arrhythmia."},
eli5="This is a fast, wide rhythm in a man with an old heart attack scar, so it's ventricular tachycardia until proven otherwise. His blood pressure is crashing and he's confused. The fix is to sedate him and shock the heart back into rhythm."),

dict(img='Rnegconc', cap='12-lead ECG',
stem="A 70-year-old man with a prior anterior myocardial infarction and an ejection fraction of 25% comes to the emergency department because of palpitations and lightheadedness. His blood pressure is 112/70 mm Hg. He has no prior ECG available. His ECG is shown.{FIG}Which of the following is the most likely rhythm?",
choices=["Atrial flutter with 2:1 block","Orthodromic AV re-entrant tachycardia","Sinus tachycardia with left bundle branch block","SVT with rate-related aberrancy","Ventricular tachycardia"], key=4,
exp="A wide, regular tachycardia whose QRS complexes are <b>negative in every precordial lead (V1 → V6)</b>: <b>negative precordial concordance</b>. Activation starts at the apex and moves away from every chest lead, which is virtually <b>diagnostic of VT</b>. His clinical picture favors VT too: <b>organic heart disease</b> (old infarct scar, EF 25%) sets up re-entry around scar. And the rule: wide + uncertain → treat as VT.<br><br><b>Educational objective:</b> Negative precordial concordance in a wide-complex tachycardia is virtually diagnostic of VT, especially with prior infarction and a low ejection fraction.",
wrong={0:"Flutter with 2:1 block is usually <b>narrow</b>, and it wouldn't give concordant negative complexes.",
1:"Orthodromic AVRT goes down the AV node, so it is <b>narrow</b>.",
2:"Sinus tachycardia with LBBB would show P waves and a typical LBBB pattern (with an RS in some chest leads), not uniform negativity.",
3:"Aberrancy produces a bundle-branch-type pattern with RS complexes. Concordance points to a ventricular origin."},
eli5="Every chest lead shows a big downward beat. That means the electrical wave starts at the bottom tip of the heart, down in the ventricles. With his old heart attack scar, this is ventricular tachycardia."),

dict(img='Rwpwaf', cap='12-lead ECG',
stem="A 25-year-old man has had self-limited episodes of palpitations for years. While driving, the palpitations don't stop and he feels lightheaded. In the emergency department his blood pressure is 125/60 mm Hg and he is alert. His ECG is shown.{FIG}Which of the following is the most appropriate pharmacotherapy?",
choices=["Adenosine","Diltiazem","Digoxin","Metoprolol","Procainamide"], key=4,
exp="A young man with a <b>wide, bizarre, irregular</b> tachycardia (QRS width varying beat to beat): <b>pre-excited AF</b> in <b>Wolff–Parkinson–White</b>. The lecture's analogy: the <b>AV node is a toll booth</b> that slows as the atria fire faster, while the <b>accessory pathway is an express lane</b> that conducts everything. Block the AV node and more impulses go down the pathway → very fast rates → VF. In his real case, AV-nodal blockers pushed the rate to ~227–300. So: <b>no adenosine, no calcium channel blockers, no β-blockers, no vagal maneuvers</b> (and no digoxin, a board add-on). Give <b>procainamide</b> (30 mg/min to a max of 17 mg/kg), or sedate and cardiovert, which is required if unstable.<br><br><b>Educational objective:</b> Pre-excited AF (WPW) is treated with procainamide or cardioversion. AV-nodal blockers are contraindicated because they divert conduction down the accessory pathway.",
wrong={0:"Adenosine blocks the AV node and can trigger AF that degenerates to VF in WPW.",
1:"Diltiazem blocks the AV node and pushes impulses down the accessory pathway.",
2:"Digoxin slows the AV node and can shorten the pathway's refractory period, which is dangerous (a board add-on).",
3:"β-blockers block the AV node, which is contraindicated in pre-excited AF."},
eli5="He has an extra electrical shortcut that skips the heart's natural speed limiter. If you slow down the normal route, even more signals race through the shortcut, which can become fatal. Procainamide slows the shortcut itself."),

dict(img='Rwpwafter', cap='12-lead ECG in sinus rhythm',
stem="A 23-year-old man applying to flight school has this ECG on screening. He has never had palpitations, lightheadedness, or syncope. There is no family history of sudden death. Physical examination is normal.{FIG}Which of the following is the most appropriate management?",
choices=["Immediate catheter ablation","Lifelong oral flecainide therapy","Yearly ECG and symptom education","Permanent pacemaker implantation","Start metoprolol and verapamil"], key=2,
exp="The ECG shows a <b>short PR</b> and a <b>delta wave</b> (slurred QRS upstroke) → ventricular <b>pre-excitation</b>. Without symptoms this is the <b>WPW pattern</b>, not the syndrome (which is the pattern plus arrhythmia). Numbers from the slides: the pattern is found in 0.15–0.25% of people, and in an aviation study only 1.8% of those with the pattern had arrhythmia. Sudden-death risk is 0–0.39%, lowest in asymptomatic patients. <b>Asymptomatic → observe with a yearly ECG</b> and teach the warning symptoms. An <b>EP study</b> is for symptomatic patients or high-risk situations (a pilot may need one for clearance).<br><br><b>Educational objective:</b> An asymptomatic WPW pattern is low risk and can be observed with yearly ECGs. Symptomatic WPW syndrome warrants an EP study and usually ablation.",
wrong={0:"Ablation is for symptomatic WPW syndrome or high-risk pathways found on EP study, not first-line for an asymptomatic pattern.",
1:"Lifelong antiarrhythmics aren't indicated for an asymptomatic pattern.",
3:"A pacemaker treats slow rhythms. Pre-excitation is the opposite problem.",
4:"AV-nodal blockers are dangerous if he ever develops AF with pre-excitation."},
eli5="His ECG shows a small electrical shortcut, the delta wave, but he's never had any symptoms from it. Most such people never do. So doctors watch him yearly and tell him what symptoms to report."),

dict(img='Rtorsades', cap='12-lead ECG',
stem="A 24-year-old runner collapses at a stadium and is reported to have \"had a seizure.\" His rhythm on arrival of the emergency team is shown. After an AED shock he returns to sinus rhythm with a markedly prolonged QT interval.{FIG}Which of the following mechanisms most likely initiated this arrhythmia?",
choices=["Delayed afterdepolarizations from Ca²⁺ overload","Early afterdepolarizations in a long phase 2–3","Enhanced automaticity of a junctional focus","Re-entry around an old infarct scar","Re-entry within the AV node"], key=1,
exp="Nothing looks the same beat to beat, and the QRS axis <b>twists around a point</b> at about 300/min: <b>torsades de pointes</b>, a polymorphic VT. The \"seizure\" was cerebral hypoperfusion. After the shock the QT is about 600 ms, so this is <b>congenital long QT syndrome</b>, usually a <b>K⁺ channel</b> defect in repolarization. A long phase 2–3 → <b>early afterdepolarizations (EADs)</b> → triggered activity → torsades. Acute treatment (a board add-on): IV magnesium, cardioversion if unstable, correct K⁺ and Mg²⁺, and stop QT-prolonging drugs.<br><br><b>Educational objective:</b> Torsades de pointes in long QT syndrome is initiated by early afterdepolarizations during a prolonged phase 2–3 of the action potential.",
wrong={0:"DADs follow <b>Ca²⁺ overload</b> after repolarization, the classic mechanism of <b>digoxin toxicity</b> and ischemic VT.",
2:"Junctional automaticity gives a narrow junctional tachycardia (JET), not polymorphic VT.",
3:"Scar re-entry produces <b>monomorphic</b> VT in patients with prior infarction.",
4:"AV nodal re-entry produces a narrow regular SVT (AVNRT)."},
eli5="His heart cells take too long to reset, so little extra bumps of voltage fire off before they finish. Those bumps set off a twisting, chaotic rhythm called torsades. He collapsed and shook, which looked like a seizure."),

dict(img='Rlqt', cap='12-lead ECG after resuscitation',
stem="The runner from the stadium is now in sinus rhythm; his post-shock ECG is shown. Genetic testing is sent, and his sister is referred for screening. While hospitalized he develops nausea.{FIG}Which of the following antiemetics should be avoided in this patient?",
choices=["Aprepitant","Dimenhydrinate","Meclizine","Ondansetron","Scopolamine patch"], key=3,
exp="The ECG shows a <b>markedly prolonged QT</b> (about 600 ms per the lecture) with normal PR and QRS. This is <b>congenital long QT syndrome</b> (~1 in 5,000, mostly autosomal dominant, LQT1–3 about 85–90%). The lecture's common QT-prolonging culprits are <b>antiemetics, antifungals and antidepressants (SSRIs)</b>. On top of genetic LQTS they can trigger torsades and sudden death. <b>Ondansetron</b> (a 5-HT3 antagonist) is a well-known QT-prolonging antiemetic. The Schwartz score combines ECG, clinical history and family history to estimate the probability of LQTS.<br><br><b>Educational objective:</b> Patients with long QT syndrome must avoid QT-prolonging drugs such as ondansetron, certain antifungals and SSRIs, which can precipitate torsades.",
wrong={0:"Aprepitant (an NK1 antagonist) isn't a notable QT-prolonging drug.",
1:"Dimenhydrinate (an antihistamine) isn't a classic QT culprit at usual doses.",
2:"Meclizine isn't a notable QT-prolonging antiemetic.",
4:"Scopolamine (anticholinergic) doesn't meaningfully prolong the QT."},
eli5="His heart already takes too long to reset between beats, the long QT. Some common anti-nausea medicines like ondansetron stretch the QT even more and could set off the dangerous rhythm again. So those have to be avoided."),

dict(img='Rbrugada', cap='12-lead ECG',
stem="A 38-year-old man is evaluated after an episode of nocturnal agonal breathing witnessed by his wife. His brother died suddenly in his sleep at age 34. Echocardiography shows a structurally normal heart. His ECG is shown.{FIG}The inherited condition suggested by this ECG primarily affects which of the following regions?",
choices=["Accessory AV pathway","Interventricular septum myocytes","Left atrial appendage","Right ventricular outflow tract","Sinoatrial node"], key=3,
exp="<b>Coved ST elevation in V1–V2</b> with a structurally normal heart, nocturnal events and a family history of sudden death in sleep → <b>Brugada syndrome</b>. The lecture's inherited-arrhythmia table: Brugada <b>mostly affects the right ventricular outflow tract</b> and produces coved ST elevation in V1–V2 (usually Na⁺ channel loss of function). Think of the genetic list after a young VT/VF arrest: long QT, short QT, WPW, Brugada, ARVC, and HCM (the most common).<br><br><b>Educational objective:</b> Brugada syndrome primarily affects the right ventricular outflow tract, producing coved ST elevation in V1–V2 and a risk of sudden death, often at night.",
wrong={0:"An accessory pathway is WPW (short PR and delta wave), not coved ST elevation.",
1:"Septal hypertrophy is <b>HCM</b>, which has a thick septum on echo. This heart is structurally normal.",
2:"The left atrial appendage is the source of AF-related clots, not Brugada.",
4:"Sinus node disease causes bradycardia, not coved ST elevation."},
eli5="This family has a faulty electrical channel mostly in the outlet part of the right ventricle. It makes a strange hump in leads V1–V2 and can trigger a deadly rhythm during sleep."),

dict(img='Rperi', cap='12-lead ECG',
stem="A 35-year-old woman comes to the emergency department because of chest pain for 1 day. The pain is sharp, worse with deep breaths and lying flat, and better when she sits up and leans forward. Two weeks ago she had a cold. Troponin is normal. Her ECG is shown.{FIG}Which of the following best distinguishes her diagnosis from an acute ST-elevation myocardial infarction?",
choices=["ST elevation confined to the inferior leads","ST elevation in every territory with PR depression","ST elevation with reciprocal depression in aVL","Tall peaked T waves in the precordial leads","Q waves in the leads with ST elevation"], key=1,
exp="The ECG looks nearly normal except the <b>ST segments are up everywhere</b>, not in one coronary territory, with <b>PR depression</b> (clear in V5–V6). With sharp, pleuritic, positional pain after a viral illness, this is <b>acute pericarditis</b>. Lecture pearls: lean on the <b>distribution</b> (diffuse), <b>PR depression</b> and the <b>history</b>, rather than the textbook \"concave\" shape. Diagnosis needs ≥2 of 4: typical pain, friction rub, widespread STE or PR depression, and new effusion. PR elevation in aVR and no reciprocal depression are board add-ons that also favor pericarditis.<br><br><b>Educational objective:</b> Pericarditis causes diffuse ST elevation across territories with PR depression, unlike the regional ST elevation with reciprocal changes of STEMI.",
wrong={0:"Elevation confined to one territory (inferior) points to <b>STEMI</b>.",
2:"Reciprocal ST depression is a sign of <b>STEMI</b>.",
3:"Tall peaked T waves suggest hyperacute ischemia or hyperkalemia.",
4:"Q waves in the involved leads indicate infarction."},
eli5="In a heart attack, the ST bumps sit over one artery's area and have mirror-image dips opposite. In pericarditis the whole sac around the heart is inflamed, so the bumps show up in almost every lead, along with a dipped PR segment."),

dict(img='Ravnrt', cap='12-lead ECG',
stem="A 29-year-old woman comes to the emergency department with sudden-onset palpitations. Her pulse is 188/min and blood pressure is 118/74 mm Hg. Her ECG is shown.{FIG}Which of the following best explains why P waves are not clearly visible on this tracing?",
choices=["Atria and ventricles activate together","Atrial activity is chaotic without organized depolarization","Retrograde conduction through the AV node is blocked","The atria are not being activated at all","The P waves are hidden in the preceding T waves because of 2:1 block"], key=0,
exp="A <b>regular narrow-complex tachycardia</b> at about 190 with <b>no visible P waves</b> → <b>typical AVNRT</b>, the lecture's \"2nd most common arrhythmia.\" A premature beat finds the fast pathway refractory, so it conducts <b>down the slow pathway</b>, then <b>back up the fast pathway</b> → the atria (retrograde) and ventricles are <b>activated at the same time</b> → the P wave is <b>buried in the QRS</b>. A narrow regular tachycardia with no visible P is a very common tip-off for AVNRT. It uses the AV node, so vagal maneuvers or adenosine can break it.<br><br><b>Educational objective:</b> In typical AVNRT (down the slow pathway, up the fast pathway), atria and ventricles depolarize simultaneously, so the P wave is hidden in the QRS.",
wrong={1:"Chaotic atrial activity is <b>AF</b>, which is irregular. This rhythm is regular.",
2:"If retrograde conduction were blocked, the circuit couldn't sustain itself.",
3:"The atria are activated, retrogradely, just at the same moment as the ventricles.",
4:"Hidden P waves from <b>2:1 block</b> fit flutter or atrial tachycardia at a lower ventricular rate, not AVNRT's simultaneous activation."},
eli5="The signal loops in a tiny circle inside the AV node. Each lap fires the upper and lower chambers at the same instant, so the P wave hides inside the big QRS spike."),

dict(img='Radenofl', cap='Rhythm strips before and after adenosine 6 mg and 12 mg (handwritten notes by the treating team)',
stem="A 68-year-old woman has a regular narrow-complex tachycardia at 151/min that persists despite IV metoprolol. Adenosine 6 mg and then 12 mg are given by rapid IV push. The rhythm strips are shown.{FIG}What does the response to adenosine indicate?",
choices=["Adenosine failed because the dose was too low","The rhythm is AV nodal re-entrant tachycardia","Atrial flutter that doesn't need the AV node","The rhythm is sinus tachycardia","The rhythm is ventricular tachycardia"], key=2,
exp="During the transient AV block from adenosine, the QRS complexes \"peter out\" and <b>regular flutter waves are unmasked</b>, but the atrial rhythm itself doesn't stop. That means the rhythm <b>doesn't depend on the AV node</b>: <b>atrial flutter</b>. Adenosine here is <b>diagnostic, not therapeutic</b>. It breaks AVNRT and AVRT, which use the AV node, but not every SVT. A regular rate near 150 is the classic clue for flutter with 2:1 block.<br><br><b>Educational objective:</b> Adenosine terminates AV-node-dependent SVTs (AVNRT, AVRT) but only unmasks flutter waves in atrial flutter, where it is diagnostic rather than curative.",
wrong={0:"12 mg is the full dose. The failure to terminate reflects the mechanism, not the dose.",
1:"AVNRT uses the AV node and would <b>terminate</b> with adenosine.",
3:"Sinus tachycardia would slow transiently and show sinus P waves, not a flutter baseline.",
4:"VT wouldn't show regular atrial flutter waves when AV conduction is blocked (and adenosine rarely affects VT)."},
eli5="Adenosine briefly shut the AV gate, and underneath the fast beats was a sawtooth pattern of flutter waves that kept going. So the rhythm lives in the atria and doesn't need the AV node. Adenosine just revealed it."),

dict(img='Rafrvr', cap='12-lead ECG',
stem="A 34-year-old woman comes to the emergency department because of palpitations and fatigue. For 2 months she has had heat intolerance, tremor, and a 6-kg (13-lb) weight loss. Her pulse is 142/min and blood pressure is 128/70 mm Hg. Serum TSH is undetectable. Her ECG is shown.{FIG}Which of the following is the most appropriate initial treatment for her heart rate?",
choices=["Adenosine","Amiodarone","Digoxin","Propranolol","Synchronized cardioversion"], key=3,
exp="The ECG shows <b>AF with a rapid ventricular response</b> (irregularly irregular, narrow, no P waves). With tremor, weight loss, heat intolerance and a <b>suppressed TSH</b>, the trigger is <b>thyrotoxicosis</b>, one of the lecture's board favorites (\"AF + thyrotoxicosis\"). It is often <b>reversible</b>: rate control with a <b>β-blocker</b> while the thyroid is treated. Propranolol also blunts the adrenergic symptoms. Always ask \"what else is going on?\" (thyroid, electrolytes, infection, alcohol).<br><br><b>Educational objective:</b> AF triggered by thyrotoxicosis is treated first with β-blocker rate control while the hyperthyroidism is addressed.",
wrong={0:"Adenosine won't terminate AF. It only briefly slows the ventricular rate.",
1:"Amiodarone contains iodine and can worsen thyroid disease. It isn't first-line here.",
2:"Digoxin works poorly in high-sympathetic states like thyrotoxicosis.",
4:"Cardioversion is for instability, and AF usually recurs while she remains thyrotoxic."},
eli5="An overactive thyroid is flooding her body with hormone, which set off atrial fibrillation. A beta-blocker slows the heart and calms the shaky, sweaty symptoms while doctors treat the thyroid itself."),
]
