# ECG II: Clinical ECG Reading & Arrhythmias — Version 0, 15 concept items (4 with ECGs). Easier, short stems.
Q = [
dict(img=None,
stem="The lecturer says \"SVT is a category, not a diagnosis.\"{FIG}Which of the following is the most common supraventricular tachycardia?",
choices=["Atrial flutter","AV nodal re-entrant tachycardia","Junctional ectopic tachycardia","Multifocal atrial tachycardia","Sinus tachycardia"], key=4,
exp="The SVT family: <b>sinus tachycardia</b> (the <b>most common SVT</b>, so always ask why: fever, pain, anemia, hypovolemia, hyperthyroidism), atrial tachycardia (one irritable focus), flutter and AF, <b>AVNRT</b> (which the lecturer called the 2nd most common arrhythmia), junctional ectopic tachycardia (uncommon, mostly children), and AVRT (using an accessory pathway, as in WPW). \"SVT\" only tells you the rhythm starts above the ventricles. You still need the specific diagnosis.<br><br><b>Educational objective:</b> Sinus tachycardia is the most common SVT, so always look for its cause. \"SVT\" is a category, not a diagnosis.",
wrong={0:"Flutter is common but less so than sinus tachycardia.",
1:"AVNRT is the most common <b>paroxysmal re-entrant</b> SVT, but sinus tachycardia is more common overall.",
2:"Junctional ectopic tachycardia is uncommon, seen mostly in children.",
3:"MAT is associated with lung disease and is relatively uncommon."},
eli5="'SVT' just means a fast rhythm starting above the ventricles. The most common one is simply the normal pacemaker running fast, sinus tachycardia, so you ask what's driving it."),

dict(img=None,
stem="A hospitalist wants to know which sustained arrhythmia she is most likely to encounter across surgery, primary care, obstetrics, and the ICU.{FIG}Which arrhythmia is the most common in the United States and worldwide?",
choices=["Atrial fibrillation","Atrial flutter","AV nodal re-entrant tachycardia","Torsades de pointes","Ventricular tachycardia"], key=0,
exp="<b>Atrial fibrillation</b> is the <b>most common arrhythmia</b> in the US and the world, found in surgery (post-op AF), primary care, obstetrics and the ICU (up to 15% of medical ICU patients). \"You will not escape AF.\" Its two big dangers are <b>stroke</b> and <b>heart failure</b>. Wearables now flag it from R–R irregularity.<br><br><b>Educational objective:</b> Atrial fibrillation is the most common sustained arrhythmia, and its main dangers are stroke and heart failure.",
wrong={1:"Flutter is common but much less so than AF.",
2:"AVNRT is the most common paroxysmal re-entrant SVT, not the most common arrhythmia overall.",
3:"Torsades is a rare polymorphic VT tied to long QT.",
4:"VT is much less common and usually occurs with structural heart disease."},
eli5="Atrial fibrillation is the heart rhythm problem doctors see most, in every specialty. It matters because it can cause strokes and weaken the heart."),

dict(img=None,
stem="Arrhythmias arise from abnormal automaticity, triggered activity, or re-entry.{FIG}Which mechanism is the most common, especially in SVT?",
choices=["Delayed afterdepolarizations","Early afterdepolarizations","Enhanced automaticity","Parasystole","Re-entry"], key=4,
exp="The three mechanisms:<br>• <b>Automaticity</b>: a focus fires too fast or where it shouldn't (atrial tachycardia, junctional ectopic tachycardia).<br>• <b>Triggered activity</b>: EADs (long QT → torsades) or DADs (digoxin, ischemic VT/VF).<br>• <b>Re-entry</b>: a <b>short circuit between two pathways</b> with different conduction and refractory properties. It is the <b>most common</b>, especially in SVT: AVNRT, AVRT, flutter and scar VT.<br><br><b>Educational objective:</b> Re-entry, a circuit between two pathways with different properties, is the most common arrhythmia mechanism, especially in SVT.",
wrong={0:"DADs are triggered activity, classically from digoxin toxicity or ischemia, and they are less common.",
1:"EADs cause torsades in long QT, and they are not the main SVT mechanism.",
2:"Automaticity explains focal atrial and junctional tachycardias, not most SVTs.",
3:"Parasystole is a rare independent ectopic focus."},
eli5="Most fast rhythms are caused by an electrical signal getting stuck going round and round a loop, called re-entry. It's like a car stuck in a traffic circle."),

dict(img=None,
stem="A 27-year-old woman has a regular narrow-complex tachycardia at 190/min with no visible P waves. The diagnosis is typical AV nodal re-entrant tachycardia.{FIG}Why are the P waves not visible?",
choices=["The atria are not depolarizing","Atria and ventricles fire together","The P waves are too small to record","The P waves fall after every T wave","There is complete AV block"], key=1,
exp="In typical <b>AVNRT</b>, the impulse goes <b>down the slow pathway</b> and <b>up the fast pathway</b> inside the AV node. So the <b>atria (activated backward) and the ventricles fire at the same time</b>, and the P wave is <b>buried inside the QRS</b>. A narrow, regular tachycardia with no visible P waves is a very common tip-off for AVNRT.<br><br><b>Educational objective:</b> In typical AVNRT the atria and ventricles depolarize simultaneously, so the P wave is hidden in the QRS.",
wrong={0:"The atria are depolarizing, backward, at the same instant as the ventricles.",
2:"P waves are normally visible. Their timing hides them here.",
3:"A P wave after the T is the pattern of some other SVTs, not typical AVNRT.",
4:"Complete block would dissociate P waves and QRS complexes, and the re-entry circuit needs conduction."},
eli5="The signal loops inside the AV node and fires the upper and lower chambers at the exact same moment. The small P wave hides inside the big QRS spike."),

dict(img=None,
stem="A stable patient with a regular narrow-complex SVT is given a rapid IV push of adenosine 6 mg followed by a saline flush.{FIG}Where does adenosine mainly act to stop this arrhythmia?",
choices=["Accessory pathway","AV node","Pulmonary veins","SA node","Ventricular myocardium"], key=1,
exp="<b>Adenosine</b> acts mainly at the <b>AV node</b>, briefly slowing or blocking conduction so that re-entry circuits that use the node (AVNRT, AVRT) break. Dose: <b>6 mg rapid push + flush</b>, then 12 mg. Its half-life is <b>under 5 seconds</b>, so it doesn't accumulate. Side effects: flushing, chest pain, hypotension, and a few seconds of asystole. Avoid it in heart transplant recipients (prolonged asystole) and WPW (it can trigger AF → VF).<br><br><b>Educational objective:</b> Adenosine terminates AV-node-dependent SVT by transiently blocking AV nodal conduction. Its half-life is under 5 seconds.",
wrong={0:"Adenosine doesn't block the accessory pathway, which is why it's dangerous in WPW.",
2:"The pulmonary veins are the source of AF triggers.",
3:"Adenosine can slow the SA node, but its therapeutic target is the AV node.",
4:"Adenosine has little effect on ventricular muscle."},
eli5="Adenosine briefly shuts the AV node, the gate between upper and lower chambers. If the fast rhythm needs that gate to loop, closing it for a moment breaks the loop."),

dict(img=None,
stem="Carotid sinus massage is attempted in a stable patient with a narrow regular tachycardia.{FIG}Through which of the following mechanisms does carotid sinus massage terminate AV nodal re-entry?",
choices=["Blocking β1 receptors on the SA node","Increasing vagal tone at the AV node level","Releasing adenosine from the carotid body","Stimulating carotid body chemoreceptors","Stimulating sympathetic outflow to the ventricles"], key=1,
exp="Pressure on the <b>carotid sinus</b> stimulates its <b>baroreceptors</b> (glossopharyngeal nerve, CN IX afferent) → the brainstem responds with <b>vagal (parasympathetic) outflow</b> → slower AV-node conduction → re-entry through the node can break. \"Patients think you're a wizard, but it's just physiology.\" Note that it's the carotid <b>sinus</b>, not the carotid body (a chemoreceptor); the recording's slip. Listen for bruits first, and don't do it after a recent stroke or TIA.<br><br><b>Educational objective:</b> Carotid sinus massage stimulates baroreceptors and increases vagal tone, slowing AV-node conduction to terminate AVNRT.",
wrong={0:"Massage doesn't block β-receptors. It increases vagal tone.",
2:"The carotid body doesn't release adenosine.",
3:"The carotid body is a <b>chemoreceptor</b> (O₂, CO₂, pH), not the target of massage.",
4:"Massage <b>reduces</b> sympathetic and increases vagal tone."},
eli5="Pressing on the carotid sinus fools the body into thinking blood pressure is high. The brain responds by turning up the vagus nerve, which slows the AV node and can stop the racing rhythm."),

dict(img='Lafrvr', cap='12-lead ECG with lead II rhythm strip',
stem="A 76-year-old man comes to the emergency department because of breathlessness. His ECG is shown.{FIG}Which of the following is the most likely rhythm?",
choices=["Atrial fibrillation","Atrial flutter with 2:1 block","Sinus tachycardia","Torsades de pointes","Ventricular tachycardia"], key=0,
exp="<b>Irregularly irregular</b> narrow complexes, <b>no P waves</b>, and a wavy baseline without a flat isoelectric line = <b>atrial fibrillation</b>, here with a rapid ventricular response. Remember that the most common AF symptoms are <b>fatigue and shortness of breath</b>. Only about half of patients notice palpitations.<br><br><b>Educational objective:</b> Atrial fibrillation is irregularly irregular with no P waves. Its most common symptoms are fatigue and dyspnea.",
wrong={1:"Flutter with 2:1 block is <b>regular</b> at about 150, with sawtooth waves.",
2:"Sinus tachycardia is regular, with a P before every QRS.",
3:"Torsades is a <b>wide</b>, twisting polymorphic VT.",
4:"VT is a <b>wide</b>-complex tachycardia."},
eli5="The beats come at completely random times and there are no proper P waves, just a wobbly line. That's atrial fibrillation."),

dict(img=None,
stem="Typical atrial flutter is a macro-re-entry circuit that runs counterclockwise around a heart valve.{FIG}In which chamber, and around which structure, does typical flutter circulate?",
choices=["Left atrium, around the mitral valve","Left atrium, around the pulmonary veins","Left ventricle, around the mitral annulus","Right atrium, around the tricuspid valve","Right ventricle, around the pulmonary valve"], key=3,
exp="Typical (type I) flutter runs <b>counterclockwise around the tricuspid valve</b> in the <b>right atrium</b>, up the septum. It depends on the <b>cavotricuspid isthmus</b> (between the IVC and the tricuspid annulus), which is why it is called \"isthmus-dependent\" and why <b>CTI ablation</b> cures it. On the ECG you see negative sawtooth waves in II, III and aVF and positive ones in V1. The atrial rate is about 250–300, often with 2:1 conduction (ventricular rate ~150).<br><br><b>Educational objective:</b> Typical atrial flutter is a right-atrial circuit around the tricuspid valve, through the cavotricuspid isthmus.",
wrong={0:"Mitral annular flutter is an <b>atypical</b> left-atrial flutter.",
1:"The pulmonary veins trigger AF, not typical flutter.",
2:"Ventricular circuits cause VT, not flutter.",
4:"Flutter is an atrial rhythm."},
eli5="Typical flutter is a signal circling the tricuspid valve in the right atrium, like a car going round a roundabout. Cutting the road at one narrow spot, the isthmus, stops it."),

dict(img='Raflutter', cap='12-lead ECG',
stem="A 64-year-old woman comes to the emergency department with palpitations. Her pulse is regular at about 150/min. Her ECG is shown.{FIG}Which of the following is the most likely rhythm?",
choices=["Atrial flutter with 2:1 block","AV nodal re-entrant tachycardia","Multifocal atrial tachycardia","Sinus tachycardia","Ventricular tachycardia"], key=0,
exp="A regular narrow tachycardia at about <b>150</b> with a sawtooth baseline in the inferior leads = <b>atrial flutter with 2:1 block</b>. The atria run at about 300/min, and the AV node \"can handle half of those\" → a fixed 2:1 → ventricular rate ~150. Days of this can cause a <b>tachycardia-mediated cardiomyopathy</b>. When you see a regular rate of 150, look for flutter waves. Flutter is anticoagulated like AF, and CTI ablation is the usual long-term fix.<br><br><b>Educational objective:</b> A regular narrow tachycardia at about 150/min with sawtooth waves is atrial flutter with 2:1 AV block.",
wrong={1:"AVNRT has no visible atrial waves and usually a faster rate. There is no sawtooth baseline.",
2:"MAT is <b>irregular</b>, with at least three distinct P-wave shapes.",
3:"Sinus tachycardia has normal P waves, not a sawtooth baseline.",
4:"VT is <b>wide</b>-complex."},
eli5="The top chambers are running at about 300, and the AV node lets every second beat through, giving a steady 150. The sawtooth pattern in the bottom leads is the flutter giveaway."),

dict(img='Rvtmono', cap='12-lead ECG',
stem="A 68-year-old man with prior myocardial infarction presents with palpitations. His ECG is shown. You are not sure whether this is VT or SVT with aberrancy, and he has no prior ECG for comparison.{FIG}According to the lecture's rule, how should this rhythm be treated?",
choices=["As SVT, with adenosine and diltiazem","Treat as VT until proven otherwise","As sinus tachycardia, by treating the cause","With carotid sinus massage first","With observation until a prior ECG is found"], key=1,
exp="A <b>wide-complex tachycardia</b> (QRS ≥120 ms). The rule that is \"constantly on the test\" is: <b>if it's wide and you can't tell, assume VT, treat it as VT, and figure it out later</b>. If the patient is unstable → sedate and cardiovert (ACLS). \"Nobody will ever mark you wrong for treating SVT-with-LBBB as VT.\" His prior infarct (scar) makes VT even more likely.<br><br><b>Educational objective:</b> An uncertain wide-complex tachycardia should be treated as ventricular tachycardia until proven otherwise.",
wrong={0:"AV-nodal drugs such as diltiazem can cause collapse if the rhythm is VT.",
2:"This isn't sinus tachycardia. It's wide and regular without clear P waves.",
3:"History of VT is an absolute contraindication to carotid massage, and it won't treat VT.",
4:"Waiting for an old ECG delays treatment of a potentially lethal rhythm."},
eli5="Wide, fast beats can come from the ventricles (dangerous) or from above with a wiring delay. If you can't tell, assume the dangerous one and treat it as VT. That's always the safe choice."),

dict(img=None,
stem="A 22-year-old man with known Wolff–Parkinson–White syndrome develops a fast, irregular, wide-complex tachycardia.{FIG}Which group of drugs must be avoided?",
choices=["AV-nodal blockers","Class IA antiarrhythmics","Intravenous magnesium","Oral anticoagulants","Sedatives for cardioversion"], key=0,
exp="In <b>WPW</b> the AV node is a \"toll booth\" that slows conduction, while the accessory pathway is an \"express lane\" that conducts everything. In pre-excited AF, <b>blocking the AV node</b> (adenosine, calcium channel blockers, β-blockers, and vagal maneuvers) sends <b>more impulses down the pathway</b> → very fast rates → VF. So <b>no AV-nodal blockers</b>. Give <b>procainamide</b> (a class IA drug), or sedate and cardiovert.<br><br><b>Educational objective:</b> AV-nodal blockers are contraindicated in WPW with pre-excited AF. Use procainamide or cardioversion.",
wrong={1:"Procainamide, a class IA drug, is the drug of choice.",
2:"Magnesium is for torsades. It isn't the danger here.",
3:"Anticoagulation decisions are separate and aren't contraindicated.",
4:"Sedation is used for cardioversion, which is appropriate."},
eli5="In WPW there's an extra shortcut that skips the heart's speed limiter. Drugs that block the normal route push more signals through the shortcut, which can be deadly. So those drugs are off-limits."),

dict(img=None,
stem="An ECG in sinus rhythm shows a PR interval of 100 ms and a slurred upstroke at the start of the QRS complex.{FIG}Which of the following best explains the slurred upstroke?",
choices=["Delayed conduction in the left bundle branch","Early activation via an accessory pathway","Enhanced automaticity of the AV node","Prolonged repolarization of the ventricles","Slowed conduction through the AV node"], key=1,
exp="An <b>accessory pathway</b> (bundle of Kent) bypasses the AV node, which removes the isoelectric PR segment → a <b>short PR</b>. The ventricle it enters is activated early and slowly, cell to cell → a slurred upstroke, the <b>delta wave</b> (\"pre-excitation\") → a slightly wide QRS. That's the <b>WPW pattern</b>. With arrhythmia it's WPW syndrome. Orthodromic AVRT (down the node, up the pathway) is narrow, and antidromic (down the pathway) is wide.<br><br><b>Educational objective:</b> The delta wave reflects early, slow ventricular activation through an accessory pathway that bypasses the AV node, which also shortens the PR.",
wrong={0:"Left bundle delay widens the QRS throughout, with a normal PR.",
2:"AV node automaticity would cause junctional rhythm, not a short PR with a delta wave.",
3:"Prolonged repolarization is long QT, a T-wave problem.",
4:"Slowed AV conduction <b>lengthens</b> the PR."},
eli5="There's an extra electrical wire that skips the AV node's delay. Part of the ventricle starts firing early and slowly, which makes a ramp at the start of the QRS (the delta wave) and a short PR."),

dict(img='Ltdp', cap='Rhythm strip',
stem="A 60-year-old man with a markedly prolonged QT interval collapses on telemetry. His rhythm strip is shown.{FIG}Which of the following is the most likely rhythm?",
choices=["Atrial fibrillation","Monomorphic ventricular tachycardia","Sinus tachycardia","Torsades de pointes","Ventricular fibrillation"], key=3,
exp="A wide polymorphic rhythm whose QRS amplitude <b>twists around the baseline</b>, growing and shrinking, in a patient with a <b>long QT</b> = <b>torsades de pointes</b>. Mechanism: a prolonged phase 2–3 → <b>early afterdepolarizations</b> → triggered activity. Treatment (a board add-on): <b>IV magnesium</b>, cardioversion if unstable, correct K⁺ and Mg²⁺, and stop QT-prolonging drugs (antiemetics, antifungals, SSRIs).<br><br><b>Educational objective:</b> Torsades de pointes is a polymorphic VT that twists around the baseline in the setting of a long QT.",
wrong={0:"AF is narrow and irregularly irregular, not a twisting wide rhythm.",
1:"Monomorphic VT has <b>identical</b> wide complexes beat to beat.",
2:"Sinus tachycardia is narrow with P waves.",
4:"VF is chaotic without organized complexes. Torsades has a recognizable twisting pattern (though it can degenerate to VF)."},
eli5="The beats twist up and down around the baseline like a ribbon, getting bigger then smaller. That's torsades de pointes, which happens when the heart takes too long to reset (a long QT)."),

dict(img=None,
stem="A 30-year-old man has sharp chest pain that improves when he leans forward. His ECG shows ST elevation in almost every lead with PR-segment depression.{FIG}Which of the following is the most likely diagnosis?",
choices=["Acute pericarditis","Acute pulmonary embolism","Anterior ST-elevation myocardial infarction","Brugada syndrome","Early repolarization"], key=0,
exp="<b>Diffuse</b> ST elevation (not in one coronary territory) + <b>PR depression</b> + sharp, pleuritic, positional pain (better sitting up and leaning forward) = <b>acute pericarditis</b>. The lecture leans on distribution, PR depression and history rather than the textbook \"concave\" shape. Diagnosis needs ≥2 of 4: typical pain, rub, widespread STE or PR depression, and effusion.<br><br><b>Educational objective:</b> Diffuse ST elevation with PR depression and positional pleuritic pain indicates acute pericarditis rather than STEMI.",
wrong={1:"PE can cause tachycardia and right-heart strain patterns, not diffuse STE with PR depression.",
2:"STEMI causes <b>regional</b> ST elevation with reciprocal depression, usually with pressure-like pain.",
3:"Brugada shows coved ST elevation limited to V1–V2.",
4:"Early repolarization gives J-point elevation in young people without pleuritic pain or PR depression."},
eli5="When the sac around the heart is inflamed, the ST segments rise in nearly every lead and the PR segment dips. The pain is sharp and eases when leaning forward. That's pericarditis, not a heart attack."),

dict(img=None,
stem="An ECG from an alert patient with a good pulse shows chaotic high-frequency deflections in most leads, and the machine prints \"ventricular fibrillation?\"{FIG}Which of the following is the most appropriate first step?",
choices=["Deliver a defibrillation shock","Give intravenous amiodarone","Repeat the ECG after checking the leads","Start chest compressions","Trust the machine and call a code"], key=2,
exp="An alert patient with a good pulse cannot be in VF, so this is <b>artifact</b>: loose leads, shivering or tremor. The lecture: \"<b>garbage in, garbage out</b>.\" The most important move is to <b>check the leads and repeat the ECG</b>. The computer may still print a diagnosis, so don't trust it. Always treat the patient, not the printout. The lecture expects a normal ECG and an artifact on the exam.<br><br><b>Educational objective:</b> Chaotic ECG deflections in an alert patient with a pulse are artifact. Fix the leads and repeat the ECG.",
wrong={0:"Shocking a perfusing rhythm is harmful. He has a pulse.",
1:"There's no real arrhythmia to treat.",
3:"Compressions are for a pulseless patient.",
4:"The machine read is wrong. Clinical assessment overrides it."},
eli5="If the patient is awake and has a strong pulse, the scary squiggles can't be real ventricular fibrillation. They're from loose wires or shaking. Fix the leads and record again."),
]
