# ECG II: Clinical ECG Reading & Arrhythmias — Version 1, 18 items (6 with ECGs)
Q = [
dict(img=None,
stem="An 18-year-old college basketball player has J-point elevation with a small notch at the end of the QRS complex in the lateral leads on a screening ECG. He is asymptomatic, and echocardiography is normal.{FIG}An imbalance in which of the following currents across the ventricular wall best explains this finding?",
choices=["Delayed-rectifier K⁺ current in the endocardium","Funny current (If) in the Purkinje fibers","L-type Ca²⁺ current in the endocardium","Na⁺ current in the mid-myocardial cells","Transient outward K⁺ current (Ito) in the epicardium"], key=4,
exp="This is <b>early repolarization</b>, usually a <b>normal variant</b> in young people and athletes. The endocardium, mid-myocardial (M) cells and epicardium repolarize at slightly different speeds. In early repolarization the <b>transient outward K⁺ current (Ito)</b>, which makes the phase 1 notch, is much larger in the <b>epicardium</b> than in the endocardium → a voltage gradient early in the action potential → <b>J-point elevation / a J wave</b>. The same mismatch underlies juvenile T waves.<br><br><b>Educational objective:</b> Early repolarization (J-point elevation, a J wave) reflects a larger transient outward K⁺ current (Ito) in the epicardium than in the endocardium.",
wrong={0:"IKr drives phase 3 repolarization. Its loss prolongs the QT (long QT), not the J point.",
1:"The funny current is a pacemaker (phase 4) current, unrelated to the J point.",
2:"L-type Ca²⁺ current sustains the plateau and doesn't produce the phase 1 J-wave gradient.",
3:"A Na⁺ current imbalance (loss) underlies Brugada's coved ST elevation in V1–V2, not benign early repolarization."},
eli5="The outer layer of his heart muscle resets a bit earlier than the inner layer because of a bigger potassium current there. That timing difference makes a small notch, the J wave. In young athletes it's usually harmless."),

dict(img='Ldig', cap='12-lead ECG with lead II rhythm strip',
stem="A 64-year-old woman with heart failure takes digoxin. Her ECG is shown. Two weeks later, after her dose is increased, she develops frequent ventricular premature beats and a run of ventricular tachycardia.{FIG}Which mechanism most likely underlies the new ventricular arrhythmia?",
choices=["Delayed afterdepolarizations from Ca²⁺ overload","Early afterdepolarizations from a prolonged QT interval","Enhanced automaticity of the SA node","Re-entry through an accessory pathway","Re-entry within the AV node"], key=0,
exp="The ECG shows the <b>digitalis effect</b>: a short QT and characteristic <b>down-sloping (\"reverse tick\") ST depression</b>, especially laterally. Digoxin inhibits the Na⁺/K⁺-ATPase → ↑ intracellular Na⁺ → less Ca²⁺ extruded by the Na⁺/Ca²⁺ exchanger → <b>intracellular Ca²⁺ overload</b> → <b>delayed afterdepolarizations (DADs)</b> just after repolarization → triggered ectopy and VT. The lecture notes that digoxin causes \"a whole host of arrhythmias\", test-writers love it, and DADs are its classic mechanism (a board add-on).<br><br><b>Educational objective:</b> Digoxin toxicity causes triggered arrhythmias through delayed afterdepolarizations from intracellular Ca²⁺ overload.",
wrong={1:"EADs come from a <b>prolonged</b> QT (long QT, hypokalemia). Digoxin <b>shortens</b> the QT.",
2:"Sinus node automaticity causes sinus tachycardia, not ventricular ectopy.",
3:"Accessory pathway re-entry is AVRT in WPW.",
4:"AV nodal re-entry is AVNRT, a narrow SVT."},
eli5="Digoxin makes heart cells hold onto too much calcium. After each beat, the extra calcium causes little late voltage bumps. Those can fire off extra beats from the ventricles, and even ventricular tachycardia."),

dict(img=None,
stem="In a patient with dual AV nodal pathways, a normal sinus beat conducts down both the fast and slow pathways without starting a tachycardia. A premature atrial beat, however, triggers a sustained narrow-complex tachycardia.{FIG}Which of the following best explains why the premature beat starts the tachycardia?",
choices=["Unidirectional block in the still-refractory fast pathway","It depolarizes the ventricles directly through an accessory pathway","It increases automaticity of the AV node","It shortens the refractory period of both pathways equally","It triggers a delayed afterdepolarization in the His bundle"], key=0,
exp="<b>Re-entry</b>, the most common mechanism (especially in SVT), needs two pathways with different properties:<br>• the <b>slow</b> pathway has <b>slow conduction and a short refractory period</b>;<br>• the <b>fast</b> pathway has <b>fast conduction and a long refractory period</b>.<br>A <b>premature beat</b> arrives while the fast pathway is still refractory → <b>unidirectional block</b> → it travels down the slow pathway → by the time it reaches the bottom, the fast pathway has recovered → it runs back up → it re-enters the slow pathway → a loop → tachycardia (typical AVNRT).<br><br><b>Educational objective:</b> Re-entry starts when a premature impulse meets unidirectional block in the pathway with the longer refractory period, travels down the other pathway, and returns up the recovered one.",
wrong={1:"An accessory pathway is AVRT in WPW, not dual AV nodal pathways.",
2:"Automaticity is a different mechanism (a focus firing too fast), not re-entry.",
3:"The asymmetry between the pathways, not an equal change, sets up the circuit.",
4:"DADs are triggered activity (digoxin, ischemia), not the mechanism of AVNRT."},
eli5="There are two lanes through the AV node, one quick to use but slow to reopen. An early beat finds the fast lane still closed, so it takes the slow lane. By the time it gets through, the fast lane has reopened, so it zooms back up, and round and round it goes."),

dict(img=None,
stem="A 70-year-old man with a narrow regular tachycardia at 176/min has stable blood pressure. He had a transient ischemic attack 6 weeks ago. The resident plans carotid sinus massage.{FIG}Which of the following is the most appropriate action?",
choices=["Avoid carotid sinus massage because of his recent TIA","Massage the carotid sinus on both sides simultaneously","Perform massage only if a bruit is heard","Proceed with 10–20 seconds of massage on the left side","Proceed without auscultation, since he is stable"], key=0,
exp="Carotid sinus massage fires a vagal (parasympathetic) reflex through the carotid sinus baroreceptors (CN IX afferent → vagal efferent), slowing AV-node conduction and breaking AVNRT. The recording said \"carotid body\", which is a slip. Technique: <b>listen to both carotids first</b>, then press firmly for 10–20 seconds with ECG and BP monitoring, <b>one side at a time</b>.<br><b>Absolute contraindications</b>: MI · <b>TIA or stroke in the last 3 months</b> · carotid occlusion · history of VF or VT · a previous bad reaction to massage. <b>Relative</b>: a carotid bruit (image first, because stenosis or plaque can occlude the vessel or embolize).<br>His TIA 6 weeks ago → <b>don't massage</b>. Move to adenosine.<br><br><b>Educational objective:</b> A TIA or stroke within 3 months is an absolute contraindication to carotid sinus massage. Always auscultate both carotids first and never massage both sides together.",
wrong={1:"Bilateral massage can cause profound bradycardia or cerebral ischemia. It is never done.",
2:"A bruit is a <b>reason to image first</b>, not a requirement to proceed, and his recent TIA already contraindicates massage.",
3:"His TIA within 3 months is an absolute contraindication.",
4:"Auscultation for bruits is always required first."},
eli5="Pressing on the neck artery can slow the heart, but it can also knock loose plaque and cause a stroke. He had a mini-stroke only 6 weeks ago, so it's too risky. Skip straight to medicine."),

dict(img='Radeno', cap='Continuous rhythm strip during and after adenosine 6 mg IV (handwritten notes by the treating team)',
stem="A 30-year-old woman with a narrow regular tachycardia receives adenosine 6 mg by rapid IV push. The continuous rhythm strip is shown; she converts to sinus rhythm.{FIG}As the drug wears off, the PR interval lengthens and some P waves are not followed by a QRS. Which of the following best explains this?",
choices=["Adenosine-induced atrial fibrillation","Complete heart block from His–Purkinje damage","Hyperkalemia from adenosine","Prolonged QT from adenosine","Fading AV nodal block from adenosine"], key=4,
exp="Adenosine acts mainly at the <b>AV node</b>, slowing conduction until the re-entry circuit breaks (half-life under 5 s, 6 mg then 12 mg). As it wears off over ~30 s, you often see a <b>Wenckebach-like pattern</b> (the PR lengthens, then a beat drops) before normal conduction returns. That is <b>transient AV nodal block</b>, not a new disease. Mechanism: the A1 receptor is Gi-coupled → ↓ cAMP and ↑ K⁺ efflux → AV node hyperpolarization (the recording's \"uptick in cAMP\" was a slip). Side effects: flushing, chest pain, hypotension and a few seconds of asystole.<br><br><b>Educational objective:</b> After adenosine terminates SVT, transient AV nodal block (PR prolongation and dropped beats) is expected as its effect wears off.",
wrong={0:"Adenosine can rarely trigger AF (especially dangerous in WPW), but lengthening PR with dropped beats isn't AF.",
1:"Adenosine's effect is transient and nodal. It doesn't cause His–Purkinje damage.",
2:"Adenosine doesn't raise potassium meaningfully.",
3:"The QT isn't the problem. The PR and AV conduction are."},
eli5="Adenosine briefly jams the AV node to stop the racing rhythm. As it wears off, the node is still sluggish for a few seconds, so signals are delayed or dropped. Then everything returns to normal."),

dict(img=None,
stem="A 58-year-old man with SVT is being considered for adenosine. He has asthma, hypertension, and a history of orthotopic heart transplantation 3 years ago.{FIG}Which of the following features is the strongest reason to avoid adenosine?",
choices=["His age of more than 55 years","Controlled hypertension","His heart transplant","Mild intermittent asthma","SVT lasting more than 1 hour"], key=2,
exp="Adenosine contraindications and cautions (lecture):<br>• <b>Heart transplant</b>: the <b>denervated heart is supersensitive</b> → risk of <b>prolonged asystole</b>. This is the key contraindication.<br>• <b>WPW</b>: it can trigger AF that degenerates to VF.<br>• Caution in <b>severe</b> reactive airway disease (bronchospasm) and ischemic heart disease.<br>Common side effects are facial flushing, chest pain, hypotension and a few seconds of asystole. Mild asthma is a caution, not the strongest reason.<br><br><b>Educational objective:</b> Adenosine is avoided in heart transplant recipients because the denervated heart is supersensitive and may have prolonged asystole.",
wrong={0:"Age alone isn't a contraindication.",
1:"Hypertension isn't a contraindication. Adenosine is a vasodilator.",
3:"<b>Severe</b> reactive airway disease is a caution. Mild asthma is less concerning than a transplant.",
4:"Duration of SVT doesn't contraindicate adenosine."},
eli5="A transplanted heart has lost its nerve connections and becomes extra sensitive to adenosine. A normal dose could stop it for a dangerously long time. That's the biggest reason to avoid it here."),

dict(img=None,
stem="A 60-year-old woman has two separate episodes of atrial fibrillation documented. The first stopped on its own after 5 days. The second has now been continuous for 3 weeks and required electrical cardioversion to restore sinus rhythm.{FIG}How should these two episodes be classified?",
choices=["Both paroxysmal","Both persistent","First paroxysmal, second long-standing persistent","First paroxysmal, second persistent","First persistent, second permanent"], key=3,
exp="AF definitions (know the first three for the wards):<br>• <b>Paroxysmal</b>: intermittent, <b>ends within ≤7 days</b> (by itself or with treatment).<br>• <b>Persistent</b>: continuous for <b>more than 7 days</b> and <b>needs intervention</b> (drug, cardioversion, procedure). It's still \"persistent\" even if therapy later makes it paroxysmal.<br>• <b>Long-standing persistent</b>: continuous for <b>more than 12 months</b>.<br>• <b>Permanent</b>: a <b>treatment decision</b> by patient and clinician to stop trying to restore sinus rhythm, not a disease state.<br>An episode currently counts as AF at ≥30 s.<br><br><b>Educational objective:</b> Paroxysmal AF ends within 7 days, persistent AF lasts more than 7 days and needs intervention, long-standing persistent AF lasts more than 12 months, and permanent AF is a decision to stop restoring rhythm.",
wrong={0:"The second episode lasted more than 7 days and needed cardioversion, so it's persistent.",
1:"The first episode ended on its own within 7 days, so it's paroxysmal.",
2:"Long-standing persistent requires more than 12 months of continuous AF.",
4:"Permanent is a joint decision to stop pursuing sinus rhythm. It isn't defined by duration."},
eli5="If AF stops within a week, it's paroxysmal. If it lasts longer than a week and needs treatment to stop, it's persistent. 'Permanent' just means everyone has agreed to stop trying to fix the rhythm."),

dict(img=None,
stem="A 76-year-old woman with hypertension and a prior transient ischemic attack is found to have atrial fibrillation. She has no heart failure, diabetes, or vascular disease.{FIG}What is her CHA₂DS₂-VASc score?",
choices=["2","3","4","5","6"], key=4,
exp="CHA₂DS₂-VASc: <b>C</b>ongestive heart failure 1 · <b>H</b>ypertension 1 · <b>A</b>ge ≥75 <b>2</b> · <b>D</b>iabetes 1 · <b>S</b>troke/TIA/thromboembolism <b>2</b> · <b>V</b>ascular disease 1 · <b>A</b>ge 65–74 1 · <b>S</b>ex category female 1.<br>Her total: hypertension 1 + age 76 (≥75) 2 + prior TIA 2 + female 1 = <b>6</b>. The lecture rule: a score of 2 or more usually means an anticoagulant (usually a DOAC). The next guideline drops the sex point (CHA₂DS₂-VA, which would give her 5), because female sex is a risk modifier rather than an independent risk factor.<br><br><b>Educational objective:</b> CHA₂DS₂-VASc assigns 2 points each for age ≥75 and prior stroke/TIA, and 1 each for heart failure, hypertension, diabetes, vascular disease, age 65–74 and female sex.",
wrong={0:"2 counts only the TIA (or only her age), not all her risk factors.",
1:"3 counts age ≥75 and TIA as 1 point each instead of 2, and adds hypertension.",
2:"4 misses one of the doubled items (age ≥75 or TIA is worth 2).",
3:"5 is her CHA₂DS₂-VA score (without the female-sex point), not CHA₂DS₂-VASc."},
eli5="Add up her stroke-risk points: 1 for high blood pressure, 2 for being over 75, 2 for her mini-stroke, and 1 for being female. That makes 6, which means she needs a blood thinner."),

dict(img='Laflut', cap='Rhythm strip',
stem="A 68-year-old woman taking digoxin reports lethargy. Her rhythm strip is shown. After her digoxin is adjusted, her cardiologist recommends a procedure to prevent recurrence of this rhythm.{FIG}The procedure will most likely target which of the following structures?",
choices=["AV node slow pathway","Bundle of Kent","Cavotricuspid isthmus","Pulmonary vein ostia","Right ventricular outflow tract"], key=2,
exp="Regular <b>sawtooth</b> atrial waves at about 300/min with a slow ventricular response (too much digoxin blocking the AV node) = <b>typical atrial flutter</b>. It is a <b>macro-re-entry circuit counterclockwise around the tricuspid valve</b> that depends on the <b>cavotricuspid isthmus</b> (CTI), the strip of tissue between the IVC and the tricuspid annulus. <b>CTI ablation</b> (the lecture's \"Jersey barrier in the traffic circle\") blocks the circuit, with about 99% acute bidirectional block using pulsed-field ablation. It is the usual long-term plan even after one episode. It doesn't prevent AF (about half develop AF within ~2 years).<br><br><b>Educational objective:</b> Typical atrial flutter is an isthmus-dependent right-atrial circuit, treated definitively with cavotricuspid isthmus ablation.",
wrong={0:"Slow-pathway modification treats <b>AVNRT</b>.",
1:"Ablating the bundle of Kent (accessory pathway) treats <b>WPW</b>.",
3:"Pulmonary vein isolation treats <b>AF</b>.",
4:"The RVOT is a site of idiopathic VT and Brugada, not flutter."},
eli5="Flutter is a signal running round and round a loop in the right atrium. The loop always passes through a narrow bridge near the tricuspid valve. Burning a line across that bridge blocks the loop for good."),

dict(img=None,
stem="A student asks why typical counterclockwise atrial flutter produces negative sawtooth waves in leads II, III, and aVF but positive flutter waves in V1.{FIG}Which of the following best explains this pattern?",
choices=["The flutter circuit runs clockwise, down the septum","It climbs the septum away from inferior leads","The impulse originates in the left atrium near the pulmonary veins","The lateral right atrial wall generates the largest vector","The ventricles, not the atria, generate the flutter waves"], key=1,
exp="An electrode sees current moving <b>toward</b> it as positive. In typical (counterclockwise) flutter the wave <b>climbs up the thick muscular septum</b>, <b>away from the feet</b> → <b>negative</b> flutter waves in the inferior leads (II, III, aVF), and <b>toward V1</b>, which sits high on the right chest → <b>positive</b> in V1. The thin lateral wall carries too little muscle to register much on the way back down. Clockwise flutter reverses the polarity.<br><br><b>Educational objective:</b> Counterclockwise typical flutter travels up the septum, so its waves are negative in II, III and aVF and positive in V1.",
wrong={0:"Clockwise flutter would produce the <b>opposite</b> polarity (positive inferiorly).",
2:"Pulmonary vein origin describes AF triggers, not typical flutter.",
3:"The thin lateral wall contributes little. The thick septum dominates the vector.",
4:"Flutter waves are atrial activity."},
eli5="In typical flutter, the electrical wave travels up the wall between the atria, away from the feet. Leads that look from below (II, III, aVF) see it moving away and show downward waves. V1, up on the chest, sees it coming and shows upward ones."),

dict(img=None,
stem="A 66-year-old man who underwent catheter ablation of the cavotricuspid isthmus for typical atrial flutter 3 months ago asks whether he is now cured of all atrial arrhythmias.{FIG}Which of the following is the most accurate counseling?",
choices=["About half develop atrial fibrillation within 2 years","Ablation also isolates the pulmonary veins, preventing AF","He can stop all monitoring because recurrence is impossible","Recurrent flutter is expected in most patients within weeks","His stroke risk is now permanently eliminated"], key=0,
exp="CTI ablation is very effective for typical flutter: in the lecture's pulsed-field data, 99.2% acute bidirectional block and 3.8% recurrence over a median of 114 days. But <b>it doesn't prevent AF</b>. Flutter and AF are \"a family\" in the same atria, and <b>about half of typical-flutter patients develop AF within ~2 years</b>. Warn patients, keep monitoring, and base anticoagulation decisions on stroke risk (CHA₂DS₂-VASc).<br><br><b>Educational objective:</b> Cavotricuspid isthmus ablation cures typical flutter but doesn't prevent atrial fibrillation, which develops in about half of patients within ~2 years.",
wrong={1:"CTI ablation is a right-atrial line. Pulmonary vein isolation is a separate AF procedure.",
2:"Recurrence (flutter or new AF) is possible, so monitoring continues.",
3:"Flutter recurrence after successful CTI ablation is uncommon (about 4% in the data shown).",
4:"Stroke risk follows his risk factors and any AF. Ablation doesn't eliminate it."},
eli5="Blocking the flutter loop works very well. But the same atria often go on to develop atrial fibrillation, in about half of people within two years. He still needs follow-up."),

dict(img='Lvtavd', cap='12-lead ECG with lead II rhythm strip',
stem="A 69-year-old man is readmitted 2 weeks after an inferior myocardial infarction because of palpitations and lightheadedness. His pulse is 205/min and blood pressure is 102/66 mm Hg. His ECG is shown.{FIG}Which of the following features of the clinical picture most strongly favors ventricular tachycardia over SVT with aberrancy?",
choices=["His age of more than 65 years","His recent myocardial infarction","The absence of any chest pain","The heart rate of about 205/min","The regularity of the rhythm"], key=1,
exp="A wide, regular tachycardia at about 205 → assume <b>VT</b> until proven otherwise. Of the clinical features, <b>organic heart disease</b>, especially <b>infarct scar</b> (2 weeks after an MI) or a low EF, most strongly favors VT, because scar creates re-entry circuits. Other clinical clues favoring VT are hypo- or hyperkalemia, hypoxia, acidosis, valve disease and drugs (digoxin, antiarrhythmics, TCAs). On the ECG, look for <b>AV dissociation</b> and capture or fusion beats (in this tracing P waves march independently), concordance, a northwest axis, and R-to-S over 100 ms (Brugada step 2).<br><br><b>Educational objective:</b> Structural heart disease, particularly recent or old myocardial infarction, strongly favors VT as the cause of a wide-complex tachycardia.",
wrong={0:"Age alone is weak, though VT is more common in older patients with heart disease.",
2:"The absence of chest pain doesn't separate VT from SVT.",
3:"Rate doesn't distinguish VT from SVT with aberrancy.",
4:"Both can be regular, and VT is often regular after the first ~20 beats."},
eli5="He just had a heart attack, which leaves scar tissue in the ventricle. Scar is the perfect track for a ventricular short-circuit. So a fast wide rhythm two weeks later is most likely ventricular tachycardia."),

dict(img='Rposconc', cap='Precordial leads V1–V6 during a wide-complex tachycardia',
stem="A 61-year-old man has a wide-complex tachycardia. His precordial leads are shown; the QRS complexes are wide and upright in every lead from V1 through V6.{FIG}This precordial pattern most strongly favors which of the following?",
choices=["Atrial flutter with 2:1 block","Sinus tachycardia with right bundle branch block","SVT with left bundle branch block aberrancy","Typical AVNRT","Ventricular tachycardia from the base"], key=4,
exp="<b>Positive precordial concordance</b>: every precordial QRS upright from V1 to V6. The activation starts at the <b>base of the heart</b> and moves <b>toward</b> all chest leads, which strongly suggests <b>VT</b> arising near the base. It could rarely be pre-excitation over a left-sided accessory pathway (antidromic AVRT or pre-excited AF). <b>Negative concordance</b> (all downward) means an apical origin and is virtually diagnostic of VT. Bundle branch aberrancy produces RS complexes in some chest leads rather than concordance.<br><br><b>Educational objective:</b> Positive precordial concordance in a wide-complex tachycardia strongly favors VT with a basal origin (or, less often, pre-excitation).",
wrong={0:"Flutter with 2:1 block is usually narrow and wouldn't produce concordant upright wide complexes.",
1:"RBBB produces an rSR′ in V1 and an RS pattern laterally, not uniform concordance.",
2:"LBBB aberrancy makes V1 negative and V6 positive, not all positive.",
3:"Typical AVNRT is a narrow-complex tachycardia."},
eli5="Every chest lead shows a tall upward wide beat. That means the electrical wave starts at the back and top of the heart and flows toward all the chest leads. That's a ventricular origin, so it's VT."),

dict(img=None,
stem="A resident applies the Brugada stepwise approach to a wide-complex tachycardia. RS complexes are present in several precordial leads, so step 1 is negative.{FIG}What is measured at step 2, and what value indicates ventricular tachycardia?",
choices=["PR interval · longer than 200 ms","QRS duration · longer than 120 ms","QT interval · longer than 500 ms","R-to-S interval · longer than 100 ms","R–R interval variability · more than 40 ms"], key=3,
exp="Brugada algorithm (1991) — the first \"yes\" diagnoses VT:<br>1. <b>No RS complex</b> in any precordial lead? → VT.<br>2. <b>R-to-S interval over 100 ms</b> in any precordial lead (from the <b>onset of the R</b> to the <b>nadir of the S</b>)? → VT.<br>3. <b>AV dissociation</b>? → VT.<br>4. Morphology criteria in V1–V2 and V6 → VT.<br>Sensitivity 0.987 and specificity 0.965 in 554 wide tachycardias. A prolonged R-to-S reflects the slow, cell-to-cell initial activation of VT. SVT with aberrancy starts on the fast conduction system, so its onset is sharp.<br><br><b>Educational objective:</b> In the Brugada algorithm, an R-to-S interval over 100 ms in any precordial lead indicates VT.",
wrong={0:"PR interval isn't part of the Brugada VT algorithm.",
1:"A QRS over 120 ms defines a <b>wide</b>-complex tachycardia, which is the starting point, not step 2.",
2:"The QT isn't used to separate VT from SVT.",
4:"R–R variability isn't a Brugada step, and VT can be irregular at first."},
eli5="Step 2 measures how long the beat takes to go from the start of its upswing to the bottom of its downswing. VT spreads slowly muscle-to-muscle, so that takes a long time, over 100 milliseconds."),

dict(img='Lwpwaf', cap='12-lead ECG with lead II rhythm strip',
stem="A 47-year-old man has a long history of palpitations and, lately, blackouts. His ECG during an episode is shown; his blood pressure is 118/72 mm Hg.{FIG}Which of the following is the most accurate statement about his management?",
choices=["An AV-nodal blocker would safely slow the rate","Carotid sinus massage is the preferred first maneuver","Intravenous diltiazem is the drug of choice","Procainamide or synchronized cardioversion is appropriate","This is torsades and requires intravenous magnesium"], key=3,
exp="A <b>fast, irregular, wide-complex</b> tachycardia with <b>varying QRS width</b> in a patient with years of palpitations and now blackouts → <b>pre-excited AF</b> (WPW syndrome). Impulses reach the ventricles through the accessory pathway, the AV node, or both (fusion), so QRS width varies. The lecture's key rule reverses the usual SVT algorithm: <b>no AV-nodal blockers</b> (adenosine, CCBs, β-blockers) and <b>no vagal maneuvers</b>, because blocking the node sends more impulses down the pathway → VF. Give <b>procainamide</b> (30 mg/min to a max of 17 mg/kg; stop for arrhythmia suppression, hypotension, or QRS widening ≥50%), or <b>sedate and cardiovert</b>. He needs an EP study and ablation.<br><br><b>Educational objective:</b> Pre-excited AF requires procainamide or cardioversion. AV-nodal blockers and vagal maneuvers are contraindicated.",
wrong={0:"AV-nodal blockers divert conduction down the accessory pathway and can precipitate VF.",
1:"Vagal maneuvers are AV-nodal blockade too, so they're contraindicated in WPW.",
2:"Diltiazem is an AV-nodal blocker, contraindicated in pre-excited AF.",
4:"Torsades twists around the baseline with a long QT. This is irregular pre-excitation with varying QRS width."},
eli5="His extra electrical shortcut is letting atrial fibrillation signals race straight into the ventricles. Blocking the normal route would push even more signals down the shortcut. So doctors use procainamide, or a shock, instead."),

dict(img=None,
stem="A newborn with cyanosis has a tricuspid valve whose septal and posterior leaflets are displaced downward into the right ventricle, creating an \"atrialized\" portion of the ventricle. An ECG shows a short PR interval and a delta wave.{FIG}This congenital lesion is most strongly associated with which of the following?",
choices=["Brugada syndrome","Congenital long QT syndrome","Hypertrophic cardiomyopathy","Short QT syndrome","Wolff–Parkinson–White syndrome"], key=4,
exp="Downward displacement of the tricuspid leaflets into the RV is <b>Ebstein anomaly</b>, the congenital lesion <b>most strongly associated with WPW</b> (accessory pathways, often right-sided). The short PR and delta wave confirm pre-excitation. Other lecture associations: most WPW patients have <b>structurally normal hearts</b>, <b>MVP</b> goes with left-sided pathways, and <b>familial WPW</b> goes with <b>HCM</b>. Inheritance is not Mendelian.<br><br><b>Educational objective:</b> Ebstein anomaly (apical displacement of the tricuspid valve) is the congenital heart lesion most strongly associated with WPW.",
wrong={0:"Brugada affects the RV outflow tract (coved ST in V1–V2), not tricuspid displacement.",
1:"Long QT is a channelopathy in structurally normal hearts.",
2:"HCM is linked to <b>familial</b> WPW, but it isn't the lesion described.",
3:"Short QT is a channelopathy without structural valve disease."},
eli5="In Ebstein anomaly the tricuspid valve sits too low in the right ventricle. Babies with it often have an extra electrical shortcut too, which is WPW. That's why the ECG shows a short PR and a delta wave."),

dict(img=None,
stem="A 26-year-old man had an out-of-hospital cardiac arrest while playing soccer and was resuscitated. His QTc is 430 ms, and there is no pre-excitation or Brugada pattern. Cardiac MRI shows thinning of the right ventricular free wall with fibro-fatty replacement of the myocardium.{FIG}Which of the following is the most likely diagnosis?",
choices=["Arrhythmogenic right ventricular cardiomyopathy","Dilated cardiomyopathy","Hypertrophic cardiomyopathy","Long QT syndrome","Wolff–Parkinson–White syndrome"], key=0,
exp="The lecture's list of genetic conditions to consider after a young VT/VF arrest: long QT, short QT, WPW, Brugada (RVOT, coved ST in V1–V2), <b>ARVC</b> (<b>fibro-fatty replacement of the right ventricle</b>) and HCM (the most common, with thickened ventricles). A thinned RV free wall with fibro-fatty replacement on MRI is <b>arrhythmogenic right ventricular cardiomyopathy</b>. It classically causes VT (LBBB morphology) and sudden death in young athletes. His normal QTc and the absence of a delta wave or Brugada pattern exclude those alternatives.<br><br><b>Educational objective:</b> Arrhythmogenic right ventricular cardiomyopathy causes fibro-fatty replacement of the right ventricle and ventricular arrhythmias or sudden death in young people.",
wrong={1:"Dilated cardiomyopathy dilates the LV (usually) without fibro-fatty RV replacement.",
2:"HCM shows <b>thickened</b> ventricles (especially the septum), not a thin fatty RV.",
3:"Long QT needs a prolonged QTc. His is 430 ms.",
4:"WPW needs pre-excitation, which is absent."},
eli5="Parts of his right ventricle's muscle have been replaced by fat and scar, which is a genetic disease called ARVC. That damaged muscle can set off deadly fast rhythms, especially during exercise."),

dict(img=None,
stem="A 32-year-old woman had acute viral pericarditis diagnosed 3 weeks ago, with diffuse ST elevation and PR depression at the time. Her pain has resolved. A repeat ECG is obtained.{FIG}Which of the following ECG findings is most expected at this stage?",
choices=["Diffuse ST elevation with PR depression persisting unchanged","Diffuse T-wave inversion with isoelectric ST segments","New pathologic Q waves in the inferior leads","Regional ST elevation with reciprocal depression","Tall peaked T waves in the precordial leads"], key=1,
exp="The ECG stages of pericarditis unfold over weeks:<br>1. <b>Diffuse ST elevation ± PR depression</b> (acute).<br>2. ST and PR segments normalize.<br>3. <b>Diffuse T-wave inversion with isoelectric ST segments</b>, typically at weeks 2–4.<br>4. The ECG returns to normal by 1–2 months.<br>At 3 weeks, stage 3 (diffuse T inversion) is expected. Unlike infarction, pericarditis doesn't produce Q waves, and its changes are diffuse, not regional. Diagnosis needs ≥2 of 4: pleuritic pain, rub, widespread STE or PR depression, and effusion.<br><br><b>Educational objective:</b> Pericarditis evolves from diffuse ST elevation to normalization, then diffuse T-wave inversion (weeks 2–4), then normal (1–2 months), without Q waves.",
wrong={0:"The acute changes typically resolve within days to a couple of weeks.",
2:"Q waves indicate infarction. Pericarditis doesn't cause them.",
3:"Regional ST elevation with reciprocal depression is STEMI.",
4:"Tall peaked T waves suggest hyperkalemia or hyperacute ischemia."},
eli5="Pericarditis changes the ECG in stages over weeks. First the ST segments go up everywhere, then they settle, then the T waves flip downward for a few weeks. Finally everything returns to normal."),
]
