# Heart Failure Pharmacology (Scully) — Version 2, 18 items (2 with images): the cases — loop diuretics, inotropes, nitrates and nitroprusside, the regimen
Q = [
dict(img='Aapedema', cap='Chest x-ray',
stem="A 60-year-old woman with two previous myocardial infarctions is sitting upright and anxious. Blood pressure is 148/108 mm Hg, pulse 132/min, and oxygen saturation 88% on room air. She has wet rales, jugular venous distension and pitting edema of both legs. Her chest x-ray is shown. A drug is given intravenously, and she produces a large volume of urine within the hour.{FIG}The drug most likely acts on which transporter?",
choices=["Na⁺–K⁺–2Cl⁻ cotransporter (NKCC2)","Na⁺–Cl⁻ cotransporter (NCC)","Epithelial Na⁺ channel (ENaC)","Carbonic anhydrase","Mineralocorticoid receptor"], key=0,
exp="This is the lecture's case 1. Wet rales, hypoxemia, jugular venous distension, pitting edema and an x-ray with cardiomegaly and pulmonary vascular congestion all mean <b>increased preload</b>. Reduce it with a <b>loop diuretic: furosemide</b>. It inhibits <b>NKCC2 on the luminal membrane of the thick ascending limb</b>, which reabsorbs about <b>25–30% of filtered Na⁺</b> (\"about 30%\"), so blocking it gives a robust diuresis. Adverse effects: hypokalemia, hyponatremia, hypocalcemia, hypomagnesemia, hypokalemic metabolic alkalosis, and dose-dependent ototoxicity.<br><br><b>Educational objective:</b> Furosemide blocks NKCC2 in the thick ascending limb, producing a robust diuresis that relieves congestion (preload reduction).",
wrong={1:"NCC (distal convoluted tubule) is the thiazide target, which carries only about 5–10% of filtered Na⁺.",
2:"ENaC (collecting duct) is blocked by amiloride and triamterene, which are weak diuretics.",
3:"Carbonic anhydrase inhibitors (acetazolamide) act in the proximal tubule and are weak diuretics.",
4:"Spironolactone blocks the mineralocorticoid receptor. It's slow and mild, not for acute congestion."},
eli5="Her lungs and legs are flooded. Furosemide shuts down the kidney's biggest salt pump, so lots of salt and water pour out in the urine and the flood drains."),

dict(img=None,
stem="A 72-year-old man receiving high-dose furosemide for heart failure develops muscle cramps and perioral tingling. His calcium and magnesium are low, although the drug's target transports neither ion.{FIG}Which of the following best explains the loss of calcium and magnesium?",
choices=["Loss of the lumen-positive potential that drives them","Direct inhibition of a Ca²⁺/Mg²⁺ pump in the loop","Increased parathyroid hormone resistance in the kidney","Volume contraction that raises their proximal secretion","Their secretion in exchange for Na⁺ through ENaC"], key=0,
exp="In the thick ascending limb, NKCC2 brings in Na⁺, K⁺ and 2 Cl⁻. Some K⁺ <b>recycles back into the lumen through ROMK</b>, which creates a <b>lumen-positive potential (~10 mV)</b>. That potential drives Ca²⁺ and Mg²⁺ <b>between the cells (paracellularly)</b> for electroneutrality, not through a transporter. Block NKCC2 and there's no K⁺ recycling, no potential, and Ca²⁺ and Mg²⁺ are lost. Board add-on: \"loops lose calcium\", while thiazides keep it.<br><br><b>Educational objective:</b> Loop diuretics cause hypocalcemia and hypomagnesemia by removing the lumen-positive potential that drives their paracellular reabsorption in the thick ascending limb.",
wrong={1:"There's no Ca²⁺/Mg²⁺ pump in the thick ascending limb. Reabsorption there is paracellular.",
2:"PTH resistance isn't the mechanism.",
3:"Volume contraction increases proximal <b>reabsorption</b>, and Ca²⁺ and Mg²⁺ aren't secreted there.",
4:"ENaC exchanges charge with K⁺ secretion, not Ca²⁺ or Mg²⁺."},
eli5="The salt pump that furosemide blocks also builds up a small electrical charge that pushes calcium and magnesium back into the body. No pump, no charge, so those minerals wash out."),

dict(img='Aaflatt', cap='12-lead ECG',
stem="A 70-year-old woman with heart failure has taken furosemide 80 mg twice daily for 3 weeks. She has fatigue and weakness, and her ECG is shown.{FIG}Besides reduced K⁺ reabsorption in the thick ascending limb, which mechanism contributes most to her K⁺ loss?",
choices=["↑ Distal Na⁺ delivery → ENaC → K⁺ out via ROMK","Electroneutral NCC transport in the distal tubule","Inhibition of the Na⁺/K⁺-ATPase in principal cells","Proximal tubular K⁺ secretion via carbonic anhydrase","Furosemide blocking aldosterone synthesis"], key=0,
exp="The ECG shows <b>flattened T waves</b> (with prominent U waves), so she is <b>hypokalemic</b>. The lecture's two sources of K⁺ loss:<br>1. Less K⁺ reabsorbed in the thick ascending limb (NKCC2 is blocked).<br>2. <b>Extra Na⁺ reaches the collecting duct</b>, where <b>ENaC reabsorbs Na⁺ alone</b>. That positive charge has to be balanced, so <b>K⁺ is secreted through ROMK</b>.<br>The same mechanism makes thiazides K⁺-wasting. NCC is electroneutral and adds no K⁺ loss itself. Volume contraction also raises aldosterone, which increases ENaC further.<br><br><b>Educational objective:</b> Loop and thiazide diuretics waste K⁺ because increased distal Na⁺ delivery drives ENaC reabsorption, balanced by K⁺ secretion through ROMK.",
wrong={1:"NCC is <b>electroneutral</b>, so it doesn't create the K⁺-secreting charge itself.",
2:"Furosemide doesn't inhibit the Na⁺/K⁺-ATPase. That's digoxin.",
3:"The proximal tubule doesn't secrete K⁺ via carbonic anhydrase.",
4:"Volume loss <b>raises</b> aldosterone. Furosemide doesn't block its synthesis."},
eli5="When more salt reaches the end of the kidney tubule, the kidney swaps that salt for potassium and throws the potassium away. That's why her potassium is low and her T waves are flat."),

dict(img=None,
stem="The patient on high-dose furosemide also develops a metabolic alkalosis. The lecture recording described a K⁺-for-H⁺ swap in the collecting duct.{FIG}Which cells secrete the H⁺ into the urine in this setting?",
choices=["α-intercalated cells","β-intercalated cells","Principal cells","Macula densa cells","Proximal tubule cells"], key=0,
exp="Hypokalemia → the intercalated cells swap K⁺ for H⁺ (\"positive for positive\": the H⁺/K⁺-ATPase) → <b>H⁺ lost in the urine → metabolic alkalosis</b>. Note the <b>recording slip</b>: the lecture said \"beta intercalated cells\". It is the <b>α-intercalated cells</b> that secrete H⁺ (H⁺-ATPase and H⁺/K⁺-ATPase). β-intercalated cells secrete bicarbonate. Board add-on: volume contraction (↑ angiotensin II and aldosterone) adds a \"contraction alkalosis\", and aldosterone also stimulates α-cell H⁺ secretion.<br><br><b>Educational objective:</b> Loop-diuretic metabolic alkalosis comes from H⁺ secretion by α-intercalated cells (H⁺/K⁺ exchange), plus contraction alkalosis.",
wrong={1:"β-intercalated cells secrete <b>bicarbonate</b>, which would lower plasma pH, not raise it. The recording misnamed them.",
2:"Principal cells reabsorb Na⁺ (ENaC) and secrete K⁺ (ROMK), not H⁺.",
3:"Macula densa cells sense NaCl for tubuloglomerular feedback.",
4:"The proximal tubule reclaims bicarbonate, but the K⁺-for-H⁺ swap described is distal."},
eli5="With potassium running low, special acid-pumping cells in the kidney (the alpha ones) trade acid out for potassium in. Losing that acid makes the blood too alkaline."),

dict(img=None,
stem="A 67-year-old man with decompensated heart failure and pneumonia receives high-dose IV furosemide boluses and intravenous gentamicin. Three days later he reports ringing in his ears and difficulty hearing conversation.{FIG}Which of the following best describes this adverse effect?",
choices=["Additive ototoxicity","Hypokalemic myopathy","Cinchonism","Gouty arthritis","Hyponatremic encephalopathy"], key=0,
exp="<b>Dose-dependent ototoxicity</b> is a loop-diuretic adverse effect and \"a board favourite\". It is most likely with <b>high doses or rapid IV boluses</b>, kidney impairment, and <b>other ototoxic drugs such as aminoglycosides</b> (board add-on). Loops also cause hypokalemia, hyponatremia, hypocalcemia, hypomagnesemia, metabolic alkalosis and hyperuricemia (gout).<br><br><b>Educational objective:</b> Loop diuretics are ototoxic in a dose-dependent way, and aminoglycosides add to the risk.",
wrong={1:"Hypokalemia causes weakness and cramps, not tinnitus or hearing loss.",
2:"Cinchonism is quinidine or quinine toxicity.",
3:"Loops cause hyperuricemia, but gout presents as an acutely painful joint.",
4:"Hyponatremia causes confusion and seizures, not isolated hearing loss."},
eli5="Furosemide and gentamicin can both hurt the inner ear. Together, at high doses, they can cause ringing and hearing loss."),

dict(img=None,
stem="A 62-year-old woman with acute pulmonary edema needs a loop diuretic. She reports a previous anaphylactic reaction to trimethoprim-sulfamethoxazole.{FIG}Which of the following is the board-preferred loop diuretic for her?",
choices=["Ethacrynic acid","Furosemide","Bumetanide","Torsemide","Hydrochlorothiazide"], key=0,
exp="Furosemide, bumetanide and torsemide are <b>sulfonamide</b> loop diuretics. For a patient with a sulfa allergy who needs a loop diuretic, <b>boards still want ethacrynic acid</b>, the non-sulfonamide loop. The lecture notes that cross-reactivity data suggest it may not matter much in practice. Ethacrynic acid is the most ototoxic loop (board add-on).<br><br><b>Educational objective:</b> Ethacrynic acid is the non-sulfonamide loop diuretic for patients with a sulfonamide allergy.",
wrong={1:"Furosemide is a sulfonamide.",
2:"Bumetanide is a sulfonamide loop.",
3:"Torsemide is a sulfonamide loop.",
4:"Hydrochlorothiazide is a sulfonamide too, and too weak for acute pulmonary edema."},
eli5="Most water pills of this type share a 'sulfa' chemical shape. Ethacrynic acid is the one that doesn't, so it's the safe pick for someone with a sulfa allergy."),

dict(img=None,
stem="A medical student asks why furosemide, which produces such a robust diuresis in acute heart failure, is not used alone as a long-term treatment for essential hypertension.{FIG}Which of the following best explains this, according to the lecture?",
choices=["Downstream segments adapt and the effect fades","Its electrolyte effects are far worse than thiazides'","It cannot be given by mouth","It raises blood pressure through renin release","It is too short-acting to give more than once daily"], key=0,
exp="Dr. Scully: the reason <b>isn't mainly the electrolytes</b> (every diuretic shifts those). It is <b>tolerance</b>. Na⁺ that escapes the thick ascending limb is reabsorbed downstream, and those segments <b>increase their capacity</b>, so the diuresis fades. Loops are good for an initial robust diuresis in fluid overload, not for long-term BP control on their own. (Thiazides are the long-term antihypertensive diuretic. See the Hypertension notes.)<br><br><b>Educational objective:</b> Loop diuretics aren't used alone for chronic hypertension because distal nephron segments adapt and the diuretic effect fades (tolerance).",
wrong={1:"The lecturer specifically said electrolytes aren't the main reason.",
2:"Furosemide is given orally all the time.",
3:"Renin release is a compensation, but tolerance is the reason given.",
4:"Dosing frequency isn't the reason given."},
eli5="If you block one big salt pump for weeks, the pumps further down the kidney get stronger and grab the salt back. So the water pill slowly stops working for blood pressure."),

dict(img=None,
stem="A 64-year-old woman with decompensated heart failure and hypotension is started on a dobutamine infusion. A pharmacology student notes that dobutamine binds α-adrenergic receptors, yet clinically it behaves as a pure β1 agonist.{FIG}Which of the following best explains this?",
choices=["Its two enantiomers cancel each other's α effects","It is converted in the liver to a β1-selective metabolite","It binds α receptors only at toxic doses","Its α effects are blocked by reflex vagal tone","It is a prodrug activated only in cardiac tissue"], key=0,
exp="Case 2: dobutamine is \"considered a pure β1 agonist\" clinically. It is a <b>racemic mixture</b>: <b>one enantiomer is an α agonist and the other an α antagonist</b>, so the α effects wash out and what's left is clean β1 inotropy. β1 → Gs → adenylyl cyclase → cAMP → PKA → phosphorylation of L-type Ca²⁺ channels (bigger influx), phospholamban (↑ SERCA) and phospholemman → more Ca²⁺ per beat → ↑ force. It is at the top of most HFrEF inotrope algorithms. It relieves symptoms but doesn't reduce mortality.<br><br><b>Educational objective:</b> Dobutamine acts as a clinically pure β1 agonist because its enantiomers cancel each other's α effects.",
wrong={1:"Dobutamine isn't converted to a selective metabolite.",
2:"Dobutamine binds α receptors at clinical doses. Their effects simply cancel.",
3:"Vagal tone acts on heart rate, not on vascular α receptors.",
4:"Dobutamine isn't a prodrug."},
eli5="Dobutamine is a 50/50 mix of mirror-image twins. One twin pushes the α 'squeeze the vessels' button and the other blocks it, so they cancel out, and only the heart-boosting β1 effect is left."),

dict(img=None,
stem="A patient in cardiogenic shock is started on norepinephrine. Contractility improves, but the heart rate falls from 105/min to 78/min.{FIG}Which of the following best explains the slower heart rate?",
choices=["α1 vasoconstriction raises BP → baroreflex vagal outflow","Norepinephrine directly stimulates cardiac M2 receptors","β2 stimulation dilates vessels and slows the SA node","Norepinephrine blocks β1 receptors at high doses","Norepinephrine depletes catecholamine stores in the SA node"], key=0,
exp="Norepinephrine acts on <b>α1 + β1, with no β2</b>. β1 raises contractility, but the <b>unopposed α1 vasoconstriction</b> (no β2 dilation to offset it) raises afterload and BP. The <b>baroreceptor reflex</b> then increases parasympathetic (vagal) outflow, causing <b>reflex bradycardia</b> despite the β1 effect. The higher afterload is the vasopressor trade-off in a weak heart. For comparison, dopamine is dose-dependent (D1 → β1 → α1) and epinephrine acts on β1, β2 and α.<br><br><b>Educational objective:</b> Norepinephrine raises afterload through α1 vasoconstriction (no β2), triggering baroreflex bradycardia despite its β1 action.",
wrong={1:"Norepinephrine is adrenergic. It doesn't act on muscarinic receptors.",
2:"Norepinephrine has negligible β2 activity, and β2 doesn't slow the SA node.",
3:"Norepinephrine is an agonist, not a β-blocker.",
4:"Norepinephrine doesn't deplete nodal stores. That's reserpine's mechanism."},
eli5="Norepinephrine squeezes the blood vessels hard, so blood pressure jumps. The body senses that and taps the brakes on the heart rate."),

dict(img=None,
stem="A 70-year-old man with heart failure with reduced ejection fraction who takes carvedilol daily presents in low-output decompensation. The team chooses milrinone over dobutamine because of his β-blocker therapy.{FIG}Which property of milrinone supports this choice?",
choices=["It raises cAMP downstream of the β-receptor","It is a more potent β1 agonist than dobutamine","It reverses β-blockade by displacing carvedilol","It increases contractility through Na⁺/K⁺-ATPase block","It acts on α1 receptors, which carvedilol spares"], key=0,
exp="<b>Inamrinone and milrinone are phosphodiesterase-3 (PDE3) inhibitors</b>. They stop cAMP breakdown, giving \"the same PKA effect without the receptor\". Because they act <b>downstream of the β-receptor</b>, they still work in a β-blocked patient. Board add-on: milrinone is an \"inodilator\". PDE3 inhibition also relaxes vascular smooth muscle (↓ afterload), so watch for <b>hypotension and arrhythmias</b>. Like other inotropes it relieves symptoms only.<br><br><b>Educational objective:</b> Milrinone inhibits PDE3, raising cAMP without the β-receptor, so it works despite β-blockade and also vasodilates.",
wrong={1:"Milrinone isn't a β-agonist.",
2:"Milrinone doesn't displace carvedilol from β-receptors.",
3:"Na⁺/K⁺-ATPase inhibition is digoxin.",
4:"Carvedilol <b>blocks</b> α1, and milrinone doesn't act on α receptors."},
eli5="Carvedilol blocks the front door (the β-receptor). Milrinone skips the door entirely and turns up the same signal inside the cell, so the heart still squeezes harder."),

dict(img=None,
stem="An ICU patient with heart failure is started on an infusion of dopamine at a low dose (1–2 µg/kg/min). The goal is to improve renal perfusion rather than raise contractility or vascular tone.{FIG}At this dose, dopamine acts mainly on which receptor?",
choices=["D1 dopamine receptor","β1-adrenergic receptor","α1-adrenergic receptor","β2-adrenergic receptor","M2 muscarinic receptor"], key=0,
exp="The lecture's table: dopamine works <b>D1 → β1 → α1 as the dose rises</b>. It \"could help\" with poor renal perfusion by dilating the renal beds, \"but watch the dose: too high and α vasoconstriction appears\". Board add-on dosing: <b>low → D1</b> (renal and mesenteric vasodilation), <b>medium → β1</b> (inotropy, chronotropy), <b>high → α1</b> (vasoconstriction, a vasopressor). High-dose dopamine is listed with norepinephrine and phenylephrine as a vasopressor for persistent shock.<br><br><b>Educational objective:</b> Low-dose dopamine acts on D1 receptors (renal vasodilation). Higher doses add β1 then α1 effects.",
wrong={1:"β1 effects dominate at <b>medium</b> doses.",
2:"α1 vasoconstriction appears at <b>high</b> doses.",
3:"β2 isn't dopamine's dose-defining receptor.",
4:"Dopamine doesn't act on muscarinic receptors."},
eli5="Dopamine does different things at different doses. A tiny dose mostly opens up the kidney's blood vessels, a medium dose pumps the heart, and a big dose squeezes all the vessels."),

dict(img=None,
stem="A 64-year-old woman in the ICU with acute heart failure has received a continuous intravenous infusion for several days. The drug raises cGMP in vascular smooth muscle. She develops an acute anion-gap metabolic acidosis with a rising lactate, then dies of an arrhythmia. Toxicology shows cyanide poisoning.{FIG}Which drug was she most likely receiving?",
choices=["Sodium nitroprusside","Nitroglycerin","Isosorbide dinitrate","Hydralazine","Milrinone"], key=0,
exp="This is case 3. \"<b>↑ cGMP</b>\" alone says the nitrate class (NO → soluble guanylyl cyclase → cGMP → protein kinase G → smooth-muscle relaxation). <b>Cyanide</b> says <b>sodium nitroprusside</b>, which has cyanide at its core. Prolonged infusion → cyanide toxicity → <b>metabolic (lactic) acidosis</b> → fatal arrhythmia. Nitroprusside breaks down <b>spontaneously</b> to NO, with no enzyme needed, so it dilates <b>arterioles and veins</b> (↓ afterload and preload), a \"universal dilator\". Board add-on antidotes: hydroxocobalamin, sodium thiosulfate.<br><br><b>Educational objective:</b> Nitroprusside (↑ cGMP, arterial + venous dilation) causes cyanide toxicity with prolonged infusion, presenting as metabolic acidosis.",
wrong={1:"Nitroglycerin raises cGMP but contains no cyanide.",
2:"Isosorbide dinitrate is an oral organic nitrate without cyanide.",
3:"Hydralazine is a direct arteriolar dilator. Its signature toxicity is drug-induced lupus.",
4:"Milrinone raises <b>cAMP</b> (PDE3 inhibition), not cGMP."},
eli5="Nitroprusside relaxes blood vessels, but each molecule carries a bit of cyanide. Over days of infusion the cyanide builds up, cells can't use oxygen, and acid floods the blood."),

dict(img=None,
stem="A pharmacology student compares intravenous nitroglycerin with sodium nitroprusside in a patient with heart failure. Nitroglycerin mainly lowers preload, whereas nitroprusside lowers both preload and afterload.{FIG}Which of the following best explains the difference?",
choices=["Nitroprusside releases NO without enzymatic activation","Nitroglycerin blocks α1 receptors on veins only","Nitroprusside also inhibits phosphodiesterase-5","Nitroglycerin is degraded before reaching arterioles","Nitroprusside acts on β2 receptors in arterioles"], key=0,
exp="<b>Organic nitrates</b> (nitroglycerin, isosorbide) must be <b>activated by an enzyme</b> (aldehyde dehydrogenase) in nearby endothelium to free NO. That machinery sits on the <b>venous (capacitance) side</b>, so they are mainly <b>venodilators → ↓ preload</b>. <b>Nitroprusside breaks down spontaneously to NO</b>, with no enzyme needed, so it dilates <b>arterioles and veins</b> alike (↓ afterload + ↓ preload).<br><br><b>Educational objective:</b> Organic nitrates need enzymatic bioactivation that is mostly venous (↓ preload). Nitroprusside releases NO spontaneously and dilates arteries and veins.",
wrong={1:"Nitrates act through NO and cGMP, not α1 blockade.",
2:"Nitroprusside doesn't inhibit PDE5. Combining nitrates with PDE5 inhibitors is the dangerous interaction.",
3:"Nitroglycerin reaches arterioles. It just isn't activated well there at usual doses.",
4:"Nitroprusside doesn't act on adrenergic receptors."},
eli5="Nitroglycerin needs a helper enzyme to switch on, and that helper lives mostly in the veins. Nitroprusside switches itself on anywhere, so it relaxes arteries and veins alike."),

dict(img=None,
stem="A 58-year-old man with heart failure is brought in with acute pulmonary edema and a blood pressure of 150/90 mm Hg. His partner reports he took tadalafil the previous evening.{FIG}Which of the following drugs should be avoided?",
choices=["Nitroglycerin","Furosemide","Morphine","Dobutamine","Oxygen"], key=0,
exp="Always ask about <b>PDE5 inhibitors</b> (sildenafil, tadalafil) before giving a nitrate. <b>Nitrates make cGMP</b> (NO → soluble guanylyl cyclase) and <b>PDE5 inhibitors stop its breakdown</b>. The result is <b>profound, refractory hypotension</b>. Board add-on: avoid nitrates for 24 hours after sildenafil and 48 hours after tadalafil (long-acting). Diuresis with furosemide is still appropriate.<br><br><b>Educational objective:</b> Nitrates are contraindicated after PDE5 inhibitors (sildenafil, tadalafil) because the cGMP excess causes refractory hypotension.",
wrong={1:"Furosemide reduces preload by a different mechanism and is appropriate.",
2:"Morphine doesn't interact with PDE5 inhibitors through cGMP.",
3:"Dobutamine acts through cAMP and isn't the classic interaction.",
4:"Oxygen is part of the decompensation checklist."},
eli5="Nitroglycerin makes a 'relax the vessels' signal, and tadalafil stops the body from clearing it. Together the vessels relax so much that blood pressure can crash."),

dict(img=None,
stem="A 66-year-old woman with heart failure with reduced ejection fraction sits at the point of high end-diastolic pressure and low output on an untreated Frank–Starling curve. Enalapril is started.{FIG}Which change best describes enalapril's effect on her position?",
choices=["A higher curve, plus a small drop in preload","Down the same curve, with no rise in output","Up the same curve to a higher filling pressure","A lower curve with less end-diastolic pressure","No change, because it acts only on blood pressure"], key=0,
exp="Slide 16: from point C (congested, low output):<br>• <b>Afterload reduction (ACE inhibitor) C → F</b>: ↓ angiotensin II → vasodilation → more output at each preload, so <b>a new, higher curve</b>. ↓ Aldosterone → less ENaC → a <b>small diuresis</b>, so a little preload drop too.<br>• Preload reduction (furosemide) C → G: down the <b>same</b> curve, no rise in output.<br>• Positive inotrope C → D (higher curve at the same preload), then D → E as better ejection lowers preload.<br>\"You're going to have to pick PV loops… what shift happens if you give this drug?\"<br><br><b>Educational objective:</b> ACE inhibitors move the patient onto a higher Frank–Starling curve (afterload reduction) with a slight preload drop (less aldosterone).",
wrong={1:"Moving down the same curve is what a diuretic (preload reduction) does.",
2:"Moving up the same curve to higher filling pressure is untreated progression (B → C).",
3:"A lower curve means worse contractile function, the A → B failure step.",
4:"Afterload reduction changes ventricular performance, not just the BP reading."},
eli5="Lowering the resistance the heart pumps against lets the same weak heart push out more blood. That's a better curve, and a bit of extra urine lowers the filling pressure too."),

dict(img=None,
stem="A 75-year-old man with heart failure with reduced ejection fraction and atrial fibrillation remains symptomatic despite sacubitril/valsartan, carvedilol, spironolactone and dapagliflozin. Digoxin is added.{FIG}Which of the following best describes digoxin's role in his heart failure?",
choices=["Secondary therapy that relieves symptoms only","A first-line pillar that lowers mortality","A substitute for the β-blocker in atrial fibrillation","An acute inotrope for cardiogenic shock only","A diuretic that reduces preload through the kidney"], key=0,
exp="The lecture sorts therapy into <b>initial</b> (ARNI/ACEi/ARB or hydralazine + nitrate, β-blocker, spironolactone, SGLT2 inhibitor, furosemide as needed) and <b>secondary</b> (<b>digoxin</b>, hydralazine + long-acting nitrate). Cardiac glycosides are <b>symptomatic relief</b>: they raise contractility (Na⁺/K⁺-ATPase → more SR Ca²⁺) and slow the AV node in AF, but <b>don't prolong life</b>. Board add-on: the DIG trial showed fewer hospitalizations without a mortality change. Its narrow therapeutic index means watching K⁺ (diuretics), renal function and interactions.<br><br><b>Educational objective:</b> In HFrEF, digoxin is secondary therapy that improves symptoms (and AF rate) without reducing mortality.",
wrong={1:"Digoxin isn't one of the four mortality-reducing pillars.",
2:"It complements, rather than replaces, the β-blocker, which is a mortality drug.",
3:"Acute shock calls for IV inotropes such as dobutamine or milrinone. Digoxin is oral maintenance therapy here.",
4:"Digoxin isn't a diuretic."},
eli5="Digoxin helps him feel better and keeps his AF rate down, but it doesn't help him live longer. The four main pills do that."),

dict(img=None,
stem="A 63-year-old woman with heart failure with reduced ejection fraction had angioedema on lisinopril and later developed hyperkalemia and acute kidney injury on an angiotensin receptor blocker. She remains on carvedilol, dapagliflozin and furosemide.{FIG}Which of the following is the most appropriate addition in place of a renin–angiotensin system drug?",
choices=["Hydralazine plus isosorbide dinitrate","Sacubitril/valsartan","Aliskiren","Amlodipine","Eplerenone"], key=0,
exp="Slide 12 lists <b>hydralazine + a long-acting nitrate</b> as the <b>alternative to the RAAS drugs</b> in initial therapy, and as a secondary option. Hydralazine is an <b>arteriolar dilator (↓ afterload)</b> and the nitrate a <b>venodilator (↓ preload)</b>. Board add-on: the combination reduced mortality in A-HeFT. Hydralazine adverse effects: reflex tachycardia and drug-induced lupus. Sacubitril/valsartan is out because of her angioedema history (neprilysin inhibition raises bradykinin) and the ARB problem.<br><br><b>Educational objective:</b> Hydralazine + isosorbide dinitrate is the alternative for HFrEF patients who can't take ACEi/ARB/ARNI.",
wrong={1:"An ARNI raises bradykinin (angioedema risk) and contains an ARB.",
2:"Aliskiren (a renin inhibitor) is still RAAS blockade, with the same hyperkalemia and kidney risks.",
3:"Amlodipine doesn't improve HFrEF outcomes.",
4:"An MRA would worsen her hyperkalemia, and it doesn't replace afterload reduction."},
eli5="She can't take the usual blood-vessel-relaxing heart pills, so she gets two older drugs instead. Hydralazine opens the arteries and the nitrate opens the veins."),

dict(img=None,
stem="In a cardiac myocyte exposed to dobutamine, protein kinase A phosphorylates several Ca²⁺-handling proteins. One of these, when phosphorylated, releases its inhibition of the sarcoplasmic reticulum Ca²⁺-ATPase (SERCA), so more Ca²⁺ is stored for the next beat.{FIG}Which protein is this?",
choices=["Phospholamban","Troponin C","Ryanodine receptor","Calsequestrin","Myosin light chain"], key=0,
exp="Dobutamine (β1) → Gs → adenylyl cyclase → cAMP → <b>protein kinase A</b>, which phosphorylates:<br>• <b>L-type Ca²⁺ channels</b>: bigger Ca²⁺ influx.<br>• <b>Phospholamban</b>: releases its brake on <b>SERCA</b> → faster Ca²⁺ reuptake (lusitropy) and <b>more SR Ca²⁺</b> for the next beat.<br>• Phospholemman (and the exchanger).<br>The result is more Ca²⁺ per beat, a bigger Ca²⁺-induced Ca²⁺ release, and ↑ contractile force. PDE3 inhibitors reach the same endpoint by keeping cAMP high.<br><br><b>Educational objective:</b> PKA phosphorylation of phospholamban relieves SERCA inhibition, increasing SR Ca²⁺ stores and contractility (and speeding relaxation).",
wrong={1:"Troponin C binds Ca²⁺ to start contraction. It doesn't regulate SERCA.",
2:"The ryanodine receptor releases SR Ca²⁺. It doesn't pump Ca²⁺ in.",
3:"Calsequestrin buffers Ca²⁺ inside the SR. It isn't the SERCA brake.",
4:"Myosin light-chain phosphorylation matters mostly in smooth muscle contraction."},
eli5="Phospholamban is the brake on the pump that reloads calcium into storage. PKA lifts that brake, so the storage tank refills faster and fuller, and the next squeeze is stronger."),
]
