# Heart Failure Pharmacology (Scully) — Version 1, 18 items (2 with images): the neurohumoral cycle, mortality vs symptoms, the four pillars
Q = [
dict(img=None,
stem="A 66-year-old man has heart failure with reduced ejection fraction after two myocardial infarctions. His falling cardiac output activates the baroreceptor reflex. Sympathetic stimulation of a receptor on renal juxtaglomerular cells starts a sequence that raises both his afterload and his preload.{FIG}Which receptor starts this sequence?",
choices=["β1-adrenergic receptor","α1-adrenergic receptor","β2-adrenergic receptor","M2 muscarinic receptor","D1 dopamine receptor"], key=0,
exp="The lecture's <b>vicious cycle</b> (slide 6): ↓ cardiac function → ↓ arterial pressure → baroreceptor reflex → ↑ sympathetic outflow. Acutely that means α-mediated vasoconstriction and tachycardia. <b>β1 on juxtaglomerular cells → ↑ renin → ↑ angiotensin II</b>:<br>• AT II vasoconstricts → <b>↑ afterload</b>.<br>• AT II → ↑ aldosterone → Na⁺ retention → volume expansion → <b>↑ preload</b>.<br>Both raise myocardial O₂ demand and worsen the failure: \"some of our compensations end up making this condition worse\". That's why the RAAS is blocked at three points: β-blockers (renin release), ACE inhibitors/ARBs (AT II) and spironolactone (the aldosterone receptor).<br><br><b>Educational objective:</b> In heart failure, sympathetic β1 stimulation of renin release drives angiotensin II (↑ afterload) and aldosterone (↑ preload), worsening the failure.",
wrong={1:"α1 receptors mediate direct vasoconstriction (afterload), not renin release.",
2:"β2 receptors mediate vasodilation and bronchodilation, not renin release.",
3:"M2 receptors slow the heart. They aren't the renin trigger.",
4:"D1 receptors dilate renal vessels. They don't start the RAAS cascade."},
eli5="When the heart weakens, the body hits the panic button. Adrenaline tells the kidney to release renin, which tightens blood vessels and holds onto salt and water. That makes the weak heart work even harder."),

dict(img=None,
stem="A 59-year-old woman with heart failure with reduced ejection fraction (ejection fraction 30%) takes sacubitril/valsartan, carvedilol and furosemide. Her potassium is 4.2 mEq/L and her kidney function is normal.{FIG}Adding which of the following drugs is most likely to reduce her mortality?",
choices=["Spironolactone","Digoxin","Isosorbide mononitrate","Hydrochlorothiazide","Ivabradine"], key=0,
exp="Know which drugs <b>prolong life</b> and which only <b>relieve symptoms</b>.<br>• <b>Four pillars (↓ mortality):</b> ARNI/ACEi/ARB · β-blocker · <b>mineralocorticoid receptor antagonist (spironolactone)</b> · SGLT2 inhibitor.<br>• <b>Symptoms only:</b> diuretics (furosemide), digoxin, veno/vasodilators (nitrates), aquaretics, sympathomimetic amines, PDE inhibitors.<br>She is missing the MRA (and an SGLT2 inhibitor). With normal K⁺ and kidney function, spironolactone is the mortality-lowering addition. Combining drugs means watching for additive hypotension, arrhythmia, electrolyte shifts and renal insufficiency.<br><br><b>Educational objective:</b> The mortality-reducing pillars in HFrEF are ARNI/ACEi/ARB, β-blocker, spironolactone and an SGLT2 inhibitor. Diuretics, digoxin and nitrates relieve symptoms only.",
wrong={1:"Digoxin is secondary therapy. It relieves symptoms (and board add-on: reduces hospitalizations) but not mortality.",
2:"A nitrate alone is a venodilator for symptoms. The mortality benefit belongs to hydralazine + nitrate in selected patients.",
3:"Thiazides relieve volume symptoms only.",
4:"Ivabradine (board add-on) lowers heart rate and hospitalizations in selected patients, but it isn't a pillar and isn't in this lecture."},
eli5="Some heart-failure drugs help people live longer and others just help them feel better. She's missing one of the 'live longer' drugs: spironolactone."),

dict(img=None,
stem="A 63-year-old man with heart failure with reduced ejection fraction is switched to sacubitril/valsartan. The sacubitril component inhibits a neutral endopeptidase.{FIG}Which of the following best describes the effect of sacubitril?",
choices=["↑ Natriuretic peptides, bradykinin and substance P","↓ Conversion of angiotensin I to angiotensin II","Blockade of the angiotensin II type 1 receptor","Blockade of the aldosterone receptor in the collecting duct","↓ Renin secretion from juxtaglomerular cells"], key=0,
exp="<b>Sacubitril inhibits neprilysin</b>, a neutral endopeptidase that normally breaks down vasoactive peptides. So <b>natriuretic peptides, bradykinin and substance P accumulate</b>. Natriuretic peptides promote natriuresis and diuresis. Bradykinin is a potent vasodilator (and causes cough). <b>Valsartan blocks the AT1 receptor</b>. Together they form the ARNI (angiotensin receptor–neprilysin inhibitor), the first-line RAAS drug in HFrEF. It lowers cardiovascular death and hospitalization. Adverse effects: hypotension, orthostasis, hyperkalemia, and a <b>boxed warning for fetal toxicity</b>.<br><br><b>Educational objective:</b> Sacubitril inhibits neprilysin, raising natriuretic peptides, bradykinin and substance P. Valsartan supplies the AT1 blockade.",
wrong={1:"Reducing AT II formation is what an ACE inhibitor does.",
2:"AT1 blockade is the <b>valsartan</b> half of the combination.",
3:"Aldosterone receptor blockade is spironolactone.",
4:"Reducing renin release is a β-blocker effect."},
eli5="Neprilysin is a cleanup enzyme that destroys the body's own 'pee out salt and relax vessels' hormones. Sacubitril stops the cleanup, so those helpful hormones stick around longer."),

dict(img=None,
stem="A 70-year-old woman with heart failure with reduced ejection fraction has taken enalapril for 2 years. Her cardiologist plans to switch her to sacubitril/valsartan.{FIG}Which of the following is most important when making this switch?",
choices=["Stop enalapril 36 hours before the first dose","Give both drugs together for the first week","Start the new drug at bedtime to avoid dizziness","Add losartan for the first month as a bridge","Check a serum digoxin level before starting"], key=0,
exp="Neprilysin and ACE both break down <b>bradykinin</b>. Giving an ACE inhibitor with sacubitril blocks both pathways, bradykinin builds up, and the risk of <b>angioedema</b> rises. Board add-on: <b>stop the ACE inhibitor at least 36 hours before the first ARNI dose</b>, and never combine them. The lecture's broader rule: <b>never use two RAAS drugs together</b> (hyperkalemia, renal injury, hypotension). An ARNI already contains an ARB (valsartan).<br><br><b>Educational objective:</b> Never combine an ARNI with an ACE inhibitor. Allow a 36-hour washout to avoid bradykinin-mediated angioedema.",
wrong={1:"Overlapping an ACE inhibitor and sacubitril causes bradykinin excess and angioedema.",
2:"Dose timing doesn't address the main risk, which is the drug interaction.",
3:"Adding losartan would mean two ARBs (valsartan is in the ARNI), a double RAAS blockade.",
4:"Digoxin isn't part of this switch."},
eli5="Both medicines stop the body from clearing bradykinin, a chemical that can make the face and throat swell. Taking them together is risky, so the old one gets a day and a half to wash out first."),

dict(img=None,
stem="A 34-year-old woman with peripartum-onset heart failure with reduced ejection fraction has been stable for a year on sacubitril/valsartan, carvedilol, spironolactone and dapagliflozin. A home pregnancy test is now positive.{FIG}Which of the following is the most appropriate change regarding sacubitril/valsartan?",
choices=["Discontinue it now because of fetal toxicity","Continue it, because the benefit outweighs the risk","Halve the dose until the second trimester","Switch to enalapril for the rest of the pregnancy","Switch to valsartan alone without sacubitril"], key=0,
exp="Sacubitril/valsartan carries a US <b>boxed warning for fetal toxicity</b>: <b>discontinue as soon as pregnancy is detected</b>. The warning comes from the valsartan, but the ARNI carries it. <b>Anything targeting the RAAS is contraindicated in pregnancy</b> (ACE inhibitors, ARBs, ARNI, and aliskiren, a board add-on). Fetal kidney development depends on angiotensin II. Board add-on: in pregnancy, hydralazine plus a nitrate (with a β-blocker such as metoprolol) can replace the RAAS drug.<br><br><b>Educational objective:</b> Sacubitril/valsartan (like all RAAS blockers) is fetotoxic. Stop it as soon as pregnancy is detected.",
wrong={1:"The boxed warning is clear: fetal toxicity means stopping, not weighing it.",
2:"Lowering the dose doesn't remove the fetotoxic effect.",
3:"Enalapril, an ACE inhibitor, is also contraindicated in pregnancy.",
4:"Valsartan (an ARB) is the source of the fetal toxicity warning."},
eli5="Medicines that block the angiotensin hormone system can harm a developing baby's kidneys, so they have to stop as soon as she knows she's pregnant."),

dict(img=None,
stem="A 61-year-old man with heart failure with reduced ejection fraction has taken spironolactone for 8 months. He reports tender enlargement of both breasts and erectile dysfunction. His potassium is 4.8 mEq/L.{FIG}Which of the following is the most appropriate change?",
choices=["Switch to eplerenone","Use amiloride instead","Switch to hydrochlorothiazide","Stop the MRA permanently","Treat with finasteride"], key=0,
exp="Spironolactone blocks the <b>mineralocorticoid (aldosterone) receptor</b> → less ENaC synthesis → less Na⁺ reabsorption and less K⁺ wasting. It is <b>not selective</b>: it also blocks <b>androgen receptors</b>, causing <b>gynecomastia, impotence and abnormal menses</b>. Board add-on: <b>eplerenone</b> is the selective MRA without antiandrogen effects. It keeps the mortality benefit (MRAs are a pillar). Watch K⁺ with either drug (avoid if K⁺ > 5.0 or eGFR < 30).<br><br><b>Educational objective:</b> Spironolactone's androgen-receptor blockade causes gynecomastia. Switch to eplerenone, a selective MRA, to keep the mortality benefit.",
wrong={1:"Amiloride blocks ENaC directly but has no proven mortality benefit in HFrEF.",
2:"Hydrochlorothiazide treats symptoms only and wastes K⁺.",
3:"Stopping the MRA gives up a mortality benefit when a better-tolerated alternative exists.",
4:"Finasteride is antiandrogenic and could worsen gynecomastia."},
eli5="Spironolactone also blocks testosterone's receptor, which can grow breast tissue in men. Eplerenone does the heart job without blocking testosterone."),

dict(img='Aapeakt', cap='12-lead ECG',
stem="A 68-year-old woman with heart failure with reduced ejection fraction was started 3 weeks ago on enalapril and spironolactone in addition to furosemide and carvedilol. Her ECG at a follow-up visit is shown.{FIG}Which of the following best explains this ECG change?",
choices=["Less aldosterone action → less ENaC-driven K⁺ secretion","Furosemide-induced K⁺ wasting via NKCC2 inhibition","β-blocker–induced K⁺ shift into skeletal muscle","Direct inhibition of the Na⁺/K⁺-ATPase in cardiac myocytes","Enalapril-induced bradykinin release from the kidney"], key=0,
exp="The ECG shows <b>tall, narrow, peaked T waves</b>, which means <b>hyperkalemia</b>. This is the lecture's case 4. <b>Enalapril</b> (\"-pril\", ACE inhibitor) → ↓ angiotensin II → <b>↓ aldosterone</b>. <b>Spironolactone</b> blocks the aldosterone receptor. Both mean less ENaC → less Na⁺ entry in the collecting duct → less driving force for K⁺ secretion through ROMK → <b>K⁺ retention</b>. Furosemide pulls K⁺ the other way, so the net potassium is unpredictable. <b>Monitor K⁺ and renal function</b>. Board add-on: β-blockers also nudge K⁺ out of cells slightly.<br><br><b>Educational objective:</b> ACE inhibitors and spironolactone both reduce aldosterone action (less ENaC-driven K⁺ secretion) and together cause hyperkalemia.",
wrong={1:"Furosemide <b>lowers</b> K⁺ and would flatten T waves, not peak them.",
2:"β-blockers shift K⁺ <b>out</b> of cells slightly. They don't drive it into muscle.",
3:"Na⁺/K⁺-ATPase inhibition is digoxin, which isn't in her regimen.",
4:"Bradykinin causes cough and angioedema, not hyperkalemia."},
eli5="Aldosterone normally tells the kidney to dump potassium. Her two new drugs both turn aldosterone down, so potassium builds up and makes the T waves tall and pointy."),

dict(img=None,
stem="A 57-year-old man with type 2 diabetes and heart failure with reduced ejection fraction takes metformin, sacubitril/valsartan, carvedilol, spironolactone and a recently added once-daily drug. He comes in with 2 days of fever and severe pain, redness and swelling of the scrotum and perineum.{FIG}Which of his medications is most associated with this condition?",
choices=["Dapagliflozin","Carvedilol","Sacubitril/valsartan","Spironolactone","Metformin"], key=0,
exp="SGLT2 inhibitors (\"-gliflozin\": <b>dapagliflozin, empagliflozin</b>) are the adverse effect to counsel on. Dr. Scully: <b>gangrene of the perineum</b> (said fast in TV adverts). \"If you have any swelling or redness around the perineum, you need to come see me right away.\" Board add-on: this is <b>Fournier gangrene</b>, a necrotizing fasciitis that needs emergency surgery. Other SGLT2-inhibitor adverse effects: renal impairment, genital and urinary infections, back pain, difficulty urinating, volume depletion and euglycemic DKA. Benefits: ↓ hospitalization and mortality in HFrEF <b>with or without diabetes</b>, and they also work in HFpEF.<br><br><b>Educational objective:</b> SGLT2 inhibitors carry a risk of perineal necrotizing fasciitis (Fournier gangrene). Counsel patients to report perineal pain or swelling immediately.",
wrong={1:"Carvedilol causes bradycardia and hypotension, not genital infection.",
2:"The ARNI's risks are hypotension, hyperkalemia, angioedema and fetal toxicity.",
3:"Spironolactone causes hyperkalemia and gynecomastia.",
4:"Metformin causes GI upset and (rarely) lactic acidosis, not perineal infection."},
eli5="Dapagliflozin makes you pee out sugar, and sugar in the genital area can feed a rare but very dangerous infection. That's why patients are told to report pain or swelling there right away."),

dict(img=None,
stem="A 76-year-old woman has dyspnea on exertion and leg edema. Echocardiography shows a thick, stiff left ventricle with an ejection fraction of 60%. Her cardiologist adds a drug class that reduces heart failure hospitalization regardless of ejection fraction.{FIG}Which drug class was added?",
choices=["SGLT2 inhibitor","Loop diuretic","Cardiac glycoside","β1-adrenergic agonist","Organic nitrate"], key=0,
exp="An ejection fraction ≥ 50% with heart failure symptoms is <b>HFpEF</b>. The lecture focuses on HFrEF (EF < 40%), \"plus the one drug class that works in both\": the <b>SGLT2 inhibitors</b> (dapagliflozin, empagliflozin). Their mechanism is selective SGLT2 inhibition in the proximal tubule. That explains the glucose lowering, but the cardio-renal benefit also seems to involve anti-inflammatory, renoprotective and anti-remodelling effects \"we don't truly understand\". The 41–49% band is the zone \"no one really knows what to do with\" (board add-on: HF with mildly reduced EF).<br><br><b>Educational objective:</b> SGLT2 inhibitors reduce heart failure hospitalization in both HFrEF and HFpEF.",
wrong={1:"A loop diuretic relieves congestion but doesn't change hospitalization or mortality as a disease-modifying class.",
2:"Digoxin is a secondary symptomatic drug for HFrEF.",
3:"Inotropes are for decompensated low-output HFrEF, not stable HFpEF.",
4:"Nitrates relieve preload symptoms only."},
eli5="Most heart-failure pills only help a weak, floppy heart. SGLT2 inhibitors also help a stiff heart that still squeezes normally."),

dict(img=None,
stem="A 64-year-old man with heart failure with reduced ejection fraction is started on carvedilol rather than atenolol. His cardiologist explains that carvedilol offers a hemodynamic benefit beyond lowering heart rate.{FIG}Which property of carvedilol provides this additional benefit?",
choices=["α1 blockade that lowers afterload","β1 selectivity that spares the lungs","β2 partial agonism that dilates vessels","Stimulation of endothelial nitric oxide","Inhibition of renal Na⁺ reabsorption"], key=0,
exp="β-blockers reduce mortality in HFrEF by <b>↓ heart rate and contractility → ↓ O₂ demand</b> and by blunting the chronic sympathetic drive (including renin release). <b>Carvedilol</b>, a third-generation agent, also <b>blocks α1 receptors → vasodilation → ↓ afterload</b>, so the weak ventricle gets more output from the contractility it has. Board add-on: the evidence-based three are carvedilol, metoprolol succinate and bisoprolol. Start low, titrate slowly, and don't start during acute decompensation.<br><br><b>Educational objective:</b> Carvedilol adds α1 blockade (↓ afterload) to the β-blocker's ↓ O₂ demand, and it is a mortality-proven HFrEF β-blocker.",
wrong={1:"Carvedilol is <b>non-selective</b> (β1 + β2 + α1).",
2:"Carvedilol has no β2 agonist activity, and partial agonism (as with pindolol) is undesirable in HF.",
3:"Nitric oxide release is <b>nebivolol</b>'s feature.",
4:"Carvedilol isn't a diuretic."},
eli5="Carvedilol slows the overworked heart and also relaxes the blood vessels, so the heart has less resistance to push against."),

dict(img=None,
stem="A 58-year-old Black man is newly diagnosed with heart failure with reduced ejection fraction (ejection fraction 28%). An older handout in the clinic says renin–angiotensin system drugs are less effective in Black patients.{FIG}Which of the following is the most appropriate approach to his renin–angiotensin system therapy?",
choices=["Start an ARNI or ACE inhibitor as in any patient","Avoid RAAS drugs because of his race","Use hydralazine-nitrate instead of any RAAS drug","Use a RAAS drug only if his BP remains high","Start an ARNI only after a trial of a diuretic"], key=0,
exp="Dr. Scully ended the lecture on this point. Heart failure was one of the first conditions where <b>avoiding RAAS drugs in Black patients was debunked</b>. You may still see the old recommendation in some materials, but it has been disproven repeatedly and removed from the risk calculators. <b>Race-agnostic prescribing closes racial disparities</b> in cardiovascular outcomes. He gets the four pillars like anyone else. Board add-on: hydralazine + isosorbide dinitrate is an <b>add-on</b> (A-HeFT) for self-identified Black patients with NYHA III–IV symptoms despite full therapy. It is not a replacement.<br><br><b>Educational objective:</b> RAAS drugs (ARNI/ACEi/ARB) are first-line in HFrEF regardless of race. Hydralazine-nitrate is an add-on, not a substitute.",
wrong={1:"Withholding RAAS drugs by race is a debunked practice that widens disparities.",
2:"Hydralazine-nitrate is an add-on (or used when RAAS drugs aren't tolerated), not a race-based substitute.",
3:"In HFrEF, RAAS drugs are given for mortality benefit, not just blood pressure.",
4:"Pillar therapy shouldn't wait on a diuretic trial. Diuretics are for symptoms."},
eli5="An old rule said these heart drugs didn't work as well in Black patients. That's been proven wrong, so he gets the same life-saving medicines as everyone else."),

dict(img=None,
stem="A 73-year-old man with heart failure with reduced ejection fraction is admitted with dyspnea and edema. IV furosemide produces a 4-L diuresis; his breathing and leg swelling improve. However, he remains fatigued with cool extremities and low urine sodium.{FIG}Which of the following best explains why his fatigue persists?",
choices=["Preload reduction slides him down the same curve","Furosemide directly depresses myocardial contractility","Diuresis raised his afterload through hemoconcentration","He moved onto a higher Frank–Starling curve","Loop diuretics cause tolerance after a single dose"], key=0,
exp="Use the lecture's Frank–Starling map (slide 16). Untreated, a failing heart sits at point C: <b>high end-diastolic pressure</b> (congestion) and <b>low output</b>. <b>Preload reduction (furosemide) moves C → G down the same curve</b>. End-diastolic pressure falls and congestion improves, but cardiac output <b>doesn't rise</b>, so low-output symptoms (fatigue, cool extremities) remain. To lift output he needs a <b>new curve</b>: afterload reduction (ACE inhibitor, C → F) or an inotrope (C → D → E). \"These things don't get tested in a vacuum.\"<br><br><b>Educational objective:</b> Diuretics relieve congestion by moving down the same Frank–Starling curve without raising cardiac output. Afterload reducers and inotropes move the patient onto a higher curve.",
wrong={1:"Furosemide isn't negatively inotropic.",
2:"A modest diuresis doesn't meaningfully raise afterload. The problem is the unchanged curve.",
3:"Only afterload reducers and inotropes shift the patient to a higher curve. A diuretic doesn't.",
4:"Tolerance develops over days to weeks, and he clearly responded to this dose."},
eli5="The water pill drained the backed-up fluid, but it didn't make the pump any stronger. He breathes better but still feels tired."),

dict(img=None,
stem="Pressure–volume loops are recorded in a 70-year-old woman with 15 years of poorly controlled hypertension and concentric left ventricular hypertrophy, and compared with a healthy control.{FIG}Which change in her loop best reflects this remodelling?",
choices=["A steeper, higher end-diastolic pressure–volume curve","A wider loop with a larger stroke volume","A rightward shift with a much larger end-diastolic volume","A lower end-diastolic pressure at every filling volume","A flatter end-systolic pressure–volume relationship only"], key=0,
exp="Remodelling: chronic wall stress → <b>hypertrophy</b> → <b>↓ ventricular compliance</b> → worse performance. On a pressure–volume loop, the bottom (filling) limb <b>kicks up</b>. Pressure rises more for each mL of filling, so the end-diastolic pressure–volume curve is steeper and shifted up and left. Dr. Scully: \"Here's 4 PV loops — pick the one that demonstrates cardiac remodelling and hypertrophy\" is the kind of physiology question this pharmacology rests on.<br><br><b>Educational objective:</b> Hypertrophic remodelling lowers compliance, so the diastolic filling curve of the PV loop becomes steeper and higher.",
wrong={1:"A wider loop with more stroke volume means improved performance or higher preload, not stiffness.",
2:"A large end-diastolic volume with a rightward shift is eccentric (dilated) remodelling, not concentric hypertrophy.",
3:"Lower filling pressure means a <b>more</b> compliant ventricle, the opposite.",
4:"A flatter end-systolic relationship means reduced contractility. Compliance shows on the diastolic limb."},
eli5="A thick, stiff heart is like a balloon that's hard to blow up: a little more blood makes the pressure jump. On the loop, the bottom 'filling' line turns upward sharply."),

dict(img='Aapitting', cap='Examination of the lower leg',
stem="A 71-year-old woman with long-standing heart failure with reduced ejection fraction has the finding shown on both legs. Her B-type natriuretic peptide is markedly elevated, yet her kidneys continue to retain sodium.{FIG}Which of the following best explains why her natriuretic peptides fail to correct the volume overload?",
choices=["Dilated atria become resistant to natriuretic peptide","Her atria have stopped producing natriuretic peptides","Natriuretic peptides constrict the renal afferent arteriole","Neprilysin is absent in heart failure","Aldosterone is suppressed by the high peptide levels"], key=0,
exp="The photo shows <b>pitting edema</b>. Lecture slide 7: atrial stretch should release ANP to \"try to make you pee\" and cut preload, but <b>chronically dilated atria become resistant to natriuretic peptide</b>, so the response fails. The kidney still senses low pressure and keeps reabsorbing Na⁺ and water. Hydrostatic pressure rises, fluid transudates into the tissues (pulmonary and peripheral edema), pressure drops again, and the cycle repeats. That's why the ARNI's sacubitril, which slows natriuretic-peptide breakdown, helps.<br><br><b>Educational objective:</b> In chronic heart failure, resistance to natriuretic peptides lets the kidney keep retaining Na⁺ despite volume overload, which causes edema.",
wrong={1:"Her BNP is high, so the peptides are being made.",
2:"Natriuretic peptides <b>dilate</b> the afferent arteriole and promote natriuresis.",
3:"Neprilysin is present. Inhibiting it is how sacubitril raises peptide levels.",
4:"Aldosterone is <b>elevated</b> in heart failure (RAAS activation), not suppressed."},
eli5="Her stretched heart is shouting 'get rid of salt and water!', but the body has stopped listening. So the kidneys keep holding fluid, and it leaks into her legs."),

dict(img=None,
stem="A 66-year-old man with heart failure with reduced ejection fraction develops a persistent dry, tickling cough 3 weeks after starting enalapril. His blood pressure and potassium are at goal. He has no history of angioedema.{FIG}Which of the following is the most appropriate change?",
choices=["Switch to an angiotensin receptor blocker","Add a cough suppressant and continue enalapril","Switch to a different ACE inhibitor","Stop all renin–angiotensin system therapy","Replace enalapril with furosemide"], key=0,
exp="ACE also breaks down <b>bradykinin</b>, so ACE inhibitors raise bradykinin and cause a <b>dry cough</b> (and, rarely, angioedema). The lecture lists cough and angioedema as ACE-inhibitor adverse effects. The fix is to keep RAAS blockade without the bradykinin effect: <b>switch to an ARB</b> (board add-on). An ARNI is the preferred RAAS drug in HFrEF, but it also raises bradykinin through neprilysin inhibition, and starting it needs a 36-hour ACE-inhibitor washout. Never give two RAAS drugs together.<br><br><b>Educational objective:</b> ACE-inhibitor cough is bradykinin-mediated. Switch to an ARB to keep RAAS blockade.",
wrong={1:"The cough is a drug effect that persists. Suppressants don't fix it.",
2:"Cough is a class effect of all ACE inhibitors.",
3:"Stopping RAAS therapy gives up a mortality benefit.",
4:"Furosemide relieves symptoms only and doesn't replace a mortality drug."},
eli5="Enalapril lets a chemical called bradykinin build up, and that tickles the throat. A cousin drug (an ARB) does the same heart job without the tickle."),

dict(img=None,
stem="A heart failure patient is treated with drugs that interrupt the renin–angiotensin–aldosterone system at three different points.{FIG}Which of the following correctly matches each drug class with its point of action?",
choices=["β-blocker: renin release; ACEi: AT II; MRA: receptor","β-blocker: AT II; ACEi: renin release; MRA: receptor","β-blocker: receptor; ACEi: AT II; MRA: renin release","β-blocker: renin release; ACEi: receptor; MRA: AT II","β-blocker: AT II; ACEi: receptor; MRA: renin release"], key=0,
exp="Slide notes: the RAAS can be blocked at three points.<br>1. <b>β-blockers ↓ renin release</b> (β1 on juxtaglomerular cells).<br>2. <b>ACE inhibitors ↓ angiotensin II</b> formation (ARBs block its AT1 receptor).<br>3. <b>Spironolactone (MRA)</b> blocks aldosterone at its <b>receptor</b>.<br>Diuretics counter Na⁺ retention, venodilators raise venous capacitance (↓ preload), arterial vasodilators relieve α- and AT II-driven vasoconstriction (↓ afterload), and glycosides, β-agonists and PDE inhibitors raise contractility.<br><br><b>Educational objective:</b> In HF, β-blockers reduce renin release, ACE inhibitors reduce angiotensin II, and MRAs block the aldosterone receptor.",
wrong={1:"β-blockers act upstream on renin. ACE inhibitors act on AT II formation.",
2:"β-blockers don't block the aldosterone receptor, and MRAs don't affect renin release.",
3:"ACE inhibitors don't act at a receptor, and MRAs don't act on AT II.",
4:"This scrambles all three targets."},
eli5="Think of a relay race. β-blockers stop the first runner (renin), ACE inhibitors stop the handoff to angiotensin II, and spironolactone blocks the finish line (aldosterone's receptor)."),

dict(img=None,
stem="A 69-year-old woman with heart failure with reduced ejection fraction is hospitalized with acute decompensation: wet rales, oxygen saturation 87%, blood pressure 150/96 mm Hg and warm extremities. She is placed upright on oxygen with IV access and continuous monitoring.{FIG}Which of the following, along with prompt IV diuresis, belongs in the lecture's early decompensation checklist?",
choices=["Early vasodilator therapy","Immediate norepinephrine","Starting carvedilol today","Intravenous digoxin load","Fluid bolus of 1 L"], key=0,
exp="The lecture's decompensation checklist (slide 12): airway assessment and pulse oximetry → supplemental O₂ and ventilatory support → vital signs (hypo- or hypertension) → continuous monitoring and IV access → <b>seated posture</b> → <b>prompt diuretic therapy</b> → <b>early vasodilator therapy</b> → urine-output monitoring. She is hypertensive and congested (\"warm and wet\"), so a vasodilator such as nitroglycerin lowers preload and afterload. Once stable, start the four pillars. Inotropes are for hypotension or low output with adequate preload.<br><br><b>Educational objective:</b> Acute decompensated HF with congestion and adequate BP is treated with oxygen, upright posture, IV loop diuretic and early vasodilator therapy.",
wrong={1:"A vasopressor is for persistent shock. Her BP is high, and norepinephrine would raise afterload.",
2:"β-blockers are not started during acute decompensation (board add-on). Start once she is euvolemic.",
3:"Digoxin is secondary therapy and doesn't treat acute congestion.",
4:"She is volume overloaded. Fluid would worsen the pulmonary edema."},
eli5="She's drowning in fluid with high blood pressure, so you sit her up, give oxygen, pull fluid off with a diuretic, and open up her blood vessels to take pressure off the heart."),

dict(img=None,
stem="A hospitalized patient with decompensated heart failure with reduced ejection fraction has a systolic blood pressure of 80 mm Hg, cool extremities, narrow pulse pressure, low urine output and confusion, despite adequate filling pressures.{FIG}Which of the following is the most appropriate first agent, according to the lecture algorithm?",
choices=["An inotrope such as dobutamine","A vasopressor such as phenylephrine","An IV loop diuretic","A nitroprusside infusion","Carvedilol or another β-blocker"], key=0,
exp="Slide 13, hypotension in a decompensated patient: first <b>assess volume</b> (diurese or resuscitate). If SBP < 85 mm Hg or there are shock signs (cool extremities, narrow pulse pressure, low urine output, confusion) <b>with adequate preload, add an inotrope</b>: dobutamine, milrinone or digoxin. <b>Vasopressors</b> (norepinephrine, phenylephrine, high-dose dopamine) are a <b>temporizing</b> measure for persistent shock. They raise BP and organ perfusion \"at the cost of\" ↑ afterload, which the weak ventricle must overcome, and that can lower cardiac output. \"Very situation specific.\"<br><br><b>Educational objective:</b> Cardiogenic hypotension with adequate preload calls for an inotrope first. Vasopressors are a temporary bridge because they raise afterload.",
wrong={1:"A pure vasopressor raises afterload on a failing ventricle. It is reserved for persistent shock.",
2:"Filling pressures are adequate, and diuresis would drop the BP further.",
3:"Nitroprusside would worsen hypotension.",
4:"A β-blocker would depress contractility in cardiogenic shock."},
eli5="The pump is too weak to keep blood pressure up. An inotrope makes the pump squeeze harder. Squeezing the pipes (a vasopressor) would just make the weak pump's job harder."),
]
