# Ischemic Heart Disease Pharmacology (Scully) — Version 2, 18 items (2 with images): stable angina case, β-blockers, calcium channel blockers, ranolazine, risk reduction
Q = [
dict(img=None,
stem="A 58-year-old man has had chest pain radiating to his left arm and jaw for 3 months. It comes on with brisk walking or stairs, lasts 5–10 minutes and goes away with rest. He has controlled hypertension, hyperlipidemia and type 2 diabetes, quit smoking 10 years ago, and his father had a myocardial infarction at 62. Blood pressure is 138/86 mm Hg, pulse 80/min; the examination is normal. He is given sublingual nitroglycerin for attacks.{FIG}Which drug is the best single agent to prevent his attacks?",
choices=["Metoprolol","Isosorbide mononitrate","Ranolazine","Short-acting nifedipine","Hydralazine"], key=0,
exp="This is case 2: <b>stable (exertional) angina</b>, meaning exertional pain relieved by rest plus cardiovascular risk factors. The plan: <b>as-needed sublingual nitroglycerin</b> for attacks + a <b>β-blocker, the best monotherapy for prevention</b> ± a calcium channel blocker or long-acting nitrate, with <b>ranolazine if refractory</b>. Add risk reduction: antiplatelet therapy, a statin, smoking cessation and comorbidity control. β-blockers ↓ heart rate and contractility → ↓ O₂ demand. They are titrated to a resting heart rate of about 50/min (lecture figure) and limit the exertional peak.<br><br><b>Educational objective:</b> A β-blocker is the best single agent for preventing stable exertional angina, alongside as-needed sublingual nitroglycerin.",
wrong={1:"Long-acting nitrates are add-ons and not first-line monotherapy (tolerance, reflex tachycardia).",
2:"Ranolazine is reserved for refractory angina.",
3:"Short-acting nifedipine causes reflex tachycardia that can worsen ischemia.",
4:"Hydralazine is an arteriolar dilator that causes reflex tachycardia, and it isn't an antianginal."},
eli5="His heart muscle runs short of oxygen when he exerts himself. A β-blocker keeps the heart rate and squeeze down, so it needs less oxygen and the pain is less likely to start."),

dict(img=None,
stem="The patient with stable angina is started on metoprolol and titrated to a resting heart rate of about 50/min. His exertional episodes become much less frequent.{FIG}Which of the following best explains how slowing the heart rate relieves his ischemia?",
choices=["Lower O₂ demand, longer diastole","More preload that stretches the myocytes","Direct dilation of epicardial coronary arteries","Less venous return through venodilation","Increased contractility from longer filling"], key=0,
exp="β-blockers <b>↓ heart rate and contractility → ↓ myocardial O₂ demand</b>, and they blunt the exertional rise in heart rate. Board add-on: a slower rate also <b>lengthens diastole</b>, when the left ventricle is perfused, so supply improves a little too. The trade-off is that a longer filling time slightly <b>raises end-diastolic volume</b>, which a nitrate offsets. Dosing per the lecture: titrate to a resting heart rate of ~50/min and limit the exertional peak.<br><br><b>Educational objective:</b> β-blockers relieve angina by lowering heart rate and contractility (↓ O₂ demand), with longer diastolic perfusion as a bonus.",
wrong={1:"More preload <b>raises</b> wall stress and O₂ demand. It's a side effect, not the benefit.",
2:"β-blockers don't dilate coronary arteries. They remove β2 dilation, which is the problem in vasospasm.",
3:"Venodilation is how nitrates work.",
4:"β-blockers <b>reduce</b> contractility."},
eli5="A slower heartbeat means the heart does less work and has more resting time between beats to refill its own arteries with blood."),

dict(img=None,
stem="A 64-year-old woman with stable angina takes both metoprolol and isosorbide mononitrate. A student asks why the combination works better than either drug alone.{FIG}Which of the following best explains the benefit of combining them?",
choices=["Each cancels the other's unwanted effect","Both drugs lower preload through venodilation","The nitrate prevents β-blocker tolerance","The β-blocker speeds nitrate bioactivation","Both drugs raise coronary blood supply directly"], key=0,
exp="Board add-on table, building on the lecture's point that nitrates are paired with β-blockers:<br>• <b>Nitrate</b>: ↓ preload but <b>reflex tachycardia and ↑ contractility</b>.<br>• <b>β-blocker</b>: ↓ heart rate and contractility, but a slower rate lengthens filling, so <b>end-diastolic volume ↑</b>.<br>• <b>Together</b>: the β-blocker stops the reflex tachycardia, and the nitrate stops the EDV increase. Myocardial O₂ demand falls the most.<br><br><b>Educational objective:</b> β-blockers and nitrates are complementary. The β-blocker blocks nitrate reflex tachycardia, and the nitrate offsets the β-blocker's rise in end-diastolic volume.",
wrong={1:"β-blockers don't venodilate. They can actually raise EDV.",
2:"Tolerance is a nitrate problem, prevented by a nitrate-free interval.",
3:"Nitrate bioactivation (ALDH2) isn't affected by β-blockers.",
4:"Neither drug's main benefit is raising supply. Both lower demand."},
eli5="Nitroglycerin makes the heart race a bit, and the β-blocker stops that. The β-blocker makes the heart fill a bit more, and the nitrate stops that. Each one cancels the other's downside."),

dict(img=None,
stem="A 60-year-old man with stable angina asks to switch his β-blocker to one he read has \"partial agonist\" activity, because his heart rate is 54/min.{FIG}Which β-blocker has this property and is generally avoided in angina?",
choices=["Pindolol","Metoprolol","Atenolol","Carvedilol","Bisoprolol"], key=0,
exp="Board add-on: β-blockers with <b>intrinsic sympathomimetic activity (ISA)</b>, such as <b>pindolol and acebutolol</b>, are <b>partial agonists</b>. They block the full catecholamine effect but stimulate the receptor a little themselves, so they <b>don't lower resting heart rate and O₂ demand</b> as much. They're avoided in angina (and post-MI). A resting rate of ~50/min is the lecture's target, not a reason to switch.<br><br><b>Educational objective:</b> β-blockers with intrinsic sympathomimetic activity (pindolol, acebutolol) are avoided in angina because partial agonism keeps O₂ demand up.",
wrong={1:"Metoprolol is β1-selective with no ISA, a standard antianginal.",
2:"Atenolol is β1-selective with no ISA.",
3:"Carvedilol blocks β and α1 with no ISA.",
4:"Bisoprolol is β1-selective with no ISA."},
eli5="Pindolol blocks the receptor but also pokes it a little, so the heart doesn't slow down as much. That's the opposite of what an angina patient needs."),

dict(img=None,
stem="A 62-year-old woman with stable angina cannot tolerate β-blockers because of fatigue. She is started on amlodipine, and her angina improves without any change in her resting heart rate.{FIG}How does amlodipine lower her myocardial oxygen demand?",
choices=["Arterial dilation lowers afterload","Slowing of AV-node conduction","Direct negative inotropy on myocytes","Venodilation that lowers preload","Blockade of the late Na⁺ current"], key=0,
exp="Calcium channel blockers <b>↓ afterload</b> through arterial dilation → ↓ impedance to ejection → less contractility and heart rate needed for the same output → <b>↓ O₂ demand</b>. <b>Dihydropyridines</b> (amlodipine, nifedipine) are selective for vascular smooth muscle, so they don't slow the heart. They can cause reflex tachycardia, edema and flushing. <b>Diltiazem and verapamil</b> also directly ↓ contractility and heart rate. CCBs work as monotherapy or with a nitrate or β-blocker.<br><br><b>Educational objective:</b> Dihydropyridine CCBs relieve angina mainly by arterial dilation (↓ afterload), without slowing the heart.",
wrong={1:"AV-node slowing is a non-dihydropyridine (verapamil, diltiazem) effect.",
2:"Amlodipine is vascular-selective with minimal direct cardiac depression.",
3:"Venodilation is the nitrate mechanism.",
4:"Late Na⁺-current block is ranolazine."},
eli5="Amlodipine relaxes the arteries the heart pumps into, so there's less resistance to push against. The heart does less work without beating any slower."),

dict(img='Aaedema', cap='Photograph of the foot',
stem="A 66-year-old woman with stable angina was started on amlodipine 10 mg daily 6 weeks ago. She now has swelling of both feet by evening (shown). Her jugular venous pressure is normal, her lungs are clear, and her serum albumin and kidney function are normal.{FIG}Which of the following best explains the swelling?",
choices=["Precapillary dilation raises capillary pressure","Sodium retention from drug-induced aldosterone release","Lymphatic obstruction from drug deposits","New heart failure from the drug's negative inotropy","Hypoalbuminemia from hepatic toxicity"], key=0,
exp="The lecture lists <b>peripheral edema</b> as a dihydropyridine adverse effect (with flushing and reflex tachycardia). Diltiazem also causes edema. Board add-on mechanism: dihydropyridines dilate <b>precapillary arterioles</b> more than venules, so <b>capillary hydrostatic pressure rises</b> and fluid filters into the tissues. It's dose-dependent and not from fluid retention, so <b>diuretics work poorly</b>. Adding an ACE inhibitor or ARB (which dilates venules) or lowering the dose helps.<br><br><b>Educational objective:</b> Dihydropyridine edema comes from precapillary arteriolar dilation raising capillary pressure. It isn't heart failure and responds poorly to diuretics.",
wrong={1:"It isn't a volume-retention edema, which is why diuretics help little.",
2:"Amlodipine doesn't obstruct lymphatics.",
3:"Her JVP and lungs are normal, and amlodipine has minimal negative inotropy.",
4:"Her albumin is normal."},
eli5="Amlodipine opens the small arteries feeding the feet more than the veins draining them. Blood pressure inside the tiny capillaries goes up and pushes fluid out into the ankles."),

dict(img=None,
stem="A 70-year-old man with stable angina is started on a short-acting formulation of nifedipine. Within an hour of each dose his heart rate rises to 110/min, and his angina becomes more frequent.{FIG}Which of the following best explains the worsening?",
choices=["Abrupt vasodilation triggers reflex tachycardia","Nifedipine blocks β1 receptors, raising catecholamines","Nifedipine causes coronary vasospasm directly","Nifedipine slows AV conduction, causing ischemia","Nifedipine raises preload by constricting veins"], key=0,
exp="Board add-on: <b>short-acting nifedipine</b> drops blood pressure abruptly → baroreceptor reflex → <b>sympathetic reflex tachycardia</b> and ↑ contractility → ↑ O₂ demand → worse ischemia. That's why short-acting nifedipine is avoided in angina. Long-acting dihydropyridines (amlodipine) cause much less of this, and pairing a dihydropyridine with a β-blocker is a good combination. Reflex tachycardia is a listed dihydropyridine adverse effect.<br><br><b>Educational objective:</b> Short-acting nifedipine can worsen angina through reflex tachycardia from abrupt vasodilation.",
wrong={1:"Nifedipine doesn't block β-receptors.",
2:"CCBs <b>prevent</b> coronary spasm.",
3:"Dihydropyridines barely affect the AV node.",
4:"Nifedipine dilates arteries. It doesn't constrict veins."},
eli5="Fast-acting nifedipine drops blood pressure suddenly, and the body panics and speeds the heart up. A racing heart needs more oxygen, so the angina gets worse."),

dict(img=None,
stem="A 63-year-old man with stable angina still has exertional symptoms despite metoprolol at a resting heart rate of 56/min and as-needed nitroglycerin. His physician adds a calcium channel blocker.{FIG}Which calcium channel blocker is the safest addition?",
choices=["Amlodipine","Verapamil","Diltiazem","Short-acting nifedipine","Bepridil"], key=0,
exp="Board add-on, consistent with the lecture's warnings: a <b>dihydropyridine (amlodipine) + β-blocker</b> is a good pair. The β-blocker blunts the dihydropyridine's reflex tachycardia, and amlodipine adds afterload reduction without further slowing the node. <b>Verapamil or diltiazem + β-blocker</b> risks <b>bradycardia and AV block</b> (both slow the node and depress contractility). IV verapamil with a β-blocker is contraindicated (electromechanical dissociation).<br><br><b>Educational objective:</b> When adding a CCB to a β-blocker for angina, choose a long-acting dihydropyridine such as amlodipine to avoid bradycardia and AV block.",
wrong={1:"Verapamil + β-blocker → bradycardia, AV block, heart failure.",
2:"Diltiazem + β-blocker carries the same additive nodal risk.",
3:"Short-acting nifedipine causes reflex tachycardia and can worsen ischemia.",
4:"Bepridil is an old CCB that prolongs the QT and is rarely used."},
eli5="His β-blocker is already slowing his heart. Amlodipine relaxes the arteries without slowing the heart any more, so it's the safe partner."),

dict(img=None,
stem="A 74-year-old woman with stable angina and hypertension was started on a calcium channel blocker 2 months ago. She now has hard stools only every 4–5 days. Her heart rate is 58/min.{FIG}Which calcium channel blocker is she most likely taking?",
choices=["Verapamil","Amlodipine","Nifedipine","Felodipine","Nicardipine"], key=0,
exp="CCB adverse effects are mostly exaggerations of their action:<br>• <b>Verapamil</b>: <b>constipation</b> (signature), bradycardia, AV block, heart failure.<br>• Diltiazem: edema, bradycardia.<br>• <b>Dihydropyridines</b> (amlodipine, nifedipine, felodipine, nicardipine): peripheral edema, flushing, headache, reflex tachycardia, and they don't slow the heart.<br>Constipation plus a slow heart rate points to verapamil, the CCB most selective for nodal tissue. It also raises digoxin levels.<br><br><b>Educational objective:</b> Verapamil's signature adverse effect is constipation, along with bradycardia and AV block.",
wrong={1:"Amlodipine causes edema and flushing, not prominent constipation, and doesn't slow the heart.",
2:"Nifedipine causes reflex tachycardia, not bradycardia.",
3:"Felodipine is a vascular-selective dihydropyridine.",
4:"Nicardipine is a dihydropyridine (often IV) with vascular effects."},
eli5="Verapamil relaxes the gut's smooth muscle as well as the heart's, so things move slowly. That's constipation."),

dict(img=None,
stem="A 69-year-old man with stable angina also has atrial fibrillation with a resting ventricular rate of 118/min. He is not on a β-blocker because of severe peripheral arterial disease symptoms with one in the past.{FIG}Which single drug best addresses both his angina and his ventricular rate?",
choices=["Diltiazem","Amlodipine","Nifedipine","Isosorbide mononitrate","Ranolazine"], key=0,
exp="<b>Diltiazem</b> (non-dihydropyridine) ↓ afterload <b>and</b> directly ↓ heart rate, AV-node conduction and contractility. That lowers O₂ demand <b>and</b> controls the ventricular rate in atrial fibrillation (class IV rate control). Diltiazem \"just does both\" (vessel and node). Dihydropyridines only dilate vessels and can raise the rate reflexively. Watch for bradycardia, AV block, hypotension and edema.<br><br><b>Educational objective:</b> Diltiazem treats angina (↓ afterload, ↓ HR and contractility) and controls the ventricular rate in AF.",
wrong={1:"Amlodipine treats angina but doesn't slow AV conduction.",
2:"Nifedipine can cause reflex tachycardia.",
3:"A nitrate treats angina but doesn't control the AF rate.",
4:"Ranolazine doesn't change heart rate."},
eli5="Diltiazem relaxes the arteries and also slows the heart's gatekeeper, so it eases the angina and calms the fast AF rate at the same time."),

dict(img=None,
stem="A 67-year-old man with refractory stable angina despite a β-blocker, amlodipine and a long-acting nitrate is started on ranolazine.{FIG}Which sequence best describes how ranolazine relieves angina?",
choices=["↓ Late Na⁺ current → ↓ Ca²⁺ overload → ↓ wall stress","↓ Heart rate via funny-current block → ↓ O₂ demand","Venodilation via NO → ↓ preload → ↓ wall stress","↓ Fatty acid oxidation → ↑ glucose use → more ATP","Coronary dilation via K⁺-channel opening → ↑ O₂ supply"], key=0,
exp="Ischemic myocytes have an <b>increased late-phase Na⁺ current</b> → ↑ intracellular Na⁺ → the <b>Na⁺/Ca²⁺ exchanger brings Ca²⁺ in</b> → <b>Ca²⁺ overload</b> → ↑ <b>diastolic wall stress</b> → ↑ O₂ demand (and worse supply). <b>Ranolazine reduces the late Na⁺ current</b>, so less Na⁺ and Ca²⁺ load, ↓ diastolic wall stress and ↓ O₂ demand. It isn't first-line. It's for refractory angina. Adverse effects: dose-dependent <b>QT prolongation</b>, dizziness, constipation.<br><br><b>Educational objective:</b> Ranolazine blocks the late Na⁺ current, preventing Na⁺-driven Ca²⁺ overload and lowering diastolic wall stress.",
wrong={1:"Funny-current (I<sub>f</sub>) block describes ivabradine.",
2:"Venodilation via NO is the nitrate mechanism.",
3:"Partial fatty acid oxidation inhibition was an older proposed mechanism. The lecture's mechanism is the late Na⁺ current.",
4:"K⁺-channel opening describes nicorandil, not ranolazine."},
eli5="Starved heart cells let too much sodium leak in, which drags calcium in after it, and the muscle can't fully relax. Ranolazine plugs that sodium leak, so the muscle relaxes and uses less oxygen."),

dict(img='Aatorsades', cap='12-lead ECG recorded during palpitations',
stem="A 71-year-old woman with refractory angina has taken ranolazine for 6 months. She is prescribed clarithromycin for pneumonia, and 3 days later she has palpitations and a brief faint. Her ECG during palpitations is shown; her potassium and magnesium are normal.{FIG}Which of the following best explains this arrhythmia?",
choices=["A CYP3A4 inhibitor raised ranolazine levels and the QT","Ranolazine's late Na⁺ block caused complete heart block","Clarithromycin induced ranolazine's hepatic clearance","Pneumonia-related hypoxemia caused re-entrant VT","Ranolazine shortened the QT, triggering fibrillation"], key=0,
exp="The ECG shows <b>torsades de pointes</b>. Ranolazine causes <b>dose-dependent QT prolongation</b>. Board add-on: it's a <b>CYP3A4 substrate</b>. <b>Clarithromycin</b> is a strong CYP3A4 inhibitor that <b>raises ranolazine levels</b> and also <b>prolongs the QT itself</b>. Avoid strong CYP3A4 inhibitors and other QT-prolonging drugs with ranolazine. Ranolazine doesn't change heart rate or BP.<br><br><b>Educational objective:</b> Ranolazine prolongs the QT in a dose-dependent way, and CYP3A4 inhibitors or other QT drugs (such as clarithromycin) can trigger torsades.",
wrong={1:"Ranolazine doesn't cause heart block, and the ECG shows polymorphic VT.",
2:"Clarithromycin <b>inhibits</b> CYP3A4. It doesn't induce it.",
3:"Hypoxemia-related VT would be monomorphic or ischemic, not this twisting pattern.",
4:"Ranolazine <b>prolongs</b> the QT."},
eli5="The antibiotic blocked the liver enzyme that clears ranolazine, so ranolazine built up. Both drugs stretch the heart's reset time, and together they set off the twisting rhythm."),

dict(img=None,
stem="A 76-year-old woman with stable angina has persistent symptoms despite isosorbide mononitrate and as-needed nitroglycerin. Her resting heart rate is 52/min and her blood pressure is 98/60 mm Hg; she felt faint on low doses of both metoprolol and amlodipine.{FIG}Which add-on drug is least likely to lower her heart rate or blood pressure further?",
choices=["Ranolazine","Diltiazem","Verapamil","Carvedilol","Nifedipine"], key=0,
exp="<b>Ranolazine</b> acts on the <b>late Na⁺ current</b>, so it relieves angina by lowering diastolic wall stress <b>without changing heart rate or blood pressure</b> (board add-on). That makes it useful when β-blockers and CCBs are limited by bradycardia or hypotension. It's the lecture's drug for <b>refractory</b> angina. The lecture also notes a <b>sex-specific effect</b>: in trials, XX patients saw a larger clinical benefit than XY patients. Watch the QT, dizziness and constipation.<br><br><b>Educational objective:</b> Ranolazine relieves refractory angina without lowering heart rate or blood pressure.",
wrong={1:"Diltiazem lowers heart rate and blood pressure.",
2:"Verapamil causes bradycardia, AV block and hypotension.",
3:"Carvedilol lowers heart rate and blood pressure (β + α1 block).",
4:"Nifedipine lowers blood pressure."},
eli5="Her pulse and blood pressure are already low, so the usual angina pills make her faint. Ranolazine works inside the heart muscle cells and doesn't push either number down."),

dict(img=None,
stem="Clinical trials of ranolazine in chronic angina were reviewed in the lecture, including a difference in benefit between patient groups.{FIG}Which group showed a larger clinical benefit from ranolazine?",
choices=["Patients with XX chromosomes","Patients with XY chromosomes","Patients over 80 years","Current smokers","Patients with vasospasm"], key=0,
exp="Dr. Scully highlighted a <b>sex-specific effect</b>: in the ranolazine trials, <b>XX patients saw a larger clinical benefit than XY patients</b>. Ranolazine reduces the late Na⁺ current → less Na⁺-driven Ca²⁺ overload → ↓ diastolic wall stress → ↓ O₂ demand. It's for refractory stable angina. Adverse effects: QT prolongation, dizziness, constipation.<br><br><b>Educational objective:</b> Ranolazine showed a greater clinical benefit in XX than XY patients in its angina trials.",
wrong={1:"XY patients had the <b>smaller</b> benefit.",
2:"The lecture didn't single out an age-based difference.",
3:"Smoking status wasn't the highlighted difference.",
4:"Ranolazine isn't a vasospastic-angina drug. CCBs and nitrates are."},
eli5="In the studies, ranolazine helped female (XX) patients more than male (XY) patients."),

dict(img=None,
stem="The 58-year-old man with stable angina (hypertension, hyperlipidemia, diabetes, ex-smoker, family history) is now well controlled on metoprolol and as-needed nitroglycerin.{FIG}Which additional drug is aimed at reducing his risk of myocardial infarction rather than relieving his angina?",
choices=["Low-dose aspirin","Isosorbide mononitrate","Ranolazine","Amlodipine","Diltiazem"], key=0,
exp="The lecture's treatment map has two halves:<br>• <b>Antianginals</b> (symptoms): nitrates, β-blockers, CCBs, ranolazine.<br>• <b>Risk reduction</b> for every patient: <b>antiplatelet therapy</b> (low-dose aspirin), dyslipidemia treatment (a statin), smoking cessation, and control of comorbidities such as hypertension and diabetes.<br>Acute coronary syndromes are handled mostly with the antiplatelets and anticoagulants from Heme.<br><br><b>Educational objective:</b> Every patient with stable angina needs risk reduction (antiplatelet therapy, statin, smoking cessation, comorbidity control) as well as antianginals.",
wrong={1:"A long-acting nitrate relieves angina but doesn't prevent MI.",
2:"Ranolazine relieves refractory angina only.",
3:"Amlodipine is an antianginal and antihypertensive, not an antiplatelet.",
4:"Diltiazem relieves angina but doesn't reduce MI risk."},
eli5="The angina pills stop the chest pain. Aspirin keeps clots from forming on his plaques, which is what actually causes heart attacks."),

dict(img=None,
stem="During a pharmacologic stress test, a patient with a fixed 90% stenosis of the left anterior descending artery receives intravenous dipyridamole, a potent arteriolar dilator. His chest pain worsens and the anterior wall becomes ischemic on imaging.{FIG}Which of the following best explains this?",
choices=["Healthy beds dilate and divert flow from the stenotic bed","The stenotic artery goes into spasm","Dipyridamole raises O₂ demand by ↑ contractility","Dipyridamole lowers preload so much that output falls","The drug constricts arterioles beyond the stenosis"], key=0,
exp="Board add-on (in the notes): in stable CAD, the arterioles <b>beyond a fixed stenosis are already maximally dilated</b> to compensate. A strong arteriolar dilator can only dilate the <b>healthy beds</b>, which then \"steal\" flow away from the stenotic territory: <b>coronary steal</b>. That's why nitrates help mainly through <b>venous preload reduction</b> rather than coronary dilation, and why dipyridamole or adenosine is used for stress imaging.<br><br><b>Educational objective:</b> Strong arteriolar dilators cause coronary steal, diverting flow from maximally dilated post-stenotic beds to healthy ones.",
wrong={1:"Dipyridamole doesn't cause spasm.",
2:"Dipyridamole isn't a positive inotrope.",
3:"It acts mostly on arterioles, not venous preload.",
4:"It dilates, not constricts. The post-stenotic arterioles just have no room left to dilate."},
eli5="Behind the blockage the vessels are already wide open. The drug opens all the healthy vessels too, so blood takes the easy route and the starved area gets even less."),

dict(img=None,
stem="A 39-year-old man with vasospastic angina is started on long-acting diltiazem, and his nocturnal episodes stop.{FIG}Which of the following best explains how the calcium channel blocker prevents his attacks?",
choices=["It blocks L-type Ca²⁺ entry into coronary smooth muscle","It releases nitric oxide from the coronary endothelium","It blocks α1 receptors on coronary smooth muscle","It stimulates β2 receptors on coronary arteries","It inhibits phosphodiesterase-5 in coronary arteries"], key=0,
exp="Coronary vasospasm is <b>smooth-muscle contraction</b>, and that contraction depends on Ca²⁺ entering through <b>L-type (voltage-gated) Ca²⁺ channels</b>. CCBs block that entry and relax the artery, preventing spasm. That's why the vasospastic criteria note that <b>CCBs, but not β-blockers, suppress episodes</b>. CCB is the <b>preventive</b> drug (dihydropyridines and diltiazem are common), CCB + nitrate is an effective combination, and sublingual nitroglycerin aborts attacks.<br><br><b>Educational objective:</b> CCBs prevent vasospastic angina by blocking L-type Ca²⁺ entry into coronary smooth muscle.",
wrong={1:"NO release is how nitrates work.",
2:"α1 blockade isn't a CCB action.",
3:"CCBs don't stimulate β2 receptors.",
4:"PDE5 inhibition is sildenafil."},
eli5="Artery muscle needs calcium to squeeze. Diltiazem blocks calcium from getting in, so the artery can't cramp."),

dict(img=None,
stem="A 60-year-old man with stable exertional angina also has moderate persistent asthma and uses inhaled albuterol several times a week. His physician wants a daily preventive antianginal.{FIG}Which of the following is the best choice?",
choices=["Amlodipine","Propranolol","Nadolol","Timolol","Pindolol"], key=0,
exp="β-blockers are the best monotherapy for exertional angina, but <b>non-selective β-blockers</b> (propranolol, nadolol, timolol, pindolol) block <b>β2 on bronchial smooth muscle</b>. That causes bronchospasm and blocks albuterol's effect, so they're \"not for asthmatics\". A <b>calcium channel blocker</b> such as amlodipine lowers afterload and O₂ demand without touching the airways. Board add-on: a cardioselective β1 blocker can be used cautiously in mild disease. Pindolol is also avoided in angina because of intrinsic sympathomimetic activity.<br><br><b>Educational objective:</b> In angina with asthma, avoid non-selective β-blockers and prevent attacks with a calcium channel blocker.",
wrong={1:"Propranolol is non-selective and causes bronchospasm.",
2:"Nadolol is non-selective (β1 + β2).",
3:"Timolol is non-selective, and it can cause bronchospasm even as eye drops.",
4:"Pindolol is non-selective and has ISA, so it's doubly unsuitable."},
eli5="Those β-blockers would also block the airway receptor his inhaler needs. Amlodipine treats the angina without touching his lungs."),
]
