# Ischemic Heart Disease Pharmacology (Scully) — Version 1, 18 items (2 with images): supply vs demand, the anginas, vasospastic case, nitrates
Q = [
dict(img=None,
stem="A pharmacology lecturer explains that nearly every antianginal drug works by lowering myocardial oxygen demand rather than by raising coronary blood supply.{FIG}Which of the following best explains this strategy?",
choices=["Plaque and endothelial dysfunction limit any rise in supply","Coronary arteries contain no smooth muscle to dilate","Raising supply would increase myocardial O₂ demand","The myocardium extracts very little of the O₂ delivered to it","Coronary flow occurs mainly during systole, when drugs act"], key=0,
exp="\"We could increase supply of oxygen, or we could decrease demand — and one tends to be much easier than the other.\" Angina means O₂ supply can't keep up with demand. <b>Supply is hard to raise</b> because it's limited by <b>atherosclerotic plaque and age-related endothelial dysfunction</b>. <b>Demand is easy to lower</b> with drugs: heart rate, contractility, and wall stress from preload and afterload. Board add-on: the myocardium already extracts about 75% of delivered O₂ at rest, so the only way to get more O₂ is more flow. Most left-ventricular perfusion happens in <b>diastole</b>.<br><br><b>Educational objective:</b> Antianginals mostly lower O₂ demand (HR, contractility, preload, afterload) because supply is limited by fixed plaque and endothelial dysfunction.",
wrong={1:"Coronary arteries have smooth muscle. That's how vasospasm happens.",
2:"Raising supply doesn't raise demand. The barrier is that supply is hard to raise.",
3:"The myocardium extracts a <b>high</b> fraction of delivered O₂ (~75%) at rest.",
4:"Left-ventricular coronary flow occurs mainly in <b>diastole</b>."},
eli5="You can't easily widen a clogged pipe, but you can ask the engine to burn less fuel. Most angina drugs make the heart work less."),

dict(img=None,
stem="A 61-year-old man has had predictable chest pressure after climbing two flights of stairs for a year. Over the past 3 weeks the pain now comes after half a flight, occurs several times a day, and lasts up to 20 minutes.{FIG}Which of the following best explains this change?",
choices=["A vulnerable plaque with superimposed thrombus","Coronary smooth-muscle spasm without plaque","Nitrate tolerance from daily nitroglycerin use","Regression of a fixed atherosclerotic plaque","Reduced myocardial O₂ demand during exercise"], key=0,
exp="Slide 7: angina pectoris is <b>progressive</b>.<br>• <b>Stable</b>: fixed atherosclerotic plaque. Pain on exertion, gone with rest.<br>• <b>Unstable</b>: a growing, <b>vulnerable plaque with thrombus</b>. Pain is <b>longer, more frequent, with a lower exertional threshold</b> and a high risk of an acute coronary event.<br>• <b>Vasospastic</b>: smooth-muscle spasm. At rest, early morning, in younger patients.<br>His pattern has changed from stable to unstable. The acute coronary syndromes are treated mainly with the antiplatelets and anticoagulants from Heme and the clinical lectures.<br><br><b>Educational objective:</b> Unstable angina (longer, more frequent, lower threshold) reflects a vulnerable plaque with thrombus and signals a high risk of an acute coronary event.",
wrong={1:"Vasospasm causes rest pain, often early in the morning, in younger patients. It doesn't cause a worsening exertional pattern.",
2:"Nitrate tolerance reduces the drug's effect. It doesn't lower the threshold at which ischemia starts.",
3:"Plaque regression would <b>improve</b> symptoms.",
4:"Demand rises with exercise. The problem is falling supply."},
eli5="His artery plaque has turned unstable and a clot is starting to form on it. That's why the pain now comes sooner, more often and lasts longer, and it's a warning that a heart attack may be near."),

dict(img='Aaprinz', cap='12-lead ECG recorded during an episode of pain',
stem="A 34-year-old man comes to the emergency department after being woken at 5 a.m. by chest pain for the fourth time this month. He is calm, has no exertional symptoms but notices poor exercise tolerance in the mornings, and his ECG between episodes is normal. An ECG captured during an episode is shown; the changes resolved within minutes with sublingual nitroglycerin. Coronary angiography shows no fixed stenosis.{FIG}Which of the following is the most appropriate drug to prevent recurrences?",
choices=["Amlodipine","Metoprolol","Ranolazine","Clopidogrel","Sumatriptan"], key=0,
exp="This is case 1: <b>vasospastic (variant, Prinzmetal) angina</b>, \"not very common — but a board favourite\". A young patient with <b>rest pain at night or early morning</b>, morning exercise intolerance, <b>transient ST elevation only during the episode</b>, a normal ECG between attacks, and no fixed stenosis.<br>• <b>Abort</b>: sublingual nitroglycerin.<br>• <b>Prevent</b>: a <b>calcium channel blocker</b> (dihydropyridine such as amlodipine, or diltiazem). CCB + nitrate is an effective combination.<br>• <b>Avoid β-blockers</b>: unopposed α tone worsens spasm.<br><br><b>Educational objective:</b> Vasospastic angina is aborted with sublingual nitroglycerin and prevented with a calcium channel blocker. β-blockers are contraindicated.",
wrong={1:"β-blockers are <b>contraindicated</b> in vasospastic angina because unopposed α tone worsens spasm.",
2:"Ranolazine is for refractory stable angina.",
3:"An antiplatelet drug is for plaque-related disease. It doesn't prevent spasm.",
4:"Triptans are 5-HT1B/1D agonists that can <b>trigger</b> coronary vasospasm."},
eli5="His coronary artery isn't clogged. It cramps, usually early in the morning. A calcium channel blocker relaxes the artery wall so it stops cramping."),

dict(img=None,
stem="A 36-year-old woman with vasospastic angina is prescribed metoprolol by an urgent-care physician for \"palpitations\". Over the following week, her early-morning chest pain episodes become more frequent and severe.{FIG}Which of the following best explains the worsening?",
choices=["Unopposed α-adrenergic coronary vasoconstriction","β-receptor upregulation causing reflex tachycardia","Increased preload from slower heart rate alone","Direct stimulation of coronary M3 receptors","Coronary steal from arteriolar dilation"], key=0,
exp="β-blockers are used in stable angina but are <b>contraindicated in vasospastic angina</b>. Blocking <b>β2-mediated coronary vasodilation</b> leaves <b>unopposed α (vasoconstrictor) tone</b> on coronary smooth muscle, so spasm gets worse. Dr. Scully: \"This has been contested in the literature more recently, but it's still ingrained in the literature and the recommendations.\" The vasospastic criteria table also notes that CCBs, but not β-blockers, suppress episodes.<br><br><b>Educational objective:</b> β-blockers worsen vasospastic angina by leaving α-mediated coronary vasoconstriction unopposed.",
wrong={1:"Reflex tachycardia comes from vasodilators (nitrates, dihydropyridines), not β-blockers.",
2:"A slower rate can raise end-diastolic volume, but that wouldn't trigger rest spasm.",
3:"β-blockers don't stimulate muscarinic receptors.",
4:"Coronary steal comes from strong arteriolar dilators, not β-blockers."},
eli5="Her coronary arteries have a 'relax' signal (β2) and a 'squeeze' signal (α). Metoprolol muffled the relax signal, so the squeeze won out and the artery cramped more."),

dict(img='Xach', cap='Right coronary angiogram before (left panel) and after (right panel) an intracoronary injection; dashed lines trace the original vessel',
stem="A 41-year-old man with recurrent rest chest pain undergoes coronary angiography with provocative testing. The right panel was recorded after an intracoronary injection of acetylcholine and shows near-total occlusion of the right coronary artery.{FIG}Which receptor mediates the contraction seen in the right panel?",
choices=["M3 receptors on vascular smooth muscle","M3 receptors on endothelial cells","M2 receptors on cardiac myocytes","M1 receptors in the central nervous system","Nicotinic receptors on autonomic ganglia"], key=0,
exp="Transient ischemic ECG changes appear only during an event, so <b>provocative testing</b> (hyperventilation, ergot or acetylcholine) is used to capture spasm on angiography. Dr. Scully's receptor rule: \"<b>M1s in the CNS, M2s in the heart, M3s everywhere else, including smooth muscle.</b>\" Intracoronary ACh acting on <b>M3 receptors of vascular smooth muscle</b> causes contraction and occlusive spasm. Board add-on: in healthy vessels, ACh acts on <b>endothelial M3 → NO → dilation</b>. With endothelial dysfunction, the direct smooth-muscle M3 contraction wins, which is why ACh unmasks spasm-prone arteries.<br><br><b>Educational objective:</b> Acetylcholine provokes coronary spasm through M3 receptors on vascular smooth muscle, which predominate when the endothelium is dysfunctional.",
wrong={1:"Endothelial M3 activation releases NO, which <b>dilates</b> the vessel.",
2:"M2 receptors slow the heart rate. They don't constrict coronary arteries.",
3:"M1 receptors are mainly in the CNS.",
4:"Nicotinic receptors are on ganglia and the neuromuscular junction, not coronary smooth muscle."},
eli5="Acetylcholine normally tells the artery's lining to relax it. In this patient the lining isn't working, so the acetylcholine hits the muscle directly and squeezes the artery shut."),

dict(img=None,
stem="A cardiologist evaluating a 38-year-old woman for suspected vasospastic angina reviews the diagnostic criteria.{FIG}Which of the following findings supports this diagnosis?",
choices=["Episodes can be set off by hyperventilation","Pain reliably appears at a fixed exercise workload","ST changes persist between pain episodes","Episodes are suppressed best by a β-blocker","Pain is relieved by rest after 5–10 minutes"], key=0,
exp="Diagnostic criteria for vasospastic angina (slide 13):<br>• <b>Nitrate-responsive</b> chest pain during a spontaneous episode.<br>• <b>Rest angina</b>, especially night to early morning, with marked diurnal variation in exercise tolerance (worse in the morning).<br>• <b>Hyperventilation can precipitate</b> an episode.<br>• <b>Transient</b> ischemic ECG changes only during an event (ST elevation or depression, new U waves).<br>• <b>CCBs, but not β-blockers</b>, suppress episodes.<br>It may be a diagnosis of exclusion in practice.<br><br><b>Educational objective:</b> Vasospastic angina is nitrate-responsive rest pain (night or early morning), can be triggered by hyperventilation, shows transient ECG changes, and is suppressed by CCBs, not β-blockers.",
wrong={1:"A fixed exertional threshold describes <b>stable</b> angina.",
2:"The ECG changes are <b>transient</b>, present only during episodes.",
3:"β-blockers don't suppress vasospasm and can worsen it.",
4:"Relief with rest after exertion is stable angina."},
eli5="In this condition the coronary artery cramps on its own, often at night or when you breathe too fast. The ECG looks abnormal only during a cramp."),

dict(img=None,
stem="A 58-year-old man with stable exertional angina places a nitroglycerin tablet under his tongue while climbing stairs, and his pain resolves within 3 minutes.{FIG}Which of the following is the principal mechanism of relief?",
choices=["Venodilation lowers preload and wall stress","Epicardial coronary dilation greatly raises supply","Direct negative inotropy lowers contractility","Slowing of the heart rate prolongs diastole","Arteriolar dilation beyond the stenosis restores flow"], key=0,
exp="Organic nitrate → <b>bioactivated by mitochondrial aldehyde dehydrogenase (ALDH2)</b> in neighbouring endothelium → NO diffuses into smooth muscle → <b>soluble guanylyl cyclase → ↑ cGMP</b> → relaxation of <b>venous capacitance vessels</b> → <b>↓ preload → ↓ end-diastolic volume → ↓ wall stress → ↓ O₂ demand</b>. There may be a small rise in supply from dilating epicardial arteries, but that \"isn't the major driving force\". Board add-on: arterioles beyond a fixed stenosis are already maximally dilated.<br><br><b>Educational objective:</b> Nitrates relieve exertional angina mainly through venodilation, which lowers preload, wall stress and O₂ demand.",
wrong={1:"Epicardial dilation adds a little supply but \"isn't the major driving force\".",
2:"Nitrates aren't negatively inotropic. Reflex sympathetic activation raises contractility.",
3:"Nitrates cause <b>reflex tachycardia</b>, not slowing.",
4:"Arterioles beyond a fixed stenosis are already maximally dilated."},
eli5="Nitroglycerin mostly relaxes the veins, so blood pools in the body and less returns to the heart. With less blood to pump, the heart works less and needs less oxygen."),

dict(img=None,
stem="A 55-year-old woman of East Asian descent has stable angina. She reports that sublingual nitroglycerin gives her little relief, although her technique and tablet storage are correct.{FIG}Variation in which enzyme most likely explains her poor response?",
choices=["Mitochondrial aldehyde dehydrogenase (ALDH2)","Cytochrome P450 2D6","N-acetyltransferase 2","Thiopurine methyltransferase","Pseudocholinesterase"], key=0,
exp="Organic nitrates must be <b>bioactivated by mitochondrial aldehyde dehydrogenase (ALDH2)</b> to release NO. <b>ALDH2 polymorphisms are common in patients of East Asian descent</b>. Less bioactivation means nitrates are less vasoactive and less effective (the lecture's pharmacogenetics point). The same variant causes alcohol flushing (board add-on). Nitroprusside releases NO spontaneously, without bioactivation.<br><br><b>Educational objective:</b> ALDH2 polymorphisms (common in East Asian patients) reduce nitrate bioactivation and clinical effect.",
wrong={1:"CYP2D6 variation affects codeine, metoprolol and others, not nitrate activation.",
2:"NAT2 (acetylation) affects isoniazid, procainamide and hydralazine.",
3:"TPMT affects azathioprine and 6-mercaptopurine toxicity.",
4:"Pseudocholinesterase deficiency prolongs succinylcholine paralysis."},
eli5="Nitroglycerin needs an enzyme to switch it on. Many people of East Asian descent have a weaker version of that enzyme, so the drug doesn't switch on as well."),

dict(img=None,
stem="A 66-year-old man with stable angina uses a transdermal nitroglycerin patch, which he changes every morning and wears around the clock. It controlled his symptoms well at first, but after 10 days his exertional angina has returned.{FIG}Which of the following is the most appropriate adjustment?",
choices=["Take the patch off overnight each day","Apply two patches to double the dose","Use continuous IV nitroglycerin instead","Add sildenafil to boost cGMP","Change the patch twice daily without a break"], key=0,
exp="Long-acting nitrates lose effect with continuous use: <b>nitrate tolerance</b>. The fix is a <b>nitrate-free interval, usually overnight</b>, so tolerance can't build up. For a patch, remove it at night (worn ~12–14 h). Dr. Scully links this to the OMK 1 \"<b>Monday morning headache</b>\": munitions workers became tolerant during the work week, lost it over the weekend, and got headaches again on Monday.<br><br><b>Educational objective:</b> Nitrate tolerance develops with continuous exposure. Prevent it with a daily nitrate-free interval, usually overnight.",
wrong={1:"Higher continuous doses still cause tolerance and more headache and hypotension.",
2:"A continuous IV infusion causes tolerance too.",
3:"PDE5 inhibitors with nitrates cause refractory hypotension and are contraindicated.",
4:"Continuous exposure is the cause of tolerance."},
eli5="If the body gets nitrate all day and night, it stops responding. Taking the patch off overnight gives the body a break so the drug works again the next day."),

dict(img=None,
stem="A 60-year-old woman with stable angina takes sublingual nitroglycerin. Within minutes her blood pressure falls from 138/84 to 112/70 mm Hg and her heart rate rises from 74 to 98/min. Her physician plans maintenance therapy with a second drug to blunt this effect.{FIG}Which drug class best complements the nitrate in this way?",
choices=["β-blocker","Dihydropyridine calcium channel blocker","α1-adrenergic agonist","Phosphodiesterase-5 inhibitor","Loop diuretic"], key=0,
exp="Vasodilation → BP falls → stretch receptors sense it → sympathetic outflow → <b>reflex tachycardia</b>, which raises O₂ demand. That's why nitrates are <b>paired with a β-blocker</b>: the reflex runs through sympathetic β1 outflow. Board add-on: each drug cancels the other's unwanted effect. The β-blocker stops the reflex tachycardia, and the nitrate offsets the β-blocker's rise in end-diastolic volume. Both lower O₂ demand.<br><br><b>Educational objective:</b> Nitrates cause baroreflex tachycardia, so they are paired with a β-blocker, which blocks the reflex while the nitrate offsets the β-blocker's rise in preload.",
wrong={1:"A dihydropyridine also vasodilates and can <b>add</b> reflex tachycardia.",
2:"An α1 agonist would raise afterload and O₂ demand.",
3:"A PDE5 inhibitor with a nitrate causes refractory hypotension.",
4:"A diuretic doesn't block the reflex tachycardia."},
eli5="When nitroglycerin drops blood pressure, the body speeds the heart up to compensate, which wastes oxygen. A β-blocker stops that speed-up."),

dict(img=None,
stem="A 63-year-old man with stable angina needs a long-acting oral nitrate for prophylaxis. His physician chooses one specifically because it is not lost to first-pass hepatic metabolism.{FIG}Which drug was chosen?",
choices=["Isosorbide-5-mononitrate","Isosorbide dinitrate","Sublingual nitroglycerin","Sodium nitroprusside","Hydralazine"], key=0,
exp="Nitrate dosage forms:<br>• <b>Sublingual or buccal nitroglycerin</b> (or spray): aborts an acute attack and bypasses first-pass metabolism (board add-on: onset 2–5 min, lasts 15–30 min).<br>• Transdermal nitroglycerin: prophylaxis. Remove overnight.<br>• Isosorbide dinitrate (oral): prophylaxis, but <b>low oral bioavailability</b>.<br>• <b>Isosorbide-5-mononitrate (oral)</b>: long-term prophylaxis and often the drug of choice. The exception: <b>high oral bioavailability</b> with no first-pass loss.<br>Long-acting nitrates are not first-line monotherapy. They are add-ons.<br><br><b>Educational objective:</b> Isosorbide-5-mononitrate is the long-acting oral nitrate with high bioavailability (no first-pass loss).",
wrong={1:"Isosorbide dinitrate has low oral bioavailability because of first-pass metabolism.",
2:"Sublingual nitroglycerin is for aborting attacks, not oral prophylaxis.",
3:"Nitroprusside is an IV infusion for acute settings.",
4:"Hydralazine is an arteriolar dilator, not a nitrate."},
eli5="Most nitrate pills get chewed up by the liver before they work. Isosorbide mononitrate slips past the liver, so a pill works reliably."),

dict(img=None,
stem="A 70-year-old woman with stable angina asks why she must dissolve her nitroglycerin tablet under her tongue rather than swallow it.{FIG}Which of the following is the best explanation?",
choices=["It avoids first-pass hepatic metabolism","It produces a longer duration of action","It reduces the risk of headache","It prevents the development of tolerance","Swallowed nitroglycerin causes ulcers"], key=0,
exp="Nitroglycerin swallowed is mostly destroyed by <b>first-pass hepatic metabolism</b>. Under the tongue (or buccally, or as a spray) it's absorbed straight into the systemic venous circulation, so it works in <b>2–5 minutes</b>. That's why it's the drug to <b>abort an acute attack</b> in both stable and vasospastic angina. The effect is brief (15–30 min, board add-on). It doesn't prevent tolerance or headache.<br><br><b>Educational objective:</b> Sublingual nitroglycerin bypasses first-pass metabolism, giving a rapid onset to abort angina attacks.",
wrong={1:"Sublingual dosing gives a <b>short</b> duration, not a longer one.",
2:"Headache is a vasodilator effect regardless of route.",
3:"Tolerance is prevented by a nitrate-free interval, not by route.",
4:"Swallowed nitroglycerin isn't avoided for ulcers. It's avoided because the liver inactivates it."},
eli5="If she swallows it, the liver destroys most of it before it reaches the heart. Under the tongue, it goes straight into the blood and works in minutes."),

dict(img=None,
stem="A 64-year-old man who uses isosorbide mononitrate for angina asks his primary care physician for sildenafil.{FIG}Which of the following best explains why the combination is dangerous?",
choices=["PDE5 inhibition stops breakdown of nitrate-made cGMP","Sildenafil blocks hepatic nitrate metabolism","Sildenafil activates soluble guanylyl cyclase directly","Both drugs block L-type Ca²⁺ channels","Sildenafil causes reflex bradycardia with nitrates"], key=0,
exp="Nitrates generate NO → soluble guanylyl cyclase → <b>↑ cGMP</b>. <b>PDE5 inhibitors</b> (sildenafil, tadalafil) <b>stop cGMP breakdown</b>. Together they amplify smooth-muscle relaxation → <b>profound, refractory hypotension</b>. Board add-on: avoid nitrates within 24 h of sildenafil (48 h for tadalafil), in right-ventricular infarction, and in preload-dependent states (severe aortic stenosis, HOCM).<br><br><b>Educational objective:</b> Nitrates (↑ cGMP production) plus PDE5 inhibitors (↓ cGMP breakdown) cause refractory hypotension.",
wrong={1:"The interaction is pharmacodynamic (cGMP), not metabolic.",
2:"Sildenafil doesn't activate guanylyl cyclase. It blocks cGMP breakdown.",
3:"Neither drug blocks Ca²⁺ channels.",
4:"Hypotension triggers reflex <b>tachycardia</b>, and the danger is the hypotension itself."},
eli5="The nitrate turns on the 'relax' tap and sildenafil plugs the drain. The relax signal overflows and blood pressure crashes."),

dict(img=None,
stem="During the First World War, munitions workers handling nitroglycerin developed pounding headaches on Monday mornings that faded as the week went on, only to return the following Monday.{FIG}Which of the following best explains this pattern?",
choices=["Tolerance built over the week and reset by Monday","Weekend alcohol use caused Monday hangovers","Nitrate levels peaked on Mondays from new stock","Cyanide accumulated during the working week","Headaches reflected weekend withdrawal hypertension"], key=0,
exp="This is the OMK 1 smooth-muscle story Dr. Scully revisits. Continuous nitrate exposure during the work week produced <b>tolerance</b>, so the vasodilator headaches faded. Over the nitrate-free weekend the tolerance was lost, and re-exposure on <b>Monday</b> brought the headaches back. The clinical lesson: schedule a <b>nitrate-free interval</b> (usually overnight) so tolerance can't build up. Headache is part of the vasodilator trio, along with flushing and hypotension.<br><br><b>Educational objective:</b> Nitrate tolerance builds with continuous exposure and resets after a nitrate-free period, which is the basis of the \"Monday morning headache\" and of nitrate-free dosing intervals.",
wrong={1:"Alcohol doesn't explain a headache that fades through the week of nitrate exposure.",
2:"Exposure was steady across the week. The <b>response</b> changed.",
3:"Cyanide accumulation is a nitroprusside problem.",
4:"Weekend withdrawal can cause rebound vasospasm (board add-on), but the Monday headache is the return of the vasodilator effect after tolerance faded."},
eli5="By midweek the workers' bodies had gotten used to the nitroglycerin, so no headaches. Over the weekend they lost that tolerance, and on Monday the headaches came back."),

dict(img=None,
stem="An investigator notes that intracoronary acetylcholine dilates the coronary arteries of healthy volunteers but causes intense spasm in patients with vasospastic angina.{FIG}Which of the following best explains the difference?",
choices=["Dysfunctional endothelium makes too little NO","Patients with spasm lack smooth-muscle M3 receptors","Acetylcholine is degraded faster in healthy vessels","Healthy vessels contain only nicotinic receptors","Spasm-prone vessels express excess β2 receptors"], key=0,
exp="Acetylcholine has two opposing actions on a coronary artery:<br>• <b>Endothelial M3 → NO → smooth-muscle relaxation</b> (dilation), which dominates in healthy vessels.<br>• <b>Direct smooth-muscle M3 → contraction</b>, which dominates when the <b>endothelium is dysfunctional</b>.<br>That's why acetylcholine provocation unmasks spasm-prone arteries (board add-on, building on the lecture's M3 rule). Age-related endothelial dysfunction is also one reason supply is hard to raise in IHD.<br><br><b>Educational objective:</b> Acetylcholine dilates arteries with healthy endothelium (via NO) but constricts arteries with dysfunctional endothelium (direct smooth-muscle M3).",
wrong={1:"Spasm needs smooth-muscle M3 receptors. Their activation is what causes it.",
2:"Acetylcholinesterase activity doesn't explain the reversal.",
3:"Coronary arteries have muscarinic receptors.",
4:"β2 receptors cause dilation, so excess β2 would oppose spasm."},
eli5="In a healthy artery, acetylcholine tells the lining to make a 'relax' chemical. If the lining is damaged, that message is lost, and acetylcholine squeezes the muscle directly instead."),

dict(img=None,
stem="A 37-year-old woman with known vasospastic angina presents to the emergency department at 4 a.m. with crushing chest pain that started at rest 10 minutes ago. Her ECG shows transient ST elevation in the inferior leads, and her blood pressure is 128/80 mm Hg.{FIG}Which of the following is the most appropriate drug to abort this episode?",
choices=["Sublingual nitroglycerin","Oral amlodipine","Intravenous metoprolol","Oral ranolazine","Intravenous adenosine"], key=0,
exp="To <b>abort an attack</b> of either stable or vasospastic angina, use a <b>short-acting nitrate</b>: <b>sublingual nitroglycerin</b>, which relaxes coronary smooth muscle and bypasses first-pass metabolism. Nitrate-responsiveness is itself a diagnostic criterion. For <b>prevention</b>, use a calcium channel blocker (± long-acting nitrate). Avoid β-blockers.<br><br><b>Educational objective:</b> Sublingual nitroglycerin aborts vasospastic angina attacks. Calcium channel blockers prevent them.",
wrong={1:"Amlodipine is the <b>preventive</b> drug. Oral onset is too slow to abort an attack.",
2:"β-blockers are contraindicated in vasospasm.",
3:"Ranolazine is for refractory stable angina, not acute attacks.",
4:"Adenosine is a PSVT drug and can itself cause chest pain."},
eli5="When the artery is cramping right now, a nitroglycerin tablet under the tongue relaxes it within minutes. The daily calcium blocker is what prevents the next cramp."),

dict(img=None,
stem="In vascular smooth muscle, nitric oxide released from an organic nitrate diffuses into the cell and binds the heme group of an enzyme, producing the second messenger that causes relaxation.{FIG}Which enzyme does nitric oxide activate?",
choices=["Soluble guanylyl cyclase","Adenylyl cyclase","Phospholipase C","Phosphodiesterase-5","Particulate guanylyl cyclase"], key=0,
exp="NO → <b>soluble guanylyl cyclase</b> (a cytosolic heme enzyme) → <b>↑ cGMP</b> → protein kinase G → smooth-muscle relaxation (board add-on: myosin light-chain dephosphorylation) → vasodilation. <b>Natriuretic peptides</b> raise cGMP through a different, membrane-bound <b>particulate</b> guanylyl cyclase. <b>PDE5</b> breaks cGMP down, which is why PDE5 inhibitors plus nitrates cause refractory hypotension.<br><br><b>Educational objective:</b> Nitric oxide activates soluble guanylyl cyclase, raising cGMP and relaxing vascular smooth muscle.",
wrong={1:"Adenylyl cyclase makes cAMP (β-receptor signaling).",
2:"Phospholipase C is the Gq pathway that <b>contracts</b> smooth muscle (α1, M3).",
3:"PDE5 <b>degrades</b> cGMP. Sildenafil blocks it.",
4:"Particulate (membrane) guanylyl cyclase is the natriuretic peptide receptor, not the NO target."},
eli5="NO switches on an enzyme inside the muscle cell that makes cGMP, a 'relax' messenger. The muscle relaxes and the vessel widens."),

dict(img=None,
stem="A 72-year-old man with an acute inferior myocardial infarction and right ventricular involvement has clear lung fields and distended neck veins. Five minutes after sublingual nitroglycerin, his blood pressure falls from 108/70 to 72/40 mm Hg.{FIG}Which of the following best explains the hypotension?",
choices=["Venodilation cut preload to a preload-dependent RV","Nitroglycerin caused acute right ventricular spasm","Nitroglycerin provoked a vasovagal reaction","Coronary steal diverted flow from the infarct","Cyanide accumulated from nitroglycerin metabolism"], key=0,
exp="Board add-on (from the notes): <b>avoid nitrates in right-ventricular infarction</b> and in other <b>preload-dependent states</b> (severe aortic stenosis, hypertrophic obstructive cardiomyopathy). A failing right ventricle relies on high filling pressure to push blood through the lungs to the left heart. Nitrates' main action is <b>venodilation → ↓ preload</b>, which drops RV output, then left-sided filling, and blood pressure collapses. Treatment is IV fluid. The lecture's general contraindication: <b>low blood pressure</b>.<br><br><b>Educational objective:</b> Nitrates are dangerous in preload-dependent states such as RV infarction, where venodilation causes profound hypotension.",
wrong={1:"Nitrates relax smooth muscle. They don't cause ventricular spasm.",
2:"A vasovagal reaction gives bradycardia and pallor, but the classic teaching here is preload dependence.",
3:"Coronary steal is mostly a strong-arteriolar-dilator concept and wouldn't cause sudden hypotension.",
4:"Cyanide comes from nitroprusside, not nitroglycerin."},
eli5="His injured right ventricle needs a lot of blood filling it to pump at all. Nitroglycerin let that blood pool in the veins, so the ventricle had too little to pump and his blood pressure crashed."),
]
