# Dyslipidemia Pharmacology (Scully) — Version 2, 18 items (3 with images): triglycerides (fish oil, fibrates, niacin), PCSK9 inhibitors, the last hypertension case
Q = [
dict(img=None,
stem="A 61-year-old man is seen one year after an ST-elevation myocardial infarction. He takes metoprolol, clopidogrel, simvastatin and fish-oil supplements and follows his diet and exercise plan. Total cholesterol is 198 mg/dL, HDL 32 mg/dL, LDL 106 mg/dL and triglycerides 354 mg/dL.{FIG}Which additional drug class best addresses his high triglycerides and low HDL?",
choices=["Fibrate","Bile acid sequestrant","PCSK9 inhibitor","Cholesterol-absorption inhibitor","Loop diuretic"], key=0,
exp="This is case 2. The leftover problems are <b>high triglycerides and low HDL</b> despite a statin and fish oil. A <b>fibrate</b> (PPAR-α activator: gemfibrozil, fenofibrate) <b>↓ TG and ↑ HDL</b>. Indications: hypertriglyceridemia and dysbetalipoproteinemia. Board add-on: by the lecture's own rule (high-intensity statin after MI), moving him from simvastatin to atorvastatin or rosuvastatin is also reasonable, since LDL 106 is above usual secondary-prevention goals.<br><br><b>Educational objective:</b> For high triglycerides and low HDL despite a statin and fish oil, add a fibrate (PPAR-α agonist).",
wrong={1:"Bile acid sequestrants lower LDL and can <b>raise</b> triglycerides.",
2:"PCSK9 inhibitors lower LDL after statin + ezetimibe failure. They aren't a TG drug.",
3:"Ezetimibe lowers LDL and doesn't affect TG.",
4:"A loop diuretic doesn't treat lipids."},
eli5="His LDL is being handled, but his triglycerides are high and his good HDL is low. A fibrate is the drug that pulls triglycerides down and nudges HDL up."),

dict(img=None,
stem="A 56-year-old woman with dysbetalipoproteinemia is started on fenofibrate, and her triglycerides fall while her HDL rises.{FIG}Fenofibrate acts mainly by activating which of the following?",
choices=["PPAR-α","PPAR-γ","HMG-CoA reductase","Hormone-sensitive lipase","NPC1L1"], key=0,
exp="<b>Fibrates activate PPAR-α</b> (peroxisome proliferator-activated receptor alpha), a nuclear transcription factor. That changes lipid metabolism in several ways → <b>↑ plasma HDL, ↓ plasma TG</b>. Board add-on: PPAR-α raises lipoprotein lipase activity (more VLDL clearance). Fibrates also cause cholesterol gallstones (they inhibit 7α-hydroxylase). <b>PPAR-γ</b> is the thiazolidinedione (pioglitazone) target.<br><br><b>Educational objective:</b> Fibrates are PPAR-α agonists that lower triglycerides and raise HDL.",
wrong={1:"PPAR-γ is activated by thiazolidinediones (insulin sensitizers).",
2:"Statins <b>inhibit</b> HMG-CoA reductase.",
3:"Niacin <b>inhibits</b> hormone-sensitive lipase (board add-on).",
4:"Ezetimibe inhibits NPC1L1."},
eli5="Fenofibrate flips on a master switch in liver and muscle cells (PPAR-α) that speeds up triglyceride clearance and boosts HDL."),

dict(img=None,
stem="A 70-year-old man on warfarin for atrial fibrillation, with a stable INR of 2.5, is started on gemfibrozil for triglycerides of 780 mg/dL. Ten days later he has bleeding gums and an INR of 5.8.{FIG}Which of the following best explains the rise in INR?",
choices=["Gemfibrozil displaces warfarin from plasma proteins","Gemfibrozil induces warfarin metabolism","Gemfibrozil inhibits platelet aggregation","Gemfibrozil causes vitamin K malabsorption","Gemfibrozil blocks hepatic synthesis of fibrinogen"], key=0,
exp="Lecture interaction: fibrates <b>displace warfarin from plasma-protein binding sites</b> → <b>↑ free (active) warfarin</b> → a bigger bleeding risk than expected. Board add-on: gemfibrozil also inhibits CYP2C9, which metabolizes S-warfarin, so the effect is added to. Reduce the warfarin dose and monitor the INR. The other fibrate interaction: with statins → more myopathy and rhabdomyolysis, worse with gemfibrozil than fenofibrate.<br><br><b>Educational objective:</b> Fibrates displace warfarin from plasma proteins (more free warfarin) and raise the bleeding risk.",
wrong={1:"Induction would <b>lower</b> the INR.",
2:"Fibrates don't meaningfully inhibit platelets.",
3:"Vitamin K malabsorption is the bile acid sequestrant mechanism.",
4:"Fibrates don't suppress fibrinogen synthesis enough to cause this."},
eli5="Most warfarin rides on blood proteins, switched off. Gemfibrozil bumps it off those proteins, so more warfarin is active and his blood gets too thin."),

dict(img=None,
stem="A 64-year-old man on high-intensity atorvastatin needs a fibrate for persistent triglycerides above 500 mg/dL. His physician wants to minimize the risk of myopathy from the combination.{FIG}Which fibrate is preferred?",
choices=["Fenofibrate","Gemfibrozil","Clofibrate","Bezafibrate only with a statin holiday","Niacin instead of any fibrate"], key=0,
exp="Lecture: <b>statins + fibrates</b> → more myopathy, myositis and <b>rhabdomyolysis</b>, <b>worse with gemfibrozil than fenofibrate</b>. Watch for muscle pain on the combination. Board add-on: gemfibrozil inhibits statin glucuronidation and raises statin levels, so <b>fenofibrate is the one to pair with a statin</b>. Fibrates are avoided in renal or hepatic failure.<br><br><b>Educational objective:</b> When combining a fibrate with a statin, use fenofibrate. Gemfibrozil carries a higher risk of rhabdomyolysis.",
wrong={1:"Gemfibrozil + statin carries the higher rhabdomyolysis risk.",
2:"Clofibrate is an old fibrate no longer used.",
3:"A statin holiday isn't needed. Fenofibrate is simply the safer partner.",
4:"Niacin also raises myopathy risk with statins and is mainly an HDL drug."},
eli5="Both fibrates lower triglycerides, but gemfibrozil makes statin muscle problems much more likely. Fenofibrate is the safer partner."),

dict(img=None,
stem="A 58-year-old woman with hypertriglyceridemia asks how her fish-oil (EPA and DHA) capsules lower her triglycerides.{FIG}Which mechanism did the lecture describe?",
choices=["↓ Hepatic TG synthesis, ↑ fatty-acid oxidation","Inhibition of intestinal triglyceride absorption","Binding of bile acids in the intestinal lumen","Inhibition of hormone-sensitive lipase in fat","Direct activation of lipoprotein lipase in plasma"], key=0,
exp="Fish oil (EPA, DHA) is the dietary cold-water-fish intervention in pill form. Omega-3 fatty acids <b>alter transcription factors</b> → <b>↓ hepatic triglyceride biosynthesis</b> and <b>↑ hepatic fatty-acid oxidation</b>. Prescription forms now exist (board add-on: icosapent ethyl, purified EPA). For hypertriglyceridemia the lecture's sequence is diet (Mediterranean, cold-water fish) → omega-3 → fibrate.<br><br><b>Educational objective:</b> Omega-3 fatty acids lower triglycerides by altering hepatic transcription: less TG synthesis, more fatty-acid oxidation.",
wrong={1:"Omega-3s don't block intestinal TG absorption.",
2:"Binding bile acids is how cholestyramine works.",
3:"Inhibiting hormone-sensitive lipase is niacin's (board add-on) mechanism.",
4:"Lipoprotein lipase activation is mostly attributed to fibrates (PPAR-α)."},
eli5="Fish oil tells the liver's control switches to make less triglyceride and burn more fat."),

dict(img=None,
stem="A 47-year-old man has an isolated HDL of 28 mg/dL with normal LDL and triglycerides. He asks which drug raises HDL most.{FIG}Which drug did the lecture describe as very effective at raising HDL?",
choices=["Niacin","Fenofibrate","Ezetimibe","Atorvastatin","Colesevelam"], key=0,
exp="Slide 6: for <b>low HDL</b>, <b>niacin is very effective at raising HDL</b>, and fibrates give a small rise. But <b>treating isolated low HDL is conflicting in the literature</b>, and the HDL : total-cholesterol ratio is gaining importance. Board add-on: niacin inhibits lipolysis in adipose tissue (hormone-sensitive lipase) and ↓ hepatic VLDL → ↓ TG and LDL, ↑↑ HDL. Adverse effects: flushing and pruritus, hyperglycemia, hyperuricemia/gout, hepatotoxicity.<br><br><b>Educational objective:</b> Niacin is the most effective HDL-raising drug, though treating isolated low HDL is contested.",
wrong={1:"Fibrates raise HDL only modestly. Their main effect is lowering TG.",
2:"Ezetimibe lowers LDL with little HDL effect.",
3:"Statins raise HDL only slightly.",
4:"Bile acid sequestrants lower LDL and can raise TG."},
eli5="Niacin is the champion at raising 'good' HDL cholesterol, though doctors debate whether raising it alone helps."),

dict(img='Aagout', cap='Photograph of the feet',
stem="A 62-year-old man with low HDL and hypertriglyceridemia began a lipid-lowering drug 8 months ago. He has had two attacks of a hot, swollen big toe and now has the findings shown. His serum uric acid is 10.2 mg/dL. He also reports episodes of facial flushing after doses, and his fasting glucose has risen.{FIG}Which drug is he most likely taking?",
choices=["Niacin","Fenofibrate","Ezetimibe","Rosuvastatin","Evolocumab"], key=0,
exp="The photo shows <b>gouty tophi</b> and inflammation, with hyperuricemia. Together with <b>flushing</b> and <b>rising glucose</b>, that's the board add-on adverse-effect profile of <b>niacin</b>: flushing and pruritus (prostaglandin-mediated), <b>hyperglycemia</b>, <b>hyperuricemia/gout</b> (it competes with urate for renal excretion), and hepatotoxicity. In the lecture niacin is the best HDL raiser. Board add-on: fenofibrate actually lowers uric acid slightly.<br><br><b>Educational objective:</b> Niacin causes flushing, hyperglycemia and hyperuricemia (gout).",
wrong={1:"Fenofibrate tends to <b>lower</b> uric acid and doesn't cause flushing.",
2:"Ezetimibe has \"few if any\" adverse effects.",
3:"Statins cause myopathy, not gout and flushing.",
4:"PCSK9 antibodies mainly cause injection-site reactions."},
eli5="Niacin can raise uric acid (gout), blood sugar, and cause hot flushing. He has all three."),

dict(img=None,
stem="A 51-year-old woman starting extended-release niacin for low HDL is warned about intense facial warmth, redness and itching after doses.{FIG}Which pretreatment reduces this effect, and why?",
choices=["Aspirin, since prostaglandins mediate it","Diphenhydramine, because it is histamine-mediated","Propranolol, because it is adrenergic","Ondansetron, because it is serotonin-mediated","Atropine, because it is cholinergic"], key=0,
exp="Board add-on: niacin flushing and pruritus come from <b>prostaglandins</b> (PGD2 and PGE2) released in the skin. <b>Taking aspirin (an NSAID) about 30 minutes before</b> the dose blunts prostaglandin synthesis and the flush. Taking niacin with food, at bedtime, and titrating slowly also help. Tolerance to flushing develops over weeks. Other niacin effects: hyperglycemia, hyperuricemia, hepatotoxicity. In the lecture niacin is the best HDL raiser.<br><br><b>Educational objective:</b> Niacin flushing is prostaglandin-mediated and is reduced by aspirin pretreatment.",
wrong={1:"Niacin flushing isn't mainly histamine-mediated.",
2:"It isn't an adrenergic flush, and β-blockers don't help.",
3:"Serotonin isn't the mediator.",
4:"It isn't cholinergic, and atropine wouldn't help."},
eli5="Niacin makes the skin release prostaglandins, which widen the blood vessels and cause flushing. Aspirin blocks prostaglandins, so taking it first softens the flush."),

dict(img=None,
stem="A researcher studies hepatocytes from a person with very low LDL and no cardiovascular disease. A circulating protein that normally binds the LDL receptor and routes it to the lysosome is nonfunctional.{FIG}Which of the following best describes this protein's normal role?",
choices=["It targets LDL receptors for degradation","It makes LDL receptors recycle faster","It is the rate-limiting enzyme of cholesterol synthesis","It transports dietary cholesterol across enterocytes","It hydrolyzes triglycerides in circulating VLDL"], key=0,
exp="Normally <b>PCSK9 binds the LDL receptor</b> → the receptor is <b>degraded instead of recycled</b> → fewer receptors → more serum LDL. <b>People with loss-of-function PCSK9 mutations</b> degrade fewer LDL receptors and have <b>lower LDL and less cardiovascular disease</b>, the genetic observation that led to the drugs. A PCSK9 inhibitor keeps the LDL receptor on the hepatocyte membrane, so more LDL is cleared.<br><br><b>Educational objective:</b> PCSK9 targets LDL receptors for degradation. Loss-of-function mutations (and PCSK9 inhibitors) preserve receptors and lower LDL.",
wrong={1:"PCSK9 <b>prevents</b> recycling, so it reduces receptor numbers.",
2:"The rate-limiting enzyme is HMG-CoA reductase (the statin target).",
3:"NPC1L1 transports dietary cholesterol (the ezetimibe target).",
4:"Lipoprotein lipase hydrolyzes VLDL triglycerides."},
eli5="PCSK9 tags the liver's cholesterol 'grabbers' for the trash. People born with broken PCSK9 keep more grabbers, so their LDL stays low."),

dict(img=None,
stem="A 60-year-old man with prior myocardial infarction remains above his LDL goal despite lifestyle changes, maximal atorvastatin and ezetimibe on a fasting lipid panel.{FIG}Which of the following is the most appropriate next drug?",
choices=["Evolocumab","Gemfibrozil","Niacin","Fish-oil capsules","Cholestyramine"], key=0,
exp="This is case 3. LDL goal still not met on <b>maximal statin + ezetimibe</b> → a <b>PCSK9 inhibitor</b>. Options: monoclonal antibodies (board add-on: evolocumab, alirocumab; injected; mainly injection-site reactions), <b>inclisiran</b> (an siRNA that reduces PCSK9 production), and a newly available <b>oral</b> PCSK9 inhibitor (GI upset). All are \"very, very effective\" at lowering LDL. Costs are falling, but patients normally have to fail first-line therapy first.<br><br><b>Educational objective:</b> When LDL stays above goal on maximal statin + ezetimibe, add a PCSK9 inhibitor.",
wrong={1:"Gemfibrozil targets triglycerides and raises myopathy risk with a statin.",
2:"Niacin mainly raises HDL and adds adverse effects.",
3:"Fish oil lowers triglycerides, not LDL.",
4:"A bile acid sequestrant lowers LDL only modestly, with GI effects. PCSK9 inhibitors are the next step in the lecture."},
eli5="He's on the strongest statin plus ezetimibe and still too high. A PCSK9 inhibitor saves the liver's LDL grabbers from destruction, so LDL drops a lot."),

dict(img=None,
stem="A 66-year-old woman needs additional LDL lowering. She prefers an injection given only twice a year after loading. Her physician explains that this drug works differently from the PCSK9 monoclonal antibodies.{FIG}How does this drug lower LDL?",
choices=["An siRNA that cuts hepatic PCSK9 production","An antibody that binds circulating PCSK9","A small molecule that blocks HMG-CoA reductase","An antisense drug that blocks apoB-100 synthesis","A resin that binds bile acids in the gut"], key=0,
exp="<b>Inclisiran</b> is a <b>small interfering RNA (siRNA)</b> that <b>decreases production of PCSK9</b> in the liver. Board add-on: after loading it is dosed only twice a year. The <b>monoclonal antibodies</b> (evolocumab, alirocumab) <b>bind free PCSK9</b> so it can't reach the LDL receptor, with mainly injection-site reactions. A new <b>oral</b> PCSK9 inhibitor causes GI upset. Either way, more LDL receptors survive and more LDL is cleared.<br><br><b>Educational objective:</b> Inclisiran (siRNA) reduces PCSK9 synthesis. The PCSK9 monoclonal antibodies bind circulating PCSK9.",
wrong={1:"Binding circulating PCSK9 is how the monoclonal antibodies work.",
2:"HMG-CoA reductase is the statin target.",
3:"Blocking apoB-100 synthesis describes mipomersen, an older antisense drug.",
4:"Binding bile acids is what sequestrants do."},
eli5="Instead of mopping up PCSK9 after it's made, inclisiran tells the liver to stop making much PCSK9 in the first place."),

dict(img=None,
stem="A 59-year-old man begins evolocumab injections every 2 weeks. At his follow-up visit his LDL has fallen by 60%.{FIG}Which adverse effect did the lecture identify as the main one for the PCSK9 monoclonal antibodies?",
choices=["Injection-site reactions","Rhabdomyolysis","Flushing","Vitamin K deficiency","Hyperuricemia"], key=0,
exp="PCSK9 monoclonal antibodies bind free PCSK9 so it can't interact with the LDL receptor. They are \"very, very effective\", and their main adverse effect is <b>injection-site reactions</b> (board add-on: also myalgia and nasopharyngitis). The new oral PCSK9 inhibitor's main adverse effect is GI upset. They're normally used after first-line therapy fails, though falling costs are reducing barriers.<br><br><b>Educational objective:</b> PCSK9 monoclonal antibodies are well tolerated. Their main adverse effect is injection-site reactions.",
wrong={1:"Rhabdomyolysis is the statin (± fibrate) concern.",
2:"Flushing is niacin.",
3:"Vitamin K deficiency comes from bile acid sequestrants.",
4:"Hyperuricemia is niacin."},
eli5="The PCSK9 shots are very well tolerated. The usual complaint is a sore or red spot where the needle went in."),

dict(img=None,
stem="A 56-year-old man at a wellness visit has had hypertension for 5 years but stopped his medication 2 years ago \"because he felt fine\". His blood pressure is elevated at two more visits over 2 weeks. He has had two calcium oxalate kidney stones.{FIG}Which antihypertensive class would also help prevent his kidney stones?",
choices=["Thiazide diuretic","Loop diuretic","Dihydropyridine calcium channel blocker","ACE inhibitor","Carbonic anhydrase inhibitor"], key=0,
exp="This is the last hypertension case, revisited at the end of the lipid lecture. Start <b>combination therapy</b> from the three first-line classes: a thiazide, a CCB and a RAAS drug (ACEi or ARB). For a history of kidney stones, <b>a thiazide does both jobs</b>: it <b>↓ urinary Ca²⁺ excretion</b>. With a diuretic, monitor for <b>hypokalemia</b> (most common and most problematic) and hyponatremia.<br><br><b>Educational objective:</b> Thiazides lower urinary calcium, so they treat hypertension and help prevent calcium kidney stones.",
wrong={1:"Loops <b>increase</b> urinary calcium (\"loops lose calcium\").",
2:"CCBs lower BP but don't affect urinary calcium.",
3:"ACE inhibitors don't reduce urinary calcium.",
4:"Carbonic anhydrase inhibitors alkalinize the urine and can <b>promote</b> calcium phosphate stones."},
eli5="Thiazides make the kidney hold onto calcium instead of sending it into the urine, so there's less calcium to form stones, and they lower blood pressure too."),

dict(img=None,
stem="A student asks why hydrochlorothiazide, which blocks a Na⁺–Cl⁻ cotransporter on the luminal side of the distal convoluted tubule, increases calcium reabsorption there.{FIG}Which of the following best explains this effect?",
choices=["Less cell Na⁺ drives basolateral Na⁺/Ca²⁺ exchange","The drug directly opens apical Ca²⁺ channels","It stimulates parathyroid hormone release","It raises the lumen-positive potential in the loop","It blocks Ca²⁺ secretion through ROMK"], key=0,
exp="Look at the <b>basolateral membrane</b>. Less Na⁺ enters through NCC, and the Na⁺/K⁺-ATPase keeps intracellular Na⁺ low. That <b>steeper Na⁺ gradient drives the basolateral Na⁺/Ca²⁺ exchanger</b> to push Ca²⁺ out of the cell, which pulls more Ca²⁺ in from the lumen. Urinary Ca²⁺ falls, which helps with kidney stones and osteoporosis. Recording slip: the recording said the DCT handles \"about 25 to 30%\" of filtered Na⁺. That figure belongs to the thick ascending limb. The DCT reabsorbs about 5–10%, which is why thiazides are milder diuretics.<br><br><b>Educational objective:</b> Thiazides increase distal Ca²⁺ reabsorption because lower intracellular Na⁺ drives the basolateral Na⁺/Ca²⁺ exchanger.",
wrong={1:"The apical Ca²⁺ channel (TRPV5) isn't directly opened by the drug.",
2:"Thiazides don't stimulate PTH release.",
3:"The lumen-positive potential is a thick-ascending-limb mechanism, which loops <b>abolish</b>.",
4:"ROMK is a K⁺ channel and doesn't carry Ca²⁺."},
eli5="With less sodium inside the cell, the cell's sodium-for-calcium swap pump works harder, pushing calcium back into the blood. Less calcium ends up in the urine."),

dict(img='Lhypok', cap='12-lead ECG with lead II rhythm strip',
stem="Six weeks after starting hydrochlorothiazide, the 56-year-old man reports muscle weakness and cramps. His ECG is shown.{FIG}Which add-on drug would correct this problem by directly blocking epithelial Na⁺ channels in the collecting duct?",
choices=["Amiloride","Spironolactone","Furosemide","Acetazolamide","Lisinopril"], key=0,
exp="The ECG shows <b>flattened T waves with prominent U waves</b>, which means <b>hypokalemia</b>, the most common and most problematic diuretic adverse effect. Mechanism: the Na⁺ that escapes NCC reaches the collecting duct, where <b>ENaC</b> reabsorbs Na⁺ alone (not electroneutral), so <b>K⁺ is secreted through ROMK</b>. The <b>K⁺-sparing</b> fix:<br>• <b>ENaC blockers — amiloride, triamterene</b>: competitively block ENaC on principal cells, so no driving force pushes K⁺ out.<br>• MR antagonists — spironolactone, eplerenone: block aldosterone's receptor, so less ENaC is made (indirect).<br><br><b>Educational objective:</b> Thiazide hypokalemia (ENaC → ROMK) is corrected by K⁺-sparing diuretics. Amiloride and triamterene block ENaC directly.",
wrong={1:"Spironolactone spares K⁺ <b>indirectly</b>, by blocking the aldosterone receptor so less ENaC is made.",
2:"Furosemide would worsen hypokalemia.",
3:"Acetazolamide also wastes K⁺.",
4:"An ACE inhibitor raises K⁺ indirectly (less aldosterone), not by blocking ENaC."},
eli5="Extra sodium reaching the end of the kidney gets swapped for potassium, which is lost. Amiloride blocks that sodium door, so the swap stops and potassium stays."),

dict(img=None,
stem="A 66-year-old woman with hypertension also has atrial fibrillation with a resting ventricular rate of 112/min. Her physician wants a single agent for both conditions.{FIG}Which drug is the best choice?",
choices=["Diltiazem","Amlodipine","Hydrochlorothiazide","Lisinopril","Nifedipine"], key=0,
exp="Last hypertension case: \"Also has AF?\" → <b>diltiazem</b>, a CCB that <b>lowers BP</b> and <b>slows AV-node conduction</b> (rate control). Dihydropyridines (\"-dipine\") act selectively on blood vessels. Non-dihydropyridines act on nodal tissue. Diltiazem acts on both, \"bridging the gap\" to verapamil. Reflex tachycardia is most obvious with the dihydropyridines (highest with nifedipine). Peripheral edema comes from arteriolar dilation raising transcapillary hydrostatic pressure.<br><br><b>Educational objective:</b> Diltiazem treats both hypertension and rate control of AF.",
wrong={1:"Amlodipine lowers BP but doesn't slow AV conduction.",
2:"A thiazide doesn't control the ventricular rate.",
3:"An ACE inhibitor doesn't slow the AV node.",
4:"Nifedipine can cause reflex tachycardia, which would worsen the rate."},
eli5="Diltiazem relaxes the blood vessels and slows the heart's gatekeeper, so one pill handles both her blood pressure and her fast heart rhythm."),

dict(img=None,
stem="A 48-year-old woman has hypertension resistant to three drugs, a serum potassium of 3.1 mEq/L and metabolic alkalosis. Her plasma aldosterone is high with suppressed renin, and imaging shows bilateral adrenal hyperplasia.{FIG}Which drug is the most appropriate monotherapy for her hypertension?",
choices=["Spironolactone","Hydrochlorothiazide","Furosemide","Amlodipine","Hydralazine"], key=0,
exp="High aldosterone with suppressed renin, hypokalemia and metabolic alkalosis means <b>primary hyperaldosteronism</b>. With bilateral hyperplasia (not a resectable adenoma) it is treated medically. Lecture: <b>MR antagonists (spironolactone, eplerenone)</b> block aldosterone at its receptor (the mineralocorticoid receptor <i>is</i> the aldosterone receptor), so less ENaC is made. They are <b>monotherapy for hypertension in primary hyperaldosteronism</b>. Adverse effects: <b>hyperkalemia</b>, <b>hyperchloremic metabolic acidosis</b>, and (spironolactone, non-selective) androgen-receptor block → <b>gynecomastia</b>, impotence, abnormal menses. Eplerenone is the selective alternative.<br><br><b>Educational objective:</b> MR antagonists (spironolactone, eplerenone) are monotherapy for hypertension due to primary hyperaldosteronism.",
wrong={1:"A thiazide would worsen her hypokalemia and alkalosis.",
2:"A loop diuretic would worsen her hypokalemia and alkalosis.",
3:"Amlodipine lowers BP but doesn't treat the aldosterone excess or the hypokalemia.",
4:"Hydralazine causes reflex tachycardia and fluid retention, and doesn't address the cause."},
eli5="Her adrenal glands make too much aldosterone, which holds salt and dumps potassium. Spironolactone blocks aldosterone's receptor, fixing the blood pressure and the potassium together."),

dict(img='Lhighk', cap='12-lead ECG',
stem="A 74-year-old man with hypertension and chronic kidney disease was taking lisinopril. A new physician, unaware of this, added losartan 3 weeks ago. He now has weakness and the ECG shown; his serum creatinine has risen from 1.6 to 2.4 mg/dL.{FIG}Which of the following best explains his presentation?",
choices=["Dual RAAS blockade","Losartan-induced bradykinin accumulation","Rebound hypertension from switching agents","Thiazide-like K⁺ wasting from losartan","Angioedema from the ACE inhibitor"], key=0,
exp="The ECG shows <b>severe hyperkalemia</b>: wide QRS complexes merging with tall T waves toward a sine-wave pattern. <b>Never co-administer two RAAS drugs</b>. Dual blockade increases <b>renal impairment, hyperkalemia and hypotension</b>. ACE inhibitors ↓ angiotensin II and aldosterone (and let bradykinin build up: cough, angioedema). ARBs block AT1 further down and spare bradykinin. Less aldosterone means less ENaC and less K⁺ secretion, especially with CKD. ACEi, ARBs and aliskiren are also teratogenic.<br><br><b>Educational objective:</b> Combining two RAAS drugs (ACEi + ARB) causes hyperkalemia, kidney injury and hypotension and is contraindicated.",
wrong={1:"ARBs <b>don't</b> cause bradykinin accumulation. ACE inhibitors do, and bradykinin wouldn't cause hyperkalemia.",
2:"Rebound hypertension doesn't cause hyperkalemia or a sine-wave ECG.",
3:"Losartan <b>retains</b> K⁺. It doesn't waste it.",
4:"Angioedema causes swelling of the lips and airway, not hyperkalemia."},
eli5="He's taking two drugs that both turn down aldosterone, the hormone that tells the kidney to dump potassium. Together they let potassium climb to a dangerous level and strained his kidneys."),
]
