# Dyslipidemia Pharmacology (Scully) — Version 1, 18 items (2 with images): secondary causes, deciding to treat, statins, ezetimibe, bile acid sequestrants
Q = [
dict(img='Aaxanth', cap='Photograph of the eyelids',
stem="A 52-year-old woman has the eyelid lesions shown. Her LDL cholesterol is 214 mg/dL and triglycerides are normal. She also reports fatigue, constipation, cold intolerance and a 5-kg weight gain over the past year; her reflexes relax slowly.{FIG}Which of the following should be checked before starting a statin?",
choices=["Thyroid-stimulating hormone","Lipoprotein(a)","Serum creatine kinase","Hemoglobin A1c","Serum uric acid"], key=0,
exp="The yellow plaques are <b>xanthelasma</b>, a sign of hypercholesterolemia. Lecture slide 4: <b>many dyslipidemias are secondary</b> and resolve when the underlying condition is treated. A full work-up may avoid lipid drugs altogether. Her fatigue, cold intolerance, weight gain, constipation and slow-relaxing reflexes suggest <b>hypothyroidism</b>, a classic secondary cause of <b>raised cholesterol</b> (fewer hepatic LDL receptors). Check <b>TSH</b>. Other cholesterol-raising causes: nephrotic syndrome, cholestasis, anorexia nervosa, corticosteroids, protease inhibitors. Board add-on: untreated hypothyroidism also raises the risk of statin myopathy.<br><br><b>Educational objective:</b> Look for secondary causes of dyslipidemia (here hypothyroidism) before starting lipid drugs. Treating the cause may correct the lipids.",
wrong={1:"Lipoprotein(a) refines risk but doesn't address an obvious, treatable secondary cause.",
2:"A baseline CK isn't the priority. The clinical picture points to the thyroid.",
3:"Diabetes raises <b>triglycerides</b> more than LDL, and her symptoms suggest hypothyroidism.",
4:"Uric acid isn't relevant to her LDL or her symptoms."},
eli5="A slow thyroid makes the liver clear cholesterol poorly. Fix the thyroid first and her cholesterol may come down without a statin."),

dict(img=None,
stem="A 49-year-old man has a triglyceride level of 410 mg/dL. He has hypertension treated with two drugs. A review of his medication list is planned before adding a lipid-lowering drug.{FIG}Which pair of antihypertensive classes is listed in the lecture as a secondary cause of hypertriglyceridemia?",
choices=["β-blockers and diuretics","ACE inhibitors and angiotensin receptor blockers","Calcium channel blockers and α1-blockers","ARBs and calcium channel blockers","α1-blockers and ACE inhibitors"], key=0,
exp="Slide 4 lists secondary causes that <b>raise triglycerides</b>: diabetes mellitus, chronic renal failure, hypothyroidism, glycogen storage disease, stress or sepsis, <b>alcohol excess</b>, lipodystrophy, pregnancy, oral estrogen, glucocorticoids, protease inhibitors, acute hepatitis, SLE, and the antihypertensives <b>β-blockers and diuretics</b>. Board add-on: thiazides cause \"hyper-GLUC\" (glycemia, lipidemia, uricemia, calcemia). ACE inhibitors, ARBs and CCBs are lipid-neutral, and α1-blockers modestly improve lipids.<br><br><b>Educational objective:</b> β-blockers and thiazide or loop diuretics are drug causes of secondary hypertriglyceridemia.",
wrong={1:"ACE inhibitors and ARBs are lipid-neutral.",
2:"CCBs are lipid-neutral, and α1-blockers slightly <b>improve</b> lipids.",
3:"Both classes are lipid-neutral.",
4:"Neither raises triglycerides."},
eli5="Some blood pressure pills, β-blockers and water pills, nudge triglycerides up. Checking his med list may reveal part of the cause."),

dict(img=None,
stem="A 46-year-old man has hypertriglyceridemia (520 mg/dL). He drinks 6–8 beers a day and has fatty liver on ultrasound; his glucose and thyroid function are normal.{FIG}Which of the following is the most appropriate first step?",
choices=["Cut alcohol, then recheck lipids","Start fenofibrate at once","Start a high-intensity statin at once","Begin a PCSK9 inhibitor","Prescribe a bile acid sequestrant"], key=0,
exp="<b>Alcohol excess</b> is a classic secondary cause of hypertriglyceridemia. The lecture: many dyslipidemias are <b>secondary and resolve when the underlying condition is treated</b>, so a full work-up and treatment of the cause may avoid lipid drugs. <b>Diet</b> (Mediterranean, cold-water fish) and lifestyle come first for triglycerides, then omega-3 fatty acids or a fibrate if needed. Board add-on: very high triglycerides (≥ 500–1,000 mg/dL) raise the risk of pancreatitis, so treat promptly if they don't fall.<br><br><b>Educational objective:</b> Treat secondary causes of hypertriglyceridemia (such as alcohol) first. The lipids may normalize without drugs.",
wrong={1:"A fibrate may be needed later, but the main driver here is alcohol.",
2:"Statins target LDL. His problem is triglycerides from alcohol.",
3:"PCSK9 inhibitors lower LDL after first-line failure. They aren't a TG drug.",
4:"Bile acid sequestrants can <b>raise</b> triglycerides."},
eli5="His drinking is pushing his triglycerides up. Cutting back on alcohol may fix the numbers without any new medicine."),

dict(img=None,
stem="A 61-year-old man with an LDL cholesterol of 162 mg/dL is reluctant to start a statin. He is a non-smoker with well-controlled blood pressure, and his values sit near the treatment thresholds.{FIG}According to the lecture, which factor should most strongly guide the decision to start drug therapy?",
choices=["His calculated cardiovascular risk score","His LDL value on a single fasting test","Whether he has xanthelasma on examination","His HDL to LDL ratio alone","His preference for one dose a day"], key=0,
exp="Slide 5: the decision to treat depends largely on the patient's <b>calculated cardiovascular risk score</b> (see the hypertension lecture; the inputs are evolving). It matters most <b>when lipid values sit near the decision thresholds</b>. <b>Diet can lower total cholesterol by ~25%</b>, depending on adherence and the cause, but lifestyle isn't enough for everyone, so drugs are widely used. Classes: synthesis inhibitors (statins), fibrates, niacin, bile acid sequestrants, absorption inhibitors (ezetimibe), PCSK9 inhibitors.<br><br><b>Educational objective:</b> Whether to start lipid-lowering drugs is decided mainly by the patient's calculated cardiovascular risk, especially near thresholds.",
wrong={1:"A single value near the threshold is exactly when the overall risk score matters most.",
2:"Xanthelasma signals dyslipidemia but doesn't set the treatment threshold.",
3:"The lecture mentions the HDL to total-cholesterol ratio gaining importance, but the overall risk score drives the decision.",
4:"Dosing convenience doesn't decide <b>whether</b> to treat."},
eli5="Whether he needs a statin depends on his overall chance of a heart attack or stroke, calculated from many factors, not on one cholesterol number."),

dict(img=None,
stem="A 55-year-old man with type 2 diabetes and hypertension (on metformin and losartan) still has an elevated LDL after a year of diet and exercise. He is started on atorvastatin, and his LDL falls by 45%.{FIG}Which of the following best explains how the drug lowered his serum LDL?",
choices=["↓ Hepatocyte cholesterol → more LDL receptors made","Direct binding and destruction of LDL in the plasma","Blocking dietary cholesterol uptake in the gut","Binding bile acids so cholesterol is excreted","Activation of PPAR-α in hepatocytes"], key=0,
exp="This is case 1 (GM). A <b>statin inhibits HMG-CoA reductase</b>, the rate-limiting step of cholesterol synthesis → <b>↓ hepatocyte cholesterol</b> → signalling cascade (<b>SREBP</b>) → <b>↑ LDL-receptor expression</b> on hepatocytes → LDL is pulled out of the serum to replace intracellular stores. Indications: hypercholesterolemia and mixed hyperlipidemias. They also lower TG and raise HDL a little, and are prescribed broadly in practice.<br><br><b>Educational objective:</b> Statins inhibit HMG-CoA reductase. The drop in hepatocyte cholesterol up-regulates LDL receptors (via SREBP), which clear LDL from the blood.",
wrong={1:"Statins don't act on LDL particles in plasma.",
2:"Blocking intestinal cholesterol uptake (NPC1L1) is ezetimibe.",
3:"Binding bile acids is the bile acid sequestrant mechanism.",
4:"PPAR-α activation is the fibrate mechanism."},
eli5="The statin stops the liver from making its own cholesterol. The hungry liver then puts out more 'grabbers' (LDL receptors) and pulls cholesterol out of the blood."),

dict(img=None,
stem="A 63-year-old man with hypercholesterolemia is being treated for a chronic infection with a long course of clarithromycin. He needs a statin started now.{FIG}Which statin is least likely to interact with clarithromycin?",
choices=["Pravastatin","Simvastatin","Lovastatin","Atorvastatin","Fluvastatin"], key=0,
exp="Not all statins are the same. Lecture metabolism table:<br>• <b>CYP3A4</b>: lovastatin, simvastatin, atorvastatin.<br>• Other CYP (2C9): fluvastatin, pitavastatin.<br>• <b>Non-CYP</b>: <b>pravastatin</b> and <b>rosuvastatin</b>, the \"special\" statins with <b>fewer drug–drug interactions</b>.<br>Clarithromycin is a strong CYP3A4 inhibitor (board add-on), so it would raise lovastatin, simvastatin or atorvastatin levels and the risk of myopathy and rhabdomyolysis.<br><br><b>Educational objective:</b> Pravastatin and rosuvastatin aren't CYP-metabolized, so they avoid interactions with CYP3A4 inhibitors such as clarithromycin.",
wrong={1:"Simvastatin is a CYP3A4 substrate, the classic interaction.",
2:"Lovastatin is a CYP3A4 substrate.",
3:"Atorvastatin is a CYP3A4 substrate.",
4:"Fluvastatin uses CYP2C9. Pravastatin avoids CYP metabolism altogether."},
eli5="Clarithromycin jams the liver enzyme that clears most statins, so those statins build up. Pravastatin doesn't use that enzyme, so it's the safe pick."),

dict(img=None,
stem="A 59-year-old man is discharged 3 days after an ST-elevation myocardial infarction. His LDL is 128 mg/dL.{FIG}Which statin is most appropriate for secondary prevention?",
choices=["Rosuvastatin","Pravastatin","Fluvastatin","Lovastatin","Simvastatin"], key=0,
exp="<b>The two high-intensity statins are atorvastatin and rosuvastatin</b>. They are given <b>after an MI for secondary prevention</b> and to patients at high cardiovascular risk. Board add-on: intensity depends on dose, and potency follows \"Flo Loves Prague Since A Tour of Russia\" (fluva < lova < prava < simva < atorva < rosuva).<br><br><b>Educational objective:</b> After an MI, use a high-intensity statin: atorvastatin or rosuvastatin.",
wrong={1:"Pravastatin is low to moderate intensity.",
2:"Fluvastatin is the least potent statin.",
3:"Lovastatin is low to moderate intensity.",
4:"Simvastatin is moderate intensity."},
eli5="After a heart attack he needs the strongest cholesterol drugs, and the two strongest statins are atorvastatin and rosuvastatin."),

dict(img=None,
stem="A 68-year-old woman taking simvastatin 40 mg daily is prescribed clarithromycin for pneumonia. Five days later she has severe aching of her thighs and shoulders, weakness, and tea-colored urine.{FIG}Which of the following best explains her presentation?",
choices=["CYP3A4 inhibition raised simvastatin levels","Clarithromycin itself causes inflammatory myositis","Pneumonia-induced hypokalemic paralysis","Statin-induced hypothyroidism","Simvastatin displaced clarithromycin from albumin"], key=0,
exp="Statins are generally well tolerated, but the classic worry is <b>myopathy → rhabdomyolysis</b>. It happens less often than first thought, but <b>severe muscle pain with tea-coloured urine means work it up</b> (CK, urinalysis, kidney function). Board add-on: myopathy risk rises with <b>CYP3A4 inhibitors</b> (macrolides, azole antifungals, protease inhibitors, grapefruit juice), fibrates (especially gemfibrozil) and niacin. Clarithromycin raised her simvastatin (a CYP3A4 substrate) level.<br><br><b>Educational objective:</b> CYP3A4 inhibitors raise levels of CYP3A4-metabolized statins (simvastatin, lovastatin, atorvastatin) and can cause rhabdomyolysis.",
wrong={1:"Macrolides don't cause inflammatory myositis. The problem is the interaction.",
2:"Hypokalemic paralysis doesn't cause muscle pain with tea-coloured urine.",
3:"Statins don't cause hypothyroidism (though hypothyroidism raises myopathy risk).",
4:"The interaction is metabolic (CYP3A4), not protein displacement."},
eli5="The antibiotic blocked the liver from clearing her statin, so the statin built up and started breaking down her muscles. That's why her urine turned dark."),

dict(img=None,
stem="A 57-year-old man is about to start atorvastatin. He has read online that statins cause muscle damage and asks what to expect.{FIG}According to the lecture, which of the following best reflects current guidance on counseling about statin myopathy?",
choices=["Avoid front-loading it (nocebo effect)","Warn that most patients develop myositis","Check a creatine kinase level every month","Advise stopping the statin for any mild ache","Tell him statins never affect muscle"], key=0,
exp="Dr. Scully: statins are taken by so many people that adverse effects appear in the literature and in clinic, but they're <b>generally well tolerated</b>. Myopathy → rhabdomyolysis <b>does happen, but less often than first thought</b>. Recommendations have shifted toward <b>not front-loading counseling about it</b> because of the <b>nocebo</b> (placebo-type) effect: expecting aches makes people report them. Still, <b>severe muscle pain with tea-coloured urine</b> means work it up.<br><br><b>Educational objective:</b> Statin myopathy is real but less common than once thought. Avoid nocebo-inducing counseling, but investigate severe pain or dark urine.",
wrong={1:"Myositis is uncommon. Most patients tolerate statins well.",
2:"Routine monthly CK checks aren't recommended. Check CK when symptoms suggest it.",
3:"Mild aches don't automatically mean stopping. Severe pain or dark urine needs workup.",
4:"Statins can cause myopathy. It's just less common than feared."},
eli5="If you tell people a pill will make their muscles hurt, many will feel aches whether or not the pill causes them. So doctors don't lead with it, but they do act on severe pain or dark urine."),

dict(img=None,
stem="A 58-year-old woman on maximal tolerated rosuvastatin remains above her LDL goal. Her physician adds a drug that selectively inhibits a brush-border sterol transporter in the small intestine.{FIG}Which transporter does this drug inhibit?",
choices=["NPC1L1","HMG-CoA reductase","PCSK9","ABCA1","Lipoprotein lipase"], key=0,
exp="<b>Ezetimibe</b> selectively inhibits the <b>Niemann-Pick C1-Like 1 (NPC1L1)</b> brush-border transporter that takes up dietary (and biliary) cholesterol. Cholesterol absorption falls <b>by up to 50%</b>, <b>without reducing absorption of triglycerides or the fat-soluble vitamins</b>. It's the usual statin add-on when LDL isn't at goal: a very good safety profile with \"few if any\" adverse effects.<br><br><b>Educational objective:</b> Ezetimibe blocks NPC1L1, cutting intestinal cholesterol absorption by up to 50% without affecting TG or fat-soluble vitamin absorption.",
wrong={1:"HMG-CoA reductase is the statin target in the liver.",
2:"PCSK9 is a circulating protein that degrades LDL receptors.",
3:"ABCA1 effluxes cholesterol to form HDL.",
4:"Lipoprotein lipase hydrolyzes triglycerides in plasma lipoproteins."},
eli5="Ezetimibe locks the door in the gut that lets cholesterol from food get absorbed."),

dict(img=None,
stem="A 50-year-old man who refuses statins is started on ezetimibe alone. His LDL drops initially but returns nearly to baseline over the next few months, although he is taking the drug correctly.{FIG}Which of the following best explains this?",
choices=["The liver makes more of its own cholesterol","He has developed antibodies against ezetimibe","Ezetimibe induces its own hepatic metabolism","NPC1L1 transporters are rapidly down-regulated","Dietary fat intake rises to compensate"], key=0,
exp="Blocking absorption → ↓ intracellular cholesterol → the body <b>up-regulates its own synthesis</b> (HMG-CoA reductase), and LDL drifts back toward baseline. That's why ezetimibe is weak as monotherapy and works well <b>with a statin</b>, which blocks that compensatory synthesis. Statins are commonly combined with absorption inhibitors or bile acid sequestrants to lower LDL further. Ezetimibe is usually the adjunct because of its fewer adverse effects.<br><br><b>Educational objective:</b> Ezetimibe alone is weak because the liver compensates by making more cholesterol. A statin blocks that compensation.",
wrong={1:"Ezetimibe is a small molecule and doesn't trigger antibodies.",
2:"Ezetimibe doesn't induce its own metabolism.",
3:"Transporter down-regulation isn't the explanation given.",
4:"Compensation is endogenous synthesis, not diet."},
eli5="Block cholesterol coming in from food, and the liver just makes more of its own. A statin stops the liver from doing that."),

dict(img=None,
stem="A 66-year-old woman who takes cholestyramine with her statin notices easy bruising and bleeding gums. Her prothrombin time and INR are prolonged; she takes no anticoagulants, and her liver function is normal.{FIG}Which of the following best explains these findings?",
choices=["Malabsorption of the fat-soluble vitamin K","Direct inhibition of platelet aggregation","Cholestyramine-induced liver failure","Bone marrow suppression of platelets","Statin-induced inhibition of clotting factor synthesis"], key=0,
exp="<b>Bile acid sequestrants</b> work with statins to lower cholesterol, but they <b>impair absorption of fat-soluble vitamins</b> and can cause <b>vitamin K deficiency</b> (a lecture point). That means less γ-carboxylation of factors II, VII, IX and X, so PT/INR rises and she bleeds. GI effects (bloating, dyspepsia) limit adherence, and \"you will see these drugs used for other indications more regularly than for dyslipidemia\". Board add-on: they bind bile acids → the liver converts more cholesterol to bile acids → ↑ LDL receptors.<br><br><b>Educational objective:</b> Bile acid sequestrants can cause vitamin K deficiency (fat-soluble vitamin malabsorption), prolonging the INR.",
wrong={1:"Cholestyramine doesn't affect platelets.",
2:"Her liver function is normal.",
3:"There's no evidence of marrow suppression, and the INR points to clotting factors.",
4:"Statins don't block vitamin K–dependent factor synthesis."},
eli5="Cholestyramine traps fat in the gut, and vitamin K travels with fat, so she isn't absorbing enough. Without vitamin K, blood can't clot well."),

dict(img='Aalipemic', cap="Centrifuged blood samples; the leftmost is the patient's",
stem="A 54-year-old man with hypercholesterolemia on atorvastatin has a fasting triglyceride level of 640 mg/dL; his centrifuged sample is shown on the left. His physician is choosing an adjunct to further lower his LDL.{FIG}Which adjunct should be avoided in this patient?",
choices=["Cholestyramine","Ezetimibe","Evolocumab","Fenofibrate","Icosapent ethyl"], key=0,
exp="The milky, <b>lipemic serum</b> reflects very high triglycerides. Board add-on: <b>bile acid sequestrants</b> (cholestyramine, colestipol, colesevelam) <b>can raise triglycerides</b>. Avoid them when TG is above ~300–500 mg/dL, since a further rise risks pancreatitis. Ezetimibe is the lecture's preferred adjunct anyway (fewer adverse effects). Fenofibrate and omega-3 fatty acids lower TG. Sequestrants also bind other drugs (warfarin, digoxin), so doses must be spaced.<br><br><b>Educational objective:</b> Bile acid sequestrants can raise triglycerides and are avoided in significant hypertriglyceridemia.",
wrong={1:"Ezetimibe doesn't raise TG. It's the usual statin add-on.",
2:"PCSK9 antibodies lower LDL and don't raise TG.",
3:"Fenofibrate <b>lowers</b> TG.",
4:"Prescription omega-3 (EPA) <b>lowers</b> TG."},
eli5="His blood is already milky with fat. Cholestyramine can push triglycerides even higher, so it's the one to skip."),

dict(img=None,
stem="A 70-year-old man takes digoxin and cholestyramine. His digoxin level is subtherapeutic, and his atrial fibrillation rate has become poorly controlled since cholestyramine was started.{FIG}Which of the following is the most appropriate change?",
choices=["Space the doses several hours apart","Double the cholestyramine dose","Take both drugs together with food","Switch digoxin to the intravenous route permanently","Add a second bile acid sequestrant"], key=0,
exp="Board add-on: <b>bile acid sequestrants bind other drugs</b> in the gut (digoxin, warfarin, thyroxine, fat-soluble vitamins) and reduce their absorption. The fix is <b>spacing</b>: give the other drug at least 1 hour before or about 4 hours after the resin. The lecture adds that GI effects (bloating, dyspepsia) limit adherence, that they can cause vitamin K deficiency, and that they're used more for other indications (cholestatic pruritus, bile-acid diarrhea).<br><br><b>Educational objective:</b> Bile acid sequestrants bind co-administered drugs such as digoxin and warfarin. Space the doses.",
wrong={1:"More resin would bind even more digoxin.",
2:"Taking them together maximizes binding.",
3:"Long-term IV digoxin is impractical when spacing solves the problem.",
4:"Another sequestrant adds to the binding problem."},
eli5="Cholestyramine is like a sponge in the gut that soaks up his digoxin too. Taking the pills hours apart keeps the sponge from grabbing it."),

dict(img=None,
stem="A 40-year-old woman with an LDL of 172 mg/dL asks how much she can expect to lower her cholesterol with a strict diet before considering a drug.{FIG}By approximately how much can diet lower total cholesterol, according to the lecture?",
choices=["5%","10%","25%","50%","75%"], key=2,
exp="Slide 5: <b>diet can lower total cholesterol by ~25%</b>, depending on adherence and the metabolic basis of the dyslipidemia. Lifestyle (exercise, weight loss) won't be enough for everyone, especially with genetic dyslipidemias. That's why drugs are widely used and the decision rests on <b>calculated cardiovascular risk</b>. Much of the stigma around dyslipidemia is about diet, but lipid metabolism has many genetic determinants that lifestyle can't fix: \"there's no cookie-cutter treatment\".<br><br><b>Educational objective:</b> Diet can lower total cholesterol by about 25%, which isn't enough for many patients.",
wrong={0:"Diet can do considerably better than 5% with good adherence.",
1:"The lecture figure is about 25%.",
3:"50% is more than diet typically achieves. It's the range of high-intensity statins.",
4:"No diet lowers cholesterol by 75%."},
eli5="A really good diet can cut cholesterol by about a quarter. That helps, but it's often not enough on its own."),

dict(img=None,
stem="A 31-year-old woman with familial hypercholesterolemia takes atorvastatin. She plans to become pregnant within the next few months.{FIG}Which of the following is the most appropriate advice regarding her statin?",
choices=["Stop the statin before trying to conceive","Continue the statin throughout pregnancy","Switch to a double dose of a low-intensity statin","Stop the statin only in the third trimester","Add fenofibrate to permit a lower statin dose"], key=0,
exp="Board add-on: statins are <b>contraindicated in pregnancy</b> (and in active liver disease), because cholesterol synthesis is needed for fetal development. Stop them before conception. Bile acid sequestrants aren't absorbed and are the usual pregnancy option. Note the lecture's \"no cookie-cutter treatment\" point: familial hypercholesterolemia is a genetic dyslipidemia (LDL-receptor defects) that lifestyle can't fix.<br><br><b>Educational objective:</b> Statins are contraindicated in pregnancy. Stop them before conception.",
wrong={1:"Statins are contraindicated in pregnancy.",
2:"Any statin, at any intensity, is contraindicated in pregnancy.",
3:"Statins should be stopped before conception, not late in pregnancy.",
4:"Fibrates aren't the answer, and adding one doesn't make a statin safe in pregnancy."},
eli5="A growing baby needs cholesterol to build its cells, so statins have to stop before she gets pregnant."),

dict(img=None,
stem="A 64-year-old man taking warfarin and amiodarone needs a statin. His physician wants one that is metabolized by CYP2C9 rather than CYP3A4 and has low potency.{FIG}Which statin fits this description?",
choices=["Fluvastatin","Atorvastatin","Simvastatin","Lovastatin","Rosuvastatin"], key=0,
exp="Lecture metabolism table: <b>fluvastatin and pitavastatin</b> use <b>other CYPs (2C9)</b>. Lovastatin, simvastatin and atorvastatin use <b>CYP3A4</b>. Pravastatin and rosuvastatin are largely <b>non-CYP</b>. <b>Fluvastatin</b> is also the <b>least potent</b> (\"<b>Flo</b> Loves Prague Since A Tour of Russia\"). Board add-on: amiodarone inhibits CYP3A4 and raises simvastatin and lovastatin levels. Warfarin is a CYP2C9 substrate, so fluvastatin needs INR monitoring.<br><br><b>Educational objective:</b> Fluvastatin (and pitavastatin) are CYP2C9-metabolized. Fluvastatin is the least potent statin.",
wrong={1:"Atorvastatin is a high-intensity CYP3A4 substrate.",
2:"Simvastatin is a CYP3A4 substrate (and interacts with amiodarone).",
3:"Lovastatin is a CYP3A4 substrate.",
4:"Rosuvastatin is high intensity and largely non-CYP."},
eli5="Fluvastatin is cleared by a different liver enzyme than most statins, and it's the gentlest one."),

dict(img=None,
stem="A 58-year-old woman on a statin has LDL 88 mg/dL, HDL 52 mg/dL and triglycerides 140 mg/dL. Her LDL fell by 40% on treatment, while her triglycerides fell modestly and her HDL rose slightly.{FIG}Which statement best describes statins' lipid effects, as summarized in the lecture?",
choices=["Large ↓ LDL with small ↓ TG and small ↑ HDL","Large ↓ TG with no effect on LDL","Large ↑ HDL with a small ↓ LDL","Equal ↓ in LDL, TG and HDL","↓ LDL only, with no TG or HDL effect"], key=0,
exp="Slide 6: <b>hypercholesterolemia (↑ LDL)</b> → statins are the first choice. They also <b>lower TG and raise HDL a little</b>, which is one reason they're prescribed broadly in practice. For <b>hypertriglyceridemia</b>: diet, omega-3 fatty acids, fibrates. For <b>low HDL</b>: niacin (very effective), fibrates (small rise), though treating isolated low HDL is contested in the literature.<br><br><b>Educational objective:</b> Statins mainly lower LDL, with small reductions in TG and small increases in HDL.",
wrong={1:"Large TG reductions are a fibrate or omega-3 effect.",
2:"A large HDL rise is niacin's signature.",
3:"Statins don't lower HDL.",
4:"Statins have modest TG and HDL effects as well."},
eli5="Statins are mainly an LDL drug. They nudge triglycerides down and HDL up a little as a bonus."),
]
