# Pediatric Cardiology (Baker / Foster slides) — Version 1, 18 items (6 with images); topics and angles differ from V2
Q = [
dict(img=None,
stem="During a sports physical, a 12-year-old boy has a loud systolic murmur at the left lower sternal border. When the examiner places a palm flat on the chest over that area, a vibration is felt with each heartbeat. The murmur is not heard when the stethoscope is lifted off the chest wall, nor with only its edge touching.{FIG}Which of the following is the grade of this murmur?",
choices=["2/6","3/6","4/6","5/6","6/6"], key=2,
exp="Murmur grading from the lecture:<br>• Grade 1: soft, heard only in quiet conditions.<br>• Grade 2: soft but heard even in noisy conditions.<br>• Grade 3: easily heard, prominent.<br>• <b>Grade 4: loud, with a palpable thrill</b> (the vibration under the palm).<br>• Grade 5: heard with the stethoscope edge tilted on the chest, plus a thrill.<br>• Grade 6: heard with the stethoscope just off the chest, plus a thrill.<br>The thrill is the threshold that moves a murmur to grade 4. He has a thrill but no grade 5–6 features. Diastolic murmurs are graded only to 4.<br><br><b>Educational objective:</b> A palpable thrill makes a murmur at least grade 4/6. Grades 5 and 6 need the stethoscope edge or no contact at all.",
wrong={0:"Grade 2 murmurs are soft and have no thrill.",
1:"Grade 3 is loud and prominent but has <b>no thrill</b>.",
3:"Grade 5 is audible with only the edge of the stethoscope touching the chest.",
4:"Grade 6 is audible with the stethoscope completely off the chest."},
eli5="If you can feel the murmur buzzing under your hand, it's at least a 4 out of 6. It only goes higher if you can hear it with the stethoscope barely touching (5) or not touching at all (6)."),

dict(img=None,
stem="A healthy 4-year-old girl has a soft, continuous humming murmur below both clavicles, louder on the right, heard while she sits on the examination table. It disappears when she lies down and when the examiner gently turns her head to the side or presses over the internal jugular vein.{FIG}Which of the following is the most appropriate next step?",
choices=["Reassurance that the murmur is innocent","Echocardiogram to look for a ductus arteriosus","Pediatric cardiology referral","Chest x-ray and electrocardiogram","Repeat examination with a fever workup"], key=0,
exp="A soft (grade 1–2), <b>continuous</b> murmur below the clavicles (R > L) in a child over 2 that <b>disappears when she lies down, turns her head, or has the jugular vein compressed</b> is a <b>venous hum</b>. It is innocent: blood flow in the neck veins, and the most common continuous murmur in children. The positional change is the key feature. A continuous murmur from a PDA doesn't vanish when the jugular is compressed.<br><br><b>Educational objective:</b> A venous hum is an innocent continuous infraclavicular murmur that disappears with supine position, head turning or jugular compression. Reassure.",
wrong={1:"A PDA murmur is continuous but doesn't disappear with positioning or jugular compression.",
2:"Referral is for possibly structural murmurs, exertional chest pain, arrhythmia or recurrent syncope. This murmur is innocent.",
3:"Imaging and an ECG add nothing when the bedside maneuvers have identified an innocent murmur.",
4:"Fever brings out flow murmurs, but this child is well and the positional change has already explained the murmur."},
eli5="This hum is just blood flowing through the neck veins. Lying down or turning the head changes that flow and the sound disappears. It's harmless."),

dict(img=None,
stem="A 2-year-old boy is seen for 2 days of fever and cough. His temperature is 39.6°C (103.3°F) and pulse is 150/min. A new grade 2/6 systolic ejection murmur is heard at the left upper sternal border. The rest of the examination is normal, and he has been growing well. Hemoglobin is normal.{FIG}Which of the following is the most appropriate next step regarding the murmur?",
choices=["Recheck once the fever resolves","Order an echocardiogram this week","Obtain an electrocardiogram today","Refer to a pediatric cardiologist for evaluation","Start antibiotics for endocarditis"], key=0,
exp="Dr. Baker: \"murmurs are very common in children, but heart disease is not\". <b>95% of childhood murmurs are innocent.</b> Innocent flow murmurs are brought out by <b>high-output states</b>: <b>fever</b>, anemia (for example sickle cell disease), pregnancy and thyrotoxicosis. More flow means more turbulence and more noise. A soft systolic ejection murmur in a febrile child with otherwise normal findings should be <b>rechecked once the fever is gone</b>; it usually disappears. He also advises discretion: a very soft murmur in a febrile child doesn't need a list of frightening possibilities.<br><br><b>Educational objective:</b> Fever and other high-output states produce innocent flow murmurs. Re-examine after the fever resolves before investigating.",
wrong={1:"An echo isn't needed for a soft murmur that is likely a flow murmur until it persists when he is afebrile.",
2:"An ECG doesn't help characterize a soft flow murmur in a febrile child.",
3:"Referral is for possibly structural murmurs or concerning symptoms, not a soft murmur with fever.",
4:"There's no evidence of endocarditis (a new harsh murmur, embolic signs, positive cultures). Respiratory fever explains the flow murmur."},
eli5="A fever makes the heart pump harder and faster, so blood rushes through and makes a soft whooshing sound. Once the fever goes away, the sound usually does too."),

dict(img=None,
stem="An 8-year-old boy is seen for a routine visit. He is active and asymptomatic. Auscultation reveals a soft, high-pitched, decrescendo murmur that begins immediately after the second heart sound, best heard along the left sternal border. The first and second heart sounds are normal.{FIG}Which of the following is the most appropriate next step?",
choices=["Echocardiogram and cardiology referral","Reassurance that it is an innocent murmur","Re-examine at next year's checkup","Recheck after an iron supplement","Repeat examination while he is supine"], key=0,
exp="The murmur starts <b>after S2</b>, so it is <b>diastolic</b>. A blowing decrescendo murmur along the left sternal border suggests a regurgitant semilunar valve (aortic or pulmonic regurgitation). The lecture rule: an isolated diastolic murmur implies regurgitation and is <b>never normal</b> (\"Always pathologic if you hear a diastolic murmur\"). However well the child looks, he needs an <b>echocardiogram and pediatric cardiology referral</b>. Innocent murmurs are systolic (or continuous, like the venous hum).<br><br><b>Educational objective:</b> An isolated diastolic murmur is always pathologic in a child. Refer for echocardiography.",
wrong={1:"Innocent murmurs are systolic or continuous. A diastolic murmur is never innocent.",
2:"Waiting a year delays the diagnosis of a valve lesion.",
3:"Anemia gives high-output <b>systolic</b> flow murmurs, not diastolic regurgitant ones.",
4:"Positional changes help identify a venous hum. They don't make a diastolic murmur innocent."},
eli5="Normal 'innocent' murmurs happen while the heart squeezes. A whoosh after the second heart sound means blood is leaking backward through a valve, which always needs a heart ultrasound."),

dict(img=None,
stem="A 3-week-old girl born at term is seen for a weight check. She is feeding well and has regained her birth weight. A soft grade 1/6 systolic murmur is heard at the left upper sternal border, radiating to both axillae and to the back. Oxygen saturation, pulses and the rest of the examination are normal.{FIG}Which of the following is the most likely cause of this murmur?",
choices=["Peripheral pulmonary stenosis","Patent ductus arteriosus","Coarctation of the aorta","Ventricular septal defect","Tetralogy of Fallot"], key=0,
exp="A soft systolic murmur at the <b>left upper sternal border</b> that <b>radiates to both axillae and the back</b> in a thriving newborn is <b>peripheral pulmonary stenosis</b>, an innocent murmur of the first weeks of life. The branch pulmonary arteries are relatively narrow at birth, and the turbulence fades as they grow (board add-on: usually gone by about 1 year). Normal saturations, pulses and growth make a structural lesion unlikely.<br><br><b>Educational objective:</b> Peripheral pulmonary stenosis is an innocent newborn murmur at the left upper sternal border radiating to the axillae and back, and it resolves as the pulmonary arteries grow.",
wrong={1:"A PDA classically gives a <b>continuous</b> machinery murmur, often with bounding pulses.",
2:"Coarctation gives weak femoral pulses and a blood-pressure difference between arms and legs. Her pulses are normal.",
3:"A VSD is a holosystolic murmur at the left <b>lower</b> sternal border.",
4:"Tetralogy causes cyanosis and a harsher murmur. Her saturation is normal."},
eli5="A newborn's lung arteries start out a bit narrow, so blood whooshes through them and you can hear it under the arms and in the back. As the baby grows, the arteries widen and the sound goes away."),

dict(img=None,
stem="A 22-week fetus is imaged as part of a research study of fetal circulation. Oxygen saturation is measured in several vessels.{FIG}Which of the following vessels is expected to carry blood with the highest oxygen saturation?",
choices=["Umbilical vein","Umbilical artery","Ductus arteriosus","Main pulmonary artery","Superior vena cava"], key=0,
exp="Before birth, gas exchange happens in the <b>placenta</b>. Oxygenated blood leaves the placenta in the <b>umbilical vein</b>, passes the liver through the ductus venosus, and enters the inferior vena cava and right atrium. Even so, fetal saturations are only about <b>50–65%</b> (slide). From the right atrium about a third crosses the <b>foramen ovale</b> to the left side. The rest goes right ventricle → pulmonary artery, and most of it crosses the <b>ductus arteriosus</b> into the aorta. Only a small fraction reaches the fluid-filled lungs. Deoxygenated blood returns to the placenta in the <b>umbilical arteries</b>. The umbilical vein carries the most oxygenated blood.<br><br><b>Educational objective:</b> In the fetus, the umbilical vein carries the most oxygenated blood (from the placenta). The foramen ovale and ductus arteriosus shunt blood past the lungs.",
wrong={1:"The umbilical arteries return <b>deoxygenated</b> blood from the fetus to the placenta.",
2:"The ductus arteriosus carries mostly right-ventricular blood (largely from the superior vena cava), which is less saturated.",
3:"The pulmonary artery carries right-ventricular output, mostly SVC return, so it is less saturated.",
4:"The superior vena cava returns deoxygenated blood from the head and arms."},
eli5="Before birth the baby gets its oxygen from the mom through the placenta. The fresh, oxygen-rich blood comes into the baby through the umbilical vein, so that's the reddest blood."),

dict(img='Aafixed', cap='Timing of the heart sounds during expiration and inspiration',
stem="A 23-year-old woman develops sudden weakness of her right arm and face 2 days after a long-haul flight; a deep vein thrombosis is found in her left calf. As a child she had a soft systolic murmur at the left upper sternal border that was never investigated. The timing of her heart sounds is shown.{FIG}Which of the following best explains her stroke?",
choices=["Venous clot crossing an atrial septal defect","Thrombus from a dilated left atrial appendage","Septic emboli from a mitral valve vegetation","Dissection of the left internal carotid artery","Cholesterol emboli from an aortic plaque"], key=0,
exp="The diagram shows <b>A2 and P2 split by the same amount in expiration and inspiration</b>: a <b>fixed, wide split S2</b>. With a soft systolic ejection murmur at the left upper sternal border (extra flow across the pulmonic valve), that's an <b>atrial septal defect</b>. The lecture lists the complications of a larger ASD: right ventricular overload with a fixed split S2, atrial arrhythmias (SVT, atrial fibrillation), and <b>thrombotic stroke</b>. A venous clot (from her DVT) can cross from right to left atrium, a <b>paradoxical embolism</b>, especially when right atrial pressure transiently exceeds left. Closure options include an Amplatzer septal occluder placed by catheter.<br><br><b>Educational objective:</b> An ASD causes a fixed split S2 and can allow a venous thrombus to cross to the systemic circulation (paradoxical embolism → stroke).",
wrong={1:"Left atrial appendage thrombus needs atrial fibrillation or mitral stenosis. Her DVT and fixed split S2 point to a paradoxical source.",
2:"Septic emboli need endocarditis (fever, positive cultures). She has a venous clot.",
3:"Carotid dissection follows neck trauma or manipulation. It doesn't explain the fixed split S2 and DVT.",
4:"Cholesterol emboli come from older patients with atherosclerosis or after vascular procedures."},
eli5="She has a hole between the two upper heart chambers. A clot from her leg traveled to the right side of the heart, slipped through the hole to the left side, and went to her brain."),

dict(img=None,
stem="A 3-year-old boy is new to the practice. His father and older sister have bicuspid aortic valves. He is asymptomatic and active. A grade 2/6 systolic ejection murmur with an early ejection click is heard at the right upper sternal border, radiating to the carotids. An echocardiogram confirms a bicuspid aortic valve with a mild gradient and a normal aorta. His parents ask whether the valve should be replaced now to prevent problems.{FIG}Which of the following is the most appropriate management?",
choices=["Serial echocardiography, intervening by gradient","Balloon valvuloplasty now to prevent future stenosis","Bioprosthetic valve replacement now","Daily aspirin to prevent valve calcification","Restriction from all physical activity"], key=0,
exp="This is the lecture's student question. A bicuspid aortic valve is inherited, 2 leaflets instead of 3, in 1–2% of people. Over time it brings stenosis or regurgitation, aortic dilation (aneurysm, dissection) and endocarditis, and nearly all patients need valve surgery eventually. But surgery is <b>not done preemptively</b>. An asymptomatic child is <b>followed by cardiology with an echocardiogram about every 2 years</b>. Intervention (balloon, later a prosthetic valve) is triggered when <b>pressure gradients across the valve reach set criteria</b>. \"Rule number one, do no harm... if it ain't broke, don't fix it.\" When a murmur is loudest in the aortic area, he also listens over the carotids.<br><br><b>Educational objective:</b> An asymptomatic child with a bicuspid aortic valve is followed with serial echocardiography, and intervention is timed to gradient criteria, not done preemptively.",
wrong={1:"Balloon valvuloplasty is for significant stenosis that meets intervention criteria, not a mild gradient.",
2:"A prosthetic valve in a growing child would need repeated replacement and brings anticoagulation or durability problems. It isn't indicated yet.",
3:"Aspirin doesn't prevent bicuspid valve degeneration.",
4:"A mild gradient doesn't warrant restricting all activity. Restrictions depend on severity."},
eli5="His valve has two flaps instead of three and will likely need fixing someday, but not now while it works well. The heart doctor checks it with ultrasound every couple of years and fixes it when it gets tight enough."),

dict(img='Ptet', cap='Drawing of an infant during an episode',
stem="A 5-month-old boy with a known heart defect becomes intensely blue around the lips and fingers, irritable and breathless after a long bout of crying (drawing shown). His usual oxygen saturation is 88%; it is now 70%. A previously harsh systolic murmur at the left upper sternal border has become much softer.{FIG}Which of the following is the most appropriate initial intervention?",
choices=["Knee-to-chest positioning","Lay him flat and raise both legs","Give intravenous furosemide","Start an albuterol nebulizer","Load with digoxin"], key=0,
exp="This is a <b>tet spell</b> in <b>tetralogy of Fallot</b>: crying or feeding triggers acute worsening of cyanosis. The lecture: crying increases the right-to-left shunt through the VSD, so less blood reaches the lungs. The murmur <b>softens</b> because less blood crosses the narrowed pulmonary outflow. Board add-on: the mechanism is a fall in systemic vascular resistance and/or a rise in outflow obstruction. <b>Knee-to-chest positioning</b> (or squatting in an older child) compresses the femoral arteries and <b>raises systemic vascular resistance</b>, which pushes blood back toward the lungs. Further steps are oxygen, morphine and fluids, then phenylephrine and a β-blocker.<br><br><b>Educational objective:</b> A tet spell is treated first with knee-to-chest positioning, which raises systemic vascular resistance and reduces right-to-left shunting.",
wrong={1:"Lying flat doesn't raise systemic vascular resistance the way knee-chest compression does.",
2:"A diuretic lowers preload and BP, which would <b>worsen</b> the right-to-left shunt.",
3:"This is a cardiac shunt problem, not bronchospasm, and albuterol's β2 vasodilation lowers systemic resistance.",
4:"Digoxin increases contractility and can worsen the outflow obstruction. It's not used for spells."},
eli5="When this baby cries, too much blue blood skips the lungs and goes to the body. Folding his knees up to his chest squeezes the leg arteries, which pushes blood back toward the lungs to pick up oxygen."),

dict(img=None,
stem="A 5-day-old boy is brought to the emergency department because he became pale, breathless and unresponsive over a few hours. He was well at discharge from the nursery. He has weak pulses in all four limbs, a capillary refill of 5 seconds, a blood pressure of 50/30 mm Hg, and hepatomegaly. An echocardiogram shows a tiny left ventricle and a hypoplastic ascending aorta.{FIG}Systemic blood flow in this condition depends primarily on flow through which of the following structures?",
choices=["Ductus arteriosus","Ductus venosus","Foramen ovale alone","Ventricular septal defect","Coronary sinus"], key=0,
exp="A newborn who collapses into <b>cardiogenic shock in the first days of life</b>, with a tiny left ventricle, has <b>hypoplastic left heart syndrome</b> (about 1 in 4,350 births). The left heart can't pump to the body, so the right ventricle supplies it: <b>RV → pulmonary artery → ductus arteriosus → aorta</b>. Blood returning from the lungs to the left atrium must cross the <b>foramen ovale/ASD</b> into the right side. While the ductus is open the baby looks well. As it closes over the first days, systemic perfusion collapses, giving sudden tachypnea, tachycardia, hypotension and shock. Treatment: <b>prostaglandin E1 to reopen the ductus</b>, then 3-stage surgery (Norwood, Glenn, Fontan) or transplant.<br><br><b>Educational objective:</b> In hypoplastic left heart syndrome, systemic blood flow depends on the ductus arteriosus. Its closure causes shock, and prostaglandin E1 keeps it open.",
wrong={1:"The ductus venosus carries placental blood through the liver before birth. It has no role after birth.",
2:"The atrial communication carries pulmonary venous return to the right heart (it is needed too), but systemic output depends on the ductus.",
3:"A VSD isn't the obligate pathway in HLHS.",
4:"The coronary sinus drains cardiac veins into the right atrium. It doesn't carry systemic output."},
eli5="In this baby the left pump is tiny, so the right pump has to feed the body through a little fetal pipe called the ductus. When that pipe naturally closes after birth, the body suddenly loses its blood supply."),

dict(img=None,
stem="A 14-year-old girl collapsed during a frog dissection in a hot classroom. She had skipped breakfast and felt lightheaded, nauseated, sweaty and \"gray\" for about a minute before she fell. She regained consciousness within seconds of lying flat. Her examination and electrocardiogram are normal.{FIG}Which of the following mechanisms best explains her episode?",
choices=["Withdrawal of α-adrenergic tone with ↑ vagal tone","Re-entrant tachycardia through an accessory pathway","Outflow obstruction from a thickened septum","Torsades de pointes from a prolonged QT","Generalized seizure with postictal confusion"], key=0,
exp="This is the lecture's frog-dissection case: <b>neurally mediated (vasovagal) syncope</b>, by far the most common category in children (15–20% faint at least once by the end of adolescence). The slide's mechanism: <b>peripheral α-adrenergic withdrawal</b> (vessels relax) plus <b>enhanced parasympathetic tone</b> (the heart slows). Cerebral perfusion falls briefly. Contributors are hunger, heat, prolonged standing, crowded rooms, emotional distress and the sight of dissection. The tell is the <b>prodrome</b>: lightheadedness, nausea, pallor, sweating and visual changes. She recovers quickly lying down. Treatment: lie down with legs raised, rest, fluids, slow position changes and a little more salt.<br><br><b>Educational objective:</b> Vasovagal syncope comes from peripheral α-adrenergic withdrawal plus increased vagal tone. It is preceded by a prodrome and recovers quickly when supine.",
wrong={1:"Re-entrant tachycardia gives palpitations and abrupt onset, and the ECG may show pre-excitation. Hers is normal.",
2:"HCM syncope classically occurs <b>during exertion</b> without a warning prodrome.",
3:"Long QT syncope is sudden (often triggered by exertion or a startle), and the ECG shows a long QT.",
4:"A seizure gives prolonged confusion. She recovered within seconds after a classic vasovagal prodrome."},
eli5="She was hungry, hot and grossed out, so her blood vessels relaxed and her heart slowed. Less blood reached her brain and she fainted. Lying down brought the blood back right away."),

dict(img=None,
stem="A pediatrician is completing a sports pre-participation evaluation for a 15-year-old basketball player. Physical examination is normal.{FIG}Which of the following answers on the American Academy of Pediatrics sudden-cardiac-arrest screening questions most warrants further cardiac evaluation before he plays?",
choices=["He fainted without warning while running sprints","He felt dizzy once after standing up quickly","He fainted once while having blood drawn","A grandfather, 80, died of a heart attack","He drinks coffee before most morning practices"], key=0,
exp="The lecture's red flags for syncope are a faint that happens <b>suddenly without a prodrome</b>, or <b>during exercise or activity</b>. The four AAP screening questions ask about:<br>1. Fainting, passing out or a seizure <b>suddenly and without warning, especially during exercise</b> (or triggered by loud sounds such as a doorbell or alarm).<br>2. Exercise-induced chest pain or shortness of breath.<br>3. A relative with sudden, unexplained death <b>before age 50</b>.<br>4. A relative with a sudden-death condition (HCM, long QT, VT).<br>Exertional syncope without warning needs an ECG and cardiology evaluation (HCM, long QT, WPW, coronary anomalies) before he plays.<br><br><b>Educational objective:</b> Syncope during exercise or without warning is a red flag for cardiac syncope and needs cardiac evaluation before sports.",
wrong={1:"Brief lightheadedness on standing quickly is orthostatic and benign. Advise slow position changes and fluids.",
2:"Fainting at a blood draw is classic vasovagal syncope with an emotional trigger.",
3:"A heart attack at age 80 isn't sudden unexplained death before 50.",
4:"Caffeine may cause harmless extra beats but isn't a screening red flag by itself."},
eli5="Fainting while running hard, with no warning, can mean a hidden heart problem. A teen who does that needs a heart check before playing sports again."),

dict(img='Radeno', cap='Rhythm strips recorded during treatment (handwritten annotations on the original)',
stem="A 12-year-old girl has had a racing heartbeat for 40 minutes. Her heart rate is 230/min and regular with narrow QRS complexes; blood pressure and perfusion are normal. Vagal maneuvers (blowing into a syringe, an ice bag to the face) fail. Adenosine is ordered, and the rhythm strips recorded during the dose are shown.{FIG}Which of the following is most important for this drug to work?",
choices=["A rapid push close to the heart, then a flush","A slow continuous infusion over 10 to 15 minutes","A loading dose given by mouth","Pretreatment with an intravenous β-blocker","Intramuscular injection of a large dose"], key=0,
exp="Adenosine converts narrow-complex re-entrant SVT. It opens K⁺ channels, hyperpolarizes nodal tissue and causes a brief AV block or asystole (the pause on the strip) before sinus rhythm returns. Its <b>half-life is only seconds</b>, so it must reach the heart as a concentrated bolus. Dr. Baker: \"given peripherally... it doesn't work... you need to give it close to the heart\". The Scully video says \"like a hand grenade\": a <b>rapid push into a large, proximal IV followed immediately by a saline flush</b>. Board add-on: a central line isn't required if the push is fast. Warn her about a brief sense of impending doom, flushing and chest pain. If it fails, repeat it or cardiovert.<br><br><b>Educational objective:</b> Adenosine has a half-life of seconds, so it must be given as a rapid IV push close to the heart followed immediately by a saline flush.",
wrong={1:"A slow infusion lets adenosine be metabolized before it reaches the AV node.",
2:"Adenosine isn't given orally. It would never reach the heart intact.",
3:"A β-blocker beforehand isn't needed and risks hypotension and bradycardia.",
4:"An IM injection is absorbed far too slowly for a drug that lasts seconds."},
eli5="Adenosine works for only a few seconds, so you have to push it in fast and wash it straight to the heart with a squirt of saline. Otherwise it wears off before it gets there."),

dict(img=None,
stem="A 12-year-old girl with nocturnal enuresis that did not respond to hypnosis or desmopressin was started on low-dose imipramine 4 months ago, with improvement. She has since had three brief episodes of sudden loss of consciousness without warning. Cardiac examination is normal.{FIG}Which of the following tests is most likely to identify the cause?",
choices=["12-lead electrocardiogram","Electroencephalogram","Tilt-table test","Serum glucose","Head computed tomography"], key=0,
exp="This is the lecture's imipramine case. Imipramine, a tricyclic antidepressant, <b>prolongs the QT interval</b>. Unexplained syncope in a child on a QT-prolonging drug points to <b>long QT syndrome</b>, here likely an unmasked congenital form, with episodes of torsades de pointes. The cardiologist found the answer on the <b>ECG</b>: QTc 0.63 s versus a normal 0.44 s. In children a normal QT is under 440 ms and a prolonged one over 460 ms. Long QT can cause unexplained bradycardia, palpitations, syncope, seizure or sudden death. The lecture's long-term treatment is an ICD. Board add-on: stop the drug and start a β-blocker.<br><br><b>Educational objective:</b> Unexplained syncope in a child taking a QT-prolonging drug (such as a tricyclic) calls for a 12-lead ECG to measure the QT interval.",
wrong={1:"Long QT episodes can look like seizures, but the EEG wouldn't show the cardiac cause.",
2:"A tilt-table test looks for vasovagal syncope. Her episodes have no prodrome and she is on a QT-prolonging drug.",
3:"Hypoglycemia gives a gradual onset with sweating and confusion, not abrupt repeated faints.",
4:"Head imaging isn't indicated for syncope with a normal exam, and it would miss the arrhythmia."},
eli5="Her bedwetting medicine can slow the heart's electrical reset, which can trigger a dangerous rhythm that makes her pass out. A simple ECG measures that reset time (the QT interval)."),

dict(img='Pkddesq', cap="Photograph of the child's fingers",
stem="A 3-year-old boy is seen for follow-up. Two weeks ago he had a high fever for 8 days with red eyes, cracked lips, a rash, and a swollen neck node; his family declined hospital treatment. The fever has resolved, and the skin on his fingertips is now peeling (shown).{FIG}Which of the following laboratory findings is most likely at this stage of his illness?",
choices=["Marked thrombocytosis","Severe thrombocytopenia","Positive antistreptolysin O titer","Eosinophilia","Hypercalcemia"], key=0,
exp="<b>Periungual desquamation</b> (peeling around the nail beds) 2–3 weeks after the fever is the <b>subacute phase of Kawasaki disease</b>, which Dr. Baker called \"something that's unique to it\". The lecture's case had a platelet count of <b>960,000</b>. Platelets rise in the subacute phase (weeks 2–4), when <b>coronary aneurysms</b> also develop. Untreated, he is at high risk of coronary artery dilation or aneurysm (about 5% even with treatment; 1% giant). He needs an <b>urgent echocardiogram</b>, plus aspirin and IVIG if he is still within the treatment window. Thrombosis in an aneurysm can cause sudden death.<br><br><b>Educational objective:</b> The subacute phase of Kawasaki disease brings periungual desquamation, marked thrombocytosis and the risk of coronary artery aneurysm.",
wrong={1:"Kawasaki disease raises the platelet count; it doesn't lower it.",
2:"A positive ASO titer supports recent streptococcal infection (scarlet or rheumatic fever), which can also cause peeling but not this picture.",
3:"Eosinophilia suggests allergy or parasites, not Kawasaki disease.",
4:"Hypercalcemia isn't a feature of Kawasaki disease."},
eli5="Weeks after the fever, his fingertips peel and his blood fills with platelets, the clotting cells. That's the same stage when Kawasaki disease can balloon the heart's arteries, so he needs a heart ultrasound."),

dict(img='Aaroth', cap='Fundoscopic photograph of the left eye',
stem="A 17-year-old who injects heroin comes to the emergency department with 5 days of fever, chills and fatigue. His temperature is 39.4°C (103°F). A new grade 3/6 holosystolic murmur is heard along the left lower sternal border, and he has dark linear lines under several fingernails. His fundoscopic examination is shown.{FIG}Which of the following is the most appropriate next step before starting antibiotics?",
choices=["Three sets of blood cultures","A single urine culture","Lumbar puncture","Throat swab for strep","Biopsy of a skin lesion"], key=0,
exp="Fever, a new murmur, splinter hemorrhages and the fundus finding, <b>Roth spots</b> (retinal hemorrhages with pale centres), mean <b>infective endocarditis</b>. The lecture's 17-year-old also had Janeway lesions and a mitral vegetation on echo. Board add-on: before antibiotics, draw <b>at least 3 sets of blood cultures</b> from separate sites, then get an echocardiogram (Duke criteria). In injection drug users the classic organism is <i>Staphylococcus aureus</i>, and the holosystolic left lower sternal border murmur suggests tricuspid regurgitation.<br><br><b>Educational objective:</b> Suspected infective endocarditis (fever, new murmur, Roth spots, splinter hemorrhages) needs three sets of blood cultures before antibiotics, followed by echocardiography.",
wrong={1:"A urine culture won't identify the organism on the valve.",
2:"There are no meningeal signs. A lumbar puncture would delay definitive diagnosis.",
3:"A throat swab looks for streptococcal pharyngitis, not bacteremia.",
4:"Skin lesion biopsy isn't needed. Blood cultures make the microbiologic diagnosis."},
eli5="Germs are probably growing on a heart valve and leaking into his blood, causing spots in his eyes and nails. Before giving antibiotics, doctors take several blood samples to grow the germ and know exactly what to treat."),

dict(img=None,
stem="The 13-year-old brother of a high-school athlete who was resuscitated from ventricular fibrillation on the soccer field is evaluated. The athlete was found to have hypertrophic cardiomyopathy. The brother is asymptomatic, his examination is normal, and his echocardiogram today shows normal wall thickness.{FIG}Which of the following is the most appropriate advice?",
choices=["Repeat echocardiograms through adolescence","No further screening is needed","Only screen again if he develops symptoms","Start a β-blocker as primary prevention now","Place an implantable defibrillator"], key=0,
exp="Hypertrophic cardiomyopathy is a <b>genetic, autosomal dominant</b> heart-muscle disease (more common in males), so a first-degree relative has about a 50% chance of carrying it. The lecture: the echo finding of a thick LV, especially the septum, <b>usually doesn't show up until early adolescence</b>. A normal echo at 13 doesn't exclude HCM, so screening is <b>repeated through adolescence</b> (board add-on: about every 1–2 years, plus genetic testing if the family mutation is known). HCM is the most common cause of sudden cardiac death in young athletes (36% in the registry slide). Mortality fell from 3–6% to about 1% with AEDs and trained staff.<br><br><b>Educational objective:</b> Because HCM is autosomal dominant and hypertrophy often appears only in adolescence, first-degree relatives need repeated echocardiographic screening.",
wrong={1:"A single normal echo at 13 doesn't exclude HCM, which often develops during adolescence.",
2:"Sudden death can be the first symptom, so waiting for symptoms is unsafe.",
3:"There's no diagnosis to treat, and β-blockers aren't given prophylactically to unaffected relatives.",
4:"An ICD is for patients with HCM and high-risk features, not an unaffected relative."},
eli5="This heart-thickening disease runs in families, and the thickening often doesn't show up until the teen years. So his brother's heart needs to be re-checked with ultrasound as he grows."),

dict(img='Aamonopvc', cap='Rhythm strip',
stem="A 16-year-old girl notices occasional \"flip-flops\" in her chest during exam week. She drinks three energy drinks a day and sleeps 5 hours a night. She has no syncope, chest pain, or exertional symptoms, and her examination and family history are normal. A rhythm strip is shown.{FIG}Which of the following is the most appropriate management?",
choices=["Cut out stimulants and reassure her","Start a daily oral β-blocker","Refer for catheter ablation of the focus","Begin oral amiodarone","Restrict her from all physical activity"], key=0,
exp="The strip shows <b>isolated, uniform (unifocal) premature ventricular contractions</b>: early, wide, bizarre QRS complexes with no P wave before them, each the same shape, and never two in a row. Dr. Baker: occasional PACs and PVCs are common in everybody, and <b>caffeine and energy drinks</b> are among the most common triggers (\"Did you stop at Aroma Joe's or Starbucks today?\"). With no symptoms on exertion, no syncope, a normal exam and no family history, management is to <b>reduce stimulants, improve sleep and reassure</b>. Worrying patterns are couplets (2 in a row), runs of 3 or more (VT), multiform PVCs, or symptoms with exercise.<br><br><b>Educational objective:</b> Isolated uniform PVCs in an asymptomatic teen are usually benign and often stimulant-related. Reduce caffeine and reassure.",
wrong={1:"A β-blocker isn't needed for occasional benign PVCs with a clear trigger.",
2:"Ablation is reserved for frequent, symptomatic or cardiomyopathy-causing ectopy that doesn't respond to conservative measures.",
3:"Amiodarone's toxicity is far out of proportion to benign PVCs.",
4:"Isolated uniform PVCs don't justify restricting activity."},
eli5="Every so often the bottom of her heart fires an extra beat early. They all look alike, she feels fine, and energy drinks are probably causing them, so cutting back on caffeine is the fix."),
]
