# Cardiac Physiology Review (Morganelli) — Version 1, 18 items (6 with images)
LOOPKEY = "In the figure, the solid loop was recorded at baseline and the dashed loop after the change."
Q = [
dict(img=None,
stem="A 44-year-old woman underwent total thyroidectomy 2 days ago. She now reports tingling around her mouth and in her fingertips, and her deep tendon reflexes are hyperactive. Serum calcium concentration is low.{FIG}In skeletal muscle, which of the following steps of contraction depends most directly on the calcium that is now in short supply?",
choices=["Binding of Ca²⁺ to tropomyosin","Conformational change in troponin after Ca²⁺ binding","Hydrolysis of ATP by myosin ATPase","Phosphorylation of myosin by myosin light-chain kinase","Stimulation of guanylyl cyclase"], key=1,
exp="Dr. Morganelli's advice: strip the stem. The one-line question is \"hypocalcemia: what step of skeletal-muscle contraction needs Ca²⁺?\" <b>Ca²⁺ binds troponin C</b> → the <b>troponin complex changes shape</b> → tropomyosin moves off the myosin-binding sites on actin → cross-bridges form and the power stroke follows. Force depends on how many cross-bridges are active at once. (The tingling and hyperreflexia are neural excitability effects of low Ca²⁺.) <b>Ca²⁺ never binds tropomyosin</b>, and half of last year's class fell for that.<br><br><b>Educational objective:</b> In striated muscle, Ca²⁺ binds troponin C, changing troponin's conformation so tropomyosin uncovers actin's myosin-binding sites. Ca²⁺ does not bind tropomyosin.",
wrong={0:"Ca²⁺ binds <b>troponin C</b>, not tropomyosin. Tropomyosin is moved by the troponin shape change.",
2:"ATP hydrolysis by myosin ATPase re-cocks the head. It needs ATP, not Ca²⁺, and continues as long as ATP is available.",
3:"Myosin light-chain kinase phosphorylation is how <b>smooth</b> muscle is activated (Ca²⁺–calmodulin → MLCK).",
4:"Guanylyl cyclase (the NO → cGMP pathway) plays no part in skeletal muscle contraction."},
eli5="Calcium is the key that unlocks muscle contraction. It fits into a lock called troponin, which swings the blocking strand (tropomyosin) out of the way. Then the muscle's grabbing heads can pull."),

dict(img='sarcEM', cap='Electron micrographs of a sarcomere, relaxed (b) and contracted (c)',
stem="Electron micrographs of the same striated muscle sarcomere at rest (b) and during contraction (c) are shown.{FIG}Which of the following structures maintains the same width in both states?",
choices=["A band","Distance between Z discs","H zone","I band","Sarcomere length"], key=0,
exp="Contraction is <b>sliding filaments</b>: thin (actin) filaments slide past thick (myosin) filaments, and <b>neither filament changes length</b>. The <b>A band</b> equals the length of the thick filaments, so it <b>stays the same width</b>. The <b>I band</b> (thin filament only) and the <b>H zone</b> (thick filament only) <b>narrow</b> as the filaments overlap more, and the <b>Z discs move closer</b>, so the sarcomere shortens.<br><br><b>Educational objective:</b> During contraction the A band (thick-filament length) stays constant, while the I band and H zone narrow and the sarcomere shortens.",
wrong={1:"The Z discs move <b>closer together</b> as the sarcomere shortens.",
2:"The H zone (thick filament without thin overlap) <b>narrows</b> or disappears.",
3:"The I band (thin filament without thick overlap) <b>narrows</b>.",
4:"Sarcomere length (Z to Z) <b>shortens</b> with contraction."},
eli5="Picture two combs sliding into each other. The teeth don't get shorter, they just overlap more. The A band is the length of the thick comb, so it stays the same, while the gaps (I band, H zone) shrink."),

dict(img=None,
stem="A 66-year-old man with a prior anterior myocardial infarction has echocardiographic measurements of end-diastolic volume 160 mL and end-systolic volume 110 mL. His heart rate is 90/min.{FIG}Which of the following best describes his stroke volume, ejection fraction, and cardiac output?",
choices=["SV 50 mL · EF 31% · CO 4.5 L/min","SV 50 mL · EF 45% · CO 4.5 L/min","SV 50 mL · EF 69% · CO 9.9 L/min","SV 110 mL · EF 69% · CO 9.9 L/min","SV 160 mL · EF 100% · CO 14.4 L/min"], key=0,
exp="• <b>SV = EDV − ESV</b> = 160 − 110 = <b>50 mL</b>.<br>• <b>EF = SV ÷ EDV</b> = 50 ÷ 160 = <b>31%</b> (reduced, normal 55–75%).<br>• <b>CO = SV × HR</b> = 50 mL × 90 = <b>4.5 L/min</b> (normal 4–5).<br>Cardiac output is maintained by a <b>faster rate and a larger EDV</b>, the classic HFrEF compensation after losing myocardium.<br><br><b>Educational objective:</b> SV = EDV − ESV, EF = SV/EDV, and CO = SV × HR. A dilated ventricle with a low EF can maintain CO through a higher rate and preload.",
wrong={1:"45% would come from dividing SV by ESV plus some error. EF uses <b>EDV</b> as the denominator: 50/160 = 31%.",
2:"69% is ESV ÷ EDV (110/160), not EF, and 9.9 L/min uses 110 mL as the stroke volume.",
3:"110 mL is the <b>end-systolic</b> volume, not the stroke volume.",
4:"160 mL is the EDV. The ventricle never ejects all of it."},
eli5="The heart holds 160 mL and still has 110 left after squeezing, so it pushes out only 50 mL per beat. That's about a third of what it holds, which is low. Beating 90 times a minute still moves 4.5 liters."),

dict(img=None,
stem="During vigorous exercise, total peripheral resistance in a healthy man falls to half its resting value as arterioles in skeletal muscle dilate. His mean arterial pressure stays essentially unchanged.{FIG}Which of the following changes must have occurred?",
choices=["Cardiac output decreased by half","Cardiac output doubled","Cardiac output quadrupled","Cardiac output was unchanged","Venous return decreased"], key=1,
exp="<b>MAP = CO × TPR</b>, the equation Dr. Morganelli marked with three exclamation marks. MAP is the <b>dependent</b> variable, and the body adjusts CO and TPR to hold it. If TPR halves and MAP is unchanged, <b>CO must double</b>. The sympathetic system drives heart rate and contractility up, and venomotor tone rises to keep venous return pace with it. At steady state VR = CO, so venous return rises too.<br><br><b>Educational objective:</b> Because MAP = CO × TPR, a halving of TPR with MAP maintained requires cardiac output to double.",
wrong={0:"Halving CO with a halved TPR would <b>quarter</b> MAP.",
2:"Quadrupling CO with a halved TPR would <b>double</b> MAP.",
3:"An unchanged CO with a halved TPR would halve MAP.",
4:"At steady state venous return equals cardiac output, so it must <b>rise</b>."},
eli5="Blood pressure equals the heart's output times the vessels' resistance. If resistance is cut in half and pressure stays the same, the heart must be pumping twice as much."),

dict(img=None,
stem="A 60-year-old man with chronic stable heart failure and a resting sinus rate of 88/min is started on ivabradine, which selectively blocks the \"funny\" current in sinoatrial nodal cells.{FIG}Which of the following best describes the effect of this drug on the SA-node action potential?",
choices=["Faster phase 0 upstroke","Flatter phase 4 slope","Longer phase 2 plateau","More negative threshold potential","Steeper phase 3 repolarization"], key=1,
exp="Pacemaker (slow-response) cells have no true resting potential:<br>• <b>Phase 4</b>: the <b>funny current (If)</b>, a slow inward Na⁺ current activated by <b>hyperpolarization</b>, drifts the cell from about −60 mV toward threshold. <b>Its slope sets the heart rate.</b><br>• Phase 0: Ca²⁺ through L-type channels (threshold about −40 mV).<br>• Phase 3: K⁺ out, whose hyperpolarization switches If back on.<br>Blocking If → a <b>flatter phase 4</b> → threshold is reached later → a <b>slower heart rate</b>. Ivabradine is a board add-on.<br><br><b>Educational objective:</b> The funny current drives phase 4 depolarization in SA-node cells. Blocking it flattens phase 4 and slows the heart rate.",
wrong={0:"The nodal upstroke is L-type Ca²⁺, which If blockade doesn't change.",
2:"Pacemaker cells have no plateau phase. That is a feature of fast-response myocytes.",
3:"Threshold is set by Ca²⁺ channel gating and isn't moved by blocking If.",
4:"Phase 3 is K⁺ repolarization, which is not the drug's target."},
eli5="The pacemaker cells slowly charge up between beats thanks to the funny current, a slow sodium leak. Block that leak and they charge more slowly, so each beat comes later and the heart rate falls."),

dict(img=None,
stem="Electrical stimulation of the right vagus nerve slows the sinoatrial nodal firing rate. Part of the effect is a reduction in the pacemaker currents If and ICa.{FIG}Which of the following is the second mechanism by which acetylcholine slows the SA node?",
choices=["Decreased K⁺ conductance, depolarizing the cell","More K⁺ conductance, hyperpolarizing the cell","Increased Na⁺ conductance through fast channels","Inhibition of the Na⁺/K⁺-ATPase","Stimulation of β1 receptors on nodal cells"], key=1,
exp="Acetylcholine acts on <b>M2</b> receptors (Gi) in the SA node and slows it in <b>two</b> ways:<br>1. <b>↓ If and ↓ ICa</b> → a <b>flatter phase 4</b>.<br>2. <b>↑ K⁺ conductance</b> → the cell <b>hyperpolarizes</b>, so phase 4 starts <b>further from threshold</b>.<br>Both lengthen the time to threshold, so the rate slows and AV conduction slows. Sympathetic NE on β1 does the reverse (↑ If and ICa, steeper phase 4). With no autonomic input (a denervated transplanted heart) the rate is about 100/min, so resting vagal tone normally holds it lower.<br><br><b>Educational objective:</b> Vagal ACh slows the SA node by flattening phase 4 (↓ If, ↓ ICa) and by increasing K⁺ conductance, which hyperpolarizes the cell away from threshold.",
wrong={0:"Decreasing K⁺ conductance would depolarize the cell toward threshold and <b>speed</b> the rate.",
2:"Fast Na⁺ channels aren't active in SA-node cells, and opening them would speed firing.",
3:"Na⁺/K⁺-ATPase inhibition is digoxin's mechanism, not the vagal effect.",
4:"β1 stimulation (sympathetic) <b>speeds</b> the SA node."},
eli5="The vagus nerve's acetylcholine does two things to the pacemaker: it slows the charging leak, and it opens potassium channels that drag the starting voltage further down. Starting lower and charging slower both mean fewer beats per minute."),

dict(img=None,
stem="Unlike skeletal muscle, cardiac muscle cannot be made to contract in a sustained tetanic spasm by rapid repetitive stimulation.{FIG}Which of the following best explains this property?",
choices=["Cardiac myocytes lack troponin C","Cardiac myocytes lack voltage-gated Na⁺ channels","Gap junctions block impulses arriving too early","Na⁺ channels stay inactivated until mid-phase 3","The Na⁺/K⁺-ATPase stops working during systole"], key=3,
exp="The <b>absolute (effective) refractory period</b> runs from phase 0 through about <b>mid-phase 3</b>. During it, most voltage-gated <b>Na⁺ channels are inactivated</b> and cannot reopen, so no new action potential can start. Because the cardiac AP (with its long plateau) lasts about as long as the contraction, the muscle is still refractory until it has begun to relax. That <b>prevents summation and tetany</b> and guarantees time to fill. The relative refractory period (late phase 3) is when a strong premature stimulus can fire the cell and start an arrhythmia.<br><br><b>Educational objective:</b> The long absolute refractory period of cardiac muscle, with Na⁺ channels inactivated until mid-phase 3, prevents summation and tetany and preserves filling time.",
wrong={0:"Cardiac muscle does use troponin C. It is essential for contraction.",
1:"Fast voltage-gated Na⁺ channels drive the cardiac myocyte upstroke (phase 0).",
2:"Gap junctions pass impulses between cells rapidly. They don't block early impulses.",
4:"The Na⁺/K⁺-ATPase keeps running. It restores gradients during phases 3–4."},
eli5="After each beat, the heart cell's sodium channels are locked shut until the muscle has mostly relaxed. So a new signal can't sneak in and cause a cramp-like, non-stop contraction. The heart always gets time to refill."),

dict(img='pvloop', cap='Left ventricular pressure–volume loop (segments a–d)',
stem="A normal left ventricular pressure–volume loop is shown.{FIG}During the segment labeled b, which of the following is true?",
choices=["Aortic valve open, mitral valve closed, volume falling","Aortic valve closed, mitral valve open, volume rising","Both valves closed, pressure falling, volume constant","Both valves closed, pressure rising, volume constant","Both valves open, volume unchanged"], key=3,
exp="Read the loop counter-clockwise from mitral valve opening:<br>• <b>a, filling</b>: the mitral valve is open and volume rises with only a small pressure rise.<br>• <b>b, isovolumic contraction</b>: starts at mitral closure (EDV, S1). <b>Both valves are closed</b>, so pressure rises straight up while <b>volume is unchanged</b>.<br>• <b>c, ejection</b>: the aortic valve opens and volume falls.<br>• <b>d, isovolumic relaxation</b>: starts at aortic closure (ESV, S2). Both valves are closed, pressure falls and volume is constant.<br>Loop width = stroke volume.<br><br><b>Educational objective:</b> Segment b of the PV loop is isovolumic contraction: both valves are closed, pressure rises and volume stays constant.",
wrong={0:"Aortic valve open with falling volume is <b>ejection (c)</b>.",
1:"Mitral open with rising volume is <b>filling (a)</b>.",
2:"Both valves closed with <b>falling</b> pressure is <b>isovolumic relaxation (d)</b>.",
4:"Both valves are never open at once in a normal heart."},
eli5="Segment b is the moment the ventricle squeezes with both doors shut. The pressure shoots up, but no blood can go anywhere yet, so the volume stays the same until the aortic door opens."),

dict(img=None,
stem="While auscultating a healthy volunteer, a student times the second heart sound (S2).{FIG}Which phase of the cardiac cycle immediately follows S2?",
choices=["Atrial contraction","Isovolumic contraction","Isovolumic relaxation","Rapid ventricular filling","Ventricular ejection"], key=2,
exp="<b>S2</b> = <b>aortic (and pulmonic) valve closure</b>, when ventricular pressure falls below arterial pressure. The next phase is <b>isovolumic relaxation</b> (early diastole): the semilunar valves are shut and the AV valves are still closed, so pressure falls with no change in volume and no filling. Once ventricular pressure drops below atrial pressure, the AV valves open → rapid filling. <b>S1</b> = AV valve closure → isovolumic contraction.<br><br><b>Educational objective:</b> S2 marks semilunar valve closure and is followed by isovolumic relaxation, before the AV valves open for filling.",
wrong={0:"Atrial contraction comes at the <b>end</b> of diastole, just before S1.",
1:"Isovolumic contraction follows <b>S1</b> (AV valve closure).",
3:"Rapid filling begins only after isovolumic relaxation, when the AV valves open.",
4:"Ejection happens between the aortic valve opening and S2, not after it."},
eli5="The second heart sound is the aortic door slamming shut. Right after, the ventricle relaxes with both doors closed for a moment. Only then does the mitral door open and let blood flow in."),

dict(img='Upreup', cap='Left ventricular pressure–volume loops',
stem="A healthy volunteer receives a rapid 1-L intravenous infusion of normal saline. Left ventricular pressure–volume loops are recorded before and after the infusion. " + LOOPKEY + "{FIG}Which of the following best explains the change?",
choices=["Decreased afterload","Decreased preload","Increased afterload","Increased contractility","Increased preload"], key=4,
exp="The dashed loop extends <b>to the right</b>: EDV rises, while ESV and the ESPVR are unchanged, so the loop is <b>wider</b> with a <b>larger stroke volume</b>. That is <b>increased preload</b>. A fluid bolus raises venous return → more filling → more sarcomere stretch → more cross-bridge overlap → a stronger contraction (<b>Starling's law</b>). Preload's indices are EDV and EDP.<br><br><b>Educational objective:</b> Increased preload (a fluid bolus) shifts the right side of the PV loop to a larger EDV, widening the loop and raising stroke volume by the Frank–Starling mechanism.",
wrong={0:"Decreased afterload makes the loop <b>shorter</b> and extends it to the <b>left</b> (lower ESV).",
1:"Decreased preload moves the right side <b>leftward</b> (smaller EDV, narrower loop).",
2:"Increased afterload makes the loop <b>taller and narrower</b>, with ESV rising.",
3:"Increased contractility steepens the ESPVR and extends the loop <b>left</b> (lower ESV) at the same EDV."},
eli5="More fluid in the veins means the heart fills more before each beat, so the loop stretches to the right. A fuller heart squeezes harder (Starling's law), so it pushes out more blood per beat."),

dict(img='Uafter', cap='Left ventricular pressure–volume loops',
stem="A healthy volunteer receives an intravenous infusion of phenylephrine, which raises aortic diastolic pressure. Heart rate is held constant with pacing, and contractility and venous return do not change. " + LOOPKEY + "{FIG}Which of the following best describes the effect on this beat?",
choices=["↑ Afterload · ↑ ESV · ↓ SV","↑ Afterload · ↓ ESV · ↑ SV","↑ Contractility · ↓ ESV · ↑ SV","↑ Preload · ↑ EDV · ↑ SV","↓ Afterload · ↓ ESV · ↑ SV"], key=0,
exp="The dashed loop is <b>taller</b> (higher systolic pressure) and <b>narrower</b>: ejection stops at a <b>larger ESV</b> while EDV is unchanged, so <b>SV falls</b>. That is <b>increased afterload</b>. Aortic diastolic pressure is a major determinant of afterload. The ventricle must build more pressure before the aortic valve opens, leaving less energy for ejection. This is the same pattern as the class question on long-standing hypertension (pick the taller, narrower loop). Over the next beats, the larger ESV raises EDV.<br><br><b>Educational objective:</b> Increased afterload makes the PV loop taller and narrower, with a higher ESV and a lower stroke volume.",
wrong={1:"Increased afterload <b>raises</b> ESV and <b>lowers</b> SV.",
2:"Increased contractility extends the loop to a <b>lower</b> ESV. This loop's ESV is higher.",
3:"EDV (the right edge) is unchanged, so preload didn't rise.",
4:"Decreased afterload gives a shorter, wider loop, which is the opposite."},
eli5="Phenylephrine tightens the arteries, so the ventricle has to push harder to open the aortic valve. Pressure goes up, but less blood gets out before it runs out of steam. The loop gets taller and skinnier."),

dict(img=None,
stem="A 78-year-old woman with long-standing hypertension has exertional dyspnea. Echocardiography shows a thick-walled left ventricle with a small cavity. Pressure–volume analysis shows a much steeper end-diastolic pressure–volume relationship than normal, with an unchanged end-systolic pressure–volume relationship.{FIG}Which of the following sets of changes is most likely?",
choices=["EDV ↑ · SV ↓ · EF ↓","EDV ↑ · SV ↑ · EF ↑","EDV ↓ · SV ↓ · EF preserved","EDV ↓ · SV ↑ · EF ↑","EDV unchanged · SV ↓ · EF ↓"], key=2,
exp="A steep <b>EDPVR</b> means a stiff, noncompliant ventricle. It fills to a <b>smaller EDV</b> at a <b>higher end-diastolic pressure</b>. Contractility (the ESPVR) is unchanged → <b>HFpEF</b> (diastolic failure). <b>SV falls because EDV falls</b>, but the <b>EF is preserved</b>, because the ventricle ejects a normal fraction of its (smaller) volume. (In the recording Dr. Morganelli slipped and said \"reduced EF\". The slide is right: EF is preserved.) Contrast <b>HFrEF</b>: a flatter ESPVR, ↑ ESV and ↑ EDV (dilation), ↓ SV and ↓ EF.<br><br><b>Educational objective:</b> In HFpEF a stiff ventricle (steep EDPVR) fills to a smaller EDV at higher pressure, so SV falls while EF is preserved.",
wrong={0:"↑ EDV with ↓ SV and ↓ EF is <b>HFrEF</b> (↓ contractility, a dilated ventricle).",
1:"Everything rising would fit increased preload in a healthy heart, not a stiff ventricle.",
3:"A smaller EDV can't raise SV when contractility is unchanged.",
4:"EDV <b>falls</b> with a steep EDPVR, and EF is preserved rather than reduced."},
eli5="Her heart wall is so thick and stiff it can't stretch to fill. With less blood inside, each beat pushes out less. But it still squeezes out the normal share of what it holds, so the ejection fraction looks normal."),

dict(img='pvAR', cap='Left ventricular pressure–volume loops: normal (dotted outline) and patient (shaded)',
stem="A 58-year-old man has exertional dyspnea and a wide pulse pressure (blood pressure 164/48 mm Hg). His left ventricular pressure–volume loop (shaded) is compared with a normal loop (dotted outline).{FIG}Which of the following is the most likely diagnosis?",
choices=["Aortic regurgitation","Aortic stenosis","Hypertrophic cardiomyopathy","Mitral regurgitation","Mitral stenosis"], key=0,
exp="The shaded loop shows a <b>huge EDV</b> (the ventricle refills from the leaking aortic valve during diastole as well as from the mitral valve), a very large stroke volume, and <b>no true isovolumic relaxation</b>: pressure and volume change together from the start of diastole, because blood flows back in as soon as ejection stops. With a <b>wide pulse pressure</b> (high systolic, low diastolic) this is <b>aortic regurgitation</b>. This is a board add-on to the lecture, since valve-lesion loops appear on boards.<br><br><b>Educational objective:</b> Aortic regurgitation produces a PV loop with a markedly increased EDV, a large stroke volume, and no true isovolumic relaxation, with a wide pulse pressure.",
wrong={1:"Aortic stenosis gives a very <b>tall</b> loop (very high systolic pressure) with ↓ SV, not a huge EDV with a low diastolic pressure.",
2:"Hypertrophic cardiomyopathy gives a stiff, small ventricle: a small EDV with a steep filling curve.",
3:"Mitral regurgitation also loses the isovolumic phases, but it shows a rounded loop with <b>↓ ESV</b>, and the pulse pressure isn't wide.",
4:"Mitral stenosis <b>under</b>-fills the ventricle (small EDV)."},
eli5="A leaky aortic valve lets blood fall back into the ventricle after each beat, so the ventricle ends up hugely overfilled. It pumps a big volume forward, much of which leaks back. That makes the loop very wide, with high top and low bottom pressures."),

dict(img=None,
stem="Vasospasm reduces the radius of an arteriole to one-half its normal value. Blood viscosity, vessel length, and the pressure gradient across the arteriole do not change.{FIG}Flow through the arteriole will change to approximately what fraction of normal?",
choices=["1/2","1/4","1/8","1/16","1/32"], key=3,
exp="<b>Poiseuille</b>: Q = ΔP·π·r⁴ / 8ηl, so <b>R = 8ηl / πr⁴</b>. <b>Radius dominates</b> (to the 4th power): halving r → (½)⁴ = 1/16 → resistance rises 16-fold → at a constant ΔP, <b>flow falls to 1/16</b>. Doubling the radius raises flow 16-fold. That is why small changes in arteriolar tone control organ blood flow so powerfully. Viscosity depends mostly on hematocrit (↑ in dehydration and polycythemia).<br><br><b>Educational objective:</b> Resistance varies inversely with radius to the fourth power, so halving vessel radius reduces flow to about 1/16 at a constant pressure gradient.",
wrong={0:"1/2 treats flow as proportional to r, but it scales with r⁴.",
1:"1/4 squares the radius (r²) instead of raising it to the fourth power.",
2:"1/8 cubes the radius. Poiseuille uses the fourth power.",
4:"1/32 overshoots. (½)⁴ = 1/16."},
eli5="Blood flow depends enormously on how wide the vessel is, to the fourth power. Squeeze the width in half and flow drops to one-sixteenth. That's why tiny changes in small arteries control blood flow so strongly."),

dict(img=None,
stem="A student compares the average velocity of blood flow in different segments of the systemic circulation at rest.{FIG}In which segment is the average flow velocity lowest?",
choices=["Aorta","Arterioles","Capillaries","Large veins","Venae cavae"], key=2,
exp="<b>Law of continuity</b>: Q = A × v, and the flow rate is the same through each segment in series. So <b>velocity is lowest where the total cross-sectional area is largest</b>. The <b>capillary network</b> has by far the largest total area (about 3,000 cm² versus about 4 cm² for the aorta), so velocity falls to about <b>0.03 cm/s</b>, which gives time for gas and nutrient exchange. Velocity rises again as area shrinks on the venous side. The trap: a single capillary is tiny, but the question is about the whole network.<br><br><b>Educational objective:</b> Flow velocity is inversely proportional to total cross-sectional area, so it is lowest in the capillaries, which have the largest combined area.",
wrong={0:"The aorta has the <b>smallest</b> total cross-section and the highest velocity.",
1:"Arterioles have the greatest <b>pressure drop</b> (resistance), but capillaries have the largest total area and the lowest velocity.",
3:"Large veins have a smaller total area than the capillary bed, so velocity rises again.",
4:"The venae cavae have a small total area and relatively high velocity."},
eli5="The same amount of blood has to pass through every part of the circulation each minute. Where the total width is biggest, the capillary bed, the blood can move slowest. That gives oxygen time to get into the tissues."),

dict(img=None,
stem="In an experimental animal, the heart is stopped and blood flow ceases. After pressures throughout the circulation equalize, a pressure of 8 mm Hg is recorded everywhere.{FIG}This pressure is determined mainly by which of the following?",
choices=["Aortic diastolic pressure","Cardiac contractility","Right atrial pressure during systole","Stressed volume and venous compliance","Total peripheral (arteriolar) resistance"], key=3,
exp="That equalized no-flow pressure is the <b>mean systemic filling pressure (Pmsf)</b>, about 7–8 mm Hg. It is set by the <b>stressed volume</b>: blood <b>above</b> the unstressed volume, which actually stretches vessel walls and creates pressure. Stressed volume depends on <b>total blood volume</b> and <b>venous compliance</b> (venomotor tone). Unstressed volume just fills the vessels without pressure (the air-mattress analogy). Pmsf is the main upstream push for venous return: <b>VR = (Pv − Pra)/Rv</b>, where Pv is mostly Pmsf.<br><br><b>Educational objective:</b> Mean systemic filling pressure is the circulatory pressure with no flow, set by the stressed volume, which depends on blood volume and venous compliance.",
wrong={0:"Aortic diastolic pressure disappears when the heart stops. Pmsf is the equalized pressure.",
1:"Contractility affects flow, not the pressure left when flow has stopped.",
2:"There is no systole when the heart is stopped. Right atrial pressure then equals Pmsf.",
4:"TPR rotates the cardiac and vascular curves but doesn't set the no-flow pressure (a board add-on)."},
eli5="Stop the heart and let everything settle, and the leftover pressure depends on how full and how tight the blood vessels are. That's the extra blood that actually stretches the walls, called stressed volume. That settled pressure is what pushes blood back to the heart."),

dict(img='guytonHF', cap='Cardiac output versus central venous pressure: cardiac function curves and vascular function curves',
stem="A patient with moderate heart failure is operating at point B. Over the next several days, sympathetic activation and renal salt and water retention expand her blood volume.{FIG}Her new operating point is most likely which of the following?",
choices=["A","B","C","D","E"], key=3,
exp="On a Guyton graph, the operating point is where the <b>cardiac function curve</b> meets the <b>vascular function curve</b>. Moderate heart failure (↓ contractility) drops the cardiac curve, so at normovolemia the patient sits at <b>B</b>: a lower CO and higher CVP than normal (A). The compensation is sympathetic venomotor tone plus fluid retention → ↑ stressed volume → ↑ Pmsf → the <b>vascular curve shifts right</b> (hypervolemia). The new crossing on the <b>same moderate-HF cardiac curve</b> is <b>D</b>: CO partly restored, at an even <b>higher CVP</b>. A transfusion does the same thing. E is the serious-failure curve after volume expansion.<br><br><b>Educational objective:</b> In heart failure, volume expansion shifts the vascular function curve right, restoring some cardiac output at the cost of a higher central venous pressure.",
wrong={0:"A is the normal heart at normal volume.",
1:"B is her current point, before volume expansion.",
2:"C is <b>serious</b> heart failure at normal volume.",
4:"E is serious heart failure after volume expansion, not moderate."},
eli5="Her weak heart keeps fluid to boost the pressure pushing blood back to it. That lets it pump a bit more, but her vein pressure goes even higher, which causes swelling. On the graph she moves from B up to D."),

dict(img=None,
stem="A 52-year-old woman with non-ischemic dilated cardiomyopathy (ejection fraction 30%) has hypotension, tachycardia, raised jugular venous pressure, bibasilar crackles, 2+ pitting edema, and low urine output. Serum sodium is 126 mEq/L, blood urea nitrogen and creatinine are increased, and urine sodium is very low.{FIG}Which of the following best explains her low serum sodium?",
choices=["Excess natriuretic peptide causing renal sodium loss","Excessive water retention relative to sodium","Loss of total body sodium through the kidneys","Primary polydipsia","Sodium loss through the gastrointestinal tract"], key=1,
exp="This is the lecture's last class question, and the <b>heart-failure paradox</b>. Venous pressures are high (the volume reflex would dump salt and water), but the arterial side is <b>underfilled</b> (hypotension, poor renal perfusion). So the <b>pressure-defending systems win</b>:<br>• <b>RAAS</b> → aldosterone holds on to Na⁺, which is why <b>urine Na⁺ is so low</b>.<br>• <b>ADH</b> adds <b>water retention without sodium</b>.<br>Water is retained <b>out of proportion to salt</b> → <b>dilutional hyponatremia</b>, even though total body sodium and volume are <b>high</b> (edema, JVD).<br><br><b>Educational objective:</b> Hyponatremia in decompensated heart failure is dilutional: RAAS and ADH, driven by arterial underfilling, retain water in excess of sodium despite total body sodium overload.",
wrong={0:"Natriuretic peptides are high in heart failure, but they are overwhelmed. Her very low urine Na⁺ shows avid sodium retention, not loss.",
2:"Total body sodium is <b>increased</b> (edema). The kidneys are retaining, not losing, sodium.",
3:"Nothing suggests excessive water drinking. The mechanism is hormonal water retention.",
4:"There is no vomiting or diarrhea, and her urine Na⁺ reflects renal retention."},
eli5="Her weak heart can't keep her arteries full, so her body thinks it's low on fluid. It releases hormones to hold onto salt and even more water. The extra water dilutes the sodium, even though she's actually overloaded with both."),
]
