# Cardiac Physiology Review (Morganelli) — Version 2, 18 items (7 with images)
LOOPKEY = "In the figure, the solid loop was recorded at baseline and the dashed loop after the change."
Q = [
dict(img=None,
stem="A researcher compares excitation–contraction coupling in isolated skeletal and ventricular muscle fibers. Removing extracellular Ca²⁺ abolishes contraction in the ventricular fibers within seconds but has little immediate effect on the skeletal fibers.{FIG}Which of the following best explains this difference?",
choices=["Cardiac contraction needs Ca²⁺ to bind tropomyosin directly","Cardiac myocytes lack a sarcoplasmic reticulum","Cardiac SR release is triggered by L-type Ca²⁺ entry","Skeletal muscle uses myosin light-chain kinase to contract","Skeletal SR release is triggered by extracellular Ca²⁺ binding troponin"], key=2,
exp="• <b>Skeletal muscle</b>: <b>depolarization-induced Ca²⁺ release</b>. The voltage sensor (the dihydropyridine receptor) is mechanically linked to the SR release channel and pulls it open directly, so extracellular Ca²⁺ isn't needed.<br>• <b>Cardiac muscle</b>: <b>Ca²⁺-induced Ca²⁺ release</b>. Ca²⁺ entering through <b>L-type channels during the plateau (phase 2)</b> opens <b>ryanodine receptors (RyR2)</b> on the SR, which release the bulk of the Ca²⁺. No extracellular Ca²⁺ means no trigger, so no contraction.<br>Relaxation (a board add-on): SERCA pumps Ca²⁺ back into the SR, and the Na⁺/Ca²⁺ exchanger pushes it out of the cell.<br><br><b>Educational objective:</b> Cardiac excitation–contraction coupling is Ca²⁺-induced Ca²⁺ release, in which L-type channel Ca²⁺ triggers RyR2. Skeletal muscle uses depolarization-induced release, independent of extracellular Ca²⁺.",
wrong={0:"Ca²⁺ binds <b>troponin C</b>, never tropomyosin, in either muscle type.",
1:"Cardiac myocytes have an SR. It supplies most of the contractile Ca²⁺.",
3:"MLCK activation is how <b>smooth</b> muscle contracts, not skeletal.",
4:"Skeletal SR release is voltage-triggered (mechanical coupling), not triggered by extracellular Ca²⁺."},
eli5="In heart muscle, a small puff of calcium from outside the cell is the spark that makes the cell's internal store release its big supply. Take away outside calcium and there's no spark. Skeletal muscle opens its store directly with an electrical signal, so it doesn't need that spark."),

dict(img=None,
stem="A student notes that increasing ventricular filling increases the force of the next cardiac contraction, whereas passively stretching a skeletal muscle in the body beyond its resting length decreases the force it can generate.{FIG}Which of the following best explains this difference?",
choices=["Cardiac muscle works on the ascending length–tension limb","Cardiac muscle relies on tetanic summation to increase force","Skeletal muscle cannot form cross-bridges when stretched at all","Skeletal muscle has no troponin to sense stretch","Stretch increases extracellular Ca²⁺ entry into skeletal muscle"], key=0,
exp="Force depends on <b>thin–thick filament overlap</b> (how many cross-bridges can form). <b>Skeletal muscle</b> in the body already sits near <b>maximal overlap</b>, so stretching it further pulls the filaments apart and force falls. <b>Cardiac muscle</b> works on the <b>ascending limb</b> of the length–tension curve, so more filling → more stretch → more overlap → more force. This is <b>Starling's law</b>: preload (EDV, EDP) sets sarcomere length, called \"heterometric\" regulation.<br><br><b>Educational objective:</b> Cardiac muscle operates on the ascending limb of the length–tension curve, so increased preload raises force (Frank–Starling), whereas skeletal muscle already sits at optimal overlap.",
wrong={1:"Cardiac muscle <b>cannot</b> tetanize, because its long refractory period prevents summation.",
2:"Stretched skeletal muscle still forms cross-bridges, just fewer, because overlap falls.",
3:"Skeletal muscle has troponin. Troponin senses Ca²⁺, not stretch.",
4:"Stretch doesn't raise Ca²⁺ entry in skeletal muscle."},
eli5="Heart muscle normally sits a little short of its best stretch, so filling it more lines up its gripping parts better and makes it stronger. Skeletal muscle already sits at its best stretch, so pulling it further lines them up worse and weakens it."),

dict(img=None,
stem="A 25-year-old runner's cardiac output rises from 5 to 20 L/min during a race while his mean arterial pressure rises only slightly.{FIG}Blood flow to which of the following organs most likely decreases in absolute terms during the race?",
choices=["Brain","Heart","Kidneys","Skeletal muscle","Skin"], key=2,
exp="MAP = CO × TPR. During exercise the <b>same pressure is redistributed</b>: heart, skin (heat loss) and skeletal-muscle flow rise a lot, and brain flow stays about constant. <b>Splanchnic (gut) and renal flow fall</b>, which helps defend pressure through sympathetic vasoconstriction. Exercise that is too hard or too long can drop gut flow enough to cause injury. At rest the kidneys get about 22% of cardiac output, but they can spare it briefly.<br><br><b>Educational objective:</b> During exercise, flow to working muscle, heart and skin rises, cerebral flow is constant, and splanchnic and renal flow fall.",
wrong={0:"Cerebral flow is autoregulated and stays about <b>constant</b>.",
1:"Coronary flow <b>rises</b> to match the heart's increased work.",
3:"Skeletal muscle flow <b>rises enormously</b>, which is the purpose of exercise.",
4:"Skin flow <b>rises</b> to dump heat (unless extreme strain overrides it)."},
eli5="During a race the body sends blood where it's needed: muscles, heart and skin. The gut and kidneys can wait, so their share gets turned down. The brain keeps its steady supply."),

dict(img=None,
stem="Three vascular beds with resistances of 2, 4, and 4 peripheral resistance units are arranged in parallel between the same arterial and venous pressures.{FIG}What is the total resistance of the three beds?",
choices=["0.5 units","1 unit","2 units","4 units","10 units"], key=1,
exp="Resistances in <b>parallel</b>: 1/R<sub>T</sub> = 1/R₁ + 1/R₂ + 1/R₃ = 1/2 + 1/4 + 1/4 = 1 → <b>R<sub>T</sub> = 1 unit</b>, lower than any single bed. Resistances in <b>series</b> add (R<sub>T</sub> = R₁ + R₂ + R₃ = 10). Small arteries, arterioles and capillaries are arranged in parallel, which is why a capillary network offers little total resistance even though each capillary is very resistant. Adding a parallel vessel lowers total resistance, and adding one in series raises it. Dr. Morganelli saw a board question that made you calculate this.<br><br><b>Educational objective:</b> Parallel resistances combine as 1/R<sub>T</sub> = Σ1/R, so total resistance is lower than any individual branch. Series resistances add.",
wrong={0:"0.5 would need the reciprocals to sum to 2. They sum to 1.",
2:"2 is the smallest single resistance. The parallel total must be <b>below</b> it.",
3:"4 is one bed's resistance, not the combined value.",
4:"10 is the <b>series</b> sum (2 + 4 + 4)."},
eli5="When blood can take several paths side by side, it's easier to get through than any single path, like opening more checkout lanes. Add the lanes' 'ease' (1/R): a half plus a quarter plus a quarter makes 1. So the total resistance is 1."),

dict(img=None,
stem="A 40-year-old man is seen 6 months after orthotopic heart transplantation. The donor heart has no autonomic innervation. He is resting comfortably and afebrile.{FIG}Which of the following resting heart rates is most likely?",
choices=["45/min","60/min","75/min","100/min","140/min"], key=3,
exp="The SA node fires <b>automatically</b>, with no nerve input needed. At rest, <b>vagal tone</b> (ACh on M2 → flatter phase 4 and hyperpolarization) holds the rate down to about 60–90. With <b>no autonomic input at all</b>, as in a denervated transplanted heart, the intrinsic SA rate is about <b>100/min</b>. Denervated hearts also speed up slowly with exercise, relying on circulating catecholamines and Starling's law rather than nerves.<br><br><b>Educational objective:</b> The intrinsic SA-node rate without autonomic input is about 100/min. Resting vagal tone normally holds the rate lower, so a denervated heart rests near 100.",
wrong={0:"45/min would be a vagally dominated or diseased node, and there is no vagal input here.",
1:"60/min is a typical rate <b>with</b> resting vagal tone.",
2:"75/min is a typical innervated resting rate.",
4:"140/min would need sympathetic or catecholamine drive, and he is at rest."},
eli5="The heart's pacemaker ticks by itself at about 100 beats a minute. Normally the vagus nerve gently holds it back to 60–80. A transplanted heart has no vagus nerve attached, so it rests near its natural 100."),

dict(img=None,
stem="A 30-year-old woman develops a narrow-complex supraventricular tachycardia at 200/min. Her blood pressure falls from 118/76 to 82/54 mm Hg, and she becomes lightheaded.{FIG}Which of the following best explains the fall in blood pressure despite the faster heart rate?",
choices=["Decreased afterload from arterial dilation","Decreased contractility from ischemic myocytes","Increased stroke volume overwhelming the aorta","Shortened filling time lowering stroke volume","Vagal activation causing systemic vasodilation"], key=3,
exp="CO = SV × HR, but faster isn't always more output. At about <b>200/min</b>, <b>diastole</b> (when the ventricles fill) becomes too short. EDV falls → by Starling's law, <b>stroke volume collapses</b> → the drop in SV outweighs the rise in HR → <b>CO and MAP fall</b>. Coronary perfusion (which happens in diastole) also suffers. The ~0.1-s AV-node delay normally protects filling time.<br><br><b>Educational objective:</b> At very fast rates, shortened diastole reduces ventricular filling and stroke volume enough that cardiac output and blood pressure fall.",
wrong={0:"Arterial dilation isn't the mechanism, and SVT tends to trigger sympathetic <b>vaso</b>constriction.",
1:"Ischemia can follow later, but the immediate problem is too little filling time.",
2:"Stroke volume <b>falls</b> in SVT, and aortic capacity isn't the issue.",
4:"Hypotension raises sympathetic tone. It doesn't trigger vagal vasodilation."},
eli5="When the heart beats 200 times a minute, it doesn't get enough time between beats to fill up. Each beat pushes out very little blood, so even with more beats the total output drops and blood pressure falls."),

dict(img='Uino', cap='Left ventricular pressure–volume loops',
stem="A healthy volunteer receives an intravenous infusion of dobutamine. Preload and afterload are held constant. " + LOOPKEY + "{FIG}Which of the following best explains the change?",
choices=["Decreased afterload","Decreased compliance","Increased afterload","Increased contractility","Increased preload"], key=3,
exp="The dashed loop has the <b>same EDV</b> (right edge) but extends <b>to the left</b>: ejection continues to a <b>smaller ESV</b>, so <b>SV rises</b>, with a slightly higher peak pressure. That is <b>increased contractility (inotropy)</b>: a <b>steeper ESPVR</b>, so at any preload and afterload the ventricle empties more. Dobutamine (β1 → cAMP) raises intracellular Ca²⁺ and cross-bridge cycling. The best measure of contractility is max dP/dt during isovolumic contraction.<br><br><b>Educational objective:</b> Increased contractility steepens the ESPVR and extends the PV loop leftward (lower ESV, higher SV) at the same EDV.",
wrong={0:"Decreased afterload also lowers ESV, but the loop becomes <b>shorter</b> (lower systolic pressure). Here the peak rises slightly, and afterload was held constant.",
1:"Decreased compliance steepens the <b>filling</b> curve and lowers EDV.",
2:"Increased afterload <b>raises</b> ESV (a taller, narrower loop).",
4:"Increased preload moves the <b>right</b> edge (EDV) rightward."},
eli5="Dobutamine makes the heart squeeze harder. It starts with the same amount of blood but squeezes more of it out, so the loop stretches to the left. More blood pumped per beat."),

dict(img='Upredown', cap='Left ventricular pressure–volume loops',
stem="A 34-year-old man loses about 800 mL of blood from a femoral artery laceration. Heart rate is held constant for the purpose of the recording, and contractility is unchanged. " + LOOPKEY + "{FIG}Which of the following best explains the change?",
choices=["Decreased afterload","Decreased contractility","Decreased preload","Increased afterload","Increased contractility"], key=2,
exp="The dashed loop's <b>right edge moves left</b> (a <b>smaller EDV</b>) with ESV about unchanged → the loop is <b>narrower</b>, with a smaller <b>stroke volume</b> and slightly lower systolic pressure. That is <b>decreased preload</b>: hemorrhage lowers blood volume → lower stressed volume and Pmsf → less venous return → less filling → less sarcomere stretch → smaller SV (Starling). Venodilators such as nitroglycerin do the same. The acute defense is sympathetic venoconstriction (mobilizing the venous reservoir), tachycardia and vasoconstriction, then RAAS and ADH.<br><br><b>Educational objective:</b> Decreased preload (hemorrhage, venodilation) moves the PV loop's right edge leftward, narrowing the loop and lowering stroke volume.",
wrong={0:"Decreased afterload extends the loop to a <b>lower ESV</b> (left edge), not a smaller EDV.",
1:"Decreased contractility flattens the ESPVR and <b>raises</b> ESV.",
3:"Increased afterload makes the loop taller, with a higher ESV.",
4:"Increased contractility lowers ESV at the same EDV."},
eli5="Losing blood means less comes back to the heart, so it starts each beat less full and the loop shrinks from the right. With less stretch, the heart pushes out less blood per beat."),

dict(img='Uex', cap='Left ventricular pressure–volume loops',
stem="A healthy 22-year-old man's left ventricular pressure–volume loop is recorded at rest and again during moderate upright exercise. " + LOOPKEY + "{FIG}Which of the following combinations best explains the dashed loop?",
choices=["↑ Afterload with no other change","↑ Contractility and ↑ venous return","↓ Contractility and ↑ afterload","↓ Preload and ↓ afterload","↓ Venous return only"], key=1,
exp="The dashed loop is <b>wider on both sides</b> (<b>larger EDV</b> and <b>smaller ESV</b>) and <b>taller</b> → a much larger stroke volume. In exercise:<br>• sympathetic <b>↑ inotropy</b> (a steeper ESPVR → lower ESV) and ↑ HR;<br>• <b>↑ venomotor tone</b> (↓ venous compliance → ↑ stressed volume → ↑ Pmsf) plus the muscle pump → <b>↑ venous return</b> → higher EDV;<br>• arteriolar dilation in muscle, skin and heart → TPR falls sharply.<br>Both the cardiac and the vascular function curves must move for CO to rise from about 5 to over 20 L/min.<br><br><b>Educational objective:</b> In exercise the PV loop widens in both directions (↑ EDV from greater venous return, ↓ ESV from greater contractility), producing a large rise in stroke volume.",
wrong={0:"Afterload alone would make the loop taller but <b>narrower</b> (a higher ESV).",
2:"Less contractility plus more afterload would <b>shrink</b> stroke volume.",
3:"Less preload would move EDV <b>left</b>. Here it moves right.",
4:"Less venous return would lower EDV and SV."},
eli5="During exercise the heart fills more, because the veins squeeze more blood back, and also squeezes harder, so it empties more. The loop grows on both sides and each beat moves much more blood."),

dict(img='Uavf', cap='Left ventricular pressure–volume loops',
stem="A 58-year-old man has a large surgically created arteriovenous fistula in his arm for hemodialysis. The solid loop was recorded before the fistula was created and the dashed loop after.{FIG}Which of the following sets of changes best explains the dashed loop?",
choices=["↑ Afterload · ↓ preload","↑ Afterload · ↑ preload","↓ Afterload · ↓ preload","↓ Afterload · ↑ preload","No change in load; ↑ contractility"], key=3,
exp="An <b>arteriovenous (AV) shunt</b> lets arterial blood bypass the high-resistance arterioles and pour straight into the veins:<br>• <b>↓ TPR → ↓ afterload</b>, so the loop is <b>shorter</b> (lower systolic pressure) and ejects to a <b>smaller ESV</b>;<br>• more blood returns directly to the right heart → <b>↑ venous return → ↑ preload</b>, so the loop's <b>right edge moves right</b> (larger EDV).<br>Result: a wider, shorter loop with a much larger SV (high-output state). On the Guyton graph, a lower TPR (exercise, AV shunt) rotates both curves up with the same Pmsf, which is a board add-on.<br><br><b>Educational objective:</b> An arteriovenous fistula lowers afterload (↓ TPR) and raises preload (↑ venous return), producing a shorter, wider PV loop with a larger stroke volume.",
wrong={0:"A fistula <b>lowers</b> resistance and <b>raises</b> venous return, which is the opposite of both.",
1:"Afterload falls with the shunt. The loop is shorter, not taller.",
2:"Preload rises. EDV moves right.",
4:"The loop's shape reflects load changes (lower pressure, larger EDV), not a pure inotropic shift."},
eli5="The fistula is a shortcut from artery to vein, so blood skips the tight small arteries. The heart pushes against less resistance, and more blood rushes back to fill it. So it fills more and empties more easily."),

dict(img='Unitro', cap='Left ventricular pressure–volume loops',
stem="A 70-year-old man with a hypertensive emergency receives an infusion of sodium nitroprusside, which dilates both arterioles and veins. " + LOOPKEY + "{FIG}Which of the following best describes the dashed loop compared with baseline?",
choices=["EDV ↑ · ESV ↑ · peak pressure ↑","EDV ↑ · ESV ↓ · peak pressure ↓","EDV ↓ · ESV ↓ · peak pressure ↓","EDV ↓ · ESV ↑ · peak pressure ↑","EDV unchanged · ESV ↓ · peak pressure ↑"], key=2,
exp="Nitroprusside (NO → cGMP) is a <b>balanced</b> vasodilator:<br>• <b>venodilation</b> → ↑ venous capacitance → ↓ venous return → <b>↓ preload (smaller EDV)</b>, so the right edge moves left;<br>• <b>arteriolar dilation</b> → ↓ TPR → <b>↓ afterload</b>, so the loop is <b>shorter</b> (lower peak pressure) and ejects to a <b>smaller ESV</b>.<br>The whole loop shifts <b>down and to the left</b>. Contrast pure afterload reduction (EDV about the same, loop extends left) and pure venodilation (EDV falls, narrower loop).<br><br><b>Educational objective:</b> Nitroprusside reduces both preload and afterload, shifting the PV loop down and to the left with lower EDV, ESV and systolic pressure.",
wrong={0:"Everything rising describes increased afterload plus preload (volume and vasoconstriction), which is the opposite of a vasodilator.",
1:"A larger EDV with a lower ESV and lower pressure is the <b>AV fistula</b> pattern (↓ afterload, ↑ preload). Nitroprusside <b>lowers</b> EDV.",
3:"A smaller EDV with a higher ESV and higher pressure doesn't fit any vasodilator.",
4:"An unchanged EDV with a lower ESV and <b>higher</b> pressure suggests increased contractility."},
eli5="Nitroprusside relaxes both the arteries and the veins. Relaxed veins hold more blood, so less comes back to fill the heart. Relaxed arteries are easier to push against. The loop gets smaller and lower, shifting left and down."),

dict(img='pvAS', cap='Left ventricular pressure–volume loops: normal (dotted outline) and patient (shaded)',
stem="A 78-year-old man has exertional chest pain and syncope and a harsh crescendo-decrescendo systolic murmur. His left ventricular pressure–volume loop (shaded) is compared with a normal loop (dotted outline).{FIG}Which of the following is the most likely cause of this loop?",
choices=["Aortic regurgitation","Aortic stenosis","Arteriovenous fistula","Dilated cardiomyopathy","Mitral regurgitation"], key=1,
exp="The shaded loop is <b>very tall</b> (LV systolic pressure about 200 mm Hg, far above the aortic pressure needed): the ventricle must generate a huge pressure to force blood past a <b>narrowed aortic valve</b> → severe <b>↑ afterload</b>. Stroke volume is <b>reduced</b> (a narrow loop), and the <b>filling curve (EDPVR) is steeper</b> from compensatory concentric LV hypertrophy, so the ventricle is stiffer. With exertional angina, syncope and a crescendo-decrescendo murmur, this is <b>aortic stenosis</b>. This is a board add-on to the lecture.<br><br><b>Educational objective:</b> Aortic stenosis produces a very tall PV loop (high LV systolic pressure), a reduced stroke volume, and a steeper diastolic filling curve from LV hypertrophy.",
wrong={0:"Aortic regurgitation gives a very <b>wide</b> loop with a huge EDV and a low diastolic pressure.",
2:"An AV fistula gives a <b>shorter</b>, wider loop from low afterload.",
3:"Dilated cardiomyopathy shifts the loop <b>right</b> with a low peak pressure (↓ contractility).",
4:"Mitral regurgitation gives a rounded loop without isovolumic phases, and the systolic pressure isn't elevated."},
eli5="A stiff, narrow aortic valve means the ventricle must push extremely hard to get blood out. Its pressure soars and the loop gets very tall. Less blood makes it through each beat, and the thickened wall makes filling stiffer."),

dict(img=None,
stem="A 60-year-old man has 10 minutes of crushing substernal chest pain radiating to the left arm, jugular venous distention, and a rising troponin I. A graph of cardiac output versus left ventricular end-diastolic volume shows a normal Starling curve and a lower (depressed) curve.{FIG}Which of the following best describes his cardiac function in the first 10 seconds after the infarct compared with before it?",
choices=["Contractility ↑ · EDV ↓ · CO ↑","Contractility ↓ · EDV ↑ · CO ↓ (partly offset)","Contractility ↓ · EDV unchanged · CO unchanged","Contractility unchanged · EDV ↑ · CO ↑","Contractility unchanged · EDV ↓ · CO ↓"], key=1,
exp="This is a class question sent in by a second-year before USMLE. An acute MI means <b>↓ contractility</b>, so the heart drops to the <b>lower (failure) Starling curve</b>. The weaker beat leaves more blood behind (↑ ESV) → the next beats start with a <b>larger EDV</b>. On the depressed curve, the operating point at the higher EDV gives a CO that is <b>lower than normal</b> but <b>higher</b> than it would be at the old EDV: <b>Starling partly compensates</b>. The \"10 seconds\" in the stem rules out remodelling and slower hormonal compensation.<br><br><b>Educational objective:</b> Acutely after an MI, reduced contractility drops the heart to a lower Starling curve. EDV rises, and cardiac output falls but is partly restored by the Frank–Starling mechanism.",
wrong={0:"Contractility falls, not rises, with ischemic myocardium.",
2:"An unchanged EDV ignores the blood left behind by weaker beats. EDV rises within a few beats.",
3:"A higher EDV and CO with unchanged contractility is a volume load on a healthy heart.",
4:"Contractility falls, and EDV rises rather than falls."},
eli5="The heart attack weakens the muscle, so each beat leaves more blood behind and the heart gets fuller. Being fuller helps it squeeze a bit harder (Starling), so output drops, but not as much as it otherwise would."),

dict(img=None,
stem="A 71-year-old woman is admitted in decompensated heart failure with an ejection fraction of 20%, jugular venous distention, bibasilar crackles, and edema. A resident suggests a 1-L intravenous fluid bolus to \"increase preload and cardiac output.\"{FIG}Which of the following statements about this plan is most accurate?",
choices=["Fluid mainly increases unstressed volume, so it has no effect","Fluid reliably raises cardiac output by raising preload","Fluid stretches the veins and increases venomotor tone","It is safe because veins can accommodate any volume","Fluid may worsen her congestion without raising output"], key=4,
exp="This is the lecture's IV-fluid class question: <b>fluid can make things worse</b>. A severely failing heart may be <b>Starling-insensitive</b>. It is on the flat part of its depressed curve, so extra preload doesn't raise stroke volume. It only raises venous pressures (more pulmonary congestion and edema) and loads a heart that can't pump what it already has. \"Fluid raises stressed volume, Pmsf and VR\" is true but doesn't answer the question. \"Mainly unstressed\" is false, since it is mostly stressed. \"Reliably raises CO\" is only the hope, and papers still argue about it.<br><br><b>Educational objective:</b> In decompensated heart failure, a failing Starling-insensitive heart may not raise output with more preload, so IV fluid can worsen congestion.",
wrong={0:"A fluid load in a filled circulation mostly adds <b>stressed</b> volume, raising Pmsf. It doesn't have no effect.",
1:"This is the hope, not a guarantee. A Starling-insensitive heart gains little or no SV from more filling.",
2:"Fluid doesn't increase venomotor tone. Sympathetic activity does that.",
3:"Veins are compliant, but added volume still raises venous and capillary pressures, worsening congestion."},
eli5="Her heart is already overfilled and too weak to pump what it has. Pouring in more fluid won't make it pump more. It just backs up into her lungs and legs and makes the congestion worse."),

dict(img=None,
stem="A healthy, normovolemic 30-year-old man receives a rapid transfusion of 2 units of packed red blood cells that he did not need.{FIG}Which of the following best describes the immediate effect on his venous circulation?",
choices=["↑ Stressed volume · ↑ Pmsf · ↑ venous return","↑ Unstressed volume only · Pmsf unchanged · VR unchanged","↓ Stressed volume · ↓ Pmsf · ↓ VR","↓ Venous compliance · Pmsf unchanged · VR ↓","No change in any venous variable"], key=0,
exp="Veins are highly compliant and accept whatever volume they receive. In a normovolemic person the unstressed \"reservoir\" is already full, so an unneeded transfusion adds <b>mostly stressed volume</b> (unstressed rises only a little) → <b>↑ Pmsf</b> (for example from 8 to 12 mm Hg) → a larger gradient for venous return (<b>VR = (Pv − Pra)/Rv</b>) → <b>↑ VR</b> → ↑ CO, renal flow and GFR → the kidneys excrete the excess (the low-pressure volume reflex helps). On the vascular function curve this is a rightward shift.<br><br><b>Educational objective:</b> Adding volume to a normovolemic circulation mainly increases stressed volume, raising mean systemic filling pressure and venous return.",
wrong={1:"In a filled circulation extra volume is mostly <b>stressed</b>, so it raises Pmsf.",
2:"Adding volume <b>raises</b> stressed volume and Pmsf.",
3:"A transfusion doesn't reduce venous compliance. Venomotor tone (sympathetic) does.",
4:"Adding 2 units of blood clearly changes venous volume and pressure."},
eli5="His veins were already comfortably full. The extra blood stretches them and raises the pressure that pushes blood back to the heart. More blood returns, the heart pumps more, and the kidneys then get rid of the extra fluid."),

dict(img=None,
stem="A healthy volunteer receives a strong positive inotrope. His venous volume and venomotor tone do not change. Cardiac output rises only slightly.{FIG}Which of the following best explains why cardiac output cannot rise much further?",
choices=["Contractility doesn't move the cardiac curve","Venous return is capped as right atrial pressure nears 0","The drug decreases heart rate by reflex","The inotrope reduces afterload excessively","Total peripheral resistance rises and blocks flow"], key=1,
exp="On the Guyton graph the inotrope shifts the <b>cardiac function curve up and left</b>. But the operating point can only slide <b>down the unchanged vascular function curve</b>: as CO rises the heart pulls blood from the venous side and <b>Pra falls</b>. Near <b>Pra ≈ 0</b> the <b>vena cava collapses</b> and the vascular curve goes flat, so <b>venous return can't keep up</b> and CO is capped. A large, sustained rise in CO needs a higher Pmsf (more volume or more venomotor tone), as in exercise, where both curves move.<br><br><b>Educational objective:</b> Cardiac output is limited by venous return. Without a rise in mean systemic filling pressure, a stronger heart only lowers right atrial pressure toward the collapse point.",
wrong={0:"Contractility is exactly what shifts the cardiac function curve up and left.",
2:"A reflex drop in heart rate isn't the limiting factor described.",
3:"Inotropes don't primarily reduce afterload, and less afterload would raise CO.",
4:"TPR isn't described as rising. The limit is venous return."},
eli5="A stronger pump can only push out what flows back in. If the veins aren't fuller or tighter, the heart soon sucks them nearly empty and the big veins collapse. So output hits a ceiling unless more blood is pushed back."),

dict(img=None,
stem="A 35-year-old woman receives a rapid 2-L infusion of normal saline. Her heart rate rises from 70 to 86/min, and over the next hours she has a brisk diuresis.{FIG}Stimulation of which of the following receptors best explains both responses?",
choices=["Aortic arch baroreceptors, via reduced firing","Atrial and caval stretch receptors","Carotid body chemoreceptors","Carotid sinus baroreceptors, via reduced firing","Macula densa cells, via increased NaCl delivery only"], key=1,
exp="The <b>low-pressure (volume) receptors</b> in the <b>atria, IVC and SVC</b> respond to increased venous pressure (infusions, heart failure, posture changes):<br>• <b>Bainbridge reflex</b>: atrial stretch → <b>↑ HR</b>;<br>• ↓ renal sympathetic activity → ↑ GFR, with RAAS inhibited;<br>• <b>↓ ADH</b> and <b>↑ ANF (ANP)</b>.<br>Net result: <b>excrete salt and water</b> → diuresis. The high-pressure baroreflex (carotid sinus through CN IX, aortic arch through CN X) works moment to moment on arterial pressure. Reduced firing there would mean <b>low</b> arterial pressure.<br><br><b>Educational objective:</b> Atrial and caval stretch receptors mediate the Bainbridge reflex (↑ HR) and a volume-reducing diuresis (↓ renal sympathetic tone, ↓ ADH, ↑ ANF) after volume loading.",
wrong={0:"Reduced aortic baroreceptor firing signals <b>low</b> arterial pressure, which is the opposite of volume loading.",
2:"Carotid body chemoreceptors respond to hypoxemia, hypercapnia and acidosis, not volume.",
3:"Reduced carotid sinus firing signals <b>hypotension</b>.",
4:"The macula densa senses distal NaCl to regulate renin. It doesn't explain the rise in heart rate."},
eli5="A big bag of fluid stretches the heart's upper chambers and big veins. Stretch sensors there speed the heart a little (the Bainbridge reflex) and tell the kidneys to let go of salt and water. So she pees the extra out."),

dict(img=None,
stem="A 45-year-old man loses 1.5 L of blood in a motorcycle crash. Renal perfusion falls, and the sodium chloride delivered to the distal tubule decreases.{FIG}Which of the following best describes the macula densa's contribution to his compensation?",
choices=["It decreases renin release from juxtaglomerular cells","It increases ANP release from atrial myocytes","It triggers renin release from nearby cells","It stimulates ADH release from the posterior pituitary","It converts angiotensin I to angiotensin II"], key=2,
exp="The <b>juxtaglomerular apparatus</b>: <b>macula densa</b> cells (distal tubule) sense <b>decreased NaCl delivery</b> and signal the neighbouring <b>juxtaglomerular (JG) cells</b> in the afferent arteriole to <b>↑ renin release</b>. Hypotension, sympathetic β1 input to the JG cells and ↓ renal perfusion also raise renin. Renin → angiotensinogen → AI → (ACE, lung capillaries) → <b>AII</b> → arteriolar constriction (↑ TPR), aldosterone (↑ Na⁺ and water), ADH and thirst → volume restored. In the recording Dr. Morganelli said the macula densa \"stops making renin.\" That was a slip, and the slide is right: ↓ Na⁺ sensed → <b>↑ renin</b>.<br><br><b>Educational objective:</b> Reduced distal NaCl delivery, sensed by the macula densa, stimulates renin release from the juxtaglomerular cells, activating the RAAS.",
wrong={0:"The macula densa <b>increases</b> renin release when NaCl delivery falls. That was the recording slip.",
1:"ANP comes from stretched atria and falls with hemorrhage. The macula densa doesn't control it.",
3:"ADH rises through ↓ baroreceptor firing and angiotensin II, not directly from the macula densa.",
4:"ACE (mainly in lung capillaries) converts AI to AII. The macula densa doesn't."},
eli5="After bleeding, less salt reaches a sensor spot in the kidney called the macula densa. It tells nearby cells to release renin, which switches on the hormones that squeeze blood vessels and hold onto salt and water. That helps rebuild blood pressure."),
]
