# Jeevs Edition — Batch 03: Anemia II · Hemolysis
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §8  s7-hemolysis        — intravascular versus extravascular  (LO 25)
#   §9  s8-membrane-enzyme  — hereditary spherocytosis, G6PD      (LO 28)
#   §10 s9-globin           — thalassemia, sickle cell disease    (LO 7, 28)
# Options are alphabetised; "correct" is the 0-based index AFTER alphabetisation.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ── 1. Mechanical valve → intravascular hemolysis; the dipstick paradox (§8) ──
q("A 64-year-old man comes to the office because of a 3-week history of fatigue and dark brown urine that is most noticeable on waking. He underwent mechanical aortic valve replacement 5 months ago. His medications are warfarin and metoprolol. He has had no muscle pain or weakness and has not done unaccustomed exercise. His temperature is 37.0°C (98.6°F), pulse is 88/min, respirations are 16/min, and blood pressure is 128/76 mm Hg. Physical examination shows scleral icterus and a crisp mechanical click at the second right intercostal space; the spleen is not palpable. A tube of blood is spun, and the plasma layer is pink.\n\nLaboratory studies show:\nHemoglobin 9.4 g/dL (N=13.5–17.5 g/dL)\nHematocrit 28% (N=41%–53%)\nMean corpuscular volume 91 µm3 (N=80–100 µm3)\nReticulocyte count 6.4% (N=0.5%–1.5%)\nPlatelet count 224,000/mm3 (N=150,000–400,000/mm3)\nLactate dehydrogenase 840 U/L (N=45–200 U/L)\nHaptoglobin <10 mg/dL (N=30–200 mg/dL)\nTotal bilirubin 2.6 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.2 mg/dL (N=0.0–0.3 mg/dL)\nCreatine kinase 62 U/L (N=25–90 U/L)\nCreatinine 1.0 mg/dL (N=0.6–1.2 mg/dL)\n\nUrinalysis of a freshly voided specimen shows a dipstick strongly positive for blood; microscopic examination of the sediment shows no erythrocytes. A peripheral blood smear is shown.\n\nWhich of the following best explains this patient's urinalysis findings?",
  ["A. Excretion of conjugated bilirubin into the urine",
   "B. Excretion of increased urobilinogen into the urine",
   "C. Filtration of free hemoglobin released into the plasma",
   "D. Filtration of myoglobin released from injured skeletal muscle",
   "E. Lysis of intact erythrocytes within the collected specimen"],
  2,
  "This is intravascular hemolysis, and the whole vignette is the triad from §8: pink plasma, dark urine, and an undetectable haptoglobin. A mechanical valve shears erythrocytes under arterial pressure → cells rupture inside the vessel → free hemoglobin is spilled directly into plasma. The smear shows the fragments that shearing produces.\n\nThe urine dipstick does not detect erythrocytes. It detects the peroxidase activity of HEME, whatever is carrying it. So free plasma hemoglobin, once it exceeds the binding capacity of haptoglobin, is filtered at the glomerulus and turns the dipstick positive → hemoglobinuria → a positive dipstick with an empty sediment.\n\nThat mismatch (dipstick positive, microscopy negative) is the finding to recognize: with true hematuria you would see erythrocytes under the microscope. And this is the dangerous form of hemolysis — filtered free heme is toxic to the renal tubule, which is why his creatinine must be followed.",
  {"0": "Conjugated (direct) bilirubin is water-soluble and does appear in urine when it accumulates — in biliary obstruction or hepatocellular disease. It would be the answer if the direct fraction were raised; his is 0.2 mg/dL, and conjugated bilirubinuria does not turn a blood dipstick positive.",
   "1": "Urobilinogen is genuinely increased in any hemolysis and darkens urine, so it is a real finding here. But urobilinogen has its own dipstick pad and contains no heme — it cannot produce a strongly positive test for blood. It explains the color, not the result asked about.",
   "3": "Myoglobin also contains heme and produces exactly this dipstick-positive, erythrocyte-negative pattern — rhabdomyolysis is the counterfactual. It would be the answer with muscle pain, unaccustomed exertion, and a raised creatine kinase. His creatine kinase is 62 U/L and his plasma is pink, which myoglobin does not cause.",
   "4": "Erythrocytes lysing in a stale specimen can produce free hemoglobin in the tube, and it is why a fresh sample is requested — this one was freshly voided. In vitro lysis also would not make the patient jaundiced, drive the lactate dehydrogenase to 840 U/L, or consume the haptoglobin."},
  "His new heart valve is shredding red cells as blood rushes past it, so hemoglobin spills loose in the blood and gets dumped into the urine. The urine test strip reacts to hemoglobin, not to whole cells — so it turns positive even though there are no red cells to find.",
  image="fig_schistocytes",
  imcap="Peripheral blood smear. Among the intact erythrocytes there are several smaller angular cells with one straight or concave edge and a sharply pointed contour.",
  exim="fig_howell_jolly",
  excap="For comparison: a peripheral blood smear in which erythrocytes contain small dense round nuclear remnants (arrows) — the Howell-Jolly bodies of a missing or non-functioning spleen, a different clue entirely.")

# ── 2. Which marker actually localizes the hemolysis (§8) ─────────────────────
q("A 44-year-old woman is admitted to the hospital because of a 4-day history of fatigue, exertional dyspnea, and yellowing of her eyes. She has no history of serious illness, takes no medications, and does not smoke cigarettes or drink alcoholic beverages. Her temperature is 37.2°C (99.0°F), pulse is 104/min, respirations are 18/min, and blood pressure is 112/70 mm Hg. Physical examination shows scleral icterus and pallor of the conjunctivae. The abdomen is soft; the liver edge is not enlarged and the spleen is difficult to assess because of body habitus.\n\nLaboratory studies show:\nHemoglobin 8.6 g/dL (N=12.0–16.0 g/dL)\nHematocrit 26% (N=36%–46%)\nMean corpuscular volume 94 µm3 (N=80–100 µm3)\nReticulocyte count 7.8% (N=0.5%–1.5%)\nPlatelet count 268,000/mm3 (N=150,000–400,000/mm3)\nLactate dehydrogenase 610 U/L (N=45–200 U/L)\nTotal bilirubin 3.4 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.3 mg/dL (N=0.0–0.3 mg/dL)\nHaptoglobin 12 mg/dL (N=30–200 mg/dL)\n\nHemolysis is established, but the site of erythrocyte destruction is not yet clear. Which of the following additional findings would best establish that destruction is occurring within the blood vessels rather than within the spleen?",
  ["A. Increased reticulocyte count",
   "B. Increased serum lactate dehydrogenase activity",
   "C. Increased serum unconjugated bilirubin concentration",
   "D. Spherocytes on the peripheral blood smear",
   "E. Urine positive for hemosiderin on Prussian blue staining"],
  4,
  "Four of the five findings are shared by both kinds of hemolysis and therefore localize nothing. The §8 table splits them cleanly:\n\n• SHARED — reticulocytosis (the marrow compensates either way), raised lactate dehydrogenase (released from any destroyed cell), raised unconjugated bilirubin (heme is catabolized either way).\n• INTRAVASCULAR ONLY — hemoglobinemia (pink plasma), hemoglobinuria, an absent rather than merely low haptoglobin, and urine hemosiderin.\n• EXTRAVASCULAR ONLY — spherocytes and splenomegaly.\n\nUrine hemosiderin is the one option that can only happen if hemoglobin was free in plasma: filtered hemoglobin is reabsorbed by proximal tubular cells → the iron is stored as hemosiderin → those cells slough into the urine days later → Prussian blue stains them. It is also the marker that survives after an acute episode has passed, when the plasma has cleared.",
  {"0": "A raised reticulocyte count establishes that the marrow is intact and responding — the split from the impaired-production anemias of §4–§6 — but it rises in both intravascular and extravascular hemolysis. It would localize nothing even if it were 20%.",
   "1": "Lactate dehydrogenase is released from erythrocytes destroyed anywhere, and is already raised at 610 U/L. It would be a localizing finding only if it were undetectable in extravascular hemolysis, which it is not.",
   "2": "Unconjugated hyperbilirubinemia only says that heme is being catabolized faster than the liver conjugates it; splenic macrophages produce it just as efficiently as vessel rupture does. Her value of 3.4 mg/dL with a normal direct fraction already shows this and still does not answer the question.",
   "3": "Spherocytes point the opposite way. They are produced when a splenic macrophage removes part of the membrane and the cell rounds up — the signature of EXTRAVASCULAR destruction. Finding them would argue against the very thing the lead-in asks you to establish."},
  "Lots of blood tests tell you red cells are dying, but not where. Only the leftovers of hemoglobin floating free — like iron showing up in the urine days later — prove they burst inside the blood vessels.",
  exim="fig_aiha",
  excap="Two antibody-mediated hemolytic anemias that illustrate the split: IgM plus complement destroys cells inside the vessel, while IgG-coated cells are removed piecemeal by splenic macrophages.")

# ── 3. The corrected reticulocyte count (§8) ──────────────────────────────────
q("A 24-year-old man comes to the emergency department because of a 5-day history of fatigue, dyspnea on exertion, and yellow eyes. He has no history of serious illness and takes no medications. His temperature is 37.1°C (98.8°F), pulse is 108/min, respirations are 18/min, and blood pressure is 118/72 mm Hg. Physical examination shows scleral icterus and marked conjunctival pallor.\n\nLaboratory studies show:\nHemoglobin 7.0 g/dL (N=13.5–17.5 g/dL)\nHematocrit 21% (N=41%–53%)\nMean corpuscular volume 96 µm3 (N=80–100 µm3)\nReticulocyte count 6.0% (N=0.5%–1.5%)\nPlatelet count 302,000/mm3 (N=150,000–400,000/mm3)\n\nWhich of the following is the best estimate of this patient's corrected reticulocyte count?",
  ["A. 0.9%", "B. 2.8%", "C. 3.2%", "D. 6.0%", "E. 12.9%"],
  1,
  "Corrected reticulocyte count = reported reticulocyte % × (patient hematocrit ÷ 45).\n\n6.0% × (21 ÷ 45) = 6.0 × 0.467 → 2.8%\n\nThe correction exists because the reticulocyte count is a PERCENTAGE of circulating erythrocytes. When the denominator collapses — this man has lost half his red cell mass — the percentage rises even if the marrow has not produced a single extra cell. Scaling to a hematocrit of 45% asks the real question: how many reticulocytes is he making compared with a person with a normal red cell mass?\n\nInterpretation is the point of the arithmetic. A corrected value above 2–3% means an intact marrow responding to peripheral destruction or blood loss → hemolysis, the whole of §8–§10. Below 2% means a production defect → iron, B12, folate, inflammation, or marrow failure. At 2.8% with jaundice, this man is destroying cells, not failing to make them.",
  {"0": "0.9% is what you get by substituting the hemoglobin for the hematocrit — 6.0 × (7 ÷ 45). It would be correct only if the formula were indexed to hemoglobin, and it inverts the clinical meaning, turning a compensating marrow into a failing one.",
   "2": "3.2% comes from dividing by 40 rather than 45 — 6.0 × (21 ÷ 40). The reference hematocrit in the correction is 45%, and although the conclusion happens to survive this error, the value does not.",
   "3": "6.0% is the uncorrected laboratory value, which is the answer only if the hematocrit were already normal. Taking it at face value at a hematocrit of 21% overstates the marrow response by more than twofold — the exact error the correction exists to prevent.",
   "4": "12.9% comes from inverting the ratio — 6.0 × (45 ÷ 21). The correction must always scale the count DOWN in an anemic patient, never up; any answer larger than the reported value has the fraction upside down."},
  "The reticulocyte count is a percentage, and when the total number of red cells drops, that percentage looks bigger than the marrow really deserves. You scale it to a normal hematocrit to get the honest number. Here 6% is really about 2.8%.",
  exim="fig_retics",
  excap="Reticulocytes in peripheral blood — the young erythrocytes whose percentage must be corrected for the degree of anemia before it can be interpreted.")

# ── 4. Hereditary spherocytosis — the diagnosis (§9) ──────────────────────────
q("A 13-year-old girl is brought to the office by her father because of 6 months of increasing weakness and intermittent yellowing of her eyes. She has had brief episodes of jaundice since early childhood, usually during colds. Her father was told he was jaundiced as a teenager and had his spleen removed at age 20. She takes no medications. Her temperature is 37.0°C (98.6°F), pulse is 92/min, respirations are 16/min, and blood pressure is 106/68 mm Hg. Physical examination shows scleral icterus; the spleen is palpated 6 cm below the left costal margin. Ultrasonography of the abdomen shows multiple small gallstones.\n\nLaboratory studies show:\nHemoglobin 9.3 g/dL (N=12.0–16.0 g/dL)\nHematocrit 25% (N=36%–46%)\nMean corpuscular volume 87 µm3 (N=80–100 µm3)\nMean corpuscular hemoglobin concentration 37.2% Hb/cell (N=31%–36% Hb/cell)\nReticulocyte count 9.8% (N=0.5%–1.5%)\nTotal bilirubin 3.8 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.3 mg/dL (N=0.0–0.3 mg/dL)\nLactate dehydrogenase 265 U/L (N=45–200 U/L)\nHaptoglobin 22 mg/dL (N=30–200 mg/dL)\n\nThe direct antiglobulin (Coombs) test is negative. Osmotic fragility is increased. A peripheral blood smear is shown.\n\nWhich of the following is the most likely diagnosis?",
  ["A. Autoimmune hemolytic anemia, warm antibody type",
   "B. Beta-thalassemia trait",
   "C. Glucose-6-phosphate dehydrogenase deficiency",
   "D. Hereditary spherocytosis",
   "E. Pyruvate kinase deficiency"],
  3,
  "Every element of the §9 picture is present: lifelong episodic jaundice, an affected parent (autosomal dominant), splenomegaly, pigmented gallstones in a teenager, spherocytes on the smear, increased osmotic fragility, and a HIGH mean corpuscular hemoglobin concentration.\n\nThe mechanism runs in one line. A defective membrane cytoskeletal protein — ankyrin, band 3, β-spectrin, α-spectrin or protein 4.2 — cannot hold the biconcave shape → the cell rounds into a sphere → a sphere has the least surface area for its volume and cannot fold through the splenic cords → splenic macrophages remove it. Extravascular hemolysis, by definition.\n\nTwo numbers deserve attention. The mean corpuscular hemoglobin concentration is raised because membrane was lost while hemoglobin was not — the same hemoglobin in a smaller container. And the haptoglobin is only modestly reduced, not absent, exactly as §8 predicts for extravascular destruction.\n\nThe NEGATIVE Coombs test is the value that decides the item.",
  {"0": "Warm autoimmune hemolytic anemia produces spherocytes, jaundice and splenomegaly as well — it is the near-miss, and the reason a Coombs test is mandatory whenever spherocytes are seen. It would be the answer if the direct antiglobulin test were POSITIVE. It also would not explain jaundice dating from early childhood or an affected father.",
   "1": "Beta-thalassemia trait gives a low mean corpuscular volume with a near-normal hemoglobin and target cells, not spherocytes. It would be correct with an MCV in the 60s and a high erythrocyte count; her MCV is 87 µm3 and her hemoglobin is 9.3 g/dL.",
   "2": "G6PD deficiency is X-linked, so it is expressed fully in males, and its hemolysis is episodic and triggered — an oxidant drug, an infection, or fava beans — with bite cells and blister cells rather than spherocytes. It would be the answer with an acute crisis after an oxidant exposure, not 6 months of steady hemolysis with an affected father.",
   "4": "Pyruvate kinase deficiency is an autosomal recessive enzyme defect that also produces chronic extravascular hemolysis from infancy, so it is a genuine competitor. It would be the answer with a NORMAL osmotic fragility, no spherocytes, and a normal mean corpuscular hemoglobin concentration; the increased fragility and the dominant family history point to the membrane instead."},
  "Her red cells are missing part of the scaffolding that holds their doughnut shape, so they become little balls. Balls cannot squeeze through the spleen, so the spleen eats them — which is why she is pale, yellow, and has a big spleen and gallstones.",
  image="fig_spherocytes",
  imcap="Peripheral blood smear. Many erythrocytes are uniformly round and densely stained and lack the pale central zone seen in normal cells; the cells vary considerably in size.",
  exim="fig_spherocytes_uw",
  excap="A higher-power field: small, dense, round erythrocytes without central pallor, alongside larger bluish polychromatophilic cells — the young erythrocytes of a marrow working at maximum.")

# ── 5. Osmotic fragility — the mechanism, investigator format (§9) ────────────
q("In a hematology laboratory, erythrocytes from a patient are washed and then incubated in a graded series of sodium chloride solutions of decreasing tonicity, and the proportion of cells that lyse at each concentration is measured against cells from a healthy control. The patient's cells begin to lyse at a HIGHER sodium chloride concentration than control cells, and lysis is complete at a concentration at which most control cells remain intact. On a stained smear, the patient's cells are round and densely stained and lack a pale central zone.\n\nWhich of the following properties of the patient's erythrocytes best explains the laboratory result?",
  ["A. Decreased intracellular potassium concentration",
   "B. Decreased ratio of membrane surface area to cell volume",
   "C. Increased hemoglobin affinity for oxygen",
   "D. Increased intracellular viscosity from polymerized hemoglobin",
   "E. Increased membrane permeability to sodium"],
  1,
  "The osmotic fragility test is old-fashioned, but the logic IS the disease. In a hypotonic solution water enters the cell and the cell swells. What decides whether it bursts is how much spare membrane it has for the volume it contains.\n\n• A normal biconcave disc carries excess surface area for its volume → it can swell a long way, rounding up into a sphere, before the membrane is stretched to failure.\n• A spherocyte is already a sphere → its surface-area-to-volume ratio is already minimal → a small amount of water entry ruptures it.\n\nSo lysis begins at a higher (less hypotonic) sodium chloride concentration → increased osmotic fragility. This is a test of SHAPE, not of the pump, the hemoglobin, or the permeability of the membrane. Note that it is not specific to hereditary spherocytosis: any process producing spherocytes, including warm autoimmune hemolysis, increases fragility, which is why a direct antiglobulin test is sent alongside it.",
  {"0": "A fall in intracellular potassium accompanies cell dehydration and would make the cell SHRINK, which if anything protects it from osmotic lysis by giving it more room to swell. It would be the answer only if the question asked about the dehydrated cells of hereditary xerocytosis, whose fragility is characteristically decreased.",
   "2": "Oxygen affinity is a property of the hemoglobin molecule and its allosteric effectors, and it has no bearing on whether a membrane ruptures in hypotonic saline. It would matter in a question about hemoglobin Barts or the oxygen dissociation curve, not in one about lysis.",
   "3": "Polymerized hemoglobin stiffens the cell and distorts it into a crescent — the mechanism of sickle cell disease. Rigid cells are trapped and fragmented in the microcirculation; they do not show a shifted osmotic lysis curve, and the described cells are round rather than crescent-shaped.",
   "4": "A sodium leak lets the cell gain solute and swell, and cation-leak disorders are real. But the cells here are spherical with no central pallor before any incubation, which is a surface-area problem present at baseline; a pure permeability defect would not produce that resting morphology."},
  "A normal red cell is a floppy doughnut with spare skin, so it can puff up a lot before it pops. A cell that is already a tight little ball has no spare skin, so it pops almost immediately in watery salt solution.",
  exim="fig_spherocytes",
  excap="Spherocytes on a peripheral blood smear: uniformly round, densely stained cells lacking the pale central zone of a normal biconcave disc.")

# ── 6. Aplastic crisis — parvovirus B19 (§9) ──────────────────────────────────
q("A 9-year-old girl with known hereditary spherocytosis is brought to the emergency department by her parents because of 3 days of increasing pallor, lethargy, and headache. She had a low-grade fever and a faint lacy rash over her trunk 5 days ago; several children at her school have had a similar illness. Her baseline hemoglobin concentration is 10.5 g/dL. She takes daily folic acid. Her temperature is 37.4°C (99.3°F), pulse is 132/min, respirations are 26/min, and blood pressure is 96/58 mm Hg. Physical examination shows marked pallor and a soft systolic murmur; the spleen is palpated 4 cm below the left costal margin, unchanged from previous examinations. There is no scleral icterus today.\n\nLaboratory studies show:\nHemoglobin 4.3 g/dL (N=11.5–15.5 g/dL)\nHematocrit 13% (N=35%–45%)\nMean corpuscular volume 86 µm3 (N=77–95 µm3)\nReticulocyte count 0.2% (N=0.5%–1.5%)\nLeukocyte count 6,200/mm3 (N=4500–11,000/mm3)\nPlatelet count 216,000/mm3 (N=150,000–400,000/mm3)\nTotal bilirubin 1.1 mg/dL (N=0.1–1.0 mg/dL)\n\nWhich of the following infectious agents is the most likely cause of these findings?",
  ["A. Epstein-Barr virus",
   "B. Human parvovirus B19",
   "C. Mycoplasma pneumoniae",
   "D. Salmonella enterica",
   "E. Streptococcus pneumoniae"],
  1,
  "The reticulocyte count of 0.2% is the whole item. In a child whose hemoglobin has fallen from 10.5 to 4.3 g/dL, the marrow should be pouring out reticulocytes. It has stopped instead → this is a production failure superimposed on chronic hemolysis → an APLASTIC crisis.\n\nParvovirus B19 infects erythroid precursors through the P antigen and shuts erythropoiesis down for about a week. A healthy child tolerates that pause, because normal erythrocytes live 120 days. A child with hereditary spherocytosis does not: her cells survive only days, and her hemoglobin is held up entirely by a marrow running at maximum. Remove the compensation and the hemoglobin falls off a cliff.\n\nTwo quiet details confirm it rather than the rash. Her bilirubin is LOWER than her usual value and she is not icteric — less hemolysis is occurring, not more, because fewer cells are being made to destroy. And her leukocyte and platelet counts are normal, because the virus targets the erythroid line specifically.\n\nParvovirus B19 does the identical thing in sickle cell disease.",
  {"0": "Epstein-Barr virus causes infectious mononucleosis with pharyngitis, cervical lymphadenopathy and atypical lymphocytosis, and it can trigger a cold-agglutinin hemolysis — in which case the reticulocyte count would be HIGH. It would be the answer with sore throat, adenopathy, and a leukocytosis with atypical lymphocytes.",
   "2": "Mycoplasma pneumoniae infection is the classic trigger of cold agglutinin disease, which would produce a hemolytic crisis with agglutinated cells on the smear and a RISING reticulocyte count and bilirubin. It would be correct with cough, patchy infiltrates and a raised reticulocyte count — the opposite of the value here.",
   "3": "Salmonella species cause osteomyelitis and bacteremia in patients with functional asplenia, particularly in sickle cell disease. That is a febrile, focal illness; it does not selectively shut off erythroid precursors, and this child has no fever, no bone pain, and a normal leukocyte count.",
   "4": "Streptococcus pneumoniae is the organism that kills asplenic and hyposplenic patients, and fever in such a child is an emergency. But it produces fulminant sepsis with a high fever, hypotension and a very abnormal leukocyte count, not an isolated reticulocytopenia in a well-perfused, afebrile child."},
  "Her red cells die fast, so her bone marrow has to work flat out just to keep up. A virus turned the marrow's red cell factory off for a week, and without that constant resupply her blood count crashed.",
  exim="fig_parvo_pronormoblast",
  excap="Bone marrow in parvovirus B19 infection: erythroid precursors are nearly absent apart from a few very large pronormoblasts with glassy nuclear inclusions.")

# ── 7. Warm autoimmune hemolysis — same smear, different mechanism (§9) ───────
q("A 58-year-old woman comes to the office because of a 2-week history of fatigue, exertional dyspnea, and darkening of her eyes' whites. She has no history of serious illness, has never been transfused, and takes no medications. Her temperature is 37.1°C (98.8°F), pulse is 102/min, respirations are 18/min, and blood pressure is 124/78 mm Hg. Physical examination shows scleral icterus and conjunctival pallor; the spleen is palpated 2 cm below the left costal margin. Her fingers and ears are normal in color and are not painful in the cold.\n\nLaboratory studies show:\nHemoglobin 8.0 g/dL (N=12.0–16.0 g/dL)\nHematocrit 24% (N=36%–46%)\nMean corpuscular volume 99 µm3 (N=80–100 µm3)\nReticulocyte count 8.4% (N=0.5%–1.5%)\nPlatelet count 254,000/mm3 (N=150,000–400,000/mm3)\nLactate dehydrogenase 430 U/L (N=45–200 U/L)\nTotal bilirubin 2.9 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.3 mg/dL (N=0.0–0.3 mg/dL)\nHaptoglobin 18 mg/dL (N=30–200 mg/dL)\n\nA peripheral blood smear shows numerous round, densely stained erythrocytes without central pallor. The direct antiglobulin test is strongly positive for IgG and negative for complement C3. Serum studies show no cold agglutinins. Urinalysis shows no blood.\n\nWhich of the following best explains the destruction of this patient's erythrocytes?",
  ["A. Complement-mediated lysis in the circulation triggered by IgM at temperatures below core body temperature",
   "B. Inherited deficiency of a membrane cytoskeletal protein",
   "C. Mechanical fragmentation of erythrocytes within small vessels",
   "D. Oxidative denaturation of hemoglobin with formation of intracellular inclusions",
   "E. Splenic macrophage removal of membrane from IgG-coated erythrocytes"],
  4,
  "Spherocytes plus a POSITIVE direct antiglobulin test for IgG is warm autoimmune hemolytic anemia. IgG autoantibody binds erythrocytes at core body temperature → splenic macrophages engage the Fc portion and remove a piece of membrane rather than the whole cell → the cell loses surface area and rounds up into a spherocyte → on a later pass it is removed entirely. Extravascular destruction, with a spleen that enlarges from the work.\n\nEvery laboratory value fits that location. The haptoglobin is reduced but far from absent, there is no hemoglobin in the urine, and the raised mean corpuscular volume simply reflects the reticulocytosis.\n\nThe teaching point of §9 is that the smear alone cannot get you here. Spherocytes have exactly two common homes — hereditary spherocytosis and warm autoimmune hemolysis — and only the direct antiglobulin test separates them. It is negative in the inherited disease and positive here. Note also that the antibody class localizes the destruction: IgG means warm, splenic and extravascular; IgM with C3 means cold, complement-mediated and intravascular.",
  {"0": "That is cold agglutinin disease: IgM binds in cooled peripheral blood, fixes complement, and lyses cells inside the vessel. It would be the answer with acrocyanosis or pain in the cold, agglutinated cells on the smear, a positive test for cold agglutinins, and a direct antiglobulin test positive for C3 rather than IgG.",
   "1": "An inherited cytoskeletal defect — hereditary spherocytosis — produces an identical smear and a similar clinical picture, which is exactly why this item exists. It would be the answer if the direct antiglobulin test were NEGATIVE, and it typically declares itself in childhood with a family history rather than over 2 weeks at age 58.",
   "2": "Mechanical fragmentation gives schistocytes — angular fragments with straight edges — together with the intravascular signature of an absent haptoglobin and hemoglobinuria. It would be the answer with a prosthetic valve or a microangiopathy and a low platelet count; her platelets are normal and there is no blood in her urine.",
   "3": "Oxidative denaturation produces Heinz bodies, and the splenic bite taken out of them leaves bite cells and blister cells — the G6PD picture. It would be the answer after an oxidant drug or fava beans, and it would not produce a positive direct antiglobulin test."},
  "Her immune system has coated her own red cells with antibody, and the spleen nibbles pieces off them until they turn into little balls and get eaten. The blood test that finds the antibody stuck on the cells is what proves it is her immune system and not an inherited cell problem.",
  exim="fig_aiha",
  excap="Warm (IgG) versus cold (IgM) autoimmune hemolysis: IgG-coated cells are stripped of membrane by splenic macrophages, while IgM plus complement lyses cells within the vessel.")

# ── 8. G6PD deficiency — the bite cell (§9) ───────────────────────────────────
q("A 7-year-old boy is brought to the emergency department by his mother because of 1 day of dark brown urine, fatigue, and yellow eyes. Two days ago he was started on trimethoprim-sulfamethoxazole for a urinary tract infection. He has been otherwise healthy and takes no other medications. An older brother had an episode of jaundice after an antibiotic several years ago. His temperature is 37.3°C (99.1°F), pulse is 118/min, respirations are 24/min, and blood pressure is 102/64 mm Hg. Physical examination shows scleral icterus and pallor; the spleen is not palpable and there is no abdominal tenderness.\n\nLaboratory studies show:\nHemoglobin 7.4 g/dL (N=11.5–15.5 g/dL)\nHematocrit 22% (N=35%–45%)\nMean corpuscular volume 88 µm3 (N=77–95 µm3)\nReticulocyte count 3.4% (N=0.5%–1.5%)\nPlatelet count 288,000/mm3 (N=150,000–400,000/mm3)\nLactate dehydrogenase 690 U/L (N=45–200 U/L)\nHaptoglobin <10 mg/dL (N=30–200 mg/dL)\nTotal bilirubin 3.1 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.2 mg/dL (N=0.0–0.3 mg/dL)\n\nThe direct antiglobulin test is negative. A peripheral blood smear is shown.\n\nWhich of the following is the most likely diagnosis?",
  ["A. Autoimmune hemolytic anemia",
   "B. Glucose-6-phosphate dehydrogenase deficiency",
   "C. Hereditary spherocytosis",
   "D. Microangiopathic hemolytic anemia",
   "E. Sickle cell disease"],
  1,
  "An acute hemolytic episode beginning within 2 days of a sulfonamide, in a previously well boy, with a smear showing cells that appear to have had a semicircular chunk removed: this is G6PD deficiency.\n\nThe chain is short. The drug generates oxidants → without G6PD the cell cannot regenerate reduced glutathione → hydrogen peroxide accumulates → hemoglobin is oxidized, denatures, and precipitates onto the inner membrane as a HEINZ BODY → a splenic macrophage removes the inclusion together with the overlying membrane → a BITE CELL. Less damaged cells round up as spherocytes, which is one more reason spherocytes alone never make a diagnosis.\n\nThe X-linked inheritance shows in the affected brother and the male patient. The undetectable haptoglobin marks a substantial intravascular component, which is why his urine is dark. Heinz bodies themselves require a supravital stain such as crystal violet — they are invisible on this routine smear, so do not wait for them.\n\nManagement is to stop the offending drug and support him; the episode is self-limited.",
  {"0": "Autoimmune hemolysis produces spherocytes and a POSITIVE direct antiglobulin test — his is negative, which is the value that excludes it. It would also not be triggered within 48 hours by a first exposure to a sulfonamide in this way.",
   "2": "Hereditary spherocytosis is autosomal dominant and chronic: lifelong episodic jaundice, splenomegaly, gallstones, a high mean corpuscular hemoglobin concentration and increased osmotic fragility. It would be the answer with a palpable spleen and a history dating from early childhood rather than a first episode 2 days after a drug.",
   "3": "Microangiopathic hemolysis shears cells into schistocytes and is accompanied by a LOW platelet count and usually renal or neurologic findings. It would be correct with fragments on the smear and thrombocytopenia; his platelet count is 288,000/mm3 and the cells have bites taken out of them rather than being fragmented.",
   "4": "Sickle cell disease produces crescent-shaped cells, target cells and Howell-Jolly bodies, with pain crises and dactylitis from infancy and a chronically raised reticulocyte count. It is detected on newborn screening and would not first appear at age 7 after an antibiotic."},
  "His red cells have no way to mop up the damage an oxidizing drug causes, so the hemoglobin inside clumps up. The spleen takes a bite out of each cell to remove the clump, leaving cells that look like someone bit a piece off a cookie.",
  image="fig_bite_cells",
  imcap="Peripheral blood smear. Several erythrocytes have a smooth semicircular defect at the edge, as though a portion had been removed, and appear smaller and more densely stained than the surrounding cells.",
  exim="fig_bite_uw",
  excap="A second field showing the same finding: erythrocytes with a discrete semicircular portion of the periphery missing.")

# ── 9. G6PD — the biochemical step (§9) ──────────────────────────────────────
q("A 6-year-old boy is brought to the office by his parents because of 2 days of pallor, dark urine, and yellow eyes that began the day after a family meal that included fava beans. He has had no fever, cough, or diarrhea. He takes no medications. His temperature is 37.0°C (98.6°F), pulse is 112/min, respirations are 22/min, and blood pressure is 98/60 mm Hg. Physical examination shows scleral icterus and pallor. His hemoglobin concentration is 6.9 g/dL, hematocrit is 21%, and lactate dehydrogenase activity is 720 U/L. A supravital stain of the peripheral blood shows small round inclusions attached to the inner surface of the erythrocyte membrane.\n\nImpairment of which of the following processes best explains the formation of these inclusions?",
  ["A. Conversion of hydrogen peroxide to water by glutathione peroxidase",
   "B. Generation of adenosine triphosphate by anaerobic glycolysis",
   "C. Generation of NADPH in the hexose monophosphate shunt",
   "D. Reduction of methemoglobin by cytochrome b5 reductase",
   "E. Synthesis of the globin chains of hemoglobin"],
  2,
  "The inclusions are Heinz bodies — precipitated, oxidized hemoglobin — and the step that fails upstream of them is NADPH production.\n\nThe chain, in order: glucose-6-phosphate dehydrogenase is the rate-limiting enzyme of the hexose monophosphate (pentose phosphate) shunt → it generates NADPH → NADPH powers glutathione reductase, which regenerates REDUCED glutathione from its oxidized form → reduced glutathione lets glutathione peroxidase convert hydrogen peroxide to water. Break the first link and everything downstream idles for want of reducing power → peroxide accumulates → hemoglobin is oxidized, denatures and precipitates as a Heinz body.\n\nWhy this is fatal specifically to a red cell: it has no nucleus and no mitochondria. It cannot make replacement enzyme, and it has no alternative route to NADPH. G6PD is the entire antioxidant plan, with no backup — which is why a single meal of fava beans can drop a hemoglobin by half.",
  {"0": "Glutathione peroxidase performs the actual detoxifying step, and it is the correct pathway — but the enzyme itself is present and functional here. It idles because its substrate, reduced glutathione, cannot be regenerated without NADPH. This is the mechanism-confusion option: right pathway, wrong step.",
   "1": "Anaerobic glycolysis supplies the red cell's adenosine triphosphate, and its failure is pyruvate kinase deficiency — a chronic hemolytic anemia from infancy with rigid, energy-depleted cells. It would be the answer without an oxidant trigger and without Heinz bodies.",
   "3": "Cytochrome b5 reductase returns oxidized ferric iron in methemoglobin to the ferrous state; its deficiency causes congenital methemoglobinemia with cyanosis and chocolate-brown blood that does not correct with oxygen. That is oxidation of the IRON, not precipitation of the globin, and it would be the answer with cyanosis rather than hemolysis.",
   "4": "Deficient globin chain synthesis is thalassemia. Unpaired chains do precipitate and can also form inclusions, so the option is genuinely tempting — but that process is chronic and lifelong, produces microcytosis and target cells, and is not triggered by a single oxidant meal in a previously well child."},
  "Red cells need a constant supply of a chemical called NADPH to neutralize the damaging oxygen chemicals that build up. One enzyme makes all of it, and if that enzyme is faulty, hemoglobin gets chemically burned and clumps into blobs inside the cell.",
  exim="fig_g6pd_pathway",
  excap="The protective pathway: glucose-6-phosphate dehydrogenase generates NADPH, NADPH regenerates reduced glutathione, and glutathione peroxidase converts hydrogen peroxide to water.")

# ── 10. The falsely normal enzyme assay (§9) ──────────────────────────────────
q("A 10-year-old boy is admitted to the hospital because of 2 days of pallor, jaundice and dark urine that began shortly after he was given primaquine before travel. His hemoglobin concentration is 7.1 g/dL, reticulocyte count is 4.6%, haptoglobin is less than 10 mg/dL (N=30–200 mg/dL), and the direct antiglobulin test is negative. A peripheral blood smear shows erythrocytes with a semicircular portion of the periphery missing. The drug is stopped, and over the next week his hemoglobin concentration rises to 10.8 g/dL without transfusion. An erythrocyte glucose-6-phosphate dehydrogenase assay drawn on the second hospital day is reported as within the reference range.\n\nWhich of the following is the most appropriate next step in diagnosis?",
  ["A. Measure erythrocyte glucose-6-phosphate dehydrogenase activity again in 3 months",
   "B. Measure erythrocyte pyruvate kinase activity",
   "C. Obtain a bone marrow aspirate and biopsy",
   "D. Perform an osmotic fragility test",
   "E. Perform hemoglobin electrophoresis"],
  0,
  "A normal enzyme assay drawn during a crisis does not exclude G6PD deficiency, and the reason follows directly from the mechanism of the disease.\n\nThe variant enzyme is not absent — it is UNSTABLE, with a shortened half-life, so activity decays as a red cell ages. Deficiency is therefore worst in the OLDEST cells. During a hemolytic episode two things happen at once: those old, enzyme-depleted cells are precisely the ones being destroyed and removed from the sample, and the marrow floods the circulation with reticulocytes, which carry the HIGHEST enzyme activity of any red cell. Measure the average of what is left and it can look entirely normal.\n\nThe fix is timing. Repeat the assay 2 to 3 months after the episode, once the age distribution of the red cell population has returned to baseline. A genetic test is unaffected by timing and is an acceptable alternative at any point.\n\nEverything else in this vignette already says G6PD deficiency: an oxidant drug, bite cells, an intravascular signature, a negative Coombs test, and spontaneous recovery once the drug was stopped.",
  {"1": "Pyruvate kinase deficiency is the other red cell enzyme defect worth knowing, but it causes chronic hemolysis from infancy without an oxidant trigger and without bite cells. It would be the answer in a child with lifelong anemia and a normal G6PD level measured at a valid time.",
   "2": "A marrow examination answers questions about production — aplasia, infiltration, dysplasia. This marrow is demonstrably working, since his hemoglobin rose by 3.7 g/dL in a week without transfusion. It is an invasive test that would not address the enzyme question.",
   "3": "Osmotic fragility tests for spherocytes, and would be the next step if the smear had shown round cells without central pallor in a child with splenomegaly and a family history of gallstones. His smear shows bite cells, his spleen is not enlarged, and his illness began with a drug.",
   "4": "Hemoglobin electrophoresis identifies structural variants and thalassemias — it would be the answer for a chronic microcytic anemia with target cells or for suspected sickling. It does not measure enzyme activity and would be normal in this boy."},
  "The test looked normal only because it was done at the wrong moment: the damaged old cells had already been destroyed and the new ones are full of the enzyme. Wait a couple of months for his blood to settle back to normal, then test again.",
  exim="fig_heinz",
  excap="Supravital staining of the same kind of episode: erythrocytes containing small round inclusions of precipitated hemoglobin, which are invisible on a routine stain.")

# ── 11. Why the episode is self-limited (§9) ──────────────────────────────────
q("A 22-year-old man is admitted to the hospital because of 3 days of fatigue, jaundice and dark urine that began 2 days after he started dapsone for a dermatologic condition. His hemoglobin concentration on admission is 8.2 g/dL and his reticulocyte count is 5.2%. The dermatologic condition requires continued treatment, and dapsone is continued at the same dose. Over the following 10 days his jaundice resolves, his urine clears, and his hemoglobin concentration rises to 12.9 g/dL despite ongoing therapy. Erythrocyte glucose-6-phosphate dehydrogenase activity measured 3 months later is 22% of normal.\n\nWhich of the following best explains the resolution of hemolysis despite continued exposure to the drug?",
  ["A. Antibody against the drug was cleared from the circulation",
   "B. Hepatic metabolism of the drug was induced, lowering its oxidant load",
   "C. Splenic macrophages became saturated and stopped removing damaged cells",
   "D. The enzyme-deficient older erythrocytes were destroyed and replaced by young, enzyme-replete cells",
   "E. Tolerance developed through downregulation of erythrocyte oxidant receptors"],
  3,
  "This is the behavior of a moderate (WHO class III) variant such as G6PD A−, and it follows from one fact: the mutant enzyme is unstable, not absent. Its half-life is roughly 13 days against a normal 62, so activity decays steeply as a cell ages.\n\nThat gives an age-graded vulnerability. When the oxidant arrives, the OLD cells — the ones whose enzyme has already decayed — hemolyze; the young cells are still protected. The oldest fraction of the population is destroyed within days, the marrow replaces it with reticulocytes carrying near-normal enzyme activity, and the remaining population is resistant to the same insult. Hemolysis stops even though the drug continues. This is why class III episodes are described as self-limited.\n\nThe contrast worth carrying is G6PD Mediterranean (WHO class II), where activity is under 10% and the enzyme half-life is measured in hours. There is no protected young population, the entire red cell mass is vulnerable, and hemolysis can be severe and sustained — that patient does not self-correct and the drug must be stopped.\n\nThe same age dependence is what makes an enzyme assay falsely normal during a crisis.",
  {"0": "Drug-dependent antibody is a real mechanism of immune hemolysis, and it would be the answer with a POSITIVE direct antiglobulin test. Here the defect is enzymatic and heritable, confirmed by an enzyme activity of 22% measured after recovery, and immune hemolysis would not remit while the drug continued.",
   "1": "Enzyme induction can lower the concentration of some drugs, but dapsone's oxidant metabolites are generated by that same hepatic metabolism, so induction would if anything worsen the hemolysis. It would also not explain why the reticulocyte-rich population is protected.",
   "2": "Splenic macrophages do not saturate and switch off — and this episode has a substantial intravascular component in any case. If splenic clearance were the limiting step, the damaged cells would accumulate in the circulation rather than the patient recovering a normal hemoglobin.",
   "4": "There is no such thing as an erythrocyte oxidant receptor to downregulate, and a red cell has no nucleus with which to alter gene expression. The protection acquired here is demographic — a younger cell population — not adaptive."},
  "The faulty enzyme wears out as a red cell gets older, so only his oldest cells were vulnerable. Once those were destroyed and replaced with brand-new cells, the rest could handle the drug just fine.",
  exim="fig_bite_uw",
  excap="The morphologic fingerprint of the episode: erythrocytes with a semicircular portion removed after a splenic macrophage extracted a Heinz body.")

# ── 12. Counting alpha genes (§10) ────────────────────────────────────────────
q("A 3-year-old boy is brought to the office for evaluation of chronic anemia first noted at 9 months of age. He has required no transfusions. His parents report that he tires more easily than his sibling. His temperature is 37.0°C (98.6°F), pulse is 104/min, and blood pressure is 94/56 mm Hg. Physical examination shows mild scleral icterus and a spleen palpated 3 cm below the left costal margin.\n\nLaboratory studies show:\nHemoglobin 8.6 g/dL (N=11.5–15.5 g/dL)\nHematocrit 26% (N=35%–45%)\nMean corpuscular volume 61 µm3 (N=77–95 µm3)\nReticulocyte count 4.8% (N=0.5%–1.5%)\nSerum ferritin 96 ng/mL (N=10–120 ng/mL)\nTotal iron-binding capacity 302 µg/dL (N=250–400 µg/dL)\nTotal bilirubin 2.2 mg/dL (N=0.1–1.0 mg/dL)\n\nA peripheral blood smear shows hypochromic erythrocytes with marked variation in size and shape and many cells with a central dark area surrounded by a pale ring. Supravital staining shows erythrocytes with multiple small inclusions composed of a beta globin tetramer. Hemoglobin electrophoresis shows no hemoglobin S and a normal hemoglobin A2 concentration.\n\nDeletion of how many alpha globin genes best accounts for these findings?",
  ["A. One of four", "B. Two of four", "C. Three of four", "D. Four of four"],
  2,
  "The inclusions made of a BETA globin tetramer are hemoglobin H (β₄), and hemoglobin H disease means three of the four alpha genes are deleted, leaving one working gene.\n\nThe framework is arithmetic. Adult hemoglobin is α₂β₂; you carry FOUR alpha genes (two on each chromosome 16) and only two beta genes (one on each chromosome 11). With alpha globin severely reduced, the beta chains produced have no partner, so they self-associate into β₄ — unstable, oxidized, precipitating, and removed by the spleen. Hence the moderate anemia, the splenomegaly and the reticulocytosis without transfusion dependence.\n\nThe two negatives in the stem do real work. Normal iron studies exclude iron deficiency as the cause of the microcytosis, and a NORMAL hemoglobin A2 excludes beta-thalassemia trait, in which A2 is raised. Alpha thalassemia is the microcytic anemia in which electrophoresis is essentially unremarkable in an older child — the diagnosis comes from the hemoglobin H inclusions and gene testing.",
  {"0": "A single gene deletion is the silent carrier state: three working alpha genes, no anemia, normal indices, and no clinical findings whatsoever. More than one person in any lecture hall has it and will never know. It cannot produce a hemoglobin of 8.6 g/dL with splenomegaly.",
   "1": "Two deletions give alpha-thalassemia trait: microcytosis with minimal or no anemia and normal iron studies — the state most often mistaken for iron deficiency. There is not enough excess beta chain to form hemoglobin H inclusions, and the spleen is not enlarged.",
   "3": "Deletion of all four genes makes no alpha-containing hemoglobin possible at all. Excess gamma chains form hemoglobin Barts (γ₄), which binds oxygen and will not release it, causing severe intrauterine anoxia — hydrops fetalis. Without intrauterine intervention such a fetus does not survive to become a 3-year-old in the office."},
  "Hemoglobin needs two kinds of chain, and this boy has lost three of his four genes for one of them. The leftover chains clump together inside his red cells, and his spleen destroys the cells that carry the clumps.",
  exim="fig_globin_chains",
  excap="Globin chain composition of the normal and abnormal hemoglobins, including the β₄ and γ₄ tetramers that form when alpha chains are deficient.")

# ── 13. Hemoglobin Barts (§10) ────────────────────────────────────────────────
q("A 26-year-old woman, gravida 2, para 1, is evaluated at 28 weeks' gestation because ultrasonography shows fetal ascites, pleural effusions, generalized skin edema, and cardiomegaly. Both she and the father of the fetus have mild microcytosis with normal iron studies. Fetal blood sampling shows severe anemia; hemoglobin analysis shows that nearly all of the fetal hemoglobin is a tetramer of gamma globin chains, with no hemoglobin F and no hemoglobin A detected.\n\nWhich of the following best explains the severe tissue hypoxia in this fetus?",
  ["A. The tetramer binds oxygen with such high affinity that it does not release it to tissue",
   "B. The tetramer cannot bind oxygen because it lacks a heme group",
   "C. The tetramer is oxidized to the ferric state and cannot bind oxygen",
   "D. The tetramer polymerizes when deoxygenated and occludes the microcirculation",
   "E. The tetramer precipitates in erythroid precursors, preventing their release from the marrow"],
  0,
  "A tetramer of four gamma chains is hemoglobin Barts, and it forms when NO functional alpha genes remain — all four deleted. Because every physiologic hemoglobin (A, F and A2) requires alpha chains, none of them can be assembled, and the gamma chains that would normally pair with alpha associate with each other instead.\n\nThe problem is not binding oxygen; it is releasing it. Hemoglobin Barts has an extremely high oxygen affinity, so it takes up oxygen in the placenta and holds onto it. The fetus is full of hemoglobin and still profoundly anoxic → high-output cardiac failure, generalized edema, effusions and ascites → hydrops fetalis. Untreated it is lethal in utero or shortly after birth; survival requires intrauterine transfusion and, later, transplantation.\n\nThe parallel with hemoglobin H disease is the point §10 is making. There, ONE alpha gene remains, the excess partner is beta, and β₄ is unstable rather than avid — it precipitates and is removed by the spleen, giving a survivable hemolytic anemia. Which chain is left over, and how that tetramer behaves, is what separates a manageable disease from a lethal one.",
  {"1": "Hemoglobin Barts assembles normally around its heme groups — the defect is in the globin genes, not in heme synthesis. A failure of heme production is the porphyrias and sideroblastic anemias, which would be the answer with ringed sideroblasts and abnormal porphyrin intermediates.",
   "2": "Oxidation of heme iron to the ferric state is methemoglobinemia, which would be the answer in a cyanotic neonate with chocolate-brown blood unresponsive to oxygen, often after an oxidizing agent. It is not a consequence of losing alpha globin genes.",
   "3": "Polymerization on deoxygenation is the mechanism of hemoglobin S, and it would be the answer with sickled erythrocytes and vaso-occlusion. Sickle cell disease is a beta chain structural mutation; it does not present as hydrops with a gamma tetramer.",
   "4": "Precipitation inside precursors with intramedullary death — ineffective erythropoiesis — is the mechanism of beta-thalassemia major and part of hemoglobin H disease. It would be the answer with an unpartnered ALPHA chain excess, and it produces a severe anemia after birth rather than a fetus whose hemoglobin cannot unload oxygen."},
  "This baby cannot make one of the two building blocks of hemoglobin at all, so the leftover blocks stick together into a version that grabs oxygen and refuses to let go. The blood is full of oxygen that never reaches the tissues.",
  exim="fig_globin_chains",
  excap="Which tetramer forms depends on which partner chain is missing: β₄ (hemoglobin H) when one alpha gene remains, γ₄ (hemoglobin Barts) when none does.")

# ── 14. Why beta-thalassemia major spares the newborn (§10) ───────────────────
q("A 7-month-old boy is brought to the office by his parents because of increasing pallor and poor weight gain over the past 6 weeks. He was born at term after an uncomplicated pregnancy, and his newborn examination and growth in the first months of life were normal. His temperature is 37.1°C (98.8°F), pulse is 148/min, and respirations are 38/min. Physical examination shows marked pallor, mild scleral icterus, and a spleen palpated 4 cm below the left costal margin.\n\nLaboratory studies show:\nHemoglobin 6.4 g/dL (N=10.5–13.5 g/dL)\nHematocrit 19% (N=33%–39%)\nMean corpuscular volume 62 µm3 (N=70–86 µm3)\nReticulocyte count 5.2% (N=0.5%–1.5%)\nSerum ferritin 180 ng/mL (N=10–120 ng/mL)\n\nA peripheral blood smear shows hypochromic erythrocytes, marked variation in size and shape, target cells, and nucleated erythrocytes. Hemoglobin electrophoresis shows markedly reduced hemoglobin A with elevated hemoglobin F and elevated hemoglobin A2.\n\nWhich of the following best explains why this infant was healthy at birth and for the first months of life?",
  ["A. Fetal hemoglobin contains gamma chains in place of the deficient beta chains",
   "B. Maternal hemoglobin crossed the placenta and persisted in the infant's circulation",
   "C. Neonatal erythrocytes have a longer lifespan than those of older infants",
   "D. Physiologic splenic function does not mature until approximately 6 months of age",
   "E. Transfused hemoglobin A from delivery persisted through the first months of life"],
  0,
  "Fetal hemoglobin is α₂γ₂ — it contains NO beta chains at all. An infant with beta-thalassemia major is therefore genuinely well in utero and in early infancy, because the hemoglobin he is running on does not require the gene that is defective.\n\nThe illness appears with the globin switch. Gamma chain production falls off over the first 3 to 6 months and beta is meant to take over → in this infant beta output is absent or nearly so → hemoglobin A cannot be assembled → the anemia declares itself at precisely the age described. His electrophoresis is a picture of a switch that never completed: little hemoglobin A, persistently high hemoglobin F, and raised hemoglobin A2 (α₂δ₂) as delta chains take up some of the unpartnered alpha.\n\nThe damage is done by the chain he has too MUCH of. Unpartnered alpha chains precipitate in erythroid precursors and kill them in the marrow (ineffective erythropoiesis) and mark surviving cells for splenic removal. Hence a hypercellular marrow with a profoundly anemic child, hepatosplenomegaly, and — later — frontal bossing and maxillary prominence from marrow cavity expansion.",
  {"1": "Maternal hemoglobin does not cross the placenta; only the gases and nutrients do, and the fetus makes its own erythrocytes from the first weeks of gestation. If maternal hemoglobin were the explanation, every fetal hemoglobinopathy would present identically at birth.",
   "2": "Neonatal erythrocytes actually have a SHORTER lifespan than adult cells — roughly 60 to 90 days — which contributes to physiologic anemia of infancy. A longer lifespan would be the answer only if it were true, and it would not explain an electrophoresis showing persistent hemoglobin F.",
   "3": "Splenic function is relevant to infection risk in asplenia, not to when a globin defect becomes apparent. It would matter in a question about encapsulated organisms in sickle cell disease; it does not determine which hemoglobin an infant is using.",
   "4": "He was not transfused — the pregnancy and delivery were uncomplicated. Even if he had been, donor erythrocytes survive only weeks, and this explanation would not account for the raised hemoglobin F and A2 on his electrophoresis."},
  "Babies use a special baby hemoglobin that does not need the broken part at all, so he was fine at first. Around 6 months the body switches over to the adult version — and that is the one he cannot make.",
  exim="fig_beta_thal_uw",
  excap="Peripheral blood in beta-thalassemia: small, pale erythrocytes with marked variation in size and shape and numerous target cells.")

# ── 15. Microcytic overlap — the iron studies grid (§10 + §4) ─────────────────
q("A 24-year-old woman comes to the office for a routine examination. She feels well, exercises regularly, and has regular light menstrual periods. Six months ago a complete blood count obtained at a blood drive showed a small mean corpuscular volume, and she has taken ferrous sulfate 325 mg by mouth daily since then without any change in her indices. She takes no other medications and eats a varied diet including red meat. Vital signs are within normal limits. Physical examination shows no abnormalities; there is no scleral icterus and the spleen is not palpable.\n\nLaboratory studies show:\nHemoglobin 11.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 34% (N=36%–46%)\nMean corpuscular volume 66 µm3 (N=80–100 µm3)\nRed cell distribution width 13.1% (N=11.5%–14.5%)\nReticulocyte count 1.4% (N=0.5%–1.5%)\nPlatelet count 246,000/mm3 (N=150,000–400,000/mm3)\n\nA peripheral blood smear is shown. Testing of the stool for occult blood is negative on three specimens.\n\nAdditional studies are obtained:\n\n    Serum iron | Total iron-binding capacity | Ferritin | Erythrocyte count\n\nWhich of the following sets of results is most likely in this patient?",
  ["A. Decreased, decreased, increased, decreased",
   "B. Decreased, increased, decreased, decreased",
   "C. Increased, decreased, increased, decreased",
   "D. Normal, normal, normal, decreased",
   "E. Normal, normal, normal, increased"],
  4,
  "Thalassemia trait is the microcytosis with NORMAL iron studies, and the erythrocyte count is the detail that separates it from everything else on the list.\n\nRead the clues in order. Her mean corpuscular volume of 66 µm3 is disproportionately low for a hemoglobin of 11.4 g/dL — iron deficiency severe enough to shrink cells that far would leave her far more anemic. Her red cell distribution width is normal, whereas iron deficiency produces a wide one as small cells mix with older normal cells. She has no source of blood loss, three negative stool tests, and 6 months of iron with no response. And she makes MORE erythrocytes than expected: in thalassemia the marrow produces a large number of small, poorly filled cells, so the count is normal or high while the hemoglobin is only mildly low.\n\nThe practical consequence is in §10's warning box. Iron given to a thalassemic patient treats nothing and eventually produces the iron overload that the rest of their care is spent chelating out. The next step here is hemoglobin electrophoresis, expected to show raised hemoglobin A2 in beta-thalassemia trait, with gene testing if alpha thalassemia is suspected.",
  {"0": "Low iron, LOW total iron-binding capacity and a normal or high ferritin is the anemia of chronic disease row — iron sequestered by hepcidin rather than absent. It would be the answer in a patient with an inflammatory, infectious or malignant illness; she is well, exercises, and has no such disease.",
   "1": "Low iron, HIGH total iron-binding capacity and low ferritin is iron deficiency, the row most students pick here. It would be the answer with a wide red cell distribution width, a source of blood loss, and — critically — a response to 6 months of oral iron. She has none of those.",
   "2": "High iron with a high ferritin and a low iron-binding capacity is the sideroblastic or iron-overload row, in which iron reaches the cell but cannot be incorporated into heme. It would be the answer with ringed sideroblasts on a Prussian blue stain of the marrow, or with a history of lead exposure or alcohol use.",
   "3": "This row has the iron studies right and the last column wrong, which is what makes it the near-miss. Thalassemia trait characteristically raises the erythrocyte count rather than lowering it — the marrow turns out many small underfilled cells — and a low count with normal iron studies would point instead toward a hypoproliferative process."},
  "Her red cells are small but she is barely anemic, and she has plenty of them — that is the fingerprint of a hemoglobin-building fault, not a shortage of iron. Six months of iron tablets did nothing because iron was never the problem.",
  image="fig_target_cells",
  imcap="Peripheral blood smear. The erythrocytes are small and pale, and many show a dark central area surrounded by a pale ring within a darker outer rim.",
  exim="fig_ida_progression",
  excap="For contrast, the sequence of laboratory change in true iron deficiency: ferritin falls first, then serum iron and transferrin saturation, and only last the mean corpuscular volume and hemoglobin.")

# ── 16. Transfusional iron overload (§10 + §17) ───────────────────────────────
q("A 9-year-old girl with beta-thalassemia major is evaluated during a routine visit. She has received packed red blood cell transfusions every 3 to 4 weeks since 14 months of age. She takes folic acid daily. Her height and weight are below the 5th percentile for age, and she has not begun puberty. Her temperature is 37.0°C (98.6°F), pulse is 92/min, and blood pressure is 104/64 mm Hg. Physical examination shows a greyish-brown discoloration of the skin, a liver edge palpated 4 cm below the right costal margin, and no scleral icterus.\n\nLaboratory studies show:\nHemoglobin 9.8 g/dL (N=11.5–15.5 g/dL)\nSerum ferritin 2,840 ng/mL (N=10–120 ng/mL)\nTransferrin saturation 88% (N=20%–50%)\nAlanine aminotransferase 96 U/L (N=10–40 U/L)\nFasting serum glucose 118 mg/dL (N=70–100 mg/dL)\n\nEchocardiography shows normal ventricular function. Which of the following is the most appropriate next step in management?",
  ["A. Begin oral deferasirox therapy",
   "B. Begin oral ferrous sulfate therapy",
   "C. Begin subcutaneous erythropoietin therapy",
   "D. Discontinue transfusions and observe",
   "E. Perform serial therapeutic phlebotomy"],
  0,
  "Every unit of transfused blood carries about 200–250 mg of iron, and the human body has NO physiologic mechanism for excreting iron. A child transfused every 3 to 4 weeks since infancy accumulates it relentlessly, and the deposits land in the organs named in this vignette: liver (hepatomegaly, raised transaminases), pancreas (impaired glucose tolerance), pituitary and gonads (growth failure and delayed puberty), skin (bronze discoloration), and — the one that kills — the heart.\n\nThe treatment is chelation: deferasirox (oral, once daily) or deferoxamine (parenteral). Thresholds in common use are a ferritin persistently above about 1,000 ng/mL or roughly 10 to 20 transfusions, both of which she has passed by a wide margin. Her normal echocardiogram is reassuring but not a reason to wait — cardiac iron deposition is silent until it is not.\n\nThe irony §10 draws out is worth keeping: this is the one anemia in which you must remove iron rather than give it. She stays anemic and she stays iron-overloaded at the same time, because the anemia is a globin problem and the overload is a transfusion problem.",
  {"1": "Oral iron would be the answer for iron deficiency — a low ferritin with a high iron-binding capacity. Giving iron to a patient with a ferritin of 2,840 ng/mL and a transferrin saturation of 88% accelerates precisely the organ damage already underway. This is the trap that the microcytosis of thalassemia sets.",
   "2": "Erythropoiesis-stimulating agents work when the marrow lacks the signal to produce cells, as in chronic kidney disease. Her marrow is already maximally driven and profoundly ineffective; she cannot make beta chains no matter how hard it is stimulated, so the drug would add toxicity without benefit.",
   "3": "Stopping transfusions would be the answer if the transfusions were unnecessary. In transfusion-dependent thalassemia major they prevent severe anemia, marrow cavity expansion with skeletal deformity, and growth failure. Withdrawing them trades a treatable complication for an untreatable one.",
   "4": "Phlebotomy is the correct treatment for HEREDITARY hemochromatosis, where the patient makes normal blood and can spare it. It would be the answer in an adult with a high transferrin saturation and a normal hemoglobin. Removing blood from a transfusion-dependent anemic child is self-defeating."},
  "Each blood transfusion brings iron with it, and the body has no way to get rid of extra iron. After years of transfusions the iron piles up in her liver, pancreas and heart, so she needs a medicine that grabs iron and carries it out.",
  exim="fig_hepcidin",
  excap="Normal iron regulation: absorption is controlled by hepcidin, but there is no regulated route of iron EXCRETION, which is why transfused iron accumulates without limit.")

# ── 17. Reading the electrophoresis (§10) ─────────────────────────────────────
q("A 19-year-old man comes to the office for a pre-participation sports examination. He feels well and has never had jaundice, bone pain, or episodes of severe pain. His younger brother was recently found to have an abnormal hemoglobin on testing, and the patient wishes to know his own status. His temperature is 36.9°C (98.4°F), pulse is 62/min, and blood pressure is 118/72 mm Hg. Physical examination shows no abnormalities; there is no scleral icterus and the spleen is not palpable.\n\nLaboratory studies show:\nHemoglobin 14.8 g/dL (N=13.5–17.5 g/dL)\nHematocrit 44% (N=41%–53%)\nMean corpuscular volume 88 µm3 (N=80–100 µm3)\nReticulocyte count 1.1% (N=0.5%–1.5%)\nTotal bilirubin 0.8 mg/dL (N=0.1–1.0 mg/dL)\n\nA peripheral blood smear shows no abnormalities. Hemoglobin electrophoresis shows hemoglobin A 58%, hemoglobin S 40%, hemoglobin A2 2%, and hemoglobin F less than 1%.\n\nWhich of the following is the most likely diagnosis?",
  ["A. Beta-thalassemia trait",
   "B. Hemoglobin SC disease",
   "C. Normal hemoglobin pattern",
   "D. Sickle cell disease",
   "E. Sickle cell trait"],
  4,
  "Both hemoglobin A and hemoglobin S are present, in roughly 60:40 proportion. That is heterozygosity read directly off the gel — sickle cell TRAIT.\n\nThe rule that decides the item is the absence, not the presence. In sickle cell disease the patient is homozygous, so 90–100% of the hemoglobin is S and there is NO hemoglobin A band at all. Any detectable hemoglobin A (in an untransfused patient) excludes the homozygous state. The clinical picture agrees: a normal hemoglobin concentration, a normal reticulocyte count, a normal bilirubin, a normal smear and no history of pain.\n\nWhy hemoglobin S stays below half in trait: the beta chains compete for alpha partners, and normal beta globin is incorporated somewhat more efficiently than S, so the S fraction settles at about 40–45%. That dilution is also the protection — hemoglobin S polymerizes readily with itself and poorly with hemoglobin A, so at this proportion polymerization essentially does not occur under ordinary conditions.\n\nTrait is generally asymptomatic and is not a disease, though it warrants genetic counseling: two carrier parents face a 25% risk of an affected child with each pregnancy.",
  {"0": "Beta-thalassemia trait would show a RAISED hemoglobin A2 (typically 3.5–7%) with a low mean corpuscular volume and a mild anemia, and no hemoglobin S at all. His A2 is 2% and his indices are entirely normal.",
   "1": "Hemoglobin SC disease shows hemoglobin S and hemoglobin C with NO hemoglobin A, and causes a mild-to-moderate hemolytic anemia with target cells, retinopathy and avascular necrosis. No hemoglobin C band is present here, and his hemoglobin A of 58% excludes any compound homozygous state.",
   "2": "A normal pattern is essentially all hemoglobin A with hemoglobin A2 under about 3.5% and no hemoglobin S. A band comprising 40% of his hemoglobin is not a normal finding, and reporting it as normal would miss the counseling that this result requires.",
   "3": "Sickle cell disease would show hemoglobin S at 90–100% with hemoglobin A ABSENT, accompanied by anemia, reticulocytosis, sickled cells and Howell-Jolly bodies on the smear, and a history of pain crises from early childhood. The presence of 58% hemoglobin A rules it out."},
  "He has one normal copy of the gene and one sickle copy, so his blood carries both kinds of hemoglobin. Having the normal kind alongside is what keeps the sickle kind from clumping, which is why he is completely healthy.",
  exim="fig_electrophoresis",
  excap="Electrophoresis patterns: the trait states show two bands, while the homozygous disease states show a single abnormal band with no hemoglobin A.")

# ── 18. Fever in a child with sickle cell disease (§10 + §11) ─────────────────
q("A 14-month-old boy with sickle cell disease, diagnosed on newborn screening, is brought to the emergency department by his mother because of a fever that began 6 hours ago. He has been fussy and is feeding less than usual. He takes penicillin twice daily and folic acid, and his immunizations, including pneumococcal conjugate vaccine, are up to date. His temperature is 39.4°C (102.9°F), pulse is 168/min, respirations are 38/min, and blood pressure is 88/50 mm Hg. Physical examination shows an irritable but consolable infant with moist mucous membranes and a capillary refill time of 2 seconds. The tympanic membranes are normal, the lungs are clear to auscultation, and there is no rash or focal tenderness. The spleen is palpated 2 cm below the left costal margin, unchanged from his last visit.\n\nLaboratory studies show:\nHemoglobin 7.6 g/dL (N=10.5–13.5 g/dL)\nHematocrit 23% (N=33%–39%)\nReticulocyte count 9.2% (N=0.5%–1.5%)\nLeukocyte count 17,400/mm3 (N=4500–11,000/mm3)\nPlatelet count 384,000/mm3 (N=150,000–400,000/mm3)\n\nHis baseline hemoglobin concentration is 7.5 g/dL. Which of the following is the most appropriate next step in management?",
  ["A. Administer intravenous ceftriaxone after blood cultures are obtained",
   "B. Administer oral amoxicillin and arrange reassessment in 24 hours",
   "C. Begin hydroxyurea therapy",
   "D. Perform red blood cell exchange transfusion",
   "E. Withhold antibiotics until blood culture results are available"],
  0,
  "Fever in a young child with sickle cell disease is a medical emergency, and the reason is anatomic. Repeated splenic infarction produces functional asplenia — autosplenectomy — within the first few years of life, even while the spleen is still palpable. Without splenic clearance of opsonized organisms the child cannot control encapsulated bacteria, above all Streptococcus pneumoniae, and can progress from fever to fulminant sepsis and death within hours.\n\nSo the sequence is: obtain blood cultures, then give an empiric parenteral third-generation cephalosporin IMMEDIATELY — do not wait for a source, a culture result, or a white count to declare itself. Neither prophylactic penicillin nor conjugate vaccination removes the risk; both reduce it, and both have been given here.\n\nThe anemia is a deliberate distraction. His hemoglobin of 7.6 g/dL is his baseline, and his reticulocyte count of 9.2% shows a marrow compensating normally — there is no aplastic crisis (reticulocytes would be low), no sequestration (the spleen is unchanged and he is not in shock), and no acute chest syndrome (the lungs are clear). The problem to treat first is the fever.",
  {"1": "Oral antibiotics with next-day review is reasonable practice for a febrile immunocompetent toddler, and it is the answer the surface reading of a well-appearing, consolable child invites. In functional asplenia the margin for error is a few hours, which oral therapy and a 24-hour interval do not provide.",
   "2": "Hydroxyurea is disease-modifying therapy for recurrent vaso-occlusive episodes, severe anemia or acute chest syndrome; it raises fetal hemoglobin over weeks to months. It would be the answer at a planning visit for a child with frequent painful episodes. It treats nothing acutely and causes myelosuppression in a child who may be septic.",
   "3": "Exchange transfusion is used for acute chest syndrome, stroke and severe vaso-occlusive events with a high hemoglobin S fraction. It would be the answer with hypoxemia and a new pulmonary infiltrate, or with focal neurologic findings. His lungs are clear and his hemoglobin is at his own baseline.",
   "4": "Waiting for cultures is the error this scenario is built to punish: pneumococcal sepsis in an asplenic child outruns the laboratory. Cultures are drawn first, but antibiotics follow within minutes, not days."},
  "His spleen has been destroyed by years of sickling, and the spleen is the organ that clears certain bacteria from the blood. That makes any fever a potential emergency, so he gets a strong antibiotic into a vein right away.",
  exim="fig_howell_jolly",
  excap="The morphologic sign of a spleen that is absent or no longer working: erythrocytes containing small dense nuclear remnants (arrows), the Howell-Jolly bodies that a functioning spleen would have removed.")

# ── 19. Which crisis? (§10) ───────────────────────────────────────────────────
q("A 3-year-old girl with sickle cell disease is brought to the emergency department by her parents because of 12 hours of increasing pallor, lethargy, and abdominal fullness. She has had no fever, cough, or pain in her arms or legs. Her baseline hemoglobin concentration is 8.0 g/dL. Her temperature is 37.0°C (98.6°F), pulse is 164/min, respirations are 36/min, and blood pressure is 78/40 mm Hg. Physical examination shows marked pallor, cool extremities, and a distended abdomen; the spleen is firm and palpated 8 cm below the left costal margin, compared with 2 cm 3 months ago. The lungs are clear to auscultation.\n\nLaboratory studies show:\nHemoglobin 4.2 g/dL (N=10.5–13.5 g/dL)\nHematocrit 13% (N=33%–39%)\nReticulocyte count 16.4% (N=0.5%–1.5%)\nLeukocyte count 14,200/mm3 (N=4500–11,000/mm3)\nPlatelet count 96,000/mm3 (N=150,000–400,000/mm3)\n\nA peripheral blood smear is shown. Which of the following is the most likely diagnosis?",
  ["A. Acute chest syndrome",
   "B. Acute splenic sequestration crisis",
   "C. Aplastic crisis",
   "D. Delayed hemolytic transfusion reaction",
   "E. Vaso-occlusive (painful) crisis"],
  1,
  "Three findings decide it together: a spleen that has grown from 2 cm to 8 cm in 3 months and is acutely distended, a hemoglobin that has halved, and a reticulocyte count of 16.4% — HIGH.\n\nIn splenic sequestration, rigid sickled cells are abruptly trapped in the splenic cords and a large fraction of the circulating blood volume is swallowed by the spleen. The cells are not destroyed so much as removed from circulation → the child becomes profoundly anemic and HYPOVOLEMIC at the same time → tachycardia, hypotension, cool extremities. Platelets are sequestered along with the erythrocytes, which is why her platelet count has fallen. It is one of the commonest causes of death in young children with sickle cell disease and requires immediate volume resuscitation and cautious transfusion.\n\n§10's memory hook is three crises and three reticulocyte counts: aplastic → LOW (production has stopped, think parvovirus B19); sequestration → HIGH with a suddenly enormous spleen (the cells are alive, just not in the circulation); vaso-occlusive → hemoglobin near baseline, because the problem is ischemia and pain rather than red cell mass. Ask for the reticulocyte count and the spleen size and the three separate immediately.\n\nThe spleen is still present and functioning here because she is only 3 — autosplenectomy has not yet completed.",
  {"0": "Acute chest syndrome presents with fever, chest pain, hypoxemia and a NEW pulmonary infiltrate, and it is the leading cause of death in adults with sickle cell disease. It would be the answer with respiratory findings; her lungs are clear and she has no fever or chest pain.",
   "2": "An aplastic crisis produces the same abrupt fall in hemoglobin, which is what makes it the near-miss — but the reticulocyte count would be LOW (often under 1%) because parvovirus B19 has shut erythropoiesis down, and the spleen would not enlarge. Hers is 16.4%, and her spleen has quadrupled.",
   "3": "A delayed hemolytic transfusion reaction occurs 2 to 10 days after a transfusion as an anamnestic response to a minor red cell antigen, with a gradual hemoglobin fall and a positive direct antiglobulin test. It would be the answer with a transfusion in the preceding 2 weeks; she has not been transfused, and it does not cause acute splenic enlargement.",
   "4": "A vaso-occlusive crisis causes severe pain in the limbs, back, abdomen or chest, and characteristically leaves the hemoglobin near the patient's baseline. It would be the answer with pain as the dominant complaint and a hemoglobin of about 8 g/dL — not a halving of the hemoglobin with hypotension and no pain."},
  "Her spleen suddenly trapped a huge amount of her blood inside itself, so her spleen got enormous while her blood count crashed. Her bone marrow is still working hard — the young cells are there — the blood is just stuck in the wrong place.",
  image="fig_sickle_smear",
  imcap="Peripheral blood smear. Numerous erythrocytes are elongated and crescent-shaped with pointed ends; others are round with a dark central area surrounded by a pale ring.",
  exim="fig_sickle_target",
  excap="A second field from a patient with the same disorder: crescent-shaped erythrocytes alongside target cells.")

# ── 20. Hydroxyurea (§10) ─────────────────────────────────────────────────────
q("A 17-year-old young man with sickle cell disease is evaluated in the clinic. Over the preceding year he was admitted five times for severe painful episodes and once for acute chest syndrome. Six months ago hydroxyurea was started at 15 mg/kg once daily and the dose was gradually increased. Since then he has had one painful episode requiring admission. His hemoglobin concentration has risen from 7.4 to 9.1 g/dL, his mean corpuscular volume has risen from 88 to 104 µm3, and quantitative hemoglobin studies show that his hemoglobin F has risen from 4% to 19%.\n\nWhich of the following best explains the reduction in this patient's painful episodes?",
  ["A. Correction of the beta globin point mutation in hematopoietic stem cells",
   "B. Decreased polymerization of hemoglobin S owing to a higher proportion of fetal hemoglobin",
   "C. Increased erythropoietin secretion with a resulting increase in erythrocyte production",
   "D. Inhibition of splenic macrophage uptake of sickled erythrocytes",
   "E. Irreversible inhibition of platelet cyclooxygenase"],
  1,
  "Hemoglobin S polymerizes readily with itself and POORLY with hemoglobin F. Raising the fetal hemoglobin fraction therefore dilutes the polymer: the deoxygenated hemoglobin S molecules are progressively separated by molecules they cannot stick to → fewer fibers form → fewer cells become rigid and crescent-shaped → less vaso-occlusion, less pain, less organ damage. His hemoglobin F rose from 4% to 19%, and his admissions fell from five to one.\n\nThis is the single therapeutic lever that almost every sickle cell treatment pulls, from different directions. Hydroxyurea raises hemoglobin F; transfusion adds hemoglobin A; intravenous fluids lower the intracellular hemoglobin concentration; oxygen keeps the molecule in the conformation that does not polymerize; and gene therapy either switches fetal hemoglobin back on (by disabling BCL11A) or inserts a working beta globin gene. Dilute the polymer, or keep it oxygenated.\n\nThe rise in mean corpuscular volume is a useful marker of adherence and effect. The trade-off must be stated: hydroxyurea carries two boxed warnings — myelosuppression and secondary malignancy — because it is a cytotoxic agent, so the blood count is monitored throughout treatment.",
  {"0": "Correcting the mutation itself is gene therapy or stem cell transplantation, not hydroxyurea, which alters gene EXPRESSION rather than sequence. It would be the answer for Lyfgenia, which inserts a functional beta globin gene, or Casgevy, which edits BCL11A to restore fetal hemoglobin.",
   "2": "Hydroxyurea suppresses the marrow; it does not stimulate it, and his rising hemoglobin reflects less hemolysis rather than more production. Increased erythropoietin action would be the mechanism of an erythropoiesis-stimulating agent, which does nothing about polymerization and could raise viscosity in this patient.",
   "3": "Blocking splenic uptake would address extravascular destruction, which is the mechanism of splenectomy or of immunosuppression in autoimmune hemolysis. It would not reduce vaso-occlusive PAIN, and most adolescents with sickle cell disease have already autoinfarcted their spleens.",
   "4": "Irreversible cyclooxygenase inhibition is aspirin. Antiplatelet therapy has not been shown to prevent vaso-occlusive episodes, and it would not raise the hemoglobin F fraction or the mean corpuscular volume, both of which changed here."},
  "The sickling happens when the abnormal hemoglobin molecules stick to each other in long chains. This drug makes the body switch some baby hemoglobin back on, and the abnormal molecules cannot stick to that — so the chains do not form and the pain attacks drop off.",
  exim="fig_sickle_target",
  excap="Sickle cell disease on a peripheral blood smear: crescent-shaped erythrocytes with pointed ends, together with target cells.")
