# Jeevs Edition — Batch 12: INFECTION, part 2 (the gaps batch 11 left)
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §18 s17-sepsis            — NEWS2 vs MEWS, the septic shock definition, post-sepsis syndrome
#   §19 s18-hiv-micro         — host vs viral protease, integration, the enhancers, JC virus
#   §20 s19-hiv-clinical      — live vaccines, U=U, PEP, the booster/nasal steroid interaction
#   §21 s19b-vector-infections— Ebola strain mismatch, cat scratch disease, plague pneumonia, RTS,S
#   §22 s19c-vhf              — Dengvaxia, the M segment, HCPS vs HFRS
# Options alphabetised; "correct" is the 0-based index AFTER alphabetisation.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ══════════════════════════ §18 · SEPSIS ══════════════════════════

# ── 1. NEWS2 versus MEWS (§18) ───────────────────────────────────────────────
q("A hospital is revising the early-warning score used to identify deteriorating patients on its general medical wards. The current protocol uses the Modified Early Warning Score, which is calculated from systolic blood pressure, heart rate, respiratory rate, temperature, and level of consciousness assessed by the AVPU scale. The committee proposes changing to the National Early Warning Score, version 2, noting that it is designed to assess risk of death from sepsis and that every parameter of the current score also appears in the proposed one.\n\nWhich of the following parameters would be added by the proposed change?",
  ["A. Level of consciousness",
   "B. Oxygen saturation",
   "C. Respiratory rate",
   "D. Systolic blood pressure",
   "E. Temperature"],
  1,
  "MEWS has FIVE parameters — systolic blood pressure, heart rate, respiratory rate, temperature, and AVPU mental status — and NEWS2 has SIX. Every MEWS parameter also appears in NEWS2, and OXYGEN SATURATION is the one NEWS2 adds. That is the cleanest way to hold the two apart.\n\nThe rest of the comparison:\n• NEWS2 assesses risk of DEATH from sepsis; its six parameters are respiration rate, oxygen saturation, systolic blood pressure, pulse, consciousness level, and temperature.\n• MEWS is the MORE SENSITIVE of the two.\n• SIRS is no longer a defining criterion for sepsis, though it remains popular and is used by the US Centers for Medicare and Medicaid Services.\n• SOFA is more specific with better predictive validity than SIRS, assessing neurologic, liver, kidney and blood/hemodynamic systems; a score of 2 or more indicates a mortality risk of about 10%.\n• qSOFA is a BEDSIDE assessment outside the emergency room, with three criteria — respiratory rate 22/min or more, systolic pressure 100 mm Hg or less, and altered mentation.\n\nWhy five competing scores exist at all is the underlying point: no assessment or diagnostic criterion has sufficient sensitivity or specificity, because the damage in sepsis comes from the host response rather than from the pathogen, so there is no single defining organism and no single defining test.",
  {"0": "Level of consciousness is in both scores — as AVPU in MEWS and as consciousness level in NEWS2. The stem lists it among the current parameters, which is the cover-the-options clue that it cannot be the addition.",
   "2": "Respiratory rate is in both, and it is among the most useful early signs in either system — it is also the most sensitive early vital sign change in qSOFA, where the threshold is 22/min or more.",
   "3": "Systolic blood pressure is in both scores. Note that in qSOFA the threshold is 100 mm Hg or less rather than below 90, deliberately catching patients before frank hypotension.",
   "4": "Temperature is in both, and in both it is scored in BOTH directions — a temperature of 35°C and a temperature of 39°C each score badly, the same bidirectional logic that runs through the SIRS criteria."},
  "Both scoring systems check the same vital signs, with one exception: the newer one also measures the oxygen level in the blood.",
  exim="fig_slide_mews",
  excap="Lecture slide: MEWS scored out — five parameters, each weighted in both directions.")

# ── 2. The septic shock definition (§18) ─────────────────────────────────────
q("A 67-year-old man with pyelonephritis is admitted to the intensive care unit. On arrival his temperature is 38.9°C (102.0°F), pulse is 122/min, respirations is 26/min, and blood pressure is 82/44 mm Hg. He receives 30 mL/kg of crystalloid over 90 minutes. His blood pressure afterward is 84/46 mm Hg, and norepinephrine is started to maintain a mean arterial pressure of 65 mm Hg or more. Blood cultures are growing gram-negative rods.\n\nLaboratory studies show:\nLeukocyte count 19,200/mm3 (N=4,500–11,000/mm3)\nPlatelet count 92,000/mm3 (N=150,000–400,000/mm3)\nSerum creatinine 2.6 mg/dL (N=0.6–1.2 mg/dL)\nSerum lactate 4.8 mmol/L (N=0.5–2.2 mmol/L)\n\nWhich of the following best describes this patient's condition?",
  ["A. Bacteremia",
   "B. Early sepsis",
   "C. Multi-organ dysfunction syndrome",
   "D. Sepsis without shock",
   "E. Septic shock"],
  4,
  "The three terms form a strict hierarchy, and each step ADDS ONE REQUIREMENT:\n\n• Infection and bacteremia are RISK FACTORS — the setup, not the diagnosis.\n• SEPSIS is life-threatening, time-dependent ORGAN DYSFUNCTION caused by a dysregulated host response to infection.\n• SEPTIC SHOCK is a SUBSET of sepsis in which underlying CIRCULATORY AND CELLULAR/METABOLIC abnormalities are profound enough to SUBSTANTIALLY INCREASE MORTALITY.\n\nHe has both halves of that last definition. The circulatory abnormality is hypotension persisting after adequate fluid resuscitation and requiring a vasopressor. The cellular and metabolic abnormality is a lactate of 4.8 mmol/L. That is why septic shock is NOT SIMPLY HYPOTENSION — the metabolic derangement is part of the definition, and it is exactly why lactate sits in the treatment bundle rather than being an optional add-on.\n\nThe mortality figures behind the wording: 10% to 52% in patients with risk factors, against 90% survival in young, healthy patients. Septic shock can progress to multi-organ dysfunction syndrome, an older term, and organ failure in sepsis is SEQUENTIAL rather than simultaneous — which is precisely what the Sequential Organ Failure Assessment was built to track. The mechanism and the scoring system share the word for the same reason.",
  {"0": "Bacteremia is organisms in the blood, and it is listed as a RISK FACTOR for sepsis rather than a stage of it. He certainly has it — his cultures are positive — but naming it ignores the organ dysfunction and the shock physiology.",
   "1": "Early sepsis in this framework refers to the setup — infection and bacteremia as risk factors, before organ dysfunction appears. He is several steps past that, with a creatinine of 2.6 mg/dL, a platelet count of 92,000/mm3, and vasopressor-dependent hypotension.",
   "2": "Multi-organ dysfunction syndrome is the older term for the end of the road, reached when septic shock progresses. He has two failing organ systems and is being supported successfully; the term that fits his current physiology is the one defined by fluid-refractory hypotension plus a metabolic abnormality.",
   "3": "This would be the answer if fluids had restored his perfusion. They did not — his pressure was unchanged after 30 mL/kg and he now needs norepinephrine, with a lactate of 4.8 mmol/L. That combination is what moves a patient from sepsis into its shock subset."},
  "An infection is making his blood pressure drop, and filling him with fluid did not fix it — he needs a drug to hold his pressure up, and his tissues are so starved of oxygen that acid is building up. That specific combination has its own name.")

# ── 3. Post-sepsis syndrome (§18) ────────────────────────────────────────────
q("A 54-year-old woman comes to the office 3 months after a 2-week intensive care unit admission for septic shock from a perforated appendix, from which she recovered fully. She reports persistent fatigue, difficulty concentrating at work, poor sleep, and intrusive memories of the intensive care unit that provoke panic and breathlessness. She has been unable to return to her previous exercise routine. Her temperature is 36.8°C (98.4°F), pulse is 76/min, and blood pressure is 122/78 mm Hg. Physical examination shows no abnormalities; the surgical wound is well healed.\n\nLaboratory studies show:\nHemoglobin 12.8 g/dL (N=12.0–16.0 g/dL)\nLeukocyte count 7,200/mm3 (N=4,500–11,000/mm3)\nC-reactive protein 0.3 mg/dL (N=<1.0 mg/dL)\nThyroid-stimulating hormone 2.1 µU/mL (N=0.4–4.0 µU/mL)\n\nWhich of the following is the most likely explanation for her symptoms?",
  ["A. Adrenal insufficiency",
   "B. Occult recurrent intra-abdominal infection",
   "C. Post-sepsis syndrome",
   "D. Recurrent pulmonary embolism",
   "E. Untreated hypothyroidism"],
  2,
  "Post-sepsis syndrome affects about 50% OF SEPSIS SURVIVORS, and the striking thing about it — the reason it is worth a question — is how much of it is NEUROPSYCHIATRIC rather than physical. Post-traumatic stress, flashbacks, panic attacks and cognitive decline sit alongside the fatigue and deconditioning that people expect.\n\nHer picture is that syndrome in full: fatigue, impaired concentration, disturbed sleep, intrusive memories of the unit with panic symptoms, and loss of exercise tolerance — with a normal examination and normal inflammatory markers, which is what tells you the sepsis itself is over.\n\nThe surrounding numbers: mortality 10% to 52% in patients with risk factors, survival about 90% in the young and healthy, and a high re-hospitalization rate. In the United States there are roughly 1.7 million cases and about 350,000 deaths per year, at a cost of about $62 billion.\n\nThe clinical point is that surviving sepsis is not the end of the illness. Naming the syndrome matters, because it converts a patient's 'I should be over this by now' into a recognized consequence of critical illness with a management plan — rehabilitation, sleep, cognitive and psychological support.",
  {"0": "Critical illness-related adrenal insufficiency is real, and a baseline cortisol below 10 mg/dL appears on the sepsis laboratory panel. It presents acutely with hypotension and hyponatremia during the illness, not as intrusive memories and poor concentration 3 months later in a normotensive woman.",
   "1": "A missed intra-abdominal collection is a genuine concern after a perforated viscus and would deserve imaging if anything pointed to it. She is afebrile with a normal leukocyte count and a C-reactive protein of 0.3 mg/dL, and her wound is healed.",
   "3": "Recurrent pulmonary embolism would produce dyspnea and tachycardia, and her breathlessness with panic is a reasonable thing to consider. Her pulse, blood pressure and examination are normal, and her breathlessness comes with intrusive memories rather than with exertion.",
   "4": "Hypothyroidism causes exactly this fatigue-and-fog picture, which is why the thyroid-stimulating hormone was checked. It is 2.1 µU/mL, squarely normal."},
  "Surviving sepsis often leaves people exhausted, foggy and frightened for months afterwards — and about half of survivors go through it. Her tests are normal because the infection really is gone; this is the aftermath.",
  exim="fig_slide_post_sepsis",
  excap="Lecture slide: post-sepsis syndrome. Note how much of the list is neuropsychiatric rather than physical.")

# ══════════════════════════ §19 · HIV MICROBIOLOGY ══════════════════════════

# ── 4. Which protease cleaves which precursor (§19) ──────────────────────────
q("A 44-year-old man with HIV infection is treated with a regimen containing darunavir. Laboratory study of virions produced by his cells during therapy shows particles that contain uncleaved precursor proteins internally and are non-infectious, but whose surface glycoprotein spikes are normally processed and correctly assembled into their mature form.\n\nWhich of the following best explains why the drug does not prevent processing of the envelope precursor?",
  ["A. The envelope precursor is cleaved by a host cell protease",
   "B. The envelope precursor is cleaved by reverse transcriptase",
   "C. The envelope precursor is not cleaved before the virion buds",
   "D. The envelope precursor is synthesized only after the drug has been cleared",
   "E. The envelope proteins are encoded by the gag gene rather than by env"],
  0,
  "This is the cleanest mechanistic distinction in the section, and it is why protease inhibitors work at all.\n\nThe gag and pol precursors are cleaved by VIRAL protease — the p55 gag precursor into p24 (capsid), p17 (matrix) and p6/p7/p9 (nucleocapsid), and the pol products into reverse transcriptase, integrase and protease itself. Darunavir and atazanavir inhibit that enzyme, so those proteins are never cut, and the virions are released IMMATURE AND NON-INFECTIOUS. That is exactly what the experiment describes.\n\nThe env precursor is different. It is a 160 kDa protein cleaved by HOST protease into gp120, the binding protein that engages CD4 plus CCR5 or CXCR4, and gp41, the fusion protein carrying the fusogenic domain. A drug aimed at the viral enzyme has no effect on a host enzyme, so the spikes are processed normally.\n\nThe memory line: gag and pol are cut by VIRAL protease — which is why protease inhibitors work; env is cut by HOST protease — which is why they do not touch it.\n\nOne more property of the class worth carrying: protease inhibitors have a notably HIGH genetic barrier. Resistance is uncommon unless the patient was previously treated with a protease inhibitor — the opposite end of the spectrum from the NNRTIs, where a single point mutation can take out the whole class.",
  {"1": "Reverse transcriptase is an RNA-dependent DNA polymerase; it makes the proviral DNA and has no proteolytic activity at all. Its claim to fame is its HIGH ERROR RATE, which generates the variant pool that drug resistance is selected from.",
   "2": "The env precursor is very much cleaved — into gp120 and gp41 — and the stem states that the spikes are correctly processed and assembled. An uncleaved envelope would not produce functional spikes.",
   "3": "Pharmacokinetics do not explain the finding: the same virion shows uncleaved internal proteins and fully processed surface proteins AT THE SAME TIME. Any explanation has to account for both happening together, which only two different enzymes can do.",
   "4": "gp120 and gp41 are env products; the gag products are p24, p17 and p6/p7/p9. Getting that mapping backwards would also predict that protease inhibitors block envelope processing, which is the opposite of what is observed."},
  "The drug jams the virus's own pair of scissors. The internal parts stay stuck together and the virus cannot infect anything — but the outer spikes are cut by OUR scissors, which the drug does not touch.",
  exim="fig_slide_hiv_cycle",
  excap="Lecture slide: the HIV replication cycle. Maturation at step 5 is where viral protease cleaves the gag and gag/pol precursors.")

# ── 5. Integration and the latent reservoir (§19) ────────────────────────────
q("A 31-year-old woman with HIV infection has had an undetectable viral load for 4 years on a single-tablet regimen. She asks whether she can stop therapy now that the virus is 'gone.' She is told that if she stops, the virus will almost certainly return to detectable levels within weeks, no matter how long she has been suppressed, because a population of infected cells persists that current drugs cannot reach.\n\nWhich of the following steps in the viral replication cycle is responsible for this persistence?",
  ["A. Attachment of gp120 to the CD4 receptor",
   "B. Cleavage of precursor proteins by viral protease",
   "C. Fusion of the viral envelope with the cell membrane by gp41",
   "D. Integration of proviral DNA into the host cell genome",
   "E. Reverse transcription of viral RNA into double-stranded DNA"],
  3,
  "Integration is described as THE IRREVERSIBLE STEP. Integrase splices the proviral DNA into the host chromosome, and from that moment the infection is permanent in that cell and in every daughter cell it produces.\n\nThe consequence is LATENCY, one of the three properties that make HIV so difficult: the integrated provirus can sit TRANSCRIPTIONALLY SILENT, invisible to drugs that only target actively replicating virus. Antiretroviral therapy suppresses replication; it does not remove a provirus already written into the genome. That is why stopping therapy leads to rebound and why cure research targets the reservoir rather than the enzymes.\n\nThe other two properties in that trio: genetic diversity, because reverse transcriptase has a high error rate that directly generates resistance mutations; and the fact that HIV attacks the immune response itself, targeting CD4 T cells and macrophages — the very cells that would clear it.\n\nThe drug class aimed at this step is the INSTIs — raltegravir, and cabotegravir, which is also available as a long-acting injectable. They prevent STRAND TRANSFER of viral DNA into the host genome, and resistance arises through mutations that alter integrase structure and reduce drug binding. They prevent NEW integration events; they cannot undo one that has already happened.",
  {"0": "Attachment is step 1 and is entirely reversible — and it is drug-targetable, by fostemsavir binding gp120 and ibalizumab blocking the CD4 receptor after attachment. A virion that has attached but not entered establishes nothing.",
   "1": "Protease-mediated cleavage is step 5, maturation, which happens as the virion buds. Blocking it produces immature, non-infectious particles, but it takes place long after the cell's fate has been decided by integration.",
   "2": "Fusion via gp41 completes entry and is the target of enfuvirtide. Entry alone does not make a permanent infection; the genome still has to be reverse transcribed and then written into the host chromosome.",
   "4": "Reverse transcription is step 3, and it is essential — but the double-stranded DNA it produces is not yet part of the host genome. Unintegrated proviral DNA is relatively short-lived; it is the splicing into the chromosome that makes the infection permanent."},
  "The virus writes a copy of itself into the cell's own instruction manual. Those cells can go quiet for years, so the drugs have nothing to attack — and the moment the drugs stop, the instructions can be read again.",
  exim="fig_slide_hiv_cycle_drugs",
  excap="Lecture slide: the replication cycle with each drug class mapped to its step. Integration is the irreversible one.")

# ── 6. The pharmacokinetic enhancer (§19) ────────────────────────────────────
q("A 52-year-old man with HIV infection is prescribed a regimen consisting of darunavir, cobicistat, emtricitabine, and tenofovir alafenamide. He asks how each of his four medicines fights the virus. He is told that one of them has no direct antiviral activity at all.\n\nWhich of the following agents in his regimen has no direct antiviral activity?",
  ["A. Cobicistat",
   "B. Darunavir",
   "C. Dolutegravir",
   "D. Emtricitabine",
   "E. Tenofovir alafenamide"],
  0,
  "Cobicistat, like ritonavir, is a PHARMACOKINETIC ENHANCER — a 'booster.' It inhibits CYP3A4, slowing the metabolic breakdown of the antiretroviral it is paired with and raising that drug's levels. It is NOT an antiretroviral itself, and that is flagged explicitly as a classic distractor.\n\nIt is also the source of the drug interaction most worth remembering. Because the boost works by inhibiting CYP3A4, anything else cleared by CYP3A4 accumulates. Combine a booster with an OVER-THE-COUNTER INTRANASAL CORTICOSTEROID and the steroid builds up, producing iatrogenic Cushing syndrome and adrenal suppression. Nasal steroids are sold over the counter, so if you do not warn the patient, no one will. The same pathway governs several statins, which is why atorvastatin, low-dose rosuvastatin or pitavastatin are favoured in people with HIV.\n\nThe rest of his regimen maps onto the cycle: darunavir is a protease inhibitor acting at maturation, and emtricitabine and tenofovir alafenamide are NRTIs — competitive inhibitors of reverse transcriptase that cause chain termination, typically used in pairs.\n\nThe practical instruction that follows: ask about over-the-counter drugs, supplements and herbal preparations at EVERY visit. Patients do not volunteer them, because they do not think of them as medicines.",
  {"1": "Darunavir is a protease inhibitor. It prevents viral protease from cleaving the gag and gag/pol precursors, so released virions are immature and non-infectious — a direct antiviral action at step 5 of the cycle.",
   "2": "Dolutegravir is an integrase strand transfer inhibitor and is directly antiviral — though note it is not actually part of this patient's regimen, which is worth catching on a careful read.",
   "3": "Emtricitabine is a nucleoside reverse transcriptase inhibitor, binding competitively at the active site and terminating the growing DNA chain. It also treats hepatitis B, which is why hepatitis B status must be known before it is stopped.",
   "4": "Tenofovir alafenamide is an NRTI, an adenosine analogue. It is the less nephrotoxic of the two tenofovir formulations — both are toxic to the proximal tubule and can cause Fanconi syndrome, which is why the alafenamide form was developed."},
  "Three of his pills attack the virus. The fourth attacks nothing — it slows down the liver enzyme that would otherwise destroy one of the other drugs, so that drug lasts longer.")

# ── 7. JC virus and progressive multifocal leukoencephalopathy (§19) ─────────
q("A 46-year-old man with AIDS who has not taken antiretroviral therapy for 3 years comes to the emergency department because of 6 weeks of progressive right-sided weakness, difficulty finding words, and clumsiness of the right hand. He has had no fever, headache, or seizures. His temperature is 36.9°C (98.2°F), pulse is 78/min, and blood pressure is 128/80 mm Hg. Neurologic examination shows expressive aphasia, right hemiparesis, and right-sided dysmetria. MRI of the brain shows confluent, non-enhancing white matter lesions without mass effect. His CD4 lymphocyte count is 52/µL (N=500–1,500/µL). Cerebrospinal fluid shows 2 leukocytes/mm3, a normal glucose concentration, and a protein concentration of 44 mg/dL.\n\nWhich of the following is the most likely causal agent?",
  ["A. Cytomegalovirus",
   "B. Epstein-Barr virus",
   "C. Human herpesvirus 8",
   "D. JC virus",
   "E. Toxoplasma gondii"],
  3,
  "JC virus, a POLYOMAVIRUS, causes PROGRESSIVE MULTIFOCAL LEUKOENCEPHALOPATHY — a DEMYELINATING disease of white matter. The imaging signature is what separates it from everything else on this list: confluent white matter lesions that do NOT enhance and produce NO mass effect, in a patient with a bland cerebrospinal fluid and no fever. The deficits accumulate over weeks, exactly as described.\n\nThe neoplastic and preneoplastic tier of opportunistic disease is a short list of ONCOGENIC VIRUSES that an intact immune system would normally hold in check, and it is worth reciting as pairs:\n• HHV-8 → Kaposi sarcoma, initially flat and red, becoming raised, darker and purple\n• Epstein-Barr virus (HHV-4) → B-cell lymphoma, Hodgkin and non-Hodgkin, and oral hairy leukoplakia\n• JC virus → progressive multifocal leukoencephalopathy\n• HPV types 16 and 18 → cervical, anal and oral squamous cell carcinoma\n• Cytomegalovirus (HHV-5) → retinitis, pneumonia, gastrointestinal disease, encephalitis\n• Herpes simplex 1 and 2 → chronic oral, genital and anal lesions, pneumonitis and esophagitis, with multinucleated giant cells as the histologic hallmark\n• Varicella-zoster (HHV-3) → shingles on reactivation\n• HIV itself → HIV encephalitis\n\nThe management point is the same one that governs every advanced opportunistic infection here: there is no specific antiviral for JC virus, and the treatment is immune reconstitution with antiretroviral therapy — while anticipating that reconstitution may itself provoke IRIS.",
  {"0": "Cytomegalovirus is the CD4 below 50/µL organism, and it does cause encephalitis as well as retinitis, esophagitis and enteritis. Its encephalitis is typically periventricular with enhancement and a cerebrospinal fluid pleocytosis, and it usually arrives alongside retinitis or gastrointestinal disease.",
   "1": "Epstein-Barr virus drives primary CNS lymphoma in advanced HIV, which is on the CD4 below 50/µL list with focal deficits, seizures and confusion. Lymphoma produces ENHANCING mass lesions with surrounding edema, not confluent non-enhancing demyelination.",
   "2": "Human herpesvirus 8 causes Kaposi sarcoma. It produces the cutaneous, mucosal and visceral vascular lesions — including the pulmonary and gastrointestinal disease that can be life-threatening — but not a progressive white matter demyelinating illness.",
   "4": "Toxoplasma gondii encephalitis is the CD4 below 100/µL diagnosis and the commonest cause of focal brain lesions in AIDS. Its signature is multiple RING-ENHANCING lesions with mass effect and edema, usually with headache and often fever — the opposite imaging pattern to this."},
  "A virus that most people carry harmlessly has started destroying the insulation around the nerve fibres in his brain. It causes no swelling and no fever — the scan just shows patches of white matter quietly being stripped away.",
  exim="fig_pml_brain",
  excap="Gross brain specimen: the demyelinating white matter change of progressive multifocal leukoencephalopathy.")

# ══════════════════════════ §20 · HIV CLINICAL ══════════════════════════

# ── 8. The live vaccine rule (§20) ───────────────────────────────────────────
q("A 28-year-old man with HIV infection comes to the office to update his immunizations before a trip. He started antiretroviral therapy 6 weeks ago. He has never had chickenpox or shingles and has no documentation of childhood measles immunization. His temperature is 36.8°C (98.2°F), pulse is 74/min, and blood pressure is 120/76 mm Hg. Physical examination shows no abnormalities.\n\nLaboratory studies show:\nCD4 lymphocyte count 140/µL (N=500–1,500/µL)\nHIV RNA 8,400 copies/mL (N=undetectable)\n\nWhich of the following vaccines may be administered today?",
  ["A. Live attenuated zoster vaccine",
   "B. Measles, mumps, and rubella vaccine",
   "C. Recombinant zoster vaccine",
   "D. Varicella vaccine",
   "E. Yellow fever vaccine"],
  2,
  "The live vaccine rule is a two-part threshold, and both halves are worth knowing because they explain the rule rather than just stating it.\n\nThe three LIVE vaccines — VARICELLA, YELLOW FEVER, and MMR — may be given only when the CD4 count is 200 cells/µL OR MORE. Two reasons: the risk of VACCINE-STRAIN DISEASE in a patient who cannot contain a live organism, and the fact that below that threshold the patient CANNOT MOUNT AN IMMUNOLOGIC RESPONSE anyway, so you are wasting the dose. His CD4 count is 140/µL, so all three are deferred until his count rises on therapy.\n\nZoster is the one where the two products diverge. The old LIVE ATTENUATED zoster vaccine is contraindicated in immunocompromised patients and in HIV with a CD4 below 200/µL. The RECOMBINANT vaccine, given as two doses, is the one to use in immunocompromised patients — including all transplant recipients — and it is not live, so the CD4 threshold does not apply.\n\nGive REGARDLESS of CD4 count: mpox, Tdap, COVID-19, influenza, hepatitis A, hepatitis B, and recombinant zoster.\n\nHis CD4 count should be rechecked in a few months; with an effective regimen it will rise, and the deferred live vaccines can then be given.",
  {"0": "The live attenuated zoster vaccine is precisely the product that is contraindicated here — it is contraindicated in immunocompromised patients generally and specifically in HIV with a CD4 count below 200/µL. The recombinant version exists to solve this problem.",
   "1": "MMR is one of the three live vaccines and requires a CD4 count of 200/µL or more. His documented lack of measles immunity is a real problem worth solving, but it is solved after immune reconstitution, not today.",
   "3": "Varicella vaccine is live, and he has no history of chickenpox, so he genuinely needs it. At a CD4 of 140/µL it carries a risk of vaccine-strain disease and would probably fail to produce an immune response.",
   "4": "Yellow fever vaccine is live and is the third member of the restricted trio — relevant here because he is travelling. If his destination requires it, the trip may need to be deferred until his CD4 count exceeds 200 cells/µL."},
  "Some vaccines contain a weakened but living germ. His immune system is too weak to handle even a weakened germ, and too weak to learn from it. The shingles vaccine that contains no living virus is the one he can have now.",
  exim="fig_slide_hiv_vaccines",
  excap="Lecture slide: vaccine timing in people with HIV, by CD4 count.")

# ── 9. Undetectable equals untransmittable (§20) ─────────────────────────────
q("A 35-year-old man with HIV infection has taken a single-tablet antiretroviral regimen for 14 months. His HIV RNA has been below the limit of detection at every measurement for the past 11 months, and his CD4 count has risen from 310 to 620 cells/µL. He is in a relationship with an HIV-negative partner and asks about the risk of transmitting the virus during condomless sex. He reports taking every dose.\n\nWhich of the following statements is the most appropriate counseling?",
  ["A. He can transmit the virus only during an intercurrent viral blip",
   "B. His partner must take post-exposure prophylaxis after each encounter",
   "C. His risk of sexual transmission is effectively zero while his viral load remains undetectable",
   "D. His risk of sexual transmission is reduced by approximately 50%",
   "E. Transmission risk is unchanged by antiretroviral therapy"],
  2,
  "Undetectable equals untransmittable. The evidence is the PARTNER trial, which followed male-female and male-male couples — roughly 3,000 individuals — across MORE THAN 74,000 CONDOMLESS SEX EPISODES and recorded ZERO HIV TRANSMISSIONS to HIV-negative partners while the partner with HIV maintained a durable undetectable viral load for 6 MONTHS OR MORE. He has had 11 months of undetectable results, so he meets that condition comfortably.\n\nThe threshold that defines 'undetectable' for this purpose is a plasma HIV RNA BELOW 200 COPIES/mL, which is the CDC's number.\n\nThis is also the cleanest illustration of the two-variable framework the whole section rests on:\n• The CD4 count measures the degree of immune impairment. It is the STAGING variable and determines opportunistic infection risk and who needs prophylaxis.\n• The HIV RNA viral load measures active replication. It is the TRANSMISSION variable, and it drives drug selection and monitors treatment response. U = U is a statement about the viral load, not about the CD4 count.\n\nCheck viral load every 3 to 4 months. Small temporary rises — 'blips' — are not immediately alarming; follow the trend rather than reacting to one value.",
  {"0": "This overstates what a blip means. Blips are small transient rises that are not immediately alarming and are managed by following the trend; treating them as windows of danger misrepresents both the biology and the trial evidence, and it would make the counseling useless in practice.",
   "1": "Post-exposure prophylaxis is for people who may have been exposed — sexual assault, an occupational needlestick, shared injection equipment — and is started within 72 hours and taken for a month. Recommending it after every encounter with a durably suppressed partner is unnecessary and unsustainable.",
   "3": "A roughly 50% reduction is far below what treatment achieves and would represent a meaningful residual risk. The PARTNER trial recorded no transmissions at all across more than 74,000 condomless episodes under durable suppression.",
   "4": "This is simply wrong, and the belief is harmful: it is the reason many people with HIV expect to be permanently infectious. Suppressing replication to undetectable levels removes sexual transmission."},
  "When the medication keeps the virus at a level too low to measure for at least six months, he cannot pass it on to his partner through sex. A very large study followed thousands of couples and found no transmissions at all.")

# ── 10. The needlestick and the 72-hour window (§20) ─────────────────────────
q("A third-year medical student sustains a deep puncture from a hollow-bore needle while assisting in the operating room. The needle had been used to draw blood from a patient whose HIV status is not documented in the chart; the patient has a history of injection drug use. The student washes the wound and notifies the attending surgeon, who reports the exposure to employee health. Source-patient testing has been sent and results are expected in about 36 hours. The student's own baseline HIV serology is drawn and is pending.\n\nWhich of the following is the most appropriate next step in management?",
  ["A. Await the source patient's test results before deciding on therapy",
   "B. Begin a three-drug antiretroviral regimen now",
   "C. Begin emtricitabine and tenofovir only if the source patient tests positive",
   "D. Obtain repeat serology in 3 months without starting therapy",
   "E. Start pre-exposure prophylaxis"],
  1,
  "The rule is that the 72-HOUR WINDOW is what matters: start post-exposure prophylaxis as soon as possible, and CONSIDER STARTING IT WHILE RESULTS ARE PENDING. Do not wait for the source patient's result. The example regimen given is TENOFOVIR PLUS EMTRICITABINE WITH RALTEGRAVIR — three drugs — taken for a month. If the source turns out to be HIV-negative, the prophylaxis is simply stopped, having cost 36 hours of a well-tolerated regimen.\n\nThe steps after a needlestick on a rotation, in order: notify the surgeon immediately, notify human resources and employee health, get tested, and consider starting post-exposure prophylaxis while results are pending. The student has done the first three.\n\nPEP reduces risk to roughly BELOW 1% when taken correctly — but it is explicitly not always effective, which is another reason not to lose hours at the front of the window. The exposure here is high-risk on every axis: a deep injury, a hollow-bore needle, and a source with a history that raises the pre-test probability.\n\nPrEP is the other half of the pair and a different thing entirely: taken BEFORE exposure by people at ongoing risk, reducing sexual transmission by about 99% and injection-drug transmission by about 74%.",
  {"0": "Waiting is the intuitive answer and the wrong one. Post-exposure prophylaxis works best the earlier it is given, and 36 hours is a large fraction of the 72-hour window spent doing nothing; if the source is positive, those hours cannot be recovered.",
   "2": "This is the same delay wearing different clothes, and it also names an incomplete regimen. The example post-exposure regimen is three drugs — tenofovir and emtricitabine plus raltegravir — not a two-drug backbone.",
   "3": "Serial serology is the monitoring plan that accompanies an exposure, not a substitute for treating it. Following the student to seroconversion without offering prophylaxis forgoes the intervention that reduces the risk to below 1%.",
   "4": "Pre-exposure prophylaxis is taken before an exposure by someone at ongoing risk, and it is a different regimen and a different clinical situation. The exposure here has already happened, which makes this post-exposure prophylaxis by definition."},
  "The clock starts the moment the needle goes in, and the medicine works best when started fast. He should start it now — if the patient's test comes back negative in a day and a half, he simply stops.",
  exim="fig_slide_prep_pep",
  excap="Lecture slide: PrEP versus PEP — before exposure or after, and the 72-hour window that governs the second.")

# ── 11. The booster and the over-the-counter steroid (§20) ───────────────────
q("A 49-year-old woman with HIV infection has taken darunavir boosted with cobicistat, emtricitabine, and tenofovir alafenamide for 3 years, with an undetectable viral load. She comes to the office because of 4 months of weight gain, easy bruising, and facial puffiness. She takes no prescription medications other than her antiretroviral regimen, but on direct questioning reports that she has used an over-the-counter intranasal corticosteroid spray daily for the past 5 months for allergic rhinitis. Her blood pressure is 152/94 mm Hg and her BMI has increased by 4 kg/m2. Physical examination shows facial rounding, supraclavicular fullness, central adiposity, and thin skin with purple abdominal striae.\n\nLaboratory studies show:\nFasting plasma glucose 138 mg/dL (N=70–99 mg/dL)\nSerum potassium 3.2 mEq/L (N=3.5–5.0 mEq/L)\nMorning serum cortisol 1.4 µg/dL (N=6–23 µg/dL)\nPlasma adrenocorticotropic hormone 4 pg/mL (N=10–60 pg/mL)\n\nWhich of the following is the most likely explanation for her findings?",
  ["A. Adrenal insufficiency from cytomegalovirus adrenalitis",
   "B. Corticotroph adenoma of the pituitary gland",
   "C. Cortisol-secreting adrenal adenoma",
   "D. Iatrogenic Cushing syndrome from impaired metabolism of the intranasal corticosteroid",
   "E. Lipodystrophy from long-term antiretroviral therapy"],
  3,
  "Cobicistat boosts darunavir by INHIBITING CYP3A4. Intranasal corticosteroids are cleared by CYP3A4. Put them together and the steroid accumulates to systemic concentrations, producing IATROGENIC CUSHING SYNDROME AND ADRENAL SUPPRESSION.\n\nThe laboratory pattern proves the source is exogenous: she is clinically cushingoid, yet her morning cortisol is 1.4 µg/dL and her ACTH is 4 pg/mL. Both are LOW because the absorbed drug is suppressing her own axis while producing the phenotype — an endogenous cause would raise one or the other.\n\nThe teaching point attached to this is a practical one: nasal steroids are sold OVER THE COUNTER, so if you do not warn the patient, no one will. She reported it only on direct questioning, which is exactly the behaviour described — patients do not volunteer supplements, herbal preparations and over-the-counter drugs, because they do not think of them as medicines. Ask at every visit.\n\nThe same CYP3A4 pathway governs several statins, which matters because people with HIV present with coronary artery disease roughly 10 years earlier, standard risk calculators UNDERESTIMATE their risk by a factor of 1.5 to 2, and many are targeted to an LDL below 70 mg/dL. The statins favoured in this population are atorvastatin, low-dose rosuvastatin, and pitavastatin.\n\nManagement is to stop the nasal steroid with taper planning — her axis is suppressed and cannot respond acutely — and to review every other CYP3A4 substrate she takes.",
  {"0": "Cytomegalovirus adrenalitis does occur in advanced AIDS and causes adrenal insufficiency, which fits her low cortisol. It would produce weight LOSS, hypotension, hyperkalemia and a HIGH ACTH as the pituitary drove a failing gland — the opposite of her ACTH of 4 pg/mL and her cushingoid habitus.",
   "2": "An adrenal adenoma making cortisol would produce this phenotype with a HIGH cortisol and a suppressed ACTH. Her cortisol is 1.4 µg/dL, which excludes endogenous overproduction from any source.",
   "1": "A pituitary corticotroph adenoma — Cushing disease — produces the same phenotype with a HIGH or inappropriately normal ACTH driving a high cortisol. Both of her values are low.",
   "4": "Antiretroviral lipodystrophy is common, affecting about half of patients, and it does produce facial change, dorsocervical fat and abdominal lipohypertrophy — so this is a genuinely tempting answer. It does not cause purple striae, thin skin, hypokalemia, or a suppressed cortisol and ACTH."},
  "One of her HIV pills works by slowing down a liver enzyme. That same enzyme is what clears the steroid in her nasal spray — so the spray has been building up in her body for months and is acting like a steroid tablet.")

# ══════════════════════════ §21 · VECTOR-BORNE INFECTIONS ══════════════════════════

# ── 12. The strain-specificity problem (§21) ─────────────────────────────────
q("A 33-year-old nurse working in an Ebola treatment unit in eastern Democratic Republic of the Congo develops fever, severe headache, myalgia, vomiting, and watery diarrhea. On day 7 of illness a maculopapular rash appears on her face and spreads to her neck and upper trunk. She received the licensed recombinant vesicular stomatitis virus-vectored Ebola vaccine 2 years ago and has documentation of a complete course. The outbreak strain in her region has been identified as Bundibugyo ebolavirus.\n\nWhich of the following best explains why she developed the infection despite vaccination?",
  ["A. The vaccine protects against the Zaire strain, and the outbreak strain differs",
   "B. The vaccine requires a booster dose every 6 months to remain protective",
   "C. The vaccine targets the nucleoprotein rather than the surface glycoprotein",
   "D. The vaccine was inactivated by a failure of the cold chain",
   "E. The vaccine's viral vector does not replicate in immunocompetent recipients"],
  0,
  "Every licensed Ebola product — the vaccine ERVEBO and the two monoclonal antibodies INMAZEB and EBANGA — was built against the ZAIRE glycoproteins, because Zaire ebolavirus was what was rampant when they were developed. In an outbreak caused by BUNDIBUGYO there is VERY LITTLE CROSS-PROTECTION, whether the person received monoclonals or the vaccine. If a question asks why a vaccinated patient still got Ebola, STRAIN MISMATCH is the answer.\n\nThe strains worth knowing: Zaire ebolavirus is the most virulent and is what every licensed product targets; Sudan ebolavirus; Taï Forest ebolavirus, named for the forest in Côte d'Ivoire; and Bundibugyo, the strain in the current outbreak — which is exactly why the Zaire-directed treatments are failing. Bundibugyo-specific candidates are in trials, an AstraZeneca viral-vector vaccine and a Moderna mRNA vaccine.\n\nErvebo itself is a live attenuated recombinant vaccine in which the vesicular stomatitis virus glycoprotein genes are REPLACED with Ebola glycoprotein genes — the same platform proposed for Lassa. Note that vesicular stomatitis virus is a RHABDOVIRUS, the family that includes rabies.\n\nHer management is early supportive care and rehydration — symptomatic treatment always improves survival — with remdesivir, which inhibits the viral RNA polymerase, and pan-Ebola monoclonals as experimental options. Confirm with antigen or antibody capture followed by RT-PCR.\n\nHer day 6 to 7 rash following the face, then neck and upper trunk, then arms and legs, is the expected course — and it is harder to see on darker skin, which is a real diagnostic error rather than a theoretical one.",
  {"1": "There is no 6-month booster schedule for this vaccine, and the failure here is not one of waning titre. The problem is which antigen the immune response was raised against, not how much of that response remains.",
   "2": "Ervebo carries the Ebola SURFACE GLYCOPROTEIN genes, which is the whole design — the same spike-protein logic used by the monoclonals Inmazeb and Ebanga. Nucleoprotein-directed immunity would not neutralize an incoming virion.",
   "3": "Cold chain failure is a real-world cause of vaccine failure and worth considering in a field setting. It would not produce the pattern the question is built on, in which the vaccine works against one strain and not another, and the stem specifies a documented complete course.",
   "4": "The vesicular stomatitis virus vector is live attenuated and does replicate, which is how it expresses Ebola glycoprotein and raises an immune response. If it did not, the vaccine would never have protected anyone."},
  "Her vaccine was built to match one particular strain of Ebola. The strain circulating now is a different one, and the protection barely carries across.",
  exim="fig_filovirus_em",
  excap="Filovirus on electron micrograph — the classic filament with a shepherd's crook at one end.")

# ── 13. Cat scratch disease and the real inoculum (§21) ──────────────────────
q("A 7-year-old girl is brought to the office because of a tender lump on the side of her neck for 10 days and low-grade fevers. Three weeks ago the family adopted a kitten, which scratched her on the right cheek during play. Her temperature is 37.9°C (100.2°F), pulse is 96/min, and blood pressure is 96/62 mm Hg. Physical examination shows a small crusted papule on the right cheek along a healed scratch line and a tender, mobile 3-cm right cervical lymph node with overlying erythema. A photograph of the neck is shown. The remainder of the examination shows no abnormalities.\n\nWhich of the following is the infectious material that was inoculated by the scratch?",
  ["A. Bacteria carried in the cat's saliva and transferred to the claws by grooming",
   "B. Bacteria within flea feces contaminating the cat's fur and claws",
   "C. Bacteria within the cat's blood on the surface of the claws",
   "D. Fungal spores carried on the cat's fur",
   "E. Viral particles shed in the cat's dander"],
  1,
  "The detail that makes the mechanism click: the organism is NOT living on the cat's claws. Bartonella henselae is in the FLEA FECES, which contaminates the fur and claws during grooming and scratching. THE CLAW IS THE DELIVERY NEEDLE, NOT THE SOURCE.\n\nThat is why FLEA CONTROL ON THE CAT IS GENUINE PREVENTION, and why the CDC diagram of this disease spends most of its space on the flea rather than the cat. Cat-to-cat spread is by the CAT FLEA; cat-to-human is the scratch, or a bite via saliva.\n\nHer presentation is textbook: children under 10 (rough play, more scratches), kittens as the most likely source, incubation 3 to 10 days — short enough that the patient still remembers the scratch — then the three stages. First a cutaneous papule at the scratch site, which may pustulate, over 3 to 14 days. Then REGIONAL LYMPHADENOPATHY draining that site, in the head, neck or upper extremity, over 1 to 3 weeks. Then, uncommonly in the immunocompetent, systemic infection over another 2 to 4 weeks.\n\nDiagnosis: DO NOT CULTURE. The organism is fastidious and takes weeks — anything that takes 2 or 3 weeks to grow is not a useful test. Send EIA or ELISA for IgG and IgM; PCR of node material is definitive; the Warthin–Starry silver stain shows the organisms black. Treat with AZITHROMYCIN, adding rifampin if severe, which realistically only shortens a self-limiting 5- to 6-week illness. Prognosis is very good.\n\nTwo traps set on purpose: it is Bartonella, NOT Bordetella (a different genus entirely — B. pertussis is whooping cough), and it is cat scratch DISEASE, not cat scratch fever.",
  {"0": "Saliva is a genuine route — a cat BITE transmits via saliva — so this is not absurd. The inoculum in a scratch is flea dirt on the claws rather than saliva transferred by grooming, and getting that right is what makes flea control the preventive measure.",
   "2": "The claws carry contaminated flea feces, not the cat's blood. Bartonella does cause a bacteremia in cats, but the material delivered into a human scratch wound is the flea dirt on the claw surface.",
   "3": "Fungal spores on fur would suggest dermatophytosis — ringworm — which produces annular scaly skin lesions rather than an inoculation papule with tender regional adenopathy. Bartonella henselae is a gram-negative COCCOBACILLUS.",
   "4": "No virus is involved. Worth noting the coccobacillus list that this organism belongs to, because examiners like to drop the word: Bartonella (cat scratch disease, bacillary angiomatosis, trench fever, culture-negative endocarditis), Haemophilus, and Bordetella."},
  "The germ does not live on the cat's claws. It lives in flea droppings in the cat's fur, and the claw just pushes those droppings into the skin. That is why treating the cat's fleas actually prevents this.",
  image="fig_csd_node",
  imcap="The child's neck at presentation.",
  exim="fig_warthin_starry",
  excap="Warthin–Starry silver stain: the organisms take up the silver and appear black. Argyrophilic organisms are a short list — Bartonella, spirochetes, Legionella and Helicobacter pylori.")

# ── 14. Secondary plague pneumonia (§21) ─────────────────────────────────────
q("A 46-year-old man from rural Colorado was admitted 3 days ago with fever and an exquisitely tender inguinal mass, and gentamicin was started for bubonic plague confirmed by rapid antigen testing. Today he develops a productive cough with bloody, frothy sputum and worsening dyspnea. His temperature is 39.4°C (102.9°F), pulse is 130/min, respirations are 34/min, and blood pressure is 88/50 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 84%. A chest radiograph is shown. He is in a shared four-bed ward.\n\nWhich of the following is the most appropriate infection control measure?",
  ["A. Contact precautions alone, since the organism is transmitted by fleas",
   "B. Droplet and airborne precautions for the patient, with prophylaxis for exposed contacts",
   "C. Insecticide treatment of the patient's clothing and bedding alone",
   "D. No additional precautions, since he did not acquire the infection by inhalation",
   "E. Standard precautions alone, with vector control in his home community"],
  1,
  "He has developed SECONDARY plague pneumonia — hematogenous spread from bubonic plague, where organisms reach the lymph, then the blood, then are filtered through the lungs. It takes a couple of days longer than primary disease to appear and is preceded by the bubonic picture, exactly as here.\n\nThe infection control point is the one people get wrong: SECONDARY PLAGUE PNEUMONIA ALSO SPREADS BY AEROSOL. You do not need exposure to a 'pneumonic plague' case to catch pneumonic plague — a bubonic case that has progressed is enough. He is in a shared ward and is now an aerosol source for everyone in it.\n\nThat chain is why the 14th century was so catastrophic, and it is worth reciting as a sequence: bubonic plague → secondary plague pneumonia in that patient → they aerosolize the organism → the next person inhales it and develops PRIMARY plague pneumonia, which is 100% fatal untreated within days and is itself highly transmissible. A flea-borne disease becomes an airborne one.\n\nPrimary versus secondary: primary follows DIRECT INHALATION, with a very short incubation of 1 to 3 days and sudden fever, chills, headache, tachypnea, dyspnea, hypoxia and hemoptysis, progressing to bilateral multilobar hemorrhagic consolidation with bloody frothy sputum. Both forms carry about 50% mortality treated and 100% untreated.\n\nAnd one thing that should raise an alarm rather than a treatment question: naturally occurring plague shows very little drug resistance, so a HIGHLY RESISTANT isolate suggests human alteration. Notify public health immediately.",
  {"0": "Contact precautions address the flea and the bubo aspirate, and would have been reasonable on admission. They do not address a patient who is now coughing bloody sputum containing Yersinia pestis into a shared ward.",
   "2": "Insecticide treatment of clothing addresses the vector that started the illness and is part of the environmental response. It does nothing about person-to-person aerosol spread from an established pneumonia.",
   "3": "This is the specific misconception the lecture warns against. How he ACQUIRED the infection does not determine how he TRANSMITS it — secondary plague pneumonia spreads by aerosol just as primary plague pneumonia does.",
   "4": "Vector control in his community is appropriate public health follow-up for a rodent-associated case, and plague is endemic in at least 17 mostly western states. It leaves the immediate hazard — the three other patients in his ward — entirely unaddressed."},
  "The bacteria in his swollen gland have spread through his blood into his lungs, and now he coughs them out. Anyone nearby can breathe them in and get the fast, lethal lung form — so he needs to be isolated and his contacts given antibiotics.",
  image="fig_plague_cxr",
  imcap="Chest radiograph at the time of deterioration.",
  exim="fig_bubo",
  excap="The bubo that preceded it — the presentation 3 days earlier.")

# ── 15. Why RTS,S targets the sporozoite (§21) ───────────────────────────────
q("A physician working on a childhood immunization programme in sub-Saharan Africa is asked to explain how the malaria vaccine RTS,S/AS01 works. The vaccine consists of Plasmodium falciparum surface proteins produced recombinantly in yeast and fused to hepatitis B surface protein as a carrier, combined with an adjuvant containing a lipopolysaccharide-derived component and a saponin from the Chilean soapbark tree.\n\nThe antibodies raised by this vaccine act against which of the following parasite stages, and why is that stage chosen?",
  ["A. Gametocytes taken up by the mosquito, so that onward transmission is blocked",
   "B. Hepatic schizonts, so that merozoites are not released into the blood",
   "C. Merozoites in the blood, so that red cells cannot be invaded",
   "D. Ring forms inside red cells, so that the erythrocytic cycle is shortened",
   "E. Sporozoites in the blood, before they reach the hepatocyte"],
  4,
  "The sporozoite is the BOTTLENECK, and that is the entire logic of the vaccine.\n\nA female Anopheles deposits sporozoites into the dermis. They travel by blood and lymphatics to the LIVER — the exo-erythrocytic or pre-erythrocytic stage — where they invade hepatocytes and form SCHIZONTS, each containing THOUSANDS UPON THOUSANDS OF MEROZOITES. Neutralizing antibody at the sporozoite stage stops the parasite IN THE BLOOD BEFORE IT REACHES THE LIVER, cutting the life cycle before ANY AMPLIFICATION OCCURS. Once the erythrocytic stage begins the burden is orders of magnitude larger and antibody is facing a vastly bigger target population.\n\nThat liver stage is also what distinguishes Plasmodium from Babesia, which is the structural comparison worth holding. Both are deposited at a bite site and both multiply inside red cells producing ring forms. Only Plasmodium has an obligatory PRE-ERYTHROCYTIC LIVER STAGE — Babesia goes straight from the dermis to the red cell. The liver phase is silent, which is why malaria has a 1- to 4-week incubation.\n\nTwo details from the vaccine's own name: the hepatitis B surface protein is PURELY A CARRIER — scaffolding, not a target, with nothing special about the hepatitis B itself. And the AS01 adjuvant is the same family used in Shingrix, which is why both shots hurt: the reactogenicity is the ADJUVANT, not the antigen.\n\nOne caution on the number. In class the protection was given as about 80% to 90%; published phase 3 efficacy is substantially lower, on the order of 30% to 50% against clinical malaria in the first year and declining thereafter, which is why it is deployed alongside bed nets and chemoprevention. If a board question asks, the lower figure is the defensible one.",
  {"0": "Transmission-blocking vaccines that target gametocytes taken up by the mosquito are a real strategy and a genuine area of research — they protect the community rather than the recipient. RTS,S is not one of them; it is designed to protect the vaccinated child.",
   "1": "Attacking the hepatic schizont means attacking AFTER a single sporozoite has already become thousands of merozoites, and antibody does not readily reach a parasite inside a hepatocyte. The point of the sporozoite target is to act before that amplification.",
   "2": "Blood-stage vaccines directed at merozoites have been pursued and are hard: once the erythrocytic stage is established the parasite burden is enormous, and this is the stage that makes the patient sick rather than the stage that establishes infection.",
   "3": "Ring forms sit INSIDE red cells, where antibody cannot follow. This is also the stage the drugs attack — chloroquine works there by blocking the conversion of toxic heme to inert hemozoin."},
  "The mosquito injects only a handful of parasites, and each one turns into thousands once it reaches the liver. The vaccine tries to catch them in that brief window while there are still only a few of them.",
  exim="fig_slide_malaria_cycle",
  excap="The Plasmodium life cycle. The vaccine attacks at the narrowest point — the sporozoites travelling to the liver.")

# ══════════════════════════ §22 · VIRAL HEMORRHAGIC FEVERS ══════════════════════════

# ── 16. Dengvaxia and the prior-infection prerequisite (§22) ─────────────────
q("A 12-year-old boy is moving with his family to Puerto Rico, where dengue is endemic. His parents ask about the dengue vaccine. He has never had a febrile illness consistent with dengue and has never travelled outside the continental United States. Serologic testing for prior dengue infection is negative. He is otherwise healthy, his immunizations are up to date, and physical examination shows no abnormalities.\n\nWhich of the following is the most appropriate advice regarding vaccination?",
  ["A. Administer the vaccine now, because seronegative children derive the greatest benefit",
   "B. Administer the vaccine now, with a booster dose in 6 months",
   "C. Administer the vaccine only if prior dengue infection can be documented",
   "D. The vaccine is contraindicated in anyone younger than 18 years of age",
   "E. Vaccination removes the need for mosquito avoidance measures"],
  2,
  "The single most examinable fact about Dengvaxia is that it is indicated ONLY for people with DOCUMENTED PRIOR DENGUE INFECTION. Do not give it to someone who has never had dengue — in the dengue-naive, the course of a subsequent infection can be rougher. A vaccine with a PRIOR INFECTION PREREQUISITE is unusual enough to be worth a question on its own, and his negative serology is the answer key.\n\nDengvaxia was FDA-approved in 2019 and is live attenuated, tetravalent and recombinant: the backbone is the ATTENUATED YELLOW FEVER VACCINE VIRUS, with inserted genes encoding the surface proteins of ALL FOUR DENV serotypes.\n\nWhat to advise instead: VECTOR CONTROL is the mainstay of dengue prevention, and it is the strategy precisely because the reservoir is people. No animal reservoir has been identified in the Western Hemisphere — the cycle is human to mosquito to human — and about 76% of infections are INAPPARENT YET STILL TRANSMISSIBLE to a mosquito, so the human reservoir is largely invisible and case isolation cannot work.\n\nScale, for context: roughly 400 million cases a year worldwide with about 40,000 deaths, about 13 million a year in the Americas, and 2,725 US cases between January and August 2025 — most of them in PUERTO RICO rather than the continental United States. The principal vector is Aedes aegypti, which is domestic and strongly prefers to bite humans; Ae. albopictus, the tiger mosquito, is competent but secondary and prefers animals.",
  {"0": "This inverts the actual indication. The concern in the seronegative recipient is that a later natural infection may run a rougher course, which is why documented prior infection is a prerequisite rather than a contraindication.",
   "1": "The dosing schedule is not the issue. No booster arrangement makes the vaccine appropriate for a child who has never had dengue.",
   "3": "Age alone is not the barrier — the licensed indication covers children in endemic areas who have had prior infection. What excludes this boy is his negative serology, not his age.",
   "4": "This is dangerous in either direction. Vector control is the MAINSTAY of dengue prevention, and no dengue vaccine replaces mosquito avoidance — particularly where Aedes aegypti, which prefers to bite humans, is established."},
  "This vaccine only helps people who have already had dengue once. In someone who has never had it, a later infection can go worse — so he should not have it. Mosquito protection is what will keep him safe.",
  exim="fig_slide_dengue_cycle",
  excap="The dengue transmission cycle — human to mosquito to human, with no animal reservoir in the Western Hemisphere.")

# ── 17. Which hantavirus segment a vaccine must target (§22) ─────────────────
q("A research group is designing a vaccine against an Old World hantavirus intended to generate NEUTRALIZING antibody — antibody capable of binding an intact virion and preventing it from entering a host cell. The hantavirus genome consists of three single-stranded RNA segments designated S, M, and L, which encode the nucleocapsid protein, the envelope glycoproteins Gn and Gc, and the RNA-dependent RNA polymerase, respectively.\n\nWhich of the following should the vaccine target?",
  ["A. Any of the three segments, because all three encode surface proteins",
   "B. None of the segments, because the hantavirus genome is non-segmented",
   "C. The L segment, which encodes the RNA-dependent RNA polymerase",
   "D. The M segment, which encodes the envelope glycoproteins Gn and Gc",
   "E. The S segment, which encodes the nucleocapsid protein"],
  3,
  "The M segment, because Gn and Gc are the OUTER SURFACE SPIKE COMPLEX — the only viral proteins ACCESSIBLE TO ANTIBODY ON AN INTACT VIRION. Neutralization means binding the particle before it enters a cell, so the target has to be on the outside.\n\nThe naming is not arbitrary, and the memory hook makes the whole thing recallable:\n• S = SURROUNDS the RNA — the nucleocapsid protein, which coats the genome. Internal, and not accessible to antibody.\n• M = MEMBRANE SPIKES — Gn and Gc, responsible for attachment and entry. The antibody target.\n• L = LARGEST protein — the RNA-dependent RNA polymerase, the replication enzyme. Internal.\n\nEach segment is named for its size, and the sizes track the size of the protein encoded.\n\nThe same principle runs through the rest of this block, which is why it is worth generalizing rather than memorizing: Ervebo carries the Ebola SURFACE GLYCOPROTEIN genes, Inmazeb and Ebanga are monoclonals against Ebola SURFACE glycoproteins, RTS,S raises antibody against the sporozoite SURFACE, and the Lassa candidates insert genes for Lassa SURFACE protein into an attenuated measles or vesicular stomatitis virus vector. Neutralizing antibody always aims at what is exposed.\n\nFor context: there is currently no hantavirus vaccine available in the United States, and treatment for hemorrhagic fever with renal syndrome is entirely supportive, with careful volume and electrolyte management and renal replacement therapy where indicated.",
  {"0": "Only one of the three encodes a surface protein. The nucleocapsid protein coats the RNA inside the particle and the polymerase sits inside it as well; neither is visible to antibody until the virion has already been disassembled.",
   "1": "Hantavirus is segmented — three segments, S, M and L, as the stem states. Segmentation varies across these families and is worth knowing: Bunyavirales three segments, Arenaviridae two, Flaviviridae non-segmented.",
   "2": "The L segment encodes the RNA-dependent RNA polymerase, which is an excellent DRUG target — it is what remdesivir inhibits in Ebola — but a poor antibody target, because antibody cannot reach an enzyme packaged inside the virion.",
   "4": "The S segment encodes the nucleocapsid protein, which surrounds the viral RNA. Antibodies against it are made during natural infection and are useful DIAGNOSTICALLY, in the ELISA for anti-hantavirus IgM and IgG, but they do not neutralize."},
  "Antibodies can only grab what is on the outside of the virus. Only one of the three genetic segments makes the outside spikes — the other two make parts buried inside.",
  exim="fig_slide_hanta_sml",
  excap="The three hantavirus genome segments: S surrounds the RNA, M makes the membrane spikes, L encodes the largest protein.")

# ── 18. New World versus Old World hantavirus (§22) ──────────────────────────
q("A 38-year-old man in rural New Mexico comes to the emergency department because of 4 days of fever, myalgia, and headache, followed by 12 hours of rapidly worsening dyspnea. Two weeks ago he cleaned out a storage shed heavily infested with deer mice. He has no rash, no lymphadenopathy, and no tender masses. His temperature is 38.6°C (101.5°F), pulse is 128/min, respirations are 36/min, and blood pressure is 84/52 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 82%. Chest radiograph shows diffuse bilateral pulmonary edema.\n\nLaboratory studies show:\nHematocrit 56% (N=41%–53%)\nLeukocyte count 22,000/mm3 (N=4,500–11,000/mm3)\nPlatelet count 62,000/mm3 (N=150,000–400,000/mm3)\nSerum creatinine 0.9 mg/dL (N=0.6–1.2 mg/dL)\nSerum albumin 2.4 g/dL (N=3.5–5.5 g/dL)\n\nBlood cultures show no growth at 48 hours. Which of the following best explains his presentation?",
  ["A. Hantavirus cardiopulmonary syndrome caused by a New World hantavirus",
   "B. Hantavirus hemorrhagic fever with renal syndrome caused by an Old World hantavirus",
   "C. Plague pneumonia caused by Yersinia pestis",
   "D. Primary influenza pneumonia with bacterial superinfection",
   "E. Pulmonary involvement of Crimean-Congo hemorrhagic fever"],
  0,
  "Old World versus New World IS the whole distinction, and getting the hemisphere right makes the syndrome follow automatically.\n\n• OLD WORLD hantaviruses — Hantaan and Seoul in Korea and China, Dobrava in central and western Europe, Puumala in Scandinavia, carried by voles — cause HEMORRHAGIC FEVER WITH RENAL SYNDROME. The kidney fails, and acute kidney injury is the usual cause of death.\n• NEW WORLD hantaviruses of the Americas, such as ANDES VIRUS, cause HANTAVIRUS CARDIOPULMONARY SYNDROME: rapidly progressive respiratory failure and pulmonary edema WITH NORMAL RENAL FUNCTION.\n\nHis creatinine is 0.9 mg/dL. That single normal value, in a man with rodent exposure in the American southwest and fulminant non-cardiogenic pulmonary edema, is what settles the question.\n\nThe hemoconcentration is worth noting as a mechanism rather than a curiosity: a hematocrit of 56% with an albumin of 2.4 g/dL is massive capillary leak — plasma has left the vascular space and the cells left behind are concentrated. That is panel D of the shared hemorrhagic fever pathogenesis, expressed in the pulmonary vascular bed.\n\nEverything else is identical between the two syndromes: the same rodent reservoir, the same AEROSOL route from urine, feces and saliva, the SAME ABSENCE OF ANY VECTOR, and the same supportive treatment with no antiviral and no vaccine available in the United States. The cardiopulmonary syndrome is formally taught in the respiratory block, which is why only the renal disease is worked in the hemorrhagic fever section.",
  {"1": "This is the Old World disease, and it is the one in scope for the hemorrhagic fever lecture — but it destroys the kidneys, and his creatinine is 0.9 mg/dL. A US case of hemorrhagic fever with renal syndrome would be someone who had travelled to the Far East or parts of western Europe.",
   "2": "Plague is genuinely endemic in New Mexico, and pneumonic plague causes fulminant respiratory failure with hemoptysis — so this deserves real consideration. He has no bubo, no bloody sputum, and no growth in blood cultures after 48 hours, and his exposure was to mice in a shed rather than to a rodent die-off or a sick animal.",
   "3": "Influenza with bacterial superinfection is the everyday explanation for a febrile prodrome followed by rapid respiratory failure, and it should be tested for. Sterile blood cultures, profound hemoconcentration with hypoalbuminemia, thrombocytopenia and that specific exposure history point elsewhere.",
   "4": "Crimean-Congo hemorrhagic fever is transmitted by the Hyalomma tick from livestock and birds that stay well, and its geography is Africa, the Middle East, Asia and southeastern Europe. Neither the vector nor the region fits New Mexico."},
  "He breathed in dust from mouse droppings. In North America that virus floods the lungs while leaving the kidneys alone; the same family of virus in Asia does the reverse. His kidneys are fine, which tells you which one this is.",
  exim="fig_hanta_mouse",
  excap="The rodent reservoir. Route, vector-free transmission and supportive treatment are identical for both hantavirus syndromes — only the failing organ differs.")
