# Jeevs Edition — Batch 08: Hemostasis Pharmacology, part 2 (gap-fill)
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html §15, §16
# The eight facts batch 07 left as distractors or explanation lines rather than items:
# enzyme induction lowering the INR, the DOAC neuraxial boxed warning, alcohol's two
# directions, the aspirin dose paradox, vorapaxar, tenecteplase, heparin's non-bleeding
# harms, and edoxaban's backwards renal rule.
# Options alphabetised; "correct" is the 0-based index AFTER alphabetisation.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ── 1. Enzyme induction — the INR falls (§15) ─────────────────────────────────
q("A 66-year-old man has taken warfarin for 4 years after a pulmonary embolism, with an international normalized ratio consistently between 2.2 and 2.8 on an unchanged dose. Over the past 6 weeks he has been started on several new medications by different clinicians. He reports taking every warfarin dose and has not changed his diet or his alcohol intake. He now has 2 days of right calf swelling and pain. His temperature is 37.0°C (98.6°F), pulse is 86/min, and blood pressure is 132/78 mm Hg.\n\nHis new medications are acetaminophen as needed for knee pain, amiodarone for atrial fibrillation, carbamazepine for trigeminal neuralgia, metronidazole for a dental infection, and omeprazole for reflux.\n\nLaboratory studies show:\nHemoglobin 14.2 g/dL (N=13.5–17.5 g/dL)\nHematocrit 42% (N=41%–53%)\nPlatelet count 232,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 15 seconds (N=11–15 seconds)\nInternational normalized ratio 1.2 (N=0.8–1.2)\n\nDuplex ultrasonography shows a new right popliteal deep vein thrombosis. Which of the following medications is the most likely cause of the change in his international normalized ratio?",
  ["A. Acetaminophen",
   "B. Amiodarone",
   "C. Carbamazepine",
   "D. Metronidazole",
   "E. Omeprazole"],
  2,
  "Carbamazepine is a potent INDUCER of hepatic cytochrome P450 enzymes, including CYP2C9 — the enzyme that clears warfarin. More enzyme means faster clearance, lower warfarin levels, less inhibition of vitamin K epoxide reductase, and a falling INR. His dropped from a stable 2.2–2.8 to 1.2, and he clotted.\n\nThe interaction table splits by DIRECTION, and both halves are tested:\n\n• INR UP — bleeding risk — by CYP2C9 inhibition: amiodarone, metronidazole, trimethoprim-sulfamethoxazole, fluconazole, ciprofloxacin, fluvoxamine.\n• INR DOWN — clot risk — by enzyme induction: rifampin, carbamazepine, phenytoin, St John's wort.\n\nHis list is deliberately mixed. Amiodarone and metronidazole would each have pushed the INR UP; the fact that it fell anyway tells you the inducer is overwhelming them, which is exactly why the direction of the net change identifies the culprit.\n\nInduction is also SLOW in both directions — it takes 1 to 2 weeks to develop as new enzyme is synthesized, and just as long to wear off when the drug stops. So the warfarin dose must be increased now with frequent INR checks, and then decreased again when the carbamazepine is stopped, or the patient swings from clotting to bleeding.",
  {"0": "Acetaminophen at occasional analgesic doses has little effect on the INR. Sustained high-dose use (about 2 g daily for several days) can raise it modestly — the direction is up, not down, and it would not explain a fall to 1.2.",
   "1": "Amiodarone is one of the strongest CYP2C9 inhibitors in clinical use and characteristically RAISES the INR, often requiring a warfarin dose reduction of 30 to 50%. Its effect here is being overwhelmed by the inducer, which is the point of including it.",
   "3": "Metronidazole also raises the INR, by inhibiting CYP2C9 and by killing the gut flora that synthesize vitamin K — two mechanisms in the same direction. It is a well-known cause of over-anticoagulation, not of treatment failure.",
   "4": "Omeprazole is a CYP2C19 inhibitor, which matters greatly for CLOPIDOGREL — a prodrug requiring that enzyme — but very little for warfarin, which is cleared principally by CYP2C9. Any effect it has tends to raise the INR slightly."},
  "One of his new drugs revs up the liver enzymes that destroy warfarin, so the warfarin disappears faster and stops working. Two of the others push the opposite way, which is why you read the direction the number actually moved.",
  exim="fig_slide_cyp2c9",
  excap="Lecture slide: CYP2C9 clears warfarin and VKORC1 is its target — inhibitors of that enzyme raise the INR, and inducers lower it.")

# ── 2. DOACs and neuraxial anesthesia (§15) ───────────────────────────────────
q("A 71-year-old woman takes apixaban 5 mg twice daily for non-valvular atrial fibrillation. She is scheduled for elective total knee arthroplasty in 1 week, and the anesthesiologist plans spinal anesthesia. She has had no bleeding and no thrombotic events. Her temperature is 36.8°C (98.2°F), pulse is 76/min and irregular, and blood pressure is 128/74 mm Hg.\n\nLaboratory studies show:\nHemoglobin 13.1 g/dL (N=12.0–16.0 g/dL)\nHematocrit 39% (N=36%–46%)\nPlatelet count 246,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 13.4 seconds (N=11–15 seconds)\nInternational normalized ratio 1.1 (N=0.8–1.2)\nCreatinine 0.9 mg/dL (N=0.6–1.2 mg/dL)\n\nWhich of the following is the most appropriate approach to her anticoagulation before the procedure?",
  ["A. Administer four-factor prothrombin complex concentrate immediately before the block",
   "B. Continue apixaban and proceed with spinal anesthesia",
   "C. Measure the international normalized ratio and proceed if it is below 1.5",
   "D. Substitute aspirin on the morning of surgery",
   "E. Withhold apixaban for at least 72 hours before the neuraxial block"],
  4,
  "Every direct oral anticoagulant carries a boxed warning for SPINAL OR EPIDURAL HEMATOMA when neuraxial anesthesia or spinal puncture is performed in an anticoagulated patient. A hematoma in that closed space compresses the cord and causes paralysis that is permanent unless decompressed within hours, so the drug is stopped for a defined interval beforehand.\n\nFor apixaban with a procedure carrying high bleeding risk — and a neuraxial block always counts — the drug is withheld for about 72 hours (roughly 3 days, or 5 half-lives) with normal renal function. Shorter intervals apply to low bleeding-risk procedures; longer ones to impaired renal clearance, which is why her creatinine matters.\n\nNote the trap her laboratory studies set. Her INR is 1.1 and her prothrombin time is normal, because routine coagulation tests are INSENSITIVE to the -xabans. A normal INR says nothing about whether apixaban is on board; the decision is made from the drug, the dose, the timing and the renal function, not from a number.\n\nThe class's other boxed warning is the mirror image: premature discontinuation increases thrombotic events. So the drug is held for exactly as long as needed and restarted promptly once hemostasis is secure — usually 24 to 72 hours after surgery, and only after any epidural catheter is out.",
  {"0": "Prothrombin complex concentrate is a treatment for life-threatening BLEEDING, not a way to prepare an elective patient for a block. It carries a thrombotic risk of its own and would not reliably render the neuraxial space safe, since apixaban would still be circulating.",
   "1": "Proceeding on a therapeutic direct oral anticoagulant is the specific scenario the boxed warning exists to prevent. Spinal hematoma is rare but catastrophic and largely irreversible, and it is entirely avoidable by waiting.",
   "2": "This applies a warfarin-era rule to a drug it does not fit. The INR is a poor measure of -xaban activity — hers is 1.1 while she is fully anticoagulated — so using it as a green light would be actively misleading.",
   "3": "Substituting aspirin neither removes the apixaban already present nor protects her from stroke during the gap, and aspirin itself is an antiplatelet agent in a patient about to have a needle placed near the spinal cord. Bridging is generally unnecessary for a direct oral anticoagulant because its onset and offset are fast."},
  "Putting a needle into the spine of someone on a blood thinner can cause a bleed that crushes the spinal cord. The drug has to be stopped for about three days first — and the usual clotting blood test cannot tell you whether it has worn off.",
  exim="fig_slide_anticoag_classes",
  excap="Lecture slide: the anticoagulant families. The direct oral anticoagulants share two boxed warnings — spinal/epidural hematoma, and thrombosis after premature discontinuation.")

# ── 3. Alcohol runs both ways (§15) ───────────────────────────────────────────
q("A 58-year-old man has taken warfarin for 3 years for recurrent venous thromboembolism, with an international normalized ratio stable between 2.0 and 3.0. He drinks 3 to 4 alcoholic beverages most evenings and has done so for years. Last weekend he attended a wedding and drank heavily over 2 days. He now has gum bleeding and extensive bruising. He has taken no new medication, has not changed his diet, and has taken every warfarin dose. His temperature is 36.9°C (98.4°F), pulse is 88/min, and blood pressure is 128/76 mm Hg. Physical examination shows ecchymoses over both arms and no hepatomegaly, spider angiomata, ascites, or asterixis.\n\nLaboratory studies show:\nHemoglobin 13.2 g/dL (N=13.5–17.5 g/dL)\nHematocrit 39% (N=41%–53%)\nPlatelet count 188,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 54 seconds (N=11–15 seconds)\nInternational normalized ratio 6.2 (N=0.8–1.2)\nAlbumin 4.1 g/dL (N=3.5–5.5 g/dL)\nAlanine aminotransferase 32 U/L (N=10–40 U/L)\n\nWhich of the following best explains the rise in this patient's international normalized ratio?",
  ["A. Acute inhibition of warfarin metabolism by ethanol",
   "B. Chronic induction of hepatic enzymes by ethanol",
   "C. Decreased dietary vitamin K intake during the weekend",
   "D. Impaired hepatic synthesis of clotting factors from cirrhosis",
   "E. Thrombocytopenia caused by alcohol-induced marrow suppression"],
  0,
  "Alcohol affects warfarin in OPPOSITE directions depending on the pattern of drinking, and this is one of the few places where acute and chronic exposure to the same substance are tested against each other.\n\n• An ACUTE binge INHIBITS warfarin metabolism — ethanol competes for the same hepatic enzymes — so warfarin levels rise and the INR goes UP.\n• CHRONIC use INDUCES those enzymes, clearing warfarin faster, so the INR drifts DOWN and the maintenance dose creeps up.\n\nHis chronic intake is already accounted for in the dose he has been stable on for 3 years. The binge added acute inhibition on top of an enzyme system tuned to a higher dose, and the INR jumped to 6.2.\n\nThe stem excludes the competing explanations deliberately: a normal albumin and transaminases with no stigmata argue against cirrhosis, his platelet count is normal, and he reports no dietary change.\n\nManagement at an INR of 6.2 with minor bleeding only: hold warfarin, give oral vitamin K, recheck in 24 hours, and reserve prothrombin complex concentrate for serious bleeding. Then counsel him — not to abstain as a condition of anticoagulation, but that CONSISTENCY matters, exactly as it does with dietary vitamin K.",
  {"1": "Chronic induction is real in this patient and is why his maintenance dose is what it is — but it lowers the INR rather than raising it. Invoking it here gets the direction backwards, which is precisely the discrimination being tested.",
   "2": "Reduced vitamin K intake does raise the INR, and would be the answer in a patient who had stopped eating — after surgery, or during a prolonged illness. He was at a wedding, so his intake is more likely to have gone up than down, and he reports no dietary change.",
   "3": "Cirrhosis impairs synthesis of the coagulation factors and prolongs the prothrombin time, and it must always be considered in a heavy drinker. His albumin is 4.1 g/dL, his transaminases are normal, and he has no physical signs of chronic liver disease — and an acute 2-day binge does not produce cirrhosis.",
   "4": "Alcohol does suppress the marrow and cause thrombocytopenia, which would produce bruising — so it is a reasonable competitor for his SYMPTOM. It does not change the INR at all, because the prothrombin time measures plasma factors, and his platelet count is 188,000/mm3."},
  "Steady drinking over years speeds up the liver's disposal of warfarin, so his dose was set high to compensate. A sudden heavy binge does the opposite and jams that disposal, so the high dose suddenly became a huge dose.",
  exim="fig_slide_cyp2c9",
  excap="Lecture slide: warfarin is cleared by CYP2C9 — the enzyme that alcohol inhibits acutely and induces chronically.")

# ── 4. The aspirin dose paradox (§16) ─────────────────────────────────────────
q("A 62-year-old man with stable coronary artery disease takes aspirin 81 mg daily. At a routine visit he says a relative told him that a 325 mg tablet would protect his heart better, and asks whether he should switch. He has had no bleeding and no chest pain. His temperature is 36.8°C (98.2°F), pulse is 68/min, and blood pressure is 126/76 mm Hg.\n\nLaboratory studies show:\nHemoglobin 14.6 g/dL (N=13.5–17.5 g/dL)\nHematocrit 43% (N=41%–53%)\nPlatelet count 240,000/mm3 (N=150,000–400,000/mm3)\n\nWhich of the following best explains why the higher dose would not provide greater antiplatelet benefit?",
  ["A. Higher doses accelerate the hepatic clearance of salicylate",
   "B. Higher doses also inhibit endothelial cyclooxygenase-2, reducing prostacyclin production",
   "C. Higher doses increase platelet turnover in the bone marrow",
   "D. Higher doses irreversibly inhibit cyclooxygenase-1 in hepatocytes",
   "E. Higher doses shorten the duration of cyclooxygenase-1 inhibition in platelets"],
  1,
  "Low dose IS the antiplatelet dose, and the reason is that cyclooxygenase is not only a platelet enzyme.\n\nAt low doses aspirin acetylates cyclooxygenase-1 in platelets, abolishing thromboxane A2 — the platelet's own 'recruit more platelets' signal. Platelets are exquisitely vulnerable because they have no nucleus and cannot synthesize replacement enzyme, so a small dose achieves near-complete, lifelong inhibition of every platelet it meets.\n\nPush the dose up and you additionally inhibit cyclooxygenase-2 in ENDOTHELIAL cells, which make PROSTACYCLIN — a vasodilator and a natural inhibitor of platelet aggregation. Suppressing prostacyclin works against the very effect you are trying to produce. Endothelial cells, being nucleated, resynthesize the enzyme within hours, which is what makes the low-dose selectivity possible in the first place.\n\nSo the higher dose buys no additional antiplatelet benefit and costs real harm: gastrointestinal ulceration and bleeding rise with dose. Clinical trials comparing aspirin doses for secondary prevention — ADAPTABLE most recently — found no difference in cardiovascular events, and low-dose aspirin remains standard.\n\nThe other dose-related harms worth carrying: tinnitus at high doses, and Reye syndrome in children with a viral illness.",
  {"0": "Salicylate clearance is actually saturable, so higher doses are cleared more SLOWLY and disproportionately — the basis of salicylate toxicity. Either way, plasma clearance is irrelevant to an irreversible effect that outlives the drug by a week.",
   "2": "Aspirin does not stimulate thrombopoiesis. Platelet turnover is what eventually restores function after aspirin is stopped — about 10% of the pool per day — but it is not dose dependent and is not the reason higher doses fail to help.",
   "3": "Hepatocyte cyclooxygenase-1 has no role in hemostasis; the enzyme that matters is in the platelet, and secondarily in gastric mucosa and endothelium. Gastric cyclooxygenase-1 inhibition is why higher doses cause more ulcers, which is a harm rather than a limit on benefit.",
   "4": "The duration of platelet inhibition is fixed by the platelet's 7 to 10 day lifespan, not by the dose. Since the inhibition is irreversible and the cell cannot make new enzyme, no dose shortens or lengthens it."},
  "A small dose already shuts down the platelet enzyme permanently. A bigger dose starts switching off a different enzyme in the blood vessel wall that normally keeps platelets calm — so you gain nothing and bleed more.",
  exim="fig_slide_platelet",
  excap="Lecture slide: platelet activation and the antiplatelet targets — aspirin acts at the thromboxane arm, and at higher doses also reaches the endothelial prostacyclin pathway.")

# ── 5. Vorapaxar and the last door (§16) ──────────────────────────────────────
q("A 64-year-old man with a myocardial infarction 2 years ago and symptomatic peripheral arterial disease continues to have claudication and recurrent ischemic events despite aspirin and clopidogrel. He has never had a stroke, a transient ischemic attack, or an intracranial hemorrhage. His cardiologist adds vorapaxar. His temperature is 36.9°C (98.4°F), pulse is 72/min, and blood pressure is 132/78 mm Hg.\n\nLaboratory studies show:\nHemoglobin 14.0 g/dL (N=13.5–17.5 g/dL)\nHematocrit 42% (N=41%–53%)\nPlatelet count 228,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 12.8 seconds (N=11–15 seconds)\n\nWhich of the following best describes the mechanism of action of the added drug?",
  ["A. Blockade of the adenosine diphosphate (P2Y12) receptor",
   "B. Blockade of the glycoprotein IIb/IIIa receptor",
   "C. Blockade of the protease-activated receptor 1",
   "D. Inhibition of cyclooxygenase-1",
   "E. Inhibition of phosphodiesterase-3"],
  2,
  "Vorapaxar antagonizes protease-activated receptor 1 (PAR-1), the THROMBIN receptor on the platelet — and thrombin is the most potent platelet agonist there is.\n\nA platelet can be activated through several doors: thromboxane (closed by aspirin), adenosine diphosphate (closed by the -grels), and thrombin (closed by nothing else in the antiplatelet armamentarium). Note the elegance of the target — anticoagulants reduce thrombin GENERATION, but none of them stops the thrombin that is made from activating platelets. Vorapaxar is the drug that closes that last door, which is why it is used as an add-on in patients still having events on aspirin and a P2Y12 inhibitor.\n\nThe price is intracranial bleeding, and it defines the drug. Vorapaxar is ABSOLUTELY contraindicated in anyone with a history of stroke, transient ischemic attack, or intracranial hemorrhage — this man is a candidate precisely because he has none of those. It is also very long acting, with platelet inhibition persisting for weeks after the last dose, and there is no practical way to reverse it.\n\nEvery path ends in the same place: glycoprotein IIb/IIIa opening so that fibrinogen can bridge one platelet to the next. Each drug class simply picks a different door upstream of that bridge.",
  {"0": "P2Y12 blockade is the mechanism of clopidogrel, prasugrel, ticagrelor and cangrelor — and he is already taking clopidogrel, which is why a drug with a different target was added. Adding a second P2Y12 inhibitor would duplicate a blocked pathway.",
   "1": "Glycoprotein IIb/IIIa blockade is eptifibatide and tirofiban, which act at the final common pathway — the fibrinogen bridge itself. Those are intravenous drugs for the catheterization laboratory and acute coronary syndromes, not oral add-ons for chronic secondary prevention.",
   "3": "Cyclooxygenase-1 inhibition is aspirin, which he already takes. Blocking the thromboxane door a second time would add nothing, which is the logic behind choosing a drug with a different receptor target.",
   "4": "Phosphodiesterase-3 inhibition describes cilostazol and dipyridamole, which raise intracellular cyclic AMP so the platelet stays calm. Cilostazol would be a reasonable thought for his claudication — but it is contraindicated in heart failure and is not what vorapaxar does."},
  "Platelets can be switched on through several different doorways, and his current drugs block two of them. This one blocks the thrombin doorway — the strongest signal of all, and the one nothing else closes.",
  exim="fig_slide_kp_antiplatelet",
  excap="Lecture slide: the antiplatelet classes and their receptor targets, including the PAR-1 antagonist that blocks the thrombin door.")

# ── 6. One bolus, in a rural emergency department (§16) ───────────────────────
q("A 57-year-old man arrives at a rural emergency department 50 minutes after the onset of crushing substernal chest pain. Electrocardiography shows 3 mm of ST-segment elevation in leads V2 through V5. The nearest facility with a catheterization laboratory is a 2-hour transfer, so fibrinolytic therapy is chosen. He has no history of stroke, no recent surgery or trauma, and no bleeding. His temperature is 36.8°C (98.2°F), pulse is 96/min, respirations are 20/min, and blood pressure is 142/86 mm Hg.\n\nLaboratory studies show:\nHemoglobin 14.2 g/dL (N=13.5–17.5 g/dL)\nHematocrit 42% (N=41%–53%)\nPlatelet count 246,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 12.5 seconds (N=11–15 seconds)\nInternational normalized ratio 1.0 (N=0.8–1.2)\n\nThe department is short-staffed and an infusion pump is not immediately available. Which of the following agents can be administered as a single intravenous bolus?",
  ["A. Alteplase",
   "B. Aminocaproic acid",
   "C. Reteplase",
   "D. Tenecteplase",
   "E. Tranexamic acid"],
  3,
  "Tenecteplase is given as a SINGLE weight-based intravenous bolus over about 5 seconds. That convenience is its whole selling point, and it is why tenecteplase has largely displaced alteplase in ST-elevation myocardial infarction and is now FDA-approved for acute ischemic stroke as well.\n\nThe three plasminogen activators differ almost entirely in how they are given:\n• alteplase — an INFUSION (bolus plus infusion protocols), the historical reference agent for acute ischemic stroke\n• reteplase — TWO bolus doses 30 minutes apart\n• tenecteplase — ONE bolus, with a longer half-life and greater fibrin specificity\n\nIn a setting like this one — short-staffed, no pump, a transfer window closing — a single push removes the commonest source of dosing error in fibrinolysis, which is a mis-set infusion.\n\nThey share a mechanism and therefore a hazard: all convert plasminogen to plasmin, plasmin degrades the fibrin mesh, and the defining risk is bleeding, intracranial hemorrhage above all. The contraindication list applies identically whichever agent is chosen, and this man has been screened against it.\n\nThe memory hook: everything ending in -plase is a plasminogen activator; tenecteplase is the one-push version.",
  {"0": "Alteplase is the reference plasminogen activator, but it is given as a bolus followed by an infusion over 60 to 90 minutes, which is exactly what cannot be delivered here without a pump. (Cathflo is the low-dose alteplase used only to unclog a central catheter.)",
   "1": "Aminocaproic acid is an ANTIfibrinolytic — it blocks the conversion of plasminogen to plasmin. Giving it here would work directly against reperfusion; it is what you reach for when a thrombolytic causes catastrophic bleeding.",
   "2": "Reteplase is given as two bolus doses 30 minutes apart, which is closer to what is wanted and makes it the near-miss. It still requires a second timed administration, and the question asks specifically for a SINGLE bolus.",
   "4": "Tranexamic acid is the other antifibrinolytic, used with cryoprecipitate to reverse thrombolysis and to control bleeding in trauma and surgery. Administering it to a patient with an occluded coronary artery would be the opposite of the intent."},
  "All three clot-dissolving drugs work the same way; they differ in how they are given. This one is a single push from a syringe, which is why it wins when there is no pump and no time.",
  exim="fig_slide_kp_thrombolytic",
  excap="Lecture slide: key points on the thrombolytics — same mechanism, different administration, and one shared bleeding hazard.")

# ── 7. Heparin's quiet harms (§15) ────────────────────────────────────────────
q("A 68-year-old man has received a continuous intravenous unfractionated heparin infusion for 6 days for an extensive pulmonary embolism. He feels well and is not bleeding. He takes no other medication, has no history of kidney disease or diabetes mellitus, and has not received any potassium supplement. His temperature is 36.9°C (98.4°F), pulse is 78/min, respirations are 16/min, and blood pressure is 126/74 mm Hg. Physical examination shows no abnormalities; the specimen was drawn atraumatically through a peripheral line without a tourniquet.\n\nLaboratory studies show:\nHemoglobin 13.6 g/dL (N=13.5–17.5 g/dL)\nHematocrit 40% (N=41%–53%)\nPlatelet count 224,000/mm3 (N=150,000–400,000/mm3)\nPotassium 5.9 mEq/L (N=3.5–5.0 mEq/L)\nSodium 138 mEq/L (N=136–146 mEq/L)\nBicarbonate 24 mEq/L (N=22–28 mEq/L)\nCreatinine 1.0 mg/dL (N=0.6–1.2 mg/dL)\nCreatine kinase 78 U/L (N=25–90 U/L)\nArterial pH 7.39 (N=7.35–7.45)\n\nHis potassium was 4.2 mEq/L on admission. Which of the following is the most likely cause of the hyperkalemia?",
  ["A. Heparin-induced suppression of adrenal aldosterone synthesis",
   "B. In vitro hemolysis of the specimen",
   "C. Metabolic acidosis shifting potassium out of cells",
   "D. Rhabdomyolysis from prolonged immobility",
   "E. Type 1 renal tubular acidosis"],
  0,
  "Heparin inhibits aldosterone synthesis in the adrenal zona glomerulosa — it reduces both the number and affinity of angiotensin II receptors there. Less aldosterone means less distal tubular potassium secretion, and the potassium rises. It occurs in roughly 5 to 10% of patients on heparin, usually after several days of therapy, and it happens with low-molecular-weight heparin as well as with unfractionated.\n\nThis is a hypoaldosteronism, so it is a type 4 renal tubular acidosis pattern in principle, though the potassium usually moves before any acidosis is apparent — note his bicarbonate of 24 mEq/L and pH of 7.39.\n\nIt belongs to the group of heparin adverse effects that are NOT bleeding, and those are what get tested: heparin-induced thrombocytopenia (the dangerous one), hyperkalemia through this mechanism, and OSTEOPOROSIS with prolonged use — which is why long-term unfractionated heparin in pregnancy is a real problem and low-molecular-weight heparin is preferred.\n\nRisk is higher with diabetes mellitus, chronic kidney disease, or concurrent potassium-sparing diuretics, ACE inhibitors or ARBs — none of which he has, which is why the drug itself is the answer. Management is to monitor the potassium and, if it rises further, to switch anticoagulant.",
  {"1": "Pseudohyperkalemia from hemolysis during collection is always worth excluding and is the commonest cause of a spuriously high potassium — which is why the stem specifies an atraumatic draw without a tourniquet. A hemolyzed specimen would also be flagged by the laboratory.",
   "2": "Acidosis does shift potassium extracellularly, and would be the answer with a low bicarbonate and a low pH. His bicarbonate is 24 mEq/L and his arterial pH is 7.39 — there is no acidosis to do the shifting.",
   "3": "Rhabdomyolysis releases intracellular potassium and would be a real consideration in an immobilized inpatient. It would come with a markedly raised creatine kinase and often acute kidney injury; his creatine kinase is 78 U/L and his creatinine is normal.",
   "4": "Type 1 (distal) renal tubular acidosis characteristically causes HYPOkalemia along with a non-anion-gap metabolic acidosis and alkaline urine. The hypoaldosterone pattern that raises potassium is type 4, and here it is drug-induced rather than a primary tubular disease."},
  "Heparin quietly switches off the hormone that tells the kidney to dump potassium, so potassium builds up after a few days. It is one of heparin's non-bleeding side effects, along with thinning the bones over the long run.",
  exim="fig_slide_heparin_ae",
  excap="Lecture slide on heparin adverse effects — bleeding and heparin-induced thrombocytopenia alongside the quieter harms, hyperkalemia and osteoporosis.")

# ── 8. Edoxaban's backwards rule (§15) ────────────────────────────────────────
q("A 54-year-old man with newly diagnosed non-valvular atrial fibrillation is seen for anticoagulation. He is otherwise healthy, exercises regularly, and takes no medications. He weighs 84 kg (185 lb). His temperature is 36.8°C (98.2°F), pulse is 88/min and irregularly irregular, and blood pressure is 124/76 mm Hg. Physical examination shows no abnormalities and echocardiography shows structurally normal valves.\n\nLaboratory studies show:\nHemoglobin 15.1 g/dL (N=13.5–17.5 g/dL)\nHematocrit 45% (N=41%–53%)\nPlatelet count 238,000/mm3 (N=150,000–400,000/mm3)\nCreatinine 0.8 mg/dL (N=0.6–1.2 mg/dL)\nCreatinine clearance 112 mL/min (N=97–137 mL/min)\n\nA colleague suggests edoxaban. Which of the following best explains why edoxaban is not recommended for this particular patient?",
  ["A. Efficacy for stroke prevention is reduced because the drug is cleared too rapidly",
   "B. Hepatic clearance becomes saturated at high creatinine clearance",
   "C. The bleeding risk rises sharply above a creatinine clearance of 95 mL/min",
   "D. The drug accumulates to toxic concentrations in hyperfiltering kidneys",
   "E. The drug is not absorbed unless it is taken with food"],
  0,
  "This is the backwards renal rule, and it is the fact edoxaban is tested on. Edoxaban should NOT be used for stroke prevention in non-valvular atrial fibrillation when the creatinine clearance is above 95 mL/min — not because of toxicity, but because efficacy is LOST. His clearance is 112 mL/min.\n\nEvery other renal rule in anticoagulation runs the other way: impaired clearance means accumulation and bleeding, so you reduce the dose or avoid the drug. Edoxaban is the exception. In the ENGAGE AF-TIMI 48 trial, patients with normal-to-high renal function cleared the drug so efficiently that trough levels fell below the therapeutic range, and the stroke rate was higher than with well-managed warfarin. It is a labelled contraindication for that indication.\n\nThe A-B-C of the xabans, which is how to keep the three apart:\n• Apixaban — twice daily, least renally cleared (~25%), All-round safest in kidney disease and the lowest bleeding rates.\n• Rivaroxaban — once daily, Requires a meal at treatment doses.\n• Edoxaban — once daily, Excellent kidneys are a problem (skip it above 95 mL/min).\n\nFor this man, apixaban or rivaroxaban is appropriate — or warfarin, though he is an ideal candidate for a fixed-dose oral agent.",
  {"1": "Edoxaban's non-renal clearance is not saturable in a way that matters clinically, and the mechanism of the problem is renal ELIMINATION being too efficient, not hepatic handling failing. This option invents a pharmacokinetic ceiling that does not exist.",
   "2": "This inverts the concern. Bleeding risk rises when a renally cleared drug ACCUMULATES — that is, when clearance is LOW. Above 95 mL/min the problem is too little drug, and the harm is stroke rather than hemorrhage.",
   "3": "Accumulation in hyperfiltering kidneys is a contradiction: faster filtration means faster elimination and lower levels. Accumulation is what happens in renal impairment, and it is the reason edoxaban is also avoided at very low clearances.",
   "4": "The food requirement belongs to RIVAROXABAN at the 15 mg and 20 mg treatment doses, where taking the dose without a meal reduces absorption and causes treatment failure. Edoxaban may be taken with or without food."},
  "Most blood thinners are risky when the kidneys are weak, because the drug builds up. This one is the opposite — his kidneys work so well that they clear it before it can do its job, so it fails to prevent strokes.",
  exim="fig_slide_anticoag_classes",
  excap="Lecture slide: the anticoagulant families, including the three direct oral factor Xa inhibitors and the rule that distinguishes each one.")
