# Jeevs Edition — Batch 1: Hematopoiesis & Marrow
# Options are alphabetised; "correct" is the 0-based index AFTER alphabetisation.
Q = []

def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)

# ── 1. Sites of hematopoiesis across the lifespan ──────────────────────────
q("An investigator is studying blood cell production in human fetal tissues obtained at autopsy. Specimens are taken at 4 weeks', 10 weeks', 20 weeks', and 36 weeks' gestation. At 4 weeks' gestation, nucleated erythroid precursors are confined to blood islands outside the embryo proper. At 20 weeks' gestation, the tissue containing the greatest number of erythroid and granulocytic precursors is a large, solid intra-abdominal organ. By 36 weeks' gestation, that organ contains almost no precursors, and precursors are instead found within the medullary cavities of the long bones.\n\nThe organ containing the greatest number of hematopoietic precursors at 20 weeks' gestation is which of the following?",
  ["A. Bone marrow", "B. Liver", "C. Lymph node", "D. Spleen", "E. Thymus", "F. Yolk sac"],
  1,
  "Hematopoiesis migrates in a fixed sequence, and the question gives you the two ends of it so you can place the middle. Yolk sac blood islands (about weeks 3–8) → LIVER (about week 6 through birth, and the dominant site for the whole second trimester) → bone marrow (begins about the 5th month, dominant by birth and thereafter).\n\nThe two anchors in the stem do the work: extraembryonic blood islands at 4 weeks = yolk sac phase, and medullary cavities at 36 weeks = marrow phase. At 20 weeks the fetus sits between them, in the hepatic phase → the liver. The spleen contributes during the same window but is a minor partner, never the dominant site.",
  {"0": "Bone marrow is correct for 36 weeks' gestation and for every point afterwards — the stem explicitly places precursors in the medullary cavities by then. Marrow only begins contributing around the 5th month, so at 20 weeks it is not yet the dominant site.",
   "2": "Lymph nodes would be correct if the question asked where lymphocytes undergo antigen-dependent maturation. They make a minor contribution to fetal hematopoiesis and never house the bulk of erythroid and granulocytic precursors.",
   "3": "The spleen does participate in fetal hematopoiesis during the same window, and would be correct if the question asked which organ is a secondary or accessory site. It is always a minor partner to the liver, and it is not a 'large solid organ containing the greatest number' of precursors.",
   "4": "The thymus would be correct if the question asked where T-cell precursors mature. It is a lymphoid training organ, not a site of erythroid or granulocytic production, at any stage of life.",
   "5": "The yolk sac is correct for 4 weeks' gestation — the stem describes it as the blood islands outside the embryo proper. It has involuted well before 20 weeks."},
  "Blood gets made in different places as a baby grows: first in the yolk sac, then in the liver for most of pregnancy, then finally in the bones. At 20 weeks the liver is doing the job.",
  exim="fig_hematopoiesis",
  excap="Hematopoiesis: the pluripotent hematopoietic stem cell gives rise to myeloid and lymphoid precursors, and from those to every mature blood cell."),

# ── 2. Adult red marrow distribution ───────────────────────────────────────
q("A 58-year-old man comes to the office because of a 3-month history of fatigue and easy bruising. He has no history of serious illness and takes no medications. His temperature is 36.9°C (98.4°F), pulse is 88/min, respirations are 16/min, and blood pressure is 126/78 mm Hg. Physical examination shows scattered ecchymoses over the forearms and no lymphadenopathy or splenomegaly.\n\nLaboratory studies show:\nHemoglobin 8.6 g/dL (N=13.5–17.5 g/dL)\nHematocrit 26% (N=41%–53%)\nMean corpuscular volume 92 µm3 (N=80–100 µm3)\nLeukocyte count 2,100/mm3 (N=4,500–11,000/mm3)\nPlatelet count 38,000/mm3 (N=150,000–400,000/mm3)\nReticulocyte count 0.3% (N=0.5%–1.5%)\n\nA bone marrow examination is planned. Which of the following is the most appropriate site from which to obtain the specimen?",
  ["A. Distal radius", "B. Mid-shaft of the femur", "C. Mid-shaft of the tibia", "D. Posterior superior iliac crest", "E. Sternal body"],
  3,
  "Three cytopenias with a LOW reticulocyte count point to a production failure, so the marrow must be sampled — and the site is determined by where red (hematopoietically active) marrow still exists in an adult.\n\nRed marrow retreats centripetally with age. In a child it fills essentially the whole skeleton; by adulthood it has withdrawn to the AXIAL skeleton and the proximal ends of the long bones, and the peripheral long-bone cavities are filled with yellow (fatty) marrow. The POSTERIOR SUPERIOR ILIAC CREST is the standard site because it reliably contains red marrow, offers a thick cortical window with no vital structure beneath it, and permits both an aspirate and an adequate core biopsy through one entry.",
  {"0": "The distal radius would be correct in an infant, in whom red marrow still occupies the peripheral skeleton. In a 58-year-old it contains yellow fatty marrow and would yield a non-diagnostic specimen.",
   "1": "The mid-shaft of the femur is fatty marrow in an adult. The PROXIMAL femur retains some red marrow, so moving the needle to the proximal end would change the answer — but the shaft itself will not give a representative specimen.",
   "2": "The mid-shaft of the tibia is the most peripheral option here and the earliest to convert to yellow marrow. It is used in infants for emergency intraosseous ACCESS, which is a different purpose from sampling hematopoietic tissue.",
   "4": "The sternum does contain red marrow and was historically used, so the tissue would be adequate — but only an ASPIRATE can be taken there. A core biopsy is unsafe at the sternum because the great vessels and right atrium lie immediately deep to it, and this patient with pancytopenia needs the cellularity assessment that only a core provides."},
  "As you get older, the bone marrow that still makes blood pulls back toward the center of the body. The back of the hip bone is where there is plenty of it and nothing dangerous underneath.")

# ── 3. Self-renewal vs pluripotency ────────────────────────────────────────
q("An investigator isolates a single cell from murine bone marrow and injects it into a lethally irradiated recipient mouse. Sixteen weeks later, the recipient's blood contains donor-derived erythrocytes, granulocytes, monocytes, platelets, B lymphocytes, and T lymphocytes. Marrow is then harvested from this first recipient and transplanted into a second lethally irradiated mouse, and the process is repeated through four successive recipients. Each recipient survives with full donor-derived blood production.\n\nThe survival of the FOURTH successive recipient most specifically demonstrates which of the following properties?",
  ["A. Clonal selection", "B. Lineage commitment", "C. Pluripotency", "D. Self-renewal", "E. Terminal differentiation", "F. Transdifferentiation"],
  3,
  "This item separates the two defining properties of a hematopoietic stem cell, which are commonly blurred together.\n\nPRODUCING ALL SIX LINEAGES demonstrates PLURIPOTENCY — but that is shown by the FIRST recipient, and the question does not ask about the first recipient.\n\nSURVIVING SERIAL TRANSPLANTATION demonstrates SELF-RENEWAL. For the fourth mouse to be reconstituted, the original cell must have divided in a way that generated differentiating daughters AND regenerated an identical stem cell, over and over, without exhausting the pool. That is the definition of self-renewal, and serial transplantation is the classic assay for it. The buried clue is the word 'fourth' — it shifts the testing point from what the cell can BECOME to whether the cell can REPLACE ITSELF.",
  {"0": "Clonal selection would be correct if the experiment showed expansion of a lymphocyte clone in response to a specific antigen. This is an adaptive-immunity term and has nothing to do with stem cell kinetics.",
   "1": "Lineage commitment is the step in which a multipotent progenitor becomes restricted to the myeloid or lymphoid branch and LOSES options. It would be correct if donor cells produced only granulocytes and monocytes — the opposite of the multilineage result described.",
   "2": "Pluripotency is genuinely demonstrated here, and would be correct if the question had asked about the first recipient's six donor-derived lineages. It describes what the cell can turn into, not whether it can perpetuate itself through four transplants.",
   "4": "Terminal differentiation describes a cell that has reached its final form and can no longer divide, such as a mature neutrophil. A terminally differentiated cell cannot reconstitute anything, let alone four successive recipients.",
   "5": "Transdifferentiation is the conversion of one differentiated cell type directly into another, and would require, for example, a mature lymphocyte becoming a hepatocyte. Nothing in the experiment crosses lineage boundaries after differentiation."},
  "A stem cell can do two special things: turn into every kind of blood cell, and make copies of itself. Transplanting it over and over again into four mice proves the copying part.")

# ── 4. HSC quiescence ──────────────────────────────────────────────────────
q("A 44-year-old woman with acute myeloid leukemia is treated with an induction regimen containing cytarabine, which is incorporated into DNA during the S phase of the cell cycle. Her leukocyte count falls to 400/mm3 by day 10, and she becomes transfusion-dependent for erythrocytes and platelets. By day 28, her neutrophil count, hemoglobin concentration, and platelet count have all recovered without stem cell transplantation.\n\nWhich of the following properties of hematopoietic stem cells best explains the recovery of all three cell lines?",
  ["A. Expression of multidrug efflux transporters on committed progenitors", "B. Localization of stem cells within a hypoxic, quiescent marrow niche", "C. Preferential apoptosis of lymphoid rather than myeloid progenitors", "D. Rapid proliferation of stem cells that outpaces drug clearance", "E. Sequestration of stem cells within the peripheral circulation"],
  1,
  "Cytarabine is S-phase specific: it can only injure a cell that is actively synthesizing DNA. The reason the marrow is not permanently destroyed is that the cells at the TOP of the hierarchy are not cycling.\n\nHematopoietic stem cells reside in a HYPOXIC niche at the endosteal surface and are largely QUIESCENT, sitting in G0. Because they are not in S phase, cycle-specific chemotherapy passes over them. What the drug kills is the rapidly dividing committed progenitor and precursor compartment — which is exactly why the counts fall at day 10, when the existing mature cells reach the end of their lifespan and are not replaced. The spared quiescent stem cells then re-enter the cycle and repopulate all three lineages by day 28.\n\nQuiescence is therefore not an incidental feature; it is the property that makes the marrow survivable as a chemotherapy target.",
  {"0": "Efflux transporters are indeed enriched on stem cells (the basis of the 'side population' phenotype), but the option places them on COMMITTED PROGENITORS — the very compartment that is destroyed here, as the day-10 nadir proves. Put the transporters on the stem cell and this becomes a defensible contributing mechanism.",
   "2": "This would be correct if the recovery had been limited to the myeloid lineage while lymphocytes stayed suppressed. All three lineages recovered, so a lineage-selective effect cannot be the explanation.",
   "3": "Rapid proliferation is precisely what makes a cell VULNERABLE to an S-phase agent, not protected from it. This option inverts the mechanism; it describes the leukemic blasts and the progenitor pool that were killed.",
   "4": "A small number of stem cells do circulate, and mobilizing them into the blood is the basis of apheresis collection — but circulating cells are no less exposed to an intravenous drug than marrow cells. Location in the blood confers no pharmacologic protection."},
  "The chemotherapy only kills cells that are busy copying their DNA. The master stem cells are resting, so they survive and rebuild everything afterwards.")

# ── 5. Common myeloid progenitor ───────────────────────────────────────────
q("A 33-year-old man is evaluated for a 6-week history of recurrent sinus infections. Flow cytometry of a bone marrow aspirate identifies a progenitor population that is capable of producing erythrocytes, granulocytes, monocytes, and platelets, but that produces no cells expressing CD19 or CD3 under any culture condition.\n\nA cell derived from this progenitor population is most likely to be which of the following?",
  ["A. B lymphocyte", "B. Megakaryocyte", "C. Natural killer cell", "D. Plasma cell", "E. T lymphocyte"],
  1,
  "The progenitor described is the COMMON MYELOID PROGENITOR. The stem tells you what it makes (erythrocytes, granulocytes, monocytes, platelets) and what it cannot make (CD19 = B cells, CD3 = T cells), which is the myeloid/lymphoid branch point stated in marker terms.\n\nThe MEGAKARYOCYTE is the marrow cell that sheds platelets, and it is myeloid. Every other option belongs to the lymphoid branch, which descends from the common LYMPHOID progenitor.\n\nThe branch point to carry: MYELOID = erythrocyte, megakaryocyte/platelet, neutrophil, eosinophil, basophil, monocyte/macrophage, and mast cell. LYMPHOID = B cell (and its plasma cell end-product), T cell, and NK cell.",
  {"0": "A B lymphocyte is lymphoid and expresses CD19, which the stem explicitly excludes. It arises from the common lymphoid progenitor.",
   "2": "The natural killer cell is the easiest lymphoid cell to misplace because it is an innate effector that kills without antigen presentation — behaviourally it feels myeloid. Its LINEAGE, however, is lymphoid, from the common lymphoid progenitor.",
   "3": "The plasma cell is the terminally differentiated antibody-secreting form of a B lymphocyte, so it sits at the end of the lymphoid branch. It would be correct only if the progenitor had produced CD19-positive cells.",
   "4": "A T lymphocyte expresses CD3, which the stem explicitly excludes. It also requires thymic education, which no marrow culture condition supplies."},
  "Blood cells come from two family trees. This progenitor belongs to the myeloid tree, and the platelet-making giant cell — the megakaryocyte — is on that tree.",
  exim="fig_hematopoiesis",
  excap="The myeloid branch yields erythrocytes, megakaryocytes/platelets, granulocytes and monocytes; the lymphoid branch yields B cells, T cells and NK cells.")

# ── 6. EPO source ──────────────────────────────────────────────────────────
q("A 62-year-old woman with a 12-year history of type 2 diabetes mellitus comes to the office for follow-up. Her only medications are metformin and lisinopril. Her pulse is 78/min and blood pressure is 138/84 mm Hg. Physical examination shows conjunctival pallor and trace bilateral ankle edema.\n\nLaboratory studies show:\nHemoglobin 9.2 g/dL (N=12.0–16.0 g/dL)\nHematocrit 28% (N=36%–46%)\nMean corpuscular volume 89 µm3 (N=80–100 µm3)\nReticulocyte count 0.4% (N=0.5%–1.5%)\nLeukocyte count 7,300/mm3 (N=4,500–11,000/mm3)\nPlatelet count 246,000/mm3 (N=150,000–400,000/mm3)\nSerum creatinine 3.4 mg/dL (N=0.6–1.2 mg/dL)\nSerum ferritin 180 ng/mL (N=20–250 ng/mL)\nTransferrin saturation 28% (N=20%–50%)\n\nDeficient production of the hormone responsible for this patient's anemia occurs in which of the following locations?",
  ["A. Hepatocytes of the periportal zone", "B. Juxtaglomerular cells of the afferent arteriole", "C. Peritubular interstitial cells of the renal cortex", "D. Principal cells of the renal collecting duct", "E. Proximal convoluted tubular epithelium", "F. Zona glomerulosa of the adrenal cortex"],
  2,
  "Normocytic anemia with a LOW reticulocyte count and NORMAL iron studies in a patient with a creatinine of 3.4 mg/dL is the anemia of chronic kidney disease: the kidney has lost its endocrine function, not its filtering function alone.\n\nErythropoietin is produced by PERITUBULAR INTERSTITIAL CELLS (fibroblast-like cells) of the RENAL CORTEX, which sit in the interstitium between the tubules and the capillaries. That position is the point of the design — it lets the cell sense the oxygen content of blood that has already passed through the glomerulus and is being delivered to the energy-hungry tubules, making it a true tissue-oxygen sensor rather than a blood-pressure sensor.\n\nThe low reticulocyte count is the buried clue: it establishes a production failure, which is what an absent hormonal signal produces.",
  {"0": "The liver is a genuine secondary source of erythropoietin, and is the DOMINANT source in the fetus — which is why anephric fetuses are not severely anemic. In adults the liver supplies only about 10% of erythropoietin and cannot compensate; the question asks where the deficient production normally occurs.",
   "1": "Juxtaglomerular cells synthesize RENIN, not erythropoietin, and they sense afferent arteriolar stretch and distal sodium delivery. They would be correct if the question concerned this patient's blood pressure or her lisinopril.",
   "3": "Principal cells of the collecting duct respond to aldosterone and antidiuretic hormone to handle sodium, potassium and water. They are hormone TARGETS, not a source of erythropoietin.",
   "4": "Proximal tubular epithelium performs bulk reabsorption and 1-alpha-hydroxylation of vitamin D, so it would be correct for the calcitriol deficiency and renal bone disease that accompany chronic kidney disease. It does not make erythropoietin — the erythropoietin-producing cells lie in the interstitium BESIDE these tubules.",
   "5": "The zona glomerulosa produces aldosterone. It would be correct for a question about this patient's volume status or potassium, not her anemia."},
  "Kidneys do two jobs: filter blood, and send the message telling the marrow to build red cells. Her damaged kidneys stopped sending the message, so the marrow stopped building.")

# ── 7. Oxygen sensing / HIF ────────────────────────────────────────────────
q("A 29-year-old man who lives at sea level travels to a research station at an altitude of 4,200 m (13,800 ft). On arrival, his arterial oxygen saturation is 88%. Over the next 10 days, his serum erythropoietin concentration rises from 12 mU/mL to 96 mU/mL (N=4–26 mU/mL), and his hematocrit increases from 44% to 51%.\n\nWhich of the following best explains the increase in this patient's serum erythropoietin concentration?",
  ["A. Decreased degradation of hypoxia-inducible factor 1-alpha", "B. Decreased renal blood flow with activation of the renin-angiotensin system", "C. Increased hepatic synthesis of thrombopoietin", "D. Increased prolyl hydroxylation of hypoxia-inducible factor 1-alpha", "E. Increased transcription of the von Hippel-Lindau tumor suppressor gene"],
  0,
  "The oxygen sensor is a controlled-degradation switch, and the exam tests its DIRECTION.\n\nIn NORMOXIA: prolyl hydroxylase enzymes use molecular oxygen as a substrate to hydroxylate proline residues on HIF-1-alpha → hydroxylated HIF-1-alpha is recognized by the von Hippel-Lindau protein → it is ubiquitinated and destroyed by the proteasome. Erythropoietin transcription stays low.\n\nIn HYPOXIA: there is not enough oxygen for the prolyl hydroxylases to work → HIF-1-alpha is NOT hydroxylated → VHL cannot bind it → DEGRADATION FALLS and HIF-1-alpha accumulates → it dimerizes with HIF-1-beta, binds the hypoxia response element of the EPO gene, and erythropoietin transcription rises.\n\nSo the correct phrasing is DECREASED DEGRADATION. Note this is the same axis that the HIF prolyl hydroxylase inhibitors (vadadustat) drug class exploits pharmacologically — they block the hydroxylase to simulate altitude.",
  {"1": "Renal hypoperfusion activates renin and would be correct for a question about this man's blood pressure or aldosterone. Erythropoietin responds to the oxygen CONTENT of blood, not to perfusion pressure; anemia raises erythropoietin with entirely normal renal blood flow.",
   "2": "Thrombopoietin is made constitutively by the liver and drives megakaryocyte production. It would be correct if his platelet count, not his hematocrit, had risen.",
   "3": "This is the correct molecule and the correct enzyme, but the wrong DIRECTION — and it is the intended trap. Prolyl hydroxylation REQUIRES oxygen, so hypoxia DECREASES it. Increased hydroxylation is what happens at sea level, and it would lower erythropoietin.",
   "4": "The von Hippel-Lindau protein is the ubiquitin ligase adaptor that destroys HIF, so increasing it would LOWER erythropoietin. Loss-of-function VHL mutations cause unopposed HIF signalling and are why VHL disease produces polycythemia and renal cell carcinoma — the opposite change from the one described."},
  "A protein that switches on red-cell production is normally destroyed as fast as it is made, and oxygen is what allows the destroying enzyme to work. Up a mountain there is less oxygen, so the protein survives and piles up.")

# ── 8. Thrombopoietin ──────────────────────────────────────────────────────
q("A 54-year-old woman with alcohol-associated cirrhosis is admitted to the hospital for evaluation of easy bruising. She has no fever. Physical examination shows scleral icterus, spider angiomas, shifting dullness, and scattered petechiae over the lower extremities. The spleen is palpated 4 cm below the left costal margin.\n\nLaboratory studies show:\nHemoglobin 11.2 g/dL (N=12.0–16.0 g/dL)\nHematocrit 34% (N=36%–46%)\nLeukocyte count 3,800/mm3 (N=4,500–11,000/mm3)\nPlatelet count 44,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 18 seconds (N=11–15 seconds)\nSerum albumin 2.4 g/dL (N=3.5–5.5 g/dL)\n\nDecreased hepatic production of which of the following most directly accounts for this patient's thrombocytopenia?",
  ["A. Erythropoietin", "B. Granulocyte colony-stimulating factor", "C. Interleukin-3", "D. Stem cell factor", "E. Thrombopoietin"],
  4,
  "This patient has two reasons to be thrombocytopenic, and the lead-in tells you which one it wants: decreased HEPATIC PRODUCTION.\n\nTHROMBOPOIETIN is synthesized constitutively by the LIVER (with a minor renal contribution), binds the c-MPL receptor on megakaryocytes and their precursors, and drives megakaryocyte proliferation, endomitotic nuclear replication and platelet shedding. In cirrhosis, hepatic synthetic function fails — which the prolonged prothrombin time and the albumin of 2.4 g/dL independently confirm — and thrombopoietin falls with it.\n\nThe splenomegaly is the deliberate decoy: congestive splenomegaly from portal hypertension genuinely sequesters platelets and contributes here, but it is a peripheral, NON-hepatic mechanism, and the lead-in asks specifically about decreased hepatic production.",
  {"0": "Erythropoietin is overwhelmingly renal in adults, and it drives the erythroid line. A deficiency would produce a hypoproliferative anemia, not thrombocytopenia — and her hemoglobin of 11.2 g/dL is the least abnormal value in the panel.",
   "1": "Granulocyte colony-stimulating factor is produced by macrophages, endothelium and fibroblasts, not by hepatocytes, and it drives neutrophil production. It would be correct if the question asked about her mildly low leukocyte count.",
   "2": "Interleukin-3 is a multilineage growth factor secreted by activated T LYMPHOCYTES, not hepatocytes. The stem specifies hepatic production, which excludes it regardless of its effect on megakaryocytes.",
   "3": "Stem cell factor is produced by marrow stromal cells and acts at the top of the hierarchy on c-KIT. It is neither hepatic nor megakaryocyte-specific, so a deficiency would depress all lineages rather than platelets selectively."},
  "The liver makes the hormone that tells the body to build platelets. A scarred liver makes less of it, so platelets run low.")

# ── 9. G-CSF ───────────────────────────────────────────────────────────────
q("A 61-year-old woman receives her second cycle of chemotherapy for breast cancer. After the first cycle, her absolute neutrophil count fell to 240/mm3 and she was hospitalized for 5 days with fever. She is otherwise well and takes no other medications. Her oncologist plans to give a recombinant growth factor after this cycle to shorten the duration of neutropenia.\n\nThe agent most appropriate for this indication acts on which of the following cell populations?",
  ["A. Committed granulocytic progenitors and mature neutrophils", "B. Erythroid colony-forming units in the marrow", "C. Megakaryocyte precursors expressing c-MPL", "D. Multipotent hematopoietic stem cells in the endosteal niche", "E. Peripheral blood T lymphocytes"],
  0,
  "The agent is FILGRASTIM (granulocyte colony-stimulating factor, G-CSF). The lead-in asks what it acts ON, which is the lineage-specificity point.\n\nG-CSF acts on COMMITTED GRANULOCYTIC PROGENITORS — it shortens their transit time through the marrow, expands the proliferating pool, and mobilizes the marginated and storage pools into the blood. It also enhances the function of MATURE neutrophils. Its action is confined to the granulocytic arm, which is exactly why it is the right drug when the problem is isolated neutropenia rather than pancytopenia.\n\nContrast with GM-CSF (sargramostim), which acts one branch point higher and stimulates granulocyte AND monocyte/macrophage lines; and with the erythroid agents (epoetin) and megakaryocyte agents (romiplostim, eltrombopag), which serve the other two lineages.",
  {"1": "Erythroid colony-forming units are the target of the erythropoiesis-stimulating agents, epoetin alfa and darbepoetin. That would be correct if the problem were her hemoglobin; her documented complication was febrile neutropenia.",
   "2": "c-MPL is the thrombopoietin receptor, targeted by romiplostim and eltrombopag. These are the right agents for chemotherapy-induced THROMBOCYTOPENIA, which is a different cytopenia from the one described.",
   "3": "Acting on the multipotent stem cell in the niche describes stem cell factor, and describes the mechanism by which plerixafor mobilizes CD34-positive cells for apheresis collection. Mobilizing stem cells into the blood does not shorten a neutrophil nadir.",
   "4": "T lymphocytes are the target of interleukin-2 (aldesleukin) and of modern immunotherapies. Stimulating T cells does nothing for a granulocyte count and is not the purpose of growth factor support after chemotherapy."},
  "Chemotherapy wipes out the infection-fighting white cells. This drug tells the marrow to hurry up and release more of that one specific cell type.",
  exim="fig_cytokines",
  excap="Hematopoiesis and its principal cytokines — each growth factor acts at a defined level of the hierarchy, which is what makes the drugs lineage-specific.")

# ── 10. Corrected reticulocyte count ───────────────────────────────────────
q("A 24-year-old woman comes to the office because of a 5-day history of fatigue and dark urine. She has no history of serious illness. Her temperature is 37.3°C (99.1°F), pulse is 104/min, respirations are 18/min, and blood pressure is 112/70 mm Hg. Physical examination shows scleral icterus and pallor; the spleen is palpated 3 cm below the left costal margin.\n\nLaboratory studies show:\nHemoglobin 7.5 g/dL (N=12.0–16.0 g/dL)\nHematocrit 22.5% (N=36%–46%)\nMean corpuscular volume 94 µm3 (N=80–100 µm3)\nReticulocyte count 8% (N=0.5%–1.5%)\nLactate dehydrogenase 540 U/L (N=45–200 U/L)\nHaptoglobin <10 mg/dL (N=30–200 mg/dL)\nTotal bilirubin 3.2 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.3 mg/dL (N=0.0–0.3 mg/dL)\n\nWhich of the following values most closely approximates this patient's corrected reticulocyte count?",
  ["A. 0.8%", "B. 1.6%", "C. 4.0%", "D. 8.0%", "E. 16.0%"],
  2,
  "The raw reticulocyte percentage is a FRACTION, and in anemia the denominator has shrunk — so the raw number always overstates marrow output. The correction restores a common denominator.\n\nCorrected reticulocyte count = reticulocyte % × (patient hematocrit ÷ 45)\n= 8% × (22.5 ÷ 45)\n= 8% × 0.5\n= 4.0%\n\nInterpretation, which is the reason the calculation exists: a corrected count ABOVE 2–3% means the marrow is responding appropriately, so the anemia is due to destruction or loss rather than a production defect. That fits everything else in the panel — the hemolysis trio moves as a unit here (LDH UP, haptoglobin UNDETECTABLE, indirect bilirubin UP with a normal direct fraction), alongside splenomegaly and jaundice.\n\nNote also that the hematocrit of 22.5% is consistent with a hemoglobin of 7.5 g/dL by the ×3 rule — always check that before trusting a panel.",
  {"0": "0.8% would be the result of dividing rather than multiplying by the hematocrit ratio, and it lands in the range that would indicate marrow FAILURE. That conclusion would contradict the undetectable haptoglobin and raised LDH.",
   "1": "1.6% is what you get if you use a denominator of 45 without first taking the ratio, or if you correct twice. It is also the value that would wrongly reclassify this hemolytic anemia as hypoproliferative.",
   "3": "8.0% is the RAW, uncorrected reticulocyte percentage, and it is the surface-read answer. It would be the correct corrected value only if the hematocrit were normal at 45%.",
   "4": "16.0% results from multiplying by 45 ÷ hematocrit — the ratio inverted. Applying that correction to an anemic patient would inflate the apparent marrow response rather than temper it."},
  "When you are very anemic, a percentage looks bigger than it really is because the total number of cells is small. You scale it down to compare fairly — here it halves, from 8% to 4%.",
  exim="fig_retics",
  excap="Peripheral blood, supravital stain. Reticulocytes retain a deep-blue granular meshwork of ribosomal RNA, are slightly larger and rounder than mature erythrocytes, and lack their central pallor.")

# ── 11. Marrow niche / CXCR4 mobilization ──────────────────────────────────
q("A 47-year-old man with multiple myeloma is scheduled for autologous hematopoietic stem cell transplantation. Before the transplant, CD34-positive cells must be collected from his peripheral blood by apheresis. After 4 days of granulocyte colony-stimulating factor, his peripheral CD34-positive cell count remains below the threshold required for collection. A second agent is added that blocks a chemokine receptor on hematopoietic stem cells, and the CD34-positive cell count rises sharply over the next 12 hours.\n\nThe added agent most likely interrupts binding between which of the following pairs?",
  ["A. c-KIT and stem cell factor", "B. CXCR4 and CXCL12", "C. Integrin alpha-4-beta-1 and fibronectin", "D. Notch1 and Jagged1", "E. P-selectin and P-selectin glycoprotein ligand 1"],
  1,
  "The niche is not a warehouse where cells are stored; it is an active anchoring system, and stem cell collection works by breaking the anchor.\n\nMarrow stromal cells and CXCL12-abundant reticular cells secrete CXCL12 (also called stromal cell-derived factor 1). Hematopoietic stem cells express its receptor, CXCR4. The CXCL12–CXCR4 bond is the dominant tether holding stem cells in the endosteal and perivascular niche.\n\nPLERIXAFOR is a reversible CXCR4 antagonist. Blocking the receptor releases the tether, and stem cells leave the marrow for the blood within hours — which is exactly the rapid 12-hour rise described. It is used precisely in this situation: the patient who mobilizes poorly on G-CSF alone.\n\nThis is also the clinical answer to 'why does the niche matter?' — three therapies live in it: mobilization for transplant, engraftment after transplant, and the niche-dependence of leukemic stem cells.",
  {"0": "c-KIT and stem cell factor is a genuine stem cell survival and proliferation signal, but stem cell factor is not a CHEMOKINE and the pair is not the positional anchor. Blocking it would impair stem cell survival rather than release cells into the blood.",
   "2": "Integrin alpha-4-beta-1 (VLA-4) binding to fibronectin and VCAM-1 is a real secondary adhesion mechanism in the niche, and natalizumab-like VLA-4 blockade does cause some mobilization. It is an adhesion-molecule pair, not the chemokine-receptor pair the stem specifies.",
   "3": "Notch1–Jagged1 signalling regulates stem cell fate decisions and self-renewal in the niche. It determines what the cell BECOMES, not where it is physically held.",
   "4": "P-selectin and its ligand mediate the rolling step of leukocyte adhesion to activated endothelium during inflammation. It is the wrong compartment entirely, and blocking it impairs neutrophil entry into tissues."},
  "Stem cells are held inside the marrow by a molecular Velcro. This drug unsticks the Velcro so the cells float into the bloodstream, where they can be collected.")

# ── 12. Aspirate vs core biopsy ────────────────────────────────────────────
q("A 67-year-old man is evaluated for a 4-month history of fatigue. His hemoglobin concentration is 9.1 g/dL, leukocyte count is 3,200/mm3, and platelet count is 96,000/mm3. A bone marrow procedure is performed at the posterior iliac crest, and two specimens are obtained: an aspirated liquid sample that is smeared and stained, and a cylindrical piece of intact bone and marrow that is decalcified, sectioned, and stained with hematoxylin and eosin.\n\nWhich of the following questions can be answered ONLY by the second specimen?",
  ["A. Whether Auer rods are present within blast cytoplasm", "B. Whether individual erythroid precursors show nuclear-cytoplasmic asynchrony", "C. Whether stainable iron is present within marrow macrophages", "D. Whether the marrow is hypocellular relative to the patient's age", "E. Whether the myeloid-to-erythroid ratio can be determined by differential count"],
  3,
  "The two specimens answer different questions, and the difference is ARCHITECTURE versus CYTOLOGY.\n\nThe ASPIRATE is a liquid sample that is smeared, so individual cells are spread in one layer and their fine cytoplasmic and nuclear detail is superb. It answers cytologic questions: blast percentage, Auer rods, dysplasia, the myeloid-to-erythroid ratio, iron stores by Prussian blue, and it supplies material for flow cytometry, cytogenetics and molecular studies.\n\nThe CORE BIOPSY preserves the marrow IN SITU — bone trabeculae, fat spaces and hematopoietic cells in their true spatial relationship. Only an intact core lets you state what fraction of the marrow space is hematopoietic tissue rather than fat, which is the definition of CELLULARITY. An aspirate is diluted by peripheral blood and by the act of suction, so it cannot be used to judge cellularity.\n\nThe core is also the only specimen that can show marrow FIBROSIS, granulomas, or focal metastatic infiltration, and it is the specimen that still yields an answer when the aspirate gives a dry tap.",
  {"0": "Auer rods are best seen on the ASPIRATE smear, where a blast lies flat in a single layer and its cytoplasmic detail is preserved. Decalcification and sectioning of a core degrade exactly this kind of fine detail.",
   "1": "Nuclear-cytoplasmic asynchrony in erythroid precursors — the hallmark of megaloblastic change — is a single-cell morphologic judgement, which is what the aspirate smear is for.",
   "2": "The Prussian blue stain for storage iron is performed on the ASPIRATE smear, and is one of the few genuine indications for marrow sampling in anemia. A core biopsy is decalcified, and decalcification can leach iron and make the stain unreliable.",
   "4": "The myeloid-to-erythroid ratio is obtained by counting several hundred individual nucleated cells on the aspirate smear. Counting cells one by one requires them spread in a monolayer, which a sectioned core does not provide."},
  "One sample is liquid marrow smeared on a slide, which is great for looking at single cells close up. The other is a solid core that keeps the marrow's structure, which is the only way to see how much of the space is actually making blood.",
  image="fig_aplastic",
  imcap="Core biopsy specimen of bone marrow (hematoxylin and eosin, medium power). Bony trabeculae are seen at the left and right; the intervening marrow space is largely occupied by clear, round fat spaces with only scattered residual hematopoietic cells.")

# ── 13. Cellularity / 100-minus-age ────────────────────────────────────────
q("A 70-year-old woman is evaluated for pancytopenia. A bone marrow core biopsy specimen is obtained and reported as showing 45% cellularity, with trilineage hematopoiesis and no fibrosis, granulomas, dysplasia, or increase in blasts. Her physician states that the cellularity is not the explanation for her cytopenias.\n\nWhich of the following best supports that conclusion?",
  ["A. Cellularity above 30% excludes a hypoproliferative process at any age", "B. Cellularity is expected to be approximately 100 minus the patient's age in years", "C. Cellularity is not interpretable on a core biopsy specimen and requires an aspirate", "D. Marrow cellularity is constant at approximately 50% throughout adult life", "E. Marrow cellularity rises with age as fat is replaced by hematopoietic tissue"],
  1,
  "Marrow cellularity is AGE-DEPENDENT, and the number alone means nothing until it is compared with what that patient's age predicts.\n\nThe working rule is CELLULARITY ≈ 100 − AGE (in years). A newborn's marrow is near 100% cellular; a 30-year-old runs about 70%; a 70-year-old runs about 30%. The rest of the marrow space is fat, and the proportion of fat rises steadily through adult life.\n\nFor this 70-year-old, the predicted cellularity is roughly 30%. Her measured 45% is therefore NORMAL to mildly increased — certainly not hypocellular. A marrow that is making plenty of cells while the blood counts are low points the workup away from production failure and toward peripheral destruction, sequestration, or ineffective hematopoiesis.\n\nThe trap is reading 45% as 'low' because it is under half. Against a predicted 30% it is not low at all.",
  {"0": "This invents a fixed threshold and, in doing so, abolishes the age adjustment that is the entire point. Thirty percent cellularity is normal at 70 years and severely hypocellular at 20 years; no single cut-off can be right for both.",
   "2": "This reverses the two specimens. Cellularity requires the intact architecture of a CORE biopsy precisely because an aspirate is diluted by blood and cannot show the tissue-to-fat proportion.",
   "3": "A constant 50% is a convenient approximation for a middle-aged adult, which is probably why it feels familiar, but applying it here would misclassify this patient's marrow as hypocellular and send the workup in the wrong direction.",
   "4": "This is the correct variable moving in the wrong direction, and it is the intended trap. Hematopoietic tissue is progressively replaced BY fat with age, so cellularity FALLS; the option describes the reverse."},
  "Bone marrow gets fattier as you age, so 'normal' fullness depends on how old you are. Roughly, 100 minus your age gives the expected percentage.")

# ── 14. Prussian blue / ringed sideroblasts ────────────────────────────────
q("A 72-year-old man is evaluated for a 6-month history of fatigue. He does not drink alcoholic beverages and takes no medications.\n\nLaboratory studies show:\nHemoglobin 9.4 g/dL (N=13.5–17.5 g/dL)\nHematocrit 28% (N=41%–53%)\nMean corpuscular volume 104 µm3 (N=80–100 µm3)\nReticulocyte count 0.6% (N=0.5%–1.5%)\nLeukocyte count 3,400/mm3 (N=4,500–11,000/mm3)\nPlatelet count 118,000/mm3 (N=150,000–400,000/mm3)\nSerum iron 190 µg/dL (N=65–175 µg/dL)\nSerum ferritin 620 ng/mL (N=20–250 ng/mL)\nTotal iron-binding capacity 240 µg/dL (N=250–400 µg/dL)\nSerum vitamin B12 480 pg/mL (N=200–900 pg/mL)\nSerum folate 12 ng/mL (N=2.5–20 ng/mL)\n\nA bone marrow aspirate is obtained and a special stain is performed, shown below.\n\nThe stain used to demonstrate this finding identifies which of the following?",
  ["A. Glycogen within cytoplasmic vacuoles", "B. Iron within erythroid precursor mitochondria", "C. Lipid within macrophage cytoplasm", "D. Myeloperoxidase within primary granules", "E. Ribosomal RNA within reticulocytes"],
  1,
  "The stain is PRUSSIAN BLUE (Perls stain), and it is the one special stain routinely applied to a marrow aspirate.\n\nPrussian blue reacts with ferric iron to produce a blue precipitate. It answers two questions at once: how much STORAGE iron sits in marrow macrophages, and whether iron is abnormally deposited inside ERYTHROID PRECURSORS. When the deposits form a ring of blue granules encircling the nucleus — iron trapped inside perinuclear MITOCHONDRIA because it cannot be incorporated into heme — the cell is a RINGED SIDEROBLAST.\n\nThe laboratory panel sets this up: a macrocytic anemia with other cytopenias in an older man, with iron studies that are HIGH ACROSS THE BOARD (high iron, high ferritin, LOW total iron-binding capacity) and normal B12 and folate. That is a picture of iron that is present but cannot be used — sideroblastic erythropoiesis, here in the setting of a myelodysplastic neoplasm.\n\nNote the contrast that iron studies make possible: iron deficiency gives low iron with HIGH binding capacity; this patient's low binding capacity with high ferritin excludes it outright.",
  {"0": "Glycogen is demonstrated by the periodic acid-Schiff stain, which produces block positivity in lymphoblasts. It would be relevant to classifying an acute leukemia, not to iron handling.",
   "2": "Lipid-laden macrophages are demonstrated by oil red O or Sudan black B on frozen material. Sudan black B is used in leukemia workups to confirm myeloid differentiation, and would be correct if the question concerned lineage assignment of blasts.",
   "3": "Myeloperoxidase staining identifies granulocytic lineage and is the stain that corroborates Auer rods in acute myeloid leukemia. It says nothing about iron, and the stem gives no increase in blasts.",
   "4": "Ribosomal RNA in reticulocytes is demonstrated by a SUPRAVITAL stain such as new methylene blue — the stain used to count reticulocytes. That is performed on peripheral blood, not on a marrow aspirate, and this patient's reticulocyte count is already reported as normal."},
  "This stain turns iron bright blue. Here it shows iron stuck in a ring inside the young red cells, which means the body has plenty of iron but cannot load it into hemoglobin.",
  image="fig_sideroblast",
  imcap="Bone marrow aspirate, Prussian blue stain. Several immature erythroid cells contain coarse blue granules arranged around the nucleus.")

# ── 15. When NOT to biopsy ─────────────────────────────────────────────────
q("A 42-year-old woman comes to the office because of a 4-month history of fatigue. She has heavy menstrual periods lasting 7 days. She has no history of serious illness and takes no medications. Physical examination shows pale conjunctivae and no organomegaly.\n\nLaboratory studies show:\nHemoglobin 9.8 g/dL (N=12.0–16.0 g/dL)\nHematocrit 29% (N=36%–46%)\nMean corpuscular volume 72 µm3 (N=80–100 µm3)\nRed cell distribution width 18.4% (N=11.5%–14.5%)\nReticulocyte count 0.7% (N=0.5%–1.5%)\nLeukocyte count 6,900/mm3 (N=4,500–11,000/mm3)\nPlatelet count 431,000/mm3 (N=150,000–400,000/mm3)\nSerum iron 22 µg/dL (N=65–175 µg/dL)\nTotal iron-binding capacity 468 µg/dL (N=250–400 µg/dL)\nSerum ferritin 6 ng/mL (N=20–250 ng/mL)\n\nWhich of the following is the most appropriate next step in management?",
  ["A. Bone marrow aspiration and biopsy", "B. Hemoglobin electrophoresis", "C. Oral iron supplementation", "D. Serum erythropoietin measurement", "E. Transfusion of packed red blood cells"],
  2,
  "The iron panel here is a complete, internally consistent row for IRON DEFICIENCY: low serum iron, HIGH total iron-binding capacity, low ferritin, microcytosis, a high red cell distribution width, and the reactive thrombocytosis that commonly accompanies it. There is a sufficient explanation for the losses in the history.\n\nWhen the diagnosis is already established non-invasively, the next step is TREATMENT, not more testing. Oral iron is first-line, and the response itself confirms the diagnosis — the reticulocyte count rises within about a week and the hemoglobin by about 1 g/dL every 2–3 weeks.\n\nThe marrow-biopsy distractor is the specific point of this item. A marrow examination is the historical gold standard for iron stores, but it is invasive, painful, and almost never necessary: ferritin and the transferrin saturation answer the question. Reserve marrow sampling for unexplained cytopenias, suspected marrow infiltration or malignancy, and cases where non-invasive testing has genuinely failed. None applies here — her white cell count is normal and her platelets are high, so there is no cytopenia to explain beyond the anemia itself.",
  {"0": "A marrow examination would be appropriate if she had unexplained cytopenias in more than one lineage, blasts or dysplasia on the smear, or an iron panel that did not fit. It is the wrong answer here precisely because the diagnosis has already been made from blood tests and a history of heavy menstrual losses.",
   "1": "Hemoglobin electrophoresis would be the next step if the microcytosis came with NORMAL iron studies, a normal or high red cell count and a normal red cell distribution width — the thalassemia trait profile. Her ferritin of 6 ng/mL excludes that pattern.",
   "3": "Serum erythropoietin measurement is used when a hypoproliferative anemia is unexplained, particularly in renal disease, or to evaluate polycythemia. It adds nothing once a definite cause of the anemia is in hand.",
   "4": "Transfusion is reserved for hemodynamic instability, active bleeding, or symptomatic anemia at a much lower threshold. She is stable at 9.8 g/dL with a chronic, correctable cause, and transfusing her would expose her to risk while treating a number rather than a patient."},
  "All her blood tests already say 'low iron', and her heavy periods explain why. Give her iron rather than putting a needle in her hip bone.")

# ── 16. Hgb vs Hct relationship ────────────────────────────────────────────
q("A 58-year-old man with poorly controlled type 2 diabetes mellitus is admitted to the hospital for evaluation of fatigue. A complete blood count performed on an automated analyzer reports a hemoglobin concentration of 17.9 g/dL and a hematocrit of 34%. A blood smear shows normochromic, normocytic erythrocytes with no agglutination, no spherocytes, and no fragmented cells. The plasma layer of a centrifuged specimen is creamy white rather than straw-coloured, and the serum triglyceride concentration is 3,400 mg/dL (N=<150 mg/dL).\n\nWhich of the following best explains the relationship between the reported hemoglobin concentration and the reported hematocrit?",
  ["A. The hematocrit is falsely decreased because agglutinated erythrocytes are counted as single particles", "B. The hemoglobin is falsely decreased because lipid binds hemoglobin and removes it from solution", "C. The hemoglobin is falsely elevated because sample turbidity increases light absorbance", "D. The values are internally consistent and indicate true polycythemia", "E. The values reflect true acute blood loss with delayed plasma refill"],
  2,
  "The first move with any complete blood count is to check the HEMOGLOBIN-TO-HEMATOCRIT RELATIONSHIP: the hematocrit is normally about THREE TIMES the hemoglobin. Here the hematocrit of 34% predicts a hemoglobin near 11.3 g/dL, but the analyzer reports 17.9 g/dL. That gap is far too wide to be biological, so one of the two numbers is wrong.\n\nThe two are measured by completely different physical principles, which is what makes the cross-check useful. HEMOGLOBIN is a direct CHEMICAL measurement: erythrocytes are lysed, hemoglobin is converted to a coloured derivative, and light ABSORBANCE is read in a spectrophotometer. HEMATOCRIT on a modern analyzer is CALCULATED from the directly counted erythrocyte number and the measured mean corpuscular volume — a particle-counting method that light scattering does not disturb.\n\nGross LIPEMIA makes the sample TURBID. Turbidity absorbs and scatters light in the photometer, and the analyzer cannot distinguish that lost light from light absorbed by the hemoglobin derivative, so it reports a FALSELY HIGH hemoglobin. Hyperbilirubinemia and marked leukocytosis interfere by the same optical route. The laboratory corrects it by replacing the lipemic plasma with an equal volume of saline and repeating the measurement — after which this patient's true hemoglobin will sit near the 11 g/dL his hematocrit predicts, and he is in fact ANEMIC, not polycythemic.\n\nThe smear findings are deliberate exclusions: no agglutination excludes a cold agglutinin, and normal morphology excludes spherocytes and fragments as a cause of index abnormalities.",
  {"0": "Cold agglutinins do corrupt this panel, but in the opposite direction and by a different route: clumped erythrocytes pass the aperture as single large particles, so the COUNT falls and the mean corpuscular volume rises. The stem explicitly states there is no agglutination, and warming the sample would resolve that artefact.",
   "1": "Lipid does not bind or sequester hemoglobin, and this option also has the direction wrong — a falsely LOW hemoglobin would make the reported value smaller than the hematocrit predicts, which is the reverse of what is reported.",
   "3": "Accepting these values is exactly the error the item is built to catch. True polycythemia raises hemoglobin and hematocrit TOGETHER — a hemoglobin of 17.9 g/dL should come with a hematocrit near 53%, not 34%.",
   "4": "Acute blood loss lowers hemoglobin and hematocrit together and in proportion, because whole blood is lost. Before plasma refill both values are near-normal; afterwards both fall. Neither phase produces two values that disagree with each other."},
  "Hematocrit is usually about three times the hemoglobin, and these two numbers do not match. His blood is full of fat, which clouds the sample and fools the machine's light-based hemoglobin reading into reading too high.")

# ── 17. MCHC / indices ─────────────────────────────────────────────────────
q("A 26-year-old woman comes to the office because of a 2-week history of fatigue and dark urine. Physical examination shows jaundice and splenomegaly.\n\nLaboratory studies show:\nHemoglobin 8.7 g/dL (N=12.0–16.0 g/dL)\nHematocrit 23% (N=36%–46%)\nMean corpuscular volume 84 µm3 (N=80–100 µm3)\nMean corpuscular hemoglobin concentration 37.8% Hb/cell (N=31%–36% Hb/cell)\nRed cell distribution width 17.1% (N=11.5%–14.5%)\nReticulocyte count 9% (N=0.5%–1.5%)\nLactate dehydrogenase 410 U/L (N=45–200 U/L)\nHaptoglobin 14 mg/dL (N=30–200 mg/dL)\nTotal bilirubin 3.6 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.4 mg/dL (N=0.0–0.3 mg/dL)\n\nThe elevated mean corpuscular hemoglobin concentration in this patient is best explained by which of the following?",
  ["A. A population of erythrocytes with reduced surface area relative to volume", "B. Cold agglutinin-induced erythrocyte clumping within the analyzer", "C. Incorporation of excess hemoglobin during erythroid maturation", "D. Lipemia causing spurious elevation of the measured hemoglobin", "E. Reticulocytosis raising the average cellular hemoglobin content"],
  0,
  "Mean corpuscular hemoglobin CONCENTRATION is hemoglobin divided by hematocrit — it asks how densely packed the hemoglobin is inside the average cell. A value above about 36–37% is one of the few genuinely useful red flags on a complete blood count, because very few things can raise it.\n\nThe cell cannot manufacture extra hemoglobin beyond its normal ceiling. So a high concentration almost always means the DENOMINATOR has shrunk: the cell has lost membrane and therefore surface area, while keeping its hemoglobin. The cell rounds up into a SPHERE — a spherocyte — whose volume is smaller for the same contents. Reduced surface area relative to volume is exactly that description.\n\nEverything else in the panel supports hereditary spherocytosis or an immune hemolytic anemia: brisk reticulocytosis at 9%, a hemolysis panel moving as a unit (LDH up, haptoglobin low, indirect bilirubin up), jaundice and splenomegaly, and a high red cell distribution width from the mixed population.\n\nThe practical rule worth carrying: MCHC above 36–37% means spherocytes, or an artefact — and the artefacts are cold agglutinins and lipemia, both of which the item must exclude before the biological answer stands.",
  {"1": "Cold agglutinins are a real cause of a spuriously high mean corpuscular hemoglobin concentration: clumped cells are counted as fewer, larger particles, so the calculated hematocrit falls and the ratio rises. It would be correct if the smear showed agglutination or the values corrected on warming the sample — neither is described.",
   "2": "There is a fixed ceiling on how much hemoglobin a normal erythroid precursor can load; the cell cannot become supersaturated. Hemoglobin synthesis defects move this value DOWN (hypochromia), never up.",
   "3": "Lipemia raises the measured hemoglobin optically and would raise the ratio — a genuine artefact, and worth excluding. It does not fit here, because there is no mention of lipemic serum and because a full hemolysis panel and splenomegaly demand a biological explanation.",
   "4": "Reticulocytes are LARGER than mature erythrocytes and contain proportionally LESS hemoglobin per unit volume, so marked reticulocytosis tends to raise the mean corpuscular volume and lower this ratio. The direction is wrong."},
  "This number says how tightly hemoglobin is packed inside a red cell. It goes up when the cell loses part of its outer skin and shrinks into a ball, with the same hemoglobin squeezed into less space.")

# ── 18. Acute blood loss and the CBC ───────────────────────────────────────
q("A 24-year-old man is brought to the emergency department 30 minutes after sustaining a stab wound to the left thigh. Bystanders report a large volume of blood at the scene. He is alert but anxious. His temperature is 36.6°C (97.9°F), pulse is 126/min, respirations are 24/min, and blood pressure is 94/58 mm Hg. Physical examination shows cool, pale extremities, delayed capillary refill, and a 3-cm laceration over the medial thigh with ongoing bleeding.\n\nLaboratory studies obtained on arrival show:\nHemoglobin 14.1 g/dL (N=13.5–17.5 g/dL)\nHematocrit 42% (N=41%–53%)\nMean corpuscular volume 89 µm3 (N=80–100 µm3)\nPlatelet count 232,000/mm3 (N=150,000–400,000/mm3)\n\nWhich of the following best explains this patient's hemoglobin concentration?",
  ["A. Hemoconcentration from third-spacing of plasma into injured tissue", "B. Loss of whole blood without a change in the ratio of erythrocytes to plasma", "C. Rapid release of stored erythrocytes from the splenic reservoir", "D. Reticulocytosis from an immediate marrow response to hemorrhage", "E. Splenic contraction driven by catecholamine release"],
  1,
  "Hemoglobin is a CONCENTRATION — grams per decilitre — not a total amount. Acute hemorrhage removes ERYTHROCYTES AND PLASMA TOGETHER, in the proportion they exist in the vessel, so the ratio between them is unchanged and the concentration initially reads NORMAL.\n\nThe hemoglobin only falls once the intravascular volume is restored and the remaining red cells are diluted — by endogenous fluid shifting from the interstitium over several hours, or far faster if crystalloid is given. A normal hemoglobin 30 minutes into a significant bleed is therefore expected and tells you nothing reassuring.\n\nThis is why the immediate threat in acute bleeding is VOLUME, not the number on the complete blood count. His tachycardia at 126/min, narrowed pulse pressure, cool extremities and delayed capillary refill are the findings that describe the severity; the hemoglobin lags behind them.\n\nContrast with chronic blood loss, which gives the opposite picture: plasma volume stays normal throughout, so the hemoglobin falls steadily and the cells become microcytic as iron stores are depleted.",
  {"0": "Third-spacing of plasma would CONCENTRATE the remaining erythrocytes and drive the hemoglobin ABOVE baseline, which is seen in burns and severe dehydration. His hemoglobin is normal, not elevated, and his cool extremities and hypotension describe volume LOSS rather than plasma redistribution.",
   "2": "The human spleen is not a physiologically significant erythrocyte reservoir, unlike in dogs and horses. Even complete emptying of the human splenic red cell pool would raise the hemoglobin only marginally and could not maintain it through a major hemorrhage.",
   "3": "A marrow response takes DAYS, not minutes: the reticulocyte count begins to rise at about 2–3 days and peaks near a week. Nothing the marrow does can influence a value drawn 30 minutes after injury.",
   "4": "Catecholamine-driven splenic contraction does occur in humans and contributes a small autotransfusion, so this is the most tempting distractor. Its magnitude is far too small to account for a fully normal hemoglobin, and it would be a partial contributor rather than the explanation."},
  "Bleeding loses red cells and the liquid they float in at the same time, so the mixture stays the same strength at first. The blood count only drops later, once the body refills the liquid part.")

# ── 19. Dry tap / architecture ─────────────────────────────────────────────
q("A 66-year-old man is evaluated for a 5-month history of fatigue, early satiety, and a 6-kg weight loss. The spleen is palpated 10 cm below the left costal margin. A peripheral blood smear shows teardrop-shaped erythrocytes, nucleated erythrocytes, and occasional immature granulocytes. Bone marrow aspiration is attempted twice at separate sites, and on both occasions no marrow can be drawn into the syringe.\n\nThe inability to aspirate marrow in this patient is best explained by which of the following marrow findings?",
  ["A. Complete replacement of hematopoietic tissue by mature adipocytes", "B. Deposition of reticulin and collagen fibrosis throughout the marrow space", "C. Diffuse infiltration by sheets of monomorphic lymphoid cells", "D. Necrosis of hematopoietic cells with preserved bony trabeculae", "E. Non-caseating granulomas surrounding marrow arterioles"],
  1,
  "A 'DRY TAP' — the inability to aspirate marrow despite correct technique at more than one site — means the marrow is not liquid enough to be sucked into a syringe. The commonest reason is that it has been replaced by FIBROUS TISSUE.\n\nEverything else in this vignette points the same way. TEARDROP erythrocytes (dacrocytes) are deformed as they squeeze out of a fibrotic marrow. The combination of nucleated red cells and immature granulocytes in the blood is a LEUKOERYTHROBLASTIC picture, which means the marrow-blood barrier has been disrupted. Massive splenomegaly reflects extramedullary hematopoiesis: when the marrow can no longer function, the fetal sites — spleen and liver — are recruited back into service. Together these describe PRIMARY MYELOFIBROSIS.\n\nThe practical consequence is the exam point: when the aspirate is dry, the CORE BIOPSY is the specimen that still yields a diagnosis, because it removes an intact cylinder of bone and marrow regardless of whether the tissue can be aspirated. A reticulin stain on that core grades the fibrosis.",
  {"0": "Complete fatty replacement describes severe aplastic anemia, and it is a genuine cause of a hypocellular aspirate. It does not fit the rest of the picture: aplastic anemia gives a SMALL or normal spleen and no teardrop cells or leukoerythroblastic smear, because there is no fibrosis to deform cells and nothing driving extramedullary hematopoiesis.",
   "2": "Dense lymphoid infiltration — as in chronic lymphocytic leukemia or a lymphoma involving the marrow — can produce a 'packed marrow' that aspirates poorly, so this is the best of the alternatives. It would not produce teardrop cells, and it would be expected to show lymphocytosis on the smear rather than the leukoerythroblastic pattern described.",
   "3": "Marrow necrosis does occur, typically in sickle cell disease or with widespread malignancy, and yields necrotic material rather than a true dry tap. It would not explain splenomegaly of this magnitude or the teardrop cells.",
   "4": "Granulomas, as in sarcoidosis or disseminated infection, are focal lesions found on the core biopsy and generally do not prevent aspiration of the surrounding marrow. They also do not cause teardrop poikilocytosis."},
  "The marrow has turned to scar tissue, so nothing liquid can be sucked out with a needle. Red cells get squeezed out of shape into teardrops, and the spleen takes over making blood, so it grows huge.")

# ── 20. Buffy coat / spin the tube ─────────────────────────────────────────
q("A medical student centrifuges an anticoagulated tube of her own venous blood at 3,000 rpm for 10 minutes. Three layers are visible afterwards: an upper straw-coloured layer occupying 55% of the column, a lower dark red layer occupying 44% of the column, and a thin greyish-white layer approximately 1% of the column thickness that lies at the interface between them.\n\nThe thin interface layer is composed principally of which of the following?",
  ["A. Erythrocytes and reticulocytes", "B. Fibrinogen and clotting factors", "C. Leukocytes and platelets", "D. Lipoproteins and chylomicrons", "E. Plasma proteins and immunoglobulins"],
  2,
  "Spinning a tube of anticoagulated blood separates it by DENSITY, and the three layers map directly onto the three cellular compartments of the blood.\n\nBOTTOM (about 45%, the hematocrit) — ERYTHROCYTES, the densest element.\nINTERFACE (about 1%) — the BUFFY COAT: LEUKOCYTES and PLATELETS, which are intermediate in density. Its greyish-white colour is what names it.\nTOP (about 55%) — PLASMA: water, proteins, electrolytes and clotting factors. It should be straw-yellow.\n\nThis single tube is also a diagnostic map: the bottom layer is where the anemias and polycythemias live, the buffy coat is where the leukemias and leukopenias live, and the plasma is where the paraproteins and coagulation disorders live. A buffy coat that is visibly thick suggests marked leukocytosis, and plasma that is milky rather than straw-coloured indicates lipemia.",
  {"0": "Erythrocytes and reticulocytes are the densest cellular elements and form the packed BOTTOM layer — the 44% dark red column described in the stem, which is the hematocrit.",
   "1": "Fibrinogen and the clotting factors are dissolved PROTEINS and remain in the plasma at the top. They would only form a separate layer if the blood had been allowed to clot, in which case the supernatant would be serum and would lack them altogether.",
   "3": "Lipoproteins and chylomicrons are the least dense components and float at the TOP of the plasma layer. In marked hypertriglyceridemia they make the plasma turbid and creamy rather than forming a discrete grey interface band.",
   "4": "Plasma proteins and immunoglobulins are dissolved in the upper straw-coloured layer and give it its colour and viscosity. They are not particulate and therefore cannot sediment into a discrete band."},
  "Spinning blood separates it into heavy red cells at the bottom, watery plasma on top, and a thin pale stripe in between that holds the white cells and platelets.")
