# Jeevs Edition — Batch 14: BENIGN WHITE CELL DISORDERS
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §26 s23-wbc-normal  — the five leukocytes, the ANC thresholds, neutropenia   (LO 76)
#   §27 s24-reactive    — leukocytosis, left shift, reactive versus malignant    (LO 66)
#   §28 s25-immunodef   — primary immunodeficiencies and where the block sits    (LO 4)
# Options alphabetised; "correct" is the 0-based index AFTER alphabetisation.
# Option lengths balanced per the audit rule — the keyed answer is not the longest.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ══════════════════ §26 · NORMAL LEUKOCYTES AND NEUTROPENIA ══════════════════

# ── 1. The absolute neutrophil count (§26) ───────────────────────────────────
q("A 58-year-old woman receiving chemotherapy for breast cancer is seen for a scheduled visit 10 days after her last cycle. She feels well and is afebrile. Her temperature is 36.8°C (98.2°F), pulse is 78/min, and blood pressure is 122/76 mm Hg. Physical examination shows no oral lesions, no skin breakdown, and no tenderness around her port site.\n\nLaboratory studies show:\nHemoglobin 10.8 g/dL (N=12.0–16.0 g/dL)\nHematocrit 33% (N=36%–46%)\nLeukocyte count 1,800/mm3 (N=4,500–11,000/mm3)\nSegmented neutrophils 20% (N=45%–74%)\nLymphocytes 72% (N=16%–45%)\nPlatelet count 138,000/mm3 (N=150,000–400,000/mm3)\n\nWhich of the following is the most accurate interpretation of her neutrophil status?",
  ["A. Control of her own skin and gut flora is now impaired",
   "B. Her neutrophil number is normal, since the percentage is normal",
   "C. No inflammatory response to an immune challenge is possible",
   "D. She has only a mild increase in her risk of infection",
   "E. The cells are marginated, so the finding is not meaningful"],
  0,
  "ANC = white cell count × percent neutrophils = 1,800 × 0.20 = 360/µL.\n\nThat is BELOW 500/µL, and the three thresholds to memorise say exactly what that means:\n\n• Below 1,000/µL — sharply increased risk of infection.\n• Below 500/µL — CONTROL OF ENDOGENOUS (SKIN, GUT) FLORA IS IMPAIRED. The patient's own commensals become the threat. This is also the definition of ABSOLUTE NEUTROPENIA.\n• Below 200/µL — NO INFLAMMATORY PROCESS in response to immune challenge; there are not enough cells left to mount a response at all.\n\nThe teaching point is that PERCENTAGE ALONE IS MISLEADING. Twenty percent does not sound alarming, and a busy clinician scanning the differential can miss it — but against a white count of 1,800 it is profound neutropenia. ALWAYS COMPUTE THE ABSOLUTE NUMBER. Note also that her lymphocyte percentage of 72% is not a lymphocytosis; it is what happens to the denominator when the neutrophils disappear.\n\nWhat follows clinically: she is at the threshold where her own mouth, skin and bowel organisms can invade, so she needs counselling about fever, and any fever must be treated as an emergency rather than observed. Granulocyte colony stimulating factor instructs the marrow to make more neutrophils and is used to lift a severely neutropenic count — the same idea as an erythropoiesis-stimulating agent, applied to a different lineage.",
  {"1": "This is the trap the question is built around. A percentage is a proportion of a total, and when the total collapses the proportion tells you nothing — 20% of 1,800 is a different cell count from 20% of 9,000.",
   "2": "Total loss of the inflammatory response comes at an ANC below 200/µL. Hers is 360/µL, so she retains some capacity to mount inflammation — which matters, because it means localizing signs may still appear.",
   "3": "A mild increase in risk describes the zone just under normal. Below 500/µL the risk is not mild: her endogenous flora can now invade, which is a categorical change rather than a gradual one.",
   "4": "Excessive peripheral pooling is a genuine mechanism of a low measured count — the cells exist but are marginated along vessel walls. It is not the explanation in a patient 10 days after chemotherapy, which is the classic nadir for marrow suppression."},
  "Twenty percent sounds fine, but it is twenty percent of a very small number. When you multiply it out she has only about a third of the infection-fighting cells she needs, and at that level the bacteria that normally live harmlessly on her skin and gut can invade.",
  exim="fig_slide_five_wbc",
  excap="The five normal circulating leukocytes. Neutrophils and lymphocytes dominate the differential; the rest are a small minority.")

# ── 2. Febrile neutropenia (§26) ─────────────────────────────────────────────
q("A 63-year-old man with acute myeloid leukemia is on day 12 after induction chemotherapy when he develops a single temperature of 38.5°C (101.3°F). He has no cough, no dysuria, no diarrhea, and no pain. His pulse is 104/min, respirations are 20/min, and blood pressure is 108/64 mm Hg. Physical examination shows no erythema or tenderness at his tunnelled catheter site, clear lungs, and no skin lesions. Chest radiograph shows no infiltrate and urinalysis is unremarkable.\n\nLaboratory studies show:\nHemoglobin 8.4 g/dL (N=13.0–16.0 g/dL)\nHematocrit 25% (N=37%–49%)\nLeukocyte count 600/mm3 (N=4,500–11,000/mm3)\nSegmented neutrophils 30% (N=45%–74%)\nPlatelet count 22,000/mm3 (N=150,000–400,000/mm3)\n\nWhich of the following is the most appropriate next step in management?",
  ["A. Await blood culture results before starting therapy",
   "B. Begin empiric broad-spectrum antibiotics now",
   "C. Give a colony stimulating factor and observe him",
   "D. Obtain CT imaging to localize a source first",
   "E. Start a bacteriostatic antibiotic and reassess"],
  1,
  "His ANC is 600 × 0.30 = 180/µL — below the 200/µL threshold, at which there is NO INFLAMMATORY PROCESS in response to immune challenge.\n\nThat threshold is the one that changes bedside behaviour, and the reason is worth stating plainly: THE CLASSIC SIGNS OF INFECTION ARE THE INFLAMMATORY RESPONSE, AND THAT RESPONSE IS MADE OF NEUTROPHILS. PUS IS DEAD NEUTROPHILS. Consolidation on a chest film is largely neutrophilic exudate. Erythema, swelling and induration around a wound or line depend on neutrophil recruitment. With too few cells to produce any of it, a serious infection can be present with ALMOST NO LOCALIZING SIGNS — and FEVER MAY BE THE ONLY SIGN.\n\nSo his clean examination, clear chest film and normal urinalysis are not reassurance. They are exactly what a profoundly neutropenic patient with an established infection looks like.\n\nFEBRILE NEUTROPENIA IS AN EMERGENCY, treated with empiric broad-spectrum antibiotics BEFORE ANY SOURCE DECLARES ITSELF. The progression to avoid is fever and chills → sepsis → multisystem organ failure. Cultures are drawn, but therapy does not wait for them.\n\nA colony stimulating factor may be added to lift the count, and it is part of the therapy list — but it takes days to work and is an adjunct, not the first move.",
  {"0": "Cultures should be drawn, and they will guide de-escalation later. Waiting for them costs hours in a patient who has no capacity to contain an infection himself, and in sepsis every hour of delay matters.",
   "2": "Granulocyte colony stimulating factor instructs the marrow to make more neutrophils and has a real role here. It does not treat the organism, and its effect takes days — the antibiotics cannot wait that long.",
   "3": "Imaging is reasonable alongside treatment, and will be done. Making it the FIRST step repeats the error of the clean examination: a patient who cannot form an exudate may have a normal-looking scan early in a serious pneumonia.",
   "4": "A bacteriostatic drug only stops organisms multiplying and RELIES ON THE PATIENT TO CLEAR WHAT IS ALREADY THERE. In a neutropenic patient that second half never happens, which is why an apparently appropriate antibiotic can seem not to work."},
  "He has almost no infection-fighting cells, so his body cannot produce the usual redness, swelling or pus that shows where an infection is. A fever may be the only clue he gets — so you treat immediately and look for the source afterwards.")

# ── 3. Duffy-null (§26) ──────────────────────────────────────────────────────
q("A 24-year-old man of West African ancestry is referred to hematology because of a persistently low neutrophil count found on three occasions over 4 years. He has never had an unusual, severe, or prolonged infection, has never been hospitalized, and takes no medications. Two previous evaluations, including a bone marrow examination 2 years ago, showed no abnormality. His temperature is 36.7°C (98.1°F), pulse is 68/min, and blood pressure is 118/72 mm Hg. Physical examination shows no oral ulceration, no lymphadenopathy, and no splenomegaly.\n\nLaboratory studies show:\nHemoglobin 14.6 g/dL (N=13.0–16.0 g/dL)\nHematocrit 44% (N=37%–49%)\nLeukocyte count 3,900/mm3 (N=4,500–11,000/mm3)\nAbsolute neutrophil count 1,300/µL (N=1,800–7,000/µL)\nPlatelet count 246,000/mm3 (N=150,000–400,000/mm3)\n\nWhich of the following is the most likely explanation?",
  ["A. Chronic idiopathic neutropenia requiring repeat marrow biopsy",
   "B. Constitutionally low count of the Duffy-null phenotype",
   "C. Cyclic neutropenia with a 21-day periodicity",
   "D. Drug-induced suppression of granulocyte production",
   "E. Early myelodysplastic syndrome with a hypocellular marrow"],
  1,
  "Duffy is a blood group antigen, and it is the receptor Plasmodium vivax uses to enter red cells. DUFFY-NULL INDIVIDUALS ARE THEREFORE RESISTANT TO P. VIVAX MALARIA, which is why the phenotype became common in populations of African ancestry — the same selection story as sickle trait, G6PD deficiency and thalassemia.\n\nSeparately, and for reasons still being worked out, DUFFY-NULL INDIVIDUALS RUN A CONSTITUTIONALLY LOWER NEUTROPHIL COUNT — with a PERFECTLY FUNCTIONAL IMMUNE SYSTEM AND NO INCREASED INFECTION RISK. His four years of a stable count with no unusual infections and a normal marrow is the evidence: this is his normal, not a disease.\n\nThe historical harm has been threefold, and it is the reason this is taught: UNNECESSARY INVESTIGATION (repeat counts, marrow biopsies — he has already had one), EXCLUSION FROM CLINICAL TRIALS whose entry criteria used a single population reference range, and UNDER-DOSING OF CHEMOTHERAPY in patients judged neutropenic when they were not.\n\nThe wider lesson the lecture draws: every time the immune system is better understood, so is the question of WHAT THE APPROPRIATE REFERENCE RANGE IS FOR A GIVEN PATIENT. A reference interval derived from one population is not a definition of health for every patient.",
  {"0": "Chronic idiopathic neutropenia is a diagnosis of exclusion, and repeating a marrow examination that was normal 2 years ago in a man who has never had an infection adds risk and cost without a question to answer.",
   "2": "Cyclic neutropenia oscillates on a roughly 21-day cycle, with the ANC dropping to near zero during nadirs and producing recurrent mouth ulcers, fevers and gingivitis. His counts are stable across years and he has no such symptoms.",
   "3": "Drugs are the usual cause of neutropenia in ADULTS, so this deserves consideration in any case — but he takes no medications, and drug-induced neutropenia does not persist unchanged for 4 years.",
   "4": "Myelodysplasia would be extraordinary at 24 and would not sit still for 4 years. It also typically brings dysplastic morphology, macrocytosis and other cytopenias; his hemoglobin, MCV and platelets are all normal."},
  "Some people naturally run a lower neutrophil count and are completely healthy — the same genetic trait also protects against one type of malaria. For years this was treated as a disease, which led to needless tests and even to under-dosing cancer drugs.")

# ── 4. Mechanisms of neutropenia (§26) ───────────────────────────────────────
q("A 67-year-old woman is seen because of a sore throat and fatigue. Six weeks ago she was started on methimazole for Graves disease. She takes no other medications, has no travel history, and has had no recent viral illness. Her temperature is 38.2°C (100.8°F), pulse is 96/min, and blood pressure is 126/78 mm Hg. Physical examination shows pharyngeal ulceration without exudate, and no splenomegaly or lymphadenopathy.\n\nLaboratory studies show:\nHemoglobin 12.6 g/dL (N=12.0–16.0 g/dL)\nHematocrit 38% (N=36%–46%)\nLeukocyte count 1,500/mm3 (N=4,500–11,000/mm3)\nAbsolute neutrophil count 150/µL (N=1,800–7,000/µL)\nPlatelet count 268,000/mm3 (N=150,000–400,000/mm3)\n\nA bone marrow examination shows markedly reduced granulocytic precursors with normal erythroid and megakaryocytic lines. Which of the following is the most likely mechanism?",
  ["A. Accelerated immune-mediated destruction in the periphery",
   "B. Impaired production caused by a drug",
   "C. Marrow replacement by metastatic carcinoma",
   "D. Peripheral margination of circulating neutrophils",
   "E. Splenic sequestration from portal hypertension"],
  1,
  "Neutropenia has three mechanisms, and the first of them splits by age in a way that changes what you ask about first in the history:\n\n• INEFFECTIVE PRODUCTION — DRUGS are the usual cause IN ADULTS, and INFECTIONS the usual cause IN CHILDREN. Also aplastic anemia, marrow replacement, and transplantation.\n• ACCELERATED DESTRUCTION — immune-mediated destruction, or splenic sequestration (the hypersplenism mechanism applied to the white cell line).\n• EXCESSIVE PERIPHERAL POOLING — the cells EXIST but are marginated along vessel walls rather than circulating, so the measured count understates them.\n\nEverything here points at the first: a new drug 6 weeks ago, an isolated neutropenia with normal hemoglobin and platelets, and a marrow showing the granulocytic line specifically depleted while the other two lines are intact. Methimazole is a classic offender.\n\nHer ANC of 150/µL is below 200, so she cannot mount an inflammatory response — which is why her pharyngeal ulceration has NO EXUDATE. Pus is dead neutrophils, and she has none to send. That absent exudate is a finding, not a reassurance.\n\nManagement: stop the drug, treat this as febrile neutropenia with empiric broad-spectrum antibiotics, and consider a colony stimulating factor to shorten the recovery.",
  {"0": "Immune destruction is a real mechanism and can be drug-associated too, so it belongs on the list. It consumes cells in the periphery, and the marrow responds by INCREASING granulocytic precursors — the opposite of what her marrow shows.",
   "2": "Marrow replacement by tumour causes ineffective production, but it crowds out ALL lineages and typically produces a leukoerythroblastic smear with nucleated red cells and tear-drop cells. Her other two lines are normal.",
   "3": "Margination means the cells are present but stuck to vessel walls, so the measured count understates the true number. The marrow would be normal, and her marrow is not — the precursors themselves are gone.",
   "4": "Splenic sequestration pools cells in an enlarged spleen and usually depresses more than one line. She has no splenomegaly, and again the marrow finding points at production rather than at pooling."},
  "A drug she started six weeks ago has shut down the part of her marrow that makes infection-fighting cells. In adults, medication is the usual culprit; in children it is usually an infection.",
  exim="fig_slide_immune_function",
  excap="Normal immune function — production, maturation, surveillance, and the enzymes and mediators. Each component maps onto a disease when it fails.")

# ── 5. Bacteriostatic therapy in a defenceless host (§26) ────────────────────
q("A 71-year-old man with severe neutropenia after chemotherapy has a urinary tract infection with Escherichia coli. Susceptibility testing reports the organism as susceptible to the agent he is receiving, and blood cultures are negative. After 4 days of therapy he remains febrile with persistent bacteriuria, and there is no obstruction on imaging and no indwelling catheter. His absolute neutrophil count is 120/µL (N=1,800–7,000/µL). The agent he is receiving inhibits bacterial protein synthesis and halts replication without killing the organism.\n\nWhich of the following best explains the failure of therapy?",
  ["A. Neutrophil enzymes are required to activate the antibiotic",
   "B. The antibiotic does not penetrate urine in neutropenia",
   "C. The drug stops growth but the host must clear the organism",
   "D. The organism acquired resistance during the course of therapy",
   "E. There is an undiagnosed second infection driving the fever"],
  2,
  "A BACTERICIDAL drug kills the organism outright. A BACTERIOSTATIC one only stops it multiplying and RELIES ON THE PATIENT TO CLEAR WHAT IS ALREADY THERE. In a neutropenic or immunodeficient patient that second half never happens — WHICH IS WHY AN APPARENTLY APPROPRIATE ANTIBIOTIC CAN SEEM NOT TO WORK.\n\nThat is the whole answer here, and it explains a laboratory report that looks contradictory: the organism genuinely is susceptible in vitro, because susceptibility testing measures whether the drug inhibits growth in a tube. The tube has no immune system. The patient, at an ANC of 120/µL, effectively does not either.\n\nThe same principle appears in the sepsis bundle, where the treatment list specifies BACTERICIDAL antimicrobial therapy rather than merely bacteriostatic — for exactly this reason, in a patient whose host response has been overwhelmed.\n\nThe management change is to switch to a bactericidal agent, and to keep the broader febrile-neutropenia rules in view: empiric broad-spectrum cover, attention to the possibility of a source that cannot declare itself because he cannot form an exudate, and consideration of a colony stimulating factor to shorten the neutropenic window.\n\nThe general lesson worth carrying: ANTIBIOTIC CHOICE IN A NEUTROPENIC PATIENT IS NOT THE SAME DECISION AS IN AN IMMUNOCOMPETENT ONE, even when the culture result is identical.",
  {"0": "No antibiotic requires neutrophil enzymes for activation. Neutrophils clear organisms directly by phagocytosis and the respiratory burst; they are not part of the drug's pharmacology.",
   "1": "Urinary penetration is a genuine consideration in choosing an agent for pyelonephritis versus cystitis, so it is worth asking about. Neutropenia does not alter a drug's renal excretion or its concentration in urine.",
   "3": "Emergent resistance during therapy does occur, particularly with some organisms and agents, and would be detected by repeat culture. It is the less likely explanation when a mechanistic one — a static drug in a host who cannot finish the job — is sitting in the stem.",
   "4": "A second occult infection is always worth considering in a persistently febrile neutropenic patient, and the workup should continue. It does not explain the PERSISTENT BACTERIURIA with an organism reported as susceptible."},
  "The antibiotic he is on only freezes the bacteria in place; it is the body's own cells that finish them off. He has almost no such cells, so the bacteria simply sit there waiting.")

# ── 6. Infection without leukocytosis (§26) ──────────────────────────────────
q("A 6-day-old neonate born at 38 weeks' gestation is brought to the emergency department because of poor feeding, lethargy, and temperature instability. His temperature is 35.9°C (96.6°F), pulse is 182/min, respirations are 68/min, and blood pressure is 58/32 mm Hg. Physical examination shows mottled skin and delayed capillary refill.\n\nLaboratory studies show:\nHemoglobin 15.2 g/dL (N=14.0–20.0 g/dL)\nHematocrit 46% (N=42%–60%)\nLeukocyte count 2,800/mm3 (N=5,000–21,000/mm3)\nBand forms 18% (N=0%–5%)\nPlatelet count 84,000/mm3 (N=150,000–400,000/mm3)\nC-reactive protein 9.4 mg/dL (N=<1.0 mg/dL)\n\nWhich of the following is the most accurate interpretation of the leukocyte count?",
  ["A. A suppressed count is compatible with infection in a neonate",
   "B. Infection raises the leukocyte count, so sepsis is unlikely",
   "C. The count indicates marrow failure and warrants a biopsy",
   "D. The count points to a viral rather than a bacterial cause",
   "E. The low count is an artefact of a partly clotted specimen"],
  0,
  "INFECTION DOES NOT ALWAYS RAISE THE COUNT. In NEWBORNS, and in certain viral infections, the white cell count can be SUPPRESSED instead. A low count in a septic-looking neonate is an ominous finding, not a reassuring one.\n\nThe same bidirectional logic runs through the sepsis criteria: the leukocyte criterion is satisfied by leukocytosis above 12,000/µL, leukopenia below 4,000/µL, OR a normal count with more than 10% immature forms. His count of 2,800/mm3 satisfies it twice over, since he also has 18% BANDS — a left shift, meaning a marrow releasing cells before they are finished because demand is high.\n\nThe temperature criterion is bidirectional too, and he demonstrates that as well: his temperature is 35.9°C, HYPOthermia rather than fever, which in a neonate is a classic presentation of serious bacterial infection.\n\nThe rest of his panel fits sepsis rather than a benign viral illness: thrombocytopenia at 84,000/mm3 from consumption, a C-reactive protein of 9.4 mg/dL, tachycardia, tachypnea and hypotension with poor perfusion.\n\nThe clinical consequence: this is sepsis until proven otherwise, and sepsis is TIME-DEPENDENT organ dysfunction — blood cultures, bactericidal antimicrobials, fluids and a lactate, all delivered together and early rather than sequentially as results return.",
  {"1": "This is the belief the question exists to dismantle. The rule holds often enough to feel reliable, and it fails in precisely the patients who are sickest — neonates and some viral infections — which is what makes it dangerous.",
   "2": "Marrow failure would be an unusual first presentation at 6 days and would not explain a C-reactive protein of 9.4 mg/dL with hypotension and mottling. The left shift argues for a marrow being driven hard, not one that has stopped.",
   "3": "A viral cause is possible in a neonate — herpes simplex and enterovirus are named neonatal triggers of sepsis — and must be considered. The count itself does not make that distinction, and a raised procalcitonin would be the marker pointing at bacteria.",
   "4": "A partly clotted specimen does lower every count, and 'no clots and no clumps' is an explicit acceptance criterion. It would depress the hemoglobin and hematocrit too, and his are normal."},
  "You expect the white cell count to go up when there is an infection. In newborns it often goes down instead — so a low count in a baby this sick is a danger sign rather than a good sign.")

# ══════════════════ §27 · REACTIVE VERSUS MALIGNANT ══════════════════

# ── 7. The leukemoid reaction (§27) ─────────────────────────────────────────
q("A 58-year-old man is admitted with a perforated appendix and generalized peritonitis. He is febrile and has undergone laparotomy with washout. He has no lymphadenopathy, no splenomegaly, and no night sweats or weight loss.\n\nLaboratory studies show:\nHemoglobin 11.4 g/dL (N=13.0–16.0 g/dL)\nHematocrit 34% (N=37%–49%)\nLeukocyte count 62,000/mm3 (N=4,500–11,000/mm3)\nPlatelet count 412,000/mm3 (N=150,000–400,000/mm3)\n\nThe peripheral smear shows Döhle bodies, coarse toxic granulation, and cytoplasmic vacuolization in neutrophils, together with occasional myelocytes and metamyelocytes. Blasts constitute 1% of leukocytes. Which of the following is the most likely explanation?",
  ["A. Acute myeloid leukemia presenting with hyperleukocytosis",
   "B. Chronic lymphocytic leukemia with a reactive component",
   "C. Chronic myelogenous leukemia driven by BCR-ABL",
   "D. Leukemoid reaction to intra-abdominal sepsis",
   "E. Primary myelofibrosis with extramedullary hematopoiesis"],
  3,
  "A LEUKEMOID REACTION is severe leukocytosis with immature cells in the peripheral blood, WHICH MAY MIMIC A NEOPLASTIC PROLIFERATION — and that mimicry IS the clinical problem, because it decides whether a patient gets antibiotics or a bone marrow biopsy.\n\nThree features on this smear are the reactive signature: DÖHLE BODIES, TOXIC GRANULATION and VACUOLIZATION. These are the changes of a neutrophil WORKING HARD, and they do not belong to a malignant clone.\n\nThe second argument is the BLAST PYRAMID. A reactive left shift keeps the normal proportions: a few blasts, more promyelocytes, more myelocytes, and progressively more cells as you approach the mature end — a pyramid standing on its point. His blasts are 1% with myelocytes and metamyelocytes present, so the pyramid is the right way up. If it were inverted — few mature cells and a lot of immature forms and blasts — that is the concerning pattern.\n\nThe third argument is context: an obvious inflammatory source, other cell lines close to normal (a reactive marrow keeps making red cells and platelets), and NO B SYMPTOMS — fever, night sweats and weight loss.\n\nAnd the resolving test if doubt remains: DURATION. Reactive morphology resolves as the infection clears, whereas a leukemia persists after the patient gets better. The lecture's advice is to keep a LOW THRESHOLD TO SEND FLOW CYTOMETRY, since it identifies a clonal population directly — better an unnecessary flow than a missed leukemia.",
  {"0": "Acute myeloid leukemia would show an EXCESS OF BLASTS out of proportion to the left shift — the inverted pyramid — often with Auer rods, and typically with anemia and thrombocytopenia from marrow crowding. His blasts are 1% and his platelets are raised.",
   "1": "Chronic lymphocytic leukemia produces a LYMPHOCYTOSIS of mature-appearing cells with smudge cells on the smear. This is a neutrophilic picture with granulocyte precursors.",
   "2": "Chronic myelogenous leukemia is the important alternative, since it looks very reactive and is driven by the BCR-ABL fusion oncogene. The tells that are absent here are BASOPHILIA — for reasons that are not obvious CML produces a lot of basophils — and persistence after the acute illness resolves. Confirm with BCR-ABL testing rather than morphology.",
   "4": "Myelofibrosis is on the differential for a leukemoid picture, and it would come with a LEUKOERYTHROBLASTIC smear — nucleated red cells and tear-drop cells — plus splenomegaly. Neither is described, and he has an obvious alternative explanation in his abdomen."},
  "A severe infection can drive the white count as high as a leukemia does. The giveaway is what the cells look like: these are ordinary cells working overtime, with the right mix of young and mature forms, in a man with an obvious infection.",
  exim="fig_toxic_granulation",
  excap="Toxic granulation — coarse dark granules in a neutrophil responding hard to a stimulus, not a malignant change.")

# ── 8. The inverted pyramid (§27) ────────────────────────────────────────────
q("A 34-year-old woman is evaluated for 3 weeks of fatigue, gum bleeding, and bruising. She has had no recent infection and no sick contacts. Her temperature is 37.9°C (100.2°F), pulse is 98/min, and blood pressure is 112/68 mm Hg. Physical examination shows gingival hypertrophy, scattered ecchymoses, and no splenomegaly.\n\nLaboratory studies show:\nHemoglobin 7.6 g/dL (N=12.0–16.0 g/dL)\nHematocrit 23% (N=36%–46%)\nLeukocyte count 38,000/mm3 (N=4,500–11,000/mm3)\nPlatelet count 26,000/mm3 (N=150,000–400,000/mm3)\n\nThe peripheral smear shows cells with scant cytoplasm, open powdery chromatin, and prominent nucleoli; every cell looks like the others. Blasts constitute 62% of leukocytes, with relatively few mature granulocytes. Occasional needle-shaped cytoplasmic inclusions are seen. Which of the following is the most appropriate next step?",
  ["A. Obtain flow cytometry and a bone marrow examination",
   "B. Repeat the count in 2 weeks after the illness resolves",
   "C. Send BCR-ABL testing and begin a tyrosine kinase inhibitor",
   "D. Start empiric antibiotics and follow the count",
   "E. Test for Epstein-Barr virus and monitor expectantly"],
  0,
  "Every discriminator points the same way, and none of them is the raw white count.\n\nTHE BLAST PYRAMID IS INVERTED. A reactive left shift keeps normal proportions — a few blasts, more promyelocytes, more myelocytes, progressively more toward the mature end. Here there are relatively few mature cells and 62% blasts. In the lecture's own phrasing: IF YOU ARE SEEING MORE BLASTS THAN ANYTHING ELSE, IT IS PROBABLY SOMETHING LIKE LEUKEMIA.\n\nTHE MORPHOLOGY IS MALIGNANT on the six criteria: an INCREASED nuclear-to-cytoplasmic ratio with SCANT cytoplasm, OPEN POWDERY CHROMATIN (a cell actively transcribing), PROMINENT NUCLEOLI (ribosome production for rapid division), and a MONOCLONAL APPEARANCE — every cell looks like the same cell. Contrast the reactive pattern: abundant cytoplasm forming a 'skirt' around neighbouring red cells, coarse clumped chromatin, small occasional nucleoli, and a VARIETY of appearances, because a polyclonal response is heterogeneous.\n\nTHE OTHER CELL LINES HAVE FAILED — the sixth criterion, and the one that needs no microscope. A reactive marrow keeps making red cells and platelets. Hers are 7.6 g/dL and 26,000/mm3.\n\nAND THE AUER RODS SETTLE IT. Granules arranged into needle-shaped rods mean a malignant cell, and specifically a MYELOID leukemia. Unlike a nucleolus, they carry no ambiguity.\n\nFlow cytometry demonstrates clonality directly, which is the one thing morphology can only hint at.",
  {"1": "Waiting is the reactive-disease strategy, and duration genuinely does settle most ambiguous cases — reactive changes resolve as the illness clears. Nothing here is ambiguous, and 2 weeks of untreated acute leukemia with a platelet count of 26,000/mm3 is dangerous.",
   "2": "BCR-ABL defines chronic myelogenous leukemia, where the picture is a mature-appearing left shift with basophilia rather than 62% blasts. Starting a tyrosine kinase inhibitor before the diagnosis is established treats the wrong disease.",
   "3": "Antibiotics are appropriate if she becomes febrile and neutropenic, and her temperature bears watching. They do not address a marrow full of blasts, and following the count defers the diagnosis.",
   "4": "Epstein-Barr virus causes a reactive lymphocytosis with large atypical lymphocytes that have ABUNDANT cytoplasm and coarse chromatin — the opposite morphology — and it does not produce Auer rods or pancytopenia in the other lines."},
  "Her blood is full of the youngest, most immature cells, and they all look identical — that means one cell has multiplied out of control. Healthy responses produce a mixture of cells at every stage.",
  exim="fig_slide_reactive_malignant",
  excap="The six morphological criteria, side by side. A reactive cell is busy and mature; a malignant cell is arrested and young.")

# ── 9. Reactive lymphocytosis (§27) ─────────────────────────────────────────
q("A 19-year-old college student is evaluated for 10 days of sore throat, fever, and fatigue. Two roommates have had similar symptoms. Her temperature is 38.3°C (100.9°F), pulse is 88/min, and blood pressure is 114/70 mm Hg. Physical examination shows tonsillar enlargement without exudate, tender posterior cervical lymphadenopathy, and a spleen tip palpable below the left costal margin. She has had no night sweats and no weight loss.\n\nLaboratory studies show:\nHemoglobin 13.2 g/dL (N=12.0–16.0 g/dL)\nHematocrit 39% (N=36%–46%)\nLeukocyte count 16,400/mm3 (N=4,500–11,000/mm3)\nLymphocytes 62% (N=16%–45%)\nPlatelet count 208,000/mm3 (N=150,000–400,000/mm3)\n\nThe smear shows large lymphocytes with abundant cytoplasm that moulds around adjacent erythrocytes, coarse clumped chromatin, occasional small nucleoli, and a variety of cell appearances. Which of the following best characterizes this lymphocyte population?",
  ["A. Indeterminate without immunoglobulin gene rearrangement",
   "B. Malignant, because the cells are enlarged and atypical",
   "C. Malignant, because the nucleoli indicate proliferation",
   "D. Reactive, because the cells are uniform in appearance",
   "E. Reactive, because the cells vary and retain cytoplasm"],
  4,
  "Five of the six criteria point to a REACTIVE population:\n\n• ABUNDANT CYTOPLASM MOULDING AROUND RED CELLS — the classic 'SKIRT', and a DECREASED nuclear-to-cytoplasmic ratio.\n• COARSE, CLUMPED, DENSE CHROMATIN — a differentiated cell.\n• OCCASIONAL, SMALL NUCLEOLI.\n• A VARIETY OF APPEARANCES — a polyclonal response, not a monoclonal one.\n• OTHER CELL LINES CLOSE TO NORMAL — her hemoglobin and platelets are untouched, so no marrow crowding.\n\nThe memory hook that organizes it: A REACTIVE CELL IS BUSY, A MALIGNANT CELL IS YOUNG. A reactive lymphocyte is a MATURE cell responding to something — it has grown cytoplasm, its chromatin is condensed because it is differentiated, and its neighbours look different because many different clones responded. A malignant cell is ARRESTED AT AN IMMATURE STAGE: scant cytoplasm, open powdery chromatin, prominent nucleoli, and every cell identical because they descend from one clone.\n\nThe most important corollary, and the one students reliably get backwards: 'THE CELLS LOOK ABNORMAL' IS A WEAKER FINDING THAN 'THE CELLS ALL LOOK THE SAME.' Reactive cells are SUPPOSED to look abnormal — a lymphocyte responding to a virus enlarges, grows cytoplasm and may develop a nucleolus, all of which is a healthy cell doing its job. UNIFORMITY is the finding that matters, because clonality in hematology is the thing that is never benign.\n\nHer clinical background confirms it: acute duration, sick contacts, and no B symptoms.",
  {"1": "Enlargement and atypia are exactly what a hard-working reactive lymphocyte looks like. Treating abnormality alone as evidence of malignancy is the single commonest misreading of a smear.",
   "2": "A nucleolus is the site of active transcription and translation, so ANY REACTIVE CELL WORKING HARD WILL HAVE ONE. What is abnormal is MANY nucleoli, or very large ones — hers are occasional and small.",
   "3": "Uniformity is the MALIGNANT criterion, not the reactive one — a monoclonal population all descends from a single cell. Her smear shows a variety of appearances, which is the polyclonal signature.",
   "0": "Gene rearrangement studies and flow cytometry do demonstrate clonality directly, and the advice is to keep a low threshold for sending flow when in doubt. Here five criteria, the clinical picture and the absence of B symptoms make the reading confident."},
  "Her lymphocytes look big and strange, but that is what they look like when they are fighting a virus — they have plenty of cytoplasm and they all look different from each other. Cancer would make an army of identical cells instead.",
  exim="fig_slide_reactive_malignant",
  excap="Reactive versus malignant: the skirt of cytoplasm and the variety of appearances are the reactive signature.")

# ── 10. The leukoerythroblastic picture (§27) ────────────────────────────────
q("A 66-year-old man is evaluated for 4 months of fatigue, early satiety, and a 7-kg weight loss. He has no fever and no recent infection. His temperature is 36.9°C (98.4°F), pulse is 88/min, and blood pressure is 128/74 mm Hg. Physical examination shows a spleen palpable 10 cm below the left costal margin.\n\nLaboratory studies show:\nHemoglobin 8.8 g/dL (N=13.0–16.0 g/dL)\nHematocrit 27% (N=37%–49%)\nLeukocyte count 14,200/mm3 (N=4,500–11,000/mm3)\nPlatelet count 96,000/mm3 (N=150,000–400,000/mm3)\n\nThe smear shows myelocytes and metamyelocytes, 22 nucleated erythrocytes per 100 leukocytes, and numerous tear-drop erythrocytes. Blasts constitute 2% of leukocytes. Which of the following does this combination of findings indicate?",
  ["A. An acute leukemia arising in the peripheral blood",
   "B. Disturbance of the marrow architecture itself",
   "C. Hemolysis with a vigorous reticulocyte response",
   "D. Recovery of the marrow after a viral suppression",
   "E. Splenic sequestration of mature circulating cells"],
  1,
  "IMMATURE WHITE CELLS plus NUCLEATED RED CELLS plus TEAR-DROP CELLS in the same smear is a LEUKOERYTHROBLASTIC PICTURE, and it means the MARROW ARCHITECTURE IS DISTURBED — either SCARRED (myelofibrosis) or DISPLACED BY SOMETHING GROWING IN IT (a space-occupying lesion such as metastatic tumour).\n\nEach component tells the same story from a different angle. A NUCLEATED RED CELL IN THE BLOOD IS A CELL RELEASED BEFORE IT WAS FINISHED — either the marrow is under stress and rushing output, or something is forcing cells out. TEAR-DROP CELLS are red cells SQUEEZED AS THEY EXIT A SCARRED MARROW. And the immature granulocytes are the same marrow releasing what it has, in whatever state it is in.\n\nHis clinical picture fits primary myelofibrosis: months of constitutional symptoms, massive splenomegaly from extramedullary hematopoiesis, anemia and thrombocytopenia. The next steps are a marrow examination showing reticulin and collagen fibrosis — and often a DRY TAP — plus JAK2, CALR and MPL mutation testing.\n\nNotice how one finding recurs across three sections. The tear-drop cell appears in the morphology atlas pointing at myelofibrosis; the nucleated red cell falsely raises the automated white count, because the analyzer identifies leukocytes by looking for nuclei; and both appear here defining the leukoerythroblastic picture. ONE FINDING, THREE PLACES IT MATTERS.\n\nAlso worth noting: his reported white count of 14,200/mm3 is itself inflated by those 22 nucleated red cells per 100 leukocytes unless the analyzer corrected for them.",
  {"0": "Acute leukemia produces an EXCESS OF BLASTS out of proportion to the left shift, and his blasts are 2%. Leukemias also arise in the marrow rather than in the blood, and the tear-drop cells point specifically at a mechanical problem with the marrow space.",
   "2": "Brisk hemolysis does raise the reticulocyte count and can push out an occasional nucleated red cell, so the direction is right. It does not produce myelocytes, metamyelocytes and tear-drop cells together, and there is no hemolysis marker here.",
   "3": "A recovering marrow does release immature forms of several lineages, which makes this a reasonable thought after chemotherapy or a viral suppression. His story is 4 months of progressive constitutional symptoms with massive splenomegaly, which is not a recovery pattern.",
   "4": "Hypersplenism sequesters MATURE cells and lowers the counts without pushing immature forms into the blood. His spleen is enlarged, but as a consequence of extramedullary hematopoiesis rather than as the cause of the smear findings."},
  "Three findings appear together: baby white cells, red cells that still have their nucleus, and red cells shaped like teardrops. Together they mean the marrow itself is being squeezed — scarred or crowded out — and cells are being forced through.",
  exim="fig_teardrop",
  excap="Tear-drop erythrocytes — red cells squeezed as they exit a scarred or infiltrated marrow.")

# ── 11. Basophilia (§27) ────────────────────────────────────────────────────
q("A 47-year-old man is evaluated after a routine blood count showed a persistently high leukocyte count over 5 months. He reports mild fatigue and early satiety but no fever, no night sweats, and no recent infection. His temperature is 36.8°C (98.2°F), pulse is 76/min, and blood pressure is 124/78 mm Hg. Physical examination shows a spleen palpable 6 cm below the left costal margin.\n\nLaboratory studies show:\nHemoglobin 12.4 g/dL (N=13.0–16.0 g/dL)\nHematocrit 37% (N=37%–49%)\nLeukocyte count 84,000/mm3 (N=4,500–11,000/mm3)\nBasophils 9% (N=0%–2%)\nEosinophils 6% (N=0%–7%)\nPlatelet count 620,000/mm3 (N=150,000–400,000/mm3)\n\nThe smear shows granulocytes at all stages of maturation with 2% blasts, and no Döhle bodies, toxic granulation, or vacuolization. Which of the following is the most appropriate next test?",
  ["A. Blood cultures and inflammatory markers",
   "B. Flow cytometry for lymphoid clonality markers",
   "C. Nitroblue tetrazolium testing of neutrophils",
   "D. Serum immunoglobulin E and a parasite screen",
   "E. Testing for the BCR-ABL fusion gene"],
  4,
  "BASOPHILIA IS OTHERWISE UNCOMMON, so persistent unexplained basophilia is ONE OF THE FEW COMPLETE BLOOD COUNT FINDINGS THAT SHOULD MAKE YOU THINK OF A MYELOPROLIFERATIVE NEOPLASM DIRECTLY.\n\nChronic myelogenous leukemia LOOKS VERY REACTIVE — a huge white count with granulocytes at every stage of maturation, which is exactly what a leukemoid reaction looks like. But it is driven by the BCR-ABL FUSION ONCOGENE, and for reasons that are not obvious IT PRODUCES A LOT OF BASOPHILS. That is the feature that separates it from a reaction, and BCR-ABL testing confirms it rather than morphology.\n\nEverything else in this vignette pushes the same way. The reactive changes are explicitly ABSENT — no Döhle bodies, no toxic granulation, no vacuolization — so this is not a neutrophil working hard. The DURATION is 5 months, and duration settles most cases: reactive morphology resolves as the illness clears, whereas a clonal process persists. There is no infection or inflammatory source. And there is splenomegaly with thrombocytosis.\n\nThe lines-up-and-what-that-suggests table is worth having whole: NEUTROPHILIA with pyogenic infection, acute inflammation and stress including tissue necrosis; LYMPHOCYTOSIS with viral infection, PERTUSSIS and chronic inflammation; MONOCYTOSIS with chronic infection and RECOVERY FROM NEUTROPENIA; EOSINOPHILIA with hypersensitivity, parasites, fungus, malignancy and DRUG REACTIONS; and BASOPHILIA with viral infection, drugs, hypersensitivity, chronic inflammation, and CML.",
  {"1": "Lymphoid flow cytometry is the right test when the expanded population is lymphoid — a lymphocytosis of uncertain clonality. His expansion is granulocytic with basophilia, which points at a myeloid process.",
   "2": "The nitroblue tetrazolium test screens for chronic granulomatous disease, a QUALITATIVE phagocyte defect in which the count is normal and the cells cannot make reactive oxygen species. Nothing here suggests recurrent catalase-positive infections.",
   "3": "An allergy and parasite workup follows EOSINOPHILIA, which has its own differential — hypersensitivity, parasites, fungus, malignancy, drug reactions. His eosinophil percentage is within the normal range; it is the basophils that are abnormal.",
   "0": "Cultures and inflammatory markers are the right move for a suspected leukemoid reaction, and a huge white count does deserve that thought. He has no fever, no source, no reactive morphology, and a 5-month course."},
  "A very high white count can just be a hard-fighting response to infection. What does not fit that pattern is a high basophil count — basophils almost never rise, and when they do persistently, one particular blood cancer is the reason.",
  exim="fig_slide_granulocyte_series",
  excap="The granulocyte maturation series. Chronic myelogenous leukemia shows every stage present, which is why it mimics a reaction.")

# ── 12. Pertussis and the lymphocytosis (§27) ───────────────────────────────
q("A 4-month-old girl is brought to the office because of 3 weeks of cough that has become paroxysmal, with episodes of repeated coughing followed by a gasping inspiration and post-tussive vomiting. She is afebrile between episodes and is feeding poorly. Her immunizations are incomplete. Her temperature is 37.0°C (98.6°F), pulse is 148/min, and respirations are 44/min. Between paroxysms her chest is clear and she appears well.\n\nLaboratory studies show:\nHemoglobin 11.2 g/dL (N=10.5–13.5 g/dL)\nHematocrit 33% (N=33%–39%)\nLeukocyte count 32,000/mm3 (N=6,000–17,500/mm3)\nLymphocytes 78% (N=45%–75%)\nPlatelet count 398,000/mm3 (N=150,000–400,000/mm3)\n\nThe smear shows small mature lymphocytes without atypia and no blasts. Which of the following is the most likely causal organism?",
  ["A. Bordetella pertussis",
   "B. Epstein-Barr virus",
   "C. Mycoplasma pneumoniae",
   "D. Respiratory syncytial virus",
   "E. Streptococcus pneumoniae"],
  0,
  "PERTUSSIS IS LISTED UNDER LYMPHOCYTOSIS — a BACTERIAL infection producing a LYMPHOCYTIC response, the OPPOSITE of the usual pattern, and often a striking one. That inversion is exactly why it is worth flagging: the reflex that bacteria cause neutrophilia and viruses cause lymphocytosis is a good rule with a famous exception, and this is the exception.\n\nHer clinical picture is classic: an infant with incomplete immunization, three weeks of cough now in the paroxysmal stage with the inspiratory whoop and post-tussive vomiting, afebrile, and well-appearing between episodes with a clear chest. The magnitude of the lymphocytosis in pertussis can be extreme and correlates with severity in young infants.\n\nThe smear detail matters too: SMALL MATURE LYMPHOCYTES WITHOUT ATYPIA. Contrast a viral lymphocytosis such as Epstein-Barr virus, where the cells are large and reactive with abundant cytoplasm moulding around red cells — the 'skirt' — and coarse chromatin.\n\nThe rest of the which-line-is-up table, for completeness: neutrophilia with pyogenic infection and acute inflammation, including stress responses such as tissue necrosis — NEUTROPHILIA DOES NOT REQUIRE AN ORGANISM, and new-onset diabetes presenting in ketoacidosis produces one purely as a stress response. Monocytosis with chronic infection and recovery from neutropenia, because MONOCYTES ARRIVE LATE and often peak after an infection has cleared. And eosinophilia with hypersensitivity, parasites, fungus, malignancy and drug reactions.",
  {"1": "Epstein-Barr virus is the classic cause of a striking lymphocytosis, and it fits the count well. It causes pharyngitis, lymphadenopathy and splenomegaly rather than a three-week paroxysmal cough, and its lymphocytes are LARGE AND REACTIVE rather than small and mature.",
   "2": "Mycoplasma causes a subacute cough and can affect this age group, so it belongs on the differential. It does not produce a paroxysmal whooping cough with post-tussive vomiting, and it is not associated with a marked lymphocytosis.",
   "3": "Respiratory syncytial virus is the commonest cause of serious respiratory illness at 4 months and causes bronchiolitis with wheeze, tachypnea and crackles. Her chest is clear between paroxysms, and the count is higher than bronchiolitis usually produces.",
   "4": "Pneumococcal pneumonia produces fever, focal chest findings and a NEUTROPHILIC leukocytosis. She is afebrile with a clear chest and a 78% lymphocyte count."},
  "The usual rule is that bacteria raise the neutrophil count and viruses raise the lymphocyte count. Whooping cough breaks that rule — it is a bacterium that drives the lymphocytes up, sometimes dramatically.")

# ══════════════════ §28 · PRIMARY IMMUNODEFICIENCIES ══════════════════

# ── 13. Chronic granulomatous disease (§28) ─────────────────────────────────
q("A 3-year-old boy is brought to the office because of a fourth deep abscess in 2 years, this time in the left axilla. Cultures from previous abscesses grew Staphylococcus aureus and Serratia marcescens, and he was treated last year for Aspergillus pneumonia. He has two maternal uncles with similar histories. His temperature is 38.1°C (100.6°F), pulse is 118/min, and blood pressure is 96/60 mm Hg. Physical examination shows hepatosplenomegaly and cervical lymphadenopathy.\n\nLaboratory studies show:\nHemoglobin 10.2 g/dL (N=11.5–13.5 g/dL)\nHematocrit 31% (N=34%–40%)\nLeukocyte count 14,800/mm3 (N=6,000–17,500/mm3)\nAbsolute neutrophil count 8,200/µL (N=1,500–8,500/µL)\n\nSerum IgG, IgA, and IgM concentrations are normal. Which of the following is the most appropriate diagnostic test?",
  ["A. Flow cytometry for CD19 and CD20 B lymphocytes",
   "B. Fluorescence in situ hybridization for a 22q11 deletion",
   "C. Neutrophil oxidative index testing",
   "D. T-cell receptor excision circle quantitation",
   "E. Total hemolytic complement, CH50 and AH50"],
  2,
  "This is CHRONIC GRANULOMATOUS DISEASE, and the critical observation is that his NEUTROPHIL COUNT IS NORMAL. This is a QUALITATIVE defect, not a quantitative one — the cells are there and they do not work. That split organizes the whole topic: sections on neutropenia and leukocytosis are the quantitative half; the immunodeficiencies are the qualitative half.\n\nThe defect is in NADPH OXIDASE (cytochrome b558), so phagocytes cannot generate REACTIVE OXYGEN SPECIES. The respiratory burst runs O₂ → superoxide (NADPH oxidase — THE STEP THAT FAILS) → hydrogen peroxide (superoxide dismutase) → hypochlorous acid (myeloperoxidase), and hypochlorous acid is the active ingredient in BLEACH. The neutrophil is manufacturing bleach inside a vacuole. Because the block is at the FIRST step, nothing downstream can be made — which is why MYELOPEROXIDASE DEFICIENCY, blocking only the last step, is a far milder disease.\n\nGenetics fit the vignette: 70% X-LINKED RECESSIVE, 30% autosomal recessive, and 86% OF PATIENTS ARE MALE — hence the maternal uncles. Incidence is 1 in 200,000.\n\nDiagnosis is the NITROBLUE TETRAZOLIUM TEST — normal neutrophils reduce a yellow dye to a blue-black precipitate, and CGD neutrophils cannot, staying yellow — or the NEUTROPHIL OXIDATIVE INDEX, the modern quantitative flow cytometry version.\n\nManagement: prophylactic antibiotics and exposure prevention, RECOMBINANT INTERFERON GAMMA, which reduces the infection rate BY UP TO 70%, and steroids when granulomas cause obstruction.",
  {"0": "CD19 and CD20 flow cytometry is the test for Bruton agammaglobulinemia, where B cells are absent and all immunoglobulin classes are low. His immunoglobulins are explicitly normal, and his organisms are the phagocyte pattern rather than the pyogenic-encapsulated pattern.",
   "1": "22q11 testing diagnoses DiGeorge syndrome, which presents at birth with a conotruncal cardiac defect and hypocalcemic seizures, and gives a T-cell pattern of viral and fungal infection. He has neither the cardiac disease nor the facies.",
   "3": "T-cell receptor excision circles are what the NEWBORN SCREEN measures to detect severe combined immunodeficiency, which presents in the first months of life with Pneumocystis, candida and chronic diarrhea. He has survived 3 years with an intact antibody arm.",
   "4": "CH50 and AH50 screen the classical and alternative complement pathways. Complement deficiencies are the SMALLEST group at about 5%, and they classically present with recurrent NEISSERIAL infection rather than staphylococcal and fungal abscesses."},
  "He has plenty of infection-fighting cells, but they cannot make the chemical bleach they normally use to kill what they swallow. The test checks whether his cells can produce that chemical at all.",
  exim="fig_slide_nadph",
  excap="The NADPH oxidase complex and the mutations that disable it — the first step of the respiratory burst.")

# ── 14. The catalase logic (§28) ────────────────────────────────────────────
q("A 5-year-old boy with chronic granulomatous disease has had infections with Staphylococcus aureus, Serratia marcescens, Nocardia, and Aspergillus. His parents ask why he has never had a serious infection with streptococci or with other common childhood bacteria, given that his phagocytes cannot produce reactive oxygen species. Laboratory study of his neutrophils confirms that ingestion of bacteria is normal.\n\nWhich of the following best explains this pattern of infection?",
  ["A. Catalase-negative organisms supply peroxide the phagocyte can use",
   "B. Catalase-positive organisms are not ingested by his phagocytes",
   "C. His antibody responses neutralize streptococci before ingestion",
   "D. Streptococci are killed by complement without any phagocytosis",
   "E. Streptococci do not survive the acidic environment of a vacuole"],
  0,
  "The central sentence: CELLS CAN INGEST ORGANISMS, BUT CATALASE-PRODUCING ORGANISMS ARE NOT KILLED, because reactive oxygen species cannot be generated. Note that PHAGOCYTOSIS IS INTACT — the failure is entirely downstream of ingestion, which is what the laboratory study in the stem confirms.\n\nThe reason only SOME organisms cause trouble is elegant. A phagocyte with no NADPH oxidase makes NO HYDROGEN PEROXIDE OF ITS OWN — but many bacteria make hydrogen peroxide as a metabolic by-product, and the phagocyte can simply BORROW THEIRS. CATALASE-POSITIVE ORGANISMS DESTROY THEIR OWN HYDROGEN PEROXIDE, leaving the defective phagocyte nothing to work with, so they survive inside it.\n\nWorked through with E. coli: the neutrophil ingests it perfectly well, can make little or no hydrogen peroxide itself, and the organism's catalase converts what trace exists back to water and oxygen. The bacterium sits there alive inside the phagocyte.\n\nThe corollary makes the rule predictive: CATALASE-NEGATIVE ORGANISMS ARE STILL KILLED, because they supply the peroxide themselves and cannot quench it. Streptococci are catalase-negative, which is exactly why his son has not had trouble with them.\n\nThe offenders to name: S. AUREUS, ASPERGILLUS, SERRATIA, NOCARDIA, BURKHOLDERIA.\n\nAnd the standoff that follows — organism alive inside a cell that cannot kill it — is what produces a GRANULOMA: a necrotic centre with still-living pathogen, a barrier of monocytes and macrophages including multinucleated giant cells, and T and B cells outside that holding the line.",
  {"1": "Ingestion is intact in chronic granulomatous disease, and the stem states it directly. Mistaking this for a phagocytosis defect is the commonest error about the disease — the cells swallow organisms perfectly well and then cannot finish them.",
   "2": "His antibody arm is normal and does help opsonize organisms, so this is not wrong about his immune system. It does not explain the specific catalase-based pattern, since antibody works against catalase-positive organisms too.",
   "3": "Complement contributes to killing encapsulated organisms and is genuinely important against some pathogens. Streptococci are cleared principally by phagocytosis after opsonization, and complement alone does not account for the sharp catalase divide.",
   "4": "Vacuolar acidification does occur and contributes to microbial killing, but it is not what separates the organisms that cause disease here from the ones that do not. The peroxide supply is the variable."},
  "His cells can swallow bacteria but cannot make the poison that kills them. Some bacteria helpfully produce that poison themselves, so his cells borrow it. The dangerous ones destroy their own supply, so nothing is left to kill them with.",
  exim="fig_slide_granuloma",
  excap="The granuloma — a necrotic centre with living organisms, walled off by macrophages and lymphocytes. A siege, not a cure.")

# ── 15. Bruton agammaglobulinemia (§28) ─────────────────────────────────────
q("A 9-month-old boy is brought to the office because of a fourth episode of otitis media, following two episodes of pneumonia since the age of 7 months. He was entirely well for his first 6 months. Cultures have grown Streptococcus pneumoniae and Haemophilus influenzae. A maternal uncle died of infection in infancy. His temperature is 38.4°C (101.1°F), pulse is 132/min, and respirations are 34/min. Physical examination shows a bulging right tympanic membrane, and the tonsils are notably small and the cervical lymph nodes are not palpable.\n\nLaboratory studies show:\nLeukocyte count 11,400/mm3 (N=6,000–17,500/mm3)\nAbsolute lymphocyte count 3,600/µL (N=3,000–9,500/µL)\nSerum IgG 96 mg/dL (N=400–1,200 mg/dL)\nSerum IgA <7 mg/dL (N=20–100 mg/dL)\nSerum IgM <5 mg/dL (N=40–180 mg/dL)\n\nWhich of the following findings is most likely on further testing?",
  ["A. A deletion at chromosome 22q11 on hybridization testing",
   "B. Absence of CD19 and CD20 positive lymphocytes",
   "C. Absence of T-cell receptor excision circles at birth",
   "D. Failure of neutrophils to reduce nitroblue tetrazolium",
   "E. Low CH50 with a normal alternative pathway screen"],
  1,
  "Bruton (X-linked) agammaglobulinemia: a BTK GENE mutation blocking maturation at the PRE-B CELL stage. Flow cytometry shows NO CD19/CD20 B CELLS AND NO PLASMA CELLS, the marrow shows ABSENT PRECURSOR B CELLS, all immunoglobulins are low, and BTK sequencing confirms.\n\nTHE TIMING IS THE SIGNATURE. Patients are generally ASYMPTOMATIC FOR THE FIRST FEW MONTHS because MATERNAL IgG CROSSES THE PLACENTA and protects them until it wanes around 6 MONTHS. An infant who was well until 6 months and then began having pyogenic infections has an ANTIBODY defect — maternal IgG protects the antibody arm and nothing else. Compare an infant with problems from the first months of life, which points at the cellular arm and severe combined immunodeficiency.\n\nTHE ORGANISMS FIT: pyogenic bacteria — HAEMOPHILUS, STREPTOCOCCUS, STAPHYLOCOCCUS — plus gastroenteritis and chronic intestinal inflammation.\n\nAND THE BEDSIDE SIGN IS IN THE STEM: ABSENT TONSILS and atrophic lymph nodes, because lymphoid tissue is mostly B cells. A boy with recurrent infection and no visible tonsils is the classic examination finding.\n\nAntibody deficiencies are the largest category of primary immunodeficiency at 65% OF THE TOTAL, which is why immunoglobulin replacement is such a common therapy. Treatment here is MONTHLY IgG INFUSIONS; marrow transplant is currently the only cure, with gene therapy plausible since the mutation's location is known.",
  {"2": "Absent excision circles identify severe combined immunodeficiency on the newborn screen. That disease presents in the FIRST MONTHS with Pneumocystis, candida and chronic diarrhea — his 6 well months and his pyogenic organisms point elsewhere, and his lymphocyte count is normal.",
   "0": "A 22q11 deletion is DiGeorge syndrome, which declares itself at birth with a conotruncal cardiac defect and hypocalcemia, and gives viral and fungal infections. He has neither, and his problem is clearly antibody.",
   "3": "Failure to reduce nitroblue tetrazolium is chronic granulomatous disease, a phagocyte defect causing abscesses with catalase-positive organisms and granulomas. His immunoglobulins would be normal in that disease; here they are almost absent.",
   "4": "Complement screening is appropriate for recurrent NEISSERIAL infection or for a suspected classical-pathway defect. Complement deficiencies are the smallest group at about 5%, and his immunoglobulin panel already localizes the lesion."},
  "He was protected for his first six months by antibodies that crossed from his mother. When those ran out he had none of his own, because his body cannot make the cells that produce them — which is also why he has no tonsils to speak of.",
  exim="fig_slide_bruton",
  excap="Bruton agammaglobulinemia: low IgG with undetectable IgM and IgA, from a BTK mutation blocking the pre-B cell.")

# ── 16. Severe combined immunodeficiency (§28) ──────────────────────────────
q("A 4-month-old boy is admitted with 6 weeks of watery diarrhea, failure to thrive, and oral thrush that has not responded to topical therapy. He now has a dry cough with hypoxemia, and bronchoalveolar lavage identifies Pneumocystis jirovecii. He was born at home and had no newborn screening. His weight has fallen from the 50th to below the 3rd percentile. His temperature is 38.0°C (100.4°F), pulse is 158/min, and respirations are 62/min. Physical examination shows oral thrush and no palpable lymph nodes; the chest radiograph shows an absent thymic shadow.\n\nLaboratory studies show:\nHemoglobin 9.8 g/dL (N=10.5–13.5 g/dL)\nLeukocyte count 4,200/mm3 (N=6,000–17,500/mm3)\nAbsolute lymphocyte count 900/µL (N=3,000–9,500/µL)\nSerum IgG 180 mg/dL (N=300–1,000 mg/dL)\n\nWhich of the following determines this patient's outcome?",
  ["A. Early allogeneic stem cell transplantation",
   "B. Lifelong monthly immunoglobulin infusions",
   "C. Prophylactic antibiotics and antifungal agents",
   "D. Recombinant interferon gamma given three times weekly",
   "E. Thymic tissue transplantation in the first year"],
  0,
  "Severe combined immunodeficiency. OUTCOME IS DETERMINED BY IMMUNE RECONSTITUTION WITH ALLOGENEIC STEM CELL TRANSPLANTATION, AND SURVIVAL IS BETTER THE EARLIER IT IS PERFORMED. Untreated, PATIENTS USUALLY DIE WITHIN 1 YEAR. Everything else on this list is supportive and buys time.\n\nHis absolute lymphocyte count of 900/µL is the number that should trigger evaluation — BELOW 2,000/µL WARRANTS IT. The presentation is the T-cell pattern in full: failure to thrive, chronic diarrhea, persistent thrush, and PNEUMOCYSTIS JIROVECII, an organism that otherwise appears only when CD4 is undetectable in advanced HIV. The absent thymic shadow and absent lymphoid tissue complete it.\n\nTHE NEWBORN SCREEN SHOULD HAVE CAUGHT THIS, and he missed it by being born at home. The screen measures T-CELL RECEPTOR EXCISION CIRCLES — small circular DNA by-products created when a maturing T cell rearranges its VDJ segments. Their presence is DIRECT EVIDENCE THAT NEW T CELLS ARE BEING MADE; a very low level means they are not. THE SCREEN EXISTS TO GET THE TRANSPLANT DONE BEFORE THE FIRST SERIOUS INFECTION — which, in his case, has already happened.\n\nTwo mechanisms produce it. The X-LINKED form, the most common, mutates the COMMON GAMMA CHAIN shared by many interleukin receptors. The autosomal recessive form is ADENOSINE DEAMINASE DEFICIENCY, where accumulated purines inhibit ribonucleotide reductase and toxic products drive precursor apoptosis — lymphocytes are hit first because they are among the most rapidly dividing cells in the body.\n\nMeanwhile: a near-sterile environment, NO LIVE VACCINES, and IRRADIATED BLOOD PRODUCTS if transfused.",
  {"1": "Monthly immunoglobulin is the definitive maintenance therapy for an ANTIBODY deficiency such as Bruton agammaglobulinemia, and it is given here as supportive care. It replaces one arm only, and does nothing for the absent T cells that are letting Pneumocystis grow.",
   "2": "Antimicrobial prophylaxis is essential and will be started, including treatment of the Pneumocystis he already has. It postpones the problem rather than solving it; without reconstitution the next organism follows.",
   "3": "Interferon gamma reduces the infection rate by up to 70% in CHRONIC GRANULOMATOUS DISEASE, where it improves phagocyte killing. There is no phagocyte defect here, and his neutrophils work.",
   "4": "Thymic transplantation is the reconstitution strategy for complete DiGeorge syndrome, where the marrow makes T-cell precursors but there is no thymus to mature them. In severe combined immunodeficiency the defect is in the stem cell compartment itself, so a thymus has nothing to work with."},
  "His immune system never developed at all, which is why an infection normally seen only in advanced AIDS has appeared in a four-month-old. Nothing short of replacing his blood-forming cells will fix it, and the sooner it is done the better he does.",
  exim="fig_slide_scid",
  excap="Severe combined immunodeficiency: infections from the first months of life, and newborn screening by T-cell receptor excision circles.")

# ── 17. DiGeorge syndrome (§28) ─────────────────────────────────────────────
q("A 3-day-old newborn is evaluated for jitteriness and a seizure. He was born at term after an uncomplicated pregnancy. Echocardiography performed for a murmur shows truncus arteriosus. His temperature is 36.8°C (98.2°F), pulse is 156/min, and respirations are 52/min. Physical examination shows a long narrow face, a prominent nasal bridge with a bulbous tip, low-set ears, micrognathia, and a cleft palate.\n\nLaboratory studies show:\nSerum calcium 6.2 mg/dL (N=8.5–10.5 mg/dL)\nSerum phosphorus 8.4 mg/dL (N=4.5–7.0 mg/dL)\nIntact parathyroid hormone 6 pg/mL (N=15–65 pg/mL)\nAbsolute lymphocyte count 1,100/µL (N=3,000–9,500/µL)\n\nWhich of the following best explains the combination of findings in this infant?",
  ["A. A defect of neural crest migration to the branchial pouches",
   "B. A maternal autoantibody crossing the placenta in utero",
   "C. An inherited defect of the calcium-sensing receptor gene",
   "D. Failure of the fetal thyroid to develop in the first trimester",
   "E. Intrauterine infection acquired during the first trimester"],
  0,
  "ONE EMBRYOLOGICAL EVENT EXPLAINS ALL FIVE FEATURES: a MIGRATION DEFECT OF NEURAL CREST-DERIVED TISSUES affecting the THIRD AND FOURTH BRANCHIAL POUCHES. Those pouches form the THYMUS (hence the T-cell deficiency) and the PARATHYROIDS (hence the hypocalcemia), and neural crest cells also populate the CONOTRUNCAL HEART and the FACIAL STRUCTURES. NOT FIVE UNRELATED PROBLEMS — ONE DEVELOPMENTAL FAILURE WITH FIVE CONSEQUENCES.\n\nCATCH-22 is both the mnemonic and the chromosome:\n• C — Cardiac abnormality (conotruncal defects, as here)\n• A — Abnormal facies (long narrow face, prominent nasal bridge with a bulbous tip, small mouth, thin eye openings, low-set or malformed ears, micrognathia)\n• T — Thymic aplasia, the immunodeficiency — no thymus, so T cells cannot mature\n• C — Cleft palate, with velopharyngeal incompetence\n• H — Hypocalcemia, from ABSENT PARATHYROID GLANDS\n• 22 — the 22q11 deletion; 90% DE NOVO, 10% autosomal dominant\n\nHis laboratory values confirm the parathyroid mechanism specifically: a calcium of 6.2 mg/dL with a HIGH phosphorus and an INAPPROPRIATELY LOW parathyroid hormone. That is absent glands, not resistance to the hormone.\n\nManagement: thymus or stem cell transplant, CALCIUM AND VITAMIN D, and IRRADIATED BLOOD PRODUCTS. Cellular deficiencies are only about 5% of primary immunodeficiencies.\n\nWatch for the later complications too — rheumatoid arthritis, thyroiditis and B-CELL NEOPLASMS — which look unrelated until you hear the mechanism: T cells also RESTRAIN exuberant B-cell proliferation, so losing them removes the brake at the same moment the body presses the accelerator.",
  {"1": "Maternal antibodies do cross the placenta and cause neonatal disease — neonatal lupus with congenital heart block is the classic example. They do not produce thymic aplasia, absent parathyroids and a cleft palate together.",
   "2": "An activating mutation of the calcium-sensing receptor causes autosomal dominant hypocalcemia with a low parathyroid hormone, so it explains one row of his panel well. It does not explain the cardiac defect, the facies, the cleft palate or the lymphopenia.",
   "3": "Thyroid agenesis causes congenital hypothyroidism, detected on newborn screening, and does not cause hypocalcemia — the PARATHYROID glands are the ones derived from the third and fourth pouches.",
   "4": "Congenital infection — toxoplasmosis, rubella, cytomegalovirus — can cause cardiac lesions and other anomalies, so it is a reasonable thought in a dysmorphic newborn. It does not produce this specific constellation, and 90% of these cases are de novo deletions rather than acquired."},
  "One group of cells that migrate during early development failed to arrive where they were needed. Those cells were supposed to build the thymus, the parathyroid glands, part of the heart and part of the face — which is why all four are abnormal in the same baby.",
  exim="fig_slide_branchial",
  excap="The third and fourth branchial pouch derivatives — thymus and parathyroids — and the role of Tbx1.")

# ── 18. Irradiated blood products (§28) ─────────────────────────────────────
q("A 6-day-old infant with DiGeorge syndrome and truncus arteriosus is scheduled for cardiac surgery and will require transfusion of packed red blood cells and platelets. His absolute lymphocyte count is 900/µL (N=3,000–9,500/µL), flow cytometry shows markedly reduced CD3 positive T cells, and the chest radiograph shows no thymic shadow. The blood bank telephones to confirm the component requirements before issue.\n\nWhich of the following modifications is most important for this patient?",
  ["A. ABO-identical rather than ABO-compatible components",
   "B. Irradiation of the cellular blood components",
   "C. Leukoreduction of the components before issue",
   "D. Volume reduction of each component before issue",
   "E. Washing the components to remove residual plasma"],
  1,
  "Donor blood contains VIABLE DONOR T LYMPHOCYTES. In a normal recipient these are recognized and destroyed. A patient with THYMIC APLASIA CANNOT DO THAT, so the donor T cells ENGRAFT AND ATTACK THE RECIPIENT — TRANSFUSION-ASSOCIATED GRAFT-VERSUS-HOST DISEASE, WHICH IS ALMOST UNIFORMLY FATAL.\n\nIRRADIATION INACTIVATES THE DONOR LYMPHOCYTES so they cannot proliferate. It does not remove them; it stops them dividing, which is all that is required.\n\nThe same rule applies to SEVERE COMBINED IMMUNODEFICIENCY AND OTHER SEVERE T-CELL DEFICIENCIES, and congenital T-cell immunodeficiency is an ABSOLUTE INDICATION for irradiated components. Other absolute indications include intrauterine and neonatal exchange transfusion, hematopoietic stem cell transplant recipients, Hodgkin lymphoma, purine analogue therapy, and directed donations from blood relatives — where partial HLA sharing makes engraftment MORE likely rather than less.\n\nThe companion rule that travels with it: LIVE VACCINES ARE CONTRAINDICATED in severe T-cell deficiency. Vaccination in these patients means INACTIVATED vaccines — plus vaccinating household contacts so they do not bring the infection home.\n\nNote the trap in leukoreduction. It removes most leukocytes and prevents febrile nonhemolytic reactions, cytomegalovirus transmission and HLA alloimmunization — all useful, and it will probably be done anyway. It DOES NOT PREVENT TRANSFUSION-ASSOCIATED GRAFT-VERSUS-HOST DISEASE, because the residual lymphocytes are still viable and still able to divide. Only irradiation addresses that.",
  {"0": "ABO-identical transfusion is good practice where supply allows and reduces the chance of clerical error, but compatible components are safe. This addresses hemolytic reactions rather than the risk that is unique to him.",
   "2": "Leukoreduction is the classic wrong answer here, and it is wrong for a specific reason: removing MOST leukocytes still leaves viable, dividing lymphocytes behind. It prevents febrile reactions, cytomegalovirus transmission and alloimmunization — not graft-versus-host disease.",
   "3": "Volume reduction limits the transfused volume and is genuinely useful in a small infant with cardiac disease at risk of circulatory overload. It reduces the plasma, not the hazard posed by donor T cells.",
   "4": "Washing removes plasma proteins and is indicated for recurrent severe allergic reactions and for IgA-deficient patients with anti-IgA antibodies. It leaves the cellular fraction — including the lymphocytes — behind."},
  "Donated blood contains some of the donor's own immune cells. Normally the recipient destroys them. This baby cannot, so those cells would take up residence and attack him — and that is almost always fatal. Irradiating the blood stops them multiplying.")

# ── 19. Live vaccines in T-cell deficiency (§28) ────────────────────────────
q("A 7-month-old girl with severe combined immunodeficiency is awaiting allogeneic stem cell transplantation. She is receiving immunoglobulin replacement and antimicrobial prophylaxis and is being cared for in a protective environment at home. Her 3-year-old brother attends daycare and is due for his routine immunizations, and the family asks about vaccination for both children. Her absolute lymphocyte count is 700/µL (N=3,000–9,500/µL).\n\nWhich of the following is the most appropriate advice?",
  ["A. Give her all routine vaccines, since immunoglobulin protects her",
   "B. Give her inactivated vaccines and immunize her household contacts",
   "C. Give her live vaccines now, before transplant conditioning begins",
   "D. Withhold all vaccines from her and from her household contacts",
   "E. Withhold her vaccines and give her brother only inactivated ones"],
  1,
  "LIVE VACCINES ARE CONTRAINDICATED IN SEVERE T-CELL DEFICIENCY. A patient who cannot contain an attenuated organism can develop VACCINE-STRAIN DISEASE from it — and below the threshold of a functioning cellular arm she also cannot mount a useful response, so the dose achieves nothing even when it does no harm. 'VACCINATION' IN THESE PATIENTS MEANS INACTIVATED VACCINES.\n\nThe second half is the part that gets forgotten: PLUS VACCINATING HOUSEHOLD CONTACTS. Her brother should receive his routine immunizations, because an unvaccinated sibling in daycare is one of the likeliest routes for a serious infection to reach her. This is cocooning — protecting the patient by immunizing everyone around her.\n\nThe nuance on which vaccines the sibling may have: most routine childhood vaccines are inactivated and are unambiguously indicated. Live vaccines in a household contact are generally acceptable because vaccine strains of measles, mumps, rubella and varicella are not meaningfully transmitted from a healthy vaccinee — the exception being the oral poliovirus vaccine, which is not used in the United States. Rotavirus vaccine is shed in stool, so careful hand hygiene is advised.\n\nThe parallel rule for this patient is the transfusion one: IRRADIATED BLOOD PRODUCTS, because she cannot reject viable donor T lymphocytes, which would otherwise engraft and cause transfusion-associated graft-versus-host disease.\n\nAnd the same live-vaccine logic appears in HIV: varicella, yellow fever and MMR require a CD4 count of 200 cells/µL or more, for both of these reasons.",
  {"0": "Immunoglobulin replaces antibody that she cannot make, and it does provide meaningful protection against many pathogens. It does not protect against a LIVE ORGANISM replicating in a host with no T cells, which is the specific hazard of a live vaccine.",
   "2": "Vaccinating before conditioning would be reasonable thinking for a patient with an intact immune system facing future immunosuppression. Hers is already absent, so a live vaccine now is at its most dangerous and least effective.",
   "3": "Withholding from the household is the opposite of what is needed and is the most harmful option here. Unvaccinated contacts are a direct threat to her, particularly a sibling in daycare.",
   "4": "Restricting the sibling to inactivated vaccines only is over-cautious and leaves him — and therefore her — unprotected against measles and varicella. Vaccine strains from a healthy vaccinee are not meaningfully transmitted, with the oral polio exception that does not apply in the United States."},
  "A live vaccine contains a weakened but living germ, and she has no immune system to keep even a weakened germ in check. She gets the killed versions — and everyone living with her should be fully vaccinated, so nothing is brought home to her.",
  exim="fig_slide_maturation_tree",
  excap="The lymphocyte maturation tree with the blocks marked. The higher the block, the more of the immune system is lost.")

# ── 20. ADA deficiency and the limits of transplant (§28) ───────────────────
q("A 5-month-old boy with severe combined immunodeficiency is found to have adenosine deaminase deficiency, with markedly elevated deoxyadenosine metabolites. His parents have been told that an allogeneic stem cell transplant can reconstitute his immune system, and they ask whether a successful transplant will make him entirely well. He has already shown mild developmental delay and a sensorineural hearing deficit.\n\nWhich of the following best explains why a stem cell transplant may not correct all of his problems?",
  ["A. Donor cells are rejected in this form of the disease",
   "B. Graft-versus-host disease is inevitable in this disorder",
   "C. The enzyme defect persists outside the blood compartment",
   "D. The transplant corrects T cells but never corrects B cells",
   "E. Transplanted cells cannot cross the blood-brain barrier",
   ],
  2,
  "A STEM CELL TRANSPLANT REPLACES BLOOD-FORMING CELLS AND NOTHING ELSE. In adenosine deaminase deficiency the enzyme defect is corrected IN THE BLOOD BUT NOT IN OTHER ORGANS — and because NEURONS ARE ALSO AFFECTED BY THE TOXIC METABOLITES, NEUROLOGICAL AND DEVELOPMENTAL PROBLEMS CAN PERSIST DESPITE A TECHNICALLY SUCCESSFUL TRANSPLANT.\n\nThe contrast is the point of the objective. X-LINKED SCID mutates the COMMON GAMMA CHAIN, a protein shared by receptors for many interleukins. That is a PURELY HAEMATOPOIETIC DEFECT, so transplant is genuinely curative. ADA DEFICIENCY IS A SYSTEMIC METABOLIC DISEASE THAT HAPPENS TO PRESENT AS AN IMMUNODEFICIENCY — which is the argument for ENZYME REPLACEMENT OR GENE THERAPY rather than transplant alone.\n\nThe mechanism, worth stating once: accumulated purines INHIBIT RIBONUCLEOTIDE REDUCTASE, deoxyribonucleotide synthesis fails, and toxic phosphorylated products drive precursor apoptosis. LYMPHOCYTES ARE HIT FIRST BECAUSE THEY ARE AMONG THE MOST RAPIDLY DIVIDING CELLS IN THE BODY — but they are not the only cells affected, which is exactly why his hearing and development are already involved.\n\nThe broader principle is a useful one to carry beyond this disease: A TRANSPLANT REPLACES A COMPARTMENT, NOT A GENOME. Any enzyme deficiency whose substrate damages tissues outside that compartment will be only partly corrected — the same logic that governs which metabolic diseases marrow transplantation helps and which it does not.",
  {"0": "Rejection is a general transplant risk managed with conditioning and matching, and it is not specific to this form of the disease. In fact severely immunodeficient recipients reject grafts LESS readily, which is part of why transplant works so well in X-linked SCID.",
   "1": "Graft-versus-host disease is a real risk of allogeneic transplantation and is a particular concern in a recipient who cannot reject donor lymphocytes. It is neither inevitable nor the reason his neurological problems will persist.",
   "3": "Reconstitution after transplant restores both arms in most patients, since the graft supplies lymphoid precursors for the whole lineage. B-cell recovery can be incomplete in some settings, but that is not what this question turns on.",
   "4": "The blood-brain barrier is a genuine obstacle for many therapies, so the instinct is sound. The issue is not that donor CELLS cannot reach neurons — it is that donor cells supply the enzyme only where they are, and his neurons carry the same enzyme defect they always did."},
  "Replacing his blood-forming cells fixes the enzyme in his blood only. The same missing enzyme is causing damage in his brain and ears, and those cells are not replaced by the transplant.",
  exim="fig_slide_pid_pie",
  excap="Primary immunodeficiency by category — antibody deficiencies dominate, with combined defects such as this one at about 15%.")
