# Jeevs Edition — Batch 04: Anemia II · Hemolysis, part 2
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §8  s7-hemolysis        — consequences of hemoglobin catabolism, kidney risk (LO 25)
#   §9  s8-membrane-enzyme  — splenectomy, pyruvate kinase, triggers, inheritance (LO 28)
#   §10 s9-globin           — marrow expansion, electrophoresis, sickle complications (LO 7, 28)
# Completes the block begun in batch 03. Options alphabetised; "correct" is the 0-based
# index AFTER alphabetisation.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ── 1. Pigmented gallstones in a young patient (§8) ───────────────────────────
q("A 19-year-old woman comes to the emergency department because of a 6-hour history of severe pain in the right upper quadrant that began after a meal and radiates to her right shoulder. She has had three similar but milder episodes over the past year. She has hereditary spherocytosis, diagnosed at 6 years of age, and takes daily folic acid. She has never been pregnant and does not use oral contraceptives. Her temperature is 37.4°C (99.3°F), pulse is 96/min, and blood pressure is 122/74 mm Hg. She is 165 cm (5 ft 5 in) tall and weighs 58 kg (128 lb); BMI is 21 kg/m2. Physical examination shows scleral icterus and tenderness in the right upper quadrant; the spleen is palpated 5 cm below the left costal margin.\n\nLaboratory studies show:\nHemoglobin 10.2 g/dL (N=12.0–16.0 g/dL)\nHematocrit 30% (N=36%–46%)\nReticulocyte count 7.4% (N=0.5%–1.5%)\nTotal bilirubin 3.6 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.4 mg/dL (N=0.0–0.3 mg/dL)\nAlkaline phosphatase 72 U/L (N=25–100 U/L)\nAlanine aminotransferase 26 U/L (N=10–40 U/L)\n\nUltrasonography of the abdomen shows multiple small echogenic stones in the gallbladder without wall thickening or ductal dilation. Which of the following best explains the formation of this patient's gallstones?",
  ["A. Bacterial deconjugation of bilirubin by β-glucuronidase within the biliary tract",
   "B. Impaired gallbladder emptying with prolonged biliary stasis",
   "C. Loss of bile salts through a diseased terminal ileum, contracting the bile salt pool",
   "D. Precipitation of calcium bilirubinate from chronically increased unconjugated bilirubin in bile",
   "E. Supersaturation of bile with cholesterol relative to solubilizing bile salts"],
  3,
  "Chronic hemolysis produces pigment (black) gallstones, and the arithmetic is simple. Every destroyed erythrocyte delivers its heme for catabolism → unconjugated bilirubin is produced far faster than normal → the liver conjugates and excretes it → the bilirubin load delivered into bile is chronically enormous → calcium bilirubinate precipitates out.\n\nThis is one of the three consequences §9 attaches to ANY long-standing hemolysis: anemia, jaundice, splenomegaly and pigmented gallstones. It is why gallstones in a teenager or young adult with a normal body habitus should not be read as ordinary gallbladder disease — at her age, with this build and no pregnancies or estrogen exposure, cholesterol stones are unlikely and the stones are a clue to the underlying hematologic disorder rather than an independent problem.\n\nHer laboratory pattern confirms the mechanism rather than obstruction: the bilirubin rise is almost entirely UNCONJUGATED (direct fraction 0.4 mg/dL), with a normal alkaline phosphatase and no ductal dilation. Splenectomy for her spherocytosis would reduce ongoing stone formation, and cholecystectomy is commonly performed at the same operation.",
  {"0": "Bacterial β-glucuronidase deconjugates bilirubin already in bile and produces BROWN pigment stones. It would be the answer with biliary infection or infestation — ascending cholangitis, a biliary stricture, or a liver fluke — with ductal dilation and cholangitic features, none of which she has.",
   "1": "Biliary stasis promotes stone formation in prolonged fasting, total parenteral nutrition, rapid weight loss, and after vagotomy. It would be the answer in a hospitalized patient who has not eaten for weeks; it does not explain stones in a young outpatient whose bilirubin production is quadrupled.",
   "2": "Terminal ileal disease or resection interrupts the enterohepatic circulation of bile salts, and does cause stones — but by contracting the bile salt pool so that cholesterol precipitates, in a patient with Crohn disease or an ileal resection. She has no gastrointestinal disease.",
   "4": "Cholesterol supersaturation is the mechanism of the common cholesterol stone, favored by female sex, obesity, multiparity, estrogen use and increasing age — the classic risk profile. She has a BMI of 21 kg/m2, has never been pregnant, takes no estrogen, and is 19 years old, and her hemolysis provides a far better explanation."},
  "Her body destroys red cells constantly, and the yellow pigment from that destruction pours into her bile. Eventually the pigment settles out and hardens into stones — which is why she has gallstones decades earlier than most people.",
  exim="fig_pigment_stones",
  excap="Pathogenesis of pigment stones: chronic hemolysis raises the unconjugated bilirubin delivered into bile, which precipitates as calcium bilirubinate.")

# ── 2. Free heme and the kidney (§8) ──────────────────────────────────────────
q("A 23-year-old man is admitted to the hospital because of 2 days of jaundice, dark brown urine, and fatigue that began after he took a sulfonamide antibiotic. Over the next 24 hours in the hospital his urine output falls to 15 mL/h despite intravenous fluids. He has no history of kidney disease. His temperature is 37.2°C (99.0°F), pulse is 118/min, respirations are 22/min, and blood pressure is 104/62 mm Hg. Physical examination shows deep scleral icterus and pallor; the jugular venous pulse is visible at 4 cm above the sternal angle, and the lungs are clear.\n\nLaboratory studies show:\nHemoglobin 5.8 g/dL (N=13.5–17.5 g/dL)\nHematocrit 17% (N=41%–53%)\nReticulocyte count 2.2% (N=0.5%–1.5%)\nPlatelet count 232,000/mm3 (N=150,000–400,000/mm3)\nLactate dehydrogenase 1,240 U/L (N=45–200 U/L)\nHaptoglobin <10 mg/dL (N=30–200 mg/dL)\nTotal bilirubin 5.2 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.4 mg/dL (N=0.0–0.3 mg/dL)\nCreatinine 2.9 mg/dL (N=0.6–1.2 mg/dL)\nPotassium 5.3 mEq/L (N=3.5–5.0 mEq/L)\n\nHis creatinine concentration was 0.9 mg/dL on admission. Urinalysis shows a dipstick strongly positive for blood with no erythrocytes on microscopy, and pigmented granular casts. Which of the following best explains the deterioration in this patient's renal function?",
  ["A. Deposition of immune complexes along the glomerular basement membrane",
   "B. Direct tubular injury by filtered free heme, with obstruction of tubules by pigment casts",
   "C. Embolic occlusion of renal arterioles by aggregated erythrocytes",
   "D. Precipitation of uric acid crystals within the renal tubules",
   "E. Prerenal hypoperfusion from intravascular volume depletion"],
  1,
  "This is why §8 calls intravascular hemolysis the more dangerous form. Hemoglobin is safe inside a cell and toxic outside one. Once free hemoglobin exceeds the binding capacity of haptoglobin — which here is entirely consumed, at less than 10 mg/dL — it is filtered at the glomerulus → free heme is directly toxic to the proximal tubular epithelium, generates reactive oxygen species, scavenges nitric oxide and causes intrarenal vasoconstriction → pigment casts obstruct the tubular lumen → acute tubular necrosis.\n\nThe urinalysis is the confirmation: a dipstick positive for blood with no erythrocytes (the dipstick detects heme, not cells) together with pigmented granular casts. His creatinine has risen from 0.9 to 2.9 mg/dL in a day, with the hyperkalemia that accompanies acute tubular injury.\n\nThe same mechanism kills patients after ABO-incompatible transfusion. Management is aggressive intravenous fluid to maintain a high urine flow and dilute the pigment load, removal of the trigger, and support of the anemia — the injury is potentially reversible if the tubules are kept flushed.",
  {"0": "Immune complex deposition produces a glomerulonephritis — hypertension, edema, proteinuria and DYSMORPHIC erythrocytes with red cell casts in the sediment. It would be the answer with erythrocytes visible on microscopy; his sediment has none, which is the whole point of the finding.",
   "2": "Erythrocytes do not aggregate into arteriolar emboli in this setting. Embolic renal injury occurs with cholesterol emboli after arterial instrumentation or with septic emboli in endocarditis, and would come with livedo reticularis, eosinophilia, or a murmur and fever.",
   "3": "Uric acid crystal nephropathy is the renal lesion of tumor lysis syndrome, after treatment of a bulky rapidly dividing malignancy, and comes with hyperphosphatemia, hyperuricemia and HYPOcalcemia. He is hemolyzing after a drug, not being treated for a tumor.",
   "4": "Volume depletion is worth excluding in any acute kidney injury, and it would be the answer with dry mucous membranes, flat neck veins and a response to fluids. He has a visible jugular venous pulse at 4 cm, has received intravenous fluid, and is still oliguric — so hypoperfusion is not the explanation."},
  "When red cells burst inside blood vessels, hemoglobin spills loose and gets filtered into the kidney. Raw hemoglobin poisons the kidney's tubes and clogs them, so the kidney stops making urine.",
  exim="fig_bilirubin",
  excap="Hemoglobin catabolism: heme released from destroyed erythrocytes is normally handled entirely within macrophages, and only reaches plasma and the glomerular filtrate when cells rupture inside the vessel.")

# ── 3. Acholuric jaundice (§8) ────────────────────────────────────────────────
q("A 31-year-old woman is evaluated because of 3 weeks of fatigue and progressive yellowing of her eyes. She takes no medications, does not drink alcoholic beverages, and has no history of liver disease. Her temperature is 37.0°C (98.6°F), pulse is 98/min, and blood pressure is 118/72 mm Hg. Physical examination shows deep scleral icterus; the abdomen is soft with no hepatomegaly, and the spleen is palpated 3 cm below the left costal margin. Her stools are normal in color.\n\nLaboratory studies show:\nHemoglobin 8.8 g/dL (N=12.0–16.0 g/dL)\nHematocrit 26% (N=36%–46%)\nReticulocyte count 9.1% (N=0.5%–1.5%)\nTotal bilirubin 4.2 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.3 mg/dL (N=0.0–0.3 mg/dL)\nAlkaline phosphatase 68 U/L (N=25–100 U/L)\nAlanine aminotransferase 22 U/L (N=10–40 U/L)\nLactate dehydrogenase 520 U/L (N=45–200 U/L)\n\nUrinalysis shows increased urobilinogen and NO bilirubin. Which of the following best explains the absence of bilirubin in this patient's urine?",
  ["A. Bilirubin is cleared entirely by biliary excretion, so none reaches the circulation",
   "B. Bilirubin is degraded within the renal collecting system before it can be detected",
   "C. Conjugated bilirubin is reabsorbed by the renal tubules after being filtered",
   "D. The excess bilirubin is unconjugated and bound to albumin, and is therefore not filtered at the glomerulus",
   "E. The renal threshold for bilirubin excretion is raised during hemolysis"],
  3,
  "Unconjugated bilirubin is water-insoluble and travels tightly bound to albumin. Albumin is not filtered by a healthy glomerulus, so neither is the bilirubin riding on it → hemolytic jaundice is ACHOLURIC: deeply jaundiced patient, no bilirubin in the urine.\n\nOnly CONJUGATED bilirubin — water-soluble and not albumin-bound — appears in urine, which is why bilirubinuria points to hepatocellular disease or biliary obstruction instead. Her direct fraction is 0.3 mg/dL against a total of 4.2 mg/dL, with a normal alkaline phosphatase and transaminases, so no conjugated bilirubin is accumulating to be excreted.\n\nThe raised urobilinogen is the positive half of the same picture and is worth reading alongside it. The liver conjugates and excretes the extra bilirubin normally → gut bacteria convert it to urobilinogen → some is reabsorbed and spills into the urine. In biliary OBSTRUCTION the pattern inverts: bilirubin appears in the urine, urobilinogen disappears from it, and the stools become pale. Hers are normal in color.",
  {"0": "Bilirubin certainly does reach the circulation — hers is 4.2 mg/dL, which is what is making her yellow. This option would describe a patient with a normal serum bilirubin, in whom the question of urinary bilirubin would not arise.",
   "1": "There is no renal or bacterial degradation pathway for bilirubin in the collecting system. Bacterial conversion of bilirubin does occur, but in the COLON, where it produces the urobilinogen that this patient has in excess.",
   "2": "Filtered conjugated bilirubin is not meaningfully reabsorbed; that is exactly why it appears in the urine in hepatocellular and obstructive jaundice. If this option were true, bilirubinuria would never occur in any disease.",
   "4": "There is no adjustable renal threshold for bilirubin in the way there is for glucose. The determinant is whether the molecule is filterable at all, which depends on conjugation and albumin binding — not on how much hemolysis is taking place."},
  "The yellow pigment from broken red cells hitches a ride on a large blood protein, and the kidney's filter will not let that protein through. So she is very yellow but her urine stays a normal color.",
  exim="fig_bilirubin",
  excap="Bilirubin metabolism: unconjugated bilirubin travels albumin-bound to the liver, and only the conjugated, water-soluble form can appear in urine.")

# ── 4. Before splenectomy (§9 + §11) ──────────────────────────────────────────
q("A 16-year-old boy with hereditary spherocytosis is evaluated in the clinic. Over the past 2 years he has required four transfusions, misses school regularly because of fatigue, and has had two episodes of biliary colic. His hemoglobin concentration ranges between 7.5 and 8.5 g/dL, and his reticulocyte count is persistently above 10%. Ultrasonography shows gallstones. His spleen is palpated 8 cm below the left costal margin. After discussion, total splenectomy with cholecystectomy is planned for 6 weeks from now. He takes daily folic acid; his childhood immunizations are complete.\n\nWhich of the following is the most appropriate next step in management?",
  ["A. Administer pneumococcal, meningococcal, and Haemophilus influenzae type b vaccines",
   "B. Begin lifelong iron chelation therapy",
   "C. Begin oral ferrous sulfate therapy",
   "D. Obtain hemoglobin electrophoresis",
   "E. Transfuse to a hemoglobin concentration of 12 g/dL"],
  0,
  "Splenectomy cures the anemia of hereditary spherocytosis in functional terms — remove the site of destruction and red cell survival normalizes, although the spherocytes themselves remain — but it trades a hematologic problem for a lifelong infectious one.\n\nWithout a spleen the patient cannot clear opsonized ENCAPSULATED organisms: Streptococcus pneumoniae above all, then Neisseria meningitidis and Haemophilus influenzae type b. Overwhelming post-splenectomy infection has a mortality measured in hours, and the risk never goes away. So vaccination against all three is given BEFORE the operation — at least 2 weeks in advance, while the spleen is still present to mount a proper antibody response. He has 6 weeks, which is ample.\n\nThe rest of the package, which the explanation should carry even though it is not the lead-in: antibiotic prophylaxis after surgery (particularly in children), a standing plan for immediate evaluation of any fever, and — the smear sign that the spleen is gone — Howell-Jolly bodies appearing afterwards.\n\nHis routine childhood immunizations do not cover this. Conjugate pneumococcal vaccine given in infancy is not equivalent to the asplenia schedule, which adds the polysaccharide vaccine and meningococcal coverage.",
  {"1": "Iron chelation is for transfusional iron overload, which develops after roughly 10 to 20 units. Four transfusions over 2 years is nowhere near that threshold, and his hemolysis is extravascular — the iron from it is recycled, not lost.",
   "2": "Oral iron treats iron deficiency. He is not iron deficient: his marrow is turning over cells at maximum speed and recycling iron efficiently, and giving iron here adds nothing. FOLIC acid is the supplement that a high-turnover marrow genuinely needs, and he already takes it.",
   "3": "Hemoglobin electrophoresis would be the answer if the diagnosis were in doubt and a hemoglobinopathy were suspected — a microcytic anemia with target cells, say. His diagnosis is established, his cells are spherocytes, and electrophoresis would be normal.",
   "4": "Transfusing to a normal hemoglobin is neither necessary nor safe practice; he tolerates 7.5 to 8.5 g/dL, and transfusion carries alloimmunization and iron loading. It would be the answer only for symptomatic severe anemia or an aplastic crisis, and it does nothing about the infection risk the surgery creates."},
  "Taking out the spleen will fix his anemia, but the spleen is also the organ that protects against a few specific bacteria. So he gets those vaccines while he still has a spleen to respond to them properly.",
  exim="fig_howell_jolly",
  excap="After splenectomy the smear shows Howell-Jolly bodies (arrows) — dense nuclear remnants that a working spleen would have removed.")

# ── 5. Pyruvate kinase deficiency (§9) ────────────────────────────────────────
q("A 6-year-old girl is evaluated because of lifelong anemia and intermittent jaundice first noted in the newborn period, when she required phototherapy and an exchange transfusion. Her parents are first cousins. She has had no episodes triggered by drugs or foods. Her temperature is 37.0°C (98.6°F), pulse is 96/min, and blood pressure is 98/60 mm Hg. Physical examination shows mild scleral icterus and a spleen palpated 4 cm below the left costal margin. She is active and plays sports without limitation despite her hemoglobin concentration.\n\nLaboratory studies show:\nHemoglobin 8.4 g/dL (N=11.5–15.5 g/dL)\nHematocrit 25% (N=35%–45%)\nMean corpuscular volume 92 µm3 (N=77–95 µm3)\nReticulocyte count 12.6% (N=0.5%–1.5%)\nTotal bilirubin 3.2 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.3 mg/dL (N=0.0–0.3 mg/dL)\nLactate dehydrogenase 310 U/L (N=45–200 U/L)\n\nA peripheral blood smear shows polychromasia and scattered contracted cells with short spiny projections; no spherocytes and no bite cells are seen. Osmotic fragility is normal, the direct antiglobulin test is negative, hemoglobin electrophoresis shows no abnormal band, and erythrocyte glucose-6-phosphate dehydrogenase activity is normal. Which of the following best explains the hemolysis in this patient?",
  ["A. Decreased production of adenosine triphosphate by anaerobic glycolysis",
   "B. Decreased regeneration of reduced glutathione by the hexose monophosphate shunt",
   "C. Defective anchoring of spectrin to the inner erythrocyte membrane",
   "D. Polymerization of deoxygenated hemoglobin into rigid fibers",
   "E. Reduced synthesis of structurally normal beta globin chains"],
  0,
  "Every alternative has been excluded by a named test, which is what the vignette is built to do: normal osmotic fragility and no spherocytes rule out the membrane, a negative antiglobulin test rules out antibody, a normal electrophoresis rules out the globins, and a normal enzyme assay rules out G6PD. What is left is the other enzyme — pyruvate kinase.\n\nPyruvate kinase catalyzes the last step of glycolysis. A red cell has no mitochondria, so anaerobic glycolysis is its ONLY source of adenosine triphosphate → without it the cation pumps fail → the cell dehydrates, stiffens and becomes the contracted, spiculated form on her smear → the spleen removes it. Chronic extravascular hemolysis, autosomal recessive (hence the consanguinity), often severe enough to cause neonatal jaundice needing exchange transfusion, and unrelated to drugs or foods.\n\nOne elegant detail explains her exercise tolerance. The block is upstream of pyruvate, so 2,3-bisphosphoglycerate accumulates → hemoglobin's oxygen affinity falls → oxygen is unloaded more readily to tissue. These patients tolerate a given hemoglobin concentration better than other anemic patients do.\n\nManagement is folic acid, transfusion when needed, and splenectomy in severe cases.",
  {"1": "Failure to regenerate reduced glutathione is G6PD deficiency — but her enzyme activity is normal, her hemolysis is continuous rather than episodic, there is no oxidant trigger, and there are no bite cells. Those are four separate points against it.",
   "2": "A defective membrane skeleton is hereditary spherocytosis, which would be the answer with spherocytes, INCREASED osmotic fragility, a high mean corpuscular hemoglobin concentration, and dominant inheritance. Her smear shows no spherocytes and her fragility is normal.",
   "3": "Polymerization of deoxygenated hemoglobin is sickle cell disease, and it would be the answer with crescent-shaped cells, pain crises, and hemoglobin S on electrophoresis. Her electrophoresis shows no abnormal band.",
   "4": "Reduced synthesis of normal beta chains is beta thalassemia — a quantity problem that produces MICROCYTOSIS with target cells and a raised hemoglobin A2. Her mean corpuscular volume is 92 µm3 and her electrophoresis is normal."},
  "Red cells have no power plant, so they make all their energy one way — and her cells are missing a key enzyme in that pathway. Starved of energy, the cells shrivel and stiffen, and the spleen clears them out.",
  exim="fig_g6pd_pathway",
  excap="For contrast, the pathway that is intact in this patient: G6PD generates NADPH for glutathione regeneration, a separate route from the glycolytic pathway that supplies the cell's adenosine triphosphate.")

# ── 6. The commonest G6PD trigger (§9) ────────────────────────────────────────
q("An 8-year-old boy is admitted to the hospital with a 3-day history of fever, cough, and right-sided chest pain. A chest radiograph shows a right lower lobe consolidation, and treatment with intravenous ampicillin is begun. He has taken no other medication, has no known allergies, and eats a regular diet with no unusual foods in the past month. On the second hospital day he becomes jaundiced and passes dark urine. His temperature is 38.6°C (101.5°F), pulse is 124/min, respirations are 30/min, and blood pressure is 100/60 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 95%.\n\nLaboratory studies on the second hospital day show:\nHemoglobin 8.0 g/dL (N=11.5–15.5 g/dL)\nHematocrit 24% (N=35%–45%)\nReticulocyte count 3.1% (N=0.5%–1.5%)\nLactate dehydrogenase 640 U/L (N=45–200 U/L)\nHaptoglobin <10 mg/dL (N=30–200 mg/dL)\nTotal bilirubin 3.4 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.3 mg/dL (N=0.0–0.3 mg/dL)\n\nHis hemoglobin concentration was 12.6 g/dL on admission. The direct antiglobulin test is negative, and a peripheral blood smear shows erythrocytes with a semicircular portion of the periphery missing. Which of the following is the most likely precipitant of this episode?",
  ["A. Acetaminophen administered for fever",
   "B. Dehydration from reduced oral intake",
   "C. Inhaled albuterol administered for wheezing",
   "D. The systemic infection itself",
   "E. Transient hypoxemia from the pneumonia"],
  3,
  "Drugs and fava beans are the triggers everyone memorizes, but §9 is explicit that INFECTION is the commonest precipitant of hemolysis in G6PD deficiency in practice — and this boy has received no oxidant drug. Ampicillin is not on the list; acetaminophen at therapeutic doses is not either.\n\nThe mechanism is the activated neutrophil. Phagocytes mounting a respiratory burst against the pathogen generate hydrogen peroxide and other reactive oxygen species → these diffuse into nearby erythrocytes → a G6PD-deficient cell cannot regenerate reduced glutathione to neutralize them → hemoglobin is oxidized and precipitates as Heinz bodies → splenic macrophages bite out the inclusions, leaving the cells on his smear.\n\nThe clinical importance is that the hemolysis is easily mistaken for the infection worsening: a child with pneumonia who becomes more tachycardic and paler on day 2 is assumed to be septic. The findings that reveal it are the jaundice, the dark urine, the hemoglobin falling from 12.6 to 8.0 g/dL, the undetectable haptoglobin, and the bite cells.",
  {"0": "Acetaminophen is safe at therapeutic doses in G6PD deficiency and is not on the list of oxidant precipitants; massive overdose is a different question, and one about the liver. It would be the answer if the drug given had been a sulfonamide, primaquine, dapsone, or nitrofurantoin.",
   "1": "Dehydration concentrates intracellular hemoglobin and worsens sickling in SICKLE CELL disease — that is where it belongs as an answer. It does not generate the oxidant stress that a G6PD-deficient cell cannot handle.",
   "2": "Albuterol is not an oxidant and has no role in hemolysis; it is included because it is a plausible-sounding inpatient medication. He was not given it, and no bronchodilator causes Heinz body formation.",
   "4": "His oxygen saturation is 95%, so there is no meaningful hypoxemia to invoke. Hypoxia is not a trigger for G6PD hemolysis in any case — the injury is oxidative, and paradoxically requires oxygen-derived species rather than their absence."},
  "Fighting an infection makes the body release bleach-like chemicals to kill germs, and those chemicals damage his red cells too. His cells lack the enzyme that normally cleans them up, so the infection itself set off the hemolysis.",
  exim="fig_bite_uw",
  excap="The resulting morphology: erythrocytes with a discrete semicircular portion of the periphery removed by a splenic macrophage.")

# ── 7. Dominant inheritance and independence (§9) ─────────────────────────────
q("A 29-year-old man and his 27-year-old partner come to the office for preconception counseling. He has hereditary spherocytosis caused by a documented mutation in ANK1, as did his mother; he underwent splenectomy at age 14. His partner is healthy, with a normal complete blood count and no family history of anemia, jaundice, gallstones, or splenectomy. Their first child, now 2 years old, has hereditary spherocytosis and has required one transfusion.\n\nIf this couple has another child, which of the following is the probability that the child will inherit hereditary spherocytosis?",
  ["A. 1 in 2", "B. 1 in 3", "C. 1 in 4", "D. 2 in 3", "E. 3 in 4"],
  0,
  "Hereditary spherocytosis is AUTOSOMAL DOMINANT in about three-quarters of cases, including the ANK1 mutations. One affected parent who is heterozygous passes the mutant allele to half of his offspring, and a single copy is sufficient to cause disease → 1 in 2 with each pregnancy.\n\nThe trap is the child they already have. Each conception is an independent event: a coin that has come up heads once is no less likely to come up heads again. Having an affected 2-year-old neither raises nor lowers the risk for the next pregnancy, and reasoning that they have 'used up' their affected child is the named error the distractors are built from.\n\nHis dominant inheritance is visible in the pedigree — his mother was affected as well, and §9 notes this pattern showing up as a parent jaundiced in adolescence or splenectomized young. His own splenectomy cured his anemia but changed nothing about what he transmits: the mutation is in every cell, and removing the spleen removes the site of destruction, not the defect.",
  {"1": "1 in 3 is the risk of being a carrier among the unaffected siblings in an autosomal RECESSIVE pedigree, once an affected child has been excluded. It has no application to a dominant condition, in which carriers are affected.",
   "2": "1 in 4 is the recurrence risk when BOTH parents are carriers of an autosomal recessive condition — the figure for sickle cell disease, beta thalassemia major, or pyruvate kinase deficiency. Applying it here treats a dominant disease as recessive.",
   "3": "2 in 3 comes from conditioning on being unaffected in a recessive pedigree, and would only be reached by a chain of reasoning that does not apply to a dominantly inherited disorder in which the father is affected.",
   "4": "3 in 4 is the probability of being unaffected in a recessive cross, or of showing a dominant phenotype when both parents are heterozygous for a dominant allele. Neither describes this couple, in whom only one parent carries the mutation."},
  "The gene is dominant, so a child only needs one copy — and dad passes on one of his two copies each time, a coin flip. Already having one affected child does not change the odds for the next one.",
  exim="fig_spherocytes",
  excap="The cellular consequence of the inherited defect: round, densely stained erythrocytes lacking the pale central zone.")

# ── 8. Marrow expansion — the skull (§10) ─────────────────────────────────────
q("A 5-year-old boy who receives regular transfusions for beta-thalassemia major is evaluated because of protrusion of the upper jaw and prominence of the forehead noted by his parents over the past year. He was diagnosed at 8 months of age and has been transfused irregularly because the family lives far from the center. His temperature is 37.0°C (98.6°F), pulse is 110/min, and blood pressure is 96/58 mm Hg. Physical examination shows frontal bossing, prominent maxillae with malocclusion of the teeth, and a spleen palpated 6 cm below the left costal margin.\n\nLaboratory studies show:\nHemoglobin 7.2 g/dL (N=11.5–15.5 g/dL)\nHematocrit 22% (N=35%–45%)\nMean corpuscular volume 63 µm3 (N=77–95 µm3)\nReticulocyte count 6.4% (N=0.5%–1.5%)\nTotal bilirubin 2.6 mg/dL (N=0.1–1.0 mg/dL)\n\nA radiograph of the skull is shown. Which of the following best explains these radiographic and facial findings?",
  ["A. Deposition of transfusional iron within the cranial bones",
   "B. Expansion of the marrow cavity driven by intense ineffective erythropoiesis",
   "C. Infiltration of the skull by leukemic blasts",
   "D. Osteopenia caused by long-term glucocorticoid therapy",
   "E. Subperiosteal hemorrhage caused by vitamin C deficiency"],
  1,
  "Unpartnered alpha globin chains precipitate inside erythroid precursors and kill them before release — ineffective erythropoiesis. The marrow is therefore working furiously and delivering almost nothing, and erythropoietin drive stays maximal → the hematopoietic marrow expands into every space it can reach.\n\nIn the skull it expands the diploic space between the inner and outer tables, and the trabeculae are pushed into perpendicular spicules, producing the radiographic appearance of fine vertical striations. In the facial bones the same expansion produces frontal bossing and maxillary prominence with dental malocclusion — the so-called chipmunk facies. Elsewhere it thins cortical bone and causes pathologic fractures, and extramedullary hematopoiesis enlarges the liver and spleen.\n\nThe clinically useful point is that these findings are largely PREVENTABLE. Adequate regular transfusion suppresses the erythropoietin drive and therefore the marrow expansion; this boy's changes reflect irregular transfusion because of the distance his family travels. The marrow is hypercellular while the child is profoundly anemic — the paradox that defines ineffective erythropoiesis.",
  {"0": "Transfusional iron does accumulate in this disease and damages liver, pancreas, heart and endocrine organs — but it deposits in parenchymal organs, not as bone expansion, and it does not widen the diploic space. It would be the answer for hepatomegaly with raised transaminases, impaired glucose tolerance and delayed puberty.",
   "2": "Leukemic infiltration can cause bone pain and lytic change in a child, and would be the answer with blasts on the smear, a leukocyte count that is very abnormal, and thrombocytopenia. His counts are those of thalassemia, and the skull change here is a symmetric expansion rather than destructive infiltration.",
   "3": "Long-term glucocorticoids cause generalized osteopenia with vertebral compression, but they have no role in the treatment of thalassemia major and he is not taking any. The appearance described is expansion of a marrow space, not loss of bone mineral.",
   "4": "Scurvy causes subperiosteal hemorrhage, bleeding gums and poor wound healing, and would be the answer with a grossly deficient diet and perifollicular hemorrhage. It does not widen the diploë, and it does not produce microcytosis with a raised hemoglobin F."},
  "His marrow is desperately trying to make red cells that die before they are finished, so it never switches off and it grows to fill every available space — including inside his skull and cheekbones. Regular transfusions would have turned that drive down.",
  image="fig_hair_on_end",
  imcap="Lateral radiograph of the skull in a child. The space between the inner and outer tables of the cranial vault is widened, and fine striations run perpendicular to the skull surface.",
  exim="fig_beta_thal_uw",
  excap="The peripheral smear from the same disease: small, pale erythrocytes with marked variation in size and shape and numerous target cells.")

# ── 9. Beta-thalassemia minor on electrophoresis (§10) ────────────────────────
q("A 27-year-old woman comes to the office for a routine examination. She feels well and has no symptoms. A complete blood count obtained 2 months ago showed microcytosis, and a 3-month course of oral iron produced no change in her indices. She has never been pregnant. Vital signs are within normal limits. Physical examination shows no abnormalities; there is no scleral icterus and the spleen is not palpable.\n\nLaboratory studies show:\nHemoglobin 11.2 g/dL (N=12.0–16.0 g/dL)\nHematocrit 34% (N=36%–46%)\nMean corpuscular volume 67 µm3 (N=80–100 µm3)\nRed cell distribution width 13.2% (N=11.5%–14.5%)\nErythrocyte count 5.4 million/mm3 (N=3.5–5.5 million/mm3)\nSerum ferritin 84 ng/mL (N=10–120 ng/mL)\nTotal iron-binding capacity 318 µg/dL (N=250–400 µg/dL)\n\nA peripheral blood smear shows small, pale erythrocytes and scattered target cells. Which of the following hemoglobin electrophoresis results is most likely in this patient?",
  ["A. Hemoglobin A2 1.8%, hemoglobin F less than 1%, no hemoglobin S",
   "B. Hemoglobin A2 2.0%, hemoglobin F 88%, no hemoglobin S",
   "C. Hemoglobin A2 2.4%, hemoglobin F 2%, hemoglobin S 39%",
   "D. Hemoglobin A2 3.0%, hemoglobin F 1%, hemoglobin S 89%",
   "E. Hemoglobin A2 5.4%, hemoglobin F 2.6%, no hemoglobin S"],
  4,
  "A RAISED hemoglobin A2 is the signature of beta-thalassemia trait, and everything in this vignette points there: microcytosis out of proportion to a nearly normal hemoglobin, a NORMAL red cell distribution width, a high-normal erythrocyte count, entirely normal iron studies, target cells, and no response to 3 months of iron.\n\nThe mechanism of the raised A2 follows from the arithmetic of globin chains. One beta gene is defective → beta chain output falls → alpha chains that would have paired with beta pair instead with delta (giving hemoglobin A2, α₂δ₂) and with gamma (giving hemoglobin F, α₂γ₂). So A2 rises above the normal ceiling of roughly 3.5%, typically to 3.5–7%, with a slight rise in hemoglobin F.\n\nThis is the counterpart to the alpha thalassemia item: in alpha-thalassemia trait, ALL of the hemoglobins need alpha chains, so every fraction falls proportionately and the electrophoresis looks unremarkable — the diagnosis there is made by gene testing after exclusion of everything else.\n\nThe practical instruction is the one §10 repeats: she should be given no more iron, and she needs counseling rather than treatment.",
  {"0": "A normal hemoglobin A2 with no hemoglobin F and no hemoglobin S is the normal adult pattern, and it would be the expected result in ALPHA-thalassemia trait or in iron deficiency. Iron deficiency has been excluded by her ferritin, iron-binding capacity and lack of response to therapy.",
   "1": "Hemoglobin F of 88% with almost no hemoglobin A is the pattern of beta-thalassemia MAJOR or of hereditary persistence of fetal hemoglobin. Thalassemia major presents in infancy with transfusion dependence, not as an incidental finding in a well 27-year-old.",
   "2": "Hemoglobin S at 39% alongside hemoglobin A is sickle cell trait, which is asymptomatic — but it does not cause microcytosis, target cells, or a mean corpuscular volume of 67 µm3. It would be the answer if her indices were normal.",
   "3": "Hemoglobin S at 89% with no hemoglobin A is sickle cell DISEASE, which would come with a hemolytic anemia, reticulocytosis, sickled forms on the smear, and a history of painful crises from early childhood. She is asymptomatic with a hemoglobin of 11.2 g/dL."},
  "Her cells are small but she is barely anemic, and iron did nothing — so the problem is building hemoglobin, not raw material. With one beta gene faulty, the spare chains pair up differently, and that alternative hemoglobin shows up raised on the gel.",
  exim="fig_thal_minor_uw",
  excap="Beta-thalassemia minor on a peripheral smear: small, pale erythrocytes with target cells, in a patient who is only mildly anemic.")

# ── 10. Alpha thalassemia — counseling arithmetic (§10) ───────────────────────
q("A 30-year-old woman and her 32-year-old partner come to the office for preconception counseling. Both are asymptomatic. Each has a mean corpuscular volume of approximately 70 µm3 with a hemoglobin concentration above 12 g/dL, normal iron studies, and a normal hemoglobin electrophoresis. Genetic testing shows that each of them carries a deletion of two alpha globin genes, and that in each of them the two deleted genes lie on the SAME copy of chromosome 16, with the other copy carrying two intact genes.\n\nFor each pregnancy, which of the following is the probability that the fetus will have hydrops fetalis?",
  ["A. 0", "B. 1 in 8", "C. 1 in 4", "D. 1 in 2", "E. 3 in 4"],
  2,
  "Each parent carries one chromosome 16 with NO functioning alpha gene and one with two. Each therefore transmits, with equal probability, either the doubly deleted chromosome or the intact one. A fetus receiving the deleted chromosome from both parents inherits zero functional alpha genes → 1/2 × 1/2 = 1 in 4.\n\nThe outcomes across a pregnancy are worth stating in full: 1 in 4 with no alpha genes (hydrops fetalis, from hemoglobin Barts), 2 in 4 with two genes on one chromosome (alpha-thalassemia trait, like the parents), and 1 in 4 with all four genes (unaffected).\n\nThe detail that decides the item is the word SAME. Two-gene deletions come in two arrangements, and they behave completely differently for a couple:\n\n• cis (--/αα), both deletions on one chromosome — can transmit a chromosome with zero alpha genes, so hydrops is possible. Commoner in Southeast Asian populations.\n• trans (-α/-α), one deletion on each chromosome — every gamete carries at least one alpha gene, so the worst outcome for a child is hemoglobin H disease, and hydrops cannot occur.\n\nCounseling, prenatal diagnosis and planning for intrauterine transfusion follow from which arrangement they have, which is why the genotype rather than the blood count is what gets tested.",
  {"0": "A risk of zero would be correct if their deletions were in the TRANS arrangement — one gene deleted on each chromosome — because then no gamete could carry a chromosome without an alpha gene. The stem specifies that both deletions lie on the same copy.",
   "1": "1 in 8 does not correspond to any step of this cross. It would require a third independent event of probability one half, which there is not; each parent contributes exactly one chromosome 16, so the denominator is 4.",
   "3": "1 in 2 is the proportion of pregnancies expected to produce a child with alpha-thalassemia trait like the parents — inheriting a deleted chromosome from one parent and an intact one from the other. It is the commonest outcome, but it is not hydrops.",
   "4": "3 in 4 is the probability that the fetus will be affected in SOME way, counting both the trait and the hydrops outcomes together, or equivalently the probability of not being entirely unaffected. The question asks specifically about hydrops fetalis."},
  "Each parent has one chromosome with both alpha genes missing, and passes on one of their two chromosomes at random. If the baby happens to get the empty one from each parent, it has no alpha genes at all — and that is a one-in-four coin-flip combination.",
  exim="fig_globin_chains",
  excap="With no alpha chains available, excess gamma chains form hemoglobin Barts (γ₄) — the tetramer that binds oxygen and will not release it.")

# ── 11. Acute chest syndrome (§10) ────────────────────────────────────────────
q("A 16-year-old boy with sickle cell disease is admitted to the hospital with severe pain in his back and thighs and is treated with intravenous fluids and an opioid infusion. On the second hospital day he develops fever, pain on the right side of his chest that is worse with inspiration, and a dry cough. His temperature is 38.8°C (101.8°F), pulse is 122/min, respirations are 30/min, and blood pressure is 114/68 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 88%. Physical examination shows splinting of the right chest and decreased breath sounds at the right base with scattered crackles.\n\nLaboratory studies show:\nHemoglobin 6.9 g/dL (N=13.5–17.5 g/dL)\nHematocrit 21% (N=41%–53%)\nReticulocyte count 11.2% (N=0.5%–1.5%)\nLeukocyte count 19,800/mm3 (N=4500–11,000/mm3)\nPlatelet count 340,000/mm3 (N=150,000–400,000/mm3)\n\nHis baseline hemoglobin concentration is 8.4 g/dL. A chest radiograph shows a new right lower lobe infiltrate that was not present on admission. Which of the following is the most appropriate next step in management?",
  ["A. Administer empiric intravenous cefotaxime and oral azithromycin",
   "B. Administer intravenous furosemide",
   "C. Begin hydroxyurea therapy",
   "D. Increase the rate of the opioid infusion",
   "E. Obtain a ventilation-perfusion scan"],
  0,
  "A new pulmonary infiltrate with fever, chest pain and hypoxemia in a patient with sickle cell disease is acute chest syndrome — the leading cause of death in this population and the complication that most often follows a vaso-occlusive crisis by a day or two.\n\nAntibiotics come first and are given empirically to everyone, because the precipitant is frequently infectious and cannot be identified quickly. Cover encapsulated organisms with a third-generation cephalosporin AND atypicals with a macrolide, since Mycoplasma pneumoniae and Chlamydia pneumoniae are disproportionately common triggers here. Alongside that: supplemental oxygen to keep hemoglobin in the conformation that does not polymerize, careful hydration, incentive spirometry, adequate analgesia — and transfusion, simple or exchange, for progressive hypoxemia.\n\nThe self-perpetuating loop is the reason it escalates so fast: infection or infarction → hypoventilation from pain and splinting → regional hypoxemia → more sickling in the pulmonary microvasculature → more infarction. Breaking any part of it helps, which is why the treatment is a bundle.\n\nA third of episodes follow a painful crisis exactly as here, and opioids themselves contribute through hypoventilation — a reason for vigilance, not for withholding analgesia.",
  {"1": "Furosemide treats volume overload, and would be the answer with distended neck veins, a third heart sound and pulmonary edema on the radiograph. Diuresis in acute chest syndrome is actively harmful: dehydration concentrates intracellular hemoglobin S and accelerates polymerization.",
   "2": "Hydroxyurea reduces the FREQUENCY of acute chest syndrome and painful crises over months by raising hemoglobin F, and he is an excellent candidate for it at discharge. It does nothing acutely, and starting a myelosuppressive agent during a possible infection is the wrong moment.",
   "3": "More opioid addresses pain but worsens the mechanism: sedation and hypoventilation reduce ventilation of the affected lung and drive further sickling. Analgesia must be adequate, but escalating it as the response to new hypoxemia and an infiltrate is the error this option captures.",
   "4": "A ventilation-perfusion scan looks for pulmonary embolism, which is a genuine consideration in a hypercoagulable, immobilized patient. It would be the next step with a clear chest radiograph and unexplained hypoxemia. He has a NEW infiltrate and fever, and imaging must not delay antibiotics."},
  "Sickled cells clogged part of his lung, and infection often starts the whole thing off. He needs antibiotics and oxygen straight away, because this complication can spiral within hours.",
  exim="fig_sickle_target",
  excap="Sickle cell disease on the peripheral smear: rigid crescent-shaped erythrocytes, the cells that lodge in the pulmonary microvasculature.")

# ── 12. Why fluids and oxygen help (§10) ──────────────────────────────────────
q("A 21-year-old woman with sickle cell disease comes to the emergency department because of 8 hours of severe pain in both thighs and her lower back, similar to previous episodes. She ran a 10-km race the previous day in hot weather and drank little afterward. Her temperature is 37.2°C (99.0°F), pulse is 110/min, respirations are 20/min, and blood pressure is 108/66 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 97%. Physical examination shows dry mucous membranes and tenderness of both thighs; the lungs are clear and there is no focal neurologic deficit.\n\nLaboratory studies show:\nHemoglobin 7.9 g/dL (N=12.0–16.0 g/dL)\nHematocrit 23% (N=36%–46%)\nReticulocyte count 10.4% (N=0.5%–1.5%)\nSodium 146 mEq/L (N=136–146 mEq/L)\nCreatinine 1.1 mg/dL (N=0.6–1.2 mg/dL)\n\nHer baseline hemoglobin concentration is 8.0 g/dL. Intravenous normal saline and analgesia are begun. Which of the following best explains the benefit of intravenous hydration in this patient?",
  ["A. Decreased intracellular concentration of hemoglobin S, reducing the rate of polymerization",
   "B. Dilution of plasma free hemoglobin, protecting the renal tubules from injury",
   "C. Increased fetal hemoglobin production by erythroid precursors",
   "D. Increased oxygen-carrying capacity of the blood",
   "E. Increased splenic clearance of sickled erythrocytes"],
  0,
  "Three variables govern how much hemoglobin S polymerizes, and hydration acts on the second of them:\n\n1. The PROPORTION of hemoglobin S and what it can partner with. Hemoglobin S polymerizes readily with itself and poorly with hemoglobin F or A — the lever pulled by hydroxyurea and by transfusion.\n2. The CONCENTRATION of hemoglobin inside the cell. Polymerization is steeply concentration-dependent, so a dehydrated, shrunken erythrocyte sickles far more readily. Restoring plasma volume and cell water lowers that concentration → polymerization falls off sharply.\n3. pH. Acidosis lowers hemoglobin's oxygen affinity (the Bohr effect) → more hemoglobin is in the deoxygenated conformation → and only DEOXYGENATED hemoglobin S polymerizes.\n\nHer crisis has an obvious precipitant in a hot 10-km race with little fluid replacement, and the sodium of 146 mEq/L quietly confirms the dehydration. Oxygen works on the same physical chemistry from the other side, keeping hemoglobin in the conformation that does not polymerize; note that her saturation is 97%, so oxygen is not the missing element here.\n\nHer hemoglobin of 7.9 g/dL is at her baseline, which is the rule in a vaso-occlusive crisis: the problem is ischemia and pain, not a fall in red cell mass.",
  {"1": "Protecting the tubules by diluting plasma free hemoglobin is the rationale for fluids in massive INTRAVASCULAR hemolysis — a G6PD crisis or an ABO-incompatible transfusion. Her crisis is vaso-occlusive, her hemoglobin is at baseline, and her creatinine is normal.",
   "2": "Raising fetal hemoglobin is the mechanism of hydroxyurea, and it takes weeks to months of therapy. No intravenous fluid changes which globin genes an erythroid precursor transcribes.",
   "3": "Oxygen-carrying capacity depends on hemoglobin concentration and saturation; intravenous crystalloid if anything dilutes the hemoglobin slightly. That effect is accepted because the benefit lies elsewhere — in the physical chemistry inside the cell.",
   "4": "Increasing splenic clearance would destroy MORE erythrocytes, not fewer, and would be harmful rather than helpful. Most adults with sickle cell disease have autoinfarcted their spleens in any case, so there is little splenic function left to increase."},
  "Sickle hemoglobin only clumps when it is packed tightly together inside the cell. Giving fluid puts water back into the cells so the molecules are spread further apart and cannot lock together as easily.",
  exim="fig_sickle_mutation",
  excap="The underlying defect: a single amino acid substitution places a sticky hydrophobic patch on the hemoglobin molecule, which allows deoxygenated molecules to polymerize.")

# ── 13. Stroke prevention (§10) ───────────────────────────────────────────────
q("An 8-year-old girl with sickle cell disease is evaluated at a routine visit. She has had three painful episodes in the past year and takes hydroxyurea, penicillin, and folic acid. She has had no headache, weakness, or difficulty with speech, and her school performance is unchanged. Her temperature is 37.0°C (98.6°F), pulse is 92/min, and blood pressure is 104/62 mm Hg. Neurologic examination shows no abnormalities.\n\nLaboratory studies show:\nHemoglobin 8.2 g/dL (N=11.5–15.5 g/dL)\nHematocrit 25% (N=35%–45%)\nReticulocyte count 8.6% (N=0.5%–1.5%)\nHemoglobin F 14% (N=less than 2% after infancy)\n\nTranscranial Doppler ultrasonography shows a time-averaged mean velocity of 212 cm/s in the right middle cerebral artery, confirmed on a repeat study 2 weeks later (abnormal is 200 cm/s or greater). Which of the following is the most appropriate next step in management?",
  ["A. Begin chronic red blood cell transfusion to maintain hemoglobin S below 30%",
   "B. Begin daily low-dose aspirin",
   "C. Begin therapeutic anticoagulation with warfarin",
   "D. Perform carotid endarterectomy",
   "E. Perform splenectomy"],
  0,
  "An abnormal transcranial Doppler velocity of 200 cm/s or more identifies a child at high risk of a first stroke — roughly 10% per year without treatment. The intervention with randomized trial evidence behind it is chronic transfusion to keep the hemoglobin S fraction below 30%, which reduces that risk by more than 90%.\n\nThe mechanism is dilution, the same lever as always. Transfused donor cells contain hemoglobin A, which hemoglobin S polymerizes with poorly → the sickling tendency of the circulating red cell mass falls → the turbulent high-velocity flow through a stenosing cerebral vessel is no longer accompanied by ongoing sickling and endothelial injury.\n\nThis is PRIMARY prevention: she is entirely asymptomatic and the screening study is what identifies her. Transcranial Doppler screening is performed annually from age 2 to 16 for that reason.\n\nWhat it commits her to also matters: transfusion every 3 to 4 weeks, iron overload requiring chelation, alloimmunization risk, and venous access problems. Hydroxyurea is not an adequate substitute at the point of an abnormal velocity, though it is appropriate to continue and is used in some children after a period of transfusion.",
  {"1": "Aspirin prevents platelet-mediated arterial thrombosis in atherosclerotic disease. The cerebral vasculopathy of sickle cell disease is driven by sickling, endothelial injury and intimal proliferation, and antiplatelet therapy has not been shown to prevent these strokes.",
   "2": "Warfarin prevents thromboembolism from atrial fibrillation or venous thrombosis, and would be the answer for a cardioembolic source. It does nothing about polymerization, and adds bleeding risk to a child who does not have a thrombotic occlusion of the type it prevents.",
   "3": "Endarterectomy treats atherosclerotic stenosis at the carotid bifurcation in adults. Her abnormality is in the intracranial middle cerebral artery and is caused by a hemoglobinopathy, not by plaque; there is nothing for a surgeon to remove.",
   "4": "Splenectomy is reserved for recurrent splenic sequestration or massive splenomegaly. By 8 years of age most children with sickle cell disease have already autoinfarcted the spleen, and removing it has no effect on cerebral blood flow."},
  "An ultrasound found blood racing through an artery in her brain, which warns that a stroke is coming. Regular transfusions swap in enough normal hemoglobin to dilute the sickle kind, and that has been shown to prevent those strokes.",
  exim="fig_electrophoresis",
  excap="Electrophoresis quantifies the hemoglobin fractions — the measurement used to confirm that transfusion has driven hemoglobin S below the 30% target.")

# ── 14. The asplenic smear (§10 + §11) ────────────────────────────────────────
q("A 20-year-old man with sickle cell disease comes to the office to establish care after moving to the area. He has had three painful episodes requiring admission in the past 2 years and takes hydroxyurea and folic acid. He has never undergone abdominal surgery. His temperature is 37.0°C (98.6°F), pulse is 84/min, and blood pressure is 118/70 mm Hg. Physical examination shows scleral icterus; the abdomen is soft and the spleen cannot be palpated. Ultrasonography of the abdomen shows a small, densely calcified spleen measuring 3 cm.\n\nLaboratory studies show:\nHemoglobin 8.0 g/dL (N=13.5–17.5 g/dL)\nHematocrit 24% (N=41%–53%)\nReticulocyte count 9.4% (N=0.5%–1.5%)\nLeukocyte count 11,200/mm3 (N=4500–11,000/mm3)\nPlatelet count 468,000/mm3 (N=150,000–400,000/mm3)\n\nWhich of the following findings on the peripheral blood smear is most likely in this patient?",
  ["A. Basophilic stippling",
   "B. Bite cells",
   "C. Howell-Jolly bodies",
   "D. Hypersegmented neutrophils",
   "E. Rouleaux formation"],
  2,
  "Howell-Jolly bodies are small, dense, round remnants of nuclear DNA left in mature erythrocytes. A working spleen pits them out as cells pass through the splenic cords, so their presence means the spleen is absent or no longer functioning.\n\nHere the spleen is present but dead. Repeated sickling and infarction from early childhood produces AUTOSPLENECTOMY — a small, fibrotic, calcified organ, exactly as the ultrasound describes. His thrombocytosis and mild leukocytosis are part of the same picture, since the spleen normally sequesters a fraction of both.\n\nThe reason to recognize it is not the smear but what follows from it. Functional asplenia means he cannot clear encapsulated organisms — Streptococcus pneumoniae, Neisseria meningitidis, Haemophilus influenzae type b — so fever in this patient is an emergency requiring empiric parenteral antibiotics, and his pneumococcal and meningococcal vaccination must be current. The smear finding is the quiet clue; the vulnerability is the point.\n\nHis smear would also show sickled forms and target cells, but those are expected in anyone with the disease and say nothing about the spleen.",
  {"0": "Basophilic stippling — fine blue cytoplasmic granules of residual ribosomal RNA — points to lead poisoning or a thalassemia, and would be the answer with an exposure history and abdominal pain or with microcytosis and a raised hemoglobin A2.",
   "1": "Bite cells appear when a splenic macrophage removes a Heinz body, which requires a functioning spleen and an oxidant insult in a G6PD-deficient cell. Both conditions are absent: he has no oxidant exposure, and the organ that takes the bite has infarcted.",
   "3": "Neutrophils with five or more lobes indicate B12 or folate deficiency. He takes folic acid precisely because chronic hemolysis consumes it, and deficiency would produce a raised mean corpuscular volume with a LOW reticulocyte count rather than the 9.4% here.",
   "4": "Rouleaux — erythrocytes stacked like coins — reflect a paraprotein coating the cells, as in multiple myeloma or Waldenström macroglobulinemia. It would be the answer with a monoclonal band, bone pain, renal impairment or hypercalcemia, none of which he has."},
  "Years of sickling have scarred his spleen into a small lump of calcium, so it no longer cleans the blood. Leftover bits of DNA that the spleen would normally pluck out of red cells stay behind and show up on the slide.",
  exim="fig_howell_jolly",
  excap="Howell-Jolly bodies (arrows): dense round nuclear remnants within circulating erythrocytes, the smear signature of a missing or non-functioning spleen.")

# ── 15. The hemolysis arm — nitric oxide (§10 + §8) ───────────────────────────
q("A 34-year-old woman with sickle cell disease comes to the office because of 6 months of increasing shortness of breath on exertion and a painful ulcer above her left medial malleolus that has not healed in 4 months. She has had few painful crises in recent years. She takes hydroxyurea and folic acid. Her temperature is 37.0°C (98.6°F), pulse is 92/min, respirations are 18/min, and blood pressure is 112/70 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 95%. Physical examination shows scleral icterus, a loud pulmonic component of the second heart sound, and a 3-cm shallow ulcer with a clean base above the left medial malleolus. The lungs are clear.\n\nLaboratory studies show:\nHemoglobin 8.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 25% (N=36%–46%)\nReticulocyte count 12.8% (N=0.5%–1.5%)\nLactate dehydrogenase 620 U/L (N=45–200 U/L)\nHaptoglobin <10 mg/dL (N=30–200 mg/dL)\nTotal bilirubin 3.4 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.3 mg/dL (N=0.0–0.3 mg/dL)\n\nEchocardiography shows a tricuspid regurgitant jet velocity of 3.4 m/s (N=less than 2.5 m/s) with normal left ventricular function. CT angiography of the chest shows no pulmonary embolism and no parenchymal disease. Which of the following best explains this patient's pulmonary hypertension and leg ulceration?",
  ["A. Chronic deposition of iron within the pulmonary vasculature",
   "B. Depletion of nitric oxide by cell-free plasma hemoglobin",
   "C. Deposition of immune complexes within small vessels",
   "D. Increased blood viscosity from a chronically raised hematocrit",
   "E. Thromboembolic obstruction of the pulmonary arteries"],
  1,
  "Sickle cell disease has three downstream arms, and this patient is showing the third. Vaso-occlusion produces pain and infarction; vasculopathy produces endothelial dysfunction; and HEMOLYSIS produces a distinct set of complications through nitric oxide.\n\nThe chain: cells are torn apart under arterial pressure → hemoglobin is released free into plasma → cell-free hemoglobin avidly scavenges nitric oxide, and arginase released from the same lysed cells depletes the substrate for making more → nitric oxide, the principal endothelial vasodilator, is consumed → sustained vasoconstriction, endothelial dysfunction and smooth muscle proliferation. The clinical results are pulmonary hypertension, chronic leg ulceration, priapism and cerebrovascular disease.\n\nHer laboratory pattern is the hemolytic phenotype in its pure form: lactate dehydrogenase 620 U/L, an undetectable haptoglobin, unconjugated hyperbilirubinemia, and a reticulocyte count of 12.8%. The intensity of hemolysis, rather than the frequency of pain crises, is what tracks these particular complications — which is why she has few crises and severe vasculopathy.\n\nPulmonary hypertension in sickle cell disease carries a markedly increased mortality, and a raised tricuspid regurgitant jet velocity warrants right heart catheterization to confirm it.",
  {"0": "Iron does accumulate in chronically transfused patients and damages the heart, liver and endocrine organs — but as parenchymal deposition producing cardiomyopathy, not as isolated pulmonary arterial hypertension, and it would not cause a leg ulcer.",
   "2": "Immune complex deposition causes vasculitis or glomerulonephritis, and would be the answer with palpable purpura, an active urinary sediment, arthritis, or a positive serology. Her ulcer has a clean base and there is no evidence of an immune-mediated process.",
   "3": "Hyperviscosity from a high hematocrit is the mechanism in polycythemia vera, and it is the reason transfusion in sickle cell disease is done cautiously. Her hematocrit is 25%, so viscosity is not raised — indeed one of the hazards of over-transfusing these patients is creating the problem this option describes.",
   "4": "Chronic thromboembolic disease is a genuine cause of pulmonary hypertension, and these patients are hypercoagulable — which is why CT angiography was obtained. It shows no embolism, and it would not explain a chronic medial malleolar ulcer."},
  "When her red cells burst, hemoglobin spills into the blood and mops up the chemical her vessels use to relax. Her blood vessels stay clamped down, which strains the lungs and starves the skin over her ankle so an ulcer will not heal.",
  exim="fig_sickle_smear",
  excap="The engine of the process: rigid crescent-shaped erythrocytes that are sheared apart under arterial pressure, releasing hemoglobin into plasma.")
