# Jeevs Edition — Batch 11: INFECTION
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §18 s17-sepsis            — scores, labs, PAMPs/DAMPs, source-organism map   (LO 1, 75)
#   §19 s18-hiv-micro         — structural genes, replication cycle, drug map    (LO 14, 24)
#   §20 s19-hiv-clinical      — testing algorithm, CD4 tiers, PJP, IRIS          (LO 77)
#   §21 s19b-vector-infections— plague, Bartonella, Babesia, Plasmodium          (LO 5, 22, 23)
#   §22 s19c-vhf              — dengue, hantavirus HFRS, CCHF, Lassa             (LO 13)
# Options alphabetised; "correct" is the 0-based index AFTER alphabetisation.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ══════════════════════════ §18 · SEPSIS ══════════════════════════

# ── 1. The bidirectional criteria (§18) ──────────────────────────────────────
q("An 81-year-old woman is brought to the emergency department from a nursing facility because of confusion for 6 hours. She has not complained of pain and has not had a documented fever. She has type 2 diabetes mellitus and was treated for a urinary tract infection 3 weeks ago. Her temperature is 35.4°C (95.7°F), pulse is 104/min, respirations are 24/min, and blood pressure is 96/58 mm Hg. She is oriented to person only. The lungs are clear and the abdomen is soft; there is mild suprapubic tenderness.\n\nLaboratory studies show:\nLeukocyte count 3,100/mm3 (N=4,500–11,000/mm3)\nSegmented neutrophils 62% (N=54%–62%)\nBand forms 15% (N=0%–5%)\nPlatelet count 96,000/mm3 (N=150,000–400,000/mm3)\nSerum creatinine 1.8 mg/dL (N=0.6–1.2 mg/dL)\nSerum lactate 3.6 mmol/L (N=0.5–2.2 mmol/L)\n\nHer creatinine was 1.1 mg/dL 3 weeks ago. Urinalysis shows 50 leukocytes per high-power field. Which of the following is the most appropriate next step in management?",
  ["A. Administer intravenous fluids and begin bactericidal antimicrobial therapy now",
   "B. Begin bacteriostatic antimicrobial therapy once culture results are available",
   "C. Defer antimicrobial therapy because she is afebrile and not leukocytotic",
   "D. Obtain a chest radiograph and reassess her in 6 hours",
   "E. Withhold fluids and begin a vasopressor for the hypotension"],
  0,
  "This is sepsis, and the trap is that all three of her 'reassuring' numbers are actually abnormal in the other direction.\n\nThe SIRS criteria are BIDIRECTIONAL. Temperature qualifies if it is high OR low — her 35.4°C is hypothermia, not normality. The leukocyte criterion is satisfied by leukocytosis above 12,000/µL, leukopenia below 4,000/µL, OR a normal count with more than 10% immature forms — she has two of those at once, a count of 3,100/mm3 with 15% bands. A septic patient who is hypothermic and leukopenic is easy to misread as 'not infected,' and that misreading is the favourite exam trap in this section.\n\nShe also meets all three qSOFA criteria: respirations 24/min (≥22), systolic pressure 96 mm Hg (≤100 — note the threshold is 100, not 90, precisely so that patients are caught before frank hypotension), and altered mentation. Add organ dysfunction — creatinine risen by more than 0.5 mg/dL, platelets under 100,000/mm3, lactate 3.6 mmol/L — and infection plus organ dysfunction is the definition of sepsis.\n\nSepsis is TIME-DEPENDENT organ dysfunction, and that single word is why the bundle is delivered together and early rather than sequentially as results return: bactericidal antimicrobials (the outline specifies bactericidal, not merely bacteriostatic), intravenous fluids, a lactate measurement, assessment of tissue perfusion, vasopressors if fluids are insufficient, plus oxygen and source control.",
  {"1": "Waiting for cultures costs hours in a time-dependent illness, and cultures are negative in 30% to 50% of sepsis cases, so the wait may never end. The outline also specifies BACTERICIDAL therapy; a bacteriostatic agent relies on a host response that is exactly what has failed here.",
   "2": "This is the trap the vignette is built around. Hypothermia and leukopenia do not argue against infection — both directions satisfy the criteria, and a normal-looking number in sepsis can still be an abnormal response.",
   "3": "Imaging and observation are what you do when the diagnosis is uncertain and the patient is stable. She has hypoperfusion with a lactate of 3.6 mmol/L and a clear urinary source; 6 hours of observation is 6 hours of untreated organ dysfunction.",
   "4": "Fluids come first — the peripheral vasodilation of sepsis is a volume-distribution problem, and vasopressors are added when fluids alone cannot maintain perfusion pressure. Squeezing an underfilled circulation raises the blood pressure number while worsening tissue perfusion."},
  "Her body is fighting an infection so badly that her temperature has gone DOWN instead of up and her white cells have been used up instead of rising. Those look like normal results, but they are the danger signs. She needs fluids and antibiotics right now.",
  exim="fig_slide_sepsis_labs",
  excap="Lecture slide: the laboratory features of sepsis. Note that the white cell and temperature criteria are satisfied in both directions.")

# ── 2. The one cause-specific marker (§18) ───────────────────────────────────
q("A 64-year-old man is admitted to the intensive care unit with fever, hypotension, and acute kidney injury 2 days after a fall at home. He has chronic obstructive pulmonary disease. His temperature is 38.9°C (102.0°F), pulse is 118/min, respirations are 26/min, and blood pressure is 88/52 mm Hg. Crackles are heard at the right base. Blood cultures and a sputum culture have been sent and are pending.\n\nLaboratory studies show:\nLeukocyte count 16,400/mm3 (N=4,500–11,000/mm3)\nPlatelet count 112,000/mm3 (N=150,000–400,000/mm3)\nSerum creatinine 2.1 mg/dL (N=0.6–1.2 mg/dL)\nTotal bilirubin 2.4 mg/dL (N=0.2–1.2 mg/dL)\nSerum lactate 4.1 mmol/L (N=0.5–2.2 mmol/L)\nC-reactive protein 18 mg/dL (N=<1.0 mg/dL)\nProcalcitonin 8.4 ng/mL (N=<0.5 ng/mL)\n\nWhich of the following laboratory findings most specifically indicates a bacterial cause of this patient's illness?",
  ["A. C-reactive protein concentration",
   "B. Leukocyte count",
   "C. Platelet count",
   "D. Procalcitonin concentration",
   "E. Serum lactate concentration"],
  3,
  "Procalcitonin is the only entry on the sepsis laboratory panel that points at a CAUSE. Every other row on that panel measures severity — how much organ dysfunction there is — and says nothing about what started it.\n\nThat division is the whole point of the table:\n• Leukocyte count, platelet count, creatinine, bilirubin, PaO₂/FiO₂, urine output, glucose — organ dysfunction and stress response.\n• Lactate — tissue hypoperfusion, and the reason lactate sits in the treatment bundle rather than the diagnostic workup.\n• C-reactive protein — non-specific inflammation. It rises in infection, trauma, surgery, autoimmune disease and malignancy alike.\n• Procalcitonin — indicative of a BACTERIAL etiology.\n\nThis matters because no single organism defines sepsis, bacterial cultures are negative in 30% to 50% of cases, and no assessment or diagnostic criterion has sufficient sensitivity and specificity — which is why five competing scoring systems exist rather than one test. Procalcitonin does not replace cultures, but among the numbers listed it is the one that speaks to etiology.",
  {"0": "C-reactive protein is elevated here at 18 mg/dL, and it is genuinely part of the sepsis panel — but it is explicitly a marker of non-specific inflammation. It rises after surgery, in trauma, in autoimmune flares and in malignancy, so it cannot separate a bacterial cause from any of those.",
   "1": "The leukocyte count measures the host response, not its trigger, and its criterion is satisfied in both directions plus by a left shift with a normal total. Viral, fungal and non-infectious critical illness all move it.",
   "2": "Thrombocytopenia below 100,000/mm3 reflects consumption and coagulopathy — a severity marker, and one of the organ-dysfunction rows on the panel. It occurs in viral sepsis, in thrombotic microangiopathy and in disseminated intravascular coagulation of any cause.",
   "4": "Lactate reflects tissue hypoperfusion, and it is the marker of the cellular and metabolic abnormality written into the definition of septic shock. That makes it central to management and prognosis, and useless for identifying the class of organism."},
  "Most of his blood tests say how sick he is. Only one of them hints at what is making him sick — and that one is raised when the cause is bacteria.",
  exim="fig_slide_sepsis_labs",
  excap="Lecture slide: the sepsis laboratory panel. Read down the right-hand column — every row reports severity except procalcitonin.")

# ── 3. PAMPs versus DAMPs (§18) ──────────────────────────────────────────────
q("A 29-year-old woman is admitted with 4 days of fever, myalgia, and cough that have progressed to dyspnea and confusion. A nasopharyngeal swab is positive for influenza A. Her temperature is 39.2°C (102.6°F), pulse is 122/min, respirations are 30/min, and blood pressure is 84/50 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 88%. Chest radiograph shows bilateral interstitial infiltrates. Two sets of blood cultures and a sputum culture show no growth at 48 hours, and procalcitonin is 0.2 ng/mL (N=<0.5 ng/mL).\n\nLaboratory studies show:\nLeukocyte count 3,400/mm3 (N=4,500–11,000/mm3)\nPlatelet count 84,000/mm3 (N=150,000–400,000/mm3)\nSerum creatinine 2.3 mg/dL (N=0.6–1.2 mg/dL)\nSerum lactate 4.4 mmol/L (N=0.5–2.2 mmol/L)\n\nWhich of the following best describes the molecular trigger that initiated this patient's inflammatory cascade?",
  ["A. Damage-associated molecular patterns released from virus-injured host tissue",
   "B. Lipopolysaccharide shed from gram-negative bacterial cell walls",
   "C. Lipoteichoic acid and peptidoglycan from gram-positive cell walls",
   "D. Polysaccharides — beta-glucans, mannans and chitin — from fungal cell walls",
   "E. Superantigens such as toxic shock syndrome toxin"],
  0,
  "Sepsis is defined by the HOST response, not by the organism, so a virus can produce it — and viral causes are explicitly noted as often underdiagnosed. But the trigger is different, and that difference is the examinable point.\n\nPAMPs are Pathogen-Associated Molecular Patterns: molecular signatures carried by the organism itself. DAMPs are Damage-Associated Molecular Patterns, released from the host's OWN damaged tissue. Viral infection triggers sepsis through DAMPs — it is the exception in the list, and therefore the likely question.\n\nThe pairings to hold:\n• Gram-negative → lipopolysaccharide (the most prominent trigger overall) — a PAMP\n• Gram-positive → lipoteichoic acid and peptidoglycan — PAMPs\n• Other bacterial → superantigens (TSST-1 and 2, streptococcal pyrogenic exotoxin) — PAMPs\n• Fungal → beta-glucans, mannans, chitin, all polysaccharides — PAMPs\n• Viral → DAMPs, from virus-damaged tissue\n• Parasitic → both\n\nEverything downstream is identical regardless of trigger: pro-inflammatory cytokines including IL-1 and IL-6, endothelial dysfunction, ischemic tissue injury, sequential organ failure, and the cell death pathways — necrosis, necroptosis, pyroptosis, autophagy. Her negative cultures and normal procalcitonin fit: cultures are negative in 30% to 50% of sepsis cases, and procalcitonin points at bacteria, which is not what she has.",
  {"1": "Lipopolysaccharide is the single most prominent sepsis trigger overall and the classic gram-negative PAMP — E. coli, Klebsiella, Pseudomonas, Enterobacter. Her blood and sputum cultures are sterile and her procalcitonin is normal, which argues against a bacterial process.",
   "2": "Lipoteichoic acid and peptidoglycan are the gram-positive PAMPs, and gram-positives — S. aureus, Enterococcus, S. pneumoniae, S. pyogenes — are the most commonly IDENTIFIED sepsis organisms. Influenza is documented here and nothing grew.",
   "3": "Fungal cell wall polysaccharides are the trigger in Candida and Aspergillus sepsis, which is increasing in the immunocompromised; Candida accounts for about 80% of fungal cases and Aspergillus about 10%. She has no immunocompromising condition and a documented viral pathogen.",
   "4": "Superantigens — toxic shock syndrome toxins 1 and 2 and streptococcal pyrogenic exotoxin — cause a spectacular cytokine surge by cross-linking T-cell receptors with MHC class II outside the antigen groove. They are bacterial products, and there is no staphylococcal or streptococcal infection here."},
  "Bacteria set off the alarm with pieces of themselves. A virus sets it off differently — it wrecks your own cells, and the debris from your own tissue is what the immune system reacts to.",
  exim="fig_slide_sepsis_cascade",
  excap="Lecture slide: the sepsis cascade. Whatever the trigger, every arm converges on endothelial damage, tissue injury and organ dysfunction.")

# ── 4. Source predicts organism (§18) ────────────────────────────────────────
q("A 58-year-old man develops fever and hypotension on the second postoperative day after emergency laparotomy for a perforated sigmoid diverticulum with fecal peritonitis. His temperature is 39.1°C (102.4°F), pulse is 126/min, respirations are 28/min, and blood pressure is 82/48 mm Hg. The abdomen is distended and diffusely tender. A drain placed at operation returns cloudy fluid.\n\nLaboratory studies show:\nLeukocyte count 21,000/mm3 (N=4,500–11,000/mm3)\nBand forms 18% (N=0%–5%)\nPlatelet count 88,000/mm3 (N=150,000–400,000/mm3)\nSerum creatinine 2.4 mg/dL (N=0.6–1.2 mg/dL)\nSerum lactate 5.2 mmol/L (N=0.5–2.2 mmol/L)\n\nBlood cultures are growing gram-negative organisms in both aerobic and anaerobic bottles. In addition to Escherichia coli, which of the following organisms is most likely to be recovered from this patient?",
  ["A. Bacteroides fragilis",
   "B. Legionella pneumophila",
   "C. Listeria monocytogenes",
   "D. Staphylococcus epidermidis",
   "E. Streptococcus pyogenes"],
  0,
  "The site of the initial infection predicts the organism list, and that mapping is the examinable content. For an ABDOMINAL source the named organisms are Escherichia coli, BACTEROIDES FRAGILIS, Candida, and mixed anaerobes. His anaerobic bottle turning positive alongside the aerobic one is the clue built into the vignette.\n\nThe rest of the map, worth reciting:\n• Respiratory — S. pneumoniae, Haemophilus influenzae b, E. coli and other aerobic gram-negative bacilli, Pseudomonas aeruginosa, Klebsiella pneumoniae (the alcohol-use association), Legionella pneumophila\n• Urinary — E. coli, Klebsiella, Enterobacter, Enterococcus, Staphylococcus epidermidis, Proteus\n• Abdominal — E. coli, Bacteroides fragilis, Candida, mixed anaerobes\n• Skin and soft tissue — S. pyogenes, S. aureus, aerobic gram-negative bacilli, Clostridium and other anaerobes, Pseudomonas aeruginosa\n• Meningitis — S. pneumoniae, N. meningitidis, E. coli, Listeria monocytogenes\n\nTwo frequencies belong with that list: sources in descending order are respiratory > urinary > abdominal > head > other, and 20% of sepsis cases are POLYMICROBIAL — abdominal sources being a major reason why. That is also why source control, surgical drainage or removal of the infected focus, is one of the treatment elements rather than an afterthought.",
  {"1": "Legionella pneumophila belongs to the respiratory list, and respiratory is the most common sepsis source overall — which is why community-acquired pneumonia appears among the risk factors. This man's source is an operative abdomen with fecal soiling.",
   "2": "Listeria monocytogenes belongs to the meningitis list alongside S. pneumoniae, N. meningitidis and E. coli, and is a particular concern at the extremes of age and in pregnancy. There is nothing here to suggest a central nervous system source.",
   "3": "Staphylococcus epidermidis appears on the urinary list and is also the classic indwelling-device and line contaminant. It is a gram-positive coccus, which does not fit gram-negative growth in both bottles.",
   "4": "Streptococcus pyogenes heads the skin and soft tissue list, with S. aureus, aerobic gram-negative bacilli, Clostridium and Pseudomonas. It is also a superantigen producer and a cause of toxic shock — but this is a gram-positive organism arising from a source he does not have."},
  "Where an infection starts tells you which bugs to expect. His came from a hole in the large bowel, and the large bowel is full of oxygen-hating bacteria — so expect one of those alongside the usual gut organism.")

# ══════════════════════════ §19 · HIV MICROBIOLOGY ══════════════════════════

# ── 5. p24 and the gag gene (§19) ────────────────────────────────────────────
q("A 26-year-old man comes to the clinic 3 weeks after a condomless sexual encounter because of 5 days of fever, sore throat, and a diffuse rash. His temperature is 38.4°C (101.1°F), pulse is 92/min, and blood pressure is 118/74 mm Hg. Physical examination shows non-exudative pharyngitis, a macular rash over the trunk, tender cervical lymphadenopathy, and a spleen tip palpable below the left costal margin. A heterophile antibody test is negative. A combination HIV-1/2 immunoassay is reactive; the antibody component of the assay is nonreactive and the antigen component is reactive.\n\nThe viral protein detected by the antigen component of this assay is encoded by which of the following genes?",
  ["A. env",
   "B. gag",
   "C. nef",
   "D. pol",
   "E. tat"],
  1,
  "The antigen detected by a 4th-generation combination assay is p24, and p24 is a gag product — the capsid core antigen, cleaved from the p55 precursor by VIRAL protease. It is described as the protein EASIEST TO DETECT IN SERA, and it is detectable before antibodies are, which is exactly what this vignette shows: reactive antigen, nonreactive antibody, 3 weeks after exposure.\n\nThat timing is the reason combination testing exists. The three periods are the eclipse period (day 0 to about day 10, when nothing is detectable by any test), acute infection (about day 10 to 50, when HIV RNA rises first, then p24 appears and peaks around day 30, then antibodies begin), and established infection (beyond about day 50, when antibodies persist, RNA settles at the viral set point, and p24 falls away).\n\nThe gag products are worth knowing as a set: p24 the capsid, which also carries the pre-integration complex into the host chromosome; p17 the matrix protein lining the inner envelope; and p6, p7 and p9, the nucleocapsid proteins that bind the viral RNA genome.\n\nHis clinical picture is the acute retroviral syndrome — the diagnosis that gets missed, because it is most often confused with mononucleosis. The discriminator to hold is that acute retroviral syndrome gives NON-exudative pharyngitis, and transmission risk is at its highest here because the viral RNA is very high and the person does not know their status.",
  {"0": "The env gene encodes a 160 kDa precursor cleaved by HOST protease into gp120, the binding protein that engages CD4 and a chemokine co-receptor, and gp41, the fusion protein. These are surface glycoproteins targeted by fostemsavir, maraviroc and enfuvirtide — not the antigen measured in serum by a screening assay.",
   "2": "The nef gene is a regulatory gene with negative regulatory function; it protects HIV-infected cells from killing by T lymphocytes, which is why it is of interest for drug development. It is not a structural gene and is not a diagnostic target.",
   "3": "The pol gene encodes the three enzymes — reverse transcriptase, integrase and protease — which sit inside the virion and are the targets of most of the drug classes. They are not the antigen used for serum detection.",
   "4": "The tat gene encodes the activator of transcription, which also inhibits T-cell proliferation. Like rev, vif, vpr and vpu it is a regulatory or accessory gene, not a structural protein detectable in serum."},
  "The test looks for a piece of the virus's protein shell, which shows up in the blood before the body has had time to make antibodies. That shell protein comes from one particular viral gene.",
  exim="fig_slide_hiv_virion",
  excap="Lecture slide: the HIV virion — two glycoprotein spikes outside, the capsid and two copies of single-stranded RNA inside.")

# ── 6. The NNRTI genetic barrier (§19) ───────────────────────────────────────
q("A 38-year-old man with HIV infection has been taking tenofovir, emtricitabine, and efavirenz for 2 years. His HIV RNA was undetectable for 18 months but is now 24,000 copies/mL, and his CD4 count has fallen from 540 to 380 cells/µL. He reports several months of intermittent missed doses because of vivid dreams. Genotype testing shows a SINGLE point mutation in a conserved domain of reverse transcriptase. Phenotypic testing shows that his virus is now resistant to every drug in the class to which efavirenz belongs, while remaining susceptible to tenofovir and emtricitabine.\n\nWhich of the following best explains why one mutation abolishes the activity of every member of that class?",
  ["A. All members are competitive inhibitors at the active site of reverse transcriptase",
   "B. All members are metabolized by the same cytochrome P450 isoenzyme",
   "C. All members bind the same allosteric pocket on reverse transcriptase",
   "D. All members require intracellular phosphorylation before becoming active",
   "E. All members terminate the growing DNA chain after incorporation"],
  2,
  "The non-nucleoside reverse transcriptase inhibitors — efavirenz, doravirine — are NON-COMPETITIVE, ALLOSTERIC inhibitors. They bind a pocket away from the active site and force a conformational change in reverse transcriptase so the enzyme cannot make viral DNA. Because every member of the class binds that same pocket, a single point mutation in that conserved domain inactivates ALL of them at once. This is the lowest genetic barrier in antiretroviral therapy.\n\nThe contrast is the point of the objective. The NRTIs — zidovudine, a thymidine analogue, and tenofovir, an adenosine analogue — bind COMPETITIVELY at the active site as nucleoside analogues and cause chain termination. Point mutations REDUCE their binding affinity rather than abolishing it, so NRTI resistance generally requires ACCUMULATED mutations. That is exactly what his genotype shows: one mutation, class-wide loss of the NNRTI, both NRTIs still working.\n\nThe spectrum of genetic barriers, worth holding as three points:\n• NNRTIs — lowest. One mutation, the whole class gone.\n• Protease inhibitors — high. Resistance is uncommon unless the patient was previously treated with a protease inhibitor.\n• Lenacapavir, the capsid inhibitor — the extreme in the other direction, where one capsid mutation confers a greater than 80,000-fold shift.\n\nUpstream of all of it is one property: reverse transcriptase has a HIGH ERROR RATE, which generates the variant pool that drug pressure then selects from. His missed doses supplied the selection pressure.",
  {"0": "Competitive inhibition at the active site is how the NRTIs work, as nucleoside analogues that cause chain termination. Their resistance mutations reduce binding affinity rather than eliminating it, which is precisely why they generally require accumulated mutations and why his tenofovir and emtricitabine still work.",
   "1": "Shared cytochrome P450 metabolism produces drug interactions, not resistance. It is the basis of the pharmacokinetic ENHANCERS — ritonavir and cobicistat — which inhibit CYP3A4 to raise antiretroviral levels, and which are not antiretrovirals themselves.",
   "3": "Requiring intracellular phosphorylation to the active triphosphate is an NRTI property, not an NNRTI one — NNRTIs are active as given. It also would not explain class-wide collapse from one mutation in reverse transcriptase.",
   "4": "Chain termination after incorporation into the growing DNA strand is the NRTI mechanism. NNRTIs never enter the DNA chain; they denature the enzyme by binding alongside it."},
  "Every drug in this family grabs the same one handle on the enzyme. Change the shape of that single handle and all of them lose their grip at once.",
  exim="fig_slide_nnrti",
  excap="Lecture slide: the NNRTI mechanism — the inhibitor binds reverse transcriptase and distorts it so the enzyme cannot make viral DNA.")

# ── 7. Tropism and the wrong entry inhibitor (§19) ───────────────────────────
q("A 47-year-old woman with a 20-year history of HIV infection and multiple previous regimens has a viral load of 62,000 copies/mL and a CD4 count of 90 cells/µL. Genotype testing shows extensive resistance to the nucleoside and non-nucleoside reverse transcriptase inhibitors and to the integrase strand transfer inhibitors, with preserved susceptibility to darunavir. A co-receptor tropism assay reports CXCR4-using (X4-tropic) virus. A new salvage regimen is being assembled.\n\nWhich of the following agents is least likely to have antiviral activity in this patient?",
  ["A. Darunavir",
   "B. Enfuvirtide",
   "C. Fostemsavir",
   "D. Ibalizumab",
   "E. Maraviroc"],
  4,
  "Maraviroc is a CCR5 ANTAGONIST. It blocks one of the two chemokine co-receptors that gp120 must engage alongside CD4 for entry. Her virus uses CXCR4 instead, so the receptor maraviroc blocks is not the one her virus is using — the drug has nothing to do. This is why a tropism assay is performed BEFORE prescribing maraviroc and never after, and it is the reason the tropism assay exists at all.\n\nThe rest of the entry blockers are agnostic to tropism because they act at other points:\n• Fostemsavir — an attachment inhibitor binding gp120 itself, before any co-receptor is engaged.\n• Ibalizumab — a post-attachment entry inhibitor, a monoclonal antibody that blocks the CD4 receptor, so virus can attach but cannot enter.\n• Enfuvirtide — a fusion inhibitor binding gp41, the fusion protein exposed after the conformational change, which happens whichever co-receptor is used.\n\nAnd darunavir is a protease inhibitor acting at maturation, with a notably HIGH genetic barrier: resistance is uncommon unless the patient has previously been treated with a protease inhibitor. Her genotype confirms she remains susceptible.\n\nStep 1 of the cycle, for reference: gp120 binds CD4 plus CCR5 or CXCR4, the conformational change exposes gp41, and gp41 fuses with the membrane.",
  {"0": "Darunavir is a protease inhibitor that prevents cleavage of the gag and gag/pol precursors, so virions are released immature and non-infectious. Her genotype specifically preserves susceptibility to it, and the class has a high genetic barrier.",
   "1": "Enfuvirtide binds gp41, the fusion protein, blocking the membrane fusion step. Fusion occurs after either co-receptor is engaged, so tropism is irrelevant to it; resistance requires an amino acid substitution in gp41 itself.",
   "2": "Fostemsavir is an attachment inhibitor that binds gp120 and prevents it from engaging CD4 at all — upstream of the co-receptor choice. Its resistance mechanism is a high rate of gp120 amino acid substitutions reducing binding efficiency.",
   "3": "Ibalizumab is a post-attachment entry inhibitor, a monoclonal antibody directed at the CD4 receptor. The virus can attach but cannot complete entry, and again this is independent of which chemokine co-receptor the strain uses."},
  "One of these drugs works by blocking a particular doorway into the cell. Her virus uses the other doorway, so blocking that one accomplishes nothing.",
  exim="fig_slide_hiv_cycle_drugs",
  excap="Lecture slide: the HIV life cycle with each drug class mapped to the step it blocks.")

# ══════════════════════════ §20 · HIV CLINICAL ══════════════════════════

# ── 8. Testing inside the window (§20) ───────────────────────────────────────
q("A 23-year-old man comes to the student health clinic because of 4 days of fever, fatigue, sore throat, and a rash. He reports a condomless sexual encounter with a new partner 12 days ago. His temperature is 38.3°C (100.9°F), pulse is 96/min, and blood pressure is 112/68 mm Hg. Physical examination shows non-exudative pharyngitis without tonsillar exudate, a faint macular rash on the trunk, and tender posterior cervical lymphadenopathy. A rapid streptococcal antigen test and a heterophile antibody test are both negative.\n\nLaboratory studies show:\nLeukocyte count 4,200/mm3 (N=4,500–11,000/mm3)\nAtypical lymphocytes 9% (N=0%–5%)\nPlatelet count 138,000/mm3 (N=150,000–400,000/mm3)\nAspartate aminotransferase 62 U/L (N=10–40 U/L)\n\nAn HIV-1/2 antigen/antibody combination immunoassay is nonreactive. Which of the following is the most appropriate next step in management?",
  ["A. Antibody differentiation immunoassay for HIV-1 and HIV-2",
   "B. Nucleic acid test for HIV-1 RNA",
   "C. Repeat the antigen/antibody immunoassay in 3 months",
   "D. Serum p24 antigen assay",
   "E. Western blot for HIV-1"],
  1,
  "The CDC algorithm says a NON-REACTIVE combination immunoassay ends the workup — EXCEPT when acute infection is clinically suspected, in which case you go straight to an HIV-1 nucleic acid test. That exception exists because of the eclipse period and the window that follows it.\n\nHis presentation is the acute retroviral syndrome: more than 50% of newly infected people develop this transient symptomatic illness, and it is most often confused with mononucleosis. The pattern to keep on the differential in a teenager or 20-something is non-exudative pharyngitis plus rash plus splenomegaly plus atypical lymphocytosis, with the frequencies fever about 75%, fatigue about 68%, myalgia about 48%, rash about 48%, headache about 45%, pharyngitis about 40%. His heterophile test is negative, which removes the diagnosis he would otherwise be given.\n\nThe marker timeline explains the negative screen at day 12: HIV RNA rises FIRST, then p24 antigen appears and peaks around day 30, then antibodies begin. At 12 days he may be at or barely past the end of the eclipse period, when RNA is the only thing detectable.\n\nWhy the nucleic acid test is not simply used first for everyone: it costs roughly three times as much, it is far more complex for laboratories to run, and it carries a real false-positive potential, particularly in low-risk individuals. That is why it sits at tier 3 of the algorithm — and why clinical suspicion is what moves a patient straight to it.",
  {"0": "The antibody differentiation immunoassay is tier 2, performed as a REFLEX when the initial combination assay is REACTIVE, to resolve HIV-1 from HIV-2. His screen was nonreactive, and an antibody test is the wrong tool this early — antibodies are the last marker to appear.",
   "2": "Repeat testing in 3 months is the correct advice for an asymptomatic person with a remote low-risk exposure. Here the patient is symptomatic now, and this is the interval of maximal transmission risk — very high viral RNA in someone who does not know their status. Waiting 3 months is a public health failure as well as a clinical one.",
   "3": "A stand-alone p24 antigen assay adds nothing: the p24 antigen component is already built into the 4th-generation combination assay he has just had, and it was nonreactive. p24 also appears AFTER RNA and peaks around day 30.",
   "4": "The Western blot is obsolete and was replaced in 2014. It detects antibodies only, has a longer detection window, has inferior sensitivity, and cannot differentiate HIV-1 from HIV-2 — every property that makes it useless in suspected acute infection."},
  "He may have caught the virus less than two weeks ago. The usual test looks for the body's response, which has not started yet. The right move is a test that looks for the virus's own genetic material, which is the first thing to show up.",
  exim="fig_slide_hiv_markers",
  excap="Lecture slide: the temporal appearance of HIV markers — RNA first, then p24 antigen, then antibodies.")

# ── 9. PJP and the steroid threshold (§20) ───────────────────────────────────
q("A 34-year-old man with untreated HIV infection comes to the emergency department because of 3 weeks of progressive exertional dyspnea and a dry cough. His temperature is 38.6°C (101.5°F), pulse is 112/min, respirations are 28/min, and blood pressure is 118/70 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 86%, falling to 80% after walking. Chest auscultation is unremarkable. Oropharyngeal examination shows white plaques that scrape off with a tongue blade. A CT scan of the chest is shown.\n\nLaboratory studies show:\nCD4 lymphocyte count 62/µL (N=500–1,500/µL)\nLactate dehydrogenase 486 U/L (N=100–220 U/L)\nArterial oxygen partial pressure 56 mm Hg (N=80–100 mm Hg)\nAlveolar-arterial oxygen gradient 48 mm Hg (N=<15 mm Hg)\n1,3-beta-D-glucan 320 pg/mL (N=<60 pg/mL)\n\nWhich of the following is the most appropriate treatment?",
  ["A. Intravenous amphotericin B",
   "B. Intravenous trimethoprim-sulfamethoxazole alone",
   "C. Intravenous trimethoprim-sulfamethoxazole plus prednisone",
   "D. Oral atovaquone alone",
   "E. Oral fluconazole"],
  2,
  "This is Pneumocystis jirovecii pneumonia — CD4 62/µL, the triad of fever, non-productive cough and progressive dyspnea, a NORMAL chest examination in a profoundly hypoxemic patient (about half of patients examine normally), an elevated LDH, an elevated beta-D-glucan, ground-glass opacities with peripheral sparing, and the thrush that so often accompanies it.\n\nTrimethoprim-sulfamethoxazole is the preferred regimen — intravenous for severe disease, dosed by weight on the TRIMETHOPRIM component — and corticosteroids are ADDED in moderate to severe disease because they reduce respiratory failure and mortality. The two thresholds that trigger them are PaO₂ below 70 mm Hg or an A-a gradient of 35 mm Hg or more. He is at 56 mm Hg and 48 mm Hg, so he meets both. Prednisone for 21 days.\n\nWhy the antifungals on this list do nothing: Pneumocystis is classified as a fungus on RNA, cell wall and enzyme grounds, but it does not grow in fungal culture, and its cell wall contains CHOLESTEROL rather than ergosterol. Amphotericin B binds ergosterol and the azoles block ergosterol synthesis, so both miss a wall that does not use it. That is precisely why the treatment is an antibacterial folate-pathway drug.\n\nTwo timing points that get tested: expect WORSENING for the first 2 to 3 days after starting treatment, because killing the organism releases inflammatory material — this is NOT immune reconstitution inflammatory syndrome, it is far too soon. And start antiretroviral therapy within 2 weeks of beginning treatment.",
  {"0": "Amphotericin B binds ergosterol in the fungal membrane. Pneumocystis uses cholesterol instead, so the drug has no target — the classic 'it is a fungus but the antifungals do not work' point.",
   "1": "Trimethoprim-sulfamethoxazole is the correct drug, and this answer would be right in mild to moderate disease. It omits the corticosteroid, and he meets both severity thresholds — PaO₂ below 70 mm Hg and an A-a gradient of 35 mm Hg or more — where steroids reduce respiratory failure and death.",
   "3": "Atovaquone is an accepted alternative for MILD to moderate Pneumocystis pneumonia in a patient who cannot take trimethoprim-sulfamethoxazole. Oral therapy for a patient with an oxygen saturation of 86% and a PaO₂ of 56 mm Hg undertreats severe disease, and it also lacks the steroid.",
   "4": "Fluconazole blocks ergosterol synthesis. It would treat the oral and esophageal candidiasis he also has, but it has no activity against an organism whose cell wall contains cholesterol, and candidiasis is not what is making him hypoxemic."},
  "An infection is filling his lungs and his oxygen is dangerously low. The right antibiotic is not an antifungal, even though the bug is a fungus — and because he is this badly off, a steroid is added to stop his lungs reacting so violently as the bug dies.",
  image="fig_pjp_ct",
  imcap="High-resolution CT of the chest.",
  exim="fig_slide_cd4_oi",
  excap="Lecture slide: organisms to consider at each CD4 count, with the clinical clue that points to each.")

# ── 10. Paradoxical IRIS (§20) ───────────────────────────────────────────────
q("A 29-year-old woman with newly diagnosed AIDS is admitted with Pneumocystis jirovecii pneumonia and is treated with intravenous trimethoprim-sulfamethoxazole and prednisone. Her CD4 count on admission was 90/µL and her HIV RNA was 1.5 million copies/mL. She improved steadily after an initial 2 days of worsening, and antiretroviral therapy was started on hospital day 10. On day 21 she develops worsening hypoxemia and new bilateral pulmonary infiltrates and requires transfer to the intensive care unit. She has had no new fevers above 38.5°C, and blood and sputum cultures show no growth.\n\nLaboratory studies show:\nCD4 lymphocyte count 180/µL (N=500–1,500/µL)\nHIV RNA 12,000 copies/mL (N=undetectable)\nLeukocyte count 6,800/mm3 (N=4,500–11,000/mm3)\n\nWhich of the following best explains her deterioration?",
  ["A. Bacterial superinfection with hospital-acquired pneumonia",
   "B. Expected early worsening from release of inflammatory material as organisms are killed",
   "C. Immune reconstitution inflammatory syndrome",
   "D. Progression of Pneumocystis pneumonia from sulfonamide resistance",
   "E. Pulmonary Kaposi sarcoma"],
  2,
  "This is PARADOXICAL immune reconstitution inflammatory syndrome: the opportunistic infection was already known and being treated, antiretroviral therapy was started, and the patient then worsened. The tell-tale combination is a known and already-treated opportunistic infection, a SHORT interval between starting treatment for it and starting antiretroviral therapy, and a ROBUST virologic and immunologic response occurring alongside clinical deterioration.\n\nThe improving laboratory numbers are the clue that separate this from treatment failure: her HIV RNA has fallen from 1.5 million to 12,000 copies/mL and her CD4 count has risen from 90 to 180/µL. In true progression of the opportunistic infection, the virology would not be improving. The timing fits too — IRIS occurs in the first few months of antiretroviral therapy, median 48 days, in 10% to 20% of patients.\n\nThe other form is UNMASKING (ART-associated) IRIS, where the opportunistic infection was undiagnosed until therapy was started and the recovering immune system reveals it.\n\nThe management point is the one people get wrong: the answer is NOT to delay antiretroviral therapy. Delaying costs more than it saves. Anticipate IRIS, counsel the patient in advance that worsening may occur, and keep it on the differential when the patient deteriorates on day 10 instead of improving. The specific regimen chosen does not affect IRIS risk.",
  {"0": "Hospital-acquired pneumonia is a reasonable thought in any deteriorating inpatient, and it must be excluded. Her cultures are sterile, her leukocyte count is normal and she has no new fever — and none of that explains why her viral load and CD4 count are moving so favourably at the same moment.",
   "1": "Worsening from the inflammatory material released as organisms are killed is real and expected — but it happens in the FIRST 2 TO 3 DAYS of treatment, and she has already passed through it. Its timing is what makes it a different phenomenon from IRIS, which comes weeks later.",
   "3": "Sulfonamide resistance in Pneumocystis is described but uncommon, and treatment failure would not come with a falling viral load and a rising CD4 count. Failure of the drug and recovery of the immune system are different stories, and the laboratory values here tell the second one.",
   "4": "Pulmonary Kaposi sarcoma occurs in advanced HIV and can cause infiltrates and hypoxemia — and it can even be the lesion that flares as part of IRIS, since IRIS has immune-mediated as well as infectious triggers. As a stand-alone explanation it does not fit a 21-day course in a patient whose known infection and treatment course explain the picture."},
  "Her immune system was almost gone, so it had stopped reacting to the infection in her lungs. The new medicines brought it back — and it came back angry. The lung damage is her own immune system overreacting, not the infection winning.")

# ── 11. The CD4 thresholds (§20) ─────────────────────────────────────────────
q("A 41-year-old man with AIDS who stopped taking antiretroviral therapy 2 years ago comes to the office because of 2 weeks of floaters and progressive blurring of vision in the right eye. He has had no eye pain and no headache. His temperature is 36.9°C (98.4°F), pulse is 82/min, and blood pressure is 124/76 mm Hg. Dilated funduscopic examination of the right eye shows scattered white retinal infiltrates with adjacent hemorrhages along the vascular arcades. Neurologic examination is normal and there is no neck stiffness.\n\nLaboratory studies show:\nCD4 lymphocyte count 28/µL (N=500–1,500/µL)\nHIV RNA 410,000 copies/mL (N=undetectable)\nLeukocyte count 3,900/mm3 (N=4,500–11,000/mm3)\n\nWhich of the following organisms is the most likely cause of his visual symptoms?",
  ["A. Cryptococcus neoformans",
   "B. Cytomegalovirus",
   "C. Mycobacterium avium complex",
   "D. Toxoplasma gondii",
   "E. Varicella-zoster virus"],
  1,
  "Cytomegalovirus retinitis is the classic CD4 below 50/µL diagnosis, and visual changes are the presenting complaint. The retinal appearance — white infiltrates with adjacent hemorrhage following the vessels — is the picture. Cytomegalovirus also causes esophagitis, enteritis, pneumonia and encephalitis in this population.\n\nThe CD4 ladder is the framework the whole section is built on, and it is worth reciting in order:\n• Above 500/µL — community-acquired organisms; bacterial pneumonia, herpes simplex and zoster reactivation\n• 200 to 500/µL — tuberculosis (hemoptysis, night sweats, weight loss)\n• Below 200/µL — Pneumocystis jirovecii (exertional hypoxia, interstitial infiltrates, high LDH), Cryptosporidium (profuse watery diarrhea), Candida (thrush), fungal pneumonia\n• Below 100/µL — toxoplasmosis (RING-ENHANCING lesions on brain imaging), candidal, herpes simplex or cytomegalovirus esophagitis (odynophagia)\n• Below 50/µL — CYTOMEGALOVIRUS (visual changes, retinitis), Cryptococcus (headache, altered mentation, positive India ink), Mycobacterium avium complex (night sweats, weight loss, diarrhea), primary CNS lymphoma (focal deficits, seizures)\n\nTwo numbers that are not the same: CD4 below 200/µL (or below 14%) defines AIDS — CDC stage 3 — and so does an AIDS-defining opportunistic infection at any CD4 count. CD4 below 50/µL is where opportunistic infection risk is greatest. And the shortcut worth having: an absolute lymphocyte count below 1,000/mm3 predicts a CD4 below 200/mm3, which often reaches you before the CD4 count does.",
  {"0": "Cryptococcus neoformans belongs in the same CD4 below 50/µL tier, but its presentation is meningoencephalitis — headache, altered mentation, a positive India ink preparation — or pneumonia. He has a normal neurologic examination and no headache or neck stiffness.",
   "2": "Mycobacterium avium complex is also a CD4 below 50/µL organism and causes disseminated disease: night sweats, weight loss, diarrhea and malaise. It does not cause retinitis.",
   "3": "Toxoplasma gondii encephalitis is the CD4 below 100/µL diagnosis, and its signature is ring-enhancing lesions on brain imaging with focal deficits or seizures. Ocular toxoplasmosis exists, but with this CD4 count and this retinal appearance cytomegalovirus is the expected answer.",
   "4": "Varicella-zoster virus reactivates as dermatomal shingles at HIGHER CD4 counts, typically above 500/µL, alongside herpes simplex reactivation. Acute retinal necrosis from varicella-zoster is rapid and painful with prominent vitritis, unlike this indolent painless course."},
  "His immune system is at rock bottom, and at that level one particular virus attacks the retina. The pattern of white patches and bleeding in the back of the eye is its signature.",
  exim="fig_slide_cd4_oi",
  excap="Lecture slide: the organisms to consider at each CD4 count. Visual changes in the bottom tier point to one organism.")

# ══════════════════════════ §21 · VECTOR-BORNE INFECTIONS ══════════════════════════

# ── 12. Bubonic plague (§21) ─────────────────────────────────────────────────
q("A 34-year-old man comes to the emergency department in northern New Mexico because of 1 day of shaking chills, fever, and profound weakness. He has been camping and 4 days ago handled several dead ground squirrels near his campsite. His temperature is 39.6°C (103.3°F), pulse is 124/min, respirations are 22/min, and blood pressure is 96/60 mm Hg. Physical examination shows an exquisitely tender 5-cm mass in the right groin with overlying erythema, and a small crusted lesion on the right calf. The lungs are clear.\n\nLaboratory studies show:\nLeukocyte count 22,400/mm3 (N=4,500–11,000/mm3)\nBand forms 16% (N=0%–5%)\nPlatelet count 104,000/mm3 (N=150,000–400,000/mm3)\nSerum creatinine 1.6 mg/dL (N=0.6–1.2 mg/dL)\n\nAspiration of the groin mass shows gram-negative rods that stain darkly at both ends with pale centers. Which of the following is the most appropriate pharmacotherapy?",
  ["A. Azithromycin",
   "B. Ceftriaxone",
   "C. Gentamicin",
   "D. Trimethoprim-sulfamethoxazole",
   "E. Vancomycin"],
  2,
  "Bubonic plague, and the treatment named in this lecture is GENTAMICIN or a quinolone. Naturally occurring plague shows very little drug resistance, so the standard agents work — and that has a corollary worth carrying: highly resistant plague is a BIOTERRORISM signal, not a treatment-failure puzzle, and public health should be notified immediately.\n\nEvery element of the stem is a deliberate pointer. Plague is endemic in at least 17 states, mostly Pacific Coast and Western — New Mexico, Colorado, California, Texas, Arizona, Oregon, Nevada — with only about 150 US cases since 2000. US epizootics occur in SQUIRRELS, prairie dogs and chipmunks. The lesion on his calf is the flea bite, which is 1 to 2 cm at most and easy to miss, and the groin mass is the BUBO in the node draining it. The bipolar 'safety pin' staining on Gram or Giemsa is the organism.\n\nThe diagnostic sequence: get the right specimen — a lymph node aspirate when there are buboes, sputum in a pneumonic presentation; demonstrate the bipolar-staining gram-negative rod; send the rapid antigen test, which is 100% sensitive and 100% specific; culture on blood agar for sensitivities; PCR where available.\n\nWatch for progression to SECONDARY plague pneumonia, at which point he becomes infectious by aerosol — and remember that humans are a DEAD-END host for this organism. Untreated bubonic plague carries about 50% mortality; treated, 1% to 15%.",
  {"0": "Azithromycin is the treatment for cat scratch disease, the other flea-associated infection in this section — one spread by the CAT flea rather than the rat flea. It is not the agent named for plague.",
   "1": "Ceftriaxone is a reasonable reflex for a septic patient with an unknown gram-negative organism, and this man does need prompt therapy. Plague has its own named regimen, and the bipolar-staining rod in a bubo identifies the organism before culture returns.",
   "3": "Trimethoprim-sulfamethoxazole treats Pneumocystis and a range of urinary and skin pathogens. It is not among the agents named for Yersinia pestis.",
   "4": "Vancomycin covers gram-positive organisms including methicillin-resistant Staphylococcus aureus, which might be considered for an infected extremity lesion with regional adenopathy. The aspirate shows gram-NEGATIVE rods."},
  "He picked up a flea from dead squirrels out west, and the bacteria it injected have swollen the gland in his groin. This is plague — treatable, but only if you recognize it fast.",
  exim="fig_bubo",
  excap="An axillary bubo — the acutely swollen, exquisitely tender node that names bubonic plague.")

# ── 13. The blocked proventriculus (§21) ─────────────────────────────────────
q("During a public health investigation of a cluster of human plague cases in a rural western county, fleas are collected from prairie dog burrows. Dissection shows that the proventriculus — the valve between the flea's esophagus and midgut — is occluded by a dense mass of bacteria in a large proportion of the fleas. Field observations show that these fleas attempt to feed far more often than unblocked fleas and will feed on host species they normally ignore.\n\nWhich of the following best explains why these fleas transmit infection more efficiently than unblocked fleas?",
  ["A. Bacteria are passed from the infected female flea to her offspring through the eggs",
   "B. Blood cannot pass the blockage, so the starving flea bites repeatedly and regurgitates bacteria into each wound",
   "C. The blockage diverts bacteria into the flea's salivary glands, where they are injected directly",
   "D. The blockage kills the flea rapidly, releasing bacteria onto the skin surface",
   "E. The blockage prolongs the flea's lifespan, increasing the number of blood meals it takes"],
  1,
  "Yersinia pestis is ingested in a blood meal and then multiplies in the PROVENTRICULUS, the valve between the flea's esophagus and midgut, until the bacterial mass occludes it — progressing from a soft mass to an extremely hard one. The flea can still bite, but NO BLOOD CAN PASS THE BLOCKAGE. It is starving while full.\n\nSo it bites frantically and repeatedly, and it expands its host range onto animals it would otherwise ignore — including humans. Each failed feeding attempt regurgitates bacteria into the wound. The flea gets no nutrition and dies, but it inoculates far more hosts than a well-fed flea ever would.\n\nThat single piece of biology answers a question that is otherwise puzzling: why do humans, a DEAD-END host that offers this organism nothing, get bitten at all? Because blockage converts an efficient, well-adapted rat parasite into a desperate and indiscriminate transmission machine.\n\nThe general rule for this whole lecture sits behind it: you cannot be a vector unless the organism GROWS IN YOU. An arthropod that merely carries a pathogen on its mouthparts delivers far too small a dose; a true vector amplifies the organism inside its own body first. The same rule explains why none of these vectors is born infected — each must acquire the organism by feeding on an infected reservoir animal.",
  {"0": "Transovarial transmission — passing the organism to the eggs — does NOT occur here, and the same is true of Ixodes ticks and Babesia. Every flea and every tick must acquire its organism by feeding on an infected reservoir animal, which is why the reservoir matters so much in these questions.",
   "2": "Plague is transmitted by REGURGITATION from a blocked foregut, not by salivary injection. The distinction matters because it explains why the blockage itself is the mechanism rather than an obstacle to transmission.",
   "3": "The blocked flea does eventually die of starvation, but the transmission happens while it is alive and biting — and bacteria deposited on intact skin surface would not establish infection. The inoculation is into the wound the flea itself makes.",
   "4": "The blockage shortens the flea's life rather than prolonging it: it cannot feed. The efficiency gain comes from the frantic FREQUENCY of failed bites in a short time, not from more successful meals over a long one."},
  "Bacteria plug up the flea's throat so no blood can get through. The flea is starving, so it bites over and over, spitting bacteria into every bite. A blocked flea is far more dangerous than a well-fed one.",
  exim="fig_flea_proventriculus",
  excap="The progressive blockage of the flea's proventriculus — from a soft bacterial mass to a hard, completely occluding one.")

# ── 14. Bacillary angiomatosis versus Kaposi sarcoma (§21) ───────────────────
q("A 38-year-old man with AIDS who is not taking antiretroviral therapy comes to the clinic because of skin lesions that have appeared over 6 weeks and bleed easily when scratched. He has a cat at home. His temperature is 37.8°C (100.0°F), pulse is 88/min, and blood pressure is 118/72 mm Hg. Physical examination shows multiple friable cherry-red papules and nodules on the face and trunk, some with a surrounding collarette of scale. There is no lymphadenopathy. His CD4 lymphocyte count is 40/µL (N=500–1,500/µL). Bartonella serology is negative. Photographs of the lesions are shown.\n\nWhich of the following is the most appropriate next step in management?",
  ["A. Begin empiric erythromycin and reassess in 2 weeks",
   "B. Biopsy a lesion for histopathologic examination",
   "C. Obtain blood cultures for Bartonella species",
   "D. Refer for chemotherapy for Kaposi sarcoma",
   "E. Repeat Bartonella serology in 4 weeks"],
  1,
  "These lesions could be bacillary angiomatosis or Kaposi sarcoma, and YOU CANNOT TELL THEM APART BY LOOKING. Both occur in patients with AIDS and both look like this. One is a treatable bacterial infection caused by Bartonella henselae (occasionally B. quintana); the other is a vascular malignancy driven by HHV-8. That is exactly why the diagnosis rests on LESION BIOPSY with histopathologic examination, with PCR as the central confirmatory test.\n\nThe negative serology is close to meaningless here, and understanding why is better than memorizing it. Serology detects the HOST's antibody response — and this patient's immune system is severely impaired at a CD4 of 40/µL, so he may not be producing much antibody. A test that looks for the host's response will underperform in exactly the population that gets this disease. Contrast cat scratch disease in an immunocompetent child, where EIA/ELISA for IgG and IgM works perfectly well: same organism, different test strategy, because the host is different.\n\nOnce bacillary angiomatosis is confirmed, treat with ERYTHROMYCIN and/or DOXYCYCLINE — note this is NOT azithromycin, which is the cat scratch disease drug — and start or optimize antiretroviral therapy. You have to get the immune system back up or antibiotics will not hold the line. Untreated, especially with organ involvement, bacillary angiomatosis is progressive and can be fatal; it is not confined to skin, and colonic involvement is described.",
  {"0": "Empiric erythromycin is the right drug for bacillary angiomatosis, and a trial of it is tempting. It abandons the critical differential: if this is Kaposi sarcoma, two weeks of an antibiotic buys nothing in a man with a CD4 count of 40/µL, and the two conditions cannot be separated clinically.",
   "2": "Do not culture Bartonella. The organism is fastidious and slow, taking weeks to grow — 'anything that takes 2 or 3 weeks to grow, forget it.' Blood cultures will not answer the question in a useful timeframe.",
   "4": "Repeating a test that is unreliable in this population does not make it reliable. The problem is not timing; it is that a profoundly immunosuppressed patient may not mount the antibody response the assay is designed to detect.",
   "3": "Committing to chemotherapy for a malignancy that has not been confirmed would mean treating a curable bacterial infection with cytotoxic drugs in a man whose immune system is already destroyed. The histology is what separates the two, and it must come first."},
  "The red bumps on his skin could be an infection you can cure with antibiotics, or a cancer. They look identical, and the blood test is unreliable in someone with almost no immune system — so you have to take a piece and look at it under the microscope.",
  image="fig_bacillary_angiomatosis",
  imcap="Cutaneous lesions in a patient with advanced HIV infection.",
  exim="fig_slide_bartonella_two",
  excap="Lecture slide: one cat, one organism, two diseases — split entirely by the state of the patient's immune system.")

# ── 15. Babesiosis (§21) ─────────────────────────────────────────────────────
q("A 72-year-old man who spends the summer on Nantucket comes to the office in late July because of 8 days of fever, shaking chills, fatigue, and diffuse myalgia. He underwent splenectomy after a motor vehicle collision 20 years ago. He recalls no tick bite and has no rash. His temperature is 38.9°C (102.0°F), pulse is 104/min, and blood pressure is 108/64 mm Hg. Physical examination shows scleral icterus.\n\nLaboratory studies show:\nHemoglobin 9.1 g/dL (N=13.0–16.0 g/dL)\nHematocrit 27% (N=37%–49%)\nMean corpuscular volume 90 µm3 (N=80–100 µm3)\nReticulocyte count 6.8% (N=0.5%–1.5%)\nPlatelet count 84,000/mm3 (N=150,000–400,000/mm3)\nLactate dehydrogenase 640 U/L (N=100–220 U/L)\nHaptoglobin <10 mg/dL (N=30–200 mg/dL)\nAspartate aminotransferase 88 U/L (N=10–40 U/L)\n\nA Giemsa-stained peripheral blood smear shows small ring forms within erythrocytes. Which of the following is the most appropriate pharmacotherapy?",
  ["A. Artemether-lumefantrine",
   "B. Atovaquone plus azithromycin",
   "C. Chloroquine phosphate",
   "D. Doxycycline",
   "E. Trimethoprim-sulfamethoxazole"],
  1,
  "Babesiosis. The treatment is AZITHROMYCIN PLUS ATOVAQUONE — atovaquone targets the parasite's electron transport system, which is the mechanism to be able to state — given intravenously in severe cases.\n\nThe stem is a checklist: coastal New England in summer, a flu-like illness, and the laboratory triad of HEMOLYTIC ANEMIA (hemoglobin 9.1 g/dL with a reticulocytosis, an LDH of 640 U/L and an unmeasurable haptoglobin), THROMBOCYTOPENIA, and TRANSAMINASE ELEVATION. His age and his asplenia both place him in the severe-disease group, alongside the immunocompromised — severe babesiosis means ARDS, disseminated intravascular coagulation, severe hemolysis, shock and heart failure.\n\nThe absence of a tick-bite history is EXPECTED and must never argue against the diagnosis. The vector is the Ixodes scapularis NYMPH, and two facts make the nymph the transmitter: ticks are not born infected (there is no transovarial transmission, so the nymph is the first stage that is both infected and hungry), and a nymph is about the size of the dot over an 'i' — it goes unnoticed and therefore stays attached long enough to transmit. An adult tick gets seen and removed.\n\nWhy doxycycline is the trap answer: it treats the co-infections — Borrelia burgdorferi and Anaplasma phagocytophilum — that share the same white-footed mouse reservoir and the same tick, so co-infection is structural rather than coincidental. It has NO useful activity against Babesia. A New England patient who is not improving on doxycycline for Lyme disease may have babesiosis as well.",
  {"0": "Artemether-lumefantrine is artemisinin-based combination therapy for CHLOROQUINE-RESISTANT malaria. Malaria also produces ring forms in red cells, but it requires tropical or subtropical exposure and typically a cyclic fever; his exposure is a New England summer.",
   "2": "Chloroquine phosphate is the treatment for chloroquine-sensitive malaria, working by blocking the conversion of toxic heme to inert hemozoin. Babesia does not digest hemoglobin in the same way, and chloroquine is not a babesiosis drug.",
   "3": "Doxycycline is the deliberate trap. It covers Lyme disease and anaplasmosis — both carried by the same Ixodes nymph from the same white-footed mouse, so both are common co-infections — but it has no useful activity against Babesia.",
   "4": "Trimethoprim-sulfamethoxazole is the Pneumocystis drug and has no role here. Nothing in the folate pathway addresses an intra-erythrocytic protozoan of this kind."},
  "A tick the size of a full stop gave him a parasite that lives inside his red blood cells and bursts them. The antibiotic used for the other tick diseases does nothing against it — it needs its own pair of drugs.",
  exim="fig_babesia_rings",
  excap="Giemsa-stained smear: Babesia trophozoites inside red cells — the ring forms that must be separated from malaria by geography and fever pattern.")

# ── 16. How chloroquine kills the parasite (§21) ─────────────────────────────
q("A 27-year-old woman comes to the emergency department 10 days after returning from a 3-week stay in a rural area of Central America where chloroquine-sensitive malaria is endemic. She has had 5 days of fever, rigors, and drenching sweats occurring approximately every 48 hours, with well intervals between episodes. Her temperature is 39.4°C (102.9°F), pulse is 108/min, and blood pressure is 106/66 mm Hg. Physical examination shows mild scleral icterus and a palpable spleen tip.\n\nLaboratory studies show:\nHemoglobin 10.2 g/dL (N=12.0–16.0 g/dL)\nHematocrit 30% (N=36%–46%)\nPlatelet count 96,000/mm3 (N=150,000–400,000/mm3)\nTotal bilirubin 2.8 mg/dL (N=0.2–1.2 mg/dL)\nLactate dehydrogenase 420 U/L (N=100–220 U/L)\n\nA thick smear is positive and a thin smear shows infected erythrocytes of normal size with ring forms. Chloroquine phosphate is started. Which of the following is the mechanism by which this drug kills the parasite?",
  ["A. Blockade of the conversion of toxic heme to inert hemozoin",
   "B. Inhibition of dihydrofolate reductase within the parasite",
   "C. Inhibition of parasite protein synthesis at the ribosome",
   "D. Inhibition of the parasite's mitochondrial electron transport chain",
   "E. Production of free radicals that alkylate parasite proteins"],
  0,
  "The elegance of this mechanism is that the drug never attacks the parasite directly — it disables the parasite's own waste-disposal system and lets the parasite poison itself.\n\nThe chain: the parasite DIGESTS HEMOGLOBIN inside the red cell and uses the globin portion as an amino acid source. That liberates free HEME, which is highly toxic to the parasite — it has created its own poison as a by-product of feeding. To survive its own metabolism it uses HEME POLYMERASE to convert toxic heme into inert HEMOZOIN. Chloroquine, quinine and mefloquine all block that conversion, heme accumulates to toxic concentrations, and the parasite dies.\n\nHer 48-hour fever periodicity is not decorative. The interval is set by the SYNCHRONIZED moment when infected red cells lyse and a new wave of merozoites bursts into the circulation, so the erythrocytic cycle length IS the fever period: P. knowlesi 24 hours, P. vivax and P. ovale 48 hours, P. malariae 72 hours, and P. falciparum IRREGULAR because its cycles are not synchronized — one reason falciparum is the most dangerous, since there is no rhythm and no fever-free window in which the patient recovers.\n\nThe smears also have distinct jobs. THICK smear: red cells are pre-lysed, parasites are concentrated, so it is the sensitive SCREEN — presence or absence. THIN smear: parasites are seen inside intact red cells, so it IDENTIFIES the species and estimates parasite density. Thick = is it there; thin = which one. Where chloroquine resistance is present, use artemisinin-based combination therapy such as artemether-lumefantrine.",
  {"1": "Dihydrofolate reductase inhibition is the mechanism of pyrimethamine and proguanil, used in combination antimalarials and in toxoplasmosis. It is not how chloroquine works.",
   "2": "Ribosomal inhibition of protein synthesis describes the antibacterials that have antiparasitic uses — doxycycline and clindamycin act on the apicoplast and are used as partner drugs — but not chloroquine.",
   "3": "Inhibition of the parasite's mitochondrial electron transport is the mechanism of ATOVAQUONE, which is why atovaquone is paired with azithromycin for babesiosis and appears in atovaquone-proguanil for malaria. It is a genuine antiparasitic mechanism attached to the wrong drug here.",
   "4": "Free-radical generation that alkylates parasite proteins is the artemisinin mechanism — the peroxide bridge is cleaved by iron within the parasite. Artemisinins are what you turn to when chloroquine resistance is present, which is not the case in this patient's exposure region."},
  "The parasite eats hemoglobin and creates a poison as waste. Normally it packs that poison away safely. The drug stops it packing it away, so the parasite is killed by its own garbage.",
  exim="fig_slide_chloroquine",
  excap="Lecture slide: chloroquine blocks the conversion of toxic heme to inert hemozoin.")

# ══════════════════════════ §22 · VIRAL HEMORRHAGIC FEVERS ══════════════════════════

# ── 17. Dengue and the analgesic rule (§22) ──────────────────────────────────
q("A 30-year-old woman comes to the emergency department because of 3 days of fever, severe headache, and pain behind her eyes. She returned 5 days ago from a 2-week stay in Puerto Rico. She also reports severe pain in her lower back and long bones. Her temperature is 39.0°C (102.2°F), pulse is 104/min, respirations are 18/min, and blood pressure is 102/62 mm Hg. Physical examination shows conjunctival injection and a faint blanching macular rash over the trunk. There is mild diffuse abdominal tenderness and she has vomited twice today.\n\nLaboratory studies show:\nHemoglobin 14.8 g/dL (N=12.0–16.0 g/dL)\nHematocrit 45% (N=36%–46%)\nLeukocyte count 3,200/mm3 (N=4,500–11,000/mm3)\nPlatelet count 88,000/mm3 (N=150,000–400,000/mm3)\nAspartate aminotransferase 96 U/L (N=10–40 U/L)\n\nWhich of the following is the most appropriate management?",
  ["A. Acetaminophen and intravenous fluid resuscitation",
   "B. Ibuprofen and intravenous fluid resuscitation",
   "C. Oral ribavirin",
   "D. Prophylactic broad-spectrum antibiotics",
   "E. Transfusion of platelets"],
  0,
  "Dengue — and the single prescribing rule that spans this entire lecture is ACETAMINOPHEN FOR FEVER AND PAIN, NEVER NSAIDs. Not ibuprofen, not naproxen, not aspirin. NSAIDs inhibit platelet function and increase bleeding risk in a patient who already has a coagulopathy. The rule is stated for dengue and repeated verbatim for Crimean-Congo hemorrhagic fever: treat it as a class rule for every viral hemorrhagic fever.\n\nFluids are the single most important intervention — there is no antiviral for dengue.\n\nEverything in the stem is a tier marker. The base syndrome is fever and chills, headache, rash, MUSCULOSKELETAL AND LUMBAR pain (the 'breakbone' component that named the disease) and RETRO-ORBITAL eye pain. Moderate dengue is that plus any TWO of abdominal tenderness, persistent anorexia, nausea or vomiting, and mucosal bleeding — she has abdominal tenderness and vomiting, so she is at that tier and warrants close observation. Severe dengue is dengue plus any ONE of hypovolemic shock, severe bleeding, or organ failure, and requires hospitalization.\n\nPuerto Rico is where most US dengue cases are, and the intrinsic incubation period of 4 to 7 days fits her timeline exactly. Diagnose with multiplex RT-PCR, which covers dengue plus the other major hemorrhagic fever viruses in one run, or ELISA for dengue antigen; antibody testing is not useful acutely because it takes weeks to turn positive.",
  {"1": "The fluids are right and the analgesic is the error — this is the specific trap the lecture sets. Ibuprofen adds platelet inhibition to a patient with a platelet count of 88,000/mm3 and an evolving coagulopathy, and the same prohibition covers aspirin and naproxen.",
   "2": "Ribavirin is the one antiviral in this lecture, and it belongs to LASSA FEVER — a guanosine analogue that inhibits viral RNA synthesis, with mixed results at that. No antiviral exists for dengue, hantavirus HFRS or Crimean-Congo hemorrhagic fever.",
   "3": "There is nothing bacterial here, and antibiotics do not address capillary leak. Her leukopenia and thrombocytopenia with a viral exposure history are the expected pattern, not evidence of bacterial infection.",
   "4": "Platelet transfusion is not the reflex response to a number. The bleeding risk in dengue comes from consumption, capillary leak and vessel injury together, and prophylactic platelet transfusion has not been shown to help; volume status is what determines outcome."},
  "She has dengue. The one thing you must not give is the common anti-inflammatory painkiller, because it makes bleeding worse — and she is already at risk of bleeding. Use acetaminophen and fluids.",
  exim="fig_dengue_rash",
  excap="The dengue rash — not diagnostic on its own, and more common in children than in adults.")

# ── 18. Hantavirus HFRS (§22) ────────────────────────────────────────────────
q("A 40-year-old man comes to the emergency department because of 5 days of fever, severe headache, and vomiting, followed by decreasing urine output. He returned 6 weeks ago from rural South Korea, where he spent 2 weeks clearing out and renovating a long-abandoned barn that was heavily infested with mice. He recalls no insect or tick bites. His temperature is 38.8°C (101.8°F), pulse is 112/min, respirations are 20/min, and blood pressure is 88/54 mm Hg. Physical examination shows conjunctival hemorrhage, facial flushing, and petechiae over the trunk and axillae.\n\nLaboratory studies show:\nHemoglobin 15.6 g/dL (N=13.0–16.0 g/dL)\nHematocrit 47% (N=37%–49%)\nLeukocyte count 14,800/mm3 (N=4,500–11,000/mm3)\nPlatelet count 40,000/mm3 (N=150,000–400,000/mm3)\nSerum creatinine 4.2 mg/dL (N=0.6–1.2 mg/dL)\nUrine protein 3+ (N=negative)\n\nWhich of the following is the most likely route by which this patient acquired his infection?",
  ["A. Contact with the blood of infected livestock",
   "B. Ingestion of contaminated drinking water",
   "C. Inhalation of aerosolized rodent urine, feces, or saliva",
   "D. The bite of an infected mosquito",
   "E. The bite of an infected tick"],
  2,
  "Hantavirus hemorrhagic fever with renal syndrome — an Old World hantavirus, most likely Hantaan or Seoul given Korea. There is NO VECTOR. The virus is shed in rodent urine, feces and saliva and acquired by AEROSOL, classically by someone generating aerosols while working in a contaminated building. That is exactly what he was doing.\n\nThe incubation period is the detail that makes this question answerable and is unusually long: 3 TO 9 WEEKS from inhalation to symptom onset, against dengue's 4 to 7 DAYS. A patient who cleaned out a rodent-infested building a month or two ago and is now febrile is still within the window — do not dismiss the exposure because it was not recent.\n\nThis is also the one agent in the lecture where a single organ fails out of proportion. Everything else fails as a set; here ACUTE KIDNEY INJURY is the usual cause of death, and the lesion is an acute tubulointerstitial nephritis that is IMMUNOPATHOLOGIC rather than directly viral — cytokines, cytotoxic T cells, antibody-dependent cytotoxicity, complement and bradykinin attacking an endothelium that has marked itself as infected by upregulating HLA and adhesion molecules. VEGF released by those cells directly increases permeability. Renal failure out of proportion to everything else is the answer key for this agent.\n\nOld World versus New World is the whole distinction: Old World hantaviruses hit the kidneys (HFRS); New World hantaviruses of the Americas, such as Andes virus, cause the cardiopulmonary syndrome with normal renal function. Treatment is supportive — no antiviral, and no vaccine available in the United States.",
  {"0": "Contact with infected livestock blood is the second route for CRIMEAN-CONGO hemorrhagic fever, where the virus circulates in livestock and birds that stay completely well. That is a Bunyaviridae relative of hantavirus, but its geography is Africa, the Middle East, Asia and southeastern Europe, and its primary route is a tick.",
   "1": "Ingestion is the route for many enteric pathogens, and Lassa fever does add EATING the rodent to its routes. Hantavirus is acquired by aerosol and contact with excreta rather than by drinking contaminated water.",
   "3": "Mosquito transmission belongs to dengue, where the Aedes mosquito is a true vector and the virus replicates inside it. He reports no bites, and the Far East plus rodent exposure plus renal failure is a different pattern entirely.",
   "4": "Tick transmission belongs to Crimean-Congo hemorrhagic fever through Hyalomma, and to babesiosis and Lyme disease through Ixodes. Hantavirus has NO arthropod vector at all — it and Lassa are the two no-vector rodent diseases in this lecture."},
  "He breathed in dried mouse droppings while clearing out an old barn. No insect was involved. The virus in those droppings attacks the kidneys, and kidney failure is what kills people with this infection.",
  exim="fig_slide_hanta_kidney",
  excap="Lecture slide: the immunopathologic mechanism of hantavirus kidney injury — the host response, not the virus, destroys the renal vascular bed.")

# ── 19. Lassa fever (§22) ────────────────────────────────────────────────────
q("A 29-year-old aid worker comes to the hospital 3 weeks after returning from rural Nigeria, where she lived in a village with a heavy rodent population. Her illness began with fever, fatigue, headache, and myalgia, and progressed over 10 days to sore throat, retrosternal chest pain, vomiting, and diarrhea. She now has swelling of the face and neck. Her temperature is 38.7°C (101.7°F), pulse is 116/min, respirations are 22/min, and blood pressure is 92/58 mm Hg. Physical examination shows conjunctival injection, facial and cervical edema, and pharyngeal inflammation. During recovery she reports that she cannot hear properly in either ear, and audiometry confirms bilateral sensorineural hearing loss.\n\nLaboratory studies show:\nHemoglobin 10.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 31% (N=36%–46%)\nPlatelet count 102,000/mm3 (N=150,000–400,000/mm3)\nAspartate aminotransferase 268 U/L (N=10–40 U/L)\nUrine protein 3+ (N=negative)\n\nWhich of the following is the most appropriate pharmacotherapy?",
  ["A. Acyclovir",
   "B. Artesunate",
   "C. Oseltamivir",
   "D. Remdesivir",
   "E. Ribavirin"],
  4,
  "Lassa fever, and it is the ONLY agent in this lecture with a drug: RIBAVIRIN, a guanosine analogue that inhibits viral RNA synthesis. The honest summary is that it is not a great drug — studies show mixed results — but it is used and it can slow things down. Supportive care remains first: oxygen, blood pressure, fluids. Dengue, hantavirus HFRS and Crimean-Congo hemorrhagic fever have no antiviral at all.\n\nThe sequela is what identifies the disease. NEW BILATERAL SENSORINEURAL HEARING LOSS after a febrile illness acquired in West Africa is Lassa until proven otherwise — no other agent in this lecture has it. Survivors also report hair loss, balance difficulty, difficulty speaking and tremor.\n\nHer course maps onto the staged natural history: stage I (fever, fatigue, headache, myalgia — where about 80% of patients stop), stage II (sore throat, cough, RETROSTERNAL CHEST PAIN, vomiting, abdominal pain, diarrhea), stage III (HEAD AND NECK EDEMA, conjunctival injection, shortness of breath, proteinuria, hypotension, anemia), stage IV (altered mental status, convulsions, bleeding, coma). Incubation is 6 to 21 days.\n\nThe reservoir is Mastomys natalensis, the MULTIMAMMATE RAT, common throughout Nigeria and neighbouring countries — Nigeria, Sierra Leone, Liberia, Guinea. There is NO insect vector: the three routes in are direct contact with urine, feces or body fluids, inhalation of aerosolized excreta, and EATING THE RODENT as a food source — that last route is what separates Lassa from hantavirus, the other no-vector rodent disease. Overall mortality is about 1%, far below the roughly 30% of Crimean-Congo.",
  {"0": "Acyclovir is a guanosine analogue too, but it requires viral thymidine kinase for activation and works against herpesviruses. It has no activity against an arenavirus.",
   "1": "Artesunate is the parenteral artemisinin used for severe malaria, and malaria is a genuine competing diagnosis in a traveller returning from Nigeria with fever. The staged illness, head and neck edema, proteinuria and bilateral sensorineural hearing loss are not malaria, and no red cell ring forms are described.",
   "2": "Oseltamivir is a neuraminidase inhibitor for influenza. Influenza can certainly produce a febrile illness in a returning traveller, but it does not cause this staged course or deafness.",
   "3": "Remdesivir inhibits the viral RNA polymerase and is used experimentally in Ebola alongside pan-Ebola monoclonal antibodies. Ebola is a filovirus from Central and West Africa with a different exposure history — body-fluid contact, including with corpses — and no hearing-loss sequela."},
  "She caught a virus from rats in West Africa. The giveaway is that she came out of it deaf in both ears — that happens with this infection and no other in the group. It is also the only one with a drug, even a mediocre one.",
  exim="fig_slide_lassa_stages",
  excap="Lecture slide: the natural history of Lassa fever, with the incubation period and the four clinical stages.")

# ── 20. Crimean-Congo hemorrhagic fever (§22) ────────────────────────────────
q("A 45-year-old sheep farmer in eastern Turkey is admitted with 4 days of abrupt high fever, severe headache, myalgia, and abdominal pain. He removed an engorged tick from his thigh about a week before the illness began and has daily contact with livestock, including assisting at slaughter. His temperature is 39.3°C (102.7°F), pulse is 118/min, respirations are 22/min, and blood pressure is 94/56 mm Hg. Physical examination shows conjunctivitis, photophobia, bleeding from the gums, and widespread petechiae and ecchymoses. On day 4 he develops hemoptysis.\n\nLaboratory studies show:\nHemoglobin 10.8 g/dL (N=13.0–16.0 g/dL)\nHematocrit 32% (N=37%–49%)\nPlatelet count 22,000/mm3 (N=150,000–400,000/mm3)\nAspartate aminotransferase 940 U/L (N=10–40 U/L)\nProthrombin time 22 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 68 seconds (N=25–35 seconds)\n\nWhich of the following is the most likely causal agent?",
  ["A. Crimean-Congo hemorrhagic fever virus",
   "B. Dengue virus",
   "C. Hantaan virus",
   "D. Lassa fever virus",
   "E. Marburg virus"],
  0,
  "Tick bite plus livestock contact plus southeastern Europe or the Middle East is the Crimean-Congo pattern, and it deserves the attention it gets: only about 1,000 cases a year worldwide, but it appears frequently on licensing examinations. Mortality is about 30% among those who become symptomatic — far above dengue or Lassa — while roughly 88% of infections are subclinical, so this man is in the minority.\n\nThe virus is a NAIROVIRUS within the Bunyaviridae. The vector is the HYALOMMA tick, which acquires the virus from LIVESTOCK AND BIRDS THAT CARRY IT AND STAY COMPLETELY WELL — a healthy-appearing reservoir is the rule across this whole block, not the exception. His second route is available too: direct contact with infected animal blood at slaughter.\n\nKeep the tick genera straight. Hyalomma is a hard tick like Ixodes but a different genus; if a stem names Ixodes scapularis it is pointing at Lyme disease, babesiosis or anaplasmosis, not Crimean-Congo. The name itself comes from two unrelated discoveries of one agent — Russian soldiers in the Crimea in 1944, then a child in the Congo about ten years later.\n\nDiagnosis is RT-PCR first, with IgM/IgG antibody kits secondary since antibodies take time. There is no antiviral: supportive care with fluids, electrolytes, ventilation, hemodialysis and vasopressors, and ACETAMINOPHEN RATHER THAN NSAIDs. Prevention is tick-bite avoidance.",
  {"1": "Dengue is transmitted by the Aedes mosquito, its reservoir is HUMANS rather than an animal, and its geography is the Americas and the Caribbean — Puerto Rico for most US cases. Its signature is retro-orbital and breakbone pain rather than a tick bite in Anatolia.",
   "2": "Hantaan virus is an Old World hantavirus acquired by inhaling aerosolized rodent excreta in the Far East, with NO vector, an incubation of 3 to 9 weeks, and acute kidney injury as the cause of death. He has a tick bite and a livestock exposure, and his creatinine is not the abnormality driving this picture.",
   "3": "Lassa fever comes from the multimammate rat Mastomys natalensis in West Africa — Nigeria, Sierra Leone, Liberia, Guinea — with no vector, and it is identified by new bilateral sensorineural hearing loss in survivors. The geography and the exposure are wrong.",
   "4": "Marburg is a filovirus with the Egyptian rousette fruit bat as its reservoir, classically acquired in CAVES, with no vector at all and no approved treatment or vaccine. It causes more hemorrhage than Ebola, but a tick bite and sheep farming in Turkey point elsewhere."},
  "A tick in the Middle East gave him a virus that lives harmlessly in farm animals. About a third of the people who get sick with it die, and there is no drug — only supportive care, and never the anti-inflammatory painkillers.",
  exim="fig_hyalomma",
  excap="Hyalomma ticks — note the banded legs. This is the Crimean-Congo vector, and it is not Ixodes.")
