# Jeevs Edition — Batch 05: Transfusion Medicine
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §12 s11-products  — the four products, thresholds, TRICC   (LO 31, 74)
#   §13 s12-immuno    — ABO/Rh, alloantibodies, Coombs         (LO 31, 61)
#   §14 s13-reactions — the reaction differential              (LO 61)
# Weighted per the third-year's advice: products/indications and the reaction
# differential carry the batch. Options alphabetised; "correct" is the 0-based index
# AFTER alphabetisation.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ── 1. The restrictive threshold — chart format (§12) ─────────────────────────
q("PATIENT INFORMATION\nAge: 68 years\nGender: Female\nSite of Care: Inpatient surgical ward, hospital day 2\n\nHISTORY\nReason for Visit: Postoperative care after elective right total hip arthroplasty\nHPI: Surgery was uncomplicated, with an estimated blood loss of 350 mL. She is ambulating with physical therapy, eating a regular diet, and reports only incisional pain. She denies chest pain, palpitations, light-headedness, and dyspnea at rest or with walking.\nPMH: Hypertension. Osteoarthritis. No coronary artery disease, heart failure, or chronic kidney disease.\nMedications: Lisinopril, acetaminophen, enoxaparin for thromboprophylaxis\nAllergies: No known drug allergies\nFamily History: Noncontributory\nPsychosocial History: Does not smoke cigarettes or drink alcoholic beverages\n\nPHYSICAL EXAMINATION\nVital Signs: Temperature 36.9°C (98.4°F), pulse 78/min, respirations 16/min, blood pressure 126/74 mm Hg, oxygen saturation 98% on room air\nGeneral: Comfortable, alert, in no distress\nCardiovascular: Regular rate and rhythm, no murmur, capillary refill less than 2 seconds\nPulmonary: Clear to auscultation bilaterally\nWound: Clean and dry, no hematoma, drain output minimal\n\nDIAGNOSTIC STUDIES\nLaboratory studies show:\nHemoglobin 7.6 g/dL (N=12.0–16.0 g/dL)\nHematocrit 23% (N=36%–46%)\nMean corpuscular volume 88 µm3 (N=80–100 µm3)\nPlatelet count 268,000/mm3 (N=150,000–400,000/mm3)\nCreatinine 0.9 mg/dL (N=0.6–1.2 mg/dL)\n\nHer preoperative hemoglobin concentration was 12.4 g/dL. Electrocardiography shows normal sinus rhythm with no ischemic changes.\n\nQuestion: Which of the following is the most appropriate next step in management?",
  ["A. Administer fresh frozen plasma",
   "B. Administer one unit of packed red blood cells",
   "C. Administer two units of packed red blood cells",
   "D. No transfusion; continue observation and reassess",
   "E. Transfuse to a target hemoglobin concentration of 10 g/dL"],
  3,
  "She is euvolemic, hemodynamically stable, asymptomatic, and not bleeding, with a hemoglobin of 7.6 g/dL. Under a restrictive strategy that is ABOVE the transfusion threshold, so the correct action is to give no blood.\n\nThe evidence is the TRICC trial (1999): 838 euvolemic critically ill patients randomized to a restrictive threshold (transfuse below 7 g/dL) or a liberal one (below 10 g/dL). There was no difference in 30-day mortality, and the LIBERAL arm — the one that received more blood — did worse. Every threshold in transfusion medicine has moved down since.\n\nTwo further points from §12 apply directly to the surgical resident's instinct here. Red cells are given to increase oxygen-carrying capacity; they are explicitly NOT given to speed wound healing or shorten time to ambulation, both of which were once believed and neither of which is supported. And when a transfusion is indicated, the order is ONE unit, then reassess — never a reflexive two.\n\nTransfusion is never free: every unit comes from a volunteer donor and carries a finite risk of reaction and infection. The question is never 'is the number low?' but 'will this unit help more than it might harm?'",
  {"0": "Plasma is given for a documented multiple factor deficiency with active bleeding, or for a markedly prolonged coagulation test before a procedure. She has neither — her problem is dilutional anemia after a normal surgical blood loss, and plasma carries no oxygen at all.",
   "1": "One unit followed by reassessment is the correct FORM of a red cell order, and would be the answer if she were below the threshold or symptomatic — chest pain, dyspnea at rest, light-headedness, or hemodynamic instability. At 7.6 g/dL in a comfortable, ambulating patient, the indication itself is missing.",
   "2": "Two units at once compounds two errors: transfusing without an indication, and ordering a fixed number of units rather than reassessing after each. This is the reflex the whole restrictive-strategy literature was written against.",
   "4": "A target of 10 g/dL is precisely the liberal arm of TRICC, which showed no mortality benefit and worse outcomes than the restrictive arm. Chasing a number rather than treating a patient is the error the trial was designed to expose."},
  "Her blood count is low after surgery, but she feels fine, is walking, and her heart and lungs are coping. Big studies showed that giving blood at this level makes people do worse, not better, so the right move is to wait and watch.",
  exim="fig_tx_reactions",
  excap="Why transfusion is never free: each product carries its own reaction mechanism, summarized by donor factor, reaction, and host factor.")

# ── 2. Platelet threshold before a procedure (§12) ────────────────────────────
q("A 54-year-old woman with acute myeloid leukemia is receiving induction chemotherapy. On the tenth day of her admission she develops a headache and neck stiffness, and a diagnostic lumbar puncture is planned. She has no bleeding, no petechiae, and no bruising. Her temperature is 38.4°C (101.1°F), pulse is 96/min, respirations are 18/min, and blood pressure is 118/70 mm Hg.\n\nLaboratory studies show:\nHemoglobin 8.9 g/dL (N=12.0–16.0 g/dL)\nHematocrit 27% (N=36%–46%)\nLeukocyte count 900/mm3 (N=4500–11,000/mm3)\nPlatelet count 14,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 12.4 seconds (N=11–15 seconds)\nPartial thromboplastin time 31 seconds (N=25–40 seconds)\n\nPlatelet transfusion is planned before the procedure. The platelet count should be raised above which of the following values?",
  ["A. 10,000/mm3", "B. 20,000/mm3", "C. 25,000/mm3", "D. 50,000/mm3", "E. 100,000/mm3"],
  1,
  "The thresholds in §12 rise with how much is about to be risked, and the lumbar puncture threshold is 20,000/mm3.\n\n• 10,000/mm3 — a stable, non-bleeding patient with HYPOPROLIFERATIVE thrombocytopenia (chemotherapy, stem cell transplant) and no procedure planned. This is where she was before the headache.\n• 20,000/mm3 — before a lumbar puncture. A needle is entering the spinal canal, where a hematoma can compress the cord.\n• 25,000/mm3 — preterm neonates, whose germinal matrix vessels are fragile.\n\nThe memory hook: ten for chemo, twenty for a tap, twenty-five for a preemie.\n\nThe rest of her picture supports transfusing rather than waiting. Her thrombocytopenia is hypoproliferative — the marrow is suppressed by chemotherapy — so transfused platelets will survive normally and the count will rise predictably. Her coagulation tests are normal, so plasma has no role. And the febrile neutropenia that prompted the lumbar puncture must be treated in parallel.",
  {"0": "10,000/mm3 is the threshold for a stable, non-bleeding patient with hypoproliferative thrombocytopenia who is NOT undergoing a procedure. It would be the answer if the lumbar puncture were not planned — her count of 14,000/mm3 alone would not require transfusion.",
   "2": "25,000/mm3 is the threshold for preterm neonates. It would be the answer for a premature infant, whose fragile germinal matrix vessels make intraventricular hemorrhage the feared complication.",
   "3": "50,000/mm3 is the conventional threshold for major surgery or an invasive procedure with substantial bleeding risk, and for an actively bleeding patient. Applying it to a lumbar puncture transfuses more product than the evidence requires.",
   "4": "100,000/mm3 is reserved for neurosurgery and ophthalmic surgery, where bleeding into a closed space is catastrophic. Using it here would expose her to unnecessary transfusion in an already heavily transfused patient."},
  "Her platelets are too low to safely put a needle into her spine, because a bruise there could squeeze the spinal cord. The cutoff for that particular procedure is twenty thousand.",
  exim="fig_tx_timeline",
  excap="Transfusion carries its own risks on a predictable timeline, which is why each product is given against a defined threshold rather than reflexively.")

# ── 3. Why platelets fail in immune thrombocytopenia (§12) ────────────────────
q("A 28-year-old woman comes to the office because of 5 days of easy bruising and small red spots on her shins. She had an upper respiratory tract infection 2 weeks ago. She takes no medications and has no history of serious illness. Her temperature is 37.0°C (98.6°F), pulse is 78/min, and blood pressure is 114/72 mm Hg. Physical examination shows scattered petechiae over both shins and a few small bruises on her forearms. There is no lymphadenopathy, the spleen is not palpable, and there is no active bleeding.\n\nLaboratory studies show:\nHemoglobin 13.1 g/dL (N=12.0–16.0 g/dL)\nHematocrit 39% (N=36%–46%)\nLeukocyte count 7,200/mm3 (N=4500–11,000/mm3)\nPlatelet count 8,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 12.1 seconds (N=11–15 seconds)\nPartial thromboplastin time 29 seconds (N=25–40 seconds)\nFibrinogen 340 mg/dL (N=200–400 mg/dL)\n\nA peripheral blood smear shows markedly reduced platelets, some of them large, with normal erythrocyte and leukocyte morphology. Bone marrow examination shows increased megakaryocytes. Which of the following best explains why platelet transfusion would be unlikely to raise this patient's platelet count?",
  ["A. Antibody-mediated destruction of transfused platelets by splenic macrophages",
   "B. Consumption of transfused platelets within widespread microvascular thrombi",
   "C. Dilution of transfused platelets by the expanded plasma volume",
   "D. Failure of megakaryocyte maturation within the bone marrow",
   "E. Sequestration of transfused platelets within an enlarged spleen"],
  0,
  "This is immune thrombocytopenia: isolated thrombocytopenia with large platelets, normal coagulation tests, INCREASED marrow megakaryocytes, and no other cause. The marrow is producing platelets perfectly well; an autoantibody is destroying them peripherally, and splenic macrophages clear the antibody-coated platelets.\n\nThat mechanism is exactly why transfusion does not work. The autoantibody does not distinguish the patient's platelets from a donor's, so transfused platelets are destroyed at the same accelerated rate → the count barely moves → the product is wasted and the patient exposed for nothing.\n\nThe 10,000/mm3 transfusion threshold in §12 is written specifically for HYPOPROLIFERATIVE thrombocytopenia, where the marrow cannot make platelets and transfused ones survive normally. It does not transfer to destructive or consumptive states. The review file makes the same point with dengue, where the platelets are being consumed.\n\nTreatment is aimed at the immune process — corticosteroids, intravenous immune globulin, or a thrombopoietin receptor agonist — with platelet transfusion reserved for serious active bleeding, where it is given alongside that treatment as a temporizing measure. Treat the mechanism, not the number.",
  {"1": "Consumption within microthrombi is the mechanism of disseminated intravascular coagulation and the thrombotic microangiopathies, and it would also make transfusion futile — so the reasoning is right but the disease is wrong. It would be the answer with schistocytes, a low fibrinogen, or organ ischemia; her fibrinogen is 340 mg/dL, her coagulation tests are normal and her smear shows no fragments.",
   "2": "Dilution explains thrombocytopenia after massive volume resuscitation or massive transfusion, and would be the answer in a patient who had received many units of red cells and crystalloid. She is euvolemic and has received nothing.",
   "3": "A maturation failure in the marrow is the hypoproliferative mechanism — aplastic anemia, myelodysplastic syndrome, marrow infiltration, or chemotherapy. That is the setting in which the 10,000 threshold applies and transfusion works well. Her marrow shows INCREASED megakaryocytes, which excludes it.",
   "4": "Splenic sequestration lowers the count in hypersplenism from portal hypertension or a large spleen of any cause, and transfused platelets would indeed be sequestered too. It would be the answer with a palpable spleen and often pancytopenia; her spleen is not palpable and her other counts are normal."},
  "Her immune system is making antibodies that tag platelets for destruction. New platelets from a donor get tagged and destroyed just as fast, so you have to switch off the immune attack instead of topping up the platelets.",
  exim="fig_tx_reactions",
  excap="Antibody-mediated destruction of platelets follows the same logic as the antibody-mediated transfusion reactions: what the antibody recognizes, it destroys — whether the cell came from the patient or a donor.")

# ── 4. Cryoprecipitate in obstetric DIC (§12) ─────────────────────────────────
q("A 31-year-old woman, gravida 2, para 2, has heavy vaginal bleeding 40 minutes after a vaginal delivery complicated by placental abruption. She has received 2 L of crystalloid and 4 units of packed red blood cells. Bleeding continues from the uterus and oozes from her intravenous sites. Her temperature is 36.4°C (97.5°F), pulse is 128/min, respirations are 26/min, and blood pressure is 88/52 mm Hg.\n\nLaboratory studies show:\nHemoglobin 7.8 g/dL (N=12.0–16.0 g/dL)\nHematocrit 23% (N=36%–46%)\nPlatelet count 96,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 22 seconds (N=11–15 seconds)\nPartial thromboplastin time 58 seconds (N=25–40 seconds)\nFibrinogen 82 mg/dL (N=200–400 mg/dL)\nD-dimer 4,900 ng/mL (N=≤250 ng/mL)\n\nIn addition to continued red blood cell transfusion, which of the following products is most appropriate to correct the abnormality most in need of replacement?",
  ["A. Albumin 5%",
   "B. Cryoprecipitate",
   "C. Fresh frozen plasma",
   "D. Packed red blood cells",
   "E. Platelet concentrate"],
  1,
  "She has disseminated intravascular coagulation after placental abruption — clotting and fibrinolysis running at once, with a prolonged prothrombin time and partial thromboplastin time, a rising D-dimer, falling platelets, and a fibrinogen of 82 mg/dL. The value most in need of replacement is the fibrinogen, and the concentrated source of fibrinogen is cryoprecipitate.\n\nWhy not simply give more plasma? Plasma contains fibrinogen only at PHYSIOLOGIC concentration, so raising a fibrinogen of 82 mg/dL toward the 150–200 mg/dL needed for hemostasis would require a volume this hypotensive, already fluid-loaded patient cannot tolerate. Cryoprecipitate is the cold-insoluble fraction left when frozen plasma is thawed at refrigerator temperature — enriched in fibrinogen, and also carrying factor VIII, von Willebrand factor, factor XIII and fibronectin — and delivers the same fibrinogen in a fraction of the volume.\n\nFibrinogen matters because it is the end of the road: the intrinsic and extrinsic pathways converge on the common pathway, and the final step is fibrinogen becoming fibrin, the protein that actually cross-links the clot. Without it the rest of the cascade has nothing to build with.\n\nObstetric hemorrhage is named in §12 as the setting that drops into a low-fibrinogen state fastest. In practice all of this happens inside a massive transfusion protocol, with balanced products delivered together.",
  {"0": "Albumin is a purified colloid volume expander made from pooled plasma. It contains NO coagulation factors at all, so it would restore blood pressure briefly while doing nothing for hemostasis — and would dilute what clotting factors she has left.",
   "2": "Plasma does address her multiple factor deficiency and is part of the resuscitation, which is what makes it the near-miss. It is not the answer to the specific question of what corrects the abnormality most in need of replacement: a fibrinogen of 82 mg/dL cannot be corrected by plasma in a tolerable volume.",
   "3": "More red cells are certainly being given — she is anemic and bleeding — and the stem says so explicitly. Red cells carry oxygen and contribute nothing to hemostasis, so they cannot correct the coagulopathy that is keeping her bleeding.",
   "4": "Platelets are reasonable in massive obstetric hemorrhage, and hers are falling. But at 96,000/mm3 she is well above any bleeding threshold, whereas her fibrinogen is less than half of the level needed to form a clot. The number that is critically low is the one to replace."},
  "Her blood has burned through the protein that forms the actual mesh of a clot. Plain plasma is too watery to replace enough of it, so she needs the concentrated version.",
  exim="fig_tx_reactions",
  excap="Each product replaces a specific deficit; cryoprecipitate is the concentrated fibrinogen source, which plasma cannot match without an intolerable volume load.")

# ── 5. Urgent warfarin reversal (§12 + §15) ───────────────────────────────────
q("A 76-year-old man is brought to the emergency department 90 minutes after the sudden onset of severe headache followed by left-sided weakness. He takes warfarin for atrial fibrillation. His temperature is 36.8°C (98.2°F), pulse is 82/min and irregular, respirations are 16/min, and blood pressure is 176/94 mm Hg. Physical examination shows left hemiparesis and a left facial droop; he is drowsy but rousable.\n\nLaboratory studies show:\nHemoglobin 13.9 g/dL (N=13.5–17.5 g/dL)\nHematocrit 41% (N=41%–53%)\nPlatelet count 232,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 38 seconds (N=11–15 seconds)\nInternational normalized ratio 4.2 (N=0.8–1.2)\nPartial thromboplastin time 46 seconds (N=25–40 seconds)\n\nCT scan of the head without contrast shows an acute right basal ganglia hemorrhage with mild mass effect. Which of the following is the most appropriate treatment to correct his coagulopathy?",
  ["A. Four-factor prothrombin complex concentrate and intravenous vitamin K",
   "B. Fresh frozen plasma alone",
   "C. Intravenous vitamin K alone",
   "D. Platelet transfusion",
   "E. Protamine sulfate"],
  0,
  "Warfarin depletes the vitamin K-dependent factors II, VII, IX and X. With an intracranial hemorrhage and an international normalized ratio of 4.2, reversal must be immediate and complete, and the combination is a factor concentrate PLUS vitamin K.\n\nWhy both, and why this concentrate:\n• Four-factor prothrombin complex concentrate replaces exactly the missing factors, works within minutes, and comes in a volume of a few hundred millilitres. §12 states plainly that it is more efficacious and faster than plasma, with far less volume — which matters in a 76-year-old with a blood pressure of 176/94 mm Hg.\n• Vitamin K is given at the same time because the concentrate is consumed within hours while warfarin's effect persists for days. Without it the international normalized ratio rebounds. Vitamin K alone takes 6 to 24 hours to work — far too slow for a bleeding brain.\n\nPlasma is the fallback only where prothrombin complex concentrate is unavailable: correcting an international normalized ratio of 4.2 with plasma takes a large volume delivered over hours, with a real risk of circulatory overload.\n\nThe general principle from §12 — do not use plasma when a specific concentrate exists — applies to single factor deficiencies in the same way.",
  {"1": "Plasma alone is the historical answer and is still used where prothrombin complex concentrate is unavailable, which is what makes it the near-miss. It corrects more slowly, requires 10–20 mL/kg (roughly a litre in this man), risks circulatory overload, and without vitamin K the international normalized ratio rebounds as the transfused factors are consumed.",
   "2": "Vitamin K is an essential part of the treatment but takes 6 to 24 hours to restore factor synthesis, because the liver must make the factors. It would be sufficient alone only for an asymptomatic raised international normalized ratio without bleeding.",
   "3": "Platelets would be indicated if the coagulopathy were thrombocytopenic or if he were on an antiplatelet drug with a bleeding threshold — his count is 232,000/mm3. Platelets do nothing about depleted vitamin K-dependent factors.",
   "4": "Protamine sulfate reverses HEPARIN, by binding it directly. It has no effect on warfarin, which acts by inhibiting vitamin K epoxide reductase rather than by circulating as an inhibitable drug."},
  "The blood thinner has knocked out four clotting proteins, and he is bleeding into his brain. He needs those proteins put straight back in, plus vitamin K so his liver starts making them again before the infusion wears off.",
  exim="fig_tx_timeline",
  excap="Plasma-based reversal takes hours and a large volume; the timeline of transfusion-related harm is one reason a concentrated, low-volume product is preferred when it is available.")

# ── 6. Hemophilia A — the specific concentrate (§12) ──────────────────────────
q("A 22-year-old man with severe hemophilia A comes to the emergency department because of a swollen, painful right knee that began 4 hours ago after a fall. His baseline factor VIII activity is less than 1% of normal (N=50%–150%). He has had no inhibitor detected on previous testing. His temperature is 37.0°C (98.6°F), pulse is 92/min, and blood pressure is 122/74 mm Hg. Physical examination shows a warm, tense, distended right knee held in slight flexion, with severely limited range of motion. There is no mucosal bleeding and no petechiae.\n\nLaboratory studies show:\nHemoglobin 13.6 g/dL (N=13.5–17.5 g/dL)\nHematocrit 40% (N=41%–53%)\nPlatelet count 254,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 12.6 seconds (N=11–15 seconds)\nPartial thromboplastin time 74 seconds (N=25–40 seconds)\n\nWhich of the following is the most appropriate treatment?",
  ["A. Cryoprecipitate",
   "B. Desmopressin",
   "C. Factor VIII concentrate",
   "D. Fresh frozen plasma",
   "E. Platelet transfusion"],
  2,
  "This is an acute hemarthrosis in severe hemophilia A, and the treatment is the specific factor that is missing. §12 states the rule directly: plasma is NOT for single factor deficiencies — if a patient is factor VIII deficient, you give factor VIII.\n\nThe reasoning is dose and volume. Recombinant factor VIII concentrate is purified, carries no risk of transfusion-transmitted infection, and delivers a calculable dose — enough to raise activity to roughly 50% for a joint bleed, or higher for intracranial or surgical bleeding. Achieving the same rise with plasma would require a volume measured in litres, because plasma carries factor VIII only at physiologic concentration.\n\nThe urgency is the joint itself. Blood in a joint space triggers synovial inflammation and cartilage destruction, and repeated hemarthroses produce the deforming arthropathy that used to define this disease. Factor is given FIRST, before imaging or aspiration, on clinical suspicion alone.\n\nHis laboratory pattern is the classic one: an isolated prolonged partial thromboplastin time with a normal prothrombin time and a normal platelet count, in a man with deep rather than mucosal bleeding.",
  {"0": "Cryoprecipitate does contain factor VIII, and was used for hemophilia A historically — which is what makes it the near-miss. It would be the answer only where factor concentrate is unavailable. It is unpurified, carries multiple donor exposures, and gives an unpredictable dose compared with a recombinant concentrate.",
   "1": "Desmopressin releases stored von Willebrand factor and factor VIII from endothelium, and is genuinely useful in MILD hemophilia A and in type 1 von Willebrand disease. It works by mobilizing an existing store; with baseline activity under 1% there is nothing to mobilize.",
   "3": "Plasma contains factor VIII at physiologic concentration, so a hemostatic level cannot be reached in any tolerable volume. It is the answer for a MULTIPLE factor deficiency with bleeding — liver disease, disseminated intravascular coagulation, or warfarin when concentrate is unavailable.",
   "4": "Platelets address primary hemostasis, which is intact here: his count is normal, he has no petechiae, and he has no mucosal bleeding. Hemophilia is a defect of the fibrin mesh built over the platelet plug, not of the plug itself."},
  "He is missing one specific clotting protein, so you give him that exact protein back. Giving whole plasma would mean pouring in litres of fluid to deliver the same amount.",
  exim="fig_tx_reactions",
  excap="Blood-bank products versus purified concentrates: a specific factor concentrate avoids the multiple donor exposures that every pooled blood product carries.")

# ── 7. Citrate toxicity in massive transfusion (§12) ──────────────────────────
q("A 34-year-old man is being resuscitated in the trauma bay after a motor vehicle collision with a splenic laceration. Over 50 minutes he has received 10 units of packed red blood cells, 8 units of plasma, and 2 pools of platelets through a rapid infuser under the massive transfusion protocol. He is awake and reports tingling around his mouth and in his fingertips. His temperature is 35.8°C (96.4°F), pulse is 122/min, respirations are 24/min, and blood pressure is 96/58 mm Hg. Physical examination shows carpal spasm when a blood pressure cuff is inflated, and continued oozing from his intravenous sites.\n\nLaboratory studies show:\nIonized calcium 0.82 mmol/L (N=1.12–1.32 mmol/L)\nPotassium 5.1 mEq/L (N=3.5–5.0 mEq/L)\nMagnesium 1.8 mg/dL (N=1.5–2.0 mg/dL)\nSodium 141 mEq/L (N=136–146 mEq/L)\nArterial pH 7.31 (N=7.35–7.45)\n\nElectrocardiography shows a prolonged QT interval. Which of the following best explains these findings?",
  ["A. Chelation of calcium by citrate contained in the transfused units",
   "B. Dilution of plasma proteins by crystalloid resuscitation",
   "C. Hypomagnesemia impairing parathyroid hormone release",
   "D. Release of potassium from stored erythrocytes",
   "E. Respiratory alkalosis increasing calcium binding to albumin"],
  0,
  "Every unit in the refrigerator contains citrate as its anticoagulant, and citrate works by chelating calcium — calcium being the trigger the coagulation cascade cannot proceed without. That is precisely why the unit does not clot in the bag.\n\nTransfuse fast enough and the recipient receives a citrate load faster than the liver can metabolize it → the citrate chelates the PATIENT's ionized calcium → hypocalcemia. The findings follow directly: perioral and digital paresthesias, carpal spasm on cuff inflation (Trousseau sign), QT prolongation, and — because calcium is a cofactor throughout the cascade — impaired hemostasis, which is part of why he continues to ooze.\n\nHepatic metabolism of citrate is the rate-limiting step, so the risk is greatest with rapid transfusion, hypothermia (his temperature is 35.8°C) and liver dysfunction, all of which are common in the exsanguinating trauma patient.\n\nManagement is to monitor ionized calcium during massive transfusion and replace it intravenously. His potassium of 5.1 mEq/L and pH of 7.31 are real accompaniments of massive transfusion, but neither produces tetany or a long QT — hyperkalemia shortens it.",
  {"1": "Dilution of albumin would actually RAISE the ionized fraction of calcium for a given total calcium, since less is protein-bound. The value reported here is the ionized calcium itself, which is not affected by protein concentration.",
   "2": "Severe hypomagnesemia does impair parathyroid hormone secretion and action and causes a refractory hypocalcemia — it would be the answer with a magnesium well below normal, classically in alcohol use disorder or with prolonged diuretic use. His magnesium is 1.8 mg/dL, squarely normal.",
   "3": "Potassium does leak from erythrocytes during storage, and hyperkalemia is a genuine hazard of rapid massive transfusion — his potassium is 5.1 mEq/L. But hyperkalemia causes peaked T waves and a SHORTENED QT interval, and it does not cause tetany or carpal spasm.",
   "4": "Alkalosis increases calcium binding to albumin and can precipitate tetany — the mechanism behind carpopedal spasm during hyperventilation. His arterial pH is 7.31, an acidemia, which moves calcium in the opposite direction."},
  "Donated blood has a chemical added that grabs calcium so the bag will not clot. Pour in ten bags quickly and it grabs the patient's calcium too, which makes his muscles cramp and his heart's electrical timing stretch out.",
  exim="fig_tx_timeline",
  excap="Massive transfusion concentrates several hazards into a short window — citrate load, hypothermia and potassium shifts — alongside the immune reactions shown on this timeline.")

# ── 8. Why the antibodies are there already (§13) ─────────────────────────────
q("A 22-year-old man donates blood for the first time. He has never been transfused, has no children, and has no history of serious illness. Testing of his red cells shows no A antigen and no B antigen. Testing of his plasma shows both anti-A and anti-B antibodies, which are predominantly IgM.\n\nWhich of the following best explains the presence of these antibodies in a person who has never been exposed to transfused blood?",
  ["A. Cross-reaction of autoantibodies with antigens expressed on his own erythrocytes",
   "B. Exposure to A-like and B-like carbohydrate antigens on gut bacteria during infancy",
   "C. Passive transfer of maternal antibody across the placenta before birth",
   "D. Prior exposure to foreign erythrocytes during fetal-maternal circulation",
   "E. Spontaneous somatic mutation within B lymphocyte germinal centers"],
  1,
  "ABO antibodies are NATURALLY OCCURRING, and this is the single fact that makes ABO incompatibility uniquely dangerous.\n\nA newborn has no ABO antibodies. Over the first six months to two years of life the gut is colonized by Escherichia coli and other organisms whose surface carbohydrates closely resemble the A and B antigens. The immune system responds to them, and tolerance ensures antibody is made only against the antigen the person does NOT express. By early childhood everybody carries the predictable mirror-image antibody, with no transfusion or pregnancy required.\n\nHe is group O — no A antigen, no B antigen — so he carries both anti-A and anti-B, and is an ocean of both.\n\nTwo consequences follow. First, the blood bank types every sample twice as a cross-check: the front type (antigens on the cells) must mirror the back type (antibodies in the plasma), and any disagreement stops the release of blood. Second, because these antibodies are IgM and IgM fixes complement extremely efficiently, an ABO-incompatible transfusion causes immediate INTRAVASCULAR hemolysis — no prior exposure needed, no sensitizing event, and a reaction that begins within minutes.\n\nContrast the alloantibodies to RhD, Kell, Duffy and Kidd: those are IgG, require prior exposure through transfusion or pregnancy, and cause slower extravascular hemolysis.",
  {"0": "An autoantibody against his own erythrocytes would cause autoimmune hemolytic anemia and a positive direct antiglobulin test. These antibodies are directed at antigens he does not express, which is the opposite situation — the immune system working exactly as intended.",
   "2": "Maternal IgG does cross the placenta and protects the infant for the first months of life, but ABO antibodies are predominantly IgM, which does not cross. Maternal antibody also wanes by about 6 months, whereas his are lifelong and self-produced.",
   "3": "Fetal-maternal exchange of erythrocytes is the sensitizing route for RhD alloimmunization in the MOTHER, and is one of only two routes of exposure to foreign red cells. It produces unpredictable IgG alloantibodies in some people, not the universal IgM anti-A and anti-B found in everyone.",
   "4": "Somatic hypermutation refines antibody affinity after an antigen has been encountered; it does not create specificities out of nothing. Something must present an A-like or B-like epitope first, which is what the gut flora provides."},
  "Bacteria that settle in a baby's gut happen to wear sugar coats that look like blood group markers. The immune system learns to attack whichever ones the body does not have, so everyone ends up with those antibodies without ever seeing donated blood.",
  exim="fig_abo",
  excap="The ABO system: each phenotype carries antibodies against precisely the antigens it lacks — the mirror image the blood bank checks on every sample.")

# ── 9. Emergency release (§13) ────────────────────────────────────────────────
q("An unidentified man in his twenties is brought to the emergency department by paramedics after a high-speed motor vehicle collision. He is unresponsive, and there is no time to obtain a blood sample before transfusion is required. His pulse is 142/min, respirations are 30/min, and blood pressure is 68/40 mm Hg. Physical examination shows a rigid, distended abdomen and pallor. Focused abdominal ultrasonography shows free intraperitoneal fluid, and he is taken directly to the operating room. The blood bank has adequate stocks of every ABO and RhD type, but supplies of RhD-negative units are limited at this time of year.\n\nWhich of the following blood products is most appropriate to transfuse immediately?",
  ["A. Group A RhD-positive red blood cells",
   "B. Group AB RhD-negative red blood cells",
   "C. Group O RhD-negative red blood cells",
   "D. Group O RhD-positive red blood cells",
   "E. Type-specific red blood cells after a full crossmatch"],
  3,
  "Two separate decisions are being made here, and the second is the one being tested.\n\nThe ABO decision: group O red cells carry neither A nor B antigen, so no recipient's naturally occurring antibody has anything to attack. Group O is the universal red cell donor, and it is what goes out on emergency release before a type is known.\n\nThe RhD decision is rationing. Only about 15% of the population is RhD negative, and group O RhD negative is only about 6% — roughly 1 in 15 people — so it is a genuinely scarce resource. The consequence of giving RhD-POSITIVE blood to an RhD-negative person is that they may form anti-D. In a male that means potential difficulty with future transfusions; in a girl or woman of childbearing potential it means a future RhD-positive fetus can be destroyed by that IgG antibody crossing the placenta — hemolytic disease of the fetus and newborn.\n\nSo the rule in §13 is explicit: save the RhD-negative units for females of childbearing potential, and give RhD-positive to male trauma patients when supply is tight. He may die while you type him; the cost of the alternative is borne by someone who needs it more.\n\nOnce a sample reaches the blood bank he is switched to type-specific blood.",
  {"0": "Group A red cells carry the A antigen. In a patient of unknown type — who has a 45% chance of being group O or B, and therefore of carrying anti-A — this risks an immediate acute hemolytic transfusion reaction. Emergency release is group O precisely to remove that possibility.",
   "1": "Group AB is the universal red cell RECIPIENT, not donor: its cells carry BOTH A and B antigens and would be attacked by almost any recipient's plasma. The AB inversion applies to plasma products, where AB is the universal donor because its plasma contains neither antibody.",
   "2": "Group O RhD-negative is the correct emergency product for a female of childbearing potential, and it would be the answer if this patient were a young woman. Spending a scarce unit on a male trauma patient when supplies are limited deprives someone for whom alloimmunization carries a much larger consequence.",
   "4": "Waiting for a full crossmatch is correct practice when there is time, but it takes 30 to 60 minutes — longer if an unexpected antibody turns up. He is hypotensive with free intraperitoneal blood and is going to the operating room now; the delay would kill him."},
  "There is no time to find out his blood type, so he gets the type that nobody reacts against. The Rh-negative version is rare and is saved for girls and women, because for them a reaction could harm a future pregnancy.",
  exim="fig_o_neg_compat",
  excap="Group O cells carry no A or B antigen, so no recipient antibody can attack them — the reason group O is the universal red cell donor and the emergency-release product.")

# ── 10. Anti-D alloimmunization (§13) ─────────────────────────────────────────
q("A 24-year-old woman who is RhD negative receives 3 units of RhD-positive packed red blood cells during emergency surgery for a ruptured ectopic pregnancy, because RhD-negative units were unavailable. She recovers and is discharged. She has never been pregnant to term and has no children. Six weeks later, an antibody screen performed before an elective procedure is positive, and antibody identification shows anti-D. Her hemoglobin concentration is 12.6 g/dL (N=12.0–16.0 g/dL) and her direct antiglobulin test is negative.\n\nWhich of the following is the most likely future consequence of this finding?",
  ["A. Anaphylactic reaction to any plasma-containing product",
   "B. Hemolytic disease in a future RhD-positive fetus",
   "C. Post-transfusion purpura within 2 weeks of any future transfusion",
   "D. Transfusion-associated graft-versus-host disease",
   "E. Transfusion-related acute lung injury"],
  1,
  "She has been alloimmunized. Exposure to a foreign red cell antigen — here RhD, through transfusion, one of only two possible routes along with pregnancy — has produced an IgG antibody. Note that forming the antibody caused her no harm at all: her hemoglobin is normal and her direct antiglobulin test is negative, because she has no D-positive cells of her own for the antibody to coat.\n\nThe consequences are all in the future, and the important one is obstetric. Anti-D is IgG, and IgG crosses the placenta. If she later carries an RhD-positive fetus, maternal anti-D will cross, coat fetal erythrocytes, and cause their destruction in the fetal spleen — hemolytic disease of the fetus and newborn, with fetal anemia, hydrops and, after delivery, hyperbilirubinemia and kernicterus. That pregnancy needs specialist monitoring with serial middle cerebral artery Doppler studies and possible intrauterine transfusion.\n\nThe transfusion consequence is real but smaller: she must receive RhD-negative units for life, since the titre may fall below detection and then rise rapidly on re-exposure — the basis of a DELAYED hemolytic transfusion reaction.\n\nThis is exactly why RhD-negative units are rationed to females of childbearing potential, and why anti-D immune globulin is given prophylactically after events that risk fetal-maternal hemorrhage.",
  {"0": "Anaphylaxis to plasma-containing products is the complication of IgA deficiency with anti-IgA antibodies, reacting to the IgA present in donor plasma. It has nothing to do with red cell antigens, and would be the answer in a patient with recurrent sinopulmonary infections and an undetectable serum IgA.",
   "2": "Post-transfusion purpura is a rare, abrupt thrombocytopenia 5 to 10 days after transfusion, caused by antibodies against a platelet antigen — most often HPA-1a — in a previously sensitized patient. It would be the answer if the alloantibody identified were directed at a PLATELET antigen rather than at D.",
   "3": "Transfusion-associated graft-versus-host disease is caused by donor LYMPHOCYTES engrafting in a recipient who cannot reject them, and is prevented by irradiating the product. It occurs in severely immunocompromised patients or with partially HLA-matched donors, and is unrelated to red cell alloantibodies.",
   "4": "Transfusion-related acute lung injury is caused by DONOR anti-HLA antibodies reacting with the recipient's leukocytes. The antibody direction here is the reverse — this patient has made an antibody, which affects her future transfusions and pregnancies rather than causing lung injury."},
  "Her body has learned to recognize a red cell marker she does not carry, and it now makes an antibody against it. That antibody can cross the placenta, so a future baby who inherits that marker from its father could have its red cells destroyed before birth.",
  exim="fig_rh_pregnancy",
  excap="RhD alloimmunization: once anti-D is formed, the IgG antibody crosses the placenta in a later pregnancy and destroys the erythrocytes of an RhD-positive fetus.")

# ── 11. The positive antibody screen (§13) ────────────────────────────────────
q("A 46-year-old woman with menorrhagia is scheduled for hysterectomy. She received 2 units of packed red blood cells 8 years ago after a postpartum hemorrhage. A type and screen is performed: she is group A, RhD positive, and the antibody screen is POSITIVE. An antibody identification panel shows anti-Kell. Her hemoglobin concentration is 9.4 g/dL (N=12.0–16.0 g/dL), hematocrit is 28% (N=36%–46%), reticulocyte count is 1.2% (N=0.5%–1.5%), and her direct antiglobulin test is negative. The blood bank reports that units will take several hours longer than usual to provide.\n\nWhich of the following is the most appropriate action regarding transfusion for this patient?",
  ["A. Administer corticosteroids before each unit is transfused",
   "B. Administer group O RhD-negative red blood cells without crossmatch",
   "C. Perform plasma exchange before transfusion",
   "D. Transfuse Kell antigen-negative, crossmatch-compatible units",
   "E. Transfuse washed red blood cells"],
  3,
  "A positive antibody screen means her plasma contains an antibody that binds donor red cells — this is the INDIRECT antiglobulin test, the 'screen' in type and screen. Her negative DIRECT antiglobulin test confirms the antibody is free in her plasma rather than already coating her own cells, so she is not hemolyzing.\n\nThe antibody was formed by one of the only two routes of exposure to foreign erythrocytes: her transfusion 8 years ago, or her pregnancy. It is IgG. Give her Kell-POSITIVE blood and the antibody will opsonize those cells for splenic clearance — extravascular hemolysis, a failed transfusion, and a delayed hemolytic reaction days later.\n\nSo the units must be Kell antigen NEGATIVE as well as ABO and RhD compatible, and each must then be individually crossmatched. Finding antigen-negative units may require a wider inventory or a reference laboratory, which is the several hours the blood bank is asking for. The requirement is lifelong: an alloantibody titre can drop below the level of detection and still rise explosively on re-exposure, which is why patients carry antibody cards.\n\nThis work is also why chronically transfused patients are difficult. Alloimmunization occurs in 1–3% of the general population but in 20–60% of patients with sickle cell disease, who are exposed repeatedly to minor antigens — Kell, Duffy, Kidd — across a lifetime, and many centres now provide extended antigen-matched blood for them from the start.",
  {"0": "Corticosteroids blunt an immune response over days and have no role in preventing hemolysis of antigen-positive cells transfused now. They would be part of the treatment of warm autoimmune hemolytic anemia, which her negative direct antiglobulin test excludes.",
   "1": "Uncrossmatched group O RhD-negative blood is for an exsanguinating patient who cannot wait. It addresses only ABO and RhD; those units are as likely as any others to be Kell positive, so this would deliver precisely the cells her antibody attacks. She is having elective surgery and can wait.",
   "2": "Plasma exchange removes circulating antibody and is used in thrombotic thrombocytopenic purpura and some antibody-mediated diseases. It would not durably remove an alloantibody — the memory B cells remain and the antibody returns — and it exposes her to a procedure when simply selecting the right units solves the problem.",
   "4": "Washing removes plasma proteins from the unit and is used for recurrent severe allergic reactions and for IgA-deficient recipients. It does nothing about antigens on the donor CELL surface, which is where the Kell antigen sits."},
  "Her blood carries an antibody against a marker some donors have, left over from a transfusion years ago. The lab has to hunt for units that lack that marker, which is why the blood takes longer to arrive.",
  exim="fig_tx_reactions",
  excap="The delayed hemolytic reaction that antigen-negative units are selected to avoid: recipient antibody formed after earlier sensitization binds donor cells and destroys them extravascularly.")

# ── 12. Delayed hemolytic transfusion reaction (§14 + §13) ────────────────────
q("A 62-year-old man received 3 units of packed red blood cells 8 days ago for anemia from a gastrointestinal hemorrhage, which has since been treated endoscopically. He returns to the office because of fatigue and mild yellowing of his eyes over the past 2 days. He has had no fever, chills, dyspnea, back pain, or dark urine. He was transfused once before, 15 years ago. His temperature is 37.1°C (98.8°F), pulse is 88/min, respirations are 16/min, and blood pressure is 128/76 mm Hg. Physical examination shows mild scleral icterus; the abdomen is soft and the stool is brown and negative for occult blood.\n\nLaboratory studies show:\nHemoglobin 8.2 g/dL (N=13.5–17.5 g/dL)\nHematocrit 25% (N=41%–53%)\nReticulocyte count 4.6% (N=0.5%–1.5%)\nPlatelet count 246,000/mm3 (N=150,000–400,000/mm3)\nLactate dehydrogenase 410 U/L (N=45–200 U/L)\nTotal bilirubin 2.8 mg/dL (N=0.1–1.0 mg/dL)\nDirect bilirubin 0.3 mg/dL (N=0.0–0.3 mg/dL)\nHaptoglobin 18 mg/dL (N=30–200 mg/dL)\n\nHis hemoglobin concentration was 10.6 g/dL at discharge 6 days ago. The direct antiglobulin test is now positive, and an antibody screen that was negative before the transfusion now detects anti-Jka. Which of the following is the most likely diagnosis?",
  ["A. Acute hemolytic transfusion reaction",
   "B. Autoimmune hemolytic anemia",
   "C. Delayed hemolytic transfusion reaction",
   "D. Febrile nonhemolytic transfusion reaction",
   "E. Post-transfusion purpura"],
  2,
  "Everything here is defined by the TIMING and by an antibody that was not there before.\n\nHe was sensitized to the Kidd antigen Jka by his transfusion 15 years ago. The titre fell below the level of detection, so his pre-transfusion antibody screen was negative and compatible-looking units were issued. Re-exposure 8 days ago triggered an anamnestic (memory) response → IgG anti-Jka rose over days → it coated the transfused Jka-positive cells → splenic macrophages removed them.\n\nThe result is exactly what he shows: a gradual fall in hemoglobin 3 to 10 days after transfusion, jaundice with unconjugated hyperbilirubinemia, a raised lactate dehydrogenase, a modestly reduced haptoglobin, a reticulocytosis, and a newly POSITIVE direct antiglobulin test — all without fever, hypotension or dark urine, because IgG-mediated destruction is extravascular rather than intravascular.\n\nKidd antibodies are notorious for this behavior; 'Kidd antibodies are evanescent' is the phrase. It is also the argument for lifelong antigen-negative transfusion once an alloantibody is identified, and for antibody cards that travel with the patient.\n\nManagement is largely supportive, with Jka-negative units for any future transfusion.",
  {"0": "An acute hemolytic reaction from ABO incompatibility begins within MINUTES of starting the unit, with fever, back and flank pain, hypotension, pink plasma and hemoglobinuria — IgM fixing complement and lysing cells inside the vessel. His reaction appeared 8 days later with none of those features.",
   "1": "Warm autoimmune hemolytic anemia also gives a positive direct antiglobulin test with extravascular hemolysis, which makes it the closest competitor. The antibody there is an AUTOantibody reacting with the patient's own cells; here a specific ALLOantibody against a donor antigen has appeared in a patient whose screen was negative days earlier.",
   "3": "A febrile nonhemolytic reaction is fever and chills DURING or shortly after the transfusion, caused by cytokines from donor leukocytes, with no hemolysis at all. He has no fever, and his laboratory studies show unmistakable hemolysis.",
   "4": "Post-transfusion purpura appears 5 to 10 days after transfusion — the same window — but as severe THROMBOCYTOPENIA with bleeding, caused by antibodies against a platelet antigen. His platelet count is 246,000/mm3 and his problem is anemia."},
  "Years ago a transfusion taught his immune system to recognize a red cell marker, and the memory faded below what tests can see. The new units carried that marker again, so his immune system woke up over the following week and quietly destroyed them.",
  exim="fig_tx_timeline",
  excap="The reaction timeline: DHTR (delayed hemolytic transfusion reaction) sits days to weeks out, well separated from the reactions that occur within the first 6 hours.")

# ── 13. Plasma compatibility runs backwards (§13 + §12) ───────────────────────
q("A 58-year-old man with group A, RhD-positive blood is bleeding after a liver laceration and has a prothrombin time of 26 seconds (N=11–15 seconds) with an international normalized ratio of 2.6 (N=0.8–1.2). Plasma transfusion is indicated. The blood bank reports that no group A plasma is immediately available; group B, group AB, and group O plasma units are in stock, and prothrombin complex concentrate is not available at this hospital.\n\nWhich of the following plasma units may be transfused to this patient without risk of hemolysis?",
  ["A. Group AB plasma", "B. Group B plasma", "C. Group O plasma", "D. Plasma of any ABO group"],
  0,
  "For red cells you ask whether the RECIPIENT's antibodies will attack the DONOR's antigens. For plasma the question inverts, because plasma carries the antibodies rather than the cells: you ask whether the DONOR's antibodies will attack the RECIPIENT's antigens.\n\nGroup AB plasma contains neither anti-A nor anti-B — an AB person expresses both antigens and therefore makes neither antibody. It can be given to anyone, which makes group AB the universal PLASMA donor, the exact mirror image of group O as the universal red cell donor.\n\nThis patient is group A, so his erythrocytes display the A antigen. Group B plasma contains anti-A and group O plasma contains both anti-A and anti-B; either would deliver antibody directed at his own circulating cells and cause hemolysis. Only AB plasma is safe.\n\nThe same inversion makes group O the universal plasma RECIPIENT — an O person has no A or B antigen for any donor's antibody to attack.\n\nThe reason to derive the table rather than memorize it is that reversing the two systems is one of the commonest errors in transfusion medicine, and the arithmetic takes about five seconds if you remember which component carries which.",
  {"1": "Group B plasma contains anti-A. This patient's red cells carry the A antigen, so transfusing it delivers an antibody aimed directly at his own circulating erythrocytes. It would be appropriate for a group B or a group O recipient.",
   "2": "Group O plasma is the most dangerous of the three here: an O donor carries BOTH anti-A and anti-B. Group O is the universal donor for RED CELLS only — its cells lack antigens — and reversing that rule for plasma is the classic error this item tests.",
   "3": "Plasma does require ABO matching, for the reason above. It is RhD matching that plasma does not require, since plasma contains no red cells and therefore no D antigen — which is a different statement and the likely source of this misconception."},
  "Red cells and plasma work in opposite directions: cells carry the markers, plasma carries the antibodies. Plasma from an AB donor has no antibodies at all, so it is safe for everyone.",
  exim="fig_abo",
  excap="Antigens on the cell, antibodies in the plasma: group AB has both antigens and neither antibody, which makes it the universal plasma donor and the universal red cell recipient.")

# ── 14. Acute hemolytic transfusion reaction (§14) ────────────────────────────
q("A 3-year-old boy is receiving a transfusion of packed red blood cells on a busy postoperative ward. Ten minutes into the unit he becomes agitated, cries out with pain in his back and flank, and vomits. The transfusion is stopped. His temperature is 39.1°C (102.4°F), pulse is 168/min, respirations are 38/min, and blood pressure is 68/38 mm Hg. Physical examination shows mottled skin and oozing from his intravenous site. A blood sample drawn and centrifuged at the bedside shows PINK plasma, and his urine is dark red. The direct antiglobulin test is positive.\n\nLaboratory studies show:\nHemoglobin 7.2 g/dL (N=11.5–15.5 g/dL)\nHematocrit 22% (N=35%–45%)\nPlatelet count 88,000/mm3 (N=150,000–400,000/mm3)\nLactate dehydrogenase 980 U/L (N=45–200 U/L)\nHaptoglobin <10 mg/dL (N=30–200 mg/dL)\nFibrinogen 118 mg/dL (N=200–400 mg/dL)\n\nWhich of the following is the most likely cause of these findings?",
  ["A. ABO-incompatible erythrocytes in the transfused unit",
   "B. Bacterial contamination of the transfused unit",
   "C. Cytokines released by donor leukocytes during storage",
   "D. Donor anti-HLA antibodies reacting with recipient leukocytes",
   "E. Recipient antibodies directed against donor IgA"],
  0,
  "Pink plasma, dark red urine and a positive direct antiglobulin test within minutes of starting a unit is an acute hemolytic transfusion reaction from ABO incompatibility — the full intravascular signature, with back and flank pain as its characteristic symptom.\n\nThe immunology is fast because the antibody is already there. ABO antibodies are naturally occurring IgM, and IgM fixes complement extremely efficiently → complement runs to completion on the transfused cells → they lyse inside the vessel → free hemoglobin appears in plasma (hemoglobinemia) and is filtered into urine (hemoglobinuria). Free heme is nephrotoxic, so the kidney is the organ at immediate risk; his falling fibrinogen and platelets with oozing show disseminated intravascular coagulation beginning as well.\n\nIt is classified as a NEVER EVENT because the incompatibility is entirely predictable and entirely preventable. In practice it happens through 'wrong blood in tube': a sample drawn from one patient is labelled with another patient's pre-printed label — the classic setting being one nurse caring for two patients in a double room. The blood bank then types that sample perfectly correctly. Everything downstream is flawlessly wrong.\n\nThis is why the clerical check — unit label against patient identity — is step 3 of the reaction algorithm, after stopping the transfusion and keeping the line open with saline.",
  {"1": "Bacterial contamination produces fever, rigors and rapid hypotension, so the early hemodynamic picture overlaps — it is the closest competitor. It would be the answer with a platelet unit (stored at room temperature, where bacteria grow) and organisms on the unit's Gram stain and culture, and it does not produce hemoglobinemia, hemoglobinuria or a positive direct antiglobulin test.",
   "2": "Cytokines from donor leukocytes cause the febrile NONhemolytic reaction — fever and chills, self-limited, with no hemolysis, which is the point of its name. It would be the answer with fever and no evidence of red cell destruction, and it is prevented by leukocyte reduction.",
   "3": "Donor anti-HLA antibodies reacting with recipient leukocytes cause transfusion-related acute lung injury, which would be the answer with hypoxia and bilateral pulmonary opacities within 6 hours. He has no respiratory findings, and that reaction does not lyse erythrocytes.",
   "4": "Recipient anti-IgA antibodies cause anaphylaxis — hypotension, dyspnea and throat tightness after a tiny volume, characteristically without fever. His fever, flank pain and laboratory evidence of red cell destruction do not fit, and anaphylaxis does not produce hemoglobinuria."},
  "He was given blood of the wrong type, and antibodies he was born with attacked it immediately, bursting the donated cells inside his blood vessels. The freed hemoglobin turns the plasma pink and the urine red, and it can wreck the kidneys.",
  exim="fig_tx_reactions",
  excap="Acute hemolytic reaction, far left: donor cells bearing A and/or B antigens meet the recipient's naturally occurring anti-A or anti-B and are destroyed.")

# ── 15. TRALI (§14) ───────────────────────────────────────────────────────────
q("A 59-year-old woman with myelodysplastic syndrome receives a unit of packed red blood cells in the outpatient infusion center. Ninety minutes after the transfusion begins she develops dyspnea and a dry cough. She has no chest pain, no urticaria, and no back pain. She has no history of heart failure or kidney disease. Her temperature is 38.2°C (100.8°F), pulse is 118/min, respirations are 34/min, and blood pressure is 86/50 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 84%. Physical examination shows diffuse crackles in both lung fields; the jugular venous pulse is not elevated, there is no peripheral edema, and there is no third heart sound.\n\nLaboratory studies show:\nHemoglobin 8.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 25% (N=36%–46%)\nB-type natriuretic peptide 62 pg/mL (N=<100 pg/mL)\nCreatinine 0.8 mg/dL (N=0.6–1.2 mg/dL)\n\nChest radiography shows bilateral pulmonary opacities. Intravenous furosemide is administered without improvement in her oxygenation. Which of the following is the most likely diagnosis?",
  ["A. Acute hemolytic transfusion reaction",
   "B. Anaphylactic transfusion reaction",
   "C. Febrile nonhemolytic transfusion reaction",
   "D. Transfusion-associated circulatory overload",
   "E. Transfusion-related acute lung injury"],
  4,
  "Hypoxia with bilateral pulmonary opacities within 6 hours of a transfusion is either TRALI or TACO, and three findings separate them here: she is HYPOTENSIVE, her jugular venous pressure is NORMAL, and she did not improve with diuresis.\n\nTRALI is an immune injury to the pulmonary capillaries. The classic donor is a woman sensitized during pregnancy — exposure to fetal cells carrying paternal tissue antigens leads her to make anti-HLA antibodies, which harm her not at all; 14–20% of parous women carry them. Transfused in her plasma, those antibodies react with the RECIPIENT's leukocytes, which agglutinate in the pulmonary capillaries → acute lung injury with an ARDS picture on imaging. Management is supportive, including ventilatory support; diuresis does not help because the problem is capillary permeability, not volume.\n\nTACO is the mirror image: too much volume too fast, with HYPERTENSION, a raised jugular venous pressure, a raised B-type natriuretic peptide, and improvement with diuresis. Her B-type natriuretic peptide is 62 pg/mL and she received a single unit.\n\nThe memory hook: TACO = Too much volume; TRALI = the donor's antibodies attacked the Lung.\n\nTRALI is now genuinely rare, because blood centres screen female donors for anti-HLA antibodies and avoid making high-plasma-volume products from those who have them — one of transfusion medicine's clearest public health successes.",
  {"0": "An acute hemolytic reaction produces fever, back and flank pain, hypotension, pink plasma and hemoglobinuria within minutes. It would be the answer with laboratory evidence of hemolysis and a positive direct antiglobulin test; she has respiratory failure with no evidence of red cell destruction.",
   "1": "Anaphylaxis causes hypotension with dyspnea and throat tightness after a very small volume, usually with urticaria and characteristically WITHOUT fever, and is associated with IgA deficiency. It does not produce bilateral pulmonary opacities on a chest radiograph.",
   "2": "A febrile nonhemolytic reaction gives fever and chills alone and is self-limited — she is febrile, which is why it is on the list, since fever accompanies TRALI too. It does not cause hypoxemia, hypotension, or infiltrates.",
   "3": "Circulatory overload is the near-miss, and the distinction is the highest-yield pair in this section. It would be the answer with HYPERTENSION, a distended jugular venous pulse, a raised B-type natriuretic peptide, and improvement after furosemide — and is more likely after several units given rapidly to an elderly patient with cardiac or renal disease."},
  "Antibodies in the donor's plasma attacked her white cells, which then clogged and inflamed the small vessels of her lungs. It looks like fluid overload on the x-ray, but her heart is fine and a water pill does not help.",
  exim="fig_tx_reactions",
  excap="TRALI, center: antibodies carried in the donor plasma activate the recipient's granulocytes within the pulmonary circulation.")

# ── 16. TACO — predicting the findings (§14) ──────────────────────────────────
q("An 81-year-old woman with chronic kidney disease and a history of heart failure with preserved ejection fraction is admitted with symptomatic anemia and a hemoglobin concentration of 6.4 g/dL. She weighs 48 kg (106 lb). Two units of packed red blood cells are ordered, and because the nursing shift is ending both units are infused over a total of 75 minutes. She has no fever at any point. Twenty minutes after the second unit finishes she becomes acutely dyspneic and cannot lie flat. Pulse oximetry on room air shows an oxygen saturation of 87%, and chest radiography shows bilateral opacities with small pleural effusions.\n\nWhich of the following sets of additional findings is most likely in this patient?\n\n    Blood pressure | Jugular venous pressure | B-type natriuretic peptide | Response to diuresis",
  ["A. Decreased, elevated, increased, improvement",
   "B. Decreased, normal, normal, no improvement",
   "C. Increased, elevated, increased, improvement",
   "D. Increased, normal, increased, no improvement",
   "E. Increased, normal, normal, improvement"],
  2,
  "Everything in the setup points to volume, not immunity: an 81-year-old weighing 48 kg with chronic kidney disease and diastolic heart failure, given two units in 75 minutes — roughly 600 mL into a patient whose heart and kidneys cannot accommodate it, at a rate chosen for the nursing shift rather than for her physiology. This is transfusion-associated circulatory overload.\n\nThe predicted row follows from hydrostatic pulmonary edema: blood pressure INCREASED, jugular venous pressure ELEVATED, B-type natriuretic peptide INCREASED as the ventricle is stretched, and IMPROVEMENT with diuresis because removing volume removes the cause.\n\nHold that against TRALI, which produces the same hypoxia and the same bilateral opacities: blood pressure decreased, jugular venous pressure normal, B-type natriuretic peptide normal, and no response to diuresis, because the lung injury is a permeability problem rather than a pressure problem. That is the row-by-row contrast the option set is built from, and knowing only one column is not enough to answer.\n\nPrevention is in the order, not the response: transfuse one unit at a time, slowly (over 2 to 4 hours), reassess between units, and consider prophylactic diuretic in a small elderly patient with cardiac or renal disease.",
  {"0": "This row has the venous pressure, natriuretic peptide and diuretic response of circulatory overload but the blood pressure of TRALI — right in three columns and wrong in the one that matters most at the bedside. Hypotension with overload would suggest cardiogenic shock, not the picture described.",
   "1": "This is the TRALI row in full: hypotension, a normal jugular venous pressure, a normal B-type natriuretic peptide, and no response to diuresis. It would be the answer if the mechanism were donor anti-HLA antibodies injuring the pulmonary capillaries — but nothing here suggests that, and the rate and volume of transfusion in a frail 48-kg patient do.",
   "3": "Hypertension with a raised natriuretic peptide but a NORMAL jugular venous pressure and no response to diuresis is internally inconsistent: a ventricle stretched enough to release natriuretic peptide transmits that pressure back to the neck veins, and hydrostatic edema responds to volume removal.",
   "4": "Hypertension with an entirely normal jugular venous pressure and natriuretic peptide describes a patient who is not volume overloaded, in which case there would be no reason for diuresis to help. The combination does not correspond to any of the transfusion reactions."},
  "A small, frail woman with a weak heart and kidneys got two bags of blood in just over an hour. Her circulation simply could not hold the extra volume, so it backed up into her lungs — and draining the fluid off fixes it.",
  exim="fig_tx_timeline",
  excap="Circulatory overload and TRALI both appear within hours of the transfusion, which is why the distinguishing findings — pressure, venous filling, and the response to diuresis — carry the diagnosis rather than the timing.")

# ── 17. Preventing the febrile nonhemolytic reaction (§14) ────────────────────
q("A 67-year-old man with myelodysplastic syndrome requires red blood cell transfusion every 3 weeks. During each of his last three transfusions he has developed a temperature rise of 1.5°C to 2°C with chills and rigors, beginning about 45 minutes into the unit and resolving within a few hours. On each occasion the transfusion was stopped, a clerical check confirmed the correct unit and patient, and the investigation showed no hemolysis: the plasma was straw-colored, the direct antiglobulin test was negative, the haptoglobin was unchanged, and cultures of the unit were sterile. His blood pressure remained stable throughout each episode, and he has never had urticaria, dyspnea, or hypoxia.\n\nWhich of the following modifications to the blood product is most likely to prevent these episodes?",
  ["A. Irradiation of the product",
   "B. Leukocyte reduction of the product",
   "C. Pathogen reduction of the product",
   "D. Use of products from IgA-deficient donors",
   "E. Washing of the product"],
  1,
  "Fever and chills during or shortly after a transfusion, with no hemolysis, no hypotension and sterile cultures, is a febrile NONhemolytic transfusion reaction — the commonest reaction there is, occurring multiple times a week at a large centre.\n\nThe mechanism explains the fix. The product is living cells in a bag, and while they survive they release cytokines; donor leukocytes are the main source, both by accumulating cytokines during storage and by reacting with recipient antibodies. Remove the white cells before storage — leukocyte reduction, a filter applied before bagging — and the reaction rate falls sharply. It is now standard of care on essentially every US product, and it also reduces HLA alloimmunization and cytomegalovirus transmission.\n\nThe diagnosis is one of exclusion, and this vignette does the excluding explicitly: straw-colored plasma and a negative direct antiglobulin test rule out an acute hemolytic reaction, sterile cultures with stable blood pressure rule out bacterial contamination, and the absence of urticaria, dyspnea and hypoxia rules out the allergic reactions and TRALI. That work has to be done every time, because a febrile reaction looks identical at onset to the two that can kill him.",
  {"0": "Irradiation damages the DNA of residual donor lymphocytes so they cannot proliferate in the recipient, and it is the only defence against transfusion-associated graft-versus-host disease. It kills the lymphocytes' ability to divide but does not remove them or the cytokines they have already released, so it does not prevent febrile reactions.",
   "2": "Pathogen reduction inactivates residual bacteria, viruses and parasites, and was introduced chiefly to reduce the risk from bacterially contaminated platelets. It would be the answer if his reactions were septic — but his cultures are sterile and his blood pressure never falls.",
   "3": "Products from IgA-deficient donors are for a patient who is IgA deficient and has formed anti-IgA, in whom a tiny volume of plasma causes anaphylaxis. That reaction is hypotension and airway compromise WITHOUT fever, the opposite of his pattern.",
   "4": "Washing removes plasma proteins from the unit and is used for recurrent severe allergic reactions and for IgA-deficient recipients. It is a reasonable second-line step for refractory febrile reactions, but it is labor-intensive, shortens the unit's shelf life, and is not the primary prevention for this reaction."},
  "The white cells in donated blood leak chemical messengers that make people feel feverish and shivery. Filtering those white cells out before the blood is stored largely prevents it.",
  exim="fig_tx_reactions",
  excap="Febrile nonhemolytic reaction, second column: cytokines from long-stored donor leukocytes, plus recipient antibodies against those white cells.")

# ── 18. Anaphylaxis and IgA deficiency (§14) ──────────────────────────────────
q("A 29-year-old woman with a history of recurrent sinus and respiratory infections since childhood receives plasma during surgery for a postpartum hemorrhage. Approximately 5 mL has been infused when she develops flushing, throat tightness, wheezing, and hypotension. She has no fever. Her temperature is 36.9°C (98.4°F), pulse is 136/min, respirations are 32/min, and blood pressure is 62/34 mm Hg. Pulse oximetry shows an oxygen saturation of 88%. Physical examination shows diffuse urticaria, audible stridor, and diffuse expiratory wheeze. The transfusion is stopped, epinephrine is administered, and she stabilizes.\n\nSubsequent testing shows an undetectable serum IgA concentration, a serum IgG concentration of 1,180 mg/dL (N=650–1500 mg/dL), and a serum IgM concentration of 142 mg/dL (N=50–300 mg/dL). The direct antiglobulin test is negative and there is no evidence of hemolysis.\n\nWhich of the following best explains this reaction?",
  ["A. Complement activation by recipient IgM directed against donor A and B antigens",
   "B. Cytokines that accumulated in the product during storage",
   "C. Donor anti-HLA antibodies reacting with recipient granulocytes",
   "D. Recipient anti-IgA antibodies reacting with IgA in the donor plasma",
   "E. Residual donor lymphocytes engrafting in the recipient"],
  3,
  "Anaphylaxis after a tiny volume — the classic description is a reaction after 5 mL — in a patient with recurrent sinopulmonary infections and an undetectable serum IgA is selective IgA deficiency with anti-IgA antibodies.\n\nThe mechanism: a person who makes no IgA can recognize it as foreign and form anti-IgA. EVERY plasma-containing product contains donor IgA. On exposure, the antibody reacts with that IgA, mast cells degranulate, and a full anaphylactic reaction follows within minutes — hypotension, bronchospasm, laryngeal edema, urticaria, and characteristically NO fever.\n\nTwo features separate it from the far commoner mild allergic reaction, which §14 describes with the strawberry model: a soluble allergen from the donor's diet meets pre-formed recipient IgE and produces hives and itching with stable vital signs, treated with an antihistamine, after which the transfusion can often be resumed cautiously. Anaphylaxis is hemodynamic and airway-threatening, needs epinephrine, and the unit is never restarted.\n\nHer future transfusions must use washed cellular products — washing removes the plasma and therefore the IgA — or products from IgA-deficient donors. Selective IgA deficiency is the commonest primary immunodeficiency, affecting roughly 1 in 500 people, which is why this scenario is worth recognizing immediately.",
  {"0": "Complement activation by IgM anti-A or anti-B is the acute hemolytic transfusion reaction, which would be the answer with fever, back and flank pain, pink plasma, hemoglobinuria and a positive direct antiglobulin test. The stem states explicitly that there is no hemolysis.",
   "1": "Storage cytokines cause the febrile nonhemolytic reaction — fever and chills with stable vital signs. She has no fever at all, and fever is precisely what that reaction is named for.",
   "2": "Donor anti-HLA antibodies reacting with recipient granulocytes cause TRALI, which produces hypoxia with bilateral pulmonary opacities within 6 hours. She has bronchospasm and stridor with urticaria — an airway and hemodynamic reaction — not a radiographic lung injury.",
   "4": "Donor lymphocytes engrafting in the recipient cause transfusion-associated graft-versus-host disease, which appears 1 to 6 weeks later as pancytopenia, rash, diarrhea and liver dysfunction, and is prevented by irradiation. The time course alone excludes it."},
  "She does not make one type of antibody at all, so her immune system treats it as a foreign substance. Donated plasma is full of it, and a few millilitres were enough to trigger a full allergic collapse.",
  exim="fig_tx_reactions",
  excap="Anaphylaxis, fourth column: an IgA-deficient host with anti-IgA meets the IgA present in donor plasma, and mast cells degranulate.")

# ── 19. The septic platelet unit (§14) ────────────────────────────────────────
q("A 44-year-old man receiving consolidation chemotherapy for acute myeloid leukemia is transfused with a single apheresis platelet unit for a platelet count of 8,000/mm3. Twenty minutes into the transfusion he develops shaking chills and becomes confused. The transfusion is stopped. His temperature is 39.9°C (103.8°F), pulse is 148/min, respirations are 32/min, and blood pressure is 76/40 mm Hg. Physical examination shows warm extremities and mottled skin; there is no urticaria, no jugular venous distention, and the lungs are clear. A clerical check confirms that the unit and the patient identifiers match.\n\nLaboratory studies show:\nHemoglobin 9.1 g/dL (N=13.5–17.5 g/dL)\nHematocrit 27% (N=41%–53%)\nLeukocyte count 400/mm3 (N=4500–11,000/mm3)\nPlatelet count 9,000/mm3 (N=150,000–400,000/mm3)\nLactate 4.2 mmol/L (N=0.5–2.2 mmol/L)\n\nHis plasma is straw-colored, the direct antiglobulin test is negative, and his urine is clear yellow. Gram stain of the residual product shows gram-positive cocci in clusters. Which of the following is the most likely diagnosis?",
  ["A. Acute hemolytic transfusion reaction",
   "B. Anaphylactic transfusion reaction",
   "C. Febrile nonhemolytic transfusion reaction",
   "D. Septic transfusion reaction",
   "E. Transfusion-associated circulatory overload"],
  3,
  "High fever with rigors, hypotension and rapid deterioration during a PLATELET transfusion, with organisms on the Gram stain of the residual product, is a septic transfusion reaction.\n\nPlatelets are the exception to everything in the blood bank. Every other product is refrigerated, but cold activates platelets and they are cleared rapidly after transfusion, so platelets are stored at 20–24°C on a continuously agitating rotator. Room temperature is also a growth medium: any bacteria introduced during collection can multiply, which is why the shelf life is 5 to 7 days rather than 42, and why a bacterially contaminated platelet is the most common INFECTIOUS risk of transfusion today — well ahead of any virus.\n\nThe route of contamination is worth knowing: when the donor's arm is accessed, the needle bore punches out a small plug of skin carrying the donor's flora into the bag — which is why skin organisms such as Staphylococcus species are typical, matching the gram-positive cocci in clusters here. Three countermeasures follow: a diversion pouch that captures and discards the first ~100 mL of the donation, scrupulous arm preparation, and pathogen reduction.\n\nManagement is broad-spectrum antibiotics and hemodynamic support immediately, with cultures of both the patient and the unit. His neutropenia makes this doubly urgent.",
  {"0": "An acute hemolytic reaction also causes fever and hypotension within minutes, which makes it the near-miss, but it would come with back and flank pain, pink plasma, hemoglobinuria and a POSITIVE direct antiglobulin test. His plasma is straw-colored, his urine is clear, and his antiglobulin test is negative.",
   "1": "Anaphylaxis produces hypotension and airway compromise after a tiny volume, typically with urticaria and characteristically WITHOUT fever. A temperature of 39.9°C with rigors is not an anaphylactic reaction, and he has no urticaria or bronchospasm.",
   "2": "A febrile nonhemolytic reaction is the commonest cause of fever during transfusion and is the diagnosis of exclusion here — but it is self-limited and does NOT cause hypotension, confusion, or a lactate of 4.2 mmol/L. The organisms on the Gram stain settle it.",
   "4": "Circulatory overload causes dyspnea with hypertension, distended neck veins and pulmonary edema, and follows large or rapid volumes. He received a single unit, has clear lungs, no jugular venous distention, and is hypotensive rather than hypertensive."},
  "Platelets have to be kept at room temperature, which is also a comfortable temperature for bacteria. A few skin bacteria that got into the bag during donation grew there, and he received a bagful of them straight into his bloodstream.",
  exim="fig_tx_timeline",
  excap="Septic and other acute reactions declare themselves within the first hours of transfusion — the window in which fever plus hypotension must be assumed dangerous until proved otherwise.")

# ── 20. Transfusion-associated graft-versus-host disease (§14) ────────────────
q("A 46-year-old man with Hodgkin lymphoma receiving chemotherapy is admitted with anemia and is transfused with 2 units of packed red blood cells donated by his brother, who volunteered as a directed donor. He is discharged the next day. Three weeks later he returns with a diffuse erythematous rash over his trunk and palms, profuse watery diarrhea, and fever. His temperature is 38.7°C (101.7°F), pulse is 104/min, and blood pressure is 108/66 mm Hg. Physical examination shows a widespread maculopapular rash and diffuse abdominal tenderness without peritoneal signs.\n\nLaboratory studies show:\nHemoglobin 7.4 g/dL (N=13.5–17.5 g/dL)\nHematocrit 22% (N=41%–53%)\nLeukocyte count 600/mm3 (N=4500–11,000/mm3)\nPlatelet count 18,000/mm3 (N=150,000–400,000/mm3)\nReticulocyte count 0.2% (N=0.5%–1.5%)\nAlanine aminotransferase 210 U/L (N=10–40 U/L)\nTotal bilirubin 4.1 mg/dL (N=0.1–1.0 mg/dL)\n\nBone marrow biopsy shows a markedly hypocellular marrow. Which of the following measures would most likely have prevented this complication?",
  ["A. Irradiation of the product",
   "B. Leukocyte reduction of the product",
   "C. Pathogen reduction of the product",
   "D. Use of ABO-identical units",
   "E. Washing of the product"],
  0,
  "Pancytopenia with a hypocellular marrow, rash, diarrhea and liver dysfunction appearing 1 to 6 weeks after a transfusion is transfusion-associated graft-versus-host disease, and the only defence is IRRADIATION of the product.\n\nThe graft is the blood product itself. Residual donor lymphocytes in the unit engraft in a recipient who cannot reject them, proliferate, and attack the recipient's tissues — skin, gut, liver, and critically the BONE MARROW, which is why every cell line collapses. That marrow involvement is what distinguishes it from graft-versus-host disease after stem cell transplantation, where the marrow is the graft and is spared; here treatment is largely futile and mortality exceeds 90%.\n\nHe carries both risk factors named in §14. His disease and chemotherapy leave him unable to reject donor lymphocytes. And his donor is his BROTHER: partial HLA matching means the donor's cells can look sufficiently 'self' to escape recognition while the donor lymphocytes still recognize the recipient's non-shared antigens as foreign — one-way recognition. This is exactly why directed donation from relatives is discouraged, and why any product from a relative must be irradiated regardless of the recipient's immune status.\n\nIrradiation damages the DNA of residual white cells so they cannot proliferate; red cells, having no nucleus, still function normally.",
  {"1": "Leukocyte reduction removes the great majority of white cells and prevents febrile nonhemolytic reactions and HLA alloimmunization — but it does not remove enough lymphocytes to prevent engraftment, and it is explicitly NOT a substitute for irradiation. Believing otherwise is the specific error this item tests.",
   "2": "Pathogen reduction inactivates bacteria, viruses and parasites in the product, and modern systems do also inactivate lymphocytes — but it is applied chiefly to platelets, and it would be the answer if the complication were transfusion-transmitted infection. His illness is immunologic, not infectious.",
   "3": "ABO-identical units prevent hemolytic reactions, which are mediated by ANTIBODY against red cell antigens and occur within minutes to days. Graft-versus-host disease is mediated by living donor lymphocytes and is unrelated to ABO matching; his units were compatible.",
   "4": "Washing removes plasma proteins and prevents allergic and anaphylactic reactions, particularly in IgA-deficient recipients. It does not remove the donor lymphocytes suspended with the cells, and would have made no difference here."},
  "The donated blood contained live donor immune cells, and his chemotherapy-weakened body could not kill them off — so they took hold and attacked his skin, gut and bone marrow. Zapping the bag with radiation first stops those cells from multiplying.",
  exim="fig_tx_timeline",
  excap="Unlike every other reaction on this timeline, transfusion-associated graft-versus-host disease appears weeks after the transfusion, long after the patient has gone home.")
