# Jeevs Edition — Batch 17: COAGULATION II · CLOTTING
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §32 s29-tma            — TTP, HUS, aHUS and the TMA/DIC split        (LO 33, 44)
#   §33 s30-thrombophilia  — inherited thrombophilias, APS               (LO 45, 46, 48)
#   §34 s31-vte-management — HIT, monitoring, testing, duration          (LO 43, 46, 52)
# Options alphabetised; "correct" is the 0-based index AFTER alphabetisation.
# Option lengths balanced — the keyed answer is not the longest.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ══════════════════ §32 · THE THROMBOTIC MICROANGIOPATHIES ══════════════════

# ── 1. TTP — and the thing not to do (§32) ─────────────────────────────────
q("A 31-year-old woman is brought to the emergency department because of confusion and bruising for 2 days. Her partner reports that she was well until 4 days ago and has become progressively disoriented since yesterday. She takes no medications and has had no diarrhea. Her temperature is 38.2°C (100.8°F), pulse is 104/min, respirations are 18/min, and blood pressure is 128/76 mm Hg. She is oriented to person only. Physical examination shows scattered petechiae over both shins and no focal neurologic deficit. A peripheral blood smear is shown.\n\nLaboratory studies show:\nHemoglobin 8.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 25% (N=36%–46%)\nPlatelet count 12,000/mm3 (N=150,000–400,000/mm3)\nReticulocyte count 8.4% (N=0.5%–1.5%)\nLactate dehydrogenase 1,240 U/L (N=100–220 U/L)\nHaptoglobin <10 mg/dL (N=30–200 mg/dL)\nSerum creatinine 1.2 mg/dL (N=0.6–1.2 mg/dL)\nProthrombin time 12 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 31 seconds (N=25–35 seconds)\nFibrinogen 340 mg/dL (N=200–400 mg/dL)\n\nWhich of the following is the most appropriate next step in management?",
  ["A. Begin eculizumab after meningococcal vaccination",
   "B. Begin plasma exchange now",
   "C. Give intravenous immunoglobulin and a corticosteroid",
   "D. Transfuse platelets to above 50,000/mm3",
   "E. Withhold therapy pending the ADAMTS13 result"],
  1,
  "This is thrombotic thrombocytopenic purpura, and PLASMA EXCHANGE IS STARTED ON CLINICAL SUSPICION, BEFORE THE ADAMTS13 LEVEL RETURNS. UNTREATED TTP HAS A MORTALITY ABOVE 90%.\n\nWhy exchange rather than infusion, which is the mechanistic point: it does TWO THINGS AT ONCE. THE PLASMA YOU GIVE BACK REPLACES ADAMTS13, and THE PLASMA YOU REMOVE TAKES THE ANTIBODY WITH IT. Infusion alone would only do the first, and the acquired IgG inhibitor would keep neutralising the enzyme you supplied. Immunosuppression is added when relapse is likely.\n\nThe diagnosis is made from the pattern, not from all five elements of the pentad. The pentad is FEVER, THROMBOCYTOPENIA, MICROANGIOPATHIC HEMOLYTIC ANEMIA, NEUROLOGICAL CHANGES and RENAL IMPAIRMENT — and the instruction is explicitly NOT TO WAIT FOR ALL FIVE. Anyone with some of these features, or with schistocytes, is treated as TTP while confirmatory results are pending. Her creatinine of 1.2 mg/dL is normal, which fits: TTP IS SYSTEMIC AND PLATELET-RICH, so the brain is involved and the presentation is NEUROLOGICAL, while HUS is renal.\n\nThe normal PT, aPTT and fibrinogen are what exclude DIC — in every thrombotic microangiopathy the clotting times are NORMAL, because the clotting factors are not being consumed.\n\nHer age fits the acquired autoimmune form, which typically presents in the 20s or 30s.",
  {"0": "Eculizumab, an anti-C5 antibody, is the targeted treatment for ATYPICAL HUS, where uncontrolled complement activation is the mechanism. That diagnosis belongs to a patient with renal-predominant disease and no ADAMTS13 deficiency, usually after Shiga toxin has been excluded.",
   "2": "Immunoglobulin and corticosteroids treat immune thrombocytopenia, which causes isolated thrombocytopenia with no hemolysis and no schistocytes. Steroids are used adjunctively in TTP, but they do not remove the antibody or replace the enzyme, and they are not the intervention that changes mortality.",
   "3": "This is the specific trap. THE THROMBOCYTOPENIA IS CONSUMPTIVE — ADDING PLATELETS ADDS FUEL TO ONGOING MICROVASCULAR THROMBOSIS, and platelets are withheld in suspected TTP unless there is life-threatening bleeding.",
   "4": "Waiting for the ADAMTS13 activity and inhibitor assay is exactly what must not happen. The result takes days in most centres, and the mortality of untreated disease is above 90% — the test confirms a diagnosis you have already begun treating."},
  "Her blood is full of tiny clots that are shredding red cells and using up platelets. The treatment swaps her plasma out, which both replaces the missing enzyme and washes out the antibody blocking it. Giving platelets would just feed the clotting.",
  image="fig_schistocytes",
  imcap="Peripheral blood smear at high power.",
  exim="fig_slide_adamts13",
  excap="Two routes to the same failure: congenital ADAMTS13 deficiency, or an acquired IgG inhibitor against the enzyme.")

# ── 2. The ADAMTS13 mechanism (§32) ────────────────────────────────────────
q("A 29-year-old woman with thrombotic thrombocytopenic purpura is found to have an ADAMTS13 activity of less than 5% (N=>60%) with a demonstrable inhibitor. Her platelet count is 16,000/mm3 and her smear shows numerous fragmented erythrocytes with two pointed ends.\n\nWhich of the following best explains the thrombocytopenia in this patient?",
  ["A. Antibody-mediated clearance of platelets by splenic macrophages",
   "B. Consumption of platelets on uncleaved ultra-large multimers",
   "C. Impaired megakaryocyte maturation within the bone marrow",
   "D. Sequestration of platelets within an enlarged spleen",
   "E. Widespread fibrin deposition consuming platelets and factors"],
  1,
  "The chain runs like this:\n\nEndothelial cells secrete von Willebrand factor from Weibel-Palade bodies → it emerges as ULTRA-LARGE MULTIMERS anchored to the cell surface → normally ADAMTS13 CLEAVES THEM into normal-sized, hemostatically useful forms → in TTP the enzyme is absent or blocked → THE UNCLEAVED ULTRA-LARGE MULTIMERS ACT AS ENORMOUS ADHESIVE ROPES, seizing platelets across the microvasculature → platelets are CONSUMED, producing the thrombocytopenia → red cells are SHREDDED on the resulting strands, producing the schistocytes.\n\nTwo routes reach the same failure: a CONGENITAL deficiency (Upshaw-Schulman), or an ACQUIRED IgG INHIBITOR against the enzyme — and THE ACQUIRED FORM IS FAR MORE COMMON, as here.\n\nThe nuance worth holding is that YOU DO NOT WANT ZERO LARGE MULTIMERS EITHER. ADAMTS13 is a BALANCING enzyme, and the large multimers are the active ones that recruit platelets to a genuine injury. The disease is having ONLY those, so platelets are recruited everywhere.\n\nThat is also the unifying idea across three sections: VON WILLEBRAND FACTOR CAUSES A BLEEDING DISEASE IN ONE LECTURE AND A CLOTTING DISEASE IN THE NEXT. Too little protein, or multimers too small, and adhesion fails — von Willebrand disease. Too large and uncleaved, and platelets are seized everywhere — TTP. And in Heyde syndrome, shear across a stenotic valve strips the large multimers out mechanically, producing a bleeding picture by a third route.",
  {"0": "Antibody-mediated clearance by splenic macrophages is the mechanism of immune thrombocytopenia. There is an antibody in this patient, but it is directed at the ENZYME rather than at platelets, and it causes consumption in clots rather than removal in the spleen.",
   "2": "Impaired megakaryocyte maturation is a production failure, as in myelodysplasia or marrow suppression. It would not shred red cells, and TTP is a consumptive process with a marrow working normally.",
   "3": "Splenic sequestration lowers the platelet count in hypersplenism, usually modestly. TTP does not cause splenomegaly, and sequestration does not produce schistocytes or hemolysis of this severity.",
   "4": "Widespread fibrin deposition consuming platelets AND FACTORS is disseminated intravascular coagulation — which is the important differential. In DIC the PT and aPTT are prolonged and the fibrinogen falls; in every thrombotic microangiopathy they are normal, because the factors are not consumed."},
  "An enzyme normally trims a sticky protein down to size. Without it, the protein stays as huge ropes that grab every platelet that floats past — so platelets run out, and red cells get sliced up on the strands.",
  exim="fig_slide_maha",
  excap="Microangiopathic hemolytic anemia: red cells sheared as they squeeze past platelet–von Willebrand factor strands.")

# ── 3. Shiga toxin HUS (§32) ───────────────────────────────────────────────
q("A 4-year-old girl is brought to the emergency department because of decreased urine output for 1 day. Six days ago she developed crampy abdominal pain and watery diarrhea that became bloody on the third day; the diarrhea has now resolved. She attended a farm visit and a barbecue 9 days ago. Her temperature is 37.4°C (99.3°F), pulse is 128/min, and blood pressure is 108/68 mm Hg. Physical examination shows pallor, periorbital edema, and mild abdominal tenderness without guarding. She is alert and fully oriented.\n\nLaboratory studies show:\nHemoglobin 7.8 g/dL (N=11.5–15.5 g/dL)\nHematocrit 24% (N=35%–45%)\nPlatelet count 44,000/mm3 (N=150,000–400,000/mm3)\nReticulocyte count 6.2% (N=0.5%–1.5%)\nLactate dehydrogenase 1,080 U/L (N=100–220 U/L)\nHaptoglobin <10 mg/dL (N=30–200 mg/dL)\nSerum creatinine 3.4 mg/dL (N=0.3–0.7 mg/dL)\nProthrombin time 12 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 30 seconds (N=25–35 seconds)\nFibrinogen 370 mg/dL (N=200–400 mg/dL)\n\nThe smear shows fragmented erythrocytes. Which of the following is the most likely underlying cause?",
  ["A. Complement factor H deficiency with unregulated activation",
   "B. Deficiency of ADAMTS13 from an acquired IgG inhibitor",
   "C. Endothelial injury caused by a bacterial Shiga toxin",
   "D. Quinine-induced immune destruction of platelets",
   "E. Systemic activation of coagulation with factor consumption"],
  2,
  "Typical hemolytic uremic syndrome. The organism is ENTEROHEMORRHAGIC E. COLI, classically O157:H7 (also Shigella dysenteriae), and the classic exposure is UNDERCOOKED OR CONTAMINATED MEAT, producing BLOODY DIARRHEA AND THEN KIDNEY FAILURE. Her farm visit and barbecue, the bloody diarrhea that has already resolved, and her creatinine of 3.4 mg/dL are the sequence.\n\nHUS IS RENAL AND FIBRIN-RICH — Shiga toxin damages glomerular endothelium, so the presentation is RENAL FAILURE. Contrast TTP, which is SYSTEMIC AND PLATELET-RICH, so the brain is involved and the presentation is NEUROLOGICAL. The first instinct 'BRAIN = TTP, KIDNEY = HUS' is correct here: she is alert and fully oriented with a creatinine six times normal.\n\nThe step that is easy to miss is WHY an intestinal infection triggers clotting at all. The toxin KILLS ENDOTHELIAL CELLS DIRECTLY — and dying cells ACTIVATE THE IMMUNE SYSTEM, releasing interleukins and chemokines. COAGULATION AND IMMUNITY ARE WIRED TOGETHER: an inflammatory signal is also a 'there may be bleeding here' signal. So FIBRINOGEN AND VON WILLEBRAND FACTOR, BOTH ACUTE-PHASE REACTANTS, ARE RELEASED — and the surge of high molecular weight von Willebrand factor reproduces the end result of TTP by a completely different route.\n\nTreatment is SUPPORTIVE, WITH DIALYSIS IF NEEDED — the key test is a stool culture and Shiga toxin assay, and antibiotics are generally avoided because they may increase toxin release.",
  {"0": "Factor H deficiency causes ATYPICAL HUS, the third branch of the recognition algorithm — reached when there is NO diarrheal prodrome and no pneumococcal infection. Her bloody diarrhea 6 days ago points firmly to the first branch.",
   "1": "An acquired ADAMTS13 inhibitor causes TTP, which is systemic and neurological, presenting typically in the 20s or 30s. She is 4 years old, fully oriented, and her dominant problem is renal.",
   "4": "Systemic coagulation activation is DIC, and it is excluded by the numbers rather than by the story: her PT and aPTT are normal and her fibrinogen is 370 mg/dL. In DIC both times prolong and fibrinogen falls.",
   "3": "Quinine is a named drug cause of thrombotic microangiopathy and belongs on the etiologic list. There is no drug exposure here, and quinine-associated disease does not follow a Shiga toxin prodrome."},
  "She ate something contaminated, and the bacteria released a toxin that poisons the lining of the small blood vessels in her kidneys. Clots form there, shredding red cells and shutting the kidneys down — days after the diarrhea has stopped.",
  exim="fig_slide_hus",
  excap="HUS pathogenesis: Shiga toxin damages glomerular endothelium directly.")

# ── 4. Atypical HUS (§32) ──────────────────────────────────────────────────
q("A 5-year-old boy is admitted with his third episode of acute kidney injury with anemia and thrombocytopenia in 2 years. He has had no diarrhea before any of the episodes, and stool studies for Shiga toxin have been negative each time. A maternal cousin required dialysis in childhood. His temperature is 36.9°C (98.4°F), pulse is 118/min, and blood pressure is 132/84 mm Hg. Physical examination shows pallor and periorbital edema.\n\nLaboratory studies show:\nHemoglobin 7.2 g/dL (N=11.5–15.5 g/dL)\nHematocrit 22% (N=35%–45%)\nPlatelet count 52,000/mm3 (N=150,000–400,000/mm3)\nLactate dehydrogenase 1,150 U/L (N=100–220 U/L)\nHaptoglobin <10 mg/dL (N=30–200 mg/dL)\nSerum creatinine 4.1 mg/dL (N=0.3–0.7 mg/dL)\nProthrombin time 12 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 31 seconds (N=25–35 seconds)\nFibrinogen 380 mg/dL (N=200–400 mg/dL)\nADAMTS13 activity 72% (N=>60%)\n\nThe smear shows schistocytes. Which of the following is the most appropriate treatment?",
  ["A. Eculizumab",
   "B. Intravenous immunoglobulin",
   "C. Plasma exchange alone",
   "D. Rituximab",
   "E. Supportive care and dialysis alone"],
  0,
  "This is ATYPICAL HUS, and it has a TARGETED THERAPY — COMPLEMENT BLOCKADE WITH ECULIZUMAB, an anti-C5 antibody. That is why establishing complement as the mechanism CHANGES MANAGEMENT, not just the label.\n\nThe recognition algorithm has three branches: a DIARRHEAL PRODROME points to Shiga toxin HUS; a PNEUMOCOCCAL INFECTION points to the neuraminidase/T-antigen form; and NEITHER triggers a full atypical HUS workup. He is on the third branch — no diarrhea before any episode, negative Shiga toxin studies, a NORMAL ADAMTS13 activity of 72% excluding TTP, and normal clotting times excluding DIC. Add recurrent episodes and an affected relative.\n\nThe mechanism: the ALTERNATIVE COMPLEMENT PATHWAY IS CONSTITUTIVELY TICKING OVER — it is held in check by REGULATORY PROTEINS rather than switched on by a trigger. When that suppression is defective the pathway is CONTINUALLY ON, and unregulated complement binds THE PATIENT'S OWN CELLS. The MEMBRANE ATTACK COMPLEX destroys their endothelium; destroyed endothelium EXPOSES COLLAGEN AND TISSUE FACTOR, and coagulation is switched on.\n\nThe defects are in COMPLEMENT FACTOR H, COMPLEMENT FACTOR I, MEMBRANE COFACTOR PROTEIN (MCP/CD46) and THROMBOMODULIN. Named triggers include HIV, cancer, transplantation, tacrolimus, and pregnancy including HELLP syndrome.\n\nRemember to vaccinate against Neisseria meningitidis before starting any complement inhibitor.",
  {"1": "Immunoglobulin treats immune thrombocytopenia and some antibody-mediated disease. It does not block terminal complement, and his thrombocytopenia is consumptive rather than immune.",
   "2": "Plasma exchange is the treatment for TTP, where it replaces ADAMTS13 and removes the inhibitor. His ADAMTS13 activity is 72%, which excludes that diagnosis — though exchange is sometimes used empirically before the result returns.",
   "3": "Rituximab depletes B cells and is used for relapsing TTP with a persistent ADAMTS13 inhibitor, and for anti-factor-H antibody disease. It does not address an inherited defect of complement regulation.",
   "4": "Supportive care with dialysis is the correct management of TYPICAL Shiga toxin HUS, which is self-limited. Atypical HUS is progressive, and withholding complement blockade risks end-stage renal disease."},
  "His complement system — part of the immune defence — has no working off-switch, so it keeps attacking the lining of his own blood vessels. A drug that blocks that system stops the damage; supportive care alone does not.",
  exim="fig_slide_ahus_complement",
  excap="Atypical HUS: loss of complement suppression leaves the alternative pathway continually active.")

# ── 5. Why the genotype matters before transplant (§32) ────────────────────
q("A 9-year-old girl with atypical hemolytic uremic syndrome has progressed to end-stage renal disease and is being assessed for kidney transplantation. Her nephrologist requests genetic testing of complement regulatory proteins before proceeding, explaining that the result substantially changes the expected outcome of the graft.\n\nWhich of the following best explains why the specific mutation matters?",
  ["A. A membrane-bound regulator is supplied by the transplanted kidney",
   "B. Complement inhibitors cannot be given after transplantation",
   "C. Donor matching is determined by the complement genotype",
   "D. Mutations in circulating regulators are corrected by dialysis",
   "E. The genotype determines whether plasma exchange will work"],
  0,
  "The recurrence rate after renal transplantation is so high that CHILDREN MUST BE GENETICALLY TESTED BEFORE RECEIVING A KIDNEY, and the reason is mechanistic:\n\n• IF THE DEFECTIVE REGULATOR IS MADE IN THE LIVER — FACTOR H, FACTOR I — a new kidney enters THE SAME HOSTILE CIRCULATION and is attacked in turn.\n• IF THE DEFECT IS IN A MEMBRANE-BOUND REGULATOR MADE BY THE KIDNEY ITSELF — MCP/CD46 — a transplanted kidney BRINGS ITS OWN WORKING COPY and does far better.\n\nPrognosis follows the same logic: A FACTOR H MUTATION CARRIES A HIGH RATE OF RECURRENCE AND OF DEATH OR END-STAGE RENAL DISEASE, whereas other mutations recur far less.\n\nThat is what makes the genotype worth knowing — for treatment planning (a factor H patient may need combined liver-kidney transplantation, or eculizumab cover through and after the transplant), and for FAMILY COUNSELLING AND SCREENING, since relatives may carry the same mutation.\n\nIt is a clean example of a principle that runs through the whole thrombophilia block: a genetic test is worth sending when you can say in advance what you will do differently with each result. Here the answers are genuinely different — one genotype changes the organ you transplant and the drug cover you give, and the other predicts a good outcome from a kidney alone.",
  {"1": "Complement inhibitors are not only permitted after transplantation but are a central part of management for high-risk genotypes, given around and after the operation to protect the graft.",
   "2": "Donor matching is based on ABO compatibility and HLA typing. The complement genotype is a property of the RECIPIENT and does not determine which donor is suitable.",
   "3": "Dialysis replaces excretory renal function; it does not replace a deficient circulating protein or correct a genetic defect. Plasma infusion can transiently supply factor H, which is a different intervention.",
   "4": "Plasma exchange is the treatment for TTP, where it replaces ADAMTS13 and removes an inhibitor. In atypical HUS it is at best a temporising measure, and eculizumab is the targeted therapy."},
  "If the faulty protein is made by the liver, a new kidney lands in the same damaged bloodstream and gets attacked too. If the faulty protein is made by the kidney itself, the donated kidney brings a working copy with it — so the same disease has two very different transplant outcomes.",
  exim="fig_slide_ahus_genetics",
  excap="Atypical HUS genetics and transplant outcome — the mutation predicts recurrence.")

# ── 6. Separating the microangiopathies from DIC (§32) ─────────────────────
q("A 44-year-old woman in the intensive care unit has thrombocytopenia and anemia, and her peripheral blood smear shows numerous fragmented erythrocytes with two pointed ends and no central pallor. Her lactate dehydrogenase is markedly elevated and her haptoglobin is undetectable. The team must distinguish a thrombotic microangiopathy from disseminated intravascular coagulation.\n\nThe relevant laboratory values are compared below:\n\n  Result set    PT          aPTT        Fibrinogen   D-dimer\n  ----------------------------------------------------------\n  A             Normal      Normal      Normal       Normal\n  B             Normal      Normal      Normal       Mildly raised\n  C             Normal      Prolonged   Normal       Normal\n  D             Prolonged   Normal      Low          Markedly raised\n  E             Prolonged   Prolonged   Low          Markedly raised\n  F             Prolonged   Prolonged   Normal       Normal\n\nWhich of the following result sets would best support disseminated intravascular coagulation rather than a thrombotic microangiopathy?",
  ["A. Result set A",
   "B. Result set B",
   "C. Result set C",
   "D. Result set D",
   "E. Result set E",
   "F. Result set F"],
  4,
  "IN EVERY THROMBOTIC MICROANGIOPATHY THE PT AND aPTT ARE NORMAL, because the clotting factors are not being consumed — the problem is PLATELETS AND ENDOTHELIUM. IN DIC THEY ARE BOTH PROLONGED AND FIBRINOGEN FALLS.\n\nSo the DIC row is BOTH TIMES PROLONGED, FIBRINOGEN LOW, D-DIMER MARKEDLY RAISED — result set E. If you are handed SCHISTOCYTES PLUS THROMBOCYTOPENIA, THE COAGULATION PANEL IS WHAT SEPARATES THE MICROANGIOPATHIES FROM DIC, AND IT TAKES ONE LOOK. THE SMEAR CANNOT DO IT — schistocytes appear in TTP, HUS, atypical HUS and DIC alike.\n\nOne caution about the fibrinogen: A FALLING TREND IS MORE USEFUL THAN A SINGLE VALUE, because fibrinogen is an ACUTE-PHASE REACTANT and starts HIGH in sepsis. A value of 180 mg/dL in a septic patient whose fibrinogen was 500 mg/dL two days earlier is a profound fall reported as a near-normal number.\n\nThe rest of the table, for orientation: TTP, typical HUS and atypical HUS all sit in the normal-PT, normal-aPTT, normal-fibrinogen rows, separated from each other by ADAMTS13 ACTIVITY AND INHIBITOR, STOOL CULTURE AND SHIGA TOXIN, and COMPLEMENT GENETICS AND ANTI-FACTOR-H ANTIBODIES respectively — and by whether the dominant organ is BRAIN or KIDNEY.\n\nThe D-dimer alone will not do the job: it rises whenever fibrin is formed and broken down, so it is raised in thrombotic microangiopathy, in sepsis, after surgery, and in venous thromboembolism.",
  {"0": "This row is entirely normal, including the D-dimer. No process producing schistocytes and consuming platelets leaves a completely normal coagulation profile, so this row fits neither diagnosis.",
   "1": "Normal times with a normal fibrinogen and a mildly raised D-dimer is the expected pattern in a THROMBOTIC MICROANGIOPATHY — TTP, HUS or atypical HUS. It is the row the question is asking you to distinguish DIC from.",
   "2": "An isolated prolonged aPTT with everything else normal points at an intrinsic-pathway factor deficiency, heparin, or a lupus anticoagulant. It does not describe a consumptive coagulopathy.",
   "3": "A prolonged PT with a NORMAL aPTT and a low fibrinogen is internally incoherent for DIC: hypofibrinogenemia affects the common pathway and would prolong both times. This row is the partial-knowledge trap for a student who remembers only that the PT prolongs first.",
   "5": "Both times prolonged with a NORMAL fibrinogen and a normal D-dimer fits vitamin K deficiency, warfarin, or liver disease — a synthetic or nutritional deficit rather than consumption. The absent D-dimer rise is what excludes DIC."},
  "The smear looks the same in all these conditions. What separates them is the clotting panel: if the clotting proteins are being used up too — long clotting times, low fibrinogen — it is the body-wide process, not the small-vessel one.")

# ══════════════════ §33 · THROMBOPHILIAS AND APS ══════════════════

# ── 7. Factor V Leiden (§33) ───────────────────────────────────────────────
q("A 34-year-old man has a second unprovoked deep venous thrombosis. His father had a pulmonary embolism at 40. Testing performed 4 months after his first event, off anticoagulation, showed normal protein C activity, normal protein S activity, and a normal antithrombin level, with a functional assay demonstrating impaired prolongation of the clotting time after addition of activated protein C. Molecular testing confirms a point mutation in the factor V gene.\n\nWhich of the following best describes the effect of this mutation?",
  ["A. Factor V cannot bind factor Xa on the platelet surface",
   "B. Factor V is produced in excessive amounts by the liver",
   "C. Factor V is resistant to cleavage by plasmin",
   "D. Factor V requires vitamin K for its activation",
   "E. Factor V resists inactivation by activated protein C"],
  4,
  "Factor V Leiden is the R506Q mutation, and it PREVENTS DEACTIVATION OF FACTOR 5 BY PROTEIN C — 'ACTIVATED PROTEIN C RESISTANCE'. The protein still works as a procoagulant cofactor; what it has lost is the cleavage site that switches it off.\n\nThe net effect is SIMILAR TO PROTEIN C DEFICIENCY, which is the conceptual point. The reaction is ACTIVATED PROTEIN C CLEAVES FACTOR 5a, and you can break it three ways, all converging on the same end result — factor 5a survives and thrombin generation runs on:\n• REMOVE THE SCISSORS → protein C or protein S deficiency.\n• ARMOUR-PLATE THE PAPER → FACTOR V LEIDEN.\n• POISON THE SCISSORS → hyperhomocysteinemia, which inhibits protein C.\n\nThat is why having factor V Leiden AND protein C deficiency is ADDITIVE.\n\nThe epidemiology matters as much as the mechanism: factor V Leiden is present in ABOUT 5% OF CAUCASIANS and accounts for 20% TO 30% OF VTE EVENTS — THE MOST COMMON THROMBOPHILIA. But COMMON IS NOT THE SAME AS DANGEROUS. Pushing the accelerator (factor V Leiden, prothrombin G20210A) gives a relative risk of only 3 TO 5 TIMES, while losing a brake (antithrombin, protein C, protein S) gives 15 TO 19 TIMES.\n\nHOMOZYGOTES CARRY SUBSTANTIALLY HIGHER RISK. Diagnosis is by MOLECULAR TESTING, which may be done at any time — DNA does not change with acute illness or drugs.",
  {"0": "Factor 5a's job is precisely to assemble with factor 10a on a phospholipid surface as the prothrombinase complex. Losing that binding would cause BLEEDING — factor V deficiency — which is the opposite phenotype.",
   "1": "Overproduction describes the PROTHROMBIN G20210A mutation, where a 3' untranslated region change increases messenger RNA stability so more prothrombin is made. Factor V Leiden alters the protein's cleavage site rather than its quantity.",
   "2": "Plasmin digests fibrin, not factor 5, and resistance to plasmin describes a fibrinolytic defect. Dysfibrinogenemia can produce a plasmin-resistant clot, which is a different disorder.",
   "3": "The vitamin K-dependent factors are 2, 7, 9 and 10, plus proteins C and S — factor 5 is not among them. That fact is separately useful: a normal factor 5 with low 2, 7, 9 and 10 identifies vitamin K deficiency rather than liver disease."},
  "A brake protein normally cuts up one of the clotting proteins to switch it off. His version of that clotting protein has armour where the cut should happen — so it never gets switched off, and clotting keeps running.",
  exim="fig_slide_fvl",
  excap="Factor V Leiden: the mutated factor 5 resists cleavage by activated protein C.")

# ── 8. Prothrombin G20210A (§33) ───────────────────────────────────────────
q("A 26-year-old woman with a first unprovoked deep venous thrombosis is found to carry a heterozygous G20210A variant in the prothrombin gene. Functional assays of prothrombin activity performed at the same visit are within normal limits, and her prothrombin time and activated partial thromboplastin time are normal. Her physician explains that the variant does not change a single amino acid in the prothrombin protein.\n\nWhich of the following best explains how this variant causes thrombophilia?",
  ["A. It creates a cleavage site resistant to activated protein C",
   "B. It impairs the binding of antithrombin to thrombin",
   "C. It increases messenger RNA stability, raising prothrombin levels",
   "D. It produces a prothrombin molecule with increased activity",
   "E. It reduces hepatic clearance of activated factor X"],
  2,
  "G20210A is a REGULATORY MUTATION, NOT A CODING ONE. It sits in the 3' UNTRANSLATED REGION of the gene and INCREASES PRE-MESSENGER-RNA STABILITY. A more stable transcript is translated more, so the patient makes MORE PROTHROMBIN.\n\nTHE PROTEIN ITSELF IS ENTIRELY NORMAL — there is simply MORE SUBSTRATE available for the cascade to convert into thrombin, which shifts the hemostatic balance toward clotting.\n\nThis is why the diagnosis is made by MOLECULAR TESTING RATHER THAN A FUNCTIONAL ASSAY: A PROTEIN ACTIVITY TEST WOULD LOOK NORMAL, exactly as hers does. It is also why the test CAN BE RUN AT ANY TIME and ONLY EVER NEEDS RUNNING ONCE — DNA does not change with acute illness, heparin, warfarin, or pregnancy, all of which corrupt the functional assays.\n\nThe epidemiology: 2.3% OF CAUCASIANS and 0.5% OF AFRICAN-AMERICANS, with a relative risk of 3 TO 5 TIMES — the accelerator group, alongside factor V Leiden, rather than the far more dangerous brake-loss group at 15 to 19 times.\n\nAnd the management consequence, which is where most questions land: a common variant with a modest relative risk in a patient whose recurrence risk is already set by the CIRCUMSTANCES of the clot rarely changes therapy. DURATION IS DRIVEN BY WHETHER THE EVENT WAS PROVOKED, NOT BY THE GENOTYPE.",
  {"0": "Resistance to activated protein C is the factor V Leiden mechanism — an altered cleavage site on factor 5. It changes the protein; this variant does not touch the protein at all.",
   "1": "Impaired antithrombin binding describes antithrombin deficiency or a thrombin variant resistant to it. That would also make heparin less effective, and her clotting times and heparin response are unaffected.",
   "3": "A hyperactive prothrombin molecule would be a coding change, and the stem states explicitly that no amino acid is altered. Her functional assay is normal, which is the clue the question turns on.",
   "4": "Hepatic clearance of factor 10a is not a recognised regulatory step in this way — factor 10a is neutralised by antithrombin and by tissue factor pathway inhibitor. The mutation concerns prothrombin, not factor 10."},
  "The gene makes a perfectly normal protein — it just makes more of it, because the instruction message lasts longer before being destroyed. More raw material means more clotting, which is why only a DNA test finds it.",
  exim="fig_slide_prothrombin_mut",
  excap="Prothrombin G20210A: a 3' untranslated region mutation that raises prothrombin levels without altering the protein.")

# ── 9. Heparin resistance (§33) ────────────────────────────────────────────
q("A 47-year-old man with nephrotic syndrome from membranous nephropathy is admitted with a proximal deep venous thrombosis and started on an intravenous unfractionated heparin infusion. Despite three dose increases over 18 hours he has not achieved a therapeutic activated partial thromboplastin time, which remains at 34 seconds (N=25–35 seconds). He has not received any heparin previously and his platelet count is stable at 268,000/mm3.\n\nLaboratory studies show:\nSerum albumin 1.8 g/dL (N=3.5–5.5 g/dL)\nUrine protein 8.4 g/24 h (N=<0.15 g/24 h)\nAntithrombin III activity 38% (N=80%–120%)\n\nWhich of the following is the most appropriate next step?",
  ["A. Add aspirin to the heparin infusion",
   "B. Continue increasing the heparin infusion rate",
   "C. Give antithrombin III concentrate or switch to argatroban",
   "D. Stop anticoagulation and place a vena cava filter",
   "E. Switch to low-molecular-weight heparin at treatment dose"],
  2,
  "HEPARIN WORKS BY INCREASING ANTITHROMBIN'S ENZYMATIC ACTIVITY — HEPARIN HAS ESSENTIALLY NO ANTICOAGULANT ACTION OF ITS OWN. With little antithrombin present, more heparin achieves little: the classic picture of HEPARIN RESISTANCE.\n\nTHE ANSWER IS NOT MORE HEPARIN. It is either ANTITHROMBIN III SUPPLEMENTATION, so that the heparin can work to its full effect, or AN AGENT THAT DOES NOT DEPEND ON ANTITHROMBIN AT ALL — a DIRECT THROMBIN INHIBITOR such as argatroban.\n\nThe cause here is acquired, not inherited. ANTITHROMBIN III IS A SMALL PROTEIN AND IS EASILY LOST, so a low level does not automatically mean an inherited disorder. The acquired causes are NEPHROTIC SYNDROME (the kidneys leak protein), CHEST TUBE DRAINAGE, PROTEIN-LOSING ENTEROPATHIES, and SEVERE HEART FAILURE. His albumin of 1.8 g/dL with 8.4 g of proteinuria a day is the mechanism in plain view — and nephrotic syndrome is itself on the list of persistent thrombosis risk factors, so the clot and the heparin failure share one cause.\n\nInherited antithrombin deficiency is present in UNDER 0.5% of the population but carries a RELATIVE RISK OF 15 TO 19 TIMES, in the brake-loss group with protein C and protein S deficiency — an order of magnitude above factor V Leiden. HOMOZYGOUS DEFICIENCY IS NOT COMPATIBLE WITH LIFE.\n\nNote also that this level, drawn on heparin during an acute clot, cannot be used to diagnose an inherited deficiency — heparin lowers antithrombin, and so does the thrombus itself.",
  {"0": "Aspirin inhibits platelet cyclooxygenase-1 and is an antiplatelet agent. Venous thrombosis is a fibrin-and-stasis problem rather than a platelet-driven arterial one, and aspirin does nothing for an ineffective heparin infusion.",
   "1": "Escalating further is the intuitive response and has already failed three times. Without antithrombin there is no cofactor for the drug to work through, so more heparin adds bleeding risk without adding anticoagulation.",
   "3": "A vena cava filter is reserved for patients who cannot be anticoagulated at all, and it does not treat the clot. Stopping anticoagulation in an acute proximal deep venous thrombosis risks extension and embolism.",
   "4": "Low-molecular-weight heparin acts through the SAME cofactor — antithrombin — so it fails for the same reason. It would also be harder to monitor, since the aPTT does not sense it and an anti-factor-10a assay would be required."},
  "Heparin does not thin blood by itself — it supercharges a natural protein that does. His kidneys are leaking that protein into the urine, so there is almost nothing for the heparin to work with. Replace the protein, or use a drug that works alone.",
  exim="fig_slide_anticoag_brakes",
  excap="The cascade with its brakes: antithrombin III acts on thrombin and factor 10a — and heparin works only through it.")

# ── 10. Neonatal purpura fulminans (§33) ───────────────────────────────────
q("A term newborn boy develops rapidly enlarging, sharply demarcated purple skin lesions over the buttocks and limbs at 14 hours of age, some of which have become black centrally. He was born after an uncomplicated pregnancy to consanguineous parents. His temperature is 36.8°C (98.2°F), pulse is 168/min, and respirations are 54/min. Physical examination shows well-perfused extremities apart from the lesions, and there is no hepatosplenomegaly. Blood cultures are drawn and are subsequently negative.\n\nLaboratory studies show:\nHemoglobin 16.2 g/dL (N=14.0–20.0 g/dL)\nPlatelet count 62,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 24 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 58 seconds (N=25–35 seconds)\nFibrinogen 98 mg/dL (N=200–400 mg/dL)\nD-dimer 14.8 µg/mL (N=<0.5 µg/mL)\nProtein C activity <5% (N=70%–140%)\n\nWhich of the following best explains the appearance of the skin lesions?",
  ["A. Bacterial embolization to dermal vessels from occult sepsis",
   "B. Immune-mediated destruction of platelets by maternal antibody",
   "C. Small-vessel vasculitis with immune complex deposition",
   "D. Thrombosis of dermal capillaries with subsequent rupture",
   "E. Transfusion of maternal blood across the placental circulation"],
  3,
  "HOMOZYGOUS PROTEIN C OR S DEFICIENCY CAUSES POTENTIALLY FATAL PURPURA FULMINANS SHORTLY AFTER BIRTH — widespread DERMAL MICROVASCULAR THROMBOSIS WITH SKIN NECROSIS. It is a neonatal emergency.\n\nTHE NAME LOOKS CONTRADICTORY UNTIL YOU FOLLOW THE MECHANISM: disseminated clotting IN THE CAPILLARIES; the occluded capillaries then RUPTURE, and blood leaks into the surrounding tissue. THE PURPURA IS THE CONSEQUENCE OF THE THROMBOSIS, NOT OF A BLEEDING TENDENCY. The black centres are frank skin necrosis downstream of the occluded vessels.\n\nProtein C, with protein S, inactivates FACTORS 5a AND 8a. At an activity below 5% there is effectively no brake at all, so thrombin generation runs unchecked — which also explains the consumptive picture on his panel: prolonged times, a fibrinogen of 98 mg/dL and a D-dimer of 14.8 µg/mL, a secondary DIC driven by the underlying thrombophilia rather than by sepsis. His negative blood cultures are the explicit negative that separates this from meningococcal purpura fulminans.\n\nConsanguinity fits the homozygous state, which is how a deficiency that is dangerous in heterozygotes becomes lethal in a newborn.\n\nTreatment is urgent replacement — A PROTEIN C CONCENTRATE EXISTS. For protein S there is no concentrate, so REPLACEMENT IS WITH PLASMA. The same protein C mechanism, arriving pharmacologically rather than genetically, produces WARFARIN-INDUCED SKIN NECROSIS in the adult.",
  {"0": "Meningococcal or pneumococcal sepsis causes an identical-looking purpura fulminans and is the main differential in any newborn with these lesions — antibiotics are given empirically. His blood cultures are negative and he is well-perfused and afebrile, and his protein C is undetectable.",
   "1": "Neonatal alloimmune thrombocytopenia causes petechiae and a risk of intracranial hemorrhage from maternal antibody against paternal platelet antigens. It does not consume fibrinogen, prolong the clotting times, or cause demarcated necrotic skin lesions.",
   "2": "Immune complex vasculitis, as in Henoch-Schönlein purpura, produces palpable purpura with a normal platelet count and normal coagulation studies, and it does not occur at 14 hours of age.",
   "4": "Fetomaternal transfusion causes anemia in the newborn, not thrombosis. His hemoglobin is 16.2 g/dL and the problem is occlusion of dermal vessels."},
  "The protein that normally switches clotting off is completely missing, so tiny clots block the small vessels in his skin. Those blocked vessels then burst, and the blood leaking out is what makes the purple patches — it is a clotting disease that looks like bleeding.",
  exim="fig_slide_protein_cs",
  excap="Protein C and S deficiency — homozygous deficiency presents as neonatal purpura fulminans.")

# ── 11. The lupus anticoagulant paradox (§33) ──────────────────────────────
q("A 33-year-old woman is evaluated before a planned laparoscopic cholecystectomy. She has had three consecutive unexplained miscarriages before the 10th week of gestation and one unprovoked deep venous thrombosis 2 years ago. She has never bled abnormally, including after two dental extractions. Her physical examination shows no abnormalities.\n\nLaboratory studies show:\nPlatelet count 176,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 13 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 56 seconds (N=25–35 seconds)\n\nA 1:1 mix with normal pooled plasma does not correct the activated partial thromboplastin time. Which of the following results would best confirm the suspected diagnosis?",
  ["A. A positive treponemal-specific antibody test",
   "B. Correction of the clotting time after adding excess phospholipid",
   "C. Correction of the clotting time after incubation at 37°C",
   "D. Demonstration of a reduced factor VIII activity level",
   "E. Normalization of the clotting time after vitamin K is given"],
  1,
  "'LUPUS ANTICOAGULANT' IS WRONG ON BOTH COUNTS. Not lupus — patients do not necessarily have it, and it is not part of the diagnostic criteria for lupus at all. NOT AN ANTICOAGULANT — it INCREASES CLOTTING TIME IN VITRO, which is where the name came from, but INCREASES THE RISK OF THROMBOSIS IN VIVO. THE TEST TUBE AND THE PATIENT POINT IN OPPOSITE DIRECTIONS.\n\nThe paradox hands you the confirmatory test. The clotting assays are run ON A PHOSPHOLIPID SURFACE. The antibody binds phospholipid, so IN THE TUBE it competes with the clotting complexes for a LIMITED amount of surface and the reaction is slowed. IN THE PATIENT, phospholipid is not limiting; instead the antibodies activate endothelium and platelets and interfere with natural anticoagulant pathways, which PROMOTES THROMBOSIS.\n\nBecause the inhibition is PHOSPHOLIPID-DEPENDENT, ADDING EXTRA PHOSPHOLIPID CORRECTS THE CLOTTING TIME. Adding normal plasma does not. THAT ASYMMETRY IS THE DIAGNOSTIC ALGORITHM: mixing study fails to correct → prolonged phospholipid-dependent assay (aPTT and/or the more specific DILUTE RUSSELL VIPER VENOM TEST) → correction with excess phospholipid → immunoassays for anti-cardiolipin and anti-β2-glycoprotein-1.\n\nShe already meets a clinical criterion — THREE OR MORE UNEXPLAINED CONSECUTIVE MISCARRIAGES BEFORE THE 10TH WEEK, and separately a vascular thrombosis. The laboratory criterion requires PERSISTENCE ON TWO OCCASIONS AT LEAST 12 WEEKS APART, because transient antibodies appear after a clot or an infection and disappear on recovery.\n\nAnd she should not receive plasma before surgery: her risk is thrombosis, not bleeding.",
  {"2": "Correction after incubation is not a recognised pattern — the incubated mixing study is used to UNMASK a slow-acting inhibitor, where the clotting time DRIFTS BACK OUT after 30 to 60 minutes at 37°C. That test identifies an acquired factor 8 antibody, which causes bleeding.",
   "3": "A reduced factor 8 level would suggest hemophilia A or an acquired factor 8 inhibitor, both of which cause BLEEDING. She has never bled, and a lupus anticoagulant can produce a spuriously low factor 8 result by interfering with the assay itself.",
   "4": "Vitamin K corrects a deficiency of factors 2, 7, 9 and 10, which prolongs the PT first. Her PT is normal, and a deficiency would have corrected on the mixing study.",
   "0": "The association runs the other way: anti-cardiolipin antibodies cause a BIOLOGICAL FALSE-POSITIVE on the NON-treponemal tests (VDRL, RPR), which use a cardiolipin antigen, while the TREPONEMAL-specific test stays NEGATIVE. A positive treponemal test means syphilis."},
  "Her clotting test is slow, but she does not bleed — she clots. The antibody hogs the fatty surface the test needs, so the test is slow in the tube while the same antibody makes her blood sticky in her body. Adding extra of that surface fixes the test and proves it.",
  exim="fig_slide_aps_mixing",
  excap="The mixing study again: a factor deficiency corrects with normal plasma; antiphospholipid antibodies do not.")

# ── 12. Antibody is not syndrome (§33) ─────────────────────────────────────
q("A 42-year-old woman is referred after a preoperative activated partial thromboplastin time of 48 seconds (N=25–35 seconds) was found before an elective knee arthroscopy. She has never had a thrombotic event, has had three uncomplicated pregnancies and no miscarriages, and has never bled abnormally. Testing shows a lupus anticoagulant that remains positive when repeated 14 weeks later, with an anti-β2-glycoprotein-1 IgG antibody at twice the upper limit of normal. She has no rash, no arthritis, and no renal abnormality, and her platelet count is 210,000/mm3.\n\nWhich of the following is the most appropriate management?",
  ["A. Begin indefinite warfarin with a target ratio of 2.0 to 3.0",
   "B. Begin lifelong low-dose aspirin and hydroxychloroquine",
   "C. Begin therapeutic low-molecular-weight heparin indefinitely",
   "D. No anticoagulation, with perioperative thromboprophylaxis",
   "E. Transfuse plasma before the procedure to correct the aPTT"],
  3,
  "MORE PEOPLE HAVE ANTIPHOSPHOLIPID ANTIBODIES THAN HAVE ANTIPHOSPHOLIPID SYNDROME. THE SYNDROME REQUIRES BOTH A CLINICAL AND A LABORATORY CRITERION.\n\nShe meets the laboratory criterion convincingly — a lupus anticoagulant persisting on repeat testing MORE THAN 12 WEEKS APART, plus an anti-β2-glycoprotein-1 antibody. She meets NO CLINICAL CRITERION: no vascular thrombosis (and note that SUPERFICIAL venous thrombosis would not count even if she had it), and no pregnancy morbidity — three uncomplicated pregnancies, no losses.\n\nTHE MANAGEMENT CONSEQUENCE IS THE PART MOST OFTEN GOT WRONG: A PATIENT WITH ANTIPHOSPHOLIPID ANTIBODIES BUT NO THROMBOSIS AND NO PREGNANCY MORBIDITY IS GENERALLY NOT ANTICOAGULATED. TREATMENT FOLLOWS THE SYNDROME, NOT THE SEROLOGY.\n\nWhat she does need is sensible: standard perioperative thromboprophylaxis for her arthroscopy, attention to modifiable risk factors (smoking, estrogen-containing contraception), and the clear documentation that her prolonged aPTT is an IN-VITRO ARTEFACT so that nobody transfuses plasma or cancels a procedure over it in the future.\n\nThe pregnancy criteria, for completeness, scale with gestational age because a late loss is rarer and more specific: THREE OR MORE consecutive losses BEFORE 10 WEEKS; ONE OR MORE fetal deaths AT OR BEYOND 10 WEEKS; or ONE OR MORE premature births BEFORE 34 WEEKS from eclampsia, severe pre-eclampsia or placental insufficiency.",
  {"0": "Indefinite warfarin is the treatment for antiphospholipid SYNDROME after a thrombotic event. Anticoagulating an asymptomatic antibody carrier exposes her to years of bleeding risk for a condition she does not have.",
   "1": "Aspirin with hydroxychloroquine is used in some patients with antiphospholipid antibodies and systemic lupus erythematosus, where the lupus itself justifies treatment. She has no rash, arthritis or renal disease, and primary prophylaxis in an isolated antibody carrier is not standard.",
   "2": "Therapeutic heparin is for treating an established thrombosis or for pregnancy in the syndrome. She has had neither a clot nor a pregnancy complication.",
   "4": "Plasma would be given to correct a bleeding coagulopathy, and her prolonged aPTT reflects an antibody competing for phospholipid in the tube. She is at risk of thrombosis rather than bleeding, and plasma will not shorten the time anyway since the inhibitor neutralises added factors."},
  "She has the antibody, but she has never had a clot or a pregnancy problem — so she does not have the disease. You treat the illness, not the blood test, and blood thinners carry their own risk.")

# ── 13. The false-positive syphilis test (§33) ─────────────────────────────
q("A 29-year-old woman has routine prenatal screening at 10 weeks' gestation. A rapid plasma reagin test is reactive at a titre of 1:8. A treponemal-specific antibody test is negative on two separate specimens. She has had one unexplained fetal death at 22 weeks' gestation and no other medical history. She is in a monogamous relationship and has no genital lesions, no rash, and no lymphadenopathy.\n\nLaboratory studies show:\nPlatelet count 132,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 13 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 49 seconds (N=25–35 seconds)\n\nWhich of the following is the most likely explanation for the reactive screening test?",
  ["A. Antibodies directed against cardiolipin",
   "B. Early primary syphilis before seroconversion",
   "C. Latent syphilis previously treated in adolescence",
   "D. Passive transfer of maternal antibody in pregnancy",
   "E. Recent viral infection causing polyclonal activation"],
  0,
  "THE NON-TREPONEMAL SYPHILIS TESTS — VDRL AND RPR — USE A CARDIOLIPIN-BASED ANTIGEN. A patient whose own antibodies are directed against cardiolipin will bind that antigen and produce a BIOLOGICAL FALSE-POSITIVE. The treponemal-specific test, which uses actual TREPONEMA PALLIDUM antigens, STAYS NEGATIVE — exactly the discordant pattern here, confirmed on two specimens.\n\nEverything else in the vignette points the same way: a PROLONGED aPTT in a woman who does not bleed, a mildly low platelet count (thrombocytopenia is common in antiphospholipid syndrome), and ONE UNEXPLAINED FETAL DEATH AT 22 WEEKS — which satisfies a clinical criterion on its own, since the requirement is ONE OR MORE unexplained deaths of a morphologically normal fetus AT OR BEYOND THE 10TH WEEK.\n\nFollow up with LUPUS ANTICOAGULANT TESTING AND ANTI-β2-GLYCOPROTEIN-1 ANTIBODIES, REPEATED AT 12 WEEKS to establish persistence — the requirement that separates a genuine, thrombosis-associated syndrome from the transient antibodies that appear after infection or illness and disappear on recovery.\n\nIf persistence is confirmed she has antiphospholipid syndrome with obstetric morbidity, and this pregnancy warrants treatment — low-dose aspirin with prophylactic heparin is the standard approach, which is a very different pregnancy from the one she would otherwise have.\n\nAnd the standing caution still applies in reverse: the antibody alone, without a clinical criterion, is not the syndrome and is generally not anticoagulated. She has the clinical criterion.",
  {"1": "In early primary syphilis the NON-treponemal test is often the one that is still negative, while treponemal tests turn positive earliest. A discordant pattern with a negative treponemal test on two specimens argues against any stage of syphilis.",
   "2": "Adequately treated syphilis characteristically leaves the TREPONEMAL test positive for life while the non-treponemal titre falls. Her pattern is the exact inverse.",
   "3": "Passive transfer of maternal antibody explains a positive test in a NEWBORN, not in the mother herself. She is the patient whose antibodies are being measured.",
   "4": "Acute infections, including viral illnesses, are a recognised cause of transient biological false-positive non-treponemal tests, so this is a genuine competitor. It does not explain her prolonged aPTT, her thrombocytopenia, or a fetal death at 22 weeks."},
  "The screening test for syphilis uses a fat molecule as bait. Her immune system makes antibodies against that exact fat molecule for a completely different reason — so the test lights up even though she does not have syphilis. That antibody is also why she lost a pregnancy.")

# ══════════════════ §34 · HIT, TESTING AND DURATION ══════════════════

# ── 14. The 4T score and the two immediate actions (§34) ───────────────────
q("A 68-year-old man is on day 7 after elective hip arthroplasty and has been receiving subcutaneous unfractionated heparin since surgery. He has no bleeding. This morning his right calf is swollen and tender, and compression ultrasonography shows an occlusive popliteal vein thrombus. He has received no other new medications, has no infection, and his surgical wound is clean and dry.\n\nLaboratory studies show:\nHemoglobin 11.4 g/dL (N=13.0–16.0 g/dL)\nHematocrit 34% (N=37%–49%)\nPlatelet count 78,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 12 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 33 seconds (N=25–35 seconds)\nFibrinogen 410 mg/dL (N=200–400 mg/dL)\n\nHis platelet count was 242,000/mm3 on admission. Which of the following is the most appropriate next step?",
  ["A. Continue heparin and transfuse platelets",
   "B. Continue heparin while awaiting antibody testing",
   "C. Stop heparin and begin argatroban",
   "D. Stop heparin and begin warfarin alone",
   "E. Stop heparin and give no further anticoagulation"],
  2,
  "His 4T score is 8 — high probability:\n• THROMBOCYTOPENIA: a fall from 242,000 to 78,000/mm3, greater than 50%, with a nadir between 20 and 100 × 10⁹/L — 2 POINTS.\n• TIMING: clear onset on day 7, within the 5 TO 10 DAY window — 2 POINTS.\n• THROMBOSIS: a new deep venous thrombosis — 2 POINTS.\n• OTHER CAUSE: none evident — 2 POINTS.\n\nHIGH (6–8) → TREAT AS HIT. STOP THE HEPARIN, START AN ALTERNATIVE. DO NOT WAIT FOR A RESULT. The alternative is a DIRECT THROMBIN INHIBITOR — ARGATROBAN or lepirudin.\n\nTHE COUNTERINTUITIVE CORE: HIT IS A PROTHROMBOTIC STATE. The platelet count falls, but the danger is THROMBOSIS, NOT BLEEDING — new venous and arterial clots at roughly 4:1 VENOUS TO ARTERIAL. Every management error follows from forgetting this.\n\nThe mechanism explains the timing: heparin binds platelets and forms a complex with PLATELET FACTOR 4; the immune system must RECOGNISE THAT COMPLEX AND MANUFACTURE ANTIBODIES against it, which takes 5 TO 14 DAYS. The antibody then binds platelets and ACTIVATES them — which is why the count falls (they are consumed into clots) and why the patient CLOTS RATHER THAN BLEEDS.\n\nStopping the heparin includes FLUSHES AND HEPARIN-BONDED LINES. Send heparin–PF4 antibodies, but treat first.",
  {"0": "Continuing the drug that is driving the thrombosis, and adding platelets to a consumptive prothrombotic state, combines two errors. Platelet transfusion is avoided in HIT except for life-threatening bleeding — and he is not bleeding.",
   "1": "The immunoassay is very sensitive but NOT SPECIFIC, and the confirmatory serotonin release assay runs only in reference laboratories, so the answer is not quick. At a 4T score of 8 you treat and send the test, not the reverse.",
   "3": "Warfarin alone in HIT is specifically prohibited: it drops PROTEIN C BEFORE IT DROPS THE PROCOAGULANT FACTORS, transiently deepening the prothrombotic state in a patient who is already thrombosing, and causing VENOUS LIMB GANGRENE.",
   "4": "Stopping everything because the platelets are low is exactly the wrong instinct — HIT is a clotting disease. He has an established thrombosis and needs alternative anticoagulation, not none."},
  "The heparin has made his immune system attack his own platelets in a way that makes them clump and clot. His platelet count is falling because the platelets are being used up in new clots — so he needs a different blood thinner immediately, not less blood thinning.",
  exim="fig_slide_hit",
  excap="Heparin-induced thrombocytopenia: heparin–platelet factor 4 complexes, antibody formation, and platelet activation.")

# ── 15. Why not low-molecular-weight heparin (§34) ─────────────────────────
q("A 59-year-old woman was diagnosed with heparin-induced thrombocytopenia 6 weeks ago during an admission for pneumonia, confirmed by a positive serotonin release assay. She recovered fully and her platelet count normalized. She now presents with a proximal deep venous thrombosis of the left leg and requires anticoagulation. Her renal and hepatic function are normal and she is not bleeding. Her platelet count today is 268,000/mm3.\n\nWhich of the following is the most appropriate anticoagulant?",
  ["A. Argatroban",
   "B. Enoxaparin",
   "C. Fondaparinux at prophylactic dose",
   "D. Unfractionated heparin with close platelet monitoring",
   "E. Warfarin alone, started today at 10 mg"],
  0,
  "ONCE A PATIENT HAS HAD HIT, LOW-MOLECULAR-WEIGHT HEPARIN AND FONDAPARINUX ARE CLOSED OFF TOO. THEY ARE STRUCTURALLY RELATED AND THE EXISTING ANTIBODY CAN CROSS-REACT. A LOWER RISK OF CAUSING HIT IS NOT THE SAME AS BEING SAFE ONCE THE ANTIBODY EXISTS.\n\nThat is the distinction the question turns on, and it is the one most often missed: the argument for enoxaparin over unfractionated heparin concerns the chance of DEVELOPING the antibody in a naive patient. It says nothing about a patient who already has one.\n\nThe correct choice is an agent from a different structural class entirely — a DIRECT THROMBIN INHIBITOR such as ARGATROBAN, which does not contain the heparin backbone and cannot be bound by an anti-PF4/heparin antibody. (In practice a direct oral factor 10a inhibitor is also used once the acute phase has passed, but argatroban is the agent named for HIT in this material.)\n\nThe timing matters too. Antibodies from an episode within the PAST 100 DAYS can produce RAPID-ONSET HIT WITHIN HOURS of re-exposure, because there is no immunisation delay — her episode was 6 weeks ago, squarely inside that window.\n\nThe three named errors, worth reciting together: DO NOT USE WARFARIN ALONE (venous limb gangrene from the early protein C drop), DO NOT SWITCH TO LOW-MOLECULAR-WEIGHT HEPARIN (cross-reactivity), and DO NOT STOP ANTICOAGULATION ALTOGETHER.",
  {"1": "Enoxaparin is the answer most students reach for, since low-molecular-weight heparin causes HIT less often than unfractionated heparin does. The existing antibody cross-reacts with it, so it can precipitate recurrent HIT with thrombosis.",
   "2": "Fondaparinux is a synthetic pentasaccharide with a much lower HIT risk and is used off-label in some HIT protocols, so it is not absurd. It shares the heparin backbone chemistry and is explicitly closed off here, and a prophylactic dose would be inadequate for an acute proximal thrombosis anyway.",
   "3": "Any heparin compound is contraindicated once the antibody exists, and monitoring the platelet count does not prevent the thrombosis it can trigger — it only detects it afterwards.",
   "4": "Warfarin alone in a patient with HIT antibodies risks VENOUS LIMB GANGRENE, because protein C falls before the procoagulant factors. Warfarin is introduced only after the platelet count has recovered and with an overlapping non-heparin anticoagulant."},
  "Her immune system already carries antibodies against heparin. The gentler versions of heparin are chemically the same family, so the antibodies recognise them too. She needs a drug from a completely different family.",
  exim="fig_slide_hit_mgmt",
  excap="Management of HIT: stop all heparin, start a non-heparin anticoagulant, and never warfarin alone.")

# ── 16. Rapid-onset HIT (§34) ──────────────────────────────────────────────
q("A 64-year-old man undergoes coronary artery bypass grafting and receives unfractionated heparin during the procedure. Four hours postoperatively he develops acute right arm pain with a cool, pulseless hand, and angiography shows brachial artery occlusion. He had received a 5-day course of unfractionated heparin during an admission 7 weeks earlier. He is not bleeding and has received no other new drugs.\n\nLaboratory studies show:\nPlatelet count 46,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 13 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 36 seconds (N=25–35 seconds)\nFibrinogen 420 mg/dL (N=200–400 mg/dL)\n\nHis platelet count was 228,000/mm3 preoperatively. Which of the following best explains the timing of his presentation?",
  ["A. Antibodies persisting from his exposure 7 weeks ago",
   "B. Dilutional thrombocytopenia from the bypass circuit",
   "C. Direct platelet aggregation by heparin without antibody",
   "D. Disseminated intravascular coagulation after cardiac surgery",
   "E. Immunization occurring more rapidly after a second exposure"],
  0,
  "The usual 5 TO 14 DAY delay in HIT is an IMMUNE DELAY: the system must recognise the heparin–platelet factor 4 complex and manufacture antibodies against it.\n\nWITH PRE-EXISTING ANTIBODY FROM EXPOSURE IN THE PAST 100 DAYS THERE IS NO IMMUNISATION DELAY, SO ONSET IS WITHIN HOURS. His exposure was 7 weeks ago — 49 days, inside the window — so circulating antibody was waiting when heparin was given on bypass. That is RAPID-ONSET HIT, and it is the variant that catches people out, because the timing looks wrong for the diagnosis.\n\nThe other variant worth knowing sits at the far end: a few patients present DAYS AFTER HEPARIN HAS BEEN STOPPED — DELAYED-ONSET HIT — easy to miss because the drug is already gone.\n\nEverything else here fits HIT rather than its mimics: a greater than 50% platelet fall, an ARTERIAL thrombosis (HIT produces new venous and arterial clots at roughly 4:1 venous to arterial, so an arterial event is entirely compatible), a normal PT and aPTT, and a fibrinogen that is HIGH rather than falling — which is what excludes DIC.\n\nManagement is unchanged by the timing: STOP ALL HEPARIN including flushes and heparin-bonded lines, START ARGATROBAN, send the heparin–PF4 immunoassay, and treat the limb ischemia as a surgical emergency. Do not switch to low-molecular-weight heparin, do not start warfarin alone, and do not simply stop anticoagulation.",
  {"1": "Cardiopulmonary bypass genuinely causes a dilutional and consumptive drop in platelets, and a modest fall in the first 24 hours is expected. It does not cause arterial thrombosis, and a fall to 46,000/mm3 with a limb-threatening clot is not explained by dilution.",
   "2": "Heparin can cause a mild, transient, non-immune platelet fall in the first 2 days without antibody — a real phenomenon. It is not associated with thrombosis, and it does not drop the count this far.",
   "3": "DIC after cardiac surgery would prolong the PT and aPTT and consume fibrinogen. His times are normal and his fibrinogen is 420 mg/dL, above the reference range as an acute-phase reactant.",
   "4": "This describes an anamnestic response — a faster secondary immune response — which sounds plausible but is not the mechanism. The antibody is already present and circulating, so no new immune response is required at all."},
  "Normally it takes about a week for the immune system to build the antibody that causes this reaction. He built it during a hospital stay two months ago, and it is still in his blood — so this time the reaction happened within hours.")

# ── 17. Monitoring the right heparin with the right test (§34) ─────────────
q("A 34-year-old woman at 26 weeks' gestation with a proximal deep venous thrombosis is receiving therapeutic subcutaneous enoxaparin twice daily. She weighs 128 kg (282 lb). The covering resident orders a daily activated partial thromboplastin time, which returns at 32 seconds (N=25–35 seconds), and proposes to increase the dose because the result is not prolonged. The patient reports no bleeding and her leg symptoms are improving.\n\nWhich of the following is the most appropriate response?",
  ["A. Add unfractionated heparin to achieve a prolonged aPTT",
   "B. Increase the enoxaparin dose as the resident proposes",
   "C. Measure anti-factor Xa activity instead of the aPTT",
   "D. Switch to warfarin, which can be monitored by the ratio",
   "E. Take no action, since anticoagulation cannot be measured"],
  2,
  "The mechanism is CHAIN LENGTH. Heparin is a CHAIN OF SUGARS and comes in different lengths.\n\n• TO INACTIVATE THROMBIN, antithrombin and thrombin must be BRIDGED TOGETHER, and it is the heparin molecule's LONG TAIL that provides that bridge. ONLY A LONG CHAIN CAN DO IT.\n• TO INACTIVATE FACTOR 10a, NO BRIDGE IS NEEDED — antithrombin does it well on its own once heparin has activated it. A SHORT CHAIN IS ENOUGH.\n\nSo unfractionated heparin has strong anti-thrombin AND anti-factor-10a effects, and the aPTT works because it senses the thrombin effect. Low-molecular-weight heparins and fondaparinux have a WEAK ANTI-THROMBIN EFFECT and a STRONG ANTI-FACTOR-10a EFFECT, so THE aPTT HAS LITTLE TO DETECT. A normal aPTT on enoxaparin means nothing about whether she is anticoagulated.\n\nMOST PATIENTS ON LOW-MOLECULAR-WEIGHT HEPARIN NEED NO MONITORING AT ALL — that predictability is the point of the drug. When monitoring is genuinely indicated — PREGNANCY, OBESITY, RENAL IMPAIRMENT, and she has two of the three — measure ANTI-FACTOR 10a ACTIVITY: 0.5–1.0 U/mL FOR TWICE-DAILY DOSING, 1.0–2.0 U/mL FOR ONCE DAILY.\n\nThe targets for unfractionated heparin, for contrast: aPTT 1.5–2.5 TIMES NORMAL, or ANTI-Xa 0.3–0.7 U/mL. A practice note worth carrying: anti-factor 10a has largely replaced the aPTT even for unfractionated heparin in many laboratories, so a modern chart saying 'therapeutic heparin level' usually means the anti-Xa result.",
  {"0": "Adding a second anticoagulant to make a monitoring test move is treating the number rather than the patient, and it multiplies bleeding risk. The aPTT is simply the wrong assay for this drug.",
   "1": "Dose escalation based on an uninformative test risks overdose and bleeding. Her clinical course is improving, and if a dose check is wanted, the correct measurement exists.",
   "3": "Warfarin is CONTRAINDICATED IN PREGNANCY — it crosses the placenta and is teratogenic, causing fetal warfarin syndrome with nasal hypoplasia and stippled epiphyses. Low-molecular-weight heparin is the agent of choice precisely because it does not cross the placenta.",
   "4": "Anticoagulation from a low-molecular-weight heparin certainly can be measured — by anti-factor 10a activity. The statement that it cannot is what leads teams either to over-escalate or to abandon monitoring in the patients who most need it."},
  "The standard clotting test only notices the long molecules of heparin. She is on the short version, so the test stays normal no matter how much she gets. There is a different test that measures the short version properly.")

# ── 18. Duration is set by the circumstances (§34) ─────────────────────────
q("A 28-year-old woman had a proximal deep venous thrombosis 3 months ago, 2 weeks after starting a combined oral contraceptive. She has completed 3 months of anticoagulation and has stopped the contraceptive. She has no personal or family history of thrombosis, no malignancy, and no recent surgery, travel, or immobility. Thrombophilia testing sent at the time of her admission, while she was receiving heparin, showed heterozygous factor V Leiden and an antithrombin III activity of 54% (N=80%–120%). Her leg symptoms have fully resolved.\n\nWhich of the following is the most appropriate management?",
  ["A. Continue anticoagulation indefinitely for antithrombin deficiency",
   "B. Continue anticoagulation indefinitely for factor V Leiden",
   "C. Repeat antithrombin testing and stop anticoagulation now",
   "D. Restart the contraceptive with aspirin for prophylaxis",
   "E. Switch to indefinite low-dose aspirin for secondary prevention"],
  2,
  "Two separate errors have to be unpicked here.\n\nFirst, THE ANTITHROMBIN RESULT IS UNINTERPRETABLE. HEPARIN DECREASES ANTITHROMBIN III LEVELS, and antithrombin can also be CONSUMED BY THE ACUTE THROMBOSIS ITSELF. Thrombophilia testing in the acute period is unreliable across the board: PREGNANCY alters multiple levels; THE ACUTE PERIOD AND INFLAMMATION elevate factor 8 and fibrinogen; HEPARIN lowers antithrombin; WARFARIN lowers proteins C and S; and a LUPUS ANTICOAGULANT MAY BE TRANSIENT, hence the 12-week repeat rule. The recommendation is to WAIT SEVERAL MONTHS AFTER THE THROMBOTIC EPISODE AND, IF POSSIBLE, OFF ANTICOAGULATION — which is exactly where she is now. GENETIC TESTING IS THE ONE EXCEPTION: factor V Leiden and prothrombin G20210A may be run at any time and only ever need running once.\n\nSecond, DURATION IS SET BY THE CIRCUMSTANCES OF THE CLOT, NOT THE GENOTYPE. Recurrence risk in the first year: 3% AFTER A MAJOR TRANSIENT RISK FACTOR (surgery, hospital bedrest); 5% AFTER A MINOR REVERSIBLE ONE (oral contraceptive, a long flight); 10% FOR UNPROVOKED VTE OR A PERSISTENT RISK FACTOR. Her contraceptive is a MINOR REVERSIBLE risk factor and it has been removed.\n\nAnd heterozygous factor V Leiden carries a relative risk of only 3 TO 5 TIMES, is carried by about 5% of Caucasians, and DOES NOT BY ITSELF JUSTIFY INDEFINITE ANTICOAGULATION.\n\nSo: stop anticoagulation, repeat the antithrombin level now that she is off heparin and months from the event, and avoid estrogen-containing contraception in future.",
  {"0": "This is the trap the vignette is built around. A single low antithrombin level drawn ON HEPARIN during an acute clot cannot establish an inherited deficiency — both the drug and the thrombus lower it — and committing her to lifelong anticoagulation on that basis is a serious harm.",
   "1": "Heterozygous factor V Leiden is the most COMMON thrombophilia and by no means the most dangerous, at 3 to 5 times relative risk. Finding it in a patient with a provoked clot rarely changes management.",
   "3": "Restarting the very agent that provoked the thrombosis is unsafe, and aspirin does not provide adequate protection against venous thromboembolism. She needs non-estrogen contraception.",
   "4": "Aspirin has a modest effect on recurrent venous thromboembolism and is sometimes used when anticoagulation is declined. For a provoked clot with the trigger removed, indefinite therapy of any kind is not indicated."},
  "The blood test suggesting a clotting disorder was taken while she was on heparin, which lowers that very protein — so it may be a false alarm and needs repeating now. And her clot had an obvious cause that has been removed, so she does not need to stay on blood thinners.",
  exim="fig_slide_risk_strat",
  excap="Risk stratification: losing a brake carries an order of magnitude more risk than factor V Leiden.")

# ── 19. Who should be tested at all (§34) ──────────────────────────────────
q("Four patients are discussed at a hematology clinic. The team must decide which should undergo an inherited thrombophilia evaluation. Patient 1 is a 72-year-old man with a calf deep venous thrombosis 5 days after a total knee replacement. Patient 2 is a 68-year-old woman with a pulmonary embolism and newly diagnosed metastatic pancreatic cancer. Patient 3 is a 24-year-old man with cerebral venous sinus thrombosis and no identifiable provoking factor, whose mother had a pulmonary embolism at 38. Patient 4 is a 55-year-old woman with a superficial thrombophlebitis of the forearm after a peripheral cannula.\n\nWhich patient is the most appropriate candidate for thrombophilia testing?",
  ["A. Patient 1",
   "B. Patient 2",
   "C. Patient 3",
   "D. Patient 4"],
  2,
  "The indications for evaluating for thrombophilia mirror the hereditary-bleeding features almost exactly: FAMILY HISTORY OF CLOTTING · YOUNG AGE, UNDER 45 YEARS · ABSENCE OF RISK FACTORS (no recent surgery, long flight or malignancy) · RECURRENT THROMBOSES · UNUSUAL LOCATION (upper extremity, mesenteric vessels, CEREBRAL VENOUS SINUS) · and specific paediatric scenarios.\n\nPatient 3 satisfies four of them at once: 24 years old, an unusual site, no provoking factor, and an affected first-degree relative at a young age.\n\nThe governing rule, put forcefully: 'IF YOU'RE SENDING THE TEST AND THE RESULT DOESN'T IMPACT ANYTHING YOU'RE DOING, YOU PROBABLY DIDN'T NEED TO SEND THAT TEST.' These assays cost money and, worse, GENERATE FINDINGS THAT INVITE UNNECESSARY LIFELONG THERAPY. Before sending, be able to finish this sentence: IF IT IS POSITIVE I WILL DO X; IF IT IS NEGATIVE I WILL DO Y. IF X AND Y ARE THE SAME, DON'T SEND IT.\n\nThe two answers that legitimately justify testing are 'IT WILL CHANGE WHETHER OR HOW LONG I ANTICOAGULATE' and 'IT WILL TRIGGER FAMILY COUNSELLING AND SCREENING'. Both apply to patient 3.\n\nThe statistical argument behind all of this: SOME FORM OF THROMBOPHILIA IS PRESENT IN ROUGHLY 25% OF THE GENERAL POPULATION, and about 60% OF PATIENTS PRESENTING WITH A DEEP VEIN THROMBOSIS will have one. A FINDING PRESENT IN A QUARTER OF EVERYONE DOES NOT, BY ITSELF, EXPLAIN A CLOT.",
  {"0": "A clot 5 days after knee replacement is provoked by a MAJOR TRANSIENT RISK FACTOR, carrying only a 3% first-year recurrence risk. Finding a thrombophilia would not change his duration of therapy, so the test fails the 'what will I do differently' question.",
   "1": "Active malignancy is a PERSISTENT risk factor that fully explains the event and independently justifies extended anticoagulation. A thrombophilia result cannot lengthen therapy that is already indefinite, and her prognosis is driven by the cancer.",
   "3": "Superficial thrombophlebitis after a cannula is a local, catheter-related, provoked event — and note that SUPERFICIAL venous thrombosis does not even satisfy the vascular criterion for antiphospholipid syndrome. It is not an indication for a thrombophilia workup."},
  "Clotting disorders are so common that finding one in someone whose clot already has an obvious cause proves nothing and changes nothing. You test the young person with a clot in a strange place, no explanation, and a family history — because there the answer actually changes what you do.",
  exim="fig_slide_thrombosis_risk",
  excap="Risk factors sorted into transient, persistent and inherited — the frame that decides who is worth testing.")

# ── 20. Warfarin-induced skin necrosis (§34) ───────────────────────────────
q("A 52-year-old woman is admitted with an unprovoked proximal deep venous thrombosis and started on warfarin 10 mg daily without an overlapping parenteral anticoagulant. On the third day she develops painful, well-demarcated purple-black lesions over both breasts and the left thigh, with surrounding erythema. She is afebrile and blood cultures are negative. Her platelet count is 224,000/mm3 and her international normalized ratio is 2.4.\n\nWhich of the following best explains this complication?",
  ["A. An immune reaction to warfarin causing small-vessel vasculitis",
   "B. Direct toxicity of warfarin to dermal capillary endothelium",
   "C. Embolization of cholesterol crystals from an aortic plaque",
   "D. Heparin-induced antibodies activating platelets in the skin",
   "E. Protein C falling faster than the procoagulant factors"],
  4,
  "WARFARIN-INDUCED SKIN NECROSIS: PROTEIN C FALLS BEFORE THE PROCOAGULANT FACTORS DO, SO THE FIRST DAYS OF WARFARIN ARE TRANSIENTLY MORE PROTHROMBOTIC. Classically this occurs in patients with underlying PROTEIN C DEFICIENCY, and classically after a large loading dose with no overlapping parenteral anticoagulant — both present here.\n\nThe arithmetic behind it is half-lives. Warfarin blocks vitamin K-dependent gamma-carboxylation of FACTORS 2, 7, 9 AND 10 PLUS PROTEINS C AND S. Protein C has a half-life of about 8 hours, comparable to factor 7 — so it disappears within a day, while factor 2 (prothrombin), with a half-life of 60 to 72 hours, is still circulating in force. The result is a window in which the ANTICOAGULANT side has gone and the PROCOAGULANT side has not.\n\nThat is also why THE INR IS MISLEADING EARLY: it is driven mainly by factor 7 and can look therapeutic at 2.4 while prothrombin remains high — the reason warfarin is bridged with heparin until the INR has been therapeutic for at least 24 to 48 hours, and why a loading dose is avoided.\n\nThe same mechanism recurs twice more in this block. VENOUS LIMB GANGRENE is warfarin alone in a patient with HIT — the identical protein C drop in someone who is ALREADY thrombosing, which is why warfarin alone is prohibited there. And NEONATAL PURPURA FULMINANS is the genetic version, in homozygous protein C or S deficiency.\n\nManagement: stop warfarin, give vitamin K, start a parenteral anticoagulant, and consider protein C concentrate.",
  {"0": "Drug-induced small-vessel vasculitis produces palpable purpura, usually on dependent areas, often with fever and sometimes renal or joint involvement. It does not produce sharply demarcated full-thickness necrosis at fatty sites within 3 days.",
   "1": "Warfarin has no direct cytotoxic effect on endothelium — it acts only by inhibiting vitamin K epoxide reductase in hepatocytes. The lesion is thrombotic occlusion of dermal vessels, not a chemical burn.",
   "2": "Cholesterol embolization causes livedo reticularis, blue toes, eosinophilia and renal impairment, typically after an arterial procedure or with anticoagulation over months. It does not localize to breast and thigh fat within 3 days of starting a drug.",
   "3": "Heparin-induced antibodies cause HIT, with a falling platelet count and thrombosis — and warfarin alone in that setting causes VENOUS LIMB GANGRENE by the same protein C mechanism. She received no heparin, and her platelet count is normal at 224,000/mm3."},
  "Warfarin switches off both the clotting proteins and one of the body's natural brakes. The brake disappears first, so for the first couple of days the blood is actually MORE likely to clot — and tiny clots killed the skin over her breasts and thigh.",
  exim="fig_slide_protein_cs",
  excap="The same protein C mechanism as neonatal purpura fulminans, arriving pharmacologically instead of genetically.")
