# Jeevs Edition — Batch 15: COAGULATION I · BLEEDING
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §29 s26-cascade            — the cascade, PT/aPTT, the mixing study      (LO 50, 32)
#   §30 s27-bleeding-inherited — bleeding patterns, hemophilia, VWD, platelets (LO 32, 36, 68, 79)
#   §31 s28-bleeding-acquired  — liver disease, DIC, vitamin K, inhibitors   (LO 32, 36)
# Options alphabetised; "correct" is the 0-based index AFTER alphabetisation.
# Option lengths balanced per the audit rule — the keyed answer is not the longest.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ══════════════ §29 · THE CASCADE, PT/aPTT AND THE MIXING STUDY ══════════════

# ── 1. The aPTT that does not bleed (§29) ───────────────────────────────────
q("A 42-year-old man has preoperative testing before an elective inguinal hernia repair. He has never had abnormal bleeding: he had a tonsillectomy at age 9 and two dental extractions without difficulty, bruises no more than his peers, and takes no medications. There is no family history of bleeding. His temperature is 36.8°C (98.2°F), pulse is 72/min, and blood pressure is 124/78 mm Hg. Physical examination shows no petechiae, no bruising, and no joint deformity.\n\nLaboratory studies show:\nProthrombin time 12 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 58 seconds (N=25–35 seconds)\nPlatelet count 254,000/mm3 (N=150,000–400,000/mm3)\nFibrinogen 320 mg/dL (N=200–400 mg/dL)\n\nA 1:1 mix with normal pooled plasma corrects the activated partial thromboplastin time to 31 seconds. Which of the following is the most likely deficiency?",
  ["A. Factor IX deficiency",
   "B. Factor VIII deficiency",
   "C. Factor XI deficiency",
   "D. Factor XII deficiency",
   "E. Von Willebrand disease"],
  3,
  "An isolated prolonged aPTT with a normal PT points at the INTRINSIC pathway — factors 8, 9, 11 and 12. If a common-pathway factor (2, 5, 10) or fibrinogen were low, THE PT WOULD BE PROLONGED TOO.\n\nThe mixing study CORRECTS, so this is a deficiency rather than an inhibitor — something is missing, not blocking.\n\nAnd the deficiency that fits a man with a completely negative bleeding history, including a tonsillectomy and two dental extractions, is FACTOR 12. Factor 12 deficiency PROLONGS THE aPTT BUT DOES NOT CAUSE BLEEDING. In vivo you do not need factor 12 at all — there is a BACKUP CONTACT SYSTEM using other contact factors. The in vitro test, however, genuinely depends on factor 12 being present. IT IS A CASE WHERE THE ASSAY IS NOT THE SAME AS THE BODY.\n\nRanked by what they mean when the aPTT is isolated and long: FACTOR 8 = hemophilia A (1 in 5,000 males); FACTOR 9 = hemophilia B (1 in 30,000 males); FACTOR 11 = hemophilia C, autosomal, milder; FACTOR 12 = no bleeding.\n\nIt still matters to make the diagnosis, because otherwise EVERY aPTT THIS PATIENT EVER HAS WILL BE RE-INVESTIGATED — and he may have a procedure delayed for a laboratory finding that carries no risk.\n\nRemember also how the arms are read: the LEFT arm runs 12 → 11 → 9 → 8 (intrinsic, aPTT), the RIGHT arm is just 7 (extrinsic, PT), and they meet at factor 10 and run down the shared trunk 10 → 5 → 2 → fibrinogen → fibrin.",
  {"0": "Factor 9 deficiency is hemophilia B, and it produces exactly this laboratory pattern — an isolated long aPTT correcting on a mix. It would not produce a lifetime without bleeding, including an uneventful tonsillectomy, which is a substantial hemostatic challenge.",
   "1": "Factor 8 deficiency is hemophilia A, six times more common than hemophilia B. Even mild disease, at 5% to 30% of normal, typically declares itself at a first operation — and his tonsillectomy would have been that test.",
   "2": "Factor 11 deficiency is hemophilia C, autosomal and enriched in Ashkenazi Jewish populations. It is genuinely mild and correlates poorly with the factor level, often surfacing only after surgery — but it does bleed, which is why the pairing to remember is that 11 bleeds and 12 does not.",
   "4": "Von Willebrand disease usually leaves the aPTT NORMAL, because the PT and aPTT are plasma assays that cannot see platelets. The aPTT prolongs only in severe disease when the factor 8 carried by von Willebrand factor falls secondarily, and that patient bleeds mucocutaneously."},
  "His clotting test looks abnormal, but the missing protein is one the body does not actually need — there is a backup route. The test needs it; he does not. He has never bled, and he will not.",
  exim="fig_slide_cascade",
  excap="The waterfall cascade. The left arm is the intrinsic pathway measured by the aPTT; the right arm is factor 7 alone, measured by the PT.")

# ── 2. The short-draw blue top (§29) ────────────────────────────────────────
q("A 55-year-old woman scheduled for a laparoscopic cholecystectomy has a coagulation screen sent from the preoperative clinic. She has no history of bleeding, takes no anticoagulant, and has had two uncomplicated cesarean deliveries. Her examination shows no bruising or petechiae. The laboratory notes that the light blue-top tube arrived approximately half filled.\n\nLaboratory studies show:\nProthrombin time 18 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 61 seconds (N=25–35 seconds)\nPlatelet count 268,000/mm3 (N=150,000–400,000/mm3)\nFibrinogen 340 mg/dL (N=200–400 mg/dL)\n\nWhich of the following is the most appropriate next step?",
  ["A. Give intravenous vitamin K and repeat the study",
   "B. Proceed to surgery after transfusing two units of plasma",
   "C. Reject the specimen and redraw a properly filled tube",
   "D. Report the result and request a mixing study",
   "E. Send factor VIII and factor IX activity levels"],
  2,
  "Coagulation samples go into SODIUM CITRATE — the LIGHT BLUE TOP. Citrate REVERSIBLY chelates calcium, so the laboratory can add calcium back and start the reaction on demand. (Contrast the lavender-top EDTA tube used for the complete blood count, where the calcium binding is not reversed.)\n\nThe critical detail is the ratio: THE RATIO OF WHOLE BLOOD TO ANTICOAGULANT MUST BE 9:1. An underfilled tube carries PROPORTIONALLY TOO MUCH CITRATE, so when calcium is added back THERE IS NOT ENOUGH OF IT — producing an ARTIFICIALLY PROLONGED CLOTTING TIME. Such samples are REJECTED.\n\nA SHORT-DRAW BLUE TOP IS ONE OF THE COMMONEST REASONS A 'COAGULOPATHY' TURNS OUT NOT TO EXIST. Notice that both times are prolonged here while the fibrinogen and platelet count are normal, in a woman with two uncomplicated cesarean deliveries — a negative bleeding history through prior surgery is the strongest single piece of contrary evidence you can get.\n\nThe underlying chemistry is worth naming: calcium is 'FACTOR 4', a required cofactor throughout the cascade. That is why the tube works as it does — and it is the same fact that makes a hypocalcemic patient coagulopathic, which recurs in massive transfusion, where citrated blood chelates the patient's own calcium, and in DiGeorge syndrome.\n\nThis is a laboratory-error question rather than a hematology question, and it is exactly the kind of thing a coagulation laboratory director puts on a test.",
  {"0": "Vitamin K would be the move for a genuinely prolonged PT from deficiency or warfarin. It does not explain a simultaneously prolonged aPTT with normal fibrinogen, and treating an artefact delays her operation for no reason.",
   "1": "Transfusing plasma exposes her to transfusion reactions, volume load and infection risk to correct a number produced by a half-filled tube. Plasma should be given for bleeding or a genuinely high-risk procedure, not to normalise an artefact.",
   "3": "A mixing study is the correct follow-up for a REAL prolongation, and it will be appropriate if the redrawn sample is still abnormal. Running it on an invalid specimen simply propagates the error into a more expensive test.",
   "4": "Factor assays are a tier-three investigation and would be sent after a valid screen localizes the problem. Isolated factor 8 or 9 deficiency also would not prolong the PT, so the pattern does not fit what is being tested for."},
  "The tube has a fixed amount of anticoagulant designed for a full tube of blood. Half a tube means twice the relative dose, and the machine cannot reverse it properly — so the clotting time reads long when her clotting is fine.")

# ── 3. The incubated mixing study (§29) ─────────────────────────────────────
q("A 68-year-old man is admitted with large spontaneous bruises over his thighs and flanks that appeared over 2 weeks. He has never had abnormal bleeding, had a hip replacement 6 years ago without difficulty, and takes no anticoagulant. He has a 3-year history of rheumatoid arthritis. His temperature is 36.9°C (98.4°F), pulse is 88/min, and blood pressure is 132/80 mm Hg. Physical examination shows extensive ecchymoses and no petechiae.\n\nLaboratory studies show:\nProthrombin time 12 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 62 seconds (N=25–35 seconds)\nPlatelet count 288,000/mm3 (N=150,000–400,000/mm3)\nFibrinogen 380 mg/dL (N=200–400 mg/dL)\n\nAn immediate 1:1 mix with normal pooled plasma corrects the activated partial thromboplastin time to 34 seconds, and the team concludes that no inhibitor is present. Which of the following is the most appropriate next step?",
  ["A. Incubate the mix at 37°C and repeat the timing",
   "B. Measure factor IX activity and stop the workup",
   "C. Order a lupus anticoagulant panel as the only test",
   "D. Reassure the patient and repeat testing in 3 months",
   "E. Transfuse fresh frozen plasma and observe overnight"],
  0,
  "They have missed a SLOW-ACTING INHIBITOR, and the answer is an INCUBATED MIXING STUDY.\n\nAcquired factor 8 antibodies are TIME- AND TEMPERATURE-DEPENDENT. On an immediate mix the antibody has not yet had time to neutralise the donated factor 8, so the clotting time corrects and LOOKS LIKE A SIMPLE DEFICIENCY. Incubating at 37°C FOR 30 TO 60 MINUTES and re-timing lets the antibody act, and the aPTT DRIFTS BACK OUT.\n\nAN IMMEDIATE MIX THAT CORRECTS DOES NOT BY ITSELF EXCLUDE AN INHIBITOR. If the clinical picture is a new bleeding diathesis, ask for the incubated study.\n\nThe clinical setting should have prompted this from the start: A NEW BLEEDING DIATHESIS IN AN OLDER PATIENT WITH NO LIFETIME HISTORY IS ACQUIRED HEMOPHILIA A UNTIL PROVEN OTHERWISE. Acquired factor inhibitors are associated with AUTOIMMUNE DISORDERS — he has rheumatoid arthritis — as well as with malignancy and cardiac valvular disease, and the typical patient is in their 50s or older with a diathesis that appears suddenly.\n\nConfirm with a FACTOR 8 ACTIVITY LEVEL and a BETHESDA TITRE, which quantifies the antibody. Treat the bleeding with a BYPASSING AGENT, since infused factor is neutralised, AND suppress the antibody with IMMUNOSUPPRESSION — because unlike congenital hemophilia, here the antibody can actually be ERADICATED.\n\nThe general principle: CORRECTS = MISSING, STAYS LONG = BLOCKED. Deficiency is a subtraction problem, so adding plasma fixes it; an inhibitor is an opposition problem, so adding plasma just gives the inhibitor more to attack.",
  {"1": "A factor 9 level addresses hemophilia B, which is congenital and would have declared itself long before age 68 — certainly at his hip replacement. Stopping the workup there would leave an acquired inhibitor untreated.",
   "2": "A lupus anticoagulant is a genuine cause of a non-correcting mix and belongs in the differential. It characteristically causes THROMBOSIS rather than bleeding, and ordering it as the only test would miss the acquired factor 8 antibody that fits his presentation.",
   "3": "Reassurance and delayed retesting is what the immediate mix appeared to justify, which is precisely the trap. Acquired hemophilia A carries substantial mortality from bleeding, and 3 months of observation is dangerous.",
   "4": "Plasma supplies factor 8 that the antibody will neutralise, so it is ineffective as treatment — and it does not establish a diagnosis. Bleeding in this setting is treated with a bypassing agent instead."},
  "Adding normal plasma made the test look normal, so the team assumed nothing was blocking the clotting. But some antibodies work slowly — warm the mixture and wait half an hour, and the antibody eats the donated protein and the test goes abnormal again.",
  exim="fig_slide_mixing_study",
  excap="The mixing study: corrects means deficiency, fails to correct means inhibitor — and a slow inhibitor needs the incubated version.")

# ── 4. The screen that cannot see platelets (§29) ────────────────────────────
q("A 27-year-old woman is referred because of lifelong heavy menstrual bleeding requiring iron therapy, frequent nosebleeds as a child, and bruising after minor contact. Her mother and sister have similar symptoms. She bled significantly after a wisdom tooth extraction at 19. Her temperature is 36.7°C (98.1°F), pulse is 84/min, and blood pressure is 112/70 mm Hg. Physical examination shows scattered ecchymoses on the limbs and no joint swelling.\n\nLaboratory studies show:\nHemoglobin 10.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 31% (N=36%–46%)\nProthrombin time 12 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 31 seconds (N=25–35 seconds)\nPlatelet count 246,000/mm3 (N=150,000–400,000/mm3)\nFibrinogen 300 mg/dL (N=200–400 mg/dL)\n\nWhich of the following is the most appropriate next test?",
  ["A. Bone marrow aspiration with cytogenetic studies",
   "B. Platelet aggregometry with lumi-aggregometry secretion studies",
   "C. Repeat the coagulation screen in 6 weeks' time",
   "D. Thrombin time and a fibrinogen activity assay",
   "E. Von Willebrand antigen and ristocetin cofactor activity"],
  4,
  "A NORMAL PT AND aPTT DOES NOT EXCLUDE A BLEEDING DISORDER, and this is the single most practically important sentence in the section.\n\nThe reason is structural, not a sensitivity limitation a better reagent could fix. These are PLASMA ASSAYS: the citrate tube is spun and the plasma taken, so THE CELLS, INCLUDING EVERY PLATELET, ARE DISCARDED WITH THE PELLET. The instrument then adds calcium back and times to clot formation. The platelets were removed before the test began, so the PT and aPTT are STRUCTURALLY INCAPABLE of detecting a platelet problem — and von Willebrand factor's platelet-tethering role is invisible to them for the same reason.\n\nSo VON WILLEBRAND DISEASE AND PLATELET FUNCTION DISORDERS DO NOT SIGNIFICANTLY AFFECT THE PT OR aPTT. A patient with a lifetime of nosebleeds, heavy periods and easy bruising can have a perfectly normal coagulation screen. ORDERING A PT AND aPTT AND STOPPING THERE IS HOW VON WILLEBRAND DISEASE GETS MISSED FOR DECADES.\n\nThe first-pass bleeding workup is therefore PT, aPTT, FIBRINOGEN, PLATELET COUNT — PLUS VON WILLEBRAND TESTING, which has to be requested separately.\n\nHer story is the classic one. Von Willebrand disease is THE MOST COMMON INHERITED BLEEDING DISORDER, usually AUTOSOMAL DOMINANT so it affects both sexes across generations, and MENORRHAGIA IS THE MOST COMMONLY MISSED PRESENTATION — von Willebrand described it in families where teenage girls died of blood loss from heavy menstrual bleeding, and heavy periods still get normalised for years before anyone sends the panel.",
  {"0": "A marrow examination looks at production, and her platelet count and hemoglobin production are not in question — her anemia is from iron loss. It is invasive and answers a question nobody has asked.",
   "1": "Platelet aggregometry is the right test for a platelet FUNCTION defect, and it will be the next tier if von Willebrand testing is normal. The explicit sequencing advice is to RULE OUT HEMOPHILIA AND VON WILLEBRAND DISEASE FIRST — platelet function disorders are rare and belong in a second- or third-tier workup.",
   "2": "Repeating a normal screen will produce another normal screen, because the assay cannot see the problem. This is the specific error that delays the diagnosis for years.",
   "3": "A thrombin time and fibrinogen assay interrogate the final step, fibrinogen to fibrin, and would pick up dysfibrinogenemia. Her fibrinogen is already normal, and this does not address primary hemostasis."},
  "The standard clotting tests are run on plasma with all the platelets spun out and thrown away. Her problem is with platelets sticking to vessel walls — so those tests are physically incapable of seeing it. She needs the specific test ordered by name.",
  exim="fig_slide_primary_hemostasis",
  excap="Primary hemostasis: collagen tethers von Willebrand factor, and the platelet grips it through GPIb — none of which a plasma clotting time can see.")

# ── 5. Factor 13 and delayed bleeding (§29) ─────────────────────────────────
q("A 4-week-old boy is brought in because of bleeding from the circumcision site that began about 30 hours after the procedure, having initially stopped normally. His umbilical stump separated at 5 weeks of age and bled for several days afterward. His parents are first cousins. His temperature is 36.9°C (98.4°F) and he is feeding well. Physical examination shows oozing from the circumcision site and no petechiae, no hepatosplenomegaly, and no joint swelling.\n\nLaboratory studies show:\nHemoglobin 11.8 g/dL (N=10.5–13.5 g/dL)\nProthrombin time 12 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 30 seconds (N=25–35 seconds)\nPlatelet count 312,000/mm3 (N=150,000–400,000/mm3)\nFibrinogen 280 mg/dL (N=200–400 mg/dL)\n\nWhich of the following is the most appropriate diagnostic test?",
  ["A. Clot solubility testing",
   "B. Factor VIII activity assay",
   "C. Platelet aggregometry",
   "D. Ristocetin cofactor activity",
   "E. Thrombin time"],
  0,
  "This is FACTOR 13 DEFICIENCY, and the reason the screening tests are normal is the reason factor 13 is drawn off to the side of the cascade: IT ACTS ON THE FIBRIN CLOT AFTER THE CLOT HAS ALREADY FORMED, cross-linking it so the finished mesh is STRONGER.\n\nThat placement IS the clinical picture. Patients with factor 13 deficiency DO MAKE A CLOT — so the PT, aPTT AND PLATELET COUNT ARE ALL NORMAL, because EVERY ONE OF THOSE TESTS STOPS TIMING AT THE POINT THE FIRST FIBRIN APPEARS. The clot is simply not as strong as it should be and FALLS OFF SOONER THAN IT SHOULD. Hence DELAYED BLEEDING, and DELAYED WOUND HEALING.\n\nThe three-way bleeding pattern match is the organizing idea:\n• MUCOCUTANEOUS — nosebleeds, gums, heavy periods, bruising → von Willebrand disease and platelet disorders → PRIMARY hemostasis.\n• JOINT AND MUSCLE — hemarthrosis, deep hematoma → hemophilia A or B → SECONDARY hemostasis.\n• DELAYED — stops, then restarts hours later → FACTOR 13 or antiplasmin deficiency → clot stabilisation.\n\nDELAYED BLEEDING AFTER CIRCUMCISION OR A DENTAL EXTRACTION WITH A NORMAL PT, aPTT AND PLATELET COUNT IS THE CLASSIC FACTOR 13 STEM. Delayed umbilical stump bleeding is the other hallmark presentation, and consanguinity fits an autosomal recessive disorder.\n\nDiagnosis needs a SPECIFIC FACTOR 13 ASSAY — classically a CLOT SOLUBILITY TEST, in which a clot from a factor 13-deficient patient dissolves in urea because it was never cross-linked. Treatment is factor 13 concentrate.",
  {"1": "Factor 8 activity diagnoses hemophilia A, which prolongs the aPTT and bleeds into joints and muscles. His aPTT is 30 seconds and his bleeding is delayed and superficial.",
   "2": "Aggregometry tests platelet function, and platelet disorders bleed mucocutaneously and IMMEDIATELY rather than 30 hours later. Platelet studies are also explicitly a second- or third-tier investigation.",
   "3": "Ristocetin cofactor activity tests the von Willebrand factor–GPIb axis. Von Willebrand disease causes mucocutaneous bleeding at the time of injury, and it is rarely the explanation for isolated delayed bleeding with normal screens.",
   "4": "The thrombin time measures the conversion of fibrinogen to fibrin and detects dysfibrinogenemia, heparin and hypofibrinogenemia. Like the PT and aPTT it STOPS AT FIRST FIBRIN, so it too is blind to a cross-linking defect."},
  "His blood clots normally — that is why every test is normal. What is missing is the protein that staples the finished clot together, so the clot holds for a while and then falls apart. That is why the bleeding starts a day later.",
  exim="fig_slide_cascade",
  excap="Factor 13 sits off to the side of the cascade because it acts after fibrin has formed — which is why every screening test stops before it matters.")

# ── 6. The isolated prolonged PT (§29) ──────────────────────────────────────
q("A 71-year-old man in the hospital for 3 weeks with a complicated intra-abdominal abscess has received broad-spectrum antibiotics throughout and has eaten almost nothing, receiving intravenous fluids only. He has no history of liver disease, drinks no alcohol, and takes no anticoagulant. His temperature is 37.2°C (99.0°F), pulse is 88/min, and blood pressure is 124/74 mm Hg. Physical examination shows a healing surgical wound with mild oozing at the drain site, no jaundice, and no ascites.\n\nLaboratory studies show:\nProthrombin time 19 seconds (N=11–15 seconds)\nInternational normalized ratio 1.8 (N=0.9–1.1)\nActivated partial thromboplastin time 33 seconds (N=25–35 seconds)\nPlatelet count 320,000/mm3 (N=150,000–400,000/mm3)\nFibrinogen 410 mg/dL (N=200–400 mg/dL)\nTotal bilirubin 0.8 mg/dL (N=0.2–1.2 mg/dL)\nAlbumin 3.2 g/dL (N=3.5–5.5 g/dL)\n\nWhich of the following best explains the laboratory findings?",
  ["A. Deficiency of factor VII, which has the shortest half-life",
   "B. Disseminated intravascular coagulation with consumption",
   "C. Factor VIII inhibitor blocking the intrinsic pathway",
   "D. Fibrinogen depletion from excessive fibrinolysis",
   "E. Lupus anticoagulant prolonging phospholipid-dependent tests"],
  0,
  "Vitamin K deficiency, presenting as an ISOLATED PROLONGED PT.\n\nVitamin K is required to make FACTORS 2, 7, 9 AND 10 functional, plus the anticoagulants PROTEIN C AND PROTEIN S. Deficiency follows MALNUTRITION, MALABSORPTION, OR PROLONGED ANTIBIOTICS — and he has two of the three, three weeks of broad-spectrum antibiotics wiping out the gut flora that supply some vitamin K, on essentially no oral intake.\n\nBecause FACTOR 7 HAS THE SHORTEST HALF-LIFE of the four, THE PT PROLONGS FIRST. An isolated long PT with a normal aPTT is the classic early picture; with time the aPTT follows as factors 2, 9 and 10 fall as well. This is the same mechanism warfarin exploits.\n\nThe PT is the test of the EXTRINSIC plus common pathway and is MOST SENSITIVE TO FACTOR 7 — which is exactly why this deficiency shows up there first.\n\nThe discriminator from liver disease is a factor most people forget to order: FACTOR 5. Vitamin K deficiency and warfarin give LOW 2, 7, 9, 10 WITH A NORMAL FACTOR 5, because factor 5 is not vitamin K dependent. Liver disease takes factor 5 down too, because the liver makes it. His normal bilirubin, absence of jaundice and absence of ascites already point away from hepatic failure, though his albumin reflects his nutritional state.\n\nTreatment is vitamin K — and the response confirms the diagnosis.",
  {"1": "Disseminated intravascular coagulation prolongs BOTH times, consumes platelets and fibrinogen, and raises the D-dimer. His platelet count is 320,000/mm3 and his fibrinogen is 410 mg/dL, both moving in the wrong direction for consumption.",
   "2": "A factor 8 inhibitor prolongs the aPTT, not the PT, since factor 8 is an intrinsic-pathway factor. His aPTT is 33 seconds.",
   "3": "Hyperfibrinolysis lowers the fibrinogen and raises fibrin degradation products, and can prolong both clotting times. His fibrinogen is above the reference range, which is what you would expect in ongoing infection since fibrinogen is an acute-phase reactant.",
   "4": "A lupus anticoagulant classically prolongs the aPTT and is associated with THROMBOSIS rather than bleeding. It also fails to correct on a mixing study, whereas a factor deficiency corrects."},
  "Three weeks of antibiotics and no food have left him short of vitamin K. The first clotting protein to run out is the one with the shortest lifespan, and that one is measured by the first test — which is why only one of his two clotting times is abnormal.",
  exim="fig_slide_pt_aptt_coverage",
  excap="Which test covers which pathway. The PT reads the extrinsic arm — factor 7 — plus the common trunk.")

# ── 7. What a D-dimer actually means (§29) ──────────────────────────────────
q("A resident asks why a D-dimer is described as a marker of clot turnover rather than simply of clotting. The attending explains that fibrin monomers contain regions labelled D and E, that factor 13 locks two adjacent D regions together when it cross-links fibrin, and that plasmin subsequently cuts the mesh apart but cannot break that particular cross-link.\n\nFor a D-dimer to be present in the circulation, which of the following must have occurred?",
  ["A. Fibrin was formed, cross-linked by factor XIII, and then lysed",
   "B. Fibrinogen was cleaved by plasmin without any clot forming",
   "C. Platelets aggregated and released their granule contents",
   "D. Prothrombin was converted to thrombin somewhere in the circulation",
   "E. Tissue factor was exposed at a site of vascular injury"],
  0,
  "The name explains the biology. Fibrin monomers contain regions labelled D and E. When FACTOR 13 cross-links fibrin it locks TWO ADJACENT D REGIONS together. Plasmin then cuts the mesh up, but IT CANNOT BREAK THAT CROSS-LINK — so the fragment released carries TWO D REGIONS: A D-DIMER.\n\nTherefore a D-DIMER CAN ONLY EXIST IF FIBRIN WAS FORMED, CROSS-LINKED BY FACTOR 13, AND THEN BROKEN DOWN. All three steps are required, which is why it is a marker of CLOT TURNOVER rather than merely of clotting.\n\nThat precision is what makes the test useful and what limits it. It is raised by ANY active clot formation and breakdown — venous thromboembolism, disseminated intravascular coagulation, recent surgery, trauma, malignancy, pregnancy, infection — which is why it has high sensitivity and poor specificity, and why it is used to EXCLUDE thrombosis in a low-probability patient rather than to establish it.\n\nIt reappears as one of the four laboratory legs of DISSEMINATED INTRAVASCULAR COAGULATION, where it rises often markedly because fibrin is being made and destroyed simultaneously throughout the circulation, and in the workup of thrombosis.\n\nThe demolition side of the system, for completeness: PLASMIN is the enzyme that digests fibrin, and TISSUE PLASMINOGEN ACTIVATOR converts plasminogen to plasmin. The mirror-image failure is also worth holding — TOO MUCH ANTIPLASMIN, or overexpression of the fibrinolysis inhibitors, CAUSES A CLOTTING PROBLEM, because clots are not taken down when they should be.",
  {"1": "Plasmin cleaving circulating fibrinogen produces fibrin degradation products, but NOT D-dimers, because no factor 13 cross-link was ever made. That distinction is exactly why the D-dimer is the more specific of the two assays.",
   "2": "Platelet activation and granule release are primary hemostasis and generate no fibrin fragments at all. The aggregometer detects that release as ATP luminescence, which is a different measurement entirely.",
   "3": "Thrombin generation is necessary but not sufficient. Thrombin cleaves fibrinogen to fibrin — but without factor 13 cross-linking and subsequent plasmin digestion, no D-dimer is released.",
   "4": "Tissue factor exposure starts the extrinsic pathway and is the trigger for the whole sequence. Starting the cascade does not by itself produce a cross-linked, subsequently degraded clot."},
  "The test detects a fragment that can only exist if a clot was built, stapled together, and then torn down. All three things must have happened — which is why it tells you clotting is actively turning over somewhere.",
  exim="fig_slide_fibrinolysis_coag",
  excap="Fibrinolysis: plasmin dismantles the cross-linked mesh, releasing the two-D fragment that gives the D-dimer its name.")

# ── 8. Both times long, neither corrects (§29) ──────────────────────────────
q("A 62-year-old woman in the intensive care unit has a coagulation screen drawn through an indwelling central venous catheter that is maintained with a flush protocol. She has had no bleeding, no bruising, and no oozing from line sites, and she is not receiving systemic anticoagulation. Her temperature is 37.1°C (98.8°F), pulse is 84/min, and blood pressure is 118/70 mm Hg.\n\nLaboratory studies show:\nProthrombin time 17 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 96 seconds (N=25–35 seconds)\nPlatelet count 232,000/mm3 (N=150,000–400,000/mm3)\nFibrinogen 360 mg/dL (N=200–400 mg/dL)\nD-dimer 0.3 µg/mL (N=<0.5 µg/mL)\n\nA 1:1 mix with normal pooled plasma corrects neither time. A sample drawn by peripheral venipuncture is normal. Which of the following best explains the original result?",
  ["A. Hemophilia A with a factor VIII level below 1%",
   "B. Heparin contamination of the specimen from the line",
   "C. Liver disease with reduced synthesis of all factors",
   "D. Vitamin K deficiency from prolonged antibiotic therapy",
   "E. Warfarin therapy at a therapeutic international ratio"],
  1,
  "Failure to correct on a mix means an INHIBITOR — something in the sample is neutralising the added factors too. When BOTH times are affected, the categories are a common-pathway inhibitor or something NON-SPECIFIC: classically a LUPUS ANTICOAGULANT, or an interfering substance such as HEPARIN CONTAMINATION FROM A LINE DRAW, or a PARAPROTEIN.\n\nHeparin is the answer here, and the vignette contains the proof: a PERIPHERAL SAMPLE IS NORMAL. Blood drawn through a heparin-flushed catheter carries enough drug to prolong the clotting times in the tube, and heparin behaves as an inhibitor on a mixing study because it acts through antithrombin to neutralise thrombin and factor 10a in the mixed sample as well. The disproportionate aPTT — 96 seconds against a PT of 17 — is the classic heparin signature, since heparin affects the aPTT far more.\n\nThe clinical context confirms it: NO BLEEDING AT ALL, with a normal platelet count, normal fibrinogen and a normal D-dimer. A patient with a genuine coagulopathy severe enough to run an aPTT of 96 seconds would usually show for it.\n\nThe practical rule: DO NOT DRAW COAGULATION STUDIES THROUGH A HEPARINIZED LINE. If it must be done, discard an adequate volume first — and when a result looks impossible, redraw peripherally before investigating further.\n\nOne paradox to carry forward: a LUPUS ANTICOAGULANT, the other classic non-correcting inhibitor, PROLONGS CLOTTING IN VITRO BUT INCREASES THROMBOSIS RISK IN VIVO.",
  {"0": "Severe hemophilia A prolongs the aPTT — often over 100 seconds — but leaves the PT NORMAL, and it is a DEFICIENCY, so the mix would correct. It would also not appear for the first time in a 62-year-old woman.",
   "2": "Liver disease reduces synthesis of nearly all factors and prolongs both times, so the pattern initially fits. It is a deficiency state, so the mixing study CORRECTS — and her fibrinogen is normal, which synthetic failure would not preserve.",
   "3": "Vitamin K deficiency is a real risk in an intensive care patient on antibiotics with poor intake, and it prolongs the PT first. It is again a deficiency that CORRECTS on mixing, and it would not normalise on a peripheral draw.",
   "4": "Warfarin prolongs the PT and INR preferentially and corrects on a mix. She is not receiving systemic anticoagulation, and her PT is only mildly long against a grossly abnormal aPTT."},
  "The blood was drawn through a line that is kept open with a blood thinner, so the sample was contaminated with the drug. A fresh sample from a vein in her arm is completely normal — and she has no bleeding at all.")

# ══════════════ §30 · READING A BLEEDING PATTERN ══════════════

# ── 9. Hemarthrosis and the expected screen (§30) ───────────────────────────
q("A 6-year-old boy is brought to the emergency department with a swollen, warm, painful right knee that developed over several hours after he tripped in the playground. He has had two similar episodes in the past year, each after minor trauma, and a large thigh hematoma after a fall at age 3. He has never had nosebleeds, gum bleeding, or petechiae. A maternal uncle has a bleeding disorder. His temperature is 37.1°C (98.8°F), pulse is 104/min, and blood pressure is 96/58 mm Hg. Physical examination shows a tense, warm knee effusion with limited flexion, and no petechiae or mucosal bleeding.\n\nWhich of the following laboratory patterns is most likely?",
  ["A. Normal PT, normal aPTT, low platelet count",
   "B. Normal PT, prolonged aPTT, normal platelet count",
   "C. Prolonged PT, normal aPTT, normal platelet count",
   "D. Prolonged PT, prolonged aPTT, low platelet count",
   "E. Prolonged PT, prolonged aPTT, normal platelet count"],
  1,
  "WHERE A PATIENT BLEEDS TELLS YOU WHICH HALF OF HEMOSTASIS HAS FAILED — BEFORE A SINGLE ASSAY IS SENT. That is the highest-yield idea in this lecture.\n\nHEMARTHROSIS — bleeding into a joint — is the signature of a COAGULATION FACTOR DEFICIENCY, not a platelet problem, and the complete absence of mucocutaneous bleeding supports it. In a boy this age with an affected maternal uncle, the answer is HEMOPHILIA A OR B until proven otherwise.\n\nThe memory hook: PLATELETS PATCH SURFACES, so when platelets fail you bleed FROM surfaces — skin and mucosa. FIBRIN FILLS SPACES, so when fibrin fails you bleed INTO spaces — joints and muscles.\n\nThe expected screen is a PROLONGED aPTT WITH A NORMAL PT, because factors 8 and 9 are both INTRINSIC-pathway factors; a NORMAL PLATELET COUNT; and a MIXING STUDY THAT CORRECTS, because this is a deficiency rather than an inhibitor. Factor 8 and factor 9 activity assays then separate hemophilia A from B — they are clinically indistinguishable at the bedside.\n\nThe X-linked inheritance fits the family history: affected MALES across generations through unaffected mothers.\n\nOne clinical point that drives management: JOINT ARTHROPATHY IS A MAJOR CAUSE OF MORBIDITY, because repeated bleeds scar a joint and it progressively stops working. That is what prophylaxis exists to prevent — not the acute pain of a single bleed.",
  {"0": "This is the platelet pattern — thrombocytopenia with normal clotting times — and it produces MUCOCUTANEOUS bleeding with petechiae. He has none, and his bleeding is into a joint.",
   "2": "An isolated prolonged PT points at factor 7, vitamin K deficiency, warfarin or early liver disease. None of those is a congenital childhood joint-bleeding disorder, and factor 7 deficiency is rare.",
   "3": "Both times prolonged with thrombocytopenia is the consumption pattern of disseminated intravascular coagulation. That is an acquired, acutely ill picture, not a 3-year history of bleeding after minor trauma in a well child.",
   "4": "Both times prolonged with a normal platelet count suggests a common-pathway factor deficiency, liver disease or vitamin K deficiency. Factors 8 and 9 sit in the intrinsic arm only, so the PT stays normal."},
  "Bleeding into a joint means the second stage of clotting has failed — the mesh that fills spaces. That stage is measured by one of the two clotting tests, so that one is long and the other is normal, with a normal platelet count.",
  exim="fig_slide_bleeding_pattern",
  excap="Platelet defects bleed from surfaces; coagulation defects bleed into spaces. The pattern points before any assay is sent.")

# ── 10. Telling hemophilia A from B (§30) ──────────────────────────────────
q("A 3-year-old boy with recurrent hemarthroses and a deep calf hematoma is being evaluated. His prothrombin time is 12 seconds (N=11–15 seconds), his activated partial thromboplastin time is 68 seconds (N=25–35 seconds), and his platelet count is 296,000/mm3 (N=150,000–400,000/mm3). A 1:1 mix with normal pooled plasma corrects the activated partial thromboplastin time to 33 seconds. His mother's brother had a similar bleeding history in childhood.\n\nWhich of the following will distinguish the two most likely diagnoses?",
  ["A. Bethesda titre for a factor inhibitor",
   "B. Factor VIII and factor IX activity assays",
   "C. Platelet aggregometry with ristocetin and collagen",
   "D. Ristocetin cofactor activity",
   "E. von Willebrand factor multimer analysis"],
  1,
  "Hemophilia A and hemophilia B are CLINICALLY INDISTINGUISHABLE AT THE BEDSIDE and produce an identical screen — prolonged aPTT, normal PT, normal platelet count, mixing study corrects. Only FACTOR 8 AND FACTOR 9 ACTIVITY ASSAYS separate them.\n\nThe two diseases side by side:\n• HEMOPHILIA A — factor 8 missing, X-LINKED, 1 IN 5,000 MALES.\n• HEMOPHILIA B — factor 9 missing, also called CHRISTMAS DISEASE, X-linked, 1 IN 30,000 MALES, so SIX TIMES RARER.\n\nBoth bleed into joints and muscles, and both are carried by females and expressed in males — his maternal uncle is the give-away in the pedigree.\n\nThe third member of the family is worth keeping in view: HEMOPHILIA C is factor 11 deficiency, AUTOSOMAL rather than X-linked, enriched in Ashkenazi Jewish populations, TYPICALLY MILDER, and correlating POORLY WITH THE FACTOR LEVEL — often surfacing only after surgery or trauma.\n\nHemophilia C is the reason to say 'FACTORS 8, 9, 11 AND 12' when listing what prolongs an isolated aPTT — and then to remember that 11 BLEEDS AND 12 DOES NOT.\n\nOne treatment rule with history behind it: in the 1980s patients with hemophilia developed AIDS with no sexual risk factors, because they were receiving CHRONIC PLASMA TRANSFUSIONS as their source of factor. Modern factor concentrates undergo VIRAL INACTIVATION, so patients with hemophilia SHOULD NOT RECEIVE PLASMA OR CRYOPRECIPITATE except as an absolute last resort.",
  {"0": "A Bethesda titre quantifies an INHIBITOR, and it is essential when a patient stops responding to factor. His mixing study corrected, which points to a deficiency rather than an antibody.",
   "2": "Aggregometry assesses platelet function, and his bleeding pattern is deep tissue rather than mucocutaneous. Platelet studies are explicitly a second- or third-tier investigation, after hemophilia and von Willebrand disease are excluded.",
   "3": "Ristocetin cofactor activity measures von Willebrand factor function. Von Willebrand disease bleeds mucocutaneously and usually leaves the aPTT normal — and it would not explain recurrent hemarthroses in a boy with an affected maternal uncle.",
   "4": "Multimer analysis subtypes von Willebrand disease and is not even a front-line test for that — it is sent after the activity-to-antigen comparison already shows something is wrong."},
  "Two different missing proteins cause exactly the same disease, with the same tests and the same symptoms. The only way to tell them apart is to measure each protein directly.",
  exim="fig_slide_hemophilia",
  excap="Hemophilia: X-linked inheritance, famously through the European royal families.")

# ── 11. Severity tracks the factor level (§30) ──────────────────────────────
q("Two cousins have hemophilia A. The first, aged 8, has had repeated spontaneous hemarthroses of both knees with no identifiable trauma, and has been on prophylaxis since age 2; his factor VIII activity is less than 1% of normal. The second, aged 34, was diagnosed only after prolonged bleeding following a wisdom tooth extraction, has never had a joint bleed, and has a factor VIII activity of 12% of normal. Both have a prolonged activated partial thromboplastin time and a normal prothrombin time.\n\nWhich of the following best explains the difference between them?",
  ["A. Factor level determines severity; below 1% bleeds spontaneously",
   "B. His cousin has hemophilia B rather than hemophilia A",
   "C. Inhibitor formation in the younger boy explains his phenotype",
   "D. Joint disease alters the local factor requirement over time",
   "E. The aPTT correlates directly with the clinical severity of bleeding"],
  0,
  "SEVERITY IS DEFINED BY THE FACTOR LEVEL, NOT BY THE SYMPTOMS, and the three bands are worth memorising:\n\n• LESS THAN 1% — SEVERE. Spontaneous bleeding, including into joints, with no identifiable trauma.\n• 1% TO 5% — MODERATE. Bleeding with minor trauma.\n• ABOVE 5% TO 30% — MILD. Bleeding usually only with surgery or significant trauma.\n\nLine that up against the 50% RULE: FACTOR LEVELS OF ROUGHLY 50% ARE ENOUGH FOR HEMOSTASIS. So a level of 30% is BELOW what full hemostasis needs but well above the severe range — which is why MILD HEMOPHILIA CAN GO UNDIAGNOSED UNTIL A FIRST OPERATION, exactly as it did in the 34-year-old.\n\nThe same 50% rule explains three other things at once: a clotting time only prolongs once a factor drops well below normal; thresholds vary with the laboratory's reagent; and the mixing study works because adding an equal volume of normal plasma lifts a deficient patient to about 50%.\n\nThe treatment target follows from the bands, and it is NOT a normal factor level. Keeping a patient above roughly 20% TO 30% is good, and ABOVE 5% ALREADY SHARPLY REDUCES THE SPONTANEOUS BLEEDING that drives joint damage. Higher targets, sustained longer, are used around major surgery.\n\nThat is the logic of prophylaxis in the 8-year-old: the aim is not to normalise a number but to lift him out of the spontaneous-bleeding range and protect his joints, because repeated bleeds scar a joint until it stops working.",
  {"1": "Hemophilia A and B are clinically indistinguishable and produce the same laboratory pattern, so swapping the diagnosis would not explain a difference in severity. Both cousins are stated to have hemophilia A.",
   "2": "An inhibitor is an alloantibody against infused factor, and it announces itself as LOSS OF RESPONSE to a dose that previously worked, with a mixing study that fails to correct. It does not create a severe phenotype in an untreated child.",
   "3": "Repeated hemarthroses genuinely do damage joints and make further bleeds more likely, so this contains a real clinical truth. It is a consequence of severe disease rather than its cause, and it does not explain a factor level of less than 1%.",
   "4": "The aPTT is a crude reflection of severity: it prolongs once the level drops below roughly 50%, is above 45 seconds under 20%, and exceeds 100 seconds in severe disease — but it is not the measure used, and it does not distinguish 12% from 30% reliably."},
  "How much of the missing protein a person still has decides how badly they bleed. Under one percent means bleeding with no injury at all; around ten percent means trouble only with surgery.",
  exim="fig_slide_fifty_percent",
  excap="Around 50% of a normal factor level is enough for hemostasis — which is why mild deficiency hides until a first operation.")

# ── 12. The inhibitor (§30) ────────────────────────────────────────────────
q("A 14-year-old boy with severe hemophilia A has been treated with recombinant factor VIII concentrate for bleeding episodes since infancy, with reliable resolution of symptoms. Over the past 2 months, two joint bleeds have failed to settle despite his usual doses, and a muscle hematoma required escalating amounts of concentrate with little effect. He is otherwise well and takes no other medication.\n\nLaboratory studies show:\nProthrombin time 12 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 74 seconds (N=25–35 seconds)\nPlatelet count 264,000/mm3 (N=150,000–400,000/mm3)\n\nA 1:1 mix with normal pooled plasma fails to correct the activated partial thromboplastin time. Which of the following is the most appropriate next step?",
  ["A. Bethesda titre and treatment with a bypassing agent",
   "B. Double the dose of factor VIII concentrate",
   "C. Give desmopressin instead of factor concentrate",
   "D. Transfuse cryoprecipitate for its factor VIII content",
   "E. Transfuse fresh frozen plasma as a factor source"],
  0,
  "INHIBITORS — alloantibodies against the infused factor — are THE SINGLE BIGGEST MANAGEMENT PROBLEM IN HEMOPHILIA. Once a patient develops one, ORDINARY REPLACEMENT IS NEUTRALISED AND STOPS WORKING.\n\nThe clue is exactly what this vignette describes: LOSS OF RESPONSE TO A DOSE THAT PREVIOUSLY WORKED. The mixing study FAILS TO CORRECT, confirming an inhibitor rather than a deficiency, and the antibody is quantified with a BETHESDA TITRE.\n\nTreatment of bleeding uses a BYPASSING AGENT, which works around the neutralised step rather than trying to replace it. Long term, immune tolerance induction aims to eradicate the antibody.\n\nEMICIZUMAB deserves its own line here, because it solves the problem by geometry. FACTOR 8a DOES NOT CUT ANYTHING — IT IS A COFACTOR that holds factor 9a and factor 10 next to each other so the reaction can happen. Emicizumab is a BISPECIFIC ANTIBODY with two arms: one grabs factor 9a, the other grabs factor 10. IT REPRODUCES THE GEOMETRY WITHOUT REPRODUCING THE PROTEIN, which is exactly what makes it INVISIBLE TO AN ANTI-FACTOR-8 ANTIBODY.\n\nAnd a practical trap worth knowing before it appears on a chart: a patient on emicizumab will have an aPTT THAT LOOKS FALSELY NORMAL OR SHORT, because the drug drives the intrinsic pathway in the tube.\n\nNote also what is NOT appropriate: plasma and cryoprecipitate are avoided in hemophilia because virally-inactivated concentrates exist — a rule that dates from the transmission of HIV and hepatitis through pooled plasma products in the 1980s.",
  {"1": "Escalating the dose is the intuitive response and has already been tried without effect. Against a significant inhibitor titre, more antigen is simply more substrate for the antibody, and it delays effective treatment of an active bleed.",
   "2": "Desmopressin releases stored von Willebrand factor and factor 8 from endothelium, and can be useful in MILD hemophilia A where there is endogenous factor to release. He has severe disease with essentially none to release, and an antibody waiting for whatever appears.",
   "3": "Cryoprecipitate contains factor 8, fibrinogen, von Willebrand factor and factor 13, so the instinct is understandable. Patients with hemophilia should not receive cryoprecipitate when concentrates exist, and the inhibitor would neutralise the factor 8 in it anyway.",
   "4": "Plasma is a dilute and non-inactivated factor source, carrying volume load and infectious risk for a small dose of factor that the antibody will neutralise. It is the historical treatment that caused the HIV catastrophe in this population."},
  "His body has made antibodies against the very protein he is given, so the treatment no longer works no matter how much is used. You measure how strong the antibody is and switch to a medicine that goes around the blocked step.",
  exim="fig_slide_emicizumab",
  excap="Emicizumab bridges factor 9a to factor 10 — reproducing what factor 8a does without being factor 8, so an anti-factor-8 antibody cannot touch it.")

# ── 13. The falsely normal aPTT on emicizumab (§30) ─────────────────────────
q("A 22-year-old man with severe hemophilia A and a high-titre factor VIII inhibitor was started on emicizumab 4 months ago and has had no bleeding episodes since. He now presents to a hospital where his history is unknown, after a motorcycle collision with a suspected retroperitoneal hematoma. The covering team notes that his coagulation screen is normal and concludes that he cannot have a significant bleeding disorder.\n\nLaboratory studies show:\nProthrombin time 12 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 23 seconds (N=25–35 seconds)\nPlatelet count 240,000/mm3 (N=150,000–400,000/mm3)\n\nWhich of the following best explains the activated partial thromboplastin time?",
  ["A. Emicizumab bridges factor IXa and factor X, driving the intrinsic pathway",
   "B. Emicizumab is a long-acting factor VIII concentrate given by subcutaneous injection",
   "C. Emicizumab neutralizes the patient's anti-factor VIII antibody",
   "D. Emicizumab replaces factor IX rather than replacing factor VIII",
   "E. The patient's inhibitor has resolved and his factor VIII has recovered"],
  0,
  "A patient on emicizumab will have an aPTT THAT LOOKS FALSELY NORMAL OR SHORT, because THE DRUG DRIVES THE INTRINSIC PATHWAY IN THE TUBE. His aPTT of 23 seconds is below the reference range, which should itself prompt the question.\n\nThe mechanism explains the artefact exactly. FACTOR 8a IS A COFACTOR, not an enzyme — it holds FACTOR 9a AND FACTOR 10 next to each other so the reaction can proceed. Emicizumab is a BISPECIFIC ANTIBODY whose two arms grab factor 9a and factor 10 respectively, REPRODUCING THE GEOMETRY WITHOUT REPRODUCING THE PROTEIN. In the aPTT tube that bridging happens continuously and without the usual regulation, so the clot forms fast.\n\nThe clinical danger is precisely what this vignette describes. He still has severe hemophilia A with a high-titre inhibitor. The drug protects him well against spontaneous bleeding, but A NORMAL OR SHORT aPTT ON EMICIZUMAB TELLS YOU NOTHING ABOUT HIS HEMOSTATIC CAPACITY for major trauma, and standard factor 8 activity assays based on the aPTT are also unreliable — chromogenic assays using bovine reagents are required.\n\nManagement here is to treat him as a severe hemophiliac with an inhibitor and a potentially life-threatening bleed: contact his hemophilia centre, use a bypassing agent with care (the combination of emicizumab with activated prothrombin complex concentrate carries a thrombotic microangiopathy risk), and image the retroperitoneum.\n\nRetroperitoneal bleeding belongs on the hemophilia list alongside joint and deep muscle bleeding, and it can be occult until a large volume has been lost.",
  {"1": "Emicizumab is not factor 8 and is not a concentrate — that is the entire design point. If it were factor 8, the patient's inhibitor would neutralise it, which is the problem it was created to solve.",
   "2": "The antibody is untouched by emicizumab; the drug simply works around it. Inhibitor eradication requires immune tolerance induction or immunosuppression, which is a separate undertaking.",
   "3": "Factor 9 is present and normal in hemophilia A — the missing protein is factor 8. Emicizumab BINDS factor 9a as one of its two targets, which is not the same as replacing it.",
   "4": "Spontaneous resolution of a high-titre inhibitor with recovery of endogenous factor 8 does not happen in severe congenital hemophilia, where the factor was never made. The short aPTT is a drug effect, not recovery."},
  "The medicine does the job of the missing protein by holding two other proteins together. In the test tube it does that job constantly, so the clotting test looks better than normal — even though he still has severe hemophilia and is bleeding.",
  exim="fig_slide_emicizumab",
  excap="The bispecific antibody in place of factor 8a. In the tube it drives the intrinsic pathway continuously, shortening the aPTT.")

# ── 14. Reading the activity-to-antigen ratio (§30) ─────────────────────────
q("A 26-year-old woman with lifelong heavy menstrual bleeding, recurrent epistaxis, and easy bruising is evaluated. Her prothrombin time, activated partial thromboplastin time, and platelet count are normal. Her father has a similar bleeding history.\n\nLaboratory studies show:\nVon Willebrand factor antigen 60% (N=50%–200%)\nRistocetin cofactor activity 22% (N=50%–200%)\nFactor VIII activity 68% (N=50%–150%)\n\nWhich of the following best describes the abnormality?",
  ["A. Complete absence of von Willebrand factor protein",
   "B. Normal protein present in a reduced amount",
   "C. Platelet receptor GPIb is absent from the surface",
   "D. Protein is present but functionally abnormal",
   "E. Secondary deficiency of factor VIII alone"],
  3,
  "The diagnostic algorithm is one sentence: ARE ACTIVITY AND ANTIGEN SIMILAR? If YES, the protein present works normally and there is just not enough of it — a QUANTITATIVE problem, TYPES 1 AND 3. If NO, with antigen much higher than activity, the protein is present but broken — a QUALITATIVE problem, TYPE 2.\n\nHer ratio is 22/60 = 0.37, well under the 0.5 TO 0.7 threshold. Plenty of protein, and it does not work: TYPE 2.\n\nWhy size is the whole story: von Willebrand factor is a large MULTIMERIC glycoprotein, and HEMOSTATIC ACTIVITY TRACKS MOLECULAR WEIGHT. Put physically, the protein has to STRETCH FROM THE COLLAGEN AT THE INJURY SITE OUT INTO THE FLOWING BLOOD to catch a passing platelet — A SHORT MULTIMER CANNOT SPAN THAT DISTANCE. So a patient who makes only the small forms has plenty of antigen and still bleeds, which is exactly the type 2 pattern. MULTIMER ANALYSIS is the confirmatory next test and would be expected to show LOSS OF HIGH MOLECULAR WEIGHT MULTIMERS.\n\nThe three types:\n• TYPE 1 — quantitative partial deficiency, the MOST COMMON form; activity and antigen fall together; DESMOPRESSIN.\n• TYPE 2 (2A, 2B, 2M, 2N) — qualitative; near-normal antigen with reduced activity; abnormal multimers; concentrate, with desmopressin only sometimes appropriate.\n• TYPE 3 — essentially complete absence, the severe form; both near zero; CONCENTRATE, since there is nothing stored to release.\n\nNote her factor 8 is preserved at 68%, which is usual outside type 3 and type 2N.",
  {"0": "Complete absence is TYPE 3 — the severe form, with both antigen and activity near zero, typically under 3%. Her antigen is 60%, so there is plenty of protein present.",
   "1": "A normal protein in reduced amount is TYPE 1, the most common form, and it is the answer when activity and antigen FALL TOGETHER with a roughly normal ratio. Hers differ by a factor of nearly three.",
   "2": "Absent GPIb is BERNARD-SOULIER SYNDROME — the platelet side of the same handshake, with thrombocytopenia and large platelets on the smear. Her platelet count is normal, and the ristocetin COFACTOR assay uses normal fixed platelets precisely so the platelet side is never the variable.",
   "4": "An isolated secondary factor 8 deficiency is the type 2N pattern, where von Willebrand factor cannot bind and carry factor 8. Her factor 8 is 68% and normal; it is her ristocetin cofactor activity that has collapsed."},
  "She has plenty of the protein, but it does not work — the pieces are too short to stretch from the vessel wall out into the bloodstream and catch a passing platelet. Quantity normal, quality poor.",
  exim="fig_slide_vwf",
  excap="Von Willebrand factor: a large multimer that both grips collagen and carries factor 8. Activity runs with multimer size.")

# ── 15. How desmopressin works (§30) ───────────────────────────────────────
q("A 31-year-old woman with type 1 von Willebrand disease is scheduled for a dental extraction. Her von Willebrand factor antigen is 34% (N=50%–200%) and her ristocetin cofactor activity is 30% (N=50%–200%), with a normal multimer pattern. A desmopressin trial is performed: a baseline level is drawn, the drug is given, and serial levels show her ristocetin cofactor activity rising to 96% at 60 minutes. Desmopressin is planned before the procedure.\n\nWhich of the following is the mechanism of this drug in her disease?",
  ["A. It cross-links fibrin strands to stabilize the formed clot",
   "B. It increases hepatic synthesis of von Willebrand factor",
   "C. It inhibits ADAMTS13 cleavage of circulating multimers",
   "D. It releases stored von Willebrand factor from endothelium",
   "E. It supplies exogenous von Willebrand factor and factor VIII"],
  3,
  "Desmopressin RELEASES STORED VON WILLEBRAND FACTOR FROM ENDOTHELIAL WEIBEL-PALADE BODIES. In type 1 disease THE STORED PROTEIN IS NORMAL — there is simply not enough circulating — so emptying the stores on demand raises the level of a protein that works perfectly well. That is why type 1 is the desmopressin-responsive type, and her rise from 30% to 96% demonstrates it.\n\nIt releases BOTH von Willebrand factor AND FACTOR 8 from endothelial stores, targeting a level above roughly 30% TO 40%.\n\nThe point about where the protein comes from is worth holding: THE LIVER MAKES ALL OF THE COAGULATION FACTORS EXCEPT VON WILLEBRAND FACTOR AND FACTOR 8. Von Willebrand factor comes from ENDOTHELIAL CELLS, stored in Weibel-Palade bodies, and from MEGAKARYOCYTES. That is why the ENDOTHELIUM, NOT THE HEPATOCYTE, is the organ of interest here.\n\nTwo practical points. Desmopressin is available as a NASAL SPRAY as well as parenterally, so a patient can take it themselves before a planned challenge. And RESPONSE IS TESTED BEFORE IT IS RELIED UPON — the trial draws a baseline, gives the drug, then draws serial levels and plots the response curve, so A NON-RESPONDER IS IDENTIFIED BEFORE THE OPERATION, NOT DURING IT. Her trial is exactly that.\n\nWhen desmopressin is not appropriate — type 2B, type 3, or a documented non-responder — the alternatives are plasma-derived factor 8/von Willebrand factor concentrates (Humate P, Alphanate), plasma-derived von Willebrand factor (Wilate) or recombinant von Willebrand factor (Vonvendi). AVOID CRYOPRECIPITATE when virally-inactivated concentrates exist.",
  {"0": "Cross-linking fibrin is what FACTOR 13 does, after the clot has formed. That is a different stage of hemostasis entirely, and its failure produces delayed bleeding with normal screening tests.",
   "1": "The liver does not make von Willebrand factor at all — it is one of the two exceptions to hepatic synthesis, along with factor 8. Desmopressin also acts within minutes, which is far too fast for a synthetic effect.",
   "2": "ADAMTS13 trims multimers down to size, and blocking it would raise the proportion of large multimers. That is not how desmopressin works, and unopposed ultra-large multimers cause thrombotic thrombocytopenic purpura rather than treating bleeding.",
   "4": "Supplying exogenous protein describes CONCENTRATE therapy, which is what type 3 patients need because they have nothing stored to release. Desmopressin supplies nothing; it mobilises what the patient already has."},
  "Her body makes normal von Willebrand protein, just not enough of it circulating. The drug squeezes the stores in her blood vessel lining and dumps the reserve into the bloodstream — so her level triples before the dentist starts.",
  exim="fig_slide_primary_hemostasis",
  excap="Von Willebrand factor is made and stored by endothelium, not the liver — which is why a drug that empties endothelial stores works.")

# ── 16. The type where desmopressin is wrong (§30) ──────────────────────────
q("A 29-year-old man with a lifelong history of gum bleeding and easy bruising is being prepared for an elective hernia repair. Multimer analysis shows loss of the high molecular weight forms, and ristocetin-induced platelet aggregation is INCREASED at low ristocetin concentrations. His father and sister have similar findings.\n\nLaboratory studies show:\nPlatelet count 82,000/mm3 (N=150,000–400,000/mm3)\nVon Willebrand factor antigen 54% (N=50%–200%)\nRistocetin cofactor activity 20% (N=50%–200%)\nFactor VIII activity 62% (N=50%–150%)\n\nWhich of the following is the most appropriate preoperative therapy?",
  ["A. Administer desmopressin before the procedure",
   "B. Give plasma-derived von Willebrand factor concentrate",
   "C. Transfuse cryoprecipitate on the morning of the operation",
   "D. Transfuse platelets alone to correct the count",
   "E. Use recombinant activated factor VII at induction"],
  1,
  "This is TYPE 2B von Willebrand disease, and it is the subtype in which DESMOPRESSIN CAN MAKE THINGS WORSE.\n\nThe abnormal von Willebrand factor in type 2B has INCREASED affinity for platelet GPIb. It binds platelets spontaneously in the circulation, and those complexes are cleared — which produces the THROMBOCYTOPENIA seen here at 82,000/mm3 and the loss of high molecular weight multimers, since the large forms are consumed preferentially. The diagnostic signature is in the stem: RISTOCETIN-INDUCED PLATELET AGGREGATION IS INCREASED AT LOW RISTOCETIN CONCENTRATIONS, which is the opposite of every other type.\n\nDesmopressin releases more of this abnormal protein from endothelial stores, DRIVING MORE ABNORMAL VON WILLEBRAND FACTOR ONTO PLATELETS AND DEEPENING THE THROMBOCYTOPENIA. The correct therapy is a CONCENTRATE, which supplies normal protein without mobilising the abnormal.\n\nThe general treatment map:\n• TYPE 1 — DESMOPRESSIN, since the stored protein is normal.\n• TYPES 2A AND 2M — desmopressin MAY work if there is residual activity, otherwise plasma-derived factor 8/von Willebrand factor concentrates (Humate P, Alphanate).\n• TYPE 2B — CONCENTRATE, NOT DESMOPRESSIN.\n• TYPE 3 — CONCENTRATE; there is nothing stored to release.\n\nAnd the standing instruction across all of them: AVOID EXPOSING THESE PATIENTS TO CRYOPRECIPITATE when virally-inactivated concentrates exist.\n\nHis activity-to-antigen ratio of 20/54 = 0.37 already places him in the qualitative group before the subtype is settled.",
  {"0": "Desmopressin is the first-line treatment for type 1 disease and the reflex answer for von Willebrand disease generally, which is exactly why this subtype is examined. Here it releases more abnormal protein, worsens the thrombocytopenia, and can precipitate bleeding rather than prevent it.",
   "2": "Cryoprecipitate does contain von Willebrand factor and was historically used. It is not virally inactivated, and the explicit instruction is to avoid exposing these patients to it when concentrates are available.",
   "3": "Platelets are being consumed by the abnormal protein, so transfused platelets will be cleared the same way. The platelet count is a consequence of the disease rather than the defect to correct, and it does not address the adhesion failure.",
   "4": "Recombinant activated factor 7 is a bypassing agent used for hemophilia with inhibitors and for some rare factor deficiencies. It does not address a defect of platelet adhesion, and it carries thrombotic risk."},
  "His abnormal protein sticks to platelets too eagerly, clearing them from the blood — which is why his platelet count is low. A drug that releases more of that protein would make things worse; he needs normal protein supplied instead.",
  exim="fig_slide_multimers",
  excap="Multimer analysis: loss of the high molecular weight forms, which is the type 2 signature.")

# ── 17. Bernard-Soulier (§30) ──────────────────────────────────────────────
q("A 19-year-old woman is evaluated for lifelong nosebleeds, heavy menstrual bleeding, and prolonged bleeding after a dental extraction. Her parents are first cousins. Her prothrombin time and activated partial thromboplastin time are normal. Von Willebrand factor antigen is 92% and ristocetin cofactor activity is 88% (N=50%–200% for both). Platelet aggregation studies show a markedly decreased response to ristocetin, with normal responses to arachidonic acid, collagen, and adenosine diphosphate, and normal ATP release.\n\nLaboratory studies show:\nHemoglobin 10.8 g/dL (N=12.0–16.0 g/dL)\nHematocrit 33% (N=36%–46%)\nPlatelet count 74,000/mm3 (N=150,000–400,000/mm3)\nMean platelet volume 14.2 fL (N=7.5–11.5 fL)\n\nWhich of the following is the most likely diagnosis?",
  ["A. Bernard-Soulier syndrome",
   "B. Glanzmann thrombasthenia",
   "C. Immune thrombocytopenia",
   "D. Storage pool disease of dense granules",
   "E. von Willebrand disease, type 2A"],
  0,
  "Hold the chain: COLLAGEN → VON WILLEBRAND FACTOR → GPIb → PLATELET. ADHESION FAILS IF YOU REMOVE EITHER PARTNER IN THE HANDSHAKE.\n\n• VON WILLEBRAND DISEASE — the LIGAND is missing. The plasma side.\n• BERNARD-SOULIER SYNDROME — GPIb/IX/V, the RECEPTOR, is missing. The platelet side.\n\nBoth produce decreased adhesion and both bleed mucocutaneously. Her von Willebrand antigen and activity are both normal, so the plasma side is intact — the defect is on the platelet.\n\nThe way to read the aggregometry table is to LOOK AT THE RISTOCETIN COLUMN FIRST. Ristocetin tests the GPIb–von Willebrand factor axis specifically; the other agonists test activation and aggregation through other receptors. RISTOCETIN LOW WITH EVERYTHING ELSE NORMAL means the GPIb receptor is the problem — Bernard-Soulier. RISTOCETIN NORMAL WITH THE OTHERS LOW means the receptor is fine and aggregation is broken — classically Glanzmann thrombasthenia.\n\nThe smear gives a free extra clue, and it is in her panel: THROMBOCYTOPENIA WITH LARGE PLATELETS — a platelet count of 74,000/mm3 with a mean platelet volume of 14.2 fL.\n\nThe memory hook: B FOR BERNARD, B FOR BIND — cannot bind the vessel wall, GPIb is missing, so ristocetin fails. G FOR GLANZMANN, G FOR GLUE TOGETHER — the fibrinogen bridge is missing, so everything EXCEPT ristocetin fails.\n\nConfirm with FLOW CYTOMETRY FOR GPIb EXPRESSION. Treatment of significant bleeding is platelet transfusion. Note the autosomal recessive inheritance, consistent with her consanguineous parents.",
  {"1": "Glanzmann thrombasthenia is the mirror image: GPIIb/IIIa cannot bind fibrinogen, so aggregation to arachidonic acid, collagen and ADP fails while RISTOCETIN STAYS NORMAL. The platelet count and size are also normal in Glanzmann.",
   "2": "Immune thrombocytopenia causes isolated thrombocytopenia, sometimes with slightly large platelets, and would explain mucocutaneous bleeding. It does not produce a selective ristocetin defect with normal responses to every other agonist, and it is acquired rather than lifelong.",
   "3": "Dense granule storage pool disease shows DECREASED ATP RELEASE — that is its defining row — with variably decreased responses to the other agonists and NORMAL ristocetin. Her ATP release is normal.",
   "4": "Type 2A von Willebrand disease also gives a decreased ristocetin response, which makes it the important alternative. It is excluded by her NORMAL von Willebrand antigen and activity, and by the large platelets: the ristocetin COFACTOR assay uses normal fixed platelets specifically so the platelet side is never the variable."},
  "Platelets stick to an injured vessel by grabbing a protein bridge with a specific hook. Her protein bridge is fine — the hook on her platelets is missing. Her platelets are also unusually large and few, which is the clue that comes free with this disease.",
  exim="fig_slide_agonist_table",
  excap="The agonist table. Read the ristocetin column first: low with everything else normal points at the GPIb receptor.")

# ── 18. Glanzmann or aspirin (§30) ─────────────────────────────────────────
q("A 44-year-old man is evaluated for easy bruising and prolonged bleeding after a recent dental procedure. His prothrombin time, activated partial thromboplastin time, platelet count, and von Willebrand studies are all normal. Platelet aggregation studies show decreased responses to arachidonic acid, collagen, and adenosine diphosphate, with a normal ristocetin response and normal ATP release. He reports no family history of bleeding and says he takes 'nothing regular' for his knee pain.\n\nWhich of the following is the most appropriate next step?",
  ["A. Ask about aspirin use and repeat in 7 to 10 days",
   "B. Measure von Willebrand factor multimer distribution",
   "C. Order electron microscopy of platelet dense granules",
   "D. Send flow cytometry for platelet GPIb expression",
   "E. Transfuse platelets and observe the clinical response"],
  0,
  "This aggregometry pattern has two explanations: GLANZMANN THROMBASTHENIA (GPIIb/IIIa deficiency) or an ASPIRIN EFFECT — the table notes explicitly that ASPIRIN PRODUCES IDENTICAL FINDINGS in the arachidonic acid/thromboxane row, and the standing instruction is ALWAYS ASK ABOUT ASPIRIN BEFORE DIAGNOSING A PLATELET DEFECT.\n\nNormal ristocetin rules out Bernard-Soulier and von Willebrand disease, because the GPIb axis is intact.\n\nSEPARATE THEM WITH THE HISTORY FIRST: recent aspirin or non-steroidal anti-inflammatory exposure — and note that his answer, 'nothing regular' for knee pain, is the kind of reply that conceals intermittent over-the-counter use. Patients do not consider these to be medicines.\n\nThen by pattern: a pure arachidonic acid/thromboxane defect tends to hit arachidonic acid hardest with only variable effects elsewhere, whereas GLANZMANN ABOLISHES AGGREGATION TO ALL of arachidonic acid, collagen and ADP.\n\nIf aspirin is suspected, STOP IT AND REPEAT AFTER 7 TO 10 DAYS — aspirin is an IRREVERSIBLE inhibitor of platelet cyclooxygenase-1, and platelets cannot synthesise new enzyme, so RECOVERY REQUIRES AN ENTIRELY NEW PLATELET POPULATION.\n\nDefinitive testing for Glanzmann is FLOW CYTOMETRY FOR GPIIb/IIIa (CD41/CD61) EXPRESSION. Also worth knowing why Glanzmann bleeds as much as it does: roughly TWO THIRDS OF THE MECHANICAL STRENGTH OF A CLOT COMES FROM THE PLATELETS ENMESHED IN IT. The patient does form a fibrin clot — it is just mechanically weak, and it fails. Adhesion is intact; incorporation is not.\n\nAlso against a congenital diagnosis: no family history, and symptoms beginning in middle age.",
  {"1": "Multimer analysis subtypes von Willebrand disease, and his von Willebrand studies are already normal. It also would not explain a defect confined to aggregation with an intact GPIb axis.",
   "2": "Electron microscopy is added when a GRANULE STORAGE POOL defect is suspected — and the marker of that is DECREASED ATP RELEASE, which he does not have. His release is normal.",
   "3": "Flow cytometry for GPIb diagnoses Bernard-Soulier, which is excluded by his normal ristocetin response and normal platelet count and size. The relevant receptor to measure here would be GPIIb/IIIa, and only after the drug question is settled.",
   "4": "Transfusing platelets is a treatment rather than a diagnostic step, and it exposes him to alloimmunization. Nothing here is urgent enough to justify it before a free and reversible explanation has been excluded."},
  "His platelet test looks like a rare inherited disorder — but ordinary aspirin produces exactly the same picture, and he did not think painkillers counted as medication. Stop them and retest a week later, after his body has made fresh platelets.",
  exim="fig_slide_agonist_table",
  excap="Aspirin reproduces the arachidonic acid pattern exactly, which is why drug history comes before any diagnosis of a platelet function defect.")

# ── 19. The grey zone and blood group O (§30) ──────────────────────────────
q("A 24-year-old woman is referred after a screening panel done because her cousin has von Willebrand disease. She reports occasional bruising on her shins, no epistaxis, and normal menstrual periods. She had a tonsillectomy at 12 and an appendectomy at 20, both without excessive bleeding, and two dental extractions without difficulty. Her blood group is O. Her prothrombin time, activated partial thromboplastin time, and platelet count are normal.\n\nLaboratory studies show:\nVon Willebrand factor antigen 44% (N=50%–200%)\nRistocetin cofactor activity 42% (N=50%–200%)\nFactor VIII activity 78% (N=50%–150%)\n\nWhich of the following is the most accurate interpretation?",
  ["A. Blood group O is associated with lower baseline levels",
   "B. The level confirms type 1 von Willebrand disease",
   "C. The level establishes type 2 von Willebrand disease",
   "D. The pattern indicates acquired von Willebrand syndrome",
   "E. The result is an artefact of an underfilled citrate tube"],
  0,
  "Two grey zones are flagged explicitly, and both apply here.\n\nFirst: BLOOD GROUP O INDIVIDUALS HAVE LOWER VON WILLEBRAND FACTOR LEVELS AT BASELINE. A group O patient can test in the low range and be entirely normal. INTERPRET THE LEVEL AGAINST THE PATIENT'S BLOOD TYPE, OR YOU WILL OVER-DIAGNOSE.\n\nSecond: 'LOW VON WILLEBRAND FACTOR' OF 30% TO 50% sits between normal and type 1. It MAY be von Willebrand disease IF THERE IS A BLEEDING HISTORY — THE CLINICAL HISTORY, NOT THE NUMBER ALONE, DECIDES.\n\nHer history is the strongest evidence available and it is negative: a tonsillectomy, an appendectomy and two dental extractions, all uneventful, with normal periods and no epistaxis. A NEGATIVE BLEEDING HISTORY THROUGH PRIOR SURGERY IS THE STRONGEST SINGLE PIECE OF CONTRARY EVIDENCE YOU CAN GET.\n\nNote that her activity and antigen are SIMILAR — 42 and 44, a ratio near 1 — so if this were disease it would be quantitative rather than qualitative. Type 1 is characteristically DECREASED, BELOW 30%.\n\nA related point about reference ranges generally: they are built by running healthy volunteers and taking the 95% CONFIDENCE INTERVAL, so BY CONSTRUCTION ABOUT 5% OF PERFECTLY HEALTHY PEOPLE FALL OUTSIDE. A value a little past the line may simply be a normal person, not a diagnosis.\n\nThe practical outcome: no diagnosis, no restriction, and a plan to repeat testing and reassess if she ever has a hemostatic challenge that goes badly.",
  {"1": "Type 1 disease is a quantitative deficiency characteristically below 30%, and — crucially — it requires a bleeding phenotype. Labelling her would commit her to a lifelong diagnosis, possible treatment before procedures, and insurance consequences on the basis of a number alone.",
   "2": "Type 2 is a QUALITATIVE defect, identified by an activity-to-antigen ratio below roughly 0.5 to 0.7. Hers is 42/44, which is essentially 1 — the protein present is working normally.",
   "3": "Acquired von Willebrand syndrome occurs with aortic stenosis, myeloproliferative neoplasms, lymphoproliferative disorders and ventricular assist devices, and presents as NEW bleeding in an older patient. She is 24, asymptomatic, and has none of those conditions.",
   "4": "An underfilled citrate tube prolongs CLOTTING TIMES by upsetting the 9:1 ratio; it is not a recognised cause of a spuriously low von Willebrand antigen. Her clotting times are normal, which argues against any tube problem."},
  "Her level is a little below the printed range, but people with blood type O naturally run lower — and she has sailed through a tonsillectomy, an appendectomy and two dental extractions. The history matters more than the number.")

# ── 20. Reading the pedigree (§30) ─────────────────────────────────────────
q("A hematologist takes a family history from a 7-year-old boy being evaluated for recurrent deep muscle hematomas. His mother has never had abnormal bleeding. Her brother had severe bleeding into his joints from early childhood and uses regular factor infusions. Her maternal grandfather's brother was described as a 'bleeder' who died young after a minor injury. No female relative in any generation has had abnormal bleeding, and the boy's father's family has no bleeding history.\n\nWhich of the following inheritance patterns does this pedigree suggest?",
  ["A. An acquired inhibitor with no inheritance pattern",
   "B. Autosomal dominant inheritance, as in von Willebrand disease",
   "C. Autosomal recessive inheritance, as in Glanzmann thrombasthenia",
   "D. Mitochondrial inheritance through the maternal line",
   "E. X-linked inheritance, as in hemophilia A or B"],
  4,
  "The pedigree is read for a pattern, and the pattern here is definitive: AFFECTED MALES ACROSS GENERATIONS THROUGH UNAFFECTED MOTHERS → X-LINKED, meaning hemophilia A or B. His bleeding pattern — deep muscle hematomas — fits secondary hemostasis and confirms the direction.\n\nThe three patterns worth recognising on sight:\n• AFFECTED MALES ACROSS GENERATIONS THROUGH UNAFFECTED MOTHERS → X-LINKED (hemophilia A or B).\n• AFFECTED MEN AND WOMEN IN EVERY GENERATION → AUTOSOMAL DOMINANT (most von Willebrand disease).\n• BOTH SEXES WITH CONSANGUINITY, OR AN ISOLATED CASE → AUTOSOMAL RECESSIVE (Bernard-Soulier, Glanzmann, hemophilia C).\n\nThe other historical features that suggest a bleeding disorder is HEREDITARY rather than acquired:\n• LIFELONG, NOT NEW. Bleeding dating from childhood — circumcision, tooth eruption, a first dental extraction — points at a congenital defect. A diathesis that APPEARS SUDDENLY IN A PATIENT'S 50s OR 70s WITH NO PRIOR HISTORY IS ACQUIRED UNTIL PROVEN OTHERWISE.\n• BLEEDING AT FIRST HEMOSTATIC CHALLENGE. Mild hemophilia and type 1 von Willebrand disease often surface at a first operation, a first delivery, or the start of menstruation — not before.\n• MENORRHAGIA IS THE MOST COMMONLY MISSED PRESENTATION, normalised for years before anyone sends a von Willebrand panel.\n• A MIXING STUDY THAT CORRECTS supports a deficiency, usually inherited; ONE THAT FAILS TO CORRECT supports an inhibitor, usually acquired.\n\nThe thrombotic counterpart of this list — young age, unusual site, recurrence, family history — belongs to the thrombophilia workup.",
  {"0": "An acquired inhibitor produces a new diathesis in an older patient with no family history, and a mixing study that fails to correct. Three generations of affected male relatives is the opposite of that picture.",
   "1": "Autosomal dominant inheritance shows affected men AND women in every generation, and is the pattern of most von Willebrand disease. No female relative here is affected, and von Willebrand disease bleeds mucocutaneously rather than into muscle.",
   "2": "Autosomal recessive disease appears in both sexes, often with consanguinity or as an isolated case — Bernard-Soulier, Glanzmann and hemophilia C. This pedigree has affected males only, transmitted through unaffected women.",
   "3": "Mitochondrial inheritance passes from mothers to ALL of their children, sons and daughters alike, and no mitochondrial disorder causes hemophilia. The unaffected daughters are what exclude it."},
  "Only the men in this family bleed, and they inherit it through mothers who are perfectly well. That specific pattern — carried by women, expressed in men — points to a gene on the X chromosome.")

# ══════════════ §31 · ACQUIRED BLEEDING ══════════════

# ── 21. Disseminated intravascular coagulation (§31) ───────────────────────
q("A 64-year-old woman in the intensive care unit with Escherichia coli urosepsis has developed oozing from every venipuncture site and around her central line over 12 hours, along with a dusky discoloration of two fingertips. Her temperature is 38.9°C (102.0°F), pulse is 124/min, and blood pressure is 88/52 mm Hg on norepinephrine.\n\nLaboratory studies show:\nHemoglobin 8.8 g/dL (N=12.0–16.0 g/dL)\nHematocrit 27% (N=36%–46%)\nPlatelet count 38,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 22 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 58 seconds (N=25–35 seconds)\nFibrinogen 140 mg/dL (N=200–400 mg/dL)\nD-dimer 14.2 µg/mL (N=<0.5 µg/mL)\n\nHer fibrinogen was 480 mg/dL 2 days ago, and the smear shows schistocytes. Which of the following is the most important element of management?",
  ["A. Administer cryoprecipitate to raise the fibrinogen",
   "B. Begin a therapeutic heparin infusion",
   "C. Transfuse plasma to correct the prolonged times",
   "D. Transfuse platelets to above 50,000/mm3",
   "E. Treat the underlying sepsis aggressively"],
  4,
  "DIC IS ALWAYS SECONDARY — to sepsis, malignancy, obstetric catastrophe, major trauma — and the management principle is TREAT THE UNDERLYING CAUSE. Product support is given FOR BLEEDING OR BEFORE A PROCEDURE, NOT TO CORRECT A NUMBER ON A PANEL.\n\nAll four laboratory legs are present:\n• PLATELET COUNT FALLS — consumed in microthrombi.\n• PT AND aPTT BOTH PROLONGED — factors consumed, and a common-pathway and fibrinogen deficit hits both tests.\n• FIBRINOGEN FALLS — and note that 140 mg/dL is near many reference ranges. A FALLING TREND IS MORE USEFUL THAN A SINGLE VALUE, because fibrinogen is an ACUTE-PHASE REACTANT and should be HIGH in sepsis. Hers has dropped from 480 to 140.\n• D-DIMER RISES, OFTEN MARKEDLY — active fibrin formation AND breakdown.\nPlus SCHISTOCYTES on the smear, from red cells sheared on intravascular fibrin strands.\n\nConceptually, DIC is the failure of one of the four specifications of a working coagulation system: RESPOND AT THE SITE OF INJURY QUICKLY AND IN A LOCALISED FASHION. In DIC coagulation is triggered SYSTEMICALLY. Widespread microvascular thrombosis consumes platelets and factors and simultaneously drives fibrinolysis, so THE PATIENT CLOTS AND BLEEDS AT THE SAME TIME — her oozing line sites and her dusky fingertips in the same body.\n\nThe products still have a role — she is bleeding, so cryoprecipitate or fibrinogen concentrate and platelets are reasonable alongside. What they cannot do is stop the process, because the trigger is her infection.",
  {"0": "Cryoprecipitate is the right product for a fibrinogen this low in a bleeding patient and should be given alongside. It replaces what is being consumed without stopping the consumption, so the effect is transient while the sepsis continues.",
   "1": "Therapeutic heparin is used in the rare thrombosis-predominant presentations, such as purpura fulminans or large-vessel thrombosis. In a patient already oozing from every site with a platelet count of 38,000/mm3 it is hazardous, and it does not address the trigger.",
   "2": "Plasma replaces consumed factors and is appropriate for active bleeding, which she has. Transfusing TO CORRECT THE NUMBERS is the specific error the management principle warns against, since the numbers will fall again within hours.",
   "3": "A platelet transfusion is reasonable in a bleeding patient at 38,000/mm3 and will probably be given. Chasing a threshold in the absence of bleeding or a planned procedure consumes product and achieves nothing while consumption continues."},
  "Her infection has switched on clotting throughout her whole body, using up the platelets and proteins until there are none left to plug the holes — so she clots and bleeds at once. Products buy time; only treating the infection stops it.",
  exim="fig_slide_dic",
  excap="Systemic activation, consumption of factors and platelets, and secondary fibrinolysis — clotting and bleeding at the same time.")

# ── 22. Vitamin K deficiency versus liver disease (§31) ────────────────────
q("Two patients are seen on the same day, each with a prolonged prothrombin time and mild prolongation of the activated partial thromboplastin time. The first is a 58-year-old man who has had 4 weeks of poor oral intake and broad-spectrum antibiotics after abdominal surgery. The second is a 61-year-old woman with cirrhosis from hepatitis C, with a serum albumin of 2.6 g/dL (N=3.5–5.5 g/dL), a total bilirubin of 3.4 mg/dL (N=0.2–1.2 mg/dL), and ascites. Both have factors II, VII, IX, and X activity well below normal.\n\nWhich of the following assays best distinguishes the two diagnoses?",
  ["A. Factor IX activity",
   "B. Factor V activity",
   "C. Factor VII activity",
   "D. Factor VIII activity",
   "E. Factor XIII activity"],
  1,
  "The clean discriminator is a factor most people forget to order: FACTOR 5.\n\n• VITAMIN K DEFICIENCY (or warfarin) — factors 2, 7, 9 and 10 LOW, FACTOR 5 NORMAL, because FACTOR 5 IS NOT VITAMIN K DEPENDENT and is therefore untouched.\n• LIVER DISEASE — factors 2, 7, 9 and 10 low AND FACTOR 5 ALSO LOW, because THE LIVER MAKES FACTOR 5 TOO, so synthetic failure takes it down as well.\n\nLOW 2, 7, 9, 10 WITH A NORMAL FACTOR 5 = VITAMIN K. EVERYTHING LOW INCLUDING FACTOR 5 = LIVER.\n\nVitamin K is required for factors 2, 7, 9 and 10 plus the anticoagulants PROTEIN C AND PROTEIN S, and deficiency follows MALNUTRITION, MALABSORPTION, OR PROLONGED ANTIBIOTICS — all three worth asking about, as in the first patient.\n\nA SUPPORTING CHECK RUNS THE OTHER WAY, and it is worth carrying because it separates liver disease from DIC: FACTOR 8 IS NORMAL OR HIGH IN LIVER DISEASE, because hepatocytes do not make it — von Willebrand factor and factor 8 are the two exceptions to hepatic synthesis — BUT LOW IN DIC, where it is consumed with everything else. When liver disease and DIC are hard to separate, that is the discriminating assay.\n\nThe practical difference this makes: the first patient will correct with vitamin K, confirming the diagnosis by response; the second will not, because her problem is the factory rather than the raw material.",
  {"0": "Factor 9 is vitamin K dependent AND made by the liver, so it is low in both patients. The stem already states that it is low in both, which is the cover-the-options clue.",
   "2": "Factor 7 is the most sensitive factor on the PT and the first to fall in vitamin K deficiency because of its short half-life. It is also hepatically synthesised and vitamin K dependent, so it is low in both conditions and cannot separate them.",
   "3": "Factor 8 is a genuinely useful discriminator — but between LIVER DISEASE and DIC, not between liver disease and vitamin K deficiency. It is normal or high in liver disease and normal in vitamin K deficiency, so it does not separate these two.",
   "4": "Factor 13 cross-links formed fibrin and is not measured by either clotting time. It has no role in separating these two synthetic or nutritional deficits."},
  "Both conditions knock out the same four clotting proteins. One extra protein is made by the liver but does not need vitamin K — so if that one is also low, the liver is the problem; if it is normal, vitamin K is.")

# ── 23. The INR in cirrhosis (§31) ─────────────────────────────────────────
q("A 59-year-old man with cirrhosis from alcohol-associated liver disease is admitted with tense ascites and is scheduled for a large-volume paracentesis. He has had no bleeding, no melena, and no bruising, and he is hemodynamically stable. His temperature is 36.9°C (98.4°F), pulse is 82/min, and blood pressure is 112/68 mm Hg.\n\nLaboratory studies show:\nHemoglobin 11.2 g/dL (N=13.0–16.0 g/dL)\nHematocrit 34% (N=37%–49%)\nPlatelet count 74,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 23 seconds (N=11–15 seconds)\nInternational normalized ratio 2.1 (N=0.9–1.1)\nFibrinogen 190 mg/dL (N=200–400 mg/dL)\nTotal bilirubin 3.8 mg/dL (N=0.2–1.2 mg/dL)\n\nThe proceduralist requests fresh frozen plasma to correct the international normalized ratio before the tap. Which of the following is the most appropriate response?",
  ["A. Give four-factor prothrombin complex concentrate first",
   "B. Give fresh frozen plasma to an international ratio below 1.5",
   "C. Give intravenous vitamin K and delay the tap by 24 hours",
   "D. Proceed without plasma, transfusing only for bleeding",
   "E. Transfuse platelets to above 100,000/mm3 beforehand"],
  3,
  "A PROLONGED INR IN LIVER DISEASE DOES NOT RELIABLY PREDICT BLEEDING, and by itself is not a reason to transfuse plasma.\n\nThe reason is that THE LIVER MAKES BOTH SIDES OF THE SYSTEM — the procoagulant factors AND the natural anticoagulants PROTEIN C, PROTEIN S AND ANTITHROMBIN. Losing both at once produces a REBALANCED BUT FRAGILE hemostasis, which is why patients with end-stage liver disease CAN BLEED AND CLOT. The INR measures ONLY THE PROCOAGULANT HALF, so it reports a coagulopathy the patient may not clinically have.\n\nThat is the OPPOSITE of warfarin, where the anticoagulants are also suppressed but the INR is a validated, dose-calibrated measure — which is why the same number means something different in the two settings.\n\nManage individually: transfuse for BLEEDING or for a genuinely high-risk procedure, not to normalise a number. A large-volume paracentesis is among the lowest-risk procedures in this population, with bleeding complications in well under 1% even at INRs in this range, and plasma carries volume load, transfusion reactions and the risk of worsening portal pressure.\n\nThe honest caveat, though: REBALANCING DOES NOT PROTECT THESE PATIENTS THROUGH MAJOR SURGERY. They bleed a great deal intra-operatively — it is routine for the blood bank to set aside 20 TO 30 UNITS FOR A LIVER TRANSPLANT. So the argument here is procedure-specific, not a general claim that cirrhotic patients do not bleed.",
  {"0": "Prothrombin complex concentrate delivers the same factors in a small volume and is the right tool for urgent warfarin reversal or major bleeding. Using it to normalise a number in a stable patient before a low-risk tap adds thrombotic risk without benefit.",
   "1": "This is the request being made, and it is the standard practice the evidence argues against. Achieving an INR below 1.5 with plasma usually requires large volumes, and in cirrhosis the number does not track bleeding risk.",
   "2": "Vitamin K is reasonable to give if deficiency is suspected — malnutrition and cholestasis both contribute in alcohol-associated liver disease — but it does not correct synthetic failure, and delaying a therapeutic tap for a tense abdomen has its own cost.",
   "4": "A platelet threshold of 100,000/mm3 is far above what a paracentesis requires. Thrombocytopenia in cirrhosis is largely from splenic sequestration and reduced thrombopoietin, and transfused platelets are sequestered too."},
  "His clotting test looks alarming, but his liver has stopped making both the proteins that cause clotting and the ones that prevent it. The test only measures one side, so it exaggerates. For a simple abdominal tap, no plasma is needed.")

# ── 24. Hemorrhagic disease of the newborn (§31) ───────────────────────────
q("A 4-day-old boy born at home at 39 weeks' gestation is brought to the emergency department because of bleeding from the umbilical stump and bruising at the site where a heel-stick was performed at a clinic visit yesterday. He is exclusively breastfed. The parents decline routine newborn interventions. His temperature is 36.9°C (98.4°F), pulse is 148/min, and respirations are 44/min. Physical examination shows oozing from the cord stump and scattered bruises; there is no hepatosplenomegaly and he is alert and feeding.\n\nLaboratory studies show:\nHemoglobin 14.2 g/dL (N=14.0–20.0 g/dL)\nPlatelet count 296,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 42 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 74 seconds (N=25–35 seconds)\nFibrinogen 240 mg/dL (N=200–400 mg/dL)\n\nWhich of the following best explains these findings?",
  ["A. Deficiency of vitamin K-dependent factors, with the PT affected first",
   "B. Disseminated intravascular coagulation from occult neonatal sepsis",
   "C. Hemophilia A presenting in the neonatal period",
   "D. Neonatal alloimmune thrombocytopenia from maternal antibody",
   "E. Physiologic prolongation of infant clotting times, needing no therapy"],
  0,
  "VITAMIN K INJECTION IS PART OF STANDARD NEONATAL CARE, and this baby did not get it.\n\nNewborns are RELATIVELY DEFICIENT for three reasons: LITTLE PLACENTAL TRANSFER, LOW STORES, AND A STERILE GUT with no flora to synthesise it. Breast milk is also low in vitamin K, which compounds it in an exclusively breastfed infant. Without the injection they are at risk of HEMORRHAGIC DISEASE OF THE NEWBORN, INCLUDING INTRACRANIAL HEMORRHAGE.\n\nThe practical history point is exactly the one this stem turns on: BABIES BORN OUTSIDE A HOSPITAL MAY MISS THE ROUTINE INJECTION, SO ASK ABOUT THE BIRTH SETTING.\n\nVitamin K is required for FACTORS 2, 7, 9 AND 10 plus proteins C and S. Because FACTOR 7 HAS THE SHORTEST HALF-LIFE, THE PT PROLONGS FIRST — and with a profound deficiency, as here, the aPTT follows as factors 2, 9 and 10 fall too. His disproportionately long PT of 42 seconds against an aPTT of 74 seconds fits that sequence, with a NORMAL platelet count and NORMAL fibrinogen, which is what separates this from consumption.\n\nTreatment is parenteral vitamin K immediately, with plasma or prothrombin complex concentrate if bleeding is severe or intracranial hemorrhage is suspected — and the response to vitamin K, with correction over hours, confirms the diagnosis.\n\nThis is the same mechanism warfarin exploits, arriving by a nutritional route.",
  {"1": "Disseminated intravascular coagulation in a neonate would consume platelets and fibrinogen and raise the D-dimer. His platelet count is 296,000/mm3 and his fibrinogen is 240 mg/dL, and he is alert, feeding and afebrile rather than septic.",
   "2": "Hemophilia A can present in the neonatal period, classically with bleeding after circumcision or heel-sticks, so it belongs on this differential. It prolongs the aPTT ALONE, leaving the PT normal — his PT is 42 seconds.",
   "3": "Neonatal alloimmune thrombocytopenia causes severe THROMBOCYTOPENIA with petechiae and a risk of intracranial hemorrhage, from maternal antibody against paternal platelet antigens. His platelet count is normal.",
   "4": "Newborns do have modestly longer clotting times than adults, and healthy term infants sit above the adult range. Values of this magnitude with active bleeding are not physiologic, and treating them as such risks a fatal intracranial bleed."},
  "Babies are born with very little vitamin K and cannot make it yet, which is why every newborn gets an injection of it. This baby was born at home and did not receive one, so the clotting proteins that need vitamin K have run out.")

# ── 25. Heyde syndrome (§31) ───────────────────────────────────────────────
q("A 76-year-old woman with known severe aortic stenosis is admitted with a third episode of gastrointestinal bleeding in 8 months. Colonoscopy on each occasion has shown angiodysplastic lesions in the ascending colon. She takes no antiplatelet or anticoagulant drugs and has no prior bleeding history. Cardiac examination shows a harsh late-peaking systolic murmur at the right upper sternal border. Her prothrombin time, activated partial thromboplastin time, and platelet count are normal.\n\nLaboratory studies show:\nHemoglobin 8.6 g/dL (N=12.0–16.0 g/dL)\nHematocrit 27% (N=36%–46%)\nVon Willebrand factor antigen 96% (N=50%–200%)\nRistocetin cofactor activity 38% (N=50%–200%)\n\nMultimer analysis shows loss of the high molecular weight forms. Which of the following best explains her bleeding?",
  ["A. Autoantibody directed against von Willebrand factor",
   "B. Hepatic failure reducing synthesis of the protein",
   "C. Inherited type 2A disease presenting in late life",
   "D. Shear across the valve exposing multimers to ADAMTS13",
   "E. Splenic sequestration of high molecular weight multimers"],
  3,
  "This is HEYDE SYNDROME — acquired von Willebrand disease with aortic stenosis — and the mechanism is worth knowing because it explains a clinical pairing that otherwise looks like coincidence.\n\nSHEAR STRESS ACROSS A STENOTIC VALVE UNFOLDS VON WILLEBRAND FACTOR AND EXPOSES IT TO ADAMTS13, which strips out the HIGH MOLECULAR WEIGHT MULTIMERS. The result is a TYPE-2-LIKE PICTURE — ANTIGEN PRESENT, ACTIVITY REDUCED, ABNORMAL MULTIMERS — in a patient with a murmur and gastrointestinal bleeding. Her ratio is 38/96 = 0.40, squarely in the qualitative range, with a normal antigen.\n\nThe reason the bleeding is gastrointestinal and from angiodysplasia specifically is that high molecular weight multimers matter most where SHEAR IS HIGHEST, and the mucosal vessels of angiodysplastic lesions are precisely such a bed.\n\nThe unifying observation across three sections: ADAMTS13 trims multimers down to size. Its FAILURE causes thrombotic thrombocytopenic purpura, where ultra-large multimers snag platelets. Its EXCESSIVE ACTION here, driven mechanically, causes bleeding. SAME ENZYME, SAME MOLECULE, OPPOSITE DISEASES — one inherited, one mechanical.\n\nThe treatment is the one that surprises people: VALVE REPLACEMENT CORRECTS THE COAGULOPATHY, because removing the shear removes the mechanism. Desmopressin or concentrate can cover acute bleeding in the meantime.\n\nThe general lesson: ACQUIRED von Willebrand syndrome should be considered whenever a type-2 pattern appears in an older patient with no lifelong history — also with myeloproliferative neoplasms, lymphoproliferative disorders, hypothyroidism and ventricular assist devices.",
  {"0": "An autoantibody against von Willebrand factor does cause acquired von Willebrand syndrome, typically with lymphoproliferative disease or a paraprotein. It usually lowers the ANTIGEN by clearing the protein, and it does not explain the specific association with a stenotic valve.",
   "1": "The liver does not make von Willebrand factor — endothelial cells and megakaryocytes do. It is one of the two exceptions to hepatic synthesis, along with factor 8, and nothing here suggests liver disease.",
   "2": "Inherited type 2A produces the same laboratory pattern, which is why it is the right differential to consider. It is congenital and would have caused bleeding decades earlier; she has no prior bleeding history, and her severe aortic stenosis supplies the mechanism.",
   "4": "The spleen clears antibody-coated and damaged cells, not selected multimers of a plasma protein. Nothing in her presentation points to splenomegaly or hypersplenism."},
  "Blood forced through her narrowed valve at high speed stretches out the clotting protein, which exposes it to an enzyme that chops it into pieces too short to work. Replacing the valve fixes the bleeding.",
  exim="fig_slide_vwf",
  excap="Von Willebrand factor and ADAMTS13. Mechanical shear unfolds the multimer and hands it to the enzyme that trims it.")
