# Jeevs Edition — Batch 18: COAGULATION II top-up (8) + LYMPH NODE PATHOLOGY (8)
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §32–§34  the gaps batch 17 left                                  (LO 33, 43, 44, 45, 46, 52)
#   §35 s31b-node-architecture — normal node, reactive mimics        (LO 63, 66)
# Options alphabetised; "correct" is the 0-based index AFTER alphabetisation.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ══════════════════ COAGULATION II — the gaps ══════════════════

# ── 1. Virchow's triad (§34) ───────────────────────────────────────────────
q("A 74-year-old woman is admitted with a fractured neck of femur after a fall and undergoes hemiarthroplasty. She is immobile in bed for 4 days postoperatively and has a right internal jugular central venous catheter placed for access. On the fifth day she develops a swollen, tender right calf, and compression ultrasonography confirms a femoral vein thrombosis. She takes no estrogen-containing medication and has no personal or family history of thrombosis.\n\nWhich of the following categories of Virchow's triad does her postoperative immobility represent?",
  ["A. Blood stasis",
   "B. Endothelial cell damage",
   "C. Hypercoagulable state",
   "D. Increased blood viscosity",
   "E. Platelet hyperreactivity"],
  0,
  "Virchow's triad is the frame for the whole thrombosis section, and every disease and drug in it maps onto one of three categories:\n\n1. ENDOTHELIAL CELL DAMAGE — surgery, trauma, CENTRAL LINES, inflammation.\n2. BLOOD STASIS — IMMOBILISATION, prolonged travel, paralysis, pregnancy.\n3. HYPERCOAGULABLE STATE — the thrombophilias, inherited and acquired.\n\nImmobility is the stasis limb, and the mechanism is mundane: VEINS ARE PUMPED BY THE SURROUNDING MUSCLES and kept unidirectional by ONE-WAY VALVES, so BLOOD ONLY MOVES UP THE LEG WHEN YOU DO. When it stops moving, PLATELETS COME INTO CONTACT WITH EACH OTHER AND RED CELLS SETTLE — add dehydration on a long flight and that is a deep vein thrombosis.\n\nNote that this patient actually has all three limbs working at once, which is typical: her SURGERY and her CENTRAL LINE are endothelial damage, her IMMOBILITY is stasis, and major surgery itself produces an acute-phase hypercoagulable state. That is why postoperative orthopaedic patients are among the highest-risk groups.\n\nTwo practical consequences follow: EVERY ADULT ADMISSION INCLUDES A THROMBOPROPHYLAXIS DECISION — compression stockings, prophylactic heparin, or both — and CENTRAL LINES MUST BE LOCKED WITH HEPARIN, because the body treats indwelling plastic as foreign, so platelets adhere to it and fibrin forms on it.\n\nClots therefore form in DEPENDENT AREAS, usually the legs — which is exactly why an UNUSUAL SITE is a red flag.",
  {"1": "Endothelial damage is the limb her SURGERY and her CENTRAL LINE occupy, so it is very much present in this case — but it is not what immobility contributes. Line-associated thrombosis is the reason lines are heparin-locked and removed once no longer needed.",
   "2": "A hypercoagulable state covers the inherited and acquired thrombophilias, plus the acute-phase changes of major surgery. She has no personal or family history, and immobility does not alter the composition of the blood.",
   "3": "Increased viscosity is a real prothrombotic mechanism — polycythemia vera, hyperviscosity from a paraprotein — but it is not one of the three named categories, and nothing here raises her hematocrit or protein load.",
   "4": "Platelet hyperreactivity contributes to ARTERIAL thrombosis and is the target of antiplatelet drugs. Venous thrombosis is a stasis-and-fibrin problem, which is why anticoagulants rather than aspirin are used for it."},
  "Leg veins only move blood when the leg muscles squeeze them. Lying still for days means the blood in her calf essentially stops moving, and still blood clots.",
  exim="fig_slide_virchow",
  excap="Virchow's triad — endothelial damage, stasis, and hypercoagulability.")

# ── 2. Pregnancy and the postpartum peak (§34) ─────────────────────────────
q("A 31-year-old woman who gave birth 6 days ago by uncomplicated vaginal delivery comes to the emergency department because of left leg swelling and calf pain for 1 day. Her pregnancy was uncomplicated and she takes no medications. Her temperature is 36.9°C (98.4°F), pulse is 92/min, and blood pressure is 118/72 mm Hg. Physical examination shows a 4-cm difference in calf circumference with tenderness along the deep venous system. Compression ultrasonography shows a femoral vein thrombosis.\n\nWhich of the following best explains the timing of this event?",
  ["A. Estrogen withdrawal after delivery triggers a rebound effect",
   "B. Physiologic hypercoagulability that peaks in the postpartum period",
   "C. Postpartum blood loss causing a reactive thrombocytosis and stasis",
   "D. Uterine involution releasing tissue factor into the circulation",
   "E. Volume depletion from lactation raising the hematocrit"],
  1,
  "Pregnancy deserves its own note, and it is a physiology question rather than a pathology one: THE HYPERCOAGULABILITY IS DELIBERATE PHYSIOLOGY, PROTECTING AGAINST HAEMORRHAGE AT DELIVERY — AND IT PEAKS POSTPARTUM, WHEN THE PLACENTAL BED MUST CLOT DOWN.\n\nThat is why the risk does not end when the pregnancy does. The incidence quoted for pregnancy-associated venous thromboembolism is 1.7 PER 1,000 DELIVERIES, and the highest-risk window is the weeks after delivery rather than the third trimester.\n\nPregnancy contributes to all three limbs of Virchow's triad at once: HYPERCOAGULABILITY from raised fibrinogen and factors 7, 8, 10 and von Willebrand factor with falling protein S; STASIS from the gravid uterus compressing the iliac veins, which is also why left-sided deep venous thrombosis predominates, as here; and ENDOTHELIAL INJURY at delivery.\n\nPregnancy also appears on the list of situations in which THROMBOPHILIA TESTING IS UNRELIABLE — it ALTERS MULTIPLE FACTOR AND PROTEIN LEVELS — so a workup sent now would be uninterpretable except for the genetic assays, which may be run at any time.\n\nTreatment is LOW-MOLECULAR-WEIGHT HEPARIN, which does not cross the placenta and is compatible with breastfeeding; warfarin is avoided in pregnancy for teratogenicity, though it is acceptable postpartum.",
  {"0": "Estrogen levels fall rapidly after delivery, and exogenous estrogen is a recognised risk factor — so the direction sounds plausible. Withdrawal of estrogen is not a recognised prothrombotic trigger; the risk comes from the procoagulant changes of pregnancy that persist for weeks.",
   "2": "Reactive thrombocytosis does follow blood loss and is real, but it is a minor contributor and platelet count is not the driver of venous thrombosis. Nothing in her history suggests significant hemorrhage.",
   "3": "Tissue factor release from the placental bed at delivery contributes to the acute procoagulant surge, so this is the closest competitor. It does not explain a risk window extending for weeks, which is what the question asks about.",
   "4": "Lactation does not cause clinically significant volume depletion or hemoconcentration. Raised hematocrit as a thrombotic mechanism belongs to polycythemia vera."},
  "Pregnancy deliberately makes blood clot more easily, so that the raw area left when the placenta detaches can seal. That protective change does not switch off at delivery — it is at its strongest in the weeks afterwards.",
  exim="fig_slide_thrombosis_risk",
  excap="Risk factors sorted into transient, persistent and inherited — pregnancy and the postpartum period sit among the transient ones.")

# ── 3. The reversible combination (§33) ────────────────────────────────────
q("A 24-year-old woman is seen 3 months after a first deep venous thrombosis that occurred 6 weeks after starting a combined oral contraceptive. She smokes 15 cigarettes daily and has done so since age 17. She has no family history of thrombosis, and testing for factor V Leiden and the prothrombin gene mutation is negative. She has completed 3 months of anticoagulation and her symptoms have resolved. She asks what she should do to avoid another clot.\n\nWhich of the following is the most appropriate advice?",
  ["A. Continue anticoagulation indefinitely regardless of other measures",
   "B. Restart the contraceptive and add low-dose aspirin",
   "C. Stop smoking and use a non-estrogen contraceptive method",
   "D. Switch to a progestin-only pill and continue smoking",
   "E. Take prophylactic heparin during air travel only"],
  2,
  "ORAL CONTRACEPTIVES PLUS SMOKING CARRIES A VERY HIGH CLOTTING RISK, AND IMPORTANTLY A REVERSIBLE ONE: STOPPING BOTH MAY REMOVE THE NEED FOR ANTICOAGULATION ALTOGETHER — WHICH IS WHY IDENTIFYING THE COMBINATION MATTERS MORE THAN TREATING AROUND IT.\n\nThat sentence is the whole answer, and it reframes the encounter. The question is not 'which anticoagulant, for how long' but 'what made this happen, and can it be removed'. Hormones — oral contraceptives, estrogen and pregnancy — sit on the ACQUIRED thrombophilia list, and oral contraceptives and hormone replacement carry a RELATIVE RISK OF ABOUT 4 TIMES on their own.\n\nDuration then follows from the circumstances rather than from a genetic result: an oral contraceptive is a MINOR REVERSIBLE RISK FACTOR, carrying about a 5% RECURRENCE RISK IN THE FIRST YEAR — against 3% after a major transient risk factor such as surgery, and 10% for an unprovoked event or a persistent risk factor. With the trigger removed, standard-duration treatment is appropriate and she has completed it.\n\nHer negative genetic testing is worth noting for what it does NOT change: even a positive factor V Leiden result, at a relative risk of 3 to 5 times in a patient with a provoked clot, would not by itself justify indefinite anticoagulation.\n\nSo the intervention with the largest effect is behavioural and contraceptive, not pharmacological — and it is permanent rather than something she takes daily with bleeding risk attached.",
  {"0": "Indefinite anticoagulation is for unprovoked events or persistent risk factors, where the recurrence risk is around 10% per year. Hers was provoked by two removable exposures, and lifelong therapy carries a real annual bleeding risk in a 24-year-old.",
   "1": "Restarting the agent that provoked the thrombosis is unsafe, and aspirin gives only modest protection against recurrent VENOUS thromboembolism. Estrogen-containing contraception is contraindicated after an estrogen-provoked clot.",
   "3": "A progestin-only method is indeed the safer contraceptive choice and would be reasonable — but leaving the smoking in place keeps half of the named high-risk combination untouched, and smoking carries cardiovascular risk of its own.",
   "4": "Travel prophylaxis addresses one minor stasis-related exposure while ignoring the two continuous risk factors she actually has. Prolonged travel confers roughly 1 thrombosis in 4,600 flights, a far smaller contribution than her current combination."},
  "Two things she can change caused this clot: the pill and the cigarettes. Stop both and her risk drops back toward normal — which is better than taking a blood thinner for life.")

# ── 4. Essential thrombocythemia versus reactive thrombocytosis (§33) ──────
q("A 62-year-old man is evaluated after a portal vein thrombosis. He has no cirrhosis, no malignancy, and no recent surgery or infection. He reports occasional burning pain and redness of his hands. His spleen is palpable 4 cm below the left costal margin. A platelet count obtained 2 years ago for an unrelated reason was 780,000/mm3.\n\nLaboratory studies show:\nHemoglobin 14.2 g/dL (N=13.0–16.0 g/dL)\nHematocrit 43% (N=37%–49%)\nLeukocyte count 9,800/mm3 (N=4,500–11,000/mm3)\nPlatelet count 1,140,000/mm3 (N=150,000–400,000/mm3)\nSerum ferritin 180 ng/mL (N=20–250 ng/mL)\nC-reactive protein 0.2 mg/dL (N=<1.0 mg/dL)\n\nWhich of the following best explains his thrombosis?",
  ["A. A myeloproliferative neoplasm with a sustained high platelet count",
   "B. Antiphospholipid antibodies acquired after an occult infection elsewhere",
   "C. Iron deficiency causing a reactive rise in the platelet count",
   "D. Portal hypertension from unrecognized hepatic cirrhosis",
   "E. Reactive thrombocytosis from an occult inflammatory process"],
  0,
  "ESSENTIAL THROMBOCYTHEMIA IS A MYELOPROLIFERATIVE DISORDER PRODUCING A PERSISTENTLY HIGH PLATELET COUNT — AT A MILLION OR MORE, in the lecture's phrase, 'A LOT OF FUEL THERE TO GENERATE A CLOT.' DISTINGUISH IT FROM A REACTIVE THROMBOCYTOSIS, WHICH IS TEMPORARY.\n\nEverything in the vignette is built to make that distinction: the count is PERSISTENT — 780,000/mm3 two years ago and 1,140,000/mm3 now, so this is not a transient rise; there is NO INFLAMMATORY DRIVER, with a C-reactive protein of 0.2 mg/dL; there is NO IRON DEFICIENCY, with a ferritin of 180 ng/mL; and there is SPLENOMEGALY, which reactive thrombocytosis does not cause.\n\nThe two clinical details are worth recognising as well. ERYTHROMELALGIA — burning pain and redness of the hands or feet — is the classic microvascular symptom of essential thrombocythemia and responds to aspirin. And a SPLANCHNIC VEIN THROMBOSIS at an unusual site, with no local cause, is one of the presentations that should prompt a search for a myeloproliferative neoplasm; UNUSUAL LOCATION is itself an indication to investigate.\n\nMyeloproliferative neoplasms appear on the PERSISTENT risk-factor list alongside malignancy, obesity and nephrotic syndrome — persistent risk factors carry about a 10% recurrence risk in the first year, which is what drives indefinite anticoagulation here.\n\nConfirm with JAK2 V617F testing, and CALR or MPL if JAK2 is negative.",
  {"1": "Antiphospholipid syndrome does cause thrombosis at unusual sites and belongs on this differential. It requires a persistent laboratory finding on testing at least 12 weeks apart plus a clinical criterion, and it does not raise the platelet count to over a million or cause splenomegaly.",
   "2": "Iron deficiency is the commonest cause of a reactive thrombocytosis and is genuinely worth excluding, which is why the ferritin is given. His ferritin of 180 ng/mL is normal.",
   "3": "Portal hypertension from cirrhosis causes portal vein thrombosis, but it also causes splenomegaly with a LOW platelet count from hypersplenism — the opposite of his count — and the stem excludes cirrhosis.",
   "4": "Reactive thrombocytosis follows infection, inflammation, bleeding, surgery or malignancy and is TEMPORARY. His count has been high for at least 2 years with a normal C-reactive protein and no inflammatory illness."},
  "His marrow is making platelets out of control rather than in response to something — the count has been over a million for years, and his spleen is enlarged. That much clotting material eventually clots somewhere unusual.")

# ── 5. Poisoning the scissors (§33) ────────────────────────────────────────
q("A 41-year-old man has a second unprovoked deep venous thrombosis. Testing performed 4 months after his first event, off anticoagulation, shows normal protein C and protein S antigen levels, a normal antithrombin level, no factor V Leiden, and no prothrombin gene mutation. His fasting plasma homocysteine is 68 µmol/L (N=5–15 µmol/L) and his serum methylmalonic acid is normal. He has a history of early-onset peripheral arterial disease and a brother who had a stroke at 44.\n\nWhich of the following best explains the prothrombotic effect of this abnormality?",
  ["A. Direct activation of factor X by the accumulated metabolite",
   "B. Increased hepatic synthesis of fibrinogen and factor VIII",
   "C. Inhibition of activated protein C, so factor Va is not cleaved",
   "D. Irreversible inhibition of platelet cyclooxygenase-1 activity",
   "E. Reduced antithrombin binding to the endothelial cell surface"],
  2,
  "The reaction at the centre of this whole section is ACTIVATED PROTEIN C CLEAVES FACTOR 5a, and YOU CAN BREAK IT THREE WAYS, ALL CONVERGING ON THE SAME END RESULT — factor 5a survives and thrombin generation runs on:\n\n• REMOVE THE SCISSORS → protein C or protein S deficiency.\n• ARMOUR-PLATE THE PAPER → factor V Leiden.\n• POISON THE SCISSORS → HYPERHOMOCYSTEINEMIA, WHICH INHIBITS PROTEIN C.\n\nHis protein C is present in normal amount and his factor V is normal — what has changed is that the enzyme cannot work. That is why a quantitative protein C assay can be normal in a patient who is functionally protein C deficient.\n\nThe normal METHYLMALONIC ACID is a deliberate detail: BOTH B12 AND FOLATE DEFICIENCY RAISE HOMOCYSTEINE, BUT ONLY B12 DEFICIENCY RAISES METHYLMALONIC ACID. A raised homocysteine with a normal methylmalonic acid therefore points away from B12 — toward folate deficiency or, at this magnitude with early arterial disease and an affected sibling, an inherited defect such as cystathionine beta-synthase deficiency or MTHFR variants.\n\nOne honest caveat from the risk table: HIGH FACTOR 9, HIGH FACTOR 11, HIGH TAFI AND HYPERHOMOCYSTEINEMIA ARE NOT INDEPENDENT RISK FACTORS for venous thrombosis in that dataset — the risk is associated with high factor 8. Homocysteine is a stronger ARTERIAL risk factor than a venous one, which fits his peripheral arterial disease and his brother's stroke.",
  {"0": "No accumulated metabolite activates factor 10 directly. Homocysteine acts on the endothelium and on the protein C system rather than by inserting itself into the cascade as an activator.",
   "1": "Raised fibrinogen and factor 8 are genuine acquired prothrombotic states, and high factor 8 is the one the risk table identifies as carrying real independent risk. They are not the mechanism of hyperhomocysteinemia.",
   "3": "Irreversible cyclooxygenase-1 inhibition is what ASPIRIN does to platelets, and it is antithrombotic rather than prothrombotic. It also acts on platelets rather than on the protein C axis.",
   "4": "Reduced antithrombin activity is the mechanism of antithrombin deficiency, which also causes heparin resistance. His antithrombin level is normal."},
  "A brake protein normally cuts up a clotting factor to switch it off. He has plenty of the brake, but a build-up of one amino acid poisons it so it cannot cut — the same end result as not having the brake at all.",
  exim="fig_slide_thrombophilia_summary",
  excap="Every named defect placed on one diagram of the protein C / thrombin axis.")

# ── 6. Pneumococcal HUS (§32) ──────────────────────────────────────────────
q("A 2-year-old girl is admitted with a 4-day history of fever, cough, and increasing lethargy. Chest radiograph shows a right lower lobe consolidation with a parapneumonic effusion, and blood culture grows Streptococcus pneumoniae. On the third hospital day her urine output falls and she becomes pale. She has had no diarrhea at any point.\n\nLaboratory studies show:\nHemoglobin 6.9 g/dL (N=11.5–15.5 g/dL)\nHematocrit 21% (N=35%–45%)\nPlatelet count 38,000/mm3 (N=150,000–400,000/mm3)\nReticulocyte count 5.8% (N=0.5%–1.5%)\nLactate dehydrogenase 1,420 U/L (N=100–220 U/L)\nSerum creatinine 2.8 mg/dL (N=0.3–0.7 mg/dL)\nProthrombin time 13 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 32 seconds (N=25–35 seconds)\nFibrinogen 390 mg/dL (N=200–400 mg/dL)\n\nThe smear shows schistocytes and the direct antiglobulin test is positive. Which of the following best explains her renal failure?",
  ["A. Acute tubular necrosis from sepsis-related hypoperfusion",
   "B. Bacterial neuraminidase exposing the Thomsen-Friedenreich antigen",
   "C. Complement factor H deficiency with unregulated activation",
   "D. Deficiency of ADAMTS13 from an acquired inhibitor",
   "E. Immune complex glomerulonephritis following pneumococcal infection"],
  1,
  "The etiologic classification of HUS has an entry that is easy to skip and shows up precisely because it is: INFECTION-INDUCED disease includes SHIGA TOXIN / SHIGA-LIKE TOXIN (E. coli) and NEURAMINIDASE AND T ANTIGEN (STREPTOCOCCUS PNEUMONIAE).\n\nThe mechanism: pneumococcal NEURAMINIDASE cleaves sialic acid from the surface of red cells, platelets and glomerular endothelium, EXPOSING THE UNDERLYING THOMSEN-FRIEDENREICH (T) ANTIGEN. Naturally occurring anti-T IgM antibodies — present in nearly all adult plasma — then bind the newly exposed antigen, producing hemolysis, platelet consumption and endothelial injury. That is also why the DIRECT ANTIGLOBULIN TEST IS POSITIVE here, which is unusual for a thrombotic microangiopathy and is the buried clue.\n\nIt matters practically: because donor plasma CONTAINS ANTI-T ANTIBODIES, plasma-containing products are traditionally avoided or washed in pneumococcal HUS, which is the opposite of the plasma exchange given in TTP.\n\nThe rest of her panel keeps the differential honest: NORMAL PT, aPTT AND FIBRINOGEN exclude DIC — in every thrombotic microangiopathy the clotting times are normal, because factors are not being consumed — and NO DIARRHEAL PRODROME excludes the Shiga toxin form.\n\nHer presentation follows invasive pneumococcal disease with empyema, which is the classic setting.",
  {"0": "Acute tubular necrosis from sepsis is the commonest cause of renal failure in a septic child and must be considered. It does not shred red cells, consume platelets, or produce a positive direct antiglobulin test.",
   "2": "Factor H deficiency causes ATYPICAL HUS, reached when there is neither a diarrheal prodrome NOR a pneumococcal infection. She has an identified pneumococcal trigger, which is its own branch of the algorithm.",
   "3": "An acquired ADAMTS13 inhibitor causes TTP, which is systemic and neurological and typically presents in the 20s or 30s. Her disease is renal, she is 2 years old, and there is an identified infectious trigger.",
   "4": "Post-infectious glomerulonephritis causes hematuria, hypertension and low complement, classically after streptococcal pharyngitis or impetigo. It does not cause microangiopathic hemolysis with schistocytes and thrombocytopenia."},
  "The pneumococcus makes an enzyme that shaves a protective sugar off the surface of her blood cells and kidney vessels, uncovering a hidden marker. Antibodies everyone already has then attack the uncovered cells.",
  exim="fig_slide_hus_algorithm",
  excap="Recognising HUS: a diarrheal prodrome, a pneumococcal infection, or neither — three different branches.")

# ── 7. Drug-associated thrombotic microangiopathy (§32) ────────────────────
q("A 46-year-old woman is 5 weeks after an allogeneic hematopoietic stem cell transplant and is receiving tacrolimus for graft-versus-host disease prophylaxis. She develops worsening anemia, a falling platelet count, hypertension, and a rising creatinine. She has had no diarrhea, and blood and stool cultures are negative.\n\nLaboratory studies show:\nHemoglobin 7.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 23% (N=36%–46%)\nPlatelet count 28,000/mm3 (N=150,000–400,000/mm3)\nLactate dehydrogenase 1,680 U/L (N=100–220 U/L)\nHaptoglobin <10 mg/dL (N=30–200 mg/dL)\nSerum creatinine 2.6 mg/dL (N=0.6–1.2 mg/dL)\nProthrombin time 12 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 31 seconds (N=25–35 seconds)\nFibrinogen 360 mg/dL (N=200–400 mg/dL)\nADAMTS13 activity 68% (N=>60%)\n\nThe smear shows schistocytes. Which of the following is the most appropriate initial step?",
  ["A. Begin daily plasma exchange until the platelet count recovers",
   "B. Begin eculizumab after meningococcal vaccination",
   "C. Discontinue tacrolimus and substitute an alternative agent",
   "D. Transfuse platelets to above 50,000/mm3 and observe",
   "E. Treat empirically for Shiga toxin-producing infection"],
  2,
  "The fourth row of the mechanistic classification is the one this patient occupies: DRUGS AND STEM CELL TRANSPLANT CAUSING ENDOTHELIAL DAMAGE, producing SYSTEMIC AND RENAL THROMBI and FEATURES OF BOTH TTP AND HUS.\n\nThe named associations on the etiologic list include CALCINEURIN INHIBITORS AND TRANSPLANTATION, alongside quinine, chemotherapy, radiation, HIV, malignancy, pregnancy and HELLP syndrome, lupus and antiphospholipid antibodies.\n\nWhen a drug is the trigger, REMOVING THE TRIGGER IS THE TREATMENT. Tacrolimus is directly toxic to endothelium, and transplant-associated thrombotic microangiopathy improves in a substantial proportion of patients when the calcineurin inhibitor is withdrawn or substituted. That step comes before committing to plasma exchange or complement blockade.\n\nHer ADAMTS13 activity of 68% is the finding that takes TTP off the table and therefore takes plasma exchange off the table as a first move — in transplant-associated disease, unlike TTP, plasma exchange has not been shown to change outcome.\n\nAnd the normal PT, aPTT and fibrinogen do the same work they always do: IN EVERY THROMBOTIC MICROANGIOPATHY THE CLOTTING TIMES ARE NORMAL, BECAUSE THE CLOTTING FACTORS ARE NOT BEING CONSUMED. IN DIC THEY ARE BOTH PROLONGED AND FIBRINOGEN FALLS.\n\nIf the microangiopathy persists after the drug is stopped, complement-mediated mechanisms are increasingly implicated and complement blockade is considered — but not as the opening move.",
  {"0": "Plasma exchange is the treatment for TTP, where it replaces ADAMTS13 and removes the inhibitor, and it is often started empirically before that result returns. Her ADAMTS13 is 68%, and exchange does not alter outcome in transplant-associated disease.",
   "1": "Complement blockade is the targeted therapy for atypical HUS and is used in refractory transplant-associated microangiopathy. It is not the first step while an identified endothelial toxin is still being given.",
   "3": "Platelet transfusion for a number alone adds fuel to ongoing microvascular thrombosis, the same error as in TTP. Platelets are reserved for bleeding or a planned procedure.",
   "4": "Shiga toxin HUS follows a bloody diarrheal prodrome, and even then treatment is supportive rather than antimicrobial — antibiotics may increase toxin release. She has had no diarrhea and her stool cultures are negative."},
  "One of her anti-rejection drugs is poisoning the lining of her small blood vessels, so clots form there and shred her red cells. The first move is to take away the drug that is doing it.")

# ── 8. When not to send the HIT assay (§34) ────────────────────────────────
q("A 71-year-old man is in the intensive care unit with septic shock from a perforated colon, receiving broad-spectrum antibiotics, vasopressors, and prophylactic subcutaneous unfractionated heparin started on admission. On day 3 his platelet count has fallen from 210,000/mm3 on admission to 148,000/mm3. He has no thrombosis, no skin lesions, and no bleeding. His fibrinogen is 520 mg/dL (N=200–400 mg/dL) and his D-dimer is 3.1 µg/mL (N=<0.5 µg/mL). The team asks whether to send heparin–platelet factor 4 antibody testing.\n\nWhich of the following is the most appropriate response?",
  ["A. Do not send the assay; the pre-test probability is low",
   "B. Send the assay and stop heparin pending the result",
   "C. Send the assay and substitute argatroban immediately",
   "D. Send the serotonin release assay rather than the immunoassay",
   "E. Stop heparin without testing and give no anticoagulation"],
  0,
  "His 4T score is low — roughly 1 to 2 points:\n• THROMBOCYTOPENIA: a fall of about 30%, with a nadir well above 100 × 10⁹/L — 0 TO 1 POINT.\n• TIMING: day 3, too early without heparin exposure in the past 100 days — 0 POINTS.\n• THROMBOSIS: none — 0 POINTS.\n• OTHER CAUSE: sepsis is a DEFINITE other cause of thrombocytopenia — 0 POINTS.\n\nTHE SCORE EXISTS TO TELL YOU WHETHER TO TEST AT ALL. LOW (0–3) → DO NOT SEND THE TEST. IT IS NOT HIT, AND A FALSE POSITIVE WILL CAUSE HARM — PLENTY OF PEOPLE CARRY THE ANTI-PF4 ANTIBODY WITHOUT HAVING HIT, AND AN INDISCRIMINATE ASSAY GENERATES POSITIVES THAT FORCE YOU TO STOP HEPARIN IN PATIENTS WHO NEVER HAD THE DISEASE.\n\nThe other two bands: HIGH (6–8) → treat as HIT, stop heparin, start an alternative, DO NOT WAIT FOR A RESULT. INTERMEDIATE (4–5) → this is where testing actually helps decide.\n\nHow to read a result you do have: the immunoassay is VERY SENSITIVE, so a NEGATIVE result essentially rules HIT out — genuinely useful. A POSITIVE leaves you stuck, because it is NOT SPECIFIC, so you must treat as HIT while sending the SEROTONIN RELEASE ASSAY, a functional test run only in reference laboratories.\n\nRead honestly: LABORATORY TESTING DOES NOT EXCLUDE A DIAGNOSIS OF HIT, but the NEGATIVE PREDICTIVE VALUE APPROACHES 100% WHEN BOTH ASSAYS ARE NEGATIVE — and POSITIVE RESULTS ALONE DO NOT MEAN THE THROMBOCYTOPENIA CAN BE ATTRIBUTED SOLELY TO HEPARIN.\n\nHis thrombocytopenia is sepsis, and his high fibrinogen argues against consumption.",
  {"1": "Stopping heparin on a low 4T score removes prophylaxis from an immobile septic patient at high thrombotic risk, in order to chase a diagnosis the score already excludes. The test's poor specificity means a positive would compound the error.",
   "2": "Substituting argatroban commits a bleeding-prone septic patient to therapeutic-intensity anticoagulation for a disease he almost certainly does not have. That step belongs to a high 4T score.",
   "3": "The serotonin release assay is the confirmatory functional test, run in reference laboratories with a slow turnaround. It is used when the immunoassay is positive in a patient with meaningful pre-test probability, not as a first-line screen.",
   "4": "Stopping anticoagulation altogether in a critically ill immobile patient raises his thromboembolic risk without addressing anything. Even in genuine HIT the instinct to stop everything is explicitly wrong."},
  "His platelets are down because he is septic, not because of the heparin — the numbers and the timing do not fit. The antibody test throws up false positives, and a false positive would take away a drug he needs.",
  exim="fig_slide_hit",
  excap="The heparin–platelet factor 4 mechanism. The 4T score decides whether this pathway is worth testing for at all.")

# ══════════════════ §35 · LYMPH NODE PATHOLOGY ══════════════════

# ── 9. The floor plan (§35) ────────────────────────────────────────────────
q("A 58-year-old man has an excisional lymph node biopsy for painless cervical lymphadenopathy. At low power the pathologist notes that the follicles of the outer rim are preserved and of varying size, while the zone between and beneath them is markedly expanded by a monotonous population of small to medium lymphoid cells, giving that zone a pale appearance. Immunohistochemistry shows the expanded population is CD3 positive and CD20 negative.\n\nThe expanded zone is the normal residence of which of the following?",
  ["A. B lymphocytes awaiting antigen exposure",
   "B. Macrophages lining the subcapsular sinus",
   "C. Plasma cells within the medullary cords",
   "D. Small T lymphocytes and dendritic cells",
   "E. Tingible body macrophages of the germinal center"],
  3,
  "The node has a fixed floor plan, and EVERY REACTIVE OR NEOPLASTIC PATTERN IS SIMPLY ONE OF THOSE ZONES EXPANDING:\n\n• CORTEX — THE B-CELL ZONE. The outer rim, packed with follicles. PRIMARY follicles have NO germinal center — naive B cells that have not met antigen. SECONDARY follicles contain a reactive germinal center. Finding both in one node is NORMAL, because different lobules drain different tissue fields.\n• PARACORTEX — THE T-CELL ZONE, also called the interfollicular or deep cortical area. Predominantly SMALL T LYMPHOCYTES, plus HISTIOCYTES, DENDRITIC CELLS, plasma cells and scattered activated immunoblasts. Dendritic cells have pale chromatin, irregular contours and abundant cytoplasm — WHEN THEY ACCUMULATE, THE PARACORTEX LOOKS PALE AT LOW POWER. It contains the HIGH ENDOTHELIAL VENULES through which circulating lymphocytes enter.\n• MEDULLA — medullary CORDS (plasma cells and lymphocytes) alternating with medullary SINUSES, toward the hilum.\n\nA CD3-positive, CD20-negative expansion of the paracortex with preserved follicles is a T-cell process. The benign version is PARACORTICAL T-CELL HYPERPLASIA — classically DERMATOPATHIC LYMPHADENOPATHY, the reactive node draining chronically inflamed skin. The malignant counterparts are PERIPHERAL T-CELL LYMPHOMA and ANGIOIMMUNOBLASTIC T-CELL LYMPHOMA.\n\nAnd the trap that makes this pattern the hardest one: MIXED CELLULARITY CLASSIC HODGKIN LYMPHOMA CHARACTERISTICALLY EXPANDS THE INTERFOLLICULAR ZONE WHILE LEAVING REACTIVE FOLLICLES STANDING.\n\nThe organizing habit behind all of it: ASK WHERE IT IS BLUE AND WHERE IT IS PINK BEFORE GOING TO HIGH POWER.",
  {"0": "Naive B cells populate the primary follicles and the mantle zones of the CORTEX — and those follicles are described as preserved here. A B-cell expansion would be CD20 positive.",
   "1": "Sinus macrophages line the subcapsular and medullary SINUSES. Their expansion gives the sinus pattern — reactive sinus histiocytosis, Rosai-Dorfman disease, or metastatic carcinoma arriving in the subcapsular sinus.",
   "2": "Plasma cells sit in the MEDULLARY CORDS toward the hilum. A plasma cell expansion suggests the plasma cell variant of Castleman disease, or a plasmacytic process, and would be CD138 positive rather than CD3 positive.",
   "4": "Tingible body macrophages live inside GERMINAL CENTERS, engulfing the apoptotic bodies of B cells that failed selection. Their presence is strong evidence of a reactive follicle, not a paracortical finding."},
  "A lymph node has fixed neighbourhoods: B cells live in the round follicles at the edge, T cells live in the zone between and beneath them. The expanded area here is full of T cells, so it is the T-cell neighbourhood that has grown.",
  exim="fig_slide_node_architecture",
  excap="The floor plan: afferent lymphatics enter at the capsule, the efferent lymphatic leaves at the hilum, and each zone holds one population.")

# ── 10. Why BCL2 is negative in a normal germinal center (§35) ─────────────
q("A 7-year-old boy has an excisional biopsy of an enlarged cervical node after a sore throat. The node shows numerous follicles that vary in size and shape and are separated by preserved paracortex. The germinal centers contain numerous macrophages filled with apoptotic debris, show a distinct dark zone and light zone, and are surrounded by crisp mantle cuffs; a germinal center is shown. A BCL2 immunostain marks the mantle zone and paracortical lymphocytes but leaves the germinal centers unstained.\n\nWhich of the following best explains the BCL2 result in the germinal centers?",
  ["A. BCL2 is degraded by the enzymes of tingible body macrophages",
   "B. Germinal center B cells suppress BCL2 so failed clones can die",
   "C. Germinal center cells are too immature to express any BCL2",
   "D. Mantle zone lymphocytes consume the available antibody",
   "E. The stain fails in germinal centers because of high mitotic rate",
   "F. The t(14;18) translocation silences the BCL2 promoter"],
  1,
  "BCL2 IS AN ANTI-APOPTOTIC PROTEIN. THE WHOLE PURPOSE OF THE GERMINAL CENTER IS SOMATIC HYPERMUTATION FOLLOWED BY RUTHLESS SELECTION: B cells randomly mutate their immunoglobulin variable regions, and THE ONES WHOSE RECEPTORS GOT WORSE MUST DIE. To make that possible, NORMAL GERMINAL CENTER B CELLS SWITCH BCL2 OFF — THEY ARE DELIBERATELY KEPT EASY TO KILL. That is why the tingible body macrophages have so much to eat.\n\nFOLLICULAR LYMPHOMA ARISES WHEN t(14;18) PUTS BCL2 (CHROMOSOME 18) UNDER THE IMMUNOGLOBULIN HEAVY CHAIN PROMOTER (CHROMOSOME 14), FORCING BCL2 BACK ON. The cells become unkillable and accumulate. So A BCL2-POSITIVE GERMINAL CENTER IS THE SINGLE MOST USEFUL STAIN HERE — AND THE REASON IS MECHANISTIC, NOT ARBITRARY.\n\nFour independent features in this node all point to a reactive process: TINGIBLE BODY MACROPHAGES PRESENT, POLARIZATION PRESERVED, MANTLE ZONES INTACT, and BCL2 NEGATIVE WITHIN THE GERMINAL CENTERS. Follicular lymphoma shows the opposite on every line — monotonous back-to-back follicles effacing the paracortex, no tingible body macrophages, lost polarization, attenuated mantles, and BCL2 positivity.\n\nOne more reason chromosome 14 keeps appearing in B-cell translocations: the germinal center B cell DELIBERATELY BREAKS AND RE-JOINS DNA AT THE IMMUNOGLOBULIN LOCI during class switching and somatic hypermutation. An error can join an oncogene to the hyperactive immunoglobulin heavy chain promoter — t(14;18) BCL2, t(8;14) MYC, t(11;14) cyclin D1.",
  {"0": "Tingible body macrophages digest apoptotic debris inside their own phagolysosomes; they do not degrade proteins in neighbouring viable cells. Their presence is a consequence of the same biology, not its cause.",
   "2": "Germinal center B cells are mature antigen-experienced cells, not immature ones, and they express plenty of other proteins including BCL6 and CD10. The BCL2 absence is a specific regulated event.",
   "4": "A high proliferation rate does not prevent an immunostain from working, and the same antibody stains the mantle and paracortex on the same slide — an internal positive control that proves the stain worked.",
   "5": "The t(14;18) translocation does the opposite: it places BCL2 under an active promoter and turns expression ON. That is the abnormality of follicular lymphoma, and it is absent here.",
   "3": "Immunostains are performed with antibody in excess; adjacent positive cells do not deplete the reagent. Again, the stained mantle zone on the same section demonstrates that reagent was available."},
  "The germinal centre is a test where B cells that mutate badly are supposed to die. To make sure they can die, the cells switch off the survival protein. When a cancer switches it back on, the cells stop dying — and the stain lights up where it should be blank.",
  image="fig_reactive_gc",
  imcap="Germinal center at high power.",
  exim="fig_slide_follicular_pattern",
  excap="The follicular pattern: reactive hyperplasia on one side, follicular lymphoma on the other.")

# ── 11. Mononucleosis versus Hodgkin lymphoma (§35) ────────────────────────
q("A 16-year-old boy has an excisional cervical node biopsy after 3 weeks of fever, sore throat, and fatigue. The node architecture is distorted but partially preserved, with follicular hyperplasia and a markedly expanded, mottled paracortex, as shown. Scattered very large mononuclear and binucleate cells with prominent nucleoli are present within a polymorphous background of small lymphocytes, plasma cells, and immunoblasts. Immunohistochemistry shows the large cells are CD30 positive, CD15 negative, CD20 strongly positive, OCT2 positive, and PAX5 positive at the same intensity as background B cells. In situ hybridization for Epstein-Barr virus is positive.\n\nWhich of the following features best establishes the diagnosis?",
  ["A. CD30 positivity of the large atypical cells",
   "B. Epstein-Barr virus positivity by in situ hybridization",
   "C. Presence of binucleate cells with prominent nucleoli",
   "D. Retained CD20 and OCT2 expression in the large cells",
   "E. The polymorphous inflammatory background"],
  3,
  "THE RS-LIKE CELLS OF INFECTIOUS MONONUCLEOSIS RETAIN THEIR B-CELL PROGRAM; THE REED-STERNBERG CELLS OF CLASSIC HODGKIN LYMPHOMA HAVE LOST THEIRS. EVERYTHING ELSE — CD30, EBV POSITIVITY, LARGE CELLS IN A MIXED BACKGROUND — IS SHARED BETWEEN THE TWO AND THEREFORE CANNOT DECIDE THE CASE. CD20 AND OCT2 ARE THE DISCRIMINATING STAINS.\n\nThe full comparison:\n• ARCHITECTURE — mononucleosis is INTACT OR PARTIALLY EFFACED with follicular hyperplasia and paracortical expansion; classic Hodgkin is effaced, though the MIXED CELLULARITY subtype can be interfollicular, WHICH IS WHAT MAKES IT TRICKY.\n• ATYPICAL CELLS — mononucleosis shows a POLYMORPHOUS SPECTRUM OF SIZES; Hodgkin shows bona fide Reed-Sternberg cells standing out from the background.\n• NUCLEOLI — mononucleosis more BASOPHILIC (blue-grey); Hodgkin well-rounded CHERRY-RED MACRONUCLEOLI WITH A PERINUCLEAR HALO.\n• CD20 POSITIVE and OCT2 POSITIVE and PAX5 AT NORMAL INTENSITY in mononucleosis; CD20 NEGATIVE, OCT2 NEGATIVE, PAX5 WEAK in Hodgkin.\n• CD15 NEGATIVE in mononucleosis; POSITIVE IN ABOUT 75% of Hodgkin.\n\nAnd the warning that goes with it: CD30 IS AN ACTIVATION MARKER, NOT A LYMPHOMA MARKER — normal activated lymphocytes express it. USING CD30 TO CALL HODGKIN LYMPHOMA IN A MONONUCLEOSIS NODE IS ONE OF THE CLASSIC WAYS TO MAKE A CATASTROPHIC ERROR.\n\nHis clinical triad — FEVER, PHARYNGITIS, CERVICAL OR GENERALIZED LYMPHADENOPATHY — is present in more than 50% of cases.",
  {"0": "CD30 is expressed by normal ACTIVATED lymphocytes, so the immunoblasts of mononucleosis are frequently positive. It is compatible with both diagnoses and is therefore uninformative here — and misusing it is the classic catastrophic error.",
   "1": "Epstein-Barr virus causes mononucleosis, and it is also present in a substantial proportion of classic Hodgkin lymphoma, particularly the mixed cellularity subtype. EBV ALONE DOES NOT SETTLE IT.",
   "2": "Large binucleate cells with prominent nucleoli are precisely the REED-STERNBERG-LIKE cells that make mononucleosis dangerous to interpret. Morphology alone cannot separate them, which is the reason immunophenotyping exists.",
   "4": "A polymorphous background is characteristic of mononucleosis AND of classic Hodgkin lymphoma, where the neoplastic cells are a small minority in a reactive infiltrate. It does not discriminate."},
  "Both diseases show huge ugly cells in a messy background, and both can be positive for the same two markers. The question that separates them is whether those big cells still behave like B cells — his do, so this is glandular fever, not lymphoma.",
  image="fig_mono_mottling",
  imcap="Paracortex at medium power.",
  exim="fig_slide_im_vs_hodgkin",
  excap="Infectious mononucleosis versus classic Hodgkin lymphoma versus large B-cell lymphoma, side by side.")

# ── 12. Kikuchi-Fujimoto disease (§35) ─────────────────────────────────────
q("A 26-year-old woman comes to the office because of a tender left cervical mass, fever, and night sweats for 3 weeks, with a 2-kg weight loss. She completed 10 days of amoxicillin-clavulanate without improvement. Her temperature is 38.4°C (101.1°F). Physical examination shows a tender, mobile 3-cm left posterior cervical node. A node biopsy shows patchy zones of eosinophilic necrosis with abundant karyorrhectic debris, numerous histiocytes with crescent-shaped nuclei, and no neutrophils and no granulomas, as shown. The histiocytes are CD68 positive and myeloperoxidase positive, CD8 T cells predominate, and clonality studies show no monoclonal population.\n\nLaboratory studies show:\nLeukocyte count 2,800/mm3 (N=4,500–11,000/mm3)\nHemoglobin 10.5 g/dL (N=12.0–16.0 g/dL)\nHematocrit 32% (N=36%–46%)\nPlatelet count 224,000/mm3 (N=150,000–400,000/mm3)\nLactate dehydrogenase 310 U/L (N=100–220 U/L)\n\nWhich of the following is the most appropriate next step?",
  ["A. Begin antituberculous therapy while awaiting culture results",
   "B. Obtain antinuclear antibody testing and provide supportive care",
   "C. Refer for combination chemotherapy for a high-grade lymphoma",
   "D. Repeat the biopsy to obtain tissue for flow cytometry",
   "E. Treat with azithromycin for presumed cat-scratch disease now"],
  1,
  "Kikuchi-Fujimoto disease — histiocytic necrotizing lymphadenitis. It is BENIGN AND SELF-LIMITED WITH SPONTANEOUS REMISSION, WHICH IS WHY THE DIAGNOSIS MATTERS SO MUCH: THE ALTERNATIVE DIAGNOSES LEAD TO CHEMOTHERAPY.\n\nThe clinical profile is the one that appears in stems: YOUNG ADULTS, WOMEN MORE THAN MEN, MORE COMMON IN ASIAN POPULATIONS; CERVICAL NODES, TYPICALLY UNILATERAL and OFTEN TENDER; FEVER, WEIGHT LOSS, NIGHT SWEATS — A B-SYMPTOM-LIKE PICTURE, WHICH IS EXACTLY WHAT MAKES LYMPHOMA THE CLINICAL WORRY; and DOES NOT RESPOND TO ANTIBIOTICS. Cytopenias are common, as here.\n\nThe morphology is decisive: EOSINOPHILIC NECROSIS with abundant karyorrhectic debris; CRESCENT-SHAPED (C-SHAPED) HISTIOCYTE NUCLEI, which are NON-PHAGOCYTIC; and THE ABSENCE OF NEUTROPHILS — THE FINDING THAT SEPARATES IT FROM SUPPURATIVE INFECTIOUS CAUSES SUCH AS CAT-SCRATCH DISEASE, WHICH IS FULL OF NEUTROPHILS. The histiocytes are CD68 AND MYELOPEROXIDASE POSITIVE, CD8 T cells predominate, and there is no monoclonality.\n\nThe one test that must still be sent is the LUPUS SEROLOGY: LUPUS LYMPHADENITIS IS THE CLOSEST MIMIC — also necrotizing, also neutrophil-poor. FAVOR KIKUCHI WHEN THE HISTIOCYTES ARE MPO POSITIVE; lupus classically shows HEMATOXYLIN BODIES AND ABUNDANT PLASMA CELLS. Some patients later develop lupus, so the serology is both a differential and a follow-up question.\n\nTreatment is supportive only.",
  {"0": "Mycobacterial lymphadenitis produces NECROTIZING GRANULOMAS, and the departmental reflex on seeing nodal necrosis is an acid-fast bacilli stain and a Grocott methenamine silver stain. Her biopsy shows NO granulomas, and empiric antituberculous therapy carries real hepatotoxicity.",
   "2": "High-grade lymphoma is the clinical worry that brings these patients to biopsy, and at high power Kikuchi can resemble it. Clonality studies show NO monoclonal population and the atypical cells are HISTIOCYTES (CD68 and MPO positive) rather than lymphoid — chemotherapy here would be a catastrophe.",
   "3": "The biopsy already answered the question, with morphology, immunophenotype and clonality studies all concordant. A repeat procedure adds risk and cost without a question to answer.",
   "4": "Cat-scratch disease causes tender regional lymphadenopathy after a kitten scratch and is treated with azithromycin, so the clinical picture overlaps. Its histology is SUPPURATIVE STELLATE GRANULOMAS FULL OF NEUTROPHILS — and her biopsy explicitly has none."},
  "Her node looks frightening under the microscope and her symptoms look like lymphoma, but the pattern — dead tissue with no pus cells and curved-nucleus scavenger cells — is a harmless condition that goes away by itself. The one thing to check is lupus.",
  image="fig_kikuchi_highpower",
  imcap="Lymph node at high power.",
  exim="fig_slide_kikuchi",
  excap="The Kikuchi-Fujimoto checklist — clinical profile, morphology and immunophenotype.")

# ── 13. Rosai-Dorfman disease (§35) ────────────────────────────────────────
q("A 34-year-old man has bilateral painless cervical lymphadenopathy with nodes up to 6 cm that have been enlarging for 8 months. Biopsy shows markedly expanded subcapsular and medullary sinuses filled with large histiocytes with abundant pale cytoplasm, many containing intact lymphocytes and plasma cells within clear spaces in their cytoplasm, as shown. The histiocytes are S100 positive, CD68 positive, and CD1a and CD207 negative. The engulfed cells are S100 negative.\n\nWhich of the following is the most likely diagnosis?",
  ["A. Hemophagocytic lymphohistiocytosis",
   "B. Langerhans cell histiocytosis",
   "C. Metastatic malignant melanoma",
   "D. Reactive sinus histiocytosis",
   "E. Rosai-Dorfman disease"],
  4,
  "The finding is EMPERIPOLESIS — INTACT, VIABLE LYMPHOCYTES AND PLASMA CELLS PASSING THROUGH a histiocyte, NOT BEING DIGESTED — and the diagnosis is ROSAI-DORFMAN DISEASE, sinus histiocytosis with massive lymphadenopathy. It is the SAME COMPARTMENT AS ORDINARY REACTIVE SINUS HISTIOCYTOSIS, EXPANDED TO THE POINT OF PRODUCING BULKY NODES, and it is now recognised as a HISTIOCYTIC NEOPLASM with MAP KINASE PATHWAY MUTATIONS IN ABOUT A THIRD OF CASES.\n\nThe elegant part is the stain: S100 STAINS THE NEOPLASTIC HISTIOCYTES BUT IS NEGATIVE IN THE LYMPHOCYTES AND PLASMA CELLS THEY HAVE ENGULFED, so the engulfed cells appear as CLEAR, UNSTAINED HOLES INSIDE A BROWN HISTIOCYTE — THE STAIN HIGHLIGHTS EMPERIPOLESIS WHILE SIMULTANEOUSLY PROVIDING A BUILT-IN INTERNAL NEGATIVE CONTROL.\n\nThe phenotype is S100+, CD68+, CD163+, cyclin D1+, OCT2+, and CRUCIALLY CD1a− AND CD207 (LANGERIN)−.\n\nHold emperipolesis apart from HEMOPHAGOCYTOSIS, which is the other 'cells inside a histiocyte' finding: in hemophagocytosis the contents are DEBRIS, APOPTOTIC BODIES AND DEGENERATED CELLS being DESTROYED, it is seen in HLH and reactive states, and CD68 highlights the histiocyte.\n\nDistribution: nodal involvement in 50% to 60%, EXTRANODAL SITES IN 30% TO 40% including SKIN AND CENTRAL NERVOUS SYSTEM. SPONTANEOUS REGRESSION OCCURS AND OBSERVATION IS OFTEN APPROPRIATE; relapsed disease gets steroids, chemotherapy, radiation, or MEK INHIBITION.",
  {"0": "Hemophagocytic lymphohistiocytosis shows histiocytes containing DEGENERATED cells and debris being destroyed, with fever, splenomegaly, cytopenias, a high ferritin, high triglycerides and a low fibrinogen. Her histiocytes contain INTACT cells, which is a different finding.",
   "1": "Langerhans cell histiocytosis is ALSO S100 POSITIVE, so S100 alone cannot separate them — which is exactly why CD1a and CD207 are done. Langerhans cells are CD1a AND CD207 POSITIVE, with grooved 'coffee-bean' nuclei and eosinophils rather than emperipolesis.",
   "2": "Melanoma is the other S100-positive sinus mimic and can grow in a sinusoidal distribution. It is SOX10 POSITIVE AND CD68 NEGATIVE, and it does not show emperipolesis.",
   "3": "Ordinary reactive sinus histiocytosis is MILD expansion of the sinuses by bland histiocytes — a normal phenomenon, not a disease. It does not produce 6-cm nodes, S100 positivity, or emperipolesis."},
  "His scavenger cells have swallowed whole living lymphocytes that are wandering through them unharmed — a very specific finding. A stain marks the scavenger cell brown and leaves the swallowed cells clear, so you can see them sitting inside.",
  image="fig_rosai_emperipolesis",
  imcap="Lymph node sinus at high power.",
  exim="fig_slide_sinus_pattern",
  excap="The sinus pattern and its differential — reactive histiocytosis, Rosai-Dorfman disease, metastasis and anaplastic large cell lymphoma.")

# ── 14. Castleman disease (§35) ────────────────────────────────────────────
q("A 29-year-old woman has an isolated 7-cm mediastinal mass found incidentally on chest imaging. She has no fever, no weight loss, and no other lymphadenopathy, and she is HIV negative. Excision shows a node containing numerous small follicles with regressed germinal centers composed largely of pale dendritic cells, surrounded by concentric rings of mantle-zone lymphocytes, with hyalinized vessels penetrating into the follicles, as shown. The interfollicular tissue shows prominent vascularity with hyalinized vessel walls.\n\nThis lesion carries an increased risk of developing which of the following?",
  ["A. Diffuse large B-cell lymphoma",
   "B. Follicular dendritic cell sarcoma",
   "C. Kaposi sarcoma of the mediastinum",
   "D. Nodular sclerosis Hodgkin lymphoma",
   "E. Primary effusion lymphoma"],
  1,
  "This is the HYALINE VASCULAR VARIANT of Castleman disease, and the morphologic buzzwords are all present:\n• HYALINIZATION — very dense pink material around the vessels, the feature the variant is named for.\n• ATRETIC FOLLICLES — small, composed mainly of PALE DENDRITIC CELLS, a normal germinal centre constituent that here becomes the dominant population.\n• THE 'LOLLIPOP SIGN' — a PENETRATING BLOOD VESSEL running into the atretic follicle (the vessel is the stick, the follicle is the candy).\n• ONION-SKINNING — mantle-zone lymphocytes in CONCENTRIC RINGS.\n• 'TWINNING' — two germinal centers within one follicle.\nGross: a large firm node, MEDIAN 7 cm — hers is exactly that.\n\nCASTLEMAN DISEASE IS A DISEASE OF DENDRITIC CELLS, which explains why its follicles look SMALL, PALE AND ATRETIC RATHER THAN HYPERPLASTIC — and the complication follows logically once you accept that: THE HYALINE VASCULAR VARIANT IS PRONE TO DEVELOPING FOLLICULAR DENDRITIC CELL SARCOMA.\n\nThe classification has two axes. AXIS 1 — HOW MANY NODES: UNICENTRIC (a single node or closely related group, USUALLY CURABLE BY EXCISION — which is her situation) versus MULTICENTRIC (20% to 25%, systemic disease, subdivided into HHV-8-ASSOCIATED especially in HIV, IDIOPATHIC, and SYNDROME-ASSOCIATED such as POEMS and TAFRO). AXIS 2 — WHAT IT LOOKS LIKE: HYALINE VASCULAR versus PLASMA CELL variant, the latter showing sheets of plasma cells between follicles and occurring more often with systemic disease.",
  {"0": "Diffuse large B-cell lymphoma is the transformation risk of several indolent B-cell lymphomas, and it can arise in HHV-8-associated multicentric disease. It is not the lesion the hyaline vascular variant is specifically prone to.",
   "2": "Kaposi sarcoma is HHV-8 driven and associates with MULTICENTRIC Castleman disease in HIV-positive patients. She has unicentric disease and is HIV negative.",
   "3": "Nodular sclerosis Hodgkin lymphoma is the classic mediastinal lymphoma in a young woman, so the location and demographic are a deliberate decoy. The histology described is Castleman disease, not Hodgkin — there are no Reed-Sternberg cells and no broad collagen bands.",
   "4": "Primary effusion lymphoma is an HHV-8-associated lymphoma presenting as a malignant effusion without a mass, typically in HIV-positive patients. It is linked to multicentric disease rather than to the unicentric hyaline vascular variant."},
  "Her lymph node is full of shrunken follicles built mostly from support cells rather than lymphocytes, with little blood vessels poking into them like lollipop sticks. Because the disease is a disease of those support cells, the cancer it can turn into is a cancer of those same cells.",
  image="fig_castleman_lollipop",
  imcap="Lymph node follicle at medium power.",
  exim="fig_castleman_onion",
  excap="Onion-skinning — concentric mantle lymphocytes around a small atretic germinal center.")

# ── 15. Formalin is a one-way door (§35) ──────────────────────────────────
q("A 62-year-old man with rapidly enlarging generalized lymphadenopathy and night sweats undergoes an excisional axillary lymph node biopsy at 4:30 p.m. The specimen is sent to the laboratory, where a resident places the entire node into formalin before the pathologist can triage it. A lymphoma is suspected clinically and the team wishes to establish clonality and to obtain a karyotype.\n\nWhich of the following studies has this handling made impossible?",
  ["A. Flow cytometry and conventional cytogenetics",
   "B. Fluorescence in situ hybridization for translocations",
   "C. Immunohistochemistry for CD20 and CD3",
   "D. Next-generation sequencing of a lymphoma panel",
   "E. Polymerase chain reaction for gene rearrangement"],
  0,
  "ONCE TISSUE GOES INTO FORMALIN, FLOW CYTOMETRY AND CONVENTIONAL CYTOGENETICS ARE NO LONGER POSSIBLE.\n\nThe reasons are physical: FLOW NEEDS A VIABLE SINGLE-CELL SUSPENSION, and KARYOTYPE NEEDS LIVING CELLS THAT CAN BE DRIVEN INTO METAPHASE. Formalin cross-links proteins and kills the cells, so both are lost.\n\nIHC, FISH AND MOST MOLECULAR STUDIES — PCR, NEXT-GENERATION SEQUENCING — STILL WORK ON FIXED PARAFFIN TISSUE. BUT FLOW AND KARYOTYPE ARE LOST FOREVER. That is exactly why the protocol TRIAGES FRESH TISSUE FIRST.\n\nThe workaround that makes triage possible is TOUCH PREPARATIONS, which EXPLOIT THE FACT THAT LYMPHOCYTES ARE DISCOHESIVE — tap the cut surface against a slide and they transfer readily. A rapid read of that imprint drives every subsequent decision while the tissue is still fresh:\n• SHEETS OF IMMATURE CELLS (BLASTS) → lymphoblastic leukemia/lymphoma.\n• SCATTERED LARGE ATYPICAL CELLS IN A MIXED BACKGROUND → Hodgkin lymphoma.\n• SHEETS OF LARGE ATYPICAL CELLS → diffuse large B-cell lymphoma.\n• VERY LARGE, BIZARRE, COHESIVE-LOOKING CELLS → anaplastic large cell lymphoma, and in adults metastatic carcinoma or melanoma.\n\nIn practice clonality can still be established here — by immunohistochemistry for light chain restriction, or by PCR for immunoglobulin gene rearrangement — so the case is not lost. What is gone is the fast, quantitative immunophenotype and the metaphase karyotype.",
  {"1": "FISH is performed on fixed paraffin sections routinely and is how t(14;18), t(8;14), t(11;14) and MYC rearrangements are demonstrated in everyday practice. Fixation does not prevent it.",
   "2": "Immunohistochemistry is designed for formalin-fixed paraffin-embedded tissue — it is the standard substrate. CD20 and CD3 will stain normally.",
   "3": "Next-generation sequencing works well on fixed tissue, which is how most solid tumour and lymphoma panels are run. Fragmentation reduces yield somewhat but does not make it impossible.",
   "4": "PCR for immunoglobulin heavy chain or T-cell receptor gene rearrangement is routinely performed on paraffin tissue and remains an available route to demonstrating clonality here."},
  "Formalin preserves tissue by killing and gluing the cells together. Two tests need the cells alive — one sorts them one at a time, the other has to grow them and catch them dividing. Everything else still works on preserved tissue.",
  exim="fig_slide_node_processing",
  excap="The processing protocol: fresh tissue is triaged before anything is fixed.")

# ── 16. Hemophagocytic lymphohistiocytosis (§35) ───────────────────────────
q("A 5-month-old boy is admitted with 10 days of fever, irritability, and poor feeding. His temperature is 39.2°C (102.6°F), pulse is 168/min, and respirations are 48/min. Physical examination shows hepatomegaly and a spleen palpable 5 cm below the left costal margin. A bone marrow examination shows macrophages containing engulfed erythrocytes, nucleated red cells, and cellular debris, as shown. Epstein-Barr virus DNA is detected in blood.\n\nLaboratory studies show:\nHemoglobin 7.6 g/dL (N=10.5–13.5 g/dL)\nLeukocyte count 2,100/mm3 (N=6,000–17,500/mm3)\nPlatelet count 44,000/mm3 (N=150,000–400,000/mm3)\nSerum ferritin 14,800 ng/mL (N=10–120 ng/mL)\nSerum triglycerides 480 mg/dL (N=<150 mg/dL)\nFibrinogen 92 mg/dL (N=200–400 mg/dL)\n\nWhich of the following best describes the significance of the marrow finding?",
  ["A. It confirms the diagnosis independently of any other findings",
   "B. It establishes a primary rather than a secondary process",
   "C. It excludes an underlying lymphoma as the disease trigger",
   "D. It indicates metastatic infiltration of the bone marrow",
   "E. It satisfies one of the criteria required for the diagnosis"],
  4,
  "HEMOPHAGOCYTOSIS IS NOT SPECIFIC — AND THAT IS THE POINT. Hemophagocytic histiocytes are seen in many settings. THEIR VALUE IS THAT, IN THE RIGHT CLINICAL AND LABORATORY CONTEXT, THEY SATISFY ONE OF THE EIGHT CRITERIA. A PATHOLOGIST REPORTING HEMOPHAGOCYTOSIS IS CONTRIBUTING ONE LINE OF EVIDENCE, NOT MAKING A DIAGNOSIS. DO NOT LET A STEM CONVINCE YOU THE MARROW FINDING ALONE ESTABLISHES HLH.\n\nHLH is a SUDDEN-ONSET SYSTEMIC INFLAMMATORY RESPONSE SECONDARY TO MACROPHAGE ACTIVATION — macrophages become uncontrolled, consume blood cells, and flood the body with cytokines. DIAGNOSIS REQUIRES 5 OF 8 CRITERIA, spread across three domains:\n• CLINICAL — FEVER, SPLENOMEGALY, CYTOPENIAS.\n• LABORATORY — HIGH FERRITIN (the one to remember), HIGH TRIGLYCERIDES, LOW FIBRINOGEN.\n• PATHOLOGIC — HEMOPHAGOCYTIC HISTIOCYTES in bone marrow, spleen or lymph node.\n\nThis infant already has fever, splenomegaly, cytopenias in three lines, a ferritin of 14,800 ng/mL, triglycerides of 480 mg/dL, a fibrinogen of 92 mg/dL, and the marrow finding — comfortably past the threshold.\n\nThe primary-versus-secondary split: PRIMARY (FAMILIAL) HLH OCCURS IN INFANTS, from inherited mutations in the GRANULE-MEDIATED CYTOTOXICITY PATHWAY. SECONDARY HLH is TRIGGERED BY INFECTION — PARTICULARLY EBV AND CMV — and also occurs with AGGRESSIVE LYMPHOMAS and AUTOIMMUNE DISEASE, where it is called MACROPHAGE ACTIVATION SYNDROME. At 5 months with EBV in the blood, BOTH apply: suspect the familial form AND hunt for the trigger.",
  {"0": "This is the misconception the question is built on. Hemophagocytosis occurs in sepsis, after transfusion, in autoimmune disease and in lymphoma, so it cannot stand alone — the diagnosis is a composite of 5 of 8 criteria.",
   "1": "The marrow appearance is identical in primary and secondary disease. That distinction is made by age, family history and genetic testing of the granule-mediated cytotoxicity pathway, not by morphology.",
   "2": "Lymphoma-associated HLH shows exactly this marrow finding, so it excludes nothing. In an older patient an occult aggressive lymphoma must be actively sought as the trigger.",
   "3": "Metastatic infiltration would show foreign tumour cells, often with a leukoerythroblastic blood picture. These are the patient's own macrophages engulfing his own blood cells."},
  "Finding scavenger cells eating blood cells in the marrow sounds like it proves the diagnosis, but it happens in lots of illnesses. It counts as one item on a checklist of eight — he needs five, and he has plenty.",
  image="fig_hemophagocytosis",
  imcap="Bone marrow aspirate at high power.")
