# Jeevs Edition — Batch 19: HEMATOLOGIC MALIGNANCY, part 1 — the frame and the myeloid diseases
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §36 s32-malig-core — the core construct, acute leukemia, TLS and DIC     (LO 6, 58)
#   §37 s33-aml        — AML and acute promyelocytic leukemia               (LO 39, 54, 80, 82)
#   §38 s34-mds-cml    — myelodysplastic syndrome and chronic myeloid leukemia (LO 37, 39)
#   §39 s35-mpn        — polycythemia vera, essential thrombocythemia, myelofibrosis (LO 38)
# Options alphabetised; "correct" is the 0-based index AFTER alphabetisation.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ══════════════════ §36 · THE CORE CONSTRUCT ══════════════════

# ── 1. Differentiation stage sets the tempo (§36) ──────────────────────────
q("Two patients are discussed at a tumor board. The first is a 9-year-old boy with a rapidly enlarging abdominal mass, a lactate dehydrogenase of 2,400 U/L (N=100–220 U/L), and a biopsy showing sheets of intermediate-sized cells with a proliferation index above 95%. The second is a 71-year-old man with 3 years of slowly progressive fatigue, a serum monoclonal protein, and a marrow containing 40% cells with eccentric nuclei and perinuclear clearing. Untreated, the first patient's disease would be fatal within weeks and the second's over years.\n\nWhich of the following best explains the difference in tempo between these two diseases?",
  ["A. The first arose in lymphoid tissue and the second in marrow",
   "B. The first has a higher mutational burden than the second",
   "C. The first is treated with curative intent and the second is not",
   "D. The second secretes a protein rather than forming a mass",
   "E. The transforming cell was less differentiated in the first"],
  4,
  "One idea organizes every blood cancer: A HEMATOPOIETIC CELL ACQUIRES A MUTATION THAT DISRUPTS THE DIFFERENTIATION AND MATURATION OF ITS PROGENY, AND THE RESULTING DISEASE DEPENDS ON THE MATURATION STAGE OF THE CELL THAT UNDERWENT TRANSFORMATION.\n\nLESS DIFFERENTIATED → AGGRESSIVE. MORE DIFFERENTIATED → INDOLENT.\n\nBurkitt lymphoma arises from a LESS DIFFERENTIATED germinal center B cell, which retains enormous proliferative capacity — it is one of the fastest-growing human tumours, and the proliferation index above 95% says so directly. Multiple myeloma arises from the FULLY DIFFERENTIATED PLASMA CELL, whose job is SECRETION RATHER THAN DIVISION.\n\nThe memory hook: DIFFERENTIATION IS A ONE-WAY STREET. A highly specialized cell can never go back and become something else, so A CANCER ARISING EARLY ON THAT STREET INHERITS THE PROLIFERATIVE CAPACITY OF AN UNDIFFERENTIATED CELL.\n\nThat also explains where the damage comes from in each. Myeloma DOES NOT BLAST THE MARROW THE WAY AN ACUTE LEUKEMIA DOES — its complications (kidney failure from light chains, bone lesions, hypercalcemia) COME FROM THE PRODUCT OF THE CELL RATHER THAN FROM ITS PROLIFERATION.\n\nThe darkest corollary runs the other way: in the very least differentiated cancers you can get an acute leukemia with BOTH MYELOID AND LYMPHOID FEATURES — transformation before the branch point — and the prognosis is correspondingly dismal.",
  {"0": "Site of origin does not set tempo — aggressive and indolent diseases arise in both marrow and lymphoid tissue. Acute myeloid leukemia and chronic myeloid leukemia both begin in marrow and behave completely differently.",
   "1": "Mutational burden correlates loosely with behaviour in some solid tumours, and Burkitt is in fact a genetically simple tumour driven largely by one translocation. It is not the organizing principle here.",
   "2": "Treatment intent is a CONSEQUENCE of the tempo rather than its cause — aggressive disease is treated with curative intent precisely BECAUSE rapidly dividing cells are what chemotherapy kills.",
   "3": "That the plasma cell secretes a paraprotein is true and explains the pattern of organ damage in myeloma. It describes what the mature cell does rather than why the disease is slow."},
  "A cancer that starts from a very immature cell inherits that cell's ability to divide endlessly, so it grows in weeks. A cancer that starts from a fully grown-up cell keeps doing that cell's day job instead, so it takes years.")

# ── 2. A high white count with no working cells (§36) ──────────────────────
q("A 57-year-old woman comes to the office because of 3 weeks of progressive malaise and spontaneous bruising. She has no history of serious illness and takes no medications. Her temperature is 37.9°C (100.2°F), pulse is 110/min, and blood pressure is 118/70 mm Hg. Physical examination shows pallor and scattered ecchymoses over both arms, with no lymphadenopathy and no splenomegaly.\n\nLaboratory studies show:\nHemoglobin 6.2 g/dL (N=12.0–16.0 g/dL)\nHematocrit 19% (N=36%–46%)\nLeukocyte count 87,000/mm3 (N=4,500–11,000/mm3)\nBlasts 90% (N=0%)\nAbsolute neutrophil count 600/µL (N=1,800–7,000/µL)\nPlatelet count 45,000/mm3 (N=150,000–400,000/mm3)\n\nWhich of the following best explains why this patient is at high risk of serious infection?",
  ["A. Blasts are non-functional, so she is functionally neutropenic",
   "B. Her anemia impairs oxygen delivery to phagocytosing cells",
   "C. Hyperleukocytosis causes leukostasis in pulmonary capillaries",
   "D. Splenic sequestration is removing mature neutrophils",
   "E. Thrombocytopenia allows bacterial entry through mucosa"],
  0,
  "The white count measures CELLS, NOT FUNCTION. She has 87,000 leukocytes of which 90% are BLASTS — undifferentiated precursors that do nothing — leaving an ABSOLUTE NEUTROPHIL COUNT OF 600/µL. She is FUNCTIONALLY NEUTROPENIC despite a hugely elevated total, and below 1,000/µL the risk of infection is sharply increased.\n\nThis is the signature presentation of acute leukemia: TRILINEAGE MARROW FAILURE WITH A PACKED MARROW. She is anemic, thrombocytopenic and neutropenic simultaneously, because unregulated blast growth has crowded out normal hematopoiesis.\n\nThe defining features to hold: unregulated growth of undifferentiated cells called BLASTS; the cells overwhelm the marrow and SPILL OUT INTO THE PERIPHERAL BLOOD; diagnosis requires MORE THAN 20% BLASTS IN THE MARROW OR THE PERIPHERAL BLOOD — either compartment suffices; the white count may be HIGH, NORMAL OR LOW, so A NORMAL WHITE COUNT DOES NOT EXCLUDE ACUTE LEUKEMIA; and untreated, DEATH WITHIN 12 WEEKS in most cases.\n\nInitial management is to EXTINGUISH THE FIRE: treat the marrow failure with transfusion support (hemoglobin below 7, platelets below 10,000 — or below 50,000 if actively bleeding); IDENTIFY AND TREAT INFECTION, which in a neutropenic patient is the thing most likely to kill her this week; and buy time with HYDROXYUREA, which is CYTOREDUCTION, NOT CURE.",
  {"2": "Leukostasis is a genuine hazard above roughly 100,000/mm3 and causes dyspnea, hypoxemia and neurologic symptoms from sludging in the microvasculature. It is a mechanical emergency, not the reason she cannot fight infection.",
   "1": "Anemia at 6.2 g/dL contributes to her fatigue and tachycardia and needs transfusion. Oxygen delivery is not the limiting factor in neutrophil function at this hemoglobin.",
   "3": "Splenic sequestration lowers counts in hypersplenism, and her examination explicitly records no splenomegaly. Her neutropenia is a production problem from a marrow packed with blasts.",
   "4": "Thrombocytopenia causes bleeding rather than infection, and it is the reason for her ecchymoses. Mucosal barrier breakdown in leukemia comes from chemotherapy-induced mucositis, not from a low platelet count."},
  "Her white cell count is enormous, but almost all of those cells are unfinished and useless. The number of cells that can actually fight bacteria is only a fraction of normal, so she is as vulnerable as someone with a very low count.",
  exim="fig_auer_rods",
  excap="Myeloblasts in acute myeloid leukemia — large cells with a high nuclear-to-cytoplasmic ratio, fine chromatin and visible nucleoli.")

# ── 3. Tumor lysis syndrome (§36) ─────────────────────────────────────────
q("A 24-year-old man with a bulky abdominal mass is admitted and begins induction chemotherapy. Forty-eight hours later he is oliguric. He is receiving intravenous fluids. His temperature is 37.1°C (98.8°F), pulse is 104/min, and blood pressure is 128/78 mm Hg. Physical examination shows no bleeding and no new focal findings.\n\nLaboratory studies show:\nSerum potassium 6.4 mEq/L (N=3.5–5.0 mEq/L)\nSerum phosphorus 7.1 mg/dL (N=2.5–4.5 mg/dL)\nSerum calcium 6.8 mg/dL (N=8.5–10.5 mg/dL)\nSerum uric acid 14.2 mg/dL (N=3.0–7.0 mg/dL)\nSerum creatinine 2.9 mg/dL (N=0.6–1.2 mg/dL)\nProthrombin time 12 seconds (N=11–15 seconds)\nFibrinogen 340 mg/dL (N=200–400 mg/dL)\n\nWhich of the following best explains the hypocalcemia?",
  ["A. Binding and precipitation of calcium by released phosphate",
   "B. Consumption of calcium during widespread microthrombosis",
   "C. Impaired renal hydroxylation of 25-hydroxyvitamin D",
   "D. Parathyroid suppression by the released intracellular potassium",
   "E. Sequestration of calcium within lysed tumor cells"],
  0,
  "TUMOUR LYSIS SYNDROME — rapid cell turnover and death releasing intracellular contents. The pattern in one line: EVERYTHING GOES UP EXCEPT CALCIUM. Potassium up, phosphate up, uric acid up, CALCIUM DOWN — BECAUSE THE RELEASED PHOSPHATE BINDS AND PRECIPITATES THE CALCIUM. IF A QUESTION LISTS THREE HIGHS AND ONE LOW IN A PATIENT STARTING CHEMOTHERAPY, THIS IS THE DIAGNOSIS.\n\nThe four derangements, each with its own treatment:\n• HYPERURICEMIA → RENAL FAILURE. Prevention: ALLOPURINOL. Severe: RASBURICASE, which degrades EXISTING urate rather than merely blocking production.\n• HYPERPHOSPHATEMIA.\n• HYPOCALCEMIA — may need calcium replacement.\n• HYPERKALEMIA → ARRHYTHMIA. Treatment: sodium polystyrene, with urgent attention.\n\nWatch for it in ACUTE LEUKEMIAS AND AGGRESSIVE LYMPHOMAS — PARTICULARLY BURKITT — either spontaneously or on starting treatment. A bulky abdominal mass in a young man with this metabolic profile is Burkitt until proven otherwise.\n\nAnd the discrimination against the other week-one emergency: DIC IS A COAGULOPATHY — low fibrinogen, prolonged times, schistocytes; TUMOUR LYSIS IS METABOLIC. THEY ARE BOTH EMERGENCIES OF THE FIRST WEEK, AND THEY ARE NOT THE SAME PROBLEM. His prothrombin time and fibrinogen are normal, which is the explicit negative that rules DIC out here.",
  {"1": "Consumption in microthrombosis describes disseminated intravascular coagulation, which consumes platelets and clotting factors rather than calcium. His prothrombin time is 12 seconds and his fibrinogen is 340 mg/dL, both normal.",
   "2": "Impaired 1-alpha-hydroxylation causes hypocalcemia in CHRONIC kidney disease, over months. His renal impairment developed over 48 hours and is a consequence of urate nephropathy rather than a cause of his calcium level.",
   "3": "Potassium does not suppress the parathyroid glands. Hyperkalemia here is a direct consequence of cell lysis and matters because of arrhythmia risk.",
   "4": "Lysed cells RELEASE their contents rather than sequestering them — that release is the entire mechanism of the syndrome. Intracellular calcium is also low relative to plasma, so lysis would not lower serum calcium."},
  "Chemotherapy burst huge numbers of tumour cells at once, spilling their insides into the blood. The phosphate that pours out grabs the calcium and drags it out of solution, so three values shoot up and calcium falls.")

# ── 4. The other week-one emergency (§36) ─────────────────────────────────
q("A 46-year-old woman is admitted with 10 days of fatigue and gum bleeding. Her temperature is 37.6°C (99.7°F), pulse is 108/min, and blood pressure is 112/68 mm Hg. Physical examination shows extensive ecchymoses, bleeding from venipuncture sites, and oozing gums. A peripheral blood smear shows numerous cells with abundant azurophilic granules and several containing multiple needle-shaped cytoplasmic inclusions.\n\nLaboratory studies show:\nHemoglobin 8.2 g/dL (N=12.0–16.0 g/dL)\nHematocrit 25% (N=36%–46%)\nLeukocyte count 2,400/mm3 (N=4,500–11,000/mm3)\nPlatelet count 22,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 21 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 52 seconds (N=25–35 seconds)\nFibrinogen 80 mg/dL (N=200–400 mg/dL)\nD-dimer 18.4 µg/mL (N=<0.5 µg/mL)\n\nWhich of the following is the most appropriate immediate step in management?",
  ["A. Begin all-trans retinoic acid now",
   "B. Begin induction with cytarabine and daunorubicin",
   "C. Begin rasburicase and intravenous fluids",
   "D. Obtain cytogenetics before starting any therapy",
   "E. Transfuse platelets and observe for 24 hours"],
  0,
  "ACUTE PROMYELOCYTIC LEUKEMIA. The rule is explicit: IN A NEW ACUTE LEUKEMIA WITH A COAGULOPATHY, START ALL-TRANS RETINOIC ACID ON SUSPICION, BEFORE THE CYTOGENETICS COME BACK. THE COST OF BEING WRONG IS SMALL; THE COST OF WAITING IS A FATAL BLEED.\n\nSEVERE DISSEMINATED INTRAVASCULAR COAGULATION CAUSES EARLY DEATH FROM BLEEDING IN UNRECOGNIZED CASES. THE PATIENT DOES NOT DIE OF THE LEUKEMIA — THEY DIE OF HEMORRHAGE, often within days, often before the diagnosis is confirmed. Her panel is DIC in full: fibrinogen 80 mg/dL, both times prolonged, platelets 22,000/mm3, D-dimer 18.4 µg/mL.\n\nThe genetics: t(15;17) producing the PML-RARA FUSION GENE.\n\nThe morphology in the stem is the other half of the recognition — heavily granular promyelocytes, some containing MULTIPLE Auer rods (described as resembling bundles of sticks). Note also that her white count is LOW at 2,400/mm3: A NORMAL OR LOW WHITE COUNT DOES NOT EXCLUDE ACUTE LEUKEMIA.\n\nAll-trans retinoic acid DOES NOT KILL THE CELLS — IT FORCES THE ARRESTED PROMYELOCYTES TO DIFFERENTIATE, the purest possible illustration of the core construct, and it carries 90% OVERALL SURVIVAL. THIS TRANSFORMS THE MOST RAPIDLY LETHAL LEUKEMIA INTO THE MOST CURABLE ONE — BUT ONLY IF IT IS RECOGNIZED.\n\nAggressive product support for the coagulopathy runs alongside it.",
  {"1": "Conventional '7 + 3' induction is the treatment for other subtypes of acute myeloid leukemia, and it will not address the differentiation block or the coagulopathy. Cytotoxic therapy in unrecognized promyelocytic leukemia can worsen the DIC by lysing granule-rich cells.",
   "2": "Rasburicase and fluids treat TUMOUR LYSIS SYNDROME, the other first-week emergency, which is metabolic rather than hemostatic. Her potassium, phosphate, calcium and uric acid are not the abnormality — her clotting screen is.",
   "3": "Waiting for cytogenetics is exactly the error the rule exists to prevent. Confirmation takes days, and fatal intracranial or pulmonary hemorrhage happens in that window.",
   "4": "Platelets and other products are genuinely needed and should be given aggressively alongside. Product support alone does not stop the process driving the consumption, and observing for 24 hours risks the bleed that kills these patients."},
  "Her leukemia cells are spilling clotting-activating material into her blood, using up every clotting protein until she bleeds everywhere. One drug forces those cells to grow up and stop — and it must be started on suspicion, not after the tests return.",
  exim="fig_apl_faggot",
  excap="Acute promyelocytic leukemia: heavy cytoplasmic granulation with multiple Auer rods resembling bundles of sticks.")

# ── 5. The grade paradox (§36) ────────────────────────────────────────────
q("A 63-year-old man is found to have stage IV follicular lymphoma with bone marrow involvement and painless generalized lymphadenopathy. He has no fever, no night sweats, and no weight loss, and his blood counts are normal. His oncologist explains that his disease is very unlikely to be cured, that a third of patients with it are never treated at all, and that he may be observed without therapy. He asks why a patient he met with a far more aggressive lymphoma is being treated with curative intent.\n\nWhich of the following best explains this apparent paradox?",
  ["A. Advanced stage at diagnosis precludes cure in any lymphoma type",
   "B. Chemotherapy kills dividing cells, and indolent cells rarely divide",
   "C. Indolent lymphomas are more likely to harbor drug resistance mutations",
   "D. Marrow involvement prevents the delivery of curative chemotherapy",
   "E. The absence of B symptoms indicates a lower response to therapy"],
  1,
  "In hematolymphoid neoplasms, GRADE IS ESSENTIALLY THE AGGRESSIVE/INDOLENT AXIS of the core construct — and it INVERTS THE USUAL INTUITION ABOUT WHAT A BAD DIAGNOSIS MEANS:\n\n• HIGH-GRADE / AGGRESSIVE disease kills in 3 TO 6 MONTHS UNTREATED — BUT IS TREATED WITH CURATIVE INTENT, BECAUSE RAPIDLY DIVIDING CELLS ARE EXACTLY WHAT CHEMOTHERAPY KILLS.\n• LOW-GRADE / INDOLENT disease is COMPATIBLE WITH DECADES OF LIFE — BUT IS NOT CURABLE BY STANDARD THERAPY, BECAUSE MOST CELLS ARE NEVER CYCLING WHEN THE DRUG IS PRESENT. A THIRD OF FOLLICULAR LYMPHOMA PATIENTS ARE NEVER TREATED AT ALL.\n\nStage behaves differently in each: ADVANCED STAGE DRIVES URGENCY IN AGGRESSIVE LYMPHOMA, WHILE INDOLENT LYMPHOMA IS USUALLY STAGE III/IV AT DIAGNOSIS AND THAT FACT ALONE CHANGES NOTHING. His stage IV disease with marrow involvement is the expected presentation, not a catastrophe.\n\nAnd molecular findings can outweigh clinical stage entirely — A DOUBLE HIT LYMPHOMA DOES WORSE THAN THE HIGHEST CLINICAL RISK SCORE.\n\nThe practical consequence for him is 'watch and wait': treatment is deferred until there is a reason — symptomatic bulk, cytopenias from marrow replacement, B symptoms, or organ compromise — because therapy given earlier does not prolong life and carries its own toxicity.",
  {"0": "Advanced stage does not preclude cure — most patients cured of diffuse large B-cell lymphoma or Hodgkin lymphoma present at stage III or IV. Stage drives urgency in aggressive disease rather than eliminating the possibility of cure.",
   "2": "Resistance mutations accumulate with treatment and matter in relapsed disease. The reason indolent lymphoma resists cure is kinetic — the cells are out of cycle — rather than a higher baseline mutation burden.",
   "3": "Marrow involvement is present in most patients with follicular lymphoma at diagnosis and does not obstruct drug delivery. Curative regimens are routinely given to patients with marrow disease in aggressive lymphomas.",
   "4": "Absence of B symptoms reflects low disease activity and is a favourable feature, not a predictor of poor response. B symptoms are a staging modifier rather than a measure of chemosensitivity."},
  "Chemotherapy kills cells while they are dividing. A fast cancer is dividing constantly, so the drug can wipe it out. A slow cancer sits still most of the time, so the drug never catches most of it — which is why the slower disease is the one you cannot cure.")

# ══════════════════ §37 · ACUTE MYELOID LEUKEMIA ══════════════════

# ── 6. What ATRA actually does (§37) ──────────────────────────────────────
q("A 38-year-old woman with newly diagnosed acute promyelocytic leukemia is started on all-trans retinoic acid. Over the following week her marrow promyelocytes are observed to acquire segmented nuclei and to lose their heavy granulation, and her white cell differential shifts toward mature forms before her counts normalize. Her fibrinogen rises and her bleeding stops.\n\nWhich of the following best describes the mechanism of this drug?",
  ["A. It cross-links DNA in rapidly dividing promyelocytes",
   "B. It inhibits the tyrosine kinase produced by the fusion gene",
   "C. It releases the maturation block imposed by PML-RARA",
   "D. It removes methylation silencing of differentiation genes",
   "E. It targets a surface antigen for antibody-mediated killing"],
  2,
  "ALL-TRANS RETINOIC ACID DOES NOT KILL THE CELLS — IT FORCES THE ARRESTED PROMYELOCYTES TO DIFFERENTIATE. The t(15;17) translocation fuses PML to the RETINOIC ACID RECEPTOR ALPHA gene, and the fusion protein binds retinoic acid response elements and holds the cell at the promyelocyte stage. Pharmacologic retinoic acid displaces that repression, and THE CELLS MATURE INTO CELLS THAT THEN DIE NATURALLY.\n\nWHY DIFFERENTIATION THERAPY IS THE PERFECT PROOF OF THE CORE CONSTRUCT: the central idea is that disease arises from ARRESTED DIFFERENTIATION. A DRUG THAT CURES A CANCER WITHOUT CONVENTIONAL CYTOTOXICITY IS ONLY CONCEIVABLE IF THE DISEASE WAS A MATURATION PROBLEM IN THE FIRST PLACE. Overall survival is 90%.\n\nThe visible consequence is exactly what the stem describes: the promyelocytes segment their nuclei and lose their granules — they become neutrophils. The coagulopathy resolves as the granule-rich cells that were driving it disappear by maturation rather than by lysis.\n\nOne complication belongs with the mechanism: DIFFERENTIATION SYNDROME, in which the maturing cells release cytokines and cause fever, hypoxemia, pulmonary infiltrates, weight gain and hypotension in the first days to weeks. It is treated with dexamethasone, and it happens BECAUSE the drug is working.\n\nArsenic trioxide is the usual partner agent, and the combination has largely replaced cytotoxic chemotherapy in this disease.",
  {"0": "DNA cross-linking is the mechanism of alkylating agents, which kill dividing cells indiscriminately. The stem describes cells MATURING rather than dying, which is incompatible with a cytotoxic mechanism.",
   "1": "Tyrosine kinase inhibition is the imatinib mechanism in chronic myeloid leukemia, where BCR-ABL encodes a constitutively active kinase. PML-RARA is a transcription factor fusion, not a kinase.",
   "3": "Removing methylation silencing describes the HYPOMETHYLATING AGENTS — azacitidine and decitabine — used in myelodysplastic syndrome and in unfit acute myeloid leukemia. Those act epigenetically rather than through a nuclear receptor.",
   "4": "Antibody-directed killing describes agents such as gemtuzumab ozogamicin, which targets CD33 and is used in acute myeloid leukemia. It kills the cell rather than maturing it."},
  "Her leukemia cells are stuck halfway through growing up. The drug does not poison them — it unsticks them, so they finish maturing into ordinary white cells and then die off naturally like normal cells do.",
  exim="fig_apl_faggot",
  excap="The arrested promyelocytes of acute promyelocytic leukemia — the cells the drug forces to mature.")

# ── 7. Flow cytometry assigns lineage (§37) ───────────────────────────────
q("A 61-year-old man is admitted with pancytopenia and 46% blasts on the peripheral blood smear. The blasts are medium to large with a high nuclear-to-cytoplasmic ratio, fine chromatin, and prominent nucleoli; occasional cells contain a single needle-shaped cytoplasmic inclusion. A bone marrow aspirate confirms 62% blasts.\n\nWhich of the following studies is required to assign the lineage of these cells?",
  ["A. Bone marrow reticulin staining",
   "B. Cytogenetic karyotype analysis",
   "C. Flow cytometry for surface antigens",
   "D. Fluorescence in situ hybridization",
   "E. Serum lactate dehydrogenase measurement"],
  2,
  "Diagnosis of acute myeloid leukemia requires a BONE MARROW BIOPSY AND ASPIRATE SHOWING MORE THAN 20% BLASTS, WITH MYELOID CELL SURFACE ANTIGENS ON FLOW CYTOMETRY. FLOW CYTOMETRY IS WHAT ASSIGNS LINEAGE — BLAST MORPHOLOGY ALONE WILL NOT.\n\nThat is the point worth carrying, because the stem is deliberately seductive: an Auer rod is a myeloid finding, and morphology suggests the answer. But a blast is a blast, myeloid and lymphoid blasts overlap substantially by eye, and the formal assignment is by immunophenotype — CD33 and CD13 for myeloid, TdT with CD10 and CD19 for precursor B, cytoplasmic CD3 for precursor T, CD41 and CD61 for megakaryocytic.\n\nHis 62% marrow blasts clear the >20% threshold, which is the line separating acute leukemia from myelodysplastic syndrome and from chronic myeloid leukemia in accelerated phase.\n\nThe other studies each have a role, but a different one. CYTOGENETIC AND MOLECULAR FINDINGS are prognostic — they stratify patients into high, intermediate and low risk, AND THAT STRATIFICATION DECIDES WHO GETS A TRANSPLANT. They do not establish lineage.\n\nThe risk factors for acute myeloid leukemia are worth noting alongside: PRIOR CYTOTOXIC CHEMOTHERAPY; A HISTORY OF MYELODYSPLASTIC SYNDROME OR A MYELOPROLIFERATIVE DISORDER; and DOWN SYNDROME. TWO OF THE THREE ARE IATROGENIC OR ANTECEDENT HEMATOLOGIC DISEASE — THIS IS OFTEN A SECOND CANCER.",
  {"0": "Reticulin staining grades marrow fibrosis and is central to diagnosing primary myelofibrosis. It says nothing about the lineage of a blast population.",
   "1": "Karyotyping identifies prognostically important abnormalities and decides transplant candidacy, so it is essential — but it is a risk-stratification tool. A normal karyotype occurs in a substantial minority and would leave lineage unassigned.",
   "3": "FISH detects specific known rearrangements such as PML-RARA rapidly, and is used precisely when promyelocytic leukemia is suspected. It interrogates named targets rather than establishing whether a blast is myeloid or lymphoid.",
   "4": "Lactate dehydrogenase reflects cell turnover and tumour burden and is raised in most acute leukemias and aggressive lymphomas. It is entirely non-specific."},
  "Under the microscope, immature leukemia cells from the two main lineages look almost identical. The test that sorts them shines a laser at each cell and reads the markers on its surface.",
  exim="fig_auer_rods",
  excap="Myeloblasts with an Auer rod. Morphology suggests myeloid lineage — flow cytometry proves it.")

# ── 8. Fitness, not age (§37) ─────────────────────────────────────────────
q("A 78-year-old man is diagnosed with acute myeloid leukemia. He has heart failure with an ejection fraction of 30%, stage 4 chronic kidney disease, and requires assistance with dressing and bathing. He spends more than half the day in a chair. His cytogenetics show an intermediate-risk karyotype.\n\nWhich of the following is the most appropriate treatment approach?",
  ["A. A hypomethylating agent with or without venetoclax",
   "B. Allogeneic stem cell transplantation after remission",
   "C. Cytarabine and daunorubicin induction as an inpatient",
   "D. High-dose cytarabine consolidation without induction",
   "E. Hydroxyurea alone for the duration of his illness"],
  0,
  "Treatment has TWO INTENTS, DECIDED BY FITNESS RATHER THAN BY AGE ALONE:\n\n• CURATIVE INTENT — YOUNGER / FIT. Induction with '7 + 3' (daunorubicin or idarubicin plus cytarabine), REQUIRING AT LEAST A 3 TO 4 WEEK HOSPITALIZATION; then consolidation; then ALLOGENEIC STEM CELL TRANSPLANT for intermediate or high risk disease.\n• PALLIATIVE INTENT — OLDER / UNFIT. A HYPOMETHYLATING AGENT — DECITABINE OR AZACITIDINE — WITH OR WITHOUT VENETOCLAX, plus supportive care: transfusions, antibiotics, hospice.\n\nTHE CHOICE BETWEEN COLUMNS TURNS ON WHETHER THE PATIENT CAN SURVIVE A MONTH OF MARROW APLASIA IN HOSPITAL, NOT SIMPLY ON A BIRTHDAY.\n\nHe cannot. An ejection fraction of 30% makes anthracycline exposure hazardous in its own right, stage 4 kidney disease limits cytarabine clearance, and a performance status in which he spends more than half the day in a chair with dependency for basic self-care predicts very poor tolerance of a month of aplasia.\n\nThe prognostic features that drive these decisions: AGE, PERFORMANCE STATUS, COMORBIDITIES, PRIOR CYTOTOXIC CHEMOTHERAPY OR RADIATION, ANTECEDENT MYELOID DISORDERS, and CYTOGENETIC AND MOLECULAR FINDINGS.\n\nNote what the palliative column is not: it is not 'no treatment'. Hypomethylating agents with venetoclax produce meaningful remission rates and are given with the intent of prolonging life and controlling disease.",
  {"1": "Transplantation is the consolidation strategy for intermediate or high risk disease in a FIT patient who has first achieved remission with induction. It carries substantial transplant-related mortality and is not offered to a patient of this performance status.",
   "2": "'7 + 3' is exactly the regimen his physiology cannot survive — it requires 3 to 4 weeks in hospital through profound aplasia, and the anthracycline is cardiotoxic in a man with an ejection fraction of 30%.",
   "3": "Consolidation follows induction and presupposes a remission to consolidate. High-dose cytarabine also carries cerebellar and ocular toxicity that rises sharply with age and renal impairment.",
   "4": "Hydroxyurea is CYTOREDUCTION, NOT CURE — it holds the count down while the workup proceeds. As sole therapy it does not alter the course of the disease, and effective lower-intensity options exist."},
  "The decision is not about his age but about whether he could survive a month in hospital with no working bone marrow. He could not — so he gets a gentler treatment that still works against the disease.")

# ── 9. Therapy-related myeloid neoplasm (§37) ─────────────────────────────
q("A 59-year-old woman is evaluated for fatigue and easy bruising. Six years ago she was treated for breast cancer with an anthracycline-containing regimen and an alkylating agent, followed by radiation. She has been in remission since. Her temperature is 37.0°C (98.6°F), pulse is 88/min, and blood pressure is 126/78 mm Hg. Physical examination shows pallor and scattered petechiae.\n\nLaboratory studies show:\nHemoglobin 8.6 g/dL (N=12.0–16.0 g/dL)\nHematocrit 26% (N=36%–46%)\nLeukocyte count 2,900/mm3 (N=4,500–11,000/mm3)\nPlatelet count 38,000/mm3 (N=150,000–400,000/mm3)\n\nBone marrow examination shows 34% blasts expressing CD33 and CD13, with a complex karyotype. Which of the following is the most likely explanation for this diagnosis?",
  ["A. A second malignancy caused by her previous cytotoxic therapy",
   "B. An inherited cancer predisposition syndrome of some kind",
   "C. Bone marrow metastasis from recurrent breast carcinoma",
   "D. Progression of an unrecognized lymphoproliferative disorder",
   "E. Radiation-induced aplastic anemia with later clonal evolution"],
  0,
  "The risk factors for acute myeloid leukemia are PRIOR CYTOTOXIC CHEMOTHERAPY; A HISTORY OF MYELODYSPLASTIC SYNDROME OR A MYELOPROLIFERATIVE DISORDER; and DOWN SYNDROME. TWO OF THE THREE ARE IATROGENIC OR ANTECEDENT HEMATOLOGIC DISEASE — THIS IS OFTEN A SECOND CANCER.\n\nHers is therapy-related acute myeloid leukemia. The features that identify it are all present: an interval of years after cytotoxic treatment for a first malignancy; ALKYLATING AGENT exposure, classically with a latency of 5 to 7 years and often preceded by a myelodysplastic phase; and a COMPLEX KARYOTYPE, which places her in the high-risk cytogenetic group.\n\nThat matters because PROGNOSTIC FEATURES include PRIOR CYTOTOXIC CHEMOTHERAPY OR RADIATION and ANTECEDENT MYELOID DISORDERS as well as cytogenetics — and CYTOGENETIC AND MOLECULAR FINDINGS STRATIFY PATIENTS INTO HIGH, INTERMEDIATE AND LOW RISK, WHICH DECIDES WHO GETS A TRANSPLANT. A complex karyotype predicts poor response to conventional induction and pushes toward transplantation in a fit patient.\n\nThe topoisomerase II inhibitors — anthracyclines and etoposide — produce the other pattern: a SHORTER latency of 1 to 3 years, no preceding myelodysplastic phase, and balanced translocations involving 11q23 (MLL/KMT2A).\n\nThe longer-term complications list closes the loop: relapse, graft-versus-host disease after transplant, and FOR SURVIVORS OF PRIOR CYTOTOXIC THERAPY, THERAPY-RELATED AML ITSELF AS A SECOND MALIGNANCY.",
  {"2": "Marrow metastasis from carcinoma produces a leukoerythroblastic picture with clumps of cohesive epithelial cells, and would express cytokeratin rather than CD33 and CD13. Her blasts are myeloid by immunophenotype.",
   "1": "An inherited predisposition — Li-Fraumeni, germline RUNX1 or CEBPA — is worth considering in a patient with two malignancies, particularly at a young age. Her exposure history supplies a sufficient acquired explanation, and the latency and complex karyotype fit it precisely.",
   "3": "A lymphoproliferative disorder would produce lymphoid rather than myeloid blasts, and would be CD19, CD20 or CD3 positive. Her cells carry myeloid antigens.",
   "4": "Aplastic anemia produces a HYPOcellular marrow with pancytopenia and no excess of blasts, and can evolve clonally over years. She has 34% blasts, which is acute leukemia by definition."},
  "The chemotherapy that cured her breast cancer six years ago damaged the DNA of her bone marrow cells too. One of those damaged cells has now become a leukemia — a second cancer caused by the treatment for the first.")

# ── 10. The 20% line (§37) ────────────────────────────────────────────────
q("A 74-year-old man has had macrocytic anemia and mild thrombocytopenia for 18 months, managed with intermittent transfusions. Serial bone marrow examinations have shown a hypercellular marrow with dysplastic changes in all three lineages and blast percentages of 6%, then 9%, then 14%. He now presents with fatigue and a new oral candidal infection, and a repeat marrow examination shows 26% blasts with myeloid surface antigens.\n\nWhich of the following best describes his current diagnosis?",
  ["A. Acute myeloid leukemia arising from myelodysplastic syndrome",
   "B. Aplastic anemia with clonal evolution over 18 months",
   "C. Chronic myeloid leukemia now entering accelerated phase",
   "D. Myelodysplastic syndrome with excess blasts, unchanged",
   "E. Primary myelofibrosis with a leukoerythroblastic blood picture"],
  0,
  "DIAGNOSIS OF ACUTE LEUKEMIA REQUIRES MORE THAN 20% BLASTS IN THE BONE MARROW OR THE PERIPHERAL BLOOD. EITHER COMPARTMENT SUFFICES. MEMORIZE THIS NUMBER — IT IS ALSO THE LINE THAT SEPARATES MYELODYSPLASTIC SYNDROME AND CHRONIC MYELOID LEUKEMIA BLAST PHASE FROM ACUTE LEUKEMIA.\n\nHe has crossed it. At 6%, 9% and 14% he had myelodysplastic syndrome with excess blasts; at 26% the same disease is now acute myeloid leukemia.\n\nThis is the commonest way the two sit on one continuum. MDS OCCUPIES THE MIDDLE BOX OF THE MAP: NOT UNDIFFERENTIATED LIKE ACUTE MYELOID LEUKEMIA, NOT NORMALLY DIFFERENTIATED LIKE THE MYELOPROLIFERATIVE NEOPLASMS, BUT ABNORMALLY DIFFERENTIATED. And 30% OF PATIENTS WITH MDS PROGRESS TO ACUTE MYELOID LEUKEMIA.\n\nIt also matters prognostically. A HISTORY OF MYELODYSPLASTIC SYNDROME is one of the three named risk factors for acute myeloid leukemia, and ANTECEDENT MYELOID DISORDERS are listed among the adverse prognostic features — AML arising from MDS responds less well to conventional induction than de novo disease.\n\nThe defining paradox of the MDS phase is worth restating: THE MARROW IS CELLULAR — OFTEN HYPERCELLULAR — YET THE PATIENT IS CYTOPENIC, BECAUSE THE CELLS BEING PRODUCED ARE STRUCTURALLY ABNORMAL AND DIE BEFORE THEY LEAVE, OR SHORTLY AFTER. PRODUCTION IS NOT REDUCED; IT IS WASTED.",
  {"1": "Aplastic anemia is a HYPOcellular marrow with pancytopenia and no dysplasia or excess blasts. His marrow has been hypercellular and dysplastic throughout.",
   "2": "Chronic myeloid leukemia is defined by t(9;22)/BCR-ABL and presents with neutrophilia, basophilia and splenomegaly rather than cytopenias. Its accelerated phase is 10% to 19% blasts — and at 26% it too would be blast phase.",
   "3": "This was the correct label at 6%, 9% and 14% blasts, which is why the trajectory is given. The 20% threshold is categorical, and at 26% the diagnosis changes.",
   "4": "Primary myelofibrosis shows marrow fibrosis with tear-drop cells, nucleated red cells and immature granulocytes in the blood, plus massive splenomegaly. His marrow is hypercellular and dysplastic rather than fibrotic."},
  "His marrow disease has been slowly worsening for a year and a half, with more and more immature cells each time. Once those immature cells pass one in five, the disease is renamed — it is now an acute leukemia.")

# ══════════════════ §38 · MDS AND CML ══════════════════

# ── 11. The MDS paradox (§38) ─────────────────────────────────────────────
q("A 74-year-old man is evaluated for 8 months of progressive fatigue. He has required two red cell transfusions in the past 3 months. He takes no medications, drinks no alcohol, and has no family history of blood disorders. Physical examination shows pallor and no organomegaly.\n\nLaboratory studies show:\nHemoglobin 8.1 g/dL (N=13.0–16.0 g/dL)\nHematocrit 25% (N=37%–49%)\nMean corpuscular volume 104 µm3 (N=80–100 µm3)\nReticulocyte count 0.6% (N=0.5%–1.5%)\nLeukocyte count 2,600/mm3 (N=4,500–11,000/mm3)\nAbsolute neutrophil count 1,100/µL (N=1,800–7,000/µL)\nPlatelet count 90,000/mm3 (N=150,000–400,000/mm3)\nSerum vitamin B12 480 pg/mL (N=200–900 pg/mL)\nSerum folate 12 ng/mL (N=>5.4 ng/mL)\n\nBone marrow examination shows a hypercellular marrow with dysplastic changes in all three lineages and 8% blasts. Which of the following best explains his cytopenias?",
  ["A. Consumption of mature cells in the peripheral circulation",
   "B. Fibrous replacement of the hematopoietic marrow space",
   "C. Ineffective production, with abnormal cells dying in the marrow",
   "D. Reduced marrow cellularity from progressive stem cell depletion",
   "E. Sequestration of circulating cells within an enlarged spleen"],
  2,
  "The defining paradox of myelodysplastic syndrome: THE MARROW IS CELLULAR — OFTEN HYPERCELLULAR — YET THE PATIENT IS CYTOPENIC, BECAUSE THE CELLS BEING PRODUCED ARE STRUCTURALLY ABNORMAL AND DIE BEFORE THEY LEAVE, OR SHORTLY AFTER. PRODUCTION IS NOT REDUCED; IT IS WASTED.\n\nHis numbers show it directly: three lineages down, a hypercellular dysplastic marrow, and a REticulocyte count of 0.6% against a hemoglobin of 8.1 g/dL — an inappropriately low response that identifies the problem as production rather than destruction.\n\nMDS OCCUPIES THE MIDDLE BOX OF THE MAP: NOT UNDIFFERENTIATED LIKE ACUTE MYELOID LEUKEMIA, NOT NORMALLY DIFFERENTIATED LIKE THE MYELOPROLIFERATIVE NEOPLASMS, BUT ABNORMALLY DIFFERENTIATED.\n\nThe rest of the disease in brief: ANEMIA IS USUALLY THE FIRST AND MOST PROMINENT cytopenia, and it is characteristically MACROCYTIC — which is why B12 and folate are checked and are normal here. The pathophysiology is EPIGENETIC, WHICH IS PRECISELY WHY HYPOMETHYLATING DRUGS ARE THE DISEASE-DIRECTED TREATMENT. Supportive care is transfusions, growth factors and antibiotics; disease-directed therapy is AZACITIDINE OR DECITABINE; and ALLOGENEIC STEM CELL TRANSPLANT IS THE ONLY CURATIVE OPTION.\n\nAt 8% blasts he remains MDS — MORE THAN 20% WOULD MAKE THIS ACUTE MYELOID LEUKEMIA — with a 30% LIFETIME RISK of that progression.",
  {"0": "Peripheral consumption — immune destruction, hypersplenism, microangiopathy — would drive a compensatory marrow response with a HIGH reticulocyte count. His is 0.6%, and his marrow shows dysplasia rather than hyperplasia of normal precursors.",
   "1": "Fibrous replacement is primary myelofibrosis, which produces tear-drop cells, nucleated red cells and immature granulocytes in the blood, with massive splenomegaly. His marrow is hypercellular, not fibrotic, and he has no organomegaly.",
   "3": "Reduced cellularity from stem cell depletion is aplastic anemia — a HYPOcellular marrow. His marrow is hypercellular, which is the whole paradox of this disease.",
   "4": "Splenic sequestration requires splenomegaly, and his examination shows none. It would also not explain dysplastic morphology or macrocytosis."},
  "His marrow is crowded with cells, yet his blood counts are low. The cells being built are faulty and die before they ever leave the factory — so production is not reduced, it is wasted.")

# ── 12. What actually kills in MDS (§38) ──────────────────────────────────
q("A 76-year-old woman with myelodysplastic syndrome diagnosed 2 years ago is seen for follow-up. She is transfusion dependent, receiving azacitidine, and her most recent marrow examination showed 9% blasts. She asks what is most likely to happen to her over the coming years, and specifically whether her disease will 'turn into leukemia.'\n\nWhich of the following is the most accurate statement about the outcome of this disease?",
  ["A. About half of patients die of bleeding or infection",
   "B. Most patients are cured by hypomethylating therapy",
   "C. Most patients die from progression to acute leukemia",
   "D. Most patients eventually develop marrow fibrosis",
   "E. Transfusion dependence itself is the usual cause of death"],
  0,
  "WHAT KILLS MOST PATIENTS WITH MYELODYSPLASTIC SYNDROME IS COUNTER-INTUITIVE: 50% DIE OF BLEEDING OR INFECTION — COMPLICATIONS OF THE CYTOPENIAS THEMSELVES. ONLY 30% DIE FROM PROGRESSION TO ACUTE MYELOID LEUKEMIA. THE FEARED OUTCOME, LEUKEMIC TRANSFORMATION, IS THE LESS COMMON ONE.\n\nThat reframes the conversation she is asking for. Her day-to-day risk is not from a future transformation but from the neutropenia and thrombocytopenia she has now — which is why supportive care (transfusions, growth factors, prompt treatment of infection) is not merely palliative but the intervention most likely to keep her alive.\n\nThe treatment tiers: SUPPORTIVE — transfusions, growth factors, antibiotics. DISEASE-DIRECTED — HYPOMETHYLATING DRUGS (azacitidine, decitabine), which work because THE PATHOPHYSIOLOGY IS EPIGENETIC: genes are silenced by methylation rather than deleted by mutation, and A HYPOMETHYLATING AGENT REMOVES THAT SILENCING AND LETS NORMAL DIFFERENTIATION RESUME. CURATIVE — ALLOGENEIC STEM CELL TRANSPLANT, THE ONLY ONE.\n\nThat same drug class is used for unfit acute myeloid leukemia, WHICH MAKES SENSE GIVEN THAT MDS AND AML ARE TWO POINTS ON ONE CONTINUUM SEPARATED BY THE 20% BLAST LINE.\n\nAt 76 with transfusion dependence she is unlikely to be a transplant candidate, so azacitidine plus supportive care is the realistic plan — and the honest answer to her question is that transformation is a real risk but not the most likely ending.",
  {"1": "Hypomethylating agents improve counts, reduce transfusion requirements and prolong survival, and they can produce remissions — but they are not curative. Allogeneic stem cell transplant is the only curative option.",
   "2": "This is the intuitive answer and the reason the question exists. Progression to acute myeloid leukemia occurs in about 30% of patients — a substantial minority, but not the leading cause of death.",
   "3": "Marrow fibrosis is the endpoint of primary myelofibrosis among the myeloproliferative neoplasms, and fibrosis can be seen in some MDS subtypes. It is not the usual course of this disease.",
   "4": "Transfusion dependence is a marker of disease severity and brings iron overload over years, requiring chelation. It is not itself the usual cause of death."},
  "People worry that this disease will turn into leukemia, and sometimes it does — but more often what harms them is what is already happening: too few white cells to fight infection and too few platelets to stop bleeding.")

# ── 13. CML versus a leukemoid reaction (§38) ─────────────────────────────
q("A 52-year-old man is found to have a leukocyte count of 96,000/mm3 on a routine preoperative blood count. He feels well and has had no fever, cough, or dysuria. He takes no medications and has had no recent illness or injury. His temperature is 36.8°C (98.2°F) and his examination shows a spleen palpable 8 cm below the left costal margin.\n\nLaboratory studies show:\nHemoglobin 12.4 g/dL (N=13.0–16.0 g/dL)\nHematocrit 38% (N=37%–49%)\nLeukocyte count 96,000/mm3 (N=4,500–11,000/mm3)\nBasophils 8% (N=0%–2%)\nEosinophils 6% (N=0%–7%)\nPlatelet count 640,000/mm3 (N=150,000–400,000/mm3)\nLeukocyte alkaline phosphatase score 12 (N=20–100)\n\nThe smear shows the whole myeloid series at all stages of maturation with 3% blasts, and no toxic granulation or Döhle bodies. Which of the following is the most appropriate diagnostic test?",
  ["A. Blood cultures and inflammatory markers",
   "B. Bone marrow reticulin staining",
   "C. Flow cytometry for lymphoid markers",
   "D. JAK2 V617F mutation analysis",
   "E. Testing for the BCR-ABL fusion gene"],
  4,
  "THE SINGLE MOST USEFUL MOVE IS TO SEND FOR BCR-ABL. EVERYTHING ELSE IS SUPPORTIVE; THE MOLECULAR RESULT IS DIAGNOSTIC.\n\nChronic myeloid leukemia is defined by three names for one event: t(9;22) — the translocation; BCR-ABL — the fusion gene and protein; THE PHILADELPHIA CHROMOSOME — the resulting derivative chromosome 22. The fusion protein is a CONSTITUTIVELY ACTIVE TYROSINE KINASE, PERMANENTLY SWITCHED ON, WHICH IS EXACTLY WHY A SMALL MOLECULE THAT BLOCKS ITS ACTIVE SITE WORKS SO WELL.\n\nHis presentation is typical: OFTEN ASYMPTOMATIC, FREQUENTLY FOUND ON A ROUTINE BLOOD COUNT, with NEUTROPHILIA, BASOPHILIA, EOSINOPHILIA AND THROMBOCYTOSIS — the whole myeloid series elevated — plus SPLENOMEGALY.\n\nThe discrimination from a leukemoid reaction, which also presents with a strikingly high neutrophil count:\n• MOLECULAR GENETICS — BCR-ABL POSITIVE in CML, negative in a reaction. The definitive test.\n• BASOPHILIA — PRESENT in CML, absent in a reaction. THE DISTINCTIVE FINDING; few other conditions raise basophils.\n• EOSINOPHILIA — present in CML.\n• UNDERLYING CAUSE — a clonal neoplasm with no trigger, versus a driving stimulus: severe infection, inflammation, tissue necrosis, corticosteroids.\n• SPLEEN — splenomegaly typical in CML, usually normal in a reaction.\n• SMEAR — whole myeloid series including blasts, versus mature neutrophils with TOXIC GRANULATION AND DÖHLE BODIES and a left shift without blasts.\n• LEUKOCYTE ALKALINE PHOSPHATASE — LOW in CML, HIGH in a reaction. His is 12.\n\nTreatment converted this disease: before tyrosine kinase inhibitors, median survival 2 TO 5 YEARS; after, 95% ALIVE AT 10 YEARS.",
  {"1": "Reticulin staining grades marrow fibrosis and is central to diagnosing primary myelofibrosis, which also causes splenomegaly. It would not identify the defining lesion of this disease.",
   "2": "Lymphoid flow cytometry is appropriate when the expanded population is lymphoid. His expansion is granulocytic across all maturation stages.",
   "3": "JAK2 V617F defines polycythemia vera, essential thrombocythemia and primary myelofibrosis, and his thrombocytosis and splenomegaly make it a fair thought. Basophilia with a LOW leukocyte alkaline phosphatase and a full myeloid left shift points at BCR-ABL, and JAK2 is characteristically negative in CML.",
   "0": "Cultures and inflammatory markers are the right move when a leukemoid reaction is suspected — but a reaction requires a driving stimulus, and he is asymptomatic with no infection, inflammation or tissue necrosis, no toxic granulation, and a low rather than high alkaline phosphatase score."},
  "A severe infection can push the white count this high, but it does not raise basophils, does not enlarge the spleen, and raises a particular enzyme score rather than lowering it. All three point away from a reaction and toward one specific leukemia — and one gene test proves it.")

# ── 14. Reading the phase criteria (§38) ──────────────────────────────────
q("A 47-year-old woman with chronic myeloid leukemia diagnosed 3 years ago has been taking imatinib. Over the past 2 months her spleen has enlarged despite therapy and her leukocyte count has risen. Repeat peripheral blood examination shows 24% basophils and 14% blasts, and cytogenetics show a new clonal abnormality in addition to t(9;22).\n\nWhich of the following best describes the phase of her disease?",
  ["A. Accelerated phase",
   "B. Blast phase",
   "C. Chronic phase with a leukemoid component",
   "D. Chronic phase with treatment failure",
   "E. Transformation to myelodysplastic syndrome"],
  0,
  "ACCELERATED PHASE. Her findings satisfy several of its criteria at once: PERSISTENT OR INCREASING SPLENOMEGALY UNRESPONSIVE TO THERAPY; a persistent or increasing white cell count unresponsive to therapy; AT LEAST 20% BASOPHILS IN THE PERIPHERAL BLOOD; 10% TO 19% BLASTS; and ANY NEW CLONAL CHROMOSOMAL ABNORMALITY ARISING DURING THERAPY.\n\nThe trap is built into the numbers: TWO NUMBERS, TWO MEANINGS — DO NOT CONFUSE THEM. In accelerated phase, 10% TO 19% BLASTS and AT LEAST 20% BASOPHILS ARE TWO SEPARATE CRITERIA THAT BOTH INVOLVE A NUMBER NEAR 20. BLASTS ABOVE 20% MEANS BLAST PHASE (ACUTE LEUKEMIA). BASOPHILS AT OR ABOVE 20% MEANS ACCELERATED PHASE. READ THE CELL TYPE BEFORE THE NUMBER.\n\nAt 14% blasts she has NOT crossed into blast phase, which requires MORE THAN 20% BLASTS in marrow or blood — the same 20% line that defines acute leukemia everywhere else in this block. The distinction matters because BLAST PHASE IS TREATED AS AN ACUTE LEUKEMIA.\n\nThe phases: CHRONIC PHASE is usually asymptomatic and 85% OF PATIENTS PRESENT THERE. ACCELERATED PHASE is defined by the criteria above. BLAST PHASE is more than 20% blasts.\n\nHer loss of response also demands mutation testing: the T315I GATEKEEPER MUTATION confers resistance to imatinib AND to the second-generation agents (nilotinib, dasatinib, bosutinib), and requires PONATINIB OR OMACETAXINE.",
  {"1": "Blast phase requires MORE THAN 20% BLASTS in the marrow or blood. Hers are 14% — it is the BASOPHILS that are 24%, and reading the number without the cell type is the error this question tests.",
   "3": "Treatment failure has occurred, but 'chronic phase' is no longer accurate once accelerated-phase criteria are met. She has at least three of them.",
   "2": "A leukemoid reaction is a reactive neutrophilia driven by infection, inflammation or tissue necrosis in a patient without a clonal neoplasm. She has an established BCR-ABL-positive leukemia.",
   "4": "Myelodysplastic syndrome is a separate entity defined by dysplastic, ineffective hematopoiesis with cytopenias. Chronic myeloid leukemia progresses to accelerated and then blast phase, not to MDS."},
  "Two of her numbers sit near twenty, and only one of them matters for the worst category. Her blasts are fourteen percent — under the line for the acute phase — while her basophils at twenty-four percent put her in the middle phase.")

# ── 15. The gatekeeper mutation (§38) ─────────────────────────────────────
q("A 44-year-old man with chronic myeloid leukemia achieved a complete molecular response on imatinib 2 years ago. Over the past 4 months his BCR-ABL transcript level has risen steadily and his leukocyte count has increased. He confirms he has taken the drug daily. Mutation analysis of the BCR-ABL kinase domain identifies a T315I substitution.\n\nWhich of the following is the most appropriate treatment?",
  ["A. Dasatinib",
   "B. Hydroxyurea with interferon alfa",
   "C. Imatinib at a doubled dose",
   "D. Nilotinib",
   "E. Ponatinib"],
  4,
  "T315I IS THE GATEKEEPER MUTATION CONFERRING RESISTANCE TO IMATINIB AND TO THE SECOND-GENERATION AGENTS — NILOTINIB, DASATINIB AND BOSUTINIB. SWITCHING WITHIN THOSE GENERATIONS WILL NOT HELP — IT REQUIRES THE SPECIFIC AGENTS ACTIVE AGAINST T315I: PONATINIB OR OMACETAXINE.\n\nThe structural reason the mutation is called a gatekeeper: threonine 315 sits at the entrance to the hydrophobic pocket of the kinase's ATP-binding site and forms a hydrogen bond with imatinib. Substituting isoleucine both removes that bond and adds a bulky side chain that blocks access — so the drug cannot enter the site it is designed to occupy. Ponatinib was engineered with a carbon-carbon triple bond to slip past that steric block.\n\nThe treatment tiers to hold: FIRST GENERATION — IMATINIB, THE DRUG THAT PROVED TARGETED THERAPY COULD WORK. SECOND GENERATION — NILOTINIB, DASATINIB, BOSUTINIB. RESISTANCE — PONATINIB OR OMACETAXINE for T315I. And TREATMENT-FREE REMISSION: SELECTED PATIENTS IN DEEP, SUSTAINED MOLECULAR RESPONSE CAN DISCONTINUE THERAPY UNDER MONITORING.\n\nThe first step in any loss of response is to confirm ADHERENCE, which the stem does explicitly — non-adherence is the commonest cause of a rising transcript, and mutation testing follows only once the drug is genuinely being taken.\n\nAnd the prognosis contrast worth memorizing: BEFORE TYROSINE KINASE INHIBITORS, MEDIAN SURVIVAL 2 TO 5 YEARS; AFTER, 95% ALIVE AT 10 YEARS.",
  {"0": "Dasatinib is a second-generation agent effective against most imatinib-resistant mutations — but not T315I, which is resistant across that entire generation.",
   "1": "Hydroxyurea controls the count without touching the driver, and interferon was the pre-imatinib standard. Both are a substantial step backwards when an agent active against this specific mutation exists.",
   "2": "Dose escalation helps with low-level resistance or suboptimal exposure. T315I is a structural block at the binding site, so more drug does not overcome it.",
   "3": "Nilotinib is also second generation and shares the same vulnerability. Choosing between second-generation agents is appropriate for other resistance mutations, not this one."},
  "His leukemia changed the shape of the doorway the drug uses to get in, and the newer versions of that drug use the same doorway. Only one agent is built to fit the changed shape.")

# ══════════════════ §39 · THE MYELOPROLIFERATIVE NEOPLASMS ══════════════════

# ── 16. Polycythemia vera (§39) ───────────────────────────────────────────
q("A 58-year-old man comes to the office because of intense generalized itching that begins within minutes of taking a hot shower, along with episodes of burning pain and redness in his hands and feet. He also reports headaches and a sensation of disequilibrium. He does not smoke and has no cardiopulmonary disease. His temperature is 36.9°C (98.4°F), pulse is 76/min, and blood pressure is 142/88 mm Hg. Physical examination shows facial plethora and a spleen palpable 3 cm below the left costal margin. Pulse oximetry on room air shows an oxygen saturation of 98%.\n\nLaboratory studies show:\nHemoglobin 19.4 g/dL (N=13.0–16.0 g/dL)\nHematocrit 58% (N=37%–49%)\nLeukocyte count 13,200/mm3 (N=4,500–11,000/mm3)\nPlatelet count 520,000/mm3 (N=150,000–400,000/mm3)\nSerum erythropoietin 2 mU/mL (N=4–24 mU/mL)\n\nWhich of the following is the most appropriate initial treatment?",
  ["A. Continuous supplemental oxygen therapy",
   "B. Hydroxyurea alone without other measures",
   "C. Phlebotomy to a hematocrit below 45%",
   "D. Ruxolitinib as first-line cytoreduction",
   "E. Therapeutic anticoagulation with warfarin"],
  2,
  "Polycythemia vera. The immediate treatment is PHLEBOTOMY TO A TARGET HEMATOCRIT: MEN BELOW 45, WOMEN BELOW 42 — plus low-dose aspirin, with hydroxyurea for higher-risk patients and RUXOLITINIB FOR REFRACTORY DISEASE.\n\nThe two characteristic symptoms are both present: AQUAGENIC PRURITUS — ITCHING AFTER A HOT SHOWER, HIGHLY CHARACTERISTIC — and ERYTHROMELALGIA — BURNING RED PAINFUL EXTREMITIES. His headaches and disequilibrium are HYPERVISCOSITY.\n\nThe erythropoietin of 2 mU/mL is the buried clue and settles the polycythemia split: in POLYCYTHEMIA VERA the marrow is autonomous, so erythropoietin is SUPPRESSED; in SECONDARY erythrocytosis — hypoxia, a tumour, exogenous testosterone — it is HIGH. His normal oxygen saturation excludes hypoxic drive as well.\n\nThe mechanism is the JAK2/STAT PATHWAY, which normally transmits growth-factor signals into the nucleus; a JAK2 mutation leaves it SIGNALLING CONTINUOUSLY, so the marrow behaves as though permanently told to produce — BUT THE CELLS IT MAKES ARE NORMAL, MATURE AND FUNCTIONAL. THAT IS WHY THESE PATIENTS ARE NOT INFECTED OR BLEEDING FROM FAILURE; THEY ARE CLOTTING FROM EXCESS.\n\nThrombosis risk factors: prior thrombosis, age over 60, white cells above 11,000, HEMATOCRIT ABOVE 45, platelets above 400,000 — he has four.\n\nTransformation: 10% to post-polycythemia vera myelofibrosis, 1% to acute myeloid leukemia.",
  {"0": "Oxygen treats hypoxia-driven SECONDARY erythrocytosis, where a high erythropoietin is an appropriate response to low oxygen delivery. His saturation is 98% and his erythropoietin is suppressed at 2 mU/mL.",
   "1": "Hydroxyurea is cytoreduction for higher-risk disease and is often added, particularly over age 60 or after a thrombosis. It works over weeks, whereas phlebotomy lowers a hematocrit of 58% immediately.",
   "3": "Ruxolitinib is a JAK inhibitor reserved for disease refractory to or intolerant of hydroxyurea, and it is the agent of choice in intermediate-2 and high risk myelofibrosis. It is not first-line here.",
   "4": "Anticoagulation is used when a thrombosis has occurred; the standard antithrombotic in uncomplicated polycythemia vera is low-dose ASPIRIN. Warfarin does not lower the red cell mass driving his hyperviscosity."},
  "His marrow is making far too many red cells, so his blood is thick and sludgy — hence the headaches, the burning hands and the itch after a hot shower. The fastest fix is to remove blood until the concentration drops.")

# ── 17. Ruxolitinib in myelofibrosis (§39) ────────────────────────────────
q("A 66-year-old woman with primary myelofibrosis has drenching night sweats, bone pain, a 9-kg weight loss, and early satiety from a spleen palpable 14 cm below the left costal margin. Her disease is classified as high risk. She is transfusion dependent.\n\nLaboratory studies show:\nHemoglobin 7.8 g/dL (N=12.0–16.0 g/dL)\nHematocrit 24% (N=36%–46%)\nLeukocyte count 3,100/mm3 (N=4,500–11,000/mm3)\nPlatelet count 62,000/mm3 (N=150,000–400,000/mm3)\n\nRuxolitinib is started. Which of the following outcomes should she be told to expect?",
  ["A. Cure of the underlying disease in most patients",
   "B. Improvement in symptoms and survival, but not in her counts",
   "C. Normalization of her blood counts within several weeks",
   "D. Prevention of any transformation to acute myeloid leukemia",
   "E. Resolution of the marrow fibrosis on repeat biopsy"],
  1,
  "RUXOLITINIB IS INDICATED FOR INTERMEDIATE-2 AND HIGH RISK DISEASE AND IMPROVES SYMPTOMS AND SURVIVAL, BUT DOES NOT IMPROVE THE CYTOPENIAS. THAT CAVEAT IS THE EXAMINABLE PART — and it is the honest thing to tell her before she starts, because her anemia and thrombocytopenia may even worsen on treatment.\n\nMyelofibrosis is THE MPN THAT ENDS IN MARROW FAILURE. Its presentation has two components: SYMPTOM BURDEN — bone pain, malaise, night sweats, weight loss, fevers, and THE SYMPTOM BURDEN ITSELF IS A TREATMENT INDICATION; and PANCYTOPENIA, AS THE MARROW IS REPLACED BY FIBROUS TISSUE IT STOPS PRODUCING. UNLIKE POLYCYTHEMIA VERA AND ESSENTIAL THROMBOCYTHEMIA, THIS DISEASE ENDS IN MARROW FAILURE.\n\nALLOGENEIC STEM CELL TRANSPLANT IS THE ONLY CURATIVE-INTENT TREATMENT, and in a 66-year-old with high-risk disease it is worth formally evaluating.\n\nThe three-disease hook: ALL JAK2-DRIVEN. PV — RED CELL EXCESS → PHLEBOTOMY. ET — PLATELET EXCESS → HYDROXYUREA. MF — MARROW FIBROSIS AND PANCYTOPENIA → RUXOLITINIB, WHICH HELPS SYMPTOMS AND SURVIVAL, NOT COUNTS. The first two are diseases of too many cells; the third is the one where the marrow finally gives out.\n\nWhat she will notice is real: the spleen shrinks, the night sweats and weight loss improve, and quality of life rises — which in a disease with this symptom burden is a substantial gain even without a change in her transfusion requirement.",
  {"0": "Cure is not achievable with ruxolitinib. Allogeneic stem cell transplant is the only curative-intent option, and it carries significant transplant-related mortality.",
   "2": "This is the expectation to correct before starting. Ruxolitinib does not improve the cytopenias, and anemia and thrombocytopenia are its principal dose-limiting toxicities.",
   "3": "Ruxolitinib has not been shown to prevent leukemic transformation, which remains a risk in myelofibrosis. Its benefits are symptomatic and survival-related.",
   "4": "Some reduction in marrow fibrosis has been reported with prolonged therapy, but reversal of fibrosis is not an expected outcome and is not what the drug is given for."},
  "The drug will make her feel substantially better — smaller spleen, fewer sweats, more appetite — and help her live longer. What it will not do is raise her blood counts, so she should expect to keep needing transfusions.")

# ── 18. Essential thrombocythemia risk stratification (§39) ───────────────
q("A 44-year-old woman is referred after two blood counts 6 months apart showed platelet counts of 890,000/mm3 and 940,000/mm3. She has no symptoms, no prior thrombosis, and no bleeding. Her ferritin is 160 ng/mL (N=20–250 ng/mL) and her C-reactive protein is 0.2 mg/dL (N=<1.0 mg/dL). Bone marrow examination shows increased large hyperlobated megakaryocytes without significant fibrosis, and JAK2 V617F is detected. Her hemoglobin and leukocyte count are normal, and her spleen is not palpable.\n\nWhich of the following determines her risk stratification?",
  ["A. Bone marrow megakaryocyte morphology on biopsy",
   "B. Degree of platelet count elevation",
   "C. Presence of the JAK2 V617F mutation",
   "D. Prior thrombosis and age over 60 years",
   "E. Spleen size and the overall symptom burden"],
  3,
  "Risk stratification in essential thrombocythemia rests on ONLY TWO FACTORS: A HISTORY OF THROMBOSIS AND AGE OVER 60. SIMPLE, AND WORTH MEMORIZING BECAUSE IT IS SO SHORT.\n\nShe has neither — she is 44 with no prior thrombotic event — so she is low risk, and the implication is that CYTOREDUCTION IS NOT AUTOMATIC. Treatment is HYDROXYUREA, and THE GOAL IS TO REDUCE THROMBOSIS RISK, NOT TO NORMALIZE A NUMBER FOR ITS OWN SAKE. A platelet count approaching a million in a low-risk asymptomatic patient is not by itself an indication to treat.\n\nNote what the vignette has excluded to make the diagnosis: iron deficiency (ferritin 160 ng/mL) and inflammation (C-reactive protein 0.2 mg/dL) are the common causes of a REACTIVE thrombocytosis, which is TEMPORARY — hers has persisted for 6 months. The JAK2 V617F mutation and the megakaryocyte morphology establish the clonal diagnosis.\n\nTRANSFORMATION: 4% LIFETIME RISK of transformation to myelofibrosis.\n\nAnd the shared danger of this family is worth restating: all three myeloproliferative neoplasms produce NORMALLY DIFFERENTIATED CELLS IN EXCESS, so THEIR SHARED CLINICAL DANGER IS THROMBOSIS, NOT MARROW FAILURE — until myelofibrosis, where the marrow finally gives out.",
  {"0": "Megakaryocyte morphology — large hyperlobated forms — is a DIAGNOSTIC criterion that helps separate essential thrombocythemia from reactive thrombocytosis and from prefibrotic myelofibrosis. It does not feature in risk stratification.",
   "1": "The absolute platelet count is a poor predictor of thrombosis, and extreme counts above 1,500,000/mm3 can paradoxically cause BLEEDING through acquired von Willebrand syndrome. Treating to a number rather than to risk is the specific error this stratification prevents.",
   "2": "JAK2 V617F is present in most patients and contributes to some contemporary scoring systems, and it is prognostically relevant. The two-factor scheme taught here uses prior thrombosis and age alone.",
   "4": "Splenomegaly and symptom burden drive treatment decisions in MYELOFIBROSIS, where the symptom burden itself is a treatment indication. Essential thrombocythemia is stratified by thrombotic risk."},
  "Only two things decide how risky her disease is: whether she has already had a clot, and whether she is over sixty. She is neither — so the very high platelet number by itself does not mean she needs treatment.")

# ── 19. The polycythemia split (§39) ──────────────────────────────────────
q("A 46-year-old man who works as a long-haul truck driver is found to have an elevated hemoglobin on a routine examination. He reports loud snoring, witnessed apneas, and daytime somnolence. He smokes one pack of cigarettes daily. He has no pruritus, no burning in the extremities, and no headaches. His BMI is 41 kg/m2. Physical examination shows no splenomegaly and no plethora.\n\nLaboratory studies show:\nHemoglobin 18.9 g/dL (N=13.0–16.0 g/dL)\nHematocrit 56% (N=37%–49%)\nLeukocyte count 8,400/mm3 (N=4,500–11,000/mm3)\nPlatelet count 232,000/mm3 (N=150,000–400,000/mm3)\nSerum erythropoietin 31 mU/mL (N=4–24 mU/mL)\n\nWhich of the following is the most likely explanation for his erythrocytosis?",
  ["A. A JAK2-mutated myeloproliferative neoplasm",
   "B. An erythropoietin-secreting renal cell carcinoma",
   "C. Hypoxia-driven erythropoietin production",
   "D. Relative erythrocytosis from plasma volume contraction",
   "E. Surreptitious use of exogenous testosterone"],
  2,
  "THE ERYTHROPOIETIN DIRECTION IS THE ITEM. In POLYCYTHEMIA VERA the marrow is autonomous and erythropoietin is SUPPRESSED; in SECONDARY erythrocytosis the drive is external and erythropoietin is HIGH. His is 31 mU/mL — raised — so the marrow is responding appropriately to a signal rather than ignoring the absence of one.\n\nThe signal here is HYPOXIA: obstructive sleep apnea, with loud snoring, witnessed apneas, daytime somnolence and a BMI of 41 kg/m2, compounded by smoking, which also raises carboxyhemoglobin and reduces effective oxygen delivery.\n\nThe features that argue against polycythemia vera are all present as negatives: NO AQUAGENIC PRURITUS, NO ERYTHROMELALGIA, NO HEADACHES from hyperviscosity, NO SPLENOMEGALY, and NO elevation of the OTHER two lineages — his white cell and platelet counts are normal, whereas polycythemia vera typically raises all three.\n\nTreatment follows the cause: treat the sleep apnea with continuous positive airway pressure, stop smoking, and the erythrocytosis resolves. Phlebotomy to a hematocrit below 45 is the treatment for polycythemia vera, not for an appropriate physiologic response — removing red cells that the body is deliberately making to compensate for hypoxia is treating the number rather than the patient, though it is occasionally done for severe symptomatic hyperviscosity.\n\nThe framework: ABSOLUTE VERSUS RELATIVE erythrocytosis first, and within absolute, a LOW erythropoietin (polycythemia vera) versus a HIGH one (hypoxia, tumour, exogenous).",
  {"1": "An erythropoietin-secreting tumour — renal cell carcinoma, hepatocellular carcinoma, cerebellar hemangioblastoma, uterine leiomyoma — also raises erythropoietin, so the direction fits. There is no mass, no hematuria and no weight loss, and a far more parsimonious hypoxic explanation is in the stem.",
   "0": "Polycythemia vera would SUPPRESS erythropoietin, and typically raises the white cell and platelet counts as well, with splenomegaly, aquagenic pruritus or erythromelalgia. All of those are explicitly absent.",
   "3": "Relative erythrocytosis from plasma contraction — dehydration, diuretics, the historical Gaisböck syndrome — raises the hematocrit without raising the red cell mass, and would not raise erythropoietin. It is worth considering in an obese hypertensive man, but his erythropoietin is high.",
   "4": "Exogenous testosterone is a common and often concealed cause of erythrocytosis and would need to be asked about directly. It typically SUPPRESSES endogenous erythropoietin, and nothing in the stem suggests it."},
  "His body is short of oxygen every night because his airway closes, so his kidneys pump out the hormone that tells the marrow to make more red cells. The marrow is obeying orders — unlike the cancer version, where it makes red cells with no orders at all.")

# ── 20. One pathway, three diseases (§39) ─────────────────────────────────
q("A hematology fellow is asked to explain why polycythemia vera, essential thrombocythemia, and primary myelofibrosis are grouped together, and why patients with these diseases characteristically present with thrombosis rather than with infection or bleeding. All three are driven by mutations activating the same intracellular signalling pathway.\n\nWhich of the following best explains the thrombotic tendency of this group of diseases?",
  ["A. The circulating cells are normally differentiated and functional",
   "B. The mutated kinase directly activates the coagulation cascade",
   "C. These diseases consume protein C and protein S in the marrow",
   "D. They produce blasts that occlude the microvasculature widely",
   "E. Uncontrolled complement activation damages the endothelial lining"],
  0,
  "The JAK2/STAT PATHWAY normally transmits growth-factor signals into the nucleus. A JAK2 mutation leaves it SIGNALLING CONTINUOUSLY, so the marrow behaves as though it is being permanently told to produce — BUT THE CELLS IT MAKES ARE NORMAL, MATURE AND FUNCTIONAL.\n\nTHAT IS WHY THESE PATIENTS ARE NOT INFECTED OR BLEEDING FROM FAILURE; THEY ARE CLOTTING FROM EXCESS.\n\nThis is the core construct applied to one family: the myeloproliferative neoplasms sit at the INDOLENT, NORMALLY DIFFERENTIATED end of the myeloid row, opposite acute myeloid leukemia at the undifferentiated end, with myelodysplastic syndrome — ABNORMALLY differentiated — in between. Three boxes, three phenotypes: too few working cells; faulty cells; too many working cells.\n\nIt also explains a workup rule from the thrombosis section: JAK2 TESTING APPEARS IN THE THROMBOPHILIA WORKUP FOR SPLANCHNIC VEIN THROMBOSIS — AN UNEXPLAINED PORTAL OR MESENTERIC VEIN CLOT CAN BE THE FIRST SIGN OF ONE OF THESE DISEASES, sometimes before the counts are obviously abnormal.\n\nAnd the clinical warning that follows: 35-YEAR-OLDS WHO NEVER SEE A DOCTOR AND PRESENT WITH A HEART ATTACK, because they have this disease. A MYOCARDIAL INFARCTION OR STROKE IN A YOUNG PERSON WITH A HIGH HEMATOCRIT OR PLATELET COUNT SHOULD PROMPT THOUGHT ABOUT A MYELOPROLIFERATIVE NEOPLASM. THESE ARE AMONG THE FEW HEMATOLOGIC CONDITIONS CAUSING ARTERIAL AS WELL AS VENOUS THROMBOSIS.\n\nAll three can transform into one another or into acute leukemia.",
  {"1": "JAK2 is an intracellular tyrosine kinase acting on cytokine receptor signalling; it has no direct access to plasma clotting factors. The thrombotic risk comes from the cells the pathway overproduces.",
   "2": "Protein C and protein S are synthesized in the liver and are not consumed by marrow activity. Their deficiency is a separate group of thrombophilias.",
   "3": "Blasts are the hallmark of ACUTE leukemia and, at high counts, cause leukostasis. The myeloproliferative neoplasms are defined by the absence of a differentiation block — that is what places them at the opposite end of the map.",
   "4": "Uncontrolled complement activation is the mechanism of atypical hemolytic uremic syndrome and, in a different form, of paroxysmal nocturnal hemoglobinuria. It has no role in the myeloproliferative neoplasms."},
  "In these diseases the marrow is stuck in the 'on' position, but the cells it churns out are perfectly normal and work fine. Too many working cells means sludgy blood and clots — not infections or bleeding, which come from having too few.")
