# Jeevs Edition — Batch 07: Hemostasis Pharmacology
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §15 s14-anticoag     — heparins, DTIs, warfarin, DOACs, the reversal bench (LO 8, 12, 26, 48, 69)
#   §16 s15-antiplatelet — antiplatelets and fibrinolytics                     (LO 12, 62, 69, 71)
# Explanation figures are largely the course's own lecture slides from summative/assets/.
# Options alphabetised; "correct" is the 0-based index AFTER alphabetisation.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ── 1. Chain length decides everything (§15) ──────────────────────────────────
q("A 68-year-old man is treated with fondaparinux for an acute pulmonary embolism. On the second hospital day he has had no bleeding and his clot burden is improving. His temperature is 37.0°C (98.6°F), pulse is 88/min, and blood pressure is 124/76 mm Hg.\n\nLaboratory studies show:\nHemoglobin 13.8 g/dL (N=13.5–17.5 g/dL)\nHematocrit 41% (N=41%–53%)\nPlatelet count 232,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 12.8 seconds (N=11–15 seconds)\nPartial thromboplastin time 33 seconds (N=25–40 seconds)\nAnti-factor Xa activity 0.9 IU/mL (N=<0.1 IU/mL in an untreated patient)\n\nWhich of the following best explains why this patient's partial thromboplastin time is normal despite therapeutic anticoagulation?",
  ["A. Accelerated antithrombin inhibition of factor Xa without inhibition of thrombin",
   "B. Direct binding to the active site of thrombin",
   "C. Inhibition of the vitamin K epoxide reductase complex",
   "D. Irreversible acetylation of platelet cyclooxygenase-1",
   "E. Reduced hepatic synthesis of factors II, VII, IX, and X"],
  0,
  "All three indirect inhibitors work the same way — they bind antithrombin and change its shape, turning a slow natural brake into a fast one. None of them touches a clotting factor directly. What differs is which factors the accelerated antithrombin can still REACH, and that is decided by chain length:\n\n• Unfractionated heparin is long enough to wrap around both thrombin (IIa) and factor Xa → inhibits both → prolongs the aPTT.\n• Low-molecular-weight heparin is too short to bridge to thrombin → mostly anti-Xa → little aPTT effect.\n• Fondaparinux is the minimal 5-sugar (pentasaccharide) sequence → pure anti-Xa, no thrombin effect at all → the aPTT stays normal.\n\nThe aPTT is a thrombin-dependent test, so a drug that never inhibits thrombin does not prolong it. That is why fondaparinux is monitored — when monitoring is needed — with an anti-Xa level, which here is clearly therapeutic at 0.9 IU/mL.\n\nThe same chain-length logic predicts reversal: protamine binds the long heparin chain fully, the shorter LMWH chain only partially (~60%), and fondaparinux not at all — which is its real clinical limitation. It also predicts HIT risk: fondaparinux does not bind platelet factor 4, so it does not cause HIT and can be used to treat it.",
  {"1": "Direct thrombin binding is the mechanism of argatroban, bivalirudin and dabigatran. Those drugs inhibit thrombin itself and therefore DO prolong the aPTT — argatroban also prolongs the INR, which complicates warfarin transitions.",
   "2": "Inhibition of vitamin K epoxide reductase is warfarin's mechanism. It depletes factors II, VII, IX and X over days and is monitored by the INR, not the aPTT — and it is an oral drug, not a parenteral one.",
   "3": "Irreversible acetylation of cyclooxygenase-1 is aspirin. Antiplatelet drugs do not change either the aPTT or the prothrombin time, because those tests measure the plasma coagulation cascade rather than platelet function.",
   "4": "Reduced hepatic synthesis of the vitamin K-dependent factors is the downstream consequence of warfarin, or of liver failure. It would prolong the prothrombin time first — factor VII has the shortest half-life — and his prothrombin time is normal."},
  "Think of antithrombin as a hand and the drug as the rope tying it to a target. A long rope reaches both thrombin and factor Xa; this drug is the shortest possible rope and only reaches factor Xa — and the aPTT test only notices when thrombin is blocked.",
  exim="fig_heparin_mech_uw",
  excap="Chain length and target: unfractionated heparin bridges antithrombin to both thrombin and factor Xa, while the shorter agents reach factor Xa alone.")

# ── 2. Heparin-induced thrombocytopenia (§15) ─────────────────────────────────
q("A 64-year-old man is on the seventh day of unfractionated heparin after a total knee arthroplasty. He now reports pain and numbness in his right foot. He has had no bleeding, no melena, and no hematuria. His temperature is 37.1°C (98.8°F), pulse is 96/min, and blood pressure is 138/82 mm Hg. Physical examination shows a cool, pale right foot with absent dorsalis pedis and posterior tibial pulses; there are no petechiae and no bruising.\n\nLaboratory studies show:\nHemoglobin 11.9 g/dL (N=13.5–17.5 g/dL)\nHematocrit 36% (N=41%–53%)\nPlatelet count 84,000/mm3 (N=150,000–400,000/mm3)\nPartial thromboplastin time 68 seconds (N=25–40 seconds)\nProthrombin time 13.1 seconds (N=11–15 seconds)\nFibrinogen 386 mg/dL (N=200–400 mg/dL)\n\nHis platelet count was 246,000/mm3 on admission. A peripheral blood smear shows reduced platelets with no schistocytes. Which of the following is the most appropriate next step in management?",
  ["A. Continue heparin and transfuse platelets",
   "B. Discontinue heparin and begin argatroban",
   "C. Discontinue heparin and begin enoxaparin",
   "D. Discontinue heparin and begin warfarin",
   "E. Discontinue heparin and observe"],
  1,
  "This is heparin-induced thrombocytopenia, and the single most important thing to understand is that it is a CLOTTING emergency, not a bleeding one.\n\nAntibodies form against the heparin–platelet factor 4 complex, and those antibodies then ACTIVATE platelets. So the falling count is a by-product of consumption by activation, and the danger is thrombosis — here a limb-threatening arterial event. He has no bleeding at all.\n\nThe features that fit: a fall on day 7 (the window is 5 to 10 days, sooner with recent prior exposure), a drop of more than 50% from baseline (246,000 → 84,000), a new thrombosis, and a normal fibrinogen with no schistocytes, which excludes disseminated intravascular coagulation and the microangiopathies.\n\nManagement has two halves and both are required. STOP all heparin — including flushes, heparin-coated catheters, and low-molecular-weight heparin, which cross-reacts. Then START a non-heparin anticoagulant immediately: argatroban, bivalirudin or fondaparinux. Simply stopping heparin is not enough, because the antibody-driven prothrombotic state continues for days to weeks.\n\nArgatroban is hepatically cleared, which makes it the choice when kidney function is poor; it prolongs the INR, which complicates the later transition to warfarin.",
  {"0": "Continuing heparin sustains the antibody-driven platelet activation that is occluding his arteries. Transfusing platelets adds fuel — more substrate for activation — and is avoided unless there is serious bleeding, which he does not have. This option gets the mechanism exactly backwards.",
   "2": "Enoxaparin is a heparin. The antibodies cross-react with low-molecular-weight heparin, so switching within the class continues the disease. It would be the answer only if the problem were an isolated bleeding risk from unfractionated heparin, which it is not.",
   "3": "Warfarin alone in acute HIT is dangerous and is the classic trap: it depletes protein C — half-life about 8 hours — before it depletes factors II, IX and X, deepening the prothrombotic state and precipitating venous limb gangrene. Warfarin is started only after the platelet count recovers, overlapping with a non-heparin anticoagulant.",
   "4": "Stopping heparin is necessary but not sufficient. The antibodies and the hypercoagulable state persist for days to weeks, and thrombosis occurs in up to half of patients managed by withdrawal alone. He already has an occluded artery."},
  "The drug meant to stop clots has triggered antibodies that switch platelets ON. His platelet count is dropping because they are being used up clotting — so you stop the heparin and immediately start a completely different kind of blood thinner.",
  exim="fig_slide_hit",
  excap="Lecture slide: antibodies form against the heparin–platelet factor 4 complex and then activate platelets, producing thrombosis despite a falling platelet count.")

# ── 3. Why warfarin alone is dangerous in HIT (§15) ───────────────────────────
q("A 58-year-old woman with heparin-induced thrombocytopenia and a new deep vein thrombosis is treated with argatroban. Her platelet count, which fell to 62,000/mm3, has risen over 4 days to 118,000/mm3. The overnight resident proposes stopping the argatroban and starting warfarin alone, so that she can be discharged on an oral agent in the morning. Her temperature is 37.0°C (98.6°F), pulse is 82/min, and blood pressure is 126/78 mm Hg.\n\nWhich of the following best explains why starting warfarin alone at this point is hazardous?",
  ["A. Depletion of protein C before depletion of the procoagulant factors",
   "B. Direct inhibition of antithrombin activity by warfarin",
   "C. Increased platelet activation caused by warfarin metabolites",
   "D. Inhibition of fibrinolysis by warfarin",
   "E. Potentiation of heparin–platelet factor 4 antibody formation by warfarin"],
  0,
  "Warfarin blocks vitamin K epoxide reductase, so the liver cannot finish ANY vitamin K-dependent protein — and that list includes the two natural anticoagulants, protein C and protein S, not only factors II, VII, IX and X.\n\nThe half-lives decide what happens first. Protein C has a half-life of about 8 hours, while factor II (prothrombin) is around 60 hours. So in the first days of warfarin the body loses its brake before it loses its accelerator → a transient HYPERcoagulable window.\n\nIn an ordinary patient that window is managed by bridging with a heparin. In acute HIT the patient is already in an intensely prothrombotic state driven by antibody-mediated platelet activation, so adding a protein C deficit on top can precipitate venous limb gangrene — a catastrophic, sometimes amputation-requiring complication that is specifically described with warfarin monotherapy in HIT.\n\nThe rules that follow: do not start warfarin until the platelet count has substantially recovered (usually above 150,000/mm3), always overlap it with a non-heparin anticoagulant for at least 5 days and until the INR is therapeutic, and remember that argatroban itself raises the INR, so the transition target must be adjusted.\n\nThe same protein C mechanism explains warfarin-induced skin necrosis in patients with underlying protein C deficiency.",
  {"1": "Warfarin does not touch antithrombin — that is the target the heparins work THROUGH. Warfarin acts upstream, on the vitamin K-dependent gamma-carboxylation of factors in the liver, and antithrombin activity is unchanged.",
   "2": "Warfarin has no direct effect on platelets and no metabolite that activates them. The platelet activation in this patient comes from the heparin–platelet factor 4 antibodies, which are already present and which warfarin neither creates nor removes.",
   "3": "Warfarin does not inhibit fibrinolysis. That mechanism belongs to tranexamic acid and aminocaproic acid, which block the conversion of plasminogen to plasmin and are used to REVERSE thrombolytic therapy.",
   "4": "Warfarin does not promote antibody formation; the antibodies arose from heparin exposure and decline over weeks regardless of what oral agent follows. The hazard is hemodynamic and biochemical, not immunologic."},
  "Warfarin switches off four clotting proteins and two natural blood-thinning proteins at once — and one of the blood thinners disappears first. For a few days the patient is more likely to clot, which is the last thing someone with this condition needs.",
  exim="fig_slide_hit_mgmt",
  excap="Lecture slide on HIT management: stop all heparin, start a non-heparin anticoagulant, and do not start warfarin until the platelet count has recovered.")

# ── 4. Why the bridge continues (§15) ─────────────────────────────────────────
q("A 54-year-old man is admitted with an acute proximal deep vein thrombosis and begins treatment with enoxaparin and warfarin on the same day. On hospital day 2 he feels well and has had no bleeding. His temperature is 36.9°C (98.4°F), pulse is 76/min, and blood pressure is 122/74 mm Hg.\n\nLaboratory studies on day 2 show:\nHemoglobin 14.1 g/dL (N=13.5–17.5 g/dL)\nHematocrit 42% (N=41%–53%)\nPlatelet count 244,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 26 seconds (N=11–15 seconds)\nInternational normalized ratio 2.4 (N=0.8–1.2)\n\nThe intern proposes stopping the enoxaparin now that the international normalized ratio is therapeutic. Which of the following best explains why the enoxaparin should be continued?",
  ["A. Enoxaparin prevents the formation of antibodies against platelet factor 4",
   "B. Factor II activity remains nearly normal because of its long half-life",
   "C. Factor VII activity is unaffected during the first week of warfarin therapy",
   "D. The international normalized ratio is insensitive to changes in factor VII",
   "E. Warfarin requires 24 hours to reach peak plasma concentration"],
  1,
  "Warfarin does not touch factors that are already circulating. It only prevents the liver from making new functional ones, so anticoagulation arrives at the pace at which the EXISTING factors decay — and they decay at very different rates.\n\nFrom the lecture's own numbers: factor VII 4–6 hours, protein C 8 hours, factor IX 24 hours, protein S 30 hours, factor X 48–72 hours, factor II (prothrombin) 60 hours.\n\nThe international normalized ratio is derived from the prothrombin time, which is dominated by factor VII — the factor with the shortest half-life. So the INR moves FIRST and moves fast, while factor II is still almost fully present. A therapeutic-looking INR of 2.4 on day 2 reflects the disappearance of factor VII, not genuine antithrombotic protection. Stop the heparin now and he is effectively unanticoagulated against a fresh proximal clot.\n\nThe second reason is the same protein C problem: its 8-hour half-life means the natural anticoagulant is lost before the procoagulants, creating a transient hypercoagulable window in the first days.\n\nBoth problems have one fix: overlap with a heparin for at least 5 days AND until the INR has been therapeutic for 24 hours.",
  {"0": "Enoxaparin does not prevent anti-platelet factor 4 antibodies — it can cause them, since HIT occurs with low-molecular-weight heparin too, only less often than with unfractionated heparin. That is an argument for limiting exposure, not for continuing it.",
   "2": "Factor VII is the factor most affected in the first days, not the one spared — its 4 to 6 hour half-life is precisely why the INR rises so quickly. This option inverts the mechanism that makes the early INR misleading.",
   "3": "The INR is highly SENSITIVE to factor VII; that sensitivity is the whole problem. If the INR tracked factor II instead, a value of 2.4 would mean he was genuinely anticoagulated and the bridge could stop.",
   "4": "Warfarin is absorbed rapidly and does reach peak plasma concentration within hours — but its plasma level is irrelevant to its effect. The delay is entirely downstream, in the decay of clotting factors already in the circulation."},
  "Warfarin does not remove the clotting proteins already floating around; it just stops new ones being made, and they fade at different speeds. The test goes therapeutic early because the fastest-fading protein drives it, while the slow one is still fully there.",
  exim="fig_slide_warf_onset",
  excap="Lecture slide: the clotting factor half-lives that set warfarin's onset — factor VII 4–6 hours against factor II at 60 hours, with protein C at 8 hours creating the transient hypercoagulable state.")

# ── 5. Warfarin-induced skin necrosis (§15) ───────────────────────────────────
q("A 47-year-old woman began warfarin 4 days ago for an acute deep vein thrombosis; no parenteral anticoagulant was given at the same time. She now has a painful, dark, rapidly enlarging lesion on the lateral thigh, which began 24 hours ago as a red patch and has become firm and black at the center. Her mother had a deep vein thrombosis at age 30. Her temperature is 37.3°C (99.1°F), pulse is 92/min, and blood pressure is 128/78 mm Hg.\n\nLaboratory studies show:\nHemoglobin 13.0 g/dL (N=12.0–16.0 g/dL)\nHematocrit 39% (N=36%–46%)\nPlatelet count 254,000/mm3 (N=150,000–400,000/mm3)\nInternational normalized ratio 2.8 (N=0.8–1.2)\nPartial thromboplastin time 34 seconds (N=25–40 seconds)\nFibrinogen 340 mg/dL (N=200–400 mg/dL)\n\nBlood cultures are sterile and a skin biopsy specimen shows fibrin thrombi occluding dermal venules without vasculitis. A photograph of the lesion is shown. Which of the following best explains this complication?",
  ["A. Antibody directed against the heparin–platelet factor 4 complex",
   "B. Deficiency of protein C, whose activity falls faster than that of the procoagulant factors",
   "C. Direct cytotoxicity of warfarin to dermal capillary endothelium",
   "D. Embolization of cholesterol crystals into dermal arterioles",
   "E. Immune complex-mediated vasculitis induced by warfarin"],
  1,
  "Warfarin-induced skin necrosis, and the mechanism is the protein C paradox in its purest form.\n\nWarfarin blocks the vitamin K-dependent carboxylation of factors II, VII, IX and X AND of proteins C and S. Protein C has a half-life of about 8 hours, far shorter than factor II at 60 hours, so in the first days its activity collapses while prothrombin is still largely intact → a transient hypercoagulable state → thrombosis in dermal venules, infarction of the overlying skin, and the well-demarcated black eschar described here.\n\nThe patients who develop it are those with an underlying heterozygous protein C (or protein S) deficiency, in whom the baseline is already low — hinted at here by her mother's deep vein thrombosis at 30. The lesions appear on fatty areas — breast, buttock, thigh, abdomen — within 3 to 10 days of starting the drug, and the biopsy shows bland fibrin thrombi WITHOUT vasculitis, exactly as reported.\n\nThe preventable error is in the history: warfarin was started without a parenteral bridge. Bridging with a heparin covers the hypercoagulable window.\n\nManagement: stop warfarin, give vitamin K, anticoagulate with a heparin, and consider protein C concentrate in severe cases; wound care and sometimes surgical debridement follow.",
  {"0": "Antibodies to the heparin–platelet factor 4 complex cause HIT, which produces thrombosis with a platelet count that falls by more than half, typically 5 to 10 days into heparin exposure. She received no heparin at all, and her platelet count is 254,000/mm3.",
   "2": "Warfarin has no direct toxic effect on endothelium. If it did, skin necrosis would be dose related and would occur in everyone rather than in the small subgroup with an underlying natural anticoagulant deficiency, and it would not be prevented by bridging.",
   "3": "Cholesterol embolization causes livedo reticularis, blue toes and eosinophilia, and follows arterial instrumentation or thrombolysis — not the initiation of an oral drug. The biopsy would show cholesterol clefts within arterioles rather than bland fibrin thrombi.",
   "4": "A drug-induced vasculitis would show inflammatory infiltration and destruction of the vessel wall on biopsy, usually with palpable purpura. The biopsy here explicitly shows thrombi WITHOUT vasculitis, which is the finding that separates the two."},
  "Warfarin switches off the body's natural blood thinner faster than it switches off the clotting proteins. For a few days she was more likely to clot, and tiny clots blocked the small veins in her skin and killed the tissue above them.",
  image="fig_warfarin_necrosis",
  imcap="Photograph of the lateral thigh. There is a well-demarcated area of black, necrotic tissue with a friable, hyperemic border and surrounding erythema.",
  exim="fig_slide_vitk",
  excap="Lecture slide: warfarin inhibits vitamin K epoxide reductase, so every vitamin K-dependent protein — including proteins C and S — fails to be carboxylated.")

# ── 6. The interaction that raises the INR (§15) ──────────────────────────────
q("A 71-year-old woman has taken warfarin for atrial fibrillation for 3 years, with an international normalized ratio consistently between 2.2 and 2.8 on a stable dose. Ten days ago she was treated with trimethoprim-sulfamethoxazole for a urinary tract infection. She now has extensive bruising on both forearms and bleeding from her gums when brushing her teeth. She has not changed her diet, her warfarin dose, or any other medication. Her temperature is 37.0°C (98.6°F), pulse is 78/min, and blood pressure is 134/80 mm Hg.\n\nLaboratory studies show:\nHemoglobin 11.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 34% (N=36%–46%)\nPlatelet count 236,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 68 seconds (N=11–15 seconds)\nInternational normalized ratio 7.9 (N=0.8–1.2)\nPartial thromboplastin time 46 seconds (N=25–40 seconds)\n\nWhich of the following best explains the change in this patient's international normalized ratio?",
  ["A. Displacement of warfarin from albumin binding sites",
   "B. Increased dietary intake of vitamin K",
   "C. Induction of CYP2C9, increasing warfarin clearance",
   "D. Inhibition of CYP2C9, reducing warfarin clearance",
   "E. Reduced enterohepatic circulation of warfarin"],
  3,
  "Warfarin is cleared by CYP2C9, and trimethoprim-sulfamethoxazole is a potent CYP2C9 INHIBITOR. Less warfarin is metabolized → plasma levels rise → more vitamin K epoxide reductase is inhibited → the INR climbs. This is a pharmacokinetic interaction, and it is one of the highest-risk antibiotic interactions with warfarin.\n\nIt is actually two mechanisms at once, which is why the effect is so large. Alongside the enzyme inhibition, any antibiotic kills the gut flora that synthesize vitamin K, leaving less substrate for the recycling pathway warfarin already blocks — a pharmacodynamic interaction added to a pharmacokinetic one.\n\nThe drugs that raise the INR by inhibiting CYP2C9: amiodarone, metronidazole, trimethoprim-sulfamethoxazole, fluconazole, ciprofloxacin, fluvoxamine. The ones that LOWER it by induction: rifampin, carbamazepine, phenytoin, St John's wort. And a third group — aspirin, other antiplatelets, NSAIDs — increases bleeding at any INR without changing the number at all.\n\nManagement at an INR of 7.9 with non-major bleeding: hold warfarin, give oral vitamin K, and reserve prothrombin complex concentrate for serious or life-threatening bleeding. Then recheck, because the interaction persists while the antibiotic does.",
  {"0": "Protein-binding displacement is a textbook idea that rarely produces a clinically meaningful, sustained change, because the freed drug is simply cleared faster and a new equilibrium is reached. It is not the mechanism by which sulfamethoxazole raises the INR.",
   "1": "More dietary vitamin K moves the INR in the opposite direction — it outcompetes warfarin at vitamin K epoxide reductase and LOWERS the INR. It would be the explanation for a subtherapeutic INR in a patient who had started eating large amounts of leafy greens; she has not changed her diet.",
   "2": "Enzyme induction increases warfarin clearance and lowers the INR — the rifampin, carbamazepine, phenytoin and St John's wort group. The direction is wrong for a patient whose INR has risen to 7.9.",
   "4": "Warfarin does not depend on enterohepatic recirculation for its effect, and interrupting it would if anything reduce exposure and lower the INR. The relevant gut contribution is bacterial vitamin K synthesis, which is a separate mechanism and also raises rather than lowers the INR when it is disrupted."},
  "The antibiotic blocks the liver enzyme that clears warfarin, so warfarin piles up and thins her blood far too much. It also wipes out the gut bacteria that make vitamin K, which pushes in the same direction.",
  exim="fig_slide_cyp2c9",
  excap="Lecture slide: CYP2C9 handles warfarin clearance and VKORC1 is its target — genotype at both explains much of the between-patient dose variability, and CYP2C9 is where the drug interactions land.")

# ── 7. The diet conversation (§15) ────────────────────────────────────────────
q("A 63-year-old man who has taken warfarin for 2 years after a pulmonary embolism comes to the anticoagulation clinic. Six weeks ago he began a new diet that includes a large kale-and-spinach salad most days. He reports taking every warfarin dose and has started no new medications. He has had no bleeding and no symptoms of recurrent thrombosis. His temperature is 36.9°C (98.4°F), pulse is 72/min, and blood pressure is 128/76 mm Hg.\n\nLaboratory studies show:\nHemoglobin 14.6 g/dL (N=13.5–17.5 g/dL)\nHematocrit 43% (N=41%–53%)\nPlatelet count 218,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 15 seconds (N=11–15 seconds)\nInternational normalized ratio 1.3 (N=0.8–1.2)\n\nHis international normalized ratio was 2.5 at his last three visits. In addition to adjusting his warfarin dose, which of the following is the most appropriate dietary advice?",
  ["A. Avoid all leafy green vegetables permanently",
   "B. Increase the warfarin dose and continue the diet without further monitoring",
   "C. Maintain a consistent daily intake of vitamin K-containing foods",
   "D. Switch to a low-protein diet to reduce warfarin binding",
   "E. Take warfarin with meals to improve its absorption"],
  2,
  "Leafy greens are rich in vitamin K, which competes with warfarin's block at vitamin K epoxide reductase → more substrate reaches the cycle → less anticoagulation → the INR falls, exactly as it has here from 2.5 to 1.3.\n\nThe counselling point is the one students most often get wrong: patients are told to keep vitamin K intake CONSISTENT, not to avoid it. Warfarin dosing is titrated to whatever steady intake a patient has. A consistent high intake simply requires a higher warfarin dose and is perfectly manageable; what destabilizes the INR is VARIATION — a new diet, a holiday, a course of illness with poor intake.\n\nTelling him to give up vegetables trades a solvable dosing problem for a worse diet and usually fails anyway, after which the INR swings when he resumes them.\n\nThe practical plan: increase the warfarin dose against his new steady intake, recheck the INR in about a week, and repeat until stable. If his diet is likely to keep changing, this is also a reasonable moment to discuss a direct oral anticoagulant, which has far fewer food interactions — though not for a patient with a mechanical valve.",
  {"0": "Avoiding greens would work biochemically but is the wrong instruction. It worsens his diet, is rarely sustained, and sets up a rebound rise in the INR whenever he eats them again — the variability is the problem, not the vitamin.",
   "1": "Raising the dose is half right — it is stated in the stem as already happening — but abandoning monitoring is unsafe. The INR must be rechecked until it is stable on the new intake, and it would also miss a further diet change in either direction.",
   "3": "Dietary protein has no meaningful effect on warfarin's action. Protein-binding displacement is a textbook idea that does not produce sustained clinical change, and no anticoagulation clinic manages warfarin by adjusting protein intake.",
   "4": "Warfarin absorption is rapid and essentially complete regardless of food, so timing with meals changes nothing. Taking the dose with food matters for RIVAROXABAN at treatment doses, where absorption genuinely depends on it."},
  "Green vegetables are full of vitamin K, which is exactly what warfarin is working against — so a sudden salad habit weakens the drug. The fix is not to give up salad but to eat roughly the same amount every day so the dose can be matched to it.",
  exim="fig_slide_vitk",
  excap="Lecture slide: the vitamin K cycle. Dietary vitamin K competes with warfarin's block of the epoxide reductase step, which is why intake must be consistent.")

# ── 8. Anticoagulation in pregnancy (§15) ─────────────────────────────────────
q("A 28-year-old woman, gravida 1, para 0, at 6 weeks' gestation comes to the office. She has taken warfarin for the past 2 years after an unprovoked deep vein thrombosis, and her international normalized ratio has been stable at 2.4. The pregnancy was unplanned and she learned of it 3 days ago. She feels well and has no leg pain or swelling. Her temperature is 36.8°C (98.2°F), pulse is 84/min, and blood pressure is 112/68 mm Hg. Physical examination shows no abnormalities.\n\nLaboratory studies show:\nHemoglobin 12.6 g/dL (N=12.0–16.0 g/dL)\nHematocrit 38% (N=36%–46%)\nPlatelet count 262,000/mm3 (N=150,000–400,000/mm3)\nInternational normalized ratio 2.4 (N=0.8–1.2)\nCreatinine 0.7 mg/dL (N=0.6–1.2 mg/dL)\n\nWhich of the following anticoagulants is most appropriate to substitute for her warfarin?",
  ["A. Apixaban",
   "B. Aspirin",
   "C. Dabigatran",
   "D. Enoxaparin",
   "E. Fondaparinux"],
  3,
  "Warfarin is TERATOGENIC and is contraindicated in pregnancy. It crosses the placenta, and first-trimester exposure causes fetal warfarin syndrome — nasal hypoplasia and stippled epiphyses — with central nervous system abnormalities and fetal bleeding later in gestation.\n\nThe heparins are the anticoagulants of pregnancy, for one structural reason: they are large, highly charged molecules that do NOT cross the placenta. Low-molecular-weight heparin such as enoxaparin is preferred over unfractionated heparin for most indications — predictable dosing, once- or twice-daily subcutaneous administration, no routine monitoring, and less osteoporosis and HIT than unfractionated heparin with long-term use. Anti-Xa monitoring is used in pregnancy, obesity or renal impairment, since the volume of distribution changes as pregnancy advances.\n\nThe urgency is real. The teratogenic window for warfarin is roughly weeks 6 to 12, so she should be switched now, at 6 weeks, and referred for fetal assessment given the exposure that has already occurred.\n\nThe rest of the plan: continue a heparin throughout pregnancy, plan the peripartum transition around delivery and neuraxial anesthesia, and note that warfarin is compatible with breastfeeding, so it can be resumed postpartum.",
  {"0": "Apixaban and the other direct oral anticoagulants are not established in pregnancy and are avoided. They are small molecules that cross the placenta, and there are no adequate human safety data — the class is explicitly listed as 'not established — avoid'.",
   "1": "Aspirin is an antiplatelet drug and is used in pregnancy for a completely different purpose — low dose for preeclampsia prophylaxis in selected patients. It does not treat or prevent venous thromboembolism, which is a fibrin-rich stasis clot.",
   "2": "Dabigatran is a direct oral anticoagulant and carries the same problem as the -xabans: no established safety in pregnancy, and placental transfer. It is also renally cleared, which matters as pregnancy alters renal handling.",
   "4": "Fondaparinux is not first line in pregnancy — the data are limited, some placental passage has been demonstrated, and it has no effective reversal agent, which matters when delivery may be sudden. It is reserved for women who cannot receive heparin, typically because of HIT or severe heparin allergy."},
  "Warfarin crosses into the baby and causes birth defects, especially in the first three months. Heparin-type drugs are too big to cross the placenta, so they are the ones used in pregnancy.",
  exim="fig_slide_anticoag_classes",
  excap="Lecture slide: the four anticoagulant families. Only the heparins are large enough to be excluded by the placenta, which makes them the drugs of pregnancy.")

# ── 9. Reversing dabigatran (§15) ─────────────────────────────────────────────
q("A 79-year-old man taking dabigatran for atrial fibrillation is brought to the emergency department after a fall down stairs. He is drowsy and vomiting. His temperature is 36.7°C (98.1°F), pulse is 92/min and irregular, respirations are 18/min, and blood pressure is 168/92 mm Hg. Physical examination shows a scalp hematoma and a left pronator drift. He took his last dose 5 hours ago.\n\nLaboratory studies show:\nHemoglobin 12.8 g/dL (N=13.5–17.5 g/dL)\nHematocrit 38% (N=41%–53%)\nPlatelet count 208,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 17 seconds (N=11–15 seconds)\nPartial thromboplastin time 64 seconds (N=25–40 seconds)\nCreatinine 1.6 mg/dL (N=0.6–1.2 mg/dL)\n\nCT scan of the head without contrast shows an acute right subdural hematoma with 6 mm of midline shift. Which of the following is the most appropriate agent to reverse his anticoagulation?",
  ["A. Andexanet alfa",
   "B. Fresh frozen plasma",
   "C. Idarucizumab",
   "D. Protamine sulfate",
   "E. Vitamin K"],
  2,
  "Dabigatran is the only ORAL direct thrombin inhibitor, and it has a specific antidote: idarucizumab, a humanized monoclonal antibody FRAGMENT that binds dabigatran with an affinity roughly 350 times that of thrombin. It is given as two 2.5 g intravenous boluses and reverses the anticoagulant effect within minutes.\n\nThe taxonomy is what makes the reversal bench memorable — sort a drug into its family and the antidote follows:\n\n• Unfractionated heparin → protamine sulfate (full reversal)\n• Low-molecular-weight heparin → protamine (partial, about 60%)\n• Fondaparinux → nothing works\n• Warfarin → vitamin K plus four-factor prothrombin complex concentrate\n• Dabigatran → idarucizumab\n• Factor Xa inhibitors (the -xabans) → four-factor prothrombin complex concentrate\n\nHis laboratory pattern fits a direct thrombin inhibitor: the aPTT is prolonged, since the drug inhibits thrombin directly, with a smaller effect on the prothrombin time. Note also his creatinine of 1.6 mg/dL — dabigatran is renally cleared, so impaired kidney function prolongs its effect and raises the bleeding risk in the first place.\n\nAlongside reversal: neurosurgical consultation, blood pressure control, and no further dabigatran.",
  {"0": "Andexanet alfa was the specific reversal agent for the factor Xa inhibitors, not for dabigatran — a decoy receptor that binds the -xabans. It was withdrawn from the market in 2026, so it is not an option for any drug at present.",
   "1": "Plasma contains all the coagulation factors but cannot overcome a direct thrombin inhibitor: the drug inhibits whatever thrombin is generated, including thrombin made from transfused prothrombin. Plasma also takes time and volume, neither of which he has.",
   "3": "Protamine binds and neutralizes heparin by charge, and is effective only against the heparins — fully for unfractionated heparin, partially for low-molecular-weight heparin. It has no affinity for dabigatran.",
   "4": "Vitamin K restores the liver's ability to carboxylate factors II, VII, IX and X — the mechanism warfarin blocks. Dabigatran does not interfere with factor synthesis at all; it inhibits the finished thrombin molecule, so vitamin K is irrelevant."},
  "His blood thinner works by grabbing thrombin directly, and there is an antibody made specifically to grab the drug right back off it. One injection and the effect is gone within minutes.",
  exim="fig_slide_xaban_reversal",
  excap="Lecture slide on direct oral anticoagulant reversal — each family has its own antidote, and the drug's mechanism predicts which one works.")

# ── 10. Reversing a factor Xa inhibitor (§15) ─────────────────────────────────
q("A 74-year-old woman taking apixaban for atrial fibrillation is brought to the emergency department 2 hours after the sudden onset of a severe headache and right-sided weakness. She took her morning dose 4 hours ago. Her temperature is 36.9°C (98.4°F), pulse is 88/min and irregular, respirations are 16/min, and blood pressure is 182/96 mm Hg. Physical examination shows a right hemiparesis and a dense right facial droop; she is drowsy.\n\nLaboratory studies show:\nHemoglobin 12.2 g/dL (N=12.0–16.0 g/dL)\nHematocrit 37% (N=36%–46%)\nPlatelet count 224,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 15 seconds (N=11–15 seconds)\nInternational normalized ratio 1.2 (N=0.8–1.2)\nPartial thromboplastin time 36 seconds (N=25–40 seconds)\nCreatinine 1.0 mg/dL (N=0.6–1.2 mg/dL)\n\nCT scan of the head without contrast shows an acute left basal ganglia hemorrhage. Which of the following is the most appropriate agent to give?",
  ["A. Four-factor prothrombin complex concentrate",
   "B. Fresh frozen plasma",
   "C. Idarucizumab",
   "D. Protamine sulfate",
   "E. Vitamin K"],
  0,
  "Apixaban is a direct factor Xa inhibitor. Andexanet alfa was the specific reversal agent for this class, but it was withdrawn from the market in 2026 — so four-factor prothrombin complex concentrate is the practical option for life-threatening bleeding.\n\nThe logic of using it is worth stating, because it is not a true antidote. Prothrombin complex concentrate does not remove apixaban; it floods the system with factors II, VII, IX and X, generating enough thrombin downstream to overwhelm the inhibited step. It bypasses the block rather than lifting it.\n\nNote the trap in her laboratory studies: her prothrombin time, INR and aPTT are all essentially NORMAL. Routine coagulation tests are insensitive to the -xabans, so normal results do not exclude a therapeutic drug level. Anticoagulation must be judged from the drug history and the timing of the last dose — hers was 4 hours ago, close to peak.\n\nThe class blueprint for the -xabans: fixed dosing, no routine monitoring, few food interactions, all substrates of P-glycoprotein and CYP3A4. Shared boxed warnings are premature discontinuation causing thrombosis, and spinal or epidural hematoma with neuraxial anesthesia.",
  {"1": "Plasma provides coagulation factors at physiologic concentration, so overcoming a direct factor Xa inhibitor would require an unachievable volume, delivered slowly, into a hypertensive elderly patient with an intracranial bleed. It is a distant fallback when concentrate is unavailable.",
   "2": "Idarucizumab is the specific antibody fragment against DABIGATRAN, a direct thrombin inhibitor. It has no affinity for apixaban or the other -xabans — matching the antidote to the right family is exactly what this item tests.",
   "3": "Protamine neutralizes heparin by ionic binding and does nothing to an oral factor Xa inhibitor. It is fully effective for unfractionated heparin, partial for low-molecular-weight heparin, and useless for fondaparinux despite that drug's anti-Xa activity.",
   "4": "Vitamin K corrects a deficiency of carboxylated factors — the mechanism of warfarin, not of a direct inhibitor. Her factors are present and functional; they are simply being blocked at factor Xa, and her normal INR reflects that."},
  "Her drug blocks one specific clotting step, and the antidote made for it was pulled from the market. So you flood the system with a concentrate of clotting factors to push past the blocked step.",
  exim="fig_slide_xaban_reversal",
  excap="Lecture slide: reversal and adjunctive therapy for the direct oral factor Xa inhibitors.")

# ── 11. Choosing an agent in renal failure (§15) ──────────────────────────────
q("A 70-year-old man with stage 4 chronic kidney disease is admitted with an acute proximal deep vein thrombosis of the left leg. He is scheduled for an arteriovenous fistula creation in 2 days, and further procedures may be required at short notice. He has no active bleeding. His temperature is 36.9°C (98.4°F), pulse is 80/min, and blood pressure is 142/84 mm Hg.\n\nLaboratory studies show:\nHemoglobin 10.6 g/dL (N=13.5–17.5 g/dL)\nHematocrit 32% (N=41%–53%)\nPlatelet count 214,000/mm3 (N=150,000–400,000/mm3)\nCreatinine 3.6 mg/dL (N=0.6–1.2 mg/dL)\nCreatinine clearance 18 mL/min (N=97–137 mL/min)\nProthrombin time 12.9 seconds (N=11–15 seconds)\n\nWhich of the following anticoagulants is most appropriate for initial treatment?",
  ["A. Apixaban",
   "B. Enoxaparin",
   "C. Fondaparinux",
   "D. Unfractionated heparin",
   "E. Warfarin"],
  3,
  "Two features of this case point to the same drug, and both are clinical-logic rules from §15.\n\nSevere renal impairment. Unfractionated heparin is cleared by the reticuloendothelial system rather than the kidney, so its effect is not prolonged by a creatinine clearance of 18 mL/min. Enoxaparin is renally cleared and accumulates below a clearance of 30 mL/min; fondaparinux is outright contraindicated there; edoxaban and dabigatran are renally handled too.\n\nYou may need to stop fast. He has surgery in 2 days and may need more at short notice. Unfractionated heparin has a half-life of about 60 to 90 minutes and a complete antidote in protamine sulfate — turn off the infusion and the effect is largely gone within hours, and protamine finishes the job. Nothing else on the list can be switched off that reliably.\n\nMonitoring is by aPTT (or an anti-Xa level), titrated to a therapeutic range. The trade-offs to keep in view: HIT risk is higher with unfractionated than with low-molecular-weight heparin, and prolonged use causes osteoporosis and hyperkalemia through aldosterone suppression.\n\nOnce he is past his procedures and stable, the conversation about a longer-term agent can begin.",
  {"0": "Apixaban is the friendliest of the -xabans in kidney disease — only about 25% renally cleared — but at a creatinine clearance of 18 mL/min it is at the edge of the evidence, and more importantly it cannot be switched off quickly for a procedure in 2 days.",
   "1": "Enoxaparin is renally cleared and accumulates in severe impairment, so it requires dose reduction below a clearance of 30 mL/min and anti-Xa monitoring. Protamine reverses it only partially (about 60%), which is a poor position to be in before surgery.",
   "2": "Fondaparinux is CONTRAINDICATED when the creatinine clearance is below 30 mL/min, and it has no effective reversal agent at all — protamine does not work on it. Both facts make it the worst choice here.",
   "4": "Warfarin takes days to become effective, so it cannot treat an acute clot on its own, and its effect cannot be turned off quickly for surgery. It may well be his long-term agent, but it needs a parenteral bridge, which brings the question back to which parenteral drug to use."},
  "His kidneys barely work and he has surgery in two days, so he needs the blood thinner that the kidneys do not have to clear and that can be switched off fast. Old-fashioned intravenous heparin wears off in about an hour and has a complete antidote.",
  exim="fig_slide_anticoag_classes",
  excap="Lecture slide: the anticoagulant families. Clearance route and reversibility are what decide the choice in renal impairment and before a procedure.")

# ── 12. Rivaroxaban needs a meal (§15) ────────────────────────────────────────
q("A 46-year-old man was treated for an unprovoked pulmonary embolism 4 months ago and was prescribed rivaroxaban 20 mg once daily. He now returns with 2 days of right calf pain and swelling. He says he has taken every dose, always first thing in the morning before eating because he skips breakfast. He takes no other medications, including no anticonvulsants, rifampin, or herbal products. He does not smoke. His temperature is 37.0°C (98.6°F), pulse is 88/min, and blood pressure is 126/78 mm Hg. Physical examination shows a warm, swollen right calf with tenderness along the deep venous system.\n\nLaboratory studies show:\nHemoglobin 14.0 g/dL (N=13.5–17.5 g/dL)\nHematocrit 42% (N=41%–53%)\nPlatelet count 240,000/mm3 (N=150,000–400,000/mm3)\nCreatinine 0.9 mg/dL (N=0.6–1.2 mg/dL)\nCreatinine clearance 104 mL/min (N=97–137 mL/min)\n\nDuplex ultrasonography confirms a new right popliteal deep vein thrombosis. Which of the following best explains this treatment failure?",
  ["A. Administration of the dose without food, reducing absorption",
   "B. Concurrent therapy with a strong CYP3A4 inducer",
   "C. Development of neutralizing antibodies against rivaroxaban",
   "D. Excessive renal clearance because the creatinine clearance exceeds 95 mL/min",
   "E. Failure of rivaroxaban to inhibit clot-bound factor Xa"],
  0,
  "Rivaroxaban at treatment doses — 15 mg and 20 mg — MUST be taken with food. Without a meal its bioavailability falls substantially (from roughly 80% to about 66% at the 20 mg dose), and the drug level never reaches the therapeutic range. He has been perfectly adherent to a regimen that cannot work.\n\nThis is the distinguishing fact for rivaroxaban within its class, and the memory hook is the A-B-C of the xabans:\n• Apixaban — twice daily, least renally cleared (~25%), all-round safest in kidney disease and the lowest bleeding rates of the class.\n• Rivaroxaban — once daily, Requires a meal.\n• Edoxaban — once daily, the backwards renal rule: do NOT use in atrial fibrillation if the creatinine clearance is above 95 mL/min, because it is cleared so fast that efficacy drops.\n\nThe stem rules out every competing explanation deliberately: he reports full adherence, takes no CYP3A4 or P-glycoprotein inducer, and his renal function is normal.\n\nManagement: treat the new clot, and either counsel him firmly to take the dose with his largest meal of the day, or switch him to apixaban, which has no food requirement and is twice daily.",
  {"1": "Strong inducers of CYP3A4 and P-glycoprotein — rifampin, carbamazepine, phenytoin, St John's wort — drop -xaban levels into the failure range, and this is a genuine cause of breakthrough thrombosis. The stem excludes all of them explicitly.",
   "2": "Neutralizing antibodies are a problem for biologic therapies such as factor VIII concentrates and monoclonal antibodies. Rivaroxaban is a small synthetic molecule and does not provoke an antibody response.",
   "3": "This inverts the edoxaban rule and applies it to the wrong drug. It is EDOXABAN that loses efficacy in atrial fibrillation when the creatinine clearance exceeds 95 mL/min; rivaroxaban has no such ceiling, and his clearance of 104 mL/min is normal.",
   "4": "Unlike the indirect inhibitors, the direct factor Xa inhibitors DO inhibit clot-bound factor Xa — that is an advantage of the class, not a limitation. If this statement were true, the drug would not work in anyone."},
  "This particular pill only gets absorbed properly when there is food in the stomach, and he has been taking it on an empty stomach every morning. He did everything he was told except the one instruction that mattered most.",
  exim="fig_slide_anticoag_classes",
  excap="Lecture slide: the direct oral anticoagulants sit alongside the older families, but each -xaban carries its own distinguishing rule.")

# ── 13. Choosing a DOAC in kidney disease (§15) ───────────────────────────────
q("A 77-year-old woman with newly diagnosed atrial fibrillation and stage 3b chronic kidney disease is to begin anticoagulation for stroke prevention. She has no valvular heart disease and no mechanical valve. She had a gastrointestinal hemorrhage from a duodenal ulcer 4 years ago, now healed. She would prefer an oral agent that does not require frequent monitoring. Her temperature is 36.8°C (98.2°F), pulse is 84/min and irregular, and blood pressure is 138/80 mm Hg.\n\nLaboratory studies show:\nHemoglobin 12.1 g/dL (N=12.0–16.0 g/dL)\nHematocrit 36% (N=36%–46%)\nPlatelet count 226,000/mm3 (N=150,000–400,000/mm3)\nCreatinine 1.7 mg/dL (N=0.6–1.2 mg/dL)\nCreatinine clearance 32 mL/min (N=88–128 mL/min)\nProthrombin time 12.6 seconds (N=11–15 seconds)\n\nWhich of the following is the most appropriate anticoagulant for this patient?",
  ["A. Apixaban",
   "B. Dabigatran",
   "C. Edoxaban",
   "D. Fondaparinux",
   "E. Rivaroxaban"],
  0,
  "Apixaban is the direct oral anticoagulant of choice when kidney function is impaired and bleeding risk is a concern. It is the LEAST renally cleared of the class — roughly 25%, against about 50% for edoxaban, 35% for rivaroxaban and 80% for dabigatran — and it has the lowest bleeding rates of the group, including the lowest rate of gastrointestinal bleeding, which matters in a woman with a previous duodenal hemorrhage.\n\nIt is dosed twice daily, with a reduced dose when two of three criteria are met: age 80 years or more, weight 60 kg or less, or creatinine 1.5 mg/dL or more. She meets one so far, and that arithmetic is part of prescribing it correctly.\n\nWhy a direct oral anticoagulant rather than warfarin at all: fixed dosing, no routine monitoring, far fewer food and drug interactions, and no dietary vitamin K constraint. The exceptions where warfarin remains necessary are a MECHANICAL heart valve and moderate-to-severe mitral stenosis — neither of which she has.\n\nThe class caveats still apply: all -xabans are substrates of P-glycoprotein and CYP3A4, so strong inhibitors raise levels and strong inducers cause failure; and the boxed warnings are premature discontinuation causing thrombosis, and spinal or epidural hematoma with neuraxial anesthesia.",
  {"1": "Dabigatran is about 80% renally cleared, the most of any agent in this group, so it accumulates as kidney function falls. It also causes dyspepsia in roughly one in ten patients and has the highest gastrointestinal bleeding rate of the class — a poor fit for a woman with a previous duodenal ulcer bleed.",
   "2": "Edoxaban is around 50% renally cleared and carries the backwards rule that makes it awkward to prescribe: it must NOT be used in atrial fibrillation when the creatinine clearance is above 95 mL/min. Hers is 32 mL/min, so the ceiling is not the problem, but its heavier renal dependence still makes apixaban the better choice.",
   "3": "Fondaparinux is a once-daily SUBCUTANEOUS injection, not an oral agent, and it is contraindicated when the creatinine clearance is below 30 mL/min — she is at 32 mL/min, uncomfortably close. It also has no reversal agent.",
   "4": "Rivaroxaban is a reasonable alternative but is a weaker fit on both of her specific issues: it is more renally cleared than apixaban, has higher gastrointestinal bleeding rates, and must be taken with food at treatment doses — an adherence trap she does not need."},
  "All these pills work, but hers is the one the kidneys barely have to clear and the one least likely to make her stomach bleed again. Given her kidney numbers and her ulcer history, that is the safest fit.",
  exim="fig_slide_anticoag_classes",
  excap="Lecture slide: within the direct oral anticoagulants, clearance route and bleeding profile are what separate one agent from another.")

# ── 14. The mechanical valve exception (§15) ──────────────────────────────────
q("A 52-year-old man underwent mechanical mitral valve replacement 3 years ago and has taken warfarin since. Frustrated by clinic visits, he stopped warfarin 5 weeks ago and began apixaban, which a friend takes for atrial fibrillation. He now has 3 days of exertional dyspnea. His temperature is 37.0°C (98.6°F), pulse is 104/min, respirations are 24/min, and blood pressure is 108/70 mm Hg. Cardiac examination shows muffled mechanical valve clicks and a new diastolic murmur at the apex.\n\nLaboratory studies show:\nHemoglobin 13.4 g/dL (N=13.5–17.5 g/dL)\nHematocrit 40% (N=41%–53%)\nPlatelet count 218,000/mm3 (N=150,000–400,000/mm3)\nLactate dehydrogenase 460 U/L (N=45–200 U/L)\nInternational normalized ratio 1.1 (N=0.8–1.2)\n\nTransesophageal echocardiography shows a thrombus restricting one leaflet of the mechanical valve. After the acute event is managed, which of the following is the most appropriate long-term anticoagulation?",
  ["A. Apixaban at an increased dose",
   "B. Aspirin plus clopidogrel",
   "C. Dabigatran",
   "D. Enoxaparin indefinitely",
   "E. Warfarin with a target international normalized ratio of 2.5 to 3.5"],
  4,
  "A mechanical heart valve is the clearest exception to the modern drift toward direct oral anticoagulants: these patients need WARFARIN, and for a mechanical mitral valve the target is 2.5 to 3.5 rather than the usual 2.0 to 3.0.\n\nThe evidence is not theoretical. The RE-ALIGN trial randomized patients with mechanical valves to dabigatran or warfarin and was stopped early because the dabigatran arm had significantly MORE thromboembolism and more bleeding. The mechanism is thought to be the intense contact-pathway activation generated by an artificial surface, which warfarin — depleting four factors at once, upstream — suppresses more completely than a single-target inhibitor does.\n\nHis presentation is the predictable consequence of the substitution: valve thrombosis, with muffled clicks, a new obstructive murmur, and a raised lactate dehydrogenase from mechanical hemolysis across the restricted leaflet.\n\nThe practical rule to carry: direct oral anticoagulants are excellent for non-valvular atrial fibrillation and for venous thromboembolism, and inadequate for a mechanical valve and for moderate-to-severe mitral stenosis. The phrase 'non-valvular atrial fibrillation' in every trial name is doing exactly this work.\n\nAcute management is heparin plus either fibrinolysis or surgery, depending on thrombus size and hemodynamic status.",
  {"0": "Raising the apixaban dose does not fix a class-level inadequacy, and it would add bleeding risk to a strategy that has already failed him. The problem is not the amount of drug — his valve thrombosed on a therapeutic regimen.",
   "1": "Dual antiplatelet therapy targets platelet-rich arterial clots. Valve thrombus is fibrin-rich and forms on an artificial surface; antiplatelet drugs alone are wholly inadequate, though low-dose aspirin is sometimes ADDED to warfarin in selected valve patients.",
   "2": "Dabigatran is the specific drug that was tested in this exact population and failed. RE-ALIGN showed more thromboembolic events and more bleeding than warfarin, and mechanical valves are now a labelled contraindication.",
   "3": "Indefinite enoxaparin is a fallback in pregnancy or in patients who cannot take warfarin, but it means twice-daily injections for life, carries osteoporosis and HIT risks, and is less effective than warfarin for mechanical valves. It is not the long-term answer for a man who finds clinic visits inconvenient."},
  "Artificial heart valves are the one situation where the newer once-a-day pills are not good enough — a trial testing that had to be stopped early because patients did worse. He needs warfarin and the blood tests that come with it.",
  exim="fig_slide_anticoag_classes",
  excap="Lecture slide: the four families. Warfarin remains mandatory where an artificial surface drives thrombosis, despite the convenience of the newer agents.")

# ── 15. Heparin resistance (§15) ──────────────────────────────────────────────
q("A 34-year-old woman is admitted with an extensive iliofemoral deep vein thrombosis. She has had two previous unprovoked thromboses, and her mother and brother have each had a deep vein thrombosis before age 40. She takes no medications and is not pregnant. An intravenous unfractionated heparin infusion is begun at a weight-based dose. Over the next 18 hours the infusion rate is increased three times, to more than twice the usual therapeutic requirement, but the partial thromboplastin time barely rises.\n\nLaboratory studies show:\nHemoglobin 13.0 g/dL (N=12.0–16.0 g/dL)\nHematocrit 39% (N=36%–46%)\nPlatelet count 246,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 12.4 seconds (N=11–15 seconds)\nPartial thromboplastin time 34 seconds (N=25–40 seconds)\nAntithrombin activity 42% (N=80%–120%)\n\nWhich of the following best explains the failure of the partial thromboplastin time to respond?",
  ["A. Antithrombin deficiency",
   "B. Factor V Leiden mutation",
   "C. Heparin-induced thrombocytopenia",
   "D. Lupus anticoagulant",
   "E. Protein C deficiency"],
  0,
  "Heparin has no intrinsic anticoagulant activity. It works entirely THROUGH antithrombin — binding it, changing its conformation, and accelerating its inhibition of thrombin and factor Xa by a factor of roughly a thousand. If antithrombin is missing, heparin has nothing to potentiate, and the aPTT does not move however much drug you give. This is heparin resistance, and antithrombin deficiency is its classic inherited cause.\n\nHer antithrombin activity of 42% makes the diagnosis, and the rest of the history fits an inherited thrombophilia: recurrent unprovoked thrombosis, a first event at a young age, and affected first-degree relatives.\n\nWhat to do about it: switch to an agent that does not require antithrombin — argatroban or bivalirudin, both direct thrombin inhibitors — or give antithrombin concentrate (or plasma, which contains antithrombin) to restore the cofactor so that heparin can work. Long-term management is warfarin or a direct oral anticoagulant.\n\nOne caution about the assay: antithrombin levels are consumed during acute thrombosis and lowered by heparin itself, so a low value in this setting should be confirmed after recovery and off anticoagulation before the inherited diagnosis is fixed.",
  {"1": "Factor V Leiden makes activated factor V resistant to cleavage by activated protein C, and is the commonest inherited thrombophilia — so it belongs on her differential. It does not interfere with heparin's action, and the aPTT would respond normally.",
   "2": "HIT is a reason heparin can fail clinically, and it must always be considered — but it presents with a platelet count falling more than 50% at 5 to 10 days, plus thrombosis. She is 18 hours in with a platelet count of 246,000/mm3, and HIT does not blunt the aPTT.",
   "3": "A lupus anticoagulant PROLONGS the baseline aPTT rather than blunting it — it interferes with the phospholipid-dependent assay. It would be the answer for an unexpectedly long aPTT that fails to correct on a mixing study, and it makes the aPTT useless for MONITORING heparin, which is a different problem from the drug not working.",
   "4": "Protein C deficiency is another inherited thrombophilia and would explain her thrombotic history, but protein C sits in a separate pathway — it inactivates factors Va and VIIIa. It has no bearing on how heparin performs, and its clinical relevance to drugs is warfarin-induced skin necrosis."},
  "Heparin does not thin blood by itself — it supercharges a natural protein called antithrombin. She was born with very little of that protein, so there is almost nothing for the drug to switch on.",
  exim="fig_heparin_mech_uw",
  excap="Heparin's mechanism: it binds antithrombin and accelerates it. With antithrombin depleted, the drug has no target to potentiate.")

# ── 16. Aspirin, irreversibly (§16) ───────────────────────────────────────────
q("A 66-year-old man with stable coronary artery disease takes aspirin 81 mg daily. He is scheduled for an elective total knee arthroplasty, and the surgeon asks that aspirin be stopped 7 days before the operation. He takes no other antiplatelet or anticoagulant medication. His temperature is 36.9°C (98.4°F), pulse is 70/min, and blood pressure is 130/78 mm Hg.\n\nLaboratory studies show:\nHemoglobin 14.4 g/dL (N=13.5–17.5 g/dL)\nHematocrit 43% (N=41%–53%)\nPlatelet count 236,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 12.4 seconds (N=11–15 seconds)\nPartial thromboplastin time 31 seconds (N=25–40 seconds)\n\nWhich of the following best explains why the drug must be stopped this far in advance?",
  ["A. Aspirin inhibits synthesis of the vitamin K-dependent clotting factors",
   "B. Aspirin irreversibly inhibits platelet cyclooxygenase-1, and platelets cannot synthesize new enzyme",
   "C. Aspirin is eliminated renally over approximately 7 days",
   "D. Aspirin's active metabolite has a plasma half-life of approximately 7 days",
   "E. Aspirin's inhibition of endothelial cyclooxygenase-2 persists for 7 days"],
  1,
  "Aspirin irreversibly ACETYLATES cyclooxygenase-1. The enzyme is permanently disabled, so the platelet can no longer make thromboxane A2 — its own 'recruit more platelets' signal.\n\nWhat makes the effect last is what the platelet lacks: a nucleus. It cannot transcribe a new gene or synthesize replacement enzyme, so that platelet is out of action for the whole of its 7 to 10 day lifespan. Recovery of platelet function depends entirely on the marrow releasing NEW platelets, at roughly 10% of the pool per day. Hence the 7-day rule before major surgery, and hence the fact that a single dose commits you for a week.\n\nAspirin's own plasma half-life is about 15 to 20 minutes — the drug is long gone while its effect persists. Duration of effect and duration of drug exposure are completely uncoupled, which is the conceptual point.\n\nTwo other aspirin facts worth carrying: the dose paradox — low dose is the ANTIPLATELET dose, because higher doses also inhibit endothelial cyclooxygenase-2, which makes prostacyclin, the platelet inhibitor, so pushing the dose can work against you. And the harms: gastrointestinal ulceration and bleeding, tinnitus at high dose, and Reye syndrome in children with a viral illness.",
  {"0": "Inhibiting the synthesis of the vitamin K-dependent factors is warfarin's mechanism, and it would be reflected in a prolonged prothrombin time. His prothrombin time is 12.4 seconds — antiplatelet drugs do not alter coagulation tests at all, because those tests measure plasma factors rather than platelet function.",
   "2": "Aspirin is hydrolyzed to salicylic acid and cleared over hours, not days. Its elimination is essentially complete long before the antiplatelet effect wanes — a fact that makes the 7-day rule look inexplicable unless you think about the platelet rather than the drug.",
   "3": "The active moiety has a half-life measured in minutes. If a 7-day half-life were the explanation, then simply waiting out the drug would restore function — whereas in reality function returns only as the marrow produces new platelets.",
   "4": "Endothelial cyclooxygenase-2 inhibition is real at higher doses, but endothelial cells are nucleated and resynthesize the enzyme within hours. That recovery is precisely why the low-dose selectivity for platelets exists."},
  "Aspirin permanently disables an enzyme inside the platelet, and platelets have no nucleus so they cannot build a replacement. You have to wait for the bone marrow to make a fresh supply, which takes about a week.",
  exim="fig_slide_platelet",
  excap="Lecture slide: platelet activation and the antiplatelet targets — aspirin acts at the thromboxane arm, upstream of the final fibrinogen bridge.")

# ── 17. Clopidogrel and the wrong proton pump inhibitor (§16) ─────────────────
q("A 61-year-old man underwent percutaneous coronary intervention with a drug-eluting stent 6 weeks ago and takes aspirin 81 mg and clopidogrel 75 mg daily. He now reports 2 weeks of burning epigastric discomfort and acid regurgitation. He has no melena, no weight loss, and no dysphagia. His temperature is 36.8°C (98.2°F), pulse is 74/min, and blood pressure is 128/76 mm Hg. Physical examination shows mild epigastric tenderness without guarding.\n\nLaboratory studies show:\nHemoglobin 13.9 g/dL (N=13.5–17.5 g/dL)\nHematocrit 41% (N=41%–53%)\nPlatelet count 244,000/mm3 (N=150,000–400,000/mm3)\n\nTest of the stool for occult blood is negative. His primary care physician had prescribed omeprazole 3 days ago. Which of the following is the most appropriate next step in management?",
  ["A. Continue omeprazole and increase the clopidogrel maintenance dose",
   "B. Discontinue antiplatelet therapy until the reflux resolves",
   "C. Replace clopidogrel with warfarin",
   "D. Replace omeprazole with pantoprazole",
   "E. Stop the proton pump inhibitor and use antacids as needed"],
  3,
  "Clopidogrel is a PRODRUG. It has no antiplatelet activity until CYP2C19 converts it to its active metabolite, which then irreversibly blocks the P2Y12 (ADP) receptor. Omeprazole is a CYP2C19 inhibitor → less active metabolite is formed → platelet inhibition is blunted — a genuine hazard 6 weeks after a drug-eluting stent, where inadequate inhibition risks stent thrombosis.\n\nPantoprazole is the answer because it does not meaningfully inhibit CYP2C19 while giving the same acid suppression. He needs a proton pump inhibitor: he is on dual antiplatelet therapy with reflux symptoms, and that is exactly the population in whom gastroprotection reduces bleeding.\n\nThe alternative is to change the antiplatelet rather than the acid drug — ticagrelor is not a prodrug and has no CYP2C19 dependency, at the cost of its own quirks (dyspnea, bradyarrhythmias, and a requirement that maintenance aspirin stay at or below 100 mg daily).\n\nThe same enzyme explains a second phenomenon worth knowing: genetic CYP2C19 poor metabolizers get little benefit from clopidogrel no matter what else they take, which is why some centres genotype before choosing a P2Y12 inhibitor.\n\nThe memory hook: CLOpidogrel needs a CLOck — it is a prodrug that needs time and an enzyme.",
  {"0": "Doubling clopidogrel does not reliably overcome CYP2C19 inhibition, because the bottleneck is enzymatic conversion rather than drug supply. It adds bleeding risk from whatever active metabolite is formed, without guaranteeing adequate platelet inhibition.",
   "1": "Stopping antiplatelet therapy 6 weeks after a drug-eluting stent is the most dangerous option on the list. Premature discontinuation of dual antiplatelet therapy is a leading cause of stent thrombosis, which carries a high mortality; his symptoms are reflux, not bleeding.",
   "2": "Warfarin is an anticoagulant and does not prevent platelet-rich arterial thrombosis on a stent. Substituting it would leave the stent inadequately protected while adding bleeding risk — the wrong class of drug for a white clot.",
   "4": "Antacids provide symptomatic relief but far less acid suppression, and they leave a patient on dual antiplatelet therapy without gastroprotection. The problem is which proton pump inhibitor, not whether to have one."},
  "Clopidogrel arrives inactive and needs a liver enzyme to switch it on — and omeprazole blocks that exact enzyme. Swapping to a different stomach-acid drug that leaves the enzyme alone fixes it.",
  exim="fig_slide_kp_antiplatelet",
  excap="Lecture slide summarizing the antiplatelet drugs, including the CYP2C19 dependence that separates clopidogrel from ticagrelor.")

# ── 18. Prasugrel and the prior stroke (§16) ──────────────────────────────────
q("A 78-year-old man is admitted with a non-ST-elevation myocardial infarction and is scheduled for percutaneous coronary intervention. He had a transient ischemic attack 14 months ago with complete resolution of symptoms, and takes aspirin. He weighs 58 kg (128 lb). His temperature is 36.9°C (98.4°F), pulse is 88/min, and blood pressure is 142/84 mm Hg.\n\nLaboratory studies show:\nHemoglobin 12.8 g/dL (N=13.5–17.5 g/dL)\nHematocrit 38% (N=41%–53%)\nPlatelet count 228,000/mm3 (N=150,000–400,000/mm3)\nCreatinine 1.2 mg/dL (N=0.6–1.2 mg/dL)\nTroponin I 3.4 ng/mL (N=≤0.04 ng/mL)\n\nAddition of a P2Y12 inhibitor is planned. Which of the following agents is contraindicated in this patient?",
  ["A. Cangrelor",
   "B. Clopidogrel",
   "C. Prasugrel",
   "D. Ticagrelor",
   "E. Vorapaxar"],
  2,
  "Prasugrel is contraindicated in any patient with a history of stroke or transient ischemic attack. In the TRITON-TIMI 38 trial those patients had net clinical HARM — the excess of intracranial hemorrhage outweighed the ischemic benefit — and the finding is a boxed contraindication.\n\nThis man also carries both of prasugrel's other caution flags, which is what makes him the illustrative case: age 75 years or older, and weight below 60 kg. He is 78 and weighs 58 kg. Prasugrel is the most potent of the irreversible P2Y12 inhibitors, and its potency is bought with bleeding.\n\nThe memory hook: PRAsugrel is PROhibited after a stroke.\n\nWhat to use instead: clopidogrel, which is weaker but far better tolerated in the elderly and in the underweight, or ticagrelor, which is reversible, is not a prodrug, and has no stroke contraindication — bearing in mind its dyspnea, its bradyarrhythmias, and the requirement to keep maintenance aspirin at or below 100 mg daily.",
  {"0": "Cangrelor is an intravenous, reversible P2Y12 inhibitor with onset and offset in minutes, used as a bridge during percutaneous coronary intervention in a patient who cannot swallow. It carries no stroke contraindication, and its short action is an advantage in a patient at high bleeding risk.",
   "1": "Clopidogrel is the standard alternative here and is not contraindicated by prior stroke — indeed it is indicated for secondary stroke prevention. Its limitation is CYP2C19-dependent variability in response, not neurologic history.",
   "3": "Ticagrelor is a reasonable choice in this patient: reversible, not a prodrug, and without a stroke contraindication. Its cautions are dyspnea, bradyarrhythmias, and keeping maintenance aspirin at or below 100 mg daily, since higher doses blunt its benefit.",
   "4": "Vorapaxar is absolutely contraindicated after stroke, transient ischemic attack or intracranial hemorrhage — so the statement is true of it as well. But vorapaxar is a PAR-1 antagonist used as an ADD-ON for secondary prevention in chronic disease; it is not a P2Y12 inhibitor and is not among the agents being chosen between for acute percutaneous coronary intervention."},
  "This particular drug is the strongest of its family, and in people who have had a stroke or mini-stroke it causes more bleeding in the brain than the benefit it gives. He has had one, is elderly, and is light — three strikes.",
  exim="fig_slide_kp_antiplatelet",
  excap="Lecture slide: the antiplatelet drugs and their contraindications, including prasugrel's prohibition after stroke or transient ischemic attack.")

# ── 19. Ticagrelor's signature adverse effect (§16) ───────────────────────────
q("A 59-year-old man began aspirin 81 mg and ticagrelor 90 mg twice daily after percutaneous coronary intervention 2 weeks ago. He comes to the office because of a sensation of breathlessness that began a few days after discharge. It occurs at rest as well as on exertion, lasts a few minutes, and is not associated with chest pain, cough, wheeze, orthopnea, or leg swelling. He has not had fever or hemoptysis. His temperature is 36.9°C (98.4°F), pulse is 62/min, respirations are 16/min, and blood pressure is 124/76 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 98%. Physical examination shows clear lung fields, no jugular venous distention, and no peripheral edema.\n\nLaboratory studies show:\nHemoglobin 13.8 g/dL (N=13.5–17.5 g/dL)\nHematocrit 41% (N=41%–53%)\nPlatelet count 232,000/mm3 (N=150,000–400,000/mm3)\nB-type natriuretic peptide 44 pg/mL (N=<100 pg/mL)\nD-dimer 180 ng/mL (N=≤250 ng/mL)\n\nChest radiography shows no abnormalities and electrocardiography shows sinus rhythm at 62/min. Which of the following is the most likely explanation for his symptom?",
  ["A. Adverse effect of ticagrelor",
   "B. Anemia from occult gastrointestinal bleeding",
   "C. Aspirin-exacerbated respiratory disease",
   "D. Pulmonary edema from left ventricular dysfunction",
   "E. Pulmonary embolism"],
  0,
  "Dyspnea is ticagrelor's signature adverse effect, occurring in roughly 10 to 15% of patients. It typically begins within the first week, comes in short episodes at rest as well as on exertion, and is not accompanied by hypoxemia or any abnormality on examination or imaging — exactly as described here.\n\nThe mechanism is thought to be adenosine-related: ticagrelor inhibits the equilibrative nucleoside transporter, raising local adenosine concentrations, which stimulate pulmonary vagal C fibers. The same adenosine effect explains its other quirk, ventricular pauses and bradyarrhythmias — note his pulse of 62/min.\n\nRecognizing it matters because the alternative is to stop dual antiplatelet therapy 2 weeks after a stent, which risks stent thrombosis. The dyspnea is benign and usually self-limited; it can be tolerated with reassurance, and if intolerable the answer is to switch to clopidogrel rather than to stop antiplatelet therapy altogether.\n\nThe rest of the ticagrelor profile: reversible P2Y12 blockade, NOT a prodrug (so no CYP2C19 problem), twice-daily dosing, and a requirement that maintenance aspirin stay at or below 100 mg daily — above that the benefit is lost.\n\nThe memory hook: TIcagrelor makes you TIred of breathing.",
  {"1": "Occult bleeding is a real hazard of dual antiplatelet therapy and would explain dyspnea through anemia — which is why it belongs on the list. His hemoglobin is 13.8 g/dL, entirely normal, so there is no anemia to cause symptoms.",
   "2": "Aspirin-exacerbated respiratory disease presents with bronchospasm, nasal polyps and rhinitis, usually in a patient with known asthma, within hours of an aspirin dose. He has no wheeze, no polyps, and normal lung fields, and he has taken aspirin without difficulty.",
   "3": "Pulmonary edema after a recent myocardial infarction is an important consideration, but it would come with orthopnea, crackles, jugular venous distention, radiographic congestion and a raised B-type natriuretic peptide. His is 44 pg/mL with a clear chest radiograph.",
   "4": "Pulmonary embolism causes dyspnea with tachycardia and often hypoxemia. His oxygen saturation is 98%, his pulse is 62/min, and his D-dimer of 180 ng/mL is normal — in a low-probability patient that effectively excludes it."},
  "The drug raises a natural chemical that irritates the nerves in the lungs, so patients feel breathless even though their lungs and heart are fine. It is harmless, and stopping the drug after a recent stent would be far more dangerous.",
  exim="fig_slide_kp_antiplatelet",
  excap="Lecture slide: the P2Y12 inhibitors side by side — reversibility, prodrug status, and the adverse effects that distinguish them.")

# ── 20. Glycoprotein IIb/IIIa inhibitors (§16) ────────────────────────────────
q("A 63-year-old man with an ST-elevation myocardial infarction undergoes emergency percutaneous coronary intervention. He receives aspirin, ticagrelor, unfractionated heparin, and an infusion of eptifibatide during the procedure. He has never received heparin before. Six hours after the procedure, routine laboratory studies are obtained. He has no bleeding and feels well. His temperature is 36.9°C (98.4°F), pulse is 76/min, and blood pressure is 124/74 mm Hg. Physical examination shows a small hematoma at the radial access site and no petechiae.\n\nLaboratory studies show:\nHemoglobin 13.6 g/dL (N=13.5–17.5 g/dL)\nHematocrit 40% (N=41%–53%)\nPlatelet count 19,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 13.0 seconds (N=11–15 seconds)\nPartial thromboplastin time 52 seconds (N=25–40 seconds)\nFibrinogen 368 mg/dL (N=200–400 mg/dL)\n\nHis platelet count was 214,000/mm3 before the procedure. A peripheral blood smear confirms markedly reduced platelets with no clumping and no schistocytes. Which of the following is the most likely cause?",
  ["A. Eptifibatide-induced thrombocytopenia",
   "B. Heparin-induced thrombocytopenia",
   "C. Immune thrombocytopenia",
   "D. Pseudothrombocytopenia from platelet clumping in EDTA",
   "E. Thrombotic thrombocytopenic purpura"],
  0,
  "The timing is the whole item: a platelet count of 214,000/mm3 falling to 19,000/mm3 within SIX HOURS. Glycoprotein IIb/IIIa inhibitors are the drugs that do this acutely, sometimes profoundly, and thrombocytopenia is their signature adverse effect alongside the strongest bleeding risk of any antiplatelet class.\n\nThe mechanism is immune: the drug binds the IIb/IIIa receptor and induces a conformational change that exposes neoepitopes, which pre-formed antibodies recognize — so the reaction can occur on first exposure and within hours.\n\nThe class blocks the final common pathway of platelet aggregation. Whichever door activated the platelet — thromboxane, ADP, or thrombin — the fibrinogen bridge between glycoprotein IIb/IIIa receptors is what actually sticks one platelet to the next, and eptifibatide and tirofiban prevent that bridge from forming. They are intravenous only, used in the catheterization laboratory and in acute coronary syndromes.\n\nManagement: stop the infusion (the effect of eptifibatide and tirofiban resolves over hours as it is reversible and renally cleared), monitor the count, and transfuse platelets only for serious bleeding.\n\nThe contrast with HIT is the point to carry: hours versus 5 to 10 days, and bleeding risk versus clotting risk.",
  {"1": "HIT requires antibody formation against the heparin–platelet factor 4 complex, which takes 5 to 10 days — or 'rapid onset' within hours ONLY in a patient exposed to heparin within the preceding 100 days. He has never received heparin before, so there is no pre-existing antibody, and HIT would also bring thrombosis rather than a bleeding tendency.",
   "2": "Immune thrombocytopenia is a diagnosis of exclusion that develops over days to weeks and has no relationship to a procedure 6 hours earlier. It would be the answer in an otherwise well outpatient with isolated thrombocytopenia and no drug exposure.",
   "3": "Pseudothrombocytopenia is a laboratory artifact in which EDTA-dependent antibodies clump platelets so the analyzer undercounts them — always worth excluding with a smear, which is why the stem reports one. The smear here shows genuinely reduced platelets with NO clumping.",
   "4": "Thrombotic thrombocytopenic purpura causes thrombocytopenia with a microangiopathic hemolytic anemia — schistocytes on the smear, a raised lactate dehydrogenase, and often neurologic or renal findings. His smear shows no schistocytes and his hemoglobin is normal."},
  "The drug he was given during the procedure blocks the final step that lets platelets stick together, and in a few people the immune system attacks the drug-coated platelets within hours. His count crashed the same afternoon, which no other cause does.",
  exim="fig_slide_platelet",
  excap="Lecture slide: however a platelet is activated, every path converges on glycoprotein IIb/IIIa and the fibrinogen bridge — the step this drug class blocks.")

# ── 21. Cilostazol and heart failure (§16) ────────────────────────────────────
q("A 68-year-old man with peripheral arterial disease comes to the office because of calf pain that reliably occurs after walking one block and resolves with rest. He also has heart failure with a left ventricular ejection fraction of 30%, for which he takes lisinopril, carvedilol, and furosemide. He takes aspirin 81 mg daily. His temperature is 36.8°C (98.2°F), pulse is 68/min, and blood pressure is 126/74 mm Hg. Physical examination shows diminished pedal pulses bilaterally, hair loss over both shins, and no edema; the lungs are clear. The ankle-brachial index is 0.62 on the right and 0.68 on the left.\n\nWhich of the following drugs is contraindicated in this patient?",
  ["A. Aspirin",
   "B. Cilostazol",
   "C. Clopidogrel",
   "D. Dipyridamole",
   "E. Ticagrelor"],
  1,
  "Cilostazol carries a BOXED warning: it is contraindicated in heart failure of any severity. It is a phosphodiesterase-3 inhibitor, and the PDE-3 inhibitors as a class — milrinone and others — increased mortality in heart failure trials, presumably through arrhythmia and increased myocardial oxygen demand driven by the rise in cyclic AMP.\n\nThe frustration of this case is that cilostazol is otherwise exactly the right drug: it is the agent with the best evidence for improving walking distance in intermittent claudication, and his symptoms are classic. His ejection fraction of 30% removes it from consideration entirely.\n\nThe mechanism is worth holding onto because it explains both the benefit and the harm. Inhibiting phosphodiesterase raises cyclic AMP inside the platelet → the platelet stays calm → less aggregation; the same cyclic AMP rise in vascular smooth muscle causes vasodilation, which is where the headache and flushing come from, and in the myocardium is where the trouble lies.\n\nWhat he gets instead: a supervised exercise program (the intervention with the strongest evidence of all), aggressive risk factor treatment with a statin and blood pressure control, smoking cessation, and continuation of an antiplatelet agent for cardiovascular protection.",
  {"0": "Aspirin is indicated in peripheral arterial disease for cardiovascular event reduction and has no heart failure contraindication — he is already taking it. Its cautions are gastrointestinal bleeding and, in children with viral illness, Reye syndrome.",
   "2": "Clopidogrel is a reasonable antiplatelet choice in peripheral arterial disease, with evidence of benefit over aspirin in the CAPRIE trial, and no heart failure contraindication. Its limitation is CYP2C19-dependent variability in activation.",
   "3": "Dipyridamole is also a phosphodiesterase inhibitor and causes headache and flushing through vasodilation, and it is used with caution in severe coronary disease because of coronary steal — but it does not carry a boxed contraindication in heart failure. The boxed warning is specific to cilostazol.",
   "4": "Ticagrelor is a P2Y12 inhibitor used in acute coronary syndromes; it has no role in claudication and no heart failure contraindication. Its adverse effects are dyspnea and bradyarrhythmias."},
  "The best drug for his leg pain when walking is one that props up a signalling chemical in cells — but that same effect proved deadly in people with weak hearts. With an ejection fraction of 30%, it is off the table.",
  exim="fig_slide_kp_antiplatelet",
  excap="Lecture slide: the antiplatelet families, including the phosphodiesterase inhibitors and the boxed warning that removes cilostazol in heart failure.")

# ── 22. White clot, red clot (§16) ────────────────────────────────────────────
q("A 69-year-old woman with newly diagnosed non-valvular atrial fibrillation is advised to begin apixaban for stroke prevention. She says she would rather take aspirin, which she has read is a blood thinner, is cheaper, and does not require a prescription. She has no prior stroke, no bleeding history, and normal renal function. Her temperature is 36.9°C (98.4°F), pulse is 92/min and irregularly irregular, and blood pressure is 134/80 mm Hg. Physical examination shows no murmur and no signs of heart failure. Echocardiography shows normal valves and a left ventricular ejection fraction of 58%.\n\nWhich of the following best explains why aspirin is inadequate for this indication?",
  ["A. Aspirin inhibits only cyclooxygenase-2 at over-the-counter doses",
   "B. Aspirin inhibits thromboxane-mediated platelet aggregation, which is not the dominant mechanism of a stasis thrombus",
   "C. Aspirin is inactivated by the endothelium of the left atrium",
   "D. Atrial thrombi are composed primarily of aggregated platelets",
   "E. Factor Xa inhibitors prevent platelet aggregation more effectively than aspirin does"],
  1,
  "Two kinds of clot, two kinds of drug — the single distinction that answers a surprising number of 'which drug' questions.\n\nARTERIAL clots are platelet-rich 'WHITE clots': high shear, a ruptured atherosclerotic plaque, platelets piling onto exposed collagen. These are the province of antiplatelet drugs — myocardial infarction, ischemic stroke from plaque, peripheral arterial disease, stents.\n\nVENOUS and STASIS clots are fibrin-and-red-cell-rich 'RED clots': slow or stagnant flow, coagulation factors activating in a quiet corner. These need anticoagulants — deep vein thrombosis, pulmonary embolism, and the thrombus that forms in a fibrillating left atrial appendage.\n\nHer clot is a stasis clot forming in an appendage that is no longer contracting. Blocking thromboxane-mediated platelet recruitment does little about a fibrin mesh, which is why aspirin is substantially inferior to anticoagulation for stroke prevention in atrial fibrillation — the AVERROES trial compared apixaban with aspirin in patients unsuitable for warfarin and was stopped early for apixaban's clear superiority, without an excess of major bleeding.\n\nThe memory hook: White = Wall of the artery = platelets. Red = Resting vein = fibrin. Fast blood makes white clots; slow blood makes red ones. It is also why aspirin is not the answer for a deep vein thrombosis.",
  {"2": "There is no endothelial inactivation of aspirin specific to the left atrium. Aspirin acts on platelets in the portal and systemic circulation and its effect is systemic and lifelong for each platelet — the failure here is one of target, not of delivery.",
   "0": "The relationship is the reverse: low-dose aspirin is relatively selective for cyclooxygenase-1 in platelets, and it is at HIGHER doses that endothelial cyclooxygenase-2 is also inhibited — which reduces prostacyclin and can work against the antiplatelet aim. Over-the-counter low-dose aspirin does inhibit platelet cyclooxygenase-1 effectively.",
   "3": "This inverts the composition of the clot. If atrial thrombi were platelet-rich, aspirin would be a reasonable choice; they are fibrin-and-red-cell-rich stasis thrombi, which is exactly why an anticoagulant is required.",
   "4": "Factor Xa inhibitors do not prevent platelet aggregation at all — they interrupt the coagulation cascade at factor Xa, upstream of thrombin and fibrin. Claiming they are better antiplatelet agents misattributes their mechanism; they work because they target the right kind of clot."},
  "Clots in fast-moving arteries are built from platelets, and aspirin blocks platelets. Clots in a quivering, stagnant heart chamber are built from fibrin instead, and you need a drug that interrupts the clotting cascade to stop those.",
  exim="fig_slide_anticoag_classes",
  excap="Lecture slide: anticoagulants interrupt the coagulation cascade — the fibrin-forming machinery that builds a stasis clot, which antiplatelet drugs leave untouched.")

# ── 23. What a thrombolytic actually does (§16) ───────────────────────────────
q("A 64-year-old man is brought to the emergency department 80 minutes after the sudden onset of right-sided weakness and inability to speak. His temperature is 36.9°C (98.4°F), pulse is 86/min, respirations are 16/min, and blood pressure is 158/88 mm Hg. Physical examination shows a dense right hemiparesis and expressive aphasia. Serum glucose is 104 mg/dL (N=70–100 mg/dL), platelet count is 242,000/mm3 (N=150,000–400,000/mm3), and international normalized ratio is 1.0 (N=0.8–1.2). CT scan of the head without contrast shows no hemorrhage and no established infarct. Intravenous alteplase is administered.\n\nWhich of the following best describes the mechanism of action of this drug?",
  ["A. Activation of antithrombin, accelerating inhibition of thrombin and factor Xa",
   "B. Conversion of plasminogen to plasmin, which degrades the fibrin mesh",
   "C. Direct competitive inhibition of the active site of factor Xa",
   "D. Inhibition of the glycoprotein IIb/IIIa fibrinogen receptor",
   "E. Irreversible blockade of the platelet P2Y12 receptor"],
  1,
  "Every other drug in this block PREVENTS a clot. The fibrinolytics destroy one that already exists.\n\nAlteplase is recombinant tissue plasminogen activator. It converts plasminogen to plasmin, and plasmin digests the fibrin mesh holding the clot together. The debris of that digestion is what the D-dimer assay measures — fibrin degradation products.\n\nThey are described as relatively fibrin-SELECTIVE, because they act best on plasminogen already bound to a clot. 'Relatively' is doing a great deal of work in that sentence, which is why systemic bleeding — and intracranial hemorrhage above all — is the defining risk of the class.\n\nThe agents: alteplase, the reference drug for acute ischemic stroke, given as an infusion (Cathflo is the low-dose version used only to unclog a central catheter); reteplase, two boluses 30 minutes apart; and tenecteplase, a single intravenous bolus with a longer half-life and greater fibrin specificity, now FDA-approved for acute ischemic stroke — the convenience of one push is why it is displacing alteplase.\n\nThe memory hook: everything ending in -plase is a plasminogen activator. It turns on the demolition crew.",
  {"0": "Accelerating antithrombin is how the heparins work. They prevent new fibrin from forming but do nothing to dissolve fibrin that has already polymerized, which is why heparin alone does not reopen an occluded cerebral artery.",
   "2": "Direct factor Xa inhibition is the mechanism of the -xabans and, indirectly, of fondaparinux. Like all anticoagulants they stop a clot growing rather than break one down, and they are given orally for prevention, not as an acute reperfusion therapy.",
   "3": "Blocking the glycoprotein IIb/IIIa receptor is eptifibatide and tirofiban — the final common pathway of platelet aggregation. That prevents platelets from bridging to one another, but it does not touch an established fibrin mesh.",
   "4": "Irreversible P2Y12 blockade describes clopidogrel and prasugrel. Antiplatelet drugs are for preventing arterial thrombosis and its recurrence; they have no lytic activity and would not restore flow through an occluded artery within the treatment window."},
  "Blood thinners stop new clots forming, but this drug is different — it switches on the body's own demolition enzyme to chew up the clot that is already blocking the artery. That is also why it can cause bleeding anywhere.",
  exim="fig_slide_fibrinolysis",
  excap="Lecture slide: tissue plasminogen activator converts plasminogen to plasmin, which degrades fibrin into the fragments measured as D-dimer.")

# ── 24. Bleeding after thrombolysis (§16) ─────────────────────────────────────
q("A 71-year-old woman is receiving intravenous alteplase for an acute ischemic stroke. Two hours into treatment she develops a severe headache, vomits, and becomes progressively less responsive. Her pulse falls from 88/min to 52/min and her blood pressure rises from 152/86 mm Hg to 198/104 mm Hg. Physical examination shows a dilated, poorly reactive left pupil and worsening right hemiparesis. The infusion is stopped immediately.\n\nLaboratory studies show:\nHemoglobin 12.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 37% (N=36%–46%)\nPlatelet count 226,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 18 seconds (N=11–15 seconds)\nPartial thromboplastin time 48 seconds (N=25–40 seconds)\nFibrinogen 74 mg/dL (N=200–400 mg/dL)\nD-dimer 8,200 ng/mL (N=≤250 ng/mL)\n\nCT scan of the head without contrast shows a large left intraparenchymal hemorrhage with midline shift. In addition to neurosurgical consultation, which of the following is the most appropriate treatment?",
  ["A. Cryoprecipitate and tranexamic acid",
   "B. Idarucizumab",
   "C. Platelet transfusion and desmopressin",
   "D. Protamine sulfate",
   "E. Vitamin K and four-factor prothrombin complex concentrate"],
  0,
  "Intracranial hemorrhage is the feared complication of thrombolysis, and the reversal is the exact mirror image of the drug's mechanism — replace what plasmin consumed, and stop plasmin from being made.\n\n• CRYOPRECIPITATE replaces fibrinogen. Her level of 74 mg/dL, with a D-dimer of 8,200 ng/mL, shows how thoroughly plasmin has digested it; below roughly 150 mg/dL a clot cannot form at all.\n• TRANEXAMIC ACID (or aminocaproic acid) blocks the conversion of plasminogen to plasmin, halting the demolition. These antifibrinolytics are the stop-work order for the crew the -plase drug called in.\n\nAlongside that: stop the infusion (already done), urgent imaging (done), blood pressure control, and neurosurgery. Her bradycardia with hypertension and a blown pupil signal raised intracranial pressure and herniation, which is its own emergency.\n\nThe contraindication list exists precisely because this can happen, and it follows from 'you are about to dissolve every clot in the body': any prior intracranial hemorrhage, ischemic stroke within 3 months, known intracranial neoplasm or vascular malformation, suspected aortic dissection, active internal bleeding or a bleeding diathesis, significant closed head trauma within 3 months, and severe uncontrolled hypertension.\n\nThe memory hook: -plase dissolves, TXA restores.",
  {"1": "Idarucizumab is the monoclonal antibody fragment that reverses DABIGATRAN, a direct thrombin inhibitor. It binds that specific drug and has no effect on plasmin, fibrinogen, or a plasminogen activator.",
   "2": "Platelets and desmopressin address platelet-related bleeding — after antiplatelet drugs, in uremia, or in von Willebrand disease. Her platelet count is 226,000/mm3 and the defect is a dissolved fibrin mesh with a fibrinogen of 74 mg/dL, which platelets cannot substitute for.",
   "3": "Protamine neutralizes heparin by ionic binding. She is not on heparin, and protamine does nothing to plasmin or to a plasminogen activator.",
   "4": "Vitamin K plus prothrombin complex concentrate is warfarin reversal — it restores the vitamin K-dependent factors II, VII, IX and X. Her factors were never depleted by warfarin; her fibrinogen was digested by plasmin, and prothrombin complex concentrates contain little to no fibrinogen."},
  "The drug turned on an enzyme that chews up clots, and it has now chewed up the protein her blood needs to clot anywhere. She needs that protein replaced and the chewing switched off.",
  exim="fig_slide_fibrinolysis",
  excap="Lecture slide: the fibrinolysis pathway. Antifibrinolytics such as tranexamic acid block the plasminogen-to-plasmin step that the -plase drugs activate.")

# ── 25. Who must not receive a thrombolytic (§16) ─────────────────────────────
q("A 58-year-old man is brought to the emergency department 2 hours after the abrupt onset of left facial droop, left arm weakness, and slurred speech. He takes aspirin 81 mg daily and atorvastatin. His temperature is 36.8°C (98.2°F), pulse is 78/min and irregularly irregular, respirations are 16/min, and blood pressure is 148/88 mm Hg. Physical examination shows a left hemiparesis and dysarthria. Electrocardiography shows atrial fibrillation.\n\nLaboratory studies show:\nHemoglobin 14.0 g/dL (N=13.5–17.5 g/dL)\nHematocrit 42% (N=41%–53%)\nPlatelet count 238,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 12.6 seconds (N=11–15 seconds)\nInternational normalized ratio 1.1 (N=0.8–1.2)\nGlucose 140 mg/dL (N=70–100 mg/dL)\n\nCT scan of the head without contrast shows no hemorrhage. Intravenous thrombolysis is being considered. Which of the following features of this case is a contraindication to treatment?",
  ["A. Atrial fibrillation on the electrocardiogram",
   "B. Blood pressure of 148/88 mm Hg",
   "C. Ischemic stroke 6 weeks ago",
   "D. Serum glucose concentration of 140 mg/dL",
   "E. Treatment with aspirin 81 mg daily"],
  2,
  "An ischemic stroke within the PREVIOUS 3 MONTHS is a contraindication to thrombolysis. Recently infarcted brain has a disrupted blood-brain barrier and fragile new vessels, so dissolving clot systemically carries a high risk of hemorrhagic transformation into the old infarct as well as bleeding at the new one.\n\nThe list follows from a single idea — you are about to dissolve every clot in the body — and is worth knowing as a list:\n• Any prior intracranial hemorrhage\n• Ischemic stroke within 3 months\n• Known intracranial neoplasm or vascular malformation\n• Suspected aortic dissection\n• Active internal bleeding or a bleeding diathesis\n• Significant closed head trauma within 3 months\n• Severe uncontrolled hypertension\n\nEverything else in this vignette is deliberately a near-miss that does NOT prohibit treatment, and recognizing the non-contraindications is as useful as knowing the list: atrial fibrillation is the likely SOURCE of his embolus, not an obstacle; a blood pressure of 148/88 mm Hg is below the 185/110 mm Hg threshold; a glucose of 140 mg/dL is mildly raised but nowhere near the hypoglycemia or marked hyperglycemia that can mimic stroke; and antiplatelet therapy with aspirin is not a contraindication, although anticoagulation with a therapeutic INR would be.\n\nHe is inside the 4.5-hour window, so the decision turns entirely on the contraindication list.",
  {"0": "Atrial fibrillation is the most likely cause of a cardioembolic stroke, and thrombolysis is used routinely in these patients. It becomes relevant afterwards, when anticoagulation is started for secondary prevention — deliberately delayed for several days after thrombolysis.",
   "1": "Severe uncontrolled hypertension is a genuine contraindication, but the threshold is a blood pressure above 185/110 mm Hg, which must be lowered before treatment. At 148/88 mm Hg he is comfortably below it.",
   "3": "Glucose is checked because profound hypoglycemia can mimic a stroke and marked hyperglycemia worsens outcome — a value of 140 mg/dL is neither. Glucose is a stroke MIMIC screen, not a bleeding risk.",
   "4": "Aspirin is not a contraindication to thrombolysis, and most patients presenting with stroke are already taking an antiplatelet drug. Full anticoagulation with a therapeutic INR is a different matter, but his INR is 1.1."},
  "He had a stroke six weeks ago, and that damaged brain tissue is still fragile. Giving a drug that dissolves clots everywhere would very likely make the old area bleed.",
  exim="fig_slide_fibrinolysis",
  excap="Lecture slide: thrombolytic mechanism. Because the drug acts on plasminogen throughout the body, the contraindications are a list of places that must not be allowed to bleed.")
