# Jeevs Edition — Batch 10: Anemia Pharmacology, part 2
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §17 s16-anemia-drugs — hydroxyurea, oral iron formulations, the ESA cancer boxed
#                          warning, ferumoxytol, complement inhibitors  (LO 9, 70, 72)
# Options alphabetised; "correct" is the 0-based index AFTER alphabetisation.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ── 1. Hydroxyurea in sickle cell disease (§17) ───────────────────────────────
q("A 14-year-old boy with hemoglobin SS disease is brought to the office for follow-up. During the past year he has had five episodes of severe bone pain requiring opioids and two hospitalizations for acute chest syndrome. He takes folic acid and penicillin prophylaxis and has received all recommended vaccinations. He is adherent to therapy. His temperature is 36.8°C (98.2°F), pulse is 88/min, and blood pressure is 112/68 mm Hg. Physical examination shows scleral icterus and no splenomegaly. A peripheral blood smear is shown.\n\nLaboratory studies show:\nHemoglobin 7.9 g/dL (N=13.0–16.0 g/dL)\nHematocrit 24% (N=37%–49%)\nMean corpuscular volume 89 µm3 (N=80–100 µm3)\nReticulocyte count 9.4% (N=0.5%–1.5%)\nLeukocyte count 13,200/mm3 (N=4,500–11,000/mm3)\nPlatelet count 448,000/mm3 (N=150,000–400,000/mm3)\nHemoglobin F 3.1% (N=<2%)\n\nA daily oral agent is started at 15 mg/kg. Which of the following is the principal mechanism by which this drug will reduce the frequency of his pain episodes?",
  ["A. Activation of erythrocyte pyruvate kinase, increasing cellular energy",
   "B. Increased production of fetal hemoglobin, which cannot enter the sickle polymer",
   "C. Inhibition of erythrocyte adhesion by blockade of endothelial P-selectin",
   "D. Stimulation of committed erythroid progenitors through the erythropoietin receptor",
   "E. Unblocking of the final stage of erythroid maturation"],
  1,
  "Hydroxyurea, 15 mg/kg once daily. Its central action in sickle cell disease is induction of fetal hemoglobin, and the reason that works is structural: HbF contains gamma chains in place of beta chains, and the deoxyhemoglobin S polymer cannot incorporate a gamma chain. Every HbF tetramer inside a red cell is a molecule that cannot join the rigid fiber, so the cell takes longer to sickle in a capillary — often longer than the transit time, so it never sickles at all.\n\nThe number to carry: HbF of 20% or more reduces acute complications. His is 3.1%, which is why he is having crises.\n\nHydroxyurea also does four other useful things at once — it raises nitric oxide, lowers the neutrophil and monocyte counts (his leukocyte count is 13,200/mm3, and those cells are part of the vaso-occlusive event), increases red cell deformability, and decreases adhesion of red cells to endothelium.\n\nThe warnings follow from what the drug actually is: an antineoplastic agent moonlighting as a sickle cell drug. Two boxed warnings — severe myelosuppression, and carcinogenicity. Monitor the blood count. Also expect dry skin and hyperpigmentation of the nails.",
  {"0": "Activation of pyruvate kinase is the mechanism of mitapivat, an oral agent that increases cellular energy and keeps red cells alive longer. It is approved for pyruvate kinase deficiency and for the thalassemias, not as the standard disease-modifying drug for sickle cell disease.",
   "2": "Blockade of P-selectin is the mechanism of crizanlizumab, a monoclonal antibody that does reduce vaso-occlusive crises by interrupting the adhesion step. It is an intravenous infusion, not a 15 mg/kg daily oral agent, and it does not raise fetal hemoglobin.",
   "3": "Stimulation of committed erythroid progenitors through the erythropoietin receptor describes the erythropoiesis-stimulating agents. His reticulocyte count is 9.4% — the marrow is already being driven maximally by his own erythropoietin, and more signal would not stop the sickling.",
   "4": "Unblocking the final stage of erythroid maturation is luspatercept, which is for the ineffective erythropoiesis of beta thalassemia and low-risk myelodysplastic syndrome. His marrow releases cells perfectly well; they are destroyed afterwards, which is a different problem."},
  "His red cells collapse into a stiff rod shape because of one abnormal hemoglobin. The drug makes his body restart the baby version of hemoglobin, and that version physically cannot join the rod — so the cells stay round long enough to get through the small vessels.",
  image="fig_sickle_smear",
  imcap="Peripheral blood smear from the patient.",
  exim="fig_slide_sickle_complications",
  excap="The complications hydroxyurea is prescribed to prevent — the vaso-occlusive column on the left, and the chronic hemolytic column on the right.")

# ── 2. The formulation that arrives too late (§17) ────────────────────────────
q("A 29-year-old woman is evaluated for persistent iron deficiency anemia attributed to heavy menstrual bleeding, now controlled with a levonorgestrel intrauterine device. For the past 3 months she has taken an over-the-counter enteric-coated ferrous sulfate tablet each morning with orange juice, and she has not missed a dose. She has had no nausea, constipation, or abdominal discomfort. She takes no antacid, histamine-2 receptor antagonist, or proton pump inhibitor. She has no diarrhea and no family history of celiac disease.\n\nLaboratory studies show:\nHemoglobin 10.1 g/dL (N=12.0–16.0 g/dL)\nHematocrit 30% (N=36%–46%)\nMean corpuscular volume 76 µm3 (N=80–100 µm3)\nReticulocyte count 1.1% (N=0.5%–1.5%)\nSerum ferritin 9 ng/mL (N=10–120 ng/mL)\nTotal iron-binding capacity 441 µg/dL (N=250–400 µg/dL)\n\nHer hemoglobin was 9.9 g/dL when the iron was started. Which of the following best explains the failure of her therapy?",
  ["A. Chelation of the iron by ascorbic acid taken with the dose",
   "B. Impaired reduction of ferric to ferrous iron from gastric acid suppression",
   "C. Release of the iron distal to the site of absorption",
   "D. Suppression of ferroportin by hepcidin induced by the preceding dose",
   "E. Undisclosed nonadherence because of gastrointestinal intolerance"],
  2,
  "The whole question turns on one word in the drug name: enteric-coated. Iron is absorbed in the DUODENUM and nowhere else of consequence. An enteric coating is designed to survive the stomach and dissolve further down the tube — which means the iron is released past the only window where it can be taken up. Sustained-release preparations do the same thing for the same reason.\n\nThe memory hook: E-C and S-R are D-O-A. Enteric-Coated and Sustained-Release arrive Dead On Arrival, downstream of the absorption window.\n\nThe cruel irony is that patients choose these formulations precisely because they are gentler — the coating that prevents the gastric irritation is the coating that prevents the absorption. Her complete absence of gastrointestinal symptoms, in a woman taking ferrous sulfate, is the buried clue rather than a reassurance.\n\nThe fix is a plain ferrous salt: ferrous sulfate 325 mg (~65 mg elemental iron), ferrous gluconate 325 mg (~36 mg, often better tolerated), or ferrous fumarate 325 mg (~106 mg, most concentrated and most upsetting). Ferric maltol is the alternative when salt intolerance is the barrier, since the iron is absorbed off the maltol molecule rather than as a salt. Keep the orange juice — ascorbic acid lowers pH and reduces Fe³⁺ to Fe²⁺, and helps.",
  {"0": "Ascorbic acid does the opposite of chelating iron away: it drops the pH and reduces Fe³⁺ to Fe²⁺, the only form that crosses the gut wall. Taking iron with orange juice is a recommendation, not an error, and it is one of the few things she is doing right.",
   "1": "Acid suppression is a genuine and common cause of oral iron failure — antacids, histamine-2 receptor antagonists and proton pump inhibitors all raise gastric pH so that ferric iron is never reduced. The stem excludes all three explicitly, which is what makes the formulation the answer.",
   "3": "Hepcidin induction is real physiology and the reason alternate-day dosing now looks better than multiple daily doses: each dose closes the ferroportin door for roughly a day, so a second dose that same day runs into it. She takes one tablet each morning, so this is not what is blocking her.",
   "4": "Silent nonadherence from gastrointestinal side effects is the single most common reason an apparent treatment failure is not a treatment failure at all — metallic taste, nausea, constipation, dark stools. She reports no symptoms and no missed doses, and the stem gives an alternative explanation that fits the absent symptoms rather than contradicting them."},
  "Iron can only be absorbed in one short stretch of gut just past the stomach. Her tablet has a coating that keeps it sealed until it is already past that stretch, so the iron is delivered to a place that cannot take it in.",
  exim="fig_slide_iron_ae",
  excap="Lecture slide: the adverse effects of iron therapy — the reason patients reach for the coated formulations in the first place.")

# ── 3. The ESA cancer boxed warning (§17) ─────────────────────────────────────
q("A 61-year-old man with stage III squamous cell carcinoma of the oropharynx is receiving concurrent cisplatin and radiation therapy with curative intent; he is in week 4 of a planned 7-week course. He reports fatigue that limits his usual walking but no dyspnea, chest pain, or lightheadedness. He has had no bleeding. His temperature is 36.7°C (98.1°F), pulse is 86/min, respirations are 16/min, and blood pressure is 124/76 mm Hg.\n\nLaboratory studies show:\nHemoglobin 9.6 g/dL (N=13.0–16.0 g/dL)\nHematocrit 29% (N=37%–49%)\nMean corpuscular volume 88 µm3 (N=80–100 µm3)\nReticulocyte count 1.2% (N=0.5%–1.5%)\nSerum ferritin 186 ng/mL (N=20–250 ng/mL)\nTransferrin saturation 27% (N=20%–50%)\nSerum creatinine 0.9 mg/dL (N=0.6–1.2 mg/dL)\n\nThe covering resident proposes starting epoetin alfa to spare him a transfusion. Which of the following is the most appropriate response?",
  ["A. Begin darbepoetin alfa instead, targeting a hemoglobin concentration of 12 g/dL",
   "B. Begin epoetin alfa and discontinue it when the chemoradiation course is finished",
   "C. Begin intravenous iron first, then add epoetin alfa if the hemoglobin does not respond",
   "D. Do not begin an erythropoiesis-stimulating agent, because the hemoglobin concentration is above 8 g/dL",
   "E. Do not begin an erythropoiesis-stimulating agent, because the treatment is intended to be curative"],
  4,
  "The cancer boxed warning for the erythropoiesis-stimulating agents has three clauses, and this vignette is built on the third:\n\n• Use in cancer ONLY for anemia caused by concurrent myelosuppressive chemotherapy.\n• DISCONTINUE when the chemotherapy course is finished.\n• DO NOT USE when the anticipated outcome is CURE.\n\nHe is receiving chemoradiation with curative intent for a stage III head and neck cancer. Erythropoietin receptors are expressed on some tumours, and the trials showed shortened overall survival and increased tumour progression or recurrence — specifically in breast, cervical, HEAD AND NECK, lymphoid and non-small cell lung cancer. Trading a possible cure for the avoidance of a transfusion is the wrong trade, and that is the whole point of the warning.\n\nManage him instead: watchful monitoring, treat any correctable cause, and transfuse if he becomes symptomatic or drops below the threshold. His iron studies are normal — ferritin 186 ng/mL with a transferrin saturation of 27% — so this is the marrow suppression of cisplatin, not a deficiency.\n\nThe frame that keeps all four boxed warnings straight: every one of them ends with the same sentence — use the lowest dose needed to avoid transfusion.",
  {"0": "Substituting darbepoetin changes only the half-life and the dosing interval, not the class warning — and the hemoglobin target named here violates a second boxed warning, since aiming above 11 g/dL increases myocardial infarction, stroke, venous thromboembolism and death with no additional benefit.",
   "1": "Discontinuing at the end of the chemotherapy course is a genuine requirement of the boxed warning, and the answer would be defensible in a patient receiving palliative chemotherapy. It does not rescue this plan, because a separate clause of the same warning forbids the drug outright when the intent is cure.",
   "2": "Repleting iron before starting an erythropoiesis-stimulating agent is correct sequencing — iron first, signal second — and prevents the functional iron deficiency that is the commonest cause of apparent ESA resistance. His ferritin and transferrin saturation are normal, and the sequencing question never arises because the drug is contraindicated here.",
   "3": "There is no hemoglobin threshold above which erythropoiesis-stimulating agents are forbidden; if anything the concern runs the other way, since the drug is not a substitute for emergency transfusion in severe anemia because its onset is delayed. The barrier here is the curative intent, not the number."},
  "The drug that tells the marrow to make more red cells can also tell certain tumours to grow. His cancer is being treated to cure it, so the risk of helping the tumour outweighs sparing him a transfusion.",
  exim="fig_slide_esa_initiate",
  excap="Lecture slide: when an erythropoiesis-stimulating agent should — and should not — be started.")

# ── 4. Ferumoxytol and the magnetic resonance image (§17) ─────────────────────
q("A 45-year-old woman is evaluated for an incidental hepatic lesion found on ultrasonography. Two weeks ago she received a single large intravenous dose of iron for iron deficiency anemia caused by uterine leiomyomata, after ferrous sulfate produced intolerable nausea. She has no abdominal pain, no jaundice, and no history of transfusion, alcohol use, or liver disease. Magnetic resonance imaging of the abdomen now shows diffuse, markedly decreased signal intensity of the liver and spleen on T2-weighted sequences, obscuring the lesion in question.\n\nLaboratory studies show:\nHemoglobin 11.4 g/dL (N=12.0–16.0 g/dL)\nSerum ferritin 96 ng/mL (N=10–120 ng/mL)\nTransferrin saturation 31% (N=20%–50%)\nAspartate aminotransferase 24 U/L (N=10–40 U/L)\nAlanine aminotransferase 21 U/L (N=7–56 U/L)\n\nWhich of the following best explains the imaging findings?",
  ["A. Chelation of the gadolinium contrast agent by circulating iron",
   "B. Deposition of an administered iron oxide within the reticuloendothelial system",
   "C. Hemosiderin deposition from transfusional iron overload",
   "D. Hepatic parenchymal iron loading from hereditary hemochromatosis",
   "E. Precipitation of iron-dextran complexes within the hepatic sinusoids"],
  1,
  "Ferumoxytol is the intravenous iron designed to deliver a large dose in very few visits — which is exactly why it was chosen for a woman who could not tolerate oral iron. Its distinguishing property is chemical: it is an IRON OXIDE, a superparamagnetic particle taken up by the macrophages of the reticuloendothelial system. Those particles distort the local magnetic field, and the liver and spleen go dark on magnetic resonance imaging for up to about 3 months after the dose.\n\nThe practical consequence is the testable one: ferumoxytol interferes with magnetic resonance imaging, so imaging should be deferred, or a different iron product used, when a scan is anticipated. Nothing has gone wrong with her liver — the study is simply uninterpretable for the next several weeks.\n\nThe other intravenous products each carry their own signature fact. Ferric carboxymaltose raises FGF23 and causes hypophosphatemia that may be severe, and is the one approved for heart failure with reduced ejection fraction. Ferric derisomaltose also gives total replacement in a single visit, with notably less hypophosphatemia. Iron sucrose and sodium ferric gluconate are the small-dose, repeated-infusion workhorses. Low-molecular-weight iron dextran carries the historical anaphylaxis reputation and the tradition of a test dose.",
  {"0": "Iron does not chelate gadolinium, and the appearance described — diffuse signal loss in both liver and spleen — is a tissue property, not a contrast-agent failure. The pattern follows the organs that contain the most macrophages, which is the clue to what is actually being imaged.",
   "2": "Transfusional hemosiderosis does darken the liver on magnetic resonance imaging, and it is the reason chronically transfused patients with thalassemia are monitored this way. It requires a lifelong transfusion programme, and she has never been transfused; her ferritin of 96 ng/mL is normal rather than in the thousands.",
   "3": "Hereditary hemochromatosis loads iron into the hepatic parenchyma and would give a high transferrin saturation, typically above 45% to 50%, with a raised ferritin. Hers are 31% and 96 ng/mL, and the spleen is spared in hemochromatosis because the iron goes into hepatocytes rather than macrophages.",
   "4": "Iron dextran is a different product, and its notorious complication is anaphylaxis rather than an imaging artefact — which is why a test dose is traditional with it. It does not precipitate in sinusoids, and nothing in her presentation suggests a hypersensitivity reaction occurred."},
  "The iron she was given is a magnetic particle, and the scanner works by magnets. Her liver and spleen soaked up those particles, so on the pictures they look black for a few months. It is the medicine showing up, not a disease.",
  exim="fig_slide_ida_tree",
  excap="Lecture slide: the treatment algorithm for iron deficiency anemia, including the branch to the intravenous products.")

# ── 5. C3 catches more than C5 (§17) ──────────────────────────────────────────
q("A 31-year-old woman with paroxysmal nocturnal hemoglobinuria has received eculizumab for 8 months. The dark morning urine that prompted her diagnosis resolved after the second dose and has not recurred, and she has had no thrombotic events. She continues to report fatigue and exertional dyspnea and has required 2 units of packed red blood cells in the past 3 months. She received meningococcal vaccination before therapy was begun. Her temperature is 36.8°C (98.2°F), pulse is 94/min, and blood pressure is 114/70 mm Hg. Physical examination shows scleral icterus and a spleen tip palpable 3 cm below the left costal margin.\n\nLaboratory studies show:\nHemoglobin 8.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 25% (N=36%–46%)\nMean corpuscular volume 93 µm3 (N=80–100 µm3)\nReticulocyte count 7.6% (N=0.5%–1.5%)\nLactate dehydrogenase 192 U/L (N=100–220 U/L)\nTotal bilirubin 2.6 mg/dL (N=0.2–1.2 mg/dL)\nDirect bilirubin 0.3 mg/dL (N=0.0–0.3 mg/dL)\nHaptoglobin 14 mg/dL (N=30–200 mg/dL)\nSerum ferritin 142 ng/mL (N=10–120 ng/mL)\n\nThe direct antiglobulin test is positive for C3d and negative for IgG. Which of the following best explains her persistent anemia?",
  ["A. Clearance of C3-opsonized erythrocytes by splenic macrophages",
   "B. Continuing intravascular hemolysis from incomplete C5 blockade",
   "C. Development of neutralizing antibodies against eculizumab",
   "D. Evolution of the underlying clone into aplastic anemia",
   "E. Iron deficiency from chronic urinary loss of hemoglobin"],
  0,
  "Eculizumab blocks C5, which is the last step of the cascade — the step that builds the membrane attack complex and lyses the cell in the bloodstream. Blocking it works: her hemoglobinuria stopped, her lactate dehydrogenase is 192 U/L, and the intravascular hemolysis is genuinely controlled.\n\nBut the cascade is still running ABOVE the block. C3 convertase keeps depositing C3b on her red cells, and because paroxysmal nocturnal hemoglobinuria cells lack CD55 (the regulator that dismantles C3 convertase) there is nothing to stop it. Those C3b-coated cells are then eaten by splenic macrophages — extravascular hemolysis, which is why she has an unconjugated hyperbilirubinemia of 2.6 mg/dL with a direct fraction of 0.3 mg/dL, a reticulocyte count of 7.6%, splenomegaly, and a direct antiglobulin test positive for C3d and negative for IgG.\n\nThe memory hook: C3 catches more than C5. Blocking higher in the cascade stops more hemolysis. C5 inhibitors — eculizumab and the longer-acting ravulizumab — stop only the intravascular half; the proximal inhibitors pegcetacoplan (C3) and iptacopan (complement factor B, the first oral agent) stop both. Switching her to a proximal inhibitor is the recognized management of exactly this problem.\n\nOne thing does not change with the switch: every complement inhibitor carries a boxed warning for life-threatening meningococcal infection, and vaccination before starting is mandatory — the same missing defence as the asplenic patient, arrived at by a different route.",
  {"1": "Continuing intravascular hemolysis would keep the lactate dehydrogenase high — it was 1,400 U/L at diagnosis in most patients and falls into the normal range on eculizumab, as hers has, at 192 U/L. Her hemoglobinuria has also resolved, which is the clinical version of the same statement.",
   "2": "Antidrug antibodies against eculizumab are rare, and breakthrough from inadequate blockade would announce itself as a return of hemoglobinuria with a rising lactate dehydrogenase. Both are absent; her hemolysis has changed location, not intensity.",
   "3": "Paroxysmal nocturnal hemoglobinuria does arise from and can progress to marrow failure, and that combination is well described. Marrow failure produces a LOW reticulocyte count, and hers is 7.6% — the marrow is responding vigorously, so cells are being destroyed rather than not being made.",
   "4": "Chronic urinary loss of hemoglobin and hemosiderin genuinely causes iron deficiency in untreated paroxysmal nocturnal hemoglobinuria, and it is worth checking. Her ferritin is 142 ng/mL and her mean corpuscular volume is 93 µm3, neither of which fits deficiency, and her hemoglobinuria stopped 8 months ago."},
  "Her medicine blocks the very end of an alarm chain, so her red cells are no longer blown up inside the blood vessels. But the earlier part of the chain still tags them, and the spleen eats anything that is tagged — so the cells are still being destroyed, just somewhere else.")
