# Jeevs Edition — Batch 06: Transfusion Medicine, part 2
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html §12, §13, §14
# Fills the gaps batch 05 left: the "treating the number" plasma error, storage conditions,
# albumin, type-and-screen vs type-and-cross, the ABO front/back discrepancy, hemolytic
# disease of the newborn, sickle cell alloimmunization, the reaction algorithm's first step,
# the mild allergic reaction, and the transfusion-refusal conversation.
# Options alphabetised; "correct" is the 0-based index AFTER alphabetisation.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ── 1. Treating the number, not the patient (§12) ─────────────────────────────
q("A 62-year-old man is scheduled for elective laparoscopic cholecystectomy tomorrow. He has no history of abnormal bleeding, has had two prior operations without bleeding complications, and takes no anticoagulant or antiplatelet medication. He has no liver disease. His temperature is 36.8°C (98.2°F), pulse is 72/min, and blood pressure is 132/78 mm Hg. Physical examination shows no petechiae, ecchymoses, or mucosal bleeding.\n\nLaboratory studies show:\nHemoglobin 14.2 g/dL (N=13.5–17.5 g/dL)\nHematocrit 42% (N=41%–53%)\nPlatelet count 226,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 16 seconds (N=11–15 seconds)\nInternational normalized ratio 1.2 (N=0.8–1.2)\nPartial thromboplastin time 33 seconds (N=25–40 seconds)\nFibrinogen 312 mg/dL (N=200–400 mg/dL)\n\nThe surgical resident requests 2 units of fresh frozen plasma to normalize the prothrombin time before the operation. Which of the following is the most appropriate next step in management?",
  ["A. Administer cryoprecipitate",
   "B. Administer four-factor prothrombin complex concentrate",
   "C. Administer two units of fresh frozen plasma",
   "D. Administer vitamin K and postpone the operation",
   "E. Proceed to surgery without plasma transfusion"],
  4,
  "§12 calls this the commonest plasma error: someone sees a mildly abnormal number and orders plasma to make it look normal.\n\nThe physiology says not to. Only about 30% coagulation factor activity is needed to form a clot — above that line hemostasis is adequate. An international normalized ratio of 1.2 corresponds to activity far above 30%; you do not approach the threshold until the prothrombin time is roughly 2 to 2.2 times normal.\n\nThe ocean-and-teacup metaphor makes the futility concrete. Circulating plasma is an ocean; one unit of transfused plasma is a teacup. If the ocean already sits at 50–60% activity, the teacup changes nothing measurable — and nothing needed changing, because he could already clot. Only when the ocean is down at 10–15% does the same teacup move the needle.\n\nSo the transfusion achieves nothing while exposing him to a febrile or allergic reaction, a residual infectious risk, TRALI, circulatory overload, and the consumption of a scarce volunteer-donated product. His clinical bleeding history — two operations without bleeding, no bruising, no mucosal bleeding — is a better predictor of surgical bleeding than a prothrombin time 1 second above the reference range.\n\nTreat the patient, not the number.",
  {"0": "Cryoprecipitate replaces fibrinogen, and would be the answer with a fibrinogen below roughly 150 mg/dL in a bleeding patient or in disseminated intravascular coagulation. His fibrinogen is 312 mg/dL — entirely normal.",
   "1": "Prothrombin complex concentrate is for urgent reversal of warfarin or another vitamin K antagonist in a patient with serious bleeding or needing emergency surgery. He takes no anticoagulant, is not bleeding, and his coagulopathy is trivial; the concentrate also carries a thrombotic risk.",
   "2": "This is the request being made, and the item exists to refuse it. Plasma is indicated for a documented multiple factor deficiency WITH active bleeding, or for a markedly prolonged coagulation test before a procedure. An international normalized ratio of 1.2 is neither.",
   "3": "Vitamin K would be appropriate for a genuine vitamin K-dependent coagulopathy — malnutrition, prolonged antibiotic use, biliary obstruction, or warfarin — where the prothrombin time is substantially prolonged and corrects with replacement. Postponing an elective operation for an international normalized ratio of 1.2 delays care for no benefit."},
  "His clotting test is a hair outside the normal range, but he can clot perfectly well — you only need about a third of normal clotting activity. Giving plasma would not change the number meaningfully and only exposes him to risk.",
  exim="fig_tx_timeline",
  excap="What an unnecessary transfusion buys: every reaction on this timeline becomes possible, in a patient who gained nothing from the product.")

# ── 2. Storage conditions — the platelet exception (§12) ──────────────────────
q("A 61-year-old woman receiving induction chemotherapy for acute myeloid leukemia has a platelet count of 7,000/mm3 with no bleeding, and a transfusion of the appropriate product is ordered. The blood bank notes that this particular product has the shortest shelf life of any component it stores, and that it cannot be refrigerated.\n\nWhich of the following sets of storage conditions applies to the product this patient requires?\n\n    Storage temperature | Agitation | Maximum shelf life",
  ["A. 1–6 °C, continuous agitation, 5 days",
   "B. 1–6 °C, no agitation, 42 days",
   "C. 20–24 °C, continuous agitation, 5–7 days",
   "D. 20–24 °C, no agitation, 42 days",
   "E. Frozen at −18 °C or below, no agitation, 1 year"],
  2,
  "She needs platelets, and platelets are the exception to everything else in the blood bank: room temperature (20–24°C), on a continuously agitating rotator, for 5 to 7 days.\n\nEach part of that follows from the biology. Cold ACTIVATES platelets and refrigerated platelets are cleared from the circulation within hours, so they cannot be kept at 1–6°C like every other component. Continuous agitation keeps them suspended and allows gas exchange through the breathable plastic of the bag — the cells in the bag are alive and still consuming oxygen.\n\nThe consequence is the one that matters clinically. Room temperature is also a bacterial growth medium, so any organism introduced during collection — classically a plug of donor skin punched out by the needle — can multiply. That is why the shelf life is 5 to 7 days rather than 42, why a bacterially contaminated platelet is the most common INFECTIOUS risk of transfusion today, and why pathogen reduction and the diversion pouch were introduced for this product in particular.\n\nFor comparison: red cells sit at 1–6°C for up to 42 days in an additive solution of adenine, mannitol and dextrose that fuels their ATP pumps; plasma and cryoprecipitate are frozen for up to a year and thawed before use.",
  {"0": "Refrigeration with agitation is not used for any component. If platelets were refrigerated they would be activated and cleared rapidly from the recipient's circulation, which is precisely why room temperature storage — and its bacterial risk — is accepted.",
   "1": "1–6°C with no agitation for 42 days is the red blood cell row. It would be the answer if she needed red cells for anemia; her hemoglobin is not the problem and red cells contain no useful platelets.",
   "3": "Room temperature for 42 days combines the correct temperature with an impossible shelf life. The whole reason the platelet expiry is 5 to 7 days is that bacteria grow at that temperature; extending it to 42 days is what the short expiry exists to prevent.",
   "4": "Freezing at −18°C or below for a year is the plasma and cryoprecipitate row. Those products are thawed before use, and freezing would destroy platelet function entirely."},
  "Platelets are the one blood product that cannot go in the fridge — cold ruins them, so they sit at room temperature being gently rocked. Room temperature also suits bacteria, which is why they must be used within about a week.",
  exim="fig_tx_reactions",
  excap="Why the platelet exception matters: room-temperature storage is what makes the septic transfusion reaction a platelet problem above all.")

# ── 3. Volume without hemostasis — albumin (§12) ──────────────────────────────
q("A 57-year-old man with cirrhosis and refractory ascites undergoes therapeutic paracentesis, and 6 L of ascitic fluid is removed. He is not bleeding, and there is no oozing from the puncture site. His temperature is 36.9°C (98.4°F), pulse is 92/min, and blood pressure is 102/62 mm Hg before the procedure.\n\nLaboratory studies show:\nHemoglobin 11.8 g/dL (N=13.5–17.5 g/dL)\nHematocrit 35% (N=41%–53%)\nPlatelet count 88,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 18 seconds (N=11–15 seconds)\nInternational normalized ratio 1.6 (N=0.8–1.2)\nSerum albumin 2.4 g/dL (N=3.5–5.5 g/dL)\nCreatinine 1.1 mg/dL (N=0.6–1.2 mg/dL)\n\nTo reduce the risk of circulatory dysfunction and acute kidney injury after this large-volume paracentesis, which of the following is most appropriate to administer?",
  ["A. Cryoprecipitate",
   "B. Fresh frozen plasma",
   "C. Intravenous albumin",
   "D. Packed red blood cells",
   "E. Platelet concentrate"],
  2,
  "Removing 6 L of ascites shifts a large volume out of the circulation over the following hours, and the effective arterial blood volume falls → renin-angiotensin and sympathetic activation → renal vasoconstriction. Albumin is given to hold volume in the vascular space and prevent post-paracentesis circulatory dysfunction and the acute kidney injury that follows it, and is standard for paracentesis above about 5 L.\n\nAlbumin belongs to the plasma-derived MEDICINES — the category §12 says students most often miss. Albumin, intravenous immunoglobulin and the prothrombin complex concentrates are manufactured from pooled plasma, then heat and solvent-detergent treated to inactivate pathogens, and purified. They arrive from the pharmacy, not the blood bank, and they have had a pathogen-inactivation step that a bag of thawed plasma has not.\n\nThe distinction being tested is the one §12 draws explicitly: albumin is a colloid volume expander containing NO coagulation factors, while plasma is given to correct a coagulation factor deficiency. Here he needs volume support and nothing hemostatic — he is not bleeding — so albumin is exactly right and plasma would be exactly wrong.\n\nHis abnormal numbers are a deliberate distraction. The prolonged prothrombin time and low platelet count of cirrhosis do not predict bleeding, because the same failing liver produces less protein C, protein S and antithrombin alongside the procoagulant factors — the balance is rebalanced, not tipped.",
  {"0": "Cryoprecipitate replaces fibrinogen in a bleeding patient with a critically low level, typically in disseminated intravascular coagulation or obstetric hemorrhage. He is not bleeding, and nothing here suggests hypofibrinogenemia.",
   "1": "Plasma is the trap: his international normalized ratio of 1.6 invites it. But plasma is indicated for a factor deficiency WITH bleeding, would not correct the rebalanced hemostasis of cirrhosis, and — as a volume expander — carries a real risk of circulatory overload in a patient with portal hypertension.",
   "3": "Red cells are given to increase oxygen-carrying capacity. His hemoglobin is 11.8 g/dL, far above any transfusion threshold, and he is not bleeding; transfusing would also raise portal pressure.",
   "4": "Platelets would be considered before an invasive procedure at a much lower count, or with active bleeding. At 88,000/mm3 with a completed paracentesis and no bleeding, they add risk without benefit."},
  "Draining six litres from his belly leaves his circulation suddenly short, which can shut down his kidneys. Albumin is a protein that holds fluid inside the blood vessels — it is for volume, and it contains no clotting factors at all.",
  exim="fig_tx_reactions",
  excap="Albumin is a purified, pathogen-inactivated plasma product rather than a blood-bank component — it carries none of the cellular or antibody-mediated reactions shown here.")

# ── 4. Type and screen versus type and cross (§13) ────────────────────────────
q("A 34-year-old woman is scheduled for elective laparoscopic cholecystectomy. The procedure has a low expected blood loss, and transfusion is rarely required. She has never been transfused and has had two uncomplicated pregnancies. She takes no medications. Vital signs are within normal limits. Physical examination shows no abnormalities.\n\nLaboratory studies show:\nHemoglobin 13.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 40% (N=36%–46%)\nPlatelet count 254,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 12.2 seconds (N=11–15 seconds)\n\nWhich of the following is the most appropriate preoperative order to the blood bank?",
  ["A. No blood bank testing before the procedure",
   "B. Type and crossmatch four units of packed red blood cells",
   "C. Type and crossmatch two units of packed red blood cells",
   "D. Type and screen only",
   "E. Uncrossmatched group O RhD-negative units held in the operating room"],
  3,
  "A type and SCREEN determines her ABO and RhD type and screens her plasma for unexpected antibodies. The blood bank then knows exactly what she would need and can issue compatible units quickly — but no physical units are set aside. That is the right level of preparation when transfusion is possible but not expected.\n\nA type and CROSS does all of that and then crossmatches actual units, which are labelled and physically reserved for her. Reserved units are unavailable to anyone else for the duration of the hold, so over-ordering type-and-cross wastes a scarce resource in a hospital where another patient may need those units today.\n\nThe memory hook: Screen = ready. Cross = reserved.\n\nHer two pregnancies matter to the screen. Pregnancy is one of only two routes of exposure to foreign red cells, so she could carry an alloantibody — and if the screen is positive, the blood bank needs time to identify it and find antigen-negative units. Discovering that days before an elective operation is exactly the point of screening in advance.",
  {"0": "Ordering nothing would be reasonable for a procedure with essentially no bleeding risk, but it leaves the blood bank starting from zero if she does bleed — including the possibility of an unexpected antibody that takes hours to work around. The screen costs little and removes that risk.",
   "1": "Crossmatching four units reserves a large share of her blood type for a procedure that rarely requires any. It would be appropriate for surgery with a high expected blood loss, such as a major hepatic resection or a repair of a ruptured aneurysm.",
   "2": "Two crossmatched units is the order for an operation where transfusion is genuinely expected — which this is not. It still ties up units that another patient may need, for a cholecystectomy that almost never bleeds.",
   "4": "Uncrossmatched group O RhD-negative blood is the emergency-release product for a patient who is exsanguinating and cannot wait to be typed. Holding it for an elective, low-risk operation consumes the scarcest units in the inventory — group O RhD negative is only about 6% of donors."},
  "A screen just means the lab knows her blood type and has checked for surprises, so it can grab compatible blood fast. A crossmatch physically locks specific bags away for her, which wastes them if she never bleeds.",
  exim="fig_abo",
  excap="What the type establishes: the antigens on the patient's cells and the mirror-image antibodies in her plasma, checked against each other before any unit is issued.")

# ── 5. The front type and back type disagree (§13) ────────────────────────────
q("A 71-year-old woman is admitted to the hospital with a hip fracture, and a preoperative blood sample is sent for typing. She has not been transfused within the past 3 months. The blood bank reports the following results on the sample:\n\nFront type (patient's red cells tested with reagent antisera): reactive with anti-A, not reactive with anti-B — consistent with group A\nBack type (patient's plasma tested against reagent red cells): reactive with group A cells AND reactive with group B cells — consistent with group O\n\nThe two determinations do not agree. The patient is otherwise stable, her hemoglobin concentration is 10.8 g/dL (N=12.0–16.0 g/dL), and surgery is scheduled for the following morning. Which of the following is the most appropriate next step?",
  ["A. Issue group A red blood cells, matching the front type",
   "B. Issue group AB red blood cells, which lack plasma antibodies",
   "C. Issue group O red blood cells and proceed with the operation",
   "D. Report the patient as group O, matching the back type",
   "E. Withhold blood and obtain a newly collected, positively identified sample"],
  4,
  "The blood bank types every sample twice, in opposite directions, precisely so that a mismatch stops the process. The front type asks what antigens are on the patient's cells; the back type asks what antibodies are in her plasma. Because everyone makes antibody against the antigen they lack, the two must be mirror images — group A cells with anti-B in the plasma, and so on.\n\nHere they do not agree: her cells say group A, her plasma says group O. One of two things is true, and both demand the same action. Either the sample is not hers — the classic 'wrong blood in tube', where a tube drawn from one patient is labelled with another patient's pre-printed label — or there is a genuine but unusual serologic explanation (a subgroup, a recent transfusion, an alloantibody reacting with the reagent cells, hypogammaglobulinemia, or a cold agglutinin).\n\nSo the blood bank stops, and a fresh sample is collected with positive patient identification at the bedside before anything is released. Recollection is what distinguishes a labelling error from a real serologic finding, and it is cheap: she is stable, not bleeding, and her operation is tomorrow.\n\nWhy this matters more than any other discrepancy: wrong blood in tube is the mechanism behind the acute hemolytic transfusion reaction, a NEVER event. The blood bank types the mislabelled sample perfectly correctly — everything downstream is flawlessly wrong.",
  {"0": "Trusting the front type assumes the discrepancy is in the plasma testing. If the sample belongs to a group O patient, issuing group A cells delivers A antigen to a patient whose plasma is full of anti-A — an immediate intravascular hemolytic reaction.",
   "1": "Group AB is the universal red cell RECIPIENT, not a safe universal issue: AB cells carry BOTH A and B antigens and would be attacked by almost any recipient's plasma. The inversion — AB as universal donor — applies only to plasma products.",
   "2": "Group O red cells would in fact be serologically safe for either interpretation, which makes this the most tempting wrong answer. It is still wrong, because it treats a signal of a possible identification error as a logistics problem to work around. If the sample is not hers, the error remains in the record and the next transfusion may not be group O.",
   "3": "Reporting her as group O accepts the back type without investigation and enters a possibly incorrect type into her permanent record. A discrepancy is a reason to investigate, not to pick the more conservative of two contradictory results."},
  "The lab checks blood type twice, in opposite directions, and the two answers must mirror each other. When they do not, the most likely reason is that the tube came from a different patient — so everything stops and a fresh, carefully labelled sample is drawn.",
  exim="fig_abo",
  excap="The mirror image the blood bank checks: each phenotype's antigens on the cell must correspond exactly to the antibodies in the plasma.")

# ── 6. Hemolytic disease of the newborn (§13) ─────────────────────────────────
q("A male newborn delivered at 38 weeks' gestation to a 29-year-old woman, gravida 2, para 2, develops jaundice at 10 hours of life. The mother is group O, RhD negative, and an antibody screen in the third trimester detected anti-D; she did not receive anti-D immune globulin during her first pregnancy, which was managed abroad. The newborn is group A, RhD positive. His temperature is 36.8°C (98.2°F), pulse is 158/min, and respirations are 48/min. Physical examination shows scleral icterus, pallor, and a liver edge 3 cm below the right costal margin.\n\nLaboratory studies show:\nHemoglobin 9.8 g/dL (N=14.0–24.0 g/dL for age)\nHematocrit 29% (N=44%–70% for age)\nReticulocyte count 12.4% (N=3%–7% for age)\nTotal bilirubin 11.2 mg/dL (N=1.0–6.0 mg/dL for age)\nDirect bilirubin 0.4 mg/dL (N=0.0–0.6 mg/dL for age)\n\nA direct antiglobulin test performed on cord blood is strongly positive, and the peripheral smear shows polychromasia and nucleated erythrocytes. Which of the following best explains the hemolysis in this newborn?",
  ["A. Deficiency of glucose-6-phosphate dehydrogenase in the newborn's erythrocytes",
   "B. Immaturity of hepatic uridine diphosphate glucuronosyltransferase",
   "C. Maternal IgG antibody that crossed the placenta and coated fetal erythrocytes",
   "D. Maternal IgM antibody that crossed the placenta and activated complement",
   "E. Sequestration and breakdown of erythrocytes within a cephalohematoma"],
  2,
  "This is hemolytic disease of the fetus and newborn from RhD incompatibility, and the positive direct antiglobulin test on cord blood is the finding that proves the mechanism: the newborn's own erythrocytes are already coated with antibody at birth.\n\nThe sequence runs across two pregnancies. The mother is RhD negative and was sensitized by her first RhD-positive fetus, forming anti-D — she received no anti-D immune globulin to prevent it. Anti-D is IgG, and IgG is the one antibody class that crosses the placenta by active transport. In this pregnancy it crossed, bound fetal D-positive erythrocytes, and marked them for splenic clearance → extravascular hemolysis in utero and after delivery.\n\nThe findings follow directly: anemia with a brisk reticulocytosis and nucleated erythrocytes (the fetal marrow compensating), unconjugated hyperbilirubinemia within the first 24 hours, and hepatomegaly from extramedullary hematopoiesis. Jaundice in the first 24 hours of life is never physiologic. Untreated, bilirubin crosses the immature blood-brain barrier and causes kernicterus, so management is phototherapy, with exchange transfusion for severe or rapidly rising levels.\n\nNote the asymmetry with ABO: naturally occurring anti-A and anti-B are IgM and do NOT cross the placenta, which is why ABO hemolytic disease is generally milder and occurs in a group O mother whose IgG anti-A,B fraction crosses.",
  {"0": "G6PD deficiency does cause neonatal jaundice, particularly in male infants, and is X-linked. It would be the answer with a NEGATIVE direct antiglobulin test and bite cells after an oxidant exposure — the positive antiglobulin test here establishes an immune mechanism instead.",
   "1": "Immature glucuronosyltransferase is the mechanism of physiologic jaundice of the newborn, and of Gilbert and Crigler-Najjar syndromes. Those produce unconjugated hyperbilirubinemia WITHOUT anemia, without reticulocytosis, and with a negative antiglobulin test — and physiologic jaundice does not appear within the first 24 hours.",
   "3": "The direction is right but the antibody class is wrong, which is what makes this the near-miss. IgM does not cross the placenta — it is far too large and there is no transport mechanism. That is precisely why naturally occurring ABO antibodies, which are IgM, cause little fetal disease.",
   "4": "A cephalohematoma is a real cause of neonatal hyperbilirubinemia, as the extravasated blood is broken down. It would be the answer with a boggy, well-demarcated scalp swelling after an instrumented delivery, a normal hemoglobin, and a negative antiglobulin test."},
  "The mother's immune system learned to attack a marker on red cells during her first pregnancy. Those antibodies are the type that can cross the placenta, so they reached this baby and destroyed his red cells before he was born.",
  exim="fig_rh_pregnancy",
  excap="RhD incompatibility: sensitization in a first pregnancy, then IgG anti-D crossing the placenta in the next and destroying the erythrocytes of an RhD-positive fetus.")

# ── 7. Alloimmunization in sickle cell disease (§13) ──────────────────────────
q("A 26-year-old woman with sickle cell disease has received chronic transfusions every 4 weeks for the past 6 years for secondary stroke prevention. She takes hydroxyurea, folic acid, and deferasirox. Over that period the blood bank has identified three separate red cell alloantibodies in her plasma — anti-Fya, anti-Jkb, and anti-K — and each new unit now takes many hours to source from a reference laboratory. Her temperature is 37.0°C (98.6°F), pulse is 84/min, and blood pressure is 116/70 mm Hg. Her hemoglobin concentration is 8.6 g/dL (N=12.0–16.0 g/dL) and her direct antiglobulin test is negative.\n\nWhich of the following best explains this patient's high rate of alloantibody formation?",
  ["A. Antigenic differences between the patient and the donor pool, with repeated exposure over years",
   "B. Autoantibody formation driven by chronic hemolysis",
   "C. Functional asplenia impairing clearance of antibody-coated erythrocytes",
   "D. Immunosuppression from long-term hydroxyurea therapy",
   "E. Transfusion of ABO-incompatible units during emergency releases"],
  0,
  "Alloimmunization occurs in 1–3% of the general transfused population but in 20–60% of patients with sickle cell disease, and the explanation is exposure arithmetic rather than anything intrinsic to the disease.\n\nUnits are always matched for ABO and RhD. They are NOT routinely matched for the minor systems — Duffy (Fya), Kidd (Jkb), Kell (K) and the rest — and those antigens differ between an individual patient and the donor pool she draws from. A patient transfused every 4 weeks for 6 years has met roughly 150 units. Each exposure to a minor antigen she lacks is another opportunity to form an antibody, and each new antibody narrows the pool of units that will do → the hours-long searches she now faces.\n\nHer three antibodies are exactly the three systems §13 names. Once formed, they are a lifelong requirement: the titre can fall below the level of detection and still rise explosively on re-exposure, which is the mechanism of the delayed hemolytic transfusion reaction.\n\nThis is why many centres now provide EXTENDED antigen-matched blood — matching Rh (C, E) and K, and more when a patient is already alloimmunized — to chronically transfused patients from the start, rather than waiting for the first antibody to appear.\n\nHer negative direct antiglobulin test confirms the antibodies are free in plasma rather than coating her own cells; she is not hemolyzing at present.",
  {"1": "An autoantibody would react with her OWN erythrocytes and produce a positive direct antiglobulin test with ongoing hemolysis. Hers is negative, and the antibodies identified have defined alloantigen specificities — anti-Fya, anti-Jkb and anti-K are directed at antigens she does not carry.",
   "2": "Functional asplenia is real in sickle cell disease and does impair clearance of encapsulated organisms — but impaired clearance of antibody-coated cells would reduce hemolysis, not increase antibody FORMATION. If anything, an absent spleen tends to blunt the response to particulate antigen.",
   "3": "Hydroxyurea is myelosuppressive but is not meaningfully immunosuppressive at the doses used in sickle cell disease, and immunosuppression would if anything REDUCE alloantibody formation. It also does not explain a pattern specific to minor red cell antigens.",
   "4": "ABO-incompatible transfusion causes an immediate, catastrophic intravascular hemolytic reaction — it is a never event, not a slow route to alloimmunization. She has had no such reaction, and ABO antibodies are naturally occurring rather than formed by exposure."},
  "Every transfusion introduces red cell markers slightly different from her own, and after roughly 150 units her immune system has learned to attack several of them. Each new antibody rules out more donors, so finding compatible blood takes longer and longer.",
  exim="fig_tx_reactions",
  excap="The delayed hemolytic reaction that alloantibodies cause on re-exposure: recipient antibody formed after earlier sensitization binds donor cells and destroys them extravascularly.")

# ── 8. The first step, whatever the reaction turns out to be (§14) ────────────
q("A 58-year-old man with anemia from chronic kidney disease is receiving the first of two units of packed red blood cells on a medical ward. Thirty minutes into the unit, approximately 120 mL has been infused, and the nurse calls because his temperature has risen from 36.8°C (98.2°F) to 38.7°C (101.7°F) and he has developed shaking chills. He has no chest or back pain, no dyspnea, and no rash. His pulse is 104/min, respirations are 20/min, and blood pressure is 128/76 mm Hg, unchanged from baseline. Pulse oximetry on room air shows an oxygen saturation of 96%.\n\nWhich of the following is the most appropriate immediate next step?",
  ["A. Administer acetaminophen and continue the transfusion",
   "B. Increase the infusion rate to complete the unit quickly",
   "C. Obtain a chest radiograph before making further decisions",
   "D. Slow the infusion rate and observe for 15 minutes",
   "E. Stop the transfusion and verify the unit label against the patient's identity"],
  4,
  "Whatever the reaction turns out to be, the first five steps are the same — and §14 is explicit about the order:\n\n1. STOP the transfusion. Do not restart that unit.\n2. Keep the intravenous line open with normal saline through fresh tubing.\n3. CLERICAL CHECK — the unit label against the patient's identity. This is where the fatal ABO error is caught.\n4. See and treat: oxygen for hypoxia, antihistamine for hives, escalating to steroids or epinephrine as required.\n5. Send the unit, the tubing and fresh samples to the blood bank, and call the blood bank physician.\n\nThe reason the order matters is that you stop the exposure BEFORE you diagnose it, because the two most lethal reactions — acute hemolysis and anaphylaxis — are dose dependent. Every additional millilitre of an ABO-incompatible unit adds to the hemolytic load.\n\nHis presentation is most likely a febrile nonhemolytic reaction, which is common, self-limited and harmless. But at 30 minutes with a fever and rigors, it is indistinguishable at the bedside from the first minutes of an acute hemolytic reaction or a septic unit, both of which kill. You cannot tell them apart without stopping and investigating, and the investigation is cheap while the missed diagnosis is not.",
  {"0": "Acetaminophen is a reasonable part of managing a febrile nonhemolytic reaction — but CONTINUING the unit is the error. That diagnosis can only be made after hemolysis and sepsis have been excluded, and the transfusion is never resumed once a febrile reaction has occurred.",
   "1": "Finishing the unit faster maximizes exposure to a product that may be incompatible or contaminated. Both of the reactions that could kill him in the next hour are dose dependent, which makes this the most dangerous action on the list.",
   "2": "Imaging would be relevant if he were hypoxic, to look for the bilateral opacities of TRALI or circulatory overload. His oxygen saturation is 96% with no dyspnea, and ordering a test before stopping the infusion leaves the exposure running while he goes to radiology.",
   "3": "Slowing the rate is a half-measure that keeps incompatible or contaminated blood flowing. It is used for circulatory overload in some protocols, but not as the initial response to fever, and not before the clerical check."},
  "Any fever during a transfusion could be the harmless common reaction or the start of a fatal one, and you cannot tell yet. So you stop the drip first and check that the bag actually belongs to this patient, then work out what happened.",
  exim="fig_tx_timeline",
  excap="Most reactions declare themselves within the first hours, and several look identical at onset — which is why the response is a fixed algorithm rather than a diagnosis.")

# ── 9. The mild allergic reaction (§14) ───────────────────────────────────────
q("A 22-year-old woman receiving plasma for a coagulopathy after obstetric hemorrhage develops itching and a raised, blotchy rash over her chest and arms 20 minutes into the unit. She has no throat tightness, no difficulty breathing, and no back pain. Her temperature is 36.9°C (98.4°F), pulse is 88/min, respirations are 16/min, and blood pressure is 118/72 mm Hg, all unchanged from before the transfusion. Pulse oximetry on room air shows an oxygen saturation of 99%. The transfusion is stopped and the intravenous line is kept open with normal saline. Physical examination shows scattered urticarial wheals on the trunk and arms; the chest is clear, there is no stridor, and there is no facial or lingual swelling. A clerical check confirms the correct unit and patient, her plasma is straw-colored, and her urine is clear.\n\nWhich of the following is the most appropriate management?",
  ["A. Administer diphenhydramine, resuming the transfusion cautiously if the symptoms resolve",
   "B. Administer epinephrine intramuscularly and discard the remainder of the unit",
   "C. Administer intravenous furosemide",
   "D. Obtain blood cultures and begin broad-spectrum antibiotics",
   "E. Perform a direct antiglobulin test and transfuse a different unit"],
  0,
  "Hives and itching with entirely stable vital signs, no airway involvement and no fever is a MILD allergic transfusion reaction — and it is the one reaction on the list where the transfusion may be restarted once symptoms settle.\n\n§14 explains it with the strawberry model: the donor ate strawberries, a soluble allergen from the donor's diet is present in the plasma, and a recipient with pre-formed IgE against it reacts. A type I hypersensitivity reaction confined to the skin, treated with an antihistamine.\n\nWhat makes it safe to resume is the constellation of negatives, all of which the vignette supplies deliberately: no hypotension or throat tightness (excluding anaphylaxis), no fever (excluding febrile nonhemolytic and septic reactions), straw-colored plasma and clear urine with a correct clerical check (excluding acute hemolysis), and a normal oxygen saturation with a clear chest (excluding TRALI and circulatory overload).\n\nThe contrast that matters is anaphylaxis, which begins after a tiny volume — classically 5 mL — with hypotension, bronchospasm, stridor and NO fever, and which is associated with IgA deficiency and anti-IgA antibodies. That patient gets epinephrine, the unit is never restarted, and all future products must be washed or from IgA-deficient donors.\n\nFor a patient who reacts repeatedly, antihistamine premedication or washed products can be used.",
  {"1": "Epinephrine is the treatment for anaphylaxis, and it would be the answer with hypotension, stridor, wheeze or angioedema — particularly in a patient with recurrent sinopulmonary infections and undetectable IgA. Her vital signs are unchanged and her airway is uninvolved; epinephrine here is an overreaction with real cardiac risk.",
   "2": "Furosemide treats transfusion-associated circulatory overload — dyspnea, hypertension, a raised jugular venous pressure and pulmonary opacities. She has normal vital signs, a clear chest and an oxygen saturation of 99%.",
   "3": "Cultures and antibiotics are the response to a septic transfusion reaction, which presents with high fever, rigors, hypotension and rapid deterioration, most often with a platelet unit. She is afebrile with a normal blood pressure.",
   "4": "A direct antiglobulin test is part of investigating a suspected HEMOLYTIC reaction. Hemolysis is already effectively excluded by the straw-colored plasma, clear urine and correct clerical check — and transfusing a different unit would not address an allergen that is present in most donors' plasma."},
  "She reacted to something dissolved in the donor's plasma, and the reaction stayed in her skin — no drop in blood pressure, no breathing trouble, no fever. An antihistamine settles it, and the same unit can usually be restarted slowly.",
  exim="fig_tx_reactions",
  excap="Minor allergic reaction, third column: donor plasma proteins meet recipient antibody and mast cells degranulate — the same mechanism as anaphylaxis, but confined to the skin.")

# ── 10. The conversation (§14) ────────────────────────────────────────────────
q("A 45-year-old woman with menorrhagia and symptomatic anemia is advised to receive a red blood cell transfusion. Her hemoglobin concentration is 6.2 g/dL (N=12.0–16.0 g/dL) and she reports dyspnea on climbing one flight of stairs. When the physician explains the plan, she says, 'My uncle got HIV from a blood transfusion in the eighties and he died. I don't want anyone else's blood in me.' She is alert, oriented, and has decision-making capacity. Her husband, who is present, says he thinks she should accept the transfusion.\n\nWhich of the following is the most appropriate initial response by the physician?",
  ["A. \"Blood transfusions are completely safe now, so there is really no reason to worry about this.\"",
   "B. \"I can see this worries you. Can you tell me more about what concerns you about the transfusion?\"",
   "C. \"I will ask the hematology service to come and discuss the risks with you instead.\"",
   "D. \"Let me explain the nucleic acid testing algorithm the blood bank runs on every donated unit.\"",
   "E. \"Your husband is right, and without this transfusion your heart could fail.\""],
  1,
  "Her refusal is grounded in a real event — thousands of people, hemophiliacs above all, did acquire HIV and hepatitis from blood products in the 1980s, and that history is the reason the modern system exists. She has capacity, so the decision is hers, and the physician's first job is to understand what she is actually afraid of before trying to change her mind.\n\nThe correct response does two things in one sentence: it ACKNOWLEDGES the concern as legitimate, and it invites her to say more with an open-ended question. Only after that does information land — because until she feels heard, reassurance is experienced as dismissal.\n\nWhat comes next in the conversation, once she has been heard: the residual risk of transfusion-transmitted HIV is now roughly on the order of being struck by lightning; every unit is tested for a panel of transmissible diseases and any positive unit is discarded; the supply comes from unpaid volunteer donors who complete a detailed health questionnaire — two independent layers, built specifically in response to the 1980s. It is also honest to say that the commoner infectious risk today is a bacterially contaminated platelet rather than a virus, and that non-infectious reactions are more common than either.\n\nAnd if, fully informed, she still declines, that refusal is respected, and the conversation turns to alternatives — intravenous iron, treating the menorrhagia, and tolerating a lower hemoglobin.",
  {"0": "This is false reassurance, and it is also not true: transfusion carries real residual risks, which is why they are disclosed. Declaring that there is 'no reason to worry' dismisses a fear rooted in a family death and tells her that her concern is unreasonable rather than understandable.",
   "2": "Handing the conversation to another service is offloading. She is refusing a treatment her own physician has recommended, and a consultant arriving cold is no better placed to address a fear about a family member; it also signals that the physician does not want to have the conversation.",
   "3": "The information is accurate and belongs in the discussion — but not first. Leading with a technical explanation answers a question she has not asked and skips the acknowledgment; a person frightened by a relative's death is not persuaded by an assay algorithm.",
   "4": "This enlists her husband against her and adds a frightening consequence to pressure her. She has capacity, so the decision is hers alone, and deferring to a family member over the patient violates her autonomy while using fear as leverage."},
  "She is scared because a transfusion killed someone in her family, so the first move is to show you understand and ask what worries her. Facts land only after someone feels heard.",
  exim="fig_tx_timeline",
  excap="The modern risk picture: the reactions on this timeline — not viral transmission — are what a transfused patient is most likely to experience today.")
