# Jeevs Edition — Batch 16: COAGULATION I · BLEEDING, part 2 (the 10 gaps batch 15 left)
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §29 s26-cascade            — anticoagulants, thrombin feedback, thrombin time, viscoelastic testing
#   §30 s27-bleeding-inherited — vessel wall, dysfibrinogenemia, storage pool, type 2N, Kasabach-Merritt
#   §31 s28-bleeding-acquired  — factor VIII separating liver disease from DIC
# Options alphabetised; "correct" is the 0-based index AFTER alphabetisation.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ── 1. Bleeding with a perfect panel — the vessel wall (§30) ────────────────
q("A 44-year-old man is evaluated for nosebleeds occurring several times a week since adolescence, which have become more frequent and now require nasal packing. He has also had two episodes of iron deficiency anemia attributed to occult gastrointestinal blood loss. His father and paternal aunt have similar nosebleeds. His temperature is 36.8°C (98.2°F), pulse is 82/min, and blood pressure is 126/76 mm Hg. Physical examination shows small, blanching red vascular lesions on the lips, the tongue, and the fingertips, and no petechiae, no purpura, and no joint abnormality.\n\nLaboratory studies show:\nHemoglobin 10.2 g/dL (N=13.0–16.0 g/dL)\nHematocrit 31% (N=37%–49%)\nProthrombin time 12 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 30 seconds (N=25–35 seconds)\nPlatelet count 284,000/mm3 (N=150,000–400,000/mm3)\nFibrinogen 320 mg/dL (N=200–400 mg/dL)\n\nVon Willebrand antigen, ristocetin cofactor activity, and platelet aggregation studies are all normal. Which of the following is the most likely diagnosis?",
  ["A. Factor XIII deficiency",
   "B. Glanzmann thrombasthenia",
   "C. Hereditary hemorrhagic telangiectasia",
   "D. Immune thrombocytopenia",
   "E. Type 1 von Willebrand disease"],
  2,
  "PROPER COAGULATION ALSO DEPENDS ON BLOOD VESSELS AND ENDOTHELIUM — THE PANEL CAN BE NORMAL AND THE PATIENT CAN STILL BLEED. That is why the three ingredients are counted as three rather than one: PLATELETS in the right number and with the right function, a FIBRIN CLOT correctly produced and correctly broken down, and BLOOD VESSELS WITH HEALTHY ENDOTHELIUM.\n\nHereditary hemorrhagic telangiectasia — Osler-Weber-Rendu — is the headline entry on the list of causes that are NOT THE COAGULATION SYSTEM AT ALL. The vessels themselves are abnormal: direct arteriovenous connections without an intervening capillary bed, so the lesions are fragile, under arterial pressure, and cannot constrict normally when torn.\n\nThe features here are the diagnostic ones: RECURRENT EPISTAXIS from adolescence, MUCOCUTANEOUS TELANGIECTASES at the classic sites (lips, tongue, fingertips), a FAMILY HISTORY consistent with autosomal dominant inheritance, and iron deficiency from gastrointestinal blood loss. Visceral arteriovenous malformations — pulmonary, hepatic, cerebral — are the complications that make the diagnosis matter beyond the nosebleeds.\n\nThe rest of that same list is worth carrying, because every entry produces real bleeding with a normal screen: KASABACH-MERRITT PHENOMENON, where a vascular tumour consumes platelets inside itself; CONNECTIVE TISSUE DISORDERS such as Ehlers-Danlos; SMALL VESSEL VASCULITIS; PARAPROTEINS; skin disease, infection and psychogenic causes — and TRAUMA AND SURGERY, the commonest cause of bleeding overall and the one a hematology lecture forgets.",
  {"0": "Factor 13 deficiency also has a normal PT, aPTT and platelet count, which makes it a fair thought. Its signature is DELAYED bleeding — umbilical stump bleeding, bleeding hours after a procedure — and delayed wound healing, not visible vascular lesions on the lips and fingers.",
   "1": "Glanzmann thrombasthenia causes mucocutaneous bleeding with a normal screen, so the pattern fits at first glance. It is excluded by his NORMAL PLATELET AGGREGATION STUDIES, and it would not produce telangiectases.",
   "3": "Immune thrombocytopenia produces petechiae and purpura with a LOW platelet count. His count is 284,000/mm3 and he has no petechiae.",
   "4": "Type 1 von Willebrand disease is the commonest inherited bleeding disorder and causes exactly this mucosal bleeding pattern — which is why it must be excluded, as it has been here. His von Willebrand antigen and ristocetin cofactor activity are both normal."},
  "Every clotting test he has is perfect. The problem is not the blood at all — it is the blood vessels, which have fragile abnormal connections that tear and bleed. You can see them on his lips and fingertips.",
  exim="fig_slide_three_ingredients",
  excap="The three ingredients for clotting. The third one — healthy vessels — is invisible to every test on the coagulation panel.")

# ── 2. What the natural anticoagulants actually do (§29) ────────────────────
q("A 28-year-old man is evaluated after a second unprovoked deep venous thrombosis. His father had a pulmonary embolism at age 35. Testing performed 3 months after completing anticoagulation shows a protein C activity of 42% (N=70%–140%), with normal protein S, normal antithrombin, and no factor V Leiden or prothrombin gene mutation. His prothrombin time, activated partial thromboplastin time, and platelet count are normal.\n\nThe deficient protein normally inactivates which of the following?",
  ["A. Factor Xa and thrombin",
   "B. Factors IXa and XIa",
   "C. Factors Va and VIIIa",
   "D. Fibrinogen and factor XIII",
   "E. Tissue factor and factor VIIa"],
  2,
  "PROTEIN C AND PROTEIN S — TOGETHER THEY INACTIVATE FACTORS 5a AND 8a. Protein S is the cofactor; activated protein C is the protease. Losing that brake leaves factors 5a and 8a active for longer, and thrombin generation runs on.\n\nThe natural anticoagulants are a short list worth knowing whole, because each one is a disease when it fails:\n• PROTEIN C AND PROTEIN S — inactivate factors 5a and 8a. Deficiencies of these are two of the most important thrombophilias.\n• ANTITHROMBIN III — neutralises THROMBIN AND FACTOR 10a. THIS IS THE PROTEIN HEPARIN WORKS THROUGH, which is why antithrombin deficiency makes heparin less effective.\n• PLASMIN — digests fibrin; tissue plasminogen activator converts plasminogen to plasmin.\n• AN INTACT ENDOTHELIAL SURFACE — expresses HEPARANS, so a healthy vessel lining is ACTIVELY anticoagulant rather than merely neutral. Heparin therapy is essentially borrowing a mechanism the endothelium already uses.\n\nThe naming trap that costs marks: PROTEIN C AND PROTEIN S ARE ANTICOAGULANTS; FACTOR 5 AND FACTOR 8 ARE PROCOAGULANTS. Because protein C inactivates factor 5, a mutation that makes factor 5 RESISTANT to protein C — FACTOR V LEIDEN — produces the same net effect as losing protein C: more clotting. His testing excluded that mutation, so the lesion is in the brake rather than in its target.\n\nAnd the mirror image completes the logic: TOO MUCH ANTIPLASMIN, or overexpression of the fibrinolysis inhibitors, CAUSES A CLOTTING PROBLEM, because clots are not taken down when they should be.",
  {"0": "Thrombin and factor 10a are the targets of ANTITHROMBIN III, which is a different anticoagulant — and the one heparin works through. His antithrombin is normal.",
   "1": "Factors 9a and 11a sit in the intrinsic arm and are not the targets of the protein C system. Factor 11 is notable instead as hemophilia C, and as one of the factors thrombin feeds back to activate.",
   "3": "Fibrinogen is cleaved by THROMBIN to make fibrin, and factor 13 cross-links that fibrin afterward. Neither is inactivated by protein C, and fibrin is dismantled by plasmin rather than by an anticoagulant protein.",
   "4": "Tissue factor and factor 7a form the extrinsic initiating complex, and they are regulated by TISSUE FACTOR PATHWAY INHIBITOR — a different brake. That is the target of the anti-TFPI antibodies used to rebalance hemostasis in hemophilia."},
  "Clotting has brakes as well as accelerators. His missing brake is the one that switches off two specific clotting proteins — so once clotting starts, it does not get turned off properly, and he clots too easily.",
  exim="fig_slide_cascade",
  excap="The cascade with its brakes. Protein C and protein S inactivate factors 5a and 8a; antithrombin neutralises thrombin and factor 10a.")

# ── 3. Factor VIII separates liver disease from DIC (§31) ───────────────────
q("A 63-year-old man with known cirrhosis is admitted with fever, hypotension, and spontaneous bacterial peritonitis. He has oozing from venipuncture sites. The team cannot decide whether his coagulopathy reflects his liver disease, a superimposed consumptive process, or both.\n\nLaboratory studies show:\nHemoglobin 9.4 g/dL (N=13.0–16.0 g/dL)\nHematocrit 29% (N=37%–49%)\nPlatelet count 52,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 24 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 56 seconds (N=25–35 seconds)\nFibrinogen 130 mg/dL (N=200–400 mg/dL)\nD-dimer 9.8 µg/mL (N=<0.5 µg/mL)\n\nWhich of the following assays best distinguishes the two possibilities?",
  ["A. D-dimer concentration",
   "B. Factor V activity",
   "C. Factor VIII activity",
   "D. Fibrinogen concentration",
   "E. Platelet count"],
  2,
  "FACTOR 8 IS NORMAL OR HIGH IN LIVER DISEASE BUT LOW IN DIC. WHEN LIVER DISEASE AND DIC ARE HARD TO SEPARATE, THAT IS THE DISCRIMINATING ASSAY.\n\nThe reason is where the protein is made. THE LIVER MAKES ALL OF THE COAGULATION FACTORS EXCEPT VON WILLEBRAND FACTOR AND FACTOR 8. Von Willebrand factor comes from endothelial cells and megakaryocytes; factor 8 is largely endothelial in origin and is carried in plasma bound to von Willebrand factor. So in hepatic synthetic failure EVERYTHING FALLS EXCEPT THESE TWO — and factor 8 is often HIGH, since it is also an acute-phase reactant. In DIC, by contrast, factor 8 is CONSUMED ALONG WITH EVERYTHING ELSE.\n\nThis matters here because every other number is ambiguous. Cirrhosis alone produces thrombocytopenia (splenic sequestration, low thrombopoietin), prolonged clotting times, and a low fibrinogen in advanced disease — and a raised D-dimer is common in decompensated cirrhosis too. None of those separates the two diagnoses.\n\nThe companion discriminator, running the other way, is FACTOR 5: LOW 2, 7, 9, 10 WITH A NORMAL FACTOR 5 = VITAMIN K DEFICIENCY; EVERYTHING LOW INCLUDING FACTOR 5 = LIVER. Factor 5 is made by the liver but is not vitamin K dependent — so it separates liver disease from vitamin K deficiency, and factor 8 separates liver disease from DIC. Two different questions, two different assays.\n\nIn practice he may well have both, since sepsis is the commonest trigger for DIC — and the management is the same either way: treat the infection, and give products for bleeding rather than to correct numbers.",
  {"0": "The D-dimer is already raised at 9.8 µg/mL, and it rises in decompensated cirrhosis as well as in DIC — reduced hepatic clearance of fibrin degradation products contributes. It cannot arbitrate between the two.",
   "1": "Factor 5 is the discriminator between LIVER DISEASE and VITAMIN K DEFICIENCY, which is a genuinely useful test — but it is low in both liver disease and DIC, since the liver makes it and consumption destroys it.",
   "3": "Fibrinogen is low here at 130 mg/dL, and a falling trend is one of the four legs of DIC. Advanced cirrhosis also lowers it through reduced synthesis and dysfibrinogenemia, so the value alone does not decide.",
   "4": "Thrombocytopenia is expected in cirrhosis from splenic sequestration and reduced thrombopoietin, and is also a cardinal feature of DIC. It is the least discriminating number on his panel."},
  "Almost every clotting protein is made by the liver — but one is not. If that one is normal or high, the liver is simply failing to make the others. If it is low too, something is actively consuming everything.",
  exim="fig_slide_dic",
  excap="DIC consumes factors and platelets indiscriminately — including factor 8, which hepatic failure leaves untouched.")

# ── 4. Thrombin amplifies its own production (§29) ─────────────────────────
q("A student is studying the coagulation cascade and asks why a system built from a series of sequential enzyme reactions can seal a wound in seconds rather than minutes. The attending points to the dotted feed-forward arrows on the diagram and explains that the enzyme at the end of the cascade acts back on several steps upstream of itself.\n\nWhich of the following best describes that mechanism?",
  ["A. Calcium is a required cofactor at every step of the cascade",
   "B. Factor XIII cross-links fibrin once the clot has formed",
   "C. Thrombin activates factors V, VIII, XI and XIII, amplifying itself",
   "D. Tissue factor is exposed only at the site of vascular injury",
   "E. Von Willebrand factor carries factor VIII through the plasma"],
  2,
  "The dotted feed-forward arrows are the part people skip when they learn the cascade: THROMBIN ACTIVATES FACTORS 5, 8, 11 AND 13. IT ACCELERATES ITS OWN PRODUCTION, WHICH IS WHAT MAKES THE RESPONSE FAST ENOUGH TO BE USEFUL.\n\nWork through what that means. Thrombin is generated in tiny amounts at first through the tissue factor pathway. Those first molecules then turn on factor 5 and factor 8 — the two COFACTORS that make the downstream reactions orders of magnitude faster — plus factor 11, which drives more factor 9 activation, and factor 13, which will cross-link the fibrin at the end. The result is an explosive burst rather than a slow linear chain.\n\nIt also explains two things that would otherwise look odd. First, why FACTOR 8a IS A COFACTOR RATHER THAN AN ENZYME — it holds factor 9a and factor 10 next to each other so the reaction can happen, which is exactly the geometry emicizumab reproduces. Second, why the system needs such powerful brakes: an amplifying loop with no regulation would consume the entire clotting system at the first injury, which is essentially what DIC is.\n\nThe cascade's architecture, for orientation: the LEFT arm runs 12 → 11 → 9 → 8 (intrinsic, measured by the aPTT), the RIGHT arm is factor 7 alone (extrinsic, measured by the PT), and they meet at FACTOR 10 and run down the shared trunk 10 → 5 → 2 (prothrombin → thrombin) → fibrinogen → fibrin, which moves BOTH tests.",
  {"0": "Calcium — 'factor 4' — genuinely is a required cofactor throughout, and it is why the citrate tube works as it does. Being required at every step is not the same as accelerating the system, and calcium is not produced by the cascade.",
   "1": "Factor 13 cross-links fibrin AFTER the clot has formed, strengthening it. Thrombin does activate factor 13, which is part of the feed-forward answer — but cross-linking itself happens at the end and adds no speed.",
   "3": "Localised tissue factor exposure is what keeps the response CONFINED to the injury — the third of the four specifications of a working system. Confinement is a different property from speed.",
   "4": "Von Willebrand factor carrying factor 8 prolongs its half-life and explains why severe von Willebrand disease lowers factor 8 secondarily. It is a transport arrangement, not an amplification loop."},
  "The final enzyme of the chain reaches back and switches on several earlier steps, so it speeds up its own production. That is what turns a slow chain of reactions into a near-instant burst.",
  exim="fig_slide_cascade",
  excap="The dotted green feed-forward lines: thrombin activating factors 5, 8, 11 and 13 — accelerating its own generation.")

# ── 5. Dysfibrinogenemia (§30) ─────────────────────────────────────────────
q("A 34-year-old woman is evaluated after an unprovoked deep venous thrombosis. She also reports easy bruising and prolonged bleeding after a dental extraction at age 22, and her brother has had both a venous thrombosis and abnormal bleeding after surgery. Her prothrombin time is 16 seconds (N=11–15 seconds), her activated partial thromboplastin time is 36 seconds (N=25–35 seconds), and her platelet count is 268,000/mm3 (N=150,000–400,000/mm3).\n\nLaboratory studies show:\nThrombin time 34 seconds (N=14–19 seconds)\nFibrinogen activity 68 mg/dL (N=200–400 mg/dL)\nFibrinogen antigen 310 mg/dL (N=200–400 mg/dL)\n\nWhich of the following is the most likely diagnosis?",
  ["A. Afibrinogenemia",
   "B. Dysfibrinogenemia",
   "C. Factor XIII deficiency",
   "D. Hypofibrinogenemia",
   "E. Primary hyperfibrinolysis"],
  1,
  "The fibrinogen disorders come in three forms, and the discriminator is ACTIVITY AGAINST ANTIGEN — the same logic as von Willebrand disease:\n• AFIBRINOGENEMIA — none at all. Both activity and antigen absent.\n• HYPOFIBRINOGENEMIA — too little. Activity and antigen both low, and proportionate.\n• DYSFIBRINOGENEMIA — PRESENT BUT NON-FUNCTIONAL. Antigen normal, activity low.\n\nHer antigen is 310 mg/dL with an activity of 68 mg/dL, so plenty of protein is present and it does not work: DYSFIBRINOGENEMIA.\n\nThe feature that makes it worth its own question is in the lecture's own wording: THIS ONE CAN CAUSE CLOTTING AS WELL AS BLEEDING. An abnormal fibrinogen may polymerise poorly, giving a bleeding phenotype; or form a clot that resists plasmin digestion, giving a thrombotic one; and some patients, like this woman and her brother, do BOTH. Roughly a quarter are asymptomatic, a quarter bleed and a fifth thrombose.\n\nThe THROMBIN TIME is the giveaway test and is markedly prolonged here, because it measures the final step directly: thrombin is added to plasma and the conversion of fibrinogen to fibrin is timed, bypassing the entire cascade above it. A prolonged thrombin time with a NORMAL fibrinogen antigen is close to diagnostic once heparin is excluded.\n\nNote the modest PT and aPTT prolongation: fibrinogen is the substrate of the COMMON pathway, so a functional deficit nudges both tests — but only modestly, because both stop timing at first fibrin, and some fibrin still forms.",
  {"0": "Afibrinogenemia is complete absence, so the ANTIGEN would be unmeasurable too. It presents in the neonatal period with umbilical stump bleeding and an infinitely prolonged thrombin time. Her antigen is 310 mg/dL.",
   "2": "Factor 13 deficiency gives DELAYED bleeding with a NORMAL PT, aPTT and thrombin time, because every one of those tests stops when the first fibrin appears — before cross-linking matters. Her thrombin time is 34 seconds.",
   "3": "Hypofibrinogenemia would show activity and antigen BOTH low and roughly proportionate. Hers differ by more than fourfold, which is the definition of a qualitative rather than a quantitative defect.",
   "4": "Primary hyperfibrinolysis — excessive plasmin activity, seen with prostate surgery, some leukemias and severe liver disease — consumes fibrinogen and raises fibrin degradation products, lowering BOTH activity and antigen. It is acquired and would not run in her family."},
  "She makes plenty of the protein that forms the mesh of a clot, but her version is built wrong. A badly built mesh can both fall apart too easily and resist being cleaned up — which is why she bleeds and clots.")

# ── 6. Dense granule storage pool disease (§30) ────────────────────────────
q("A 23-year-old woman with oculocutaneous albinism is evaluated for lifelong easy bruising, frequent nosebleeds, and prolonged bleeding after a tonsillectomy at age 8. Her parents are unaffected and are second cousins. Her prothrombin time, activated partial thromboplastin time, platelet count, and von Willebrand studies are all normal. Aggregometry shows markedly DECREASED ATP release in response to thrombin, variably decreased aggregation to arachidonic acid, collagen, and adenosine diphosphate, and a normal ristocetin response.\n\nWhich of the following is the most likely diagnosis?",
  ["A. Alpha granule storage pool disease",
   "B. Bernard-Soulier syndrome",
   "C. Dense granule storage pool disease",
   "D. Glanzmann thrombasthenia",
   "E. von Willebrand disease, type 2M"],
  2,
  "The defining row on the agonist table is the ATP RELEASE column, and it is DECREASED in DELTA (DENSE) GRANULE STORAGE POOL DISEASE and normal in everything else.\n\nWhat the aggregometer is detecting is worth stating, because it makes the finding intuitive: activated platelets change shape and release CALCIUM, SEROTONIN AND ATP from their DENSE granules. THE ATP IS WHAT THE LUCIFERASE CHANNEL SEES — the firefly reaction — while aggregation is read as LIGHT TRANSMISSION. Hence LUMI-AGGREGOMETRY. A platelet with no dense granules has nothing to release, so the luminescence channel goes flat, and because that released ATP and ADP normally recruit further platelets, aggregation to the other agonists falls variably as a secondary effect.\n\nDense granule disease includes HERMANSKY-PUDLAK and CHEDIAK-HIGASHI, both of which carry OCULOCUTANEOUS ALBINISM — her albinism is the clue that turns a non-specific aggregometry pattern into a diagnosis, since the same lysosome-related organelle biogenesis defect affects melanosomes and dense granules alike. Confirmation is by ELECTRON MICROSCOPY, added only when a granule storage pool defect is suspected.\n\nThe contrast is ALPHA granule disease — GRAY PLATELET SYNDROME — where the smear shows GRAY PLATELETS WITHOUT TYPICAL GRANULES and ATP release is NORMAL, since dense granules are intact.\n\nAnd the sequencing rule still applies: RULE OUT HEMOPHILIA AND VON WILLEBRAND DISEASE FIRST. Platelet function disorders are rare, aggregometry is a second- or third-tier test, and electron microscopy is third-tier again.",
  {"0": "Alpha granule disease — gray platelet syndrome — shows NORMAL ATP release, because the dense granules are intact, with variably decreased aggregation to the other agonists. Its clue is on the smear: large gray platelets lacking typical granules.",
   "1": "Bernard-Soulier is identified by a DECREASED RISTOCETIN response with everything else normal, plus thrombocytopenia with large platelets. Her ristocetin response and platelet count are both normal.",
   "3": "Glanzmann thrombasthenia abolishes aggregation to arachidonic acid, collagen and ADP while leaving RISTOCETIN AND ATP RELEASE NORMAL. Her ATP release is the abnormality, which points one step earlier — to the granules rather than the fibrinogen receptor.",
   "4": "Type 2M von Willebrand disease is a qualitative defect with reduced ristocetin cofactor activity, and her von Willebrand studies are normal. It also has no effect on platelet granule contents."},
  "Her platelets are missing the tiny storage packets that normally spill their contents to call in more platelets. The machine measures that release as a flash of light — and hers does not flash. Her albinism comes from the same underlying defect.",
  exim="fig_slide_agonist_table",
  excap="The agonist table. Decreased ATP release is the defining row for a dense granule storage pool defect.")

# ── 7. Type 2N — the von Willebrand disease that looks like hemophilia (§30) ─
q("A 26-year-old man is referred with a diagnosis of mild hemophilia A made after prolonged bleeding following a knee arthroscopy. He has had occasional deep bruises but no joint bleeds and no mucosal bleeding. His prothrombin time is normal and his activated partial thromboplastin time is 44 seconds (N=25–35 seconds), correcting on a 1:1 mix. His factor VIII activity is 14% (N=50%–150%). His mother and his sister have both had heavy menstrual bleeding and have factor VIII levels of 22% and 18%, and genetic testing shows no F8 mutation.\n\nLaboratory studies show:\nVon Willebrand factor antigen 88% (N=50%–200%)\nRistocetin cofactor activity 84% (N=50%–200%)\nPlatelet count 272,000/mm3 (N=150,000–400,000/mm3)\n\nWhich of the following is the most likely diagnosis?",
  ["A. Acquired factor VIII inhibitor",
   "B. Hemophilia A, mild",
   "C. Hemophilia B",
   "D. Type 2N von Willebrand disease",
   "E. Type 3 von Willebrand disease"],
  3,
  "TYPE 2N von Willebrand disease — 'Normandy' — is the subtype in which the protein CANNOT BIND AND CARRY FACTOR 8.\n\nRecall the protein's two jobs: (1) bind platelet GPIb and mediate ADHESION to exposed collagen, and (2) act as the CARRIER FOR FACTOR 8, prolonging its half-life. In type 2N the first job is intact — which is why his von Willebrand ANTIGEN AND RISTOCETIN COFACTOR ACTIVITY ARE BOTH NORMAL, and why he has no mucosal bleeding. Only the second job fails, so unbound factor 8 is cleared rapidly and the level falls, producing a prolonged aPTT and a picture indistinguishable from mild hemophilia A.\n\nThe inheritance is what gives it away, and this vignette is built on it: HEMOPHILIA A IS X-LINKED and does not affect a man's mother and sister. Type 2N is AUTOSOMAL RECESSIVE, so affected women are entirely expected. Add the absence of an F8 mutation on genetic testing and the diagnosis is made.\n\nWhy it matters: treatment differs. Giving recombinant FACTOR 8 alone to a type 2N patient produces a short-lived rise, because there is no carrier to hold it in the circulation. The right products are PLASMA-DERIVED FACTOR 8/VON WILLEBRAND FACTOR CONCENTRATES, which supply both; desmopressin gives only a transient response for the same reason.\n\nThe diagnostic test is a VON WILLEBRAND FACTOR–FACTOR 8 BINDING ASSAY. It is worth requesting in any man with apparent mild hemophilia A and a non-X-linked pedigree, and in any woman with an unexplained low factor 8.",
  {"0": "An acquired inhibitor fails to correct on a mixing study, and his corrects. It also produces a NEW diathesis in an older patient, usually with autoimmune disease or malignancy, rather than a familial pattern across three relatives.",
   "1": "Mild hemophilia A produces exactly this laboratory picture, which is why he carries the label. It is X-LINKED, so his mother would be a carrier with a mildly reduced level at most and his sister would be unaffected — and no F8 mutation was found.",
   "2": "Hemophilia B is factor 9 deficiency, also X-linked, and his factor 8 is the measured abnormality. The two are indistinguishable clinically, which is why activity assays are done — and his points to factor 8.",
   "4": "Type 3 is essentially complete ABSENCE of von Willebrand factor, with antigen and activity near zero and a severe mucocutaneous phenotype plus a very low factor 8. His antigen is 88% and his activity is 84%."},
  "His von Willebrand protein grips platelets normally, so he has no mouth or nose bleeding — but it cannot carry factor 8 around, so that factor disappears from his blood. It mimics mild hemophilia, except his mother and sister have it too, which hemophilia cannot do.",
  exim="fig_slide_vwf",
  excap="Von Willebrand factor has two jobs — gripping collagen and carrying factor 8. Type 2N breaks only the second.")

# ── 8. The thrombin time after bypass (§29) ────────────────────────────────
q("A 68-year-old man is in the intensive care unit 3 hours after coronary artery bypass grafting and has bled 900 mL into his mediastinal drains. He received unfractionated heparin during cardiopulmonary bypass and protamine at the end of the case. His temperature is 35.9°C (96.6°F), pulse is 104/min, and blood pressure is 102/60 mm Hg.\n\nLaboratory studies show:\nPlatelet count 118,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 16 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 64 seconds (N=25–35 seconds)\nFibrinogen 240 mg/dL (N=200–400 mg/dL)\nThrombin time 42 seconds (N=14–19 seconds)\nD-dimer 1.1 µg/mL (N=<0.5 µg/mL)\n\nAdding protamine to the sample normalizes the thrombin time. Which of the following best explains the findings?",
  ["A. Dysfibrinogenemia from an inherited fibrinogen variant",
   "B. Factor XIII deficiency from dilution during bypass",
   "C. Hypofibrinogenemia from consumption on the circuit",
   "D. Residual circulating unfractionated heparin",
   "E. Vitamin K deficiency from preoperative fasting"],
  3,
  "The thrombin time measures the LAST step only: thrombin is added to plasma and the conversion of FIBRINOGEN TO FIBRIN is timed, bypassing the entire cascade above it. So a prolonged thrombin time has a short differential — HEPARIN, a fibrinogen problem (too little, or abnormal), or high concentrations of fibrin degradation products.\n\nHeparin is the answer here, and the vignette supplies the proof: ADDING PROTAMINE TO THE SAMPLE NORMALIZES THE THROMBIN TIME. Protamine neutralises heparin, so a correction identifies the interfering substance directly. (The other classical version of this test is the REPTILASE TIME, which is insensitive to heparin: prolonged thrombin time with a NORMAL reptilase time means heparin, while both prolonged means a fibrinogen problem.)\n\nClinically this is HEPARIN REBOUND after cardiac surgery — heparin redistributing out of tissues after protamine has been cleared, since protamine has the shorter half-life. It is a recognised cause of postoperative bleeding and is treated with further protamine rather than with plasma or platelets.\n\nThe rest of his panel fits a dilutional and mildly consumptive postoperative picture but does not explain a thrombin time of 42 seconds: his fibrinogen is 240 mg/dL, normal, and his D-dimer is only mildly raised.\n\nThe disproportion between the aPTT (64 seconds) and the PT (16 seconds) is the other heparin signature, since heparin acting through antithrombin hits the intrinsic and common pathways far harder than the extrinsic arm.",
  {"0": "An inherited dysfibrinogenemia also prolongs the thrombin time and would give a low fibrinogen ACTIVITY with a normal antigen — but it would not correct with protamine, and it would have declared itself before his seventh decade.",
   "1": "Factor 13 deficiency leaves the PT, aPTT AND thrombin time normal, because all three stop timing when the first fibrin appears. Acquired factor 13 depletion after bypass is described as a cause of bleeding, but it would not prolong any of these tests.",
   "2": "Consumption or dilution of fibrinogen on the bypass circuit is a genuine and common cause of post-bypass bleeding, and a fibrinogen below about 150 mg/dL would prolong the thrombin time. His is 240 mg/dL.",
   "4": "Vitamin K deficiency prolongs the PT first, through factor 7, and does not touch the thrombin time at all — it operates far upstream of the fibrinogen-to-fibrin step."},
  "One test looks only at the very last step of clotting, and it is dramatically slow. Adding the heparin antidote to the test tube fixes it instantly — which proves the leftover blood thinner from his surgery is the cause.",
  exim="fig_slide_pt_aptt_coverage",
  excap="Which test covers which pathway. The thrombin time sits below all of them, reading only fibrinogen to fibrin.")

# ── 9. Kasabach-Merritt phenomenon (§30) ──────────────────────────────────
q("A 7-week-old girl is brought in because of a rapidly enlarging, firm, purple-red mass on the left thigh that has grown since birth and is now 9 cm across, with overlying skin tension and bruising. She has petechiae on the trunk and has bled at her immunization sites. Her temperature is 36.9°C (98.4°F), pulse is 162/min, and respirations are 48/min. Physical examination shows no hepatosplenomegaly and no lymphadenopathy.\n\nLaboratory studies show:\nHemoglobin 8.4 g/dL (N=10.5–13.5 g/dL)\nPlatelet count 14,000/mm3 (N=150,000–400,000/mm3)\nProthrombin time 19 seconds (N=11–15 seconds)\nActivated partial thromboplastin time 48 seconds (N=25–35 seconds)\nFibrinogen 92 mg/dL (N=200–400 mg/dL)\nD-dimer 12.6 µg/mL (N=<0.5 µg/mL)\n\nThe blood smear shows schistocytes. Which of the following best explains her findings?",
  ["A. Consumption of platelets within a vascular tumor",
   "B. Immune destruction of platelets by maternal antibody",
   "C. Infiltration of the marrow by metastatic tumor",
   "D. Sequestration of platelets in an enlarged spleen",
   "E. Shear-induced cleavage of von Willebrand multimers"],
  0,
  "KASABACH-MERRITT PHENOMENON — a VASCULAR TUMOUR THAT CONSUMES PLATELETS INSIDE ITSELF. It belongs to the short list of causes of bleeding that are NOT THE COAGULATION SYSTEM AT ALL, alongside hereditary hemorrhagic telangiectasia, connective tissue disorders, small vessel vasculitis and paraproteins.\n\nThe mechanism is local rather than systemic: the abnormal, disorganised vascular channels of the tumour trap and activate platelets, which triggers coagulation within the lesion. The result is a LOCALISED CONSUMPTIVE COAGULOPATHY that looks exactly like DIC on a panel — profound thrombocytopenia, prolonged PT and aPTT, a low fibrinogen, a markedly raised D-dimer, and SCHISTOCYTES from red cells sheared through the lesion.\n\nThe distinguishing feature is that THE TUMOUR IS THE CAUSE AND THE TREATMENT TARGET. Unlike true DIC, there is no sepsis, malignancy, obstetric catastrophe or trauma driving it — there is a mass you can see and measure. Treatment is directed at the lesion: sirolimus, corticosteroids, vincristine, or embolisation and resection, with platelets and products reserved for active bleeding.\n\nOne point of nomenclature worth knowing, since it appears in questions: the associated tumours are KAPOSIFORM HEMANGIOENDOTHELIOMA and TUFTED ANGIOMA — not the common infantile hemangioma, which does not cause this and usually involutes on its own.\n\nThe general lesson this question carries: when a consumptive panel appears with no systemic trigger, look for a LOCAL one.",
  {"1": "Neonatal alloimmune thrombocytopenia — maternal antibody against paternal platelet antigens — causes severe isolated thrombocytopenia with petechiae and a risk of intracranial hemorrhage. It does not consume fibrinogen, prolong the clotting times, or produce schistocytes, and it presents in the first days of life.",
   "2": "Marrow infiltration crowds out production and produces a leukoerythroblastic smear with nucleated red cells and tear-drop cells. It would not consume fibrinogen or raise the D-dimer to 12.6 µg/mL, and she has no hepatosplenomegaly or lymphadenopathy.",
   "3": "Hypersplenism pools platelets in an enlarged spleen and lowers the count, usually modestly and without a coagulopathy. Her examination explicitly records no splenomegaly.",
   "4": "Shear-induced cleavage of von Willebrand multimers is the mechanism of acquired von Willebrand syndrome in aortic stenosis — Heyde syndrome. It causes mucosal bleeding with a normal platelet count and normal fibrinogen, not a consumptive picture."},
  "The big purple lump on her thigh is a tangle of abnormal blood vessels, and her platelets and clotting proteins are being used up inside it. Her blood tests look like a body-wide clotting crisis, but the cause is one lesion you can point at.")

# ── 10. Viscoelastic testing in massive hemorrhage (§29) ───────────────────
q("A 29-year-old man is brought to the trauma bay after a motor vehicle collision with a pelvic fracture and ongoing hemorrhage. He has received 6 units of packed red blood cells and 4 units of plasma, and remains hypotensive with diffuse oozing from wounds and line sites. He is hypothermic at 34.8°C (94.6°F) and acidotic. The trauma team needs to know within minutes whether he needs fibrinogen, platelets, or an antifibrinolytic, and conventional coagulation results take 45 minutes to return in this laboratory.\n\nWhich of the following tests assesses clot initiation, clot strength, and clot lysis together in whole blood?",
  ["A. Activated partial thromboplastin time",
   "B. D-dimer concentration",
   "C. Platelet aggregometry with agonist panel",
   "D. Prothrombin time with international ratio",
   "E. Thromboelastography"],
  4,
  "THROMBOELASTOGRAPHY (TEG) and rotational thromboelastometry (ROTEM) are the VISCOELASTIC WHOLE-BLOOD tests, and the entry in the testing table says exactly what they add: they MONITOR CLOT INITIATION, STRENGTH AND LYSIS TOGETHER, IN WHOLE BLOOD.\n\nCompare what the conventional tests do. The PT and aPTT are PLASMA assays: the sample is spun and THE CELLS, INCLUDING EVERY PLATELET, ARE DISCARDED WITH THE PELLET, and the instrument then times to the appearance of THE FIRST FIBRIN STRAND and stops. So they are blind to platelet contribution, blind to clot strength, and blind to whether the clot is subsequently dissolved — which is why a patient can have an acceptable PT and still have a mechanically useless clot.\n\nThat blindness matters most in exactly this patient. Roughly TWO THIRDS OF THE MECHANICAL STRENGTH OF A CLOT COMES FROM THE PLATELETS enmeshed in it, and trauma-induced coagulopathy includes HYPERFIBRINOLYSIS, which no conventional test detects at all. A viscoelastic trace separates those problems: a slow initiation points to factors and plasma, a weak maximum amplitude points to fibrinogen and platelets, and a falling trace after peak strength points to fibrinolysis and an antifibrinolytic such as tranexamic acid.\n\nThe practical argument is the one embedded in the stem: results in minutes, at the bedside, on whole blood, against 45 minutes for a plasma assay that answers a narrower question. Also worth remembering: hypothermia and acidosis themselves impair enzyme function, and the laboratory warms every sample to 37°C — so the reported numbers understate the coagulopathy of a cold patient.",
  {"0": "The aPTT reports the intrinsic and common pathways and stops at first fibrin. It says nothing about platelet contribution, clot strength or lysis, and here it would take 45 minutes to return.",
   "1": "A D-dimer confirms that fibrin has been formed, cross-linked and broken down — it is a marker of clot turnover. In a bleeding trauma patient it will be raised regardless and cannot guide which product to give.",
   "2": "Platelet aggregometry measures platelet function in response to specific agonists, and it is a specialised, time-consuming, second- or third-tier investigation. It is not a point-of-care test for active hemorrhage.",
   "3": "The PT and its standardised form, the international normalized ratio, read the extrinsic and common pathways in plasma. The INR is calibrated for warfarin monitoring and performs poorly as a measure of global hemostasis in trauma."},
  "The standard clotting tests use plasma with the platelets removed, and they stop the clock the instant the first thread of clot appears. This test uses whole blood and watches the whole story — how fast the clot forms, how strong it gets, and whether it dissolves again.",
  exim="fig_slide_pt_aptt_coverage",
  excap="The conventional tests each read one slice of the system; a viscoelastic test reads initiation, strength and lysis in one trace.")
