# Jeevs Edition — Batch 09: Anemia Pharmacology
# Source: OMK_2A_Heme_Summative_3_Objective_Review.html
#   §17 s16-anemia-drugs — oral and IV iron, chelators, B12/folate, ESAs, HIF-PHI,
#                          luspatercept, complement inhibitors   (LO 9, 70, 72)
# Explanation figures are the course's own lecture slides (assets/anemiadrug-*).
# Options alphabetised; "correct" is the 0-based index AFTER alphabetisation.
Q = []


def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)


# ── 1. Acid, Fe2+, and the proton pump inhibitor (§17) ────────────────────────
q("A 58-year-old woman with iron deficiency anemia from menorrhagia has taken ferrous sulfate 325 mg three times daily for 4 months. She reports taking every dose and tolerates it well. She also takes omeprazole 40 mg daily for gastroesophageal reflux, which she swallows with her morning iron tablet. She eats a varied diet and her menstrual bleeding has been controlled for 6 months. Her temperature is 36.9°C (98.4°F), pulse is 84/min, and blood pressure is 118/72 mm Hg.\n\nLaboratory studies show:\nHemoglobin 9.8 g/dL (N=12.0–16.0 g/dL)\nHematocrit 29% (N=36%–46%)\nMean corpuscular volume 74 µm3 (N=80–100 µm3)\nReticulocyte count 1.0% (N=0.5%–1.5%)\nSerum ferritin 8 ng/mL (N=10–120 ng/mL)\nTotal iron-binding capacity 448 µg/dL (N=250–400 µg/dL)\nC-reactive protein 0.2 mg/dL (N=<1.0 mg/dL)\n\nHer hemoglobin was 9.5 g/dL 4 months ago. Which of the following best explains the failure of her oral iron therapy?",
  ["A. Impaired absorption because gastric acid suppression prevents reduction of ferric to ferrous iron",
   "B. Impaired incorporation of iron into heme despite adequate absorption",
   "C. Ongoing gastrointestinal blood loss exceeding the absorbed dose",
   "D. Sequestration of absorbed iron within macrophages by hepcidin",
   "E. Suppression of erythropoietin production by chronic inflammation"],
  0,
  "Only FERROUS iron (Fe²⁺) crosses the gut wall, and only in an acidic duodenum. Dietary and supplemental iron arrives substantially as ferric (Fe³⁺), which must be reduced first — and that reduction depends on gastric acid.\n\nOmeprazole 40 mg daily raises gastric pH profoundly, so the ferric iron is never reduced and never absorbed. Taking the two together, as she does, is the worst possible timing. Antacids and H2 receptor blockers do the same thing, which is why the instruction is to separate them: iron 2 hours BEFORE, or 4 hours AFTER, an antacid.\n\nThe memory hook: Fe²⁺ = Free to enter. The '2' gets through the door; Fe³⁺ needs a reducing agent, which is why vitamin C helps — it both lowers pH and converts Fe³⁺ to Fe²⁺.\n\nEverything else in this vignette excludes a competing explanation on purpose: she is adherent and tolerating the drug (so the commonest cause, gastrointestinal intolerance and quiet non-adherence, is out), her menorrhagia is controlled (no ongoing loss), and her C-reactive protein is 0.2 mg/dL with a low ferritin and a high iron-binding capacity (not anemia of inflammation).\n\nThe fix: separate the doses, add vitamin C or switch to ferric maltol, or move to intravenous iron — she has now failed 4 months of oral therapy.",
  {"1": "Iron reaching the marrow but not being incorporated into heme is the sideroblastic pattern — lead poisoning, alcohol, isoniazid, or a myelodysplastic syndrome — and it comes with a HIGH ferritin and ringed sideroblasts. Her ferritin is 8 ng/mL, so almost no iron is getting in at all.",
   "2": "Continued blood loss outpacing absorption is a genuine reason oral iron fails, and it is why the source must always be found. Her menorrhagia has been controlled for 6 months and there is no other bleeding described, so nothing is draining the iron she absorbs.",
   "3": "Hepcidin-mediated sequestration is the mechanism of anemia of inflammation, in which iron is trapped in macrophages — producing a low serum iron with a LOW iron-binding capacity and a normal or high ferritin. Her iron-binding capacity is 448 µg/dL and her ferritin is 8 ng/mL, the opposite row.",
   "4": "Suppressed erythropoietin production occurs in chronic kidney disease and in inflammation, and would give a hypoproliferative anemia with normal iron studies. Her iron studies are unambiguously deficient, and her C-reactive protein is normal."},
  "Iron can only cross the gut wall in one particular chemical form, and stomach acid is what converts it. Her reflux medicine removes the acid, so the iron tablet passes straight through — especially since she takes them together.",
  exim="fig_slide_ida_tree",
  excap="Lecture slide: the treatment algorithm for iron deficiency anemia, including when oral therapy should be abandoned.")

# ── 2. When to give up on the oral route (§17) ────────────────────────────────
q("A 34-year-old woman with celiac disease diagnosed 2 years ago comes to the office because of fatigue. She has adhered to a gluten-free diet imperfectly and has intermittent diarrhea. She has taken ferrous sulfate 325 mg twice daily for 3 months and reports taking it consistently, with only mild nausea. Her menstrual periods are regular and light. Her temperature is 36.8°C (98.2°F), pulse is 92/min, and blood pressure is 106/66 mm Hg. Physical examination shows conjunctival pallor and angular cheilitis; the abdomen is soft and nontender.\n\nLaboratory studies show:\nHemoglobin 9.2 g/dL (N=12.0–16.0 g/dL)\nHematocrit 28% (N=36%–46%)\nMean corpuscular volume 71 µm3 (N=80–100 µm3)\nReticulocyte count 0.9% (N=0.5%–1.5%)\nSerum ferritin 6 ng/mL (N=10–120 ng/mL)\nTotal iron-binding capacity 462 µg/dL (N=250–400 µg/dL)\nTissue transglutaminase IgA antibody 88 U/mL (N=<20 U/mL)\n\nHer hemoglobin was 9.0 g/dL when oral iron was started. Which of the following is the most appropriate next step in management?",
  ["A. Add ascorbic acid to each oral iron dose and continue for 3 more months",
   "B. Administer intravenous iron",
   "C. Begin an erythropoiesis-stimulating agent",
   "D. Increase ferrous sulfate to three times daily",
   "E. Transfuse 2 units of packed red blood cells"],
  1,
  "Iron is absorbed in the DUODENUM, and celiac disease damages exactly that segment. With active disease — her tissue transglutaminase antibody is 88 U/mL and she has ongoing diarrhea — no oral dose will be reliably absorbed, however faithfully she takes it. Three months of adherent therapy moved her hemoglobin by 0.2 g/dL, which is the demonstration.\n\n§17 lists when to abandon the oral route: iron malabsorption, intolerance of oral iron, non-adherence, severe or ongoing blood loss (losing it faster than the gut can absorb), gastric surgery, and malabsorption syndromes — celiac disease, Whipple disease, bacterial overgrowth. She meets the first and last.\n\nIntravenous iron bypasses the duodenum, the acid requirement and the hepcidin door entirely. Give it slowly with observation for infusion reactions; if she had asthma or multiple drug allergies, premedicate with methylprednisolone 125 mg intravenously — NOT diphenhydramine.\n\nAlongside the iron, her celiac disease needs attention, since the malabsorption will otherwise recur and will also cost her folate and, in time, B12.\n\nKnowing it worked: a reticulocyte bump at 7 to 10 days, then roughly 1 g/dL of hemoglobin every 2 to 3 weeks.",
  {"0": "Ascorbic acid genuinely helps oral absorption — it lowers pH and reduces Fe³⁺ to Fe²⁺ — and would be a reasonable adjustment in a patient with an intact duodenum. It cannot rescue absorption across a damaged mucosal surface, and another 3 months of failure is time she does not need to lose.",
   "2": "An erythropoiesis-stimulating agent drives the marrow to build red cells, which consumes iron rapidly. Giving one to an iron-deplete patient produces functional iron deficiency and no hemoglobin response — iron first, signal second. Her erythropoietin response is presumably intact anyway.",
   "3": "Raising the dose increases gastrointestinal side effects without increasing absorption across damaged duodenum — and more frequent dosing is counterproductive in any case, since each dose spikes hepcidin for about a day, which is the argument for alternate-day rather than three-times-daily regimens.",
   "4": "Transfusion is for symptomatic or severe anemia, typically below 7 g/dL in a stable patient. She is at 9.2 g/dL and not acutely compromised; transfusing exposes her to reactions and alloimmunization when a definitive, safe treatment for the deficiency exists."},
  "Iron is only absorbed in one short stretch of gut, and her celiac disease has damaged exactly that stretch. No matter how many tablets she swallows, they cannot get in — so the iron has to go into a vein instead.",
  exim="fig_slide_ida_tree",
  excap="Lecture slide: the iron deficiency treatment algorithm — the branch points that send a patient from the oral to the intravenous route.")

# ── 3. Premedicating an iron infusion (§17) ───────────────────────────────────
q("A 42-year-old woman with iron deficiency anemia and intolerance of oral iron is scheduled for her first intravenous iron infusion. She has moderate persistent asthma treated with an inhaled corticosteroid, and reports allergies to penicillin and to sulfa drugs, both causing rash. She has never received intravenous iron before. Her temperature is 36.9°C (98.4°F), pulse is 82/min, respirations are 16/min, and blood pressure is 116/70 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 98%. Physical examination shows clear lungs.\n\nLaboratory studies show:\nHemoglobin 9.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 28% (N=36%–46%)\nMean corpuscular volume 73 µm3 (N=80–100 µm3)\nSerum ferritin 7 ng/mL (N=10–120 ng/mL)\n\nWhich of the following is the most appropriate premedication?",
  ["A. Intravenous diphenhydramine",
   "B. Intravenous methylprednisolone",
   "C. Intravenous ondansetron",
   "D. No premedication is indicated",
   "E. Subcutaneous epinephrine"],
  1,
  "For a patient with asthma or more than one drug allergy, §17 specifies methylprednisolone 125 mg intravenously — a corticosteroid, given because these patients are at higher risk of an infusion reaction.\n\nThe heavily tested half is what NOT to give. Diphenhydramine is the reflexive choice and it is wrong twice over. It does not prevent the reaction, and it causes its own: hypotension, somnolence, flushing, dizziness, irritability, nasal congestion, wheezing and supraventricular tachycardia. That list looks exactly like the infusion reaction you were trying to prevent — so the patient gets the reaction anyway, it is attributed to the iron, and they are labelled iron-allergic for life. Steroid yes, Benadryl no.\n\nThe distinction that makes all of this manageable: non-allergic INFUSION reactions are common and self-limiting — urticaria, palpitations, dizziness, and neck and back spasm — and are not anaphylaxis. They are managed by stopping, observing, and restarting at a slower rate. True anaphylaxis is exceedingly rare with modern preparations.\n\nThe universal rules for every intravenous iron product: start slowly, observe, and reduce the dose or rate if reactions occur.",
  {"0": "Diphenhydramine is the classic error. It has no preventive efficacy for iron infusion reactions, and its own adverse effects — hypotension, flushing, wheezing, tachycardia — mimic the reaction so closely that patients are wrongly labelled iron-intolerant.",
   "2": "Ondansetron treats nausea and vomiting, which are not the feature of an iron infusion reaction that matters. It would be reasonable symptomatic therapy during chemotherapy; it does nothing about hypersensitivity or the hemodynamic features.",
   "3": "No premedication is the correct approach for most patients receiving intravenous iron — routine premedication is not recommended. She is the exception: asthma plus more than one drug allergy is precisely the profile for which corticosteroid premedication is specified.",
   "4": "Epinephrine is the TREATMENT for anaphylaxis, given when it occurs. Administering it prophylactically to a patient with asthma and a normal blood pressure would cause tachycardia and hypertension for no benefit, and it would mask the early signs of a genuine reaction."},
  "She has asthma and several drug allergies, so she gets a steroid before the iron drip. The antihistamine everyone reaches for does not prevent anything and causes side effects that look just like the reaction — so it gets blamed on the iron.",
  exim="fig_slide_iron_ae",
  excap="Lecture slide on adverse effects of iron therapy, including the infusion reactions that premedication is chosen to address.")

# ── 4. Ferric carboxymaltose and phosphate (§17) ──────────────────────────────
q("A 46-year-old woman with heavy menstrual bleeding and iron deficiency has received two doses of intravenous ferric carboxymaltose over the past 6 weeks. She returns because of 2 weeks of diffuse bone pain, proximal muscle weakness, and fatigue that is worse than before treatment. She takes no other medications. Her temperature is 36.8°C (98.2°F), pulse is 78/min, and blood pressure is 118/74 mm Hg. Physical examination shows proximal muscle weakness and tenderness over both tibiae.\n\nLaboratory studies show:\nHemoglobin 12.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 37% (N=36%–46%)\nSerum ferritin 186 ng/mL (N=10–120 ng/mL)\nPhosphorus 1.2 mg/dL (N=3.0–4.5 mg/dL)\nCalcium 9.2 mg/dL (N=8.4–10.2 mg/dL)\nAlkaline phosphatase 186 U/L (N=25–100 U/L)\nCreatinine 0.8 mg/dL (N=0.6–1.2 mg/dL)\nIntact parathyroid hormone 42 pg/mL (N=10–60 pg/mL)\n\nWhich of the following best explains these findings?",
  ["A. Increased fibroblast growth factor 23 activity causing renal phosphate wasting",
   "B. Osteomalacia from vitamin D deficiency",
   "C. Primary hyperparathyroidism",
   "D. Redistribution of phosphate into newly formed erythrocytes",
   "E. Tumor-induced osteomalacia from an occult mesenchymal tumor"],
  0,
  "Ferric carboxymaltose raises fibroblast growth factor 23 (FGF23), the hormone that makes the kidney dump phosphate. Urinary phosphate excretion rises, serum phosphate falls, and the hypophosphatemia can be SEVERE and prolonged — particularly after repeated doses, as here.\n\nThe clinical picture is one of phosphate-deficient bone and muscle: bone pain, proximal myopathy, fatigue, a raised alkaline phosphatase, and in prolonged cases osteomalacia with pseudofractures. Her parathyroid hormone is normal and her calcium is normal, which separates this from the parathyroid causes — FGF23 acts independently of them.\n\nThe memory hook: CarboxyMaltose Munches Phosphate. Three C's for one drug — Carboxymaltose, Crashes phosphate, Cardiac indication. That third C is its other flagship fact: ferric carboxymaltose is approved for NYHA class II/III heart failure with reduced ejection fraction and iron deficiency, WITH OR WITHOUT anemia, to improve exercise capacity — treating the iron-starved myocyte rather than the hemoglobin.\n\nManagement: check phosphate before and after repeat courses, replace phosphate, and for future dosing use ferric derisomaltose, which produces notably less hypophosphatemia and can give total replacement in a single visit.\n\nNote that her iron deficiency has been corrected — hemoglobin 12.4 g/dL, ferritin 186 ng/mL. The treatment worked; this is its adverse effect.",
  {"1": "Vitamin D deficiency causes osteomalacia with bone pain and a raised alkaline phosphatase, so the presentation overlaps — but it produces a LOW or low-normal calcium with a compensatory rise in parathyroid hormone. Her calcium is 9.2 mg/dL and her parathyroid hormone is 42 pg/mL, both normal.",
   "2": "Primary hyperparathyroidism also lowers phosphate, by reducing renal reabsorption — but it does so with HYPERcalcemia and a raised parathyroid hormone. Both of hers are normal, which excludes it.",
   "3": "A shift of phosphate into newly formed cells does occur when a starved marrow suddenly restarts — the refeeding-type phenomenon also seen after B12 replacement. Her hemoglobin has risen only modestly, and that mechanism does not produce sustained hypophosphatemia at 1.2 mg/dL with bone pain over weeks.",
   "4": "Tumor-induced osteomalacia is the other FGF23-mediated syndrome and produces an identical biochemical picture — which is what makes it the near-miss. It would be the answer without an obvious iatrogenic cause; here two doses of the one intravenous iron known to do this precede the illness."},
  "This particular iron infusion switches on a hormone that tells the kidney to throw phosphate away. Without enough phosphate, bones ache and muscles weaken — and the iron itself worked fine.",
  exim="fig_slide_iron_ae",
  excap="Lecture slide on the adverse effects of iron therapy, oral and intravenous.")

# ── 5. Acute iron overdose (§17) ──────────────────────────────────────────────
q("A 2-year-old boy is brought to the emergency department 90 minutes after his mother found him with an open bottle of her prenatal iron tablets; an estimated 20 tablets are missing. He has vomited four times, twice with blood-streaked material, and has had one episode of diarrhea. His temperature is 36.9°C (98.4°F), pulse is 168/min, respirations are 36/min, and blood pressure is 72/40 mm Hg. Physical examination shows lethargy, cool extremities, and diffuse abdominal tenderness.\n\nLaboratory studies show:\nSerum iron 640 µg/dL (N=65–175 µg/dL)\nGlucose 168 mg/dL (N=70–100 mg/dL)\nBicarbonate 12 mEq/L (N=22–28 mEq/L)\nArterial pH 7.21 (N=7.35–7.45)\nAnion gap 22 mEq/L (N=8–12 mEq/L)\nAlanine aminotransferase 64 U/L (N=10–40 U/L)\n\nAbdominal radiography shows multiple radiopaque tablets in the stomach and small bowel. Which of the following is the most appropriate antidote?",
  ["A. Deferasirox",
   "B. Deferiprone",
   "C. Deferoxamine",
   "D. N-acetylcysteine",
   "E. Succimer"],
  2,
  "Acute iron poisoning is classically an accidental pediatric ingestion of adult iron tablets, and iron remains one of the leading causes of poisoning death in young children. The antidote is DEFEROXAMINE, given PARENTERALLY: it chelates free iron and is excreted in the urine, classically turning it a reddish 'vin rosé' colour.\n\nHis presentation is the full syndrome — vomiting and hematemesis from direct corrosive injury to the mucosa, hypotension from fluid loss and vasodilation, and a high anion gap metabolic acidosis, because free iron uncouples oxidative phosphorylation and drives lactate production. His transaminase rise signals the hepatotoxicity that follows, and the radiopaque tablets on the film confirm the ingestion and guide decontamination.\n\nAlongside the antidote: aggressive supportive care and, for a large ingestion with tablets visible on imaging, whole bowel irrigation. Activated charcoal does NOT bind iron and has no role.\n\nKeep the three chelators apart by route and rhythm — deferasirox once daily by mouth, deferiprone three times daily by mouth, deferoxamine parenterally by 8 to 12 hour subcutaneous infusion. Only deferoxamine is used for ACUTE toxicity; the oral agents are for the chronic overload of a lifelong transfusion programme.",
  {"0": "Deferasirox is an ORAL chelator for chronic transfusional iron overload, taken once daily. It is not used in acute poisoning — a vomiting, hypotensive child cannot reliably take or absorb an oral drug — and it carries boxed warnings for renal failure, hepatic failure and gastrointestinal hemorrhage, the last of which is already happening here.",
   "1": "Deferiprone is also oral, taken three times daily for chronic overload, and carries a boxed warning for agranulocytosis requiring weekly white cell counts. Like deferasirox it has no role in acute ingestion.",
   "3": "N-acetylcysteine is the antidote for acetaminophen poisoning, replenishing glutathione. It is a reasonable reflex in a pediatric ingestion with transaminase elevation, but the radiopaque tablets and a serum iron of 640 µg/dL identify the toxin.",
   "4": "Succimer (dimercaptosuccinic acid) is an oral chelator for LEAD poisoning, and also binds arsenic and mercury. Lead is the other classic pediatric metal exposure, but it causes a chronic microcytic anemia with basophilic stippling rather than acute shock with hematemesis."},
  "A toddler swallowed a bottle of adult iron pills, which burns the gut and poisons the body's energy machinery. The antidote is a drug that grabs the loose iron and carries it out in the urine, which turns it reddish.",
  exim="fig_slide_iron_toxicity",
  excap="Lecture slide: acute iron toxicity and chronic iron overload, and the chelator used for each.")

# ── 6. Choosing a chelator, and its boxed warning (§17) ───────────────────────
q("A 24-year-old woman with beta-thalassemia major has been transfused every 3 to 4 weeks since infancy. Her serum ferritin is 3,100 ng/mL and cardiac magnetic resonance imaging shows myocardial iron deposition. She has previously been unable to tolerate nightly subcutaneous infusions, and deferasirox was stopped last year because of a rising creatinine. She is started on deferiprone. Her temperature is 36.9°C (98.4°F), pulse is 84/min, and blood pressure is 108/66 mm Hg.\n\nLaboratory studies show:\nHemoglobin 9.4 g/dL (N=12.0–16.0 g/dL)\nHematocrit 28% (N=36%–46%)\nLeukocyte count 5,800/mm3 (N=4500–11,000/mm3)\nPlatelet count 212,000/mm3 (N=150,000–400,000/mm3)\nCreatinine 1.3 mg/dL (N=0.6–1.2 mg/dL)\nAlanine aminotransferase 46 U/L (N=10–40 U/L)\n\nWhich of the following must be monitored most closely during treatment with this agent?",
  ["A. Absolute neutrophil count",
   "B. Ocular and auditory function",
   "C. Serum calcium concentration",
   "D. Serum potassium concentration",
   "E. Thyroid-stimulating hormone concentration"],
  0,
  "Deferiprone carries a boxed warning for AGRANULOCYTOSIS and neutropenia, and the monitoring that goes with it is a weekly white cell count with an absolute neutrophil count. Patients are instructed to report any fever or sore throat immediately and to stop the drug pending a count, because agranulocytosis in a transfusion-dependent patient is life-threatening.\n\nThe three chelators are best kept apart by route, rhythm and signature problem:\n\n• deferasirox — oral, once daily. Boxed warning: renal failure, hepatic failure, gastrointestinal hemorrhage. Her creatinine rose on it, which is why it was stopped.\n• deferiprone — oral, three times daily. Boxed warning: agranulocytosis/neutropenia. Weekly counts.\n• deferoxamine — parenteral, 8 to 12 hour subcutaneous infusions. The burden is the problem, plus ocular and auditory toxicity. It is also the antidote for acute iron poisoning.\n\nConvenience improved with each generation; the boxed warnings changed shape but never went away — and this patient has now run through the tolerability of two of the three.\n\nWhy chelation cannot simply be abandoned: there is no physiologic route to excrete iron, and her cardiac magnetic resonance already shows myocardial loading. Cardiac iron is what kills these patients, and it is silent until it is not.",
  {"1": "Ocular and auditory toxicity — retinal changes and high-frequency hearing loss — belongs to DEFEROXAMINE, and patients on it have annual ophthalmologic and audiometric screening. It is the agent she could not tolerate because of the nightly infusions.",
   "2": "Calcium is not a chelator monitoring parameter. It would matter for a bisphosphonate or in parathyroid disease; the electrolyte disturbance worth knowing in this block is the hypophosphatemia caused by ferric carboxymaltose.",
   "3": "Potassium monitoring belongs to heparin (aldosterone suppression) and to vitamin B12 replacement, where a suddenly restarting marrow pulls potassium into new cells. Neither applies to deferiprone.",
   "4": "Thyroid function is genuinely worth following in a chronically transfused patient, because iron deposits in endocrine organs and causes hypothyroidism, hypogonadism and diabetes mellitus. That is a consequence of the OVERLOAD, not a monitoring requirement of the chelator — and it is not what the boxed warning is about."},
  "This chelator can wipe out the white cells that fight infection, so she needs a blood count every week and must report any fever straight away. Each of the three iron-removing drugs has its own particular danger.",
  exim="fig_slide_iron_toxicity",
  excap="Lecture slide: chronic iron overload and the chelators — route, dosing rhythm, and the boxed warning that distinguishes each.")

# ── 7. How long to continue iron (§17) ────────────────────────────────────────
q("A 29-year-old woman was found to have iron deficiency anemia from menorrhagia 10 weeks ago and began ferrous sulfate. Her menorrhagia has been treated and has resolved. She feels well, her exercise tolerance has returned to normal, and she has had no bleeding. She asks whether she may now stop the iron. Her temperature is 36.8°C (98.2°F), pulse is 72/min, and blood pressure is 112/70 mm Hg. Physical examination shows no pallor.\n\nLaboratory studies show:\nHemoglobin 12.6 g/dL (N=12.0–16.0 g/dL)\nHematocrit 38% (N=36%–46%)\nMean corpuscular volume 84 µm3 (N=80–100 µm3)\nReticulocyte count 1.2% (N=0.5%–1.5%)\nSerum ferritin 14 ng/mL (N=10–120 ng/mL)\n\nHer hemoglobin was 9.1 g/dL and her ferritin was 5 ng/mL when treatment began. Which of the following is the most appropriate advice?",
  ["A. Continue iron for another 3 to 6 months",
   "B. Repeat the hemoglobin in 1 year and restart iron only if it falls",
   "C. Stop iron now and begin a multivitamin containing 18 mg of iron",
   "D. Stop iron now, since the hemoglobin has normalized",
   "E. Switch to intravenous iron to complete repletion"],
  0,
  "Her hemoglobin has normalized, but her STORES have not. Ferritin reflects the iron reserve, and at 14 ng/mL she is barely above the floor — the body fills the circulating hemoglobin first and the storage compartment last.\n\nSo iron continues for 3 to 6 months AFTER the hemoglobin normalizes, to refill ferritin. §17 calls stopping when the hemoglobin looks pretty the classic under-treatment, and the consequence is predictable: she relapses within months, especially with any recurrence of menstrual loss.\n\nHer response has been textbook and confirms the diagnosis and the adherence: a reticulocyte bump at 7 to 10 days, then roughly 1 g/dL of hemoglobin every 2 to 3 weeks — 9.1 to 12.6 g/dL over 10 weeks is exactly that trajectory.\n\nA reasonable target is a ferritin above about 50 to 100 ng/mL before stopping, with a recheck a few months later. Worth reinforcing at the same visit: take it at least an hour before meals, avoid enteric-coated and sustained-release formulations (they release iron distal to the duodenum, past the absorption window), keep antacids separated by 2 to 4 hours, and expect black stools — which alarm patients and are not bleeding.",
  {"1": "Waiting a year and watching the hemoglobin means treating the relapse rather than preventing it, and the hemoglobin is the LAST thing to fall — by the time it drops she will have been iron deplete and symptomatic for months.",
   "3": "This is the specific error the item is built around. A normal hemoglobin with a ferritin of 14 ng/mL means the circulating compartment is full and the storage compartment is empty; stopping now guarantees recurrence.",
   "2": "A multivitamin contains roughly 18 mg of elemental iron, against about 65 mg in a single ferrous sulfate 325 mg tablet. It is a maintenance dose for a replete person, not a repletion dose for someone with a ferritin of 14 ng/mL.",
   "4": "Intravenous iron is for patients who cannot absorb or tolerate the oral route, or who are losing iron faster than they can absorb it. She has responded beautifully to oral therapy — switching adds cost and infusion-reaction risk for no benefit."},
  "Her blood count looks normal again, but the body's iron savings account is still nearly empty — it refills the blood first and the reserve last. She keeps taking iron for a few more months or the anemia simply comes back.",
  exim="fig_slide_ida_tree",
  excap="Lecture slide: the iron deficiency treatment algorithm, including how long therapy continues once the hemoglobin has recovered.")

# ── 8. Hypokalemia after starting B12 (§17) ───────────────────────────────────
q("A 68-year-old man with pernicious anemia is admitted with severe megaloblastic anemia and begins intramuscular cyanocobalamin. He has no vomiting or diarrhea, takes no diuretic, and has normal renal function. Three days after the first injection he reports generalized weakness and palpitations. His temperature is 36.9°C (98.4°F), pulse is 96/min, respirations are 16/min, and blood pressure is 124/76 mm Hg. Physical examination shows mild proximal weakness and no focal neurologic deficit.\n\nLaboratory studies on admission and on hospital day 3 show:\nHemoglobin 6.8 g/dL on admission and 7.4 g/dL on day 3 (N=13.5–17.5 g/dL)\nHematocrit 21% on admission and 22% on day 3 (N=41%–53%)\nMean corpuscular volume 118 µm3 (N=80–100 µm3)\nReticulocyte count 0.4% on admission and 7.8% on day 3 (N=0.5%–1.5%)\nPotassium 4.1 mEq/L on admission and 2.9 mEq/L on day 3 (N=3.5–5.0 mEq/L)\nUric acid 5.8 mg/dL on admission and 9.4 mg/dL on day 3 (N=3.0–8.2 mg/dL)\n\nWhich of the following best explains the fall in this patient's potassium concentration?",
  ["A. Cyanocobalamin-induced renal potassium wasting",
   "B. Gastrointestinal potassium loss from cyanocobalamin",
   "C. Potassium uptake by rapidly proliferating hematopoietic cells",
   "D. Redistribution of potassium caused by metabolic alkalosis",
   "E. Suppression of aldosterone secretion by cyanocobalamin"],
  2,
  "The two uncommon adverse effects of vitamin B12 replacement both come from the same event: a stalled marrow suddenly restarting.\n\nWhen B12 is replaced, erythropoiesis resumes explosively — his reticulocyte count went from 0.4% to 7.8% in 3 days. Building enormous numbers of new cells consumes raw material from the extracellular space:\n• POTASSIUM is pumped into the new cells → hypokalemia, which can be severe enough to cause weakness, arrhythmia, and rarely sudden death in the first days of treatment.\n• NUCLEIC ACID turnover rises as precursors proliferate → hyperuricemia, which his uric acid of 9.4 mg/dL shows.\n\nThat pairing — a brisk reticulocytosis with a falling potassium and a rising urate — is the fingerprint, and it is why potassium is monitored during the first week of treating a severe megaloblastic anemia, with replacement as needed.\n\nThe response itself is also the diagnostic confirmation: reticulocytosis within 3 to 5 days, peaking around day 7, then the hemoglobin climbing. His has already begun.\n\nThe drug: cyanocobalamin is available orally, intranasally and by injection. In pernicious anemia the defect is absent intrinsic factor, so the parenteral or intranasal route is what bypasses the broken gut — although high-dose oral B12 works in many patients through passive diffusion.",
  {"0": "Cyanocobalamin has no renal tubular effect and does not cause potassium wasting. If the kidney were the route of loss, the urinary potassium would be inappropriately high — and there would be no reason for uric acid to rise at the same time.",
   "1": "He has neither vomiting nor diarrhea, so there is no gastrointestinal route for loss, and B12 replacement does not cause either. Gastrointestinal losses would also not produce the simultaneous hyperuricemia.",
   "3": "Alkalosis does shift potassium into cells and is a genuine cause of hypokalemia — classically with vomiting or diuretics. Nothing here suggests an alkalosis, and it would not explain the reticulocytosis or the rising urate, which tie the potassium shift to the marrow.",
   "4": "Aldosterone suppression is what HEPARIN does, and it raises potassium rather than lowering it. Excess aldosterone would lower potassium, but there is no reason for cyanocobalamin to stimulate it."},
  "His bone marrow had almost stopped making red cells, and the vitamin switched it back on all at once. The billions of new cells being built suck potassium out of the blood as they form.",
  exim="fig_slide_b12_tree",
  excap="Lecture slide: the treatment algorithm for vitamin B12 deficiency anemia, including the route chosen when intrinsic factor is absent.")

# ── 9. Leucovorin rescue (§17) ────────────────────────────────────────────────
q("A 57-year-old woman receiving high-dose methotrexate for osteosarcoma is admitted 36 hours after her infusion with oral ulceration, nausea, and a rising creatinine. She has not received her scheduled rescue therapy because of a prescribing error. Her temperature is 37.4°C (99.3°F), pulse is 98/min, and blood pressure is 114/70 mm Hg. Physical examination shows extensive painful oral mucosal ulceration.\n\nLaboratory studies show:\nHemoglobin 9.6 g/dL (N=12.0–16.0 g/dL)\nHematocrit 29% (N=36%–46%)\nLeukocyte count 1,400/mm3 (N=4500–11,000/mm3)\nPlatelet count 74,000/mm3 (N=150,000–400,000/mm3)\nCreatinine 2.1 mg/dL (N=0.6–1.2 mg/dL)\nSerum methotrexate concentration 12 µmol/L at 36 hours (N=<0.1 µmol/L at 36 hours)\n\nA resident has written for high-dose oral folic acid. Which of the following best explains why that will not work, and what should be given instead?",
  ["A. Folic acid is displaced from its transporter by methotrexate; glucarpidase should be given",
   "B. Folic acid is not absorbed during mucositis; intravenous folic acid should be given",
   "C. Folic acid must be converted by the liver, which is impaired; vitamin B12 should be given",
   "D. Folic acid requires dihydrofolate reductase for activation; folinic acid should be given",
   "E. Folic acid worsens methotrexate toxicity; thymidine should be given"],
  3,
  "Methotrexate inhibits DIHYDROFOLATE REDUCTASE (DHFR) — and DHFR is precisely the enzyme required to convert folic acid into its biologically active tetrahydrofolate forms. Giving folic acid hands the cell a substrate it cannot activate, because the activating enzyme is the one the poison has blocked.\n\nFolinic acid (leucovorin) is already PAST that step. It is a reduced folate that is converted directly to the active forms without needing DHFR, so it restores the folate pool that thymidine and purine synthesis depend on — which is why the marrow and the gut mucosa, the two fastest-dividing tissues, are what fail first when the pool is empty.\n\nThat is what 'leucovorin rescue' means: you are not reversing methotrexate or displacing it from the enzyme. You are handing the cell an activated folate it can still use while the drug is cleared.\n\nThe memory hook: FoliNic is fiNished — N for 'No enzyme needed'.\n\nThe rest of her management: aggressive hydration with urinary alkalinization to keep methotrexate soluble in the tubule, avoidance of drugs that impair its excretion (NSAIDs, trimethoprim-sulfamethoxazole, proton pump inhibitors), leucovorin dosed against serial methotrexate levels, and glucarpidase — an enzyme that cleaves methotrexate directly — for severe toxicity with renal impairment, which her creatinine of 2.1 mg/dL and level of 12 µmol/L may well warrant.",
  {"1": "Absorption is not the problem, and giving the same inactive-for-her molecule intravenously changes nothing. Folic acid would still require DHFR, which is blocked, whatever route it arrives by.",
   "4": "Folic acid does not worsen methotrexate toxicity — it is simply useless here. Thymidine is a real experimental rescue that bypasses the thymidylate synthase block, but it is not standard therapy, and leucovorin is the established answer.",
   "0": "Methotrexate and reduced folates do share the reduced folate carrier, so there is competition at the transporter — but the decisive block is enzymatic, at DHFR. Glucarpidase is genuinely part of severe toxicity management, which makes this the most tempting distractor; it is paired here with the wrong explanation.",
   "2": "Folic acid activation is not a hepatic conversion step in the sense implied, and her liver is not the issue. Vitamin B12 is required for the methionine synthase reaction and matters in megaloblastic anemia, but it does nothing for a DHFR blockade."},
  "Methotrexate breaks the enzyme that turns folic acid into its usable form, so giving folic acid is like delivering a locked box with no key. Folinic acid is the already-opened version, so the cell can use it straight away.",
  exim="fig_slide_folate",
  excap="Lecture slide on prevention and treatment of folate deficiency, including the distinction between folic acid and the rescue agent folinic acid.")

# ── 10. What an erythropoiesis-stimulating agent actually does (§17) ──────────
q("A 62-year-old man with stage 4 chronic kidney disease and symptomatic anemia begins subcutaneous epoetin alfa. His iron studies were checked and repleted before treatment. Over the following 2 weeks his reticulocyte count rises before any measurable change in his hemoglobin concentration. His temperature is 36.9°C (98.4°F), pulse is 76/min, and blood pressure is 138/84 mm Hg.\n\nLaboratory studies show:\nHemoglobin 9.1 g/dL (N=13.5–17.5 g/dL)\nHematocrit 27% (N=41%–53%)\nReticulocyte count 0.6% before treatment and 3.4% at 2 weeks (N=0.5%–1.5%)\nSerum ferritin 220 ng/mL (N=20–250 ng/mL)\nTransferrin saturation 28% (N=20%–50%)\nCreatinine 3.9 mg/dL (N=0.6–1.2 mg/dL)\n\nWhich of the following best describes the mechanism of action of this drug?",
  ["A. Inhibition of hepcidin, releasing iron from macrophage stores",
   "B. Inhibition of prolyl hydroxylase, stabilizing hypoxia-inducible factor",
   "C. Promotion of late-stage erythroid maturation in the marrow",
   "D. Stimulation of division and differentiation of committed erythroid progenitors",
   "E. Stimulation of pluripotent hematopoietic stem cell self-renewal"],
  3,
  "Epoetin alfa is recombinant erythropoietin. It binds the erythropoietin receptor on COMMITTED erythroid progenitor cells, stimulating their division and differentiation, and it induces the release of reticulocytes from the marrow into the blood, where they finish maturing.\n\nThe dose–response follows that sequence exactly, and his laboratory studies show it: the reticulocyte count rises FIRST, then the hematocrit and hemoglobin. Seeing reticulocytes climb at 2 weeks while the hemoglobin has not yet moved is the expected pattern, not a treatment failure.\n\nThe class, fully specified: epoetin alfa and darbepoetin alfa share a mechanism, with darbepoetin having a longer half-life and less frequent dosing; methoxy polyethylene glycol-epoetin beta is longest-acting. All may be given intravenously or subcutaneously — and subcutaneous administration has a prolonged absorption phase, so the target hemoglobin is maintained at doses 15 to 30% LOWER than intravenous, with less blood pressure rise.\n\nApproved indications are anemia of chronic kidney disease and chemotherapy-induced anemia in cancer patients. They are started only when the anemia is symptomatic and the goal is avoiding transfusion, and only after iron stores have been checked and repleted — as they were here.\n\nOnset is delayed, so an ESA is never a substitute for emergency transfusion.",
  {"0": "Hepcidin inhibition to mobilize sequestered iron is an investigational strategy in anemia of inflammation; no approved drug in this section works that way. Erythropoietin acts on the progenitor cell, not on iron trafficking — though it consumes iron rapidly, which is why stores are repleted first.",
   "1": "Prolyl hydroxylase inhibition describes VADADUSTAT, the newer oral HIF-PHI class. It stabilizes hypoxia-inducible factor so the cell transcribes its own erythropoietin gene — convincing the cell it is at altitude. That is an indirect route to the same hormone, and a different mechanism from giving the hormone itself.",
   "2": "Promoting late-stage erythroid maturation is LUSPATERCEPT, used in beta-thalassemia and low-risk myelodysplastic syndrome. It unblocks the end of the assembly line rather than shouting louder at the start, which is why it suits ineffective erythropoiesis and an ESA does not.",
   "4": "Erythropoietin does not act on pluripotent stem cells; its receptor appears on progenitors already committed to the erythroid lineage. A drug acting at the stem cell level would raise all lineages, whereas an ESA raises red cells alone."},
  "The drug is a manufactured copy of the kidney hormone that tells the marrow to build red cells. It pushes the cells already committed to becoming red cells to divide and be released early — which is why young cells show up in the blood before the blood count itself rises.",
  exim="fig_slide_erythropoiesis",
  excap="Lecture slide: the steps of erythropoiesis and where the erythropoiesis-stimulating agents act.")

# ── 11. The ESA boxed warnings (§17) ──────────────────────────────────────────
q("A 59-year-old woman with stage 5 chronic kidney disease on hemodialysis has been receiving epoetin alfa for symptomatic anemia. Her iron stores are adequate. She feels considerably better and no longer requires transfusion. Her temperature is 36.8°C (98.2°F), pulse is 78/min, and blood pressure has risen from 128/76 mm Hg to 158/92 mm Hg over the past 2 weeks. Physical examination shows no edema and clear lungs.\n\nLaboratory studies show:\nHemoglobin 9.2 g/dL two weeks ago and 10.9 g/dL today (N=12.0–16.0 g/dL)\nHematocrit 28% two weeks ago and 33% today (N=36%–46%)\nReticulocyte count 4.2% (N=0.5%–1.5%)\nSerum ferritin 340 ng/mL (N=10–120 ng/mL)\nTransferrin saturation 32% (N=20%–50%)\n\nThe nephrology fellow proposes increasing the epoetin dose to bring her hemoglobin to 12 g/dL. Which of the following is the most appropriate response?",
  ["A. Continue the current dose and recheck in 2 weeks",
   "B. Decrease the dose, because the rate of rise exceeds 1 g/dL in 2 weeks",
   "C. Increase the dose as proposed, targeting a hemoglobin of 12 g/dL",
   "D. Stop the epoetin permanently and transfuse when symptomatic",
   "E. Switch to intravenous administration at the same dose"],
  1,
  "The proposal violates both numbers that govern this class.\n\nThe TARGET is wrong. Every one of the four boxed warnings turns on the same threshold: targeting a hemoglobin above 11 g/dL increases death, serious cardiovascular events, myocardial infarction, stroke, venous thromboembolism and vascular access thrombosis — with NO additional benefit. In chronic kidney disease specifically, the warning names death, serious cardiovascular events and stroke. The goal is the lowest dose needed to avoid transfusion, not a normal hemoglobin.\n\nThe RATE is also wrong. Her hemoglobin rose 1.7 g/dL in 2 weeks. The rule is to decrease the dose if it rises more than 1 g/dL in any 2-week period, because an excessive rate causes or worsens hypertension — the commonest adverse effect of the class, occurring in up to a third of treated patients, and her blood pressure has climbed from 128/76 to 158/92 mm Hg. Hypertensive encephalopathy has been reported, and uncontrolled hypertension is a contraindication to continuing.\n\nSo: cut the dose, control the blood pressure, confirm iron stores remain adequate, and recheck. Think of an ESA as a thermostat set to 'just warm enough not to transfuse', never to 'comfortable'.\n\nThe memory hook: Eleven is the ceiling, and 1-in-2 is the rate rule.",
  {"0": "Holding the dose steady ignores a rise of 1.7 g/dL in 2 weeks and a blood pressure that has climbed 30 mm Hg systolic. Continuing unchanged would carry her past 11 g/dL within days, into the range the boxed warnings describe.",
   "2": "This is the proposal, and it breaches the boxed warnings twice — a target above 11 g/dL, reached at an excessive rate. It is worth naming why it feels reasonable: normalizing a number seems like good care, and the trials found it increases death without improving symptoms.",
   "3": "Permanent discontinuation overcorrects. She is symptomatic, dialysis-dependent, and doing well on therapy; stopping returns her to transfusion dependence with its alloimmunization and iron-loading risks. The answer is dose reduction, not abandonment.",
   "4": "Switching to intravenous dosing moves in the wrong direction. Subcutaneous administration has a prolonged absorption phase, so the same target is maintained at doses 15 to 30% LOWER than intravenous, with less blood pressure rise — the opposite of what she needs."},
  "The drug works, but pushing the blood count up to normal has been shown to cause strokes and heart attacks without making people feel better. Her count is also climbing too fast, which is why her blood pressure has jumped — so the dose comes down.",
  exim="fig_slide_esa_ae",
  excap="Lecture slide: adverse effects of the erythropoiesis-stimulating agents, with hypertension the commonest and the boxed warnings turning on a hemoglobin above 11 g/dL.")

# ── 12. Apparent ESA resistance (§17) ─────────────────────────────────────────
q("A 71-year-old man with anemia of chronic kidney disease has received darbepoetin alfa for 8 weeks at progressively increasing doses. His hemoglobin concentration has not changed. He is adherent, has had no bleeding, and his stool is negative for occult blood on three specimens. He has no infection, no known malignancy, and normal thyroid function. His temperature is 36.9°C (98.4°F), pulse is 80/min, and blood pressure is 132/78 mm Hg.\n\nLaboratory studies show:\nHemoglobin 9.0 g/dL (N=13.5–17.5 g/dL)\nHematocrit 27% (N=41%–53%)\nMean corpuscular volume 79 µm3 (N=80–100 µm3)\nReticulocyte count 1.1% (N=0.5%–1.5%)\nSerum ferritin 68 ng/mL (N=20–250 ng/mL)\nTransferrin saturation 12% (N=20%–50%)\nC-reactive protein 0.3 mg/dL (N=<1.0 mg/dL)\nCreatinine 4.2 mg/dL (N=0.6–1.2 mg/dL)\n\nWhich of the following is the most appropriate next step in management?",
  ["A. Add a hypoxia-inducible factor prolyl hydroxylase inhibitor",
   "B. Administer intravenous iron",
   "C. Begin luspatercept",
   "D. Increase the darbepoetin dose further",
   "E. Perform bone marrow aspiration and biopsy"],
  1,
  "This is FUNCTIONAL iron deficiency, and it is the commonest reason an erythropoiesis-stimulating agent appears not to work.\n\nAn ESA drives the marrow to build red cells, and building red cells consumes iron fast — faster than a patient with chronic kidney disease can mobilize it from stores. The order is shouted, the factory has no raw material, and the hemoglobin does not move. §17 states the rule as: iron first, signal second. Check and replete iron before blaming the ESA.\n\nHis numbers show it precisely. The transferrin saturation of 12% is the giveaway — iron is not reaching the marrow — while the ferritin of 68 ng/mL looks unremarkable and is the reason this gets missed. In chronic kidney disease, ferritin is an acute-phase reactant and a value in this range does NOT exclude deficiency; a falling mean corpuscular volume (his is 79 µm3) and a low saturation do. His C-reactive protein of 0.3 mg/dL argues against inflammation as the cause of the discordance.\n\nIntravenous iron is preferred over oral in dialysis and advanced chronic kidney disease, because hepcidin is high and oral absorption is poor.\n\nOnly if the hemoglobin still fails to respond after iron repletion should other causes of resistance be pursued — occult blood loss, infection or inflammation, hyperparathyroidism, aluminium toxicity, folate or B12 deficiency, and the rare pure red cell aplasia from anti-erythropoietin antibodies.",
  {"0": "An HIF prolyl hydroxylase inhibitor raises endogenous erythropoietin production — it is another way of shouting the same order, so it fails for the same reason while adding a boxed warning for thrombosis. It is an alternative to an ESA in dialysis patients, not a solution to iron starvation.",
   "2": "Luspatercept is an erythroid maturation agent for beta-thalassemia and low-risk myelodysplastic syndrome, where the problem is ineffective erythropoiesis. His marrow is not jammed at the end of the line; it is short of raw material.",
   "3": "Escalating the dose is what has already been tried for 8 weeks without effect, and it is the trap. Higher doses without iron produce no hemoglobin response while increasing the cardiovascular and thrombotic risks the boxed warnings describe.",
   "4": "A marrow examination is reasonable for unexplained ESA resistance AFTER iron has been repleted and the common causes excluded — it would look for myelodysplasia, infiltration, or pure red cell aplasia. It is invasive and premature when a transferrin saturation of 12% offers a straightforward explanation."},
  "The drug is ordering the marrow to build red cells, but the marrow has run out of iron to build them from. Shouting the order louder does nothing — you have to deliver the raw material first.",
  exim="fig_slide_esa_initiate",
  excap="Lecture slide: when to initiate an erythropoiesis-stimulating agent — including the requirement that iron stores be checked and repleted first.")

# ── 13. Fake altitude in a pill (§17) ─────────────────────────────────────────
q("A 66-year-old woman with anemia of chronic kidney disease who has been on hemodialysis for 2 years is switched from an injected erythropoiesis-stimulating agent to oral vadadustat, because she dislikes injections. She has no history of malignancy, has had no acute coronary syndrome or stroke, and her blood pressure is well controlled on three agents. Her temperature is 36.8°C (98.2°F), pulse is 74/min, and blood pressure is 128/76 mm Hg.\n\nLaboratory studies show:\nHemoglobin 9.6 g/dL (N=12.0–16.0 g/dL)\nHematocrit 29% (N=36%–46%)\nSerum ferritin 280 ng/mL (N=10–120 ng/mL)\nTransferrin saturation 30% (N=20%–50%)\nCreatinine 6.8 mg/dL (N=0.6–1.2 mg/dL)\n\nWhich of the following best describes how this drug increases erythropoiesis?",
  ["A. It binds the erythropoietin receptor directly on erythroid progenitors",
   "B. It inhibits hepcidin, increasing iron availability to the marrow",
   "C. It inhibits prolyl hydroxylases, stabilizing hypoxia-inducible factor",
   "D. It inhibits transforming growth factor beta signalling in late erythroblasts",
   "E. It stimulates renal interstitial fibroblasts to secrete stored erythropoietin"],
  2,
  "Vadadustat is a hypoxia-inducible factor prolyl hydroxylase inhibitor (HIF-PHI), and the mechanism is elegant: it convinces the cell it is at altitude.\n\nHypoxia-inducible factor is the master regulator of the erythropoietin gene. When oxygen is plentiful, prolyl hydroxylase enzymes tag HIF for destruction, so it never accumulates and the gene stays quiet. Inhibit those hydroxylases and intracellular HIF is stabilized → the oxygen-sensing pathway switches on → the cell transcribes erythropoietin and a set of iron-handling genes → erythropoiesis is stimulated.\n\nIt raises the patient's OWN erythropoietin rather than supplying a manufactured hormone, and it is oral — which is the entire selling point against injected ESAs, and the reason this patient was switched. It is approved for anemia of chronic kidney disease in adults on dialysis for at least 3 months. (Daprodustat was withdrawn from the US market in late 2024 for commercial rather than safety reasons.)\n\nThe safety profile follows directly from the memory hook — fake altitude in a pill gives you everything a body at altitude with thicker blood gets: a boxed warning for increased THROMBOTIC events, contraindication in uncontrolled hypertension and in acute coronary syndrome or cerebrovascular events within 3 months, and caution in malignancy, since the pathway can stimulate tumour growth.\n\nShe was screened against all of those, which is why she is a candidate.",
  {"0": "Binding the erythropoietin receptor directly is what epoetin alfa and darbepoetin alfa do — they ARE erythropoietin. Vadadustat contains no hormone; it makes the patient produce their own, which is the distinction between the two classes.",
   "1": "Hepcidin suppression is a downstream consequence of HIF stabilization and contributes to the drug's effect on iron availability, so the statement is not wholly wrong — but it is not the primary mechanism, and no approved drug works by hepcidin inhibition alone.",
   "3": "Inhibiting transforming growth factor beta superfamily signalling in late erythroblasts is LUSPATERCEPT, an erythroid maturation agent for beta-thalassemia and low-risk myelodysplastic syndrome. It unjams the end of the assembly line rather than increasing the build order.",
   "4": "Erythropoietin is not stored and released on demand; it is synthesized on transcription by renal interstitial fibroblasts in response to hypoxia. The drug acts by preventing the degradation of the transcription factor that drives that synthesis — a genuine mechanistic difference, not a semantic one."},
  "The body senses low oxygen and responds by making the hormone that builds red cells. This pill blocks the enzyme that normally destroys that oxygen sensor, so the kidney behaves as though she were up a mountain and makes its own hormone.",
  exim="fig_slide_vadadustat",
  excap="Lecture slide on vadadustat — the oral HIF prolyl hydroxylase inhibitor, its class, and its boxed warning for thrombotic events.")

# ── 14. Matching the drug to the mechanism in thalassemia (§17) ───────────────
q("A 27-year-old woman with transfusion-dependent beta-thalassemia requires packed red blood cells every 3 weeks despite chelation therapy and folic acid. Her marrow biopsy specimen shows marked erythroid hyperplasia with extensive intramedullary destruction of erythroid precursors. Her serum erythropoietin concentration is markedly elevated. Her temperature is 36.9°C (98.4°F), pulse is 88/min, and blood pressure is 112/68 mm Hg. Physical examination shows scleral icterus and a spleen palpated 5 cm below the left costal margin.\n\nLaboratory studies show:\nHemoglobin 8.2 g/dL (N=12.0–16.0 g/dL)\nHematocrit 25% (N=36%–46%)\nMean corpuscular volume 66 µm3 (N=80–100 µm3)\nReticulocyte count 3.8% (N=0.5%–1.5%)\nSerum ferritin 1,860 ng/mL (N=10–120 ng/mL)\nErythropoietin 320 mIU/mL (N=4–26 mIU/mL)\n\nWhich of the following agents is most appropriate to reduce her transfusion requirement, and why?",
  ["A. Darbepoetin alfa, because it has a longer half-life than epoetin alfa",
   "B. Epoetin alfa, because her marrow requires a stronger erythropoietic signal",
   "C. Filgrastim, because it shortens the duration of cytopenia",
   "D. Luspatercept, because it promotes maturation of late-stage erythroid precursors",
   "E. Vadadustat, because it raises endogenous erythropoietin production"],
  3,
  "Thalassemia's problem is INEFFECTIVE erythropoiesis, not an absent signal — and matching the drug to the mechanism is the whole item.\n\nHer marrow has no shortage of precursors; it is hyperplastic, and they are dying before release because unpaired globin chains precipitate and destroy them. Her erythropoietin is already 320 mIU/mL — more than ten times normal — so the build order is being shouted at maximum volume. Amplifying it further with an erythropoiesis-stimulating agent, or raising endogenous erythropoietin with a HIF-PHI, only shouts louder at an assembly line already jammed at the end.\n\nLuspatercept is an erythroid MATURATION agent. It acts on the transforming growth factor beta superfamily pathway to let late-stage erythroid cells complete development — unblocking the actual bottleneck. It is approved for transfusion-dependent beta-thalassemia and for low-risk myelodysplastic syndrome, and it reduces transfusion burden in exactly this population.\n\nThe general principle worth carrying out of §17: every drug here answers one question — which ingredient is missing? Iron, B12, folate, the erythropoietin signal, or, in this case, none of those. The missing element is the final step of maturation.\n\nThe other newer option in thalassemia is mitapivat, an oral pyruvate kinase activator that raises cellular energy and prolongs red cell survival.",
  {"0": "Darbepoetin's longer half-life is a genuine advantage over epoetin — it is dosed less often — but that is a pharmacokinetic convenience, not a reason to choose the class. An erythropoiesis-stimulating agent addresses a signal deficit she does not have.",
   "1": "This is the trap the item is built around. Her erythropoietin is already ten times normal and her marrow is hyperplastic, so the signal is not what is missing; an ESA would add thrombotic and hypertensive risk without reducing transfusion need.",
   "2": "Filgrastim is a granulocyte colony-stimulating factor that shortens neutropenia after chemotherapy, with bone pain as its expected side effect. It acts on the myeloid line and has no effect on erythroid maturation or transfusion requirement.",
   "4": "Vadadustat stabilizes hypoxia-inducible factor to raise the patient's own erythropoietin — the same futility as an ESA in a patient whose erythropoietin is already 320 mIU/mL. It is also approved specifically for anemia of chronic kidney disease on dialysis, which she does not have."},
  "Her marrow is packed with young red cells that die before they can finish growing up, and her body is already screaming at it to make more. She needs the drug that helps those cells finish maturing, not one that shouts the order louder.",
  exim="fig_slide_erythropoiesis",
  excap="Lecture slide: the steps of erythropoiesis. An erythropoiesis-stimulating agent acts near the start of the sequence; luspatercept acts at the final maturation step.")

# ── 15. Complement inhibitors and the vaccine (§17) ───────────────────────────
q("A 31-year-old man has paroxysmal nocturnal hemoglobinuria with recurrent dark urine, profound fatigue, and a portal vein thrombosis 6 months ago. Flow cytometry shows an absence of CD55 and CD59 on 78% of his erythrocytes and granulocytes. Treatment with eculizumab is planned. His temperature is 36.9°C (98.4°F), pulse is 88/min, and blood pressure is 118/72 mm Hg.\n\nLaboratory studies show:\nHemoglobin 8.4 g/dL (N=13.5–17.5 g/dL)\nHematocrit 25% (N=41%–53%)\nReticulocyte count 8.6% (N=0.5%–1.5%)\nLactate dehydrogenase 1,420 U/L (N=45–200 U/L)\nHaptoglobin <10 mg/dL (N=30–200 mg/dL)\nTotal bilirubin 2.8 mg/dL (N=0.1–1.0 mg/dL)\n\nWhich of the following is most important to complete before beginning this treatment?",
  ["A. Bone marrow transplantation workup",
   "B. Iron loading to anticipate increased erythropoiesis",
   "C. Meningococcal vaccination",
   "D. Splenectomy to reduce extravascular hemolysis",
   "E. Testing for glucose-6-phosphate dehydrogenase deficiency"],
  2,
  "Eculizumab binds complement C5 and prevents formation of the membrane attack complex. That is exactly the defence the body uses against ENCAPSULATED organisms, and Neisseria meningitidis above all — patients with terminal complement deficiency have a dramatically increased risk of meningococcal disease.\n\nSo every complement inhibitor carries a boxed warning for serious, life-threatening meningococcal infection, and patients must be vaccinated against Neisseria meningitidis before starting, covering both the quadrivalent serogroups and serogroup B. Where treatment cannot wait for vaccine-induced immunity, antibiotic prophylaxis is given in the interim, and patients carry a card so that any fever is treated as meningococcal disease until proved otherwise.\n\nThe parallel with asplenia is worth holding: same organisms, different missing defence — one has lost the filter, the other has lost the complement that opsonizes and lyses.\n\nThe disease behind it: paroxysmal nocturnal hemoglobinuria is a deficiency of the GPI-anchored complement regulators CD55 and CD59, leaving red cells defenceless against complement. It produces intravascular hemolysis — his lactate dehydrogenase is 1,420 U/L with an undetectable haptoglobin — and a highly prothrombotic state, and it is THROMBOSIS, not anemia, that kills these patients. His portal vein thrombosis is the dangerous feature.\n\nThe class: eculizumab and ravulizumab (C5), pegcetacoplan (C3), and iptacopan, the first oral agent, inhibiting complement factor B. The memory hook: C3 catches more than C5 — blocking higher in the cascade stops both the intravascular hemolysis and the extravascular clearance of C3b-coated cells.",
  {"0": "Allogeneic transplantation is the only curative option for paroxysmal nocturnal hemoglobinuria and is considered in selected patients, particularly with marrow failure. It is not a prerequisite for starting a complement inhibitor, and its risks are far higher than those of the drug.",
   "1": "Iron loading would be actively wrong. These patients lose iron continuously in the urine as hemoglobin and hemosiderin, so they are often iron DEFICIENT and may need replacement — but that is treatment of a deficiency, not preparation for the drug.",
   "3": "Splenectomy has no established role in paroxysmal nocturnal hemoglobinuria, whose hemolysis is predominantly intravascular and complement-mediated. It would also add asplenia to a patient about to lose terminal complement — compounding precisely the infection risk that matters here.",
   "4": "G6PD deficiency is another cause of episodic hemolysis with dark urine, so the thought is reasonable — but the diagnosis here is already established by flow cytometry showing absent CD55 and CD59. Knowing his G6PD status would not change the vaccination requirement."},
  "The drug works by switching off part of the immune system's complement cascade — which happens to be the exact defence against meningitis bacteria. He must be vaccinated first, or a routine infection could kill him.",
  exim="fig_slide_esa_ae",
  excap="Every drug in this section is chosen by matching it to the missing ingredient; for paroxysmal nocturnal hemoglobinuria the missing element is complement regulation, and blocking complement creates its own vulnerability.")
