# CV Pharm Basic Sciences Review (Scully) — Version 2, 18 items (2 with images)
Q = [
dict(img=None,
stem="A 60-year-old man with hypertension is treated with clonidine. His blood pressure and heart rate fall.{FIG}Which of the following best describes the receptor and signaling mechanism responsible?",
choices=["α1 receptor antagonism in vascular smooth muscle","Central α2 receptor agonism acting through Gi","β1 receptor antagonism coupled to Gs in the heart","M2 receptor agonism coupled to Gi in the SA node","Ganglionic nicotinic receptor blockade"], key=1,
exp="<b>Clonidine</b> (and α-methyldopa, through its metabolite) is a <b>central α2 agonist</b>. α2 receptors sit <b>presynaptically</b> and in the <b>CNS</b> and couple to <b>Gi</b>. The α subunit inhibits adenylyl cyclase, and the <b>βγ subunit blocks presynaptic Ca²⁺ influx</b> → fewer vesicles released → <b>↓ sympathetic outflow</b> → ↓ SVR and ↓ heart rate. It is the same presynaptic brake that μ-opioid and GABA-B receptors use.<br><br><b>Educational objective:</b> Clonidine is an α2 (Gi) agonist that reduces sympathetic outflow by inhibiting presynaptic transmitter release, the same brake norepinephrine uses for negative feedback.",
wrong={0:"α1 antagonism is <b>prazosin</b>, which lowers SVR but not heart rate (it can even cause reflex tachycardia).",
2:"β1 antagonism is the β-blocker mechanism, not clonidine's.",
3:"M2 agonism would slow the heart but doesn't explain the fall in SVR. Clonidine isn't a muscarinic agonist.",
4:"Ganglionic blockers are rarely used and aren't clonidine's mechanism."},
eli5="Clonidine presses the brake pedal that nerves use to limit their own signals. With less 'fight or flight' signal leaving the brain and nerve endings, blood vessels relax and the heart slows."),

dict(img=None,
stem="A patient who ingested a large dose of an antimuscarinic drug has hot, flushed, completely dry skin. A student is surprised because the sweat glands are innervated by the sympathetic nervous system.{FIG}Which of the following best explains the dry skin?",
choices=["Sweat glands are activated by α1 receptors","Sweat glands are activated by β2 receptors","Sweat glands use acetylcholine on muscarinic receptors","Sweat glands use norepinephrine on nicotinic receptors","Sweat glands are innervated only by the parasympathetic system"], key=2,
exp="Sweat glands are the classic exception raised in class. Their innervation is <b>sympathetic</b>, but the postganglionic fibers release <b>acetylcholine onto muscarinic receptors</b> (sympathetic cholinergic fibers). So an <b>antimuscarinic</b> (atropine, and many anticholinergic drugs) blocks sweating → hot, dry, flushed skin. Dr. Scully's reminder: \"<b>muscarinic = cholinergic</b>.\" Anything muscarinic is produced by cholinomimetics and blocked by antimuscarinics.<br><br><b>Educational objective:</b> Eccrine sweat glands receive sympathetic cholinergic fibers acting on muscarinic receptors, so antimuscarinics cause dry skin.",
wrong={0:"α1 receptors mediate vasoconstriction (and localized apocrine sweating), but not the thermoregulatory sweating that antimuscarinics block.",
1:"β2 receptors mediate bronchodilation and muscle vasodilation, not eccrine sweating.",
3:"Nicotinic receptors respond to ACh, not norepinephrine, and they're found in ganglia rather than sweat glands.",
4:"Sweat glands have <b>no</b> parasympathetic innervation."},
eli5="Sweat glands get their nerve supply from the 'fight or flight' side, but those particular nerves use acetylcholine as their messenger. An anticholinergic drug blocks acetylcholine, so the sweat glands shut off and the skin gets hot and dry."),

dict(img=None,
stem="A 55-year-old man is started on metoprolol for hypertension. Two weeks later his plasma renin activity and aldosterone concentration are both lower than before treatment.{FIG}Which of the following best explains these laboratory changes?",
choices=["Blockade of juxtaglomerular β1 receptors","Blockade of β2 receptors in the adrenal cortex","Direct inhibition of aldosterone synthase","Inhibition of angiotensin-converting enzyme","Stimulation of atrial natriuretic peptide release"], key=0,
exp="β1 receptors are on the heart <b>and on the juxtaglomerular (JG) cells</b>. Sympathetic β1 (Gs) stimulation → <b>renin release</b>. A β1 blocker such as metoprolol → <b>↓ renin</b> → ↓ angiotensin II → <b>↓ aldosterone</b>. That's one reason β-blockers lower BP beyond slowing the heart, and why they add to the potassium-raising effect of RAAS blockers.<br><br><b>Educational objective:</b> β-blockers lower renin, and therefore aldosterone, by blocking β1 receptors on juxtaglomerular cells.",
wrong={1:"Aldosterone secretion is driven by angiotensin II and potassium, not by adrenal β2 receptors.",
2:"Metoprolol doesn't inhibit aldosterone synthase directly. Aldosterone falls downstream of renin.",
3:"ACE inhibition is the lisinopril mechanism. Metoprolol acts upstream at renin release.",
4:"ANP is released by atrial stretch. β-blockade isn't how it rises."},
eli5="The kidney cells that release renin are switched on by β1 signals. Metoprolol blocks β1, so less renin is released, and that means less aldosterone downstream too."),

dict(img=None,
stem="A pharmacology student is organizing autonomic receptors by their G-protein coupling using the rule \"odd = Gq, even = Gi, betas are BS.\"{FIG}Which of the following receptors is coupled to Gi?",
choices=["α1-adrenergic","α2-adrenergic","β1-adrenergic","β2-adrenergic","M3 muscarinic"], key=1,
exp="Dr. Scully's rule for muscarinic and α receptors: <b>odd = Gq</b> (M1, M3, α1) and <b>even = Gi</b> (M2, <b>α2</b>). \"<b>Betas are BS</b>\": every β (β1, β2, β3) → <b>Gs</b>, breaking the pattern. Gq → PLC → IP3 and DAG → Ca²⁺ (contraction). Gi → ↓ adenylyl cyclase, and βγ blocks presynaptic Ca²⁺ (slower heart, less transmitter release). Gs → ↑ adenylyl cyclase → cAMP → PKA.<br><br><b>Educational objective:</b> α2 and M2 are Gi-coupled, α1, M1 and M3 are Gq-coupled, and all β receptors are Gs-coupled.",
wrong={0:"α1 is odd → <b>Gq</b> (vasoconstriction).",
2:"All β receptors → <b>Gs</b>.",
3:"All β receptors → <b>Gs</b>.",
4:"M3 is odd → <b>Gq</b> (smooth muscle contraction, glands)."},
eli5="A memory trick: odd-numbered alpha and muscarinic receptors use Gq, even-numbered ones use Gi, and every beta receptor uses Gs. So α2, being even, uses Gi."),

dict(img=None,
stem="A patient on a continuous dobutamine infusion (a β1 agonist) has a heart rate of 110/min. A sudden strong vagal stimulus (a Valsalva maneuver) then slows the rate transiently.{FIG}At the level of the SA node cell, the two inputs integrate most directly through which of the following?",
choices=["Opposing actions on adenylyl cyclase activity","Competing effects on phospholipase C and IP3","Competing effects on soluble guanylyl cyclase","Opposing effects on Na⁺/K⁺-ATPase activity","Opposing effects on Na⁺ channels"], key=0,
exp="In the heart, <b>β1 (Gs)</b> and <b>M2 (Gi)</b> pull on the <b>same enzyme, adenylyl cyclase</b>. Gs → ↑ cAMP → PKA phosphorylates Ca²⁺-handling proteins (L-type channel, phospholamban) → faster, stronger beats. Gi inhibits adenylyl cyclase → less cAMP → slower rate and slower AV conduction. The net heart rate reflects the <b>integrated cAMP signal</b>.<br><br><b>Educational objective:</b> Sympathetic β1 (Gs) and vagal M2 (Gi) inputs converge on adenylyl cyclase, so heart rate reflects the net cAMP level.",
wrong={1:"PLC and IP3 are the Gq pathway (α1, M3), not how β1 and M2 interact.",
2:"Soluble guanylyl cyclase is the nitric oxide → cGMP pathway.",
3:"Na⁺/K⁺-ATPase is digoxin's target, not the β1 versus M2 integration point.",
4:"Fast Na⁺ channels drive the myocyte upstroke and aren't the nodal integration point."},
eli5="The 'speed up' signal and the 'slow down' signal both act on the same enzyme that makes cAMP. One pushes it up and the other pushes it down. Whichever wins sets the heart rate."),

dict(img=None,
stem="An isolated cardiac myocyte is exposed to a β1 agonist. Contraction becomes stronger, and relaxation becomes faster.{FIG}Phosphorylation of which of the following proteins by protein kinase A best explains the faster relaxation?",
choices=["Myosin light-chain kinase","Na⁺/K⁺-ATPase","Phospholamban","Ryanodine receptor","Troponin C"], key=2,
exp="β1 → Gs → ↑ cAMP → <b>PKA</b> phosphorylates Ca²⁺-handling proteins:<br>• <b>L-type Ca²⁺ channels</b> → more Ca²⁺ entry → stronger contraction (inotropy).<br>• <b>Phospholamban</b>: PKA phosphorylation <b>relieves its inhibition of SERCA</b> → faster Ca²⁺ reuptake into the sarcoplasmic reticulum → <b>faster relaxation</b> (lusitropy), plus more Ca²⁺ stored for the next beat.<br>PDE3 inhibitors (milrinone, inamrinone) reach the same endpoint by stopping cAMP breakdown.<br><br><b>Educational objective:</b> β1 → cAMP → PKA phosphorylates phospholamban, disinhibiting SERCA and speeding relaxation. It also phosphorylates L-type channels, increasing contractility.",
wrong={0:"MLCK drives <b>smooth</b> muscle contraction. Cardiac muscle is regulated through troponin.",
1:"Na⁺/K⁺-ATPase is inhibited by digoxin. It isn't the PKA target behind lusitropy.",
3:"Ryanodine receptor phosphorylation enhances Ca²⁺ <b>release</b> (contraction), not relaxation.",
4:"Troponin C binds Ca²⁺ to trigger contraction. PKA phosphorylates troponin <b>I</b>, not C."},
eli5="Adrenaline-like signals tell the heart cell to pump calcium back into storage faster, by switching off a brake protein called phospholamban. Calcium clears quickly, so the muscle relaxes faster between beats."),

dict(img=None,
stem="A patient with cardiogenic shock is receiving dobutamine. Inamrinone is added, and his heart rate and contractility rise sharply, overshooting the target.{FIG}Both drugs increase heart rate and contractility by which of the following shared mechanisms?",
choices=["Activating Gs-coupled receptors","Increasing intracellular cAMP","Inhibiting Na⁺/K⁺-ATPase","Inhibiting voltage-gated Na⁺ channels","Stimulating α1 receptors"], key=1,
exp="Class question 4. <b>Dobutamine</b> is a <b>β1 agonist</b> → Gs → adenylyl cyclase → <b>↑ cAMP</b>. <b>Inamrinone</b> (amrinone) and milrinone <b>inhibit PDE3</b> → cAMP isn't broken down → <b>↑ cAMP</b>. Inamrinone does <b>not</b> activate a Gs receptor. Their <b>common ground is more cAMP</b> → PKA → inotropy and chronotropy, and together they overshoot easily. It's the same pharmacodynamic shape as nitrates plus sildenafil (make cGMP, then block its breakdown).<br><br><b>Educational objective:</b> Dobutamine (β1 agonist) and inamrinone or milrinone (PDE3 inhibitors) both raise intracellular cAMP, one by making it and the other by preventing its breakdown.",
wrong={0:"Only dobutamine activates a Gs-coupled receptor. Inamrinone acts downstream on PDE3.",
2:"Na⁺/K⁺-ATPase inhibition is <b>digoxin</b>.",
3:"Na⁺ channel blockade is class I antiarrhythmic action, which slows conduction.",
4:"Neither drug's inotropy comes from α1 stimulation."},
eli5="Dobutamine turns on the machine that makes cAMP, and inamrinone blocks the enzyme that destroys cAMP. Either way cAMP rises, which revs up the heart. Together they can rev it too much."),

dict(img=None,
stem="A patient receives an M2 muscarinic antagonist and then a continuous intravenous infusion of norepinephrine.{FIG}Which of the following sets of changes in heart rate and blood pressure is most likely?",
choices=["Heart rate decreased · blood pressure decreased","Heart rate decreased · blood pressure increased","Heart rate increased · blood pressure decreased","Heart rate increased · blood pressure increased","Heart rate unchanged · blood pressure unchanged"], key=3,
exp="Class question 3. Norepinephrine activates <b>α1</b> (vasoconstriction), <b>α2</b>, and <b>β1</b> (tachycardia), but <b>not β2</b>.<br>• <b>NE alone</b>: unopposed α1 → ↑↑ SVR → ↑ BP → baroreflex → vagal M2 → <b>heart rate falls</b>. The reflex overrides the direct β1 effect: BP ↑, HR ↓.<br>• <b>After an M2 antagonist</b>: the reflex bradycardia is blocked, so the <b>direct β1 tachycardia shows</b> → <b>HR ↑ and BP ↑</b>.<br><br><b>Educational objective:</b> Norepinephrine alone raises BP and slows heart rate by reflex. After an M2 antagonist blocks that reflex, both heart rate and BP rise.",
wrong={0:"Norepinephrine raises BP through α1, so pressure can't fall.",
1:"BP up with HR down is what norepinephrine does <b>alone</b>. The M2 antagonist removes the reflex.",
2:"Norepinephrine doesn't lower BP. It has no β2 vasodilation.",
4:"Norepinephrine clearly raises BP, so \"unchanged\" is wrong."},
eli5="Norepinephrine squeezes vessels and would speed the heart. Normally the vagus nerve slams the brakes because pressure rose, so the heart slows. Block the vagus with the M2 antagonist and there's no brake, so pressure and heart rate both go up."),

dict(img=None,
stem="A medical student asks why norepinephrine is never used as a bronchodilator, even though epinephrine can be used in severe bronchospasm.{FIG}Which of the following best explains this difference?",
choices=["Norepinephrine activates β2 receptors only weakly","Norepinephrine does not cross cell membranes","Norepinephrine is cleaved by cholinesterase","Norepinephrine only stimulates M3 receptors","Norepinephrine selectively blocks β2 receptors"], key=0,
exp="Norepinephrine's receptor profile (lecture table): <b>α1 yes</b> (vasoconstriction), <b>α2 yes</b> (presynaptic feedback), <b>β1 yes</b> (direct tachycardia), <b>β2 no</b> (or very weak). Without β2 activity it gives <b>no bronchodilation</b> and no skeletal-muscle vasodilation to oppose α1. As Dr. Scully put it, \"you can't nebulize NE for asthma.\" Epinephrine activates β2 strongly, so it bronchodilates.<br><br><b>Educational objective:</b> Norepinephrine acts on α1, α2 and β1 but has little β2 activity, so it doesn't bronchodilate. Epinephrine does, through β2.",
wrong={1:"Norepinephrine acts on <b>surface</b> GPCRs, so crossing membranes isn't the issue.",
2:"Acetylcholinesterase breaks down <b>acetylcholine</b>. NE is cleared by reuptake, MAO and COMT.",
3:"Norepinephrine is an adrenergic agonist. It doesn't act on muscarinic receptors.",
4:"Norepinephrine isn't a β2 antagonist. It simply has little β2 agonist activity."},
eli5="To open the airways a drug has to hit β2 receptors. Epinephrine hits them hard, but norepinephrine barely touches them. That's why norepinephrine can't treat an asthma attack."),

dict(img=None,
stem="In an adrenergic synapse, the concentration of norepinephrine in the synaptic cleft is increased experimentally.{FIG}Which of the following is the most likely direct consequence?",
choices=["Activation of dopa decarboxylase","Activation of presynaptic α2 receptors","Increased norepinephrine release per impulse","Increased postsynaptic M2 receptor activity","Stimulation of monoamine oxidase activity"], key=1,
exp="Class question 2. Excess NE in the cleft binds <b>presynaptic α2 autoreceptors</b>, which are <b>Gi</b>-coupled. The βγ subunit blocks voltage-gated Ca²⁺ influx → fewer vesicles fuse → <b>less NE released</b>. This is <b>negative feedback</b>, and clonidine and methyldopa exploit it to lower BP. High NE does <b>not</b> stimulate MAO, does <b>not</b> increase its own release, and has nothing to do with dopa decarboxylase.<br><br><b>Educational objective:</b> Increased synaptic norepinephrine activates presynaptic α2 (Gi) autoreceptors, providing negative feedback on further release.",
wrong={0:"Dopa decarboxylase makes dopamine in the synthesis pathway, and NE levels don't activate it.",
2:"NE <b>reduces</b> its own release through α2 feedback.",
3:"M2 receptors respond to acetylcholine, not NE.",
4:"MAO degrades NE that is taken back up, but high NE doesn't stimulate MAO."},
eli5="When too much norepinephrine builds up, some of it lands on sensors on the nerve that released it. Those sensors (α2) act like a thermostat and tell the nerve to release less."),

dict(img=None,
stem="A 70-year-old man with angina is given a drug whose dominant action is dilation of large veins, with relatively little effect on arterioles at low doses.{FIG}Which determinant of cardiac work is most directly reduced?",
choices=["Afterload through lower arteriolar resistance","Contractility through β1 blockade","Heart rate through M2 stimulation","Preload through increased venous capacitance","Stroke volume through increased contractility"], key=3,
exp="The circulation has a <b>resistance side</b> (arterioles, which set afterload and SVR) and a <b>capacitance side</b> (veins, which set preload). A low-dose <b>venodilator</b> (nitroglycerin: NO → cGMP) increases venous capacitance → blood pools in the veins → less venous return → <b>↓ preload</b> (ventricular filling) → less wall stress and oxygen demand, which relieves angina. The lecture's BP dials table: <b>preload is lowered by NO (nitrates, nitroprusside)</b> through venous tone, or by diuretics and RAAS blockade through volume.<br><br><b>Educational objective:</b> Venodilators such as nitrates lower preload by increasing venous capacitance, reducing ventricular filling and myocardial oxygen demand.",
wrong={0:"Arteriolar dilation lowers afterload, but this drug acts mainly on the veins at low doses.",
1:"β1 blockade (β-blockers) reduces contractility. A venodilator doesn't.",
2:"M2 stimulation slows the heart. This drug has no muscarinic effect.",
4:"Venodilators don't raise contractility. Lower preload actually lowers stroke volume by the Frank–Starling relationship."},
eli5="Relaxing the big veins lets blood pool in them like a bigger reservoir. Less blood returns to the heart, so it fills less and doesn't have to work as hard. That eases angina."),

dict(img=None,
stem="A 64-year-old woman with heart failure is started on a drug that reduces the formation of angiotensin II.{FIG}Reduced angiotensin II activity at which of the following sites most directly lowers her intravascular volume?",
choices=["Adrenal cortex, reducing aldosterone","Carotid sinus, increasing baroreceptor firing","Efferent arteriole, reducing its constriction","Hypothalamus, increasing ADH release","Heart, increasing contractility"], key=0,
exp="Angiotensin II acts on the <b>adrenal cortex</b> (aldosterone), proximal tubule (NaCl reabsorption), efferent arterioles (constriction), hypothalamus (thirst, ADH) and heart (remodelling). Less angiotensin II → <b>less aldosterone</b> → less Na⁺ reabsorption in the collecting duct (fewer ENaC channels) → <b>natriuresis → lower intravascular volume</b> (and preload). The kidney's sodium handling is the long-term volume regulator. Less angiotensin II also means less thirst and ADH, and less proximal NaCl reabsorption.<br><br><b>Educational objective:</b> Reducing angiotensin II lowers intravascular volume mainly by decreasing aldosterone-driven sodium reabsorption.",
wrong={1:"Baroreceptor firing isn't angiotensin II's volume effect.",
2:"Relaxing the efferent arteriole lowers <b>glomerular pressure</b>, protecting the kidney. It doesn't directly remove volume.",
3:"Less angiotensin II means <b>less</b> ADH and thirst, not more.",
4:"Angiotensin II drives cardiac <b>remodelling</b>. Blocking it doesn't raise contractility."},
eli5="Angiotensin II tells the adrenal gland to release aldosterone, the hormone that makes the kidney hold onto salt and water. Block angiotensin II and there's less aldosterone, so the kidney lets go of salt and water and blood volume drops."),

dict(img=None,
stem="A patient receives a drug that selectively blocks the delayed-rectifier K⁺ channels in ventricular myocytes. The upstroke velocity of the action potential is unchanged.{FIG}Which of the following ECG changes is most likely?",
choices=["Prolonged PR interval","Prolonged QT interval","Shortened QT interval","Tall peaked T waves","Widened QRS complex"], key=1,
exp="In both myocytes and nodal cells, <b>repolarization (phase 3) is carried by K⁺</b>. Blocking delayed-rectifier K⁺ channels → phase 3 is slowed → a longer action potential → a <b>prolonged QT interval</b> on the ECG. This is the class III antiarrhythmic mechanism (dofetilide, sotalol, amiodarone), and it carries a torsades risk. The upstroke is unchanged because the <b>myocyte upstroke is Na⁺</b>, so the QRS is unaffected, and the <b>nodal upstroke is Ca²⁺</b>, so the PR is unaffected.<br><br><b>Educational objective:</b> K⁺ channel blockade slows phase 3 repolarization, prolonging the action potential and the QT interval.",
wrong={0:"A longer PR comes from slowed <b>nodal</b> conduction (Ca²⁺ channel blockade, β-blockade, vagal tone).",
2:"A shorter QT would need <b>faster</b> repolarization (such as K⁺ channel gain of function), which is the opposite.",
3:"Peaked T waves are the sign of <b>hyperkalemia</b>.",
4:"A wide QRS reflects a slowed <b>Na⁺-dependent</b> upstroke or conduction. The upstroke here is unchanged."},
eli5="Potassium channels let heart cells reset after each beat. Block them and the reset takes longer. On the ECG that shows up as a longer QT interval."),

dict(img='Uiso', cap='Cardiac contractility (left) and systemic vascular resistance (right) during a 5-minute drug infusion',
stem="A healthy volunteer receives an intravenous infusion of an adrenergic drug. The graphs show cardiac contractility and systemic vascular resistance over 5 minutes.{FIG}Which of the following drugs was most likely infused?",
choices=["Atropine","Isoproterenol","Norepinephrine","Phenylephrine","Propranolol"], key=1,
exp="Contractility <b>rises</b> (a β1 effect), and vascular resistance <b>falls</b> (β2 vasodilation in skeletal-muscle beds, with no α1 constriction). That fits a <b>non-selective β agonist</b>, <b>isoproterenol</b> (β1 = β2, no α). Expected accompaniments: diastolic BP falls, and heart rate rises from direct β1 plus the reflex response to lower pressure.<br><br><b>Educational objective:</b> Isoproterenol (β1 + β2 agonist) increases contractility and heart rate while lowering systemic vascular resistance through β2 vasodilation.",
wrong={0:"Atropine blocks muscarinic receptors. It raises heart rate but doesn't directly change contractility or lower SVR.",
2:"Norepinephrine raises contractility (β1) but <b>raises</b> SVR through unopposed α1, since it has no β2.",
3:"Phenylephrine (α1) <b>raises</b> SVR and doesn't increase contractility.",
4:"Propranolol <b>decreases</b> contractility."},
eli5="This drug makes the heart squeeze harder and relaxes the blood vessels at the same time. Only a drug that hits both beta receptors, β1 for the heart and β2 for the vessels, with no alpha effect does that. That drug is isoproterenol."),

dict(img='Uvap', cap='Action potential of a ventricular myocyte (phases labeled A–E)',
stem="The figure shows an action potential recorded from a ventricular myocyte.{FIG}The portion labeled D is maintained by which of the following?",
choices=["Inward Ca²⁺ balanced by outward K⁺","Inward Na⁺ current through fast channels","Inward Na⁺ 'funny' current (If)","Outward K⁺ current through delayed rectifiers","Electrogenic Na⁺/K⁺-ATPase pumping alone"], key=0,
exp="<b>D is phase 2, the plateau</b>. <b>Inward Ca²⁺</b> through L-type channels is balanced by <b>outward K⁺</b>, so the membrane potential stays nearly flat. The Ca²⁺ that enters triggers Ca²⁺-induced Ca²⁺ release from the sarcoplasmic reticulum → contraction. That is why L-type Ca²⁺ channel blockers (verapamil, diltiazem) reduce contractility. The other phases: A = phase 4 (rest), B = phase 0 (Na⁺ upstroke), C = phase 1 (transient outward K⁺), E = phase 3 (K⁺ repolarization).<br><br><b>Educational objective:</b> The ventricular plateau (phase 2) is a balance of inward L-type Ca²⁺ current and outward K⁺ current, and its Ca²⁺ entry triggers contraction.",
wrong={1:"Fast inward Na⁺ is <b>phase 0 (B)</b>, the upstroke.",
2:"The funny current drives phase 4 in <b>pacemaker</b> cells, not the myocyte plateau.",
3:"Outward K⁺ alone would repolarize the cell, which is <b>phase 3 (E)</b>.",
4:"The Na⁺/K⁺-ATPase maintains ion gradients but doesn't generate the plateau."},
eli5="The flat plateau is a tug-of-war. Calcium flowing in pushes the voltage up while potassium flowing out pulls it down, so it stays level. That calcium is also what makes the muscle contract."),

dict(img=None,
stem="A 56-year-old man presents with sudden crushing chest pain. Angiography shows a thrombus on a ruptured coronary atherosclerotic plaque. He is given aspirin in the emergency department.{FIG}Which of the following best explains why an antiplatelet drug is used in this setting?",
choices=["Platelets aggregate on the exposed plaque","Platelets are the main source of LDL within the plaque","Platelets form the fibrous cap that stabilizes plaques","Platelets oxidize LDL to create foam cells","Platelets release nitric oxide that constricts the artery"], key=0,
exp="Lecture sequence: LDL enters the intima → oxidized → macrophage <b>foam cells</b> → fatty streak → plaque. When a plaque <b>ruptures</b>, it exposes thrombogenic material (collagen, lipid core, tissue factor) → <b>platelets adhere and aggregate</b> → thrombus → occlusion or embolism (acute coronary syndrome). Therefore: <b>lipid-lowering drugs to prevent disease</b>, and <b>antiplatelet drugs</b> (aspirin) to prevent clotting on plaques.<br><br><b>Educational objective:</b> Plaque rupture exposes thrombogenic material on which platelets aggregate to form a thrombus, which is why antiplatelet drugs are used in acute coronary syndromes.",
wrong={1:"LDL comes from the blood, not from platelets.",
2:"The fibrous cap is made by smooth muscle cells and collagen.",
3:"LDL oxidation happens in the intima, and macrophages form the foam cells.",
4:"Nitric oxide <b>dilates</b> vessels, and it comes mainly from the endothelium."},
eli5="When a cholesterol plaque cracks, the sticky inside is exposed and platelets pile onto it, forming a clot that blocks the artery. Aspirin makes platelets less sticky, so the clot is less likely to grow."),

dict(img=None,
stem="A 49-year-old man with high LDL cholesterol begins atorvastatin. Three months later his LDL concentration has fallen by 45%.{FIG}Which of the following best explains the fall in LDL?",
choices=["Blocking intestinal cholesterol absorption through NPC1L1","Binding bile acids in the intestine","Inhibiting HMG-CoA reductase in hepatocytes","Inhibiting PCSK9-mediated LDL receptor degradation","Increasing lipoprotein lipase activity through PPAR-α"], key=2,
exp="<b>Statins</b> inhibit <b>HMG-CoA reductase</b>, the rate-limiting enzyme of cholesterol synthesis. Lower intracellular hepatic cholesterol → SREBP activation → <b>more LDL receptors</b> on hepatocytes → more LDL cleared from the blood → a large fall in LDL. The lecture says you are accountable for the mechanism of each lipid drug: statins (HMG-CoA reductase), ezetimibe (NPC1L1), PCSK9 inhibitors (preserve LDL receptors), bile acid sequestrants, fibrates (PPAR-α) and niacin.<br><br><b>Educational objective:</b> Statins inhibit HMG-CoA reductase, lowering hepatic cholesterol and upregulating LDL receptors, which lowers plasma LDL.",
wrong={0:"Blocking NPC1L1 is <b>ezetimibe</b>.",
1:"Binding bile acids is how <b>bile acid sequestrants</b> (cholestyramine) work.",
3:"PCSK9 inhibition (evolocumab, alirocumab) prevents LDL receptor degradation. It is a different drug class.",
4:"PPAR-α activation is how <b>fibrates</b> work, and they mainly lower triglycerides."},
eli5="Statins block the liver's cholesterol factory. The liver then needs cholesterol from the blood, so it puts out more LDL receptors to grab it. More LDL is pulled out of the blood, so blood LDL falls."),

dict(img=None,
stem="A kidney from a donor with long-standing hypertension of renal origin is transplanted into a normotensive recipient. Over the following months the recipient develops sustained hypertension.{FIG}This observation best supports which of the following concepts?",
choices=["Baroreceptors in the donor kidney reset systemic pressure","Hypertension is caused mainly by cardiac output","The autonomic nervous system is the long-term regulator of BP","The kidney's sodium and volume handling sets long-term BP","Vascular smooth muscle dysfunction is transferred with the graft"], key=3,
exp="Dr. Scully's striking fact: <b>hypertension can be transplanted</b>. A kidney from a donor with renal-based hypertension makes the recipient hypertensive, which shows how central the kidney is. The <b>ANS is the fast responder</b> (seconds to minutes). <b>Volume, set by the kidney's Na⁺ and water handling, is the long-term answer</b>: the kidney effectively decides the pressure at which Na⁺ excretion matches intake.<br><br><b>Educational objective:</b> The kidney is the long-term regulator of blood pressure through sodium and volume handling, and renal-origin hypertension can be transferred by transplantation.",
wrong={0:"Baroreceptors are in the carotid sinus and aortic arch, not the kidney.",
1:"The transplant shows that the <b>kidney</b> drives the pressure, not the recipient's heart.",
2:"The ANS is the <b>short-term</b> regulator. Long-term control is renal.",
4:"The graft's own vessels are a trivial part of total systemic resistance. The kidney's volume control is the driver."},
eli5="Moving a 'high blood pressure' kidney into a healthy person gave that person high blood pressure. That shows the kidney, by deciding how much salt and water to keep, is the long-term boss of blood pressure."),
]
