# CV Pharm Basic Sciences Review (Scully) — Version 1, 18 items (3 with images)
Q = [
dict(img=None,
stem="A healthy volunteer receives an infusion of a drug that selectively activates β1-adrenergic receptors. Heart rate and contractility increase.{FIG}Which of the following additional changes is most likely?",
choices=["Decreased plasma renin activity","Decreased plasma aldosterone","Increased bronchial smooth muscle tone","Increased plasma renin activity","Increased skeletal-muscle vascular resistance"], key=3,
exp="<b>β1 receptors</b> sit on the heart (↑ rate, force, conduction velocity) <b>and on the juxtaglomerular (JG) cells</b> of the kidney → ↑ renin → RAAS → angiotensin II and aldosterone → more volume. So a β1 agonist <b>raises renin</b>, and β-blockers lower renin for the same reason. All β receptors are Gs-coupled → ↑ cAMP.<br><br><b>Educational objective:</b> β1 receptors on juxtaglomerular cells stimulate renin release, so β1 agonists raise renin and β-blockers lower it.",
wrong={0:"Renin <b>rises</b> with β1 stimulation. It falls with β-blockade.",
1:"More renin means more angiotensin II and therefore <b>more</b> aldosterone.",
2:"Bronchial smooth muscle is governed by <b>β2</b> (relaxation), which a selective β1 agonist wouldn't affect.",
4:"Skeletal-muscle vascular tone is set by α1 (constrict) and β2 (dilate), not β1."},
eli5="The β1 receptor isn't only on the heart. It's also on special kidney cells that release renin. Stimulate β1 and you speed the heart and switch on renin at the same time."),

dict(img=None,
stem="A 45-year-old man using nicotine lozenges to quit smoking notices a racing heartbeat and, at the same time, more frequent bowel movements.{FIG}Stimulation of which of the following receptors best explains both effects?",
choices=["α1-adrenergic receptors on vascular smooth muscle","β1-adrenergic receptors on the SA node","M2 muscarinic receptors on the SA node","M3 muscarinic receptors on intestinal smooth muscle","Neuronal nicotinic receptors in autonomic ganglia"], key=4,
exp="Preganglionic neurons of <b>both</b> the sympathetic and parasympathetic systems release acetylcholine onto <b>neuronal nicotinic (NN) receptors in the autonomic ganglia</b> (and the adrenal medulla). Nicotine activates them all → <b>both branches fire</b>: sympathetic (tachycardia, arousal) and parasympathetic (GI tract \"wakes up\"). That's also why nicotine toxicity is unpredictable. NN receptors are ligand-gated ion channels, not GPCRs.<br><br><b>Educational objective:</b> Neuronal nicotinic receptors sit in both sympathetic and parasympathetic ganglia, so nicotine activates both branches at once.",
wrong={0:"α1 stimulation causes vasoconstriction. It doesn't explain increased bowel activity.",
1:"β1 explains the tachycardia but not the increased GI motility (a parasympathetic effect).",
2:"M2 activation would <b>slow</b> the heart.",
3:"M3 explains the GI effect but not the tachycardia."},
eli5="Nicotine switches on the relay stations that both the 'fight or flight' and the 'rest and digest' systems pass through. So it revs up the heart and the gut at the same time."),

dict(img=None,
stem="A student asks how the diameter of peripheral arterioles is controlled at rest, given that the parasympathetic system innervates the heart, glands, and gut.{FIG}Which of the following best describes the autonomic control of resting peripheral arteriolar tone?",
choices=["Balanced sympathetic α1 and parasympathetic M3 input","Mainly parasympathetic nitric oxide release","Only β2-mediated sympathetic vasodilation","Tonic sympathetic α1 input, no vagal supply","Tonic vagal input via M2 receptors"], key=3,
exp="The peripheral vasculature has <b>no parasympathetic innervation</b>. Its tone comes only from <b>sympathetic α1</b> signalling (Gq → IP3 → Ca²⁺ → contraction), kept \"a little on\" like a <b>dimmer switch</b>. Dialing it up constricts, and dialing it back dilates. That's why α1 antagonists, central α2 agonists and anything that reduces sympathetic tone lower SVR. β2 receptors in skeletal-muscle beds add dilation during fight-or-flight.<br><br><b>Educational objective:</b> Peripheral arterioles have no parasympathetic supply. Resting tone is tonic sympathetic α1 activity, adjusted up or down like a dimmer.",
wrong={0:"There is no parasympathetic (M3) supply to peripheral arterioles to \"balance\" against.",
1:"Endothelial nitric oxide is a local mediator, not parasympathetic innervation of the vessel wall.",
2:"β2 dilation is limited to skeletal-muscle beds and fight-or-flight, and it isn't the source of resting tone.",
4:"M2 receptors are on the SA and AV nodes, not on arterioles, and the vagus doesn't innervate peripheral vessels."},
eli5="Blood vessels in the body only get nerve signals from the 'fight or flight' side. Those nerves keep the vessels slightly squeezed all the time, like a dimmer switch half on. Turning the dimmer down relaxes them."),

dict(img=None,
stem="Intravenous phenylephrine is given to a hypotensive patient, and systemic vascular resistance rises within a minute.{FIG}Which of the following intracellular events in vascular smooth muscle directly mediates this response?",
choices=["Activation of adenylyl cyclase and protein kinase A","Activation of soluble guanylyl cyclase","IP3-triggered Ca²⁺ release from internal stores","Inhibition of myosin light-chain kinase","Opening of K⁺ channels with hyperpolarization"], key=2,
exp="Phenylephrine is an <b>α1 agonist</b>. The rule: odd receptors (<b>α1</b>, M1, M3) → <b>Gq</b> → phospholipase C → PIP2 → <b>IP3</b> (releases Ca²⁺ from the sarcoplasmic reticulum) + DAG (activates PKC). ↑ Ca²⁺ → Ca²⁺–calmodulin → <b>MLCK</b> phosphorylates myosin → cross-bridges → contraction → vasoconstriction → ↑ SVR.<br><br><b>Educational objective:</b> α1 agonists act through Gq → PLC → IP3 → sarcoplasmic reticulum Ca²⁺ release → MLCK activation → vascular smooth muscle contraction.",
wrong={0:"Adenylyl cyclase → cAMP → PKA is the <b>Gs</b> (β) pathway. In smooth muscle PKA <b>inhibits</b> MLCK and causes relaxation.",
1:"Soluble guanylyl cyclase → cGMP is the <b>nitric oxide</b> relaxation pathway.",
3:"Inhibiting MLCK causes <b>relaxation</b>, which is the opposite effect.",
4:"K⁺ channel opening hyperpolarizes the cell and relaxes it."},
eli5="Phenylephrine docks on α1 receptors, which send a message (IP3) telling the cell's calcium store to release calcium. Calcium makes the muscle in the vessel wall contract, so the vessel narrows and resistance rises."),

dict(img=None,
stem="A patient with asthma uses inhaled albuterol, a β2 agonist, during an attack, and airflow improves within minutes.{FIG}Which of the following best describes how albuterol relaxes bronchial smooth muscle?",
choices=["Gi → ↓ cAMP → ↑ myosin light-chain kinase activity","Gq → IP3 → Ca²⁺ release → light-chain kinase on","Gs → cAMP → protein kinase A blocks light-chain kinase","NO → cGMP → protein kinase G → MLC phosphatase","Opening of ligand-gated Na⁺ channels, depolarizing"], key=2,
exp="\"<b>Betas are BS</b>\": every β receptor (β1, β2, β3) couples to <b>Gs</b> and breaks the odd/even rule. β2 → Gs → adenylyl cyclase → <b>↑ cAMP</b> → <b>PKA</b>. In smooth muscle, PKA <b>inhibits MLCK</b> → less myosin phosphorylation → <b>relaxation</b> (bronchodilation, and vasodilation in skeletal-muscle beds). In the heart the same cAMP increase causes the opposite outcome, stronger and faster contraction, through PKA phosphorylating Ca²⁺-handling proteins.<br><br><b>Educational objective:</b> β2 agonists relax smooth muscle through Gs → ↑ cAMP → PKA, which inhibits myosin light-chain kinase.",
wrong={0:"Gi lowering cAMP is the M2 and α2 pathway. It wouldn't relax bronchial muscle.",
1:"Gq → IP3 → Ca²⁺ causes <b>contraction</b> (the α1 and M3 pathway, bronchoconstriction).",
3:"NO → cGMP → PKG → MLC phosphatase is a real relaxation pathway, but it belongs to nitrates and endothelial NO, not β2 receptors.",
4:"Ligand-gated Na⁺ channels are nicotinic receptors, which depolarize cells."},
eli5="Albuterol hits β2 receptors, which raise cAMP inside the airway muscle. cAMP switches on PKA, which turns off the enzyme that makes muscle contract. The airway muscle relaxes and opens up."),

dict(img=None,
stem="Vagal stimulation slows the sinoatrial node firing rate and slows conduction through the AV node.{FIG}Which of the following receptor–G protein pairs mediates these effects?",
choices=["M1 muscarinic receptor · Gq","M2 muscarinic receptor · Gi","M3 muscarinic receptor · Gq","β1-adrenergic receptor · Gs","Neuronal nicotinic receptor · ion channel"], key=1,
exp="The vagus releases ACh onto <b>M2 receptors</b> in the SA and AV nodes → <b>Gi</b>. The α subunit <b>inhibits adenylyl cyclase</b> → ↓ cAMP, and the βγ subunit opens K⁺ channels (a board add-on) → <b>slower rate (negative chronotropy) and slower AV conduction (negative dromotropy)</b>. β1 (Gs) and M2 (Gi) <b>converge on adenylyl cyclase</b>, so the net heart rate is the integrated cAMP signal. The odd/even rule: M2 and α2 are Gi, and M1, M3 and α1 are Gq.<br><br><b>Educational objective:</b> Vagal slowing of the SA and AV nodes is mediated by M2 receptors coupled to Gi, which lowers cAMP.",
wrong={0:"M1 receptors (Gq) are in the CNS and gastric glands, not the cardiac nodes.",
2:"M3 (Gq) mediates smooth muscle contraction and gland secretion.",
3:"β1 (Gs) <b>speeds</b> the heart.",
4:"Nicotinic receptors are in the ganglia, upstream of the nodal effect, and don't slow the node directly."},
eli5="The vagus nerve releases acetylcholine onto M2 receptors in the heart's pacemaker. M2 uses a braking G protein (Gi) that lowers cAMP. Less cAMP means a slower heartbeat and slower passage through the AV node."),

dict(img=None,
stem="Acetylcholine applied to an intact artery causes relaxation, but the same artery constricts when the endothelium has been removed.{FIG}Which of the following best describes the pathway responsible for relaxation of the intact artery?",
choices=["Endothelial NO → guanylyl cyclase → cGMP","Endothelial prostacyclin → smooth muscle Gq → IP3","Smooth muscle M3 → Gq → IP3 → Ca²⁺ release","Smooth muscle β2 → Gs → cAMP → PKA","Smooth muscle α2 → Gi → ↓ cAMP"], key=0,
exp="With the endothelium intact, ACh acts on <b>endothelial</b> muscarinic receptors → ↑ Ca²⁺–calmodulin → <b>eNOS</b> → <b>nitric oxide</b>, which diffuses into smooth muscle → <b>soluble guanylyl cyclase</b> → <b>cGMP</b> → <b>PKG</b> → activates <b>MLC phosphatase</b> → dephosphorylated myosin → relaxation. Without endothelium, ACh hits smooth-muscle M3 (Gq) directly → contraction. Nitrates and nitroprusside plug into the same NO → cGMP pathway, and PDE5 inhibitors (sildenafil) stop cGMP breakdown.<br><br><b>Educational objective:</b> Endothelium-dependent vasodilation works through NO → soluble guanylyl cyclase → cGMP → PKG → MLC phosphatase.",
wrong={1:"Prostacyclin is a vasodilator through Gs/cAMP, not Gq/IP3, and it isn't the endothelium-dependent ACh pathway taught here.",
2:"Smooth-muscle M3 → Gq causes <b>contraction</b>, which explains the denuded artery constricting.",
3:"β2 → cAMP relaxes smooth muscle, but ACh isn't a β2 agonist.",
4:"α2 → Gi is presynaptic inhibition and doesn't explain ACh relaxation."},
eli5="In a healthy artery, acetylcholine tells the inner lining to release nitric oxide. Nitric oxide seeps into the muscle layer and makes cGMP, which relaxes the muscle. Strip off the lining and acetylcholine squeezes the muscle directly instead."),

dict(img=None,
stem="A patient with systolic heart failure is given a drug that dilates arterioles but has no effect on veins, heart rate, or contractility.{FIG}Which of the following is the most likely effect on this patient's cardiac performance?",
choices=["Decreased afterload with increased stroke volume","Decreased preload with decreased stroke volume","Increased afterload with decreased stroke volume","Increased contractility with increased stroke volume","Increased preload with increased stroke volume"], key=0,
exp="<b>MAP = CO × PVR</b>, with CO = HR × SV, and SV set by preload, contractility and afterload. Dilating <b>arterioles</b> (the resistance side) lowers <b>SVR = afterload</b>. Veins (the capacitance side) are untouched, so preload is unchanged. A failing ventricle ejecting against <b>less impedance</b> produces a <b>larger stroke volume for the same contractility</b>. That is the logic behind afterload reduction and the mortality-benefit drugs in heart failure.<br><br><b>Educational objective:</b> Arteriolar dilators lower afterload (SVR), and in systolic heart failure this raises stroke volume without changing contractility.",
wrong={1:"Lowering preload needs <b>venodilation</b> (nitrates) or volume removal (diuretics). This drug spares the veins.",
2:"Arteriolar dilation <b>reduces</b> afterload.",
3:"The drug has no effect on contractility, as stated.",
4:"Preload depends on venous tone and volume, which aren't changed here."},
eli5="Relaxing the small arteries lowers the resistance the heart has to push against. A weak heart can then push out more blood with each beat, even though it isn't squeezing any harder."),

dict(img=None,
stem="A 30-year-old man loses about 1 L of blood from a leg laceration. Over the next minutes his blood pressure falls modestly and then partially recovers before any fluids are given.{FIG}Which of the following best describes his immediate autonomic compensation?",
choices=["α1 vasoconstriction and β1-mediated tachycardia","β2-mediated muscle-bed vasodilation","Increased vagal (M2) tone to the SA node","Release of atrial natriuretic peptide","Suppression of renin release"], key=0,
exp="Blood loss → ↓ preload → ↓ cardiac output → BP falls → baroreceptors fire less → <b>sympathetic outflow rises</b> and vagal tone falls:<br>• <b>α1</b> → peripheral vasoconstriction (↑ SVR, and venoconstriction to restore preload).<br>• <b>β1</b> → tachycardia and more contractility (also ↑ renin).<br>That is the <b>fast</b> (ANS) response. The <b>slow</b> response is RAAS + thirst restoring volume over hours to days. The same machinery defends a <b>high</b> set point in hypertension.<br><br><b>Educational objective:</b> Acute blood loss is compensated within minutes by sympathetic α1 vasoconstriction and β1 tachycardia, and later by RAAS and thirst restoring volume.",
wrong={1:"β2 dilation of muscle beds would <b>lower</b> SVR, which is the wrong direction for compensation.",
2:"Vagal tone <b>falls</b> when BP drops, which lets the heart rate rise.",
3:"ANP is released with atrial <b>stretch</b> (volume overload) and promotes sodium loss. Blood loss suppresses it.",
4:"Renin <b>rises</b> with low renal perfusion and β1 stimulation."},
eli5="When he bleeds, pressure sensors notice the drop and hit the 'fight or flight' switch. Blood vessels squeeze and the heart speeds up to hold his pressure. Later, hormones make him thirsty and keep water to refill his blood."),

dict(img=None,
stem="In the kidney, angiotensin II helps maintain glomerular filtration rate when renal perfusion pressure falls.{FIG}Which of the following actions of angiotensin II is primarily responsible for this effect?",
choices=["Constriction of the efferent arteriole","Dilation of the afferent arteriole","Inhibition of antidiuretic hormone release","Stimulation of atrial natriuretic peptide release","Stimulation of bradykinin synthesis"], key=0,
exp="Angiotensin II's targets (lecture): the <b>adrenal cortex</b> (aldosterone), <b>proximal tubule</b> (↑ NaCl reabsorption), <b>efferent arterioles</b> (constrict), the <b>hypothalamus</b> (thirst, ADH) and the <b>heart</b> (remodelling). Constricting the <b>efferent</b> arteriole keeps pressure up inside the glomerulus, so <b>GFR is maintained</b> when perfusion falls. That is why ACE inhibitors and ARBs can drop GFR when a patient depends on it, such as with renal artery stenosis or volume depletion, and why they lower intraglomerular pressure and albuminuria in CKD.<br><br><b>Educational objective:</b> Angiotensin II maintains GFR mainly by constricting the efferent arteriole.",
wrong={1:"Angiotensin II constricts, rather than dilates, arterioles. Afferent dilation is driven by prostaglandins.",
2:"Angiotensin II <b>stimulates</b> ADH and thirst.",
3:"ANP is released by atrial stretch and opposes angiotensin II.",
4:"ACE <b>degrades</b> bradykinin. Angiotensin II doesn't make it."},
eli5="Angiotensin II squeezes the exit vessel of each kidney filter. That keeps the pressure inside the filter up, so the kidney keeps filtering even when less blood is coming in."),

dict(img='Uvap', cap='Action potential of a ventricular myocyte (phases labeled A–E)',
stem="The figure shows an action potential recorded from a ventricular myocyte.{FIG}Which of the following ionic currents is chiefly responsible for the portion of the action potential labeled B?",
choices=["Inward Ca²⁺ current through L-type channels","Inward Na⁺ current through fast channels","Inward Na⁺ 'funny' current (If)","Outward K⁺ current through delayed rectifier channels","Transient outward K⁺ current"], key=1,
exp="Ventricular myocyte phases: <b>A</b> = phase 4 (stable resting potential, about −85 mV). <b>B = phase 0</b>, the rapid upstroke, carried by <b>inward Na⁺ through fast voltage-gated channels</b>. C = phase 1 (transient outward K⁺). D = phase 2 plateau (inward Ca²⁺ balanced by outward K⁺). E = phase 3 (K⁺ repolarization).<br><br>Dr. Scully's three class questions: <b>myocyte upstroke = Na⁺</b>, <b>nodal upstroke = Ca²⁺</b>, <b>repolarization (both) = K⁺</b>. These are exactly the currents antiarrhythmics target (class I blocks Na⁺).<br><br><b>Educational objective:</b> Phase 0 of the ventricular myocyte action potential is carried by fast inward Na⁺ current.",
wrong={0:"L-type Ca²⁺ current sustains the <b>plateau (phase 2, D)</b> in myocytes. It is the upstroke only in <b>nodal</b> cells.",
2:"The funny current (If) drives <b>phase 4</b> depolarization in <b>pacemaker</b> cells, not myocytes.",
3:"Delayed-rectifier K⁺ current drives <b>phase 3</b> repolarization (E).",
4:"Transient outward K⁺ current causes the small notch of <b>phase 1</b> (C)."},
eli5="Segment B is the lightning-fast jump when the heart muscle cell fires. It happens because sodium rushes in through fast channels. Later, calcium holds the plateau and potassium brings the cell back down."),

dict(img='Upace', cap='Action potential of a sinoatrial nodal cell (phases numbered)',
stem="The figure shows an action potential recorded from a sinoatrial nodal cell. The upward arrows beneath the tracing mark inward currents.{FIG}Which of the following currents is chiefly responsible for the slow depolarization during phase 4?",
choices=["Inward Ca²⁺ current through L-type channels","Inward Na⁺ current through fast voltage-gated channels","Inward Na⁺ 'funny' current (If)","Outward K⁺ current through delayed rectifier channels","Transient outward K⁺ current"], key=2,
exp="Nodal (pacemaker) cells have <b>no stable resting potential</b>:<br>• <b>Phase 4</b>: slow spontaneous depolarization, from the <b>funny current (If)</b> (inward, mainly Na⁺), joined late by T-type Ca²⁺.<br>• <b>Phase 0</b>: a slow upstroke carried by <b>Ca²⁺</b> (L-type).<br>• <b>Phase 3</b>: repolarization by <b>K⁺</b>.<br>The slope of phase 4 sets the heart rate: sympathetic stimulation steepens it and vagal (M2) stimulation flattens it.<br><br><b>Educational objective:</b> Phase 4 pacemaker depolarization in SA nodal cells is driven by the funny current (If). The nodal upstroke is Ca²⁺ and repolarization is K⁺.",
wrong={0:"L-type Ca²⁺ current carries the nodal <b>phase 0</b> upstroke.",
1:"Fast Na⁺ channels carry the <b>myocyte</b> upstroke. They are largely inactive in nodal cells.",
3:"Delayed-rectifier K⁺ current causes <b>phase 3</b> repolarization.",
4:"Transient outward K⁺ current creates phase 1 in <b>myocytes</b>. Nodal cells lack a phase 1."},
eli5="The heart's pacemaker cells never sit still. A trickle of sodium called the funny current slowly lifts their voltage between beats until they fire. The steeper that slope, the faster the heart beats."),

dict(img=None,
stem="A 60-year-old man is started on verapamil. His follow-up ECG shows a slower sinus rate and a longer PR interval, with an unchanged QRS duration.{FIG}Which of the following best explains these ECG changes?",
choices=["Blockade of K⁺ channels prolonging phase 3 in myocytes","Blockade of Na⁺ channels slowing phase 0 in myocytes","Reduced Ca²⁺ entry slowing phase 0 in nodal cells","Stimulation of M2 receptors in the SA node","Stimulation of β1 receptors in the AV node"], key=2,
exp="Verapamil blocks <b>L-type Ca²⁺ channels</b>. In <b>nodal (SA and AV) cells</b>, phase 0 is carried by Ca²⁺ → slower SA firing (slower sinus rate) and slower AV conduction (<b>longer PR</b>). In ventricular myocytes, phase 0 is Na⁺, so the QRS is unchanged. Verapamil is the most cardioselective CCB, and that's why it is never combined with a β-blocker.<br><br><b>Educational objective:</b> L-type Ca²⁺ channel blockers slow the Ca²⁺-dependent nodal upstroke, lowering the sinus rate and prolonging the PR interval without widening the QRS.",
wrong={0:"K⁺ channel blockade prolongs repolarization and the <b>QT</b> interval, not the PR.",
1:"Na⁺ channel blockade slows the myocyte upstroke and <b>widens the QRS</b>, which is unchanged here.",
3:"Verapamil isn't a muscarinic agonist. The nodal slowing comes from Ca²⁺ channel blockade.",
4:"β1 stimulation would <b>speed</b> the rate and <b>shorten</b> the PR."},
eli5="The SA and AV nodes use calcium to fire. Verapamil blocks calcium channels, so the pacemaker fires more slowly and the AV node passes signals more slowly, which lengthens the PR. Ventricular muscle fires with sodium, so the QRS stays the same."),

dict(img=None,
stem="A coronary artery specimen from a 58-year-old man shows a lipid-rich plaque in the intima. Microscopy reveals large cells with foamy, lipid-filled cytoplasm beneath the endothelium.{FIG}These foam cells are derived mainly from which of the following, after uptake of which lipid?",
choices=["Endothelial cells · native HDL","Fibroblasts · triglycerides","Macrophages · oxidized LDL","Neutrophils · chylomicron remnants","Platelets · free fatty acids"], key=2,
exp="Lecture sequence: too much <b>LDL</b> enters the intima → it is <b>oxidized</b> → monocytes enter and become <b>macrophages</b> → they ingest <b>oxidized LDL</b> through scavenger receptors → <b>foam cells</b> → fatty streak → plaque. When a plaque <b>ruptures</b>, it exposes thrombogenic material → platelet aggregation and thrombus → occlusion or embolism. Hence lipid-lowering drugs to prevent disease and antiplatelets to prevent clots on plaques. Smooth muscle cells can also become foam cells, but macrophages are the classic source.<br><br><b>Educational objective:</b> Foam cells are mainly macrophages that have ingested oxidized LDL in the intima, forming the fatty streak.",
wrong={0:"Endothelial cells don't become foam cells, and HDL removes cholesterol from the vessel wall.",
1:"Fibroblasts form the fibrous cap, not lipid-laden foam cells.",
3:"Neutrophils are not the source of foam cells in atherosclerosis.",
4:"Platelets gather on a <b>ruptured</b> plaque to form thrombus. They don't become foam cells."},
eli5="Bad cholesterol (LDL) sneaks into the artery wall and gets damaged, or oxidized. Clean-up cells called macrophages gobble it up until they're stuffed with fat and look foamy. Piles of these foam cells start a plaque."),

dict(img=None,
stem="A patient receives an intravenous infusion of phenylephrine. His blood pressure rises from 110/70 to 150/95 mm Hg, and his heart rate falls from 80 to 58/min.{FIG}Which of the following drugs would prevent the fall in heart rate while leaving the rise in blood pressure intact?",
choices=["Atropine","Clonidine","Metoprolol","Nicotine","Prazosin"], key=0,
exp="Class question 1. <b>Phenylephrine</b> is a pure <b>α1 agonist</b> → vasoconstriction → ↑ SVR → ↑ BP → <b>baroreceptors</b> (carotid sinus, cranial nerve IX; aortic arch, cranial nerve X) → brainstem → sympathetic tone down and <b>parasympathetic up</b> → ACh on <b>M2</b> in the SA node → <b>reflex bradycardia</b>. Block it with an M2 antagonist: <b>atropine</b>.<br><br><b>Educational objective:</b> Phenylephrine raises BP through α1 and causes reflex bradycardia through a vagal (M2) baroreflex, which atropine blocks.",
wrong={1:"Clonidine lowers sympathetic outflow and would <b>worsen</b> bradycardia.",
2:"Metoprolol blocks β1 and would slow the heart further.",
3:"Nicotine stimulates both autonomic branches unpredictably, and it is not a treatment.",
4:"Prazosin blocks α1 receptors, so it would prevent the <b>pressure rise</b> itself (and the reflex only indirectly). The question asks to keep the pressor effect."},
eli5="Phenylephrine squeezes the blood vessels, so pressure jumps. Pressure sensors respond by pressing the vagus nerve's brake on the heart, which slows it. Atropine blocks that brake."),

dict(img=None,
stem="In an isolated adrenergic synapse preparation, norepinephrine is released by nerve stimulation, and investigators measure how quickly the synaptic signal ends.{FIG}Which of the following is the principal mechanism that terminates norepinephrine's action in the synapse?",
choices=["Diffusion into the bloodstream","Hydrolysis by acetylcholinesterase","Metabolism by catechol-O-methyltransferase","Metabolism by monoamine oxidase","Reuptake by the norepinephrine transporter"], key=4,
exp="Unlike acetylcholine (destroyed in the cleft by acetylcholinesterase), norepinephrine is mainly <b>recycled</b>: <b>reuptake by the norepinephrine transporter (NET)</b> removes about <b>70%</b>, the primary termination, and VMAT repackages it into vesicles. What escapes is broken down by <b>MAO</b> (in the nerve terminal) and <b>COMT</b> (mainly liver), or diffuses away. NE in the cleft also hits presynaptic <b>α2 (Gi)</b> autoreceptors, a negative-feedback brake on further release.<br><br><b>Educational objective:</b> Norepinephrine's synaptic action ends mainly by reuptake through the norepinephrine transporter (~70%). MAO and COMT handle the rest.",
wrong={0:"Diffusion contributes a little but isn't the main route.",
1:"Acetylcholinesterase ends <b>cholinergic</b> signaling, not adrenergic.",
2:"COMT metabolizes catecholamines mainly in the liver. It is a secondary route.",
3:"MAO degrades NE that has been taken back up or escaped. It isn't the primary termination."},
eli5="After norepinephrine does its job, most of it is vacuumed back into the nerve that released it, to be reused. Only the leftover bits get broken down by enzymes."),

dict(img='Uepi', cap='Diastolic blood pressure and heart rate during epinephrine infusion, alone (left) and after pretreatment with Drug A (right)',
stem="In a pharmacology experiment, one group of volunteers receives an intravenous infusion of low-dose epinephrine. A second group receives the same infusion after pretreatment with Drug A. The effects on diastolic blood pressure and heart rate are shown.{FIG}Drug A is most likely which of the following?",
choices=["Atropine","Phentolamine","Phenylephrine","Prazosin","Propranolol"], key=4,
exp="<b>Epinephrine alone</b> (low dose) stimulates β1 (↑ heart rate) and <b>β2 > α1</b> in skeletal-muscle beds → vasodilation → <b>diastolic pressure falls</b>.<br><b>After Drug A</b>, diastolic pressure <b>rises</b> and heart rate <b>falls</b>. That means the β effects are gone and epinephrine's <b>α1 vasoconstriction is unmasked</b>. The rise in BP then triggers <b>reflex bradycardia</b> (baroreflex → vagal M2). A <b>non-selective β-blocker (propranolol)</b> blocks both the β2 dilation and the β1 tachycardia.<br><br><b>Educational objective:</b> A non-selective β-blocker unmasks epinephrine's α1 vasoconstriction, so diastolic pressure rises and heart rate falls by reflex.",
wrong={0:"Atropine blocks M2 and would <b>prevent</b> reflex bradycardia. It wouldn't unmask α1 pressor effects.",
1:"Phentolamine blocks α receptors, leaving β2 dilation <b>unopposed</b>. Diastolic BP would fall further (\"epinephrine reversal\").",
2:"Phenylephrine is an α1 agonist. As a pretreatment it doesn't explain the loss of epinephrine's β effects.",
3:"Prazosin blocks α1 and would make epinephrine's net effect <b>more</b> vasodilatory, not less."},
eli5="On its own, low-dose epinephrine opens muscle blood vessels and speeds the heart. Propranolol blocks those beta effects, so epinephrine's vessel-squeezing alpha effect takes over. Pressure goes up, and the body slows the heart in response."),

dict(img=None,
stem="A 64-year-old man with stable angina uses sublingual nitroglycerin. He has also been prescribed sildenafil for erectile dysfunction. He is counseled never to take the two within the same day.{FIG}Which of the following best explains the danger of combining these drugs?",
choices=["Both block L-type Ca²⁺ channels in arterioles","Both increase cAMP in vascular smooth muscle","Nitroglycerin makes cGMP; sildenafil blocks its breakdown","Sildenafil inhibits the metabolism of nitroglycerin","Sildenafil stimulates α1 receptors"], key=2,
exp="<b>Nitrates</b> release NO → soluble guanylyl cyclase → <b>↑ cGMP production</b>. <b>Sildenafil</b> inhibits <b>PDE5</b>, which normally <b>breaks down cGMP</b>. One makes cGMP and the other keeps it from being destroyed → cGMP accumulates → PKG → profound vasodilation → <b>dangerous hypotension</b>. Dr. Scully draws the parallel to <b>dobutamine + inamrinone</b>: one makes cAMP (β1 agonist) and the other blocks its breakdown (PDE3 inhibitor), so together they overshoot.<br><br><b>Educational objective:</b> Nitrates (↑ cGMP synthesis) plus PDE5 inhibitors (↓ cGMP breakdown) cause severe hypotension through additive cGMP accumulation.",
wrong={0:"Neither drug is a calcium channel blocker.",
1:"The shared messenger is <b>cGMP</b>, not cAMP. The cAMP version of this interaction is dobutamine + PDE3 inhibitors.",
3:"The problem is pharmacodynamic (the same messenger), not a metabolic interaction.",
4:"Sildenafil doesn't act on α1 receptors. It dilates vessels."},
eli5="Nitroglycerin makes a relaxing messenger called cGMP, and sildenafil stops cGMP from being cleaned up. Together cGMP floods the blood vessels, they relax too much, and blood pressure crashes."),
]
