# ECG Basics (Qazi) — Version 0, 15 concept items (4 with an image). Easier, short stems.
Q = [
dict(img=None,
stem="On a normal ECG, each wave represents one step of the heart's electrical cycle.{FIG}The P wave represents which of the following?",
choices=["Atrial depolarization","Atrial repolarization","Delay in the AV node","Ventricular depolarization","Ventricular repolarization"], key=0,
exp="The trace follows conduction step by step: SA node fires → <b>atria depolarize (P wave)</b> → pause in the AV node (the flat PR segment) → His–Purkinje → <b>ventricles depolarize (QRS)</b> → <b>ventricles repolarize (T wave)</b>. Atrial repolarization happens during the QRS and is hidden by it.<br><br><b>Educational objective:</b> P = atrial depolarization, PR segment = AV nodal delay, QRS = ventricular depolarization, T = ventricular repolarization.",
wrong={1:"Atrial repolarization is buried inside the QRS complex, so it has no visible wave of its own.",
2:"The AV nodal delay is the flat <b>PR segment</b> after the P wave, not the P wave itself.",
3:"Ventricular depolarization is the <b>QRS complex</b>.",
4:"Ventricular repolarization is the <b>T wave</b>."},
eli5="The P wave is the little bump made when the top chambers get their electrical signal. Next comes a short pause, then the big QRS spike for the bottom chambers. The T wave is the bottom chambers resetting."),

dict(img=None,
stem="An ECG is recorded at the standard paper speed of 25 mm/s.{FIG}How much time does one large box (5 small boxes) represent?",
choices=["0.04 seconds","0.10 seconds","0.20 seconds","0.40 seconds","1.00 second"], key=2,
exp="At 25 mm/s: <b>1 small box = 1 mm = 0.04 s (40 ms)</b>. <b>1 large box = 5 small boxes = 0.20 s (200 ms)</b>. <b>5 large boxes = 1 second</b>, and a standard 12-lead is 10 seconds. Handy anchors: the upper limit of a normal PR (200 ms) is one large box, and the upper limit of a normal QRS (120 ms) is 3 small boxes.<br><br><b>Educational objective:</b> At 25 mm/s a small box is 0.04 s and a large box is 0.20 s.",
wrong={0:"0.04 s is <b>one small box</b>, not a large box.",
1:"0.10 s would be 2½ small boxes, which is not a standard grid unit.",
3:"0.40 s is two large boxes.",
4:"1 second is <b>five</b> large boxes."},
eli5="Each tiny square on ECG paper is 0.04 seconds. A big square holds five tiny squares, so it's 0.2 seconds. Five big squares make one second."),

dict(img=None,
stem="Every level of the cardiac conduction system (SA node, AV node, His–Purkinje fibers) can generate beats on its own.{FIG}Which of the following best explains why the SA node normally controls the heart rate?",
choices=["It has the fastest intrinsic firing rate","It is supplied by the left coronary artery","It is the only tissue with automaticity","It lies closest to the ventricles","It receives no autonomic innervation"], key=0,
exp="Each level of the conduction system has its own intrinsic rate, each slower than the one above: SA node (~60–100) > AV node/junction (~40–60) > ventricles (~20–40). The <b>fastest pacemaker wins</b> because it resets the slower ones before they fire. The SA node leads only because it is fastest. If it fails or is ablated, the AV node takes over at a slower rate (an escape rhythm).<br><br><b>Educational objective:</b> The SA node is the dominant pacemaker because it has the fastest intrinsic rate. Lower pacemakers take over as slower escape rhythms if it fails.",
wrong={1:"The SA node is usually supplied by the <b>right</b> coronary artery (~60%), and its blood supply is not why it leads.",
2:"The AV node and Purkinje fibers also have automaticity, which is how escape rhythms occur.",
3:"The SA node lies high in the right atrium, the <b>farthest</b> part of the system from the ventricles.",
4:"The SA node is heavily innervated. Vagal and sympathetic tone slow it down and speed it up."},
eli5="Several spots in the heart can act as a pacemaker, but each has its own speed. The SA node is the fastest, so it always fires first and sets the beat. If it stops, a slower backup takes over."),

dict(img=None,
stem="Dr. Qazi determines the axis in about two seconds by looking only at the QRS in lead I and lead aVF.{FIG}Which of the following combinations indicates a normal axis?",
choices=["Lead I negative, aVF negative","Lead I negative, aVF positive","Lead I positive, aVF isoelectric","Lead I positive, aVF negative","Lead I positive, aVF positive"], key=4,
exp="The two-lead shortcut:<br>• I <b>+</b>, aVF <b>+</b> → <b>normal</b> (\"two thumbs up\").<br>• I +, aVF − → <b>left</b> axis (peaks point away from each other).<br>• I −, aVF + → <b>right</b> axis (peaks point toward each other).<br>If aVF is isoelectric, use <b>lead II</b> instead (same pattern), which gets you ~95% of the way. Normal is about −30° to +90°.<br><br><b>Educational objective:</b> A positive QRS in both lead I and aVF means a normal axis. I positive with aVF negative is left axis, and I negative with aVF positive is right axis.",
wrong={0:"Both negative puts the axis in the far upper-right quadrant (\"northwest\"), which is extreme axis deviation.",
1:"Lead I negative with aVF positive is <b>right</b> axis deviation (causes: RVH, left posterior fascicular block, old lateral infarct).",
2:"When aVF is isoelectric you can't decide from aVF, so look at <b>lead II</b> as a tie-breaker.",
3:"Lead I positive with aVF negative is <b>left</b> axis deviation (causes: LVH, LBBB, left anterior fascicular block, old inferior infarct)."},
eli5="Look at two leads, I and aVF. If the main spike points up in both, like two thumbs up, the axis is normal. Up in one and down in the other means the axis has swung left or right."),

dict(img=None,
stem="A resident is checking whether a regular rhythm is sinus rhythm.{FIG}Which of the following findings is one of the required criteria for sinus rhythm?",
choices=["A biphasic P wave in lead aVR","A heart rate between 50 and 90/min","A PR interval that lengthens each beat","A QRS duration of at least 120 ms","An upright P wave in lead II each beat"], key=4,
exp="Dr. Qazi's <b>five criteria for sinus rhythm</b> (all must be true):<br>1. Regular R–R.<br>2. Regular P–P.<br>3. Constant PR.<br>4. A P for every QRS.<br>5. An <b>upright P in lead II</b> (the impulse started in the SA node and travels down toward lead II).<br>Sinus rhythm can be any rate: under 60 is sinus bradycardia, and 100 or more is sinus tachycardia.<br><br><b>Educational objective:</b> Sinus rhythm needs regular R–R and P–P intervals, a constant PR, a P for every QRS, and an upright P wave in lead II.",
wrong={0:"The P wave is normally <b>inverted</b> in aVR. It is lead V1 where the normal P is biphasic.",
1:"Rate doesn't define sinus rhythm. A sinus rhythm at 110 is still sinus, and is called sinus tachycardia.",
2:"A lengthening PR is <b>Mobitz I</b> AV block. Sinus rhythm needs a <b>constant</b> PR.",
3:"A QRS of 120 ms or more means a bundle branch block or a ventricular origin, which has nothing to do with whether the rhythm starts in the SA node."},
eli5="A normal sinus rhythm starts at the top of the heart, so the signal travels down toward lead II and makes an upright P wave. The beats also have to be evenly spaced, each with its own P wave, and the same gap before every QRS."),

dict(img='kafib', cap='12-lead ECG',
stem="A 78-year-old man comes to the office because of palpitations. His ECG is shown.{FIG}Which of the following is the most likely rhythm?",
choices=["Atrial fibrillation","Atrial flutter","Multifocal atrial tachycardia","Sinus arrhythmia","Sinus tachycardia"], key=0,
exp="No distinct P waves, an undulating (fibrillatory) baseline, and an <b>irregularly irregular</b> R–R interval with no pattern = <b>atrial fibrillation</b>. It is the arrhythmia you'll see most, about 90% of rhythm problems in adult cardiology.<br><br>Why it matters: the atria contribute 20–30% of cardiac output, so losing them can tip a weak heart into failure. Stagnant blood in the left atrium also forms clots, causing embolic stroke, so patients are anticoagulated.<br><br><b>Educational objective:</b> Atrial fibrillation has no P waves, an undulating baseline and an irregularly irregular rhythm.",
wrong={1:"Atrial flutter has regular <b>sawtooth</b> waves (best in II, III, aVF), often with a fixed ratio to the QRS.",
2:"Multifocal atrial tachycardia has distinct P waves of <b>at least three shapes</b>. Here there are none.",
3:"Sinus arrhythmia has normal P waves before every QRS, with a rate that varies with breathing.",
4:"Sinus tachycardia is regular, with an upright P before every QRS."},
eli5="The top chambers are quivering instead of beating, so there are no clear P waves, just a wobbly line. The bottom chambers get random signals, so the beats come at totally irregular times."),

dict(img=None,
stem="A patient's rhythm strip shows the PR interval getting a little longer with each beat until a P wave is not followed by a QRS complex. The next PR is short again, and the cycle repeats.{FIG}Which of the following is the most likely diagnosis?",
choices=["2:1 AV block","First-degree AV block","Mobitz I (Wenckebach) block","Mobitz II AV block","Third-degree AV block"], key=2,
exp="A PR that <b>lengthens progressively</b> until a QRS is dropped, then resets to a shorter PR = <b>second-degree AV block, Mobitz I (Wenckebach)</b>. Dr. Qazi's tip: the PR <b>after</b> the dropped beat is shorter than the one before it, which is easier to see than the gradual lengthening. Mobitz I is at the AV node and is usually <b>benign</b>. Mobitz II (constant PR, sudden drops) is high-grade and needs a pacemaker.<br><br><b>Educational objective:</b> Mobitz I (Wenckebach) is a progressively lengthening PR ending in a dropped QRS, and it is usually benign.",
wrong={0:"In 2:1 block every other P is dropped, so there are never two conducted beats in a row to show lengthening. You can't tell type I from type II.",
1:"First-degree block has a long but <b>constant</b> PR, and no beats are dropped.",
3:"Mobitz II has a <b>constant</b> PR before a sudden dropped beat, with no warning lengthening.",
4:"Third-degree block has P waves and QRS complexes marching independently, with a PR that varies randomly and no cycle."},
eli5="Each beat, the AV node gets a bit more tired and the signal takes longer to pass. Eventually one signal doesn't get through at all. Then the node recovers and the cycle starts over."),

dict(img=None,
stem="A medical student is measuring intervals on a 12-lead ECG.{FIG}What is the upper limit of a normal QRS duration?",
choices=["80 ms (2 small boxes)","120 ms (3 small boxes)","200 ms (1 large box)","450 ms (about 11 small boxes)","500 ms (2½ large boxes)"], key=1,
exp="Normal intervals from the lecture:<br>• <b>PR ≤200 ms</b> (1 large box). Longer points to AV nodal delay or AV block.<br>• <b>QRS under 120 ms</b> (3 small boxes). Wider points to a bundle branch block or a ventricular origin.<br>• <b>QTc under 450 ms (men) or 460 ms (women)</b>. Over 500 ms is dangerous (torsades risk).<br><br><b>Educational objective:</b> A normal QRS is under 120 ms (3 small boxes). A wider QRS suggests a bundle branch block.",
wrong={0:"80 ms is a typical, comfortably normal QRS, but it isn't the <b>upper limit</b>.",
2:"200 ms is the upper limit of a normal <b>PR interval</b>, not the QRS.",
3:"About 450 ms is the upper limit of a normal <b>corrected QT</b> in men.",
4:"Over 500 ms is the dangerous <b>QTc</b> threshold for torsades, not a QRS value."},
eli5="The QRS is the quick spike made when the bottom chambers fire. Normally it's narrow, under 3 tiny boxes (0.12 seconds). If it's wider, the signal is taking a slow detour, often because a bundle branch is blocked."),

dict(img=None,
stem="An ECG shows a QRS duration of 140 ms.{FIG}Which of the following findings in lead V1 would indicate a right bundle branch block?",
choices=["A deep, wide, mostly negative QRS","A late second R wave (rSR′ pattern)","A slurred upstroke with a short PR interval","A tall, peaked T wave after the QRS","ST elevation with a pathologic Q wave"], key=1,
exp="Wide QRS + <b>rSR′ (\"rabbit ears\") in V1–V2</b> + slurred S waves in I, aVL and V5–V6 = <b>right bundle branch block</b>. The mnemonic is \"MaRRoW\": M in V1, W in V6. The right ventricle is activated late, from the left, and that late activation makes the second R (R′). RBBB alone has a <b>normal axis</b>.<br>LBBB is the opposite (\"WiLLiaM\"): V1–V3 mostly negative, broad notched R waves in I, aVL and V6, and a left axis.<br><br><b>Educational objective:</b> Right bundle branch block is a wide QRS with an rSR′ in V1–V2 and slurred lateral S waves.",
wrong={0:"A deep, mostly negative V1 with a wide QRS is <b>left</b> bundle branch block.",
2:"A slurred upstroke (delta wave) with a short PR is <b>Wolff–Parkinson–White</b> pre-excitation.",
3:"Tall, peaked T waves suggest <b>hyperkalemia</b>.",
4:"ST elevation with Q waves reflects an evolving <b>infarction</b>, not a bundle branch block."},
eli5="When the right wiring branch is blocked, the right side of the heart gets its signal late. That late signal adds a second bump in lead V1, which looks like rabbit ears. It also makes the QRS wider."),

dict(img=None,
stem="A patient is being started on a drug known to prolong the QT interval, and a baseline ECG is obtained.{FIG}Above which corrected QT (QTc) value does the risk of torsades de pointes rise sharply?",
choices=["200 ms","350 ms","400 ms","450 ms","500 ms"], key=4,
exp="QTc = QT ÷ √RR (Bazett). Normal is under <b>450 ms (men) or 460 ms (women)</b>. <b>Over 500 ms</b>, the risk of <b>torsades de pointes</b> (polymorphic ventricular tachycardia that \"twists\" around the baseline) rises sharply.<br><br>Common culprits: class III antiarrhythmics (dofetilide, sotalol), fluoroquinolones, antidepressants, antipsychotics, HIV drugs, and low potassium or magnesium. Check the medication list and electrolytes before prescribing.<br><br><b>Educational objective:</b> A QTc over 500 ms markedly raises the risk of torsades de pointes.",
wrong={0:"200 ms is the upper limit of a normal <b>PR</b> interval.",
1:"350 ms is a normal QTc.",
2:"400 ms is a normal QTc.",
3:"450 ms is the upper limit of <b>normal</b> for men. Values above it are prolonged, but the sharp rise in torsades risk comes above 500 ms."},
eli5="The QT is how long the bottom chambers take to fire and reset. When it's stretched past 500 milliseconds, the heart can slip into a dangerous twisting rhythm called torsades. Many common drugs stretch it."),

dict(img='kflutter', cap='12-lead ECG',
stem="A 70-year-old woman comes to the emergency department because of palpitations. Her ECG is shown.{FIG}Which of the following is the most likely rhythm?",
choices=["Atrial fibrillation","Atrial flutter","Complete heart block","Sinus tachycardia","Wandering atrial pacemaker"], key=1,
exp="Regular <b>\"sawtooth\"</b> atrial waves at ~300/min, best seen in the inferior leads (II, III, aVF), with a fixed ratio of flutter waves to QRS complexes (here several flutter waves per QRS) = <b>atrial flutter</b>. Dr. Qazi calls it \"highly tested.\" Typical flutter is a re-entry circuit in the <b>right atrium around the cavotricuspid isthmus</b>, while atrial fibrillation starts around the pulmonary veins in the left atrium.<br><br><b>Educational objective:</b> Atrial flutter shows regular sawtooth flutter waves, best in II, III and aVF, usually with a fixed conduction ratio.",
wrong={0:"Atrial fibrillation has a chaotic baseline and an <b>irregularly irregular</b> rhythm, with no organized sawtooth waves.",
2:"In complete heart block, discrete P waves march independently of the QRS complexes. There are no sawtooth waves.",
3:"Sinus tachycardia has a single normal P wave before each QRS.",
4:"A wandering atrial pacemaker has discrete P waves of at least three shapes at a rate under 100."},
eli5="The top chambers are looping an electrical signal round and round very fast, which draws a sawtooth line. Only some of those loops get through to the bottom chambers. That sawtooth pattern is the giveaway for atrial flutter."),

dict(img='kste', cap='Normal complex (left) and two abnormal complexes (right)',
stem="The diagram compares a normal P–QRS–T complex (left) with two abnormal complexes (right) recorded in a patient with acute chest pain.{FIG}The change shown on the right most likely indicates which of the following?",
choices=["An old, completed infarction","Delayed ventricular repolarization","Normal repolarization in young adults","Subendocardial ischemia","Transmural myocardial injury"], key=4,
exp="The two right-hand complexes show <b>ST elevation</b>: the segment between the QRS and T is raised above the baseline. In a patient with chest pain, ST elevation of ≥1 mm in two or more contiguous leads = <b>transmural injury</b>, which is a STEMI. It usually means plaque rupture with <b>100% occlusion</b> of a coronary artery, so the artery needs to be opened now (\"time is muscle\").<br><br>Dr. Qazi's three findings:<br>• ST elevation = transmural injury (STEMI).<br>• ST depression = subendocardial injury (NSTEMI).<br>• Q waves = dead, old infarct.<br><br><b>Educational objective:</b> ST elevation in contiguous leads indicates acute transmural injury (STEMI), usually from complete coronary occlusion.",
wrong={0:"An old, completed infarct shows <b>Q waves</b> with a flat ST segment, not ST elevation.",
1:"Delayed repolarization prolongs the <b>QT interval</b>. It does not raise the ST segment.",
2:"Benign early repolarization can raise the ST segment slightly in the young, but in a patient with acute chest pain, marked ST elevation must be treated as injury.",
3:"Subendocardial ischemia causes ST <b>depression</b>."},
eli5="When a heart artery is completely blocked, the whole thickness of the wall is injured. That lifts the flat part after the QRS, the ST segment, above the baseline. Doctors call it a STEMI and rush to open the artery."),

dict(img='kqwave', cap='Normal complex (top) and abnormal complex (bottom)',
stem="The diagram compares a normal P–QRS–T complex (top) with an abnormal complex (bottom) seen in leads II, III, and aVF of a patient with no current chest pain.{FIG}The abnormality in the bottom complex most likely indicates which of the following?",
choices=["Acute transmural injury","Delayed conduction in the right bundle","High serum potassium","Old infarction with dead myocardium","Subendocardial ischemia"], key=3,
exp="The bottom complex has a <b>deep, wide Q wave</b> (at least 1 small box wide and deep) with a flat ST segment. A <b>pathologic Q wave</b> in an anatomic group of leads (here II, III and aVF, the inferior wall) means <b>dead myocardium, an old, completed infarction</b>. The infarct is usually completed within 12–24 hours, and the Q waves persist. Dr. Qazi: a small Q is normal only in lead III.<br><br><b>Educational objective:</b> Pathologic Q waves (1 small box or more) in contiguous leads indicate an old, completed myocardial infarction.",
wrong={0:"Acute transmural injury shows <b>ST elevation</b>. This ST segment is flat.",
1:"Right bundle branch delay widens the <b>end</b> of the QRS (the rSR′ in V1). It does not produce a deep initial Q wave.",
2:"High potassium produces <b>tall, peaked T waves</b> and a widening QRS, not a Q wave.",
4:"Subendocardial ischemia shows ST <b>depression</b>."},
eli5="When heart muscle dies, it turns into scar that doesn't conduct electricity. The leads over that scar see a deep downward dip at the start of the QRS, called a Q wave. It's a footprint of an old heart attack."),

dict(img=None,
stem="A patient with chest pain has ST elevation in leads II, III, and aVF.{FIG}In most people, occlusion of which of the following arteries causes this pattern?",
choices=["Left anterior descending artery","Left circumflex artery","Left main coronary artery","Obtuse marginal artery","Right coronary artery"], key=4,
exp="Leads <b>II, III and aVF</b> look at the <b>inferior wall</b>. In a <b>right-dominant</b> circulation (~80% of people), the <b>right coronary artery</b> gives off the posterior descending artery, which supplies the inferior wall. In a left-dominant circulation (~20%), the circumflex does. The right coronary artery also supplies the AV node (~90%), which is why inferior infarcts often cause bradycardia or heart block.<br><br>Territory map: II/III/aVF inferior → right coronary artery. V1–V4 anteroseptal and anterior → left anterior descending. I, aVL, V5–V6 lateral → circumflex or diagonal branches.<br><br><b>Educational objective:</b> ST elevation in II, III and aVF (inferior STEMI) is usually a right coronary artery occlusion.",
wrong={0:"Left anterior descending occlusion gives ST elevation in <b>V1–V4</b> (anterior wall).",
1:"The circumflex supplies the inferior wall only in the ~20% of people who are left-dominant. It more often affects the lateral leads (I, aVL, V5–V6).",
2:"Left main occlusion causes a massive anterior and lateral injury, not an isolated inferior pattern.",
3:"An obtuse marginal branch of the circumflex supplies part of the lateral wall, not the inferior wall."},
eli5="Leads II, III and aVF look at the bottom of the heart. In most people the bottom is fed by the right coronary artery. So heart-attack changes in those leads usually mean that artery is blocked."),

dict(img=None,
stem="A patient receiving hemodialysis missed two treatments. An ECG is obtained.{FIG}Tall, narrow, peaked T waves on this patient's ECG most strongly suggest which of the following?",
choices=["High serum calcium","High serum potassium","Low serum calcium","Low serum magnesium","Low serum potassium"], key=1,
exp="<b>Tall, narrow, peaked (tented) T waves</b> are the earliest ECG sign of <b>hyperkalemia</b>, which is common when dialysis is missed. As potassium keeps rising, the P waves flatten and disappear, the PR lengthens, the QRS widens, and the tracing becomes a sine wave before ventricular fibrillation or asystole. Dr. Qazi: \"high K prolongs everything.\" Contrast <b>low</b> potassium: flat T waves and prominent U waves.<br><br><b>Educational objective:</b> Peaked T waves are the earliest ECG sign of hyperkalemia. Worsening hyperkalemia widens every interval.",
wrong={0:"High calcium <b>shortens</b> the QT (a short ST segment). It doesn't peak the T waves.",
2:"Low calcium lengthens the ST segment and the QT, without peaking the T waves.",
3:"Low magnesium prolongs the QT and predisposes to torsades de pointes.",
4:"Low potassium does the opposite: <b>flat</b> T waves with prominent U waves."},
eli5="Without dialysis, potassium builds up in the blood. Extra potassium makes the T waves tall and pointy, like a tent. If it keeps rising, the whole heartbeat stretches out and can stop, so it's an emergency."),
]
