# Pharmacologic Management of Hypertension (Scully) — Version 2, 18 items (3 with images)
Q = [
dict(img=None,
stem="A 24-year-old man has blood pressures of 146/84 mm Hg on repeated visits. His resting pulse is 94/min. Echocardiography shows a hyperdynamic left ventricle with an increased cardiac output; calculated systemic vascular resistance is normal. Thyroid function, plasma metanephrines, and aldosterone-to-renin ratio are normal.{FIG}This patient's hypertension is best classified as which of the following types?",
choices=["Cardiac (pump-based)","Neuroendocrine (secondary)","Renal (volume-based)","Vascular (resistance-based)","White-coat"], key=0,
exp="<b>Cardiac (pump-based)</b> hypertension = <b>↑ cardiac output with normal SVR</b>, and it tends to occur in <b>younger</b> patients (a hyperdynamic circulation). Contrast <b>vascular</b> (normal cardiac output, ↑ SVR) in the ageing population, <b>renal</b> (volume: both ↑), and <b>neuroendocrine</b> (a hormone excess, excluded here by normal thyroid, metanephrines and aldosterone). Knowing the source tells you which dial to turn.<br><br><b>Educational objective:</b> Hypertension with raised cardiac output and normal systemic vascular resistance is the cardiac (pump-based) type, typical of younger patients.",
wrong={1:"Neuroendocrine causes (pheochromocytoma, hyperaldosteronism, hyperthyroidism) have been excluded by normal tests.",
2:"Volume-based hypertension raises both cardiac output and SVR. His SVR is normal.",
3:"Vascular hypertension has a <b>normal</b> cardiac output with raised SVR, mostly in older patients.",
4:"White-coat hypertension is limited to office readings. His hemodynamics are measurably abnormal."},
eli5="His heart is pumping harder and faster than usual, pushing out extra blood, while his blood vessels are normal. That pump-driven kind of high blood pressure is typical of young people."),

dict(img=None,
stem="A 38-year-old woman has had episodes of pounding headache, palpitations, and drenching sweats over 6 months. During an episode her blood pressure is 210/120 mm Hg; between episodes it is 150/95 mm Hg. Plasma free metanephrines are markedly elevated, and CT shows a 4-cm left adrenal mass.{FIG}Which of the following best describes the approach to this patient's hypertension?",
choices=["Begin a calcium channel blocker plus an ACE inhibitor","Start lifestyle modification and recheck in 3–6 months","Treat the underlying cause of the hypertension","Use a thiazide diuretic to reduce intravascular volume","Use β-blocker monotherapy to slow the heart rate"], key=2,
exp="Episodic headache, palpitations and sweating with paroxysmal severe hypertension and high metanephrines = <b>pheochromocytoma</b>, a <b>neuroendocrine (secondary)</b> hypertension driven by catecholamines. Dr. Scully: for secondary causes (pheochromocytoma, primary hyperaldosteronism, hyperthyroidism), <b>treat the cause</b>, and the patient may not need drugs aimed at the pump or the RAAS at all. For pheochromocytoma that means surgical removal after α-blockade, with a β-blocker only after α-blockade (a board add-on).<br><br><b>Educational objective:</b> Secondary (neuroendocrine) hypertension such as pheochromocytoma is managed by treating the underlying cause rather than with routine first-line antihypertensives.",
wrong={0:"First-line CCB + ACEi is the essential-hypertension algorithm. It doesn't address a catecholamine-secreting tumor.",
1:"Lifestyle-only management is for low-risk stage 1 essential hypertension, not a tumor causing crises.",
3:"Diuretics target volume, which is not the driver here.",
4:"A β-blocker <b>alone</b> in pheochromocytoma leaves α1 vasoconstriction unopposed and can trigger a hypertensive crisis (a board add-on)."},
eli5="Her high blood pressure comes from a small adrenal tumor pumping out adrenaline in bursts. Ordinary blood pressure pills don't fix the source. Removing the tumor, after preparing her with the right medicine, does."),

dict(img=None,
stem="A 52-year-old man with stage 1 hypertension and a body mass index of 34 kg/m² wants to avoid medication. He plans to lose weight through diet and exercise.{FIG}If he loses 10 kg (22 lb), approximately how much should his systolic blood pressure fall from weight loss alone?",
choices=["1 mm Hg","5 mm Hg","10 mm Hg","25 mm Hg","40 mm Hg"], key=2,
exp="The lecture rule of thumb: <b>~1 mm Hg systolic per 1 kg of weight lost</b>, so 10 kg ≈ <b>10 mm Hg</b>. Each lifestyle measure (weight loss, a DASH or Mediterranean diet, low sodium, more potassium, aerobic and resistance exercise, moderate alcohol, stopping oral contraceptives or stimulants) lowers BP by about 1–10 mm Hg, and together about <b>10–20 mm Hg</b>. The effect is larger in hypertensive than in normotensive people. Lifestyle is for <b>every</b> patient, and it is the only treatment for elevated BP and low-risk stage 1.<br><br><b>Educational objective:</b> Weight loss lowers systolic blood pressure by about 1 mm Hg per kilogram lost. Combined lifestyle changes lower it by about 10–20 mm Hg.",
wrong={0:"1 mm Hg is the drop per <b>single</b> kilogram, not per 10 kg.",
1:"5 mm Hg underestimates the ~1 mm Hg/kg relationship.",
3:"25 mm Hg is more than all lifestyle measures <b>combined</b> typically achieve (10–20 mm Hg).",
4:"40 mm Hg is far beyond the expected effect of weight loss."},
eli5="A handy rule: every kilogram lost drops the top blood pressure number by about 1 point. Losing 10 kg should lower it by about 10 points. Add less salt, more exercise and less alcohol, and the drops add up."),

dict(img=None,
stem="A 57-year-old woman with type 2 diabetes mellitus has confirmed blood pressures averaging 136/86 mm Hg. She has no kidney disease or cardiovascular disease and takes metformin.{FIG}According to the 2025 guideline, which of the following is the most appropriate management?",
choices=["Emergency evaluation for target-organ damage","Lifestyle only, then monotherapy if needed","No treatment, because BP is below 140/90","Start a single antihypertensive drug plus lifestyle","Start a two-drug single-pill combination"], key=3,
exp="136/86 = <b>stage 1</b> (130–139/80–89). The stage 1 question: clinical ASCVD, heart failure, <b>diabetes</b>, CKD, age ≥65, or 10-year risk ≥7.5%? She has <b>diabetes → yes</b> → <b>monotherapy</b> (ACEi, ARB, DHP CCB or thiazide) plus lifestyle. Without a risk feature, stage 1 gets lifestyle first with a recheck in 3–6 months. Two-drug combinations are the default for <b>stage 2</b>.<br><br><b>Educational objective:</b> Stage 1 hypertension with a high-risk feature (diabetes, CKD, heart failure, ASCVD, age ≥65, or risk ≥7.5%) is treated with a single drug plus lifestyle.",
wrong={0:"Emergency evaluation is for BP over 180/120.",
1:"Lifestyle-first is for <b>low-risk</b> stage 1. Diabetes makes her high-risk.",
2:"The 2025 thresholds treat 130/80 and above. 140/90 is outdated.",
4:"A two-drug single pill is the default for <b>stage 2</b>, not stage 1."},
eli5="Her blood pressure is only mildly high, but diabetes raises her heart risk. So she starts one blood pressure pill along with healthy habits rather than waiting."),

dict(img=None,
stem="An 81-year-old woman who lives alone and uses a walker has confirmed blood pressures of 158/92 mm Hg. She has had two falls this year and becomes lightheaded easily. She has no other chronic diseases.{FIG}Which of the following is the most appropriate initial pharmacotherapy?",
choices=["Amlodipine–olmesartan–hydrochlorothiazide single pill","Amlodipine–perindopril single pill","Clonidine plus prazosin","Low-dose amlodipine alone","No treatment until BP exceeds 180/110"], key=3,
exp="158/92 = <b>stage 2</b>. The stage 2 question: age <b>over 75</b>, <b>underweight or frail</b>, or multiple medication intolerances? She is 81 and frail (falls, walker) → <b>monotherapy</b> is appropriate, started gently, because two drugs at once risk hypotension and falls. In lecture Case 1, a 76-year-old was likewise given a single drug (lisinopril).<br><br><b>Educational objective:</b> In stage 2 hypertension, patients over 75, frail, underweight or with multiple drug intolerances start with monotherapy rather than a combination.",
wrong={0:"Three-drug single pills are for <b>stepped care</b>, not initiation, and are riskiest in a frail patient.",
1:"A two-drug combination is the default only when the patient is ≤75 and not frail.",
2:"Two sympatholytics is a combination to avoid (stacked side effects, orthostasis), especially in someone prone to falls.",
4:"Stage 2 hypertension warrants treatment. 180/120 is the threshold for urgent assessment, not for starting therapy."},
eli5="She's elderly, frail and prone to falls, so dropping her pressure too fast could make her dizzy and fall. The guideline starts older frail patients on just one gentle pill."),

dict(img=None,
stem="A 49-year-old man has a blood pressure of 188/112 mm Hg at a routine visit and 186/114 mm Hg on repeat. He has no headache, chest pain, dyspnea, neurologic symptoms, or visual changes. Funduscopic examination, ECG, serum creatinine, and urinalysis are normal.{FIG}Which of the following is the most appropriate management?",
choices=["Admit for intravenous nitroprusside","Begin two-drug therapy with close follow-up","Lifestyle modification and recheck in 3–6 months","Reassure him and recheck at his next annual visit","Start a single low-dose agent and recheck in 6 months"], key=1,
exp="Severe hypertension (SBP >180 and/or DBP >120) triggers <b>urgent assessment for acute target-organ damage</b>. His fundi, ECG, creatinine, urinalysis and symptoms are all normal → <b>no acute damage</b> (a hypertensive urgency, not an emergency). Per the algorithm: no damage → <b>combination therapy</b> (oral, outpatient) with close follow-up. Emergency or inpatient care is only for acute target-organ damage.<br><br><b>Educational objective:</b> Blood pressure over 180/120 without acute target-organ damage is treated with oral combination therapy and close follow-up, not emergency admission.",
wrong={0:"IV nitroprusside and admission are for a hypertensive <b>emergency</b> with acute organ damage. He has none.",
2:"Lifestyle-only management is for low-risk stage 1, not BP over 180/110.",
3:"Deferring to next year is unsafe at this level.",
4:"Monotherapy is inadequate at this level unless he is over 75 or frail, and 6 months is far too long."},
eli5="His pressure is very high, but nothing is being damaged right now: eyes, heart, kidneys and brain all check out. So he doesn't need the hospital, but he does need two medicines started and a quick check-up."),

dict(img=None,
stem="A 63-year-old woman with type 2 diabetes mellitus and chronic kidney disease has blood pressures of 142/88 mm Hg. Her urine albumin-to-creatinine ratio is 480 mg/g. She is postmenopausal.{FIG}Which of the following drug classes should be part of her regimen because it specifically addresses her comorbidity?",
choices=["α1-adrenergic antagonist","Angiotensin II receptor blocker","Central α2-adrenergic agonist","Dihydropyridine calcium channel blocker","Loop diuretic"], key=1,
exp="Inset 1 (\"let the comorbidity choose the drug\"): <b>CKD with albuminuria → ACEi or ARB</b>. Blocking angiotensin II dilates the <b>efferent arteriole</b> more than the afferent → intraglomerular pressure falls → less albumin leaks → the kidney is protected. Losartan is specifically indicated for <b>diabetic nephropathy</b>. Monitor potassium and creatinine, and never combine an ACEi with an ARB. She is postmenopausal, so pregnancy is not a concern.<br><br><b>Educational objective:</b> Hypertension with CKD and albuminuria (especially diabetic nephropathy) calls for an ACE inhibitor or ARB for renal protection.",
wrong={0:"α1 antagonists are not first-line and have no renal-protective effect. They are reserved for comorbid BPH.",
2:"Central α2 agonists (clonidine) have no albuminuria benefit and aren't first-line.",
3:"A DHP CCB lowers BP but dilates the afferent arteriole and doesn't reduce albuminuria as RAAS blockers do.",
4:"Loop diuretics treat volume overload in advanced CKD, but they are not antiproteinuric."},
eli5="Her kidneys are leaking protein because the pressure inside their filters is too high. ARBs relax the filters' exit vessels, lowering that pressure and protecting the kidneys."),

dict(img=None,
stem="A 70-year-old man has hypertension and bothersome urinary hesitancy and weak stream from benign prostatic hyperplasia. His blood pressure is 142/86 mm Hg. He wants to treat both problems with one drug if possible.{FIG}Which of the following drugs is most appropriate?",
choices=["Amlodipine","Clonidine","Hydrochlorothiazide","Lisinopril","Prazosin"], key=4,
exp="Inset 1 (lecture example): <b>BPH → α1 antagonist (prazosin)</b>. Blocking α1 receptors <b>relaxes genitourinary smooth muscle</b> (prostate and bladder neck), which improves flow, and <b>peripheral vascular smooth muscle</b>, which lowers SVR and BP. α1 antagonists are otherwise <b>not first-line</b> for hypertension. Watch for first-dose orthostatic hypotension, and don't pair with a second sympatholytic.<br><br><b>Educational objective:</b> An α1 antagonist such as prazosin treats hypertension and BPH together by relaxing vascular and genitourinary smooth muscle. It is not otherwise first-line.",
wrong={0:"Amlodipine lowers BP but has no effect on prostatic smooth muscle.",
1:"Clonidine lowers sympathetic outflow centrally but doesn't treat BPH and isn't first-line.",
2:"A thiazide increases urine volume, which can worsen urinary symptoms, and doesn't treat BPH.",
3:"Lisinopril is first-line for BP but does nothing for the prostate."},
eli5="Prazosin relaxes the muscle in blood vessels and in the prostate. So one pill lowers his blood pressure and makes it easier to pee."),

dict(img=None,
stem="A 74-year-old woman with hypertension has had several episodes of lightheadedness on standing. Her blood pressure is 150/88 mm Hg supine and 124/74 mm Hg after 3 minutes standing, with a rise in heart rate from 72 to 80/min. She currently takes no antihypertensives.{FIG}Which of the following is the most appropriate antihypertensive for her?",
choices=["Amlodipine","Clonidine","Furosemide","Hydrochlorothiazide","Prazosin"], key=0,
exp="Inset 1: <b>orthostatic hypotension → DHP CCB, ACEi or ARB</b>. <b>Avoid sympatholytics and diuretics</b>. Sympatholytics (α1 antagonists, central α2 agonists, β-blockers) blunt the reflex vasoconstriction and tachycardia needed to stand up. Diuretics lower preload by removing volume. Both worsen orthostatic drops.<br><br><b>Educational objective:</b> In hypertension with orthostatic hypotension, choose a dihydropyridine CCB, ACE inhibitor or ARB, and avoid sympatholytics and diuretics.",
wrong={1:"Clonidine reduces sympathetic outflow, blunting the standing reflex, and can cause marked orthostasis.",
2:"A loop diuretic depletes volume and lowers preload, which worsens orthostasis.",
3:"Thiazides reduce intravascular volume, which worsens orthostatic drops.",
4:"Prazosin (an α1 antagonist) blocks the reflex vasoconstriction needed on standing and is notorious for first-dose orthostasis."},
eli5="When she stands, her body needs to squeeze her blood vessels and hold onto fluid to keep blood in her head. Some pills block that squeeze or remove fluid, making her dizzier. Amlodipine lowers pressure without taking away those defenses."),

dict(img=None,
stem="A 61-year-old man with type 2 diabetes mellitus and hypertension takes losartan 100 mg daily. His blood pressure remains 144/90 mm Hg. A colleague suggests adding a drug that blocks renin directly.{FIG}Adding this drug would carry the greatest risk of which of the following?",
choices=["Hyperkalemia and kidney injury","Hypoglycemia","Hyponatremia and hypokalemia","Peripheral edema","Reflex tachycardia from vasodilation"], key=0,
exp="The direct renin inhibitor is <b>aliskiren</b> (\"-kiren\"), which blocks renin so no angiotensin I is formed. Dr. Scully: <b>never give two RAAS blockers</b>, especially <b>aliskiren with an ACEi or ARB in diabetics</b>. Double RAAS blockade → aldosterone falls → <b>hyperkalemia</b>, plus a fall in glomerular pressure → <b>renal impairment</b> and hypotension. Aliskiren is also contraindicated in pregnancy. Add a complementary class instead (a DHP CCB or thiazide).<br><br><b>Educational objective:</b> Aliskiren (a direct renin inhibitor) must not be combined with an ACE inhibitor or ARB, especially in diabetics, because of hyperkalemia, renal impairment and hypotension.",
wrong={1:"Aliskiren doesn't cause hypoglycemia. Thiazides, if anything, impair glucose tolerance.",
2:"Hyponatremia and hypokalemia are <b>thiazide</b> effects. Double RAAS blockade raises potassium.",
3:"Peripheral edema is the hallmark of <b>DHP CCBs</b>.",
4:"Reflex tachycardia comes from rapid, vessel-selective dilators such as nifedipine."},
eli5="Losartan and aliskiren block two steps of the same hormone chain. Using both shuts it down too hard, so potassium builds up and the kidneys can get hurt, especially in people with diabetes. Doctors add a different kind of pill instead."),

dict(img=None,
stem="A 55-year-old man with hypertension switches from lisinopril to valsartan. His blood pressure remains well controlled.{FIG}Which of the following best describes the difference in mechanism between the two drugs?",
choices=["Only lisinopril blocks AT1 receptors","Only lisinopril prevents bradykinin breakdown","Only valsartan lowers aldosterone secretion","Only valsartan prevents conversion of angiotensin I","Only valsartan requires hepatic activation"], key=1,
exp="<b>ACE inhibitors (lisinopril)</b> block angiotensin-converting enzyme → less angiotensin II <b>and</b>, because ACE is kininase II, <b>bradykinin is not broken down</b> → extra vasodilation, but also cough and angioedema. <b>ARBs (valsartan)</b> are <b>competitive AT1 receptor antagonists</b>. They block angiotensin II's action downstream and leave ACE, and bradykinin breakdown, untouched. Both lower aldosterone. Valsartan is indicated for hypertension, heart failure and post-MI.<br><br><b>Educational objective:</b> ACE inhibitors reduce angiotensin II formation and prevent bradykinin breakdown. ARBs block the AT1 receptor and don't affect bradykinin.",
wrong={0:"It's the reverse: <b>valsartan</b> blocks AT1 receptors. Lisinopril reduces angiotensin II formation.",
2:"<b>Both</b> reduce angiotensin II's stimulation of aldosterone.",
3:"Preventing conversion of angiotensin I to II is what the <b>ACE inhibitor</b> does.",
4:"Valsartan is active as given. Among ACE inhibitors, enalapril is the prodrug."},
eli5="Lisinopril blocks the enzyme that makes angiotensin II. That same enzyme also clears bradykinin, so bradykinin builds up. Valsartan instead blocks the receptor angiotensin II docks onto, leaving the enzyme and bradykinin alone."),

dict(img=None,
stem="A 66-year-old woman has hypertension and newly diagnosed atrial fibrillation with a ventricular rate of 118/min. Her blood pressure is 152/94 mm Hg. She prefers a single medication that addresses both problems.{FIG}Which of the following is the most appropriate choice?",
choices=["Amlodipine","Diltiazem","Hydrochlorothiazide","Losartan","Nifedipine"], key=1,
exp="Inset 1: <b>atrial fibrillation → β-blocker or non-DHP CCB</b>. Among CCBs, <b>diltiazem</b> is Dr. Scully's \"<b>sweet spot</b>\": it acts on the <b>AV node</b> (rate control) <b>and</b> the peripheral vessels (BP), neither as strongly as the selective agents. Verapamil is mostly cardiac, and the \"-dipines\" are mostly vascular. Diltiazem is excreted hepatically. Don't combine it with a β-blocker.<br><br><b>Educational objective:</b> Diltiazem acts on both the AV node and the peripheral vessels, so it controls both ventricular rate and blood pressure in hypertension with atrial fibrillation.",
wrong={0:"Amlodipine lowers BP but doesn't slow AV nodal conduction, so the AF rate stays fast.",
2:"A thiazide lowers BP but has no effect on the AF rate.",
3:"Losartan lowers BP but doesn't control ventricular rate.",
4:"Nifedipine is purely vascular and can cause <b>reflex tachycardia</b>, the opposite of what's needed."},
eli5="Diltiazem does two jobs at once: it slows the AV node so the racing AF heartbeat calms down, and it relaxes blood vessels to lower pressure. One pill covers both problems."),

dict(img=None,
stem="A 72-year-old man who takes metoprolol for coronary disease arrives at the emergency department with a regular narrow-complex tachycardia at 170/min. A clinician is about to give intravenous-push verapamil.{FIG}This combination is most likely to cause which of the following?",
choices=["Acute drug-induced heart failure","Angioedema","Hyperkalemia","Hypertensive crisis","Torsades de pointes"], key=0,
exp="Inset 2: <b>β-blocker + non-DHP CCB</b> (verapamil, diltiazem) is a combination to avoid. Both depress the SA node, the AV node and contractility. IV-push verapamil on top of a β-blocker can cause <b>electromechanical decoupling</b>, meaning <b>acute drug-induced heart failure</b>, with severe bradycardia, heart block and hypotension. Verapamil is the <b>most cardioselective</b> CCB, the worst partner for a β-blocker.<br><br><b>Educational objective:</b> Giving IV verapamil to a patient on a β-blocker can cause electromechanical decoupling (acute drug-induced heart failure) from additive nodal and contractile depression.",
wrong={1:"Angioedema is an ACE inhibitor effect (bradykinin).",
2:"Hyperkalemia comes from RAAS blockers and potassium-sparing diuretics.",
3:"Both drugs <b>lower</b> blood pressure. The danger is collapse, not a crisis.",
4:"Torsades follows QT-prolonging drugs (dofetilide, sotalol), not this combination."},
eli5="Metoprolol and verapamil both put the brakes on the heart. Together, especially with verapamil given fast into a vein, the heart can slow and weaken so much that it can't pump properly. That's why this combination is avoided."),

dict(img=None,
stem="A 50-year-old woman with nephrotic syndrome and resistant hypertension has a serum albumin of 1.9 g/dL. Her physician adds a diuretic that will work despite her low albumin and reduced glomerular filtration.{FIG}Which of the following best explains why spironolactone is effective in this setting?",
choices=["It reaches its receptor from the blood side","It blocks NCC in the distal convoluted tubule","It is a prodrug activated within the renal tubule","It is secreted into the tubule bound to albumin","It potently inhibits carbonic anhydrase"], key=0,
exp="Most diuretics (thiazides, loops) must be <b>albumin-bound and secreted or filtered</b> into the tubular lumen to reach their luminal target. So they work poorly with low albumin (nephrotic syndrome) or a low GFR. <b>Spironolactone</b> is a mineralocorticoid receptor antagonist that reaches the <b>intracellular MR of the principal cell from the blood side</b>. It <b>doesn't need albumin binding or glomerular filtration</b>, so it works in <b>liver failure and nephrotic syndrome</b>. Its mechanism: bind MR → prevent nuclear translocation → fewer Na⁺ channels.<br><br><b>Educational objective:</b> Spironolactone acts on the intracellular mineralocorticoid receptor from the blood side, so it doesn't need albumin binding or filtration and works in nephrotic syndrome and liver failure.",
wrong={1:"Blocking NCC is the <b>thiazide</b> mechanism, which needs luminal delivery.",
2:"Spironolactone is not activated in the tubule. Its effect is on the principal cell's intracellular receptor.",
3:"Needing albumin for secretion is exactly why <b>thiazides and loops</b> fail in hypoalbuminemia.",
4:"Spironolactone doesn't inhibit carbonic anhydrase (that's acetazolamide)."},
eli5="Most water pills have to be carried by albumin into the urine-side of the kidney tubule to work. With her low albumin they can't get there. Spironolactone reaches its target from the blood side, so it still works."),

dict(img='Ahypok', cap='12-lead ECG',
stem="A 67-year-old woman began a new antihypertensive 6 weeks ago. She now reports muscle cramps and fatigue. Her blood pressure is 132/80 mm Hg. Her ECG is shown.{FIG}Which of the following sets of laboratory findings is most likely?",
choices=["Na⁺ high · K⁺ high · HCO₃⁻ low","Na⁺ low · K⁺ high · HCO₃⁻ low","Na⁺ low · K⁺ low · HCO₃⁻ high","Na⁺ normal · K⁺ high · HCO₃⁻ normal","Na⁺ normal · K⁺ low · HCO₃⁻ low"], key=2,
exp="The ECG shows low, <b>flat T waves</b>, the pattern of <b>hypokalemia</b>. The likely new drug is a <b>thiazide</b> (hydrochlorothiazide), whose adverse effects include <b>hyponatremia</b> and <b>hypokalemic metabolic alkalosis</b>. More Na⁺ delivered to the collecting duct → more K⁺ and H⁺ secretion (worsened by volume-driven aldosterone) → low K⁺ and raised bicarbonate. Also hyperuricemia and gout, impaired glucose tolerance, hyperlipidemia, hypercalcemia and photosensitivity.<br><br><b>Educational objective:</b> Thiazides cause hyponatremia and hypokalemic metabolic alkalosis. Hypokalemia flattens the T waves (and can add U waves).",
wrong={0:"High Na⁺ with high K⁺ and acidosis isn't a thiazide pattern, and her ECG shows low, not high, potassium.",
1:"Low Na⁺ with <b>high</b> K⁺ and acidosis fits mineralocorticoid deficiency or potassium-sparing diuretics, not a flat-T ECG.",
3:"Isolated hyperkalemia (RAAS blockers, K⁺-sparing diuretics) causes <b>peaked</b> T waves, the opposite of this ECG.",
4:"Low K⁺ with <b>low</b> bicarbonate (as in renal tubular acidosis or diarrhea) is not the thiazide pattern, which is an alkalosis."},
eli5="Her water pill makes the kidneys lose extra potassium and acid. Low potassium flattens the T waves on her ECG and causes muscle cramps. Low sodium and extra bicarbonate come along with it."),

dict(img='Lhighk', cap='12-lead ECG with lead II rhythm strip',
stem="A 71-year-old man with hypertension and stage 3 chronic kidney disease has taken lisinopril for 5 years with stable laboratory results. One week ago, a new diuretic was added for edema. He now has profound weakness. His ECG is shown.{FIG}Which of the following newly added drugs most likely caused this ECG?",
choices=["Amiloride","Chlorthalidone","Furosemide","Hydrochlorothiazide","Metolazone"], key=0,
exp="The ECG shows <b>severe hyperkalemia</b>: peaked T waves, flattened P waves and a widening QRS. The new drug that <b>raises potassium</b> is the <b>potassium-sparing diuretic</b> amiloride (or triamterene), which blocks <b>ENaC</b> in the principal cell. Less Na⁺ enters → a less negative lumen → less K⁺ secretion. Stacked on an <b>ACE inhibitor</b> (↓ aldosterone) in <b>CKD</b>, potassium climbs dangerously. Its adverse effects are hyperkalemia and hyperkalemic metabolic acidosis.<br><br><b>Educational objective:</b> Potassium-sparing diuretics (ENaC blockers, MR antagonists) cause hyperkalemia, especially combined with ACE inhibitors or ARBs in CKD.",
wrong={1:"Chlorthalidone is a thiazide-like diuretic, which <b>lowers</b> potassium.",
2:"Furosemide, a loop diuretic, <b>wastes</b> potassium.",
3:"Hydrochlorothiazide causes <b>hypokalemia</b>.",
4:"Metolazone is a thiazide-like diuretic, which <b>lowers</b> potassium."},
eli5="The new water pill tells the kidney to hold onto potassium, and lisinopril already does the same. With weak kidneys, potassium piled up to a dangerous level. That's what makes these tall, spiky T waves and wide beats."),

dict(img=None,
stem="A 29-year-old woman with chronic hypertension at 20 weeks' gestation is started on a drug with the longest safety record in pregnancy, with offspring followed up to 7 years. She is counseled that it may cause sedation.{FIG}This drug lowers blood pressure by which of the following mechanisms?",
choices=["Blocking α1 and β receptors","Blocking L-type calcium channels in arterioles","Directly relaxing arteriolar smooth muscle","Inhibiting angiotensin-converting enzyme","Stimulating central α2 receptors"], key=4,
exp="<b>α-Methyldopa</b> has the <b>longest safety record</b> in pregnancy (offspring data to 7 years), but it is less effective. It works <b>like clonidine</b>: a <b>central α2 agonist</b> (through its metabolite α-methylnorepinephrine, a board add-on) → presynaptic Gi brake → <b>↓ sympathetic outflow</b> → ↓ cardiac output and SVR. Its adverse effects are <b>sedation</b>, depression and dizziness.<br><br><b>Educational objective:</b> α-Methyldopa is a central α2 agonist that lowers sympathetic outflow. It has the longest safety record in pregnancy but causes sedation.",
wrong={0:"Blocking α1 and β receptors is <b>labetalol</b>, another pregnancy option.",
1:"Blocking L-type channels is <b>nifedipine</b> (the ER form is used in pregnancy).",
2:"Direct arteriolar relaxation is <b>hydralazine</b>, used only for acute management.",
3:"ACE inhibition is contraindicated in pregnancy."},
eli5="Methyldopa works in the brain, turning down the nerve signals that squeeze blood vessels and speed the heart. It's been used in pregnancy the longest, so doctors trust it, though it can make people sleepy."),

dict(img=None,
stem="A 34-year-old woman with chronic hypertension controlled on lisinopril learns she is 7 weeks pregnant. She is distressed and worried that the medication has already harmed her baby.{FIG}Which of the following is the most appropriate response?",
choices=["Advise termination because of certain fetal harm","Continue lisinopril at a lower dose","Continue lisinopril and add labetalol","Stop antihypertensives until the third trimester","Switch to labetalol or nifedipine ER now"], key=4,
exp="ACE inhibitors, ARBs and aliskiren are contraindicated in pregnancy because of fetal renal toxicity (low amniotic fluid). The lecture's reassurance: the harm is greatest in the <b>2nd and 3rd trimesters</b>. A patient who discovers an early pregnancy on an ACE inhibitor <b>shouldn't panic</b>. <b>Switch now</b> to a pregnancy-safe agent (labetalol, nifedipine ER or α-methyldopa). The contraindication also covers patients <b>planning</b> pregnancy.<br><br><b>Educational objective:</b> If a patient becomes pregnant on an ACE inhibitor or ARB, switch promptly to labetalol, nifedipine ER or methyldopa. Fetal risk is greatest in the second and third trimesters.",
wrong={0:"Fetal harm is concentrated in the later trimesters, and early exposure does not mean certain harm. Switching is the answer.",
1:"Any dose of an ACE inhibitor remains contraindicated in pregnancy.",
2:"Adding labetalol while keeping lisinopril continues the contraindicated drug.",
3:"Stopping all treatment leaves chronic hypertension untreated, which carries its own risks for mother and baby."},
eli5="Her blood pressure pill can hurt a baby's kidneys, mainly later in pregnancy. At 7 weeks the best move is to calmly switch to a pregnancy-safe pill like labetalol right away."),
]
