# Pharmacologic Management of Hypertension (Scully) — Version 1, 18 items (4 with images)
Q = [
dict(img=None,
stem="A 72-year-old man is found to have a blood pressure of 170/92 mm Hg on three visits. Invasive hemodynamic studies performed for another reason show a normal cardiac output and an increased systemic vascular resistance. His renal function and plasma aldosterone, metanephrine, and thyroid-stimulating hormone concentrations are normal.{FIG}This patient's hypertension is best classified as which of the following types?",
choices=["Cardiac (pump-based)","Neuroendocrine (secondary)","Renal (volume-based)","Vascular (resistance-based)","White-coat"], key=3,
exp="Dr. Scully's four sources of high pressure:<br>• <b>Cardiac (pump)</b>: ↑ cardiac output, normal systemic vascular resistance (SVR). Tends to be younger patients.<br>• <b>Vascular</b>: normal cardiac output, <b>↑ SVR</b> from endothelial or smooth-muscle dysfunction. Tends to be the <b>ageing population</b>.<br>• <b>Renal (volume)</b>: Na⁺ and water retention → ↑ cardiac output and ↑ SVR.<br>• <b>Neuroendocrine (secondary)</b>: pheochromocytoma, primary hyperaldosteronism, hyperthyroidism. Treat the cause.<br>Most patients have a mix, but normal cardiac output with high SVR in a 72-year-old is the vascular pattern.<br><br><b>Educational objective:</b> Hypertension with normal cardiac output and raised systemic vascular resistance is the vascular type, typical of older patients.",
wrong={0:"Pump-based hypertension has a <b>raised</b> cardiac output with normal SVR and is typical of younger patients.",
1:"Neuroendocrine hypertension needs a hormone excess. His aldosterone, metanephrines and thyroid tests are normal.",
2:"Volume-based hypertension raises both cardiac output and SVR, and his renal function is normal.",
4:"White-coat hypertension is high only in the office. His pressure is sustained, with measurable raised resistance."},
eli5="His heart is pumping a normal amount, but his arteries have become stiff and narrow, like squeezing a garden hose. That kind of blood pressure problem is common in older people."),

dict(img=None,
stem="A 58-year-old woman begins amlodipine for stage 1 hypertension. Her physician schedules a follow-up visit in 2 to 4 weeks and tells her the full effect may take time as her body \"gets used to\" a lower pressure.{FIG}Which of the following best explains why blood pressure control improves over the first several weeks of treatment?",
choices=["Amlodipine accumulates to steady state over months","Baroreceptors gradually reset to a lower set point","Plasma volume expands to offset vasodilation","Tolerance develops to the drug's effect","Vascular smooth muscle cells undergo apoptosis"], key=1,
exp="<b>Baroreceptors reset</b> to whatever pressure is held long enough, so a hypertensive patient's reflexes defend the <b>high</b> pressure as \"normal.\" When a drug lowers BP, the baroreflex and the renin–angiotensin system initially push back. If the pressure is held low long enough, those compensations fade and the receptors reset lower. Hence Dr. Scully's \"see you in 2–4 weeks.\" Patients lost to follow-up in that window are one reason the guideline now starts two drugs.<br><br><b>Educational objective:</b> Baroreceptors reset to a sustained pressure. After an antihypertensive is started, compensation fades over weeks as the set point moves lower, which is why follow-up is at 2–4 weeks.",
wrong={0:"Amlodipine has a long half-life but reaches steady state in about a week or two. Drug accumulation is not the lecture's explanation.",
2:"Plasma volume expansion (RAAS activation) is a compensation that <b>opposes</b> the drug. It explains a blunted response, not improving control.",
3:"Tolerance would make control <b>worse</b> over time, not better.",
4:"Antihypertensives do not work by killing smooth muscle cells."},
eli5="The body's pressure sensors get used to whatever pressure they see for a long time. At first they fight a lower pressure as if something were wrong. After a few weeks they accept the new, lower level as normal."),

dict(img=None,
stem="A 55-year-old man with stage 2 hypertension is started on amlodipine alone. Two weeks later his blood pressure has fallen less than expected. His plasma renin activity has increased compared with baseline.{FIG}Adding a drug from which of the following classes would best counter this compensation?",
choices=["α1-adrenergic antagonist","Angiotensin-converting enzyme inhibitor","Central α2-adrenergic agonist","Loop diuretic","Non-dihydropyridine calcium channel blocker"], key=1,
exp="Lowering BP with one drug triggers two counter-moves (Dr. Scully's \"compensation undoes monotherapy\"):<br>• the <b>baroreflex</b> → ↑ sympathetic outflow (heart rate, contractility, vasoconstriction);<br>• ↓ renal perfusion → <b>↑ renin</b> → angiotensin II → aldosterone → Na⁺/water retention and thirst.<br>A rising renin means the RAAS branch is fighting back, so block it with an <b>ACE inhibitor (or ARB)</b>. Dihydropyridine CCB + ACEi/ARB is the <b>preferred single-pill combination</b>.<br><br><b>Educational objective:</b> Vasodilator monotherapy is blunted by RAAS activation (rising renin). Adding an ACE inhibitor or ARB complements a dihydropyridine CCB.",
wrong={0:"An α1 antagonist hits the sympathetic branch, not the renin surge, and it is not first-line (reserved for comorbid BPH).",
2:"A central α2 agonist (clonidine) lowers sympathetic outflow. It doesn't block renin–angiotensin, and it is not a first-line add-on.",
3:"A loop diuretic removes volume but would <b>further raise renin</b>, and it is not a first-line antihypertensive.",
4:"Adding verapamil or diltiazem stacks a second CCB mechanism. It doesn't address the RAAS compensation."},
eli5="When one drug lowers the pressure, the kidneys notice less blood flow and release renin to push the pressure back up. An ACE inhibitor blocks that renin pathway, so the two drugs work together."),

dict(img=None,
stem="A 60-year-old man has confirmed blood pressures averaging 152/96 mm Hg at home and in the office. He has no other medical conditions, takes no medications, and has never had a drug reaction. He is not frail.{FIG}According to the 2025 guideline, which of the following is the most appropriate initial pharmacotherapy?",
choices=["Amlodipine alone, recheck in 3–6 months","Amlodipine–olmesartan single pill","Hydrochlorothiazide alone","Lifestyle modification only for 6 months","Metoprolol–hydrochlorothiazide single pill"], key=1,
exp="BP 140–180/90–120 = <b>stage 2</b>. The algorithm asks: age over 75, underweight or frail, or multiple medication intolerances? <b>No</b> → <b>combination therapy, preferably a single pill</b>. The preferred pairing is a <b>dihydropyridine CCB + ACEi or ARB</b> (ACEi/ARB + thiazide is also acceptable). Single pills improve adherence, and >50% of patients who qualify for two drugs are still stuck on stepped-up monotherapy. Lifestyle changes are added for everyone.<br><br><b>Educational objective:</b> Stage 2 hypertension in a patient who is ≤75, not frail and without intolerances is started on two complementary first-line drugs, ideally a single pill such as a DHP CCB + ACEi/ARB.",
wrong={0:"Monotherapy in stage 2 is reserved for patients over 75, frail, or with multiple intolerances. The 3–6-month recheck belongs to low-risk stage 1.",
2:"A thiazide is first-line, but <b>alone</b> it is monotherapy, which is not the default for stage 2.",
3:"Lifestyle alone applies to elevated BP and <b>low-risk stage 1</b>, not stage 2.",
4:"β-blockers are not first-line for uncomplicated hypertension. The preferred combination is DHP CCB + ACEi/ARB."},
eli5="His pressure is high enough (stage 2) that one drug probably won't be enough. Guidelines start two complementary drugs combined in one pill, which is easier to remember to take."),

dict(img=None,
stem="A 45-year-old woman has confirmed blood pressures of 134/84 mm Hg. She has no diabetes, kidney disease, heart failure, or cardiovascular disease, and her 10-year atherosclerotic cardiovascular disease risk is 3%.{FIG}Which of the following is the most appropriate next step in management?",
choices=["Amlodipine–benazepril single pill","Hydrochlorothiazide 12.5 mg daily","Lifestyle changes, recheck in 3–6 months","Lisinopril 10 mg daily","Urgent evaluation for target-organ damage"], key=2,
exp="130–139/80–89 = <b>stage 1</b>. The algorithm asks: clinical ASCVD, heart failure, diabetes, CKD, age ≥65, or 10-year risk ≥<b>7.5%</b>? She has none (risk 3%) → <b>lifestyle modification</b> and a recheck in <b>3–6 months</b>. Start monotherapy only if BP is still over 130/80. Lifestyle measures (weight loss ~1 mmHg per kg, DASH diet, less sodium, more potassium, exercise, moderate alcohol) each lower BP 1–10 mmHg, or 10–20 together.<br><br><b>Educational objective:</b> Low-risk stage 1 hypertension (no ASCVD, HF, DM or CKD, age <65, risk <7.5%) is managed with lifestyle and a recheck in 3–6 months.",
wrong={0:"Single-pill combination therapy is for <b>stage 2</b> (or severe) hypertension.",
1:"Monotherapy in stage 1 needs a high-risk feature or failure of lifestyle changes at 3–6 months.",
3:"Same as above: an ACE inhibitor alone is monotherapy, reserved for high-risk stage 1.",
4:"Urgent assessment is for BP over 180/120."},
eli5="Her pressure is only mildly high and her overall heart risk is low. So she gets a few months to fix it with diet, exercise and less salt before any pills."),

dict(img=None,
stem="A 76-year-old man was started on lisinopril 2 weeks ago. His blood pressure is now 126/84 mm Hg, matching home readings. He reports a persistent, nonproductive, tickling cough that started a few days after the drug. Chest x-ray is normal, and testing for COVID-19 and other respiratory infections is negative.{FIG}Which of the following is the most appropriate change to his therapy?",
choices=["Add a codeine cough suppressant","Add hydrochlorothiazide","Increase the lisinopril dose","Switch lisinopril to enalapril","Switch lisinopril to losartan"], key=4,
exp="This is lecture Case 2. ACE is also <b>kininase II</b>. Blocking it lets <b>bradykinin accumulate</b> in the airways → dry cough. BP is well controlled by RAAS blockade, so keep that benefit with an <b>ARB</b> (losartan). ARBs antagonize the AT1 receptor without inhibiting ACE, so bradykinin is still degraded. Counsel him too: a cough on an ACE inhibitor flags the risk of <b>angioedema</b>, which nearly always follows a cough.<br><br><b>Educational objective:</b> ACE inhibitor cough is caused by bradykinin accumulation. Switch to an ARB, which blocks AT1 receptors without raising bradykinin.",
wrong={0:"Suppressing the cough ignores the cause and leaves him on the drug, with its angioedema warning sign.",
1:"Adding a diuretic doesn't stop the bradykinin cough, and his BP is already controlled.",
2:"A higher dose would <b>worsen</b> the bradykinin effect.",
3:"Enalapril is another ACE inhibitor, so it causes the same class effect."},
eli5="Lisinopril blocks an enzyme that also clears a cough-causing chemical, so the chemical builds up and he coughs. Losartan lowers pressure a similar way but leaves that enzyme alone, so the cough goes away."),

dict(img=None,
stem="A 64-year-old man with hypertension and cirrhosis needs an ACE inhibitor for albuminuria. His physician prefers an agent that is active as given and does not depend on hepatic conversion to an active metabolite.{FIG}Which of the following ACE inhibitors requires hepatic conversion to its active form and would therefore be the least suitable?",
choices=["Captopril","Enalapril","Lisinopril","Losartan","Valsartan"], key=1,
exp="Dr. Scully's ACE inhibitor pharmacokinetics:<br>• <b>Captopril</b>: active as given, plus an active metabolite.<br>• <b>Enalapril</b>: a <b>prodrug</b>, hydrolyzed in the liver to enalaprilat.<br>• <b>Lisinopril</b>: <b>active as given, excreted unchanged</b> in the urine.<br>So enalapril depends on hepatic activation, and lisinopril doesn't. For CKD with albuminuria, an ACEi or ARB is the comorbidity-directed choice.<br><br><b>Educational objective:</b> Enalapril is a prodrug activated in the liver. Lisinopril is active as given and excreted unchanged, and captopril is active with an active metabolite.",
wrong={0:"Captopril is <b>active as given</b> (it also has an active metabolite), so it doesn't need hepatic activation.",
2:"Lisinopril is active as given and cleared unchanged by the kidney, which makes it the natural choice here.",
3:"Losartan is an ARB, not an ACE inhibitor, so it doesn't answer the question asked.",
4:"Valsartan is an ARB, not an ACE inhibitor."},
eli5="Some pills have to be switched on by the liver before they work. Enalapril is one of those, so a damaged liver may not activate it properly. Lisinopril works straight away and leaves through the kidneys unchanged."),

dict(img=None,
stem="A 54-year-old woman began lisinopril 3 weeks ago. She comes to the emergency department because of painless swelling of her lips and tongue that began 2 hours ago. She has no hives or itching. For the past 2 weeks she has had a dry cough. She has no history of allergies.{FIG}Which of the following best explains this reaction?",
choices=["Accumulation of bradykinin in tissues","Complement C1-inhibitor gene mutation","Histamine release from mast cells","IgE-mediated hypersensitivity to the drug","Increased angiotensin II activity"], key=0,
exp="<b>ACE inhibitor angioedema</b>: ACE (kininase II) normally inactivates bradykinin. Blocking it → <b>bradykinin accumulates</b> → vasodilation and capillary leak → non-pitting swelling of the lips, tongue, face, or larynx. It is <b>not</b> histamine- or IgE-mediated (no hives or itching), so antihistamines and epinephrine work poorly. Lecture pearls: a dry cough usually comes first. The risk is ~<b>5× higher in Black patients</b>. Recurrence is possible up to 2 years after stopping, and a history of angioedema is a <b>contraindication</b> to ACE inhibitors. Early laryngeal signs are hoarseness and stridor.<br><br><b>Educational objective:</b> ACE inhibitor angioedema is bradykinin-mediated (not histaminergic) and is often heralded by a dry cough.",
wrong={1:"Hereditary angioedema from C1-inhibitor deficiency also raises bradykinin, but it causes recurrent attacks from childhood, not new swelling after a new drug.",
2:"Histamine-mediated swelling comes with <b>urticaria and itching</b>, which she doesn't have.",
3:"An IgE-mediated allergy would cause hives, itching and possibly anaphylaxis, usually soon after a first dose. This is non-allergic.",
4:"ACE inhibitors <b>decrease</b> angiotensin II."},
eli5="Lisinopril blocks the enzyme that breaks down bradykinin, a chemical that makes blood vessels leaky. Bradykinin builds up and fluid leaks into her lips and tongue. The cough she had earlier was an early warning from the same chemical."),

dict(img='Apeakt', cap='12-lead ECG',
stem="A 70-year-old man with hypertension and chronic kidney disease comes to the emergency department because of muscle weakness for 2 days. He takes lisinopril prescribed by his primary care physician, and a nephrologist recently added losartan \"for his kidneys.\" His ECG is shown.{FIG}Which of the following best explains this patient's condition?",
choices=["Decreased aldosterone-driven potassium secretion","Increased insulin-driven potassium shift into cells","Increased renal sodium–potassium exchange","Metabolic alkalosis shifting potassium out of cells","Potassium leak from bradykinin-injured cells"], key=0,
exp="The ECG shows tall, narrow, <b>peaked T waves</b>, the earliest sign of <b>hyperkalemia</b>. Two prescribers stacked an <b>ACE inhibitor + ARB</b>, which is <b>double RAAS blockade</b>. Less angiotensin II → <b>less aldosterone</b> → fewer Na⁺ channels and K⁺ channels in the principal cells → <b>less K⁺ secretion</b> → potassium rises, worse with CKD. Dr. Scully's \"combinations to avoid\": <b>never give two RAAS blockers</b> (ACEi + ARB, or either + aliskiren), because of hyperkalemia, renal impairment and hypotension.<br><br><b>Educational objective:</b> Combining an ACE inhibitor with an ARB causes hyperkalemia by reducing aldosterone-driven potassium secretion. Never combine two RAAS blockers.",
wrong={1:"Insulin moves potassium <b>into</b> cells and lowers serum potassium. It's a treatment for hyperkalemia.",
2:"More distal Na⁺/K⁺ exchange (as with aldosterone excess or loop/thiazide diuretics) <b>lowers</b> potassium.",
3:"Alkalosis shifts potassium <b>into</b> cells, causing hypokalemia. Acidosis shifts it out.",
4:"Bradykinin causes cough and angioedema, not potassium release from cells, and ARBs don't raise bradykinin."},
eli5="Two different doctors each gave him a drug that blocks the same hormone system. Together they switched off aldosterone, the hormone that tells the kidney to get rid of potassium. Potassium built up, which made the T waves tall and pointy."),

dict(img='Aedema', cap='Lower leg; pressure applied (top right) leaves an indentation (bottom right)',
stem="A 62-year-old woman comes to the office because of swelling of both ankles for 1 month. Six weeks ago she began a new antihypertensive medication. Her blood pressure is 128/80 mm Hg and pulse is 84/min. Jugular venous pressure is normal, the lungs are clear, and serum albumin and creatinine concentrations are normal. The finding in her legs is shown.{FIG}Which of the following best explains this finding?",
choices=["Arteriolar dilation raising capillary pressure","Hypoalbuminemia from urinary protein loss","Lymphatic obstruction from drug-induced fibrosis","Sodium retention from increased aldosterone","Venous congestion from right-sided heart failure"], key=0,
exp="New bilateral pitting ankle edema after starting an antihypertensive, with normal neck veins, lungs, albumin and kidneys, is the classic <b>dihydropyridine CCB</b> (amlodipine, nifedipine) adverse effect. It is the first-line class that causes <b>peripheral edema</b>.<br><br>Mechanism: DHPs dilate the <b>pre-capillary arterioles</b> far more than the veins → more pressure reaches the capillary bed → <b>↑ transcapillary hydrostatic pressure</b> → fluid leaks into the tissue. It's <b>not</b> volume overload, so diuretics help little. Adding an ACEi or ARB (which also dilate veins) reduces it, which is a board add-on.<br><br><b>Educational objective:</b> Dihydropyridine CCB edema results from preferential arteriolar dilation raising capillary hydrostatic pressure. It is not fluid overload.",
wrong={1:"Nephrotic-range protein loss lowers oncotic pressure, but her albumin is normal.",
2:"No antihypertensive causes lymphatic fibrosis, and lymphedema is usually non-pitting and chronic.",
3:"Aldosterone-driven sodium retention would raise volume, often with raised neck veins. This edema is local, and the circulation isn't overloaded.",
4:"Right heart failure would raise the jugular venous pressure. Hers is normal."},
eli5="Her new pill (likely amlodipine) opens up the small arteries feeding her ankles more than the veins draining them. Extra pressure builds in the tiny vessels and fluid seeps out, so her ankles swell. She doesn't have too much fluid overall."),

dict(img=None,
stem="A 68-year-old man with atrial fibrillation takes metoprolol for rate control and apixaban. His heart rate is 72/min, but his blood pressure is consistently 148/92 mm Hg. He has no other conditions.{FIG}Which of the following is the most appropriate drug to add for his blood pressure?",
choices=["Amlodipine","Clonidine","Diltiazem","Prazosin","Verapamil"], key=0,
exp="Dr. Scully's combinations to avoid:<br>• <b>β-blocker + non-dihydropyridine CCB</b> (verapamil, diltiazem) → additive depression of the SA/AV nodes and contractility (bradycardia, heart block, acute heart failure). IV-push verapamil on a β-blocker can cause <b>electromechanical decoupling</b>.<br>• <b>Two sympatholytics</b> (β-blocker + clonidine, or α1 antagonist + β-blocker) → only one branch of BP control is hit, and the side effects stack.<br>So add a class that works on a different branch: a <b>dihydropyridine CCB</b> (amlodipine), or an ACEi/ARB or thiazide.<br><br><b>Educational objective:</b> In a patient on a β-blocker, add a dihydropyridine CCB (or ACEi/ARB or thiazide). Avoid verapamil or diltiazem and a second sympatholytic.",
wrong={1:"Clonidine plus a β-blocker is two sympatholytics. Side effects stack, and stopping clonidine can cause rebound hypertension.",
2:"Diltiazem is great for AF with hypertension <b>on its own</b>, but combined with metoprolol it risks bradycardia and heart block.",
3:"Prazosin is a sympatholytic reserved for BPH. Paired with a β-blocker it stacks sympatholytic effects.",
4:"Verapamil is the most cardioselective CCB, the riskiest partner for a β-blocker."},
eli5="Metoprolol already slows his heart. Verapamil or diltiazem would slow it even more and could stop it beating properly. Amlodipine works on the blood vessels instead, so it lowers pressure without adding more brakes to the heart."),

dict(img=None,
stem="A 50-year-old man is started on a calcium channel blocker for hypertension. Within an hour of the first dose he notices a pounding heartbeat, flushing, and a headache. His pulse has risen from 76/min to 108/min.{FIG}Which of the following drugs most likely caused these effects?",
choices=["Diltiazem","Immediate-release nifedipine","Nimodipine","Sustained-release amlodipine","Verapamil"], key=1,
exp="Reflex tachycardia is highest with <b>nifedipine</b>, especially immediate-release. Its strong <b>vessel selectivity</b> drops SVR fast → the baroreflex fires → sympathetic tachycardia, flushing and headache. There is no nodal blockade to blunt it. The CCB spectrum (Dr. Scully): <b>verapamil</b> (heart: nodes, conduction, contractility) → <b>diltiazem</b> (both: the \"sweet spot\") → <b>-dipines</b> (vessels). Immediate-release nifedipine is reserved for severe acute BP in hospital settings.<br><br><b>Educational objective:</b> Immediate-release nifedipine causes the most reflex tachycardia, because a rapid, vessel-selective drop in SVR triggers the baroreflex without nodal blockade.",
wrong={0:"Diltiazem slows the SA and AV nodes, which blunts reflex tachycardia.",
2:"Nimodipine is a DHP used for subarachnoid hemorrhage vasospasm, not hypertension, and it isn't the classic reflex-tachycardia drug.",
3:"Amlodipine is a DHP, but its slow onset and long half-life lower BP gradually, so reflex tachycardia is much milder.",
4:"Verapamil is the most cardioselective CCB. It <b>slows</b> the heart rate."},
eli5="Fast-acting nifedipine opens the blood vessels very quickly, so blood pressure drops suddenly. The body panics and speeds up the heart to compensate. That causes the pounding heart, flushing and headache."),

dict(img=None,
stem="A 58-year-old woman with hypertension has had two episodes of calcium oxalate kidney stones in the past 3 years, and a bone density scan shows osteopenia. Her 24-hour urine calcium excretion is increased.{FIG}The most appropriate antihypertensive for this patient lowers urinary calcium by which of the following mechanisms?",
choices=["Blocking aldosterone at the mineralocorticoid receptor","Blocking the Na⁺–Cl⁻ cotransporter in the distal tubule","Blocking the Na⁺–K⁺–2Cl⁻ cotransporter in the thick ascending limb","Blocking the epithelial sodium channel in the collecting duct","Inhibiting carbonic anhydrase in the proximal tubule"], key=1,
exp="Comorbidity picks the drug: osteoporosis, edema, or <b>calcium stones with hypercalciuria → thiazide</b>. Hydrochlorothiazide blocks the <b>Na⁺–Cl⁻ cotransporter (NCC)</b> on the luminal side of the <b>distal convoluted tubule</b> → less Na⁺ enters the cell → a steeper gradient for the basolateral Na⁺/Ca²⁺ exchanger → <b>↑ Ca²⁺ reabsorption</b> → less calcium in the urine (fewer stones) and more for bone. One drug treats all three problems.<br><br><b>Educational objective:</b> Thiazides block NCC in the distal convoluted tubule, increasing calcium reabsorption, so they suit hypertension with calcium stones or osteoporosis.",
wrong={0:"Mineralocorticoid receptor antagonists (spironolactone) act in the collecting duct and don't meaningfully reduce urinary calcium.",
2:"Blocking NKCC2 (loop diuretics) <b>increases</b> urinary calcium, which would worsen stones.",
3:"ENaC blockers (amiloride) spare potassium but are not the calcium-sparing antihypertensive of choice.",
4:"Carbonic anhydrase inhibitors alkalinize the urine and <b>promote</b> calcium phosphate stones."},
eli5="Thiazides block a salt channel in part of the kidney tubule, and that makes the same cells pull more calcium back into the blood. Less calcium in the urine means fewer stones, and more stays in the bones. So one pill helps her blood pressure, stones and bones."),

dict(img='Agout', cap='Feet of the patient',
stem="A 66-year-old man with hypertension comes to the office because of an exquisitely painful, red, swollen great toe that began overnight. He has had similar attacks over the past year and now has firm, chalky nodules over several joints of his feet. His antihypertensive regimen was changed 18 months ago. Serum uric acid concentration is 10.4 mg/dL.{FIG}Which of the following drugs most likely contributed to this patient's condition?",
choices=["Amlodipine","Hydrochlorothiazide","Labetalol","Lisinopril","Losartan"], key=1,
exp="The photo shows <b>gouty tophi</b> (chalky urate deposits) with an acute flare of the first toe joint. <b>Thiazide diuretics</b> cause <b>hyperuricemia</b>: volume contraction raises proximal urate reabsorption, and thiazides compete with urate for tubular secretion → gout.<br><br>Thiazide adverse effects (\"hyperGLUC\", a board add-on): hyper-Glycemia, hyper-Lipidemia, hyper-Uricemia, hyper-Calcemia, plus hyponatremia, hypokalemic metabolic alkalosis and photosensitivity. In the lecture's Case 4, \"on a diuretic, watch for\" gout.<br><br><b>Educational objective:</b> Thiazide diuretics cause hyperuricemia and can precipitate gout, one of the \"hyperGLUC\" adverse effects.",
wrong={0:"Amlodipine causes edema, flushing and reflex tachycardia, not hyperuricemia.",
2:"Labetalol's adverse effects are bronchoconstriction and bradycardia.",
3:"ACE inhibitors cause cough, angioedema and hyperkalemia. They don't raise uric acid.",
4:"Losartan actually has a mild <b>uricosuric</b> (urate-lowering) effect, which is a board add-on."},
eli5="His water pill makes the kidneys hold onto uric acid, so it builds up in his blood. Uric acid crystals settle in his joints, causing painful gout attacks and chalky lumps."),

dict(img=None,
stem="A 59-year-old man with resistant hypertension was started on a potassium-sparing diuretic 4 months ago. He now reports tender enlargement of both breasts and decreased libido. His serum potassium is 4.9 mEq/L.{FIG}Switching to which of the following would most likely resolve his new symptoms while keeping the same mechanism of action?",
choices=["Amiloride","Eplerenone","Furosemide","Hydrochlorothiazide","Triamterene"], key=1,
exp="Gynecomastia and impotence on a potassium-sparing diuretic point to <b>spironolactone</b>. Besides blocking the mineralocorticoid receptor (MR), it <b>blocks androgen receptors</b> and shifts testosterone to estradiol (↑ testosterone clearance, ↑ estradiol). Hence gynecomastia, impotence and menstrual changes. <b>Eplerenone</b> is a <b>more MR-selective</b> antagonist with little anti-androgen effect (a board add-on). It keeps the same mechanism: it binds the MR and prevents its nuclear translocation, so fewer Na⁺ channels are made.<br><br><b>Educational objective:</b> Spironolactone causes gynecomastia through anti-androgen effects. Eplerenone is a more selective mineralocorticoid receptor antagonist that avoids them.",
wrong={0:"Amiloride is potassium-sparing but blocks <b>ENaC</b> directly. That is a different mechanism from MR antagonism.",
2:"Furosemide is a loop diuretic that wastes potassium, which is a different mechanism entirely.",
3:"Hydrochlorothiazide blocks NCC and wastes potassium, which is a different mechanism.",
4:"Triamterene, like amiloride, blocks ENaC rather than the mineralocorticoid receptor."},
eli5="Spironolactone blocks the salt hormone, but it also blocks male hormones, which made his breasts grow. Eplerenone blocks the salt hormone much more precisely and leaves male hormones alone. So it keeps the benefit without that side effect."),

dict(img=None,
stem="A 27-year-old woman comes for a prenatal visit at 16 weeks' gestation. At her first prenatal visit her blood pressure was 158/110 mm Hg; today it is 160/114 mm Hg on two readings 4 hours apart. She has no headache, visual changes, or proteinuria. She takes a prenatal vitamin only.{FIG}Which of the following is the most appropriate pharmacotherapy?",
choices=["Atenolol","Labetalol","Lisinopril","Losartan","Spironolactone"], key=1,
exp="This is lecture Case 3, and the one-word trap is <b>\"pregnant\"</b>. BP ≥160/110 is severe-range, and hypertension before 20 weeks is <b>chronic hypertension</b>. Watch for superimposed preeclampsia.<br><br><b>Use</b>: <b>labetalol</b>, nifedipine ER, α-methyldopa (hydralazine only for acute management).<br><b>Avoid</b>: ACEi, ARBs, aliskiren (fetal renal toxicity → oligohydramnios), nitroprusside, spironolactone (anti-androgenic), and atenolol (low birth weight, growth restriction).<br><br><b>Educational objective:</b> Treat hypertension in pregnancy with labetalol, nifedipine ER or α-methyldopa. ACE inhibitors, ARBs, aliskiren, spironolactone, atenolol and nitroprusside are contraindicated.",
wrong={0:"Atenolol is associated with low birth weight and fetal growth restriction.",
2:"ACE inhibitors are contraindicated in pregnancy (fetal renal toxicity, oligohydramnios, worst in the 2nd–3rd trimesters).",
3:"ARBs carry the same fetal renal toxicity as ACE inhibitors.",
4:"Spironolactone is anti-androgenic and contraindicated in pregnancy."},
eli5="She's pregnant, so many usual blood pressure pills could harm the baby, especially the ones that block angiotensin. Labetalol is a safe, well-studied choice that lowers her pressure while keeping blood flowing to the placenta."),

dict(img=None,
stem="A 30-year-old woman at 24 weeks' gestation has chronic hypertension. Her obstetrician chooses labetalol rather than metoprolol.{FIG}Which of the following properties of labetalol best explains this choice?",
choices=["α1 blockade preserving placental blood flow","Central α2 agonism reducing sympathetic outflow","Direct arteriolar dilation via nitric oxide release","Greater β1 selectivity, sparing the airways","Inhibition of the renin–angiotensin system"], key=0,
exp="Labetalol is a 3rd-generation β-blocker that blocks <b>β1, β2 and α1</b> receptors. Blocking β1 alone (metoprolol) lowers cardiac output → the body responds with <b>sympathetic vasoconstriction</b>, including of the placental bed → less placental flow. Labetalol's <b>α1 blockade prevents that reflex vasoconstriction</b>, so BP falls while <b>placental blood flow is preserved</b>. Cautions (ACOG): bronchoconstriction (avoid in asthma), decompensated heart failure, heart block and bradycardia.<br><br><b>Educational objective:</b> Labetalol is preferred in pregnancy because its α1 blockade prevents the reflex vasoconstriction that β1 blockade alone would cause, preserving placental perfusion.",
wrong={1:"Central α2 agonism is how <b>α-methyldopa</b> works, which is another pregnancy option but not labetalol's mechanism.",
2:"Labetalol doesn't release nitric oxide. Hydralazine is the direct arteriolar dilator used acutely.",
3:"Labetalol is <b>non-selective</b> for β receptors (it blocks β2 too), which is why it can cause bronchoconstriction.",
4:"Inhibiting the renin–angiotensin system is contraindicated in pregnancy."},
eli5="Most beta-blockers lower pressure, but the body answers by squeezing blood vessels, including the ones feeding the placenta. Labetalol also blocks that squeezing signal, so the baby's blood supply stays open."),

dict(img='Aretino', cap='Funduscopic examination of the right eye',
stem="A 52-year-old man is brought to the emergency department because of severe headache and blurred vision for 1 day. He stopped taking his antihypertensive medications 3 months ago. His blood pressure is 224/132 mm Hg in both arms. He is mildly confused. Serum creatinine concentration has risen from 1.0 to 2.3 mg/dL, and urinalysis shows proteinuria and red blood cells. Funduscopic examination is shown.{FIG}Which of the following is the most appropriate management?",
choices=["Admission for intravenous antihypertensive therapy","Oral amlodipine–olmesartan and follow-up in 1 week","Oral hydrochlorothiazide and recheck in 2–4 weeks","Oral lisinopril, recheck in 3–6 months","Reassurance and lifestyle counseling"], key=0,
exp="The fundus shows <b>optic disc swelling (papilledema)</b> with flame hemorrhages and exudates: severe (grade IV) hypertensive retinopathy. With BP over 180/120, confusion (encephalopathy) and an acute kidney injury, there is <b>acute target-organ damage</b> = a <b>hypertensive emergency</b>.<br><br>The algorithm's severe branch: SBP >180 and/or DBP >120 → urgent assessment for acute target-organ damage. <b>Yes → emergency, inpatient care</b> (IV agents, a controlled reduction). No → combination therapy. Lower BP in steps, not all at once: chronic hypertension shifts the autoregulation curve right, so a rapid drop can cause ischemia of the brain and kidneys.<br><br><b>Educational objective:</b> BP over 180/120 with acute target-organ damage (papilledema, encephalopathy, acute kidney injury) is a hypertensive emergency needing inpatient parenteral therapy.",
wrong={1:"Outpatient combination therapy is right for severe BP <b>without</b> acute target-organ damage. He has encephalopathy, papilledema and acute kidney injury.",
2:"Oral monotherapy with delayed follow-up is far too slow for an emergency.",
3:"A 3–6-month recheck is the low-risk stage 1 pathway.",
4:"Reassurance ignores life-threatening target-organ damage."},
eli5="His pressure is so high it's damaging his eyes, brain and kidneys right now. That's an emergency, so he needs the hospital and IV medicine. Doctors lower the pressure carefully, not all at once."),
]
