# Application Session 2 (Segal/Scully/Qazi HF cases + Segal PAD case) — Version 2, 18 items (5 with images). NBME house style (2026-10-07).
Q = [
dict(img=None,
stem="A 28-year-old woman comes to the office because of a 2-month history of episodes of a racing heartbeat, breathlessness on climbing stairs and feeling anxious. She has lost 5 kg (11 lb) without trying and has had loose stools. She was told at an urgent care visit that she was having panic attacks. Her pulse is 112/min and regular, and blood pressure is 138/62 mm Hg. Her skin is warm and moist, and there is a fine tremor of the outstretched hands. Lungs are clear to auscultation. There is no edema. Hemoglobin concentration is 13.4 g/dL.{FIG}Which of the following tests is most likely to establish the underlying cause of her symptoms?",
choices=["24-hour Holter monitoring","D-dimer","Plasma free metanephrines","Serum thyroid-stimulating hormone","Transthoracic echocardiography"], key=3,
exp="Weight loss, loose stools, warm moist skin, tremor, wide pulse pressure and resting tachycardia → <b>hyperthyroidism</b> → <b>TSH</b>. Dr. Segal (dyspnea buckets): anxiety is real, but <b>rule out the serious, organic causes first</b> (arrhythmia, <b>thyroid</b>, anemia) before labeling it panic. Her normal hemoglobin excludes anemia.<br><br><b>Educational objective:</b> Before diagnosing anxiety or panic in a patient with palpitations and dyspnea, exclude organic causes such as hyperthyroidism.",
wrong={0:"Would be correct for intermittent palpitations with a normal exam, to catch a paroxysmal arrhythmia.",
1:"Would be correct for suspected PE with pleuritic pain, hypoxemia or leg swelling.",
2:"Would be correct for paroxysms of headache, sweating and hypertension (pheochromocytoma), without weight loss and loose stools.",
4:"Would be correct for suspected structural heart disease or HF (edema, murmur, S3)."},
eli5="Weight loss, a shaky hand, sweaty warm skin and a fast heart point to an overactive thyroid. Check the thyroid blood test before blaming nerves."),

dict(img='A2psax', cap='Transthoracic echocardiogram, parasternal short-axis view',
stem="A 64-year-old woman with obesity, type 2 diabetes mellitus and long-standing hypertension comes to the office because of a 2-month history of dyspnea on exertion and ankle swelling. Her blood pressure is 158/88 mm Hg. Plasma NT-proBNP is elevated. An echocardiogram is shown; the left ventricular ejection fraction is 63%, and grade II (pseudonormal) diastolic dysfunction with left atrial enlargement is reported. Echocardiograms over the past 5 years have never shown an ejection fraction below 55%.{FIG}Which of the following is the most likely diagnosis?",
choices=["Heart failure with improved ejection fraction","Heart failure with mildly reduced ejection fraction","Heart failure with preserved ejection fraction","Heart failure with reduced ejection fraction","High-output heart failure"], key=2,
exp="Symptoms and signs of HF + elevated NT-proBNP + <b>EF ≥ 50% (63%)</b> + evidence of ↑ filling pressure (grade II diastolic dysfunction, LA enlargement) + concentric LVH (thick walls, small cavity) → <b>HFpEF</b>. EF categories: HFrEF ≤ 40, HFmrEF 41–49, <b>HFpEF ≥ 50</b>, HFimpEF = prior ≤ 40 now &gt; 40. Her risk profile (HTN, diabetes, obesity, older woman) is the classic HFpEF phenotype.<br><br><b>Educational objective:</b> HF with EF ≥ 50% and evidence of raised filling pressures is HFpEF.",
wrong={0:"Would be correct if a prior EF had been ≤ 40% and was now > 40%.",
1:"Would be correct for an EF of 41–49%.",
3:"Would be correct for an EF ≤ 40% with a dilated, poorly contracting ventricle.",
4:"Would be correct with ↑ CO and ↓ SVR (AV fistula, thyrotoxicosis, beriberi)."},
eli5="Her heart squeezes normally but its thick wall won't relax and fill, so pressure backs up. That's heart failure with a normal pumping number."),

dict(img=None,
stem="An 81-year-old woman is brought to the emergency department because of 1 day of increased shortness of breath. Natriuretic peptide testing is ordered to help determine whether acute heart failure is present. Her estimated GFR is 72 mL/min/1.73 m2. Plasma NT-proBNP is 1,400 pg/mL.{FIG}Which of the following is the age-appropriate NT-proBNP threshold above which acute heart failure is considered likely in this patient?",
choices=["300 pg/mL","450 pg/mL","900 pg/mL","1,800 pg/mL"], key=3,
exp="NT-proBNP (lecture table): <b>rule out ≤ 300 pg/mL</b> at any age; <b>rule in</b> is age-specific: <b>&lt; 50 y: 450 · 50–75 y: 900 · &gt; 75 y: 1,800 pg/mL</b>. Her 1,400 sits in the grey zone for an 81-year-old (above rule-out, below rule-in). BNP: rule out ≤ 100, rule in &gt; 400. NT-proBNP has a longer half-life (1–2 h vs 20 min) and rises more in CKD.<br><br><b>Educational objective:</b> NT-proBNP rule-in thresholds rise with age: 450 (< 50), 900 (50–75), 1,800 (> 75 years).",
wrong={0:"Would be correct for the <b>rule-out</b> threshold at any age.",
1:"Would be correct for a patient younger than 50.",
2:"Would be correct for a patient aged 50–75."},
eli5="Older people naturally have higher levels of this heart-strain marker, so the cut-off for calling it heart failure goes up with age."),

dict(img=None,
stem="A 78-year-old woman with well-controlled hypertension undergoes echocardiography before cataract surgery. She has no dyspnea and walks 2 miles daily. The report states: left ventricular ejection fraction 62%, normal wall thickness, left atrial volume index normal, grade I diastolic dysfunction (impaired relaxation pattern), estimated pulmonary artery systolic pressure 24 mm Hg. Plasma NT-proBNP is 140 pg/mL.{FIG}Which of the following is the most accurate interpretation of the diastolic function finding?",
choices=["Age-related impaired relaxation with normal LA pressure","Constrictive physiology from pericardial thickening","Pseudonormal filling indicating elevated LA pressure","Restrictive filling indicating very high LA pressure"], key=0,
exp="Dr. Qazi: echo reports grade diastolic function as normal or <b>grade 1, 2 or 3</b>. <b>Grade 1 (impaired relaxation) → LA pressure usually normal</b>, and in patients in their 70s–80s it is <b>a normal pattern for age</b>. <b>Grade 2 (pseudonormal) → LA pressure elevated.</b> Grade 3 (restrictive) → markedly elevated. Normal LA size, normal PASP and a low NT-proBNP all fit grade 1.<br><br><b>Educational objective:</b> Grade 1 diastolic dysfunction implies normal LA pressure and is common with normal aging.",
wrong={1:"Would be correct for constrictive pericarditis: a thick pericardium, septal bounce, respiratory variation and Kussmaul sign.",
2:"Would be correct for <b>grade II</b>, with LA enlargement and raised filling pressures.",
3:"Would be correct for <b>grade III</b>, with high filling pressures and usually symptomatic HF."},
eli5="With age the heart relaxes a bit more slowly, but here the pressure behind it is still normal, so it's an expected aging finding, not heart failure."),

dict(img=None,
stem="A 58-year-old man on hemodialysis for 6 years through a large left upper-arm arteriovenous fistula comes to the office because of a 3-month history of progressive dyspnea and leg swelling. His pulse is 104/min, and blood pressure is 146/52 mm Hg. A loud continuous bruit is heard over the fistula; manual compression of the fistula slows his pulse to 86/min. There are crackles at both lung bases and 2+ edema. Echocardiography shows a left ventricular ejection fraction of 60% with a dilated left ventricle.\n\nCardiac output | Systemic vascular resistance{FIG}Which of the following sets of hemodynamic findings is most likely?",
choices=["Decreased, decreased","Decreased, increased","Increased, decreased","Increased, increased"], key=2,
exp="A large AV fistula shunts blood past the high-resistance arterioles → <b>↓ SVR</b> → compensatory <b>↑ cardiac output</b> → <b>high-output heart failure</b>. Classic clue: <b>Branham (Nicoladoni) sign</b>, where compressing the fistula raises SVR and slows the HR. Lecture: high output = ↑ metabolic demand or shunt (thyrotoxicosis, AV fistula, severe obesity, beriberi), with ↑ CO and ↓ SVR. Low output = pump failure with ↑ SVR and ↓ CO.<br><br><b>Educational objective:</b> AV-fistula heart failure is high-output: increased cardiac output and decreased SVR.",
wrong={0:"Would be correct for late vasoplegic or neurogenic shock with bradycardia.",
1:"Would be correct for low-output (pump) failure or cardiogenic shock.",
3:"Would be correct for nothing typical; ↑ CO with ↑ SVR would mean exercise-like hypertension, not this shunt."},
eli5="His dialysis fistula is a shortcut for blood, so resistance drops and the heart has to pump much more blood every minute until it wears out."),

dict(img=None,
stem="Patient Information\nAge: 66 years · Gender: M · Site of Care: cardiology clinic\n\nHistory\nReason for Visit: swollen legs and abdomen\nHistory of Present Illness: 4 months of increasing ankle and abdominal swelling and early satiety; 3 years of orthopnea and exertional dyspnea\nPast Medical History: anterior myocardial infarction 5 years ago; left ventricular ejection fraction 25%\nMedications: furosemide, carvedilol, sacubitril/valsartan\nPsychosocial History: no alcohol; never smoked\n\nPhysical Examination\nP 88/min · BP 104/66 mm Hg · R 18/min\nNeck: JVP 15 cm H₂O; positive hepatojugular reflux\nAbdomen: tender hepatomegaly; shifting dullness\nExtremities: 3+ edema\n\nDiagnostic Studies\nRight heart catheterization: pulmonary capillary wedge pressure 28 mm Hg; pulmonary artery pressure 58/30 mm Hg\nCT pulmonary angiography 1 month ago: no emboli\n\nQuestion:{FIG}Which of the following is the most likely cause of this patient's right-sided heart failure?",
choices=["Chronic pulmonary thromboembolism","Left ventricular systolic failure","Primary pulmonary arterial hypertension","Right ventricular infarction","Tricuspid valve endocarditis"], key=1,
exp="Right-sided failure (↑ JVP, hepatomegaly, ascites, edema) in a patient with long-standing <b>left</b> HF (EF 25%, years of orthopnea) and a <b>high wedge pressure (28)</b> → post-capillary pulmonary HTN → RV failure. Lecture: <b>the most common cause of right-sided HF is left-sided HF</b> (backward failure).<br><br><b>Educational objective:</b> The most common cause of right heart failure is left heart failure.",
wrong={0:"Would be correct with a normal wedge pressure and chronic emboli on imaging; his CTPA is negative.",
2:"Would be correct for <b>pre-capillary</b> pulmonary HTN with a <b>normal</b> wedge pressure (≤ 15).",
3:"Would be correct for an acute inferior MI with hypotension, clear lungs and ↑ JVP.",
4:"Would be correct in injection drug use with fever, a TR murmur and septic emboli."},
eli5="His left heart has been weak for years, so pressure backed up into the lungs and then the right side gave out too. That's the most common way right-sided failure happens."),

dict(img=None,
stem="A 34-year-old woman with type 1 diabetes mellitus and heart failure is evaluated because of 2 days of nausea, vomiting and abdominal pain. Four weeks ago a new drug was added to her insulin regimen for her heart failure, and she reduced her insulin dose because her glucose readings fell. Her pulse is 108/min, respirations are 28/min, and blood pressure is 104/64 mm Hg. Serum studies show:\n\nGlucose: 196 mg/dL\nNa⁺: 136 mEq/L\nCl⁻: 100 mEq/L\nHCO₃⁻: 10 mEq/L\nβ-Hydroxybutyrate: 6.2 mmol/L (N<0.4)\n\nUrine glucose is 4+.{FIG}Which of the following drugs was most likely added?",
choices=["Dapagliflozin","Finerenone","Furosemide","Semaglutide","Spironolactone"], key=0,
exp="<b>Euglycemic DKA</b> (anion gap 26, ketosis, glucose &lt; 250) with marked <b>glucosuria</b> in type 1 diabetes → an <b>SGLT2 inhibitor</b>. Glucosuria lowers glucose and prompts insulin reduction → lipolysis and ketogenesis. Lecture: SGLT2i for everyone with HF <b>unless contraindicated</b>: pregnancy, <b>type 1 diabetes</b>, volume depletion or symptomatic hypotension, amputation risk, complicated UTI.<br><br><b>Educational objective:</b> SGLT2 inhibitors are avoided in type 1 diabetes because they can cause euglycemic DKA.",
wrong={1:"Would be correct for <b>hyperkalemia</b> (non-steroidal MRA), not ketoacidosis.",
2:"Would be correct for hypokalemic metabolic <b>alkalosis</b>, not ketoacidosis.",
3:"Would be correct for nausea, delayed gastric emptying, pancreatitis or gallstones; it doesn't cause glucosuria.",
4:"Would be correct for hyperkalemia or gynecomastia."},
eli5="This drug makes the kidneys spill sugar, so her sugar readings looked fine and she cut her insulin. Without enough insulin her body burned fat and made acid."),

dict(img=None,
stem="A 70-year-old man with heart failure with reduced ejection fraction is evaluated 10 days after spironolactone 25 mg daily was added to his regimen of sacubitril/valsartan, carvedilol, dapagliflozin and furosemide. He feels well. His pulse is 64/min, and blood pressure is 112/68 mm Hg. Serum potassium is 6.1 mEq/L (4.6 mEq/L before the change), and creatinine is 1.5 mg/dL (1.3 mg/dL before). An ECG shows peaked T waves without QRS widening. He takes no potassium supplements and uses no salt substitute.{FIG}Which of the following is the most appropriate change in management?",
choices=["Add potassium chloride","Discontinue dapagliflozin","Discontinue furosemide","Hold spironolactone","Switch carvedilol to metoprolol"], key=3,
exp="Hyperkalemia appearing after an <b>MRA</b> was added to an ARNI → hold or reduce the <b>MRA</b>, recheck K⁺ and creatinine, and treat acutely if needed. Lecture: with MRAs, \"<b>potassium is kind of the dangerous part</b>\"; watch SCr and K⁺ closely, especially alongside ARNI and SGLT2i. Start an MRA only if K⁺ ≤ 4.7–5.0 and eGFR ≥ 30. <span class=\"src-tag\">Board add-on</span> SGLT2 inhibitors modestly <b>reduce</b> hyperkalemia risk, so stopping them won't help.<br><br><b>Educational objective:</b> Hyperkalemia after starting an MRA in HFrEF is managed by holding or reducing the MRA.",
wrong={0:"Would be correct for <b>hypo</b>kalemia; it worsens hyperkalemia.",
1:"Would be correct for genital infections, volume depletion or ketoacidosis; it doesn't drive K⁺ up.",
2:"Would be correct for hypovolemia; stopping it would actually <b>raise</b> K⁺ further.",
4:"Would be correct for nothing: β-blocker choice doesn't explain an acute K⁺ rise after an MRA."},
eli5="The new spironolactone blocks the hormone that helps get rid of potassium, so potassium built up. Pause that pill and recheck."),

dict(img='Adcm', cap='Gross specimen, longitudinal section through the left ventricle',
stem="A 54-year-old man dies of refractory heart failure. He had consumed 12 to 15 standard drinks daily for 20 years. Coronary angiography 2 years ago showed no stenoses, and echocardiography showed a left ventricular ejection fraction of 20%. The heart at autopsy is shown.\n\nLeft ventricular wall thickness | Left ventricular cavity size{FIG}Which of the following sets of findings best describes this heart?",
choices=["Increased, decreased","Increased, normal","Normal or thin, increased","Normal, normal"], key=2,
exp="Chronic heavy alcohol use → <b>dilated cardiomyopathy</b> (no coronary disease, EF 20%): a markedly <b>dilated</b> LV with a <b>normal or thin wall</b> (eccentric remodeling). Lecture: alcohol damages the heart directly (oxidative stress, fibrosis, excitation–contraction coupling) and indirectly (↑ SNS, RAAS, HTN). Contrast <b>concentric LVH</b> (HTN, aortic stenosis): thick wall, normal cavity.<br><br><b>Educational objective:</b> Alcoholic cardiomyopathy produces a dilated LV with a normal or thin wall.",
wrong={0:"Would be correct for hypertrophic or restrictive physiology with a small cavity (HCM, amyloid).",
1:"Would be correct for <b>concentric</b> LVH from pressure overload (HTN, aortic stenosis).",
3:"Would be correct for a normal heart, which doesn't fit an EF of 20%."},
eli5="Years of heavy drinking poisoned the heart muscle until the main chamber stretched out like an overblown balloon with thin walls that can't squeeze well."),

dict(img=None,
stem="A 71-year-old woman with atrial fibrillation is brought to the emergency department 3 hours after the sudden onset of severe pain in the left leg. She stopped apixaban 10 days ago before a dental procedure and did not resume it. The left foot is pale and cold. Femoral pulse is present, but popliteal and pedal pulses are absent. Light-touch sensation in the toes is reduced; dorsiflexion strength is 4/5. The right leg is normal, and she had no previous leg symptoms with walking.{FIG}Which of the following is the most appropriate next step in management?",
choices=["Intravenous unfractionated heparin","Oral aspirin and cilostazol","Outpatient arterial duplex ultrasonography","Resume apixaban and reassess in 1 week","Supervised exercise therapy"], key=0,
exp="Sudden (&lt; 2 weeks) <b>pain, pallor, pulselessness, poikilothermia, paresthesia</b> with mild weakness, in AF off anticoagulation, with no prior claudication → <b>embolic acute limb ischemia</b>. Lecture: <b>\"time = tissue\"</b>: <b>IV unfractionated heparin at diagnosis</b>, <b>emergent vascular surgery</b> evaluation (embolectomy or thrombolysis), a careful sensory and motor exam, and a search for the embolic source. Motor loss signals a threatened limb.<br><br><b>Educational objective:</b> Acute limb ischemia is treated immediately with IV unfractionated heparin and emergent vascular evaluation.",
wrong={1:"Would be correct for chronic claudication without heart failure, not an acute threatened limb.",
2:"Would be correct for chronic, stable symptoms; this needs emergent imaging and intervention.",
3:"Would be correct for nothing here: oral anticoagulation is too slow for an ischemic limb.",
4:"Would be correct for stable intermittent claudication."},
eli5="A clot from her irregular heart shot down and blocked her leg artery. Start a fast blood thinner right away and get the vascular surgeon, because the leg is dying by the hour."),

dict(img='Acpe', cap='Chest x-ray, AP view, sitting',
stem="A 72-year-old woman with heart failure with reduced ejection fraction is brought to the emergency department because of a 3-day history of worsening orthopnea and a 4-kg (9-lb) weight gain after a salty holiday meal. Her pulse is 96/min, respirations are 26/min, and blood pressure is 148/88 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 89%. Her extremities are warm, capillary refill is brisk, and she is alert. Jugular venous pressure is 14 cm H2O, and there are crackles throughout both lung fields. Her chest x-ray is shown. Serum creatinine is at baseline, and lactate is 1.1 mmol/L.{FIG}In addition to supplemental oxygen, which of the following is the most appropriate initial pharmacotherapy?",
choices=["Intravenous dobutamine","Intravenous furosemide","Intravenous normal saline","Oral metoprolol uptitration","Thoracentesis-guided diuresis"], key=1,
exp="Congested (↑ JVP, crackles, interstitial and alveolar edema with cardiomegaly on x-ray) but <b>warm</b> (alert, warm extremities, brisk refill, normal lactate, adequate BP) → <b>wet and warm</b>, the most common profile → <b>IV loop diuretic</b> (± thiazide, or IV nitroglycerin when hypertensive), strict I/O, daily weights, Na⁺ restriction, monitoring of K⁺/Mg²⁺ and creatinine. Dr. Qazi: <b>reduce preload first</b>, then afterload.<br><br><b>Educational objective:</b> Wet-and-warm acute decompensated HF is treated first with an IV loop diuretic.",
wrong={0:"Would be correct for wet–<b>cold</b> (low perfusion: cool skin, confusion, rising lactate).",
2:"Would be correct for dry–cold hypovolemic hypoperfusion, not pulmonary edema.",
3:"Would be correct for nothing now: don't uptitrate β-blockers during decompensation (negative inotropy).",
4:"Would be correct for a large symptomatic effusion; diuresis comes first."},
eli5="She is full of fluid but her organs are still getting blood (wet but warm), so the first job is an IV water pill to drain the fluid."),

dict(img=None,
stem="An investigator studies left ventricular function in an anesthetized dog. Stroke volume is plotted against left ventricular end-diastolic pressure across a range of infused volumes, generating a Frank–Starling curve. A dobutamine infusion is then started together with an arterial vasodilator that lowers systemic vascular resistance by 30%, and the measurements are repeated.{FIG}Compared with baseline, the new curve is most likely shifted in which of the following directions?",
choices=["Downward and to the right","Upward and leftward from baseline","Along the same curve, to the left","Along the same curve, to the right"], key=1,
exp="Lecture (Starling curves): <b>venous return sets where on a curve</b> the heart sits; <b>afterload and inotropy set which curve</b>. <b>↑ Inotropy (dobutamine) + ↓ afterload (vasodilator)</b> → a higher stroke volume at any filling pressure → the curve shifts <b>up and to the left</b>. ↑ Afterload + ↓ inotropy (failing heart) → <b>down and to the right</b>. This is the logic of inotropes and afterload reduction in ADHF.<br><br><b>Educational objective:</b> More contractility and less afterload shift the Frank–Starling curve up and to the left.",
wrong={0:"Would be correct for ↑ afterload and/or ↓ contractility (failing heart, vasoconstriction).",
2:"Would be correct for ↓ preload alone (diuresis), moving down the same curve.",
3:"Would be correct for ↑ preload alone (volume infusion), moving up the same curve."},
eli5="Making the heart squeeze harder and easing the pressure it pumps against lets it push out more blood at every filling level, so the whole curve moves up."),

dict(img=None,
stem="A 62-year-old man with heart failure with reduced ejection fraction (ejection fraction 30%) comes for follow-up. He takes sacubitril/valsartan, metoprolol succinate 200 mg daily (the target dose), spironolactone and empagliflozin, and he still has NYHA class II–III symptoms. His pulse is 78/min and regular, and blood pressure is 118/72 mm Hg. An ECG shows sinus rhythm at 78/min with a QRS duration of 98 msec. Serum potassium is 4.3 mEq/L.{FIG}Which of the following is the most appropriate additional drug?",
choices=["Amiodarone","Digoxin","Diltiazem","Ivabradine","Metoprolol 300 mg daily"], key=3,
exp="HFrEF in <b>sinus rhythm with HR ≥ 70</b> despite the <b>maximal or target β-blocker</b> dose → <b>ivabradine</b>: blocks the <b>HCN (funny, I<sub>f</sub>) channel</b> in the SA node → ↓ HR without changing contractility, repolarization or BP (lecture pearls). It reduces HF hospitalization (SHIFT). It needs sinus rhythm (no effect in AF).<br><br><b>Educational objective:</b> Add ivabradine for HFrEF in sinus rhythm with HR ≥ 70 on a maximally tolerated β-blocker.",
wrong={0:"Would be correct for symptomatic ventricular arrhythmias or rhythm control of AF, not routine rate lowering.",
1:"Would be correct for persistent symptoms with AF or after other options, for symptoms only (no mortality benefit).",
2:"Would be correct for nothing in HFrEF: non-DHP CCBs are negatively inotropic and contraindicated.",
4:"Would be correct for nothing: he's already at the target dose."},
eli5="His β-blocker is maxed out but his heart rate is still a bit high, so add a pill that slows only the heart's pacemaker without weakening its squeeze."),

dict(img=None,
stem="A 58-year-old woman newly diagnosed with heart failure with reduced ejection fraction (ejection fraction 32%) is euvolemic at discharge. She has been taking metoprolol tartrate 25 mg twice daily for palpitations for 2 years. Her pulse is 82/min, and blood pressure is 124/76 mm Hg. Lungs are clear. She has no asthma or bradycardia.{FIG}Which of the following β-blockers is most appropriate to replace her current regimen?",
choices=["Atenolol","Esmolol","Labetalol","Metoprolol succinate","Propranolol"], key=3,
exp="Only <b>three β-blockers</b> have mortality evidence in HFrEF: <b>metoprolol succinate</b> (long-acting, once daily), <b>carvedilol</b> (β₁, β₂ + α₁) and <b>bisoprolol</b>. Lecture: <b>succinate</b> is the long-acting form; <b>tartrate</b> (short-acting, twice daily) lacks the outcome data. Start low and titrate once compensated.<br><br><b>Educational objective:</b> Use metoprolol succinate, carvedilol or bisoprolol, not metoprolol tartrate, for HFrEF.",
wrong={0:"Would be correct for rate control or HTN, but atenolol has no HFrEF mortality evidence.",
1:"Would be correct for acute IV rate control, not chronic therapy.",
2:"Would be correct for HTN in pregnancy or cocaine-related HTN; no HFrEF outcome data.",
4:"Would be correct for essential tremor, migraine or thyrotoxicosis; non-selective, no HFrEF data."},
eli5="Only a few β-blockers are proven to help weak hearts live longer, and the once-a-day long-acting metoprolol is one of them."),

dict(img='A2leriche', cap='Contrast-enhanced CT angiography of the abdomen and pelvis (coronal reconstruction)',
stem="A 58-year-old man comes to the office because of a 1-year history of aching in both buttocks and thighs after walking 1 block and erectile dysfunction for 8 months. He has smoked 1 pack of cigarettes daily for 40 years. Femoral pulses are diminished bilaterally, and popliteal and pedal pulses are faint. Ankle–brachial index is 0.62 on the right and 0.58 on the left. CT angiography is shown.{FIG}Arterial occlusion at which of the following sites best explains this patient's findings?",
choices=["Common femoral arteries","Infrarenal abdominal aorta","Popliteal arteries","Superficial femoral arteries","Tibial arteries"], key=1,
exp="<b>Leriche syndrome</b> (\"a great board question\"): <b>bilateral buttock/hip claudication + ↓ femoral pulses + erectile dysfunction</b> → <b>aortoiliac occlusion</b>. The CT shows the infrarenal aorta occluded just below the renal arteries, with collaterals reconstituting the external iliacs. Dr. Segal: ED, especially in a younger man, is a vascular sign. Location map: buttock/hip = aortoiliac; upper two-thirds of the calf = SFA; lower third = popliteal; foot = tibial.<br><br><b>Educational objective:</b> Buttock claudication, weak femoral pulses and erectile dysfunction localize to aortoiliac (infrarenal aortic) occlusion.",
wrong={0:"Would be correct for thigh and calf claudication with ↓ femoral pulses, but without the aortic occlusion or ED from internal iliac inflow loss.",
2:"Would be correct for lower-calf claudication with normal femoral pulses.",
3:"Would be correct for upper-calf claudication with normal femoral pulses (the most common site).",
4:"Would be correct for foot or ankle symptoms (often diabetes) with normal femoral and popliteal pulses."},
eli5="The main artery splitting toward both legs is blocked just below the kidneys, so both buttocks hurt, the groin pulses are weak, and blood flow for erections drops."),

dict(img='Agangrene', cap='Both feet',
stem="A 74-year-old man with a 30-year history of type 2 diabetes mellitus, end-stage kidney disease on hemodialysis and a 45-pack-year smoking history comes to the office because of a 6-week history of foot pain at night and blackened toes. His feet are shown. Pedal pulses are not palpable. Resting ankle–brachial index is 1.55 on the right and 1.62 on the left, and the arteries at the ankle cannot be compressed by the cuff.{FIG}Which of the following is the most appropriate next step in noninvasive diagnosis?",
choices=["Exercise treadmill ankle–brachial index","Repeat resting ankle–brachial index in 3 months","Segmental limb pressures at the thigh","Toe–brachial index with arterial waveforms"], key=3,
exp="An ABI <b>&gt; 1.40</b> = <b>non-compressible, calcified tibial arteries</b> (diabetes, ESKD), so it can't exclude PAD, even with obvious <b>CLTI</b> (≥ 2 weeks of rest pain plus gangrene). Next: <b>toe–brachial index</b> (digital arteries are usually spared; abnormal ≤ 0.70) ± waveforms or TcPO₂, then anatomic imaging if revascularization is considered. Lecture: ABI ≤ 0.90 abnormal · 0.91–0.99 borderline → exercise ABI · 1.00–1.40 normal · &gt; 1.40 → TBI.<br><br><b>Educational objective:</b> With non-compressible vessels (ABI > 1.40), use the toe–brachial index to assess PAD.",
wrong={0:"Would be correct for <b>borderline or normal</b> ABI with typical claudication; he has rest pain and gangrene, and the cuff readings are invalid.",
1:"Would be correct for nothing: the values are falsely high and the limb is threatened.",
2:"Would be correct for localizing disease when vessels are compressible; calcification invalidates pressure cuffs."},
eli5="His leg arteries are so stiff with calcium that the ankle cuff can't squeeze them, giving a falsely normal number. Toe arteries usually stay soft, so measure there."),

dict(img=None,
stem="A 67-year-old woman with symptomatic peripheral artery disease (intermittent claudication, ankle–brachial index 0.71) and stable coronary artery disease takes atorvastatin 80 mg, lisinopril and aspirin 81 mg. She has no history of bleeding, stroke or kidney disease. Her physician adds a second antithrombotic drug at a low dose of 2.5 mg twice daily, citing a reduction in both major adverse cardiovascular events and major adverse limb events compared with aspirin alone.{FIG}The added drug acts by which of the following mechanisms?",
choices=["Antagonism of protease-activated receptor-1","Direct inhibition of factor Xa","Inhibition of phosphodiesterase-3","Irreversible blockade of P2Y12","Vitamin K epoxide reductase inhibition"], key=1,
exp="<b>Low-dose rivaroxaban 2.5 mg twice daily + aspirin</b> (dual pathway inhibition; COMPASS, VOYAGER-PAD) → ↓ MACE <b>and</b> MALE vs aspirin alone in symptomatic PAD when bleeding risk is acceptable (guideline Class 1). Rivaroxaban = <b>direct factor Xa inhibitor</b> → ↓ thrombin generation. Lecture match game: aspirin = COX-1; clopidogrel = P2Y12; cilostazol = PDE3; vorapaxar = PAR-1.<br><br><b>Educational objective:</b> Low-dose rivaroxaban (factor Xa inhibitor) plus aspirin reduces cardiovascular and limb events in symptomatic PAD.",
wrong={0:"Would be correct for vorapaxar: no MACE reduction alone and ↑ intracranial hemorrhage.",
2:"Would be correct for cilostazol: improves walking distance, not events, and is contraindicated in HF.",
3:"Would be correct for clopidogrel 75 mg, the single-antiplatelet alternative to aspirin.",
4:"Would be correct for warfarin, which doesn't improve PAD outcomes and raises bleeding."},
eli5="Adding a small dose of a blood thinner that blocks one clotting factor to aspirin prevents both heart attacks and leg emergencies better than aspirin alone."),

dict(img=None,
stem="A 64-year-old man with peripheral artery disease and a 50-pack-year smoking history wants to quit. He has tried nicotine patches twice. He has no history of seizures or eating disorders. He is prescribed a drug that relieves cravings and withdrawal while blunting the reward from any cigarette he smokes. Two weeks later he reports mild nausea and vivid dreams.{FIG}This drug most likely acts as which of the following at α4β2 nicotinic acetylcholine receptors?",
choices=["Allosteric inhibitor","Full agonist","Inverse agonist","Partial agonist","Pure antagonist"], key=3,
exp="<b>Varenicline</b>: <b>partial agonist at α4β2 nicotinic receptors</b>. Modest receptor stimulation → dopamine release relieves craving and withdrawal; occupying the receptor blocks nicotine's full effect, blunting reward. Adverse effects: nausea, vivid dreams. <b>Cytisine</b> (a plant alkaloid, cheap in Europe, not FDA-approved) is also an α4β2 partial agonist. Quitting lowers death and amputation in PAD.<br><br><b>Educational objective:</b> Varenicline and cytisine are α4β2 nicotinic partial agonists.",
wrong={0:"Would be correct for nothing among standard cessation drugs.",
1:"Would be correct for nicotine itself (patch, gum, lozenge), which wouldn't blunt reward.",
2:"Would be correct for nothing used clinically for nicotine dependence.",
4:"Would be correct for mecamylamine-like blockade, which wouldn't relieve withdrawal."},
eli5="The drug gently switches on the nicotine receptor to ease cravings, and because it's sitting there, a cigarette can't give the usual kick."),
]
