# Application Session 1 (Watkins CAD case + Segal HTN case) — Version 1, 18 items (4 with images). NBME house style (2026-10-07).
Q = [
dict(img=None,
stem="A 64-year-old woman comes to the office because of a 6-week history of episodic chest discomfort. She describes a dull pressure behind the sternum that comes on each time she climbs the two flights of stairs to her apartment and resolves within 4 minutes of resting. Twice it has also occurred after a large evening meal, with a burning quality. Last week a single episode resolved 5 minutes after a sublingual nitroglycerin tablet borrowed from her husband. She has hypertension treated with losartan. Her pulse is 74/min, and blood pressure is 142/86 mm Hg. Physical examination shows no abnormalities. An ECG at rest shows no abnormalities.{FIG}Which of the following features of her history most strongly increases the likelihood that her symptoms are caused by myocardial ischemia?",
choices=["Its burning quality after a large meal","Its relief after sublingual nitroglycerin","Its reproducibility at a predictable workload","Its retrosternal location without any radiation"], key=2,
exp="Dr. Watkins' rule: the best discriminator is that angina is <b>predictable and inducible</b>. The patient can tell you the workload that brings it on (\"Can you make it occur?\"), and it resolves within minutes of rest. Stable exertional angina → fixed stenosis → demand exceeds supply at a reproducible threshold. The 2021 chest-pain guideline: <b>relief with nitroglycerin is not diagnostic</b> of ischemia (esophageal spasm also responds).<br><br><b>Educational objective:</b> Reproducible exertional onset with prompt relief at rest is the most ischemia-specific feature of a chest-pain history.",
wrong={0:"Would be correct for reflux or esophageal pain: burning, meal-related, without an exertional pattern.",
1:"Would be correct only if NTG response were diagnostic; it isn't, because smooth-muscle relaxation also relieves esophageal spasm.",
3:"Would be correct only as supporting detail; location without the exertional pattern is far less specific."},
eli5="Heart pain from a narrowed artery comes on with the same amount of effort every time and goes away when you rest. That pattern matters more than how it feels or whether a pill helped."),

dict(img='A1xanth', cap='The posterior ankle (arrow)',
stem="A 38-year-old man comes to the office for a health maintenance examination. His father died of a myocardial infarction at the age of 44 years. He does not smoke and takes no medications. His blood pressure is 124/78 mm Hg, and BMI is 24 kg/m2. Firm, nontender nodules are palpated along both Achilles tendons; the right ankle is shown. Fasting serum studies show:\n\nTotal cholesterol: 382 mg/dL\nLDL-cholesterol: 291 mg/dL\nHDL-cholesterol: 46 mg/dL\nTriglycerides: 118 mg/dL\nThyroid-stimulating hormone: 1.8 μU/mL\n\nThere are no papular skin eruptions on the trunk, and the palmar creases are normal.{FIG}A defect in which of the following is the most likely cause of this patient's findings?",
choices=["Apolipoprotein E (E2/E2)","LDL receptor","Lipoprotein lipase","Microsomal triglyceride transfer protein","PCSK9 (loss of function)"], key=1,
exp="Isolated, very high <b>LDL-C</b> with normal triglycerides, <b>tendon xanthomas</b> (Achilles) and a father with MI at 44 → <b>heterozygous familial hypercholesterolemia</b>, most often an <b>LDL-receptor</b> mutation → ↓ hepatic LDL clearance. Dr. Watkins: <b>tendon xanthoma is highly specific</b> for FH, as is corneal arcus before 45; xanthelasma is not. These signs should prompt lipid testing, an FH score and cascade screening of relatives.<br><br><b>Educational objective:</b> Tendon xanthomas with isolated severe LDL elevation indicate familial hypercholesterolemia from an LDL-receptor defect.",
wrong={0:"Would be correct for dysbetalipoproteinemia: palmar crease and tuberoeruptive xanthomas with ↑ cholesterol <b>and</b> ↑ triglycerides.",
2:"Would be correct for familial chylomicronemia: triglycerides > 1000, eruptive xanthomas, pancreatitis.",
3:"Would be correct for abetalipoproteinemia: very <b>low</b> lipids, fat malabsorption, acanthocytes.",
4:"Would be correct for a <b>low</b> LDL-C (loss of PCSK9 keeps more LDL receptors); gain of function causes FH."},
eli5="His liver can't pull bad cholesterol out of the blood because the docking receptor is broken, so cholesterol builds up, even in his tendons."),

dict(img=None,
stem="A 66-year-old woman is evaluated because of a 3-month history of exertional chest pressure that resolves within minutes of rest. She has hypertension and walks 2 miles daily. Her pulse is 70/min, and blood pressure is 138/82 mm Hg. Physical examination shows no abnormalities. The calculated pretest probability of obstructive coronary artery disease is 48%. An ECG at rest shows increased QRS voltage with 2-mm downsloping ST-segment depression and T-wave inversion in leads V5 and V6. Serum studies show no abnormalities.{FIG}Which of the following is the most appropriate next step in diagnosis?",
choices=["Coronary angiography","Dobutamine stress echocardiography","Exercise ECG treadmill test","Exercise stress echocardiography","Transthoracic echocardiography at rest"], key=3,
exp="Intermediate pretest probability → functional or anatomic testing. She <b>can exercise</b>, but the resting ECG is <b>uninterpretable</b> for ischemia (LVH with repolarization abnormality) → <b>exercise with imaging</b> (echo or perfusion). Exercise is preferred over pharmacologic stress because it also gives functional capacity. Lecture plan for the case patient: stress echo is more sensitive and specific than a plain treadmill test, <b>especially in women</b>.<br><br><b>Educational objective:</b> An intermediate-risk patient who can exercise but has an uninterpretable resting ECG needs exercise stress imaging.",
wrong={0:"Would be correct for high-risk features, ACS, or a strongly positive non-invasive test.",
1:"Would be correct if she <b>could not exercise</b> (pharmacologic stress); she walks 2 miles daily.",
2:"Would be correct with a <b>normal</b> resting ECG; baseline ST depression makes exercise ECG uninterpretable.",
4:"Would be correct for assessing structure and EF, but a resting echo can't detect inducible ischemia."},
eli5="She can walk on a treadmill, but her baseline heart tracing is already abnormal, so you need ultrasound pictures during exercise to see if part of the heart stops moving well."),

dict(img='A1ecg', cap='12-lead ECG obtained in the office',
stem="A 72-year-old woman with stable exertional angina returns to the office 1 week after her initial evaluation, for a scheduled stress echocardiogram. During the past 4 days her episodes have become more frequent and last up to 45 minutes. Last night she had 4 hours of chest pressure at rest with nausea. She now has mild chest pressure. Her pulse is 84/min, respirations are 18/min, and blood pressure is 160/100 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 93%. Her ECG is shown. Her husband offers to drive her to the hospital 10 minutes away.{FIG}Which of the following is the most appropriate next step in management?",
choices=["Aspirin, nitroglycerin and ambulance transfer","Husband drives her to the emergency department","Outpatient high-sensitivity troponin today","Proceed with the scheduled stress echocardiogram","Uptitrate losartan and reassess in 1 week"], key=0,
exp="Crescendo angina with <b>prolonged rest pain</b> and <b>dynamic inferolateral ST depression</b> → <b>NSTE-ACS</b>. In the office: <b>aspirin, nitroglycerin, oxygen as needed and monitoring</b>, with <b>ambulance transfer</b>. Dr. Watkins: <b>\"No patient with ACS symptoms should ever be transferred by car\"</b> (arrhythmia or arrest en route). Stress testing during active ischemia is contraindicated.<br><br><b>Educational objective:</b> Suspected ACS in the office → aspirin, nitroglycerin, monitoring and ambulance transfer, never stress testing or private-car transport.",
wrong={1:"Would be correct for nothing: ACS patients go by ambulance because of the risk of arrhythmia and arrest.",
2:"Would be correct for nothing: troponin belongs in the ED as serial values; it delays care.",
3:"Would be correct for stable symptoms; stress testing with active ischemia is contraindicated.",
4:"Would be correct for uncomplicated hypertension, not unstable rest angina with ST depression."},
eli5="Her heart pain is now happening at rest and the tracing shows strain, so it's a heart attack in progress. Give aspirin and nitroglycerin and call an ambulance; don't let her ride in a car or put her on a treadmill."),

dict(img=None,
stem="A 70-year-old man is admitted from the emergency department with non-ST-elevation myocardial infarction. High-sensitivity troponin T was 48 ng/L at arrival and 290 ng/L 3 hours later. An ECG shows 1-mm ST-segment depression in leads V4 through V6 that resolved after intravenous nitroglycerin. He is now pain free. His pulse is 76/min, and blood pressure is 128/74 mm Hg. Lungs are clear to auscultation. His calculated GRACE score is 152. He has had no arrhythmias on telemetry, and echocardiography shows a left ventricular ejection fraction of 55% without regional wall motion abnormalities or murmurs.{FIG}Coronary angiography is most appropriately performed within which of the following time frames?",
choices=["2 hours","24 hours","72 hours","Only after a positive stress test","Not indicated"], key=1,
exp="NSTE-ACS invasive timing (lecture slide): <b>very high risk</b> (shock, refractory pain, life-threatening arrhythmia, mechanical complication, acute HF, recurrent dynamic ST changes) → <b>&lt; 2 h</b>. <b>High risk</b> (NSTEMI confirmed by troponin rise, dynamic ST/T changes, GRACE &gt; 140) → <b>early invasive, &lt; 24 h</b>. Intermediate risk (diabetes, CKD, EF &lt; 40%, prior PCI/CABG, GRACE 109–140) → &lt; 72 h. He is now pain-free, stable and arrhythmia-free, so he is not very high risk.<br><br><b>Educational objective:</b> A stable NSTEMI with a troponin rise, dynamic ST changes or GRACE > 140 needs angiography within 24 hours.",
wrong={0:"Would be correct with ongoing refractory pain, shock, arrhythmia, acute HF or a mechanical complication.",
2:"Would be correct with only intermediate features (e.g. GRACE 109–140, diabetes, CKD) and no troponin-confirmed MI.",
3:"Would be correct for low-risk chest pain; confirmed NSTEMI warrants an invasive strategy.",
4:"Would be correct for nothing here: a troponin-positive NSTEMI with high risk needs angiography."},
eli5="He had a heart attack with high-risk features but is stable now, so he gets his heart arteries looked at within a day, not instantly and not 'later.'"),

dict(img=None,
stem="An 84-year-old woman is admitted to the intensive care unit with pyelonephritis. Her temperature is 39.4°C (102.9°F), pulse is 136/min, and blood pressure is 82/48 mm Hg. Hemoglobin concentration is 8.1 g/dL. High-sensitivity troponin T rises from 22 to 94 ng/L over 3 hours, and an ECG shows diffuse 1-mm ST-segment depression. Coronary angiography performed 1 year ago for atypical chest pain showed 30% luminal narrowing of the left anterior descending artery and no other lesions. Echocardiography shows global hyperdynamic function without regional wall motion abnormality.{FIG}Which of the following is the most likely mechanism of this patient's myocardial injury?",
choices=["Coronary artery vasospasm","Embolism to a coronary artery","Myocardial oxygen supply–demand mismatch","Plaque rupture with coronary thrombosis","Spontaneous coronary artery dissection"], key=2,
exp="Sepsis + <b>hypotension, tachycardia and anemia</b> → ↓ O₂ supply and ↑ demand → <b>secondary (type 2) MI</b>, supply–demand mismatch without acute plaque disruption. Lecture (2023 trigger-based classification): <b>primary</b> MI = coronary plaque/thrombus or dissection; <b>secondary</b> = sepsis, shock, tachycardia, severe HTN, anemia; <b>procedural</b> = PCI/surgery. Type 2 patients are older, more often women, with many comorbidities, and usually have a lower peak troponin.<br><br><b>Educational objective:</b> Troponin rise during sepsis, hypotension, tachycardia and anemia without new regional dysfunction is a secondary (type 2) MI.",
wrong={0:"Would be correct for transient rest angina with ST elevation in a younger smoker or cocaine user.",
1:"Would be correct with atrial fibrillation or endocarditis and a new regional wall motion defect.",
3:"Would be correct for a primary (type 1) MI with a regional wall motion abnormality, not global hyperdynamic function.",
4:"Would be correct for a young woman (often peripartum) with a sudden regional infarct."},
eli5="Her heart got hurt because it was racing with low blood pressure and too little blood, not because a clot blocked an artery."),

dict(img=None,
stem="An investigator measures coronary blood flow at rest and during maximal pharmacologic vasodilation in a canine model as a coronary artery is progressively narrowed with an adjustable occluder. Flow is expressed as a multiple of resting flow.{FIG}Maximal (hyperemic) coronary flow first begins to decline at approximately which of the following degrees of luminal diameter stenosis?",
choices=["30%","50%","70%","85%","95%"], key=1,
exp="Coronary flow reserve (Gould): resting flow is preserved by autoregulatory arteriolar dilation until about <b>80–90%</b> stenosis, but <b>maximal flow begins to fall at ~50%</b> because the reserve is used up. That is why stable angina appears with exertion first, and why stress testing unmasks lesions a resting ECG misses.<br><br><b>Educational objective:</b> Maximal coronary flow falls from about 50% stenosis; resting flow is maintained until about 80–90%.",
wrong={0:"Would be correct for no reserve loss; a 30% lesion is hemodynamically insignificant.",
2:"Would be correct for the conventional 'significant' angiographic cut-off, but reserve is already falling before this.",
3:"Would be correct for when <b>resting</b> flow begins to fall (~80–90%).",
4:"Would be correct for near-occlusion, when even resting flow is severely limited."},
eli5="A partly blocked artery still delivers enough blood when you're sitting still, but once it's about half blocked it can't increase flow when you exercise."),

dict(img=None,
stem="A 67-year-old man with stable angina comes for follow-up. He takes metoprolol succinate at the maximally tolerated dose, aspirin, atorvastatin and lisinopril, and continues to have angina when walking his dog uphill. He also has dizziness when standing quickly. His pulse is 54/min, and blood pressure is 102/64 mm Hg sitting and 92/58 mm Hg standing. ECG shows sinus bradycardia with a QTc of 420 msec. Coronary angiography 2 months ago showed diffuse distal disease not amenable to revascularization.{FIG}The most appropriate additional antianginal drug for this patient has which of the following mechanisms of action?",
choices=["Blockade of L-type Ca²⁺ channels in arterioles","Blockade of L-type Ca²⁺ channels in nodal tissue","Blockade of the HCN funny current","Inhibition of the late inward Na⁺ current","Release of nitric oxide in venous smooth muscle"], key=3,
exp="He needs more anti-ischemic effect but has <b>bradycardia</b> and <b>low, orthostatic BP</b>, so drugs that lower HR or BP are limited. <b>Ranolazine</b> blocks the <b>late Na⁺ current</b> → ↓ intracellular Na⁺ → ↓ Na⁺/Ca²⁺-exchange Ca²⁺ overload → better diastolic relaxation and ↓ O₂ demand, with <b>little effect on HR or BP</b>. Watch the QTc (his is normal). Note: the lecture slide gave ivabradine the late Na⁺ mechanism; ivabradine blocks the HCN (funny) current.<br><br><b>Educational objective:</b> Ranolazine (late Na⁺ current inhibitor) treats angina without lowering heart rate or blood pressure.",
wrong={0:"Would be correct (amlodipine) with normal BP; it would worsen his hypotension.",
1:"Would be correct (diltiazem/verapamil) with a faster HR; it would worsen bradycardia and hypotension.",
2:"Would be correct (ivabradine) with sinus rhythm and a HR still > 70 on a maximal β-blocker; his is 54.",
4:"Would be correct (nitrates) with adequate BP; venodilation would worsen his orthostasis."},
eli5="His heart rate and blood pressure are already low, so he needs an angina drug that works inside heart cells without slowing the heart or dropping blood pressure."),

dict(img=None,
stem="A 76-year-old woman is hospitalized for an anterior ST-elevation myocardial infarction. She arrived 14 hours after symptom onset, and the left anterior descending artery was opened with a stent. On the fourth hospital day, while coughing, she reports sudden severe chest pain and becomes unresponsive. Her pulse is not palpable, and blood pressure is not obtainable. The cardiac monitor shows sinus rhythm at 98/min. Neck veins are distended. No murmur was heard on examination 2 hours earlier.{FIG}Which of the following is the most likely diagnosis?",
choices=["Dressler syndrome","Left ventricular aneurysm","Left ventricular free-wall rupture","Papillary muscle rupture","Stent thrombosis","Ventricular septal rupture"], key=2,
exp="An elderly woman, <b>anterior</b> MI with <b>late reperfusion</b>, day 3–5, sudden pain after <b>coughing or straining</b> → <b>free-wall rupture</b> → hemopericardium → tamponade (distended neck veins) → <b>pulseless electrical activity</b> (organized rhythm, no pulse; ~95% predictive). Lecture: two peaks (24 h and 3–5 days), > 50% mortality. No new murmur argues against septal or papillary rupture.<br><br><b>Educational objective:</b> Sudden PEA with tamponade 3–5 days after an anterior MI in an elderly woman is free-wall rupture.",
wrong={0:"Would be correct for pleuritic pain, fever and a friction rub weeks after MI, not sudden death.",
1:"Would be correct for persistent ST elevation, HF or emboli weeks later, without sudden collapse.",
3:"Would be correct after an <b>inferior</b> MI with sudden pulmonary edema and a new apical holosystolic murmur.",
4:"Would be correct for recurrent chest pain with new ST elevation in the stented territory and a shockable rhythm.",
5:"Would be correct for a new harsh holosystolic murmur at the LSB with a thrill and an O₂ step-up."},
eli5="A big front-wall heart attack left a weak spot that tore when she coughed. Blood filled the sac around her heart, so the heart's electricity kept going but it couldn't pump."),

dict(img='Aretino', cap='Fundoscopic examination of the right eye',
stem="A 49-year-old man is brought to the emergency department because of a 2-day history of headache and blurred vision. He stopped taking his antihypertensive medications 3 months ago. His blood pressure is 228/134 mm Hg in both arms, and pulse is 92/min. He is oriented to person, place and time. Neurologic examination shows no focal findings. Fundoscopic examination of the right eye is shown; the left fundus is similar. Serum creatinine is 1.1 mg/dL, urinalysis shows no blood or protein, and an ECG shows no ischemic changes.{FIG}Which of the following is the most likely diagnosis?",
choices=["Central retinal vein occlusion","Hypertensive emergency","Idiopathic intracranial hypertension","Severe hypertension without target-organ damage","White-coat hypertension"], key=1,
exp="BP &gt; 180/120 with <b>acute target-organ damage</b> = <b>hypertensive emergency</b>. Here the damage is in the eyes: cotton-wool spots, flame hemorrhages and optic disc swelling (<b>grade 4 retinopathy</b>, papilledema). Lecture: in severe HTN, look for organ damage first (brain, heart, kidney, <b>retina</b>) to separate emergency from severe HTN, then pursue the cause. Normal creatinine, urine and ECG don't exclude it when the fundus is involved.<br><br><b>Educational objective:</b> Severe hypertension with papilledema and retinal hemorrhages is a hypertensive emergency.",
wrong={0:"Would be correct for unilateral sudden vision loss with diffuse 'blood-and-thunder' hemorrhages; his findings are bilateral with disc edema and severe HTN.",
2:"Would be correct for papilledema in a young obese woman with normal BP.",
3:"Would be correct if the fundi showed only arteriolar narrowing and he had no symptoms of acute organ injury.",
4:"Would be correct for high office BP with normal out-of-office readings and no organ damage."},
eli5="His blood pressure is so high it's damaging the back of his eyes right now, so this is an emergency, not just 'very high blood pressure.'"),

dict(img=None,
stem="A 46-year-old woman comes to the office for follow-up of hypertension diagnosed at a workplace screening 2 months ago. She takes no medications. Office blood pressure, measured correctly with an appropriately sized cuff after 5 minutes of seated rest, averages 152/96 mm Hg over three visits. Her home readings with a validated device average 121/77 mm Hg. A 24-hour ambulatory recording shows a daytime average of 122/78 mm Hg and a nighttime average of 108/66 mm Hg. Physical examination shows no abnormalities. An ECG and urinalysis show no abnormalities.{FIG}Which of the following is the most likely diagnosis?",
choices=["Masked hypertension","Normotension","Sustained hypertension","White-coat hypertension"], key=3,
exp="Lecture phenotype grid: <b>office high + out-of-office normal = white-coat hypertension</b>; office normal + out-of-office high = masked; both high = sustained; both normal = normotension. Measurement technique was correct, so this isn't simply error. Home and ambulatory BP correlate more strongly with outcomes and are how you find both white-coat and masked HTN.<br><br><b>Educational objective:</b> Elevated office BP with normal ambulatory and home BP is white-coat hypertension.",
wrong={0:"Would be correct for normal office BP with elevated home/ambulatory readings.",
1:"Would be correct if office BP were also normal.",
2:"Would be correct if home and ambulatory readings were also elevated."},
eli5="Her blood pressure is only high at the doctor's office; at home and all day on a monitor, it's normal."),

dict(img=None,
stem="A 31-year-old man comes to the office because his blood pressure was 158/98 mm Hg at a pharmacy kiosk. It was 118/74 mm Hg 1 year ago. He has had nasal congestion for 6 weeks and takes an over-the-counter tablet containing pseudoephedrine every morning. He takes ibuprofen 400 mg about twice a month for headaches, drinks one cup of coffee each morning, and takes levothyroxine for hypothyroidism. Serum thyroid-stimulating hormone is 2.1 μU/mL. His blood pressure, measured correctly, is 154/96 mm Hg. Physical examination shows no abnormalities.{FIG}Which of the following is most likely contributing to this patient's elevated blood pressure?",
choices=["Daily morning coffee","Daily pseudoephedrine","Levothyroxine replacement","Occasional ibuprofen"], key=1,
exp="Lecture (drugs that raise BP): <b>decongestants (pseudoephedrine, phenylephrine)</b> are α-adrenergic sympathomimetics → vasoconstriction → ↑ BP. Taken daily for 6 weeks, timed with the rise from 118/74. The planted alternatives are real but weaker: NSAIDs raise BP with regular use (not twice a month), caffeine's effect is small and tolerated, and levothyroxine with a normal TSH causes nothing.<br><br><b>Educational objective:</b> Decongestants such as pseudoephedrine are a common reversible cause of new hypertension.",
wrong={0:"Would be correct only for acute, small rises in caffeine-naive people; one daily cup is tolerated.",
2:"Would be correct with over-replacement (low TSH, tachycardia); his TSH is normal.",
3:"Would be correct with regular daily NSAID use (Na⁺ retention, ↓ prostaglandins); twice monthly is too little."},
eli5="His cold pill squeezes his blood vessels, and he's been taking it every day, so that's what pushed his pressure up."),

dict(img='Ahypok', cap='12-lead ECG',
stem="A 33-year-old woman comes to the office because of a 3-month history of muscle weakness, fatigue and nocturia. Her blood pressure is 168/104 mm Hg on three occasions despite amlodipine. She does not use diuretics, laxatives or licorice products, and there is no family history of early hypertension. Her pulse is 70/min. There is no edema. No abdominal bruit is heard. Serum studies show:\n\nNa⁺: 145 mEq/L\nK⁺: 2.7 mEq/L\nHCO₃⁻: 31 mEq/L\nCreatinine: 0.8 mg/dL\n\nHer ECG is shown. Renal artery duplex ultrasonography shows normal flow bilaterally.\n\nPlasma renin activity | Plasma aldosterone{FIG}Which of the following sets of findings is most likely?",
choices=["Decreased, decreased","Decreased, increased","Increased, decreased","Increased, increased"], key=1,
exp="Young woman, resistant HTN, <b>spontaneous hypokalemia</b> (ECG: flattened T waves and prominent U waves) with <b>metabolic alkalosis</b> and high-normal Na⁺, no edema → <b>primary aldosteronism</b>: autonomous aldosterone → Na⁺ retention → volume expansion → <b>renin suppressed</b>. Lecture: \"HTN + ↓K⁺ + alkalosis: read the renin.\" ↓R/↑A = PA · ↑R/↑A = renovascular or diuretics · ↓R/↓A = Liddle, licorice, Cushing, CAH.<br><br><b>Educational objective:</b> Primary aldosteronism shows suppressed renin with elevated aldosterone.",
wrong={0:"Would be correct for Liddle syndrome or licorice (non-aldosterone mineralocorticoid effect); she has no family history and no licorice.",
2:"Would be correct for adrenal insufficiency or ACEi/ARB effect, with <b>hyper</b>kalemia and low BP.",
3:"Would be correct for renovascular HTN or diuretic use; her renal duplex is normal and she takes no diuretics."},
eli5="Her adrenal gland is making too much salt-keeping hormone on its own. The body senses the extra salt and switches off renin."),

dict(img=None,
stem="A 52-year-old man comes to the office because he wakes 4 times nightly to urinate and fills large containers with urine during the day. His blood pressure is 172/102 mm Hg. Serum studies show:\n\nNa⁺: 144 mEq/L\nK⁺: 2.6 mEq/L\nCa²⁺: 9.4 mg/dL\nGlucose: 96 mg/dL\n\nUrine osmolality is 190 mOsm/kg H₂O after an overnight water restriction and remains low after administration of desmopressin. Plasma renin is suppressed and aldosterone is elevated.{FIG}Which of the following is the most likely mechanism of this patient's polyuria?",
choices=["Hypercalcemia impairing renal concentrating ability","Hypokalemia blunting collecting-duct response to ADH","Osmotic diuresis from glucose in the tubular fluid","Pressure natriuresis from the elevated blood pressure","Suppressed ADH release from volume expansion"], key=1,
exp="Dr. Segal's \"milk jug\" patient: polyuria in primary aldosteronism comes from <b>hypokalemia (K⁺ ~2.6)</b> → <b>nephrogenic diabetes insipidus</b> (↓ aquaporin-2 response to ADH, \"kind of like putting someone on lithium\"). Urine stays dilute despite water restriction <b>and desmopressin</b> → nephrogenic, not central. It resolved after his adrenalectomy.<br><br><b>Educational objective:</b> Severe hypokalemia in primary aldosteronism causes nephrogenic DI and polyuria.",
wrong={0:"Would be correct with a high serum calcium; his is 9.4.",
2:"Would be correct with hyperglycemia and glycosuria; his glucose is 96.",
3:"Would be correct only as a minor contributor; it wouldn't make urine dilute and ADH-resistant.",
4:"Would be correct for central DI, which <b>responds</b> to desmopressin; his urine stays dilute."},
eli5="Very low potassium stops the kidney from listening to the 'hold on to water' hormone, so he pees out huge amounts of dilute urine."),

dict(img=None,
stem="A 45-year-old woman with a 2-year history of hypertension is found to have primary aldosteronism with a serum potassium of 3.2 mEq/L, suppressed plasma renin and an elevated plasma aldosterone. Despite urinary sodium excretion that matches intake and a stable body weight over 6 months, physical examination shows no peripheral edema. Serum albumin is 4.2 g/dL. Echocardiography shows normal ventricular function.{FIG}Which of the following best explains the absence of edema in this patient?",
choices=["Decreased capillary oncotic pressure","Decreased mineralocorticoid receptor density","Increased lymphatic drainage of interstitial fluid","Increased proximal tubular Na⁺ reabsorption","Pressure natriuresis and natriuretic peptides"], key=4,
exp="<b>Aldosterone escape</b>: autonomous aldosterone → Na⁺ retention → plasma volume expansion → ↑ renal perfusion and peritubular hydrostatic pressure (<b>pressure natriuresis</b>) plus atrial stretch → <b>ANP</b> → natriuresis. Na⁺ balance resets (excretion matches intake) with HTN but <b>no edema</b>. Lecture pearl: edema in suspected PA should prompt a search for another cause.<br><br><b>Educational objective:</b> Aldosterone escape (pressure natriuresis + ANP) explains hypertension without edema in primary aldosteronism.",
wrong={0:"Would be correct for causing edema (nephrotic, cirrhosis), not preventing it; albumin is normal.",
1:"Would be correct for nothing here: MR action persists, hence the ongoing hypokalemia.",
2:"Would be correct for nothing physiologic in this setting; lymphatic flow is not the escape mechanism.",
3:"Would be correct for the <b>opposite</b>: proximal Na⁺ reabsorption actually falls during escape."},
eli5="The extra salt raises blood pressure and stretches the heart, which releases a hormone and pushes the kidneys to dump the extra salt, so fluid never builds up in her legs."),

dict(img=None,
stem="A 51-year-old man with resistant hypertension is referred for evaluation of primary aldosteronism. His medications are spironolactone 50 mg daily, amlodipine 10 mg daily and doxazosin 4 mg daily. His blood pressure is 146/90 mm Hg. Serum potassium is 4.2 mEq/L. He has no symptoms. The physician plans to measure plasma aldosterone and renin.{FIG}Which of the following is the most appropriate next step before testing?",
choices=["Discontinue doxazosin for 2 weeks","Discontinue spironolactone for 4 weeks","Replace amlodipine with lisinopril","Test now without changing any medications"], key=1,
exp="Lecture (meds to hold before PA testing): <b>MRAs are a mandatory hold for 4 weeks</b>, because blocking the MR raises renin and gives a false-negative ratio. ACEi, ARBs, β-blockers, diuretics and DHP CCBs are optional 2–4-week holds. <b>α-blockers, non-DHP CCBs and vasodilators can be continued</b> and are what you use to control BP during the washout. Draw in the morning, seated, on an ad lib diet, after correcting K⁺.<br><br><b>Educational objective:</b> Stop MRAs for 4 weeks before aldosterone-to-renin testing; α-blockers can be continued.",
wrong={0:"Would be correct for nothing: doxazosin doesn't interfere and helps cover BP during the washout.",
2:"Would be correct for nothing: ACE inhibitors raise renin and can cause false negatives.",
3:"Would be correct only if he were off MRAs; spironolactone invalidates the ratio."},
eli5="His spironolactone hides the hormone problem we're testing for, so he has to stop it for a month first. The other pills can stay."),

dict(img=None,
stem="Patient Information\nAge: 48 years · Gender: F · Site of Care: endocrinology clinic\n\nHistory\nReason for Visit: follow-up of confirmed primary aldosteronism\nHistory of Present Illness: 6 years of hypertension requiring 3 drugs; K⁺ 3.1 mEq/L on supplements; aldosterone-to-renin ratio 46 with suppressed renin, confirmed by saline infusion test\nPast Medical History: obesity\nMedications: amlodipine, doxazosin, potassium chloride\nPsychosocial History: works as an accountant; wishes to pursue surgery if it could cure her\n\nPhysical Examination\nT 36.8°C (98.2°F) · P 72/min · R 14/min · BP 150/94 mm Hg\nGeneral: no striae, plethora or proximal muscle weakness\n\nDiagnostic Studies\nAdrenal CT: 1.3-cm low-attenuation nodule in the left adrenal gland; right adrenal gland appears normal\n\nQuestion:{FIG}Which of the following is the most appropriate next step in management?",
choices=["Adrenal venous sampling","Bilateral adrenalectomy","Dexamethasone suppression test","Left laparoscopic adrenalectomy","Repeat adrenal CT in 12 months"], key=0,
exp="Lecture pearl 8: <b>\"Lateralize before the scalpel.\"</b> CT alone misclassifies; at 48, a 1.3-cm nodule may be a <b>non-functioning incidentaloma</b> on top of <b>bilateral hyperplasia</b> (60% of PA). In a surgical candidate → <b>adrenal venous sampling</b>. Unilateral → laparoscopic adrenalectomy; bilateral → MRA (spironolactone). ES 2025 lets select patients &lt; 35 with marked hypokalemia and a clear adenoma &gt; 1 cm skip AVS; she is 48.<br><br><b>Educational objective:</b> In confirmed PA with a candidate for surgery, adrenal venous sampling must confirm lateralization before adrenalectomy.",
wrong={1:"Would be correct for nothing: bilateral disease is treated medically (lifelong steroid replacement otherwise).",
2:"Would be correct with Cushing features (striae, plethora, weakness) or autonomous cortisol concern; she has none.",
3:"Would be correct <b>after</b> AVS shows left-sided lateralization (or in a young patient meeting the skip criteria).",
4:"Would be correct for a non-functioning incidentaloma without hormonal disease."},
eli5="The scan shows a lump on one adrenal gland, but it might not be the one making the hormone. Sample blood from each adrenal vein first to find the real culprit before surgery."),

dict(img=None,
stem="A 56-year-old man with primary aldosteronism from bilateral adrenal hyperplasia has been taking spironolactone 100 mg daily for 8 months. His blood pressure is 128/80 mm Hg, and serum potassium is 4.4 mEq/L. He reports tender enlargement of both breasts and decreased libido for 3 months. Examination shows bilateral subareolar glandular tissue 3 cm in diameter. Testicular examination is normal. Serum creatinine is 1.0 mg/dL.{FIG}Which of the following is the most appropriate change in pharmacotherapy?",
choices=["Amiloride","Eplerenone","Hydrochlorothiazide","Lisinopril","Triamterene"], key=1,
exp="Spironolactone also blocks the <b>androgen receptor</b> (and progesterone receptor) → <b>gynecomastia</b>, ↓ libido, especially at doses above ~50 mg. <b>Eplerenone</b> is far more <b>selective for the mineralocorticoid receptor</b>, so it keeps blocking aldosterone's effects (BP, K⁺, cardiac and renal fibrosis) without the anti-androgen effects. It needs twice-daily dosing and costs more. Amiloride (an ENaC blocker) is the 2nd-line option but doesn't block the MR.<br><br><b>Educational objective:</b> Switch spironolactone to eplerenone for gynecomastia in primary aldosteronism.",
wrong={0:"Would be correct as a 2nd-line agent if MRAs were not tolerated at all; it blocks ENaC, not the MR.",
2:"Would be correct for essential HTN; it worsens hypokalemia in PA.",
3:"Would be correct for essential HTN or proteinuria; PA has suppressed renin, so RAAS blockade adds little.",
4:"Would be correct only as an ENaC alternative like amiloride; it doesn't address MR-mediated harm."},
eli5="His water pill is also blocking male hormones, which grew breast tissue. A cousin drug blocks only the salt hormone, so he keeps the benefit without that side effect."),
]
