# Application Session 1 (Watkins CAD case + Segal HTN case) — Version 2, 18 items (4 with images). NBME house style (2026-10-07).
Q = [
dict(img=None,
stem="Investigators analyze sex-specific risk factors for myocardial infarction in a prospective cohort of 24,000 adults followed for 12 years. Among men, current smokers had about three times the risk of myocardial infarction of men who never smoked, after adjustment for age, blood pressure, lipids and diabetes.{FIG}Which of the following is the best estimate of the adjusted relative risk of myocardial infarction for women who currently smoke compared with women who never smoked?",
choices=["1.5","3","6","12"], key=2,
exp="Lecture (sex differences in CAD risk): <b>smoking is more detrimental in women</b>, about <b>6-fold</b> MI risk vs <b>3-fold in men</b>. Diabetes is also a more potent risk factor in women, HTN is more prevalent in women after 60, and CAD presents ~10 years later in women (a woman of 70 ≈ a man of 60).<br><br><b>Educational objective:</b> Smoking raises MI risk about 6-fold in women vs about 3-fold in men.",
wrong={0:"Would be correct for a weak risk factor, underestimating smoking in either sex.",
1:"Would be correct for <b>men</b> (the stem's figure); women's relative risk is higher.",
3:"Would be correct for no lecture figure; it overstates the reported 6-fold risk."},
eli5="Smoking roughly triples heart-attack risk in men but about sextuples it in women."),

dict(img='A1arcus', cap='The left eye',
stem="A 39-year-old man comes to the office for a health maintenance examination. He feels well. His mother had coronary artery bypass grafting at the age of 50 years. He does not smoke. His blood pressure is 122/76 mm Hg, and BMI is 25 kg/m2. Examination of the eyes is shown. There are no skin eruptions, palmar xanthomas or tendon nodules. Fasting serum studies show:\n\nLDL-cholesterol: 236 mg/dL\nHDL-cholesterol: 48 mg/dL\nTriglycerides: 104 mg/dL\nThyroid-stimulating hormone: 1.6 μU/mL\nAlbumin: 4.4 g/dL\n\nUrinalysis shows no protein.{FIG}Which of the following is the most likely diagnosis?",
choices=["Dysbetalipoproteinemia","Familial chylomicronemia","Familial combined hyperlipidemia","Heterozygous familial hypercholesterolemia","Hypothyroidism-induced hyperlipidemia","Nephrotic syndrome"], key=3,
exp="A grey-white <b>corneal arcus in a man under 45</b>, isolated severe LDL elevation with normal triglycerides, and premature CAD in a first-degree relative → <b>heterozygous familial hypercholesterolemia</b>. Lecture: <b>arcus &lt; 45 years and tendon xanthomas are highly specific</b>; xanthelasma has low specificity. Secondary causes are excluded by a normal TSH, albumin and urinalysis.<br><br><b>Educational objective:</b> Corneal arcus before 45 with isolated severe LDL elevation suggests familial hypercholesterolemia.",
wrong={0:"Would be correct with ↑ cholesterol <b>and</b> ↑ triglycerides plus palmar or tuberoeruptive xanthomas (ApoE2/E2).",
1:"Would be correct with triglycerides > 1000, eruptive xanthomas and pancreatitis.",
2:"Would be correct with variably raised LDL <b>and</b> triglycerides in family members, without arcus or xanthomas.",
4:"Would be correct with an elevated TSH.",
5:"Would be correct with proteinuria and hypoalbuminemia."},
eli5="A grey ring around the eye in a young man, plus very high bad cholesterol and family heart disease, points to an inherited cholesterol-clearing defect."),

dict(img='Alvh', cap='12-lead ECG',
stem="A 70-year-old woman comes to the office because of a 4-month history of shortness of breath when walking up a hill. She has had hypertension for 30 years, poorly controlled. Her pulse is 56/min, and blood pressure is 168/94 mm Hg. The point of maximal impulse is sustained and not displaced. An S4 is heard; there is no murmur, and the intensity of heart sounds does not change with the Valsalva maneuver. Her ECG is shown.{FIG}Echocardiography is most likely to show which of the following?",
choices=["Asymmetric septal hypertrophy with dynamic outflow obstruction","Concentric left ventricular hypertrophy","Dilated left ventricle with thin walls","Large circumferential pericardial effusion","Right ventricular hypertrophy"], key=1,
exp="Long-standing HTN → <b>pressure overload</b> → <b>concentric LVH</b> (↑ wall thickness, normal cavity, ↑ relative wall thickness). The ECG shows tall precordial voltage meeting Sokolow–Lyon criteria with lateral ST–T \"strain,\" and a broad P wave (LA enlargement). The exam fits: a sustained, non-displaced impulse and an S4 (stiff ventricle). Session 2: concentric = pressure overload (HTN, aortic stenosis); eccentric = volume overload.<br><br><b>Educational objective:</b> Long-standing hypertension produces concentric LVH with voltage and strain on ECG.",
wrong={0:"Would be correct for HCM: a younger patient with a systolic murmur that <b>increases with Valsalva</b>.",
2:"Would be correct for dilated cardiomyopathy: a displaced impulse, S3 and often low voltage.",
3:"Would be correct for <b>low</b> QRS voltage and electrical alternans.",
4:"Would be correct for right axis deviation with tall R in V1 (e.g. pulmonary HTN)."},
eli5="Decades of high blood pressure made her heart muscle thick, like lifting weights all the time, and the ECG shows the bigger electrical signals."),

dict(img=None,
stem="An investigator compares three models for estimating the pretest probability of obstructive coronary artery disease in patients with stable chest pain. Model 1 uses age, sex and symptom type. Model 2 adds diabetes, hypertension, dyslipidemia and smoking. Model 3 adds one further variable and substantially improves specificity, especially by down-classifying symptomatic patients who have no coronary atherosclerosis.{FIG}Which of the following variables was most likely added in Model 3?",
choices=["Coronary artery calcium score","Family history of premature CAD","High-sensitivity C-reactive protein","Lipoprotein(a) concentration","Urine albumin-to-creatinine ratio"], key=0,
exp="The <b>CAD Consortium</b> calculator (lecture): basic model = age, sex, symptoms; clinical model = + risk factors; <b>clinical + CCS model</b> = + <b>coronary calcium score</b>, which increases specificity (a CAC of 0 makes obstructive CAD much less likely). The case patient: basic 40%, clinical 43–50% → intermediate → testing.<br><br><b>Educational objective:</b> Adding a coronary calcium score to the CAD Consortium model increases specificity of pretest probability.",
wrong={1:"Would be correct for refining <b>long-term ASCVD</b> risk (a risk enhancer), not the calculator's third model.",
2:"Would be correct as a risk enhancer for primary prevention; it isn't part of the CAD Consortium model.",
3:"Would be correct as a once-in-a-lifetime lipid risk marker, not a pretest-probability variable.",
4:"Would be correct as an optional input to the PREVENT equations, not the CAD Consortium model."},
eli5="Adding a calcium scan of the heart arteries tells you whether plaque is actually there, which sharpens the guess about blocked arteries."),

dict(img=None,
stem="A 44-year-old man comes to the emergency department 40 minutes after he fainted at home. For 2 months he has had chest pressure while carrying groceries upstairs. A friend gave him a sublingual nitroglycerin tablet for the pressure; he became lightheaded 3 minutes after taking it and lost consciousness for 20 seconds. His pulse is 88/min, and blood pressure is 112/70 mm Hg supine. A harsh systolic murmur is heard at the left lower sternal border; it becomes louder when he stands and softer when he squats. Carotid upstrokes are brisk and bifid. An ECG shows left ventricular hypertrophy. Troponin is within the reference range.{FIG}Which of the following best explains this patient's syncope?",
choices=["Bradyarrhythmia from heart block","Fixed outflow obstruction at the aortic valve","Lower preload worsening dynamic obstruction","Reflex vasovagal bradycardia and vasodilation","Ventricular tachycardia from acute ischemia"], key=2,
exp="A murmur that <b>gets louder with standing</b> (↓ preload) and <b>softer with squatting</b>, brisk bifid carotids → <b>hypertrophic obstructive cardiomyopathy</b>. Nitroglycerin → venodilation → ↓ preload → smaller LV cavity → <b>worse dynamic LVOT obstruction</b> → ↓ cardiac output → syncope. Lecture antianginal table: <b>nitrates are contraindicated in HOCM</b>.<br><br><b>Educational objective:</b> Nitrates can cause syncope in HOCM by lowering preload and worsening dynamic outflow obstruction.",
wrong={0:"Would be correct with a slow ventricular rate or AV block on the ECG.",
1:"Would be correct for valvular aortic stenosis: a delayed, weak carotid upstroke and a murmur that <b>decreases</b> on standing.",
3:"Would be correct for a prodrome after standing or emotion, with a normal heart exam.",
4:"Would be correct with troponin elevation or ischemic ECG changes; troponin is normal."},
eli5="His thick heart muscle partly blocks its own exit when the heart is underfilled. The nitroglycerin pill emptied it further, so less blood got out and he passed out."),

dict(img=None,
stem="A 63-year-old man with ischemic cardiomyopathy and stable angina comes to the office because of a 2-week history of worsening shortness of breath and ankle swelling. Three weeks ago a new cardiovascular drug was added to his aspirin, atorvastatin and isosorbide mononitrate because of persistent angina. His pulse is 52/min, and blood pressure is 108/68 mm Hg. Jugular venous pressure is 12 cm H2O. There are crackles at both lung bases and 2+ pitting edema to the knees. An ECG shows sinus bradycardia with a PR interval of 0.26 seconds. Echocardiography 6 months ago showed a left ventricular ejection fraction of 30%.{FIG}Which of the following drugs was most likely added?",
choices=["Amlodipine","Hydralazine","Ivabradine","Ranolazine","Verapamil"], key=4,
exp="A <b>non-dihydropyridine CCB</b> (verapamil, diltiazem) → ↓ chronotropy, ↓ AV conduction and <b>↓ inotropy</b>. In a patient with <b>EF 30%</b> it precipitates HF decompensation, and here also bradycardia and first-degree AV block. Lecture table: non-DHP side effects = bradycardia, heart block, low EF; contraindications include HFrEF, severe AS and HOCM.<br><br><b>Educational objective:</b> Non-dihydropyridine calcium channel blockers can precipitate heart failure in reduced ejection fraction.",
wrong={0:"Would be correct for edema alone (DHP vasodilation); it doesn't cause bradycardia or AV block and is HF-neutral.",
1:"Would be correct for reflex tachycardia, headache or a lupus-like syndrome; it doesn't slow the heart or AV conduction.",
2:"Would be correct for bradycardia without AV block or negative inotropy (it can cause luminous visual phenomena).",
3:"Would be correct for QTc prolongation; it has no effect on HR, AV conduction or contractility."},
eli5="The new pill slowed his heart and weakened its squeeze, and his heart was already weak, so fluid backed up into his lungs and legs."),

dict(img=None,
stem="A 61-year-old woman with stable angina and normal coronary-artery-bypass grafts on angiography 3 months ago comes for follow-up 2 weeks after starting a new antianginal drug. She has had episodes of brief bright spots and halos in her vision when moving from a dark room into bright light. Her pulse is 58/min (previously 78/min on maximally tolerated bisoprolol), and blood pressure is 132/78 mm Hg, unchanged. Ophthalmologic examination shows no abnormalities.{FIG}The new drug most likely acts by which of the following mechanisms?",
choices=["Blockade of L-type Ca²⁺ channels in arterioles","Blockade of the SA-node HCN funny current","Inhibition of the late inward Na⁺ current","Release of nitric oxide in venous smooth muscle","Selective blockade of β₁-adrenergic receptors"], key=1,
exp="HR fell from 78 to 58 <b>without a change in BP</b>, with <b>luminous phenomena (phosphenes)</b> → <b>ivabradine</b>: blocks <b>HCN channels (the funny current, I<sub>f</sub>)</b> in the SA node → slower diastolic depolarization → ↓ HR without changing contractility or BP. Retinal photoreceptors carry a related HCN current (I<sub>h</sub>), hence the visual effects. The lecture slide mislabeled it as a late Na⁺ inhibitor.<br><br><b>Educational objective:</b> Ivabradine blocks the HCN funny current, slowing HR without changing BP, and can cause luminous visual phenomena.",
wrong={0:"Would be correct (amlodipine) with BP lowering, edema or flushing, not HR slowing.",
2:"Would be correct (ranolazine) with no HR change and possible QTc prolongation.",
3:"Would be correct (nitrates) with headache and orthostatic BP fall.",
4:"Would be correct for adding another β-blocker; she was already maximal, and visual phenomena aren't a β-blocker effect."},
eli5="This drug slows the heart's natural pacemaker by blocking a special channel, and a similar channel in the eye can cause flashes of light."),

dict(img=None,
stem="A 66-year-old man comes to the emergency department 3 hours after the onset of substernal chest pressure that persists at 4/10. His pulse is 82/min, and blood pressure is 142/86 mm Hg. Lungs are clear. ECG shows 1.5-mm horizontal ST-segment depression in leads V3 through V6 that was absent on an ECG 1 year ago; there is no ST elevation in any lead, including V7 through V9. High-sensitivity troponin T rises from 34 to 160 ng/L at 3 hours. Aspirin and sublingual nitroglycerin have been given.{FIG}Which of the following is the most appropriate next step in management?",
choices=["Discharge with an outpatient stress test","Exercise treadmill test in the emergency department","Heparin, P2Y12 load and angiography within 24 h","Intravenous alteplase","Repeat troponin in 24 hours before deciding"], key=2,
exp="<b>NSTEMI</b> (troponin rise + new ST depression, no ST elevation including posterior leads) without very-high-risk features → <b>anticoagulation (heparin), P2Y12 loading (clopidogrel), IV nitroglycerin, admission on the ACS pathway</b> and <b>early invasive angiography (&lt; 24 h)</b>. In the case, the ED repeated the ECG and troponin, did bedside echo, gave O₂/IV NTG/heparin and loaded clopidogrel, then took her for urgent cath.<br><br><b>Educational objective:</b> NSTEMI is treated with anticoagulation, dual antiplatelet loading and early angiography, not fibrinolysis.",
wrong={0:"Would be correct for low-risk chest pain with negative serial troponins and a normal ECG.",
1:"Would be correct for nothing during active ischemia; stress testing is contraindicated.",
3:"Would be correct for STEMI when PCI isn't available within 120 minutes; fibrinolysis doesn't help (and may harm) in NSTEMI.",
4:"Would be correct for nothing: troponin is already rising, and waiting delays treatment."},
eli5="A blood clot is partly blocking a heart artery. Thin the blood, block the platelets and get him to the cath lab within a day; clot-busting drugs are only for the fully blocked (ST-elevation) kind."),

dict(img='A1vsr', cap='Apical four-chamber transthoracic echocardiogram with color Doppler',
stem="A 72-year-old woman comes to the office because of shortness of breath that began abruptly this morning. Three days ago she was discharged after an inferior non-ST-elevation myocardial infarction treated with stenting of the right coronary artery. She cannot lie flat. Her pulse is 130/min, respirations are 24/min, and blood pressure is 100/60 mm Hg. There are crackles at both lung bases. A loud holosystolic murmur is heard at the left lower sternal border with a palpable thrill. An ECG shows sinus tachycardia without new ST-segment elevation. Echocardiography is shown. Pulmonary artery catheterization shows an oxygen saturation of 62% in the right atrium and 81% in the pulmonary artery.{FIG}Which of the following is the most likely diagnosis?",
choices=["Free-wall rupture with tamponade","Left ventricular aneurysm","Papillary muscle rupture","Postinfarction pericarditis","Stent thrombosis","Ventricular septal rupture"], key=5,
exp="Abrupt HF 3–5 days after MI, a <b>holosystolic murmur at the LSB with a thrill</b>, color Doppler flow across the interventricular septum, and an <b>O₂ step-up from RA (62%) to PA (81%)</b> → left-to-right shunt → <b>ventricular septal rupture</b>. This is the lecture's case. Next: ICU, stabilization (afterload reduction, mechanical support), surgical repair. Critical diagnostic tests: <b>ECG and echo</b>.<br><br><b>Educational objective:</b> A new LSB holosystolic murmur with a thrill and an oxygen step-up after MI is ventricular septal rupture.",
wrong={0:"Would be correct for sudden PEA/tamponade without a murmur, usually after an anterior MI.",
1:"Would be correct for persistent ST elevation and HF weeks later, without an acute shunt.",
2:"Would be correct for an <b>apical</b> holosystolic murmur radiating to the axilla, a tall v wave and <b>no</b> O₂ step-up.",
3:"Would be correct for pleuritic pain and a friction rub without a new holosystolic murmur.",
4:"Would be correct for recurrent chest pain with new ST elevation in the RCA territory."},
eli5="The heart attack left a hole in the wall between the two pumping chambers, so blood shoots from left to right. That's why oxygen-rich blood shows up on the right side."),

dict(img='Ainfstemi', cap='12-lead ECG on arrival',
stem="A 68-year-old man is admitted after the ECG shown was obtained 90 minutes after the onset of chest pain; the culprit vessel was stented. Four days later he develops sudden severe shortness of breath. His pulse is 118/min, and blood pressure is 86/54 mm Hg. There are crackles throughout both lung fields. A new holosystolic murmur is heard at the apex radiating to the axilla; there is no thrill. Pulmonary artery catheter oxygen saturations are 64% in the right atrium and 65% in the pulmonary artery, and the wedge tracing shows prominent v waves.{FIG}Rupture of which of the following structures is the most likely cause of this patient's deterioration?",
choices=["Anterolateral papillary muscle","Interventricular septum","Left ventricular free wall","Posteromedial papillary muscle","Tricuspid chordae tendineae"], key=3,
exp="The ECG shows <b>ST elevation in II, III and aVF</b> with reciprocal depression in I and aVL → <b>inferior STEMI</b>. Days later: abrupt pulmonary edema, an <b>apical holosystolic murmur to the axilla</b>, tall wedge v waves and <b>no O₂ step-up</b> → acute MR from <b>posteromedial papillary muscle rupture</b>. It's 3× more likely than anterolateral because it has a <b>single blood supply</b> (PDA). Lecture: ~80% within 7 days of inferior STEMI; surgery lowers mortality to ~30%.<br><br><b>Educational objective:</b> Acute MR after an inferior MI is usually from posteromedial papillary muscle rupture.",
wrong={0:"Would be correct after an anterolateral infarct, but its dual LAD + circumflex supply makes rupture rare.",
1:"Would be correct for an LSB murmur with a thrill and an O₂ step-up.",
2:"Would be correct for tamponade and PEA without a regurgitant murmur.",
4:"Would be correct for a right-sided murmur that increases with inspiration and giant v waves in the <b>jugular</b> (RA) pulse."},
eli5="The inferior heart attack killed the little muscle that holds the mitral valve shut. It snapped, the valve flops open, and blood rushes backward into the lungs."),

dict(img=None,
stem="A 26-year-old man comes to the office to establish care. He has no history of serious illness and takes no medications. One year ago his blood pressure was 120/80 mm Hg. Today it is 200/110 mm Hg and 198/112 mm Hg on repeat measurement with an appropriate cuff after 5 minutes of rest. He has no headache, visual change, chest pain or dyspnea. His pulse is 76/min.{FIG}Which of the following is the most appropriate next step in management?",
choices=["Assess for acute target-organ damage","Begin an intravenous nitroprusside infusion","Measure the aldosterone-to-renin ratio today","Order renal artery duplex ultrasonography","Recheck BP in 6 months with lifestyle advice"], key=0,
exp="Lecture pearl 2: <b>BP &gt; 180/120 → look for organ damage first</b>: fundoscopy, focused neuro and cardiopulmonary exam, ECG, creatinine and urinalysis (± troponin if symptomatic). Acute TOD = <b>hypertensive emergency</b> (ICU, IV therapy); none = <b>severe HTN</b>, treated orally with close follow-up. <b>Then pursue the cause</b>: age &lt; 30 and abrupt onset are both red flags for secondary HTN.<br><br><b>Educational objective:</b> In severe hypertension, first assess for acute target-organ damage to separate an emergency from severe HTN.",
wrong={1:"Would be correct for a <b>hypertensive emergency</b> with documented acute organ damage.",
2:"Would be correct soon, as a secondary work-up, but not before excluding an emergency.",
3:"Would be correct later if renovascular disease were suspected (bruit, rising creatinine on ACEi).",
4:"Would be correct for stage 1 HTN with low risk, not 200/110 in a 26-year-old."},
eli5="A pressure this high could already be hurting the brain, heart, kidneys or eyes. Check those first to decide whether it's an emergency, then hunt for why a young person has it."),

dict(img=None,
stem="Patient Information\nAge: 74 years · Gender: M · Site of Care: emergency department\n\nHistory\nReason for Visit: sudden shortness of breath at night\nHistory of Present Illness: second episode in 3 months of abrupt nocturnal dyspnea requiring admission; BP control lost over the past 6 months despite 4 drugs\nPast Medical History: coronary artery disease with stent 4 years ago; peripheral artery disease; 50 pack-years of smoking\nMedications: amlodipine, chlorthalidone, carvedilol, lisinopril (started 3 weeks ago)\n\nPhysical Examination\nT 36.9°C (98.4°F) · P 92/min · R 26/min · BP 196/104 mm Hg\nLungs: crackles throughout\nAbdomen: systolic–diastolic bruit in the left upper quadrant\nExtremities: no edema\n\nDiagnostic Studies\nCreatinine: 2.1 mg/dL (1.4 mg/dL 1 month ago)\nK⁺: 3.4 mEq/L\nEchocardiography: left ventricular ejection fraction 60%, concentric hypertrophy\n\nQuestion:{FIG}Which of the following is the most likely cause of this patient's hypertension?",
choices=["Atherosclerotic renal artery stenosis","Cushing syndrome","Fibromuscular dysplasia","Obstructive sleep apnea","Pheochromocytoma","Primary aldosteronism"], key=0,
exp="Lecture (secondary HTN by age): in adults <b>≥ 65</b> the leading cause is <b>atherosclerotic renal artery stenosis</b>. Clues: diffuse atherosclerosis (CAD, PAD, heavy smoking), loss of BP control on 4 drugs, <b>flash pulmonary edema</b> with preserved EF, an <b>abdominal bruit</b>, and creatinine rising &gt; 30% after starting an ACE inhibitor (the stenotic kidney depends on angiotensin II-mediated efferent constriction).<br><br><b>Educational objective:</b> Resistant HTN with flash pulmonary edema, an abdominal bruit and an ACEi-related creatinine rise in an older vasculopath suggests atherosclerotic renal artery stenosis.",
wrong={1:"Would be correct with central obesity, striae, proximal weakness and hyperglycemia.",
2:"Would be correct for a young woman (19–39) without atherosclerosis.",
3:"Would be correct with snoring, daytime sleepiness and obesity; it doesn't explain the bruit or creatinine rise.",
4:"Would be correct with paroxysms of headache, sweating and palpitations.",
5:"Would be correct with spontaneous marked hypokalemia and suppressed renin, without flash edema or ACEi-related azotemia."},
eli5="Clogged arteries all over his body include the one to his kidney. The kidney thinks blood pressure is low and cranks it up, and an ACE inhibitor makes that kidney struggle."),

dict(img=None,
stem="A 74-year-old man with resistant hypertension, flash pulmonary edema and an abdominal bruit is found to have a 90% stenosis of the left renal artery on duplex ultrasonography. He takes amlodipine and carvedilol only; lisinopril and chlorthalidone were discontinued 2 months ago. Serum potassium is 3.3 mEq/L.\n\nPlasma renin activity | Plasma aldosterone{FIG}Which of the following sets of findings is most likely in this patient?",
choices=["Decreased, decreased","Decreased, increased","Increased, decreased","Increased, increased"], key=3,
exp="Renal artery stenosis → ↓ renal perfusion → juxtaglomerular cells release <b>renin</b> → angiotensin II → <b>aldosterone</b>: <b>secondary hyperaldosteronism (↑R, ↑A)</b>, with hypokalemia and HTN. Lecture: read the renin. ↑R/↑A = renovascular or diuretics; ↓R/↑A = primary aldosteronism; ↓R/↓A = Liddle, licorice, CAH, Cushing.<br><br><b>Educational objective:</b> Renovascular hypertension produces secondary hyperaldosteronism with high renin and high aldosterone.",
wrong={0:"Would be correct for Liddle syndrome or licorice (apparent mineralocorticoid excess).",
1:"Would be correct for <b>primary</b> aldosteronism (autonomous adrenal secretion).",
2:"Would be correct for primary adrenal insufficiency, with hyperkalemia and hypotension."},
eli5="The narrowed artery makes the kidney think blood pressure is low, so it pumps out renin, which drives the salt-keeping hormone up too."),

dict(img=None,
stem="A 45-year-old man comes to the office because of a 2-month history of headaches and leg cramps. His blood pressure is 172/104 mm Hg, previously normal. He drinks 1.5 L daily of an imported herbal tea flavored with natural licorice root. Serum potassium is 2.9 mEq/L, and bicarbonate is 32 mEq/L. Plasma renin activity and plasma aldosterone are both suppressed. Serum cortisol at 8 AM is 14 μg/dL, and there are no cushingoid features.{FIG}Which of the following is the most likely mechanism of this patient's hypertension?",
choices=["ACTH-driven excess of adrenal cortisol","Autonomous adrenal aldosterone secretion","Gain-of-function mutation in the ENaC channel","Inhibition of 11β-HSD type 2 in the kidney","Loss of 11β-hydroxylase activity"], key=3,
exp="Licorice (glycyrrhetinic acid) <b>inhibits 11β-HSD2</b> in the collecting duct → cortisol is no longer converted to inactive cortisone → <b>cortisol activates the mineralocorticoid receptor</b> → ↑ ENaC/ROMK → Na⁺ retention, HTN, <b>hypokalemic alkalosis</b> with <b>suppressed renin AND aldosterone</b> (<b>apparent mineralocorticoid excess</b>). Lecture: ↓R/↓A = Liddle, licorice/AME, Cushing, CAH.<br><br><b>Educational objective:</b> Licorice causes apparent mineralocorticoid excess by inhibiting 11β-HSD2, with low renin and low aldosterone.",
wrong={0:"Would be correct for Cushing disease, with cushingoid features and high cortisol.",
1:"Would be correct for primary aldosteronism, where aldosterone is <b>high</b>.",
2:"Would be correct for Liddle syndrome: a family history, onset in youth, no licorice exposure.",
4:"Would be correct for CAH (11-deoxycorticosterone excess) with virilization and early onset."},
eli5="Licorice blocks the enzyme that switches off cortisol in the kidney, so ordinary cortisol acts like the salt hormone even though real aldosterone is low."),

dict(img=None,
stem="A 17-year-old boy is evaluated because of hypertension discovered at a sports physical. His father and paternal aunt developed hypertension before age 30. His blood pressure is 156/98 mm Hg. He does not consume licorice or take any medications. Physical examination shows no abnormalities. Serum studies show:\n\nNa⁺: 141 mEq/L\nK⁺: 6.0 mEq/L\nCl⁻: 112 mEq/L\nHCO₃⁻: 18 mEq/L\nCreatinine: 0.8 mg/dL\n\nPlasma renin activity and plasma aldosterone are both low. The hypertension and hyperkalemia correct fully with low-dose hydrochlorothiazide.{FIG}Which of the following is the most likely diagnosis?",
choices=["Apparent mineralocorticoid excess","Bartter syndrome","Gitelman syndrome","Gordon syndrome","Liddle syndrome","Primary aldosteronism"], key=3,
exp="Low-renin HTN algorithm (lecture slide): low renin + low aldosterone + young age/family history → <b>hyperkalemia and hyperchloremic metabolic acidosis?</b> Yes → <b>Gordon syndrome</b> (pseudohypoaldosteronism type 2): WNK kinase mutations → <b>overactive thiazide-sensitive NCC</b> → Na⁺ retention with less distal Na⁺ for K⁺/H⁺ exchange → HTN + ↑K⁺ + acidosis, <b>exquisitely thiazide-sensitive</b>. No → Liddle, AME, CAH.<br><br><b>Educational objective:</b> Familial HTN with hyperkalemia, hyperchloremic acidosis and suppressed renin and aldosterone that responds to thiazides is Gordon syndrome.",
wrong={0:"Would be correct for <b>hypo</b>kalemic alkalosis with low renin and aldosterone (11β-HSD2 deficiency).",
1:"Would be correct for <b>normotensive</b> hypokalemic alkalosis with high renin (NKCC2 defect).",
2:"Would be correct for <b>normotensive</b> hypokalemic alkalosis with low Mg²⁺ and hypocalciuria (NCC loss of function).",
4:"Would be correct for familial HTN with <b>hypo</b>kalemic alkalosis responding to amiloride.",
5:"Would be correct for <b>high</b> aldosterone with hypokalemia."},
eli5="A gene makes his kidney's thiazide-target pump work overtime, so he holds onto salt and can't get rid of potassium or acid. A thiazide pill fixes it."),

dict(img=None,
stem="A 50-year-old woman with hypertension controlled on atenolol and amlodipine is screened for primary aldosteronism because of an incidentally found 1-cm adrenal nodule. Morning seated laboratory studies on an unrestricted diet show:\n\nK⁺: 4.3 mEq/L\nPlasma renin activity: 0.2 ng/mL/h (N=0.6–4.3)\nPlasma aldosterone: 7 ng/dL (N=4–31)\nAldosterone-to-renin ratio: 35\n\nShe has no symptoms.{FIG}Which of the following is the most appropriate next step?",
choices=["Adrenal venous sampling","Repeat the ratio after replacing atenolol","Start spironolactone for presumed PA","Surgical removal of the adrenal nodule"], key=1,
exp="Lecture pearls: the ARR is <b>only meaningful when renin is suppressed and aldosterone is inappropriately non-suppressed</b>; <b>β-blockers lower renin → false-positive ratio</b>. Here aldosterone is only 7 ng/dL (below the usual ≥ 10 threshold), and the high ratio is driven by a β-blocker-suppressed renin. Repeat testing after switching atenolol to a non-interfering drug (α-blocker, non-DHP CCB or hydralazine).<br><br><b>Educational objective:</b> A high ARR from a β-blocker-suppressed renin with low aldosterone is a likely false positive; retest off the β-blocker.",
wrong={0:"Would be correct only after PA is confirmed and the patient wants surgery.",
2:"Would be correct for confirmed bilateral PA, not an unconfirmed, likely false-positive screen.",
3:"Would be correct for a lateralized aldosterone-producing adenoma confirmed by AVS."},
eli5="Her blood pressure pill pushed renin so low that the ratio looks high even though aldosterone is normal. Swap the pill and test again before doing anything else."),

dict(img=None,
stem="A 55-year-old man with primary aldosteronism confirmed by saline suppression testing undergoes adrenal CT, which shows normal-appearing adrenal glands. Adrenal venous sampling with cosyntropin shows a lateralization index of 1.4 (no lateralization). He has no family history of early hypertension, and dexamethasone does not suppress his aldosterone.{FIG}Which of the following is the most likely subtype of this patient's primary aldosteronism?",
choices=["Aldosterone-producing adenoma","Aldosterone-producing adrenocortical carcinoma","Bilateral idiopathic adrenal hyperplasia","Glucocorticoid-remediable aldosteronism","Unilateral adrenal hyperplasia"], key=2,
exp="No lateralization on AVS with normal CT → <b>bilateral idiopathic hyperplasia</b>, the <b>most common subtype (~60%)</b> (adenoma ~30%, unilateral hyperplasia 2%, carcinoma &lt; 1%, familial forms &lt; 6%). Treatment: <b>medical</b>, sodium restriction + spironolactone (eplerenone if gynecomastia), amiloride second line. Dr. Segal: you wouldn't remove both adrenals and commit the patient to lifelong steroid replacement.<br><br><b>Educational objective:</b> Primary aldosteronism without lateralization is most often bilateral idiopathic hyperplasia, treated with an MRA.",
wrong={0:"Would be correct with lateralization on AVS (index > 4) to a single gland.",
1:"Would be correct for a large (> 4 cm) heterogeneous mass, often co-secreting cortisol or androgens.",
3:"Would be correct (FH type I) with early-onset familial HTN and aldosterone that <b>suppresses with dexamethasone</b>.",
4:"Would be correct with lateralization to one gland but no discrete adenoma."},
eli5="Both adrenal glands are a bit overactive, so neither one can be removed to fix it. Instead he takes a pill that blocks the hormone."),

dict(img=None,
stem="Investigators compare 3,800 patients with primary aldosteronism with 9,500 patients with essential hypertension matched for age, sex and blood pressure. Over follow-up they calculate odds ratios for cardiovascular and renal complications.{FIG}Which of the following complications is most likely to show the greatest increase in patients with primary aldosteronism?",
choices=["Atrial fibrillation","Congestive heart failure","Coronary artery disease","Left ventricular hypertrophy","Stroke"], key=0,
exp="Lecture (Monticone meta-analysis): vs BP-matched essential HTN, PA carries an excess risk of <b>atrial fibrillation OR 3.52</b>, proteinuria 2.68, stroke 2.58, LVH 2.29, HF 2.05, CAD 1.77. Aldosterone damages the myocardium, endothelium and kidney <b>beyond the BP number</b>: \"Treat the aldosterone excess, not just the reading.\"<br><br><b>Educational objective:</b> Primary aldosteronism carries excess CV risk beyond BP, greatest for atrial fibrillation (OR about 3.5).",
wrong={1:"Would be correct if the outcome were HF; its OR (~2.0) is smaller than AF's.",
2:"Would be correct for the <b>smallest</b> of the listed excesses (OR ~1.8), not the largest.",
3:"Would be correct for a moderate excess (OR ~2.3), less than AF.",
4:"Would be correct as the second-tier excess (OR ~2.6), below AF."},
eli5="Too much aldosterone scars the heart's upper chambers, so these patients get an irregular heartbeat about three and a half times as often as people with ordinary high blood pressure."),
]
