# Application Session 2 (Segal/Scully/Qazi HF cases + Segal PAD case) — Version 1, 18 items (4 with images). NBME house style (2026-10-07).
Q = [
dict(img='Aedema', cap='The lower legs before and after pressure',
stem="A 55-year-old man comes to the office because of a 6-week history of progressive swelling of both legs and foamy urine. He has no shortness of breath, orthopnea or paroxysmal nocturnal dyspnea. His pulse is 76/min, and blood pressure is 134/84 mm Hg. Jugular venous pressure is 6 cm H2O. Lungs are clear to auscultation. Heart sounds are normal without S3. The legs are shown. Serum studies show an albumin of 1.9 g/dL, normal liver enzymes and a total bilirubin of 0.6 mg/dL. Urinalysis shows 4+ protein. NT-proBNP is within the reference range.{FIG}Which of the following is the most likely mechanism of this patient's edema?",
choices=["Decreased plasma oncotic pressure","Increased capillary hydrostatic pressure","Increased capillary permeability","Increased interstitial oncotic pressure","Obstruction of lymphatic drainage"], key=0,
exp="Dr. Segal: think about edema by <b>Starling forces</b>, not organs. Heavy proteinuria → <b>hypoalbuminemia (1.9)</b> → <b>↓ plasma oncotic pressure</b> → fluid leaves capillaries → pitting edema (\"salt and water trapped in the interstitium\"). Nephrotic syndrome, like cirrhosis and protein-losing states, sits in this bucket. Heart failure (the most common cause overall) raises <b>capillary hydrostatic pressure</b>, but his JVP is normal, his lungs are clear and his NT-proBNP is normal.<br><br><b>Educational objective:</b> Nephrotic-range proteinuria causes edema by lowering plasma oncotic pressure.",
wrong={1:"Would be correct for heart failure: raised JVP, crackles, S3 or a high natriuretic peptide.",
2:"Would be correct for sepsis, burns or angioedema (leaky capillaries).",
3:"Would be correct for protein-rich lymphedema or local inflammation, not generalized pitting edema with hypoalbuminemia.",
4:"Would be correct for lymphedema: non-pitting, often unilateral, after surgery or radiation."},
eli5="He is losing protein in his urine, and that protein normally holds water inside blood vessels. Without it, water leaks into his legs."),

dict(img=None,
stem="A 68-year-old man with heart failure with reduced ejection fraction (ejection fraction 30%) comes for follow-up 8 weeks after enalapril was replaced by sacubitril/valsartan. His dyspnea has improved from NYHA class III to class II, and his weight is 2 kg lower. His pulse is 64/min, and blood pressure is 112/70 mm Hg. Jugular venous pressure is 6 cm H2O. Lungs are clear, and there is no edema. Plasma B-type natriuretic peptide (BNP), 380 pg/mL before the switch, is now 520 pg/mL.{FIG}Which of the following is the most appropriate next step in evaluating this patient's heart failure status?",
choices=["Measure plasma NT-proBNP","Obtain a chest x-ray","Repeat BNP in 2 weeks","Right heart catheterization","Switch back to enalapril"], key=0,
exp="Sacubitril inhibits <b>neprilysin</b>, which normally <b>degrades BNP</b> → plasma BNP rises as a <b>drug effect</b>, even when the patient improves. <b>NT-proBNP</b> is the inert 76-amino-acid fragment, <b>not cleared by neprilysin</b>, so it tracks the real wall stress. Dr. Segal: knowing this can be your decision tree when choosing which peptide to order. Clinically he is better (NYHA II, euvolemic).<br><br><b>Educational objective:</b> In patients on sacubitril/valsartan, monitor NT-proBNP rather than BNP.",
wrong={1:"Would be correct for suspected congestion or a new pulmonary process; he is euvolemic on exam.",
2:"Would be correct only if BNP were interpretable; on an ARNI it stays raised regardless.",
3:"Would be correct for unclear hemodynamics or transplant evaluation, not a stable outpatient.",
4:"Would be correct for ARNI intolerance (angioedema, hypotension), not a misleading lab."},
eli5="His new pill stops the body breaking down BNP, so BNP looks high even though he's better. Its sister marker, NT-proBNP, isn't affected, so check that instead."),

dict(img='A2ecg', cap='12-lead ECG',
stem="A 60-year-old woman comes to the office because of a 3-week history of progressive shortness of breath with exertion, two-pillow orthopnea and ankle swelling. She has type 2 diabetes mellitus, hypertension and obesity. Her pulse is 60/min, and blood pressure is 150/86 mm Hg; BMI is 33 kg/m2. Jugular venous pressure is 7 cm H2O. There are crackles at both lung bases. There is 1+ pitting edema to the mid-tibia. Her ECG is shown. Echocardiography shows a left ventricular ejection fraction of 65% with increased wall thickness and a normal cavity size.{FIG}Cardiac auscultation is most likely to reveal which of the following?",
choices=["Fixed splitting of S2","Midsystolic click","Opening snap after S2","Presystolic sound before S1","Early diastolic sound after S2"], key=3,
exp="The case patient: HTN + diabetes + obesity → <b>concentric LVH</b> (ECG voltage, preserved EF 65%) → a <b>stiff, non-compliant ventricle</b> → the atrial kick into that ventricle produces an <b>S4</b> (presystolic, just before S1). Session discussion: <b>S4 = non-compliant ventricle</b>; <b>S3</b> = filling of a volume-overloaded (often dilated, low-EF) ventricle, or normal in the young. Her exam on the slides: +S4, no S3.<br><br><b>Educational objective:</b> HFpEF with concentric LVH produces an S4 from atrial contraction into a stiff ventricle.",
wrong={0:"Would be correct for an atrial septal defect.",
1:"Would be correct for mitral valve prolapse.",
2:"Would be correct for rheumatic mitral stenosis.",
4:"Would be correct for an <b>S3</b>: a dilated, volume-overloaded ventricle, typically with reduced EF."},
eli5="Her heart wall is thick and stiff, so when the top chamber gives its final push, it makes an extra thud just before the normal 'lub.'"),

dict(img=None,
stem="A 72-year-old woman is evaluated for exertional dyspnea of 4 months' duration. Her BMI is 36 kg/m2. Her hypertension is treated with three drugs. She has paroxysmal atrial fibrillation. Echocardiography shows a left ventricular ejection fraction of 62%, an estimated pulmonary artery systolic pressure of 32 mm Hg, and an E/e′ ratio of 11. The physician calculates her H₂FPEF score.{FIG}Which of the following is this patient's score?",
choices=["4","6","7","8","9"], key=3,
exp="H₂FPEF: <b>H</b>eavy (BMI &gt; 30) = <b>2</b> · <b>H</b>ypertensive (≥ 2 drugs) = <b>1</b> · Atrial <b>F</b>ibrillation = <b>3</b> · <b>P</b>ulmonary HTN (PASP &gt; 35) = 0 (hers is 32) · <b>E</b>lder (&gt; 60) = <b>1</b> · <b>F</b>illing pressure (E/e′ &gt; 9) = <b>1</b> → 2 + 1 + 3 + 0 + 1 + 1 = <b>8</b> (&gt; 95% probability of HFpEF).<br><br><b>Educational objective:</b> H₂FPEF weights obesity 2, AF 3, and HTN, PASP > 35, age > 60 and E/e′ > 9 one point each.",
wrong={0:"Would be correct if AF scored 1 point instead of 3 (and the age point were missed).",
1:"Would be correct if the age and filling-pressure points were both omitted.",
2:"Would be correct if one of the 1-point items (age or E/e′) were missed.",
4:"Would be correct if her PASP (32) had exceeded 35 mm Hg."},
eli5="Add up: heavy 2, blood-pressure pills 1, atrial fibrillation 3, older than 60 gives 1, stiff-filling measurement 1. That's 8, so heart failure with a normal pumping strength is almost certain."),

dict(img=None,
stem="A 70-year-old man with heart failure with preserved ejection fraction has taken oral furosemide 40 mg each morning for 5 months. His weight fell by 4 kg in the first 3 weeks and has since stabilized despite persistent 2+ ankle edema and good adherence. His dietary sodium intake has not changed. He has normal intestinal absorption of oral drugs. Serum creatinine is stable at 1.0 mg/dL, and serum potassium is 4.1 mEq/L.{FIG}Which of the following best explains the diminishing diuretic response?",
choices=["Distal tubule hypertrophy raising Na⁺ reabsorption","Hypokalemia blunting tubular response to ADH","Loss of NKCC2 transporters in the thick ascending limb","Reduced filtered sodium load from falling GFR"], key=0,
exp="The <b>braking phenomenon</b> (diuretic tolerance): sustained loop-diuretic exposure delivers more Na⁺ distally → the <b>distal convoluted tubule hypertrophies</b> and reabsorbs more (e.g. 10–15% → 20–25% of the filtered load). Add <b>post-diuretic Na⁺ retention</b>: furosemide (\"Lasix lasts six\" hours) → ~6 h of natriuresis, then ~18 h of avid reabsorption. Fix: add a <b>thiazide</b> (sequential nephron blockade) or split or IV dosing.<br><br><b>Educational objective:</b> Loop diuretic tolerance (braking) is mainly from distal tubular hypertrophy and post-diuretic Na⁺ retention.",
wrong={1:"Would be correct for <b>nephrogenic DI</b> with dilute polyuria and low K⁺; his K⁺ is 4.1.",
2:"Would be correct for nothing physiologic: the transporter target isn't lost; distal compensation is the issue.",
3:"Would be correct with a rising creatinine (cardiorenal); his is stable at 1.0."},
eli5="The kidney adapts: the part after the loop grows stronger and grabs back the salt the water pill made it lose."),

dict(img=None,
stem="A 66-year-old woman with heart failure is admitted for volume overload. Oral metolazone is added to intravenous furosemide. Four days later she has lost 7 kg. Serum studies show:\n\nNa⁺: 136 mEq/L\nK⁺: 2.9 mEq/L\nCl⁻: 88 mEq/L\nHCO₃⁻: 34 mEq/L\n\nArterial pH is 7.51. She takes no other medications, and she has had no vomiting or diarrhea.{FIG}Which of the following is the primary mechanism of her potassium loss?",
choices=["Direct inhibition of ROMK channels","Increased distal Na⁺ delivery to principal cells","Inhibition of carbonic anhydrase in the proximal tubule","Intracellular K⁺ shift from insulin release"], key=1,
exp="Dr. Scully: both loop and thiazide diuretics leave more Na⁺ in the lumen → <b>principal cells</b> reabsorb it through <b>ENaC</b> (up-regulated, plus aldosterone from volume contraction) → the lumen becomes <b>negative</b> → <b>K⁺ secreted via ROMK</b> and <b>H⁺</b> secreted by intercalated cells → <b>hypokalemic metabolic alkalosis</b> (pH 7.51, HCO₃⁻ 34). With no vomiting, this is renal loss, not GI.<br><br><b>Educational objective:</b> Loop and thiazide diuretics waste K⁺ and H⁺ through increased distal Na⁺ delivery to the principal cell.",
wrong={0:"Would be correct for <b>hyper</b>kalemia (ROMK blockade retains K⁺).",
2:"Would be correct for acetazolamide: <b>metabolic acidosis</b> (bicarbonaturia), not alkalosis.",
3:"Would be correct for a transcellular shift (insulin, β₂-agonists), which doesn't cause alkalosis or renal loss."},
eli5="When the water pills send extra salt downstream, the kidney swaps it for potassium and acid, so she pees out potassium and acid and her blood turns alkaline."),

dict(img=None,
stem="A 62-year-old man with heart failure with preserved ejection fraction and type 2 diabetes mellitus is started on empagliflozin. Two weeks later his serum creatinine has risen from 1.10 to 1.24 mg/dL, and his edema has decreased. His blood pressure is 128/76 mm Hg. Hemoglobin A1c decreases from 7.6% to 7.2% at 3 months. The physician explains that the small creatinine rise reflects a protective hemodynamic change in the kidney.{FIG}Which of the following best explains this change?",
choices=["Afferent arteriolar vasoconstriction","Efferent arteriolar vasodilation","Increased proximal glucose reabsorption","Reduced renal blood flow from hypotension"], key=0,
exp="SGLT2 inhibition → less proximal Na⁺/glucose reabsorption → <b>↑ NaCl at the macula densa</b> → <b>tubuloglomerular feedback</b> → <b>afferent arteriolar constriction</b> → ↓ intraglomerular pressure (a small, expected GFR dip) → long-term renal protection. Session: SGLT2i are natriuretic; they lower A1c only ~0.5%, so the HF benefit isn't about glucose.<br><br><b>Educational objective:</b> SGLT2 inhibitors lower intraglomerular pressure via tubuloglomerular feedback and afferent vasoconstriction.",
wrong={1:"Would be correct for ACE inhibitors and ARBs (↓ angiotensin II at the efferent arteriole).",
2:"Would be correct for the <b>opposite</b>: SGLT2i <b>reduce</b> proximal glucose reabsorption (glucosuria).",
3:"Would be correct with low BP or over-diuresis; his BP is 128/76."},
eli5="The drug makes the kidney's salt sensor think it's getting too much salt, so it gently tightens the inflow vessel, lowering pressure in the kidney's filters and protecting them."),

dict(img='A2cxr', cap='Chest x-ray, PA view',
stem="A 70-year-old man with ischemic cardiomyopathy (left ventricular ejection fraction 35%) is brought to the emergency department because of a 4-week history of progressive shortness of breath. He drinks 4 beers daily. His pulse is 84/min and irregular, respirations are 24/min, and blood pressure is 110/70 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 90%. Jugular venous pressure is 12 cm H2O. There are crackles halfway up both lung fields. His chest x-ray is shown; short horizontal linear opacities extend to the pleural surface at both lung bases.{FIG}The basal linear opacities most likely represent fluid within which of the following structures?",
choices=["Alveolar air spaces","Bronchial walls","Interlobular septa","Pleural space","Pulmonary veins"], key=2,
exp="Short, horizontal lines at the lung bases reaching the pleura = <b>Kerley B lines</b>: <b>interstitial edema thickening the interlobular septa</b>, which Dr. Segal called \"very characteristic of heart failure.\" Rising pulmonary venous pressure → cephalization → interstitial edema (Kerley lines, peribronchial cuffing) → alveolar edema (bat-wing) and effusions.<br><br><b>Educational objective:</b> Kerley B lines are fluid-thickened interlobular septa from interstitial pulmonary edema.",
wrong={0:"Would be correct for alveolar edema: fluffy perihilar \"bat-wing\" opacities and air bronchograms.",
1:"Would be correct for <b>peribronchial cuffing</b> (ring-like thickening around end-on bronchi).",
3:"Would be correct for a pleural effusion: blunted costophrenic angles and a meniscus.",
4:"Would be correct for <b>cephalization</b> (distended upper-lobe vessels), not basal horizontal lines."},
eli5="Fluid backed up from the weak heart is filling the thin walls between the lung's little compartments, which show up as short white lines at the bottom of the lungs."),

dict(img=None,
stem="A 52-year-old man with heart failure with reduced ejection fraction is brought to the emergency department 2 hours after smoking crack cocaine. His medications are furosemide and metoprolol succinate. He has severe dyspnea and diaphoresis. His pulse is 88/min, and blood pressure is 204/118 mm Hg. There are crackles over all lung fields. An ECG shows sinus rhythm with a QRS duration of 96 msec and no ST-segment elevation. Serum creatine kinase and troponin are within the reference ranges.{FIG}Which of the following best explains his marked hypertension despite β-blockade?",
choices=["Blockade of cardiac Na⁺ channels","Unopposed α₁-adrenergic vasoconstriction","Unopposed β₁ inotropic stimulation","α₂-mediated reduction in sympathetic tone"], key=1,
exp="Cocaine <b>blocks norepinephrine reuptake</b> → catecholamines persist at α₁ and β₁ receptors. Dr. Scully: with a <b>β₁-selective blocker (metoprolol)</b> on board, the heart-rate and inotropic effects are blunted, but <b>α₁-mediated vasoconstriction is unopposed</b> → ↑ systemic vascular resistance → ↑ <b>afterload</b> (\"the one thing you don't want to increase in heart failure\"). Carvedilol and labetalol block both α and β.<br><br><b>Educational objective:</b> Cocaine with a β₁-selective blocker leaves α₁ vasoconstriction unopposed and raises afterload.",
wrong={0:"Would be correct for QRS widening and wide-complex arrhythmias (local anesthetic effect); his QRS is 96 msec.",
2:"Would be correct without β-blockade; metoprolol blunts β₁ effects (pulse only 88).",
3:"Would be correct for <b>lowering</b> BP (clonidine-like central effect), not raising it."},
eli5="Cocaine floods the body with adrenaline. His heart pill blocks the heart-speeding part, but the blood-vessel-squeezing part has nothing stopping it, so his pressure shoots up."),

dict(img=None,
stem="Patient Information\nAge: 74 years · Gender: M · Site of Care: emergency department\n\nHistory\nReason for Visit: confusion and shortness of breath\nHistory of Present Illness: 5 days of worsening dyspnea and orthopnea; urine output low today; family notes confusion since this morning\nPast Medical History: ischemic cardiomyopathy, left ventricular ejection fraction 20%\nMedications: sacubitril/valsartan, carvedilol, spironolactone, dapagliflozin, furosemide\n\nPhysical Examination\nT 36.4°C (97.5°F) · P 112/min · R 26/min · BP 82/58 mm Hg · SpO₂ 91% on room air\nNeck: JVP 16 cm H₂O\nLungs: crackles to the mid-lung fields\nExtremities: cool, mottled; capillary refill 5 seconds; 2+ edema\n\nDiagnostic Studies\nCreatinine: 2.4 mg/dL (1.3 mg/dL 1 month ago)\nLactate: 4.1 mmol/L\n\nQuestion:{FIG}In addition to diuresis in the intensive care unit, the most appropriate pharmacotherapy has which of the following mechanisms of action?",
choices=["α₁-adrenergic receptor agonism","β₁-adrenergic receptor agonism","β₁-adrenergic receptor blockade","Nitric oxide release in venous smooth muscle","SGLT2 inhibition"], key=1,
exp="Congestion (↑ JVP, crackles, edema) + hypoperfusion (cool mottled skin, confusion, oliguria, rising creatinine, lactate 4.1, narrow pulse pressure) = <b>wet and cold</b> (Forrester) = <b>cardiogenic shock</b> → <b>ICU</b> and an <b>inotrope</b>: ↑ contractility → ↑ CO → perfusion. <b>Dobutamine</b> = β₁ agonist (milrinone = PDE3 inhibitor). Lecture: cold–wet patients need inotropes plus decongestion; never start or up-titrate a β-blocker while decompensated.<br><br><b>Educational objective:</b> Wet-and-cold (cardiogenic shock) acute HF requires an inotrope such as the β₁ agonist dobutamine.",
wrong={0:"Would be correct for distributive shock (phenylephrine); pure α₁ agonism raises afterload in a failing LV.",
2:"Would be correct for chronic compensated HFrEF; it is negatively inotropic in shock.",
3:"Would be correct for wet–<b>warm</b> HF with adequate BP (nitroglycerin); his SBP is 82.",
4:"Would be correct for chronic GDMT, which is held during shock."},
eli5="His heart is too weak to push blood out (cold) and fluid is backing up (wet), so he needs a drip that makes the heart squeeze harder."),

dict(img=None,
stem="A 64-year-old woman is ready for discharge after 5 days of intravenous diuresis for her first admission with heart failure. Echocardiography shows a left ventricular ejection fraction of 28%. She is now at her dry weight, without orthopnea or edema. She takes oral furosemide. Her pulse is 84/min, and blood pressure is 114/70 mm Hg. Serum potassium is 4.2 mEq/L, and estimated GFR is 58 mL/min/1.73 m2.{FIG}Which of the following is the most appropriate pharmacologic plan before discharge?",
choices=["Continue furosemide alone and reassess in 6 months","Start enalapril plus sacubitril/valsartan together","Start low doses of all four GDMT pillars","Start metoprolol tartrate twice daily only","Start sacubitril/valsartan; others in 3 months"], key=2,
exp="She is <b>compensated (near euvolemia)</b> with adequate BP, K⁺ and eGFR → start <b>quadruple GDMT</b> (ARNI + evidence-based β-blocker + MRA + SGLT2i) at <b>low doses, before discharge</b>, then titrate within 4–6 weeks with labs. Dr. Qazi: start everything in hospital because outpatient follow-up is unreliable; educate with the family; follow up in 7–10 days. All four together: HR 0.36 vs 0.84 for ACEi + BB; ~5 years longer survival.<br><br><b>Educational objective:</b> Once a patient with new HFrEF is euvolemic, start all four GDMT pillars at low doses before discharge.",
wrong={0:"Would be correct for nothing: withholding GDMT forfeits large mortality benefit.",
1:"Would be correct for nothing: ACEi + neprilysin inhibitor → <b>angioedema</b>; a 36-hour washout is required.",
3:"Would be correct for nothing: tartrate lacks the mortality evidence (use succinate, carvedilol or bisoprolol).",
4:"Would be correct for the old sequential approach; delays cost lives (\"avoid delays\")."},
eli5="Now that the fluid is off, start all four heart-protecting pills at small doses before she goes home, because each one adds years."),

dict(img=None,
stem="A 48-year-old man is admitted because of a 3-week history of progressive shortness of breath, leg swelling and numbness of both feet. He drinks 1 L of vodka daily and eats little. His pulse is 112/min, and blood pressure is 128/48 mm Hg. His extremities are warm with bounding pulses. Jugular venous pressure is 14 cm H2O, there are crackles at both lung bases, and there is 3+ pitting edema. Vibration sense is decreased in both feet. Right heart catheterization shows a cardiac output of 9.2 L/min and low systemic vascular resistance. Serum thyroid-stimulating hormone is 2.0 μU/mL, and there is no arteriovenous fistula or murmur.{FIG}Which of the following is the most likely cause of this patient's heart failure?",
choices=["Alcohol-induced dilated cardiomyopathy","Cocaine cardiotoxicity","Hyperthyroidism","Thiamine deficiency","Viral myocarditis"], key=3,
exp="<b>High-output HF</b> (CO 9.2, ↓ SVR, warm skin, bounding pulses, wide pulse pressure) + peripheral neuropathy + malnutrition in heavy drinking → <b>wet beriberi (thiamine deficiency)</b> → ↓ pyruvate dehydrogenase → peripheral vasodilation. Lecture: alcohol harms the heart directly (dilated CM) <b>and</b> via thiamine deficiency. High-output causes: thyrotoxicosis, AV fistula, severe obesity, beriberi.<br><br><b>Educational objective:</b> Heavy drinking with high-output HF and neuropathy suggests wet beriberi from thiamine deficiency.",
wrong={0:"Would be correct for <b>low</b>-output HF with a dilated, poorly contracting LV and normal-to-high SVR.",
1:"Would be correct with cocaine use, HTN, chest pain or ischemia.",
2:"Would be correct with a <b>suppressed</b> TSH; his is 2.0.",
4:"Would be correct after a viral prodrome with troponin rise and <b>low</b> output."},
eli5="Drinking without eating used up his vitamin B1, which makes blood vessels relax wide open, so his heart pumps hard but still can't keep up, and his nerves suffer too."),

dict(img=None,
stem="Investigators review meta-analyses of individual guideline-directed medical therapies in heart failure with reduced ejection fraction, each compared with placebo or standard therapy on a background of contemporaneous care. They tabulate the relative risk reduction in all-cause mortality for each class.{FIG}Which of the following drug classes showed the largest relative reduction in mortality?",
choices=["ACE inhibitor","β-Blocker","Mineralocorticoid receptor antagonist","SGLT2 inhibitor"], key=1,
exp="Lecture table (four pillars): relative risk reduction in mortality / HF hospitalization: <b>β-blocker 35% / 41%</b>, MRA 30% / 35%, switching ACEi → ARNI 28% / 21%, ACEi/ARB 17% / 31%, SGLT2i 17% / 31%. Together: CV death or HF hospitalization HR 0.84 (ACEi + BB) → <b>0.36</b> (ARNI + BB + MRA + SGLT2i).<br><br><b>Educational objective:</b> Among individual HFrEF pillars, β-blockers show the largest relative mortality reduction (~35%).",
wrong={0:"Would be correct for a smaller mortality benefit (~17%).",
2:"Would be correct for second place (~30%).",
3:"Would be correct for ~17% mortality, with larger benefit on hospitalization."},
eli5="All four heart-failure pill families help, but β-blockers cut the death rate the most on their own, and using all four together helps far more."),

dict(img=None,
stem="A 71-year-old woman with heart failure with reduced ejection fraction (ejection fraction 25%) was hospitalized 6 weeks ago for decompensation. She takes maximally tolerated doses of sacubitril/valsartan, metoprolol succinate, spironolactone and dapagliflozin. Her pulse is 66/min, and blood pressure is 108/68 mm Hg. A drug is added that increases cyclic GMP in vascular smooth muscle and myocardium, acting on its target enzyme independently of nitric oxide and also sensitizing it to endogenous nitric oxide.{FIG}Which of the following best describes the mechanism of the added drug?",
choices=["Inhibition of neprilysin","Inhibition of phosphodiesterase 5","Inhibition of soluble guanylate cyclase","Stimulation of soluble guanylate cyclase"], key=3,
exp="<b>Vericiguat</b>: a <b>soluble guanylate cyclase (sGC) stimulator</b>. It directly stimulates sGC and sensitizes it to endogenous NO → ↑ cGMP → vasodilation and less myocardial remodeling, which restores the NO–sGC–cGMP pathway. It's used after a recent worsening-HF event on top of GDMT. <b>Slide 38 called it an \"inhibitor\"; it is a stimulator.</b><br><br><b>Educational objective:</b> Vericiguat stimulates soluble guanylate cyclase to raise cGMP in HFrEF.",
wrong={0:"Would be correct for sacubitril (↑ natriuretic peptides → particulate GC → cGMP); she already takes it.",
1:"Would be correct for sildenafil (blocks cGMP breakdown, not its production).",
2:"Would be correct for the slide's wording, but inhibiting sGC would <b>lower</b> cGMP."},
eli5="This new pill turns up the enzyme that makes a relaxing signal molecule in the heart and blood vessels, even when the body's own trigger is weak."),

dict(img=None,
stem="A 71-year-old man comes to the office because of a 1-year history of pain in both buttocks and thighs when walking more than 2 blocks. The pain also occurs when he stands at the sink for 15 minutes and does not improve if he stops walking and remains standing. It improves after he sits for several minutes or leans forward on a shopping cart, and he can walk farther uphill than on level ground. Dorsalis pedis and posterior tibial pulses are 2+ bilaterally. Ankle–brachial index is 1.08 on both sides. Straight-leg raise is negative.{FIG}Which of the following is the most likely diagnosis?",
choices=["Chronic venous insufficiency","Lumbar spinal stenosis","Peripheral artery disease","Popliteal artery entrapment","Thromboangiitis obliterans"], key=1,
exp="Pain with <b>standing</b> as well as walking, <b>not relieved by standing still</b>, relieved by <b>sitting or flexion</b> (\"<b>shopping-cart sign</b>\"), easier <b>uphill</b> (leaning forward) and a <b>normal ABI</b> with full pulses → <b>neurogenic claudication</b> from lumbar spinal stenosis. Extension lets the hypertrophic ligamentum flavum compress the cauda equina. Dr. Segal: \"Boards love this question.\"<br><br><b>Educational objective:</b> Leg pain relieved by flexion or sitting, not standing still, with a normal ABI is neurogenic claudication.",
wrong={0:"Would be correct for aching, heavy legs with edema, varicosities and medial-malleolus ulcers.",
2:"Would be correct for reproducible exertional calf pain relieved within minutes by standing still, with ↓ pulses and an ABI ≤ 0.90.",
3:"Would be correct for a young athlete with calf claudication and pulses that disappear on plantar flexion.",
4:"Would be correct for a young male smoker with distal digital ischemia and ulcers."},
eli5="Standing straight pinches the nerves in his lower back, and bending forward opens the space. That's why a shopping cart and walking uphill help while his leg arteries are fine."),

dict(img='A2rubor', cap='Both feet, with the patient sitting with legs dependent',
stem="A 78-year-old woman with type 2 diabetes mellitus and a 60-pack-year smoking history comes to the office because of a 5-week history of burning pain in the right foot that wakes her at night and improves when she hangs her leg over the side of the bed. Her feet with the legs hanging are shown. When the right leg is elevated to 60 degrees for 1 minute, the foot becomes pale; the redness returns within 30 seconds of lowering it. The foot is cool, and the dorsalis pedis and posterior tibial pulses are not palpable. Her temperature is 36.8°C (98.2°F). There is no warmth, induration or tenderness of the skin.{FIG}Which of the following is the most likely diagnosis?",
choices=["Acute limb ischemia","Cellulitis","Chronic limb-threatening ischemia","Diabetic peripheral neuropathy","Intermittent claudication"], key=2,
exp="<b>Rest pain ≥ 2 weeks</b>, worse lying flat and better with the leg dependent, with <b>dependent rubor</b> and <b>elevation pallor</b> (Buerger test), a cool foot and absent pulses → <b>chronic limb-threatening ischemia</b>: \"the unstable angina of PAD.\" Dr. Segal's island patient had been treated for \"cellulitis.\" Rubor <b>fades with elevation</b>; cellulitis doesn't, and has warmth, tenderness and induration.<br><br><b>Educational objective:</b> Rest pain for ≥ 2 weeks with dependent rubor and elevation pallor is chronic limb-threatening ischemia.",
wrong={0:"Would be correct for sudden onset (< 2 weeks) with the 6 Ps.",
1:"Would be correct with warmth, induration, tenderness, fever, and redness that persists on elevation.",
3:"Would be correct for burning pain with <b>intact</b> pulses and stocking sensory loss, without positional color change.",
4:"Would be correct for exertional pain relieved by rest, not pain at rest at night."},
eli5="So little blood reaches her foot that it hurts even lying in bed. Gravity helps blood flow down when she dangles her leg, which turns the foot red."),

dict(img=None,
stem="A 69-year-old man with exertional right calf pain undergoes noninvasive arterial testing. Systolic pressures are:\n\nRight brachial: 150 mm Hg\nLeft brachial: 138 mm Hg\nRight dorsalis pedis: 70 mm Hg\nRight posterior tibial: 78 mm Hg{FIG}Which of the following is the right ankle–brachial index?",
choices=["0.47","0.51","0.52","0.57","0.92"], key=2,
exp="<b>ABI = highest ankle pressure on that side ÷ highest brachial pressure</b> = 78 (PT) ÷ 150 (right arm) = <b>0.52</b> → PAD (≤ 0.90), moderate obstruction (0.41–0.70). Sensitivity ~90% and specificity ~95% for a ≥ 50% stenosis. An ABI &gt; 1.40 means non-compressible vessels → toe–brachial index.<br><br><b>Educational objective:</b> Ankle–brachial index uses the higher ankle pressure on that side and the higher of the two arm pressures.",
wrong={0:"Would be correct using the <b>lower</b> ankle pressure (70 ÷ 150).",
1:"Would be correct using the lower ankle and the lower arm (70 ÷ 138).",
3:"Would be correct using the <b>lower</b> arm pressure (78 ÷ 138).",
4:"Would be correct for the arm-to-arm ratio (138 ÷ 150), which flags a subclavian difference, not the ABI."},
eli5="Divide the stronger ankle pressure by the stronger arm pressure: 78 ÷ 150 ≈ 0.52, about half of normal."),

dict(img=None,
stem="A 66-year-old man comes to the office because of an 8-month history of cramping in both calves after walking 2 blocks, relieved within 3 minutes of standing still. He has ischemic cardiomyopathy with a left ventricular ejection fraction of 30%, and he quit smoking 1 year ago. His medications are aspirin, atorvastatin 80 mg, sacubitril/valsartan, carvedilol, spironolactone and dapagliflozin. Ankle–brachial index is 0.68 on the right and 0.72 on the left. There are no ulcers, and he has no rest pain.{FIG}Which of the following is the most appropriate next step to improve his walking distance?",
choices=["Cilostazol","Endovascular stenting","Pentoxifylline","Supervised exercise therapy","Surgical bypass"], key=3,
exp="Lifestyle-limiting claudication without limb threat → <b>supervised exercise therapy</b> (first line, 30–45 min ≥ 3×/week for ≥ 12 weeks; Medicare-covered) plus risk-factor management. Dr. Segal: exercise grows <b>collaterals</b>. <b>Cilostazol</b> (PDE3 inhibitor) also helps walking but carries a <b>boxed warning: contraindicated in heart failure of any severity</b>. Pentoxifylline has no role.<br><br><b>Educational objective:</b> Supervised exercise is first-line for claudication; cilostazol is contraindicated in heart failure.",
wrong={0:"Would be correct for claudication <b>without</b> heart failure, after or alongside exercise.",
1:"Would be correct for disabling claudication that fails exercise and medical therapy, or for limb-threatening disease.",
2:"Would be correct for nothing: no benefit (guideline Class 3).",
4:"Would be correct for CLTI or failed conservative therapy, depending on anatomy."},
eli5="Regular supervised walking grows new little detour arteries around the blockages. The usual walking pill is off-limits because it's dangerous with a weak heart."),
]
