# Cardiac Cycle & Valve Hemodynamics (Qazi) — Version 2, 18 items (6 with images). NBME house style (2026-10-06).
Q = [
dict(img='Cms', cap='Simultaneous left heart pressures at catheterization (blue = left ventricle, green = aorta, red = left atrium)',
stem="A 38-year-old woman comes to the office because of an 8-month history of shortness of breath with exertion and episodes of a racing heartbeat. She had joint pains and a heart murmur during an illness at age 12. Her pulse is 92/min and regular, and blood pressure is 110/72 mm Hg. The point of maximal impulse is not displaced. Pressures recorded at catheterization are shown.{FIG}Auscultation at the apex is most likely to reveal which of the following?",
choices=["Early diastolic decrescendo blowing murmur","Holosystolic murmur radiating to the axilla","Midsystolic click with a late systolic murmur","Opening snap with a low-pitched diastolic rumble","Systolic crescendo–decrescendo murmur with S4"], key=3,
exp="The red LA curve stays <b>above</b> the blue LV curve throughout diastole (shaded) → <b>diastolic LA–LV gradient</b> → <b>mitral stenosis</b>, likely rheumatic. Lecture buzzwords: a <b>rumbling diastolic murmur at the apex, always with an opening snap</b>. The snap is the stiff valve opening once LV pressure falls below the high LA pressure. The LV is underfilled, so the impulse isn't displaced.<br><br><b>Educational objective:</b> An LA–LV diastolic gradient is mitral stenosis: opening snap plus apical diastolic rumble.",
wrong={0:"Would be correct for aortic regurgitation: low aortic diastolic pressure and a wide pulse pressure.",
1:"Would be correct for mitral regurgitation: a tall v wave with no diastolic gradient.",
2:"Would be correct for mitral valve prolapse, which has no diastolic gradient.",
4:"Would be correct for aortic stenosis: an LV–aortic systolic gradient. LV and aortic peaks are superimposed here."},
eli5="The top chamber's pressure stays higher than the bottom chamber's while it's trying to fill it, so the door between them is narrowed. That makes a snap and a rumble."),

dict(img='Cmr', cap='Left ventricular, aortic and left atrial (dotted) pressures at catheterization',
stem="A 55-year-old man comes to the office because of a 2-year history of progressive shortness of breath with exertion and intermittent palpitations. His pulse is 84/min, and blood pressure is 124/76 mm Hg. Jugular venous pressure is 6 cm H2O. The point of maximal impulse is displaced laterally. Right atrial pressure is 5 mm Hg, and right and left ventricular diastolic pressures differ by 14 mm Hg. Left heart pressures are shown.{FIG}Which of the following is the most likely diagnosis?",
choices=["Aortic regurgitation","Aortic stenosis","Constrictive pericarditis","Mitral regurgitation","Mitral stenosis","Tricuspid regurgitation"], key=3,
exp="The dotted LA curve rises steeply during systole into a <b>tall v wave</b> that approaches LV pressure. That is the lecture's exam phrase: \"tall v wave = <b>mitral regurgitation</b>.\" The LA fills from the pulmonary veins <i>plus</i> the systolic regurgitant jet. The extra volume returns to the LV → high preload → LV dilation (eccentric hypertrophy) → laterally displaced impulse. Aortic and LV systolic peaks overlap (no stenosis), and aortic diastolic pressure is normal.<br><br><b>Educational objective:</b> A tall v wave on the left atrial (wedge) tracing indicates mitral regurgitation.",
wrong={0:"Would be correct if aortic diastolic pressure fell steeply (wide pulse pressure).",
1:"Would be correct if LV systolic pressure far exceeded aortic systolic pressure.",
2:"Would be correct if diastolic pressures equalized across chambers; they differ by 14 mm Hg.",
4:"Would be correct for a persistent diastolic LA–LV gradient; the curves overlap in diastole here.",
5:"Would be correct for a giant v wave on the <b>right</b> atrial/jugular tracing with raised venous pressure; his RA pressure is 5 mm Hg."},
eli5="Each squeeze shoots some blood backward into the top-left chamber, so its pressure spikes up. That spike is the tall v wave."),

dict(img='Car', cap='Simultaneous left heart pressures (blue = left ventricle, green = aorta, red = left atrium)',
stem="A 34-year-old man comes to the office because of a 6-month history of shortness of breath with exertion and an uncomfortable awareness of his heartbeat when lying on his left side. He had infective endocarditis 3 years ago treated with intravenous antibiotics. His pulse is 66/min, and blood pressure is 162/50 mm Hg. Pressures recorded at catheterization are shown.{FIG}Palpation of this patient's carotid and radial pulses is most likely to show which of the following?",
choices=["Alternating strong and weak beats","Bifid pulse with a spike-and-dome contour","Bounding pulse that collapses abruptly","Fall in amplitude with inspiration","Weak, delayed carotid upstroke"], key=2,
exp="LV and aortic systolic peaks are superimposed, but aortic pressure plunges in diastole → <b>wide pulse pressure</b> (162/50) → <b>aortic regurgitation</b>, here a sequel of endocarditis (in her practice, the lecturer's commonest setting). Large stroke volume plus rapid runoff in two directions → <b>bounding, \"water-hammer\" (Corrigan) pulses</b>. Lecture: diastolic murmur + bounding pulses = AR.<br><br><b>Educational objective:</b> Aortic regurgitation produces bounding pulses that rise and collapse abruptly, with a wide pulse pressure.",
wrong={0:"Would be correct for <b>pulsus alternans</b> in severe LV systolic dysfunction.",
1:"Would be correct for hypertrophic cardiomyopathy with dynamic outflow obstruction.",
3:"Would be correct for <b>pulsus paradoxus</b> in cardiac tamponade.",
4:"Would be correct for aortic stenosis (pulsus parvus et tardus), which shows an LV–aortic systolic gradient."},
eli5="A big squirt of blood goes out with each beat, then leaks back and runs off fast. The pulse feels like a hammer that slaps up and falls away."),

dict(img='Casx', cap='Chamber pressures (mm Hg) and outflow: normal heart (left) and this patient (right)',
stem="A 73-year-old man comes to the office because of a 6-month history of shortness of breath and chest tightness when he climbs stairs. He has no history of hypertension. His pulse is 68/min, and blood pressure is 110/70 mm Hg. Carotid upstrokes are weak and delayed. Chamber pressures measured at catheterization are compared with normal values in the figure. An ECG shows increased QRS voltage, and cardiac MRI shows no infiltrative pattern.{FIG}Which of the following best describes the cellular adaptation in this patient's left ventricle?",
choices=["Interstitial amyloid deposition","Myocyte disarray with septal predominance","Myocyte hyperplasia","Sarcomeres added in parallel","Sarcomeres added in series"], key=3,
exp="LV 200/25 versus aorta 110/70 → a 90 mm Hg systolic gradient across a narrowed aortic valve → <b>pressure overload</b>. To normalize wall stress (Laplace), myocytes add <b>sarcomeres in parallel</b> → thicker fibers → <b>concentric hypertrophy</b>: a thick wall with a normal-sized cavity. Lecture: myocardial hypertrophy is \"never normal\"; the thick wall is stiff (diastolic dysfunction, LA 25) and has high O₂ demand (angina).<br><br><b>Educational objective:</b> Pressure overload (aortic stenosis) causes concentric hypertrophy by adding sarcomeres in parallel.",
wrong={0:"Would be correct for cardiac amyloidosis: a thick wall with low ECG voltage and an infiltrative MRI pattern. Both are normal here.",
1:"Would be correct for hypertrophic cardiomyopathy: a younger patient with asymmetric septal hypertrophy and dynamic obstruction.",
2:"Would be correct for no adult myocardial response. Adult cardiomyocytes enlarge but don't divide.",
4:"Would be correct for <b>volume</b> overload (aortic or mitral regurgitation): eccentric hypertrophy with a dilated cavity."},
eli5="Pushing against a narrow exit makes each heart muscle cell add more contracting units side by side, so the wall gets thick, like a weightlifter's muscle."),

dict(img='Cph', cap='Simultaneous left heart pressures, left ventricular volume, ECG and heart sounds in one cardiac cycle',
stem="A physiology instructor shows the recording to a group of students and points to the gray shaded interval that begins at about 0.37 seconds, just after the second heart sound. During this interval left ventricular volume is constant at about 50 mL while left ventricular pressure falls from about 100 mm Hg toward 10 mm Hg.{FIG}Which of the following valve events ends this interval?",
choices=["Aortic valve closure","Aortic valve opening","Mitral valve closure","Mitral valve opening","Pulmonic valve closure"], key=3,
exp="This band is <b>isovolumetric relaxation</b> (phase 5). It <b>begins</b> with aortic (and pulmonic) valve closure, which is S2 and the dicrotic notch. All valves are then closed and LV pressure falls at constant volume (ESV). It <b>ends</b> when LV pressure drops below LA pressure → <b>mitral valve opens</b> → rapid filling begins. In mitral stenosis this moment produces the opening snap.<br><br><b>Educational objective:</b> Isovolumetric relaxation ends when left ventricular pressure falls below left atrial pressure and the mitral valve opens.",
wrong={0:"Would be correct for the event that <b>begins</b> the interval (S2, the dicrotic notch), not the one that ends it.",
1:"Would be correct for the end of isovolumetric <b>contraction</b> (the other shaded band).",
2:"Would be correct for the <b>start</b> of isovolumetric contraction (S1).",
4:"Would be correct for a right-sided event that also marks the start, not the end, of relaxation."},
eli5="After the exit door slams (the \"dub\"), the chamber relaxes with every door shut. That ends when the inlet door from the top chamber swings open."),

dict(img='Cph', cap='Simultaneous left heart pressures, left ventricular volume, ECG and heart sounds in one cardiac cycle',
stem="A 70-year-old man with long-standing hypertension and left ventricular hypertrophy is studied in the cardiac physiology laboratory. On the recording shown, the interval numbered 1 on the top axis accompanies the a wave on the left atrial curve and a final rise in left ventricular volume, with a fourth heart sound.{FIG}This interval and its heart sound would be absent if the patient developed which of the following rhythms?",
choices=["Atrial fibrillation","First-degree atrioventricular block","Right bundle branch block","Sinus bradycardia","Sinus tachycardia"], key=0,
exp="Interval 1 is <b>atrial systole</b>: the P wave → atrial contraction → the a wave → the last top-up of LV volume (the <b>atrial kick</b>, ~20–25% of output per the lecture). In a stiff, hypertrophied LV that kick produces an <b>S4</b>. <b>Atrial fibrillation</b> has no organized atrial contraction → no a wave, no kick and no S4. That is why AF so often decompensates stiff ventricles.<br><br><b>Educational objective:</b> Atrial fibrillation abolishes atrial systole: no a wave, no atrial kick and no S4.",
wrong={1:"Would be correct only for a delay. A long PR interval keeps atrial contraction (and the S4), just earlier relative to S1.",
2:"Would be correct for a widely split S2 (delayed pulmonic closure); atrial contraction is unaffected.",
3:"Would be correct for lengthening diastasis (phase 7); atrial systole is preserved.",
4:"Would be correct for shortening diastole, diastasis first. The atria still contract."},
eli5="That first slot is the top chambers giving a final push. In atrial fibrillation the top chambers just quiver and never push, so that slot and its thud disappear."),

dict(img=None,
stem="Two women with rheumatic mitral stenosis are examined on the same day. Both are in sinus rhythm with a heart rate of 72/min and have a normal aortic valve. Phonocardiography shows that the interval between the aortic component of S2 and the opening snap is 0.10 seconds in patient X and 0.04 seconds in patient Y.{FIG}Compared with patient X, patient Y most likely has a higher value of which of the following?",
choices=["Aortic diastolic pressure","Cardiac output","Left atrial pressure","Left ventricular end-diastolic pressure","Mitral valve area"], key=2,
exp="After aortic closure (A2), LV pressure falls during isovolumetric relaxation until it drops below LA pressure → the stiff mitral valve snaps open. The <b>higher the LA pressure</b>, the sooner LV pressure crosses it → <b>shorter A2–opening snap interval</b> → <b>more severe stenosis</b> (Board add-on, UWorld). Severe mitral stenosis = valve area ≤ 1.5 cm².<br><br><b>Educational objective:</b> A shorter A2–opening snap interval means higher left atrial pressure and more severe mitral stenosis.",
wrong={0:"Would be correct only if A2 timing were the variable; the snap timing depends on LA, not aortic, pressure.",
1:"Would be correct for <b>milder</b> stenosis. Cardiac output falls as the orifice narrows.",
3:"Would be correct for left-sided volume overload; in mitral stenosis the LV is underfilled and its diastolic pressure low.",
4:"Would be correct for patient X, whose longer interval means a larger, less stenotic orifice."},
eli5="The higher the pressure piled up behind the narrow valve, the sooner it pops open after the \"dub,\" so a shorter gap means a tighter valve."),

dict(img=None,
stem="A 45-year-old woman with rheumatic mitral stenosis (valve area 1.2 cm2) is evaluated 1 day after the onset of palpitations. She has no history of hypertension, diabetes mellitus, stroke, or vascular disease. Her pulse is 88/min and irregularly irregular, and blood pressure is 118/74 mm Hg. An ECG shows atrial fibrillation. Echocardiography shows an enlarged left atrium without visible thrombus. Serum creatinine concentration is 0.8 mg/dL. Rate control with metoprolol is started.{FIG}Which of the following is the most appropriate antithrombotic therapy?",
choices=["Apixaban","Aspirin","Clopidogrel","No antithrombotic therapy","Rivaroxaban","Warfarin"], key=5,
exp="Mitral stenosis → high LA pressure → <b>LA enlargement</b> → atrial fibrillation with stagnant LA blood → a very high thromboembolic risk. Board add-on (UWorld): anticoagulate <b>every</b> patient with AF due to moderate-to-severe rheumatic mitral stenosis; the CHA₂DS₂-VASc score does not apply. A <b>vitamin K antagonist (warfarin)</b> is preferred over direct oral anticoagulants because it is more effective in this setting. β-blockade also lengthens diastolic filling time.<br><br><b>Educational objective:</b> Atrial fibrillation with rheumatic mitral stenosis requires anticoagulation with warfarin, regardless of risk score.",
wrong={0:"Would be correct for non-valvular atrial fibrillation; in rheumatic mitral stenosis it is less effective than warfarin.",
1:"Would be correct for no current AF indication; antiplatelet therapy doesn't prevent LA thrombus.",
2:"Would be correct after coronary stenting, not for atrial thromboembolism.",
3:"Would be correct for non-valvular AF with a CHA₂DS₂-VASc of 0–1, a score that doesn't apply in mitral stenosis.",
4:"Would be correct for non-valvular atrial fibrillation; it is inferior to warfarin in rheumatic mitral stenosis."},
eli5="A narrow mitral valve makes blood sit still in a big, quivering top chamber, where clots form easily. The old blood thinner warfarin works best here."),

dict(img=None,
stem="A 77-year-old woman is brought to the emergency department 30 minutes after she fainted while walking briskly up a ramp. She regained consciousness within 1 minute and had no incontinence or confusion. She has had exertional shortness of breath for 4 months. Her pulse is 70/min and regular, and blood pressure is 112/86 mm Hg; there is no orthostatic change. A harsh systolic murmur at the right upper sternal border radiates to both carotid arteries and does not increase with the Valsalva maneuver. ECG monitoring for 24 hours shows sinus rhythm without pauses or arrhythmias.{FIG}Which of the following is the most likely mechanism of this patient's syncope?",
choices=["Dynamic outflow obstruction from reduced preload","Fixed cardiac output with exercise vasodilation","Paroxysmal high-grade atrioventricular block","Reflex vagal bradycardia with vasodilation","Venous pooling with impaired vasoconstriction"], key=1,
exp="Aortic stenosis = a <b>fixed outflow obstruction</b>. During exercise, muscle arterioles dilate (↓ peripheral resistance), but the narrowed valve prevents cardiac output from rising → BP falls → cerebral hypoperfusion → <b>exertional syncope</b>. Lecture order: exercise intolerance → angina → exertional syncope → heart failure. A narrow pulse pressure (112/86) and carotid radiation fit.<br><br><b>Educational objective:</b> Exertional syncope in aortic stenosis results from a fixed cardiac output that can't match exercise-induced vasodilation.",
wrong={0:"Would be correct for hypertrophic cardiomyopathy, whose murmur gets louder with Valsalva; hers doesn't.",
2:"Would be correct with pauses or heart block on monitoring; the rhythm stayed sinus.",
3:"Would be correct for vasovagal syncope with a prodrome after standing or a trigger, not during exertion.",
4:"Would be correct for orthostatic hypotension; there was no orthostatic change."},
eli5="Exercise opens the leg blood vessels wide, but a narrowed exit valve can't let more blood out to fill them. Blood pressure drops and she faints."),

dict(img=None,
stem="Patient Information\nAge: 84 years · Gender: M · Site of Care: office\n\nHistory\nReason for Visit: getting tired on walks\nHistory of Present Illness: 4 months of fatigue and breathlessness on his usual 2-mile walk, which includes a hill; now stops halfway; one episode of chest pressure on the hill that resolved with rest\nPast Medical History: hyperlipidemia\nMedications: atorvastatin\nPsychosocial History: retired engineer; does not smoke\n\nPhysical Examination\nT 36.8°C (98.2°F) · P 66/min · R 16/min · BP 118/80 mm Hg\nNeck: carotid upstrokes are weak and delayed\nHeart: harsh, late-peaking systolic crescendo–decrescendo murmur at the right second intercostal space radiating to the neck; soft S2; the murmur decreases with sustained handgrip and does not increase with the Valsalva maneuver\nLungs: clear\n\nDiagnostic Studies\nECG: sinus rhythm; left ventricular hypertrophy\n\nQuestion:{FIG}Which of the following is the most likely diagnosis?",
choices=["Aortic regurgitation","Aortic stenosis","Hypertrophic cardiomyopathy","Mitral regurgitation","Pulmonic stenosis","Ventricular septal defect"], key=1,
exp="An elderly man with <b>exercise intolerance first</b> (\"I get really exhausted walking up that hill\"), then exertional angina; a <b>systolic crescendo–decrescendo murmur at the right 2nd intercostal space</b> radiating to the carotids; <b>blunted carotid upstrokes</b>. This is calcific (age-related) <b>aortic stenosis</b>. Severity clues from the lecture: a <b>late-peaking</b> murmur and a <b>soft S2</b>.<br><br><b>Educational objective:</b> Exertional fatigue with a late-peaking crescendo–decrescendo murmur at the right upper sternal border and delayed carotid upstrokes is severe aortic stenosis.",
wrong={0:"Would be correct for a diastolic decrescendo murmur with bounding pulses.",
2:"Would be correct for a murmur that <b>increases</b> with Valsalva, in a younger patient with brisk (not delayed) carotids.",
3:"Would be correct for a holosystolic apical murmur radiating to the axilla that <b>increases</b> with handgrip.",
4:"Would be correct for a murmur at the <b>left</b> upper sternal border that increases with inspiration.",
5:"Would be correct for a holosystolic murmur at the left lower sternal border that increases with handgrip."},
eli5="An old, calcified exit valve is narrowed: the murmur is loudest over that valve, and the neck pulse is weak and late."),

dict(img=None,
stem="A 79-year-old woman with exertional angina is evaluated for aortic stenosis. A harsh systolic crescendo–decrescendo murmur peaks in late systole, and the aortic component of S2 is barely audible. Carotid upstrokes are weak and delayed. Left ventricular ejection fraction is 60%.{FIG}Which of the following is the most likely aortic valve area in this patient?",
choices=["3.5 cm2","2.0 cm2","1.3 cm2","0.7 cm2"], key=3,
exp="As stenosis worsens, the LV takes longer to build enough pressure to push blood through → the murmur's peak <b>moves later</b> (more crescendo) and the soft, delayed A2 is muffled. Lecture: a crisp S2 makes severe disease less likely. Severe aortic stenosis (Board add-on): valve area <b>≤ 1.0 cm²</b>, mean gradient ≥ 40 mm Hg, jet velocity ≥ 4 m/s. Normal is ~3–4 cm².<br><br><b>Educational objective:</b> A late-peaking murmur with a soft S2 indicates severe aortic stenosis (valve area ≤ 1.0 cm²).",
wrong={0:"Would be correct for a normal valve with no murmur.",
1:"Would be correct for mild stenosis: an early-peaking murmur with a crisp S2.",
2:"Would be correct for moderate stenosis, where the peak is mid-systolic and S2 still audible."},
eli5="The tighter the exit valve, the longer the heart strains each beat, so the murmur peaks later and drowns out the closing sound."),

dict(img=None,
stem="An 81-year-old man with known severe aortic stenosis (valve area 0.6 cm2) is brought to the emergency department because of chest pressure for 40 minutes. His pulse is 88/min, and blood pressure is 128/78 mm Hg. Five minutes after receiving sublingual nitroglycerin 0.4 mg, he becomes lightheaded; his pulse is 104/min, and blood pressure is 74/48 mm Hg. Heart rhythm remains sinus, and an ECG shows no new ST-segment changes.{FIG}Which of the following best explains the fall in blood pressure?",
choices=["Coronary steal from arteriolar dilation","Decreased preload from venous dilation","Direct negative inotropic effect","Reflex vagal slowing of the heart rate","Sudden increase in valve gradient"], key=1,
exp="Severe aortic stenosis is <b>preload-dependent</b>: the hypertrophied, stiff LV needs ample filling volume to generate the pressure that drives blood across a fixed obstruction. Nitroglycerin → <b>venodilation</b> → ↓ venous return → ↓ preload → ↓ stroke volume, with no way to compensate through the narrowed valve → hypotension. Board add-on (UWorld): avoid nitrates and overdiuresis in severe aortic stenosis.<br><br><b>Educational objective:</b> Nitrates can cause severe hypotension in aortic stenosis by reducing preload in a preload-dependent ventricle.",
wrong={0:"Would be correct for dipyridamole or adenosine-type arteriolar dilators causing ischemia; there are no new ST changes.",
2:"Would be correct for a β-blocker or nondihydropyridine calcium blocker; nitrates aren't negatively inotropic.",
3:"Would be correct for a bradycardic reflex; his pulse rose from 88 to 104.",
4:"Would be correct only if the valve itself changed; the obstruction is fixed."},
eli5="A heart pushing through a tight valve needs a full tank. Nitroglycerin lets blood pool in the veins, so the tank runs low and the pressure crashes."),

dict(img=None,
stem="An investigator records left ventricular, left atrial and aortic pressures with left ventricular volume in a patient with severe chronic mitral regurgitation and normal aortic valve function. Left atrial pressure is 12 mm Hg at the end of diastole, and aortic diastolic pressure is 78 mm Hg.{FIG}Regurgitant flow into the left atrium most likely begins during which of the following phases of the cardiac cycle?",
choices=["Atrial systole","Isovolumetric contraction","Isovolumetric relaxation","Rapid ejection","Reduced ejection"], key=1,
exp="Valve rule: blood flows down its pressure gradient. Once the ventricle contracts, LV pressure exceeds LA pressure (12 mm Hg) almost at once. With an incompetent mitral valve, blood leaks backward <b>immediately</b>, long before LV pressure reaches aortic pressure (78) to open the aortic valve. So the phase that would be isovolumetric contraction is no longer truly isovolumetric (LV volume falls into the LA). Board add-on (AMBOSS): the mitral regurgitation pressure–volume loop has no true isovolumetric phases.<br><br><b>Educational objective:</b> In mitral regurgitation, backflow starts as soon as left ventricular pressure exceeds left atrial pressure, during isovolumetric contraction.",
wrong={0:"Would be correct for forward flow. In atrial systole LA pressure exceeds LV pressure, so blood moves into the LV, not back.",
2:"Would be correct for the end of regurgitation: leak continues until LV pressure falls below LA pressure in relaxation.",
3:"Would be correct if the leak needed the aortic valve open first; it doesn't.",
4:"Would be correct for the late part of the regurgitant period, not its start."},
eli5="The moment the bottom chamber starts squeezing, its pressure beats the top chamber's, so blood starts leaking back right away, even before the main exit door opens."),

dict(img=None,
stem="A 26-year-old woman with mitral valve prolapse is examined in the office. With her squatting, a midsystolic click is followed by a brief late systolic murmur at the apex. She then stands up abruptly.\n\nTiming of click | Duration of murmur{FIG}Which of the following sets of changes is most likely heard after she stands?",
choices=["Earlier, longer","Earlier, shorter","Later, longer","Later, shorter","Unchanged, unchanged"], key=0,
exp="Standing → ↓ venous return → ↓ preload → <b>smaller LV</b>. A smaller ventricle leaves the elongated, myxomatous leaflet relatively redundant, so it prolapses <b>sooner</b> in systole → <b>click earlier</b> and <b>murmur longer</b> (Board add-on). Squatting or handgrip (↑ preload or afterload) does the opposite: click later, murmur shorter. Lecture: midsystolic click + late systolic murmur = mitral valve prolapse; the click is the leaflet and chordae snapping taut.<br><br><b>Educational objective:</b> Maneuvers that shrink the left ventricle (standing, Valsalva) make the prolapse click earlier and the murmur longer.",
wrong={1:"Would be correct only if earlier prolapse shortened the leak. Starting the leak sooner makes the murmur longer.",
2:"Would be correct for no maneuver. Click timing and murmur length move together, so a later click means a shorter murmur.",
3:"Would be correct for squatting or sustained handgrip, which enlarge the LV.",
4:"Would be correct for a fixed lesion such as a ventricular septal defect, not mitral valve prolapse."},
eli5="Standing makes the heart smaller, so the floppy valve flips backward sooner. The click comes earlier and the leak lasts longer."),

dict(img=None,
stem="A 58-year-old man with long-standing mitral valve prolapse comes to the emergency department 2 hours after the sudden onset of severe shortness of breath while lifting a box. His temperature is 37.0°C (98.6°F), pulse is 118/min, respirations are 30/min, and blood pressure is 96/60 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 86%. There are crackles over both lung fields. A soft apical systolic murmur is heard. Two sets of blood cultures obtained 1 hour ago show no growth to date. Echocardiography shows a flail posterior mitral leaflet with a ruptured chord, severe regurgitation, and a normal-sized left ventricle with an ejection fraction of 70%. Intravenous furosemide and nitroprusside are begun.{FIG}Which of the following is the most appropriate next step in management?",
choices=["Discharge with oral furosemide and follow-up","Oral metoprolol and repeat echocardiography","Percutaneous balloon mitral valvuloplasty","Six weeks of empiric intravenous antibiotics","Urgent surgical mitral valve repair"], key=4,
exp="Mitral valve prolapse → progressive chordal stretching → <b>chordal rupture</b> → <b>flail leaflet</b> → a large gap → <b>acute severe mitral regurgitation</b> → pulmonary edema and hypotension. The murmur is soft because the small, non-adapted LA's pressure equalizes quickly with the LV. Lecture: these patients \"need surgery before they go home\"; choose a surgeon likely to <b>repair</b> rather than replace (a repair lasts a lifetime). Afterload reduction only bridges to surgery.<br><br><b>Educational objective:</b> Acute severe mitral regurgitation from chordal rupture needs urgent surgical repair after afterload-reducing stabilization.",
wrong={0:"Would be correct only for compensated chronic regurgitation; he is hypoxic and hypotensive.",
1:"Would be correct for rate control in stable disease; β-blockade worsens acute decompensated regurgitation.",
2:"Would be correct for rheumatic mitral <b>stenosis</b> with pliable leaflets, not regurgitation.",
3:"Would be correct for infective endocarditis with fever and positive cultures; he is afebrile with sterile cultures and a mechanical cause."},
eli5="One of the strings holding his valve shut snapped, so the valve flops open and blood floods back into the lungs. It needs a surgeon to fix the valve soon."),

dict(img=None,
stem="A 63-year-old man with a nonischemic dilated cardiomyopathy comes for follow-up. His left ventricular ejection fraction is 25%. A holosystolic murmur of the same intensity throughout systole is heard at the apex. Echocardiography shows structurally normal, thin mitral leaflets with normal chordae, a dilated mitral annulus, laterally displaced papillary muscles, and a central regurgitant jet. Coronary angiography 1 year ago showed no stenoses.{FIG}Which of the following is the most likely mechanism of this patient's mitral regurgitation?",
choices=["Ischemic tethering of the posterior leaflet","Leaflet perforation by bacterial vegetation","Myxomatous elongation of the leaflets","Rheumatic fusion of the commissures","Dilation of the ventricle and annulus"], key=4,
exp="<b>Secondary (functional) mitral regurgitation</b>: the valve is normal, and the <b>ventricle</b> is the problem. Lecture: the LV is part of the mitral apparatus. A dilated LV → <b>annular dilation</b> and papillary muscle displacement → leaflets can't coapt → a <b>central</b> holosystolic leak. Treatment targets the cardiomyopathy, unlike primary mitral valve prolapse, which is surgically repaired.<br><br><b>Educational objective:</b> In dilated cardiomyopathy, mitral regurgitation is secondary to ventricular and annular dilation with structurally normal leaflets.",
wrong={0:"Would be correct after an inferior MI (posteromedial papillary muscle); his coronaries are normal.",
1:"Would be correct for infective endocarditis with fever and a vegetation; leaflets are normal.",
2:"Would be correct for mitral valve prolapse: thickened, redundant leaflets and a click. His are thin.",
3:"Would be correct for rheumatic disease with thickened, fused leaflets."},
eli5="The valve itself is fine, but the heart around it has stretched so much that the flaps can't reach each other anymore."),

dict(img=None,
stem="A 64-year-old man with chronic severe aortic regurgitation comes to the office because of chest pressure that awakens him from sleep. Exercise tolerance is good. His pulse during sleep is recorded at 48/min. In the office, blood pressure is 150/45 mm Hg, and catheterization shows a left ventricular end-diastolic pressure of 20 mm Hg. Coronary angiography shows no stenoses.{FIG}Which of the following is the best estimate of this patient's coronary perfusion pressure at end-diastole?",
choices=["25 mm Hg","45 mm Hg","60 mm Hg","80 mm Hg","130 mm Hg"], key=0,
exp="Coronary perfusion pressure = <b>aortic diastolic pressure − LV end-diastolic pressure</b> = 45 − 20 = <b>25 mm Hg</b> (Board add-on, UWorld). In aortic regurgitation the aorta loses blood two ways in diastole (back into the LV + forward runoff) → low diastolic pressure, while LVEDP rises from the extra volume. Coronaries fill mainly in diastole, and slow nocturnal heart rates let aortic pressure sink further by end-diastole → <b>nocturnal angina</b> despite clean coronaries.<br><br><b>Educational objective:</b> Coronary perfusion pressure = aortic diastolic − LV end-diastolic pressure, which is low in aortic regurgitation.",
wrong={1:"Would be correct if LVEDP were ignored (aortic diastolic pressure alone).",
2:"Would be correct for mean arterial pressure minus LVEDP: (150 + 2 × 45)/3 = 80, then 80 − 20.",
3:"Would be correct for mean arterial pressure without subtracting LVEDP.",
4:"Would be correct if systolic pressure (150) were used instead of diastolic."},
eli5="Heart arteries fill between beats, pushed by the aorta's low pressure minus the pressure inside the heart. 45 minus 20 leaves only 25, so the heart muscle runs short at night."),

dict(img=None,
stem="A 40-year-old man comes to the office because of a 1-year history of fatigue with exertion. He was told in childhood that he had a two-cusp aortic valve. His pulse is 70/min, and blood pressure is 156/48 mm Hg. Visible carotid pulsations rise and collapse abruptly, and the point of maximal impulse is displaced laterally. The carotid upstrokes are not delayed.\n\nTiming | Best location | Shape{FIG}Which of the following sets of characteristics best describes this patient's murmur?",
choices=["Diastolic, apex, rumble after an opening snap","Diastolic, left sternal border, decrescendo","Systolic, apex to axilla, holosystolic","Systolic, right upper sternal border, crescendo–decrescendo","Systolic, left upper sternal border, crescendo–decrescendo"], key=1,
exp="A bicuspid valve with a <b>wide pulse pressure (156/48)</b>, bounding collapsing pulses and a dilated LV → <b>aortic regurgitation</b> (UWorld: bicuspid valve is the most common cause in resource-rich countries; lecture: many bicuspid patients have mixed disease or pure AR). The murmur is <b>diastolic</b> (lecture), an early diastolic, high-pitched, blowing <b>decrescendo</b> at the <b>left sternal border</b> (Board add-on). Undelayed carotids argue against significant stenosis.<br><br><b>Educational objective:</b> Aortic regurgitation produces an early diastolic decrescendo murmur at the left sternal border with a wide pulse pressure.",
wrong={0:"Would be correct for mitral stenosis, or for an Austin Flint murmur (which lacks an opening snap).",
2:"Would be correct for mitral regurgitation, which has no wide pulse pressure.",
3:"Would be correct for aortic stenosis, the commoner bicuspid lesion, with delayed carotid upstrokes.",
4:"Would be correct for pulmonic stenosis, which increases with inspiration."},
eli5="A two-flap aortic valve that leaks lets blood fall back into the heart right after each beat, making a fading whoosh just after the \"dub.\""),
]
