# Cardiac Cycle & Valve Hemodynamics (Qazi) — Version 1, 18 items (4 with images). NBME house style (2026-10-06).
Q = [
dict(img='Cph', cap='Simultaneous left heart pressures, left ventricular volume, ECG and heart sounds in one cardiac cycle',
stem="An investigator records aortic, left ventricular and left atrial pressures, left ventricular volume, an ECG and a phonocardiogram in a healthy 30-year-old volunteer whose heart rate is 75/min. Two intervals of the cycle are shaded gray in the recording shown.\n\nMitral valve | Aortic valve | Left ventricular volume{FIG}Which of the following sets of findings applies to both shaded intervals?",
choices=["Closed, closed, constant","Closed, closed, decreasing","Closed, open, decreasing","Open, closed, constant","Open, closed, increasing"], key=0,
exp="The two shaded bands are <b>isovolumetric contraction</b> (right after the QRS and S1) and <b>isovolumetric relaxation</b> (right after S2). In both, <b>all four valves are closed</b>, so blood can't enter or leave → <b>volume is flat</b> while pressure changes. Pressure rises in isovolumetric contraction until LV pressure > aortic pressure, which opens the aortic valve. It falls in isovolumetric relaxation until LV pressure < LA pressure, which opens the mitral valve.<br><br><b>Educational objective:</b> During both isovolumetric phases all valves are closed and left ventricular volume is constant; only pressure changes.",
wrong={1:"Would be correct only if blood could escape a sealed chamber. With all valves competent, volume can't fall (in mitral regurgitation there is no true isovolumetric phase).",
2:"Would be correct for ejection (phases 3–4), when the aortic valve is open and volume falls.",
3:"Would be correct for diastasis (phase 7), when the mitral valve is open but filling has nearly stopped.",
4:"Would be correct for rapid filling (phase 6) just after the mitral valve opens."},
eli5="In the two gray strips every door of the heart is shut, so no blood moves in or out. The squeeze or relax just changes the pressure."),

dict(img=None,
stem="A 52-year-old man undergoes left heart catheterization because of exertional chest pain. Simultaneously recorded aortic pressure is 136/82 mm Hg, and mean arterial pressure is 100 mm Hg. Pulmonary capillary wedge pressure is 10 mm Hg, and left ventricular end-diastolic pressure is 10 mm Hg. Echocardiography 1 week earlier showed normal valve structure and function. Coronary angiography shows a 70% stenosis of the left circumflex artery.{FIG}At approximately which of the following left ventricular pressures does the aortic valve open?",
choices=["10 mm Hg","54 mm Hg","82 mm Hg","100 mm Hg","136 mm Hg"], key=2,
exp="A valve opens when the pressure <b>behind</b> it exceeds the pressure <b>in front of</b> it. During isovolumetric contraction LV pressure climbs from its end-diastolic value (10 mm Hg) until it just exceeds <b>aortic diastolic pressure (≈ 82 mm Hg)</b> → aortic valve opens → ejection. LV and aortic pressures then rise together to the systolic peak (136) because a normal valve creates no gradient. The circumflex stenosis is scenery.<br><br><b>Educational objective:</b> The aortic valve opens when left ventricular pressure exceeds aortic diastolic pressure.",
wrong={0:"Would be correct for <b>mitral valve closure</b>: the point where LV pressure first exceeds LA (wedge) pressure.",
1:"Would be correct only if the pulse pressure (136 − 82) were mistaken for the opening pressure.",
3:"Would be correct if mean arterial pressure, rather than the end-diastolic aortic pressure, set the threshold.",
4:"Would be correct for the <b>peak</b> of ejection, reached only after the valve is already open."},
eli5="The door into the aorta opens as soon as the heart pushes harder than the blood already sitting in the aorta, which is the bottom blood-pressure number."),

dict(img=None,
stem="A 71-year-old woman comes to the office because of a 4-month history of shortness of breath when climbing one flight of stairs. She has had hypertension for 25 years and takes amlodipine. Her pulse is 72/min and regular, and blood pressure is 168/94 mm Hg. With the bell of the stethoscope at the apex and the patient in the left lateral decubitus position, a low-pitched sound is heard immediately before S1. The point of maximal impulse is sustained and is not displaced. There is no murmur. An ECG shows sinus rhythm with increased QRS voltage. Echocardiography shows a left ventricular wall thickness of 15 mm, an ejection fraction of 65%, and normal valves.{FIG}Which of the following mechanisms most likely produces the extra sound?",
choices=["Atrial contraction into a stiff ventricle","Delayed closure of the aortic valve","Early rapid filling of a dilated ventricle","Opening of a thickened mitral valve","Sudden tensing of a prolapsing leaflet"], key=0,
exp="A presystolic sound (just <b>before S1</b>) is an <b>S4</b>. Long-standing hypertension → concentric LV hypertrophy → <b>non-compliant ventricle</b> → the atrial kick at end-diastole meets high pressure → vibration. Lecture: S4 = filling against <b>pressure</b>; S3 = filling against <b>volume</b>. An S4 needs an organized atrial contraction, so it disappears in atrial fibrillation (the recording said \"before S2\"; it is before S1).<br><br><b>Educational objective:</b> An S4 comes from atrial contraction into a stiff, hypertrophied left ventricle.",
wrong={1:"Would be correct for a <b>paradoxically split S2</b> (severe aortic stenosis, left bundle branch block), heard at S2, not before S1.",
2:"Would be correct for an <b>S3</b>: early diastole after S2, with a dilated, volume-overloaded ventricle and low ejection fraction.",
3:"Would be correct for an <b>opening snap</b> of mitral stenosis, heard just after S2 with a diastolic rumble.",
4:"Would be correct for the <b>midsystolic click</b> of mitral valve prolapse, between S1 and S2."},
eli5="Her heart wall is thick and stiff. When the top chamber gives its last push, the stiff wall makes a thud right before the normal \"lub\"."),

dict(img=None,
stem="A 58-year-old man comes to the emergency department because of a 3-week history of worsening shortness of breath, two-pillow orthopnea, and ankle swelling. He has a dilated cardiomyopathy. His pulse is 96/min, and blood pressure is 104/68 mm Hg. Jugular venous pressure is 10 cm H2O. There are crackles at both lung bases. The point of maximal impulse is displaced to the anterior axillary line. A low-pitched sound is heard at the apex 0.14 seconds after S2. Echocardiography shows a left ventricular ejection fraction of 20%, a left ventricular end-diastolic volume of 260 mL, and no valvular stenosis.{FIG}The extra sound occurs during which of the following phases of the cardiac cycle?",
choices=["Atrial systole","Diastasis","Isovolumetric contraction","Isovolumetric relaxation","Rapid ventricular filling","Reduced ejection"], key=4,
exp="A sound shortly after S2 in a <b>volume-overloaded, dilated</b> ventricle is an <b>S3</b>. Sequence: S2 (aortic closure) → isovolumetric relaxation (~0.06–0.08 s) → mitral valve opens → <b>rapid filling</b>. Blood rushing into an already full, dilated ventricle decelerates abruptly → low-pitched vibration. Lecture: in adults an S3 marks volume overload, e.g. heart failure with reduced ejection fraction. It can be normal in young people.<br><br><b>Educational objective:</b> An S3 occurs during rapid ventricular filling in early diastole.",
wrong={0:"Would be correct for an <b>S4</b>, heard just before S1 with a stiff ventricle.",
1:"Would be correct for a sound in mid-to-late diastole when filling has slowed; the S3 comes earlier.",
2:"Would be correct for <b>S1</b> itself or an ejection click at the start of systole.",
3:"Would be correct for a sound within ~0.06 s of S2 (e.g. a split S2), before the mitral valve opens. At 0.14 s the valve is already open.",
5:"Would be correct for a late systolic event, which lies before S2, not after it."},
eli5="Right after the \"dub,\" blood pours into a heart that's already overfull and makes an extra thud. That's the fast-filling moment."),

dict(img=None,
stem="A 66-year-old man is evaluated 6 weeks after an anterior wall myocardial infarction. His pulse is 110/min, and blood pressure is 102/64 mm Hg. Echocardiography shows anterior and apical akinesis. Measured left ventricular volumes are:\n\nEnd-diastolic volume: 160 mL\nEnd-systolic volume: 112 mL{FIG}Which of the following is the best estimate of this patient's left ventricular ejection fraction?",
choices=["5.3%","30%","43%","48%","70%"], key=1,
exp="Stroke volume = EDV − ESV = 160 − 112 = <b>48 mL</b>. Ejection fraction = SV ÷ EDV = 48 ÷ 160 = <b>30%</b> (normal ≈ 50–70%; ≤ 40% = reduced). Cardiac output = SV × HR = 48 mL × 110 = 5.3 L/min, maintained only by the tachycardia.<br><br><b>Educational objective:</b> Ejection fraction = (end-diastolic volume − end-systolic volume) ÷ end-diastolic volume.",
wrong={0:"Would be correct for <b>cardiac output in L/min</b> (48 mL × 110/min), not a percentage.",
2:"Would be correct if stroke volume were divided by the <b>end-systolic</b> volume (48 ÷ 112).",
3:"Would be correct if the <b>stroke volume in mL</b> were reported as the fraction.",
4:"Would be correct for ESV ÷ EDV, which is the fraction <b>left behind</b>, not ejected."},
eli5="The heart fills to 160 and squeezes down to 112, so it pushes out 48. 48 out of 160 is 30%."),

dict(img=None,
stem="Investigators study 12 patients with a dilated cardiomyopathy (mean left ventricular ejection fraction 20%) and 12 healthy volunteers. Each subject undergoes right atrial pacing at 70/min and then at 140/min; atrioventricular conduction remains 1:1 at both rates. Systemic vascular resistance does not change. In volunteers, cardiac output rises from 5.2 to 7.0 L/min. In the patients, cardiac output falls from 3.6 to 3.1 L/min.{FIG}Which of the following best explains the fall in cardiac output in the patients?",
choices=["Decreased aortic diastolic pressure","Decreased diastolic filling time","Increased afterload from vasoconstriction","Increased end-diastolic volume","Loss of the atrial contribution to filling"], key=1,
exp="CO = SV × HR. Faster rates shorten <b>diastole</b> far more than systole. A healthy, compliant ventricle fills quickly, so SV is preserved and CO rises. A failing ventricle already has a low SV; at 140/min the <b>filling time shrinks</b> → SV falls more than HR rises → <b>CO falls</b>. Lecture: \"tachycardia in a sick heart can actually reduce cardiac output.\"<br><br><b>Educational objective:</b> In a failing ventricle, tachycardia lowers cardiac output by shortening diastolic filling time.",
wrong={0:"Would be correct for reduced <b>coronary perfusion</b> (e.g. aortic regurgitation), which doesn't explain an acute fall in stroke volume here.",
2:"Would be correct if systemic vascular resistance had risen; it was unchanged.",
3:"Would be correct for <b>slower</b> rates: longer filling enlarges EDV and raises stroke volume.",
4:"Would be correct for atrial fibrillation or AV dissociation; atrial pacing with 1:1 conduction keeps the atrial kick."},
eli5="A weak heart needs time to fill. If you make it beat very fast, it doesn't fill enough, so it pumps out less blood overall."),

dict(img=None,
stem="A 79-year-old woman is brought to the emergency department because of a 2-day history of shortness of breath at rest that began with palpitations. She has severe aortic stenosis (valve area 0.8 cm2) and until this week walked one block without symptoms. Her pulse is 84/min and irregularly irregular, and blood pressure is 112/70 mm Hg. There are crackles at both lung bases. An ECG shows atrial fibrillation with no P waves; the ventricular rate is 84/min. Serum troponin I concentration is within the reference range. Echocardiography shows an unchanged aortic valve area, left ventricular wall thickness of 15 mm, ejection fraction of 60%, and no mitral regurgitation.{FIG}Which of the following is the most likely mechanism of this patient's decompensation?",
choices=["Acute ischemic left ventricular dysfunction","Loss of atrial contribution to filling","Progression of the aortic valve obstruction","Chordal rupture with an acute mitral leak","Shortened diastolic filling time"], key=1,
exp="Atrial systole (the <b>atrial kick</b>) supplies roughly 20–25% of output per the lecture, and much more in a <b>stiff, hypertrophied</b> ventricle that fills poorly passively (aortic stenosis). New atrial fibrillation → no organized atrial contraction → LV underfills → stroke volume falls and LA pressure rises → pulmonary edema. The rate is controlled (84/min), so filling time isn't the problem.<br><br><b>Educational objective:</b> Atrial fibrillation removes the atrial kick, which non-compliant ventricles such as those in aortic stenosis depend on.",
wrong={0:"Would be correct if troponin were elevated and the ejection fraction had fallen; both are normal.",
2:"Would be correct if the valve area or gradient had worsened; the valve area is unchanged.",
3:"Would be correct for acute mitral regurgitation with a new holosystolic murmur; echocardiography shows no mitral regurgitation.",
4:"Would be correct with a rapid ventricular response (e.g. 150/min); her rate is 84/min."},
eli5="A thick, stiff heart needs the top chamber's final push to fill. Atrial fibrillation takes that push away, so blood backs up into the lungs."),

dict(img=None,
stem="A 41-year-old woman comes to the office because of a 6-month history of shortness of breath with exertion and two episodes of blood-streaked sputum. She emigrated from India 10 years ago. She had painful, migrating joint swelling after a sore throat at age 9. Her pulse is 88/min and regular, and blood pressure is 112/76 mm Hg. A high-pitched sound follows S2 and is followed by a low-pitched diastolic murmur heard best at the apex with the patient in the left lateral decubitus position. There is no systolic murmur. Carotid upstrokes are normal. The point of maximal impulse is not displaced.{FIG}Simultaneous intracardiac pressure recording is most likely to show which of the following?",
choices=["Equalized diastolic pressures in all chambers","Left atrial–ventricular gradient in diastole","Left ventricular–aortic gradient in systole","Tall v wave on the left atrial tracing","Widened pulse pressure with low aortic diastolic"], key=1,
exp="Opening snap + apical diastolic rumble + childhood rheumatic fever → <b>rheumatic mitral stenosis</b>. The narrowed orifice makes flow turbulent, so pressures don't equalize: <b>LA pressure stays above LV diastolic pressure throughout diastole</b> (the lecture's hallmark gradient). LA ↑ and enlarged; LV diastolic pressure ↓ (underfilled). Normally the LA and LV diastolic curves overlap (gradient 0–5 mm Hg).<br><br><b>Educational objective:</b> Mitral stenosis produces a persistent diastolic pressure gradient between the left atrium and left ventricle.",
wrong={0:"Would be correct for cardiac tamponade or constrictive pericarditis, with pulsus paradoxus or a pericardial knock.",
2:"Would be correct for aortic stenosis: a systolic crescendo–decrescendo murmur and delayed carotid upstrokes. Her carotids are normal.",
3:"Would be correct for mitral regurgitation: a holosystolic apical murmur. She has no systolic murmur.",
4:"Would be correct for aortic regurgitation with bounding pulses; her blood pressure is 112/76."},
eli5="The doorway between the top and bottom left chambers is narrowed, so the top chamber's pressure stays higher the whole time it's trying to fill the bottom one."),

dict(img='Cas', cap='Simultaneous left heart pressures at catheterization (blue = left ventricle, green = aorta, red = left atrium)',
stem="A 68-year-old man comes to the office because of a 5-month history of fatigue and shortness of breath when walking up the hill to his mailbox. Two weeks ago he had chest tightness while shoveling snow that resolved with 5 minutes of rest. His pulse is 70/min, and blood pressure is 124/78 mm Hg. Pressures recorded at cardiac catheterization are shown. Coronary angiography shows no significant stenoses.{FIG}Physical examination of this patient is most likely to show which of the following?",
choices=["Early diastolic decrescendo murmur at the left sternal border","Holosystolic murmur at the apex radiating to the axilla","Midsystolic click followed by a late systolic murmur","Opening snap followed by an apical diastolic rumble","Systolic crescendo–decrescendo murmur, right 2nd interspace"], key=4,
exp="The tracing shows LV systolic pressure (~190) far above aortic systolic pressure (~115): a <b>systolic LV–aortic gradient</b> → <b>aortic stenosis</b>. Lecture buzzwords: <b>systolic crescendo–decrescendo murmur at the right 2nd intercostal space with blunted (weak, delayed) carotid upstrokes</b>. Exercise intolerance is the first symptom, then exertional angina from supply–demand mismatch (thick muscle, fixed output), which is why his coronaries are clean.<br><br><b>Educational objective:</b> A systolic gradient between the left ventricle and aorta is aortic stenosis, heard as a crescendo–decrescendo murmur at the right upper sternal border.",
wrong={0:"Would be correct for aortic regurgitation, where LV and aortic systolic peaks are superimposed and aortic diastolic pressure is low.",
1:"Would be correct for mitral regurgitation, which shows a tall v wave, not an LV–aortic gradient.",
2:"Would be correct for mitral valve prolapse, which has no outflow gradient.",
3:"Would be correct for mitral stenosis, with an LA–LV diastolic gradient instead."},
eli5="The heart has to push much harder than the pressure that comes out the other side, so the exit valve is narrowed. That makes a whooshing murmur that swells and fades during each squeeze."),

dict(img=None,
stem="A 44-year-old man comes for follow-up 2 weeks after transthoracic echocardiography for a murmur heard at a routine visit. The study showed a two-cusp aortic valve with moderate stenosis (mean gradient 30 mm Hg) and normal left ventricular function. He has no symptoms. He has never smoked. His pulse is 68/min, and blood pressure is 150/88 mm Hg in the right arm. There are no carotid or abdominal bruits. He has no claudication.{FIG}Which of the following is the most appropriate additional study?",
choices=["Abdominal aortic ultrasonography","Ankle–brachial index","Carotid duplex ultrasonography","CT angiography of the chest","Renal artery duplex ultrasonography"], key=3,
exp="A <b>bicuspid aortic valve</b> comes with an <b>aortopathy</b> (abnormal aortic connective tissue). Lecture: screen for <b>ascending aortic aneurysm</b> and <b>coarctation of the aorta</b>, e.g. with a contrast CT of the chest (as major centres do). His arm hypertension is a quiet nudge toward coarctation. Aortic stenosis is the most common lesion of a bicuspid valve and presents in the 40s–60s.<br><br><b>Educational objective:</b> A bicuspid aortic valve warrants imaging of the thoracic aorta for aneurysm and coarctation.",
wrong={0:"Would be correct for a man aged 65–75 who has ever smoked (abdominal aortic aneurysm screening).",
1:"Would be correct with claudication or absent pedal pulses (peripheral artery disease); he has none.",
2:"Would be correct with a carotid bruit or transient neurologic symptoms; there is no bruit.",
4:"Would be correct for resistant hypertension with an abdominal bruit or flash pulmonary edema (renal artery stenosis)."},
eli5="People born with a two-flap aortic valve often have a weak or narrowed main artery too, so you scan the chest to check the aorta."),

dict(img=None,
stem="An 86-year-old woman is evaluated because of two episodes of fainting while walking to her mailbox during the past month. She has exertional chest pressure and walks with a cane. Her pulse is 70/min, and blood pressure is 118/72 mm Hg. A late-peaking systolic crescendo–decrescendo murmur is heard at the right upper sternal border, and S2 is barely audible. Echocardiography shows an aortic valve area of 0.7 cm2, a mean gradient of 52 mm Hg, and an ejection fraction of 60%. Her serum LDL-cholesterol concentration is 162 mg/dL. Her estimated surgical risk is high, and CT shows femoral arteries of adequate caliber.{FIG}Which of the following is the most appropriate next step in management?",
choices=["High-intensity statin therapy to slow progression","Repeat echocardiography in 6 months","Sublingual nitroglycerin as needed for pain","Surgical aortic valve replacement","Transcatheter aortic valve replacement"], key=4,
exp="Severe (area ≤ 1.0 cm², mean gradient ≥ 40 mm Hg), <b>symptomatic</b> aortic stenosis (exertional syncope and angina) → valve replacement. Lecture: <b>TAVR is now first-line</b>, mostly transfemoral (\"kind of like having a PCI\"), versus at least 5 hospital days and a month of sternotomy healing for surgery. Her age, frailty and high surgical risk make it clearly preferable. <b>Statins don't slow calcific aortic stenosis</b> (Otto).<br><br><b>Educational objective:</b> Symptomatic severe aortic stenosis needs valve replacement, and TAVR is first-line in elderly high-risk patients.",
wrong={0:"Would be correct for treating her LDL-cholesterol, but statins don't slow the valve disease or relieve symptoms.",
1:"Would be correct for asymptomatic mild-to-moderate stenosis; she is symptomatic and severe.",
2:"Would be correct for angina from coronary disease without aortic stenosis. In severe aortic stenosis, venodilation can cause syncope.",
3:"Would be correct for a younger patient at low surgical risk (e.g. a bicuspid valve in a 55-year-old)."},
eli5="Her exit valve is badly narrowed and making her faint, so it needs replacing. The gentlest way for a frail 86-year-old is to slide a new valve in through a leg artery."),

dict(img=None,
stem="A 74-year-old man with severe aortic stenosis undergoes right heart catheterization before valve replacement. Pulmonary capillary wedge pressure is 24 mm Hg (N=6–12), and pulmonary artery pressure is 44/26 mm Hg. Echocardiography shows a structurally normal mitral valve with no mitral regurgitation, a left ventricular wall thickness of 16 mm, a normal left ventricular cavity size, and an ejection fraction of 65%.{FIG}Which of the following best explains the elevated pulmonary capillary wedge pressure?",
choices=["Decreased left ventricular compliance","Decreased left ventricular contractility","Increased mitral valve gradient","Increased mitral regurgitant volume","Increased pulmonary vascular resistance"], key=0,
exp="Lecture (repeated): <b>LA pressure is always high in aortic stenosis</b>, but not because of the mitral valve. Pressure overload → <b>concentric LV hypertrophy</b> → thick, <b>non-compliant</b> ventricle (\"the epitome of diastolic dysfunction\") → higher pressure for any filling volume → back-pressure into the LA and pulmonary veins → wedge ↑. Systolic function (EF 65%) is preserved.<br><br><b>Educational objective:</b> Left atrial pressure rises in aortic stenosis because the hypertrophied left ventricle is non-compliant.",
wrong={1:"Would be correct for late, decompensated aortic stenosis with a reduced ejection fraction; his is 65%.",
2:"Would be correct for mitral stenosis; his mitral valve is normal.",
3:"Would be correct with mitral regurgitation and a tall v wave; there is none.",
4:"Would be correct for pre-capillary pulmonary hypertension, which raises pulmonary artery pressure but leaves the wedge pressure normal."},
eli5="The heart wall got so thick and stiff it can't stretch to take in blood, so blood backs up into the chamber above it and the lungs."),

dict(img='Cmr', cap='Left ventricular and pulmonary capillary wedge (left atrial, dotted) pressures with aortic pressure',
stem="A 64-year-old man in the coronary care unit develops sudden shortness of breath 3 days after an inferior wall myocardial infarction treated with stenting of the right coronary artery. His pulse is 112/min, and blood pressure is 92/58 mm Hg. There are crackles over both lung fields. A new holosystolic murmur is heard at the apex and radiates to the left axilla. There is no parasternal thrill. Pulmonary artery catheter tracings are shown. Oxygen saturation is 64% in the right atrium and 65% in the pulmonary artery.{FIG}Dysfunction of which of the following structures most likely explains these findings?",
choices=["Anterolateral papillary muscle","Interventricular septum","Left ventricular free wall","Posteromedial papillary muscle","Right ventricular free wall"], key=3,
exp="The wedge (LA) tracing shows a <b>tall v wave</b>: the lecture's hallmark of <b>mitral regurgitation</b> (the LA fills from the pulmonary veins <i>and</i> the systolic regurgitant jet). After an <b>inferior</b> MI, the <b>posteromedial papillary muscle</b> (usually single supply from the posterior descending artery) becomes dysfunctional or ruptures, tethering the posterior leaflet → <b>ischemic (secondary, functional) MR</b>. With no oxygen step-up, a ventricular septal rupture is ruled out.<br><br><b>Educational objective:</b> A tall v wave after an inferior MI means mitral regurgitation from posteromedial papillary muscle dysfunction.",
wrong={0:"Would be correct after an anterolateral infarct, but it has dual supply (LAD and circumflex) and rarely fails.",
1:"Would be correct for ventricular septal rupture: a parasternal thrill and an oxygen step-up from the RA to the PA. Here 64% → 65%.",
2:"Would be correct for free-wall rupture → tamponade with equalized pressures and muffled heart sounds, not a regurgitant murmur.",
4:"Would be correct for RV infarction: hypotension, distended neck veins and clear lungs. He has pulmonary edema."},
eli5="The heart attack damaged the little muscle that holds the mitral valve shut, so blood squirts backward into the top chamber and makes a tall pressure bump."),

dict(img=None,
stem="A 29-year-old woman comes to the office because of a 2-month history of intermittent palpitations. She has no chest pain or syncope. Her pulse is 74/min, and blood pressure is 108/66 mm Hg. Auscultation at the apex shows a midsystolic click followed by a late systolic murmur; when she stands from squatting, the click moves earlier. There is no diastolic murmur. Her arm span is less than her height, and the lenses are normally positioned. Echocardiography shows the posterior mitral leaflet bulging more than 2 mm into the left atrium during systole.{FIG}If this valve were examined microscopically, which of the following would most likely be seen?",
choices=["Accumulation of proteoglycans in the spongiosa","Commissural fusion with neovascularization","Fibrin–platelet vegetations containing neutrophils","Nodular calcium deposits at the leaflet base","Sterile vegetations on both leaflet surfaces"], key=0,
exp="Midsystolic click + late systolic murmur that moves earlier on standing → <b>mitral valve prolapse</b>, the most common cause of primary mitral regurgitation in the US (lecture). The leaflets are <b>myxomatous</b>: elongated and floppy, with <b>proteoglycan (mucopolysaccharide) infiltration</b> of the spongiosa that disrupts collagen. The long leaflet billows into the LA and leaves a gap. The click is the leaflet and chordae snapping taut. Normal arm span and lenses argue against Marfan syndrome.<br><br><b>Educational objective:</b> Mitral valve prolapse reflects myxomatous degeneration with proteoglycan accumulation in the leaflets.",
wrong={1:"Would be correct for <b>rheumatic</b> valve disease: an opening snap and diastolic rumble after childhood rheumatic fever.",
2:"Would be correct for <b>infective endocarditis</b>: fever and a new regurgitant murmur.",
3:"Would be correct for <b>mitral annular calcification</b> or calcific disease in the elderly.",
4:"Would be correct for <b>Libman–Sacks</b> endocarditis in systemic lupus erythematosus."},
eli5="Her valve flaps are too long and floppy, like stretched-out rubber. They flip backward with each squeeze and click."),

dict(img='Car', cap='Simultaneous left heart pressures (blue = left ventricle, green = aorta, red = left atrium)',
stem="A 27-year-old man comes to the office because of a 3-month history of shortness of breath with exertion and a pounding sensation in his chest when he lies on his left side. His pulse is 64/min, and blood pressure is 158/52 mm Hg. Prominent pulsations are visible in the neck. A diastolic murmur is heard. Serum thyroid-stimulating hormone concentration is within the reference range, and there is no arteriovenous fistula. Pressures recorded at catheterization are shown.{FIG}Which of the following best explains this patient's low aortic diastolic pressure?",
choices=["Decreased left ventricular stroke volume","Decreased systemic vascular resistance","Diastolic backflow into the left ventricle","Increased aortic wall stiffness","Increased heart rate shortening diastole"], key=2,
exp="LV and aortic systolic peaks are superimposed (no obstruction), but aortic pressure falls steeply in diastole → <b>widened pulse pressure</b>, the lecture's hallmark of <b>aortic regurgitation</b>. In diastole the aorta loses blood <b>two ways</b>: back through the leaky valve into the LV, and forward as normal systemic runoff → diastolic pressure ↓. The large stroke volume raises systolic pressure → bounding (\"water-hammer\") pulses.<br><br><b>Educational objective:</b> In aortic regurgitation, diastolic backflow into the left ventricle plus systemic runoff lowers aortic diastolic pressure.",
wrong={0:"Would be correct for narrowing the pulse pressure; in chronic aortic regurgitation stroke volume is increased.",
1:"Would be correct for high-output states (thyrotoxicosis, arteriovenous fistula, sepsis); TSH is normal and there is no fistula.",
3:"Would be correct for isolated systolic hypertension in an elderly patient with a stiff aorta, not a 27-year-old with a diastolic murmur.",
4:"Would be correct for tachycardia; his pulse is 64/min."},
eli5="The aorta's door doesn't shut, so between beats blood leaks back into the heart while it also flows on to the body. The aorta empties fast and its low pressure drops."),

dict(img=None,
stem="A 61-year-old man with mitral valve prolapse diagnosed 15 years ago comes for follow-up. He has had increasing shortness of breath with exertion for 1 year. His pulse is 78/min and regular, and blood pressure is 126/74 mm Hg. A holosystolic murmur is heard at the apex and radiates to the axilla. The point of maximal impulse is displaced laterally. There is no chordal rupture on echocardiography.\n\nLeft atrial size | Left ventricular wall thickness | Left ventricular cavity size{FIG}Echocardiography is most likely to show which of the following sets of findings?",
choices=["Increased, increased, normal","Increased, normal, increased","Increased, normal, normal","Normal, increased, normal"], key=1,
exp="Chronic mitral regurgitation is a <b>volume</b> lesion. The LA fills from two sources (pulmonary veins + the regurgitant jet) → <b>LA enlarges</b>. That extra volume returns to the LV in diastole → high preload → <b>LV dilation with eccentric hypertrophy</b> (wall thickness near normal, cavity ↑), seen as a laterally displaced impulse. Lecture rule: wall thickens = concentric (pressure); chamber enlarges = eccentric (volume).<br><br><b>Educational objective:</b> Chronic mitral regurgitation enlarges both the left atrium and the left ventricular cavity (eccentric hypertrophy).",
wrong={0:"Would be correct for <b>aortic stenosis</b>: concentric hypertrophy (thick wall, normal cavity) with a high LA pressure.",
2:"Would be correct for <b>mitral stenosis</b>, where the LV is spared and underfilled while the LA enlarges.",
3:"Would be correct for early hypertensive heart disease, before diastolic dysfunction enlarges the left atrium."},
eli5="Leaking blood sloshes back and forth between the top and bottom chambers, so both get stretched bigger."),

dict(img=None,
stem="Patient Information\nAge: 29 years · Gender: F · Site of Care: obstetric clinic\n\nHistory\nReason for Visit: shortness of breath\nHistory of Present Illness: 28 weeks' gestation, gravida 2, para 1; 3-week history of shortness of breath after one flight of stairs; two-pillow orthopnea; one episode of blood-streaked sputum\nPast Medical History: sore throat followed by weeks of painful, migrating swelling of the knees and ankles at age 10; no antibiotic prophylaxis afterward\nMedications: prenatal vitamin\nPsychosocial History: emigrated from Nepal 4 years ago; does not smoke\n\nPhysical Examination\nT 37.0°C (98.6°F) · P 104/min, regular · R 20/min · BP 108/70 mm Hg\nLungs: fine crackles at both bases\nHeart: a sharp early diastolic sound after S2, then a low-pitched apical diastolic rumble that intensifies just before S1; no systolic murmur\nExtremities: trace ankle edema\n\nDiagnostic Studies\nEchocardiography: thickened mitral leaflet tips with fused commissures; mitral valve area 1.1 cm2; left ventricular size normal; ejection fraction 62%\n\nQuestion:{FIG}Which of the following is the most likely underlying cause of this patient's symptoms?",
choices=["Infective endocarditis","Mitral annular calcification","Myxomatous degeneration","Parachute mitral valve","Peripartum cardiomyopathy","Rheumatic heart disease"], key=5,
exp="Childhood pharyngitis → migratory polyarthritis (acute rheumatic fever) → decades later, <b>rheumatic mitral stenosis</b>: commissural fusion, opening snap, apical diastolic rumble with presystolic accentuation. Lecture: rheumatic disease is the <b>most common cause of mitral stenosis worldwide</b>, everywhere in South Asia and rare in the US. Pregnancy (blood volume ↑ ~50%) commonly unmasks it. The normal LV size and EF rule out peripartum cardiomyopathy.<br><br><b>Educational objective:</b> Mitral stenosis with commissural fusion after childhood rheumatic fever is rheumatic heart disease, often unmasked by pregnancy.",
wrong={0:"Would be correct with fever, positive blood cultures and vegetations causing a regurgitant (systolic) murmur.",
1:"Would be correct for an elderly patient with chronic kidney disease and calcification of the annulus, not fused commissures.",
2:"Would be correct for mitral valve prolapse: a midsystolic click and late systolic murmur from regurgitation.",
3:"Would be correct for a congenital lesion (single papillary muscle) presenting in childhood.",
4:"Would be correct with a dilated LV and an ejection fraction below 45% near delivery or postpartum; her LV is normal."},
eli5="A strep throat as a kid led to rheumatic fever, which scarred her mitral valve shut over the years. Pregnancy's extra blood volume finally made it cause symptoms."),

dict(img=None,
stem="An investigator records left atrial pressure through a transseptal catheter in a healthy volunteer. One positive wave begins to rise shortly after the start of ventricular ejection, climbs steadily throughout ventricular systole, and peaks just before the mitral valve opens.{FIG}Which of the following events produces this wave?",
choices=["Atrial contraction at the end of ventricular diastole","Atrial relaxation during ventricular ejection","Bulging of the closed mitral valve into the atrium","Rapid atrial emptying after mitral valve opening","Venous inflow against the closed mitral valve"], key=4,
exp="This is the <b>v wave</b>: <b>atrial filling</b> (\"atrial diastole\"). Pulmonary venous blood keeps entering the LA while the mitral valve is closed during ventricular systole → volume and pressure rise together (direct relationship) → peak just before the mitral valve opens. It is tall in mitral regurgitation. The <b>a</b> wave = atrial contraction (after the P wave). The <b>c</b> wave = the AV valve bulging back at the onset of systole.<br><br><b>Educational objective:</b> The v wave reflects atrial filling against a closed atrioventricular valve during ventricular systole.",
wrong={0:"Would be correct for the <b>a wave</b>, which follows the P wave at the end of diastole.",
1:"Would be correct for the <b>x descent</b>, a fall in pressure, not a rising wave.",
2:"Would be correct for the <b>c wave</b>, a small bump at the very start of systole.",
3:"Would be correct for the <b>y descent</b>, a fall in pressure after the mitral valve opens."},
eli5="While the bottom chamber is squeezing, the door to it is shut, so blood from the lungs piles up in the top chamber and its pressure climbs. That climb is the v wave."),
]
