# Exercise Rehabilitation & Lifestyle (Qazi) — Version 1, 18 items (3 with images). NBME house-style rewrite (2026-10-02).
Q = [
dict(img=None,
stem="A health-policy researcher models how much incident coronary artery disease in a population could, in principle, be prevented if every adult ate a healthy diet, was physically active, and did not smoke. Age, sex, and family history are treated as fixed.{FIG}Which of the following is the best estimate of the proportion of coronary artery disease incidence attributable to these three modifiable exposures?",
choices=["10–20%","25–35%","50–60%","75–90%","95–100%"], key=3,
exp="Slide 4: an estimated <b>75–90% of CAD incidence</b> is explained by modifiable risk factors: <b>poor diet, physical inactivity, cigarette smoking</b>. CVD is the leading cause of death globally (~17.6 million deaths in 2016). Physical inactivity is an <b>independent</b> risk factor linked to 12% of all US mortality. The remaining 10–25% reflects non-modifiable factors (age, sex, genetics).<br><br><b>Educational objective:</b> Poor diet, inactivity and smoking explain about 75–90% of coronary artery disease.",
wrong={0:"Would be correct for physical inactivity's share of all-cause US mortality (~12%), not CAD incidence from all three exposures.",
1:"Would be correct for the mortality reduction from regular activity (20–30%), not attributable CAD incidence.",
2:"Would be correct for no lecture estimate. It underestimates the modifiable share.",
4:"Would be correct only if age, sex and genetics contributed nothing."},
eli5="Most coronary disease, three-quarters or more, comes from what we eat, whether we move, and whether we smoke."),

dict(img=None,
stem="A 45-year-old man comes to the office for a health maintenance examination. He works at a desk and does not exercise. He does not smoke. His blood pressure is 132/84 mm Hg, and BMI is 29 kg/m2. He asks how much physical activity he needs to lower his risk of heart disease. He has no symptoms with exertion and no history of cardiovascular disease.{FIG}Which of the following recommendations is most appropriate?",
choices=["150 min/wk moderate or 75 min vigorous","30 minutes of walking once weekly","300 minutes weekly of vigorous activity only","Resistance training alone three times weekly","Stretching 10 minutes daily"], key=0,
exp="2019 ACC/AHA primary prevention (Arnett): <b>Class I</b> → counsel adults at healthcare visits to optimize an active lifestyle, and <b>≥ 150 min/week of accumulated moderate-intensity or ≥ 75 min/week of vigorous aerobic activity</b> (or an equivalent combination). Class IIa → some activity below that is still beneficial. Class IIb → reduce sedentary behaviour. Resistance, flexibility and balance work add to aerobic activity but don't replace it.<br><br><b>Educational objective:</b> The class I target for adults is ≥ 150 min/week moderate or ≥ 75 min/week vigorous aerobic activity.",
wrong={1:"Would be correct only as an IIa \"some is better than none\" starting point, not the target.",
2:"Would be correct for no guideline. It exceeds the target and excludes moderate activity.",
3:"Would be correct as an add-on (\"beyond aerobic activity\"), not as the primary recommendation.",
4:"Would be correct as an add-on for flexibility, not cardiovascular risk reduction."},
eli5="Aim for about 30 minutes of brisk activity five days a week, or half that time if it's vigorous."),

dict(img=None,
stem="A 55-year-old woman is scheduled for an exercise treadmill test. She takes no medications that affect heart rate. Before the test, the exercise physiologist estimates her maximal heart rate from her age to set the target for an adequate test.{FIG}Which of the following is the best estimate of her age-predicted maximal heart rate?",
choices=["145/min","155/min","165/min","175/min","185/min"], key=2,
exp="Slide 7: <b>age-predicted maximal HR = 220 − age</b> (SD about ±10–15 bpm) → 220 − 55 = <b>165/min</b>. HR rises linearly with workload and plateaus within 2–3 minutes at a given submaximal work rate. <b>Peak HR</b> is the HR actually reached at symptom-limited peak. <b>HR reserve</b> = peak HR − resting HR.<br><br><b>Educational objective:</b> Age-predicted maximal heart rate = 220 − age.",
wrong={0:"Would be correct using 200 − age.",
1:"Would be correct for a 65-year-old.",
3:"Would be correct for a 45-year-old.",
4:"Would be correct for a 35-year-old."},
eli5="Subtract her age from 220: 220 − 55 = 165."),

dict(img=None,
stem="A 60-year-old man in a cardiac rehabilitation maintenance program walks briskly at an intensity of 4 metabolic equivalents (METs) for 30 minutes per session, 5 days each week.{FIG}Which of the following is the best estimate of his weekly exercise volume in MET-hours?",
choices=["2","4","10","20","600"], key=2,
exp="Slide 6: <b>MET-hours = intensity (METs) × time (hours) × frequency</b> → 4 × 0.5 × 5 = <b>10 MET-h/week</b>. The lecture's example: 3 METs × 1 h × 3 days = 9 MET-h/week. <b>1 MET</b> = resting VO₂ per kg ≈ 3.5 mL O₂/kg/min.<br><br><b>Educational objective:</b> Weekly MET-hours = METs × hours per session × sessions per week.",
wrong={0:"Would be correct if the frequency were left out (4 × 0.5).",
1:"Would be correct if only the intensity were reported.",
3:"Would be correct if each session lasted 1 hour.",
4:"Would be correct if minutes were used instead of hours (4 × 30 × 5)."},
eli5="Multiply how hard (4) by how long in hours (0.5) by how many days (5): 4 × 0.5 × 5 = 10."),

dict(img='Esv', cap='One cardiovascular variable plotted against exercise time during a graded test (y-axis label removed)',
stem="An investigator records hemodynamic variables during a graded cycle-ergometer test in a healthy 25-year-old volunteer. One variable rises steeply at low workloads and then levels off at roughly half of the subject's maximal oxygen consumption, rising only slightly thereafter (curve shown).{FIG}Which of the following variables does this curve most likely represent?",
choices=["Arteriovenous oxygen difference","Diastolic blood pressure","Heart rate","Oxygen consumption","Stroke volume","Systolic blood pressure"], key=4,
exp="Slide 8: <b>stroke volume rises curvilinearly</b> and reaches a near-maximum at about <b>50% of VO₂max</b>, then plateaus or rises only slightly. Beyond that, cardiac output rises mainly through heart rate. The comparison set: HR rises <b>linearly</b> to a maximum; SBP rises <b>linearly</b> (~8–12 mm Hg/MET); DBP is flat or falls slightly; VO₂ rises linearly to a plateau at VO₂max; the a–v O₂ difference rises about 3-fold toward max.<br><br><b>Educational objective:</b> Stroke volume rises curvilinearly and plateaus at about 50% of VO₂max.",
wrong={0:"Would be correct for a variable that keeps rising toward maximal exercise (about 3-fold).",
1:"Would be correct for a flat or slightly falling line.",
2:"Would be correct for a straight-line rise to a ceiling at maximal effort.",
3:"Would be correct for a linear rise that plateaus only at VO₂max.",
5:"Would be correct for a straight line rising throughout the test."},
eli5="How much blood the heart pushes per beat goes up fast at first, then levels off about halfway to max effort. After that the heart just beats faster."),

dict(img='Ebp', cap='Blood pressure response during a graded treadmill test',
stem="A healthy 40-year-old man completes a graded treadmill test from 2 to 12 metabolic equivalents without symptoms. His blood pressure response is shown; systolic pressure rises from 124 to 196 mm Hg while diastolic pressure goes from 78 to 74 mm Hg.{FIG}Which of the following best explains why diastolic pressure does not rise?",
choices=["Decreased stroke volume at higher heart rates","Muscle vasodilation lowering resistance","Decreased venous return during exercise","Increased aortic compliance during exercise","Increased baroreflex-mediated bradycardia"], key=1,
exp="Slide 10: <b>SBP rises linearly, ~8–12 mm Hg per MET</b> (to ~190 ± 25 in men, ~170 ± 25 in women) as cardiac output rises. <b>DBP falls slightly or stays unchanged</b>. Board add-on mechanism: <b>metabolic vasodilation of working-muscle arterioles → ↓ total peripheral resistance</b> → runoff during diastole offsets the higher output. Up to 85–90% of cardiac output goes to active muscle. A <b>fall</b> in SBP with rising work would suggest severe ischemia or LV dysfunction.<br><br><b>Educational objective:</b> During dynamic exercise SBP rises while DBP stays flat because muscle vasodilation lowers peripheral resistance.",
wrong={0:"Would be correct if SV fell at high rates. It plateaus near 50% VO₂max but doesn't fall in a healthy subject.",
2:"Would be correct if venous return fell. The muscle pump actually <b>raises</b> it.",
3:"Would be correct for no acute exercise effect. Compliance doesn't change meaningfully.",
4:"Would be correct for no exercise response. HR rises during exercise."},
eli5="The heart pumps harder and pushes the top number up, but the muscles open their small arteries wide, so the bottom number doesn't rise."),

dict(img=None,
stem="A physiology student calculates the distribution of cardiac output in a healthy 30-year-old man at rest and during maximal treadmill exercise.\n\nShare of cardiac output to skeletal muscle: At rest | At maximal exercise{FIG}Which of the following pairs of values is most likely?",
choices=["15–20%, 15–20%","15–20%, 85–90%","50%, 50%","80–85%, 15–20%","85–90%, 85–90%"], key=1,
exp="Slide 9: <b>at rest, 15–20% of blood flow goes to muscle and 80–85% to the visceral organs</b>. <b>With exercise this reverses: 85–90% of cardiac output goes to active muscle</b>. Muscle O₂ extraction (SaO₂ − SvO₂) also rises about 3-fold. Board add-on (Fick): VO₂ = CO × (a–v O₂ difference), and both terms rise.<br><br><b>Educational objective:</b> Exercise redistributes cardiac output from viscera (rest: 80–85%) to active muscle (max: 85–90%).",
wrong={0:"Would be correct if no redistribution occurred.",
2:"Would be correct for no physiologic state. It's an even split.",
3:"Would be correct if the rest and exercise values were swapped.",
4:"Would be correct only if muscle received most of the flow even at rest."},
eli5="At rest the gut and organs get most of the blood. During hard exercise the body reroutes almost all of it to the working muscles."),

dict(img=None,
stem="A 64-year-old man with coronary artery disease completes phase II cardiac rehabilitation 4 months after a myocardial infarction, and his exercise capacity increases from 5 to 6 metabolic equivalents (METs). He asks how much this improvement matters.{FIG}Which of the following is the best estimate of the relative reduction in mortality associated with each 1-MET increase in exercise capacity in patients with coronary artery disease?",
choices=["1–2%","8–35%","50–60%","70–80%"], key=1,
exp="Slide 12: <b>cardiorespiratory fitness is a powerful independent predictor of mortality</b>. In CAD, <b>each 1-MET increase → 8–35% relative reduction in mortality</b>, comparable to statins, β-blockers, low-dose aspirin and ACE inhibitors after MI. Kodama's meta-analysis (33 studies, ~103,000 people): RR 0.87 per MET. \"Exercise is medicine.\"<br><br><b>Educational objective:</b> Each 1-MET gain in fitness lowers mortality by about 8–35% in CAD.",
wrong={0:"Would be correct if fitness were a weak marker. The effect rivals cardioprotective drugs.",
2:"Would be correct for no lecture estimate. It overstates the per-MET effect.",
3:"Would be correct for no lecture estimate. Far too large."},
eli5="Getting fitter by one level cuts the chance of dying about as much as a major heart pill."),

dict(img=None,
stem="A 58-year-old woman is discharged 3 days after an uncomplicated non-ST-elevation myocardial infarction treated with a stent. Her cardiologist refers her to a supervised outpatient program in which she will exercise under electrocardiographic monitoring with individualized risk-factor counseling.{FIG}Which of the following best describes this phase of cardiac rehabilitation?",
choices=["About 36 monitored sessions over 8–12 weeks","Bedside mobilization and education during admission","Independent lifelong exercise at a community gym","One exercise test followed by written advice","Daily sessions for 1 week, then discharge"], key=0,
exp="Slide 19, the phases of cardiac rehabilitation:<br>• <b>Phase I</b> (inpatient): physical therapy and education immediately after the event.<br>• <b>Phase II</b> (outpatient, supervised): individualized exercise prescription and risk-factor reduction under a medical team, <b>36 sessions, typically three times weekly, ECG-monitored, over 8–12 weeks</b>.<br>• <b>Phases III–IV</b> (maintenance): independent long-term continuation.<br><br><b>Educational objective:</b> Phase II cardiac rehab is supervised outpatient training: ~36 ECG-monitored sessions over 8–12 weeks.",
wrong={1:"Would be correct for phase I (inpatient).",
2:"Would be correct for phases III–IV (maintenance).",
3:"Would be correct for the intake assessment, not the program.",
4:"Would be correct for no lecture phase. Phase II spans 8–12 weeks."},
eli5="Phase II is a supervised gym program about three times a week for roughly three months, with heart monitoring during each session."),

dict(img=None,
stem="A cardiology practice reviews referral eligibility for cardiac rehabilitation. Five patients are listed: a 59-year-old man 4 months after an anterior myocardial infarction; a 66-year-old woman 6 weeks after coronary artery bypass grafting; a 71-year-old man with chronic stable angina; a 64-year-old woman with claudication from peripheral artery disease; and a 68-year-old man with chronic heart failure with reduced ejection fraction.{FIG}Which of these diagnoses carries a class IIa (rather than class I) recommendation for cardiac rehabilitation?",
choices=["Chronic heart failure","Chronic stable angina","Coronary artery bypass grafting","Myocardial infarction within 12 months","Peripheral artery disease"], key=0,
exp="Slide 21, indications for CR: <b>class I</b> → ACS within the preceding 12 months, post-CABG or post-PCI, chronic angina, peripheral artery disease; <b>class IIa → chronic heart failure</b>. Also listed: valve replacement or repair, LVAD, heart or heart–lung transplant. Evidence for other conditions is incomplete, so coverage is often restricted. Heart failure benefit was established by HF-ACTION.<br><br><b>Educational objective:</b> Cardiac rehab is class I after ACS, CABG/PCI and for stable angina and PAD, and class IIa for chronic heart failure.",
wrong={1:"Would be correct if chronic angina were IIa. It's class I.",
2:"Would be correct if post-CABG were IIa. It's class I.",
3:"Would be correct if the MI were more than 12 months ago and listed as IIa. Within 12 months it's class I.",
4:"Would be correct if PAD were IIa. It's class I."},
eli5="Rehab is strongly recommended after heart attacks, bypass, angina and leg-artery disease. For chronic heart failure it's recommended a little less strongly."),

dict(img=None,
stem="A 67-year-old man undergoes three-vessel coronary artery bypass grafting through a median sternotomy and is discharged home on postoperative day 5. His sternal wound is healing, and he walks 10 minutes three times daily without symptoms.{FIG}Approximately when is it most appropriate for him to begin outpatient cardiac rehabilitation?",
choices=["1–2 days after discharge","1–2 weeks after discharge","2–6 weeks after surgery","3–6 months after surgery","12 months after surgery"], key=2,
exp="Slide 23: patients can enter CR <b>1–2 weeks after discharge following a non-surgical event</b>, but <b>2–6 weeks may be needed after surgical procedures such as CABG</b> or other major cardiovascular operations (sternal healing, recovery). The intake includes a history and examination plus a symptom-limited exercise test on usual medications.<br><br><b>Educational objective:</b> Outpatient CR begins about 2–6 weeks after CABG (1–2 weeks after non-surgical events).",
wrong={0:"Would be correct for no lecture scenario. Too soon after sternotomy.",
1:"Would be correct after a non-surgical event such as PCI or medically treated ACS.",
3:"Would be correct for no lecture scenario. It delays the benefit.",
4:"Would be correct for no lecture scenario. It forfeits the window of benefit."},
eli5="After open-heart surgery the chest bone needs a few weeks to heal, so rehab usually starts 2 to 6 weeks later."),

dict(img=None,
stem="A 70-year-old woman with coronary artery disease is scheduled for a symptom-limited exercise test at her cardiac rehabilitation intake. She takes metoprolol succinate, aspirin, atorvastatin, and lisinopril every morning. She asks whether she should skip her medications before the test so that her heart \"shows what it can really do.\"{FIG}Which of the following is the most appropriate instruction?",
choices=["Hold all cardiac medications for 24 hours","Hold metoprolol for 48 hours","Take a double dose of metoprolol that morning","Take only aspirin that morning","Take all her usual medications as scheduled"], key=4,
exp="Slide 23: the intake exercise test establishes baseline fitness and maximal HR and monitors for ischemia or arrhythmia, and <b>patients should be continued on their usual medications during exercise testing</b>. The β-blocker blunts HR, so the prescription (target HR, ischemic threshold) must be built under the same conditions she'll train in. A test off metoprolol would give a peak HR she never reaches in training, and 220 − age would mislead too.<br><br><b>Educational objective:</b> The CR intake exercise test is done on the patient's usual medications so the exercise prescription matches real training conditions.",
wrong={0:"Would be correct for a diagnostic stress test (to unmask ischemia), not a rehab prescription test.",
1:"Would be correct for a diagnostic test aiming to reach target HR, not the CR intake.",
2:"Would be correct for no protocol. It distorts the test and risks bradycardia.",
3:"Would be correct for no protocol. Selectively holding drugs distorts the prescription."},
eli5="She should be tested under the same conditions she'll exercise in, so she takes her normal pills."),

dict(img=None,
stem="A 62-year-old man in phase II cardiac rehabilitation completes a symptom-limited treadmill test while taking his usual medications. Typical substernal pressure develops at a heart rate of 128/min and resolves with rest; ECG shows 1.5 mm of horizontal ST-segment depression at that heart rate.{FIG}Which of the following is the most appropriate upper limit for his training heart rate?",
choices=["98/min","108/min","118/min","128/min","138/min"], key=2,
exp="Slide 28: in symptomatic patients, set the training intensity about <b>10 beats below the ischemic threshold</b> (the HR at which typical angina occurs) → 128 − 10 = <b>118/min</b>. The general intensity rules: threshold ≈ 45% of oxygen-uptake reserve (≈ 70% of peak HR), progressing to 50–80%. FITT also lists 40–80% of HR reserve, 65–80% of peak HR, RPE 11–16.<br><br><b>Educational objective:</b> With exercise-induced angina, cap the training HR about 10 beats below the ischemic threshold.",
wrong={0:"Would be correct for 30 beats below the threshold, which needlessly limits training.",
1:"Would be correct for 20 beats below the threshold, more conservative than the lecture rule.",
3:"Would be correct only if training at the ischemic threshold were safe. It provokes angina.",
4:"Would be correct for no protocol. It's above the ischemic threshold."},
eli5="His heart runs short of oxygen at 128 beats a minute, so he trains about 10 beats below that to stay safe."),

dict(img=None,
stem="A 57-year-old woman begins phase II cardiac rehabilitation after a myocardial infarction. The exercise physiologist explains the Borg rating-of-perceived-exertion scale, which ranges from 6 (no exertion) to 20 (maximal exertion), and asks her to keep her rating within a target band during aerobic exercise.{FIG}Which of the following ranges is the target in the FITT exercise prescription?",
choices=["6–8","9–10","11–16","17–18","19–20"], key=2,
exp="Slide 27, <b>FITT</b>: Frequency ≥ 3×/week (preferably most days) · <b>Intensity 40–80% of peak HR reserve or VO₂ reserve, 65–80% of peak exercise HR, RPE 11–16</b> (\"fairly light\" to \"hard\") · Time 5–10 min warm-up, 30–60 min aerobic, 5–10 min cool-down · Type: walking, jogging, rowing, cycling, elliptical.<br><br><b>Educational objective:</b> The FITT prescription targets an RPE of 11–16.",
wrong={0:"Would be correct for rest or very light activity, below a training stimulus.",
1:"Would be correct for a warm-up or cool-down intensity.",
3:"Would be correct for very hard exertion, above the CR target.",
4:"Would be correct for maximal exertion, used only at symptom-limited peak testing."},
eli5="On a 6-to-20 effort scale, rehab aims for the middle, 11 to 16: working, but able to keep going."),

dict(img='Epredimed', cap='Cumulative incidence of acute MI, stroke, or death from cardiovascular causes by diet assignment',
stem="Investigators randomly assigned 7,447 adults at high cardiovascular risk but without cardiovascular disease to a Mediterranean diet supplemented with extra-virgin olive oil, a Mediterranean diet supplemented with mixed nuts, or a control diet with advice to reduce dietary fat. The primary outcome was a composite of myocardial infarction, stroke, and cardiovascular death. Results are shown.{FIG}Which of the following conclusions is best supported by this trial?",
choices=["Both Mediterranean diets reduced events by about 30%","Mixed nuts reduced events but olive oil did not","No diet affected clinical events","The low-fat control diet reduced events the most","The benefit appeared only after 10 years"], key=0,
exp="<b>PREDIMED</b> (Estruch, NEJM 2013): both Mediterranean arms lowered the composite of MI, stroke and CV death compared with the reduced-fat control: <b>HR 0.70</b> each (~30% reduction), with curves separating within the first 1–2 years over ~5 years of follow-up. The lecture's conclusion: <b>the Mediterranean diet is the only dietary pattern with RCT evidence of reduced ASCVD events</b>.<br><br><b>Educational objective:</b> PREDIMED showed a Mediterranean diet (olive oil or nuts) reduced major cardiovascular events by about 30%.",
wrong={1:"Would be correct if the olive oil HR crossed 1.0. Both arms were 0.70.",
2:"Would be correct for a null trial. The confidence intervals excluded 1.0.",
3:"Would be correct if the control curve were lowest. It was highest.",
4:"Would be correct for a longer trial with late separation. Follow-up was about 5 years."},
eli5="People told to eat a Mediterranean diet with extra olive oil or nuts had about 30% fewer heart attacks, strokes and heart deaths than people told to cut fat."),

dict(img=None,
stem="A 59-year-old man with hypertension (blood pressure 144/90 mm Hg on lisinopril) and a high-salt diet asks how much sodium he should eat. The physician cites the 2013 lifestyle guideline, which sets one threshold for patients who would benefit from blood pressure reduction and a lower threshold that offers further benefit.{FIG}Below which daily sodium intake does the guideline describe further blood pressure benefit?",
choices=["500 mg","1,500 mg","2,400 mg","4,000 mg","5,000 mg"], key=1,
exp="Slide 42, <b>2013 lifestyle guidelines</b>: those who benefit from BP reduction → <b>< 2,400 mg sodium/day</b>; <b>further benefit < 1,500 mg/day</b>. Higher sodium intake: ↑ stroke 24%, ↑ fatal CHD 32%. Sodium reduction lowers SBP by ~3.4 mm Hg (Aburto). DASH-Sodium: diet and sodium reduction are additive.<br><br><b>Educational objective:</b> The sodium target is < 2,400 mg/day, with further BP benefit below 1,500 mg/day.",
wrong={0:"Would be correct for no guideline. It's unrealistically low.",
2:"Would be correct for the first threshold, not the further-benefit one.",
3:"Would be correct for no guideline. It's near typical intake.",
4:"Would be correct for no guideline. It's a high-salt diet."},
eli5="Keep sodium under about 2,400 mg a day, and going below 1,500 mg helps blood pressure even more."),

dict(img=None,
stem="A 48-year-old man with an LDL-cholesterol concentration of 172 mg/dL reviews the 2019 ACC/AHA dietary recommendations with a dietitian. The dietitian explains that one dietary component carries a recommendation of harm and should be avoided entirely, whereas the others should be emphasized or used as replacements.{FIG}Which of the following is the component that carries a class III (harm) recommendation?",
choices=["Extra-virgin olive oil","Monounsaturated fats","Omega-3 fats from fish","Polyunsaturated fats","Trans fats"], key=4,
exp="Slides 35–36, 2019 ACC/AHA nutrition recommendations: <b>I</b> → vegetables, fruit, legumes, nuts, whole grains, fish. <b>IIa</b> → replace saturated fat with mono- and polyunsaturated fat; reduce cholesterol and sodium; minimize processed meats, refined carbohydrates, sweetened beverages. <b>III: Harm → avoid trans fats</b>.<br><br><b>Educational objective:</b> Trans fats carry a class III (harm) recommendation and should be avoided.",
wrong={0:"Would be correct for no harm category. Olive oil is central to PREDIMED's benefit.",
1:"Would be correct for no harm category. It's the recommended replacement for saturated fat (IIa).",
2:"Would be correct for no harm category. Fish is a class I food.",
3:"Would be correct for no harm category. It's a recommended replacement for saturated fat (IIa)."},
eli5="Trans fats, found in some processed and fried foods, are the one fat the guidelines say to avoid completely."),

dict(img=None,
stem="A 55-year-old man with frequent premature ventricular contractions completes 12 weeks of supervised aerobic training. His resting heart rate falls from 82/min to 64/min, and his ectopic burden on Holter monitoring decreases by half. He takes no new medications.{FIG}Which of the following best explains these changes?",
choices=["Decreased HDL-cholesterol concentration","Increased C-reactive protein concentration","Increased platelet aggregation","↑ Vagal and ↓ sympathetic tone","Lowered myocardial ischemic threshold"], key=3,
exp="Slide 11, cardioprotective effects of exercise: <b>antiarrhythmic → improved cardiac autonomic function: ↑ vagal tone, ↓ sympathetic activity</b>, which lowers resting HR and ectopy. Also anti-inflammatory (↓ CRP), antithrombotic (↓ platelet aggregation, ↑ fibrinolysis), antiatherogenic (↑ NO, better endothelial function), risk-factor effects (↓ LDL and TG, ↑ HDL, ↓ BP, ↑ insulin sensitivity), anti-ischemic (↑ ischemic threshold), and psychological (↓ depression and stress).<br><br><b>Educational objective:</b> Exercise training is antiarrhythmic by increasing vagal and decreasing sympathetic tone.",
wrong={0:"Would be correct for the opposite of training's effect. Exercise <b>raises</b> HDL.",
1:"Would be correct for the opposite of training's effect. Exercise <b>lowers</b> CRP.",
2:"Would be correct for the opposite of training's effect. Exercise <b>decreases</b> platelet aggregation.",
4:"Would be correct for the opposite of training's effect. Exercise <b>raises</b> the ischemic threshold."},
eli5="Regular exercise turns up the heart's 'calm' nerve signals and turns down its 'stress' signals, so it beats slower and misfires less."),
]
