# Exercise Rehabilitation & Lifestyle (Qazi) — Version 2, 18 items (2 with images). NBME house-style rewrite (2026-10-02).
Q = [
dict(img=None,
stem="A 60-year-old woman begins phase II cardiac rehabilitation 3 weeks after percutaneous coronary intervention. On a symptom-limited treadmill test performed while she was taking her usual metoprolol, her resting heart rate was 72/min and her peak heart rate was 142/min, with no angina or ST-segment changes. The exercise physiologist prescribes training at 60% of her heart rate reserve.{FIG}Which of the following is the best estimate of her target heart rate?",
choices=["85/min","100/min","114/min","128/min","142/min"], key=2,
exp="<b>HR reserve = peak HR − resting HR</b> = 142 − 72 = 70. Board add-on (Karvonen): <b>target = resting HR + % × reserve</b> = 72 + 0.6 × 70 = <b>114/min</b>. FITT intensity: <b>40–80% of HR reserve</b>, 65–80% of peak HR, RPE 11–16. Use the <b>measured peak HR on usual medications</b>: on a β-blocker, 220 − age (160) would overestimate.<br><br><b>Educational objective:</b> Target HR by the heart-rate-reserve method = resting HR + % × (peak HR − resting HR).",
wrong={0:"Would be correct if 60% were applied to the peak HR (0.6 × 142), ignoring resting HR.",
1:"Would be correct if 60% were applied to the age-predicted maximum minus the resting HR, without adding the resting HR back.",
3:"Would be correct for 90% of the peak HR, an intensity above the prescription.",
4:"Would be correct for the peak HR itself (100% intensity)."},
eli5="Her 'reserve' is the gap between resting (72) and peak (142), which is 70 beats. Add 60% of that gap (42) to her resting rate: 114."),

dict(img=None,
stem="A 58-year-old sedentary man with obesity performs a treadmill test with expired-gas analysis. He stops at minute 7 because of leg fatigue. Oxygen uptake is still rising at the moment he stops, and his respiratory exchange ratio is 1.02.{FIG}Which of the following terms best describes the highest oxygen uptake recorded?",
choices=["Heart rate reserve","Resting oxygen uptake (1 MET)","Ventilatory threshold","VO2max","VO2peak"], key=4,
exp="Slide 6: <b>VO₂max</b> is the rate of O₂ use at <b>maximal exertion</b>, with a true plateau despite rising work. <b>VO₂peak</b> is the highest value at <b>symptom-limited peak performance</b>. Because his VO₂ was still rising when he stopped (and his RER was only ~1.0), no plateau was reached → VO₂peak. <b>VO₂peak < VO₂max in most sedentary adults.</b> 1 MET ≈ 3.5 mL O₂/kg/min is resting uptake.<br><br><b>Educational objective:</b> VO₂peak is the symptom-limited highest O₂ uptake, below the true VO₂max in most sedentary adults.",
wrong={0:"Would be correct for a heart-rate quantity (peak − resting HR), not oxygen uptake.",
1:"Would be correct for the value at rest before exercise.",
2:"Would be correct for the submaximal point where ventilation rises disproportionately.",
3:"Would be correct if VO₂ had plateaued despite increasing workload."},
eli5="He stopped because his legs gave out before his body hit its true oxygen ceiling, so his best number is his 'peak', not his 'max'."),

dict(img=None,
stem="During a submaximal constant-load cycling protocol in a healthy 30-year-old woman, the workload is increased by 25 watts at each stage. A technician records the heart rate continuously to decide when each stage has reached steady state before recording data.{FIG}Approximately how long after each increase in work rate does heart rate typically plateau?",
choices=["10–15 seconds","2–3 minutes","15–20 minutes","45–60 minutes"], key=1,
exp="Slide 7: <b>with exercise HR increases linearly and then generally plateaus in 2–3 minutes at a given submaximal work rate</b>. That's why graded protocols use stages of about 2–3 minutes. Maximal HR ≈ 220 − age (± 10–15). Stroke volume, by contrast, plateaus at about 50% of VO₂max.<br><br><b>Educational objective:</b> Heart rate reaches a steady state about 2–3 minutes after each submaximal workload increase.",
wrong={0:"Would be correct for the immediate vagal withdrawal at exercise onset, not the steady state.",
2:"Would be correct for prolonged steady exercise with cardiovascular drift, not each stage.",
3:"Would be correct for no physiologic steady state. It's far too slow."},
eli5="When the effort steps up, the heart rate climbs for a couple of minutes and then holds steady at the new level."),

dict(img=None,
stem="A 69-year-old man undergoes an exercise treadmill test because of exertional chest tightness for 2 months. Systolic blood pressure is 138 mm Hg at rest and rises to 162 mm Hg at stage 2. At stage 3, as the workload increases, he develops chest tightness, his systolic blood pressure falls to 128 mm Hg, and there is 2 mm of horizontal ST-segment depression in leads V4–V6. He takes no antihypertensive medications.{FIG}Which of the following is the most likely explanation for the blood pressure response at stage 3?",
choices=["Dehydration from exertion","Exaggerated vagal tone from training","Cardiac output failing to rise from ischemia","Normal decline of systolic pressure at high workloads","Rising diastolic pressure compressing pulse pressure"], key=2,
exp="Normally <b>SBP rises linearly with work, ~8–12 mm Hg per MET</b>, while DBP stays flat or falls slightly. A <b>fall in SBP with increasing workload</b> (board add-on: exercise-induced hypotension) means cardiac output can't keep rising → <b>severe ischemia</b> (e.g., left main or three-vessel disease) or LV dysfunction. Stop the test. The angina and ST depression are confirmatory. Applying the lecture's physiology to exercise testing is LO 2.<br><br><b>Educational objective:</b> A fall in systolic BP with rising workload on an exercise test signals extensive ischemia or LV dysfunction.",
wrong={0:"Would be correct for prolonged exercise in heat with orthostasis, not a fall within one stage with ischemic ST changes.",
1:"Would be correct for a trained athlete's low resting HR, not exertional hypotension.",
3:"Would be correct for no normal physiology. SBP should keep rising.",
4:"Would be correct for no exercise physiology. DBP normally stays flat or falls."},
eli5="Blood pressure should keep climbing as exercise gets harder. When it drops, the heart can't keep up, which points to serious blockage."),

dict(img='Efit', cap='Mortality per 10,000 man-years by fitness at two examinations about 5 years apart (9,777 men)',
stem="Investigators assessed treadmill fitness in 9,777 men at two examinations about 5 years apart and followed them for mortality. Men were classified as unfit at both examinations, unfit then fit, or fit at both. Results are shown.{FIG}Which of the following conclusions is best supported by these data?",
choices=["Getting fit was linked to lower mortality","Fitness in mid-life was unrelated to mortality","Mortality was highest among men who were fit at both examinations","Only men who were fit at the first examination benefited","The study included only women"], key=0,
exp="Aerobics Center Longitudinal Study (Blair, JAMA 1995): mortality per 10,000 man-years was <b>~122 for unfit → unfit</b>, <b>~68 for unfit → fit</b> (about a 45% reduction), and <b>~40 for fit → fit</b>. Improving fitness in mid-life still pays off. Together with Kodama's RR 0.87 per MET, this supports \"exercise is medicine.\"<br><br><b>Educational objective:</b> Becoming fit in mid-life is associated with substantially lower mortality.",
wrong={1:"Would be correct if all three bars were similar.",
2:"Would be correct if the fit–fit bar were tallest. It was the lowest.",
3:"Would be correct if unfit → fit men had mortality similar to unfit → unfit.",
4:"Would be correct for a different cohort. This one was 9,777 men."},
eli5="Men who got fit between two checkups cut their death rate nearly in half compared with men who stayed unfit. It's not too late."),

dict(img=None,
stem="A cardiac rehabilitation program has one remaining enrollment slot this month. Four candidates have the following characteristics: (1) a 71-year-old woman 2 months after myocardial infarction whose exercise capacity is 4 METs; (2) a 48-year-old marathon runner after an ankle sprain; (3) a 55-year-old man without cardiovascular disease who already exercises 200 minutes weekly; (4) a 62-year-old man with rest angina for 2 days.{FIG}According to the lecture, which candidate is most likely to gain the greatest benefit from structured exercise-based cardiac rehabilitation?",
choices=["The marathon runner after an ankle sprain","The man already exercising 200 minutes weekly","The man with rest angina for 2 days","The woman 2 months after MI at 4 METs"], key=3,
exp="Slide 15: \"For the <b>least-fit, least-active high-risk cohort (bottom 20%; less than 5 METs) with CVD</b>, referral to structured exercise-based CR programs may be the key to improving CV health and outcomes.\" Each 1-MET gain lowers mortality 8–35%, so the least fit gain most. Rest angina is <b>unstable disease (AHA class D)</b>, which calls for activity restriction, not training.<br><br><b>Educational objective:</b> Patients with CVD and very low fitness (< 5 METs) gain the most from structured cardiac rehabilitation.",
wrong={0:"Would be correct for no CR indication. Musculoskeletal rehab isn't cardiac rehab.",
1:"Would be correct for no CR indication. He's already meeting activity targets without CVD.",
2:"Would be correct only after stabilization. Unstable angina (class D) requires activity restriction."},
eli5="The people with the lowest fitness and real heart disease gain the most from each step up, so they need rehab most."),

dict(img=None,
stem="A 66-year-old man is evaluated for enrollment in cardiac rehabilitation. Over the past 48 hours he has had three episodes of chest pressure at rest lasting 10 minutes each; he has no chest pain now. ECG shows new T-wave inversions in leads V2–V4. Serum troponin concentration is within the reference range.{FIG}According to the American Heart Association risk classification for exercise training, which of the following best describes his category and management?",
choices=["Class A: apparently healthy, unrestricted exercise","Class B: stable disease, standard supervised training","Class C: higher risk, closely monitored training","Class D: unstable disease, activity restriction"], key=3,
exp="Slide 24: <b>A</b> apparently healthy · <b>B</b> known <b>stable</b> CVD, low risk with vigorous exercise · <b>C</b> moderate to high risk of complications or unable to self-regulate (most CR patients are B or C) · <b>D unstable disease requiring activity restriction</b>. Rest angina with new ischemic T-wave changes is <b>unstable angina</b> → class D → admit, stabilize and revascularize as indicated before training. The normal troponin is the decoy: it excludes infarction, not instability.<br><br><b>Educational objective:</b> Unstable cardiovascular disease (such as unstable angina) is AHA class D: restrict activity rather than start training.",
wrong={0:"Would be correct for a person without evidence of increased cardiovascular risk.",
1:"Would be correct after stabilization, with stable disease and a low-risk exercise test.",
2:"Would be correct for stable but high-risk features (e.g., reduced EF, exercise-induced arrhythmia), not active instability."},
eli5="His heart condition is unstable right now, so exercise training has to wait until doctors calm it down."),

dict(img=None,
stem="A 61-year-old man begins cardiac rehabilitation 3 weeks after an uncomplicated percutaneous coronary intervention for stable angina. His left ventricular ejection fraction is 58%. On a symptom-limited treadmill test he reaches 9 METs without angina, arrhythmia, or ST-segment changes, and his blood pressure rises normally.{FIG}According to the American Heart Association risk classification for exercise training, which category best fits this patient?",
choices=["Class A","Class B","Class C","Class D"], key=1,
exp="Slide 24: <b>class B = known stable CVD at low risk for complications with vigorous exercise</b> (slightly greater than apparently healthy). He has established CAD (so not class A), with preserved EF, good capacity, and a normal test response (so not class C), and he's stable (so not class D). \"Most patients referred for CR belong to class B or C.\"<br><br><b>Educational objective:</b> Stable CAD with preserved function and a low-risk exercise test is AHA exercise class B.",
wrong={0:"Would be correct if he had no known cardiovascular disease.",
2:"Would be correct with reduced EF, exercise-induced ischemia or arrhythmia, or inability to self-regulate activity.",
3:"Would be correct for unstable disease requiring restriction."},
eli5="He has heart disease, but it's stable and his test was excellent, so he's in the lower-risk rehab group, B."),

dict(img=None,
stem="Investigators randomly assigned patients with chronic systolic heart failure to supervised aerobic exercise training followed by home training, or to usual care. Two composite outcomes were reported.\n\nAll-cause mortality or hospitalization | Cardiovascular death or heart failure hospitalization{FIG}Which of the following pairs of relative reductions with exercise training was reported?",
choices=["11%, 15%","13%, 26%","15%, 11%","30%, 30%","No reduction, no reduction"], key=0,
exp="<b>HF-ACTION</b> (slide 25), the seminal trial establishing CR in systolic HF: <b>11% reduction in all-cause mortality and hospitalization</b>, <b>15% reduction in CV death and HF hospitalization</b>, and better QoL. Exercise is safe and beneficial across a broad spectrum of HF. Chronic HF is a class IIa CR indication.<br><br><b>Educational objective:</b> HF-ACTION showed exercise training in systolic HF reduced all-cause death/hospitalization by 11% and CV death/HF hospitalization by 15%.",
wrong={1:"Would be correct for the CAD meta-analysis (total 13%, CV mortality 26%).",
2:"Would be correct if the two HF-ACTION outcomes were swapped.",
3:"Would be correct for PREDIMED's ~30% event reduction (HR 0.70).",
4:"Would be correct for a null trial."},
eli5="A big trial showed structured exercise helps people with weak hearts stay out of the hospital and live a bit longer."),

dict(img=None,
stem="An 81-year-old woman is being discharged after her second hospitalization this year for acute decompensated heart failure. She uses a walker, has had two falls, and scores poorly on a balance test. She is afraid exercise will \"strain her heart.\" Her blood pressure is 118/70 mm Hg, and she is euvolemic.{FIG}Which of the following is the most appropriate next step to improve her physical function?",
choices=["Bed rest until she can walk without a walker","High-intensity interval training starting this week","Low-intensity multicomponent program, 36 sessions","Resistance training alone at home, unsupervised","Waiting 12 months before any rehabilitation"], key=2,
exp="Slide 26: <b>REHAB-HF</b> randomized <b>frail, elderly</b> patients after an HF hospitalization to a <b>multicomponent, low-intensity exercise intervention over 36 sessions</b> (strength, balance, mobility, endurance) or usual care → <b>improved physical function, better Kansas City Cardiomyopathy Questionnaire scores, fewer depressive symptoms</b>. Slide 29 adds balance and mobility work, especially for older patients. Her falls and poor balance are the buried clue.<br><br><b>Educational objective:</b> Frail older patients after HF hospitalization benefit from multicomponent, low-intensity rehabilitation (REHAB-HF).",
wrong={0:"Would be correct for no current approach. Inactivity worsens frailty.",
1:"Would be correct for a fit, stable patient, not a frail 81-year-old with falls.",
3:"Would be correct as one component, but it lacks balance and mobility work and supervision.",
4:"Would be correct for no current approach. It forfeits the post-discharge benefit."},
eli5="Even frail older patients get stronger with gentle, varied exercise (balance, strength, walking) after a heart-failure stay."),

dict(img=None,
stem="A meta-analysis pooled 47 randomized trials of 10,794 patients with recent myocardial infarction, coronary artery bypass grafting, percutaneous coronary intervention, or angina who were assigned to exercise-based cardiac rehabilitation or usual care.\n\nTotal mortality | Cardiovascular mortality{FIG}Which of the following pairs of relative reductions was reported?",
choices=["11%, 15%","13%, 26%","26%, 13%","30%, 30%","No reduction, no reduction"], key=1,
exp="Slide 22: exercise-based CR lowered <b>total mortality by 13%</b> and <b>cardiovascular mortality by 26%</b>, with better ASCVD risk factors (BP, lipids, smoking), fewer hospitalizations, less angina and depression, and better exercise performance and quality of life.<br><br><b>Educational objective:</b> In CAD, exercise-based cardiac rehab lowers total mortality ~13% and cardiovascular mortality ~26%.",
wrong={0:"Would be correct for HF-ACTION's composite outcomes.",
2:"Would be correct if the two values were swapped.",
3:"Would be correct for PREDIMED's diet effect.",
4:"Would be correct for a null meta-analysis."},
eli5="People with heart disease who did rehab were about a quarter less likely to die from heart causes."),

dict(img=None,
stem="A 64-year-old man is seen in the office 1 week after hospitalization for a non-ST-elevation myocardial infarction. He did not attend his first cardiac rehabilitation appointment. He says, \"I feel fine now, and I don't think I need to go to a gym with a bunch of sick people.\"{FIG}Which of the following is the most appropriate response by the physician?",
choices=["\"I strongly recommend rehab; it saves lives. What's in the way?\"","\"If you feel fine, rehab is optional, so it's your call.\"","\"Let's revisit rehab in 6 months if you develop symptoms.\"","\"The cardiologist can talk to you about rehab at your next visit.\"","\"You'll end up back in the hospital if you don't go.\""], key=0,
exp="Slides 30–31: CR is <b>underutilized</b> (only ~30–40% of eligible patients enroll), and a key system determinant is <b>\"the strength of the endorsement of CR by the patient's physician.\"</b> The best response gives a <b>clear, strong recommendation</b> with its benefit (CR lowers CV mortality ~26% in CAD) and then <b>explores barriers</b> (transport, work, beliefs, depression) so they can be addressed.<br><br><b>Educational objective:</b> A strong physician endorsement plus exploring barriers increases cardiac rehabilitation participation.",
wrong={1:"A weak endorsement. That fits only if CR offered no proven benefit.",
2:"Delay. That fits only if the benefit weren't time-sensitive after MI.",
3:"Offloads to another clinician. That fits only if the PCP had no role in the endorsement.",
4:"Fear-based and closed. That fits only if the goal weren't to understand his barriers."},
eli5="Patients go to rehab much more often when their own doctor strongly recommends it and helps solve whatever is stopping them."),

dict(img=None,
stem="A 68-year-old woman is referred to cardiac rehabilitation after a myocardial infarction. She is recently widowed, does not drive, lives 30 miles from the nearest program, and screens positive for depression. Six weeks later she has not enrolled. A hospital quality team reviews strategies to improve enrollment among similar patients.{FIG}Which of the following interventions is most likely to increase participation?",
choices=["Automatic referral, strong endorsement, and support","Waiting for patients to request referral themselves","Delaying referral until 6 months after discharge","Mailing a brochure without follow-up","Treating depression and deferring rehabilitation discussion"], key=0,
exp="Slides 30–31: <b>referral has improved with automatic inpatient referrals</b>. Enrollment is only 30–40%, and patient factors (older age, <b>women</b>, minorities, low SES, limited social support, <b>depression</b>) and system factors (<b>distance</b>, transport, hours, availability, and <b>the strength of the physician's endorsement</b>) drive participation. Automatic referral plus a strong endorsement plus help with barriers (transport, home-based options) addresses both.<br><br><b>Educational objective:</b> Automatic referral, a strong physician endorsement, and addressing barriers (transport, depression, support) increase CR participation.",
wrong={1:"Would be correct only if self-referral performed well. It worsens the referral gap.",
2:"Would be correct for no lecture strategy. It forfeits the early post-MI benefit.",
3:"Would be correct only if information alone drove enrollment. It doesn't address her barriers.",
4:"Would be correct as part of care, but deferring CR loses its benefit (CR itself also reduces depression)."},
eli5="Rehab attendance goes up when the referral happens automatically, the doctor pushes for it, and someone helps with rides and other obstacles."),

dict(img=None,
stem="A 59-year-old man completed 36 sessions of electrocardiogram-monitored outpatient cardiac rehabilitation 1 month ago after a myocardial infarction. He now exercises on his own at a community gym 4 days weekly and continues the dietary and risk-factor changes he learned.{FIG}Which phase of cardiac rehabilitation is he currently in?",
choices=["Phase I","Phase II","Phases III–IV","Primordial prevention"], key=2,
exp="Slide 19: <b>Phase I</b> → inpatient PT and education right after the event. <b>Phase II</b> → supervised outpatient program, 36 ECG-monitored sessions over 8–12 weeks (completed). <b>Phases III and IV (maintenance)</b> → long-term lifestyle change through <b>independent continuation</b> of the exercise program and the CV risk reduction learned in phase II. Primordial prevention is the base of the prevention pyramid (preventing risk factors from developing).<br><br><b>Educational objective:</b> Phases III–IV are the independent, long-term maintenance phases after supervised phase II.",
wrong={0:"Would be correct during the index hospitalization.",
1:"Would be correct during the supervised, monitored 36-session program.",
3:"Would be correct for someone without risk factors, preventing them from developing."},
eli5="After the supervised program ends, keeping up the exercise on your own for life is the maintenance phase."),

dict(img='Edash', cap='Systolic blood pressure by diet and sodium level (DASH-Sodium trial)',
stem="A 54-year-old man with stage 1 hypertension (blood pressure 138/88 mm Hg) wants to avoid medication and asks whether to adopt the DASH diet or reduce his salt intake. In a feeding trial, participants were assigned to a control diet or the DASH diet, each at high, intermediate, and low sodium levels. Results are shown.{FIG}Which of the following conclusions is best supported by these data?",
choices=["Both lower systolic pressure; the effects add up","Low sodium raises systolic pressure on the DASH diet","Neither strategy meaningfully lowers systolic pressure","Only sodium reduction lowers systolic pressure","Only the DASH diet lowers systolic pressure"], key=0,
exp="DASH-Sodium (NEJM 2001): at every sodium level the <b>DASH diet lowered SBP</b> vs control (most at high sodium, −5.9 mm Hg), and <b>reducing sodium lowered SBP further on both diets</b>. The lowest SBP came with <b>DASH plus low sodium</b>, so the effects are <b>additive</b>. 2013 guideline: < 2,400 mg/day, with further benefit < 1,500 mg/day.<br><br><b>Educational objective:</b> The DASH diet and sodium reduction each lower BP, and their effects add.",
wrong={1:"Would be correct if the DASH line rose at low sodium. It fell.",
2:"Would be correct if both lines were flat and overlapping.",
3:"Would be correct if the DASH and control lines overlapped at each sodium level.",
4:"Would be correct if both lines were flat across sodium levels."},
eli5="Eating the DASH way lowers blood pressure, cutting salt lowers it too, and doing both lowers it the most."),

dict(img=None,
stem="A 62-year-old woman with hypertension and hyperlipidemia treated with atorvastatin comes to the office for a health maintenance examination. She has no history of cardiovascular disease, gastrointestinal bleeding, or bleeding disorder. Her calculated 10-year ASCVD risk is 6.0%. She asks whether she should start taking a low-dose aspirin daily to prevent a heart attack.{FIG}Which of the following is the most appropriate recommendation regarding aspirin?",
choices=["Do not start routine aspirin for primary prevention","Start aspirin because she is older than 50 years","Start aspirin because she has hypertension","Start aspirin in place of atorvastatin","Start full-dose aspirin, 325 mg daily"], key=0,
exp="Slide 33's 2019 ACC/AHA primary prevention wheel: <b>\"low-dose aspirin for primary prevention now reserved for select high-risk patients\"</b> (bleeding risk offsets benefit in most). Her intermediate risk (6%) on a statin doesn't qualify. The other components: ASCVD risk assessment with enhancers or coronary calcium, BP < 130/80, ≥ 150 min/week activity, diabetes (metformin first, then SGLT-2 inhibitor or GLP-1 agonist), a healthy diet, and tobacco cessation, within team-based care.<br><br><b>Educational objective:</b> Routine aspirin isn't recommended for primary prevention. It's reserved for select high-risk patients.",
wrong={1:"Would be correct under older guidance that used age alone.",
2:"Would be correct for no current guideline. Hypertension alone doesn't justify aspirin.",
3:"Would be correct for no guideline. Aspirin doesn't replace LDL lowering.",
4:"Would be correct for no prevention indication. Full dose adds bleeding without benefit."},
eli5="For people without heart disease, daily aspirin's bleeding risk usually cancels out its benefit, so it's saved for a few very high-risk people."),

dict(img=None,
stem="A 50-year-old man reviews six popular heart-healthy eating plans with his dietitian: DASH, low-fat, Mediterranean, TLC (Therapeutic Lifestyle Changes), Ornish, and Esselstyn. He asks what they have in common so he can choose a pattern he can sustain.{FIG}Which of the following best summarizes the features these diets share?",
choices=["High protein with very low carbohydrate intake","Produce, grains, fiber up; saturated fat down","Strict alternate-day fasting","Unlimited red meat with restricted fruit intake","Unrestricted saturated fat with low fiber"], key=1,
exp="Slide 34: across DASH, low-fat, Mediterranean, TLC, Ornish and Esselstyn, the common ground is <b>increased fruits and vegetables, whole grains, increased fiber, and reduced saturated fat</b>. The guideline adds: class I emphasis on vegetables, fruit, legumes, nuts, whole grains and fish; IIa replacement of saturated with unsaturated fat; limit cholesterol, sodium, processed meat, refined carbohydrate and sweetened beverages; avoid trans fats (III: harm). Only the Mediterranean pattern has RCT evidence of fewer events (PREDIMED).<br><br><b>Educational objective:</b> Heart-healthy diets share more produce, whole grains and fiber and less saturated fat.",
wrong={0:"Would be correct for a ketogenic or low-carb diet, which isn't among the six.",
2:"Would be correct for an intermittent-fasting regimen, which isn't among the six.",
3:"Would be correct for no heart-healthy pattern. Red meat is limited in all six.",
4:"Would be correct for no heart-healthy pattern. It's the opposite of the guidance."},
eli5="All the good heart diets boil down to the same idea: lots of plants, whole grains and fiber, and not much saturated fat."),

dict(img=None,
stem="A 52-year-old man with an LDL-cholesterol concentration of 168 mg/dL and a father who had a myocardial infarction at age 50 wants to change his diet before considering medication. He eats red meat daily, cooks with butter, and drinks two sugar-sweetened sodas daily. He eats few vegetables.{FIG}Which of the following dietary changes is supported by a class IIa recommendation in the 2019 ACC/AHA guideline?",
choices=["Adding a daily serving of processed meat","Increasing dietary trans fats","Replacing saturated fat with unsaturated fat","Replacing whole grains with refined carbohydrates","Switching sodas to fruit juice drinks with added sugar"], key=2,
exp="Slides 35–36: <b>replacement of saturated fat with dietary monounsaturated and polyunsaturated fats can be beneficial (IIa)</b>, e.g., olive oil instead of butter, fish and legumes instead of red meat. Also IIa: less dietary cholesterol and sodium, and <b>minimal processed meat, refined carbohydrates and sweetened beverages</b>. Class I: vegetables, fruit, legumes, nuts, whole grains, fish. <b>Trans fats: III (harm)</b>.<br><br><b>Educational objective:</b> Replacing saturated fat with mono- and polyunsaturated fat is a class IIa dietary recommendation.",
wrong={0:"Would be correct for no guideline. Processed meat should be minimized (IIa).",
1:"Would be correct for no guideline. Trans fats are class III (harm).",
3:"Would be correct for no guideline. Refined carbohydrates should be minimized.",
4:"Would be correct for no guideline. Sweetened beverages of any kind should be minimized."},
eli5="Cooking with olive oil instead of butter, and eating fish or beans instead of red meat, swaps bad fats for better ones."),
]
