# Vascular Disease (Ciraulo) — Image Quiz V2, 18 items, every stem has an image. NBME house-style rewrite (2026-10-02).
Q = [
dict(img='Vbluetoe', cap='Photograph of the right foot',
stem="A 74-year-old man comes to the office because of a 5-day history of painful discoloration of several toes on the right foot. He has a 4.8-cm infrarenal abdominal aortic aneurysm followed with ultrasonography. He has hypertension and a 50-pack-year history of cigarette smoking. His pulse is 72/min and regular, and blood pressure is 150/86 mm Hg. The foot is shown; it is warm, and the dorsalis pedis and posterior tibial pulses are 2+. Sensation and toe movement are intact. ECG shows normal sinus rhythm.{FIG}Which of the following is the most appropriate next step in diagnosis?",
choices=["Ankle-brachial index","Abdominal and iliac CT angiography","Nerve conduction studies of the leg","Transthoracic echocardiography","Venous duplex ultrasonography of the leg","X-ray of the foot"], key=1,
exp="Dusky toes with <b>palpable pedal pulses</b> → small-vessel occlusion by <b>microemboli</b> → <b>blue toe syndrome</b>, whose source is upstream plaque or an <b>aneurysm</b> (\"more common in patients with aneurysmal disease\"). \"It's not a blue toe because there's a problem with the knee… it's a problem upstream.\" Image the source: CTA of the aorta and iliacs. Sinus rhythm makes a cardiac macroembolus less likely, and macroemboli lodge at bifurcations and abolish pulses. An embolizing aneurysm is an indication for repair.<br><br><b>Educational objective:</b> Blue toes with intact pulses are microemboli from a proximal aortoiliac source (often an aneurysm), so image the aorta and iliacs.",
wrong={0:"Would be correct for suspected flow-limiting stenosis with claudication and diminished pulses.",
2:"Would be correct for numbness or weakness in a nerve distribution, not ischemic discoloration.",
3:"Would be correct with atrial fibrillation or a recent MI and a macroembolus with absent pulses.",
4:"Would be correct for a swollen, tender calf suggesting DVT.",
5:"Would be correct for suspected osteomyelitis or fracture."},
eli5="Tiny cholesterol bits are breaking off his aneurysm and plugging the toe arteries. You image the aorta to find the source."),

dict(img='Vrubor', cap='Photograph of the legs in a dependent position',
stem="A 77-year-old woman with type 2 diabetes mellitus comes to the office because of a 6-week history of burning pain in the right forefoot that wakes her at night and improves when she hangs the foot over the side of the bed. Two years ago she had calf pain after walking one block. Her legs in the dependent position are shown; with elevation, the right foot becomes pale. Popliteal and pedal pulses are absent on the right. There are no ulcers. The right ankle-brachial index is 0.32. Hemoglobin A1c is 7.1%.{FIG}Which of the following is the most appropriate next step in management?",
choices=["Cilostazol therapy and follow-up in 3 months","Gabapentin therapy","Graduated compression stockings","Referral for revascularization","Supervised exercise therapy"], key=3,
exp="Pain <b>at rest, at night</b>, relieved by <b>dependency</b> (gravity aids perfusion), dependent rubor with pallor on elevation, absent pulses and an ABI of ~0.3 → <b>chronic limb-threatening (critical) ischemia</b>. 30% progress to major amputation within a year and 25% die within a year. Rest pain is an indication for <b>revascularization</b>: \"an indication to get someone to a vascular surgeon.\" The diabetes is the decoy that surface-reads as neuropathy. Neuropathic pain doesn't improve with dependency or come with an ABI of 0.32.<br><br><b>Educational objective:</b> Ischemic rest pain relieved by dependency, with a very low ABI, is limb-threatening ischemia that needs revascularization.",
wrong={0:"Would be correct for stable intermittent claudication without rest pain.",
1:"Would be correct for painful diabetic neuropathy with normal pulses and ABI.",
2:"Would be correct for venous insufficiency. Compression worsens severe arterial ischemia.",
4:"Would be correct for intermittent claudication, not rest pain."},
eli5="Her foot is so starved of blood that it hurts even lying in bed, and hanging it down lets gravity push a little more blood in. She needs her arteries opened."),

dict(img='Vlathromb', cap='Axial contrast-enhanced CT of the chest (arrow)',
stem="An 80-year-old woman is brought to the emergency department 3 hours after the sudden onset of pain in the right leg. She has atrial fibrillation and stopped taking apixaban 3 weeks ago because of cost. Her pulse is 112/min and irregularly irregular, and blood pressure is 146/84 mm Hg. The right leg is pale and cool below the knee; popliteal and pedal pulses are absent. Sensation in the foot is decreased, and she can move her toes. A CT scan of the chest obtained for shortness of breath is shown.{FIG}Which of the following is the most appropriate initial pharmacotherapy?",
choices=["Aspirin","Cilostazol","Clopidogrel","Intravenous alteplase","Intravenous unfractionated heparin","Warfarin"], key=4,
exp="The CT shows a filling defect in the <b>left atrium</b> → the source of an <b>arterial embolus</b> in atrial fibrillation. Acute limb ischemia (pain, pallor, pulselessness, paresthesia). Slide 31: <b>anticoagulation is always the first step; IV heparin is the drug of choice</b> → it stops propagation. Then, with motor function intact, catheter-directed thrombolysis or thrombectomy, or open Fogarty embolectomy. Long-term anticoagulation for the source follows.<br><br><b>Educational objective:</b> Acute embolic limb ischemia is treated first with IV unfractionated heparin.",
wrong={0:"Would be correct for stable chronic atherosclerotic disease (secondary prevention).",
1:"Would be correct for stable intermittent claudication.",
2:"Would be correct after arterial stenting or in aspirin-intolerant atherosclerotic disease.",
3:"Would be considered for catheter-directed (not systemic) lysis after heparin, if there were no contraindication.",
5:"Would be correct for long-term prevention once the limb is revascularized, not acute therapy."},
eli5="A clot from her heart blocked the leg artery. Heparin first stops it from growing while doctors arrange to remove it."),

dict(img='Vfasc', cap='Intraoperative photograph of the lower leg',
stem="A 66-year-old man undergoes femoral embolectomy for a 7-hour-old occlusion. Four hours later the calf is tense and swollen, passive dorsiflexion of the toes causes severe pain, and sensation is absent in the first web space of the foot. Dorsalis pedis and posterior tibial pulses are palpable. Serum creatine kinase concentration is 18,400 U/L. He undergoes the procedure shown.{FIG}Which of the following processes best explains the condition that required this procedure?",
choices=["Embolization of a new thrombus to the popliteal artery","Occlusion of the deep veins of the calf","Reperfusion-induced capillary leak","Peroneal nerve compression from intraoperative positioning","Rupture of the medial head of the gastrocnemius"], key=2,
exp="Restored flow after hours of ischemia → <b>reperfusion injury</b> (\"like putting peroxide right into the bloodstream\"): oxygen free radicals damage capillary membranes → interstitial edema inside unyielding fascia → compartment pressure exceeds perfusion → ischemia again → <b>compartment syndrome</b>. Signs: pain on passive stretch, calf tenderness, numbness in the first web space (deep peroneal nerve). The photo shows a <b>fasciotomy</b>. Palpable pulses are the buried clue: a new embolus would abolish them.<br><br><b>Educational objective:</b> Compartment syndrome after revascularization results from reperfusion injury and is treated with fasciotomy.",
wrong={0:"Would be correct if the pulses had disappeared again with a cold, pale foot.",
1:"Would be correct for a swollen leg with prominent veins but no pain on passive stretch or nerve deficit.",
3:"Would be correct for foot drop without a tense compartment or CK elevation.",
4:"Would be correct for sudden calf pain during push-off activity, not after revascularization."},
eli5="When blood rushed back into the starved muscle, the muscle swelled inside its tight sleeve until it choked itself. Cutting the sleeve open gives it room."),

dict(img='Vctadis', cap='Sagittal CT angiogram of the chest',
stem="A 61-year-old man is brought to the emergency department 2 hours after the onset of tearing pain between his shoulder blades. He has a 20-year history of poorly controlled hypertension. His pulse is 102/min, and blood pressure is 184/104 mm Hg in both arms. Pulses are equal in all extremities. Urine output, serum lactate, and creatinine are normal. CT angiography is shown; the flap begins distal to the left subclavian artery, and the ascending aorta is normal.{FIG}The most appropriate initial pharmacotherapy has which of the following mechanisms of action?",
choices=["α1-Adrenergic receptor blockade","β1-Adrenergic receptor blockade","Dihydropyridine L-type calcium channel blockade","Nitric oxide release in vascular smooth muscle","Plasminogen activation","Vitamin K epoxide reductase inhibition"], key=1,
exp="Flap distal to the left subclavian with a normal ascending aorta → <b>DeBakey III / Stanford B</b>. No malperfusion → <b>uncomplicated</b> → <b>medical BP control</b> (\"if you control the hypertension, sometimes these dissections will heal\"), with TEVAR if it fails. Board add-on: start with an <b>IV β-blocker</b> (esmolol, labetalol) → ↓ heart rate and dP/dt → ↓ aortic wall shear stress, to HR ≤ 60 and SBP 100–120. Add a vasodilator <b>afterward</b>, because a vasodilator alone causes reflex tachycardia.<br><br><b>Educational objective:</b> Uncomplicated Stanford B dissection is treated first with an IV β-blocker to lower heart rate and shear stress, then BP control.",
wrong={0:"Would be correct as an add-on in pheochromocytoma or cocaine-related hypertension, not as first-line here.",
2:"Would be correct for BP control only after β-blockade. Alone it causes reflex tachycardia.",
3:"Would be correct (nitroprusside) as the second agent once heart rate is controlled.",
4:"Would be correct for acute ischemic stroke or STEMI without dissection. It's contraindicated here.",
5:"Would be correct for long-term atrial fibrillation anticoagulation, not acute dissection."},
eli5="The tear is past the heart's branches, so you calm the heart rate and blood pressure, starting with a β-blocker, to take the strain off the aorta."),

dict(img='Vaaact', cap='Axial contrast-enhanced CT of the abdomen at the level of L4',
stem="A 79-year-old man comes to the emergency department because of a 3-day history of dull, constant lower back pain. His pulse is 84/min, and blood pressure is 148/88 mm Hg. Hemoglobin concentration is 13.8 g/dL. A pulsatile mass is palpated in the periumbilical region; it is mildly tender. CT of the abdomen is shown; there is no periaortic hematoma.{FIG}Which of the following is the most appropriate next step in management?",
choices=["Repair of the aneurysm during this admission","Repeat CT in 12 months","Ultrasonography in 3 months","Ultrasonography in 6 months","Ultrasonography in 12 months"], key=0,
exp="The CT shows an <b>infrarenal abdominal aortic aneurysm about 9 cm</b> across (measured on the outer wall; thrombus lines the lumen). Indications for repair: <b>> 5.5 cm</b>, <b>symptomatic</b> (back pain and tenderness), growth > 5 mm in 6 months, saccular shape. Stable hemoglobin and no hematoma mean it hasn't ruptured, but a symptomatic aneurysm is repaired urgently (EVAR if neck > 15 mm, angle < 60°, calcification < 50%; otherwise open).<br><br><b>Educational objective:</b> A symptomatic AAA or one > 5.5 cm is repaired, urgently when symptomatic.",
wrong={1:"Would be correct for no aneurysm on the lecture chart. Yearly CT is too infrequent.",
2:"Would be correct for an asymptomatic aneurysm of 4.5–5.0 cm.",
3:"Would be correct for an asymptomatic aneurysm < 4.5 cm.",
4:"Would be correct for none of the lecture bands."},
eli5="His aorta has ballooned to about three times its normal width and it's starting to hurt, a warning sign it could burst. It needs fixing now."),

dict(img='Vischcol', cap='Endoscopic view of the sigmoid colon 25 cm from the anal verge',
stem="A 72-year-old man is evaluated 18 hours after open repair of an infrarenal abdominal aortic aneurysm with a tube graft because of three episodes of maroon stool and left lower quadrant pain. He received 6 units of packed red blood cells intraoperatively and is receiving norepinephrine. His pulse is 112/min, and blood pressure is 96/58 mm Hg. Flexible sigmoidoscopy is shown; the rectum appears normal.{FIG}Loss of flow through which of the following arteries most likely caused this complication?",
choices=["Celiac trunk","Inferior mesenteric artery","Left renal artery","Middle colic artery","Superior mesenteric artery"], key=1,
exp="Bloody stool within 12–24 h of aortic surgery with dusky, ulcerated <b>sigmoid</b> mucosa → <b>ischemic colitis</b>. The sigmoid is supplied by the <b>inferior mesenteric artery</b>, which is often sacrificed during aortic replacement. When collaterals from the SMA (marginal artery) are poor, the sigmoid infarcts. Lecture rule: pulsatile back-bleeding from the cut IMA → ligate; a weak trickle → <b>re-implant</b>. Hypotension and vasopressors worsen it. A spared rectum (middle and inferior rectal supply) fits.<br><br><b>Educational objective:</b> Ischemic colitis of the sigmoid after aortic repair results from loss of IMA flow without adequate collaterals.",
wrong={0:"Would be correct for gastric, duodenal or hepatic ischemia.",
2:"Would be correct for oliguria and a rising creatinine, not bloody stool.",
3:"Would be correct for transverse colon ischemia.",
4:"Would be correct for diffuse small-bowel and right-colon ischemia with pain out of proportion."},
eli5="The artery feeding the lower colon was tied off during the aortic repair, and his colon had no good backup supply, so that part ran short of blood."),

dict(img='Vsplenic', cap='Axial contrast-enhanced CT of the upper abdomen (measurement shown)',
stem="A 31-year-old woman, gravida 2, para 2, comes to the office to discuss an incidental finding on CT done 1 week ago for flank pain from a kidney stone. The CT is shown; it demonstrates a 2.6-cm calcified saccular aneurysm of the splenic artery. She has no abdominal pain. She plans to become pregnant next year. Her pulse is 70/min, and blood pressure is 124/78 mm Hg. Abdominal examination shows no abnormalities.{FIG}Which of the following is the most appropriate next step in management?",
choices=["CT surveillance every 6 months","Embolization or stent graft now","No follow-up unless symptoms occur","Repair only if it ruptures during pregnancy","Start propranolol and observe"], key=1,
exp="<b>Splenic artery aneurysms</b>: risk factors female sex, multiple pregnancies, hypertension. They are often asymptomatic, but they <b>rupture in pregnancy</b> (\"mother has a baby… next thing you know, mom's coding\"), often as a \"double rupture\" (lesser sac first, then free). <b>Repair if > 2 cm, symptomatic, or in a woman of child-bearing age</b>, ideally <b>before</b> pregnancy: endovascular embolization or stent graft, or open ligation. She meets two criteria.<br><br><b>Educational objective:</b> Splenic artery aneurysms > 2 cm or in women planning pregnancy should be repaired before pregnancy.",
wrong={0:"Would be correct for a small (< 2 cm) aneurysm in a postmenopausal woman.",
2:"Would be correct for neither scenario. Size and pregnancy plans both call for repair.",
3:"Would accept a rupture risk with high maternal and fetal mortality.",
4:"Would be correct for neither scenario. β-blockade doesn't prevent visceral aneurysm rupture."},
eli5="This kind of aneurysm is known to burst during pregnancy, so it gets fixed before she becomes pregnant."),

dict(img='Vpopl', cap='Angiogram of the distal right thigh and knee',
stem="A 70-year-old man comes to the office because of a painless pulsatile mass behind the right knee that he noticed 2 months ago. He has hypertension and a 40-pack-year history of cigarette smoking. Pedal pulses are 2+ bilaterally. There is no calf swelling, and sensation and motor function in the foot are normal. The angiogram shown demonstrates a 3-cm fusiform aneurysm of the popliteal artery.{FIG}If left untreated, which of the following complications is this lesion most likely to cause?",
choices=["Arteriovenous fistula with high-output heart failure","Distal embolization or thrombosis","Free rupture into the popliteal fossa","Infection of the aneurysm sac","Tibial nerve compression with plantar numbness"], key=1,
exp="<b>Popliteal aneurysms</b> occur primarily in men, often as a pulsatile mass behind the knee. Unlike aortic aneurysms they <b>rarely rupture</b>. Laminated thrombus in the sac <b>embolizes to the tibial and pedal arteries or thromboses</b> → acute limb ischemia (\"symptomatic: embolic to feet or thrombosis\"). Repair if <b>> 2 cm or symptomatic</b> (bypass, interposition graft, endovascular), so this one qualifies. Board add-on: often bilateral and associated with AAA, so image the other knee and the aorta.<br><br><b>Educational objective:</b> Popliteal aneurysms threaten the limb by embolization or thrombosis, not rupture. Repair if > 2 cm.",
wrong={0:"Would be correct after penetrating trauma or catheter injury creating an artery–vein connection.",
2:"Would be correct for an abdominal aortic aneurysm, the classic rupture risk.",
3:"Would be correct for a mycotic aneurysm in endocarditis or injection drug use.",
4:"Would be a possible but much rarer compressive complication."},
eli5="Clot builds up inside the bulge behind his knee. It can block the artery or shed pieces that plug the arteries of his foot."),

dict(img='Vsma', cap='Coronal CT angiogram of the abdomen (arrows)',
stem="An 83-year-old woman is brought to the emergency department 6 hours after the sudden onset of severe periumbilical pain with one episode of vomiting and loose stool. She has atrial fibrillation and takes no anticoagulant. She is writhing on the stretcher. Her temperature is 37.4°C (99.3°F), pulse is 118/min and irregularly irregular, and blood pressure is 138/82 mm Hg. The abdomen is soft and only mildly tender, without guarding. Serum lactate concentration is 4.1 mmol/L. CT angiography is shown; the arrows indicate a filling defect a few centimeters beyond the origin of the superior mesenteric artery.{FIG}Which of the following is the most appropriate next step in management?",
choices=["Aortomesenteric bypass","Bowel rest, intravenous fluids, and antibiotics alone","Embolectomy, bowel assessment, and anticoagulation","Esophagogastroduodenoscopy","Repeat CT angiography in 24 hours"], key=2,
exp="Elderly + <b>atrial fibrillation</b> + sudden pain <b>out of proportion</b> to a soft abdomen + rising lactate → \"a 911 event.\" An occlusion <b>beyond the SMA origin</b> (past the proximal jejunal branches) is the pattern of an <b>embolus</b>; thrombosis occurs at the ostium on chronic plaque. Treatment by cause: <b>embolus → embolectomy + anticoagulation</b> (lifelong), with resection of dead bowel (\"you need about 100 cm of small bowel\") · thrombosis → aortomesenteric bypass · non-occlusive → bowel rest, fluids, antibiotics · venous → anticoagulation. \"When in doubt, operate.\"<br><br><b>Educational objective:</b> An SMA embolus from atrial fibrillation is treated with urgent embolectomy, bowel assessment and anticoagulation.",
wrong={0:"Would be correct for acute thrombosis at the SMA origin on chronic atherosclerotic stenosis.",
1:"Would be correct for non-occlusive mesenteric ischemia (low-flow vasospasm) with patent vessels.",
3:"Would be correct for upper GI bleeding or peptic disease, not an arterial occlusion.",
4:"Would let the bowel infarct. Delay is the lethal error."},
eli5="A clot from her heart blocked the main gut artery. Surgeons have to pull it out fast, check for dead bowel, and keep her on blood thinners for life."),

dict(img='Vrasmra', cap='MR angiogram of the abdominal aorta and renal arteries (arrow)',
stem="A 67-year-old man comes to the office because of hypertension that has remained above 160/95 mm Hg for 6 months despite adherence to amlodipine, hydrochlorothiazide, and metoprolol. He has been hospitalized twice in the past year for sudden pulmonary edema with a normal ejection fraction. He has a 45-pack-year history of cigarette smoking. An abdominal bruit is heard. MR angiography is shown.{FIG}Which of the following sets of plasma findings is most likely in this patient?\n\nRenin activity | Aldosterone | Potassium",
choices=["Decreased, decreased, decreased","Decreased, increased, decreased","Increased, decreased, increased","Increased, increased, decreased","Normal, normal, normal"], key=3,
exp="The MRA shows <b>renal artery stenosis</b>. <b>Goldblatt hypertension</b>: ↓ renal perfusion → juxtaglomerular cells ↑ <b>renin</b> → ↑ angiotensin II (vasoconstriction) → ↑ <b>aldosterone</b> (Na⁺ and water retention, K⁺ excretion → ↓ <b>potassium</b>). Clues from the lecture: refractory hypertension, pulmonary edema out of proportion to LV function, a bruit, and a smoker (atherosclerosis; in young women think fibromuscular dysplasia). Board add-on: thiazide use also lowers K⁺, so all three point the same way.<br><br><b>Educational objective:</b> Renovascular (Goldblatt) hypertension causes high renin, high aldosterone and hypokalemia.",
wrong={0:"Would be correct for a mineralocorticoid excess other than aldosterone (e.g., Liddle syndrome, licorice).",
1:"Would be correct for primary hyperaldosteronism (adenoma), with suppressed renin.",
2:"Would be correct for primary adrenal insufficiency (Addison disease).",
4:"Would be correct for essential hypertension without RAAS activation."},
eli5="The narrowed kidney artery fools the kidney into thinking blood pressure is low, so it floods the body with renin and aldosterone. Pressure goes up and potassium goes down."),

dict(img='Vraynaud', cap='Photograph of the hand 1 minute after holding a cold drink',
stem="A 24-year-old woman comes to the office because of a 2-year history of episodes in which her fingers turn white when she is cold or anxious, then blue, then red and throbbing as they rewarm; each episode lasts 15–20 minutes. Gloves and avoiding cold have not prevented them. She has no rash, joint pain, dysphagia, skin thickening, or digital ulcers. Her hand during an episode is shown. Nailfold capillaries appear normal. Antinuclear antibody test is negative.{FIG}The most appropriate pharmacotherapy has which of the following mechanisms of action?",
choices=["β-Adrenergic receptor blockade","Cyclooxygenase inhibition","Glucocorticoid receptor activation","L-type calcium channel blockade","Serotonin 5-HT1B/1D receptor activation"], key=3,
exp="Episodic <b>white → blue → red</b> color change triggered by cold or emotion → <b>Raynaud phenomenon</b>. Negative ANA, normal nailfold capillaries and no skin, joint or GI findings → <b>primary</b> (no underlying disease). Management: avoid cold, then a <b>calcium channel blocker</b> (board add-on: dihydropyridine, e.g., nifedipine) → blocks L-type Ca²⁺ entry into arteriolar smooth muscle → vasodilation. Sympathectomy is rarely used.<br><br><b>Educational objective:</b> Raynaud phenomenon is treated with cold avoidance and a dihydropyridine calcium channel blocker.",
wrong={0:"Would be correct for performance anxiety or tachyarrhythmia. β-Blockers can worsen vasospasm.",
1:"Would be correct for inflammatory pain. It doesn't relieve digital vasospasm.",
2:"Would be correct for a vasculitis such as GCA or Takayasu, not primary vasospasm.",
4:"Would be correct for migraine (triptans), which are vasoconstrictors and worsen Raynaud."},
eli5="Her finger arteries clamp down too hard in the cold. A calcium channel blocker relaxes the artery muscle so they don't clamp shut."),

dict(img='Vgca', cap='Photograph of the right temple (arrow)',
stem="A 76-year-old woman comes to the office because of a 3-week history of new right-sided headache, fatigue, low-grade fever, and pain in her jaw when chewing that subsides when she stops. This morning she had a 5-minute episode of blurred vision in the right eye. Her temperature is 37.8°C (100°F). The structure at the arrow is tender and firm with a reduced pulse. Visual acuity is 20/25 bilaterally. Erythrocyte sedimentation rate is 92 mm/h.{FIG}Which of the following is the most appropriate next step in management?",
choices=["CT of the head without contrast","High-dose glucocorticoid therapy now","Ibuprofen and reevaluation in 2 weeks","Sumatriptan therapy","Temporal artery biopsy before any treatment"], key=1,
exp="New headache + <b>jaw claudication</b> + fever and fatigue + a tender, thickened temporal artery + ESR 92 in a patient over 70 → <b>giant cell (temporal) arteritis</b>, a large-vessel vasculitis. Lecture: temporal artery biopsy and corticosteroids. The transient visual blurring is the buried clue: ophthalmic artery involvement threatens permanent blindness → <b>start steroids immediately</b>. Board add-on: the biopsy stays diagnostic for 1–2 weeks after steroids start, so it shouldn't delay treatment.<br><br><b>Educational objective:</b> Suspected giant cell arteritis with visual symptoms is treated with immediate high-dose glucocorticoids, without waiting for the biopsy.",
wrong={0:"Would be correct for a thunderclap headache or focal deficits suggesting hemorrhage.",
2:"Would be correct for tension-type headache. It risks blindness here.",
3:"Would be correct for migraine. Vasoconstrictors are harmful in arteritis.",
4:"Would be correct only in the absence of visual symptoms, and even then it shouldn't delay steroids."},
eli5="Her temple artery is inflamed, and the same inflammation is starting to threaten the artery to her eye. Steroids go in right away, before the biopsy."),

dict(img='Vtaka', cap='3D CT angiogram of the aortic arch and its branches',
stem="A 25-year-old woman comes to the office because of a 4-month history of fevers, myalgias, and a 5-kg (11-lb) weight loss, and a 1-month history of aching in the left arm when she blow-dries her hair. Her temperature is 37.9°C (100.2°F). Blood pressure is 138/82 mm Hg in the right arm and 104/70 mm Hg in the left arm. The left radial pulse is weak, and a bruit is heard over the left supraclavicular fossa. Erythrocyte sedimentation rate is 64 mm/h. CT angiography is shown. She has no history of smoking or trauma.{FIG}Which of the following is the most likely diagnosis?",
choices=["Atherosclerotic subclavian stenosis","Coarctation of the aorta","Fibromuscular dysplasia","Giant cell arteritis","Takayasu arteritis","Thoracic outlet syndrome","Thromboangiitis obliterans"], key=4,
exp="A <b>young woman</b> with <b>constitutional symptoms</b> (fever, myalgia, weight loss, high ESR), arm claudication, a <b>pulse and pressure difference between the arms</b> and irregular arch-branch narrowing → <b>Takayasu arteritis</b>, a large-vessel vasculitis of the aorta, its branches and the pulmonary arteries. Diagnosis by angiography (CTA/MRA). Treatment: <b>steroids</b>, revascularization if needed. Age is the near-miss discriminator from giant cell arteritis.<br><br><b>Educational objective:</b> A young woman with constitutional symptoms and unequal arm pulses from arch-branch stenoses has Takayasu arteritis.",
wrong={0:"Would be correct in an older smoker without fever or a high ESR.",
1:"Would be correct for upper-extremity hypertension with weak femoral pulses and radio-femoral delay.",
2:"Would be correct for renal or carotid beading in a young woman without systemic inflammation.",
3:"Would be correct for a patient over 50 with temporal headache and jaw claudication.",
5:"Would be correct for positional arm symptoms from compression at the thoracic outlet, without inflammation.",
6:"Would be correct for distal digital ischemia in a young male smoker."},
eli5="Her immune system is inflaming the big arteries off her heart, narrowing the one to her left arm. That's why that pulse is weak and the arm aches with use."),

dict(img='Vbuerger', cap='Photograph of the left hand (left) and left hand angiogram (right)',
stem="A 35-year-old man comes to the office because of a 3-month history of painful, dusky fingertips on the left hand and a nonhealing ulcer on the index finger. Last year he had tender red cords along veins of his forearm that resolved. He smokes two packs of cigarettes daily. His blood pressure is 124/78 mm Hg. Radial and ulnar pulses are 2+. The hand and its angiogram are shown; proximal arteries are smooth, and there are segmental digital occlusions with tortuous collaterals. Serum lipid and glucose concentrations are within the reference ranges.{FIG}Which of the following is the most effective intervention to prevent amputation?",
choices=["Complete cessation of all tobacco use","High-dose glucocorticoid therapy","Lifelong warfarin therapy","Nifedipine therapy alone","Surgical bypass to the digital arteries"], key=0,
exp="A young male heavy smoker with <b>distal</b> ischemia, preserved proximal pulses, prior <b>migratory superficial thrombophlebitis</b>, and <b>corkscrew collaterals</b> around segmental small-artery occlusions → <b>thromboangiitis obliterans (Buerger disease)</b>, which affects small and medium arteries <b>and veins</b>. The <b>only effective treatment is smoking cessation</b>. Dr. Ciraulo: \"You don't stop smoking, your hand's coming off, pick one.\" Normal lipids and glucose make atherosclerosis unlikely.<br><br><b>Educational objective:</b> Buerger disease is treated by complete tobacco cessation.",
wrong={1:"Would be correct for a steroid-responsive vasculitis such as GCA or Takayasu.",
2:"Would be correct for a cardioembolic or hypercoagulable cause. It doesn't halt Buerger disease.",
3:"Would ease vasospasm in Raynaud, but it can't prevent amputation if smoking continues.",
4:"Would be correct for a focal large-vessel occlusion. Diffuse digital disease has no bypass target."},
eli5="Smoking keeps inflaming and plugging the small arteries of his hand. Stopping completely is the only thing that stops the disease."),

dict(img='Vphleg', cap='Photograph of the legs',
stem="A 58-year-old woman with metastatic ovarian cancer comes to the emergency department because of a 2-day history of rapidly increasing swelling and severe pain of the left leg. The left leg is shown; it is tense, mottled, and bluish from the groin to the toes. Pedal pulses are faint by Doppler, and sensation in the foot is decreased. Duplex ultrasonography shows occlusive thrombus from the common femoral vein through the external and common iliac veins.{FIG}Which of the following is the most likely diagnosis?",
choices=["Acute arterial embolism","Cellulitis","Phlegmasia alba dolens","Phlegmasia cerulea dolens","Post-thrombotic syndrome"], key=3,
exp="Massive <b>iliofemoral DVT</b> → venous outflow blocked → tissue pressure rises until arterial inflow falls → a <b>painful, swollen, blue</b> leg with failing pulses and sensation → <b>phlegmasia cerulea dolens</b>, the <b>reversible phase of ischemic venous occlusion</b>. It precedes <b>venous gangrene</b> (irreversible). <b>Phlegmasia alba dolens</b> (\"milk leg\") is the earlier, non-ischemic, blanched-white stage. The recording called alba \"arterial,\" but both are venous. Management: anticoagulation plus urgent thrombus removal. Cancer drives the hypercoagulability.<br><br><b>Educational objective:</b> A massively swollen, painful, cyanotic leg from iliofemoral DVT is phlegmasia cerulea dolens.",
wrong={0:"Would be correct for a pale, cold, pulseless leg that is NOT swollen and has patent veins.",
1:"Would be correct for warm, erythematous skin infection with fever and patent veins on duplex.",
2:"Would be correct if the leg were swollen and blanched white with intact perfusion.",
4:"Would be correct years after a DVT, with chronic edema, pigmentation and ulceration."},
eli5="The clot blocked all the veins draining her leg. The leg swelled so much that fresh blood could barely get in, so it turned blue."),

dict(img='Ahollen', cap='Fundus photograph of the right eye',
stem="A 70-year-old man comes to the office because of three episodes of painless loss of vision in the right eye during the past 2 weeks, each described as \"a shade coming down\" and lasting about 5 minutes. He has hypertension and hyperlipidemia. His pulse is 74/min and regular, and blood pressure is 152/86 mm Hg. A bruit is heard over the right carotid bifurcation. His right fundus is shown. Neurologic examination shows no abnormalities. ECG shows normal sinus rhythm.{FIG}Which of the following is the most appropriate next step in diagnosis?",
choices=["Carotid duplex ultrasonography","Electroencephalography","Lumbar puncture","MRI of the orbits with contrast","Temporal artery biopsy"], key=0,
exp="Transient monocular blindness = <b>amaurosis fugax</b> → emboli from the <b>carotid bifurcation</b> to the retinal artery. The fundus shows bright yellow refractile <b>Hollenhorst plaques</b> (cholesterol emboli) at arteriolar branch points with retinal whitening. A right carotid bruit and sinus rhythm point to an ipsilateral carotid source. Slide 38: <b>carotid duplex is the primary screening test</b> to grade stenosis (angiography during intervention; echo for a cardiac source). Symptomatic > 70% → endarterectomy.<br><br><b>Educational objective:</b> Amaurosis fugax with Hollenhorst plaques signals carotid atheroembolism. Grade the stenosis with carotid duplex.",
wrong={1:"Would be correct for transient episodes with seizure features.",
2:"Would be correct for suspected meningitis or subarachnoid hemorrhage.",
3:"Would be correct for painful vision loss with optic neuritis or an orbital mass.",
4:"Would be correct with headache, jaw claudication and a high ESR in giant cell arteritis."},
eli5="Little cholesterol bits from his narrowed neck artery keep blocking the eye's artery for a few minutes. An ultrasound of the neck artery shows how narrow it is."),

dict(img='Apseudo', cap='Photograph of the right groin and upper thigh',
stem="A 69-year-old woman is evaluated 1 day after coronary angiography performed through the right common femoral artery because of right groin pain and swelling (shown). Her pulse is 88/min, and blood pressure is 134/80 mm Hg. Hemoglobin concentration is 12.1 g/dL; it was 12.6 g/dL before the procedure. There is a tender, pulsatile, expansile 4-cm mass over the puncture site with a systolic bruit and no continuous thrill. Dorsalis pedis and posterior tibial pulses are 2+. The leg is not swollen.{FIG}Which of the following is the most likely diagnosis?",
choices=["Arteriovenous fistula","Deep venous thrombosis","Femoral artery pseudoaneurysm","Inguinal lymphadenitis","Simple groin hematoma"], key=2,
exp="A <b>pulsatile, expansile</b> mass with a <b>systolic</b> bruit at the puncture site after femoral access → a contained leak through the arterial wall → <b>femoral pseudoaneurysm</b>. Slide 17 lists the access-site complications of percutaneous procedures: bleeding or hematoma, <b>pseudoaneurysm</b>, AV fistula, iliac dissection, thrombosis, distal embolization. Board add-on: confirm with duplex; treat with ultrasound-guided thrombin injection or repair if large. The \"no continuous thrill\" and the non-swollen leg are the negatives that remove the fistula and DVT.<br><br><b>Educational objective:</b> A pulsatile, expansile groin mass with a systolic bruit after femoral catheterization is a pseudoaneurysm.",
wrong={0:"Would be correct with a continuous bruit or thrill and possibly a swollen leg from venous hypertension.",
1:"Would be correct for a swollen leg without a pulsatile groin mass.",
3:"Would be correct for tender, nonpulsatile nodes with fever or a distal infection.",
4:"Would be correct for a nonpulsatile, non-expansile swelling or bruise."},
eli5="The hole in the artery from the catheter never sealed, so blood squirts into a pocket beside it with every heartbeat. That's the throbbing lump."),
]
