# Vascular Disease (Ciraulo) — Version 1, 18 items (6 with images). NBME house-style rewrite (2026-10-02).
Q = [
dict(img=None,
stem="A 71-year-old man comes to the office because of a 6-month history of pain in both buttocks and thighs. The pain begins after he has stood at his workbench for about 10 minutes and resolves within a few minutes when he sits down or leans forward on a shopping cart; walking uphill is easier than walking downhill. He has a 40-pack-year history of cigarette smoking and has hypertension treated with amlodipine. Vital signs are within normal limits. Femoral, popliteal, and pedal pulses are 2+ bilaterally. Straight-leg raising is negative. The ankle-brachial index is 1.08 on the right and 1.10 on the left.{FIG}Which of the following is the most likely diagnosis?",
choices=["Aortoiliac occlusive disease","Chronic exertional compartment syndrome","Femoropopliteal occlusive disease","Lumbar spinal stenosis","Peripheral polyneuropathy","Venous claudication"], key=3,
exp="Pain brought on by <b>standing</b> (not by walking a set distance) → relieved by <b>sitting or lumbar flexion</b> (leaning on a cart, easier uphill) → canal narrowing that widens with flexion → <b>neurogenic claudication from lumbar spinal stenosis</b>. Normal pulses and normal ankle-brachial indices exclude a flow-limiting arterial lesion. The smoking history is the decoy: it surface-reads toward arterial disease. Lecture contrast: vascular claudication is reproducible with exertion and relieved by rest; neurogenic claudication comes with back pain, radiating pain and paresthesia, and occurs with standing.<br><br><b>Educational objective:</b> Leg pain on standing that is relieved by flexion, with normal pulses and ABI, is neurogenic claudication (lumbar stenosis), not arterial disease.",
wrong={0:"Would be correct if the femoral pulses were diminished and the pain came with walking and eased with standing still.",
1:"Would be correct in a young athlete with calf tightness during running that resolves over 20–30 minutes of rest.",
2:"Would be correct if the pain were exertional calf cramping with palpable femoral but absent popliteal and pedal pulses.",
4:"Would be correct if there were constant stocking-distribution numbness unrelated to posture.",
5:"Would be correct if there were a prior iliofemoral DVT with leg swelling and bursting pain on walking."},
eli5="His legs hurt from standing, not from walking far, and bending forward fixes it. That points to pinched nerves in the lower back, not blocked arteries, and his normal pulse tests confirm the arteries are fine."),

dict(img=None,
stem="A 68-year-old man with type 2 diabetes mellitus comes to the office because of a 4-month history of right calf cramping after walking two blocks. Systolic blood pressure is 144 mm Hg in the right arm and 130 mm Hg in the left arm. Doppler systolic pressure is 72 mm Hg at the right ankle and 131 mm Hg at the left ankle.{FIG}Which of the following is the best estimate of the right ankle-brachial index?",
choices=["0.50","0.55","0.91","1.01","2.00"], key=0,
exp="Lecture formula: <b>ABI = ankle systolic pressure ÷ the HIGHER of the two brachial systolic pressures</b> → right = 72 ÷ 144 = <b>0.50</b>. Using the higher arm protects against underestimating central pressure when one subclavian is stenosed (here the 14 mm Hg arm difference). Board add-on cut-offs: ≥ 1.0 normal · ≤ 0.9 PAD · < 0.4 severe · > 1.4 non-compressible (diabetes, CKD).<br><br><b>Educational objective:</b> Each ankle pressure is divided by the higher of the two brachial pressures.",
wrong={1:"Would be correct if the lower (left) arm pressure were used as the denominator: 72 ÷ 130.",
2:"Would be correct for the left leg: 131 ÷ 144.",
3:"Would be correct for the left ankle divided by the lower arm pressure: 131 ÷ 130.",
4:"Would be correct only if the ratio were inverted (arm ÷ ankle): 144 ÷ 72."},
eli5="Take the ankle pressure and divide it by the bigger arm pressure: 72 ÷ 144 = 0.5. Only half the expected pressure reaches that ankle."),

dict(img=None,
stem="A 74-year-old man is referred to a vascular surgeon for planning of an elective repair of an abdominal aortic aneurysm. Six months ago, an ultrasonography done for back pain showed a 5.8-cm infrarenal aneurysm. A catheter aortogram done at another hospital last week showed a contrast-filled lumen 2.6 cm in diameter, and the patient was told that his aorta is \"normal size.\" He has a 50-pack-year history of cigarette smoking. Serum creatinine concentration is 1.0 mg/dL. A nontender pulsatile mass is palpated above the umbilicus.{FIG}Which of the following is the most appropriate next step in diagnosis?",
choices=["Abdominal CT angiography","Plain abdominal x-ray","Repeat catheter aortography","Serum D-dimer concentration","Transesophageal echocardiography","Ultrasonography in 6 months"], key=0,
exp="An angiogram shows only where contrast flows → <b>mural thrombus</b> lining an aneurysm leaves a narrow channel that looks normal. Dr. Ciraulo: \"The way they trick you on exams is to say the hallmark for making this diagnosis is an aortogram. That's not true.\" <b>CT with contrast is the gold standard</b>: outer diameter, thrombus, relation to the renal arteries, iliac and access anatomy for EVAR (neck > 15 mm, angle < 60°, calcification < 50%). Normal creatinine → contrast is acceptable. Angiography is reserved for the table.<br><br><b>Educational objective:</b> CT angiography, not catheter angiography, diagnoses and sizes an aortic aneurysm, because thrombus hides the true diameter on a luminogram.",
wrong={1:"Would be correct only for an incidental eggshell calcification on a film obtained for another reason. It can't size or plan.",
2:"Would be correct on the operating table to size a stent graft, not to establish the true diameter.",
3:"Would be considered for suspected venous thromboembolism.",
4:"Would be correct for suspected thoracic dissection in an unstable patient.",
5:"Would be correct for surveillance of an asymptomatic aneurysm < 4.5 cm, not one already above repair threshold."},
eli5="Dye only lights up the open channel, and clot lining the bulge hides how big it really is. A CT scan shows the whole wall and the clot."),

dict(img=None,
stem="A 58-year-old man comes to the office requesting a prescription for sildenafil. He reports a 9-month history of erectile dysfunction and an aching pain in both buttocks and thighs that begins after he climbs one ladder at work and resolves after 3 minutes of rest. He has a 35-pack-year history of cigarette smoking and hyperlipidemia. His pulse is 76/min, and blood pressure is 142/86 mm Hg. Femoral pulses are faint bilaterally, and popliteal and pedal pulses are not palpable. Testicular examination shows no abnormalities. Serum testosterone concentration is within the reference range.{FIG}The arterial lesion is most likely located at which of the following sites?",
choices=["Aortic bifurcation","Common femoral artery","Internal pudendal artery","Popliteal artery","Superficial femoral artery in the adductor canal","Tibioperoneal trunk"], key=0,
exp="<b>Bilateral buttock and thigh claudication + erectile dysfunction + diminished femoral pulses</b> = <b>Leriche syndrome</b> → occlusion at the <b>aortic bifurcation</b> (infrarenal aortoiliac disease). The bilateral, proximal (buttock) distribution and the weak femorals place the lesion above the inguinal ligament. Normal testosterone and testes remove the endocrine decoy. \"Don't just write a prescription for Viagra.\"<br><br><b>Educational objective:</b> Bilateral buttock claudication with impotence and weak femoral pulses localizes to the aortic bifurcation (Leriche syndrome).",
wrong={1:"Would be correct if the symptoms and the weak femoral pulse were unilateral, with thigh rather than buttock pain.",
2:"Would be correct for isolated vasculogenic impotence with normal femoral pulses and no limb claudication.",
3:"Would be correct for calf claudication or a pulsatile mass behind the knee with normal femoral pulses.",
4:"Would be correct for calf claudication with strong femoral and absent popliteal pulses.",
5:"Would be correct for foot claudication and tissue loss in a diabetic with normal femoral and popliteal pulses."},
eli5="One blockage right where the aorta splits starves both legs, both buttocks and the penis, and makes both groin pulses weak."),

dict(img=None,
stem="A 66-year-old woman comes to the office because of a 1-year history of cramping in the right calf after walking three blocks; it resolves after 2 minutes of rest. She has no pain at rest and no foot wounds. She has ischemic cardiomyopathy with a left ventricular ejection fraction of 25%. She stopped smoking 2 years ago. Current medications are aspirin, atorvastatin, carvedilol, sacubitril-valsartan, and spironolactone. Her pulse is 64/min, and blood pressure is 112/70 mm Hg. The right popliteal and pedal pulses are diminished; the skin of the feet is intact. The ankle-brachial index is 0.68 on the right.{FIG}Which of the following is the most appropriate next step in management?",
choices=["Aortobifemoral bypass","Cilostazol therapy","Endovascular stenting of the superficial femoral artery","Lumbar sympathectomy","Supervised exercise therapy","Warfarin therapy"], key=4,
exp="Stable claudication without rest pain or tissue loss → <b>conservative therapy first</b>: smoking cessation (done), antiplatelet and statin (already on), and a <b>graded/supervised exercise programme</b>, which is very effective (it develops collaterals and relieves symptoms). The buried clue is the <b>ejection fraction of 25%</b>: <b>cilostazol</b>, a PDE3 inhibitor and the only drug that improves claudication, is <b>contraindicated in heart failure</b>.<br><br><b>Educational objective:</b> Treat stable claudication conservatively with supervised exercise. Cilostazol is contraindicated in heart failure.",
wrong={0:"Would be correct for disabling aortoiliac disease with weak femoral pulses after failed conservative therapy.",
1:"Would be correct if her ejection fraction were normal and claudication persisted despite exercise.",
2:"Would be considered for lifestyle-limiting claudication, rest pain or tissue loss despite exercise therapy.",
3:"Would be considered for refractory vasospasm (Raynaud), not occlusive claudication.",
5:"Would be correct for a cardiac embolic source such as atrial fibrillation, not for atherosclerotic claudication."},
eli5="Walking training builds detour blood vessels. The usual walking pill is off-limits because her heart pumps weakly."),

dict(img=None,
stem="A 79-year-old man is brought to the emergency department 4 hours after the sudden onset of pain and numbness in the left leg. His history includes a CABG 10 years ago, a duodenal ulcer treated 6 years ago, atrial fibrillation for which he stopped taking apixaban 1 month ago, and an ischemic stroke with full recovery 6 weeks ago. Five weeks ago, he underwent arthroscopic knee debridement. His pulse is 104/min and irregularly irregular, and blood pressure is 150/88 mm Hg. The left leg is cool and pale from the mid-calf down, with no palpable popliteal or pedal pulses; sensation is decreased in the foot, and toe movement is intact. An infusion of heparin is started.{FIG}Which of the following findings in this patient's history most strongly argues against catheter-directed thrombolysis?",
choices=["Age of 79 years","Arthroscopic knee surgery 5 weeks ago","Atrial fibrillation","CABG 10 years ago","Duodenal ulcer 6 years ago","Ischemic stroke 6 weeks ago"], key=5,
exp="Slide 31: thrombolysis is preferred for acute limb ischemia with <b>intact motor and sensory function</b>, but its <b>absolute contraindications</b> are <b>stroke or brain surgery within 2 months</b>, <b>major surgery within 2 weeks</b>, and significant bleeding risk. A stroke 6 weeks ago falls inside the 2-month window → lysis is out → open <b>Fogarty embolectomy</b>. Atrial fibrillation is the <b>cause</b> (left atrial thrombus), the decoy. The ulcer was remote and healed, and the arthroscopy was minor and over 2 weeks ago.<br><br><b>Educational objective:</b> A stroke within 2 months is an absolute contraindication to thrombolysis for acute limb ischemia.",
wrong={0:"Would be decisive only if combined with active bleeding risk. Age alone is not an absolute contraindication.",
1:"Would be correct if the operation were major surgery performed within the past 2 weeks.",
2:"Would be correct to explain the cause of the occlusion, not a reason to withhold lysis.",
3:"Would be correct only for a recent (days to weeks) sternotomy, not one done 10 years ago.",
4:"Would be correct if the ulcer were active or had bled recently."},
eli5="Clot-busting drugs could make his recent brain stroke bleed, and 6 weeks isn't long enough for it to have healed."),

dict(img=None,
stem="A 52-year-old man with long-standing hypertension is brought to the emergency department 1 hour after the sudden onset of severe tearing pain between his shoulder blades. His pulse is 108/min, and blood pressure is 168/96 mm Hg in the right arm and 150/90 mm Hg in the left arm. A soft diastolic murmur is heard along the left sternal border. CT angiography shows an intimal flap beginning 2 cm above the aortic valve and ending proximal to the brachiocephalic artery; the descending aorta is normal. Serum troponin concentration is within the reference range.{FIG}Which of the following is the most appropriate definitive management?",
choices=["Antihypertensive therapy and serial CT","Emergency open repair of the ascending aorta","Percutaneous coronary intervention","Thoracic endovascular aortic repair","Thrombolytic therapy"], key=1,
exp="A dissection limited to the <b>ascending aorta</b> → <b>DeBakey II = Stanford A</b>. The new diastolic murmur (aortic regurgitation from root involvement) shows how proximal it is. <b>Stanford A → emergency open repair</b> (root, ± valve). <b>Uncomplicated Stanford B</b> (distal to the left subclavian) → BP control, with TEVAR for complications. The normal troponin removes the ACS decoy.<br><br><b>Educational objective:</b> Any dissection involving the ascending aorta (Stanford A, DeBakey I or II) needs emergency open repair.",
wrong={0:"Would be correct for an uncomplicated dissection beginning distal to the left subclavian artery (Stanford B).",
2:"Would be correct for an acute coronary occlusion with ST elevation and rising troponin, not a dissection flap.",
3:"Would be correct for a complicated Stanford B dissection (malperfusion or failed medical therapy).",
4:"Would be correct for an occlusive thrombus, never for a dissection."},
eli5="The tear is right next to the heart, where it can rip the aortic valve or burst into the heart sac, so surgeons repair it immediately."),

dict(img=None,
stem="A 70-year-old man comes to the office for follow-up of an abdominal aortic aneurysm found incidentally on ultrasonography 12 months ago. He has no abdominal or back pain. He smokes one pack of cigarettes daily. His blood pressure is 136/82 mm Hg. A nontender pulsatile mass is palpated in the epigastrium. Today's ultrasonography shows a fusiform infrarenal aneurysm measuring 4.7 cm; it measured 4.5 cm 12 months ago. He has no family history of aneurysm.{FIG}In addition to smoking cessation counseling, which of the following is the most appropriate next step in management?",
choices=["Endovascular repair now","Open surgical repair now","Ultrasonography in 3 months","Ultrasonography in 6 months","Ultrasonography in 12 months"], key=2,
exp="Dr. Ciraulo: \"You're gonna have something on this on the test.\"<br>• <b>< 4.5 cm</b> → ultrasound every 6 months.<br>• <b>4.5–5.0 cm</b> → <b>every 3 months</b> (\"the danger zone\").<br>• 5.0–5.5 cm → repair if female, familial or proven rapid growth.<br>• <b>> 5.5 cm</b> → repair.<br>Also repair if symptomatic, growing > 5 mm in 6 months, or saccular. His growth (0.2 cm in 12 months) is within the expected 0.2–0.3 cm/year → surveillance at 3 months.<br><br><b>Educational objective:</b> An asymptomatic AAA of 4.5–5.0 cm with expected growth is followed with ultrasonography every 3 months.",
wrong={0:"Would be correct for an aneurysm > 5.5 cm, a symptomatic one, or growth > 5 mm in 6 months, with suitable anatomy.",
1:"Would be correct for the same indications when the anatomy is unsuitable for a stent graft.",
3:"Would be correct for an aneurysm < 4.5 cm.",
4:"Would be correct for neither band. Yearly imaging is too infrequent for any aneurysm on the lecture chart."},
eli5="At 4.7 cm the aneurysm is close to the size where surgery is needed, so it's rechecked every 3 months."),

dict(img=None,
stem="Patient Information\nAge: 71 years · Gender: M · Site of Care: emergency department\n\nHistory\nReason for Visit: vomiting blood\nHistory of Present Illness: vomited about 50 mL of bright red blood 6 hours ago, then felt well; 30 minutes ago vomited a large volume of blood and felt faint\nPast Medical History: open repair of an abdominal aortic aneurysm with a Dacron tube graft 6 years ago; hypertension\nMedications: amlodipine\nPsychosocial History: does not drink alcohol; takes no NSAIDs\n\nPhysical Examination\nT 37.0°C (98.6°F) · P 128/min · R 22/min · BP 84/50 mm Hg\nPale and diaphoretic; healed midline laparotomy scar; abdomen soft and nontender; no spider angiomata or splenomegaly; no retching before the first episode\n\nQuestion: Which of the following is the most likely diagnosis?",
choices=["Aortoenteric fistula","Bleeding esophageal varices","Bleeding peptic ulcer","Dieulafoy lesion","Ischemic colitis","Mallory-Weiss tear"], key=0,
exp="A <b>prior aortic graft + upper GI bleeding</b>, with a small <b>herald bleed</b> hours before a massive one → <b>aortoenteric (aortoduodenal) fistula</b>: the graft erodes into the third or fourth part of the duodenum. Dr. Ciraulo: bleeding \"like a hose coming out of you.\" Diagnosis: endoscopy and CT. Treatment: graft removal and extra-anatomic bypass, sometimes after a temporizing stent graft. The negatives clear the competitors: no alcohol or stigmata of liver disease (varices), no NSAIDs (ulcer), no retching (Mallory-Weiss).<br><br><b>Educational objective:</b> GI bleeding (especially a herald bleed) in a patient with an aortic graft is an aortoenteric fistula until proven otherwise.",
wrong={1:"Would be correct with cirrhosis or portal hypertension (alcohol, spider angiomata, splenomegaly).",
2:"Would be correct with NSAID use or Helicobacter pylori infection and no vascular graft.",
3:"Would be a consideration for massive bleeding from a gastric submucosal artery without a graft history. The graft makes the fistula the must-not-miss answer.",
4:"Would be correct for bloody diarrhea within days of aortic surgery, not hematemesis years later.",
5:"Would be correct after forceful retching or vomiting, typically with alcohol use."},
eli5="His old aortic graft has worn a hole into the gut beside it. A small warning bleed came first, then the big one."),

dict(img=None,
stem="A 57-year-old woman comes to the office because of a 7-month history of crampy periumbilical pain that begins about 30 minutes after meals and lasts 1–2 hours. She has lost 9 kg (20 lb) because she eats only small amounts. She has a 45-pack-year history of cigarette smoking. Her pulse is 78/min, and blood pressure is 148/88 mm Hg. Abdominal examination shows a soft, nontender abdomen with an epigastric bruit. Upper endoscopy 2 months ago showed no abnormalities. Abdominal ultrasonography shows no gallstones.{FIG}Which of the following is the most appropriate next step in diagnosis?",
choices=["Colonoscopy","CT angiography of the abdomen","Hepatobiliary iminodiacetic acid scan","Repeat upper endoscopy","Small-bowel follow-through"], key=1,
exp="<b>Postprandial pain 30–90 minutes after eating + food fear + weight loss + epigastric bruit in a smoker</b> → <b>chronic mesenteric ischemia</b>: atherosclerotic stenosis can't meet the post-meal rise in demand. <b>CTA is the diagnostic modality of choice</b> (duplex ~80% sensitive and specific; the angiogram is the gold standard, used with endovascular treatment). Treatment: revascularization. The explicit negatives remove the dramatic decoys of peptic disease and biliary colic.<br><br><b>Educational objective:</b> Suspected chronic mesenteric ischemia is diagnosed with CT angiography.",
wrong={0:"Would be correct for bloody stools, anemia or a change in bowel habit suggesting a colonic lesion.",
2:"Would be correct for suspected acalculous cholecystitis or biliary dyskinesia with right-upper-quadrant pain.",
3:"Would be correct if the recent endoscopy had shown an ulcer needing follow-up.",
4:"Would be correct for suspected small-bowel mucosal disease or obstruction, not a vascular cause."},
eli5="Her gut arteries are narrowed, so eating, which needs extra blood flow, hurts. A CT scan of the arteries shows the narrowing."),

dict(img=None,
stem="A 63-year-old man is evaluated 7 days after total hip arthroplasty because of a new cold, painful left foot. He has received subcutaneous unfractionated heparin since admission. Results of laboratory studies:\n\nPlatelet count: day 1, 248,000/mm3; day 7, 92,000/mm3\nProthrombin time: 12 sec\nPartial thromboplastin time: 34 sec\nFibrinogen: 340 mg/dL (N=200–400)\n\nThe left popliteal and pedal pulses are absent. He has no petechiae, gum bleeding, or wound oozing.{FIG}Which of the following is the most likely mechanism of this patient's thrombocytopenia?",
choices=["Consumption of platelets and clotting factors","Direct nonimmune heparin–platelet aggregation","Hypersplenism with sequestration","IgG against heparin–PF4 complexes","Marrow suppression by the drug","Transfusion-related dilution"], key=3,
exp="Platelets fall by > 50% on <b>day 5–10</b> of heparin, <b>with a new arterial thrombosis</b> → <b>heparin-induced thrombocytopenia</b>: IgG binds heparin–PF4 → immune complexes activate platelets via Fc receptors → thrombocytopenia <b>and thrombosis</b>. The lab panel is the buried clue: normal PT, aPTT and fibrinogen exclude DIC. The decoy is the low platelet count itself, which tempts a bleeding diagnosis. Treatment: stop all heparin and start a direct thrombin inhibitor (argatroban, bivalirudin). Confirm with a PF4 antibody or serotonin release assay.<br><br><b>Educational objective:</b> HIT is an IgG response to heparin–PF4 that causes thrombocytopenia with thrombosis on days 5–10.",
wrong={0:"Would be correct (DIC) if the PT and aPTT were prolonged and fibrinogen low.",
1:"Would be correct for a mild, early (days 1–2), non-thrombotic drop that recovers on continued heparin.",
2:"Would be correct with splenomegaly and a stable, chronically low count.",
4:"Would be correct with a gradual fall of all cell lines over weeks.",
5:"Would be correct after massive transfusion, not 7 days into an uncomplicated recovery."},
eli5="His immune system made antibodies to heparin that make platelets clump. That uses up platelets and forms clots, which is how his leg artery blocked."),

dict(img=None,
stem="A 34-year-old man is admitted to the intensive care unit after a motorcycle collision with an acute subdural hematoma and an unstable pelvic fracture. On hospital day 4, duplex ultrasonography shows an occlusive thrombus in the left common femoral vein extending into the external iliac vein. His pulse is 92/min, and blood pressure is 128/78 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 97%. A repeat CT scan of the head shows the hematoma is unchanged in size.{FIG}Which of the following is the most appropriate next step in management?",
choices=["Catheter-directed thrombolysis","Full-dose intravenous heparin","Graduated compression stockings only","Retrievable vena cava filter","Warfarin with a target INR of 2–3"], key=3,
exp="A proximal DVT needs treatment: untreated proximal DVT carries a <b>30–50% risk of pulmonary embolism</b>. But an <b>intracranial hemorrhage contraindicates anticoagulation</b>. Slide 82: IVC filters are used when anticoagulation is contraindicated, placed immediately, and a <b>retrievable</b> design is preferred (snared off its hook once the risk passes or anticoagulation becomes safe).<br><br><b>Educational objective:</b> A proximal DVT in a patient who can't be anticoagulated is managed with a retrievable IVC filter.",
wrong={0:"Would be considered for limb-threatening iliofemoral DVT (phlegmasia) without a bleeding contraindication.",
1:"Would be correct if there were no intracranial hemorrhage.",
2:"Would be correct only as an adjunct. Stockings don't prevent embolism from an existing proximal DVT.",
4:"Would be correct (after heparin overlap) in a patient without a bleeding contraindication."},
eli5="He can't take blood thinners with bleeding in his skull, so a small metal net in the big vein catches clots before they reach his lungs."),

dict(img='Advt', cap='Photograph of the lower legs',
stem="A 58-year-old woman comes to the office because of a 2-day history of swelling and aching of the left leg. Nine days ago she underwent total knee arthroplasty on the left. Her temperature is 37.4°C (99.3°F), pulse is 88/min, respirations are 16/min, and blood pressure is 128/76 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 98%. Her legs are shown; the left calf is warm and tender, and dorsiflexion of the left ankle causes calf pain. The lungs are clear.{FIG}Which of the following is the most appropriate next step in diagnosis?",
choices=["Ankle-brachial index","Duplex ultrasonography of the leg","Contrast venography of the left leg","CT pulmonary angiography","Serum D-dimer concentration"], key=1,
exp="Unilateral swelling, warmth, calf tenderness and pain on dorsiflexion (Homans sign) after knee replacement (50–60% DVT incidence without prophylaxis) → suspected <b>DVT</b> → <b>duplex ultrasonography</b>: \"let's get a duplex ultrasound, we'll tell you what's going on.\" The buried clue is <b>9 days after surgery</b>: the D-dimer is elevated after any operation, so it can't confirm or exclude. Board add-on: D-dimer only rules out DVT when pretest probability is low.<br><br><b>Educational objective:</b> Suspected DVT is confirmed with compression duplex ultrasonography. D-dimer is uninformative after surgery.",
wrong={0:"Would be correct to assess arterial insufficiency (claudication, absent pulses), not venous thrombosis.",
2:"Would be correct only when ultrasound is unavailable or nondiagnostic. It's invasive and mostly of historical interest.",
3:"Would be correct with dyspnea, pleuritic pain or hypoxemia suggesting pulmonary embolism.",
4:"Would be correct only to rule out DVT in a low-probability outpatient without recent surgery."},
eli5="An ultrasound can see the clot in her leg vein directly. The D-dimer blood test is always high after surgery, so it can't help."),

dict(img='Acarotid', cap='Selective angiogram of the left carotid bifurcation',
stem="A 69-year-old man comes to the office because of two episodes of right-hand weakness and difficulty finding words during the past 3 weeks; each lasted about 20 minutes and resolved completely. He has hypertension and hyperlipidemia. His pulse is 72/min and regular, and blood pressure is 146/84 mm Hg. Neurologic examination shows no abnormalities. A bruit is heard over the left side of the neck. ECG shows normal sinus rhythm. MRI of the brain shows no infarct. Duplex ultrasonography and the angiogram shown demonstrate an 80% stenosis of the left internal carotid artery; the right is 30% stenotic.{FIG}In addition to aspirin and a statin, which of the following is the most appropriate next step in management?",
choices=["Anticoagulation with warfarin","Left carotid endarterectomy","Medical therapy alone with duplex in 6 months","Right carotid endarterectomy","Vertebral artery angioplasty"], key=1,
exp="Transient left-hemisphere deficits (right hand, language) lasting < 24 h with no infarct → <b>TIAs</b> from the <b>left</b> carotid → a <b>symptomatic 80% stenosis</b>. Slide 39: symptomatic stenosis > 70% → surgery lowers the 2-year stroke risk from <b>26% to 9%</b>. <b>Carotid endarterectomy</b> with patch closure (watch the hypoglossal and vagus nerves). Normal sinus rhythm removes the cardioembolic decoy.<br><br><b>Educational objective:</b> Symptomatic carotid stenosis > 70% is treated with carotid endarterectomy plus medical therapy.",
wrong={0:"Would be correct for a cardioembolic source such as atrial fibrillation.",
2:"Would be correct for a symptomatic stenosis < 50% or a patient too high-risk for any intervention.",
3:"Would be correct if the symptoms were left-sided (right hemisphere) with a severe right stenosis.",
4:"Would be correct for posterior-circulation symptoms (vertigo, ataxia, diplopia)."},
eli5="The tight plaque in his left neck artery keeps throwing tiny clots to the left side of his brain. Cleaning it out sharply cuts his stroke risk."),

dict(img='Avenulcer', cap='Photograph of the medial left lower leg',
stem="A 64-year-old woman comes to the office because of a 6-month history of a painful wound above the left medial malleolus. Four years ago she had an iliofemoral deep venous thrombosis of the left leg and completed 6 months of anticoagulation. She reports leg heaviness that worsens by evening and improves overnight. The wound is shown; there is surrounding brown pigmentation and pitting edema to the mid-calf. Dorsalis pedis and posterior tibial pulses are 2+, and the ankle-brachial index is 1.02.{FIG}Which of the following is the most appropriate initial management?",
choices=["Below-knee amputation","Compression and leg elevation","Femoropopliteal arterial bypass","Lifelong warfarin therapy","Systemic thrombolytic therapy"], key=1,
exp="<b>Post-thrombotic syndrome</b> after an iliofemoral DVT: venous hypertension and valve damage → swelling, evening heaviness, pigmentation (lipodermatosclerosis) and a <b>medial malleolar ulcer</b>. The normal pulses and ABI are the buried negative that exclude an arterial ulcer. Therapy: <b>compression</b> (\"probably one of the most important things\") and elevation, plus wound care. Iliac vein angioplasty or stenting if a stenosis is found (50–75% of patients).<br><br><b>Educational objective:</b> Post-thrombotic venous ulcers are treated with compression and elevation.",
wrong={0:"Would be considered only for a non-salvageable, infected or necrotic limb.",
2:"Would be correct for an arterial ulcer with absent pulses and a low ABI.",
3:"Would be correct for recurrent or unprovoked VTE, not to heal damaged valves.",
4:"Would be considered only for an acute, limb-threatening DVT, not a 4-year-old one."},
eli5="The old clot broke the one-way valves in her leg veins, so blood pools and the skin breaks down. Squeezing the leg with compression pushes the blood back up."),

dict(img='Vgraftinf', cap='Axial contrast-enhanced CT of the abdomen at the level of the graft',
stem="A 70-year-old man comes to the emergency department because of a 3-week history of dull abdominal pain and intermittent fevers. Three years ago he underwent aortobifemoral bypass for aortoiliac occlusive disease. His temperature is 38.6°C (101.5°F), pulse is 104/min, and blood pressure is 132/78 mm Hg. Femoral pulses are palpable. The leukocyte count is 16,500/mm3. CT of the abdomen is shown; there is fluid and gas around the body of the graft below the renal arteries. Blood cultures grow Staphylococcus aureus. Endoscopy shows no communication with the bowel.{FIG}Which of the following is the most appropriate definitive management?",
choices=["Graft excision and extra-anatomic bypass","Intravenous antibiotics alone for 6 weeks","Percutaneous drainage with graft retention","Placement of a new stent graft inside the old graft","Repeat CT in 1 week"], key=0,
exp="<b>Fever + abdominal pain + leukocytosis + perigraft fluid and gas</b> after aortic grafting → <b>aortic graft infection</b>. Slide 54: antibiotics + <b>graft removal</b> + extra-anatomic bypass. Because the graft is <b>infrarenal</b>, an axillobifemoral bypass keeps the legs perfused outside the infected field. \"Graft infections basically mean you take the damn graft out.\" The negative endoscopy rules out a fistula.<br><br><b>Educational objective:</b> An infected aortic graft is managed with graft excision, extra-anatomic bypass and antibiotics.",
wrong={1:"Would be correct only for superficial wound cellulitis without perigraft involvement.",
2:"Would be considered as a temporary bridge in a patient too sick for surgery. It leaves the infected prosthesis in place.",
3:"Would be considered only as a temporizing measure for a bleeding aortoenteric fistula.",
4:"Would be correct for perigraft fluid in the first weeks after surgery without fever or bacteremia."},
eli5="Germs living on plastic can't be cleared by antibiotics alone, so the graft comes out and blood is rerouted through a new graft placed away from the infection."),

dict(img='Alivedo', cap='Photograph of the skin of the lower legs',
stem="A 72-year-old man comes to the office because of a 2-week history of painful purple discoloration of several toes and a lacy rash on both legs. Three weeks ago he underwent cardiac catheterization and stenting through the right femoral artery. His temperature is 37.0°C (98.6°F), pulse is 76/min and regular, and blood pressure is 152/88 mm Hg. The skin of the legs is shown. Dorsalis pedis and posterior tibial pulses are 2+ bilaterally. Laboratory studies:\n\nCreatinine: 2.4 mg/dL (1.1 mg/dL before the procedure)\nEosinophils: 9%\nUrinalysis: no blood or casts\n\nEchocardiography shows no intracardiac thrombus or vegetation.{FIG}Which of the following is the most likely cause of this patient's findings?",
choices=["Atheroemboli from the aortic wall","Contrast-induced tubular necrosis","Infective endocarditis","Left atrial thrombus","Polyarteritis nodosa"], key=0,
exp="Livedo reticularis + <b>blue toes with palpable pulses</b> (microemboli to small distal vessels) + subacute AKI + eosinophilia, <b>weeks after a femoral catheter procedure</b> → <b>atheroembolization</b>. Catheters scrape cholesterol from aortic plaque (lecture: iatrogenic atheroembolization after percutaneous interventions). The 3-week interval is the buried clue, and contrast is the decoy. Board add-on: low complement, cholesterol clefts on biopsy.<br><br><b>Educational objective:</b> Blue toes with intact pulses, livedo and delayed kidney injury after catheterization mean cholesterol (athero-) embolization.",
wrong={1:"Would be correct for a creatinine peaking 2–5 days after contrast, without skin or toe findings.",
2:"Would be correct with fever, a murmur or a vegetation on echocardiography.",
3:"Would be correct with atrial fibrillation and a macroembolus occluding a larger artery (absent pulses).",
4:"Would be correct with mononeuritis, hypertension and microaneurysms, unrelated to a procedure."},
eli5="The catheter scraped tiny bits of cholesterol off the aorta wall. They showered into the small arteries of his toes, skin and kidneys."),

dict(img='Vcfa', cap='Digital subtraction angiogram of the right groin and thigh',
stem="A 66-year-old woman comes to the office because of an 8-month history of right thigh and calf claudication after one block that has not improved despite 3 months of supervised exercise, smoking cessation, aspirin, and atorvastatin. She has no rest pain or wounds. The right femoral pulse is absent; the left is normal. The angiogram shown demonstrates a 3-cm occlusion confined to the common femoral artery, with reconstitution of the profunda femoris and superficial femoral arteries below it; the aorta and iliac arteries are normal.{FIG}Which of the following is the most appropriate operation?",
choices=["Aortobifemoral bypass","Axillobifemoral bypass","Femoral endarterectomy with patch","Femoral–tibial bypass with saphenous vein","Lumbar sympathectomy"], key=2,
exp="Lifestyle-limiting claudication despite best medical therapy → intervention. A <b>short, focal common femoral lesion</b> with normal inflow (aorta and iliacs) → slide 24: <b>local endarterectomy of the common femoral and profunda with patch angioplasty</b>, \"good for local lesions.\" The common femoral flexes with the hip, so stents fare poorly there, and the profunda is the key thigh collateral. Bypass procedures treat longer or more proximal disease.<br><br><b>Educational objective:</b> A focal common femoral (± profunda) occlusion is treated with endarterectomy and patch angioplasty.",
wrong={0:"Would be correct for bilateral aortoiliac occlusion with weak femoral pulses on both sides.",
1:"Would be correct for aortoiliac disease in a patient too high-risk for an aortic operation.",
3:"Would be correct for infrageniculate (tibial) disease with tissue loss.",
4:"Would be considered for refractory vasospasm, not an occlusive lesion."},
eli5="The blockage is short and right in the groin, so the surgeon opens the artery, scoops out the plaque and patches it closed."),
]
