# Cardiovascular Health in Women (Qazi) — Version 1, 18 items (2 with images). NBME house-style rewrite (2026-10-02).
Q = [
dict(img=None,
stem="A 42-year-old woman comes to the office for a health maintenance examination. She has smoked one pack of cigarettes daily for 20 years. Her mother died of a myocardial infarction at age 58. When the physician recommends a lipid panel, she says, \"Heart disease is a man's problem. Women don't have heart attacks until after menopause, so I'm not worried.\" Her blood pressure is 142/90 mm Hg.{FIG}Which of the following is the most appropriate initial response by the physician?",
choices=["\"That's a common belief, but heart disease is the leading killer of women. Shall we review your own risks together?\"","\"I'd like you to see a cardiologist, who can explain your heart risk much better than I can right now.\"","\"That's mostly true at your age, so let's revisit your heart risk once you have gone through menopause.\"","\"Honestly, with your smoking and your mother's history, you really should know better than to say that.\"","\"To be safe, we'll start you on aspirin and a statin today and recheck everything in three months.\""], key=0,
exp="The lecture's two myths: heart disease is \"a man's disease,\" and heart attacks occur in women only after menopause. In fact <b>CVD is the leading cause of death in US women (1 in 3 deaths)</b>, more than 10,000 women under 45 have an MI each year, and under 65 a woman's MI mortality is almost <b>twice</b> a man's. The best response <b>corrects the misconception without judgment</b> and <b>invites shared exploration</b> of her own risks: smoking, hypertension, and a premature family history.<br><br><b>Educational objective:</b> Correct the \"heart disease is a man's disease\" myth with facts and engage the patient in assessing her own risk.",
wrong={1:"Offloads to another service. That would only be appropriate after the PCP's own assessment found complex disease.",
2:"False reassurance. It accepts the myth and delays care for a woman with three active risk factors.",
3:"Judgment and blame. That would only be fitting if the goal were to end the conversation, not engage her.",
4:"A premature, closed plan before exploring her views or completing the risk assessment."},
eli5="Heart disease kills more women than anything else, even before menopause. The doctor kindly corrects her and offers to look at her own risks together."),

dict(img=None,
stem="A medical student completes cardiovascular risk worksheets for two 47-year-old patients, a woman and a man. Both are nonsmokers with normal blood pressure, lipid concentrations, glucose concentration, and BMI, and neither has a family history of premature cardiovascular disease. The student must decide whether age itself counts as a traditional risk factor for each patient.{FIG}According to the lecture, beginning at which age does age count as a traditional coronary risk factor in women?",
choices=["40 years","45 years","50 years","55 years","65 years"], key=2,
exp="Slide 10's traditional risk factors for CAD/MI: <b>age (men > 40, women > 50)</b>, family history, smoking, high blood pressure, high cholesterol, diabetes, physical inactivity, obesity. At 47, age counts for the man but not yet for the woman. Women's coronary disease lags men's by about a decade and accelerates after menopause. The prevalence chart shows women catching up at 60–79 and overtaking men at 80+.<br><br><b>Educational objective:</b> Age becomes a traditional coronary risk factor at > 40 in men and > 50 in women.",
wrong={0:"Would be correct for men.",
1:"Would be correct for neither sex in the lecture's list. It's a midpoint guess.",
3:"Would be correct for neither sex in the lecture's list. It's another midpoint guess.",
4:"Would be correct for no lecture threshold. 65 is a Medicare and geriatric cut-off."},
eli5="On the classic risk list, age starts counting at 40 for men and 50 for women."),

dict(img=None,
stem="A 46-year-old woman, gravida 3, para 3, comes to the office to establish care. Her history includes an appendectomy at age 20, lactose intolerance, preeclampsia that required delivery at 35 weeks' gestation in two of her pregnancies, and breastfeeding each child for 12 months. She uses a copper intrauterine device. Menarche occurred at age 13. She does not smoke. Her blood pressure is 128/80 mm Hg, and BMI is 24 kg/m2. Fasting lipid and glucose concentrations are within the reference ranges.{FIG}Which of the following factors in her history most increases her risk of future cardiovascular disease?",
choices=["Age at menarche","Appendectomy","Breastfeeding history","Copper intrauterine device","Preeclampsia in two pregnancies"], key=4,
exp="Slide 11's <b>female-specific risk enhancers</b>: age at menarche, postmenopausal status, and <b>pregnancy-related complications</b>. <b>Preeclampsia</b>, a placentally mediated syndrome of hypertension and proteinuria (2–8% of pregnancies), predicts later heart failure, CHD, stroke and chronic hypertension. Recurrence and preterm delivery strengthen the signal. Her menarche at <b>13</b> is the nadir of the U-shaped risk curve. Her normal BP and lipids are the decoy: today's numbers don't erase the pregnancy signal.<br><br><b>Educational objective:</b> Preeclampsia is a female-specific risk enhancer for later cardiovascular disease, even when current risk factors are normal.",
wrong={0:"Would be correct if menarche had occurred at 10 or younger (RR 1.27) or at 17 or older.",
1:"Would be correct for no cardiovascular outcome. Remote abdominal surgery isn't a CV risk factor.",
2:"Would be correct for no lecture risk. If anything, breastfeeding is associated with lower maternal CV risk.",
3:"Would be correct for no cardiovascular risk. Copper IUDs are hormone-free (unlike estrogen-containing contraception)."},
eli5="Pregnancy is like a stress test for the blood vessels. Failing it twice with preeclampsia is a warning that heart trouble is more likely later."),

dict(img='Wmenarche', cap='Relative risk of incident coronary heart disease by age at menarche in 1.2 million women',
stem="Investigators followed 1.2 million women (mean age 56 years) without known cardiovascular disease at baseline and recorded incident coronary heart disease by self-reported age at menarche. Results are shown, with the reference category at age 13.{FIG}Which of the following conclusions is best supported by these data?",
choices=["U-shaped: highest at ≤ 10 years, lowest at 13","Risk falls steadily with each later year of menarche","Risk is unrelated to age at menarche","Risk rises steadily with each later year of menarche","Risk rises only when menarche occurs at 17 years or older"], key=0,
exp="Canoy (Circulation 2015): the most common menarche age was 13 (25%), which is the lowest-risk reference. <b>Menarche at ≤ 10 → RR 1.27</b> (1.22–1.31). Risk falls toward 13, then <b>rises again with later menarche (≥ 17, RR 1.23)</b>. The relationship is <b>U-shaped</b>, so linear descriptions fail.<br><br><b>Educational objective:</b> Age at menarche has a U-shaped relationship with CHD: highest at ≤ 10 years, lowest at 13, rising again with late menarche.",
wrong={1:"Would be correct if the ≥ 17 category had the lowest risk.",
2:"Would be correct if all confidence intervals crossed 1.0. The extremes clearly don't.",
3:"Would be correct if the ≤ 10 category had the lowest risk.",
4:"Would be correct if the ≤ 10 and 11 categories sat at 1.0."},
eli5="Girls whose periods start very early or very late both have more heart disease later. Around 13 is the sweet spot."),

dict(img=None,
stem="A 34-year-old woman comes to the office because of a 10-year history of irritability, bloating, and breast tenderness during the 5 days before each menstrual period; the symptoms resolve within 2 days after menses begins and interfere with work each month. She takes no medications. Her blood pressure is 124/78 mm Hg. Physical examination shows no abnormalities.{FIG}According to a prospective cohort study discussed in the lecture, this patient is at greatest increased risk for which of the following?",
choices=["Atrial fibrillation","Heart failure with preserved ejection fraction","Hypertension","Peripheral arterial disease","Venous thromboembolism"], key=2,
exp="Cyclic luteal-phase physical and emotional symptoms → <b>premenstrual syndrome</b>. Bertone-Johnson (Am J Epidemiol 2015, Nurses' Health Study II): PMS → adjusted <b>HR 1.4 for hypertension</b>, and <b>HR 3.3 for hypertension before age 40</b>. The association was attenuated with high thiamine and riboflavin intake. At 34 she sits in the highest-risk window.<br><br><b>Educational objective:</b> Premenstrual syndrome is associated with later hypertension, most strongly before age 40.",
wrong={0:"Would be correct for a study of hyperthyroidism, alcohol or obesity, not PMS.",
1:"Would be correct for a cohort with longstanding hypertension and obesity, not PMS.",
3:"Would be correct for a smoker or diabetic cohort.",
4:"Would be correct for estrogen-containing contraception, pregnancy or thrombophilia, not PMS."},
eli5="Women with bad premenstrual symptoms were more likely to develop high blood pressure later, especially before 40."),

dict(img=None,
stem="A 29-year-old woman, gravida 1, para 0, at 35 weeks' gestation comes to the hospital because of a 1-day history of headache. Her blood pressure is 158/104 mm Hg on two readings 4 hours apart; at her first prenatal visit it was 112/70 mm Hg. Urine protein:creatinine ratio is 0.6. Ultrasonography shows fetal growth below the 10th percentile. She is delivered by induction of labor, and her blood pressure normalizes by 6 weeks postpartum.{FIG}Over the next 20 years, this patient is at greatest increased risk for which of the following?",
choices=["Breast cancer","Chronic hypertension","Hypothyroidism","Osteoporosis","Type 1 diabetes mellitus"], key=1,
exp="New hypertension after 20 weeks with proteinuria and fetal growth restriction → <b>preeclampsia</b>, a multisystem, placentally mediated disease (usually after 32 weeks, 2–8% of pregnancies). A history of preeclampsia <b>raises future cardiovascular risk</b> (Ahmed, JACC 2014). Board add-on: about <b>4-fold chronic hypertension</b> and about double CHD, stroke and heart failure. Normal postpartum BP is the decoy: the long-term risk persists. In the year after delivery, preeclampsia predicted heart failure (OR ~4.1), CHD and stroke (Savitz).<br><br><b>Educational objective:</b> Preeclampsia strongly predicts later chronic hypertension and cardiovascular disease.",
wrong={0:"Would be correct for nulliparity or late first pregnancy, not preeclampsia.",
2:"Would be correct for postpartum thyroiditis or autoimmune history.",
3:"Would be correct for long-term glucocorticoids, early menopause or low weight.",
4:"Would be correct only for autoimmune diabetes. Gestational diabetes predicts type 2."},
eli5="Preeclampsia is the blood vessels failing the pregnancy stress test, and high blood pressure often comes back for good later."),

dict(img=None,
stem="A 31-year-old woman is seen 6 weeks after an uncomplicated vaginal delivery. During pregnancy, a 3-hour glucose tolerance test at 26 weeks' gestation showed two abnormal values, and she required insulin until delivery. She is breastfeeding. Her BMI is 31 kg/m2. Her blood pressure is 118/74 mm Hg.{FIG}Based on the cohort data presented in the lecture, this patient is at greatest relative risk for which of the following new diagnoses?",
choices=["Coronary heart disease","Deep venous thrombosis","Heart failure","Stroke","Type 2 diabetes mellitus"], key=4,
exp="Gestational diabetes (abnormal glucose tolerance in pregnancy) → in Savitz's New York City cohort (1995–2004), <b>gestational diabetes predicted type 2 diabetes after delivery with an OR of ~22.6</b>, by far the largest association in the table. Preeclampsia, gestational hypertension and multiple gestation predicted the cardiovascular outcomes (heart failure, CHD, stroke). Pregnancy unmasks metabolic susceptibility → screen her for diabetes postpartum and periodically.<br><br><b>Educational objective:</b> Gestational diabetes strongly predicts later type 2 diabetes, a CVD risk factor.",
wrong={0:"Would be correct for preeclampsia (OR ~3.1) or multiple gestation (OR ~4.5).",
1:"Would be correct for preeclampsia (OR ~2.6), not gestational diabetes.",
2:"Would be correct for preeclampsia (OR ~4.1), gestational hypertension or multiple gestation.",
3:"Would be correct for preeclampsia (OR ~2.8)."},
eli5="Diabetes that shows up during pregnancy is a strong sign the body struggles with sugar, so ordinary type 2 diabetes often follows."),

dict(img=None,
stem="Investigators followed 11,518 postmenopausal women for a mean of 10.8 years and recorded myocardial infarction according to reproductive history. One participant, a 58-year-old woman with no other cardiovascular risk factors, reports four first-trimester miscarriages in her 20s and 30s and no stillbirths.{FIG}Which of the following adjusted hazard ratios best estimates this participant's risk of myocardial infarction compared with women without pregnancy loss?",
choices=["1.00","1.42","2.65","8.90"], key=3,
exp="Ann Fam Med 2014: compared with no pregnancy loss, <b>any miscarriage → HR 1.42</b>, <b>stillbirth → HR 2.65</b>, and <b>recurrent miscarriage (more than three) → HR 8.90</b>, the highest. With four miscarriages she belongs to the recurrent group. A meta-analysis also linked miscarriage (OR ~1.45) and recurrent miscarriage (OR ~2) to CHD.<br><br><b>Educational objective:</b> Recurrent miscarriage (> 3) carried the highest later MI risk (HR ~8.9), above stillbirth and single miscarriage.",
wrong={0:"Would be correct if pregnancy loss carried no excess risk (the reference group).",
1:"Would be correct for any history of miscarriage, not more than three.",
2:"Would be correct for a history of stillbirth."},
eli5="Losing many pregnancies seems to flag something about the blood vessels, and women with more than three losses had far more heart attacks later."),

dict(img='Wptd', cap='Cumulative hazard of cardiovascular hospitalization over ~22 years by study group',
stem="Investigators compared cumulative cardiovascular hospitalization over 22 years between women with and without a particular pregnancy outcome in their obstetric history. The exposed group is labeled \"PTD\" in the curves shown. Exposed women had a consistently higher hazard throughout follow-up.{FIG}Which pregnancy outcome defined the exposed group?",
choices=["Placental abruption","Polyhydramnios","Postterm delivery","Preterm delivery","Previous twin delivery"], key=3,
exp="<b>PTD = preterm delivery</b> (Kessous, Am J Obstet Gynecol 2013): women with a preterm delivery had a higher cumulative hazard of <b>cardiovascular hospitalization</b> over about 20 years. Preterm birth is on the lecture's list of pregnancy complications that predict later CVD. In the 50-year Cirillo cohort it carried an adjusted HR of 2.1 for CVD death, rising 4–7-fold when combined with hemorrhage, gestational hypertension or pre-existing hypertension.<br><br><b>Educational objective:</b> Preterm delivery predicts later cardiovascular hospitalization and death.",
wrong={0:"Would be correct if the label were abruption. It's a different exposure.",
1:"Would be correct if the label were amniotic-fluid excess, which the lecture didn't link to CVD.",
2:"Would be correct for delivery after 42 weeks, which the lecture didn't list.",
4:"Would be correct if the exposure were multiple gestation, which predicted early heart failure in another study."},
eli5="Women who had a baby too early were hospitalized for heart problems more often in the following decades."),

dict(img=None,
stem="A 66-year-old woman participates in a 50-year follow-up of a pregnancy cohort enrolled in the 1960s. Her prenatal records from two pregnancies document the following: irregular menses before conception, one postpartum hemorrhage treated with uterine massage, gestational hypertension, delivery of a small-for-gestational-age infant, and glucose detected on urine dipstick at 24 weeks' gestation. She is White.{FIG}Which of the following documented findings carried the highest adjusted risk of later cardiovascular death in this cohort?",
choices=["Gestational hypertension","Glycosuria","Irregular menses","Postpartum hemorrhage","Small-for-gestational-age delivery"], key=1,
exp="Cirillo and Cohn (Circulation 2015), adjusted HRs for CVD death: <b>glycosuria 4.2</b> (a new marker) · early-onset preeclampsia 3.6 · pre-existing hypertension 3.5 · preterm delivery 2.1 · late preeclampsia 2.0 · hemoglobin decline 1.7 · <b>SGA 1.6</b>. <b>Gestational hypertension</b> was associated only in Black women (HR 1.8; ~1.0 in non-Black women). <b>Hemorrhage and irregular menses/PCOS were not associated</b>. Obstetric records can identify high-risk women decades early.<br><br><b>Educational objective:</b> Glycosuria in pregnancy is a strong new marker of later cardiovascular death (HR ~4.2).",
wrong={0:"Would be correct if she were Black (HR ~1.8). In non-Black women it wasn't associated.",
2:"Would be correct for no association. Irregular menses/PCOS wasn't associated in this cohort.",
3:"Would be correct for no association. Hemorrhage alone wasn't associated (only in combination with preterm birth).",
4:"Would be correct if no stronger marker were present. SGA carried HR ~1.6."},
eli5="Sugar spilling into the urine during pregnancy turned out to be one of the strongest early clues to heart death decades later."),

dict(img=None,
stem="A 56-year-old woman comes to the office for cardiovascular risk assessment. She went through natural menopause 4 years ago. She does not smoke, her blood pressure is 126/80 mm Hg, and her lipid and glucose concentrations are within the reference ranges. She asks whether being postmenopausal changes her risk estimate.{FIG}According to ACC/AHA guidelines as presented in the lecture, how is postmenopausal status weighted as a risk factor?",
choices=["Equal to diabetes mellitus","Equal to male sex","Equal to smoking","Only if menopause was surgical","Not counted until age 65"], key=1,
exp="Slide 22: CVD is unusual in premenopausal women, and <b>postmenopausal status is recognized in ACC/AHA guidelines as a CVD risk factor with the same weight as male sex</b>. Early natural menopause (≤ 44) is associated with more CVD. Surgical vs natural menopause data are conflicting. Causality isn't proven.<br><br><b>Educational objective:</b> ACC/AHA guidelines weight postmenopausal status like male sex as a CVD risk factor.",
wrong={0:"Would be correct for neither factor. Diabetes is weighted more heavily as a separate factor.",
2:"Would be correct for neither factor. Smoking is a separate, stronger traditional factor.",
3:"Would be correct only if surgical menopause were clearly riskier. The data are conflicting, and natural menopause counts.",
4:"Would be correct for no guideline threshold. Postmenopausal status counts from menopause onward."},
eli5="Guidelines treat being past menopause like being male: it bumps the risk score by the same amount."),

dict(img=None,
stem="A 58-year-old woman comes to the office for cardiovascular risk assessment. Menarche was at age 13. She had two uncomplicated term pregnancies and breastfed both children. Natural menopause occurred at age 42. She stopped smoking 25 years ago after 3 years of light smoking. Her father had a myocardial infarction at age 76. Her blood pressure is 124/78 mm Hg, and fasting LDL-cholesterol concentration is 118 mg/dL.{FIG}Which of the following factors in her history most increases her cardiovascular risk?",
choices=["Age at menarche","Father's myocardial infarction at 76 years","Former light smoking","Menopause at 42 years","Two term pregnancies"], key=3,
exp="<b>Early natural menopause (≤ 44 years)</b> is associated with increased cardiovascular risk (slide 22), with earlier loss of estrogen's protective effects (eNOS vasodilation, angiogenesis, anti-fibrotic and anti-oxidant actions) and earlier onset of insulin-resistance features. The other items are real but weak or non-risk factors: menarche at 13 is the lowest-risk age, a paternal MI at 76 isn't premature (< 55 in male relatives), and light smoking that stopped 25 years ago adds little.<br><br><b>Educational objective:</b> Natural menopause at or before 44 is a female-specific cardiovascular risk enhancer.",
wrong={0:"Would be correct if menarche had occurred at 10 or younger.",
1:"Would be correct if her father's MI had occurred before age 55 (premature).",
2:"Would be correct for current or heavy recent smoking.",
4:"Would be correct only if the pregnancies had been complicated (preeclampsia, preterm delivery, gestational diabetes)."},
eli5="Losing estrogen early, at 42, takes away its protection for her arteries years sooner than usual."),

dict(img=None,
stem="Two large randomized trials of postmenopausal hormone therapy found no reduction, and possibly an increase, in coronary events. One trial enrolled women with established coronary heart disease, and the other was mostly primary prevention. In both, participants had a mean age in the mid-60s.{FIG}Which feature of the trial populations best explains the absence of cardiovascular benefit, according to the timing hypothesis?",
choices=["Inclusion of a progestin in some regimens","Starting > 10 years after menopause","Oral rather than transdermal route","Sample size too small to detect benefit","Use of conjugated equine estrogens"], key=1,
exp="WHI (mostly primary prevention) and HERS (secondary prevention) enrolled women <b>more than 10 years past menopause</b>. The <b>timing hypothesis</b>: MHT started <b>< 10 years after menopause and before age 60</b> appears to lower CHD by ~50% and all-cause mortality by ~30%, while in older women far from menopause it has no effect. KEEPS and ELITE tested this on subclinical atherosclerosis.<br><br><b>Educational objective:</b> WHI and HERS showed no CV benefit because participants started MHT more than 10 years after menopause.",
wrong={0:"Would be correct if estrogen-alone arms had shown benefit at the same ages. The lecture attributes the null result to timing.",
2:"Would be correct if transdermal regimens had shown benefit in the same older women. Route wasn't the lecture's explanation.",
3:"Would be correct for a small trial. WHI and HERS were very large.",
4:"Would be correct if other estrogens had helped the same population. The formulation wasn't the lecture's point."},
eli5="The big trials gave hormones to women long after menopause, when their arteries had already changed. Started early, hormones seem to help instead."),

dict(img=None,
stem="A 52-year-old woman comes to the office because of 8 months of hot flashes that wake her nightly. Her last menstrual period was 2 years ago. She walks 45 minutes daily, does not smoke, and has no history of venous thromboembolism, coronary disease, stroke, or breast cancer. Her blood pressure is 118/74 mm Hg, and BMI is 23 kg/m2. Her calculated 10-year ASCVD risk is 2.8%. She asks how hormone therapy would affect her heart.{FIG}Based on the evidence presented, what is the expected effect of starting menopausal hormone therapy now on her coronary heart disease risk?",
choices=["Decreased by about 50%","Decreased only after age 65","Increased about twofold","Increased about fourfold","No change"], key=0,
exp="She is in the <b>timing window</b> (< 10 years after menopause and < 60 years old) and the <b>green (acceptable) category</b>: recent menopause, normal weight and BP, active, 10-year risk < 5%. MHT started early appears to <b>reduce CHD by ~50% and all-cause mortality by ~30%</b>. KEEPS found no CIMT increase, ELITE found slower CIMT progression in early postmenopause, and Lau found MHT restored a premenopausal biomarker profile.<br><br><b>Educational objective:</b> In low-risk women within 10 years of menopause and under 60, MHT appears to lower CHD risk by about half.",
wrong={1:"Would be correct for no lecture finding. Late initiation shows no benefit.",
2:"Would be correct for neither scenario. A harm signal came from women > 10 years postmenopause (WHI/HERS).",
3:"Would be correct for no lecture finding.",
4:"Would be correct if she started MHT more than 10 years after menopause."},
eli5="She's young, healthy and recently through menopause, the group where hormone therapy looks heart-friendly."),

dict(img=None,
stem="A 55-year-old woman comes to the office because of severe hot flashes and night sweats that began 18 months ago, when her menses stopped. Two years ago she had an anterior myocardial infarction treated with a drug-eluting stent. Current medications are aspirin, clopidogrel, atorvastatin, metoprolol, and lisinopril. Her blood pressure is 122/76 mm Hg. She asks for hormone therapy.{FIG}Which of the following is the most appropriate management of her vasomotor symptoms?",
choices=["Avoid MHT; use nonhormonal therapy","Low-dose oral estradiol with a progestin","Oral conjugated estrogens alone","Transdermal estradiol with a progestin","Vaginal estradiol cream only"], key=0,
exp="Slide 32's traffic light: <b>known ASCVD, CAD, PAD, stroke/TIA or MI</b> (and VTE/PE, a clotting disorder, breast cancer, or 10-year risk ≥ 7.5%) → <b>red: avoid MHT</b>. That holds even inside the timing window. HERS (secondary prevention in women with CHD) showed no benefit and early harm. Board add-on: nonhormonal options for vasomotor symptoms (SSRIs/SNRIs, gabapentin, fezolinetant). Her recent menopause is the decoy, since the timing window applies only to women without ASCVD.<br><br><b>Educational objective:</b> Established ASCVD (prior MI or stent) is a red-light contraindication to menopausal hormone therapy.",
wrong={1:"Would be correct for a green-category woman with a uterus and no ASCVD.",
2:"Would be correct for a green-category woman without a uterus and no ASCVD.",
3:"Would be correct for a woman with a uterus in the green or yellow category. ASCVD makes her red regardless of route.",
4:"Would be correct for genitourinary symptoms only, not systemic vasomotor symptoms."},
eli5="After a heart attack, the clotting and blood-vessel risks of hormone pills outweigh the benefit, so her hot flashes need a non-hormone treatment."),

dict(img=None,
stem="In a randomized trial, healthy postmenopausal women were stratified by time since menopause into an early stratum (less than 6 years) and a late stratum (more than 10 years), then assigned to low-dose oral estradiol or placebo. The primary outcome was the rate of progression of carotid intima-media thickness.\n\nEarly stratum | Late stratum{FIG}Which of the following sets of results was observed with estradiol compared with placebo?",
choices=["Accelerated progression, no effect","No effect, no effect","No effect, slowed progression","Slowed progression, no effect","Slowed progression, slowed progression"], key=3,
exp="This is <b>ELITE</b>: low-dose oral estradiol <b>reduced CIMT progression in women < 6 years postmenopause</b> but <b>not in women > 10 years</b> postmenopause. <b>KEEPS</b> found no significant CIMT increase with MHT in women < 3 years postmenopause. Both support the <b>timing hypothesis</b>: the vascular benefit depends on starting early.<br><br><b>Educational objective:</b> ELITE showed estradiol slows CIMT progression only in early postmenopause, supporting the timing hypothesis.",
wrong={0:"Would be correct if estradiol harmed young vessels. The trial showed benefit early.",
1:"Would be correct for a fully null trial.",
2:"Would be correct only if benefit appeared late, the opposite of the timing hypothesis.",
4:"Would be correct if timing didn't matter."},
eli5="Estrogen kept the neck arteries from thickening only in women who started soon after menopause, not in women who started many years later."),

dict(img=None,
stem="A 48-year-old woman comes to the office because of 6 months of disabling hot flashes; her last menstrual period was 7 months ago. She smokes 10 cigarettes daily and has migraine with visual aura twice monthly. She has no history of coronary disease, stroke, venous thromboembolism, clotting disorder, or breast cancer. Her blood pressure is 124/80 mm Hg, and her calculated 10-year ASCVD risk is 4.0%.{FIG}According to the risk-assessment traffic light presented in the lecture, which category best describes her suitability for menopausal hormone therapy?",
choices=["Acceptable — green","Avoid — red","Caution — yellow","Indicated — for cardiovascular prevention"], key=2,
exp="Slide 32: <b>yellow (definite CVD risk / caution)</b> includes diabetes, <b>smoking</b>, uncontrolled HTN, obesity or a sedentary lifestyle, SLE/RA/<b>migraine with aura</b>, high TG or uncontrolled cholesterol, and 10-year risk 5–7.4%. Her low 10-year risk score is the decoy: it alone would be green (< 5%), but two yellow features override it. Red requires known ASCVD, VTE/PE, stroke/MI, a clotting disorder, breast cancer, or risk ≥ 7.5%. Address the smoking.<br><br><b>Educational objective:</b> Smoking and migraine with aura place a woman in the yellow (caution) MHT category despite a low risk score.",
wrong={0:"Would be correct if she didn't smoke and had no migraine with aura (risk < 5%).",
1:"Would be correct with known ASCVD, prior VTE, a clotting disorder, breast cancer, or risk ≥ 7.5%.",
3:"Would be correct for no lecture category. MHT isn't prescribed to prevent CVD."},
eli5="Her overall risk score is low, but smoking and migraines with aura are flashing yellow lights, so hormones would need extra caution."),

dict(img=None,
stem="A 50-year-old woman comes to the office because her periods have become irregular over the past 8 months. She has hypertension and takes no medications. She does not exercise. Her blood pressure is 148/92 mm Hg on three visits, and BMI is 31 kg/m2. Fasting LDL-cholesterol concentration is 168 mg/dL. She asks what she can do to protect her heart through the menopause transition.{FIG}Which of the following is the most appropriate initial approach?",
choices=["Control her blood pressure, lipids, weight, and inactivity","Defer risk-factor treatment until menopause is complete","Order coronary angiography","Start daily low-dose aspirin","Start estrogen therapy for cardioprotection"], key=0,
exp="Slide 27, \"So what can we do about all of this?\" → <b>control the traditional risk factors</b>: good BP control, good cholesterol numbers, a healthy diet, no smoking, losing excess weight, and exercising at least 30 minutes a day most days. MHT is an individualized decision for symptoms (timing window and traffic light), not a cardioprotective substitute. Board add-on (2019 guideline): aspirin for primary prevention is reserved for select high-risk patients.<br><br><b>Educational objective:</b> Cardiovascular prevention across the menopause transition starts with aggressive control of the traditional risk factors.",
wrong={1:"Would be correct for no lecture approach. Risk is already rising and current HTN and LDL need treatment.",
2:"Would be correct with anginal symptoms or a high-risk stress test, not for asymptomatic risk factors.",
3:"Would be correct only for select high-risk primary prevention without bleeding risk, not as the first step.",
4:"Would be correct for no lecture approach. MHT isn't a CV-prevention strategy."},
eli5="Before thinking about hormones, fix the basics: blood pressure, cholesterol, weight and daily exercise."),
]
