# Cardiovascular Health in Women (Qazi) — Version 2, 18 items (1 with an image). NBME house-style rewrite (2026-10-02).
Q = [
dict(img='Wprev', cap='Prevalence of cardiovascular disease among US adults by age group and sex, 2005–2008',
stem="A public health analyst reviews national prevalence data for cardiovascular disease (including coronary disease, heart failure, stroke, and hypertension) among adults 20 years and older, shown in the chart.{FIG}Which of the following conclusions is best supported by these data?",
choices=["Men and women have equal prevalence at every age","Women exceed men only at 80 years and older","Prevalence among women exceeds that among men at every age","Prevalence declines after 80 years of age","Prevalence among women exceeds that among men before 40 years of age"], key=1,
exp="Slide 8: men lead at <b>20–39 (14.2% vs 9.7%)</b> and <b>40–59 (39.3% vs 37.2%)</b>, the sexes are nearly equal at <b>60–79 (72.6% vs 71.9%)</b>, and <b>women exceed men at 80+ (86.7% vs 80.1%)</b>. Women's disease lags by about a decade, then catches up after menopause. That's consistent with age counting from 50 in women vs 40 in men.<br><br><b>Educational objective:</b> CVD prevalence in women trails men's until late life and exceeds men's at 80+.",
wrong={0:"Would be correct if the bars matched in every group. They differ by up to 6.6 points.",
2:"Would be correct if the blue bars were taller in all four groups.",
3:"Would be correct if the 80+ bars were shorter than the 60–79 bars.",
4:"Would be correct if women led at 20–39. Men do (14.2% vs 9.7%)."},
eli5="Men get heart disease earlier, but women catch up and pass them in old age."),

dict(img=None,
stem="A cardiology fellow prepares a lecture on secular trends in coronary heart disease in the United States and reviews mortality from acute myocardial infarction during the 1990s and 2000s. Cardiovascular disease remained the leading cause of death throughout this period.{FIG}Which of the following best describes the trend in acute myocardial infarction mortality over these two decades?",
choices=["Decreased by as much as 50%","Decreased by about 5%","Increased by about 50%","Increased only among women","Remained unchanged"], key=0,
exp="Slide 9, \"Some Good News\": although CVD remains the leading cause of death in most developed countries, <b>mortality from acute MI appears to have decreased by as much as 50% in the 1990s and 2000s</b> (reperfusion, medical therapy, prevention). The lecture still warns that under 65, a woman's MI mortality is almost twice a man's.<br><br><b>Educational objective:</b> Acute MI mortality fell by up to 50% in the 1990s–2000s, even though CVD remains the leading cause of death.",
wrong={1:"Would be correct if treatment advances had had only a marginal effect.",
2:"Would be correct for neither decade. Mortality fell.",
3:"Would be correct for neither sex. The slide reports an overall fall, though women's outcomes still lag.",
4:"Would be correct if there had been no therapeutic progress."},
eli5="Heart-attack care got much better, so about half as many people die of heart attacks as before."),

dict(img=None,
stem="A 63-year-old woman is brought to the emergency department 2 hours after the onset of fatigue, nausea, and shortness of breath while gardening. She has no chest pain. She has type 2 diabetes mellitus and hypertension. Her pulse is 104/min, and blood pressure is 146/88 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 95%. The lungs are clear, and the abdomen is soft and nontender. ECG shows ST-segment elevation of 3 mm in leads V2 through V4. Serum lipase activity is within the reference range.{FIG}Which of the following is the most likely diagnosis?",
choices=["Acute gastroenteritis","Acute myocardial infarction","Acute pancreatitis","Panic attack","Pulmonary embolism"], key=1,
exp="Anterior <b>ST-segment elevation</b> → acute anterior STEMI, despite the <b>absence of chest pain</b>. Board add-on, which reinforces the lecture's point that heart disease in women is under-recognized: women (and people with diabetes) more often present with <b>dyspnea, fatigue, nausea</b>, jaw or back pain, and are diagnosed later. Under 65, women's MI mortality is almost twice men's. Normal lipase and a soft abdomen remove the GI mimics. Emergent reperfusion follows.<br><br><b>Educational objective:</b> Myocardial infarction in women and diabetics often presents without chest pain. The ECG decides.",
wrong={0:"Would be correct with diarrhea, sick contacts and a normal ECG.",
2:"Would be correct with an elevated lipase and epigastric tenderness.",
3:"Would be correct with a normal ECG and situational triggers.",
4:"Would be correct with hypoxemia, pleuritic pain and a right-heart strain pattern rather than focal ST elevation."},
eli5="Her heart attack felt like tiredness, nausea and breathlessness instead of chest pain, which is common in women. The ECG gave it away."),

dict(img=None,
stem="A 33-year-old woman comes to the emergency department because of 1 hour of severe substernal chest pain that began 3 weeks after an uncomplicated vaginal delivery of her second child. She has no history of hypertension, diabetes, hyperlipidemia, or tobacco use, and her urine toxicology screening is negative. ECG shows ST-segment elevation in leads V1 through V4, and serum troponin concentration is increased. Coronary angiography shows a long, smooth, tapered narrowing of the mid left anterior descending artery without atherosclerotic plaque.{FIG}Which of the following is the most likely diagnosis?",
choices=["Atherosclerotic plaque rupture","Cocaine-induced coronary vasospasm","Coronary embolism from endocarditis","Spontaneous coronary artery dissection","Stress (Takotsubo) cardiomyopathy"], key=3,
exp="A peripartum MI in a young woman with no atherosclerotic risk factors and a <b>smooth, tapered coronary narrowing without plaque</b> (an intramural hematoma) → <b>spontaneous coronary artery dissection</b>. Board add-on, which rounds out the lecture's \"heart disease in women is a complex story\": SCAD causes a large share of MIs in young women, especially <b>peripartum</b> and with fibromuscular dysplasia, and is usually managed conservatively. The negative toxicology rules out the cocaine distractor.<br><br><b>Educational objective:</b> Peripartum MI with a smooth coronary narrowing and no plaque in a young woman is spontaneous coronary artery dissection.",
wrong={0:"Would be correct for an older patient with risk factors and an irregular, plaque-laden lesion.",
1:"Would be correct with a positive toxicology screen and a reversible focal spasm.",
2:"Would be correct with fever, a murmur and an abrupt cutoff of a distal vessel.",
4:"Would be correct with normal coronaries and apical ballooning in a postmenopausal woman after emotional stress."},
eli5="Shortly after childbirth, the wall of a heart artery split on its own and pinched it shut, even though her arteries were otherwise healthy."),

dict(img=None,
stem="A 66-year-old woman is brought to the emergency department 3 hours after the onset of chest pain and dyspnea that began after she learned that her husband had died suddenly. ECG shows ST-segment elevation in leads V2 through V5, and serum troponin concentration is mildly increased. Emergency coronary angiography shows no obstructive coronary lesions. Left ventriculography shows akinesis and ballooning of the apex with hyperkinesis of the basal segments. There is no pericardial effusion.{FIG}Which of the following is the most likely diagnosis?",
choices=["Acute pericarditis","Anterior STEMI from plaque rupture","Hypertrophic cardiomyopathy","Myocarditis","Spontaneous coronary artery dissection","Stress (Takotsubo) cardiomyopathy"], key=5,
exp="Emotional stress → catecholamine surge → transient <b>apical ballooning</b> with a hyperkinetic base, ST elevation and a modest troponin rise, with <b>no obstructive coronary disease</b> → <b>stress (Takotsubo) cardiomyopathy</b>. Board add-on: predominantly <b>postmenopausal women</b>, with recovery over weeks. It belongs with the lecture's theme that women's heart disease extends beyond classic plaque rupture (alongside SCAD and microvascular disease).<br><br><b>Educational objective:</b> Apical ballooning with normal coronaries after emotional stress in a postmenopausal woman is Takotsubo cardiomyopathy.",
wrong={0:"Would be correct with diffuse ST elevation, PR depression, a friction rub, and no regional ballooning.",
1:"Would be correct if angiography showed an occluded left anterior descending artery.",
2:"Would be correct with asymmetric septal thickening and an outflow murmur.",
3:"Would be correct after a viral prodrome with a diffuse or patchy wall-motion abnormality.",
4:"Would be correct if angiography showed a dissected, tapered coronary segment."},
eli5="Sudden grief flooded her heart with stress hormones and stunned the tip of the ventricle. It looks like a heart attack, but the arteries are clear."),

dict(img=None,
stem="In a 50-year follow-up of 14,062 women enrolled during pregnancy (Child Health and Development Studies), investigators examined combinations of pregnancy complications as predictors of cardiovascular death. A 36-year-old woman's obstetric history includes chronic hypertension before both pregnancies and preeclampsia in her first.{FIG}Compared with women without pregnancy complications, which of the following best estimates the relative risk of cardiovascular death conferred by this combination?",
choices=["About 1.7-fold","About 2-fold","About 3.5-fold","About 6-fold"], key=3,
exp="Cirillo and Cohn (Circulation 2015): <b>combinations identified the highest-risk women</b>. <b>Preeclampsia + pre-existing hypertension → nearly 6-fold</b> risk of CVD death, vs about 4-fold for pre-existing hypertension alone (adjusted HR 3.5). Preterm birth combined with hemorrhage, gestational hypertension or pre-existing hypertension → 4–7-fold. Single markers: glycosuria 4.2, early-onset preeclampsia 3.6, preterm delivery 2.1, late preeclampsia 2.0, hemoglobin decline 1.7.<br><br><b>Educational objective:</b> Combined pregnancy complications (preeclampsia plus chronic hypertension) carry multiplicative risk of later CVD death (~6-fold).",
wrong={0:"Would be correct for a hemoglobin decline alone.",
1:"Would be correct for late-onset preeclampsia alone.",
2:"Would be correct for pre-existing hypertension alone (adjusted HR 3.5)."},
eli5="Each pregnancy problem is a warning sign, and having two together is a much bigger warning than either one alone."),

dict(img=None,
stem="Investigators in a 50-year pregnancy cohort compared the adjusted hazard ratios for later cardiovascular death associated with preeclampsia according to its gestational timing.\n\nEarly-onset (by week 34) | Late-onset (after week 34){FIG}Which of the following pairs of adjusted hazard ratios was reported?",
choices=["1.0, 1.0","2.0, 3.6","3.6, 2.0","3.6, 3.6"], key=2,
exp="Cirillo and Cohn: <b>early-onset preeclampsia HR 3.6</b> vs <b>late-onset preeclampsia HR 2.0</b> for CVD death. Early-onset disease was rarer (0.3% vs 3% of women) but more ominous, consistent with more severe placental and vascular pathology. Late preeclampsia still counts: slide 14 lists \"preeclampsia after 34 weeks\" among risk-predicting complications.<br><br><b>Educational objective:</b> Early-onset preeclampsia predicts later CVD death more strongly (HR 3.6) than late-onset preeclampsia (HR 2.0).",
wrong={0:"Would be correct if preeclampsia carried no later cardiovascular risk.",
1:"Would be correct if late-onset disease were the more ominous form. The pairing is reversed.",
3:"Would be correct if timing didn't modify the risk."},
eli5="Preeclampsia that strikes earlier in pregnancy is a stronger sign of future heart trouble than preeclampsia close to the due date."),

dict(img=None,
stem="A 30-year-old woman who delivered twins 3 months ago comes to the office for a postpartum visit. She has dyspnea when climbing one flight of stairs and new ankle swelling. During pregnancy her blood pressure and glucose tolerance were normal. Her pulse is 98/min, and blood pressure is 118/72 mm Hg. Jugular venous pressure is elevated, and there is pitting edema to the mid-shin.{FIG}In the New York City cohort of women followed for 1 year after delivery, multiple gestation most strongly predicted which of the following?",
choices=["Deep venous thrombosis","Heart failure","Stroke or transient ischemic attack","Type 1 diabetes mellitus","Type 2 diabetes mellitus"], key=1,
exp="Savitz (Am J Epidemiol 2014): <b>multiple gestation</b> predicted <b>heart failure (OR ~4.5)</b> and coronary heart disease (OR ~4.5) in the year after delivery (it also predicted intracranial hemorrhage, with a wide confidence interval). Preeclampsia predicted heart failure (~4.1), stroke, CHD and DVT, and gestational diabetes predicted type 2 diabetes (~22.6). Her dyspnea, elevated JVP and edema fit that outcome (board add-on: consider peripartum cardiomyopathy).<br><br><b>Educational objective:</b> Multiple gestation predicted heart failure (and CHD) in the year after delivery.",
wrong={0:"Would be correct for preeclampsia (OR ~2.6) rather than multiple gestation.",
2:"Would be correct for preeclampsia (OR ~2.8). With multiple gestation the stroke association wasn't significant.",
3:"Would be correct for gestational diabetes (OR ~40, small numbers).",
4:"Would be correct for gestational diabetes (OR ~22.6)."},
eli5="Carrying twins puts a big extra load on the heart, and in the year after delivery those mothers had more heart failure."),

dict(img=None,
stem="A cardiologist presents two models of cardiovascular risk across a woman's life. In the first, risk is minimal or absent before menopause and is triggered at menopause. In the second, risk rises steadily from early adulthood, and menopause shifts it up or down without starting it.{FIG}Which of the following observations from the lecture most directly supports the second model?",
choices=["CVD is uncommon in premenopausal women","Pregnancy complications predict CVD early","Postmenopausal women have more hot flashes","Postmenopausal status is weighted like male sex","Estrogen therapy started late has no cardiac benefit"], key=1,
exp="Slide 23's <b>alternative paradigm</b>: cardiovascular risk is <b>increasing across the lifespan</b>, and menopause <b>modulates</b> it rather than switching it on. The strongest support is that <b>reproductive-era events</b> (preeclampsia, gestational diabetes, preterm birth, pregnancy loss, early menarche, PMS) already identify women at higher risk decades before menopause. Low premenopausal prevalence and the weight given to postmenopausal status fit the traditional model too.<br><br><b>Educational objective:</b> In the alternative paradigm, risk accumulates through life (revealed by reproductive history) and menopause modulates it.",
wrong={0:"Would be correct support for the traditional (switch-on) model.",
2:"Would be correct for neither model. Vasomotor symptoms aren't a risk marker in the lecture.",
3:"Would be correct support for menopause as a risk factor, compatible with either model.",
4:"Would be correct support for the timing hypothesis, not lifespan accumulation."},
eli5="Heart risk builds up through a woman's whole life. Pregnancy problems reveal it early, and menopause only turns the dial."),

dict(img=None,
stem="A student argues that because cardiovascular disease increases after menopause, estrogen loss itself must cause the increase. A reviewer points out that observational data cannot establish causation.{FIG}Which of the following observations most weakens the student's causal inference?",
choices=["Early natural menopause is associated with more CVD","Estradiol increases endothelial nitric oxide synthase activity","Estrogen replacement in WHI and HERS did not reduce CVD events","Postmenopausal biomarker profiles resemble those of men","Postmenopausal women have more visceral adiposity"], key=2,
exp="Slide 22: \"Observations do not prove that menopause itself is causal.\" Postmenopausal women who develop CVD carry <b>more traditional risk factors</b>, and the <b>lack of benefit from replacing estrogen in WHI (primary prevention) and HERS (secondary prevention)</b> is consistent with menopause not being directly responsible. If estrogen loss were the cause, replacing it should have helped (timing caveats aside). The other options are associations or mechanisms that support a causal role.<br><br><b>Educational objective:</b> The null results of estrogen replacement in WHI and HERS argue against menopause directly causing CVD.",
wrong={0:"Would be correct support FOR causation (a dose-like timing association).",
1:"Would be correct support FOR causation (a protective mechanism that is lost).",
3:"Would be correct support FOR causation (MHT restored the premenopausal profile).",
4:"Would be correct support FOR causation through an insulin-resistance pathway."},
eli5="If losing estrogen caused heart disease, giving it back should have helped. In the big trials it didn't."),

dict(img=None,
stem="An investigator studies endothelial cells from premenopausal women before and after exposure to physiologic concentrations of 17β-estradiol. The cells' production of a short-lived gaseous vasodilator increases, and arterial rings from the same donors relax more in response to acetylcholine.{FIG}Increased activity of which of the following enzymes most likely explains these findings?",
choices=["Cyclooxygenase-1","Endothelial nitric oxide synthase","Matrix metalloproteinase-9","NADPH oxidase","Phosphodiesterase-5"], key=1,
exp="Slide 24: estradiol's vascular protection includes <b>↑ vasodilation via eNOS</b> and ↑ angiogenesis via VEGF, plus ↓ fibrosis (↓ collagen deposition through MMP and angiotensin II), mitochondrial protection, and anti-oxidant effects. eNOS → nitric oxide → soluble guanylyl cyclase → cGMP → smooth-muscle relaxation. After menopause these effects decline: ↑ extracellular matrix, ↑ reactive oxygen species, impaired hypoxia–angiogenesis coupling.<br><br><b>Educational objective:</b> Estradiol enhances endothelial nitric oxide synthase activity, increasing NO-mediated vasodilation.",
wrong={0:"Would be correct for prostacyclin or thromboxane synthesis, not a gaseous vasodilator.",
2:"Would be correct for matrix remodeling (collagen breakdown), which isn't a vasodilator.",
3:"Would be correct for increased reactive oxygen species, which impair vasodilation (as after estrogen loss).",
4:"Would be correct if cGMP breakdown increased, which would reduce, not enhance, relaxation."},
eli5="Estrogen switches on the enzyme that makes nitric oxide, the gas that tells blood vessels to relax."),

dict(img=None,
stem="A 54-year-old woman comes to the office for follow-up. Her last menstrual period was 5 years ago. Her diet and activity have not changed. Over the past 5 years, her measurements have changed as listed below.\n\nWaist circumference | Insulin sensitivity | HDL-cholesterol | Blood pressure{FIG}Which of the following sets of changes is most consistent with the cardiometabolic effects of menopause described in the lecture?",
choices=["Decreased, increased, increased, decreased","Increased, decreased, decreased, increased","Increased, decreased, increased, decreased","Increased, increased, decreased, increased","Unchanged, unchanged, unchanged, increased"], key=1,
exp="Slide 26: menopause (with genes, programming, lifestyle and aging) → ↑ sympathetic activity, ↓ parasympathetic tone, and the core features of the <b>insulin-resistance syndrome</b>: <b>↑ visceral adiposity, ↓ insulin sensitivity (insulin resistance), dyslipidemia (board add-on: ↓ HDL, ↑ LDL and TG), ↑ blood pressure</b>. Downstream: inflammation, endothelial dysfunction, oxidative stress → ↑ CVD.<br><br><b>Educational objective:</b> Menopause promotes visceral adiposity, insulin resistance, lower HDL and higher blood pressure.",
wrong={0:"Would be correct for the effects of intensive exercise and weight loss, the opposite pattern.",
2:"Would be correct only if HDL rose and BP fell despite insulin resistance, an incoherent row.",
3:"Would be correct if insulin sensitivity improved despite central weight gain, an incoherent row.",
4:"Would be correct for isolated hypertension without metabolic change."},
eli5="After menopause, belly fat goes up, the body handles sugar worse, good cholesterol drops and blood pressure rises, all together."),

dict(img=None,
stem="Investigators measured 71 circulating cardiovascular biomarkers in premenopausal women, postmenopausal women not taking hormone therapy, postmenopausal women taking hormone therapy, and men of similar age.{FIG}Which of the following patterns best describes their findings?",
choices=["Like men's; therapy restored premenopausal profile","Postmenopausal profiles resembled premenopausal women's in all groups","Hormone therapy shifted postmenopausal profiles toward men's","Biomarker profiles were identical across all four groups","Only lipid biomarkers differed by menopausal status"], key=0,
exp="Slide 31 (Emily S. Lau's group): <b>postmenopausal profiles closely resembled those of men</b>, and <b>hormone therapy \"rescued\" the premenopausal biomarker phenotype</b>, so women taking MHT looked more like premenopausal women. This supports the biological plausibility of the timing hypothesis.<br><br><b>Educational objective:</b> Postmenopausal cardiovascular biomarker profiles resemble men's, and MHT restores a premenopausal-like profile.",
wrong={1:"Would be correct if menopause didn't change the biomarker profile.",
2:"Would be correct if MHT worsened the profile. It moved it the other way.",
3:"Would be correct for a fully null study.",
4:"Would be correct if the panel had been lipid-only. It spanned 71 markers."},
eli5="After menopause, women's blood markers of heart risk start to look like men's, and hormone therapy pushed them back toward the younger-woman pattern."),

dict(img=None,
stem="A 51-year-old woman asks how long she can expect to live after menopause. With current life expectancy in the United States, the lecture emphasizes the large share of a woman's life spent in the postmenopausal state when discussing the relevance of hormone therapy.{FIG}Up to approximately what proportion of their lives will most women spend in menopause?",
choices=["10%","20%","40%","60%","80%"], key=2,
exp="Slide 28: \"With rising life expectancy, <b>most women will spend up to 40% of their lives in menopause</b>.\" Menopause around 51 with a life expectancy in the 80s gives roughly 30+ postmenopausal years. That's why cardiometabolic change across the transition, and the hormone-therapy question, is one of the lecture's three objectives.<br><br><b>Educational objective:</b> Women may spend up to 40% of their lives postmenopausal.",
wrong={0:"Would be correct only with a life expectancy of about 57 years.",
1:"Would be correct with a life expectancy of about 64 years.",
3:"Would be correct with a life expectancy of about 128 years.",
4:"Would be correct for no plausible life expectancy."},
eli5="If menopause comes around 50 and women live into their 80s, up to about 40% of life is spent after menopause."),

dict(img=None,
stem="A 57-year-old woman comes to the office because of 1 year of hot flashes that disrupt her sleep; her last menstrual period was 3 years ago. She does not exercise and has no history of coronary disease, stroke, venous thromboembolism, clotting disorder, or breast cancer. She does not smoke. Her blood pressure is 128/82 mm Hg, and BMI is 34 kg/m2. Her calculated 10-year ASCVD risk is 6.1%.{FIG}According to the risk-assessment traffic light presented in the lecture, which category best describes her suitability for menopausal hormone therapy?",
choices=["Acceptable — green","Avoid — red","Caution — yellow","Indicated — for cardiovascular prevention"], key=2,
exp="Slide 32: <b>yellow (definite CVD risk / caution)</b> includes <b>obesity, a sedentary lifestyle or limited mobility</b>, diabetes, smoking, uncontrolled HTN, SLE/RA/migraine with aura, high TG or uncontrolled cholesterol, and a <b>10-year ASCVD risk of 5–7.4%</b>. She meets three yellow criteria and no red ones (known ASCVD, VTE/PE, stroke/TIA or MI, clotting disorder, breast cancer, or risk ≥ 7.5%). Her timing (3 years, < 60) is the decoy: it's favorable, but the risk profile sets the color.<br><br><b>Educational objective:</b> Obesity, inactivity and a 10-year ASCVD risk of 5–7.4% place a woman in the yellow (caution) MHT category.",
wrong={0:"Would be correct for a normal-weight, active woman with risk < 5%.",
1:"Would be correct with known ASCVD, VTE, a clotting disorder, breast cancer, or risk ≥ 7.5%.",
3:"Would be correct for no lecture category. MHT isn't prescribed to prevent CVD."},
eli5="She doesn't have heart disease, but her weight, inactivity and moderate risk score put her in the be-careful zone."),

dict(img=None,
stem="A 49-year-old woman comes to the office because of 9 months of frequent hot flashes; her last menstrual period was 11 months ago. Five years ago she had a pulmonary embolism after a long flight and completed 6 months of anticoagulation. Her mother had breast cancer at age 71. She walks daily and does not smoke. Her blood pressure is 116/72 mm Hg, and BMI is 26 kg/m2. Her calculated 10-year ASCVD risk is 2.0%.{FIG}Which of the following factors in her history most strongly determines that she should avoid menopausal hormone therapy?",
choices=["Age of 49 years","BMI of 26 kg/m2","Mother's breast cancer at age 71","Prior pulmonary embolism","Ten-year ASCVD risk of 2.0%"], key=3,
exp="Slide 32's <b>red (avoid MHT)</b> list: known ASCVD/CAD/PAD, <b>known venous thrombosis or pulmonary embolism</b>, stroke/TIA or MI, a known clotting disorder, <b>known (personal) breast cancer</b>, and 10-year risk ≥ 7.5%. Estrogen raises clotting risk (board add-on: WHI showed more VTE), so a prior PE is decisive even with a 2% ASCVD risk. Her mother's cancer is the decoy: a family history isn't the same as personal breast cancer. Her age and BMI are favorable.<br><br><b>Educational objective:</b> A prior VTE/PE is a red-light contraindication to MHT regardless of ASCVD risk.",
wrong={0:"Would be correct for no category. Her age is inside the favorable timing window.",
1:"Would be correct only for obesity (yellow), not a BMI of 26.",
2:"Would be correct if SHE had a personal history of breast cancer.",
4:"Would be correct only if the risk were ≥ 7.5% (red) or 5–7.4% (yellow)."},
eli5="Estrogen makes blood clot more easily, and she's already had a dangerous clot in her lungs, so hormones are off the table."),

dict(img=None,
stem="In a randomized trial, healthy women within 3 years of menopause were assigned to menopausal hormone therapy or placebo, and carotid intima-media thickness was measured serially over 4 years.{FIG}Which of the following best describes the effect of hormone therapy on carotid intima-media thickness in this trial?",
choices=["Marked acceleration of thickening","No significant increase","Reversal to premenopausal thickness","Thickening only in women older than 60","Thickening only with transdermal therapy"], key=1,
exp="This is <b>KEEPS</b> (slide 30): <b>no significant increase in CIMT</b> with MHT in women less than 3 years postmenopause, so no signal of harm to subclinical atherosclerosis when started early. <b>ELITE</b> showed low-dose oral estradiol <b>slowed</b> CIMT progression in women < 6 years postmenopause but not > 10 years. Together they test and support the <b>timing hypothesis</b>.<br><br><b>Educational objective:</b> KEEPS showed MHT started within 3 years of menopause did not increase carotid intima-media thickness.",
wrong={0:"Would be correct if early MHT harmed the arteries, the opposite of the trial result.",
2:"Would be correct for no trial in the lecture. CIMT isn't reset.",
3:"Would be correct for no KEEPS finding. Participants were within 3 years of menopause.",
4:"Would be correct for no KEEPS finding. The route didn't produce thickening."},
eli5="When hormones were started soon after menopause, the neck arteries didn't thicken, so there was no sign of harm."),

dict(img=None,
stem="A 38-year-old woman comes to the office to establish care. Menarche occurred at age 10. She had gestational diabetes during her first pregnancy and a stillbirth at 32 weeks' gestation in her second. She does not smoke. Her blood pressure is 122/78 mm Hg, BMI is 27 kg/m2, and fasting glucose and lipid concentrations are within the reference ranges.{FIG}Which of the following is the most appropriate next step in management?",
choices=["Begin hormone therapy to offset the risk","Defer cardiovascular assessment until menopause","Recheck cardiovascular risk only if symptoms develop","Start daily low-dose aspirin","Screen earlier as a high-risk woman"], key=4,
exp="She has several <b>female-specific risk enhancers</b>: <b>menarche at ≤ 10 years (RR 1.27 for CHD)</b>, <b>gestational diabetes</b> (strongly predicts type 2 diabetes), and <b>stillbirth (HR 2.65 for later MI)</b>. The lecture concludes these factors \"have only recently been considered.\" They should prompt <b>earlier and more frequent screening</b> (glucose, lipids, BP) and aggressive control of traditional risk factors, even with normal numbers today, which is the decoy.<br><br><b>Educational objective:</b> Reproductive history (early menarche, gestational diabetes, pregnancy loss) should prompt earlier cardiovascular screening and prevention.",
wrong={0:"Would be correct for no lecture indication. MHT isn't a premenopausal prevention tool.",
1:"Would be correct only if reproductive history carried no risk. It does.",
2:"Would be correct for no evidence-based approach. Sudden death or MI can be the first symptom.",
3:"Would be correct only for select high-risk primary prevention without bleeding risk."},
eli5="Her early periods, pregnancy diabetes and stillbirth are early warning lights, so she should be checked for heart risks sooner and more often."),
]
