H='Segal/Scully — HF case'; P='Segal — PAD case'
FIGS={
 'hfpef-ecg':('as2-hfpef-ecg.jpg','Case 1 ECG: sinus ~60/min, left axis deviation, borderline first-degree AV block, broad QRS with high voltage (LVH) and no precordial transition',H,'10',False),
 'psax-lvh':('as2-psax-lvh.jpg','Parasternal short-axis echo: thick LV walls and a small cavity (concentric LV hypertrophy)',H,'11',True),
 'concentric-eccentric':('as2-concentric-eccentric.jpg','Concentric LVH (↑ wall thickness, normal cavity, ↑ relative wall thickness) = pressure overload vs eccentric LVH (normal wall, ↑ cavity, ↓ RWT) = volume overload',H,'12',True),
 'h2fpef':('as2-h2fpef.jpg','H₂FPEF score: Heavy (BMI > 30) 2 · Hypertensive (≥ 2 drugs) 1 · AF 3 · Pulmonary HTN (PASP > 35) 1 · Elder (> 60) 1 · Filling pressure (E/e′ > 9) 1 → probability of HFpEF',H,'13 · Reddy, Circulation 2018',True),
 'hfref-vs-hfpef':('as2-hfref-vs-hfpef.jpg','HFrEF vs HFpEF: younger male post-MI with eccentric hypertrophy and CV death vs older female with AF, CKD, diabetes, HTN, concentric remodeling and non-CV death',H,'17',True),
 'nyha':('as2-nyha.jpg','NYHA functional classes I–IV: no limitation → slight → marked (comfortable only at rest) → symptoms at rest',H,'18 · medcomic.com',True),
 'diuretic-sites':('as2-diuretic-sites.jpg','Where diuretics act: acetazolamide (PCT), SGLT2 inhibitors (PCT), loop diuretics (thick ascending limb), thiazides (DCT), spironolactone (collecting duct MR), tolvaptan (V2)',H,'21 · Siddiqi, JACC HF 2025',False),
 'sglt2i-mechanism':('as2-sglt2i-mechanism.jpg','SGLT2 inhibitors: natriuresis and glucosuria → tubuloglomerular feedback, lower intraglomerular pressure, BP and volume → renal and cardiovascular protection',H,'22 · Zelniker, JACC 2020',True),
 'mra-mechanisms':('as2-mra-mechanisms.jpg','MRA / aldosterone-synthase-inhibitor effects: anti-fibrotic, anti-inflammatory, sympathetic blockade, natriuresis, BP lowering, ↓ K⁺ excretion',H,'23',True),
 'alcohol-cm':('as2-alcohol-cm.jpg','Alcoholic dilated cardiomyopathy: indirect (↑ SNS, ↑ RAAS, endothelial dysfunction → HTN) and direct (oxidative stress, fibrosis, excitation–contraction coupling) effects',H,'27',True),
 'cocaine-bb':('as2-cocaine-bb.jpg','Cocaine blocks catecholamine reuptake; a β₁-selective blocker leaves α-receptors unopposed (vasoconstriction ↑ SVR), whereas carvedilol/labetalol block both',H,'27',True),
 'cxr-edema':('as2-cxr-edema.jpg','Case 2 chest radiograph: pulmonary vascular congestion with interstitial edema and septal (Kerley B) lines',H,'29',True),
 'cxr-signs':('as2-cxr-signs.jpg','Radiographic signs of heart failure: redistribution, wide vascular pedicle and azygos, pulmonary edema, Kerley lines, cardiomegaly, pleural fluid',H,'29',True),
 'forrester':('as2-forrester.jpg','Hemodynamic profiles in acute HF: congestion (dry/wet) × perfusion (warm/cold), with the bedside signs of each axis',H,'31 · US Pharmacist',True),
 'neurohormonal':('as2-neurohormonal.jpg','Systolic HF → ↓ CO → SNS and RAAS activation → vasoconstriction, Na⁺/water retention, ↑ filling pressure and cardiac remodeling (the targets of GDMT)',H,'32 · Tulane pharmwiki',True),
 'loop-diuretic':('as2-loop-diuretic.jpg','Loop diuretics block NKCC2 in the thick ascending limb, dissipating the lumen-positive potential that drives Mg²⁺ and Ca²⁺ reabsorption',H,'33',True),
 'pillars-remodeling':('as2-pillars-remodeling.jpg','How each GDMT pillar (ACEi/ARB/ARNI, β-blocker, SGLT2i, MRA) drives reverse remodeling: ↓ LV volume and mass, ↑ LVEF, ↓ filling pressure',H,'34',True),
 'pillars-hr':('as2-pillars-hr.jpg','Quadruple therapy on a diuretic foundation; CV death or HF hospitalization falls from HR 0.84 (ACEi + BB) to 0.36 (ARNI + BB + MRA + SGLT2i)',H,'35',True),
 'shock-types':('as2-shock-types.jpg','Approach to shock: tissue hypoperfusion → cardiac output/SvO₂ and CVP → distributive, hypovolemic, cardiogenic or obstructive, confirmed by echo',H,'36 · NEJM',True),
 'starling-curves':('as2-starling-curves.jpg','Frank–Starling curves (stroke volume vs LVEDP): lower afterload and more inotropy shift the curve up and left; higher afterload and less inotropy shift it down and right',H,'37',True),
 'adhf-cycle':('as2-adhf-cycle.jpg','The ADHF vicious cycle: ↓ CO → sympathetic and RAAS responses → vasoconstriction (↑ afterload) and Na⁺/water retention (↑ preload) → more cardiac strain',H,'37',True),
 'hfpef-algorithm':('as2-hfpef-algorithm.jpg','HFpEF algorithm: confirm HF, decongest, exclude masqueraders; exercise and SGLT2i for all, ARNI/MRA in selected patients with EF 50–60%',H,'39 · Desai, JACC HF 2023',True),
 'hfref-rapid-gdmt':('as2-hfref-rapid-gdmt.jpg','Rapid, intensive GDMT for HFrEF: start all four pillars (low doses) quickly, ideally in hospital, then titrate within 4–6 weeks',H,'39 · Greene, Circulation 2024',True),
 'leg-arteries':('as2-leg-arteries.jpg','Arteries of the leg: common/internal/external iliac → common femoral → superficial femoral and profunda → popliteal → anterior tibial, tibioperoneal trunk → posterior tibial and peroneal',P,'1',True),
 'claudication-ddx':('as2-claudication-ddx.jpg','True claudication vs pseudoclaudication: spinal stenosis, arthritis, venous congestion, compartment syndrome',P,'6 · White, NEJM 2007',False),
 'pad-prevalence':('as2-pad-prevalence.jpg','PAD prevalence rises steeply with age in both sexes, to ~20–27% at ≥ 80',P,'9 · CDC',True),
 'pad-odds-ratios':('as2-pad-odds-ratios.jpg','Odds ratios for PAD by risk factor: current smoking, diabetes, hypertension and prior CVD carry the largest risks',P,'10 · Criqui & Aboyans, Circ Res 2015',True),
 'pad-subsets':('as2-pad-subsets.jpg','Clinical subsets of PAD: asymptomatic, chronic symptomatic (claudication), chronic limb-threatening ischemia, acute limb ischemia',P,'16 · Gornik, Circulation 2024',True),
 'dependent-rubor':('as2-dependent-rubor.jpg','Dependent rubor in advanced ischemia: the dependent foot (right) is dusky red, the other pale',P,'17 · NEJM 2007',True),
 'buerger-test':('as2-buerger-test.jpg','Buerger test: pallor and venous guttering with the foot elevated; rubor when dependent',P,'17',True),
 'pad-symptom-sites':('as2-pad-symptom-sites.jpg','Where the blockage is vs where it hurts: aortoiliac → buttock, hip, thigh; femoral → thigh, calf; popliteal → calf; tibial → calf, ankle, foot',P,'18 · Harvard Health',True),
 'leriche-ct':('as2-leriche-ct.jpg','Leriche syndrome on CT angiography: complete occlusion of the infrarenal aorta (arrow) with collaterals reconstituting both external iliac arteries',P,'18',True),
 'abi-method':('as2-abi-method.jpg','Ankle–brachial index: highest ankle pressure (DP or PT) ÷ highest brachial pressure; example 92/164 = 0.56 (moderate obstruction)',P,'20 · NEJM',True),
 'abi-cutoffs':('as2-abi-cutoffs.jpg','2024 ABI cut-points: ≤ 0.90 diagnostic · 0.91–0.99 borderline (exercise ABI) · 1.00–1.40 normal · > 1.40 non-compressible (use toe–brachial index)',P,'20 · CardioNerds',False),
 'pvr-doppler':('as2-pvr-doppler.jpg','Segmental pressures and Doppler waveforms: normal triphasic on the left; reduced biphasic to monophasic on the right with ABI ~0.56',P,'21 · NEJM',True),
 'pad-diagnostic-algorithm':('as2-pad-diagnostic-algorithm.jpg','2024 diagnostic algorithm for suspected PAD and CLTI: resting ABI ± exercise ABI or TBI, then imaging only if revascularization is considered',P,'24 · Gornik, Circulation 2024',True),
 'pad-antithrombotic':('as2-pad-antithrombotic.jpg','Antithrombotic therapy in symptomatic PAD: SAPT (clopidogrel or aspirin) or low-dose aspirin + rivaroxaban 2.5 mg BID; regimens after revascularization',P,'25 · Gornik, Circulation 2024',False),
 'pad-medical-therapy':('as2-pad-medical-therapy.jpg','Medical therapy of PAD: structured exercise, leg-symptom drugs, foot care, antithrombotics, lipid lowering, BP and diabetes control, smoking cessation',P,'25 · AHA/ACC 2024',True),
 'exercise-mechanisms':('as2-exercise-mechanisms.jpg','Why PAD limits function (↓ O₂ delivery and use, ↑ inflammation) and how exercise reverses it (angiogenesis, ↑ NO-mediated vasodilation, better mitochondrial metabolism)',P,'30 · Gornik, Circulation 2024',True),
 'set-table':('as2-set-table.jpg','Structured exercise programs: supervised (treadmill, 30–45 min ≥ 3×/week for ≥ 12 weeks, Medicare-covered) and community-based',P,'30 · Gornik, Circulation 2024',False),
 'smoking-outcomes':('as2-smoking-outcomes.jpg','PAD patients who quit smoking: better survival, fewer major amputations, and better amputation-free survival over 5 years',P,'31 · Armstrong, J Vasc Surg 2014',True),
 'smoking-plan':('as2-smoking-plan.jpg','Smoking-cessation plan: counseling + pharmacotherapy (nicotine replacement, bupropion, varenicline); e-cigarettes uncertain',P,'31',True),
 'polyvascular':('as2-polyvascular.jpg','Polyvascular disease: survival falls and 1-year CV death, MI, stroke or hospitalization rises (5.3% → 26.3%) with each additional affected vascular bed',P,'33 · REACH; van Kuijk 2010',False)}
